### ISSUE TITLE
Release to individual testers and multiple distribution groups

### ISSUE THREAD

**Issue by botatoes** [Microsoft/appcenter#10]
Right now on App Center, you can distribute to one distribution group at a time. You would need to re-release to distribute to multiple groups. You also cannot distribute to individual users. You would need to create a single user group to distribute to individual users. This feature will allow users to distribute to multiple distribution groups at once and distribute to individual testers in the portal UI and in the API.

**Comment by rolfsormo** [comment]
Hey guys,

Any status on this? Obviously March has passed already, and the iteration is closed, but no new iteration has been assigned.

**Comment by botatoes** [comment]
Hi @rolfsormo this was released in March.

**Comment by LuckyGolfer** [comment]
While the UI for this change apparently allows selecting multiple Distribution groups (imported from HockeyApp), after saving the distribution, only a single distribution group is saved, so this item may not be complete?
