### ISSUE TITLE
strongly-named

### ISSUE THREAD

**Issue by PatrickV82** [microsoft/appcenter#1000]
Will the Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes nuget packages be strongly-named in the future?

This is for a WinForm application

**Comment by derpixeldan** [comment]
@PatrickV82 let me loop in @hamswan who can answer this question. Thank you.

On another note ONETHOUSAND!
![nod](https://user-images.githubusercontent.com/3369400/64592082-807c2a00-d3ab-11e9-8f54-412fa6fdf433.gif)

**Comment by hamswan** [comment]
We will discuss this for the future

**Comment by PatrickV82** [comment]
> We will discuss this in our team.
Any news?

**Comment by WaivedAnswer** [comment]
@PatrickV82 this request seems to have received more traction

**Comment by PatrickV82** [comment]
Any progress ?

**Comment by MatkovIvan** [comment]
Hi there. Let's track this feature request in #1321, I know this one was opened a bit early, but anyway.

Duplicate of #1321
