### ISSUE TITLE
Support distributing multiple apps per AppCenter project

### ISSUE THREAD

**Issue by dp-1a** [microsoft/appcenter#1001]
**Describe the solution you'd like**

I would like to distribute multiple apps per AppCenter project and not just one app in multiple versions.

**Describe alternatives you've considered**

Currently you need to create a standalone project for every "App" you want to distribute.

**Additional context**

We are currently creating a B2B iOS application for which we want to distribute 3 different flavours per release, per customer. E.g. a development version, a pre-release and a release version per customer which might contain different features.

Our structure looks something like this.

* App
* * Customer A
* * *  DEV release
* * * PRE-PRODUCTION release
* * * PROD release

Therefore, in order to distribute 3 different versions to a customer we currently would need to create 3 different projects which quickly becomes hard to manage for multiple customers.

**Comment by victorkvarghese** [comment]
@dp-1a  Did you find any solutions?
