### ISSUE TITLE
Appium update from 1.11.0 to any version with appium-desktop version available

### ISSUE THREAD

**Issue by Zhappa** [microsoft/appcenter#1002]
**Describe the solution you'd like**
Update appium to ANY version with desktop version available.
https://github.com/appium/appium-desktop

**Describe alternatives you've considered**
As an alternative: provide a fixed appium-desktop v1.11.0 for all platrforms

**Additional context**
Appium desktop 1.11.0 binaries removed due to some major bug
Reference: https://github.com/appium/appium-desktop/releases/tag/v1.11.0
This means you can't just take a desktop version and use it, you have to get appium elsewhere.
Usability is seriously damaged by this situation.
P.S. 
in my case, instructions of "how to compile webDriver for appium on MAC" did not work and took a lot of time.

**Comment by elamalani** [comment]
@zhappa Thanks for adding this feature request. We will review it with the team and consider it for future prioritization.

**Comment by Oddj0b** [comment]
@zhappa To be sure I understand you correctly, version 1.11 which App Center Test is running is not compatible with Appium Desktop? And you're looking for a workaround?

**Comment by Zhappa** [comment]
> @Zhappa To be sure I understand you correctly, version 1.11 which App Center Test is running is not compatible with Appium Desktop? And you're looking for a workaround?

Hi! No, the problem is: there is no binary (exe, dmg) of appium-desktop v1.11.0 available.
I can't just take a well compiled binary for my platform (PC, MAC) and use it. I have to download appium from, lets say, npm package manager.
This is not a big deal for windows, but for mac it generates a ton of unnecessary movements (from installing brew to recompiling the webDriver) and not guarantee the success.

In the other hand Appium-desktop binaries do not expect any configuration, you just download it and run. Everything is work out of the box.

Example:
https://github.com/appium/appium-desktop/releases/tag/v1.13.0 - binaries is here.
https://github.com/appium/appium-desktop/releases/tag/v1.11.0 - no binaries


To prevent your next question like "why don't use appium-desktop v1.13.0?" - they works differently. I spend a lot of time trying to understand why are my tests keep failing on appcenter, but works locally previously. It was because of the difference in versions on Appcenter vs local env.

So i definitely need Appium with version == Appcenter's Appium version. Wich is not the case for appium-desktop 1.11.0, since its not available:(

**Comment by Oddj0b** [comment]
@Zhappa Thank you for the explanation, I'm hoping to get an Appium update into our backlog in the near future. Sorry for the inconvenience.

**Comment by King-of-Spades** [comment]
related to #1203 & #1038 which are also requests for Appium upgrades.

**Comment by Oddj0b** [comment]
We're internally testing the latest Appium upgrade and would like your help. If you want to test Appium in version 1.16 in App Center Test, all you have to do is add a `--test-parameter pipeline=appium-v1.16.0` switch when submitting your test. If you have problems, please don't hold back and let our support know.

**Comment by Zhappa** [comment]
> We're internally testing the latest Appium upgrade and would like your help. If you want to test Appium in version 1.16 in App Center Test, all you have to do is add a `--test-parameter pipeline=appium-v1.16.0` switch when submitting your test. If you have problems, please don't hold back and let our support know.

This is a great news!!
Awesome! I will bring my results asap (probably in monday).
Thank you for info!!

**Comment by Zhappa** [comment]
This is works! https://appcenter.ms/orgs/Wontok/apps/Android_3440_WontokGa_Release/test/runs/735b8c2c-2d21-4c2e-b27a-6c95922e1d8e/2-0-10/9e5a2f9b-8577-4ab0-a8a7-5a1e709704c8
I can now contunue with my Android Q devices, thank you!

I will close this ticket when 1.16.0 will be fully on board.

**Comment by StasGrishaev** [comment]
> We're internally testing the latest Appium upgrade and would like your help. If you want to test Appium in version 1.16 in App Center Test, all you have to do is add a `--test-parameter pipeline=appium-v1.16.0` switch when submitting your test. If you have problems, please don't hold back and let our support know.

@Oddj0b it will be nice if you add this information to https://docs.microsoft.com/ru-ru/appcenter/test-cloud/preparing-for-upload/appium
i spended some time to finding proper solution for this :)

**Comment by Oddj0b** [comment]
Appium 1.16 is the default version for all Appium Test runs and the `--test-parameter pipeline=appium-v1.16.0` is no longer required.
