### ISSUE TITLE
Cannot see available app builds when clicking email link

### ISSUE THREAD

**Issue by marudy** [microsoft/appcenter#1006]
As soon as a build is completed successfully, an email is sent to all the collaboration team members. Recently and when clicking to the install button over the email we get redirected to appcenter's following screen instead of the list with the available builds.

![File (4)](https://user-images.githubusercontent.com/16783589/64632443-bd730b80-d401-11e9-8c48-2dd37e105019.jpg)

Please let me know what more info you require, thanks

**Comment by elamalani** [comment]
@marudy Thanks for reporting it. Our team will look into this issue.

**Comment by botatoes** [comment]
HI @Marudy, can you please open a support ticket on appcenter.ms in intercom so we can take a deeper look into your app?

**Comment by marudy** [comment]
Hey @botatoes thanks for the reply. Can you show me to the direction of intercom? I mean some link to follow? thanks

**Comment by usmanmohamnad** [comment]
> As soon as a build is completed successfully, an email is sent to all the collaboration team members. Recently and when clicking to the install button over the email we get redirected to appcenter's following screen instead of the list with the available builds.
> 
> ![File (4)](https://user-images.githubusercontent.com/16783589/64632443-bd730b80-d401-11e9-8c48-2dd37e105019.jpg)
> 
> Please let me know what more info you require, thanks
