### ISSUE TITLE
WPF distribution and UWP NUnit tests

### ISSUE THREAD

**Issue by richard-motion** [microsoft/appcenter#1007]
Hi,

I'm using app center for the first time as I've used Jenkins in the past. I've created a Xamarin forms app with the normal UWP, Android and iOS flavours. The first thing I want to do is run NUnit as a post build process. This was easy to do in Android but I'm struggling to get this to work as a powershell script. I have on test project, let's call it xamarinUnit test that's written in NUnit3. 

The second thing is a query, can you build WPF on app center or do you need to build this in azure DevOps? Ideally it would pull from bitbucket and build the WPF app from there.

Thanks for any help.

**Comment by elamalani** [comment]
@richard-motion Can you elaborate on your first question a bit more? What do you want to do?

We don't support Build service for WPF apps. You can use Azure Pipelines for building WPF apps.

**Comment by richard-motion** [comment]
@elamalani Hi, if you ignore the WPF part, I just want to run nunit after a UWP application is built in app center. I've managed to write a bash script to do this for Android and iOS, but I can't seem to get the same result for UWP.  
I wasn't aware until yesterday morning that we would need to use Azure Devops to build WPF after reading an article. Is it the case the UWP and WPF need to be built in Azure and then pushed to App Center?

Thanks so much for the response too. It's appreciated.

**Comment by winnieli1** [comment]
Hi Richard - I'm not sure about your build question but I passed this along to my colleague who would have more knowledge in this space. Thanks for your patience!

**Comment by richard-motion** [comment]
No problem Winnie. I appreciate the update.

**Comment by anpin** [comment]
hi @winnie , I wonder if UWP support is coming soon?
