### ISSUE TITLE
Toggle Email Notifications from Admin for all the users

### ISSUE THREAD

**Issue by DevSachinOps** [microsoft/appcenter#1009]
**Describe the solution you'd like**
We have 4 apps in our account and around 100 users so whenever a build triggers and release new version of app, it sends email notification as well as slack alerts. So for one build there are 400 emails trigger. We don't want the email notifications for these apps. 

Currently we can not disable email notifications for all the users under an account. User can only change their own settings for email notifications. 
**I wish if there could be a feature for admins of that account from where admin can toggle email notifications for all the users.**

**Describe alternatives you've considered**
I have communicated to my complete team to disable the email notifications from the account settings for them. We had around 100 users registered and they had to disable the email notifications for them.

**Comment by elamalani** [comment]
@DevSachinOps Thanks for adding this feature request. We will review it with the team and consider it for future prioritization.
