### ISSUE TITLE
Mono repo

### ISSUE THREAD

**Issue by RWOverdijk** [microsoft/appcenter#101]
We have a mono repository but still want to automatically make builds on merge. The problem is that we only want to build on changes in the directory of the app. Currently it would rebuild on every change made in the repository.

Is there a way to only run a build when there have been changes in our directory? If not, it might be a cool feature.

**Comment by RWOverdijk** [comment]
Hei! Any news on this?

**Comment by nrajpurkar** [comment]
Hi @RWOverdijk, no update on this feature request at the moment, but something we are still tracking as a feature request

**Comment by RWOverdijk** [comment]
Thanks for the reply :)

**Comment by teovillanueva** [comment]
Any news?

**Comment by RWOverdijk** [comment]
https://news.google.com/
