### ISSUE TITLE
Multiple Build Config

### ISSUE THREAD

**Issue by mdbill** [microsoft/appcenter#1010]
**Describe the solution you'd like**
I would like to have multiple build configurations on ONE branch.
For example, I'd like an AppStore , and Ad-Hoc, for devices, and a simulator build config...all on the master branch.

**Describe alternatives you've considered**
multiple branches. each with one config

**Comment by Boosten** [comment]
This would be very useful. Especially to differentiate on release type. At the moment we're creating multiple apps for each release type for each platform (e.g. iOS: Ad-hoc and App Store). This clutters the app overview page a bit when you've quite some apps. 
Only 1 app per platform would be necessary if we could define multiple build definitions within 1 app. 

Other approach would be to introduce a different branch for testing: 
- develop: integration branch that will be used for Ad-Hoc/Alpha channel releases
- master: production branch that will be used for App-Store/Play-store production releases

@mdbill How are you now handling multiple release types?

**Comment by mdbill** [comment]
> @mdbill How are you now handling multiple release types?

I'm still building locally with my Macbook. I couldn't convince myself to switch to appcenter.

**Comment by ThomasLoidolt** [comment]
In my case I think its enough to have the resign option at store distribution. For me I found the solution to download the IPA file with AddHoc built run a resign script for signing with store and upload the IPA to store.

Because if you have to rebuild it it could be an additional error source
