### ISSUE TITLE
Increase width of "What's New" container for new app version emails

### ISSUE THREAD

**Issue by thsbrown** [microsoft/appcenter#1011]
**Describe the solution you'd like**
Currently when a new version of an app is release an email is sent to testers. Were noticing that "What's New" container is pretty slim which makes text a bit more difficult to read. We think increasing this container width would make text much more legible.

**Additional context**
Below are some screenshots of a before and after of the suggested change. After was generated via chrome developer console adjustment.

**Before**
![Before](https://user-images.githubusercontent.com/2967721/64736154-de3d6e80-d49e-11e9-9c2f-22749ec67de9.jpg)
**After**
![After](https://user-images.githubusercontent.com/2967721/64736173-e7c6d680-d49e-11e9-8ff9-0bd8846891d9.jpg)

**Comment by elamalani** [comment]
@Spartanace1024 Thanks for adding this feature request. We will review it with the team and consider it for future prioritization.

**Comment by thsbrown** [comment]
Ooof this one hurts as it seems like it was a trivial change that would make the display a whole lot more readable.
