### ISSUE TITLE
App Center With Appium + Cucumber + Java

### ISSUE THREAD

**Issue by apamcamargo** [microsoft/appcenter#1012]
App center have support to run tests with Appium + Cucumber + Java?

I trying execute but return exceptions every time.

To copy all dependencies I run this command:
mvn -DskipTests -P prepare-for-upload package

To run tests on app center I execute this command:
appcenter test run appium --app "appName" --devices "devicesName" --app-path "MyAPKPATH"  --test-series "test" --locale "en_US" --build-dir target/upload

(P.S: when I run, I replace the app path, device name, and app name with my parameters)
-----------

**Comment by elamalani** [comment]
@apamcamargo Thanks for submitting this feature request. We will discuss it with the team and consider it for further prioritization.

**Comment by mail2madhva** [comment]
Any updates on this, we are trying to run tests through Cucumber Java and the Appcentre appium test always gives 0/0 tests run at the end. Is there any work around ?

**Comment by fabiore** [comment]
any update on this request ?

**Comment by rlechetaudemy** [comment]
any update on this?

**Comment by rlechetaudemy** [comment]
this issue is from 2019, the app center documents are out of date.. still don't support cucumber+appium?

**Comment by rlecheta** [comment]
any update on this?

**Comment by flutterdev-vinit** [comment]
Any updates on this thread? 
Is there anyway to make use of cucumber for automation on windows app center. It seems Calabash is already deprecated and no major updates is there in Github.

**Comment by MatEvangelist** [comment]
Has anyone found a solution to this problem?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
