### ISSUE TITLE
Webhook for distribution | incorrect release_notes | Slack

### ISSUE THREAD

**Issue by aamol** [microsoft/appcenter#1015]
Hi , I am using Webhook for slack integration and found that the release notes section is randomly having correct release notes (Git message) and sometime the name of the job.
I tried to create a webhook with the request.bin but seeing the same behaviour there in the release_notes vairable in the JSON . 

Is this a known issue or I am missing something

**Comment by elamalani** [comment]
@aamol Are you still running into this issue? Can you please reach out to us via support for further investigation?

**Comment by botatoes** [comment]
Please open a support ticket on appcenter.ms. Closing this issue for now.
