### ISSUE TITLE
Allow the user to log into App center from multiple devices simultaneously without logging them out on other devices

### ISSUE THREAD

**Issue by alxprodn** [microsoft/appcenter#1017]
I use AppCenter for testing my apps and I have a load of mobile devices where I have to log into app center daily. This is annoying as hell, as with Hockey app, I was logged into it for months and all of my 50 devices at the same time without being asked to log in daily.

Could you please change or add the following:

- Set session expiration to several months (or allow me to pick that option for my account)
- Increase number of simultaneous sessions to unlimited (or allow me to pick this)

It's getting really tedious and time consuming to repeat this every day.

Thank you

**Comment by botatoes** [comment]
Hi, this should not be an issue. Can you open a support ticket on appcenter.ms? We'll get more info about your app and take it from there.
