### ISSUE TITLE
UITests iOS: Unable to start UITest on selected simulator or device

### ISSUE THREAD

**Issue by nielscup** [microsoft/appcenter#1019]
**Describe the solution you'd like** 
Start UITest on selected iOS simulator

**Describe alternatives you've considered**
Selecting a different simulator in build config or Test pad does not work.

**Additional context**
To test on smaller screens I need to be able to run UITest on iPhone 5s.
Currently, UITests always start on the same Simulator, iPhone Xs Max in my case. This problem started since VS 2019 8.x (for Mac) and did not occur on VS 7.x.

**Comment by nielscup** [comment]
Selecting a real device only works sometimes: it runs once correctly on the correct device, but I have to make sure all simulators are closed and only 1 device is connected. If I then start another UITest it will start the same simulator again and run there.

**Comment by nielscup** [comment]
Any progress on this issue? I can't reproduce failed UItests on small devices because of this issue. I have to restart VS each time it decides to run our tests on a different simulator. Target device in UITests pad is set correctly, even if build config is set to iPhone VS still decides to launch the simulator.

**Comment by nielscup** [comment]
Additional info:
When testing on a real device, I noticed that if you right click a UITests in your testpad and select "Run" the simulator starts.
If I select "Debug", the UI test starts on the correct device. If I select a different UITest and select "Debug", the simulator (sometimes?) starts again.

If I restart the UITest to quickly I get the Xamarin.UITest.XDB.Exceptions.DeviceAgentException.

I am still unable to start the UITest on the correct simulator, it always starts the same simulator, even if the app is currently running on the selected simulator.

**Comment by Oddj0b** [comment]
Hey @nielscup, thanks for keeping this alive. I'm talking with people around the board to find a solution.

**Comment by LeroyStaines** [comment]
> Selecting a real device only works occasionally: it runs once correctly on the correct device, but I have to make sure all simulators are closed and only 1 device is connected. If I then start another UITest it will start the same simulator again and run there.

Same issue here. Really struggling to test, as it fails on the simulator with a deployment issue (simulator version not supported) and it almost always refuses to select the real device I have plugged in, even though it's the deployment target.

**Comment by justinimel** [comment]
I'm seeing this issue in VS22 as well.  Will there ever be a solution where we can reliably use the VS level settings to chose the simulator/device to run on?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
