### ISSUE TITLE
Error in fetching the Apple service connection details

### ISSUE THREAD

**Issue by andreialecu** [microsoft/appcenter#1022]
When trying to connect to App Store Connect for a new project I'm getting this error:

![image](https://user-images.githubusercontent.com/697707/64851638-7747c300-d620-11e9-9840-d1c653938036.png)

Trying to add the account again also results in an error that the account already exists.

What could be wrong?

**Comment by andreialecu** [comment]
An additional error when trying to set up a new app specific password (although the previous one that was set was still valid):

![image](https://user-images.githubusercontent.com/697707/64851955-1cfb3200-d621-11e9-8382-c6256ed21e4f.png)

**Comment by andreialecu** [comment]
I was able to completely remove the account and re-add it. Seems that it went through.

Perhaps there could be a better explanation of what is wrong, and hints on what to try in the interface. The errors were quite unhelpful.

**Comment by elamalani** [comment]
@andreialecu  Were you able to resolve the issue? If you see it again, please reach out to us via support.

**Comment by andreialecu** [comment]
I was able to resolve it by re-adding the account. 

Would be a good idea to improve this flow though. Feel free to close.

**Comment by thinking-twins** [comment]
Another solution: Click on your Avatar -> Account Settings -> Developer Accounts
There was a message noting "invalid". Just click on it and "re-connect" your account.

**Comment by oguennec** [comment]
The mis-leading error is still present as of today but thinking-twins solution works well (when clicking on Reconnect, the apple password is not requested, it's just an Apple re-authentication).
