### ISSUE TITLE
React Native > 0.6 - Unable to build via AppCenter for ios

### ISSUE THREAD

**Issue by peacepostman** [microsoft/appcenter#1024]
Hello,

I'm writing here to publish an issue that i've resolved and maybe it can help people struggling with it.

We were always having those following errors while building for ios 

> clang: error: no such file or directory: "/Users/vsts/agent/2.155.1/work/1/s/ios/Pods/DoubleConversion/double-conversion/bignum.cc"
> clang: error: no input files
> 
> clang: error: no such file or directory: "/Users/vsts/agent/2.155.1/work/1/s/ios/Pods/DoubleConversion/double-conversion/bignum-dtoa.cc"
> clang: error: no input files

I've managed to resolved it with those two steps : 

**1. Edit appcenter-post-clone**

Open your `appcenter-post-clone.sh`, if none created, refer to microsoft guide, and add the following : 

> COCOAPODS_VER=`sed -n -e 's/^COCOAPODS: \([0-9.]*\)/\1/p' Podfile.lock`
> if test -z "$COCOAPODS_VER" 
> then
>     COCOAPODS_VER=1.7.5
> fi
> 
> echo "Installing CocoaPods version $COCOAPODS_VER"
> sudo gem install cocoapods -v $COCOAPODS_VER

**2. Edit appcenter-pre-build**

Open your `appcenter-pre-build.sh`, if none created, refer to microsoft guide, and add the following : 

> echo 'Installing Pods'
> cd ./ios/ && pod install
> echo 'Pods are installed properly !'

I hope it can help some future folks.

Best regards,

**Comment by elamalani** [comment]
@peacepostman Thanks for listing the steps that helped you resolve the issue. We would likely more it over and update our docs with the suggested steps.

**Comment by djohnsonkc** [comment]
Thanks for the tip! 

I had to alter the "cd ./ios/ && pod install" command in the appcenter-pre-build.sh. a bit to the following to help with our migration from React Native 0.57 to 0.60. 

cd ./ios && rm -rf Pods && pod cache clean --all && pod repo update && pod install

Thanks again!

**Comment by stephan-markovic** [comment]
A workaround for building on ReactNative > 0.6 is provided.
Current React Native is 0.68
