### ISSUE TITLE
When running a uitest it should be possible to specify a TestFixture

### ISSUE THREAD

**Issue by jpc1963** [microsoft/appcenter#1025]
I am new to the app center - and how it can be use to run tests. But I would like to see a (small) improvement. I develop & test mainly on a MAC (so think VS2019 for mac).

The following is an example of how to start a ui test in the appcenter:

> **appcenter test run uitest --app "MyApp" --devices BlaBla --app-path /path/MytApp.ipa  --test-series "master" --locale "en_US" --build-dir /test/bin/Debug --include-category Login**

This of course works OK but it does not correspond to how I designed my tests almost 3 years ago. This was initially done to schedule ui tests using Jenkins and to run tests on simulators/emulators. 

Note that the above command line specifies a test category. But I have never used these. I have always use TestFixtures. The reason for this is two-fold: 
1. You can add parameters to your tests using TestFixtures
2. Visual studio by default shows tests by test fixture. Each parameter in you test fixture is shown as an individual test you can select an run.

An example of how I use this would be as follows:
**[TestFixture(MyApp01, Platform.Android)]**
**[TestFixture(MyApp01, Platform.iOS)]**
**[TestFixture(MyApp99, Platform.Android)]**
**[TestFixture(MyApp99, Platform.iOS)]**
    
These test fixtures are defined per feature (think category). So for the "Login" feature/category, I can specifically test multiple apps which share the same functionality. This setup also works perfectly in Jenkins where I can schedule my test per app/feature. Here I use the following command to start the test:

> **nunit-console.exe Test/bin/Debug/MyTest.dll -run="Features.Login(MyApp01,iOS)"**

With the above TestFixture example, the app center would run the test 4 times. 
 
**Describe alternatives you've considered**
It should be possible to start a test in the appcenter by specifying a "TestFixture" instead of a "Category". Or to be able to specify both.

**Comment by VincentH-Net** [comment]
This is already possible with the `--fixture` parameter.

Excerpt from output of `appcenter test run uitest --help`:
```
--fixture <arg>                      NUnit fixture / namespace to run. If used with include / exclude the fixture filter is applied first (Can be used multiple times)
```

**Comment by King-of-Spades** [comment]
Thanks @VincentH-Net! 

@jpc1963 if you try that solution and it doesn't work for you, I'd recommend providing your observations & background data. 

(e.g. what Xamarin.UITest version you're using, whether there's an error message, if the test runs but ignores the fixture specification etc.) 

I'm tagging this issue with "Response Required", our bot will automatically close the issue in 1 week if we don't hear back from you; though you can still comment on the issue and we can potentially reopen it if justified.

**Comment by jpc1963** [comment]
Obviously I did'nt read the help properly. But in the app center chat, I was also told it was not possible - and because of that conversation I created this. You live and learn.

I'm sure it works ok and I have adjusted my local scripts. I will test them when I can - but my free test subscription has run out.

**Comment by King-of-Spades** [comment]
@jpc1963 sorry to hear about that discrepancy. Can you open that chat and request the case number for the ticket so I can find and review it for improving support? 

Or you can ask the ticket be assigned to Kent Green (that's me).

**Comment by jpc1963** [comment]
I have asked for the ticket to be assigned to you. thanks.

**Comment by King-of-Spades** [comment]
Thanks for sharing that. In reviewing the ticket, I think what happened is when we discussed the question internally there was some confusion between expected vs. desired behavior. My apologies for the mixup, I think the best thing we can do at this point is document it accordingly.

**Comment by jpc1963** [comment]
No problem. Like I said, I could also have read the manual properly :)

**Comment by imatviienkoomcinc** [comment]
Guys, are you able to use  --fixture to specify run only IOS or Android tests. Where can I find some examples of it uses.

**Comment by jpc1963** [comment]
> @King-of-Spades , Guys, are you able to use --fixture to specify run only IOS or Android tests. Where can I find some examples of it uses.

I have not run scripts for a while as we are trying to do it all from the appcenter ie: build then test.
But this script (example) should work:
`appcenter test run uitest --app "MyTeam/iOS-My-App" --devices 4c3ab95c --app-path /Users/Shared/Jenkins/TestApps/MyApp.ipa  --test-series "master" --locale "en_US" --build-dir /Users/me/SourceCode/UITests/bin/Debug --fixture "UITest.Fixtures.LoginToApp("MyApp,iOS")"
`

**Comment by Oddj0b** [comment]
It's also possible to mix fixtures with categories: https://docs.microsoft.com/en-gb/appcenter/test-cloud/uitest/working-with-categorized-tests?tabs=vswin

**Comment by imatviienkoomcinc** [comment]
I try to run it from command line, I use "(" it said that it is an inappropriate symbol.  Here is the command I use : 

appcenter test run uitest --app "Omcinc/Omcinc-IOS" --devices "Omcinc/ios-set" --app-path /Users/ymatviienko/work/IOS/TaskMaverick.Xamarin.iOS.ipa --test-series "ios-smoke" --locale "en_US" --build-dir /Users/ymatviienko/Projects/Taskmaverick.TestAutomation/TaskMaverickMobileTests/TaskMaverickMobileTests/bin/Debug/net472/ --uitest-tools-dir /Users/ymatviienko/Downloads/Archive/packages/Xamarin.UITest.3.0.5/tools/ --include appsettings.json —fixture “TaskMaverickMobileTests.Tests.ScheduledMissionTests(Android)”

And I got Error: 
Filtered.: TaskMaverickMobileTests.Tests.LocationTests(Android).TaskE2ETest, TaskMaverickMobileTests.Tests.LocationTests(iOS).TaskE2ETest, TaskMaverickMobileTests.Tests.ScheduledMissionTests(Android).ScheduledMissionTest, TaskMaverickMobileTests.Tests.ScheduledMissionTests(iOS).ScheduledMissionTest

Preparing tests... failed.

**Comment by imatviienkoomcinc** [comment]
Maybe some suggestions of what is wrong with my command. 
I got such structure:
namespace TaskMaverickMobileTests.Tests
{
    [TestFixture(Platform.iOS)]
    [TestFixture(Platform.Android)]
    public class ScheduledMissionTests : BaseTestFixture

And I want to run only IOS or Android tests via app center

**Comment by jpc1963** [comment]
> I try to run it from command line, I use "(" it said that it is an inappropriate symbol. Here is the command I use :
> 
> appcenter test run uitest --app "Omcinc/Omcinc-IOS" --devices "Omcinc/ios-set" --app-path /Users/ymatviienko/work/IOS/TaskMaverick.Xamarin.iOS.ipa --test-series "ios-smoke" --locale "en_US" --build-dir /Users/ymatviienko/Projects/Taskmaverick.TestAutomation/TaskMaverickMobileTests/TaskMaverickMobileTests/bin/Debug/net472/ --uitest-tools-dir /Users/ymatviienko/Downloads/Archive/packages/Xamarin.UITest.3.0.5/tools/ --include appsettings.json —fixture “TaskMaverickMobileTests.Tests.ScheduledMissionTests(Android)”
> 
> And I got : -bash: syntax error near unexpected token `('

i think you need to put quotes around Android ie: `“TaskMaverickMobileTests.Tests.ScheduledMissionTests("Android")”
`

**Comment by imatviienkoomcinc** [comment]
it looks like it failed on the first symbol "(" so it even not come to Android word.
