### ISSUE TITLE
Choose devices in test by availability for faster execution

### ISSUE THREAD

**Issue by mattperzel** [microsoft/appcenter#1026]
**Describe the solution you'd like**
Our used case would be to select by OS version any device that is currently available. Then maybe select the newest device that matches the OS version and is available.

**Describe alternatives you've considered**
Look at the API to see if this information is exposed and modify our CI to dynamically generate the call to test. Or select undesirable devices in our sets,

**Additional context**
We generally run with device sets, but sometimes we want to run our tests quickly. In those cases it would be helpful to have the tests run with less waiting for devices.

**Comment by elamalani** [comment]
@mattperzel Thanks for adding this feature request. We will talk to the team and consider it for future prioritization.

**Comment by Oddj0b** [comment]
@mattperzel If I understand you correctly, you want to run a test on any devices running a specific OS version. Is this because you've experienced long wait times on our devices?

**Comment by mattperzel** [comment]
@Oddj0b I think its more that we have a couple of scenarios.  In general we are happy with our device set of popular devices.  That works well for running comprehensive tests against our builds as any delay in getting the devices doesn't really matter.

But there are other scenarios,  testing the tests, PRs, etc where we just to be able to run the tests ASAP.  In particular we have been debugging tests that only fail on the AppCenter but the developer fixing them has been having up to an hour delay provisioning the devices. At the moment their doesn't seem to be a way for us to find the idle devices in order to speed up our dev loop.

So to answer your question, yes its because of long wait times. But only in some scenarios does it really matter.

**Comment by Oddj0b** [comment]
@mattperzel thank you for elaborating, I understand your request and I'm hoping we get enough 👍 reactions.
