### ISSUE TITLE
Make it easier to switch GitHub account for build

### ISSUE THREAD

**Issue by zerojozhanwork** [microsoft/appcenter#1027]
**Describe the solution you'd like**
The scenario is that I wanted to switch to a different GitHub account after I connected a GitHub repository for build. Today, after I disconnected all the repos, the UI opens repo selection for the already "linked" GitHub account. There is no UI to allow me "unlink" and it doesn't even point me to where or how I can do that.

There should be a button or link which at least takes me to the OAuth page of my linked GitHub account. Or maybe just the documentations so I don't have to ask search engine to do it.

**Additional context**
![image](https://user-images.githubusercontent.com/49210532/64879853-b9b2d500-d60b-11e9-9768-a847b2d542a8.png)

**Comment by joezha** [comment]
Ah, apologies that I used my test github account to open the issue. :)

**Comment by nrajpurkar** [comment]
Thanks for creating this issue. We do have [information](https://docs.microsoft.com/en-us/appcenter/build/connect#github) in our documentation on how to disconnect the current connection and replace with another one. Showing this somewhere in the UI would make this clearer.
