### ISSUE TITLE
Make it easier to toggle screen context between different Apps

### ISSUE THREAD

**Issue by grahamyesfit** [microsoft/appcenter#1028]
**Describe the solution you'd like**
I use AppCenter primarily to deploy my Android App to test users and Google Play (when AppCenter can manage my certificates and provisioning profiles I'll use it for deploying my iOS App too, but that's a different feature request). I use CodePush for both Android and iOS. From the CodePush dashboard, I wish it was easier to toggle between Apps. Navigating from Android to iOS and back again takes so many clicks. When I'm monitoring code push bundles, especially right after a new release, I navigate between my Apps a lot, and the click-count starts to add up. It's especially frustrating when I navigate out using the breadcrumbs and then I forget where I'm coming from and where I'm going to. So much clicking.

**Describe alternatives you've considered**
An App select-list in the AppCenter site header would greatly improve navigation, for all pages. The select-list would be available from every screen and would allow you to instantly toggle the current page context between your Apps.

**Comment by elamalani** [comment]
@grahamhayes Thanks for adding this feature request. We will talk to the team and consider it for future prioritization.
