### ISSUE TITLE
Add support for a heuristic approach to detect iOS Signals

### ISSUE THREAD

**Issue by dive** [microsoft/appcenter#103]
# Describe the solution you'd like 

## Proposal 

It would be really nice to have a heuristic approach to handle crashes caused by iOS (via signals).
It is not easy and complicated sometimes, but this information is crucial when you have huge applications with DAU more than 1M users because it helps to identify hidden issues with the application, performance or with 3rd party modules integration.

## How HockeyApp handles signals

To make a point, let's assume that AppCenter is going to implement all the features of HockeyApp. Basing on this assumption, I will explain how it works in HockeyApp at the moment (I'm sure you know, but still) because this is the simplest way to implement this feature for AppCenter.

With HockeyApp SDK it is possible to handle iOS signals with a **heuristics** handler that tries to get a crash report when the application got killed while being in the foreground due to the following reasons:

- The main thread was blocked for too long;
- The application took too long to start up;
- The application tried to allocate too much memory;
- The application overloaded CPU and was killed by iOS Watchdog;
- Probably something else related to iOS Watchdog behaviour.

Also, this heuristic approach tracks `didReceiveMemoryWarning` and mark such crashes with additional information:

- `SIGKILL` - The application did not terminate cleanly but no crash occurred;
- `SIGKILL` - The application did not terminate cleanly but no crash occurred. The app received at least one Low Memory Warning.
 
There are some limitations though, from [HockeyApp documentation](https://www.hockeyapp.net/help/sdk/ios/3.6.4/Classes/BITCrashManager.html#//api/name/enableAppNotTerminatingCleanlyDetection):

> Crash reports triggered by this mechanism do NOT contain any stack traces since the time of the kill cannot be intercepted and hence no stack trace of the time of the kill event can’t be gathered.

But it is still possible to investigate such crashes when the application provides additional information via attachments and custom descriptions. 

The current heuristic approach in HockeyApp is implemented as follows: 

> It is assumed that the app got either killed by iOS while being in the foreground or a crash occurred that couldn’t be detected when: 
> - the application never gets a `UIApplicationDidEnterBackgroundNotification`;
> - or the application never gets a `UIApplicationWillTerminateNotification` notification; 
> - or `PLCrashReporter` doesn’t detect a crash itself, and the app starts up again.

# Describe alternatives you've considered

There are no alternatives in general but you can consider the logic implemented for Fabric Crashlytics to track [OOM terminations](https://docs.fabric.io/apple/crashlytics/OOMs.html).

# Additional context

**Links**

- [HockeyApp `enableAppNotTerminatingCleanlyDetection`](https://www.hockeyapp.net/help/sdk/ios/3.6.4/Classes/BITCrashManager.html#//api/name/enableAppNotTerminatingCleanlyDetection);
- [Reducing FOOMs in the Facebook iOS app](https://code.fb.com/ios/reducing-fooms-in-the-facebook-ios-app/) - this is the same approach that Crashlytics used for their OOM tracking, but with images, explanations and additional information about the states;
- [Fabric: Out of Memory (OOM) Terminations](https://docs.fabric.io/apple/crashlytics/OOMs.html).

**Comment by dive** [comment]
@winnieli1208, @derpixeldan, let me know if you need more information or real-life examples. As I said before, this metric is fundamental to us in Badoo.

**Comment by winnieli1208** [comment]
Hi @dive, 

Thanks for the feedback! We don't currently have this on our short term roadmap but I'll monitor this feature request to better prioritize this in the future. I spoke with our SDK team and it looks like supporting a heuristic approach would require some non-trivial backend changes. 

I encourage you to follow our [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) for any updates and our [iteration plan](https://github.com/Microsoft/appcenter/wiki/Iteration-plans) to see what our team is working on. Thanks!

**Comment by dive** [comment]
Hi @winnieli1208,

You're welcome. I see your points about backend support, but is there any chance that you will implement the feature before HockeyApp shutdown?

**Comment by winnieli1208** [comment]
Hi @dive - unfortunately I can't make a commitment on the ETA. Our team is focused on ensuring our users have a smooth transition to App Center and we're monitoring feedback to prioritize these features. I spoke to the team and we haven't heard this request from too many other users which is why we don't have this on our immediate plans. 

I apologize for not having a more helpful answer but if anything changes I will definitely let you know!

**Comment by smpeleato** [comment]
This feature is also very important to us, consider this another vote for it.

**Comment by liguopku** [comment]
We also use this feature to track FOOM/BOOM in hockeyapp previously and vote up for it!
