### ISSUE TITLE
Push.Send(push_notification)

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#1030]
Hi,

Please add a command to send pus notification from within the app without having to call the API to make it easier to send messages.

This can be something like this:

```
var push_notification = new PushNotification(
     Owner = ..................,
     AppName = .....................,
     Message = ........................,
     Sound = ................................,
     SendOn = [...Shcedule.....],
     Parameters = {param1 = ....., param2 = ........},
     SendTo = {device1, device2, ......},
);

var result = Push.Send(push_notification);

```

Thanks,
Jassim

**Comment by jwargo** [comment]
@jrahma just to make sure I understand the request, you're look for a device to device push API in the SDK? Can you describe the app requirement for this?  I'm curious about the app you're building if this is a requirement. Most developers send notifications from their app backend, not from a device application.

**Comment by jrahma** [comment]
@jwargo no app in my hand with this requirement but it's just a thought in case it can be done and if it's helpful for others

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
