### ISSUE TITLE
Flutter .aab files publish suport?

### ISSUE THREAD

**Issue by RenanDelfanti** [microsoft/appcenter#1034]
How to build and publish aab files with appcenter-post-clone.sh flutter?

**Comment by nrajpurkar** [comment]
Hi @RenanDelfanti, please take a look at the [build script examples](https://github.com/microsoft/appcenter/tree/master/sample-build-scripts/flutter) for Flutter apps. This gives you the ability to build Flutter apps even though it is not natively supported in App Center. @botatoes can speak to any plans we have for Distribution support for Flutter apps.

**Comment by RenanDelfanti** [comment]
Hi @nrajpurkar, with this scripts I'm able to build and distribuite .apk files normaly. When I'm select on build config to generate .aab files, I see this error and my build fail: 

`##[error]Publishing build artifacts failed with an error: Not found PathtoPublish: /Users/vsts/agent/2.155.1/work/1/a/bundle`

**Comment by nrajpurkar** [comment]
I'd recommend posting the build script you're using. You could also cross post in the AAB issue and see if anybody else is building Flutter AABs with build scripts. Generally, we don't troubleshoot and debug build scripts as the possibilities are endless.

**Comment by RenanDelfanti** [comment]
@nrajpurkar I change my script build, and now I don't have the error.
But, how to select appbundle to distribute on store?
`#!/usr/bin/env bash
#Place this script in project/android/app/

cd ..

# fail if any command fails
set -e
# debug log
set -x

cd ..
git clone -b beta https://github.com/flutter/flutter.git
export PATH=`pwd`/flutter/bin:$PATH

#flutter channel stable
flutter version v1.7.8+hotfix.4
flutter doctor

echo "Installed flutter to `pwd`/flutter"
flutter packages get
flutter build apk --release
flutter build appbundle

#copy the APK where AppCenter will find it
mkdir -p android/app/build/outputs/apk/; mv build/app/outputs/apk/release/app-release.apk $_
mkdir -p android/app/build/outputs/bundle/; mv build/app/outputs/bundle/release/app.aab $_`

**Comment by RenanDelfanti** [comment]
I create a pull request with my script.
See in #1037
