### ISSUE TITLE
Appium 1.11.0 is not supporting android 10 (Q)

### ISSUE THREAD

**Issue by Zhappa** [microsoft/appcenter#1038]
**Describe the solution you'd like**
Update to appium 1.13.0 at least

**Describe alternatives you've considered**
Provide a solution to be able to run tests using Appium v1.11.0 and Android 10 devices.

**Additional context**
I believe appium v 1.11.0 can't run any test using devices with Android version 10 (Q)

My tests are working using Appium 1.11.0 and Android <10 for both local and appium center environments.
But they did not work (exact same tests) using Appium 1.11.0 and Android 10 for both local and appium center environments.
And they DID work locally if we are using Appium 1.13.0 for all of the Android versions

**Can someone confirm this?**

You can use this sample project: https://github.com/King-of-Spades/AppCenter-Samples/tree/master/Appium/Android

Environment:
- appium v1.11.0 (to install from npm: npm -g install appium@1.11.0)
- emulator with android 10

**Comment by jwargo** [comment]
@Zhappa thank you for this feedback, I've passed this on to the Test PM for his review.

**Comment by Oddj0b** [comment]
@Zhappa Internally we're running test on Android 10, have you experienced any problems?

**Comment by Zhappa** [comment]
> @Zhappa Internally we're running test on Android 10, have you experienced any problems?

Yeap, my tests did not work with android Q emulator using appium v1.11.0, but exact same tests are working with exact same android Q emulator using appium v1.13.0.

So, i believe the problem is in appium version. And i asking you to confirm this.
The reason im asking you to do so - Appcenter support appium v1.11.0 only.

We discussed this with the Appcenter's (chat) support team and this ticket -  is the result of this discussion.


Still, this might be tests technical issue, so im looking forward for your reply to be sure this is not because of Appium v1.11.0 version, but because of my test malfunction.

So
> @Zhappa Internally we're running test on Android 10, have you experienced any problems?
Are you able to run them using Appium v1.11.0 or another framework?

**Comment by King-of-Spades** [comment]
Related to ADO PM - 40170

**Comment by King-of-Spades** [comment]
Related to #1203 (Request to update to Appium 1.15 for iOS 13 support.)

**Comment by caisd1998** [comment]
My simple test does not have issues with Pixel 4 (with Android 10).
It launches app, taps a button to go to login screen, enters user name and password to login and proceed to home screen.

**Comment by Oddj0b** [comment]
We're internally testing the latest Appium upgrade and would like your help. If you want to test Appium in version 1.16 in App Center Test, all you have to do is add a `--test-parameter pipeline=appium-v1.16.0` switch when submitting your test. If you have problems, please don't hold back and let our support know.

**Comment by Zhappa** [comment]
This is works! https://appcenter.ms/orgs/Wontok/apps/Android_3440_WontokGa_Release/test/runs/735b8c2c-2d21-4c2e-b27a-6c95922e1d8e/2-0-10/9e5a2f9b-8577-4ab0-a8a7-5a1e709704c8
I can now contunue with my Android Q devices, thank you!

I will close this ticket when 1.16.0 will be fully on board.

**Comment by Oddj0b** [comment]
@zhappa Thank you for testing it out.

**Comment by Oddj0b** [comment]
Appium 1.16 is the default version for all Appium Test runs and the `--test-parameter pipeline=appium-v1.16.0` is no longer required.
