### ISSUE TITLE
Build Status Cancel Button + Commit Message Build Trigger Feature Requests

### ISSUE THREAD

**Issue by bobber205** [microsoft/appcenter#1039]
**Describe the solution you'd like**
On a branch screen you can see all the builds/ the ones that are running and the ones queued up. Sometimes I'll make a push or two I don't want to start a build then say the 3rd push is the one I want to build.

Here's what would be really nice.

1) Some kind of message a person could put in a commit message to either trigger a build or prevent it depending on the settings.

2) A "Cancel" build button on this main page. It'd be nice to cancel a few queued up builds by just pressing 1 button instead of having to click into the build log page, wait for it to load, then press Cancel.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by King-of-Spades** [comment]
If a build is active, I do see a cancel button. Here's a pseudo url to find that, replacing the ALL_CAPS strings with acceptable values:

https://appcenter.ms/orgs/ORG_NAME/apps/APP_NAME/build/branches/BRACH_NAME/builds/BUILD_NUMBER

Are you referring to adding a Cancel button on a different spot? (You could always try a screenshot and then drawing with some Paint program where you'd like to see the button.) If it's clear to the team where you'd like to see those it might increase the likelihood of it getting implemented.

**Comment by bobber205** [comment]
![image](https://user-images.githubusercontent.com/5841107/65451822-ccd85880-ddf4-11e9-84ea-fc9fa149b282.png)

Image of the requested place.
