### ISSUE TITLE
Cucumber support in Appium Java Tests

### ISSUE THREAD

**Issue by mohamedsaif** [microsoft/appcenter#104]
**Describe the solution you'd like**
App Center currently do not support Cucumber tests running as part of Appium Java tests. Cucumber offers a convenient way of writing the BDD tests and it would be great if these tests are supported to run in App Center Test.

**Describe alternatives you've considered**
Stick to using JUnit tests on Appium is not really a solution.

**Additional context**
Cucumber is a test framework which supports BDD where the tests are written in normal English, expressing how the application or system has to behave. It is great to have a domain specific language that is an executable test, which starts with a known state, perform some action and verify the expected state.

**Comment by Oddj0b** [comment]
Thank you for your feedback.

**Comment by Oddj0b** [comment]
I'm the program manager responsible for App Center Test and I'm working on a new idea which will support more frameworks in Test, allow unit testing, and browser testing. I would like to talk to you about it and understand your needs better.

Below is a link where you can sign-up for a 30-minute call with me. The agenda will be about the value of testing for you and your organization, and my new idea to allow more frameworks and testing styles in App Center Test.

Link to choose https://calendly.com/vigimm/appcenter-test

**Comment by Rishivanthya** [comment]
Can I have the update on this ..Whether Appium with Cucumber framework is  supported ?

**Comment by dmishra2** [comment]
Can I have the update on this ..Whether Appium with Cucumber framework is supported ?

**Comment by dmishra2** [comment]
> **Describe the solution you'd like**
> App Center currently do not support Cucumber tests running as part of Appium Java tests. Cucumber offers a convenient way of writing the BDD tests and it would be great if these tests are supported to run in App Center Test.
> 
> **Describe alternatives you've considered**
> Stick to using JUnit tests on Appium is not really a solution.
> 
> **Additional context**
> Cucumber is a test framework which supports BDD where the tests are written in normal English, expressing how the application or system has to behave. It is great to have a domain specific language that is an executable test, which starts with a known state, perform some action and verify the expected state.

Is the support for Appium with Cucumber framework restored?

**Comment by guruo5** [comment]
Hi, is there any update on Appium with cucumber framework?

**Comment by asafetech1** [comment]
> I'm the program manager responsible for App Center Test and I'm working on a new idea which will support more frameworks in Test, allow unit testing, and browser testing. I would like to talk to you about it and understand your needs better.
> 
> Below is a link where you can sign-up for a 30-minute call with me. The agenda will be about the value of testing for you and your organization, and my new idea to allow more frameworks and testing styles in App Center Test.
> 
> Link to choose https://calendly.com/vigimm/appcenter-test

Hi I want to know whether App center support any BDD test framework, Its really hard to perform Automation testing without BDD. As a part of CI CD we need to perform Mobile automation Testing.

**Comment by Oddj0b** [comment]
Currently, we support Appium Java with Maven and to my knowledge, it's experimental with a BDD layer on top of that. Hopefully, we can work on adding a BDD layer if feature requests like this get enough upvotes.

**Comment by agulia1** [comment]
could we have an update if cucumber feature files are supported? We are stuck with not being able to run them so far...

**Comment by rlechetaudemy** [comment]
any update on this? still not supporting cucumber/bdd?

**Comment by MatEvangelist** [comment]
Has anyone already find a solution?
