### ISSUE TITLE
Recruitment link feature?

### ISSUE THREAD

**Issue by prnewman** [microsoft/appcenter#1040]
Hoping that App Center will introduce a feature like the [HockeyApp recruitment link](https://support.hockeyapp.net/kb/app-management-2/how-to-invite-beta-testers) or the [TestFlight public link](https://developer.apple.com/news/?id=09262018a). This makes distribution of builds to new testers much easier. You can also make this link available via a web view to enlist current app users to be beta testers.

Current workaround is to use the App Center API with fastlane to invite users to an app or distribution group: https://openapi.appcenter.ms/#/account/appInvitations_create

**Comment by jwargo** [comment]
@prnewman I thought we had something like this, but it's not my area of focus. I'll pass on your feedback to the PM team and they'll respond with clarification.

**Comment by prnewman** [comment]
Excellent, thank you.

**Comment by botatoes** [comment]
I have logged this as a feature request we'll want to add in the future. Thank you!

**Comment by awBSH** [comment]
+1 
this is a very important feature since we are using Enterprise Signed iOS Apps, which we need to ensure are only be available for our internal staff

**Comment by des5ve** [comment]
You can do this by following these steps:
1. Create Distribution group
2. Enable installs from public link within group
3. Add the entire app to the group
4. Go to individual build within the app and "distribute" to group created
5. Copy/paste link from the group and share.
