### ISSUE TITLE
Build Error building android app

### ISSUE THREAD

**Issue by lcamilo** [microsoft/appcenter#1042]
I am trying to build an android application, but I am getting the error below, already tried to understand, already researched and found nothing that could help me. Could anyone help me understand if it's a build agent bug? The project is built smoothly on my machine.

Thanks in advance.

Leandro Camilo

> SYSTEMVSSCONNECTION exists true
>[command]/Users/vsts/agent/2.155.1/work/1/s/android/gradlew -p android clean  :app:assembleDebug
>Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
>Gradle 5.4.1
>
>FAILURE: Build failed with an exception.
>
>* Where:
>Script '/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 190

>* What went wrong:
>A problem occurred evaluating settings 'EscolaPatelli'.
>> Unable to determine the current character, it is not a string, number, array, or object
  
>  The current character read is 'i' with an int value of 105
>  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
>  info React Native CLI will continue to run if your local environment matches what React Native expects. If it does fail, check out "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native/node_modules/@react-native-community/cli/setup_env.sh" and adjust your environment to match it.{  "root": "/Users/vsts/agent/2.155.1/work/1/s",  "reactNativePath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native",  "dependencies": {    "appcenter": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter",      "name": "appcenter",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter/ios/AppCenterReactNative.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter/ios/appcenter.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter/ios/AppCenterReactNative.xcodeproj",          "projectName": "AppCenterReactNative.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": null      },      "assets": [],      "hooks": {        "postlink": "node node_modules/appcenter/scripts/postlink"      },      "params": []    },    "appcenter-analytics": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-analytics",      "name": "appcenter-analytics",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-analytics/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-analytics",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-analytics/ios/AppCenterReactNativeAnalytics.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-analytics/ios/appcenter-analytics.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-analytics/ios/AppCenterReactNativeAnalytics.xcodeproj",          "projectName": "AppCenterReactNativeAnalytics.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": null      },      "assets": [],      "hooks": {        "postlink": "node node_modules/appcenter-analytics/scripts/postlink"      },      "params": []    },    "appcenter-crashes": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-crashes",      "name": "appcenter-crashes",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-crashes/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-crashes",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-crashes/ios/AppCenterReactNativeCrashes.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-crashes/ios/appcenter-crashes.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/appcenter-crashes/ios/AppCenterReactNativeCrashes.xcodeproj",          "projectName": "AppCenterReactNativeCrashes.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": null      },      "assets": [],      "hooks": {        "postlink": "node node_modules/appcenter-crashes/scripts/postlink"      },      "params": []    },    "react-native-vector-icons": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons",      "name": "react-native-vector-icons",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/RNVectorIcons.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/RNVectorIcons.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/RNVectorIcons.xcodeproj",          "projectName": "RNVectorIcons.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": null      },      "assets": [        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/AntDesign.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/Entypo.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/EvilIcons.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/Feather.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/FontAwesome.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/FontAwesome5_Brands.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/FontAwesome5_Regular.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/FontAwesome5_Solid.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/Fontisto.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/Foundation.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/Ionicons.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/MaterialIcons.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/Octicons.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/SimpleLineIcons.ttf",        "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-vector-icons/Fonts/Zocial.ttf"      ],      "hooks": {},      "params": []    },    "react-native-code-push": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-code-push",      "name": "react-native-code-push",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-code-push/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-code-push",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-code-push/ios/CodePush.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-code-push/CodePush.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-code-push/ios/CodePush.xcodeproj",          "projectName": "CodePush.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [            "libz.tbd"          ],          "plist": []        },        "android": null      },      "assets": [],      "hooks": {        "postlink": "node node_modules/react-native-code-push/scripts/postlink/run",        "postunlink": "node node_modules/react-native-code-push/scripts/postunlink/run"      },      "params": []    },    "@react-native-community/async-storage": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/async-storage",      "name": "@react-native-community/async-storage",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/async-storage/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/async-storage",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/async-storage/ios/RNCAsyncStorage.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/async-storage/RNCAsyncStorage.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/async-storage/ios/RNCAsyncStorage.xcodeproj",          "projectName": "RNCAsyncStorage.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/async-storage/android",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/async-storage",          "packageImportPath": "import com.reactnativecommunity.asyncstorage.AsyncStoragePackage;",          "packageInstance": "new AsyncStoragePackage()"        }      },      "assets": [],      "hooks": {},      "params": []    },    "react-native-fs": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-fs",      "name": "react-native-fs",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-fs",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-fs",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-fs/RNFS.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-fs/RNFS.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-fs/RNFS.xcodeproj",          "projectName": "RNFS.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-fs/android",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-fs",          "packageImportPath": "import com.rnfs.RNFSPackage;",          "packageInstance": "new RNFSPackage()"        }      },      "assets": [],      "hooks": {},      "params": []    },    "react-native-gesture-handler": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-gesture-handler",      "name": "react-native-gesture-handler",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-gesture-handler/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-gesture-handler",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-gesture-handler/ios/RNGestureHandler.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-gesture-handler/RNGestureHandler.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-gesture-handler/ios/RNGestureHandler.xcodeproj",          "projectName": "RNGestureHandler.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-gesture-handler/android",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-gesture-handler",          "packageImportPath": "import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;",          "packageInstance": "new RNGestureHandlerPackage()"        }      },      "assets": [],      "hooks": {},      "params": []    },    "react-native-html-to-pdf": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-html-to-pdf",      "name": "react-native-html-to-pdf",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-html-to-pdf/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-html-to-pdf",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-html-to-pdf/ios/RNHTMLtoPDF.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-html-to-pdf/react-native-html-to-pdf.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-html-to-pdf/ios/RNHTMLtoPDF.xcodeproj",          "projectName": "RNHTMLtoPDF.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-html-to-pdf/android",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-html-to-pdf",          "packageImportPath": "import com.christopherdro.htmltopdf.RNHTMLtoPDFPackage;",          "packageInstance": "new RNHTMLtoPDFPackage()"        }      },      "assets": [],      "hooks": {},      "params": []    },    "react-native-share": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-share",      "name": "react-native-share",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-share/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-share",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-share/ios/RNShare.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-share/RNShare.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-share/ios/RNShare.xcodeproj",          "projectName": "RNShare.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-share/android",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-share",          "packageImportPath": "import cl.json.RNSharePackage;",          "packageInstance": "new RNSharePackage()"        }      },      "assets": [],      "hooks": {},      "params": []    },    "react-native-version-number": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-version-number",      "name": "react-native-version-number",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-version-number/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-version-number",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-version-number/ios/RNVersionNumber.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-version-number/react-native-version-number.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-version-number/ios/RNVersionNumber.xcodeproj",          "projectName": "RNVersionNumber.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-version-number/android",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native-version-number",          "packageImportPath": "import com.apsl.versionnumber.RNVersionNumberPackage;",          "packageInstance": "new RNVersionNumberPackage()"        }      },      "assets": [],      "hooks": {},      "params": []    },    "rn-fetch-blob": {      "root": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/rn-fetch-blob",      "name": "rn-fetch-blob",      "platforms": {        "ios": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/rn-fetch-blob/ios",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/rn-fetch-blob",          "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/rn-fetch-blob/ios/RNFetchBlob.xcodeproj/project.pbxproj",          "podfile": null,          "podspecPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/rn-fetch-blob/rn-fetch-blob.podspec",          "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/rn-fetch-blob/ios/RNFetchBlob.xcodeproj",          "projectName": "RNFetchBlob.xcodeproj",          "libraryFolder": "Libraries",          "sharedLibraries": [],          "plist": []        },        "android": {          "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/rn-fetch-blob/android",          "folder": "/Users/vsts/agent/2.155.1/work/1/s/node_modules/rn-fetch-blob",          "packageImportPath": "import com.RNFetchBlob.RNFetchBlobPackage;",          "packageInstance": "new RNFetchBlobPackage()"        }      },      "assets": [],      "hooks": {        "prelink": "node ./node_modules/rn-fetch-blob/scripts/prelink.js"      },      "params": []    }  },  "commands": [    {      "name": "log-ios",      "description": "starts iOS device syslog tail"    },    {      "name": "run-ios",      "description": "builds your app and starts it on iOS simulator",      "examples": [        {          "desc": "Run on a different simulator, e.g. iPhone 5",          "cmd": "react-native run-ios --simulator \"iPhone 5\""        },        {          "desc": "Pass a non-standard location of iOS directory",          "cmd": "react-native run-ios --project-path \"./app/ios\""        },        {          "desc": "Run on a connected device, e.g. Max's iPhone",          "cmd": "react-native run-ios --device \"Max's iPhone\""        },        {          "desc": "Run on the AppleTV simulator",          "cmd": "react-native run-ios --simulator \"Apple TV\"  --scheme \"helloworld-tvOS\""        }      ],      "options": [        {          "name": "--simulator [string]",          "description": "Explicitly set simulator to use. Optionally include iOS version betweenparenthesis at the end to match an exact version: \"iPhone 6 (10.0)\"",          "default": "iPhone X"        },        {          "name": "--configuration [string]",          "description": "Explicitly set the scheme configuration to use",          "default": "Debug"        },        {          "name": "--scheme [string]",          "description": "Explicitly set Xcode scheme to use"        },        {          "name": "--project-path [string]",          "description": "Path relative to project root where the Xcode project (.xcodeproj) lives.",          "default": "ios"        },        {          "name": "--device [string]",          "description": "Explicitly set device to use by name.  The value is not required if you have a single device connected."        },        {          "name": "--udid [string]",          "description": "Explicitly set device to use by udid"        },        {          "name": "--no-packager",          "description": "Do not launch packager while building"        },        {          "name": "--verbose",          "description": "Do not use xcpretty even if installed"        },        {          "name": "--port [number]",          "default": 8081        },        {          "name": "--terminal [string]",          "description": "Launches the Metro Bundler in a new window using the specified terminal path."        }      ]    },    {      "name": "log-android",      "description": "starts logkitty"    },    {      "name": "run-android",      "description": "builds your app and starts it on a connected Android emulator or device",      "options": [        {          "name": "--root [string]",          "description": "Override the root directory for the android build (which contains the android directory)",          "default": ""        },        {          "name": "--variant [string]",          "description": "Specify your app's build variant",          "default": "debug"        },        {          "name": "--appFolder [string]",          "description": "Specify a different application folder name for the android source. If not, we assume is \"app\"",          "default": "app"        },        {          "name": "--appId [string]",          "description": "Specify an applicationId to launch after build.",          "default": ""        },        {          "name": "--appIdSuffix [string]",          "description": "Specify an applicationIdSuffix to launch after build.",          "default": ""        },        {          "name": "--main-activity [string]",          "description": "Name of the activity to start",          "default": "MainActivity"        },        {          "name": "--deviceId [string]",          "description": "builds your app and starts it on a specific device/simulator with the given device id (listed by running \"adb devices\" on the command line)."        },        {          "name": "--no-packager",          "description": "Do not launch packager while building"        },        {          "name": "--port [number]",          "default": 8081        },        {          "name": "--terminal [string]",          "description": "Launches the Metro Bundler in a new window using the specified terminal path."        },        {          "name": "--tasks [list]",          "description": "Run custom Gradle tasks. By default it's \"installDebug\""        },        {          "name": "--no-jetifier",          "description": "Do not run \"jetifier\" – the AndroidX transition tool. By default it runs before Gradle to ease working with libraries that don't support AndroidX yet. See more at: https://www.npmjs.com/package/jetifier.",          "default": false        }      ]    }  ],  "assets": [],  "platforms": {    "ios": {},    "android": {}  },  "haste": {    "providesModuleNodeModules": [      "react-native"    ],    "platforms": [      "ios",      "android"    ]  },  "project": {    "ios": {      "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/ios",      "folder": "/Users/vsts/agent/2.155.1/work/1/s",      "pbxprojPath": "/Users/vsts/agent/2.155.1/work/1/s/ios/EscolaPatelli.xcodeproj/project.pbxproj",      "podfile": "/Users/vsts/agent/2.155.1/work/1/s/ios/Podfile",      "podspecPath": null,      "projectPath": "/Users/vsts/agent/2.155.1/work/1/s/ios/EscolaPatelli.xcodeproj",      "projectName": "EscolaPatelli.xcodeproj",      "libraryFolder": "Libraries",      "sharedLibraries": [],      "plist": []    },    "android": {      "sourceDir": "/Users/vsts/agent/2.155.1/work/1/s/android/app",      "isFlat": false,      "folder": "/Users/vsts/agent/2.155.1/work/1/s",      "stringsPath": "/Users/vsts/agent/2.155.1/work/1/s/android/app/src/main/res/values/strings.xml",      "manifestPath": "/Users/vsts/agent/2.155.1/work/1/s/android/app/src/main/AndroidManifest.xml",      "buildGradlePath": "/Users/vsts/agent/2.155.1/work/1/s/android/app/build.gradle",      "settingsGradlePath": "/Users/vsts/agent/2.155.1/work/1/s/android/settings.gradle",      "assetsPath": "/Users/vsts/agent/2.155.1/work/1/s/android/app/src/main/assets",      "mainFilePath": "/Users/vsts/agent/2.155.1/work/1/s/android/app/src/main/java/br/com/nascam/escolapatelli/MainApplication.java",      "packageName": "br.com.nascam.escolapatelli"    }  }}
>  ^
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

>* Get more help at https://help.gradle.org

>BUILD FAILED in 15s
>Error: /Users/vsts/agent/2.155.1/work/1/s/android/gradlew failed with return code: 1
>    at ChildProcess.<anonymous> (/Users/vsts/agent/2.155.1/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/1.128.0/node_modules/vsts-task-lib/toolrunner.js:569:30)
>    at emitTwo (events.js:106:13)
>    at ChildProcess.emit (events.js:191:7)
>    at maybeClose (internal/child_process.js:886:16)
>    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
>##[error]Error: /Users/vsts/agent/2.155.1/work/1/s/android/gradlew failed with return code: 1

**Comment by nrajpurkar** [comment]
Hi @lcamilo, can you reach out to App Center support for this? You should see a bubble in the lower right hand corner of App Center to engage.
