### ISSUE TITLE
Ability to delete individual builds

### ISSUE THREAD

**Issue by King-of-Spades** [microsoft/appcenter#1043]
**Describe the solution you'd like**
In App Center Build, being able to delete individual Builds. 

**Describe alternatives you've considered**
Deleting the branch configuration deletes *all* Builds that were created with that configuration; however, it's not possible to choose some to keep and some to get rid of.

**Comment by nicolgit** [comment]
Any news on this FR?

**Comment by nrajpurkar** [comment]
@nicolgit no update to share on this at the moment.

**Comment by indieshack** [comment]
Still no update on this?

**Comment by david-m-globant** [comment]
you can use the API [https://github.com/microsoft/appcenter/issues/200#issuecomment-474993389](https://github.com/microsoft/appcenter/issues/200#issuecomment-474993389)
