### ISSUE TITLE
Different Badges for ios and android

### ISSUE THREAD

**Issue by wamry** [microsoft/appcenter#1044]
Could you have two badges for build success/failure ? one for android and one for ios ?

Maybe the android would have the android logo, and ios would have the apple logo, maybe just the word "ios" and "android" before the word "build", for example "ios | build", "android | build"

**Comment by nrajpurkar** [comment]
Thanks for the feature request @wamry. The way App Center is set up, you have two different apps - one for iOS and one for Android. You'll have a different build badge for each app that you can embed. I understand how this can be confusing for putting those both in the same repo.

**Comment by wamry** [comment]
> Thanks for the feature request @wamry. The way App Center is set up, you have two different apps - one for iOS and one for Android. You'll have a different build badge for each app that you can embed. I understand how this can be confusing for putting those both in the same repo.

yes, i understand that, the problem is that they look exactly the same

**Comment by jkapsouras** [comment]
You can put some text like above to distinguish them
<img width="388" alt="Screenshot 2020-04-07 at 10 52 05 AM" src="https://user-images.githubusercontent.com/19539170/78644025-e38c5b80-78bd-11ea-930d-6d5c31ba59f1.png">

**Comment by wamry** [comment]
> You can put some text like below to distinguish them:
> 
> <img alt="Screenshot 2020-04-07 at 10 52 05 AM" width="388" src="https://user-images.githubusercontent.com/19539170/78644025-e38c5b80-78bd-11ea-930d-6d5c31ba59f1.png">

That's exactly what i'm trying to avoid

**Comment by jkapsouras** [comment]
> > You can put some text like below to distinguish them:
> > <img alt="Screenshot 2020-04-07 at 10 52 05 AM" width="388" src="https://user-images.githubusercontent.com/19539170/78644025-e38c5b80-78bd-11ea-930d-6d5c31ba59f1.png">
> 
> That's exactly what i'm trying to avoid

Understandable but as @nilofer commented these are two different projects. For me, a good feature would be extra badges (not necessarily dynamic) to show the project name or type or programming language used (for example #xamarin or #swift or #iOS or #fantasting_project like avatars). So you will have a build badge and and extra badge to show you the type of project.

**Comment by softlion** [comment]
Any way to get badges for groups ? And releases ? With release number on them ?

**Comment by elemanhillary** [comment]
my badges never update, why?
