### ISSUE TITLE
Release error using Xcode 11: "Your app was built with an unsupported version of Xcode or SDK"

### ISSUE THREAD

**Issue by jvandenaardweg** [microsoft/appcenter#1045]
After a successful build using Xcode 11 in AppCenter, when releasing to TestFlight:

> DEBUG [2019-09-18 02:47:03.32]: [Transporter]: DBG-X:  parameter Errors = [ERROR ITMS-90534: "Invalid Toolchain. Your app was built with an unsupported version of Xcode or SDK. If you plan to submit this build to the App Store, make sure you are using the GM version of Xcode 9 and the SDK for iOS 11, tvOS 11, watchOS 4, or macOS 10.13 or later. If you are using an Xcode beta version to test your app, make sure you are using the latest supported version. For more information about supported beta versions, view the TestFlight Release Notes (https://developer.apple.com/testflight/release-notes/)."]

Using a previous Xcode version (10) worked without a problem. But I need Xcode 11 to work atm.

According to [this topic](https://discuss.circleci.com/t/xcode-11-gm-seed-1-released/32379/13), it might have to do with the builder using GM 1, but Apple already requires you to use GM 2 since 1-2 days.

From [Apple's release notes (September 16, 2019)](https://developer.apple.com/app-store-connect/whats-new/?id=09162019a):
> You can now submit apps built with Xcode 11 GM seed 2 (11A420a) using the iOS 13 SDK and watchOS 6 SDK to the App Store. **Apps built with Xcode 11 GM seed (11A419c) can no longer be uploaded to App Store Connect.** Please note that apps built with Xcode 11 GM seed (11A419c) using named colors may experience lookup failures (with no value returned) when they run on iOS 11 or earlier. If you’ve uploaded an app that uses named colors, you’ll need to rebuild your app with Xcode 11 GM seed 2 (11A420a), test on iOS 11 or earlier, and resubmit to the App Store.

And the builder is actually using that version:
> Task         : Xcode
> Description  : Build, test, or archive an Xcode workspace on macOS. Optionally package an app.
> Version      : 4.130.0
> Author       : Microsoft Corporation
> 
> [command]/usr/bin/xcodebuild -version
> Xcode 11.0
> Build version **11A419c**

Can AppCenter look at this asap? The solution would be to just use the latest GM seed in the build process.

**Comment by jvandenaardweg** [comment]
Seems to be fixed now 🎉

**Comment by max-lobanov** [comment]
@jvandenaardweg, we are deploying new image with `Xcode 11 GM seed 2` right now.
Deployment takes long time, so some machines might still contain `Xcode 11 GM seed 1`

**Comment by max-lobanov** [comment]
Deployment is done. `Xcode 11 GM seed 2` is available on all machines

**Comment by jvandenaardweg** [comment]
Thanks @max-lobanov for the quick fix! 👍

**Comment by tritter** [comment]
@maxim-lobanov The issue is there again we need 11.2.1! 
"Invalid Toolchain. Your app was built with an unsupported version of Xcode or SDK. If you plan to submit this build to the App Store, make sure you are using the GM version of Xcode 10.1 and the SDK for iOS 12.1"

**Comment by maxim-lobanov** [comment]
@tritter, Xcode 11.2.1 request is tracked by own issue: #1336 .
It will be available in 1-2 days.
