### ISSUE TITLE
Add timestamp next to the date in the App Center mobile site

### ISSUE THREAD

**Issue by davisben85** [microsoft/appcenter#1047]
**Describe the solution you'd like**
Currently, only the date shows under the build information on the install.appcenter.ms site.  Please add the time too, as that exists in Hockey App and is useful.

**Describe alternatives you've considered**
No other alternatives, please add the time.

**Additional context**
<img width="575" alt="Screen Shot 2019-09-18 at 12 17 24 PM" src="https://user-images.githubusercontent.com/4484573/65166245-59a69f00-da0e-11e9-84db-5e89a9a752a4.png">
<img width="494" alt="Screen Shot 2019-09-18 at 12 17 15 PM" src="https://user-images.githubusercontent.com/4484573/65166251-5c08f900-da0e-11e9-8ee1-3ccf79b9da9c.png">

**Comment by davisben85** [comment]
The image that does not have the time, is from App Center, and the image with the time, is from Hockey App, for the same build.

**Comment by jwargo** [comment]
@davisben85 thank you for that feedback, I'll pass it on to the Build team.
