### ISSUE TITLE
Unexpected error while talking to CosmosDB

### ISSUE THREAD

**Issue by TomSoderling** [microsoft/appcenter#1048]
[MainPageViewModel.txt](https://github.com/microsoft/appcenter/files/3627594/MainPageViewModel.txt)

I've followed [this doc](https://docs.microsoft.com/en-us/appcenter/sdk/data/xamarin#creating-a-document) to get started with App Center Data for a brand new XF app, but when I attempt to create a document, I get this error every time.

```
{Microsoft.AppCenter.Data.DataException: Unexpected error while talking to CosmosDB. ---> 
  Foundation.NSErrorException: Error Domain=com.Microsoft.AppCenter.Data.ErrorDomain Code=300 "Unexpected error while talking to CosmosDB." UserInfo={NSLocalizedDescription=Unexpected error while talking to CosmosDB., MSHttpCodeKey=403}
   --- End of inner exception stack trace ---
  at AppCenterBaaS.ViewModels.MainPageViewModel.OnCreateNewUserButtonTapped () [0x00081] in /Users/tomso/Documents/Code/AppCenterBaaS/AppCenterBaaS/ViewModels/MainPageViewModel.cs:33 }
```

Code file for my ViewModel is attached

I'm currently working with support on this item, but I saw that this is the requested place to leave feedback

**Comment by jwargo** [comment]
@TomSoderling yes, this is the place for App Center feedback, feature requests, etc. The support team is the right place to work through problems, that's a faster path to the resources that can help you.

**Comment by TomSoderling** [comment]
Not sure what caused this - I think it was due to my B2C tenant being in a separate directory from my subscription. Creating a new App Center app and doing the auth setup with a link to the B2C tenant seemed to do the trick.

One point of feedback - it seems that if your azure subscription already has an active directory, a new directory is created when creating the new database in App Center. This is really confusing - is that the intended behavior?

**Comment by Zakeelm** [comment]
Glad this was resolved! I believe that was likely the issue. And no, I don't believe that's intended behavior. I can't seem to replicate this either. Would you mind telling me the steps you took?

**Comment by TomSoderling** [comment]
Trying to think back, I just followed the flow in the App Center portal, Data section. I suspect that the Azure subscription I used already had an Active Directory tenant, so that's what it created the B2C tenant in a different directory. Does that make sense? Is that possible?
Happy to discuss more - I really struggled with this issue for the first week + of trying to get this to work
