### ISSUE TITLE
Missing option to create ticket in bug tracker

### ISSUE THREAD

**Issue by chris-paterson** [microsoft/appcenter#1049]
In HockeyApp there was an option to create a new ticket in a bug tracker. This option appears to be missing in AppCenter. There is an option to auto-create tickets when the number of crashes exceeds some threshold but that does not fit our workflow. 

Are there any plans to add the ability to create a Jira ticket for a specific crash group?

**Comment by jwargo** [comment]
@chris-paterson thank you for that feedback, I've passed it on to the Distribution team. I know we have bug tracker integration from the Diagnostics side, I'm not sure what we have planned for the Distribution service.

**Comment by chris-paterson** [comment]
Hey, thanks for the quick reply! Sorry if there was a misunderstanding but I was talking about diagnostics, not distribution. 
Where would I find the option to create a ticket for a specific crash group in the diagnostic side?

**Comment by amchew** [comment]
Hi @chris-paterson! We do support creating a ticket in Jira Cloud for crash groups: https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/. Today it is auto-creation, but if I understand you correctly, you're asking for manual creation of a bug in a specific crash group, is that right? 

If so, that's on our backlog, but no ETA yet. Adding @winnieli1 to share more details.

**Comment by chris-paterson** [comment]
Yeah, that's correct, we'd like to manually create tickets. 

Thanks for the update!

**Comment by winnieli1** [comment]
Hi Chris - thanks for the feature request! This is something we'd like to support but unfortunately I don't have a better answer for you. We'll keep this issue open to track community support and I'll update you if I have any news. We also consitently update our public roadmap to reflect what our plans are so definitely keep an eye out on that!

**Comment by happysally** [comment]
we just moved from hockey app to app center and looking forward to such feature,

**Comment by awBSH** [comment]
This is also a very important feature of HockeyApp. We have multiple App variants which would create redundant JIRA tickets from crashes. We manually create crash tickets and mostly just link to existing crash tickets.

**Comment by DanieleScipioni** [comment]
Very important for our app too.
Automatic creation of a ticket is not useful to us also because we have in Jira some mandatory custom fields and I believe that automatic ticket creation would be almost impossible; I can create the Jira ticket manually, this is not a problem.
What will be useful is a way to link the crash to the Jira ticket so that from the crash I can open ticket quickly, and most important I would like to see which crash is connected to the bug tracker in crash list: I mean to add one more status "tracked" so that I can quickly see identify crash without ticket (like it was in Hockey App).

**Comment by awBSH** [comment]
Same for us - thanks @DanieleScipioni 

It's very hard to keep track if you don't see which crash is already linked to a JIRA issue.

**Comment by theeagle** [comment]
The automatic creation feature is very useful for our workflow, but the inability to set a specific threshold in AppCenter makes the auto-create feature very noisy. If possible, please add the threshold option back in for AppCenter.

**Comment by princiangi** [comment]
Same here, auto-create works, but its not usefull when you can't set any parameters like 'minimum crashrate' or some additional fields. 
Would be nice to get this function :)

**Comment by evnik** [comment]
This seems to be a duplicate of #902
