### ISSUE TITLE
Use or allow to configure using App Center manually uploaded image in Build distribution email.

### ISSUE THREAD

**Issue by JPSiller** [microsoft/appcenter#1051]
When we distribute and iOS or Android build through app center, the Icon that is shown in the email is the one that was embedded into the APK/IPA. This results in different icons being shown between both builds as well as bad resolution since the icon image might be pretty small. This also allow use to use a totally different image (ie. Using the company's logo).

It is also inconsistent with the Build Successful/Build Failed email, that one shows the image manually uploaded to app center.

I would like the email to contain the image that I manually uploaded in app center, basically the one showing up in my app center dashboard for each platform. It would be nice to either use the one uploaded when available or be able to tell app center to use the one I uploaded rather than the one from the build itself.

Thanks

**Comment by jwargo** [comment]
@JPSiller that's a great suggestion, I'll pass this on to the service PM.

**Comment by botatoes** [comment]
Hi, thanks for raising this concern. In general, the logic behind the app icon is that for developer-facing scenarios, the uploaded icon is used and for tester scenarios, the extracted icon is used. This is so that in the case app icon and the extracted icon is different, the testers won't be confused between the email they get and the actual app downloaded.

**Comment by JPSiller** [comment]
Hi @botatoes thanks for the explanation, although I agree that makes sense, it wouldn't hurt to have the option to override the icon with what ever icon you want to present rather than being forced to use the one from the build. It might be an edge case scenario but it would be handy for us. Definitely not a priority but a nice to have if your team has capacity.

Thanks
