### ISSUE TITLE
Functionality to upload .env files

### ISSUE THREAD

**Issue by akiwarheit** [microsoft/appcenter#1052]
**Describe the solution you'd like**
An `Upload .env file` button to populate environment variables

e.g.

![Lit2019](https://user-images.githubusercontent.com/713107/65465929-9ad8fc00-deb1-11e9-96a0-61f7025f219d.png)

**Describe alternatives you've considered**
Manually copy pasting environment variables

**Additional context**
Most projects that follow 12factor would already have a local `.env` so rather than having to type it all over again in appcenter, it would be nice to just upload the file.

https://12factor.net/config

> A litmus test for whether an app has all config correctly factored out of the code is whether the codebase could be made open source at any moment, without compromising any credentials.

Following 12factor - we shouldn't commit `.env` files so we leverage appcenter's environment variables to re-create the `.env` file via build scripts.

**Comment by jwargo** [comment]
@akiwarheit is this for the Build service? Can you please provide some context?

**Comment by akiwarheit** [comment]
@jwargo apologies for being vague - I've uploaded a screenshot above.

But essentially what I'm asking for is a button under `Environment Variables` that allows us to upload our `.env` files rather than typing all the environment variables manually.

**Comment by jwargo** [comment]
@akiwarheit got it, I'll share this with the PM.

**Comment by nrajpurkar** [comment]
Thanks for the feature suggestion! I can see how this would be speedier than defining the variables in the UI. We'll track this feature request as a potential future improvement.

**Comment by akiwarheit** [comment]
Lit. Thanks fam. Let me know if I can provide more info.

**Comment by harisraza123** [comment]
BUMP
