### ISSUE TITLE
In App Center the version display should be larger

### ISSUE THREAD

**Issue by stevedavis7** [microsoft/appcenter#1053]
In App Center there is a popup to choose which version to view the data. 
If it is currently set to something with a short version (2.3.0) and you open the menu, the menu is small and it truncates the name of versions with a longer version string. This makes it impossible to differentiate the versions in the menu

Ex:
<img width="420" alt="Screen Shot 2019-09-18 at 6 25 15 PM" src="https://user-images.githubusercontent.com/3642172/65191430-ed459300-da41-11e9-9632-8442e7470d82.png">

**Comment by baileybrooks** [comment]
@stevedavis7 Thanks for this piece of feedback. I will get this communicated with our CoreUX team ASAP and we will get moving on the fix.
