### ISSUE TITLE
[Build] Support Bitbucket on-prem as source code service

### ISSUE THREAD

**Issue by bnoffer** [microsoft/appcenter#1054]
**Describe the solution you'd like**
As support for on-prem Gitlab is already being worked on it would be nice to support on-prem Bitbucket as well.

**Describe alternatives you've considered**
We currently have to use Azure DevOps to deliver our builds to App Center Test, which is not ideal.

**Additional context**
As discussed:
* MicrosoftDocs/appcenter-docs#404
* MicrosoftDocs/appcenter-docs#247

**Comment by jwargo** [comment]
@bnoffer thank you for this suggestion, we've had customers ask for this before. I'll share your feedback with the service PM.

**Comment by tgb-greenhouse** [comment]
Yes pleeeease. I'd love to test this and see the benefits it offers over our current CI tool. Though it seems that those of us still using BB Server are few & far between, it'd be highly appreciated! Early Christmas present? :-)

**Comment by tme-apps** [comment]
@jwargo Any update from the service PM?

**Comment by nrajpurkar** [comment]
Hi @tme-apps, there are no short-term plans to support on-prem Bitbucket. We will continue to monitor this feature request and review it when prioritizing future work.

**Comment by harman-sunnysun** [comment]
Request to support on-prem Bitbucket too!!!

**Comment by SHoen** [comment]
Request Bitbucket on-prom too.

**Comment by SOliasS** [comment]
Any update on this topic?

**Comment by isamabufool** [comment]
Any update on this topic?
