### ISSUE TITLE
Building an iOS app with Xcode 11 fails with IDEFoundationErrorDomain Code=1 "IPA processing failed"

### ISSUE THREAD

**Issue by tamassengel** [microsoft/appcenter#1055]
When I try to build an iOS app using Xcode 11, the build fails and the following error appears in the build output log:

```
Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed}

** EXPORT FAILED **

##[error]Error: /usr/bin/xcodebuild failed with return code: 70
```
This error wasn't present when my selected Xcode version was 10.3.
What should I do in order to fix this?

**Comment by jwargo** [comment]
@tamassengel have you contacted our support team on this issue? Click the blue chat button at the bottom-right corner of every App Center page, that connects you directly to our dedicated support team.

**Comment by tamassengel** [comment]
@jwargo Thanks for your response, I've contacted the support team.

**Comment by tamassengel** [comment]
As it turned out, this is an issue in my project. Thank you for your assistance!

**Comment by 87073312130** [comment]
> As it turned out, this is an issue in my project. Thank you for your assistance!

**Comment by desaikevin** [comment]
I am also seeing this issue @tamassengel what was the resolution?

**Comment by tamassengel** [comment]
@desaikevin It was caused by a framework incompatible with Xcode 11. I'm now building with Xcode 10.3 until that framework gets updated.

**Comment by desaikevin** [comment]
thank you! @tamassengel

**Comment by yilunx-flurrydev** [comment]
I have the exact same issue as you. Can you share what is the frame you found that cause the issue?@tamassengel

**Comment by tamassengel** [comment]
@yilunx-flurrydev It was an earlier version of the FoxitRDK framework. I downloaded the latest version again and it works perfectly now.

**Comment by yilunx-flurrydev** [comment]
Thank you for your response.

**Comment by auernmri** [comment]
Hi @tamassengel  
i think i have a similar problem as one of my dependencies (pods) is not able to be exported with XCode 11 Tools... May i ask how you found out which was the incompatible one, i can`t detect in the logs from the export. 

Thank s in advance!

**Comment by zulkis** [comment]
Hi @auernmri,

Can you bring a light on what was `incompatible` for you and how did you found it?

Thanks!

**Comment by auernmri** [comment]
Hi @zulkis 
i found the problem in the device error logs after the "ipa processing failed". 
I was using some embedded framework and it came with a script (apparently which is stripping some architectures and codesigning). After executing the script in build phases it worked again. 
The error came up with XCode 11, but i guess it s more related to the new build system... (just a guess)

**Comment by Darren-chenchen** [comment]
https://www.darrenblog.cn/#/detail/5dbf9a8a7bb725236692b6d4
