### ISSUE TITLE
Accidentally dismissing modal

### ISSUE THREAD

**Issue by beeradmoore** [microsoft/appcenter#1056]
**Describe the solution you'd like**
To dismiss a modal that pops in from the right it's common to click the blank space on the left to hide it.  If you are in a rush and try to select everything in a box you may overshoot the text box (shown in the example below) and release outside of the modal. This causes the distribute window to dismiss. I know this is 100% user error and can be fixed by me being more careful, but I feel this action of click quick drag and release is a common one. This can be particularly annoying if you've just typed up your app changes and go to copy it to paste on the iOS/Android platform as well as the temporary change log is not retained.

This issue isn't specific to the distribute window, it's very easy to dismiss the build settings page while trying to copy an environment variable name, discarding all changes in the process.

It took me a while to realise what was happening, I though the dashboard was just buggy. I can't speak for anyone else if they are coming across the same issue.

**Describe alternatives you've considered**
Either replace dismiss modal with mouse down outside of it or only dismiss modal if the mouse up and mouse down events occur outside the modal. (I am not 100% confident as a web developer but I believe that should be possible)

**Additional context**
[Video showing the issue](https://youtu.be/tuLgCumsh-0)

**Comment by jwargo** [comment]
@beeradmoore would it just be easier to give you a copy button for copying the content from the modal?

**Comment by beeradmoore** [comment]
Yes and no. It gets me on both ends, selecting all to copy (or write new), selecting all to paste.

**Comment by iageoghe** [comment]
@beeradmoore I actually can't duplicate this with a mouse up event. What browser are you using? Do you have any extension turned on that might impact this behavior?

**Comment by beeradmoore** [comment]
@iageoghe , I am able to replicate it in macOS (10.14.6) on both Edge (Chromium dev, version 79.0.279.0) and Safari (13.0.1). Both in incognito mode with 0 extensions loaded.

**Comment by MichaelCrimando** [comment]
Happens to me on Chrome 77.0.3865.120 (Official Build) (32-bit) as well

**Comment by MichaelCrimando** [comment]
Still happens on Chrome Version 91.0.4472.124 (Official Build) (32-bit)

**Comment by beeradmoore** [comment]
Another nice solution would be if changes are present in the right settings window to pop up a dialog of "are you sure you want to quit without saving?"

**Comment by beeradmoore** [comment]
Ping. Still happening.
