### ISSUE TITLE
Analytics: see detailed OS version distribution

### ISSUE THREAD

**Issue by valerianb** [microsoft/appcenter#1057]
I'd like to know which iOS versions our users have. This helps me decide when I can drop support for old versions.
Currently, it's only possible to see a very succinct OS Distribution bar chart which shows the top 3 versions. It would be awesome to be able to expand that bar chart to a table view showing all the OS versions.

Thank you.

**Comment by jwargo** [comment]
@valerianb thank you for the suggestion, I will pass your feedback on to the service PM.

**Comment by hamswan** [comment]
Thanks @valerianb , We will add this as a feature request.

**Comment by yoannchaudet** [comment]
@valerianb Only our portal limits you to the top 3 OS in the distribution. You are only a [quick API call](https://openapi.appcenter.ms/#/analytics/Analytics_OperatingSystemCounts) away from getting the full list ;).

**Comment by valerianb** [comment]
> @valerianb Only our portal limits you to the top 3 OS in the distribution. You are only a [quick API call](https://openapi.appcenter.ms/#/analytics/Analytics_OperatingSystemCounts) away from getting the full list ;).

Oh, awesome. Thanks.

**Comment by humblehacker** [comment]
Unfortunately, the API is not sufficient.  It does give back more versions than are visible in the UI, but it still includes "Other" which encompasses a significant percentage (almost 7% in my case).  

We need a breakdown of _all_ versions - especially the least used versions - in order to determine where to make the cut.

**Comment by yoannchaudet** [comment]
@humblehacker If the aggregation our Analytics engine provide is not sufficient, I can only recommend you to enable [Export to Application Insights](https://docs.microsoft.com/en-us/appcenter/analytics/export#azure-application-insights). This will give you access to an actual query engine on top of your raw SDK logs.

**Comment by valerianb** [comment]
@humblehacker you need to pass the `top` query parameter. See doc:
`The maximum number of results to return. (0 will fetch all results) Default value : 30`
Passing 0 will get you *all* versions :)

**Comment by humblehacker** [comment]
@valerianb It works! Thanks so much for your help.

**Comment by minhnh94** [comment]
> @humblehacker you need to pass the `top` query parameter. See doc:
> `The maximum number of results to return. (0 will fetch all results) Default value : 30`
> Passing 0 will get you _all_ versions :)

Thanks! I needed that level of granularity as well and your answer saved me!

**Comment by sgoehler** [comment]
I would like to bump this feature request. It should be possible to just tap the distribution to get a more detailed view. Reasons are the same as original post: We need to be able to understand when we can make cuts for certain iOS versions. I see that there's now the possibility to make an API call, but I feel this is too much for a feature that should be easily accessible via the web UI.
Thanks for your consideration!

**Comment by datwelk** [comment]
Bump. This needs to be within the App Center web UI. No export should be needed.
