### ISSUE TITLE
Android Distribute keeps opening browser after data storage clear

### ISSUE THREAD

**Issue by philemonmerlet** [microsoft/appcenter#1058]
Sometimes, to perform tests or to spot problems, we have to clear application storage.
With AppCenter Distribute enabled, after Data storage is cleared, it is impossible to use the app. The browser keeps opening to the AppCenter enable install page every time we try to access it.

**Comment by jwargo** [comment]
@philemonmerlet an interesting issue. I'm trying to think through what's going on here. I'm curious as to why clearing app storage opens the install window. What did our support team tell you? 

If this is a feature request, what's the feature you're requesting?

**Comment by philemonmerlet** [comment]
Hello, I think it is more an issue than a feature request. 
Sorry I forgot to ask the AppCenter support, I went directly to the github. If you think it will help I can try this first.

**Comment by botatoes** [comment]
Hi there, please open a support ticket on appcenter.ms and our CSS team will escalate if necessary.
