### ISSUE TITLE
Seeing upload time as well as date, on devices

### ISSUE THREAD

**Issue by GamingRay** [microsoft/appcenter#1064]
Would like to see the time the build was uploaded to App Center, not only the date.
We often upload more than one build per day and it would help a lot to see the upload time.
Thanks

![Image from iOS](https://user-images.githubusercontent.com/50926842/65357381-e98e4980-dbc4-11e9-8a4f-435ccdb6fb32.jpg)

**Comment by t-miomok** [comment]
@GamingRay Thank you for this feedback, I'll share this with the Service Owner.

**Comment by ryang1428** [comment]
+100! We switched to AppCenter last week from Hockey and this is the first thing our QA team was asking about

**Comment by NicholasMaher** [comment]
+1 for this, this is very helpful when working in a continuous integration environment

**Comment by lumaxis** [comment]
Thanks for the interest everyone, I just merged a Pull Request that will add the timestamp on this page and it should become available later today 😊

**Comment by lumaxis** [comment]
This is now live! Thanks y'all for the suggestion 👍🏼
