### ISSUE TITLE
Hard to gather statistics on crashes vs total sessions

### ISSUE THREAD

**Issue by stevedavis7** [microsoft/appcenter#1065]
In Hockey App it was easy to compare the total number of crashes and sessions for a particular version and timeframe.
In App Center every time I switch between Diagnostics and Analytics it resets the version and  and time selections which makes it extremely painful to gather the statistic that we're looking at which is % of sessions that end in a crash (crashes/sessions * 100)

**Comment by baileybrooks** [comment]
Hi Steve, thanks for this feedback. I've added the service area owners to the issue and we will keep you updated.

**Comment by ryang1428** [comment]
I added a similar feature request! Its a very basic piece of data from crash reporters that's unfortunately missing here! https://github.com/microsoft/appcenter/issues/218
