### ISSUE TITLE
How does one fetch the sample-document in an app?

### ISSUE THREAD

**Issue by TomSoderling** [microsoft/appcenter#1066]
**Describe the solution you'd like**
When I create a new database under the Data node, the Data explorer shows that there is one sample document in the db. Since it's public, I'd like to fetch it from my app using the Data SDK to make sure that the app to App Center connection is working - before I go through the steps of setting up an AD tenant and the other more complicated Auth setup. I wish there were instructions in the getting started guide or anywhere else on how to do this.

**Describe alternatives you've considered**
Using the document ID and partition, I've tried to do this several ways and haven't been able to figure it out. I just get one of these two exceptions each time: 

> Microsoft.AppCenter.Data.DataException: Unexpected error while talking to CosmosDB

> Microsoft.AppCenter.Data.DataException: Error while retrieving cached token, aborting operation: The token store returned 400

Some examples of what I've tried:
```
var result = await Data.ListAsync<object>(DefaultPartitions.AppDocuments);
var result = await Data.ListAsync<string>(DefaultPartitions.AppDocuments);

var result = await Data.ReadAsync<object>("sample-document", DefaultPartitions.AppDocuments);
var result = await Data.ReadAsync<object>("sample-document", "readonly"); 
var result = await Data.ReadAsync<string>("sample-document", DefaultPartitions.AppDocuments);
```
**Additional context**
<img width="1068" alt="sample-document" src="https://user-images.githubusercontent.com/18268845/65377516-c621d800-dc72-11e9-90e0-c423821094be.png">

I'm just starting out using the Data feature, so I'm not very experienced with the Data SDK yet.

**Comment by Zakeelm** [comment]
Hey there! 

I'll look into making this much more clear in the documentation. Can you try creating an object that has a field "message" that is of type sting. Then when calling your read or list command, using that as the type  within your call rather than object or string.  I believe this may be the issue, let me know if this works!

**Comment by TomSoderling** [comment]
This ended up working for me
`var doc = await Data.ReadAsync<object>("sample-document", DefaultPartitions.AppDocuments);`

Would be cool if that was in the Data docs somewhere to validate that things are set up before diving into all the Auth setup steps.

**Comment by Zakeelm** [comment]
Glad this was resolved. That's a great idea. I'll add this information to the docs. Definitely the best way to validate things are all set up. Thanks for the feedback, i'm going to get that added and close this issue!

**Comment by TomSoderling** [comment]
Thanks!!
