### ISSUE TITLE
Hide missing symbol warning for certain (system) frameworks

### ISSUE THREAD

**Issue by renfeisong** [microsoft/appcenter#1068]
**Describe the solution you'd like**
In the Diagnostics section, the "Symbols are missing for multiple versions." warning always show up for me. After clicking into the details, it shows a list of system frameworks (e.g. AppKit, Foundation, CoreFoundation) that are missing symbols. These are non-issues and I don't think there is a way to get symbols for these frameworks. For this reason, I think they should be hidden and not generate an alert.

**Describe alternatives you've considered**
It might be hard to define what is considered "system framework" and to get a list for all the platforms. A more flexible solution would be to allow the users to define a list of frameworks for which they don't want to be alerted for missing symbols.

**Additional context**

See screenshow below:

<img width="584" alt="Screen Shot 2019-09-23 at 12 01 18 AM" src="https://user-images.githubusercontent.com/4545784/65406730-480a2200-dd95-11e9-9945-01fcf3f24c36.png">

**Comment by matthiaswenz** [comment]
Hi there, sorry for the long delay in follow up - in general we do filter out system binaries from requiring symbols or rather try to provide these symbols ourselves in App Center.
If this is not happening for your app, it would be best if you can file a support request through the App Center portal for that. This way we can look into the details for your app and see why it isn't working in your case.
