### ISSUE TITLE
API for accessing crash report before sending

### ISSUE THREAD

**Issue by hydrixos** [microsoft/appcenter#1069]
Crash reports might contain personal data of the user: Exception messages might contain log output of the app. We also add additional logs from the app's session as an attachment to the crash.

We think that the user should be completely informed which information is sent together with a crash report. 

In our app, we show the user a dialog asking for consent before sending a crash report (alongside with a comment and contact information). It would be great if we could offer a "Show Details" button that reveals the full crash report to the user, so the user can feel comfortable about the level of private information shared with the developers.

To implement this, the mac/iOS SDK of App Center needs an API providing access to a human-readable version of the unsymbolicated crash report. It should contain all information sent to the server – including assertion messages, crash metadata and stack traces.

Thanks!

**Comment by winnieli1** [comment]
Hi @hydrixos thanks for feature request! I can definitely see this being helpful for privacy conscious users. We don't have immediate plans to support this feature but let's keep this issue open to track interest.
