### ISSUE TITLE
AppCenter support 

### ISSUE THREAD

**Issue by nishaatr** [microsoft/appcenter#1070]
Its regrettable that I have to raise this here.

I have been struggling to get WebHook working with our JIRA on-premise instance and so raised support query via chat. After some initial response, there is no feedback or help for past week or so. 

WebHook test fails but then after ~10mins we get the ticket created in JIRA. We have added many AppCenter/HockeyApp IP addresses/domain names to our firewall but its not helping. Last week I realized AppCenter is using TLS 1.3 but our JIRA only supports upto 1.2

So I looking for further assistance on this. If we can check logging/tracing on AppCenter side that will be great and then we can take it from there.

PS: when I use curl externally the ticket is created immediately without problems. So either issue is with IP addresses, or TLS or WbeHook itself.

Please assist?

**Comment by baileybrooks** [comment]
@nishaatr Hi Nishaat, I apologize for that delay in support! Looks like our support team has now responded to your query via chat – will now close this issue. Please continue the conversation there for further assistance.
