### ISSUE TITLE
Support articles never load in the support chat

### ISSUE THREAD

**Issue by onethread** [microsoft/appcenter#1071]
**Describe the solution you'd like**
While in the support chat box, when I search for a solution or am offered one and I click on it, I'd like for the article to load. Instead the loading bar never completed, indefinitely.

**Describe alternatives you've considered**
Search the Microsoft appcenter support site directly instead.

**Additional context**
Safari 13.0.1
The console is returning these errors:

```
[Error] Unrecognized Content-Security-Policy directive 'worker-src'.

[Error] Refused to load https://intercom-sheets.com/sheets_proxy because it does not appear in the child-src directive of the Content Security Policy.
```

**Comment by blparr** [comment]
Hi @onethread ! Thanks for reporting. The team has been notified and we will be fixing this shortly.

**Comment by RamonPage** [comment]
@onethread Hi! We've made some changes and hopefully that fixed your issue. Could you please try again?

**Comment by onethread** [comment]
It works! Thanks!
