### ISSUE TITLE
Automatic resigning and provisioning doesn't work for iOS

### ISSUE THREAD

**Issue by onethread** [microsoft/appcenter#1072]
**Describe the solution you'd like**
Per the documentation, I use the the same provisioning profile that Xcode uses, which is set to automatic management. 
When a new user is invited, re-signing never works. 

The "Register devices" step succeeds, the "Update provisioning profile" succeeds, but the Re-sign app & upload new release" step fails with the error: `Profile named 'iOS Team Provisioning Profile: com.fill-in-bundle-id-here' was not found in the account.`

I am an admin with the associated Apple developer account if that matters. 

**Describe alternatives you've considered**
TestFlight. Being cheeky, but this is fairly make or break it for us. Appcenter's been nice so far, but I can't be manually provisioning testers all the time. 

**Additional context**

**Comment by phillipleblanc** [comment]
@onethread Thanks for reaching out! This is an expected error when using the Xcode "Automatically manage signing" option. You will need to switch to using "Manually manage signing" for the App Center Automatic resigning to work properly.

https://docs.microsoft.com/en-us/appcenter/distribution/auto-provisioning#prerequisites

> Prerequisites
Use Manually manage signing instead of Automatically manage signing when distributing the app from Xcode.

**Comment by onethread** [comment]
Hi @phillipleblanc, thanks for the quick response. After looking over the prerequisites, I wanted to try every permutation of settings that I could think of, but I still can't seem to get it to work, so you might need to walk me through it.

I've done the following: 
1. Generated an Apple Distribution provisioning profile with only 1 device allowed
2. Generated a distribution signing certificate
3. Downloaded said distribution certificate and installed it to my local machine
3. Disable "Automatically manage signing" in Xcode for my pertinent schema
4. Set the Provisioning Profile in Xcode for my pertinent schema to the one created in 1. The signing certificate is automatically selected and set to the one in step 2 as expected
5. Go to the build settings in App Center.
6. Verify the pertinent schema is still selected
7. Upload the provisioning profile created in step 1. 
8. Generate a p12 using Keychain against the Distribution signing cert from Step 2 and my private key. 
9. Upload the p12 file and enter the needed password.
10. Kick off a build
11. Go to AppCenter > Distribute > Groups > pertinent group > Devices
12. Appcenter correctly notifies that several devices are unprovisioned. 
13. Click on Register Devices > Re-sign my app > Register
14. Results:  
Step 1: Register Devices succeeds. 
Step 2: Update provisioning profile succeeds. 
Step 3: Re-sign app and upload new release fails. "One or more profiles does not contain the provided certificate."

**Comment by phillipleblanc** [comment]
@onethread - Did you upload the certificate you generated in step 1 when performing the Register Devices step? That error message means the certificate we tried to use for resigning did not match the certificate originally used to build the app - so most likely you are seeing that issue. If you are continuing to see issues, please contact us via the support chat so we can further debug your issue.

**Comment by onethread** [comment]
@phillipleblanc Yes, that was step 8 (although it should say "Upload the provisioning profile created in step 3.")

**Comment by jpeg-ms** [comment]
@onethread I'm following up from the other side of the chat bubble.

**Comment by jpeg-ms** [comment]
It appears the certificate used by @onethread was one of the new "Apple Distribution" certificates introduced for Xcode 11. Somehow those were not supported, but we are rolling out a quick fix for this. Closing this issue now. I will follow-up more in the support chat.

**Comment by onethread** [comment]
Confirmed that the fix now works. Thanks all!

**Comment by phu-tang-tiki** [comment]
hmm I'm seeing the same problem. How can we fix it?

**Comment by SuperCorks** [comment]
I'm still having this issue. Could we have an update on this ticket?

**Comment by vqt123** [comment]
same issue, i guess microsoft doesn't think iOS development isn't worth their time?

**Comment by jp-andre** [comment]
You might want to open a new issue to get some attention, some folks in this thread are not involved in this project anymore.
