### ISSUE TITLE
Would Be Nice to Have a "Cancel Build" Feature here

### ISSUE THREAD

**Issue by bobber205** [microsoft/appcenter#1073]
![image](https://user-images.githubusercontent.com/5841107/65450890-fb553400-ddf2-11e9-8b81-851c67c1577b.png)
On the commits screen for a branch it'd be nice to cancel builds here instead of having to click into each commit. Sometimes I'll make several small commits and they will each build up in the queue.

A quick easy way to cancel would be great! <3

**Comment by nrajpurkar** [comment]
Hey @bobber205, thanks for the request! This sounds similar to the other issue you opened at #1039. Can we close this a duplicate and track this feature request there?

**Comment by bobber205** [comment]
Yeah sure I'll close it. I forgot I had opened this already!
