### ISSUE TITLE
HockeyApp for MacOS Upload App

### ISSUE THREAD

**Issue by ehlersd** [microsoft/appcenter#1074]
**Describe the solution you'd like**
Will existing app continue to work after moving apps to AppCenter?

**Describe alternatives you've considered**
New AppCenter for Mac App?

**Additional context**
N/A

**Comment by Zakeelm** [comment]
Yes! Existing apps will continue to work after moving apps to App Center. Our goal is to provide a seamless pipeline and transition from HockeyApp to App Center! 

Hope this helps, going to close this issue.

**Comment by JuliusSkrisa** [comment]
I am afraid your goal was not achieved, since the HockeyApp upload app for MacOS stopped working and the upload is stuck on "Doing preflight check..." :(

**Comment by ehlersd** [comment]
Yeah, noticed it also.  I’m currently looking into AppCenter alternatives that have an easier path to upload builds...

**Comment by ehlersd** [comment]
@Zakeelm any chance there’s plans to fix this?

**Comment by traderhut** [comment]
If you don't have a solution, seems you need to 'unclose' this issue
