### ISSUE TITLE
iCloudContainerEnvironment': expected one of {Development, Production},

### ISSUE THREAD

**Issue by indraneely** [microsoft/appcenter#1075]
What App Center service does this affect?
iOS Project Build

Describe the bug
Build failed by
Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided}

To Reproduce
Each time building

Expected behavior
Build success

**Comment by Zakeelm** [comment]
Hey there! 

For this bug, I would recommend going to the App Center portal and using the blue bubble on the bottom right of the page for support. This will connect you with an engineer who will be able to do a deep dive into the issues you're having! 
Going to close this issue here.
