### ISSUE TITLE
Can't Configure Build React Native with gitlab on premise 

### ISSUE THREAD

**Issue by plamworapot** [microsoft/appcenter#1078]
When i connect React Native project with gitlab on premise and configure build it shown error 

> We couldn't find any React-Native Android project in your branch

**Additional context**

***Request Log***

```
{
	"correlation_id":"XXXXXXXX",
	"error":"badgateway: failed after 10s: context canceled",
	"level":"error",
	"method":"GET",
	"msg":"error",
	"time":"XXXXXXXX",
	"uri":"/api/v4/projects/XXX/repository/tree?per_page=100\u0026page=4\u0026ref=XXXXXXXXXXXXXXXXXX\u0026recursive=true"
}

{	"correlation_id":"XXXXXXXX",
	"duration_ms":9983,
	"host":"git.mycompany.com",
	"level":"info",
	"method":"GET",
	"msg":"access",
	"proto":"HTTP/1.1",
	"referrer":"",
	"remote_addr":"XXX.XXX.XXX.XXX:X",
	"remote_ip":"XXX.XXX.XXX.XXX:X",
	"status":502,
	"system":"http",
	"time":"XXXXXXXX",
	"uri":"/api/v4/projects/XXX/repository/tree?per_page=100\u0026page=4\u0026ref=XXXXXXXXXXXXXXXXXX\u0026recursive=true",
	"user_agent":"",
	"written_bytes":24
}


```

***screenshot***

<img width="1224" alt="Screen Shot 2562-09-24 at 19 07 17" src="https://user-images.githubusercontent.com/4770354/65510459-2f1d8000-deff-11e9-8fbf-2b07917626e8.png">

<img width="821" alt="Screen Shot 2562-09-24 at 19 09 13" src="https://user-images.githubusercontent.com/4770354/65510458-2f1d8000-deff-11e9-801a-e461ea38949c.png">

<img width="821" alt="Screen Shot 2562-09-24 at 19 09 23" src="https://user-images.githubusercontent.com/4770354/65510457-2e84e980-deff-11e9-96fc-834a022bd336.png">

**Comment by nrajpurkar** [comment]
Hi @plamworapot, can you reach out to App Center support via the bubble in the bottom-right hand corner about this please? This will allow us to dig in a bit deeper to understand what's going on here. Thanks!
