### ISSUE TITLE
React-Native Android build fails. Cannot find CLI tools?

### ISSUE THREAD

**Issue by safaiyeh** [microsoft/appcenter#1079]
`> Could not read script '/Users/vsts/agent/2.155.1/work/1/s/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.`

Consistently getting this error on App Center. node_modules should correctly install `@react-native-community/cli-platform-android`. I cannot reproduce this locally as yarn installs the package correctly. However consistently fails on App Center

**Comment by safaiyeh** [comment]
Platform was set to Kotlin/Java instead of React Native.

**Comment by JulioOrellana** [comment]
I am having this issue, my plaform is already on React Native, but it can't find `font.gradle`

`Could not read script '/Users/runner/runners/2.161.1/work/1/s/node_modules/react-native-vector-icons/fonts.gradle' as it does not exist.`

`node_modules/react-native-vector-icons/fonts.gradle` really exists
