### ISSUE TITLE
Issue when building Flutter Android App with different main entry point

### ISSUE THREAD

**Issue by Stereopie** [microsoft/appcenter#1080]
I'm currently building a Flutter application through App Center build which works fine when I have a main.dart file in my lib directory, however when trying to use a different entry point for my dev and production builds (main_dev.dart and main_prod.dart) the gradle script fails. Building the APK itself works fine as I can set the target in the build script itself depending on which build I want, however the automated script gives me the below error. 

![Screen Shot 2019-09-24 at 3 06 24 pm](https://user-images.githubusercontent.com/9936459/65556445-059e3c00-df73-11e9-840c-57f7558adbb2.png)

Is there any way to change the gradle parameters or potential workarounds?

**Comment by nrajpurkar** [comment]
Hi @Stereopie, we don't officially support Flutter today, so I don't have a ton of guidance to share here. Tapping in @ranterle who may have more insight on the gradle parameters.

**Comment by ranterle** [comment]
Hi @Stereopie - as Nilofer mentioned we don't officially support Flutter today - in any case, tracking our main feature request #67 for this will be good.

With regards to the step that is failing: If there is any pre-flighting you can do this would work through one of our [build scripts](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/) - i.e. correct any paths or configure environment variables. I don't know too many details on how the file is looked up during build time - can you provide an example of what kind of different inputs you would like for the Gradle command?

**Comment by immortal-88** [comment]
any update on this?

**Comment by Holofox** [comment]
@Stereopie, @immortal-88 it's easy to get around with aliases:

**main.dart**
```dart
Future<void> main({Environment environment = dev}) async {
  WidgetsFlutterBinding.ensureInitialized();
  await configureInjection(environment);
  runApp(App(environment: environment));
}
```

**main_dev.dart**
```dart
import 'main.dart' as common;

Future<void> main() => common.main();
```

**main_prod.dart**
```dart
import 'main.dart' as common;

Future<void> main() => common.main(environment: prod);
```
