### ISSUE TITLE
I am getting the error “Unable to determine the simulator version for (UDID of mobile) in IOS Automation using C# “

### ISSUE THREAD

**Issue by vishnuprakash9845** [microsoft/appcenter#1081]
I am getting the error “Unable to determine the simulator version for (UDID of mobile) “
Steps Followed
        
1-Added the ENABLE_TEST_CLOUD code in AppDelegate.cs and added the iOS project reference to the UI Tests
2-Selected the IOS Project à Debug|iPhoneSimulator à iPhone 11 iOS 13.0
3-Tried to debug the tests
4-At the line return ConfigureApp.iOS.DeviceIdentifier(“UDID”).AppBundle(“Path of .app”).StartApp(); getting the above mentioned error.
 
Can you help me to solve the above problem, i am facing this problem and not able to resolve from past 30 days. Any help will be appreciated. Thank you.

**Comment by Oddj0b** [comment]
Hi @vishnuprakash9845, what version of Visual Studio are you using and what is the version of your Nuget package?

**Comment by vishnuprakash9845** [comment]
Sorry for the Late reply,
Visual Studio Version: Enterprise 2019 version 16.0.3
Xamarin nuget package: Xamarin.UITest.3.0.3

**Comment by Oddj0b** [comment]
@vishnuprakash9845 sometimes it helps to replace `ENABLE_TEST_CLOUD` with `DEBUG`.

**Comment by vishnuprakash9845** [comment]
> @vishnuprakash9845 sometimes it helps to replace `ENABLE_TEST_CLOUD` with `DEBUG`.

OK thank you.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
