### ISSUE TITLE
Carthage Support Build Error

### ISSUE THREAD

**Issue by nickfrollo** [microsoft/appcenter#1082]
I have integrated the new Carthage support in 2.4.0 and am getting a build error:

`Undefined symbol: ___llvm_profile_runtime`

I can work around this by enabling "Gather test coverage" in the Test Scheme but it would be preferable to not have to enable this for all targets. Can this be resolved?

Thanks

**Comment by nrajpurkar** [comment]
@nickfrollo can you reach out via App Center support in the bottom-right hand corner please? We'll be able to troubleshoot the issue better there. Thanks!

**Comment by nickfrollo** [comment]
Hey,

This isn't a support issue, just reporting an issue with how the static libraries are compiled when using via Carthage. You can fix this in the AppCenter SDK by not generating code coverage in the static libraries. This will resolve the above compile error and workaround.

Examples (where I found the workaround too):
https://github.com/erikdoe/ocmock/issues/349#issuecomment-366320480
https://github.com/aws-amplify/aws-sdk-ios/issues/833

**Comment by nickfrollo** [comment]
Sorry I listed this under the wrong project. Moved here- https://github.com/microsoft/appcenter-sdk-apple/issues/1794
