### ISSUE TITLE
iOS project with cyrilic workspace unable to build

### ISSUE THREAD

**Issue by ivanbogomoloff** [microsoft/appcenter#1083]
Hello,

I have iOS project with cyrilic workspace name and when i try to connect it project with bitbucket repo -> Configure build -> I get message "We couldn’t find any iOS Objective-C/Swift projects in your branch." 

But if i rename workspace to english everything is ok. 

I propose to supplement the documentation for this case, or detect cyrilic symbols in project assocated files and show full description about this case instead of "We couldn’t find any iOS Objective-C/Swift projects in your branch" 

Thank you.

**Comment by nrajpurkar** [comment]
Thanks for pointing this out @ivanbogomoloff. It does look like this is a current limitation. We are going to take a further look into this. I'll update the issue when I have more details.

**Comment by DennisPan** [comment]
@ivanbogomoloff Could you reach out to support from App Center portal about this? We likely need more details, as I wasn't able to reproduce it.

**Comment by ivanbogomoloff** [comment]
I will be able to do in the next 2 weeks

> @ivanbogomoloff Could you reach out to support from App Center portal about this? We likely need more details, as I wasn't able to reproduce it.

I will be able to do in the next 2 weeks with sample ios project

**Comment by DennisPan** [comment]
@ivanbogomoloff Did you get a chance to look at this? No rush. Just checking.

**Comment by ivanbogomoloff** [comment]
i will try now

**Comment by stephan-markovic** [comment]
Xcode 11.1 which is deprecated as of Nov 5, 2020.
