### ISSUE TITLE
Search/Filter on install.appcenter.com

### ISSUE THREAD

**Issue by punksta** [microsoft/appcenter#1086]
**Describe the solution you'd like**
Currently apps on https://install.appcenter.ms/apps are sorted alphabetically. I would like to have search/filter 
1. by app name
2. by package name/bundle id

**Describe alternatives you've considered**
I haven't considered alternatives

**Additional context**
In the company I work for, we have more than 30 applications, and it’s very inconvenient to scroll every time you need to find some application.

**Comment by baileybrooks** [comment]
Hello Stanislav, our design team is currently working on this feature. Thanks for your feedback and you should see updates as we make progress on this!

**Comment by punksta** [comment]
cool! thanks

**Comment by ffittschen** [comment]
Hi @bailey, what is the progress with this feature request? As far as I can see it is still not possible to search/filter apps or more importantly builds within apps, or am I missing something?

**Comment by FranzBusch** [comment]
@Bailey We are currently looking at migrating from Fabric to MS AppCenter and one of our crucial workflow features is having a full text search for builds. Our testers are finding the correct builds to test by searching for ticket numbers in the release notes. Would be really great to have that.
