### ISSUE TITLE
Indie-level Test Plan & Pricing

### ISSUE THREAD

**Issue by TomSoderling** [microsoft/appcenter#1088]
**Describe the solution you'd like**

I really want to leverage Test Cloud for my app development, but as an indie shop $100/mo for 30hrs of device time is 1.) way too expensive, 2.) way more hours than I would ever need.

Instead, give me a plan that's right-sized. I would jump all over a plan that was $10/mo and gave me 3hrs of device time. Others I've talked to would love a plan that was $50/mo for 15hrs of device time.

You'll be able to get more developers into using App Center Test and have a better chance of retaining that revenue each month as they get hooked. It's an awesome feature - open it up a bit!

**Describe alternatives you've considered**
The alternative (what I do) is to run all my UI tests locally on spare devices that I have. I'm also working towards setting up my own device lab. Both alternatives keep developers from using the test services in App Center.

**Additional context**
I resisted the urge to put a meme photo here

**Comment by Oddj0b** [comment]
@TomSoderling Thank you for the great feature request. I actually can't provide any insights into how the 30 hours limit originally was determined. I will investigate the history of it and see if it makes sense.

Missing meme photo minus two points 🤣
