### ISSUE TITLE
Users on beta distribution lists should not be required to create App Center accounts

### ISSUE THREAD

**Issue by tinrocket** [Microsoft/appcenter#109]
I am migrating my Mac beta app from Hockey App to App Center:

Previously, Hockey App allowed users to be on a beta distribution list, and download beta builds, *without* requiring them to create a Hockey App account. This made it easy to recruit beta testers for my app.

However, App Center requires users on a beta distribution list to create Microsoft/App Center accounts. This raises the diffuculty bar in recruiting users to for semi-public/private beta testing becuase it forces users (who are volunteering their time to beta test my app) to now create accounts.

There is the option to create a public download link, but this is not secure because it can be shared with users outside the ditribution list. Alternatively, continue to use Hockey App until it's EOL.

**Comment by derpixeldan** [comment]
@tinrocket thanks for bringing this up. We're aware and have "allow to download releases from public distribution groups without authentication" on our list.

**Comment by derpixeldan** [comment]
@tinrocket just to be sure I understand you correctly. On HockeyApp there's a private and a public page. The private one can be accessed by users of the app only and the public one by anyone who has the link. Despite the authentication for the public links on App Center, everything works the same.

**Comment by derpixeldan** [comment]
@tinrocket public distribution groups are also available without authentication now. Would that resolve your issue?

**Comment by tinrocket** [comment]
@derpixeldan Thank you; I will take a look tonight. I have not been able to follow up on your earlier questions yet.

(Yes, a support member (Alex E.) did mentioned that it was on your todo list, and suggested making a user-request.)

**Comment by tinrocket** [comment]
@derpixeldan Yes, I think public distribution groups is working solution for my current situation. I did the following:

1. I enabled the public link option in a distribution group
2. I sent a reminder to a tester in the group (who had not registered) to download the last release
3. They were able to access the build without logging in.

Is this what you mean by public distribution groups?

**Comment by derpixeldan** [comment]
@tinrocket great! Yes, that's exactly what I meant. I'm closing the ticket, feel free to re-open when you have additional questions on that topic.
