### ISSUE TITLE
App Center Auth: Support for Sign In with Apple

### ISSUE THREAD

**Issue by TomSoderling** [microsoft/appcenter#1091]
**Describe the solution you'd like**
Seeing [this](https://docs.microsoft.com/en-us/samples/xamarin/ios-samples/ios13-addingthesigninwithappleflowtoyourapp/?WT.mc_id=docsmsft-twitter) sparked an idea of being able to use Sign In with Apple as one of the identity providers in Azure B2C and support for it in the App Center Auth SDK. 

**Additional context**
<img width="909" alt="Screen Shot 2019-09-25 at 1 19 47 PM" src="https://user-images.githubusercontent.com/18268845/65628682-92f38780-df97-11e9-9334-ea14daee1bd5.png">

**Comment by Zakeelm** [comment]
Hi! 

I believe B2C now supports sign in with Apple: https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-apple . There are some directions on setting this up on that link. I've also assigned this to the Auth PM on the App Center team, who may have more insight on this.

**Comment by TomSoderling** [comment]
Very cool! Thanks - would be interested on @amchew's thoughts

**Comment by lumaxis** [comment]
I believe it's already possible to use Sign In with Apple by using a custom OpenID Connect provider, see this guide from the Azure B2C folks: https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-apple

**Comment by amchew** [comment]
Hey @tomsoderling, thanks for reaching out! The Azure Active Directory B2C (AAD B2C) team currently has a feature to have the Sign in with Apple as an Identity Provider on their roadmap, but there's no ETA yet.

Today you can still implement Sign in with Apple with AAD B2C. You do that by selecting "+ New OpenID Connect Provider" in the screenshot below. Sign in with Apple implements the basics of OpenID Connect, and you can configure it as an OpenID Connect identity provider in Azure AD B2C. 

To configure Azure AD B2C to use Sign in with Apple, you’ll need to have an Apple Developer account, set up your application in the Apple Developer portal, and collect some configuration values. As Apple’s implementation of the authentication protocol is somewhat incomplete, there are some steps which deviate from a typical OpenID Connect identity provider configuration process.

Learn more in the:
- [GitHub guide](https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-apple) on how to obtain the appropriate OpenID Connect configuration values from the Apple Developer portal and for instructions on how to integrate Azure AD B2C with Sign in with Apple.
- [AAD B2C's blog post on Sign in with Apple](https://techcommunity.microsoft.com/t5/Azure-Active-Directory-Identity/Azure-AD-Mailbag-Use-Azure-Active-Directory-B2C-to-enable-Sign/ba-p/566489)
- [App Center's article on how to Sign in with Apple](https://intercom.help/appcenter/en/articles/3369241-sign-in-with-apple-with-azure-ad-b2c)

![image](https://user-images.githubusercontent.com/33160470/65696881-dfd66d00-e02e-11e9-8d60-0056bb145952.png)

**Comment by TomSoderling** [comment]
Okay, cool. Thanks for the info!

**Comment by amchew** [comment]
Np! Will keep this ticket open for a month  to track interest. Feel free to give a thumbs up or comment.

**Comment by amchew** [comment]
Hi all! I’ll be closing this ticket for now, please re-open or comment if you’ve any other questions. Thank you for the feedback!
