### ISSUE TITLE
GitHub repo address changed yesterday can't reset - build broken!

### ISSUE THREAD

**Issue by dgobaud** [microsoft/appcenter#1095]
I filed a support ticket support is being very slow and unhelpful. Build is broken since yesterday! Randomly for 1 of my apps I had to reconnect GitHub now the GitHub repo link points to an old address from like a year ago! Don't know how to change it don't want to lose my build config Please help! Build won't work.

**Comment by DennisPan** [comment]
@dgobaud I found your support conversation. Will reach out there and take a look
