### ISSUE TITLE
Add support for Android 10 & iOS 13

### ISSUE THREAD

**Issue by eman1986** [microsoft/appcenter#1096]
**Describe the solution you'd like**
Recently Visual Studio just updated to support both Android 10 & iOS 13, but it seems like that hasn't bubbled up to app center just yet.

**Describe alternatives you've considered**
My only alternative is to not set my code to build for those new version just yet.

**Additional context**
Seeing that Visual Studios has already published a release that supports them, it'd make sense that App center would be pretty close behind.

**Comment by nrajpurkar** [comment]
Hi @eman1986, to clarify is this for building Xamarin apps or something else?

**Comment by eman1986** [comment]
sorry, yes it is for Xamarin.

**Comment by nrajpurkar** [comment]
We are working on support for latest stable Xamarin versions at the moment! It's been added to our iteration plan at #970

**Comment by eman1986** [comment]
That's great to hear :smile:

**Comment by nrajpurkar** [comment]
We've enabled support for latest Xamarin versions! You can update your configurations to use these versions now 😄
