### ISSUE TITLE
Android SDK Include Custom Session Info with Crashes

### ISSUE THREAD

**Issue by Drenet** [microsoft/appcenter#1097]
**Describe the solution you'd like**
Please add/allow the ability to include custom information of the doomed session with Crash Reports. The existing getErrorAttachments() is not invoked until the subsequent launch, at which time relevant cache/memory information is no longer available. HockeyApp SDK included getDescription() within its CrashManagerListener which could easily be used for this purpose. 

**Describe alternatives you've considered**
There does not appear to be any public/available functionality within the Android SDK available to replicate the previous behavior.

**Comment by Zakeelm** [comment]
Hey there! 

I've assigned this thread to the product owner of Diagnostics on our team for visibility. She'll take a look at this and investigate accordingly

**Comment by liszto** [comment]
At the same time don't hesitate to support this : 

```
/// <summary>
/// Collect all header fields for the custom exception report.
/// </summary>
/// <returns>A list which contains the header fields for a log file.</returns>
protected virtual List<string> GetLogHeaders ()
```

It was present in HockeyApp and it seems not present in AppCenter ? :p
