### ISSUE TITLE
Bug: Refreshing on the analytics tab, reverts to all versions

### ISSUE THREAD

**Issue by stevedavis7** [microsoft/appcenter#1098]
-In App Center select Analytics
-Select a particular version and see the stats
-Now refresh the browser
Bug: the version popup still says the version that you selected but the data is incorrect. The data is for all versions

**Comment by blparr** [comment]
Thanks for your bug report - I'll notify the team and we will fix as soon as we can.

**Comment by yoannchaudet** [comment]
The fix should be live in production already :)
