### ISSUE TITLE
Add custom property when application crashed

### ISSUE THREAD

**Issue by OmidID** [microsoft/appcenter#1099]
For some reason, it's good to have extra information when the application is crashing, As an example logged in username or Id.

I can see custom property exists when we want to send exception trace but this is not the case when the application is crashing. It's good to have some default set property at initializing time then we can see the value of property all the times in any crashes.

I can see something similar exists in other platforms 
https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=unity

**Comment by Zakeelm** [comment]
Hi there! 

I can definitely see why this would help when application crashes. I'm going to add the product owners of our Diagnostics service to that they can look into this further.

**Comment by sdobart** [comment]
Seconding this, I would always like to include some default information with the error report anytime my application crashes.

**Comment by winnie** [comment]
Hey there! We support attaching custom data to crash reports with [User ID](https://docs.microsoft.com/en-us/appcenter/diagnostics/features#user-identification) or via [attachments](https://docs.microsoft.com/en-us/appcenter/diagnostics/features#attachments). Do these features address your needs?

Unfortunately, [key value pairs (custom properties)](https://docs.microsoft.com/en-us/appcenter/diagnostics/features#key-value-pairs) are only supported for handled exceptions at this time.

**Comment by sdobart** [comment]
For my use case (enterprise related) we are looking to track a crash to a specific user/device. I am using the crash attachment functionality to upload the mobile application database with user/device identifiers in it, but in order to link the crash to a user, I have to download the database for a given crash, open it and find/compare the unique information inside. Often times a user will indicate they experienced a crash at a certain spot or time in the application, and we want to find the associated crash report in AppCenter to attempt to triage. This process would be much quicker if properties could be associated to individual crash reports. An enhancement on top of that would be the ability to query for property values on individual crashes.

**Comment by OmidID** [comment]
Any update here?

**Comment by OmidID** [comment]
So, Any update?

**Comment by OmidID** [comment]
Any update here? :)

**Comment by odiazpaycor** [comment]
Nothing yet on this?

**Comment by OmidID** [comment]
Any update?

**Comment by AnastasiaKubova** [comment]
Hi there! Unfortunately, there is no ETA for this feature at this moment, but we are keeping an eye on this thread.
See more info in our [Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap).

**Comment by DmitriyKirakosyan** [comment]
Hi @OmidID , Have you tried setting [User ID](https://docs.microsoft.com/en-us/appcenter/diagnostics/features#user-identification) using the [setUserId API](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#identify-users)?

**Comment by MichaelLHerman** [comment]
Why doesn't crash reporting automatically include and report key-value pairs included in the Exception.Data dictionary?  I shouldn't have to  log my crash as an error as well to be able to record additional data? 

https://docs.microsoft.com/en-us/dotnet/api/system.exception.data

**Comment by DmitriyKirakosyan** [comment]
Hi @MichaelLHerman , this looks like a separate feature request, which was reported here https://github.com/microsoft/appcenter-sdk-dotnet/issues/1546.
As an alternative, you can use attachments to send the data from Exception.Data.

**Comment by ElijahRomer** [comment]
This needs to be added!
