### ISSUE TITLE
Create initial designs for new identity service

### ISSUE THREAD

**Issue by patniko** [microsoft/appcenter#11]
After many requests to better integrate identity into the existing services we've made the decision to begin work on a new identity service to let you get up and running in a matter of minutes. We'll be sharing mockups and design specifications asap while we start laying the foundation.

**Comment by fileman** [comment]
The Azure B2C "under the covers" should be accessible from application outside AppCenter.

**Comment by patniko** [comment]
@fileman The b2c resource will be in your own subscription and available for use in other apps. You will have the option of using the App Center SDK's to ease onboarding for supported platforms or using the standard MSAL packages for other platforms like web that we don't currently support in App Center today.

**Comment by amchew** [comment]
Closing this issue; App Center Auth was shipped in public preview on May 7, and you can l[earn more about Auth](https://devblogs.microsoft.com/appcenter/introducing-visual-studio-app-center-auth/)!
