### ISSUE TITLE
IPA processing failed in Xcode 11

### ISSUE THREAD

**Issue by abhilashkgowda** [microsoft/appcenter#1101]
Assertion failed: Expected 4 archs in otool output:
/var/folders/y8/x7dbsn8d23vcyzyknl7ljjl00000gn/T/IDEDistributionOptionThinning.~~~95y04K/Payload/MAA DEV.app/Frameworks/HaloMem.framework/HaloMem:
Mach header

**Comment by Zakeelm** [comment]
Hey there! 

I'm assuming this is a bug you're getting. If that's the case, I recommend using the blue button the bottom right of our portal, which will start a thread with our support team!

**Comment by Oddj0b** [comment]
Hi @abhilashkgowda, I'm assuming you got help from our support team because we haven't back from you. If you don't respond the ticket will be closed, and everything is dandy.

**Comment by Darren-chenchen** [comment]
https://www.darrenblog.cn/#/detail/5dbf9a8a7bb725236692b6d4
