### ISSUE TITLE
Diagnostics Dashboard

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#1103]
Hi,

It will be great if you add a diagnostics dashboard which will be the home page for the Diagnostics options where developer can decide what to show

For example, most of the times, Errors are not as critical as crashes so developer might decide to show only diagnostics list and the crashes chart (without the Affected users chart) and only for Open cases.

Thanks,
Jassim

**Comment by blparr** [comment]
Thanks for your feature request! We will take it into consideration for future improvements.

**Comment by bo3po** [comment]
I would like this also
