### ISSUE TITLE
Build errors on Android for React Native 0.60.5 

### ISSUE THREAD

**Issue by baldursson** [microsoft/appcenter#1104]
I can't get my Android app to build on App Center after upgrading to React Native 0.60.5. I always get the same error:

> Task :ReactAndroid:buildReactNdkLib FAILED
Android NDK: ERROR:/Users/vsts/agent/2.155.1/work/1/s/node_modules/react-native/ReactAndroid/src/main/jni/first-party/hermes/Android.mk:hermes: LOCAL_SRC_FILES points to a missing file

This task always succeeds when building the app for release on my local computer and when looking intro it, it seams like App Center I calling the `Android.mk` file from the wrong directory. When building locally it is executed from the `build` directory which has the files that `LOCAL_SRC_FILES` is pointing to (it is a path relative to the directory of the script).

Has anyone succeeded in building React 0.60.5, or any React Native version > 0.59 on App Center for Android? On iOS it works just fine.

I don't even have Hermes enabled, so don't understand why it needs to be built in the first place.

**Comment by blparr** [comment]
Hello @baldursson! Have you tried contacting customer support (blue chat button in the App Center portal)?

**Comment by baldursson** [comment]
@blparr I have now, thank you 😊

**Comment by veenavl** [comment]
@baldursson , is this issue resolved?
