### ISSUE TITLE
Issue when attempting to transition app from HockeyApp to AppCenter

### ISSUE THREAD

**Issue by bencmorrison** [microsoft/appcenter#1106]
I am attempting to move my organisation's applications to AppCenter. My account is listed in an owners group and is applied to all the applications we want to move to AppCenter. However when I attempt to transition the applications I am given a pop up that says I need to have an own of an application move the application to AppCenter. We don't have a direct owner as we have had the organisation set as the owner of the applications. Is there something that I am missing? I haven't seen anything in the docs or FAQ that can help me here.

**Comment by derpixeldan** [comment]
@bencmorrison can you please reach out to us in support and mention this issue. Let us know which organization you're talking about and we'll look into it.

**Comment by bencmorrison** [comment]
I was unable to find out the correct way to reach out to support. I was only able to find the knowledge bases, would you be able to point me in the direction of contacting support?

**Comment by dipree** [comment]
@bencmorrison apologize, this one slipped through the cracks. I assume you've figured it out in the meantime? In case not, in App Center there's a blue button on the lower right corner which lets you contact us.
