### ISSUE TITLE
There's no way to set an annotation via the API without also setting the error group state

### ISSUE THREAD

**Issue by dalemyers** [microsoft/appcenter#1108]
**Describe the solution you'd like**
When sending a PATCH to `/errors/errorGroups/{errorGroupId}`, the `state` property should be optional. Otherwise, you need to know what state the group should be in order to set an annotation.

**Describe alternatives you've considered**
You can read the state and then set it, but this has 2 problems:

1) It requires an additional API call
2) It has inherent race conditions as the state may change in between calls

**Comment by blparr** [comment]
Thanks for sharing that. We will be taking it into consideration for future improvements.

**Comment by dalemyers** [comment]
Commenting to keep this open.

**Comment by dalemyers** [comment]
Commenting to keep this open.

**Comment by dalemyers** [comment]
This bug is still an issue.

**Comment by dalemyers** [comment]
Still an issue.

**Comment by dalemyers** [comment]
Still an issue.

**Comment by dalemyers** [comment]
Still an issue.
