### ISSUE TITLE
Provide a crash and bug reporting SDK

### ISSUE THREAD

**Issue by JanabiSoft** [microsoft/appcenter#1109]
**Describe the solution you'd like**
Provide a crash and bug reporting SDK similar to for e.g. Instabug.

**Describe alternatives you've considered**
Instabug.

**Comment by blparr** [comment]
Hello @JanabiSoft , we already provide crashes and errors reporting SDKs. I'm not sure what you are referring to, could you elaborate?

Thanks!

**Comment by JanabiSoft** [comment]
Hello @blparr I mean a mechanism for users to fill a form to report a bug or give a feedback about the app similar to instabug.com or buglife.com offering.
Regards

**Comment by blparr** [comment]
I see - unfortunately, we are not planning to offer a functionality to provide feedback in App Center.

**Comment by sathukorale** [comment]
I think you are looking for the feature request #412. Please drop a like there, this is a much needed feature.

**Comment by JanabiSoft** [comment]
@sathukorale Yes you are right I didn't catch it earlier thanks for directing me, I will definitely drop a like
