### ISSUE TITLE
Configurable Granularity of Reports Graph

### ISSUE THREAD

**Issue by daryl-fontaine-iugo** [microsoft/appcenter#111]
Currently, the Reports graph (and Affected Users graph) has a fixed daily granularity. In cases where issues cluster around specific times of day, it would be useful to see the trend over a finer granularity such as hourly or even minutely.

Ideally you could click into the Reports graph which would allow better insight into the data, with control over the time window as well as the granularity.

![reports](https://user-images.githubusercontent.com/1820523/53456134-fdcce800-39e1-11e9-83b7-3ce752e48ca7.png)

**Comment by winnieli1208** [comment]
Thanks for the feature request. This isn't on our immediate roadmap but I can definitely see the value in this. For now, you can use our [crash free device API](https://openapi.appcenter.ms/#/errors/Errors_ErrorFreeDevicePercentages) and [crashes per day API ](https://openapi.appcenter.ms/#/errors/Errors_CountsPerDay)to get the granular data that's not show in the graphs. I know this isn't exactly what you're looking for but I hope that helps a bit!

**Comment by baolongnt** [comment]
This is something we are looking for also. The system we use today provides this feature.
