### ISSUE TITLE
Option to Send Screenshot of time of Application Crash

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter#1110]
**Describe the solution you'd like**
Take a screenshot at the time of Application Crash to provide extra insight into what the user was doing at the time of the crash. I see you can add these at the time of of sending the error report, but I don't see any place to actually take the screenshot to then add to the error report on restarting the application?

**Describe alternatives you've considered**
Alternatives are to do it ourselves, we are replacing our current crash handling with yours. Ours at present tries to take a screenshot on hitting the unhandled exception. This is optional as the screenshot may contain sensitive data, so the user has to confirm this.

**Additional context**
This is currently for our WPF application, as it has a little more going on at the same time.

**Comment by blparr** [comment]
Hello, thanks for your question - my colleague @winnieli1 will help you with this.

**Comment by james1301** [comment]
Is there any further feedback of implementing this feature?
