### ISSUE TITLE
Ability to configure columns in Release history

### ISSUE THREAD

**Issue by dzmitrykavalchuk** [microsoft/appcenter#1113]
Hey Guys,

Our team is building a significant number of builds each day, having different versions. Currently it's really difficult to understand which version this or that build is, cause version name cannot fully fit the with of column. 
https://drive.google.com/open?id=0B8aY6IzbQ01oamJRQVJyQnF2WXRLVGdXUUlXV25fUG5ITmdJ

Is that possible to
a) make the set up of columns configurable
b) add ability to configure the width of the columns

Best Regards,

Dzmitry Kavalchuk
EPAM systems

**Comment by blparr** [comment]
Thanks for your feature request! We will take it into consideration when planning next set of improvements.
