### ISSUE TITLE
Add Filter to Main User-Focused Page

### ISSUE THREAD

**Issue by StarTether** [microsoft/appcenter#1115]
**Describe the solution you'd like**
When viewing the AppCenter (HockeyApp) app on my phone, I would like to have a filter in the upper-right for filtering down the apps shown in the list. For example, I keep forgetting that "Teams" is actually "Microsoft Teams" and navigating to it is a pain on my phone, especially with so many insider apps shown. 

**Describe alternatives you've considered**
The current alternative is to just scroll through to the different apps I need to consider.
Another alternative is the ability to "favorite" the different apps I am interested in (i.e. any I have downloaded to my machine) so that I don't have to scan through all apps to get what I need. This might even be a better approach: the first time I download an app automatically "favorite" it and present me a filtered view by default and make it clear how to get back to the full list.

**Additional context**
![Screenshot_20190930-155317](https://user-images.githubusercontent.com/8376906/65919896-78a01c00-e392-11e9-8c9f-2b61fd0a2273.png)

**Comment by tjsomasundaram** [comment]
Thank you for adding this feature request! I will take this back to the team so we can review the feature and add it to the appropriate backlog.
