### ISSUE TITLE
Android App Cancel Download

### ISSUE THREAD

**Issue by MSFTjarredM** [microsoft/appcenter#1116]
**Describe the solution you'd like**
End users need the ability to cancel downloads from the Android notification when they attempt to download a Hockey App/App Center Beta program.  Without the ability to cancel the download, it will stay on your phone (potentially for hours) until you get back on dependable WIFI. 

**Describe alternatives you've considered**
Alternatives would be similar to the way the Google Play Store works - anytime during the download, there is the opportunity from the Store to stop downloading, or to uninstall.  It would appear that the status is asynchronously updated as the download happens.

**Comment by tjsomasundaram** [comment]
Thank you for creating this feature request! This is great input, I will take this back to the team for review.
