### ISSUE TITLE
User and Custom Property information in Analytic and Diagnostics

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter#1117]
**Describe the solution you'd like**
User information in Analytic and Diagnostics. So you can filter by custom properties and user. We might set custom properties for the Client (as we are B2B).

**Describe alternatives you've considered**
N/A

**Additional context**
Finding out which client is getting the errors allows us to get in touch and investigate as they have their own infrastructure.

**Comment by tjsomasundaram** [comment]
Thank you for creating this feature request! Your input is valuable to us, and I will take this feature back to the team to be reviewed.

**Comment by james1301** [comment]
Has a review taken place on this?
