### ISSUE TITLE
Add capability to pass arguments to XCode from package.json instead of using magical behavior for react-native

### ISSUE THREAD

**Issue by mcarlson** [microsoft/appcenter#112]
Right now, we use appcenter to build and test our react-native applications. There is some magic that forces 'legacy compiler mode' for react-native, which is required if we want to build using XCode 10 like we do on developer's machines. Unfortunately, this appcenter magic doesn't work when package.json contains a nonstandard react-native build, in our case it's a pointer to a fork that has some important fixes for stability...

Because of this we are stuck on XCode 9 with appcenter which keeps causing issues because it's inconsistent with our developer machines where we actually build, test and distribute our apps. It seems like every time I add a new podfile I run into an incompatibility issue with XCode 9 that only crops up once appcenter does a build and I'm getting quite frustrated...

I've been around and around this issue with your support team, they suggested a post-clone script to 'hardcode @0.56.0 then run npm install github:Outpatient/react-native#0.56.0_uiviewmanager_patch in a pre-build script, which will run after yarn/npm install.'  We don’t run appcenter post-clone scripts on our local builds so I’d have to run them on our dev machines. This would introduces complexity to the workflow because there would be local changes to the package.json which make commits less clean and error-prone.

All we really need to do is set the 'UseModernBuildSystem = NO' flag in XCode. I can see underlying command https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops supports passing arguments to XCode under the advanced section so this should be fairly easy to to, at least conceptually. It seems like having the ability to pass arguments into the build system via a config section in package.json is way more powerful than relying on a magical value in the dependencies section… It’s much more clear what’s going on and more reliable - and you’d end up with a feature that everyone building iOS apps could use, not just react-native developers.

Do you think you could make this work? I don’t want to break our workflow just to support appcenter. Thanks so much!

**Comment by lklepner** [comment]
We have been forcing legacy compiler mode on our RN app by setting 

```
<dict>
	<key>BuildSystemType</key>
	<string>Original</string>
</dict>
```
in 
`ios/[AppProject].xcworkspace/xcshareddata/WorkspaceSettings.xcsettings`

Perhaps you could use a post-clone script to insert this setting?

This said .. it does seem like it would be useful if we could configure artbitrary xcode flags in App Center Build jobs.

**Comment by mcarlson** [comment]
@lklepner Thanks for the tip, we have that set already so we can build on our dev machines using XCode 10. Unfortunately the command-line xcodebuild being called by https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops doesn't seem to respect that... It's tough for us because we need to keep Appcenter back on XCode 9 which doesn't match our dev or deployment environments. More and more podfiles seem to be shipping with bitcode only available for XCode 10 - most recently crashlytics, see https://stackoverflow.com/questions/51128462/vsts-build-generation-throwing-invalid-bitcode-version-error so this is a critical problem for us. We really need to be able to use XCode 10 in Appcenter!

**Comment by ChimeraScorn** [comment]
Why do we need to keep Appcenter back on XCode 9?

**Comment by mcarlson** [comment]
@ChimeraScorn I have to keep Appcenter on XCode 9 because appcenter doesn't support manually setting the 'UseModernBuildSystem = NO' flag in XCode 10 which is required for react-native. You already have a fix in place for this, but unfortunately that fix relies on matching the value of the react-native key in package.json... Shawn from appcenter support told me: 'Well our backend parses the package.json for 56 RN or greater than applies the legacy build system variable. I think because you have a special branch in there as well it's throwing it off.' 

To which I replied: 'All we really need to do is set this flag. I can see underlying command https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops supports passing arguments to XCode under the advanced section so this should be fairly easy to to, at least conceptually. It seems like having the ability to pass arguments into the build system via a config section in package.json is way more powerful than relying on a magical value in the dependencies section… It’s much more clear what’s going on and more reliable - and you’d end up with a feature that everyone building iOS apps could use, not just react-native developers.'

Do you think you can make this happen for me? It's 100% a better fix and way more useful in the long run... Thanks!

**Comment by mcarlson** [comment]
@ChimeraScorn I have to keep Appcenter on XCode 9 because appcenter doesn't support manually setting the 'UseModernBuildSystem = NO' flag in XCode 10 which is required for react-native. You already have a fix in place for this, but unfortunately that fix relies on matching the value of the react-native key in package.json... Shawn from appcenter support told me: 'Well our backend parses the package.json for 56 RN or greater than applies the legacy build system variable. I think because you have a special branch in there as well it's throwing it off.' 

To which I replied: 'All we really need to do is set this flag. I can see underlying command https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops supports passing arguments to XCode under the advanced section so this should be fairly easy to to, at least conceptually. It seems like having the ability to pass arguments into the build system via a config section in package.json is way more powerful than relying on a magical value in the dependencies section… It’s much more clear what’s going on and more reliable - and you’d end up with a feature that everyone building iOS apps could use, not just react-native developers.'

Do you think you can make this happen for me? It's 100% a better fix and way more useful in the long run... Thanks!

**Comment by mcarlson** [comment]
Any updates on this one?

**Comment by naoey** [comment]
I'm actually having the opposite problem, the fact that AppCenter forcibly sets `UseModernBuildSystem = NO` which overrides any workspace settings. With React Native 59 the framework is migrating towards using the new build system because of which my app currently cannot be built on AppCenter. I don't believe it should be too hard to set this flag as a build setting with the default value being `NO`?

**Comment by mcarlson** [comment]
It seems like this feature is vital for us on a legacy react-native and it still won't be usable when we migrate to the latest version which we plan to do in an upcoming release. @ChimeraScorn @lklepner any updates on this?

**Comment by barryelevatyr** [comment]
I am having the same issue as @naoey.  AppCenter currently forces "UseModernBuildSystem = NO" as a command line parameter when XCode 10.x is chosen.  XCode 10 build support still has some lingering issues from what I've read but its been supported since RN 0.58.x and I've been successfully building on development machines since then using the new build system.

Since fixing the limitation of not being able to use the new build system is different (but related) to what is asked for in this issue, I've created https://github.com/Microsoft/appcenter/issues/364 which is specific to supporting new new build system.

@mcarlson - If I'm understanding your situation correctly, if you change to 10.x, `UseModernBuildSystem = NO` will be passed automatically for you on command line (you don't even have a choice currently).  Possibly I'm misunderstanding your scenario?

**Comment by mcarlson** [comment]
@barryelevatyr That's correct, but we are moving to 0.59 and there's the opposite issue there. Basically, the fact that there's no way for us to set UseModernBuildSystem to the appropriate value is a huge problem for react-native users. This issue proposes a way to fix that and generalize your system so any arbitrary XCode build flags (including this one) could be set which is a much more flexible and future-looking direction for you and your users...

**Comment by barryelevatyr** [comment]
@mcarlson - Agreed 100% that not having control over UseModernBuildSystem and it being forced on us is a major issue.  I see where you are going with the ability to pass additional build flags in as well, would be very helpful.  Hopefully we'll see exposed support for UseModernBuildSystem to be followed by additional build flags as well!
