### ISSUE TITLE
Syntax issues with Swagger API

### ISSUE THREAD

**Issue by littlefyr** [microsoft/appcenter#1120]
I'm trying to use the Azure AutoRest tool to create a Powershell module for the App Center api and I've found a number of issues with the swagger JSON, and fixed them:

- The version is `preview` which is not a valid SemVer value. changing it to `0.0.0+preview` fixes it
- `Schema 'CrashGroupChangeStatus' is declared with invalid type 'undefined'`
- `Schema 'CrashGroupStatusEnum' is declared with invalid type 'undefined'`
- `Schema 'TeamUserResponseRole' is declared with invalid type 'undefined'`
- `Schema 'GetReleaseStatusResponseReleaseUrl' is declared with invalid type 'undefined'`
- `Schema 'V2MissingSymbolCrashGroupStatusEnum' is declared with invalid type 'undefined'`
 - `Schema 'V2SymbolStatusEnum' is declared with invalid type 'undefined'` 

Adding `"type": "string"` in all the right spots solve the problems. 

AutoRest is also reporting a lot of warnings like `The schema 'schemas:1158' with a undefined type and using allOf is a bit ambigious. This has been auto-corrected to 'type:object'` and `Schema with type:'string and 'format:'dateTime' is not recognized.`

Its worth noting that running on my MacBook Pro, it takes between 4.5 and 5 hours to process the swagger JSON when there are no fatal errors

**Comment by tjsomasundaram** [comment]
Thank you for the feedback and noting the details of the issues above! I will take this back to the team so we can address these and any other issues we find in the Swagger API.

**Comment by BRB2000** [comment]
I can add to this, that I am unable to create an API client using VisualStudio's add service reference feature, which is using NSwag. It seems to have a problem with the name attribute being "name": "$inlinecount" for example. But that is actually not the only thing that is going wrong there. NSwag is done with the client code generation in 30 seconds, but the client has all sorts of errors, so maybe there are other problems when handling such a large specification.

Reproducing the issue should be fairly simple. Just try to create a client as mentioned above. I am using Visual Studio 2019 16.3.2, which is using NSwag.ApiDescription.Client 13.1.2.
