### ISSUE TITLE
Build fails to find the jetifier package for React Native if node_modules is not in the root folder 

### ISSUE THREAD

**Issue by kierangmst** [microsoft/appcenter#1124]
**Describe the solution you'd like**
Have the jetifier package installed on the build machines and executed from there, instead of the current project's node modules.

**Describe alternatives you've considered**
1. Use the directory of the project json as the location for node_modules
2. Search for the jetifier package within the project.

**Additional context**
Our mobile project is not in the root folder. As a result, the jetifier step on appcenter fails to find the jetifier package:
Warning: node_modules/jetifier/bin/jetify does not exist source code will not be upgraded to AndroidX

This is despite the fact that the jetifier package is included in the packages for the project. It was also not clear that the jetifier package needed to be included until we started seeing the build failures on appcentre as its not needed locally.  As a workaround, I've added a pre-build script to call jetifier at the correct location for our project
'node $APPCENTER_SOURCE_DIRECTORY/Mobile/node_modules/jetifier/bin/jetify'

**Comment by DennisPan** [comment]
Thanks for reporting this! The intention was to use the package.json directory, but we have a bug. Working on the fix.

**Comment by DennisPan** [comment]
@kierangmst Could you re-save your branch configuration and try again?

**Comment by kierangmst** [comment]
@DennisPan I did as you requested, and I removed our custom Jetifier action. The build worked perfectly. Thanks for the quick turnaround.
