### ISSUE TITLE
Ability to Upload Windows zip folder to AppCenter

### ISSUE THREAD

**Issue by mkhalid195** [microsoft/appcenter#1127]
Hi,

Our Team creates daily builds for Windows platform and upload them to hockeyapp. It was a 2 step upload procedure where we use to create a version and then upload the zip in that version through APIs. This is no longer supported on appcenter. When our team upload zip file manually on appcenter we get the following error: 
" version couldnot be created from build". 
We also tried through CLI and mentioned the bundle version but get the followiing error: 
"Error: release binary file uploading failed: HTTP 422 Unprocessable Entity"

It would be great to if Appcenter can support Windows zip file so we can distribute the app similar to iOS and Android 

Thanks

**Comment by tjsomasundaram** [comment]
Sorry to hear you are having issues. I will take this back to the team to see if we have a process that may work for you.

**Comment by AstroViking** [comment]
We have the same issue and would be very thankful if this could be resolved in the future.

**Comment by winnieli1** [comment]
Hi! Thanks for submitting an issue. Are you building an UWP apps? 

We currently support releasing .zip files for WPF and WinForms applications and are adding the same support for UWP and Windows Unity in the upcoming weeks. I'll post here with updates!

**Comment by kpatwa** [comment]
@mkhalid195  - I had same issue. In HockeyApp to App Center transition all WPF/Windows app had transitioned to app center as UWP app which is why I was getting " version couldnot be created from build" error. I requested App Center team to update my app from UWP to WPF. After that I was able to upload zip file. Please check project setting in app center project.

**Comment by AstroViking** [comment]
@winnieli1

What about standalone Windows EXE files (created by Unity)?

**Comment by winnieli1** [comment]
Hi all - we just added support for releasing .zip files for UWP apps. You'll need to specify the build version manually in the release flow. Thanks for the patience!

**Comment by vladlibrestream** [comment]
I think you forgot to update the App Center distribute extension for the Azure build pipeline. Since I wasn't able to upload .zip file due to the error of the  ```missing required params from body: build_version```
