### ISSUE TITLE
Allow .NET Core 3.0 Single File Executables when uploading a new release

### ISSUE THREAD

**Issue by rummelsworth** [microsoft/appcenter#1128]
**Describe the solution you'd like**
I want to be able to upload a .NET Core 3.0 SFE (which is a .exe file) as a new release of my app.

**Describe alternatives you've considered**
I could zip the exe, but that's kind of silly for an SFE. Especially for my user, who gets to manually extract the SFE so it can then self-extract...

**Additional context**
None.

**Comment by tjsomasundaram** [comment]
Thank you for the feature request. I will take this item back to the team for further review.

**Comment by NLI-KelbyHunt** [comment]
Similar to the request in #242 - I mention that I use self-contained EXE's provided by .NET Core 3.0 - I still zip these self-contained EXE's with 7Zip self-extracting EXE to save ~40% in size due to better compression.

**Comment by adirh3** [comment]
@tjsomasundaram 
Any update on this? This is relevant to Inno Setup as well as single files, it confused some end users to download a ZIP with an EXE file within it.
Thanks!
