### ISSUE TITLE
Create a new or configure an existing AD B2C directory in App Center

### ISSUE THREAD

**Issue by amchew** [Microsoft/appcenter#113]
[Identity MVP Technical Specification](https://github.com/Microsoft/appcenter/blob/master/specs/2019-02/Identity/Identity-Spec.md)

Following up on #11, we are working on allowing app developers to:
1. Easily set up an Identity service (by configuring a new AD B2C directory)
2. Connect to an existing AD B2C directory 

Let us know if you have any feedback, or would like to be a part of our private preview!

Here are some designs:

1. Set up an Identity service
![image](https://user-images.githubusercontent.com/33160470/53460411-e990e700-39f1-11e9-931c-ee67d000a9ee.png)

2. Connect to an existing AD B2C directory 
![image](https://user-images.githubusercontent.com/33160470/53460425-f1508b80-39f1-11e9-8119-e013a2eb153b.png)

**Comment by nickrandolph** [comment]
@amchew is there a Swagger document for the proposed apis associated with this?

**Comment by amchew** [comment]
Hey @nickrandolph! Not yet. We are in the process of developing this, and the APIs are private for now. We plan to launch this under Preview in a couple of months, and will make the APIs public then. 

We're looking for users to test our service under private preview, and share feedback. Let me know if you'd be keen!

**Comment by nickrandolph** [comment]
absolutely - sign me up for all the preview bits and I can provide feedback

**Comment by amchew** [comment]
:) We have a call scheduled on Mon 3/25, and will get your details then. Thank you @nickrandolph!
