### ISSUE TITLE
Find users quickly in large tester groups

### ISSUE THREAD

**Issue by pbearstare** [microsoft/appcenter#1130]
**Describe the solution you'd like**
The list of testers to be sortable by clicking on the column header
A search box at the top of the list that starts filtering names as soon as you start typing

**Describe alternatives you've considered**

**Additional context**
We regularly use tester groups of 100+ names and it becomes very challenging to know if someone is or isn't included when testers are added in chronological order
Note - this was a key limitation in hockeyapp and one of our biggest pain points

**Comment by tjsomasundaram** [comment]
Thank you for sharing your feedback! I will take this request to the team for review.

**Comment by Bloophub** [comment]
yes needed too
