### ISSUE TITLE
Upload CSV or other text files to populate a distribution group

### ISSUE THREAD

**Issue by pbearstare** [microsoft/appcenter#1131]
**Describe the solution you'd like**
When creating a distribution group, we should have the option to upload a CSV or other text file containing email addresses to populate the group with testers

**Describe alternatives you've considered**

**Additional context**
This feature was present on HockeyApp

**Comment by tjsomasundaram** [comment]
Thank you for your feedback. I am a PM on the App Center team, and will ensure that your request is reviewed.
