### ISSUE TITLE
I get internal error

### ISSUE THREAD

**Issue by zek** [microsoft/appcenter#1133]
##[error]{"code":"internal_server_error","message":"internal error (Support ID: 508f52b0-2762-4d7e-9569-745e11475979)"}

**Comment by tjsomasundaram** [comment]
Hi! Sorry to hear you are having issues. Could you please provide some additional detail to when you are getting the error, and perhaps a screenshot? Thank you!

**Comment by zek** [comment]
We have solved the issue with live support.
Problem occurs when building for iOS apps. If product names (output) contains any turkish-letter, appcenter fails to find generated app file. Therefore it gives internal error. We need unicode support or some internal check to warn the user.
