### ISSUE TITLE
Display update Download progress alert for non-mandatory updates as well

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter#1135]
**Describe the solution you'd like**
On Android, while distributing a mandatory update via the the AppCenter Android SDK, an in-app progress dialog is shown.
While distributing a non-mandatory update, this dialog is not shown. Only the Android OS Download manager notification is visible in the notification drawer.

It's likely to be this condition:
https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L757

I am not sure to understand why we wouldn't show the in-app download progress alert for non-mandatory updates, it would be a bit more user friendly. Or at least have the control on showing or not this alert.

**Describe alternatives you've considered**
N/A apart from HockeyApp.

**Comment by tjsomasundaram** [comment]
Hi. Thank you for bringing this feature up. I will get the right team assigned to take a look at the request.
