### ISSUE TITLE
Preprocessor directives fail on AppCenter iOS builds

### ISSUE THREAD

**Issue by krudraiah** [microsoft/appcenter#1136]
We have pre-processor directive in our code as below and we have defined configurations that define these directive. no matter what configuration we chose, the build from app center always resorts to #else clause. This code works fine with builds made straight from visual studio

#if MOCK_EXCEPT_SYNC

    public class DependencyRegistrar : IDependencyRegistrar
    {
        public DependencyRegistrar()
        {
        }
    }

#endif

----Project properties
```
 <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='MockExceptSync|AnyCPU'">
    <DefineConstants>DEBUG;TRACE;MOCK_EXCEPT_SYNC;NETSTANDARD;NETSTANDARD2_0</DefineConstants>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <NoWarn />
  </PropertyGroup>
```

**Comment by tjsomasundaram** [comment]
Hi, sorry to hear of the issue you are facing. I am a PM on App Center, and I'll get the right team to take a look at this issue!

**Comment by AngelGarcia13** [comment]
Any news on this?

**Comment by krudraiah** [comment]
In my case the preprocessor directive was duplicated across other build configurations in the project file and missing on some. All I had to do was to edit the project file and add them to configurations where it was missing. We can also remove them from all configurations and just leave it on default config
