### ISSUE TITLE
Add method to check manually for new updates

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter#1137]
**Describe the solution you'd like**
The Distribute Android SDK relies on the host Activity lifecycle to start the update check process.
This is fine in most scenario, but if we want to initialize AppCenter Distribute manually later on (after `onResume`) it is causing issues.

I have written a ReactNative wrapper for AppCenter Distribute so I can start the library from the ReactNative layer.
But by the time the wrapper is ready and initializes `Distribute`, the `Activity` already went through the `onStart`/`onResume` calls so the update check is not triggered.

So the user would have to send the app to the background and foreground to trigger the `onResume` call and so the update check process.

Having a method to trigger the check of updates, out of the lifecycle of the Activity would fix this issue.

**Describe alternatives you've considered**
~It looks like we can enforce the update process to kick in by disabling and enabling `Distribute` manually by doing the following:~

~`Distribute.setEnable(false).get()` and then `Distribute.setEnable(true).get()`~
- https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L347
- https://github.com/microsoft/appcenter-sdk-android/blob/aef71abd8164d769eba6408f2a53fcee45fa07cb/sdk/appcenter/src/main/java/com/microsoft/appcenter/AbstractAppCenterService.java#L97
I have tried the above and it doesn't work :/

An alternative is to call the following:

```java
// Edit: Do not use
Distribute.getInstance()
		  .onActivityResumed(this.reactContext.getCurrentActivity());
```
This works but is obviously a bit hacky...

Edit: Don't do this ⬆️  https://github.com/microsoft/appcenter/issues/1205#issuecomment-546318788

**Comment by tjsomasundaram** [comment]
Thanks for bringing up this feature! I will take this to the right team for review.

**Comment by Bishbulb** [comment]
@tjsomasundaram I'm trying to figure out how the app updates are supposed to be handled when we wire up `AppCenter.Start` in `Application.OnCreate`. From all the testing I've done, the in-app updates are never triggered, and I'm wondering if this is because it isn't properly wiring into the Activity.OnResume/OnPaused handlers.

I am happy to take control of this and manage my own updates (ie. check every 30 minutes), but I simply cannot see how this should be done with the existing API. I'm on Xamarin.Android, so I don't see an option to call Distribute.getInstance().onActivityResumed()...

Any input would be appreciated!

**Comment by tjsomasundaram** [comment]
Hi @Bishbulb, thank you for providing great details on what you are looking for. I took this to the Distribute team and they are looking to see the scope of the work involved. I am not aware of this feature being a part of their plans in the near future, but I can confirm with them.

**Comment by dimazaid** [comment]
Hello @Bishbulb and @fabiendem - Thanks for providing all the info. We don't have plans to make this scenario from the SDK in the near future. I'll keep you updated on this thread if anything changes!
