### ISSUE TITLE
Ability to sort builds by date

### ISSUE THREAD

**Issue by SergeySorokinPM** [microsoft/appcenter#1138]
**Describe the solution you'd like**
I want to have opportunity to sort builds by going to https://install.appcenter.ms/apps/YourApplication
Right now it's only sorted by build code
It can be like link "Sort by Date/Code" (where to choose how you want to sort builds)

Also i see the same issue by numbers #404  and #307 , that was created in April - May - so i just want to raise this issue once again.

**Comment by tjsomasundaram** [comment]
Thank you for bringing up this feature request! I will take this back to the team for review.

**Comment by guidorubin** [comment]
Any update on this?

**Comment by nrajpurkar** [comment]
@guidorubin no update to share at the moment.

**Comment by mattg95** [comment]
This isn't completed. It seems very odd appCenter doesn't have such a simple feature
