### ISSUE TITLE
Ability to give direct link

### ISSUE THREAD

**Issue by SergeySorokinPM** [microsoft/appcenter#1139]
**Describe the solution you'd like**
Previously on HockeyApp you can choose any build by link. For example you have 1000 build for 5 years - you pick 7th build from 5 years ago - pick weblink - send it to your device, and just install it from this direct link. (android or ios it does not matter - of course i exclude moment with ios provisions, 5 years it's just the example)

In AppCenter this is only possible if i "Distribute" this build again - this looks fine, but still not the same and not so comfortable like it was with direct links.

So is it possible to make direct links for each build?

I saw one issue that mostly looks like mine - #141 and it does not have any answers.

**Comment by tjsomasundaram** [comment]
Thanks for bringing up this feature request. I will have the right team review the request.
