### ISSUE TITLE
De-emphasize non-Open crashes.

### ISSUE THREAD

**Issue by BioTurboNick** [microsoft/appcenter#1142]
**Describe the solution you'd like**
Visually de-emphasize non-Open crashes in the Diagnostics/Issues interface. Medium gray for Closed and Light gray for Ignored? Something like that. Make it easy to scan the list for the ones you need to worry about.

**Describe alternatives you've considered**
Sticky filters settings, separate groups.

**Additional context**
This may go along with #854 and #258 or be an alternative to them. Sticky filters would be very helpful anyway, but even when the filters are off, being able to pick out the open crashes more easily would be helpful.

**Comment by amchew** [comment]
Thanks @BioTurboNick for sharing your user scenario! Getting @winnieli1 to take a look
