### ISSUE TITLE
Detox appcenter-post-build.sh script fails to install applesimutils

### ISSUE THREAD

**Issue by aldrinc** [microsoft/appcenter#1146]
The example appcenter post-build script for detox fails to install applesimutils since the repo location has been updated.

**Old**
```
curl https://raw.githubusercontent.com/wix/homebrew-brew/master/AppleSimulatorUtils-0.5.22.tar.gz -o applesimutils.tar.gz 
```

**Updated**

```
curl -L https://github.com/wix/AppleSimulatorUtils/archive/0.7.2.tar.gz -o applesimutils.tar.gz
```

Line 21 in https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/detox/appcenter-post-build.sh

**Comment by patniko** [comment]
Updated - thanks!

**Comment by pacozaa-paloit** [comment]
@patniko @aldrinc I can't access to 
https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/detox/appcenter-post-build.sh 
I did some google and found this instead
https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/detox/appcenter-pre-build.sh
