### ISSUE TITLE
Make "Version" string of releases editable

### ISSUE THREAD

**Issue by jam-cmesquita** [microsoft/appcenter#1147]
### Description
As a developer,
with HockeyApp I could **change the "Version" string of my releases** so it is more readable for testers and other colleges in the company.

With the current state of AppCenter this is not possible. I think it can be beneficial and helpful for many people.

![image](https://user-images.githubusercontent.com/45820724/66377432-e0b5ba00-e9b1-11e9-807a-34211ad2bdc6.png)

### Suggestion
I would make it editable not only on the AppCenter website, but I would also enable that on the **Fastlane plugin** and as an **API end point**.

**Comment by derpixeldan** [comment]
Thanks for the request. We'll consider bringing that back.

**Comment by etacker** [comment]
This is also a feature that I used regularly in HockeyApp that would be very beneficial to have back.
