### ISSUE TITLE
Public distribution group urls are unsecure compared to HockeyApp

### ISSUE THREAD

**Issue by gmerinojimenez** [microsoft/appcenter#1148]
In our company, we use public distribution urls to publish alpha versions to clients and testers and we have projects for each of them.
The public distribution urls are based on the project id, which is a random alphanumeric:
https://rink.hockeyapp.net/apps/<project_id>/app_versions/67

But in AppCenter, public distribution groups are like this:
https://install.appcenter.ms/orgs/<organization_name>/apps/<project_name>/distribution_groups/<group_name>

So, it is quite easy to, given an organization name, try to guess another project names.

Our suggestion is to have public urls based on project id, instead of project name.

**Comment by derpixeldan** [comment]
@gmerinojimenez thanks for the feedback. The public download pages on HockeyApp aren't considered "secure" either, however, I see your point that at least the IDs are not guessable.

**Comment by gmerinojimenez** [comment]
Sure, I agree. If it is public, it will be unsecure, but considering that those urls are shared between a small group of people, for us having them obscured by the id is safe enough

**Comment by derpixeldan** [comment]
Referencing https://github.com/microsoft/appcenter/issues/1255

**Comment by gmerinojimenez** [comment]
I think this issue is still valid, are there any plans to take it into account?
