### ISSUE TITLE
user-settings-page extension for email-notifications 

### ISSUE THREAD

**Issue by nrettich** [microsoft/appcenter#1149]
In our company, we have got many Apps to manage with multiple builds and development distributions per day. It would be very helpful if any user could manage email-notification settings for all apps on a central/single page. 
Currently, we need to go to any app’s settings page and turn email-notifications on/off or entirely disable email-notifications for the user.

**Comment by derpixeldan** [comment]
Thanks for the request, how many apps are we talking about in your case, just to get an idea?

**Comment by nrettich** [comment]
we currently have got 150 Apps to care about
