### ISSUE TITLE
Insert a link node with a direct URL to Release Notes into Sparkle feeds

### ISSUE THREAD

**Issue by shpakovski** [microsoft/appcenter#1150]
**Describe the solution you'd like**

Releases for a Sparkle feed are provided by public distribution groups. Could you please insert an XML node `sparkle:releaseNotesLink` with a direct URL to Release Notes, so that customers could open a webpage in their browser?

**Additional context**

We discussed this in a [Sparkle Issue](https://github.com/microsoft/appcenter/issues/202#issuecomment-538632095). Thanks!

**Comment by derpixeldan** [comment]
Thanks for opening the separate request @shpakovski.
