### ISSUE TITLE
Ability to change LaunchTest for a UITest project in the solution

### ISSUE THREAD

**Issue by caiofbpa** [microsoft/appcenter#1154]
**Describe the solution you'd like**
I want to be able to Test the application built with my own suite of UITests that run on AppCenter.

**Describe alternatives you've considered**
A clear alternative is to make this happen in a post-build script, but then I would have to compile the app in Debug mode again and deal with installation of appcenter-cli and whatnot. It would be a much better experience if AppCenter supported this integration between Build and Test.

**Additional context**
What I imagined was a project selection just like the build one, but for selecting a project with UITests to be run. After that AppCenter makes sure the test project is built and run accordingly.

**Comment by Oddj0b** [comment]
@caiofbpa, thank you for making the request. Let's hope there's enough 👍 to make it happen.
