### ISSUE TITLE
Contact column for Mac crash reports isn't visible in App Center diagnostics

### ISSUE THREAD

**Issue by ksuther** [microsoft/appcenter#1156]
**Describe the solution you'd like**

App Center diagnostics doesn't show the contact column for Mac crash reports. We use this column to store the user's email so we can contact them to follow up on the crash.

**Describe alternatives you've considered**

We can use App Center's attachments API once we migrate to App Center, but we can't see this info from existing apps using the HockeyApp framework. Until this is added we need to keep using the HockeyApp UI to view this info, which prevents us from migrating the app to App Center.

**Additional context**

Screenshot of what the contact info looks like in HockeyApp:
![image](https://user-images.githubusercontent.com/106152/66422126-bb837480-e9ce-11e9-9c5f-361dfcf06c37.png)

**Comment by winnie** [comment]
Hey @ksuther - we recently added a column to display the user ID and to indicate if a report has an attachment. 

![image](https://user-images.githubusercontent.com/8868628/76965574-e7e6d980-68fa-11ea-9dc9-8840c961c94a.png)

Hope that helps!

**Comment by ksuther** [comment]
That shows the user name from HockeyApp but it doesn't show the email address. Is there a way to show both columns in the User ID so we still have the same data available?

**Comment by winnie** [comment]
App Center doesn't have the concept of contact and username but you can set the user ID field to whatever string you'd like including an email address: https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/macos#identify-users

**Comment by ksuther** [comment]
That helps for the future, thanks. The problem is that our existing releases using the HockeyApp SDK don't show the user's contact info. This means we're unable to contact users to provide them with additional information if they submit a crash report to us.
