### ISSUE TITLE
Testflight Production Store bug

### ISSUE THREAD

**Issue by gamsim** [microsoft/appcenter#1157]
**Describe the solution you'd like**
If a Testflight group called Production is created it should be treated as a Testflight group not an AppStore group.

**Describe alternatives you've considered**
Rename Testflight Production test group to SmokeTest.

**Additional context**
This bug caused our iOS app to go out live when it wasn't ready for Production release.

**Comment by Oddj0b** [comment]
@gamsim Thanks for reporting the issue, I'll see what we can do about it.
