### ISSUE TITLE
Expose Run ID via environmental variable

### ISSUE THREAD

**Issue by davidvavra** [microsoft/appcenter#1158]
We are generating PagerDuty incidents when test fail in App Center. We would like to automatically add a link to the failed run for easy debugging. But we have no way of knowing the test run id. It would be great if test run id can be exposed via environmental variable. 

This is what I mean by test run id:

`https://appcenter.ms/orgs/<organization>/apps/<app>/test/runs/<test-run-id>`

**Comment by Oddj0b** [comment]
Would this work with a webhook like it's proposed in #318
