### ISSUE TITLE
[IMPROVEMENT] Allow to see symbols uploaded

### ISSUE THREAD

**Issue by liszto** [microsoft/appcenter#1159]
Hello,
could you allow us to see the .dsym or breakpad or whatever file uploaded to symbolicate. 
Because currently when we upload the .dsym.zip archive through appcenter-cli there is no way to check if the upload has succeeded.

The issue is the same if we upload on the appcenter website. When the upload is done, we can't check all symbols uploaded.

thanks.

**Comment by winnieli1** [comment]
Thanks for the feature request! This is something we're aware of and looking to improve. I don't have an ETA but you can follow our roadmap and iteration plans to see what our team is working on.

**Comment by kirktay** [comment]
This is important for those of us with our CI on Prem and uploading everything to AppCenter.

**Comment by winnieli1** [comment]
Hi all - we recently added a tab in the UI that shows your uploaded symbol files. Hope that helps!

![image](https://user-images.githubusercontent.com/8868628/69273004-75543000-0b8c-11ea-86be-7f2219d463c1.png)

We also have plans to to improve the overall experience and make the status of symbol uploads more clear. Thanks for the feedback!
