### ISSUE TITLE
Ability for AppCenter to process .so files for NDK Crash symbolication like how it used to work in HockeyApp

### ISSUE THREAD

**Issue by Steve9215** [microsoft/appcenter#1160]
**Describe the solution you'd like**
Back in HockeyApp, we used to be able to upload a .zip file containing a libcopilot.so for each supported eabi, and HockeyApp would process the files and generate a symbol table to symbolicate NDK crashes.  This functionality is either lost or not working in AppCenter

**Describe alternatives you've considered**
We've tried following the instructions here to upload zip files, but they do not work as expected: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#reporting-ndk-crashes

**Comment by derpixeldan** [comment]
Thanks for bringing this up, we're aware of it and will consider doing it once the blockers tracked on our public roadmap are done.

**Comment by sarahyc** [comment]
> Thanks for bringing this up, we're aware of it and will consider doing it once the blockers tracked on our public roadmap are done.

Can you share what are blockers? We want to learn what are existing blocking issues.
Also pls consider treat this as high priority, this breaks our automation totally.

**Comment by winnieli1** [comment]
Hi @sarahyc - we added this feature to our iteration plan this month. Our team is actively working on this and we'll post here with updates. Thanks for the patience!

You can also find other blocking issues on our roadmap here: https://github.com/microsoft/appcenter/wiki/Roadmap

**Comment by winnieli1** [comment]
Hi all! We just enabled support for this. You can find the docs here: https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk#generate-a-zip-file-to-upload 

Give it a try and let me know if you run into any issues.

**Comment by Steve9215** [comment]
Hi @winnieli1 , 

I have followed the instructions and we uploaded a zip containing 4 native libraries yesterday, but it doesn't look like our symbols have been generated yet.  Our zip folder has the following format:

something.zip/arm64/libsomething.so
something.zip/armeabi-v7a/libsomething.so
something.zip/x86/libsomething.so
something.zip/x86_64/libsomething.so

Is this correct?  Or should we be using a different folder structure?

**Comment by cainejette** [comment]
Hi @Steve9215 ! Can you reach out to our support team via the blue chat icon within App Center, and we can dive more closely into your particular case to see what may be the issue? Thanks!

**Comment by Steve9215** [comment]
> 
> 
> Hi @Steve9215 ! Can you reach out to our support team via the blue chat icon within App Center, and we can dive more closely into your particular case to see what may be the issue? Thanks!

Done.  Sorry for the delay.  I look forward to hearing from a rep.
