### ISSUE TITLE
Ability to select a random device from TestCloud

### ISSUE THREAD

**Issue by caiofbpa** [microsoft/appcenter#1162]
**Describe the solution you'd like**
I would like to be able to get a random device from the farm, just like the LaunchTest does, but for my custom test run. If I could select which OS version, manufacturer or Tier, it would be perfect! I don't care too much about which specific device the tests will run on, and I don't like selecting one specific device and having to wait in line for the device to be available, so if I could get a random one that was available right away, it would be amazing!

**Describe alternatives you've considered**
There's no alternative that I know of, other than settle with selecting one device and hoping it's readily available every time.

**Additional context**
Appium supports this when you select some `DeviceCapability`, and the test server (AppCenter competitors) can choose whatever agent from the grid complies with that selection. Since I use Xamarin.UITest and I run the tests through `appcenter-cli`, I would like to have something like that too.

**Comment by Oddj0b** [comment]
@caiofbpa I've been thinking about this one for a while and I have some theories as to why you would want a random device. Is it because of the wait time you would like to select a random device?

**Comment by caiofbpa** [comment]
@Oddj0b exactly, I want to make sure the wait time is as close to 0 as possible. This would have the added benefit of testing "automatically" in a wide variety of devices, and this is desired in my point of view. Limiting the test-set to some devices (and always those same devices) seem... Limiting.

**Comment by LeroyStaines** [comment]
The ability to select _n_ number of random devices, based on a range of filters, would be ideal for selecting a random sample of say 100 devices.
