### ISSUE TITLE
Change the region on test devices

### ISSUE THREAD

**Issue by alatem** [microsoft/appcenter#1163]
<img width="1264" alt="Captura de Pantalla 2019-10-07 a la(s) 20 42 30" src="https://user-images.githubusercontent.com/11216948/66511647-ec31df80-ea9c-11e9-8a15-6cc9c80d5406.png">
I would like to be able to change the region of the test devices, because my app doen´t support the region of the United states. I`m from Mexico.

**Comment by Oddj0b** [comment]
@alatem We change the geographical location through the framework by spoofing GPS, would that work for you?
