### ISSUE TITLE
Display provisioning profile expiration date for iOS app

### ISSUE THREAD

**Issue by dmak12** [microsoft/appcenter#1164]
In HockeyApp there was a feature where we could see the expiration date of a provisioning profile or certificate of an app.

I would like to please see this feature added to App Center.

**Comment by nrajpurkar** [comment]
Hi @dmak12, thanks for opening this issue. Looks like a duplicate of #1013. Closing this out to continue tracking on the other issue. Feel free to add your support via reactions or comments on that issue. Thanks!
