### ISSUE TITLE
Android app does not work properly

### ISSUE THREAD

**Issue by haneal** [microsoft/appcenter#1166]
Hi,
migration is over (from HockeyApp) and ios is now working normally but Android only dumps the ThirdParty side, and you can see the normal call stack, and UE4 internal native code is not properly analyzed and is stacked in Unsymbolicated in Diagnostics.

Step1.
Curl -X POST \"https://api.appcenter.ms/v0.1/apps/{0}/{1}/release_uploads\" -H \"Accept: application/json\" -H \"X-API-Token: {2}\" -H \"Content-Type: application/json\""
 
Step2.
if (IsAndroid)
        step2Args = string.Format("-F \"ipa=@{0}\" -F \"libs=@{1}\" {2}", ApkFilename, Symbols.zip, Step1 upload_url);
else
step2Args = string.Format("-F \"ipa=@{0}\" -F \"dsym=@{1}\" {2}", ipaFilename, X.dSYM.zip, Step1 upload_url);
 
Step3.
Curl -X PATCH \"https://api.appcenter.ms/v0.1/apps/{0}/{1}/release_uploads/{2}\

Final
Curl -X PATCH \"https://api.appcenter.ms/v0.1/apps/{0}/{1}/releases/{2}\
(When creating an APK, I created a Proguard setup, obfuscated, and compressed the code using the Distribution option.)

Have you missed anything while migrating to AppCenter?

**Comment by derpixeldan** [comment]
@haneal can you please reach out to us via support so we can better investigate the problem? You can mention this issue.
