### ISSUE TITLE
Allow App Center to receive crashes from UWP app through HockeySDK

### ISSUE THREAD

**Issue by lwq008** [microsoft/appcenter#1167]
**Describe the solution you'd like**
I would like App Center to receive crashes sent through HockeySDK from UWP app.

**Describe alternatives you've considered**
Alternative is to migrate our UWP app to use App Center SDK. However, we are unable to accomplish that before the cut over date of November 16, 2019.

**Additional context**
Not sure if there is already existing feature request for this ask. Please mark this as duplicate and point me to the same ticket if so.

**Comment by derpixeldan** [comment]
@lwq008 we're working on it. HockeyApp won't be unavailable for you on November 16. You will have extra time, no worries.

**Comment by lwq008** [comment]
@derpixeldan That is great. Thank you!

**Comment by winnieli1** [comment]
Hi @lwq008! You should be seeing new HockeyApp UWP crashes in App Center now. Closing this issue but let me know if that's not the case. Thanks!

**Comment by lwq008** [comment]
I see the following message under **Diagnosis** -> **Legacy Issues**. Is it expected?

"Crashes for this app can’t be forwarded from HockeyApp yet but we are working hard so that you can see all your data in one place."
