### ISSUE TITLE
Check For Updates on Cordova Apps

### ISSUE THREAD

**Issue by EinfachHans** [microsoft/appcenter#1169]
In the older Hockey Cordova Plugin, there was an Function to check for newer Versions of this App in Hockey: https://github.com/bitstadium/HockeySDK-Cordova#checking-for-updates

I'm missing this at the Moment to make it possible to my tester to automatically update the App.

Is this possible?

**Comment by derpixeldan** [comment]
@HansKrywaa no it's not, but you can keep using the HockeySDK for now even after you've moved your app.

**Comment by HansKrywaa** [comment]
@derpixeldan Danke dir 🙏🏼 Dann bau ich wieder die HockeySDK ein, bis das kommt

**Comment by derpixeldan** [comment]
Referencing duplicates: https://github.com/microsoft/appcenter/issues/990 https://github.com/microsoft/appcenter/issues/1312

**Comment by dun3** [comment]
Hello @dipree - is this still the recommended approach? How do I integrate the old SDK into a new Cordova app? Where can I get the SDK? Is there a timeline when AppCenter supports Cordova for distribute? Thank you!
