### ISSUE TITLE
I can not configure Build for Apple without a certificate (use global)

### ISSUE THREAD

**Issue by rudacs** [microsoft/appcenter#117]
**What App Center service does this affect?**
No.

**Describe the bug**
I added the certificate in the account settings part (https://appcenter.ms/settings/accounts).
In my understanding this would be a place where we can put one or more certificates to not have to configure (upload) for each application.

But I can not save a build without being able to put the certificate.

**To Reproduce**
1. Add an Apple certificate to the account.
2. Configure the Build.
3. Add the provisioning.
4. Click Save.

Save button disabled.

**Expected behavior**
Hoping I can save and build take the account certificates.

**Comment by nrajpurkar** [comment]
@rudacs apologies for the confusion here. That section is for certificates related to [automatic re-signing](https://docs.microsoft.com/en-us/appcenter/distribution/auto-provisioning), but not for build. At this time, signing credentials need to be uploaded for each build configuration.

@Oddj0b we should take a look at clarifying this UI to avoid this confusion.

**Comment by rudacs** [comment]
Thanks for the clarification, I was in doubt. But there is an idea, to be able to use global keystore certificate or for an organization.
