### ISSUE TITLE
Give ability to send logging information from app to app center, not just exceptions

### ISSUE THREAD

**Issue by aaronlabeau** [microsoft/appcenter#1171]
**Describe the solution you'd like**
Today App Center allows you to log exceptions to App Center.  What would be nice is if you could also send other logging information to App Center.  Categories should include:

-Information
-Debug
-Error

A web page would be provided that would allow you to filter your logs based on the type of log event, date/time, and user.

**Describe alternatives you've considered**
Internal logging frameworks are ok - but since App Center already does exceptions it would be nice to have all logging in one area.

**Additional context**
This feature would add a lot of value to any team using App Center.

**Comment by winnieli1** [comment]
Thanks for the feature request! I can see how this would be really useful. We don't have immediate plans to implement this but let's keep the issue open to track interest. 

Issue #64 and #689 are sort of similar if you want to give those a +1. We'll post here if there are any updates. Thanks!

**Comment by Darkwonder** [comment]
Crashlytics from Firebase has this feature:
https://firebase.google.com/docs/crashlytics/customize-crash-reports#add-logs
I also need custom message logging, which for me is different than event tracking.
