### ISSUE TITLE
Show date in Builds list.

### ISSUE THREAD

**Issue by c-lamont** [microsoft/appcenter#1172]
**Describe the solution you'd like**
When looking at my Builds list, the dates are shown as 1 day/month/year ago.
I would like to see the actual date of the build to help me track down an issue.

**Describe alternatives you've considered**
Include the date as a greyed out subtitle under the current date. 
**2 days ago**
***10/10/2019 13:20***

**Additional context**

**Comment by nrajpurkar** [comment]
Thanks for the feature request @c-lamont. I understand how having the date visible and not having to do the calculation yourself is helpful.

FYI @baileybrooks @plainspace
