### ISSUE TITLE
Execute UI tests from the portal

### ISSUE THREAD

**Issue by grockland** [microsoft/appcenter#1175]
Great going - es geht as they say.  

However the command line interface to Test runs is very clumsy and difficult.  This should be handled in the AppCenter UI (as you probably already know).

**Comment by derpixeldan** [comment]
@grockland can you please elaborate what improvement exactly you want to see in App Center?

**Comment by grockland** [comment]
Currently AppCenter test runs are initiated through a complex local command
line interface.  (it is clumsy and the command parameters are difficult to
locate and determine). This should be moved to an automatic feature as part
of the App Center UI. i.e.  a button push that initiates test runs from App
Center itself.

**Comment by bo3po** [comment]
I think @grockland is right. It's not an elegant way to do testing by cli all the time. Never has been. I can figure out why AppCenter and the mobile testing is not more connected. Seems like they are two very different systems. I wasted a lot of build time debugging the test - and still i can not make it run. It runs fine local. Changes of me making this work within 5 builds is zero. My point is that if this was a gui/wizzard scanning the projects so we could select the project that is the test project within the gui we have today I could make this run in no time. And then in the end it should output the EXCACT cli that was used for running so I can put this into a script if I wanted to.

**Comment by Oddj0b** [comment]
@grockland @bo3po I've changed the name to `Execute UI tests from the portal` I think that shows what the actual request is.

**Comment by bo3po** [comment]
hi,

not sure what you mean :)

everything looks the same to me.

bo
