### ISSUE TITLE
[IMPROVEMENTS] Add possibility to add custom/extra logs when crashes are saved

### ISSUE THREAD

**Issue by liszto** [microsoft/appcenter#1176]
Hello,
it could be a really huge improvement for us to add some possibility to add extra infos during the crash saving phase not only during upload process (Attachement system).

With HockeyApp we had implemented this as an extra step but it could be nice to have it natively in the plugin with AppCenter. We made some method abstract and we override them when it was wanted.

Or just extend the attachment system to this moment specifically.

This allow us to bring some extra information like this : 

```
protected override List<string> GetLogHeaders()
{
	List<string> list = base.GetLogHeaders();
	if (ApplicationManager.Instance != null)
	{
		ApplicationManager.Instance.UpdateHockeyAppLogHeaders(list);
	}
	return list;
}
```

With this override, this allow us to obtain a log with "information" like the user in our system, what action he did before this occured etc...

**Comment by PaulTaro** [comment]
I also need urgently a feature to include the custom app state at the time when the app crashes in the crash report. See SetExceptionDescriptionLoader of Hockey app!
