### ISSUE TITLE
Support uploading native library .so files in App Center VSTS task like HockeyApp does

### ISSUE THREAD

**Issue by msdof** [microsoft/appcenter#1178]
Hi,

We team highly depend on App Center VSTS task(called: "App Center distribute") to make our build pipelines run well. But currently it **CAN'T** support uploading native library .so files. There is only an configurable entry for uploading Android mapping file:
![image](https://user-images.githubusercontent.com/52813313/66626097-8c1c7400-ec29-11e9-98be-6ef702481ec0.png)

It's blocking us to get real de-obfuscated traces. Please refer HockeyApp VSTS task(we were using it), they can well support it.
![image](https://user-images.githubusercontent.com/52813313/66626230-064cf880-ec2a-11e9-8871-5e79feceac33.png)

Any timeline for this?

**Comment by derpixeldan** [comment]
Duplicate https://github.com/microsoft/appcenter/issues/1160
