### ISSUE TITLE
Support Codebase as bug tracker

### ISSUE THREAD

**Issue by futuretap** [microsoft/appcenter#1179]
In HockeyApp, we could auto-generate issues in [Codebase](https://www.codebasehq.com) for repeating crash reports. Please bring that feature back as we have to transition to App Center.

**Comment by winnie** [comment]
Thanks for the feature request. This is a gap we are aware of but unfortunately I don't have an ETA. We'll keep this issue open to track interest and prioritize accordingly. Thanks!

**Comment by futuretap** [comment]
We're still interested in this.

**Comment by futuretap** [comment]
Still relevant!

**Comment by futuretap** [comment]
The get-on-my-nerves bot is kicking again. 😟
It's still relevant!

**Comment by futuretap** [comment]
Still relevant, stupid @msftbot.

**Comment by futuretap** [comment]
It is still super-relevant, stupid @msfbot.
