### ISSUE TITLE
Add WPF as a Platform Selection

### ISSUE THREAD

**Issue by adammarks** [microsoft/appcenter#118]
**Describe the solution you'd like**
Add WPF as a platform selection.

**Describe alternatives you've considered**
Alternatively you could just change UWP to UWP / WPF if the features/functionality will work the same for WPF as they will for UWP. 

**Additional context**
This is important as HockeyApp users are migrating WPF apps that were "custom" in HockeyApp over to AppCenter. 
![wpfplatform](https://user-images.githubusercontent.com/1170063/53498485-6bc1ef80-3a74-11e9-9266-5e8ad832c6a0.png)

**Comment by derpixeldan** [comment]
@adammarks thanks, it's tracked on our [Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#platform-support)

**Comment by rido-min** [comment]
With the new desktop modernization efforts we are trying to remove the barriers/differences between platforms. We'd like to talk about *Windows Applications* delivered with *MSIX*. If it has WinForms, WPF or UWP UI should not change the AppCenter experience.

**Comment by winnieli1208** [comment]
Hi @adammarks - as Dan mentioned, this is currently on our roadmap. We haven't finalized the details of the app creation flow but either way, you will be able to create an app instance to support your WPF app once we finish the Windows work.

As we make progress in our Windows support, you will still be able to upload .zip files or any other file types we currently support today. Thanks!

**Comment by winnieli1208** [comment]
Closing this issue. As mentioned in #242, we just released support for WPF and WinForms apps. Thanks!
