### ISSUE TITLE
Enable CLI `publish` auto-emailing to work with Microsoft Office365 `corp` account members

### ISSUE THREAD

**Issue by AlohaDaveKlein** [microsoft/appcenter#1183]
**Describe the solution you'd like**
Companies that have Office365 contracts with Microsoft have their users log into MS with usernames in the format of `JDoe@corp.mycompany.com`.  And although users' MS online accounts list their official email addresses as `JDoe@mycompany.com`, the AppCenter CLI command `appcenter distribute publish --group mycompany` sends the emails to the `usernames` (with the `corp.` in the address), not to the real email.   The email-send silently fails; whereas it should likely show the failure in the CLI --debug log.

**Describe alternatives you've considered**
Testing the `corp.` emails from a regular mail client, the mail system returns: 
`DNS Error: 2447138 DNS type 'mx' lookup of corp.mycompany.com responded with code NXDOMAIN Domain name not found: corp.mycompany.com`

MyCompany could try to register `corp.mycompany.com`, but that adds additional burden to all customers.

Also, a new email/account outside of the MyCompany's Office365 could be registered as a user (like a gmail account), but that causes security issues since the gmail account is outside the company.

**Additional context**
None

**Comment by Oddj0b** [comment]
Thanks for the bug, my colleague will pick it up in the near future.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
