### ISSUE TITLE
"Not Found" when attempting to download an an app via the API

### ISSUE THREAD

**Issue by stephenquan** [microsoft/appcenter#1185]
Dear AppCenter,

I'm trying to download a distributed app programmatically.

I think I need to use the downloads API.
I start by getting a `uri` from the downloads API.
But, my attempts to use that `uri` results in a `Not Found` JSON message.

This is the script I used to get the `DOWNLOAD_URI` :

```bash

# APPCENTER_OWNER_NAME=...
# APP_NAME=...
# APPCENTER_TOKEN=...
# BUILD_ID=...
DOWNLOAD_TYPE=build
curl -X GET \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header "X-API-Token: ${APPCENTER_TOKEN?}" \
"https://api.appcenter.ms/v0.1/apps/${APPCENTER_OWNER_NAME?}/${APP_NAME?}/builds/${BUILD_ID?}/downloads/${DOWNLOAD_TYPE?}" 
```

Which outputs something like:

```json
 {
    "uri": "https://build.appcenter.ms/v0.1/public/apps/12341234-1234-1234-1234-12341234123/downloads?token=123412341234123412341234123412341234134123412341234123413412"
}
```

However, I cannot figure how to use this `DOWNLOAD_URI`. Here's my attempt:

```bash
curl \
--header "X-API-Token: ${APPCENTER_TOKEN?}"  \
${DOWNLOAD_URI?} \
-o output.dat
```

But this fails with the following JSON written to `output.dat` 🔢 

```json
{
    "id": "98e477c0-ee43-11e9-8b1a-e592eb023ae0",
    "message": "Not Found"
}
```

**Comment by MateuszSawicki** [comment]
Im having the same problem

**Comment by svats-nn** [comment]
I am facing the similar issue

{
"id": "43a3e150-f0d3-11e9-8e69-8b9789963eea",
"message": "Invalid or expired token"
}

**Comment by MateuszSawicki** [comment]
Hello.
Kindly asking, what's the status of the work regarding the issue?

**Comment by derpixeldan** [comment]
Sorry for the delay, we're investigating.

**Comment by derpixeldan** [comment]
@stephenquan can you please elaborate what service you're using and what you're trying to achieve? From your description it seems you're trying to download a distributed build, however, the API you're using is for downloading successful build artifacts from the Build service. To download a distributed release you can use this [API](https://openapi.appcenter.ms/#/distribute/releases_getLatestByUser).

**Comment by stephenquan** [comment]
Hi @derpixeldan, indeed, I was trying to download a distributed release, and, your conclusion was absolutely correct.

I was using the wrong API.

Once I used the release API you indicated, it worked.

Below is an excerpt from my now-working script and output. (Note that secrets have been redacted and replaced with a "secret" prefix):

```bash
# APPCENTER_TOKEN=${secret_appcenter_token}
# APPCENTER_OWNER_NAME=${secret_appcenter_owner_name}
# APP_NAME=${secret_app_name}
RELEASE_ID=latest
API_JSON=release.json
curl -X GET \
  --header 'Content-Type: application/json' \
  --header 'Accept: application/json' \
  --header "X-API-Token: "${APPCENTER_TOKEN?} \
https://api.appcenter.ms/v0.1/apps/${APPCENTER_OWNER_NAME?}/${APP_NAME?}/releases/${RELEASE_ID?} | tee ${API_JSON?}
```

Which outputs:

```
{
    "origin": "appcenter",
    "min_os": null,
    "app_name": "secret_app_name",
    "bundle_identifier": "secret_bundle_identifier",
    "distribution_groups": [
        {
            "origin": "appcenter",
            "is_public": false,
            "display_name": "Collaborators",
            "id": "00000000-0000-0000-0000-000000000000",
            "name": "Collaborators"
        }
    ],
    "owner": {
        "display_name": "secret_display_name",
        "name": "secret_display_name"
    },
    "app_os": "Windows",
    "id": secret_id,
    "size": secret_size,
    "install_url": "secret_install_url",
    "package_hashes": [
        "secret_package_hashes"
    ],
    "download_url": "secret_download_url",
    "version": "secret_version",
    "destination_type": "group",
    "release_notes": "secret_release_notes",
    "distribution_group_id": "00000000-0000-0000-0000-000000000000",
    "status": "available",
    "short_version": "secret_short_version",
    "fingerprint": "secret_finger_print",
    "is_latest": true,
    "uploaded_at": "secret_uploaded_at",
    "app_display_name": "secret_app_display_name",
    "enabled": true,
    "device_family": null,
    "mandatory_update": false
}
```

**Comment by aikuznetsov** [comment]
The question is still actual. How I can download bundle file by download link? 
I use simple curl command: 
`curl \
--header "X-API-Token: ${APPCENTER_TOKEN?}"  \
${DOWNLOAD_URI?}`

and the actual response is
`{"id":"dedf15d0-05ab-11ea-9540-4d1915be514f","message":"Invalid or expired token"}`

**Comment by stephenquan** [comment]
@aikuznetsov I was the one who created this issue, but, conceded that this issue was a user error because I was distributing my releases but incorrectly using the build apis to download them, whereas, I needed to use the release API to download them.

I showed the correct release API needed to download the items and that is why I closed this issue.

You need to confirm with yourself what you are actually downloading. A distributed release or a build? Then, that should clarify to you the `curl` command you really should be using,

**Comment by pradyhk** [comment]
> Hi @derpixeldan, indeed, I was trying to download a distributed release, and, your conclusion was absolutely correct.
> 
> I was using the wrong API.
> 
> Once I used the release API you indicated, it worked.
> 
> Below is an excerpt from my now-working script and output. (Note that secrets have been redacted and replaced with a "secret" prefix):
> 
> ```shell
> # APPCENTER_TOKEN=${secret_appcenter_token}
> # APPCENTER_OWNER_NAME=${secret_appcenter_owner_name}
> # APP_NAME=${secret_app_name}
> RELEASE_ID=latest
> API_JSON=release.json
> curl -X GET \
>   --header 'Content-Type: application/json' \
>   --header 'Accept: application/json' \
>   --header "X-API-Token: "${APPCENTER_TOKEN?} \
> https://api.appcenter.ms/v0.1/apps/${APPCENTER_OWNER_NAME?}/${APP_NAME?}/releases/${RELEASE_ID?} | tee ${API_JSON?}
> ```
> 
> Which outputs:
> 
> ```
> {
>     "origin": "appcenter",
>     "min_os": null,
>     "app_name": "secret_app_name",
>     "bundle_identifier": "secret_bundle_identifier",
>     "distribution_groups": [
>         {
>             "origin": "appcenter",
>             "is_public": false,
>             "display_name": "Collaborators",
>             "id": "00000000-0000-0000-0000-000000000000",
>             "name": "Collaborators"
>         }
>     ],
>     "owner": {
>         "display_name": "secret_display_name",
>         "name": "secret_display_name"
>     },
>     "app_os": "Windows",
>     "id": secret_id,
>     "size": secret_size,
>     "install_url": "secret_install_url",
>     "package_hashes": [
>         "secret_package_hashes"
>     ],
>     "download_url": "secret_download_url",
>     "version": "secret_version",
>     "destination_type": "group",
>     "release_notes": "secret_release_notes",
>     "distribution_group_id": "00000000-0000-0000-0000-000000000000",
>     "status": "available",
>     "short_version": "secret_short_version",
>     "fingerprint": "secret_finger_print",
>     "is_latest": true,
>     "uploaded_at": "secret_uploaded_at",
>     "app_display_name": "secret_app_display_name",
>     "enabled": true,
>     "device_family": null,
>     "mandatory_update": false
> }
> ```

@stephenquan can you please share us the command you used to download an app using curl.. we were able to get release build info for distributed build just like you mentioned above.. but using the `download_url` from above response in `curl \ --header "X-API-Token: ${APPCENTER_TOKEN?}" \ ${download_url?}` is not downloading the app .. any help is much appreciated ..

@dipree please let me know if I need to open a separate issue, since this one is already closed.

**Comment by kopax-polyconseil** [comment]
Is this issue resolved ? We can't find on the API doc how to download our apk from command line in our CI.

**Comment by 123abceng** [comment]
We are experiencing the same problem.
