### ISSUE TITLE
Add support for xcodebuild build-for-testing with Developer certificates (iOS)

### ISSUE THREAD

**Issue by antpuleo2586** [microsoft/appcenter#1187]
**Describe the solution you'd like**
I've started running automated UI tests using XCUITest for iOS in our React Native app.
My plan was to automatically build these tests during the App Center build, then upload and trigger them in cloud platforms such as Firebase Test Lab.

However, I had a problem because the test build must be signed with a Developer profile/certificate and we were using a Distribution profile/certificate.

It would be great if there was the option for App Center to automatically build-for-testing for you and/or allow you to upload a Developer profile/certificate for the test build.

**Describe alternatives you've considered**
To get this to work, I have to run the `xcodebuild build-for-testing` command in a post-build script ensuring that in my build configuration I use a Developer profile/certificate.
While this works now, it means I can't distribute this app to the app store because it must be signed with a Distribution certificate.

**Additional context**
Using React Native v0.64

**Comment by rraczae** [comment]
This would be nice indeed...
