### ISSUE TITLE
Analytics with UWP app

### ISSUE THREAD

**Issue by atiyka** [microsoft/appcenter#1188]
I'm developing an app in WPF and the analytics are working fine with it. But when I build my app with desktop bridge to be able to run as a UWP app, then the analytics stops working. I know that the crash reporting is not yet done, but also the analytics part is in progress? Or I was missing something?

I tried with version 2.1.1 and with 2.3.0-prerelease, too. Both works the same way.

**Comment by atiyka** [comment]
We tried to fall back to the HockeyApp, because we need the analytics data, but even there isn't working. I don't receive any analytics data neither in WPF mode, nor in UWP.

**Comment by derpixeldan** [comment]
@atiyka please write a support ticket to us so we can better investigate the issue.
