### ISSUE TITLE
Virtual test support

### ISSUE THREAD

**Issue by ghost** [microsoft/appcenter#1189]
**Describe the solution you'd like**
_AppCenter_ should let you create virtual test that simply look at iso/android log for regex to see start/end/success/fail event of a test. A virtual test is a simple definition containing regex. The primary purpose of this is to support existing testing framework where companies have invested time and money and could not possible duplicate the effort to add wrapper or other hacks to get it to run with AppCenter. 

In our case we have google test (cross platform) which we were able to run on any connected ios/andriod devices as a regular application and look at the log for failures. While now in addition to that we have large number of test in javascript  (require native addon) on Node.js while on iOS it run in JavascriptCore with native addon build. Running our same javascript test written in mocha/chai is fundamental. To do this i wrapped our backend js test into a single UIXCode test but generated necessary log so that as part of CI job in VSTS i would grep to see failing test and fail the CI job for iOS.

Another senario is performance test that is written native and js. That we like to test with various version of devices. Again all our test are non-UI.

**Describe alternatives you've considered**
Given our existing test is written in mocha and gtest try and all are backend test with no UI. I was going with CI Job test with script to look at log to see which test has failed or pass. This is what i like to be done on AppCenter rather then by some script.

**Additional context**
Current  AppCenter focus on testing framework that assume platform specific code and end user applications. But in our case we building framework that is cross platform and test already exist we just need to run them on different platforms. While on connected devices we ran them as regular applications and collected log on AppCenter we cannot do that. We also do not like to manage devices and like to have this as part of pipleline the only good alternative is appcenter but then we have to use scripts to get the desire behaviour while it would have been nice if appcenter reported failing test rather then grepping for it.

**Comment by Oddj0b** [comment]
@afkn I don't think I fully understand what you would gain from a virtual test. Is it because you want all test results shown in the App Center UI?

**Comment by afkn** [comment]
In simple word i have single test in objective-c that kick of test suit in javascript running on javascript core written in js/mocha. The test is run as part of CI job in azure which build ios test app and send it over to app center to run. Appcenter given a test report that is just says one test has run successfully. My CI job has script that call appcenter rest api to get the device log. From device log it scrap test report and write any failing test to stderr to get the CI job to fail to alert user that something he pushed has broken the test on iOS platform.

The device log think look a bit fragile to me. I like to output my report as juint.xml or other format the azure CI job understand and can show in its portal to developer. I am not highly concern if appcenter show that report as well. Currently the only data we get from appcenter is either test report of devicelog. If there is any way to write my test output (Generated by mocha reporter) to a some file and allow that to be downloaded as  test report it would be awesome. Writing fragment to logs and then scraping it to create report seem fragile and may break if device log format change some how or the app name is changed etc.
