### ISSUE TITLE
"Unauthorized" responses when make API Request

### ISSUE THREAD

**Issue by balivo** [microsoft/appcenter#1191]
HI everyone,

My (own) admin panel has a push send functionality connected to AppCenter, I have 2 types of push, immediate and scheduled... In the immediate push, a message is sent at registration and everything works perfectly... Scheduled push, registers a message to be sent in the future through a Timer Trigger Function that every hour consults the pending messages and sends them according to the established time.

When sending via Function that triggers an Endpoint from my API to send the messages using AppCenter, the AppCenter API requests return "Unauthorized" status, but I am using the same web panel token (used in immediate way).

This is intermittent, not every time AppCenter API calls gives error, sometimes it fires correctly.

Any information about?

Tks

**Comment by turanuk** [comment]
Hello, sorry you are experiencing issues. Can you please file a support ticket with us so we can look into your specific issues and logs? https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us

**Comment by turanuk** [comment]
Screenshot of the support icon on the bottom right of the screen when you load up appcenter.ms:

![image](https://user-images.githubusercontent.com/723462/66769172-4cdc6600-ee69-11e9-84f1-0b469fccaffa.png)

**Comment by balivo** [comment]
Ok! Tks...
