### ISSUE TITLE
Appcenter option to "stop testing platform X"

### ISSUE THREAD

**Issue by moody31415** [microsoft/appcenter#1193]
**Describe the solution you'd like**
Today, appcenter (eg, https://install.appcenter.ms/apps) will show me apps for windows, android, and ios. I briefly used an ios device, and enrolled in testing on a bunch of apps - but now I no longer have that device and use an android instead. Yet I get period emails from appcenter telling me to update my ios apps. There should be a one-button "stop testing platform X" to 'unsubscribe' me from all apps on a given platform.

**Comment by derpixeldan** [comment]
@moody31415 in case you're a tester on the app, you can opt-out from testing it on the upper right corner
![Screenshot 2019-10-15 at 16 30 55](https://user-images.githubusercontent.com/3369400/66841072-68c73100-ef69-11e9-886d-17eba3658e3c.png)
in case you're developer you can turn off notifications
![Screenshot 2019-10-15 at 16 32 18](https://user-images.githubusercontent.com/3369400/66841384-e8550000-ef69-11e9-816c-895a72eeacac.png)

However, I see the problem that as a tester you can't opt-out from emails.

**Comment by moody31415** [comment]
The view I have on appcenter has literally hundreds of applications. None of those indicate what I'm testing, so I have to go through each one individually - and if the next page has a "..." menu, then I can opt out, if it doesn't have a "..." menu, then I never started testing it. Of those hundreds of applications, 1/3 say they're for 'windows', 1/3 says 'Android', and 1/3 says iOS. So what I want is a way to trigger (eg) "stop testing all iOS apps"

**Comment by moody31415** [comment]
eg, a small snippit of the list of apps - which ones have I tested? which ones do I need to leave? 
![image](https://user-images.githubusercontent.com/15916159/66863779-9c459380-ef48-11e9-8305-ce55ef076b03.png)

**Comment by botatoes** [comment]
Hi, @moody31415 We just released a feature that will always show you '...' to stop testing. 
Because of permissions granted through distribution groups / shared distribution groups / collaborator groups / etc, it's hard to stop testing for a specific platform since you might have access to apps from different sources. Our new feature should allow you to better understand how you have access to the apps and steps needed to stop testing.

**Comment by ferdicus** [comment]
Is there a way to disable this feature?  
Let's say you're using one email for multiple testers - one might accidentally select "Stop testing app" and disable it for all others that use the same email :S
