### ISSUE TITLE
Support for Searching Recent ErrorGroups

### ISSUE THREAD

**Issue by gestrich** [microsoft/appcenter#1194]
Hockey's rest API had support for searching for crashes by app version, upload date, etc.. These search parameters are important for scripts which process crash information, some which run on a regular basis -- looking for new crashes for targeted versions. With a large app, it is time-consuming to pull the JSON for all versions/dates since the App's creation date, when only the recent crashes are relevant.

In App Center, I see a very limited number of search options using the oData notation https://openapi.appcenter.ms/#/errors/Errors_ErrorGroupsSearch

I can filter by exceptionMethod and a few others. I get the "Cannot filter on the <field name> field" if I try to search on lastOccurrence, appVersion, or appBuild and most others. I suppose I could order the results by lastOccurrence but that will still return old versions of the app, with recent crashes. So a few requests here:

- Support to search for ErrorGroups and limit to a specific app version.
- Support to search for ErrorGroups and limit to a specific app build.
- Support to search for ErrorGroups and limit a an occurrence date range.

**Comment by Petr-2019** [comment]
One request I can think of as work-around is:

- Once the search results return, I'd like to be able to sort by `app version`
