### ISSUE TITLE
Some testers can no longer install iOS app

### ISSUE THREAD

**Issue by klogeaage** [microsoft/appcenter#1197]
**What App Center service does this affect?**
iOS app distribution

**Describe the bug**
Since october 2nd, some of our testes can no longer install new releases. All devices are provisioned (green) and a release has been prepared, but some of the testers cannot install the build.
There is no INSTALL button available for the testers, only a GET button. Once the tester clicks GET she gets an error "Oops, there was a problem building the app".
Automatic device management is turned on.

**To Reproduce**

As a tester select a release
Instead of the usual INSTALL, there is a GET button. Clicking on that gives you the "Oops..." message.

Expected behavior
There should be an INSTALL button and the app should be downloaded and installed on the device

**Screenshots**
This is the latest "bad" release:
![2019-10-15](https://user-images.githubusercontent.com/776718/66822072-ca74a480-ef43-11e9-82d1-8e55af8513b0.png)

As mentioned, this only happens to some testers. They tend to have newer models, i.e. iPhone X, XS or 8. For others with older devices like iPhone 6 or 7, there is no problem. Also, the testers with the problem are located in Denmark, while the ones that work are in Italy. Whether that is significant is hard to tell.

**Comment by derpixeldan** [comment]
@klogeaage please reach out to us in support so we can better investigate the problem.

**Comment by klogeaage** [comment]
Sure, using comments here or do you prefer another channel?

**Comment by derpixeldan** [comment]
@klogeaage sorry, I mean the support system in App Center. It's the blue button in the lower right corner.

**Comment by dimazaid** [comment]
Hi @klogeaage  - I just wanted to check-in to see if you're still running into the issue. Did you contact support on App Center?

**Comment by klogeaage** [comment]
Yes, the problem is still there, but being worked on by a developer in Sacramento (Attinder) and the team that handles Apple's account validation and provisioning.

**Comment by Oddj0b** [comment]
Hej @klogeaage,

I'll assume the problem was handled by support or is on-going.

**Comment by klogeaage** [comment]
Yes, it was handled and I told them that they could close this issue. I’ll do it now if I can.
