### ISSUE TITLE
Allow to rename application URL as name changes from AppCenter portal (settings)

### ISSUE THREAD

**Issue by stvansolano** [microsoft/appcenter#1198]
**Describe the solution you'd like**
As a `alpha` application developer or even for POCs, the final details for my app not quite defined yet, but the URL of the app seems to be written in stone. Can I change it even if I rename the app?

**Describe alternatives you've considered**
I tried the `Settings` rename option but it doesn't change the URL. Try deleting the app? Recreate?

**Additional context**
When renaming, redirecting to new URL would be awesome. GitHub is pretty good on that ;)

**Comment by lumaxis** [comment]
@stvansolano This is actually already possible through our API today (and thereby also our CLI, for example), just not exposed in the UI.
This the the documentation for the API call: https://openapi.appcenter.ms/#/account/apps_update

**Comment by lumaxis** [comment]
One thing to note though is that a change of `name` also changes the URL for API calls, i.e. from there on out, you'll need to adjust any automation/CI or similar that you might have set up.

**Comment by stvansolano** [comment]
Hi @lumaxis thank you for that! I didn't know that's possible through the CLI too.

Will take a look on that. I also updated the ticket in case that can be included as part of the UI too.

Thanks a lot!!

**Comment by amchew** [comment]
Thanks @stvansolano for letting us know! FYI for @baileybrooks

**Comment by stvansolano** [comment]
Hi @amchew guess what? Others are having the same inquiry :) @CShri

https://github.com/microsoft/appcenter/issues/1249

So both may be duplicated.

**Comment by jbrozen** [comment]
Yeah, this is becoming a bigger issue for us and our CI/CD pipeline - as it appears the technical URL structure is based on initial app name and cannot be updated after the fact (so you basically have to create a new app if you want to rename)

**Comment by yousseftarekkh** [comment]
In case anyone is still wondering how to overcome this issue, here's the piece of code that worked for me through the [Appcenter CLI Commands](https://github.com/microsoft/appcenter-cli#Commands).

The following command `appcenter apps update` helps update your **appcenter's application argument(s)**. To address a specific app you need to concatenate `--app <app_id>`, your can retrieve your _app_id_ through calling `appcenter apps list` then add to it the the new value for each argument you want to update.

**The command you are waiting for.** 
Assume changing the **name** argument for the app with the following **app_id**: junior/awesome_app, you can run the following command `appcenter apps update --app junior/awesome_app --name even_awesomer_app`.

**Comment by antpuleo2586** [comment]
I used the swagger API to patch the `name` of one of my apps and now I get the response 

```
{
"message": "Forbidden",
"statusCode": 403,
"code": "Forbidden"
}
```

when I try to access it.

Here is the request that was made, which was successful:

```
curl -X PATCH "https://api.appcenter.ms/v0.1/apps/MyCompany/Name.Mobile.Android.Dev" -H "accept: application/json" -H "X-API-Token: xxxxxxxxxxxxxxxxxxx" -H "Content-Type: application/json" -d "{ \"name\": \"Renamed.Mobile.Android.Dev\"}"
```

Please help! I don't want to have to delete this app and start again and I have other apps I need to rename.

Thanks!

**Comment by jphenow** [comment]
Hey there @antpuleo2586 could you navigate to https://appcenter.ms and contact us on the blue chat bubble in the bottom right of the website? We should be able to get you sorted out and figure out how to improve this a little better.
