### ISSUE TITLE
View individual analytics events in AppCenter Analytics

### ISSUE THREAD

**Issue by davidallen-bluemetal** [microsoft/appcenter#1199]
Currently, when AppCenter displays analytics events, it aggregates the properties for each event type and lists them in grouped mode. This might occasionally be useful at a very very high level, it is mostly useless.

Please add a feature to allow each event (record) in an event type to be viewed with the values for each property. Best would be a sortable table with each event instance listed with a column for each property. This was we can see how the values of the properties relate. This is what is required if we are to utilize AppCenter Analytics in maintenance support and track down the cause of issues and behaviours.

**Comment by amchew** [comment]
Thanks @davidallen-bluemetal for sharing your feature request, @hamswan would you be able to take a look?

**Comment by davidallen-bluemetal** [comment]
Thanks. Even the ability to export event instances (records) to a local Excel spreadsheet rather than have to export data to Application Insights or blob storage would be a big step forward.

**Comment by ben-dean** [comment]
I'm just bumping this as I'd love to see the instances of the event in the web UI to actually make it useful. 

In what situation would you ever really just want the grouped information?!

**Comment by zoli13** [comment]
Agree, this is a highly needed feature!
