### ISSUE TITLE
Unable to mock class methods on MSAppCenter

### ISSUE THREAD

**Issue by jeffwatkins** [microsoft/appcenter#1201]
Mocking class methods on MSCrashes and MSAnalytics seems to work, but MSAppCenter does not seem to work. We'd like to use OCMock to ensure our application is setting up App Center correctly, but perhaps App Center is doing something to thwart this?

Please see the attached sample project.

[MSAppCenterMock.zip](https://github.com/microsoft/appcenter/files/3731825/MSAppCenterMock.zip)

**Comment by amchew** [comment]
Thanks @jeffwatkins for reporting this. @winnieli1 would you mind taking a look?

**Comment by jeffwatkins** [comment]
Just because no work has been done on an issue doesn't mean the issue is **stale** or no longer relevant. Automatically closing issues in this manner makes it clear filing them in the first place was a waste of my time.
