### ISSUE TITLE
invite or add multiple users in ‘Collaborators’ and ‘Teams’ using separator

### ISSUE THREAD

**Issue by millanie** [microsoft/appcenter#1202]
**Describe the solution you'd like**
For ease of user management, we would like to invite or add multiple users to and from the 'co-worker' and 'team' using separators. 

**Describe alternatives you've considered**
No alternatives

**Additional context**
![appcentermultiuser](https://user-images.githubusercontent.com/23490278/66880172-a628ce80-effc-11e9-80cc-e1d50fcbdf90.JPG)
![appcentermultiuser2](https://user-images.githubusercontent.com/23490278/66880199-ce183200-effc-11e9-80b6-7ea275365403.JPG)

**Comment by amchew** [comment]
Thanks @millanie for sharing your feature request - @baileybrooks would you mind taking a look?

**Comment by kuyazee** [comment]
Any updates on this?

**Comment by vorrin** [comment]
Is there really no plan to add this in? Isn't that pretty much necessary for bigger teams?

**Comment by kuyazee** [comment]
Up on this

**Comment by cbillante-gpsw** [comment]
I would like to bump this request.  It is very cumbersome to manage larger groups with the current design.  It should also ignore if a user is already in the group without erring.  Thanks.
