### ISSUE TITLE
More information about the user in the same depth 

### ISSUE THREAD

**Issue by millanie** [microsoft/appcenter#1204]
**Describe the solution you'd like**
There is little information when reviewing users. We would like to check the information about devices, distribution groups, apps and engaged teams when we check user's information. 

**Describe alternatives you've considered**
No alternatives or manually investigating on each apps or each distribution group or team. 

**Additional context**
On HockeyApp, admin can easily check what kind of apps or devices the user have on the same depth. 
![image](https://user-images.githubusercontent.com/23490278/66880947-fead9b00-efff-11e9-822a-bf50a13ed581.png)

**Comment by Brantone** [comment]
The ability to see what groups / devices a user has access is extremely crucial when dealing with larger teams. Losing this functionality as a result of HockeyApp migration is very frustrating.

**Comment by Brantone** [comment]
This is precisely a case for why this feature is needed: Off-boarding : https://github.com/microsoft/appcenter/issues/1242

**Comment by ScottArbeit** [comment]
@Brantone Yes, we agree, and we intend to bring this kind of functionality to App Center. I can't say for sure when that will happen, but it's definitely on the backlog. When we plan this feature, I'll be back on this issue to ask for feedback about the design.

I'm leaving the issue open to get more feedback from App Center users about it... if you're interested in similar functionality, please give us a thumbs-up so we know how to prioritize the work!

In the meantime, I've created a small sample utility to show off the App Center REST API to dump all of the users in an App Center organization. I didn't add devices yet, but it wouldn't be difficult, and hopefully I'll get to it this week. Feel free to try it, and I hope it helps: https://github.com/ScottArbeit/ListAppCenterUsers

**Comment by Brantone** [comment]
Sounds good. Thanks!!
