### ISSUE TITLE
Android app icon not shown on In-app update setup page

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter#1206]
**Describe the solution you'd like**
While using Distribute, when the in-app updates get enabled the first time the app is launched with the Android AppCenter SDK, the icon of the app is not shown on the webpage.
Instead the first letter of the app is used a placeholder.
See partial screenshot:

<img width="585" alt="enabling" src="https://user-images.githubusercontent.com/1186282/66924477-9de38a00-f022-11e9-8821-6a5e2f1b70f9.png">

Meanwhile the icon properly shows up in the AppCenter dashboard.

Is there some specific setup to do or is this a bug?

**Describe alternatives you've considered**
N/A

**Comment by amchew** [comment]
Thanks @fabiendem for reporting this, and we'll take a look. @botatoes would you mind checking?
