### ISSUE TITLE
Pull Bug Reports / Tombstone files after Android test crashes

### ISSUE THREAD

**Issue by rygo-msft** [microsoft/appcenter#1207]
**Describe the solution you'd like**
Native code is particularly prone to device specific issues, so testing native code in AppCenter is extremely useful. However, failures in native code can often result in app process crash. 
Normally, developers can pull tombstone and bugreport files directly from the device when the app crashes.

It would be extremely helpful if AppCenter would automatically pull those files for failed Android tests. Otherwise it becomes extremely difficult to investigate the failures.

**Describe alternatives you've considered**
The only alternative currently would be to purchase the device and run the tests locally.

**Additional context**
https://source.android.com/devices/tech/debug/native-crash#tombstones
https://developer.android.com/studio/debug/bug-report

**Comment by amchew** [comment]
Thanks @rygo-msft for sharing your feature request, and getting my teammate @winnieli1 eli1 to take a look at it.

**Comment by tpetsas** [comment]
Is there any progress on that? Otherwise is there a way to upload tombstone files manually, e.g., through an API request? Will App Center be able to analyze them? Does this need specific formatting?

**Comment by KristofferHenriksson** [comment]
We use appcenter to automate our BVTs and perf tests and occasionally run into a crash here. The Android default logcat output for a native code crash doesn't always include enough information to get to our code and having tombstones gives us more information to go on in trying to track these down.

**Comment by rygo-msft** [comment]
This is still relevant
