### ISSUE TITLE
Run tests with Android Test Orchestrator

### ISSUE THREAD

**Issue by rygo-msft** [microsoft/appcenter#1208]
**Describe the solution you'd like**
Provide the ability to run tests using the Android Test Orchestrator. The test orchestrator makes writing test cases easier and allows for better isolation of tests when an app crashes.

Support for this will require allowing installation of orchestration APKs alongside the test app and invoking the test orchestrator instrumentation command.

**Describe alternatives you've considered**
All tests that run in AppCenter must be rewritten with additional logic to reset app state. These alternatives are not fool proof, because you cannot add crash isolation at the Espresso/JUnit level. This must be done at the orchestration level.

Currently, when a test causes the app to crash we lose the full set of results for the device as they are all marked as having failed.

**Additional context**
https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator

**Comment by amchew** [comment]
Thanks @rygo-msft for sharing your feature request, and getting my teammate @Oddj0b to take a look at it.

**Comment by Oddj0b** [comment]
Thank you for sharing the link, hopefully, there will be more reactions.

**Comment by NilsLattek** [comment]
Please keep it open, still an important feature.

**Comment by rygo-msft** [comment]
My team now leverages test orchestrator for the vast majority of our tests in order to wipe apps and install additional apps for testing scenarios. We can only run a small subset of our tests in AppCenter currently because test orchestrator isn't supported.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.
