### ISSUE TITLE
Disable releases

### ISSUE THREAD

**Issue by patniko** [Microsoft/appcenter#121]
Ability to disable a release. Once a release is disabled, testers won't be able to install it. 
This feature will allow users to enable / disable releases in the UI and API. 
This feature will allow clean up some inconsistencies between different user entry points when editing a release.

**Comment by botatoes** [comment]
Some mock ups 
![Disable a release in the list view](https://d2mxuefqeaa7sj.cloudfront.net/s_C63A5DB5B4A7C7FA664EC2FCC87AD7618B07013BCEC256FB2FAB812C0576DFB7_1550298989528_image.png)

![Vertical dot menu in details view](https://d2mxuefqeaa7sj.cloudfront.net/s_C63A5DB5B4A7C7FA664EC2FCC87AD7618B07013BCEC256FB2FAB812C0576DFB7_1550300044819_image.png)

![Disabled Release](https://d2mxuefqeaa7sj.cloudfront.net/s_C63A5DB5B4A7C7FA664EC2FCC87AD7618B07013BCEC256FB2FAB812C0576DFB7_1550789341238_image.png)

**Comment by davebcn87** [comment]
what's the status on this? I tried to disable one release but this button is not available in my builds. I only see "Delete release".
