### ISSUE TITLE
AppCenter does not support startup crash handling

### ISSUE THREAD

**Issue by shnaz** [microsoft/appcenter#1211]
HockeyApp gives the ability to handle startup crashes, when will AppCenter Diagnostics be able to do the same?

[HockeyApp: How to handle crashes during startup...](https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/how-to-handle-crashes-during-startup-on-ios-and-os-x)

We are using HockeyApp for crash-reporting, and soon we are forced over to AppCenter, which is why our team has already began to migrate some of our apps and use AppCenter Diagnostics SDK in instead of HockeyApp SDK, and we have noticed that startup crash handling is not supported by AppCenter SDK.

**Comment by amchew** [comment]
Thanks @shnaz for sharing your user scenario. @winnieli1 would you mind sharing more details?

**Comment by shnaz** [comment]
Any news on this? Our apps stability depend on this functionality. When will it be available in AppCenter.Diagnostics?
