### ISSUE TITLE
Ability for AppCenter Webhook test button to test different events

### ISSUE THREAD

**Issue by nishaatr** [microsoft/appcenter#1212]
**Describe the solution you'd like**
The Webhook test button currently sends a simple JSON (with incorrect content-type). Allow the test button to test these events (send a complete JSON payload perhaps with fake data):
•	App build failed/succeeded
•	New app version released
•	New app crash group created

Moreover, the Webhook should also have an option to send a crash report within the same group.

**Describe alternatives you've considered**
None

**Additional context**
This came about during my recent problem with the test button. It turns out that the test button sends incorrect content-type and should be application/json (JIRA expects this). We fixed this by re-writing the HTTP request content-type in our Load Balancer

**Comment by amchew** [comment]
Thanks @nishaatr for mentioning this feature request! We currently don't have an ETA for this feature yet, but will keep this issue open, and if others would like to see this, please give a thumbs up.

**Comment by dansiegel** [comment]
this would be a really powerful feature... any updates on this?
