### ISSUE TITLE
App Center Push Xamarin Failed to install

### ISSUE THREAD

**Issue by ColdstarJoey** [microsoft/appcenter#1213]
Hi when i try to install App Center push on the nuget packages window it says it can not install.

the error i get is:

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	NU1107	Version conflict detected for Xamarin.Android.Support.v7.AppCompat. Install/reference Xamarin.Android.Support.v7.AppCompat 28.0.0.1 directly to project ServiceTimber.Android to resolve this issue. 
 ServiceTimber.Android -> Xamarin.Forms 4.2.0.709249 -> Xamarin.Android.Support.v7.AppCompat (>= 28.0.0.1) 
 ServiceTimber.Android -> ServiceTimber -> Microsoft.AppCenter.Push 2.1.1 -> Xamarin.Android.Support.v7.MediaRouter 26.0.2 -> Xamarin.Android.Support.v7.AppCompat (= 26.0.2).	ServiceTimber.Android	C:\Users\Joeey\Documents\XamarinApps\ServiceTimber\ServiceTimber\ServiceTimber.Android\ServiceTimber.Android.csproj	1

**Comment by amchew** [comment]
Thanks @coldstarjoey for reporting this. @jwargo would you mind taking a look?

**Comment by jwargo** [comment]
@ColdstarJoey there's a version conflict in your project and instructions in the error message for how to resolve it. the best way to get help with this is to contact our support team - just click the blue chat button in the lower-right corner of any App Center page and start a conversation - that connects you directly with our dedicated support team.
