### ISSUE TITLE
AppCenter iOS SDK integration generates compiler warnings

### ISSUE THREAD

**Issue by jcavar** [microsoft/appcenter#1215]
Hello,
After integrating AppCenter SDK via CocoaPods I am getting a bunch of similar warnings:
`warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.runner/ModuleCache/3P60SF4AFYDAA/MachO-50MILLCRORLA.pcm: No such file or directory`

It seems that other people had similar issues and fixed it by disabling module debugging:

https://github.com/OneSignal/OneSignal-iOS-SDK/pull/443

**Comment by amchew** [comment]
Thanks @jacavar for reporting this. @elamalani would you mind taking a look?

**Comment by dermaaarkus** [comment]
We experiencing the same issue. Its really annoying, because it generates multiple warnings when building like:

```
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/1B76CAT92BTRK/Foundation-OIS75AKBYQKF.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/1B76CAT92BTRK/Foundation-OIS75AKBYQKF.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
```

**Comment by kaybutter** [comment]
Looks like this issue: https://forums.swift.org/t/swift-behavior-of-gmodules-and-dsyms/23211

**Comment by dermaaarkus** [comment]
@elamalani since you got mentioned 11 days ago, is there any chance to fix this soon? Looks like an easy fix disabling debug information in your productive code

**Comment by dermaaarkus** [comment]
Or @patniko ?

**Comment by clpolet** [comment]
Hi there, these warnings are known issues. It's fixed by this PR: https://github.com/microsoft/appcenter-sdk-apple/pull/1836 and will be part of the next release.

**Comment by dermaaarkus** [comment]
@jcavar it is fixed, do you like to close the issue?

**Comment by jcavar** [comment]
Yes, thank you. Looking good now!
