### ISSUE TITLE
Unable to Mark issue as Closed

### ISSUE THREAD

**Issue by jcavar** [microsoft/appcenter#1216]
Hello,
I am trying to mark Crash Report issue as closed in web interface, but not able. Here is video of it:
[failed-to-close.mov.zip](https://github.com/microsoft/appcenter/files/3740259/failed-to-close.mov.zip)

**Comment by amchew** [comment]
Thanks, @jacavar for reporting this. @winnieli1 would you mind taking a look?

**Comment by winnieli1** [comment]
Hi @jcavar! It looks like your status filter is set to All which means even issues you mark as Closed will appear in the table. Can you change the status filter to Closed and see if the issue shows up?

![image](https://user-images.githubusercontent.com/8868628/67314196-20ec6080-f4b9-11e9-9acb-9fb75625f126.png)

Thanks!

**Comment by jcavar** [comment]
Oh, that is right! Thank you.
