### ISSUE TITLE
Support group email for the distribution group

### ISSUE THREAD

**Issue by joyl1216** [microsoft/appcenter#1217]
**Describe the solution you'd like**
Support group email for the distribution group. Instead of putting bunch of email address in the distribution group, I would like to use the group email address, which would cover the whole team by putting one email address.

**Describe alternatives you've considered**
If not, can I share the email list from one app in App Center to the other app? Or maybe just export the email list and import?

**Additional context**

**Comment by amchew** [comment]
Thanks @joyl1216 for reaching out. You can add an [AAD group to the destination of your distribution group](https://docs.microsoft.com/en-us/appcenter/distribution/groups#adding-azure-active-directory-aad-groups-to-a-distribution-group) today. Would this work for you?
