### ISSUE TITLE
Debug|iPhoneSimulator not available for iOS build - just for Android and Xamarin.UITest builds!

### ISSUE THREAD

**Issue by stuarth-inova** [microsoft/appcenter#1219]
Before updating Xcode to 11.1, and updating Visual Studio for Mac Community edition (see below for a copy/paste from VS's About dialog) to the latest suggested stuff re: Xamarin.UITest, I could select build targets like "Debug|iPhoneSimulator" for all platforms. Now, I can only select it for every platform *except* iOS!! Here are screen shots showing the issue:

<img width="584" alt="Screen Shot 2019-10-17 at 6 39 53 PM" src="https://user-images.githubusercontent.com/2287831/67053041-3145b980-f10e-11e9-96f6-b170b59942dc.png">

<img width="559" alt="Screen Shot 2019-10-17 at 6 39 32 PM" src="https://user-images.githubusercontent.com/2287831/67053051-39055e00-f10e-11e9-8a13-64bb2508bc3e.png">

=== Visual Studio Community 2019 for Mac ===

Version 8.3.4 (build 8)
Installation UUID: 33998536-035a-4b58-95d2-c4caec0e6d2d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.2.401
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.2.6
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.1 (15405)
Build 11A1027

=== Xamarin.Mac ===

Version: 6.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin.iOS ===

Version: 13.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin Designer ===

Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

=== Xamarin.Android ===

Version: 10.0.3.0 (Visual Studio Community)
Commit: xamarin-android/d16-3/4d45b41
Android SDK: /Users/stuartholme/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@5608fe0abb3
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/stuartholme/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:20 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:44 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803040008
Git revision: 8da5857bc3d33e5667cacaab3bd1ab55375ed3e3
Build date: 2019-10-14 18:26:13+00
Build branch: release-8.3
Xamarin extensions: 61c91e660a01512a3b8187c749fd3bccc75a2bf4

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by stuarth-inova** [comment]
Note that "Project -> Active Configuration" has all possible options, but when on iOS and you try to select "Debug|iPhoneSimulator" from the drop-down menu, nothing happens.

**Comment by amchew** [comment]
Hi @stuarth-inova! Thanks for sharing your feature request. I apologize, but I don't think I got your scenario yet. Would you mind elaborating more on how it applies and App Center and what you'd like us to change? 

It seems to me that the feedback was more for [VS for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/ide-tour?view=vsmac-2019). If so, you can click that link and scroll to the bottom, and leave a feedback.

**Comment by VladislavAntonyuk** [comment]
It is expected behavior. You select debug and then you can choose emulator or device. So if you choose emulator your build will use Debug|iPhoneSimulator otherwise Debug|iPhone

**Comment by VladislavAntonyuk** [comment]
It is how VS for Mac displays configuration. VS for Windows will show you iPhoneSimurator and iPhone

**Comment by stuarth-inova** [comment]
I can pick iPhoneSimulator for Android but not for the iOS build, and
you’re saying this is “as designed”? That makes no sense at all.


Stuart

**Comment by VladislavAntonyuk** [comment]
IDE automatically choose Platform depends on your choice (Simulator or device)

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
