### ISSUE TITLE
Silence notifications when releasing

### ISSUE THREAD

**Issue by patniko** [Microsoft/appcenter#122]
Distributing a release without notifying testers. Can be done via API or UI. 

<img width="597" alt="image" src="https://user-images.githubusercontent.com/7900087/53670810-d9b31600-3c30-11e9-8fbe-8ec8cff995d4.png">

**Comment by lumaxis** [comment]
This has shipped and is now available both in our UI and through the APIs [[1](https://openapi.appcenter.ms/#/distribute/releases_addDistributionGroup)] [[2](https://openapi.appcenter.ms/#/distribute/releases_addTesters)]! 💪🏼
