### ISSUE TITLE
Show UserId On Reports Page

### ISSUE THREAD

**Issue by bobdoe132** [microsoft/appcenter#1220]
The Reports page for a crash group only has three columns. Device, OS, Date.

It would make life easier if the page would also list userIDs and allow us to sort by userIDs so that it can be seen at a glance.

Currently you have to investigate each report, make note of the userIDs you're interested in, make groups for those userIDs and then you can see them grouped. This is cumbersome.

Hockeyapp already supports this so it's lost functionality.

**Comment by amchew** [comment]
Thanks @bobdoe132 for sharing! FYI for @winnieli1 ^

**Comment by winnie** [comment]
Hey @bobdoe132 - we just added a few new columns to the crash reports page including a User ID column. 

![image](https://user-images.githubusercontent.com/8868628/76965257-5e370c00-68fa-11ea-8776-78e4b196c15f.png)


Closing this issue but let me know if you have any questions. Thanks!
