### ISSUE TITLE
Auth and Data SDK's should support UWP/Windows apps as a first class citizen - only iOS and Android are supported today

### ISSUE THREAD

**Issue by jimmccurdy** [microsoft/appcenter#1221]
**Describe the solution you'd like**
Auth and Data (Cosmos DB) SDK's should support UWP/Windows apps as a first class citizen - only iOS and Android are supported today.

**Describe alternatives you've considered**
There are no real alternatives right now, other than not using App Center for Auth and Data (Cosmos DB)

**Additional context**
UWP is an essential part of the dev cycle and is vital for many enterprise consumers of Xamarin apps.

**Comment by amchew** [comment]
Thanks @jimmccurdy for letting us know! UWP is the next platform we plan to support and on our roadmap. It's on our backlog right now, but there's no firm ETA. We'll keep this ticket open - and for folks who are interested, please feel free to comment/give it a thumbs up. 

Thanks!

**Comment by amchew** [comment]
Hi all! Keeping everyone updated, there’s still no ETA on supporting UWP for Auth and Data. I’ll close this thread for now, please re-open or comment if you’ve any questions.
