### ISSUE TITLE
App Bundles support for distribution and dynamic feature support for testers and distributors 

### ISSUE THREAD

**Issue by Vikaass** [microsoft/appcenter#1222]
Do Appcenter supports App Bundles for distribution and dynamic feature support for testers and distributors ?

**Comment by amchew** [comment]
Hey @Vikaass thanks for reaching out! We'll get back shortly, fyi @botatoes ^

**Comment by Vikaass** [comment]
@amchew @botatoes any updates ?

**Comment by amchew** [comment]
Hey @Vikaass, thanks for checking in again! Adding @dimazaid who will be able to share more as Bo is OOF.

**Comment by dimazaid** [comment]
Hello @Vikaass 👋 - We do not support AAB for dynamic loading and beta distribution. We only support AAB distribution via Google Play store. 
We also support AAB in the App Center Build service.
