### ISSUE TITLE
Apple TV Distribution

### ISSUE THREAD

**Issue by MattiasBurstrom** [microsoft/appcenter#1226]
**Describe the solution you'd like**
Distribution support of Apple TV apps.

**Describe alternatives you've considered**
So far we've been using HockeyApp and have not been looking at any other solution besides TestFlight but it doesn't support AdHoc builds.

**Additional context**

We have been using HockeyApp for tvOS app distribution and I've been expecting support for it to be in AppCenter as well since I was told that you're aiming to support everything HockeyApp has but so far it's not been added, and looking at the platform support matrix it's the only platform without distribution support. Will tvOS be supported before HockeyApp eol?

https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix

Thanks!

**Comment by amchew** [comment]
Thanks @MattiasBurstrom for letting us know! We unfortunately have no ETA for this, but will leave this open to keep track of interest. @botatoes fyi ^

**Comment by mattmartindale** [comment]
Really looking forward to this feature!  We have testers that need to test tvOS builds, so our current solution is manually installing each build for them (not ideal).  Would love a dedicated tvOS app that we can use to install builds (like how TestFlight does it)
Thanks guys~

**Comment by stodirascu** [comment]
+1 to reanimate this please

**Comment by tgkess1018** [comment]
another +1 too
