### ISSUE TITLE
Enable In-app updates for WPF Applications (feature parity with HockeyApp)

### ISSUE THREAD

**Issue by Mostlypyjamas** [microsoft/appcenter#1228]
**Describe the solution you'd like**
We would like to use AppCenter to provide in-app notifications of our WPF applications. 

On Startup, or on demand (e.g. from a "Check For Updates" menu item) we should be able to check for new public releases of our application, then have these automatically downloaded and the installation started. We distribute our applications using MSI or sometimes setup.exe and use standard Windows Installer deployments.

**Describe alternatives you've considered**
I see that Winsparkle is now supported for AppCenter, but native built in support using Appcenter.Distribute would be much more preferable as it keeps behaviour the same as for mobile app development.

**Comment by Oddj0b** [comment]
Thank you for requesting in-app updates for WPF apps. My colleague will take it into consideration, in the meanwhile, we evaluate feature request by reactions. If we get enough :+1: it will be considered for our backlog.

**Comment by usamakhanaspect** [comment]
Can we keep our WPF applications on HockeyApp until this feature is added? 

I use the call HockeyClient.Current.CheckforUpdatesAsync(), this will stop working if our apps transition to Appcenter.

**Comment by OzBob** [comment]
Support for Sparkle and therefore WinSparkle feeds is 'closed' #202 
I am now investigating how to add WinSparkle and integrate it into the App Center workflow.

**Comment by benwilkinson** [comment]
This would be super useful
