### ISSUE TITLE
Track activations (new installs)

### ISSUE THREAD

**Issue by jbrodriguez** [microsoft/appcenter#1229]
**Describe the solution you'd like**
I would like to get a report showing how many new installs happened daily, weekly, monthly

**Describe alternatives you've considered**
A way to download all data, to perform this in house

**Additional context**
N/A

**Comment by Oddj0b** [comment]
Thank you for your request. At the moment we're showing installs per distribution group in the overview tab, can you help me understand how the data you are looking for is different?

**Comment by jbrodriguez** [comment]
Thanks for the reply !

In the overview tab, I see the following, not sure if that's what you were referring to.

![Screen Shot 2019-10-21 at 17 13 49](https://user-images.githubusercontent.com/1305422/67247188-36647a80-f426-11e9-842d-8f5ee38a7a05.png)
