### ISSUE TITLE
NUnit 3 support

### ISSUE THREAD

**Issue by patniko** [Microsoft/appcenter#123]
We're finally adding support for NUnit 3 for Xamarin.UITest. We will be supporting NUnit 2 and 3 in the cloud, but you can finally upgrade in Visual Studio.

**Comment by ssidizc** [comment]
After Upgrading to NUnit 3,  will it support Local Test Run?

**Comment by Oddj0b** [comment]
@ssidizc Yes! You will be able to run local NUnit 3 UITests.

**Comment by DrakeNash** [comment]
exist some ETA for this upgrade?

**Comment by developer9969** [comment]
Hi any news on upgrade ? Reply very much appreciated

**Comment by Oddj0b** [comment]
It is still in the works, the team is still squashing and developing.

**Comment by jwhiteDev** [comment]
Hi All, there is a pre-release of this available now. Go check it out, let us know how it looks. https://www.nuget.org/packages/Xamarin.UITest/3.0.0-dev1

**Comment by MrAusnadian** [comment]
It seems like NUnit 3 support was removed from App Center (At least via the appcenter-cli) recently, however I cannot find any information on why. Can someone please provide an update on this?

**Comment by jwhiteDev** [comment]
@MrAusnadian what issues are you seeing with the CLI? It should still work, at least it was working for me last week when I last ran an upload.

**Comment by King-of-Spades** [comment]
I have successful test uploads using NUnit 3 from within the last 24 hours, @MrAusnadian the exact CLI version & error message you are seeing would help with debugging this issue.

**Comment by MrAusnadian** [comment]
Sorry for the confusion. I think it may have been a local environment issue. I just attempted to reproduce it and was not able to.
