### ISSUE TITLE
Silent Login/authentication

### ISSUE THREAD

**Issue by curelom** [microsoft/appcenter#1230]
**Describe the solution you'd like**
Would like a way to silently login if the user has logged in previous session.  If the user has not, then it should fail and should not bring up a login for the user.  When new users come in, don't want them to see a login first off, but rather show them why the app is so great that they'd want to log in.  At the same time, would like the existing users to not have to see login.

**Comment by curelom** [comment]
saw this is repeat of  #1151

**Comment by amchew** [comment]
Hey @curelom, thanks for reaching out! If you’d like this feature, you can give a thumbs up to #1151. 

For your scenario, you can do that today, but it's not exactly elegant.

To do so,

call the signIn() method (for example, in the Auth Andriod SDK)
In the else statement of the signIn() method, you can edit the code to modify the user experience when the user has signed in to show an alternate screen, etc. The signIn UI wouldn't appear again: if the app calls signIn again, the SDK shows the sign-in UI again only if the saved sign-in information expired or was revoked by the authentication server.

The feature you requested is on our backlog, but ETA so far, unfortunately.
