### ISSUE TITLE
Analytics Webhook

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#1232]
Hi,

It will be great if you add and analytics webhook to the AppCenter

Thanks,
Jassim

**Comment by jwargo** [comment]
@jrahma Can you please explain how you'd use this? What triggers/events are you expecting that would fire this web hook?

**Comment by jrahma** [comment]
@jwargo this will allow to have own dashboards, notifications and alerts instantly. It should have the details of users and sessions in rows

**Comment by jwargo** [comment]
@jrahma I'm sorry, but I don't understand how this relates to webhooks. I'm asking what events in Analytics you want to trigger a webhook.

**Comment by jrahma** [comment]
I am referring here to row data for visits' event for example, so when a visit is triggered then user can capture the row data and send it through webhook to a URL service for monitoring or analysis..
