### ISSUE TITLE
Carthage support is not documented in the "Getting started" view for macOS

### ISSUE THREAD

**Issue by sindresorhus** [microsoft/appcenter#1233]
Carthage support was added in https://github.com/microsoft/appcenter-sdk-apple/issues/1226, and it's documented in https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/macos, but there's no mention of it in the AppCenter UI in `https://appcenter.ms/users/<username>/apps/<AppName>/`

It only mentions Cocoapods:

<img width="787" alt="Screenshot 2019-10-20 at 16 19 07" src="https://user-images.githubusercontent.com/170270/67157380-5f690a80-f355-11e9-8062-61e780311ede.png">

**Comment by blparr** [comment]
Thank you! We are improving our landing experience and will take this into consideration.

**Comment by phranck** [comment]
@blparr What is the current status of this issue? Nine months gone already, unfortunately there is no change. The landing page still shows only CocoaPods integration.

**Comment by DmitriyKirakosyan** [comment]
Hi @phranck and @sindresorhus 

Currently getting started page for all applications on Portal contains a single option of integration (the most popular). All other options you can find in [AppCenter Docs](https://docs.microsoft.com/en-us/appcenter/sdk/).
Do you feel it is still worth displaying all integration options on the application page?

**Comment by sindresorhus** [comment]
I think it's useful to display all options, but if there can only be a single option there, I would definitely show SwiftPM.

**Comment by wisdeom** [comment]
Hi all! We appreciate your feedback. This helps us shape the product to better serve our mobile developers. For the time being, we want to take this idea into the yellow pad findings as this could potentially need an entire redesign of the landing page. 

Currently, we support Cocoapods, Carthage, and SwiftPM integration for Swift and Objective-C. We want to provide the best landing experience without complicating tabs, yet with enough information. We didn't want to bombard with too much information for those who're completely new. However, we definitely heard you and want to come up with a better UX for all demographics. Thanks again for sharing your feedback with us!
