### ISSUE TITLE
Build Overview Page Feature Request

### ISSUE THREAD

**Issue by brad-dixon** [microsoft/appcenter#1235]
VSTS (DevOps) currently has a feature that displays all of the current builds in progress, those queued and those that had previously completed (in a timeframe) for the given project.

This same functionality in AppCentre would be highly useful at the organisation level with consideration to security.

I sometimes find myself with x amount of Chrome windows open trying to keep on top of what is building.  If you consider that there are potentially multiple branches building at the same time on a single app, it can mean I need quite a few pages open.

It's also a little intense in its current state because the build status for an individual job is buried down around 4 levels ... Org / App / Build / Branches.

Something to think about anyway.

Thanks for listening.

Brad

**Comment by Oddj0b** [comment]
Hi Brad, thank you for your feature request. My colleague @nilofer will run it from here, however, it helps a lot if this Github issue gets more :+1: reaction.
