### ISSUE TITLE
Wildcard SSL certificate expiration preventing application initialisation

### ISSUE THREAD

**Issue by ugl-rian** [microsoft/appcenter#1236]
The wildcard SSL certificate for appcenter.ms has expired.

Apps utilising the AppCenter SDK do not initialise correctly due to an SSL validation check failure when attempting to access config.appcenter.ms

![image](https://user-images.githubusercontent.com/54877157/67169556-b1fb0300-f3f7-11e9-8fe6-e451610d84fd.png)

**Comment by yoannchaudet** [comment]
Now that's embarrassing.

We did rotate this certificate a while ago but omitted this endpoint (which is a CDN). The new certificate is being propagated through the network already.

Sorry for that.

**Comment by ugl-rian** [comment]
Thanks @yoannchaudet - I can confirm the new cert is now available and valid.
