### ISSUE TITLE
Display build number in slack message

### ISSUE THREAD

**Issue by nickhung13** [microsoft/appcenter#1237]
**Describe the solution you'd like**
We moved our project from HockeyApp to App Center. I integrate slack to send message when app was uploaded to App Center. But it only displays version name without build number.

**Additional context**
<img width="459" alt="hockeyapp" src="https://user-images.githubusercontent.com/20365381/67187530-fcdb4180-f41c-11e9-99f3-1f476a157898.png">

<img width="298" alt="appcenter" src="https://user-images.githubusercontent.com/20365381/67187588-18464c80-f41d-11e9-83f4-e31a578364ec.png">

**Comment by Oddj0b** [comment]
Thanks for making a feature request, my colleague will give it a look in the future. Depending on the work involved in supporting a feature, we might not be able to implement until there's enough :+1: reactions.

**Comment by triplef** [comment]
This is impacting us as well. During development of an update the version number usually stays the same while only the build number changes. Not seeing the build number in the notifications makes it difficult to cross-reference builds using the notification, as one always has to first click on the link in order to see the build number.

**Comment by triplef** [comment]
We’d still very much like to see this implemented.

Simply adding the build number in parentheses behind the version number would be sufficient. Doesn’t seem like this would involve a lot of work @Oddj0b.

**Comment by nickhung13** [comment]
My workaround is I add the build number into release notes.

```
notes = "[#{your_env}(#{your_BUILD_NUMBER})]\n#{changelog}" 
```

and put the notes into your opts call 

```
appcenter_upload(opts)
```

**Comment by triplef** [comment]
Bump

**Comment by BrandonWalker88** [comment]
Bump

**Comment by BrandonWalker88** [comment]
Any word on an update?
