### ISSUE TITLE
Sparkle feed URL fails to redirect in some circumstances

### ISSUE THREAD

**Issue by invariant** [microsoft/appcenter#1238]
As discussed in issue #202, the HockeyApp Sparkle feed URLs now redirect to the equivalent App Center feed.

However, depending on the form of the HTTP request used to access the Sparkle feed, the HockeyApp sparkle URL sometimes erroneously return a `200 OK` with old data.

Specifically, as far as I can tell, it seems to depend on the contents of the `Accept: ` header. These are the combinations I have tested.

`Accept: ` Header | Result | Notes
---- | --- | ----
Not present | 200 OK and old data ❌  | This it what happens when you naively `curl` the feed.
`Accept: ` | 301 redirect ✅ |
`Accept: */*` | 200 OK and old data ❌  | This accept header is used by some versions of Sparkle in the wild.

The specific feed URL I used for the tests above is `https://rink.hockeyapp.net/api/2/apps/58adb6c5bea28ffe22f304f2f383d089`.

Please note that this bug means that version of apps out in the wild (including my own) are unable to update.

**Comment by Oddj0b** [comment]
Thanks for reporting the bug @invariant. Please allow some time because of time zones for my colleagues to look into it.

**Comment by Soph** [comment]
@invariant Thanks for reporting this. We rolled out a fix and the redirect should now also work in the case the feed is requested for a macOS app but no accept headers are send. Please let us know if you see any issues.

**Comment by invariant** [comment]
Just tested now, the redirect is working and my problem is solved. Thank you.
