### ISSUE TITLE
Exposing yaml piplines

### ISSUE THREAD

**Issue by digital-flowers** [microsoft/appcenter#1240]
**Describe the solution you'd like**
After checking out many issues in your repository I think one feature can solve most of these issues, is by allowing overriding your default pipeline by creating a `ci` folder with YAML files to override specific tasks, after migrating from `Circle/Ci` to AppCenter, I really like how AppCenter work and I think it's one of the best web apps UX I have ever used, but having the ability to override that single pipeline template is something really necessary and I believe if it's fixed along with this amazing UX  AppCenter will be ahead of any other build systems.

**Describe alternatives you've considered**

**Additional context**

**Comment by nrajpurkar** [comment]
Thanks for the feature request @digital-flowers. We do use a build template and exposing this template to those configuring builds would allow the ability for more complex build scenarios to be supported. We'll continue to track this issue and total interest.

**Comment by nrajpurkar** [comment]
This is also similar to #589

**Comment by digital-flowers** [comment]
Thanks @nrajpurkar, you are right it's similar I will close this issue :)
