### ISSUE TITLE
Please provide global user administration per organization

### ISSUE THREAD

**Issue by lbrownell-gpsw** [microsoft/appcenter#1242]
**Describe the solution you'd like**
Would like an overarching Users page for org Admins.  In this would be listed all collaborators, team members and distribution group testers.  While there are a lot of features and complexity that such a page could include, for now it would be sufficient to simply add the ability to remove users from the organization.

Right now, I need to offboard an employee who left.  This includes removing their access to all our App Center builds, etc.  There is no simple way to do that.  The user in question isn't a collaborator, or on any teams, but is in several distribution groups.  Our only recourse is to go, one by one, thru all the distribution groups, find the user, and delete there.  Not. Good.

**Describe alternatives you've considered**
See above.  I'd asked via help chat if there is some straightforward way to do this via API/CLI. The answer was no, but we could likely build a script to automatically walk all distribution groups.

**Additional context**
This capability existed in HockeyApp.  It's a major regression.

**Comment by jbrozen** [comment]
Yes! This is absolutely needed

**Comment by Brantone** [comment]
Similar issue to this : https://github.com/microsoft/appcenter/issues/1204

**Comment by lbrownell-gpsw** [comment]
Note:  Kudos to the API team.  It was easy to create a python script finds a user (by email address) as a organization member, and in all distribution groups, and which removes said user from all.

Doesn't mean that global user administration *isn't needed*, just that it's not critical specifically for this request.

And how often do your devs get a thumbs up?  👍

**Comment by ScottArbeit** [comment]
@lbrownell-gpsw Thank you for writing this up. We want to add this kind of feature to App Center, and we will (not sure of the timing yet).

In the meantime, for anyone who wants it, I just threw together a utility to show users and distribution groups in an organization (and please submit PR's if there's anything you see missing) at https://github.com/ScottArbeit/ListAppCenterUsers. 

And we're going to keep this issue open to continue to track interested so we know how to prioritize the work.

**Comment by tomachi** [comment]
Interested. Lots of employees transitioned from Hockeyapp and now in order to remove them we need to check each and every app and distribution group and remove them . Removing them from one is not removing them from the other.

**Comment by tomachi** [comment]
> Note: Kudos to the API team. It was easy to create a python script that finds a set of users (by email address) as organization members, and in all distribution groups, and which removes said users from all.
> 
> Doesn't mean that global user administration _isn't needed_, just that it's not critical specifically for this request.
> 
> And how often do your devs get a thumbs up? 👍

Can you share your script?
