### ISSUE TITLE
It would be convenient to have an unchanging URL pointing towards to latest release build

### ISSUE THREAD

**Issue by ezathashim** [microsoft/appcenter#1243]
**Describe the solution you'd like**
I have links on my website that allow users to download the latest release build of my application.

Currently, I have to manually copy the download URL for the latest build in AppCenter and paste it into my website each time I make a release build.

It would be convenient to have a single unchanging URL for downloading the latest release build so that I could avoid the copy/paste system, which is error prone.

**Describe alternatives you've considered**
No other solutions except for Copy/Paste. I guess I could get the latest downloadable URL from the Sparkle App Cast, but I do not do web development. Maybe your Sparkle AppCast system could generate a redirect URL every time a release build is uploaded? 

**Additional context**
Thanks!

**Comment by justinhorner** [comment]
You could use the API to fetch the latest download release URL for you:

https://openapi.appcenter.ms/#/distribute/releases_getLatestByDistributionGroup

**Comment by ezathashim** [comment]
It is a nice API, and I've now used it to fix another problem I had (thanks!).

However, using it on a website is a bit of a pain since I would need to parse the fetch, etc, and I'm not a web developer. It would be good to have a 'fixed' URL for the latest release download for a particular app that I can just plug in to my website.

**Comment by yigitcanyurtsever** [comment]
Hey all,

Here at Zeplin, we are using a short link to download the latest version of the app. This allows us to just share the link with our users. The short url is https://zpl.io/download-mac  and it redirects to https://rink.hockeyapp.net/api/2/apps/8926efffe734b6d303d09f41d90c34fc?format=zip 

Compared to using the API to get the download url, having a static link is much more convenient. It’d be great if we can have the same functionality as HockeyApp had as we are finalizing our transition onto AppCenter. I’m guessing we are not the only ones facing this issue and it’d be helpful for others as well.

We also rely on having direct download links for specific releases (not just the public page) as we try to support our users on previous OS versions but that is another issue I guess. I know we can use the API for this as well but it would be nice if we can copy it from the releases tab on appcenter.ms.
