### ISSUE TITLE
Add support for deobfuscation of stracktraces, obfuscated with DexGuard tool

### ISSUE THREAD

**Issue by mikegr** [microsoft/appcenter#1244]
**Describe the solution you'd like**
AppCenter can deobfuscate stacktraces that originated from a DexGuard obfuscated build. 
Hockey supported this. 

**Describe alternatives you've considered**
You can manually deobfuscate on commadline with jar from DexGuard
> java -jar /var/DexGuard/lib/retrace.jar -verbose mapping.txt trace.txt
or use https://github.com/tfKamran/dex-guard-retracer

**Additional context**
The obfuscated stacktraces from DexGuard obfuscated builds can not be deobfuscated using the regular ProGuard retrace tool. Instead it requires the DexGuard library or other improved retracer.

**Comment by Oddj0b** [comment]
Hi and thanks for the feature request. I have tagged my colleague who will consider it for the backlog, alternatively if it gets enough :+1: reactions it will be considered as part of the larger backlog.

**Comment by winnie** [comment]
Hi! We recently added deobfuscation support for DexGuard. Closing this issue for now but please start a support ticket if you run into any issues. Thanks!
