### ISSUE TITLE
Capacitor Support for Code Push

### ISSUE THREAD

**Issue by Raedtelpme** [microsoft/appcenter#1245]
I would like to request capacitor support for Code push.  We are looking to migrate from Cordova to Capacitor. However, we are reluctant since Code Push is not yet supported. We really value having Code Push as a part of our application, and we would love to see a capacitor plugin created for Code Push.

**Comment by Oddj0b** [comment]
Thank you for your request. Looks like there's good progress on reactions already :D

**Comment by dwasyluk** [comment]
Any updates here? Our team is trying out https://github.com/areo/capacitor-codepush in the interim.

**Comment by richardkshergold** [comment]
@dwasyluk - how have you got on with that plugin?  I was looking at AppFlow for live deployments of our ionic/capacitor app and I assumed App Centre would provide that until I saw this issue - does that plugin work well for you?

**Comment by Pitouli** [comment]
Any update?

**Comment by pkvince** [comment]
@dwasyluk Did you have any success with the plugin you mentioned?

**Comment by johnborges** [comment]
Take a look at [this](https://github.com/capacitor-community/proposals/issues/43) issue. Some folks are working on this.

**Comment by riderx** [comment]
You can migrate to Capgo : https://capgo.app/blog/appcenter-migration/
