### ISSUE TITLE
Manual create bug in diagnostics

### ISSUE THREAD

**Issue by dalemyers** [microsoft/appcenter#1246]
**Describe the solution you'd like**
There is the ability to have App Center automatically open bugs with a configured bug tracker, but it would be useful to be able to keep that off, but have a button on each crash group which can be clicked to open a bug. 

**Describe alternatives you've considered**
N/A

**Additional context**
This is what Hockey has.

**Comment by Oddj0b** [comment]
Thank you for feature request, I have renamed it to "Manual create bug in diagnostics." If you feel it's wrong, feel free to revert it.

**Comment by dalemyers** [comment]
Commenting to keep this open.

**Comment by dalemyers** [comment]
Commenting to keep this open.

**Comment by dalemyers** [comment]
Keeping this open.

**Comment by dalemyers** [comment]
Still an issue.

**Comment by dalemyers** [comment]
Still an issue.

**Comment by dalemyers** [comment]
Still an issue.
