### ISSUE TITLE
Azure DevOps bug tracker should not require project admin

### ISSUE THREAD

**Issue by dalemyers** [microsoft/appcenter#1247]
**Describe the solution you'd like**
To set up ADO for bug tracking, you need to use a project admin account. This is probably not the type of account you want to use for opening bugs. You should be able to use any account for this (even if a project admin account is used for configuration). 

**Describe alternatives you've considered**
Making our bot account a project admin - we don't want to do this though as it poses a security risk.

**Additional context**
N/A

**Comment by Oddj0b** [comment]
Thank you for the feature request. I have tagged a colleague who will triage it accordingly, have a great weekend.

**Comment by dalemyers** [comment]
Commenting to keep this open.

**Comment by dalemyers** [comment]
Commenting to keep this open. Again.

**Comment by dalemyers** [comment]
This is still an issue. @winnie any updates?

**Comment by dalemyers** [comment]
Still an issue.

**Comment by dalemyers** [comment]
Still an issue. And it looks bad that the bot is complaining about it being stale because no one is responding to the issue rather than it being me that isn't responding.

**Comment by dalemyers** [comment]
Still an issue.
