### ISSUE TITLE
Having a problem with auth on android

### ISSUE THREAD

**Issue by FultonBrowne** [microsoft/appcenter#1248]
I am getting a blank web page when I run the sign in, everything works in the web version of b2c, its, for what ever reason not working on android. the code on android appears to work fine it opens the link with all the info needed the page exists, when I opened the debugger it was a blank <body> tag. is there any possible causes, or common fixes for this?

thanks

**Comment by Oddj0b** [comment]
I'll ping a colleague who will look at it in the near future.

**Comment by FultonBrowne** [comment]
Thanks @Oddj0b, I was able to resolve the issue, but I am still confused about how.

**Comment by amchew** [comment]
Hey @fultonbrowne, thanks for reporting it! I just tried it on my android app, and it works for me. Sounds like the issue was already solved for you, yes? If you face this again, please let us know - we can work to debug.

**Comment by FultonBrowne** [comment]
Thanks, @amchew , will do.

**Comment by Oddj0b** [comment]
Sounds to me like this is closed. I think it's easier to open a new case if the problem re-appears.

**Comment by akamud** [comment]
If anyone else is having this problem, double check the redirect-uris configured for the App in Azure B2C. That was my problem.
