### ISSUE TITLE
AppCenter Data Local Debug using CosmosDB Emulator

### ISSUE THREAD

**Issue by fileman** [microsoft/appcenter#1250]
Add possibility to the SDK for AppCenter Data to connect Local Debug using CosmosDB Emulator

**Comment by Oddj0b** [comment]
Hi @fileman, thank you for your feature request. I have tagged my colleague and he will follow up if there's any question.

**Comment by Zakeelm** [comment]
@fileman Thank you so much for your request. We announced this week in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Auth and Data services later this year and recommending customers transition to Azure Active Directory B2C and Azure Cosmos DB instead. Let me know if you have any additional questions about this transition and i'll make sure to get them answered! Closing this issue.
