### ISSUE TITLE
Add Ability to enable Dark Mode in Xamarin.UITest programatically

### ISSUE THREAD

**Issue by MrAusnadian** [microsoft/appcenter#1251]
**Describe the solution you'd like**
I'd like to be able to programatically enable Dark Mode so that I can run Xamarin.UITests against both Light and Dark Mode. Something like this:

```
app.SetDisplayMode("Dark");
app.Screenshot("dark mode");
// Dark mode tests here

app.SetDisplayMode("Light");
app.Screenshot("light mode");
//Light mode tests here
```

**Describe alternatives you've considered**
I have not been able to find any options for enabling Dark Mode programatically. The only option I've been able to find is to manually switch the emulator to Dark Mode prior to testing, which cannot be done on App Center devices, so it's difficult to do this at scale.

**Additional context**
Our application is written in react-native, so I'd like the solution to work with both Xamarin and React-Native

**Comment by Oddj0b** [comment]
A really interesting scenario I haven't thought about yet. I tried to see if it was possible today in XCUITest and it didn't seem possible which makes it hard to achieve it in Xamarin.UITest.

**Comment by MrAusnadian** [comment]
Here’s an example implementation I saw. I’ll see how difficult it is to translate it to my needs. 

https://kazucocoa.wordpress.com/2019/10/19/appiumioshandle-dark-mode-via-process-arguments/

**Comment by MrAusnadian** [comment]
> A really interesting scenario I haven't thought about yet. I tried to see if it was possible today in XCUITest and it didn't seem possible which makes it hard to achieve it in Xamarin.UITest.

Do you know how I can start an app with process arguments in Xamarin.UITest?

**Comment by FinHorsley** [comment]
@MrAusnadian 

#### 1. Pass in Variables 
Pass custom parameters into a test using `Run Test With` -> `Custom Parameters`
<p align="center">
<img src="https://user-images.githubusercontent.com/10697741/73004095-a526ea80-3dfe-11ea-9d0d-3b6fe20fd3d1.png" width="300"/>
</p>
<p align="center">
<img src="https://user-images.githubusercontent.com/10697741/73006167-14eaa480-3e02-11ea-91f7-6a759c35aa69.png" width="300" />
</p>



#### 2. Get variables 
Get the arguments parsed into the test
``` csharp
var envVar = Environment.GetEnvironmentVariable("ENV_VAR");
Console.WriteLine(envVar);

// OUTPUT: false (the value we passed in above)
```

#### 3. Optionally
There's no guarantee that any arguments have been passed into your process. If the environment variable is null, return a default value instead
``` csharp
public string GetVariable(string name, string default = string.Empty)
{
    return Environment.GetEnvironmentVariable(name) ?? default;
}
```

**Comment by PhilOchu** [comment]
Another option is the use the backdoor feature provided by UITest to trigger the theme change in your app.
https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with/backdoors

NOTE - This does not change the device dark mode. Instead you would trigger your app to make a change to respond to the theme selection you provide. For Xamarin Forms this would help: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes

**Comment by MrAusnadian** [comment]
> Another option is the use the backdoor feature provided by UITest to trigger the theme change in your app.
> 
> https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with/backdoors
> 
> 
> 
> NOTE - This does not change the device dark mode. Instead you would trigger your app to make a change to respond to the theme selection you provide. For Xamarin Forms this would help: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes

This only applies if your app is written in Xamarin. Our app is react-native

**Comment by will-gluwa** [comment]
Would still like this functionality
