### ISSUE TITLE
Have App Details with '/v0.1/apps/{owner_name}/{app_name}/releases' API

### ISSUE THREAD

**Issue by ezathashim** [microsoft/appcenter#1253]
**Describe the solution you'd like**
- I would like to compile a 'Release Notes' file from the AppCenter API
- currently, when I use the API '/v0.1/apps/{owner_name}/{app_name}/releases', it allows me to fetch releaseIDs for each release, but the JSON does not contain 'Release Notes' information

**Describe alternatives you've considered**
- what I currently do is a 2-part fetch:
 1) I run '/v0.1/apps/{owner_name}/{app_name}/releases' and get a list of releaseIDs
 2) Them I iterate through each releaseID and do a fetch for each one using the API 'api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/releases/{release_id}' which gives me more detailed information, including 'Release Notes'

**Additional context**
- As you can see, I am forced to using multiple fetches to aggregate a 'Release Notes' document. It would be nice if the first API (or a new similar one) would include the 'Release Notes' when fetching the list of releases.

**Comment by Oddj0b** [comment]
thanks for the great write-up, which makes it easy to understand. I have tagged my colleague for follow-up or questions.
