### ISSUE TITLE
Problem connect apple account on appcenter

### ISSUE THREAD

**Issue by RenanDelfanti** [microsoft/appcenter#1254]
**Describe the solution you'd like**
I have problem to connect my apple account on appcenter, appcenter don't have option to recive verification code by like sms when i don't have my trusted device.

**Describe alternatives you've considered**
Make possible to get verification code account without trusted device, like sms.

**Comment by Oddj0b** [comment]
I believe this is a duplicate of #996 if not feel free to re-open.
