### ISSUE TITLE
Distribute functionality similar to HockeyApp

### ISSUE THREAD

**Issue by jsheetzati** [microsoft/appcenter#1255]
**Describe the solution you'd like**
Looking for AppCenter to support similar distribution functionality as HockeyApp. HockeyApp allowed us to configure Private download pages and Unrestricted Builds. With this implementation, our app is able to update itself provided it has a valid HockeyApp API Key. This works very well for our Internal Enterprise application that we distribute to end-users. Essentially we want Private Installation (only valid AppCenter users can install the application). If we send the application to a new user, they should be able to install the application and get In-App updates without an AppCenter account.

Ideally, if our application has an embedded AppCenter API key, it can get in-app updates like it did with HockeyApp.

**Describe alternatives you've considered**
We considered Public Distribution and adding end-users to AppCenter. Public Distribution does not work because it violates our client agreement so we cannot make  the installation page publically accessible. Adding end-users to AppCenter may work, but we do not want to add hundreds of users to AppCenter just to get In-App updates.

**Additional context**
This is the HockeyApp functionality we were expecting to retain with AppCenter. It is unfortunate that we thought this was going to be a smooth process, and that we would not lose functionality that we previously had with HockeyApp.

>By default, builds are unrestricted and can be downloaded anonymously through HockeySDK or the HockeyApp API. The reason for this anonymous access is that sandboxing on iOS and Android prevents HockeySDK from identifying the user. For a higher level of security, we recommend the following steps
https://support.hockeyapp.net/kb/app-management-2/how-to-restrict-app-and-build-access

**Comment by ariveraati** [comment]
@dimazaid Do you all have an ETA on this implementation? It is a roadblock for us using App Center in our production environment.

**Comment by jsheetzati** [comment]
With the announcement of retiring the HockeyApp SDK (https://github.com/microsoft/appcenter/issues/1840), any plans to introduce this functionality to AppCenter SDK before the November 13 date? 

@ahdbilal, you recommended that we use the HockeyApp SDK because it allows anonymous users to get in-app updates without requiring a login. The HockeyApp SDK allows us to have a private download page with unrestricted builds. 

Our use case is that we develop an internal iOS app. We have system support users who have AppCenter access to install the app on our corporate MDM managed devices. Our field users do not have access to AppCenter nor have a login to it. If we gave our field users access to AppCenter, they would be able to install our enterprise application on any device they want, which is not ideal and against our policy.

Are you planning to add a new update track that allows functionality similar to `MSUpdateTrackPublic`? However, we do not want to make the distribution group in AppCenter public as that means anyone could install the application. We just do not want to require an AppCenter login in order for in-app updates to work.

Thanks!

**Comment by jbrozen** [comment]
And why was this closed? This was a major gap between HockeyApp and AppCenter

Thanks

**Comment by fabiendem** [comment]
I don't work for them and still use AppCenter Distribute, but https://www.applivery.com/ is a good alternative and is very close to HockeyApp if needed. They have a lot of distribution methods.

**Comment by jbrozen** [comment]
> I don't work for them and still use AppCenter Distribute, but https://www.applivery.com/ is a good alternative and is very close to HockeyApp if needed. They have a lot of distribution methods.

Thanks! Looks pricey...guess you get what you pay for...

**Comment by jsheetzati** [comment]
Sorry, I wasn't sure anyone else was looking for this, and I found a workaround that seems to be working so far. Need to do a little more testing then I can share my solution. I reopened the issue in the mean time.

**Comment by jsheetzati** [comment]
Think my method is working and seems to avoid prompting for a user login. However, we are only using this for iOS, and I am not sure what the Android equivalent is. 

For iOS, I am using method swizzling to replace the functionality of MSKeychainUtil. If MSKeychainUtil returns a token for `MSUpdateToken`, it will not open Safari for the user to login.

1. Generate an AppCenter API read-only token
2. Create new Objective-C file

```objc
@interface NSObject (PrivateSwizzleCategory)

@end

@implementation NSObject (PrivateSwizzleCategory)

+ (void)load {
    Method original = class_getInstanceMethod(objc_getMetaClass("MSKeychainUtil"), @selector(stringForKey:statusCode:));
    Method swizzled = class_getInstanceMethod(self, @selector(swizzled_stringForKey:statusCode:));
    method_exchangeImplementations(original, swizzled);
}

- (NSString *)swizzled_stringForKey:(NSString *)key statusCode:(OSStatus *)statusCode {
    // hardcodes a token that way AppCenter SDK can prompt for updates
    // without this, AppCenter would pop open a Safari window so the user can log into AppCenter
    if ([key isEqualToString:@"MSUpdateToken"]) {
        return [AppSettingsObjc appCenterUpdateToken];
    }
    
    NSString* result = [(NSObject *)self swizzled_stringForKey:key statusCode: statusCode];
    return result;
}
@end
```
