### ISSUE TITLE
Support CLI/non-UI applications for macOS

### ISSUE THREAD

**Issue by sschilli** [microsoft/appcenter#1256]
**Describe the solution you'd like**
For macOS, AppCenter currently only supports/is tested on UI applications (it must be started in `applicationDidFinishLaunching` in the `AppDelegate`, which do not exist in non-UI apps). It would be great to support analytics for applications with no UI, such as a CLI app, as the information gleaned is still very useful despite the lack of UI.

**Describe alternatives you've considered**
No other popular analytics libraries seem to support this either in my research.

**Additional context**
N/A

**Comment by Oddj0b** [comment]
Thanks for your request, is this a request to have analytics available to CLI apps?

**Comment by sschilli** [comment]
@Oddj0b yes. Currently when building a basic CLI app (so no AppDelegate or UI), starting AppCenter does not work properly and analytics data doesn't seem to be collected/sent to the server.
