### ISSUE TITLE
Apple watchOS support

### ISSUE THREAD

**Issue by LukeCS** [Microsoft/appcenter#126]
**Describe the solution you'd like**
When archiving, it should support watchOS as if an App has watchOS extension it cannot build the iOS App, hence not being able to use the service.

**Comment by nrajpurkar** [comment]
Hi @LukeCS, are you building a Xamarin app? We support watchOS for native iOS and React Native. See our [post](https://blogs.msdn.microsoft.com/vsappcenter/announcing-ios-app-extension-and-watchos-support-in-visual-studio-app-center/) detailing this.

**Comment by LukeCS** [comment]
Hello! I am not building a Xamarin app, solely iOS and extensions. One of your colleagues told me you don't support watchOS and to post a feature request here. That link is helpful though so will try. Will update tomorrow. Thank you!

**Comment by LukeCS** [comment]
Can confirm I have followed the post and now worked successful. Thank a lot. :)  Closing this issue.

**Comment by nrajpurkar** [comment]
Glad to hear it!
