### ISSUE TITLE
Package installation should use npm ci instead of npm install

### ISSUE THREAD

**Issue by adelphes** [microsoft/appcenter#1260]
**Describe the solution you'd like**
React Native builds should use `npm ci` to install packages instead of `npm install`.

From the [NPM docs](https://docs.npmjs.com/cli/ci.html):

> npm ci
>
> This command is similar to npm-install, except it’s meant to be used in automated environments such as test platforms, continuous integration, and deployment – or any situation where you want to make sure you’re doing a clean install of your dependencies.

The reason is that `npm install` checks `package.json` and installs **the latest compatible version** of the dependant packages, whereas `npm ci` installs **the exact package versions** listed in `package-lock.json`.

In other words, running `npm ci` will always result in the same set of packages being installed, but `npm install` may randomly upgrade packages, depending on the version specified.

**Additional context**
Build logs where `npm install` is run:
```
#[section]Starting: yarn/npm install
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
[command]/bin/sh -c if [ -f yarn.lock ]; then { yarn install && yarn list --depth=0; } else npm install; fi
```

**Comment by florian-milky** [comment]
Any update on this? `npm ci` would also speed up the build and avoid installing unnecessary dependencies

**Comment by Subv** [comment]
This is still a thing that happens in 2022:

`[command]/bin/sh -c if [ -f yarn.lock ]; then { yarn install --network-timeout=600000 && yarn list --depth=0; } else npm install; fi`

I recently ran into a bug with a dependency because I didn't expect AppCenter to update it under the hood.
I believe this should be configurable at the build-level if maintaining backwards compatibility with the existing behavior is desired.

**Comment by quant-daddy** [comment]
No updates? Trying a microsoft product after a long time and it's disappointing to see these issues are not actively being fixed.
