### ISSUE TITLE
Ability to run tests on a build already in App Center

### ISSUE THREAD

**Issue by rjcollingham** [microsoft/appcenter#1261]
Currently using the appcenter cli I have to specify an app-path to a local apk or ipa file. It would be nice to be able to choose a build that has already been uploaded to App Center instead of having to use a local build.

**Comment by Oddj0b** [comment]
Are you thinking of builds that are available in Distribute or after they've been build using our Build service?

**Comment by rjcollingham** [comment]
Correct, I was thinking of the Releases available under distribute. I appreciate that ideally we need to incorporate automated testing in to our CI/CD pipeline, but where we are at the moment, our build teams upload builds to AppCenter for internal testing and our testing team can't run automated testing on those builds in AppCenter, they need to be provided with local .ipa / .apk files. It would be nice to run the CLI command and choose a release already on App Center.
