### ISSUE TITLE
App build retention

### ISSUE THREAD

**Issue by emartynov** [microsoft/appcenter#1263]
**Describe the solution you'd like**
I read that app build retention is just 250 builds. It is quite a lot.
however, we use AppCenter to easily distribute also production and acceptance version. For these types of builds I would like to keep binaries forever.

**Describe alternatives you've considered**
As an alternative please allow to pull builds to be archived.

**Comment by Oddj0b** [comment]
@emartynov  Would it be possible to distribute the build to a Distribution group, to keep them available?

**Comment by emartynov** [comment]
I don't think it is necessary for the distribution groups. It is for the case when you have some exotic bug when people are using super old build or migrating from it to new. For case when you want to reproduce something rare and time consuming.
