### ISSUE TITLE
Existing URLs to crash reports are broken

### ISSUE THREAD

**Issue by awBSH** [microsoft/appcenter#1264]
We have lots of existing crashes reported in our JIRA.

JIRA -> AppCenter:
After migrating an App, the existing URLs (HockeyApp) to the crash reports from JIRA are not being redirected to the respective crash report in AppCenter but only to the App overview. 
It's difficult for the developers to navigate to the crash report to retrieve more detailed information about the crash.

AppCenter -> JIRA:
In addition to that, the existing JIRA links no longer exist in AppCenter.

**Comment by Oddj0b** [comment]
Thanks for reporting the issue.

**Comment by derpixeldan** [comment]
@awBSH unfortunately the links won't work anymore because there's no mapping between HockeyApp and App Center crash groups.
