### ISSUE TITLE
Ability to identify users on a specific version

### ISSUE THREAD

**Issue by chschrae** [microsoft/appcenter#1266]
**Describe the solution you'd like**
I want to be able to identify users on a specific version.

**Describe alternatives you've considered**
I do not want to use push notifications as that is distracting in our case.
currently I've added a custom analytics event that will help me identify the user but it is independent of AppCenter. AppCenter clearly has a userId I just can't seem to find it in any of the telemetry.

**Comment by Oddj0b** [comment]
I don't see a feature request in what you're writing, our support should be able to help you. You can contact support through our portal.

**Comment by yoannchaudet** [comment]
Hello,

The User Id property is used for tagging Push and Diagnostics logs only.

You may use an event property like you are describing to inject a custom "user id" field. While our Analytics engine does aggregated counts only and will not let you query the information you are seeking, this is something you can do fairly easily with our [Export feature](https://docs.microsoft.com/en-us/appcenter/analytics/export).

You can configure Export to go to Application Insights (for instance) so you can query your raw logs from there.

**Comment by chschrae** [comment]
I do have it exported to app center. The issue becomes that I have no way to identify the user from the user id in the app center logs. I have the id, but I don’t know which user it corresponds to.

Chris

**Comment by yoannchaudet** [comment]
I was suggesting you emit yourself a custom event to track your own user identifier. Just like [here](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/xamarin#custom-events).

You can query your raw events when you configure [Export to Application Insights](https://docs.microsoft.com/en-us/appcenter/analytics/export).

**Comment by chschrae** [comment]
Right that is similar to what I am doing. I just want to be able to take advantage of the reports that AppCenter creates and shows in the portal. In that portal I can see # of users based on version and I can see a user ID for each user but there is no correlation. It would be nice to not have to do that separately.
