### ISSUE TITLE
App center api failed to upload ipa.

### ISSUE THREAD

**Issue by kumarGautamAramark** [microsoft/appcenter#1267]
Hi, 
I have written a script to use app center api to release a build. I am following app center api documentation. What I am doing is - 
**step 1:** Create upload resource. I get upload _id and upload_url.
**step 2:**  using upload_url and path of ipa, making another call to app center which will upload the ipa.
**step 3:** After the upload has finished, update upload resource's status to committed. In this i am passing the upload_id that i got in **step 1**. But app center api is throwing error:

**{"code":"no_upload_resource","message":"upload_id is not recognized. An Upload resource should be created first."}**

**Comment by Oddj0b** [comment]
hi @kumarGautamAramark have you contacted our customer service through the portal?

**Comment by kumarGautamAramark** [comment]
I have fixed this issue. This was due to adding extra quotes in the upload_url in my scripts. Thanks.
