### ISSUE TITLE
java.lang.IllegalStateException - SharedPreferencesManager.initialize

### ISSUE THREAD

**Issue by StinkyTowel** [microsoft/appcenter#1271]
Hello.  We released an update to our xamarin android app to open beta on 10/7/2019 (posted this issue in the wrong github initially - https://github.com/microsoft/app-center-app-xamarin/issues/3).  This release includes the first time we're using the AppCenter SDK (replaces HockeyApp).  We did not encounter any crashes in our test environment however, Google Play is showing the following: 

> **java.lang.IllegalStateException:** 
>   _at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:458)
>   at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:443)
>   at android.content.ContextWrapper.getSharedPreferences (ContextWrapper.java:178)
>   at com.microsoft.appcenter.utils.storage.SharedPreferencesManager.initialize (SharedPreferencesManager.java:45)
>   at com.microsoft.appcenter.AppCenter.finishConfiguration (AppCenter.java:749)
>   at com.microsoft.appcenter.AppCenter.access$600 (AppCenter.java:58)
>   at com.microsoft.appcenter.AppCenter$6.run (AppCenter.java:654)
>   at android.os.Handler.handleCallback (Handler.java:883)
>   at android.os.Handler.dispatchMessage (Handler.java:100)
>   at android.os.Looper.loop (Looper.java:214)
>   at android.os.HandlerThread.run (HandlerThread.java:67)_

This is occurring on **Android 9/10** OSs on the following devices:

- Galaxy   Note10+ (d2q)
- Galaxy Note9   (crownqltesq)
- Galaxy S10   (beyond1q)
- Galaxy S10+   (beyond2q)
- Galaxy S8   (dreamqltesq)
- Galaxy S9+   (star2qltesq)
- OnePlus 6   (OnePlus6)
- Pixel 2 (walleye)
- Pixel 2 XL   (taimen)
- Pixel 3 (blueline)
- Pixel 3 XL   (crosshatch)
- Pixel XL (marlin)

We call our AppCenter regsitration routines in the _OnCreate()_ method in _MainApplication.cs_

```
public override void OnCreate()
{
    // execute base oncreate           
    base.OnCreate();
    RegisterActivityLifecycleCallbacks(this);
    // changed due to update in CurrentActivityPlugin.
    CrossCurrentActivity.Current.Init(this);
    CrossFingerprint.SetCurrentActivityResolver(() => CrossCurrentActivity.Current.Activity);

    // register settings needed for the app
    RegisterSettings();

    // register app center needed for crash and exception logging
    RegisterAppCenter();
}
```

And _RegisterAppCenter()_

```
void RegisterAppCenter()
{
   var appCenterLoggerService = new AppCenterLoggerService(appCenterKey);
   //splat   
   Locator.CurrentMutable.RegisterConstant(appCenterLoggerService, typeof(IAppCenterLoggerService));
}
```
And _AppCenterLoggerService()_

```
public AppCenterLoggerService(string appCenterAppKey)
{
   if (string.IsNullOrEmpty(appCenterAppKey))
      throw new ArgumentNullException(nameof(appCenterAppKey), "The app center app key cannot be null or empty.");

   AppCenterAppKey = appCenterAppKey;
   AppCenter.Start(AppCenterAppKey, typeof(Crashes));
}

public void WriteExceptionLog(Exception ex, Dictionary<string, string> customProperties = null)
{
   AppCenter.SetUserId(UserId);
   Crashes.TrackError(ex, customProperties);
}
```
It is unknown if these are real crashes and affecting users as we have not rec'd any feedback yet.

Please advise on this issue and any recommendations to address/correct.

**Comment by StinkyTowel** [comment]
RE-posted here: https://github.com/microsoft/appcenter-sdk-dotnet/issues/1181

**Comment by SufiyaNidheesh** [comment]
This issue still exists while rebooting  in the latest lib - implementation "com.microsoft.appcenter:appcenter-crashes:4.3.1" even if we use the direct boot context , it crashes 

java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:530)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:506)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
        at com.microsoft.appcenter.utils.storage.SharedPreferencesManager.initialize(SharedPreferencesManager.java:45)
        at com.microsoft.appcenter.AppCenter.finishConfiguration(AppCenter.java:848)
        at com.microsoft.appcenter.AppCenter.access$600(AppCenter.java:62)
        at com.microsoft.appcenter.AppCenter$6.run(AppCenter.java:753)
