### ISSUE TITLE
Automatic Distribution to all Distribution Groups for each Release (HockeyApp Rights Management)

### ISSUE THREAD

**Issue by jbrozen** [microsoft/appcenter#1272]
**Describe the solution you'd like**
We have many (30+) different distribution groups within HockeyApp/App Center and would like to keep the granularity so that we can distribute certain app builds to certain groups. <The fact that you also can't reference Distribution Groups across Organizations is a major limitation within AppCenter that was not present in HockeyApp - we have worked around this by keeping all apps in one Organization (not ideal).>

With HockeyApp and our CI/CD pipeline (which was Jenkins and the HockeyApp Plugin), we did not need to specify which Distribution Group received which release/build - the distribution rights management were such that if a user was in a Distribution Group and that Distribution Group had access to a certain app, then they would get access to all releases/builds. This way the actual Jenkins build job did not need to have awareness of which Distribution Groups got which application release.

**Describe alternatives you've considered**
We would have to add additional overhead and manage the Distribution Group to App release/builds mapping within our Jenkins instance - as this is already established in AppCenter, we would then need to ensure these stay in sync (Jenkins jobs fail if Distribution Group does not have access to App in AppCenter - so we can't just add all Distribution Groups and let AppCenter ensure the app is distributed correctly)

**Additional context**
If I'm missing something and there's a way to do this, please let me know but I have not been able to find a way to make users within a Distribution Group automatically gain access to all releases/builds within App Center

**Comment by Brantone** [comment]
+1 on this.
If possible for the API to have some kind of "all" flag when posting for version to be released.
That would be nice.

**Comment by Brantone** [comment]
Bump.
There is ability to do CSV of group names (via the CLI), but that then requires the "pre-fetch" of everything.

**Comment by Brantone** [comment]
This would also cut-down on number of API calls.

**Comment by kwacks** [comment]
Can't believe this isn't available yet. Any word on where this is in the backlog?

**Comment by Brantone** [comment]
Bump.

**Comment by Brantone** [comment]
Still useful.
