### ISSUE TITLE
Allow uploading dSYM files along with ipa on manual release

### ISSUE THREAD

**Issue by florianbuerger** [microsoft/appcenter#1274]
When I release an app manually through the web UI, I can only upload an `.ipa` file. If that version has crashed, I first get the notification that `dSYMs` are missing, then I have to dig up the corresponding `dSYM` files for that release an upload them.

It would be great if I could upload an archive with the `.ipa` **and** `dSYM` files. Or even better, upload the whole `.xcarchive` but that then requires configuring the full export flow so I can understand that this won't happen soon. I miss the dedicated macOS app HockeyApp had, which detected a new archived app and offered to upload them with the correct export options.

**Comment by VaibhavMisra** [comment]
It would also be great, if we can have a run script similar to Crashlytics that auto uploads `dSYM` files during the build process, either manual or automated.

**Comment by Slobako** [comment]
I asked their support about this and got the following workaround options:

> 
You can use our API to upload the symbol file, https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#app-center-api. (this also works for Android). Or you can try our CLI command tool, https://github.com/Microsoft/appcenter-cli.
> 

But all this sounds inconvenient and I' am also voicing my support for adding the option to upload dSYMs at the same time as .ipa. This was a convenient and quick feature on Hockey.

**Comment by winnieli1** [comment]
Thanks for the feature request! I can see why uploading symbols with the .ipa file makes sense.

We don't have immediate plans to add this but we'll keep this issue open to track interest and prioritize accordingly. Thanks!

Note: if you are using App Center Build and Distribute, then we automatically forward the dSYM files to Diagnostics so you don't need to upload those files seperately.
