### ISSUE TITLE
AzureDevops: Deploy existing release to other distribution group

### ISSUE THREAD

**Issue by michaelmairegger** [microsoft/appcenter#1276]
Currently the AzureDevops release step "App Center distribute" allows to publish an apk to a specific distribution group.
If I want to distribute the same apk to another distribution group I can execute the same step again with specifying the other distribution group. But the issue is that the step creates a new release. Therefore I have now two releases with the same version and manifest version with different distribution groups listed.

Is it possible to distribute a apk to a group A and then distribute it to group B without uploading the apk again.

I know that is is possible throug the web-API but not directly as release step.

**Comment by winnieli1** [comment]
Hi Michael - thanks for submitting a feature request! I'm not sure if this is currently possible in the UI but we'll keep this issue open to help us prioritize. I've also tagged my colleague who is better positioned to address this.
