### ISSUE TITLE
People section: show last login in the Collaborators list and on the profile page 

### ISSUE THREAD

**Issue by claudius-automator** [microsoft/appcenter#1278]
**Describe the solution you'd like**
For us it would be helpful to see the time and date of the last login of a user somewhere so we can maintain the users better and clean up from time to time by throwing out users that don't use the tool. 
It could be shown on the Collaborators list and on the profile page - see screenshots below.

![Screenshot-AppCenter-Collaborators-Table](https://user-images.githubusercontent.com/57137553/67766123-06346180-fa4e-11e9-8b18-bef176e33213.png)

![Screenshot-AppCenter-Profile-Page](https://user-images.githubusercontent.com/57137553/67766152-11878d00-fa4e-11e9-9cfe-cd12cfe513c1.png)

**Describe alternatives you've considered**
I have not thought of any alternative solutions.

**Comment by ch-the-automator** [comment]
Addition: the field "last login" should then also be added to the API call ´/v0.1/orgs/{org_name}/users/{user_name}´
Doc: https://openapi.appcenter.ms/#/account/users_getForOrg

**Comment by claudius-automator** [comment]
@ScottArbeit : is there any news on this issue?

**Comment by claudius-automator** [comment]
@ScottArbeit : any news here??
