### ISSUE TITLE
Xamarin UI Test iOS 13- Webview class name changed

### ISSUE THREAD

**Issue by CameronMcDougall** [microsoft/appcenter#1280]
UIWebView became depreciated and replaced by WkWebView. When using .WebView() on a appquery, it uses the deprecated webview class for iOS.

Package version-
Xamarin.UITest v3.0.4-dev3

![image](https://user-images.githubusercontent.com/29968096/67730543-3124b280-fa5a-11e9-914e-0cef45710d68.png)

**Comment by winnieli1** [comment]
Thanks for filing an issue! I tagged by colleague who can take a closer look.

**Comment by GlennWilson** [comment]
@Oddj0b @CameronMcDougall 

> There are two APIs to obtain a reference to a webview control in UITest:
> `AppQuery.WebView` is used for `UIWebView` controls.
> `AppQuery.Class` is used for `WKWebView` controls.
> ...
> UITest provides the `AppQuery.Class` method to obtain a reference to a `WKWebView` control. The following snippet is an example:
> `app.Query(c=>c.Class("WKWebView"))`
> 

https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-webviews

**Comment by CameronMcDougall** [comment]
@GlennWilson Sure there are ways to fix it (as per initial screenshot) but UIWebView gives warnings when you upload to the app store because they will eventually stop supporting it. People will remove it for WKWebView for that reason.

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

 I don't think the method shouldn't be primarily using deprecated code as its search method(.WebView()).

**Comment by aaulmer** [comment]
``` csharp
// This works as expected
app.Query(q => q.WebView().InvokeJS(myJavaScript));

// This does NOT work at all and instead throws a JavaScript execption
app.Query(q => q.Class("WKWebView").InvokeJS(myJavaScript));
```

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
