### ISSUE TITLE
[Question] For which reason is there a Microsoft.AppCenter.AppCenterLog class?

### ISSUE THREAD

**Issue by SebastianKruseWago** [microsoft/appcenter#1282]
I can't find anything in the documentation about this class. What does it do? Does it create proper log files to view? Currently I track events with Analytics.Track and exceptions with Crashes.Track but currently I have a error in my app where proper log files could help. I cannot find anything like this on AppCenter so where is the Microsoft.AppCenter.AppCenterLog going? How do I have to use it? 

This is currently my setup method, do I have to change this too if I want to use the AppCenterLog class? 

```
public void StartAppCenter()
{
    var typesToInitialize = new List<Type>();
    var settings = Mvx.IoCProvider.Resolve<IAppSettings>();

    if (!settings.DataPrivacySettingsShown)
        return;

    if (settings.AllowAnalyticsTracking)
        typesToInitialize.Add(typeof(Analytics));

    if (settings.AllowCrashesTracking)
        typesToInitialize.Add(typeof(Crashes));

    if (settings.AllowPushMessages)
        typesToInitialize.Add(typeof(Push));

    Analytics.SetEnabledAsync(settings.AllowAnalyticsTracking);
    Crashes.SetEnabledAsync(settings.AllowCrashesTracking);
    Push.SetEnabledAsync(settings.AllowPushMessages);

    if (typesToInitialize.Any())
        AppCenter.Start(Metadata.GetAppCenterSecret(Device.RuntimePlatform), typesToInitialize.ToArray());
}
```

**Comment by clpolet** [comment]
Hi, `AppCenterLog` is used internally for logging the SDK activity to the device console. What platform are you on? So, while you won't manipulate this class directly you could activate the device console logging to observe the events you are sending. This will help you debugging your issue. Here is how you activate it on a  Xamarin project: https://docs.microsoft.com/appcenter/sdk/other-apis/xamarin#adjust-the-log-level
