### ISSUE TITLE
HockeyApp -> App Center Data Migration

### ISSUE THREAD

**Issue by ronnyremesnik** [microsoft/appcenter#1284]
### **Description**
Hello, I didn't understand from the documentation so I'm asking here.
I have an app that is still using the HockeyApp SDK, the crash and events modules.

What is the amount of time that data from the hockey app SDK will continue transferring automatically to the app center servers?

What will happen to the client for example that will not migrate to the app center SDK and will open an app after 1 year?

Thanks.
Ronny.

**Comment by derpixeldan** [comment]
@ronnyremesnik crashes from the HockeySDK are forwarded to App Center. However, we recommend to update to the App Center SDK after moving your apps. The reason that there's no support commitment is that a major OS release could cause the SDKs to be unusable and we won't fix them anymore. A year is a reasonable time frame, but I don't think it's going to be longer than that. Worst thing that can happen to customers opening an old app version is that it stops working but more likely that nothing happens in the background anymore in terms of sending crash reports etc.

**Comment by ronnyremesnik** [comment]
@derpixeldan @annakocheshkova 
Thanks for the answers, I started to migrate the app and then I noticed that our app is using the 
`ExceptionHandler.saveException` from HockeyApp to send custom crashes.

I didn't found something similar in the app center SDK, I found some thread that said that this feature is still in development.

https://github.com/microsoft/appcenter/issues/289

**Comment by annakocheshkova** [comment]
@ronnyremesnik have you seen my answers [here](https://github.com/microsoft/appcenter-sdk-android/issues/1298)?

**Comment by ronnyremesnik** [comment]
@annakocheshkova Yes, just did, thank you!
