### ISSUE TITLE
Analytics: More detailed OS version distribution

### ISSUE THREAD

**Issue by miklselsoe** [microsoft/appcenter#1286]
**Describe the solution you'd like**
Analytics reports detailed OS Platform version distribution, down to the patch level, but a big chunk (in my case ~15-20% is just displayed as "Other"). It would be nice if numbers for all versions were available. It's the same situation whether you look at the online overview or pull the numbers in the API.

**Describe alternatives you've considered**
I realize that it might be due to privacy concerns that versions with small numbers are chunked into the "other" category. If detailed numbers for all versions cannot be made available, please consider just publishing numbers for all major OS versions. It is really useful for support and maintenance purposes to know what OS versions users are running on.

**Additional context**
Screenshot from appcenter.ms
<img width="402" alt="osversions" src="https://user-images.githubusercontent.com/910031/67929062-b627dd00-fbbc-11e9-92aa-d3e41d1c1baf.png">

**Comment by winnieli1** [comment]
Hi @miklselsoe you should be able to see the exact counts from this API: https://openapi.appcenter.ms/#/analytics/Analytics_OperatingSystemCounts

Give it a try and let me know if that works!

**Comment by rolikoff** [comment]
That worked  @winnieli1 
Although, it would be awesome to have those numbers somewhere on appcenter dashboard :). We needed OS stats for deciding if we have to support our apps for win7/8/8.1 or not. Turned out most of our users use Windows 10 (good job on that Microsoft :) ).

**Comment by tonyarnold** [comment]
This has been frustrating me, too: 

![twitter_EjkMbIIU4AAYiqs](https://user-images.githubusercontent.com/4802/95143194-296ca280-07c1-11eb-8565-42ae1fc54945.jpg)

"Other" is completely unhelpful (these are macOS releases here) - it represents a significant number of users, but there's no way to get more information from this other than spending an hour setting up communication with the backend API. 

Please consider exposing more detailed information for everything on the overview screen - as it is, it's not really useful for any kind of real decision making.

**Comment by rolikoff** [comment]
@tonyarnold I have been using the API that  Winnie provided above, but I also prefer to have those numbers on the dashboard, instead of doing cURL requests to the appcenter API.

**Comment by diogot** [comment]
This still a wanted feature.

**Comment by eaigner** [comment]
In typical MSFT fashion, close it as stale and not touch it. Time to abandon ship. You know this thing is going nowhere since MS bought it.
