### ISSUE TITLE
App.screenshot() method doesn't return screenshot full path and name on cloud.

### ISSUE THREAD

**Issue by VikashChauhan51** [microsoft/appcenter#1287]
**In our application we want to read screenshot as a bytes array or stream to read OCR character from screenshot, but App.screenshot() method return "FileInfo" class instance which contains that screenshot information, but on cloud (appcenter) it doesn't work.** 

 As per the appcenter team reply, it is not possible in code (There is no direct way of taking all the screen shot but We have the ability to download screenshots via our App Center API,Use the GET/v0.1/apps/{owner_name}/{app_name}/test_runs/{test_run_id}/report endpoint).

But in the code we have no test test_runs  and test_run_id information.

Could you please provide a solution for same case?

Note: we are using xamarin.uitest 3.0.3 dll and nuint 3.12.0.

**Comment by winnieli1** [comment]
Thanks for the feature request! Tagging my colleague who can give you updates on when we can address this.
