### ISSUE TITLE
C# compilation define

### ISSUE THREAD

**Issue by godboutj** [microsoft/appcenter#1289]
**Describe the solution you'd like**
It would be nice to allow compilation define and not just env var. To enable code part or configuration of the source code.

**Describe alternatives you've considered**
Right now I have to set env variable, use sed and awk to modify the project define manually before compiling and this is pretty bad and will be hard to maintain.

**Additional context**
There is some features that we enable for some testing build only and we do not want the source code to have this features enabled into the source code by default.

**Comment by winnieli1** [comment]
Thanks for the feature request! This isn't currently on our roadmap but I'm tagging my colleague who can give you any updates on an ETA.

**Comment by godboutj** [comment]
I did change my approach and made some property sheet .props into the projects that convert the env variable into define value instead, so I do not have to maintain some obscure scripts into that only live into AppCenter. This allow me to convert the env vars into define, the only draw back is that I have to include the .props file into all project that require the define. Not super, but less invasive compare to the scripting option available on AppCenter. Wish we could simply add define that would be pass to the compile project/solution instead, I could even get ride of those props sheet.
