### ISSUE TITLE
Upload Crash Report to Different Apps or Groups for iOS?

### ISSUE THREAD

**Issue by TLiu2121999** [Microsoft/appcenter#129]
**What App Center service does this feature apply to?**
SDK initialization and Crash uploading

**Further description of the issue**
We are currently migrating from HockeyApp to AppCenter.
According to the [migration document ](https://docs.microsoft.com/en-us/appcenter/transition/ios-sdk-migration), it indicates that App Center SDK does not have equivalents for `[[BITHockeyManager sharedHockeyManager] configureWithBetaIdentifier:liveIdentifier:delegate]`, which is how we initialize the manager with different HockeyApp app identifiers for beta and live usage. 

But since there is NO equivalents for this function, how can we keep this feature after switching to AppCenter by calling `[MSAppCenter start:@"{Your app secret}" withServices:@[[MSAnalytics class], [MSCrashes class], [MSDistribute class]]];` ?

Is there any other way for differentiating beta and live Apps so we can automatically detect if the app is running in the App Store or debug mode?

This is considered as one of our main gap.

**Describe the solution you'd like**
Add an equivalents initializing function for `[[BITHockeyManager sharedHockeyManager] configureWithBetaIdentifier:liveIdentifier:delegate]`, or provide other ways to differentiate beta and live build.

**Comment by lumaxis** [comment]
@TLiu2121999 Did you intentionally close this issue?

**Comment by TLiu2121999** [comment]
@lumaxis Yes so we add some scripts in out code base to modify the appSecret based on our bundleId so we can differentiate the Apps.

**Comment by lumaxis** [comment]
@TLiu2121999 Gotcha, thanks!

@elamalani I still feel that this might be an interesting scenario for us to cover 🤔 If not with a similar SDK method as exists in the HockeyApp SDK, maybe we could add documentation/a guide with best practices for how to do this?

**Comment by TLiu2121999** [comment]
Yea that would be very helpful, especially for people who are also trying to migrate from HockeySDK to AppCenter. Since the current doc "Note" only brings up:

> App Center doesn't support Carthage yet. Please look at our roadmap to stay up to date on it.

but never tell the user what to do.

So it would be helpful if you can update the [doc](https://docs.microsoft.com/en-us/appcenter/transition/ios-sdk-migration?pivots=swift).
