### ISSUE TITLE
Ability to select build script

### ISSUE THREAD

**Issue by godboutj** [microsoft/appcenter#1290]
**Describe the solution you'd like**
The post clone, pre build and post build scripts should be selectables from the repos and not hardcoded at specific places into the source code. This make same script for Android and iOS copies and need to maintain twices the same files in our case.

**Describe alternatives you've considered**
Not much choice here, I could wrap the functions into another shell script and call the common scripts from that scripts, but this make fragile positions between common scripts and the projects folder.

**Additional context**
Avoid hardcoded path or filename and give us option to changed them at least. Could be an env var with a default value. And use relative path to the source and not the launch project.

**Comment by winnieli1** [comment]
Thanks for submitting an issue! I've tagged my colleague who has more expertise in this area and can give you a better answer.

**Comment by mfrischbutter** [comment]
Status?
