### ISSUE TITLE
Add "In Progress" status for Diagnostics

### ISSUE THREAD

**Issue by macmade** [microsoft/appcenter#1291]
**Describe the solution you'd like**

AppCenter diagnostics can actually have the following statuses:

 - Open
 - Closed
 - Ignored

It would be really nice to also have an `In Progress` status, to flag crashes developers are currently working on.

**Describe alternatives you've considered**

N/A

**Additional context**

Most developers on our team looks at crash reports, for the same product(s).  

Personally, when I look at a new crash (status Open), I may start investigating and try to fix it.  
Unfortunately, as I have no way to flag this crash, an other developer may start looking at it at the same time, without knowing that I'm already trying to fix it.

An additional `In Progress` status for diagnostics would solve the issue, as it would imply that someone from the team is already actively investigating the issue.

**Comment by ahbilal-ms** [comment]
`#DFDFDF`

**Comment by winnieli1** [comment]
Thanks for the feature request! This is a great idea and I can see how it would be very useful for developers to track the issues they're actively working on with this status. 

This isn't on our short term roadmap but we'll use this issue to track community interest and post here with updates. Thanks!

**Comment by macmade** [comment]
Issue is not fixed...

**Comment by macmade** [comment]
Issue is not fixed...

**Comment by macmade** [comment]
Bump…
