### ISSUE TITLE
Add support for capturing ANRs on Android

### ISSUE THREAD

**Issue by tallior** [microsoft/appcenter#1293]
On Android, apart from crashes, users may experience an [ANR](https://developer.android.com/topic/performance/vitals/anr) (app not responding).
This happens when too much 'work' is done on the app's main thread.

It could be a great to be able to track these ANRs together with app crashes in the same system, as it is closely related to crashes and both of these metrics together give a clearer picture of the overall app 'health'.

Other services i know that track this:
- BugSnag
- Splunk Mint

**Comment by winnieli1** [comment]
Hey thanks for the feature request! Due to other priorities at the moment, we don't have immediate plans to add this. We'll keep this thread open to track community interest and post here with any updates. 

Thanks!

**Comment by vineyugave** [comment]
You could consider something similar : 
https://github.com/bugsnag/bugsnag-android/tree/master/bugsnag-plugin-android-anr
