### ISSUE TITLE
Xamarin Forms Push.PushNotificationReceived Event - no way to know whether it was clicked or received in foreground

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter#1294]
### **Description**
Xamarin Forms Push.PushNotificationReceived Event - no way to know whether it was clicked or received in foreground. This even fires when receiving a Push Notification when the App is in the foreground and when a user clicks on it. There doesn't seem away to determine which of these occurred? If they clicked on it I want to navigate them to the relevant screen, if it is received in the foreground, at present, I want to do nothing.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Set up App Center Push Notifications
2. Run Xamarin Forms iOS Application
3. Send Push Notification from App Center
4. PushNotificationReceived Event fires because it is in the foreground
5. Press Home button on device
6. Send Push Notification from App Center
7. Click on Push Notification on Device
8. PushNotificationReceived Event fires because it is clicked
9. How do you determine either of these scenarios because they will most likely want a different action to occur

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms (3.6) > iOS app
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    NET standard 2.0.
2. Which SDK version are you using?
    - 1.14
4. Which OS version did you experience the issue on?
    - iOS 12.2
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPod Touch
6. What third party libraries are you using? 
    - N/A
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
[logs.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/3063443/logs.txt)

**Comment by pfedotovsky** [comment]
Any updates? When will this feature be available?

**Comment by jwargo** [comment]
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

**Comment by james1301** [comment]
@jwargo very disappointing.
