### ISSUE TITLE
Dynamic frameworks for macOS

### ISSUE THREAD

**Issue by alexrinass** [microsoft/appcenter#1296]
### **Description**

The macOS framework bundles are not properly symlinked inside the bundle. All symlinks appear to have been resolved before or during the archiving process.

This leads to code signing errors when the AppCenter frameworks are copied into the app bundle and signed. The signing of the frameworks actually succeeds, but when the app bundle is signed, an error is raised that the AppCenter frameworks are “not signed at all”.

Manually restoring all symlinks resolves the problem.

Normally, the framework bundle only contains files under e.g. `Versions/A` and then there is a symlink `Versions/Current` to `Versions/A`. All files in the framework bundle's root directory are symlinked to files within `Versions/Current`.

### **Repro Steps**

1. Download Release archive 2.4.0 and unzip in Finder
2. Inspect the framework bundles

### **Details**

1. Which SDK version are you using?
    - 2.4.0
2. Which OS version did you experience the issue on?
    - macOS 10.15

**Comment by schriftgestalt** [comment]
I just stumbled over that, too. 
So either use a framework (those are supposed to be dynamic, that is the whole point of it) or static libraries. But don’t mix the two concepts. That is really confusing.
