### ISSUE TITLE
Summary report on Azure Pipelines like HockeyApp

### ISSUE THREAD

**Issue by Tinyakov** [microsoft/appcenter#1297]
I'd like to have a summary report about App Center Distribution on Azure Pipelines. Like it was in HockeyApp - with hyperlink to app version page.

It was very convenient to go to this link and open QR-code for build installation. Now with App Center I have to open App Center and find desired version manually.

![image](https://user-images.githubusercontent.com/4831721/68000124-65ce7f00-fc91-11e9-898e-ca95cd8dd887.png)

**Comment by winnieli1** [comment]
Thanks for the feature request! This is a great idea. We don't have any immediate plans to add this but our team will monitor this thread for community interest and prioritize accordingly.

Thanks!
