### ISSUE TITLE
Better documentation regarding Push notification android 9

### ISSUE THREAD

**Issue by gabsterdev1** [microsoft/appcenter#1298]
**Describe the solution you'd like**
Being trying to implement push notification for android and noticed that on android 9 push notification do not work out of the box as it does for android 7.

It seems and it's not documented in your website that you have to implement a notification channel.
I hope I am wrong but it's not clear in any documentation how to implement push notification for latest version of android.(it works out of the box with android 7)

**Describe alternatives you've considered**
I have considered moving to onesignal for better support but I would like to avoid that.

**Additional context**
Could you please point me to a code sample where I can see where you create a notification channel and customise icon etc..  Goggling led me nowhere. I need to get notification working on all android devices (8 and 9). It also seems that you have to have either the correct size icon or set one otherwise you get a blank icon. Correct?

Also messages in the AppCenter push notifications keep saying queued when they are actually received. (android 7)

thanks a lot

**Comment by winnieli1** [comment]
Thanks for the feedback! I'm tagging my colleague who will take a closer look and send you some resources.

**Comment by jwargo** [comment]
@gabsterdev1 Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
