### ISSUE TITLE
Make ProGuard mapping.txt file available

### ISSUE THREAD

**Issue by hsc-alexe** [microsoft/appcenter#130]
**Describe the solution you'd like**
On any completed App Center build, I would like the ability to download the ProGuard mappings.txt file associated with that build.

**Describe alternatives you've considered**
Not using App Center for release builds?

**Additional context**
Our Android team has integrated with App Center & set up a release process that gets triggered when we push to a specific branch. This then creates an Alpha release in the Play Store, which we promote through the pipeline to production if everything goes well. The issue is that we use ProGuard to obfuscate our apk, but App Center doesn't provide a way for us to download that file so that we can deobfuscate our crashes & logs. This is frankly not a world we can live in long-term, and although I am requesting this as a feature since it sounds like you haven't ever supported this functionality, it feels like a fairly severe bug in the system if you are truly offering a CI/CD solution.

**Comment by patniko** [comment]
Thanks for the request @hsc-alexe! We do support proguard deobfuscation with our diagnostics service - are you using an alternative product for crash information?

**Comment by hsc-alexe** [comment]
My understanding is that you support proguard deobfuscation by uploading a mappings.txt file in your diagnostics tool, correct? The problem is that I don't actually have access to that file for builds run by App Center.

**Comment by patniko** [comment]
You're correct. We don't do it today, but could always automatically send mapping files from our build to the service so you wouldn't have to download and re-upload them. Would that be a better option for you?

**Comment by hsc-alexe** [comment]
I would see that as a nice-to-have to make the App Center use-case better. The Play Store also has diagnostics tools and we send some of our data to other 3p services, so being able to download the file is still more important to me. As a consumer, I would like the ability to be able to select the diagnostics/analytics tools we want to use, independent of the CI system we use. If App Center's tools are the best and the easiest to use, then great we will gladly use them, but forcing us into one ecosystem by not allowing us to deobfuscate our own code does not seem very customer-centric.

**Comment by patniko** [comment]
We agree with that sentiment! Appreciate the clarity so we can hone in on the specific requirements.

**Comment by chrisseed** [comment]
> We don't do it today, but could always automatically send mapping files from our build to the service so you wouldn't have to download and re-upload them.

My scenario is very similar to @hsc-alexe's - we use the Build service to build a Xamarin project and push it to Play's Alpha channel. In our case, we are sending diagnostics data back to App Center so being able to download the mappings.txt is a nice to have, but really we need the mappings file to be automatically uploaded to Diagnostics for us.

Appreciate this is a slightly different feature request but given @patniko just mentioned exactly the solution we are after I thought I would add my comment here.

To second @hsc-alexe's point, App Center is currently pushing us away from using its own Diagnostics service because we can't de-obfuscate our stack traces which seems bizarre.

**Comment by ddui** [comment]
We have exactly the same requirement as @hsc-alexe would be great if this feature was fast tracked as it would be very common for Android developers.

**Comment by mike14u** [comment]
To add, hopefully the error logs / crash logs on Diagnostics feature should not be obfuscated any more, to be more visible with the crashes, since the mapping file itself is already in the AppCenter Builds / Diagnostics.

**Comment by nrajpurkar** [comment]
Downloading the mapping file after a build is now available! Check it out and let us know if you have any issues. Note: you many need to re-save your build configuration for existing configurations for this to work.
