### ISSUE TITLE
Allow Ability to Change Git Remote for a Build

### ISSUE THREAD

**Issue by aaronrogers** [microsoft/appcenter#1300]
**Describe the solution you'd like**
I've recently moved my repository to a new location and would like to change my builds to point to the new repository.  However, there appears to be no way to change it.  Instead there's simply a "disconnect" feature which prompts with the scary text:

> This will delete all build history and settings for this app. This cannot be undone.

🙀

As all that is changing is the url for the repository, I would like the ability to edit it.

**Describe alternatives you've considered**
1. Keep the same URL
  - Pros I'd be able to keep my builds, build number, and history
  - Cons I'd be unable to migrate my code to a better location
2. Change the URL
  - Pros I'd be able to migrate my code
  - Cons I'd loose all my history.  I could start over, but it's less than ideal.

**Additional context**

**Comment by DennisPan** [comment]
@aaronrogers Could you try this https://github.com/microsoft/appcenter/issues/934#issuecomment-542289572? Still haven't got to the official documentation yet. Hopefully that helps for the time being.

**Comment by aaronrogers** [comment]
No, it doesn't look like that works.  I could successfully change the `repo_url`, but the build doesn't have access to the repository.
```
##[error]Git lfs fetch failed with exit code: 2. Git lfs logs returned with exit code: 0.
```

**Comment by DennisPan** [comment]
Does the user who originally connected the repository have access to the new repository?

**Comment by aaronrogers** [comment]
Yes, that's me.

**Comment by DennisPan** [comment]
hmmm... except double-checking the git url, not sure what else to look for. The best path now I think is reaching out to support (via App Center portal), so that I can collect details of your app then take a deeper look.

**Comment by aaronrogers** [comment]
Ok, they're the ones that suggested I make this feature request. 😄 Thanks for the help.

**Comment by DennisPan** [comment]
Ah okay - let me look for the conversation in support

**Comment by DennisPan** [comment]
Close this as we are following up on the support conversation now. If the instruction from https://github.com/microsoft/appcenter/issues/934#issuecomment-542289572 doesn't work, will update there.
