### ISSUE TITLE
Push.Token getter property

### ISSUE THREAD

**Issue by Duranom** [microsoft/appcenter#1302]
Due to the many benefits of AppCenter a project is moving to use AppCenter for iOS, Android and UWP.
However one issue with AppCenter being experienced is that limitations of AppCenter push are very restrictive compared to Azure notifications and it seems unlikely that it will change dramatically and that the project will use that feature from the portal any time soon.
Which leads to a dillema, preferable despite that we would like to use the AppCenter Push module due to its simplicity as well as there is more faith in its longevity unlike the many other packages seen.

After inspecting AppCenter SDK and the Push module it seems it is possible but a problem being experienced is that you cannot get the token for push notifications directly, like how you can listen to a notification being received, and in order retrieve/listen to the token one has to intercept the log objects that are being passed around, like with iOS through MSAppCenter.SetLogHandler, and intercept the PushInstallationLog.

Question regarding this is, is it safe/fine to intercept the log like that and get the token, or is there another way, or is it really discouraged?
Like said, would really like use the package and module as well.

**Comment by jwargo** [comment]
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
