### ISSUE TITLE
Add commit_sha optional metadata on release upload and releases API

### ISSUE THREAD

**Issue by pyby** [microsoft/appcenter#1305]
[HockeyApp API](https://support.hockeyapp.net/kb/api/api-apps#upload-app) has in the upload app API, optional properties, associated to a release build:

- `commit_sha`, optional, set to the git commit sha for this build.
- `build_server_url`, optional, set to the URL of the build job on your build server.
- `repository_url`, optional, set to your source repository.

Those informations are useful for developers with nighty builds or snapshot builds, which are not tagged.

It would be helpful to add it on the App Center service, and then in the [fastlane api](https://github.com/Microsoft/fastlane-plugin-appcenter).

If it can be also displayed in the web front end page, it's the best.

**Comment by blparr** [comment]
Thanks for your feature request!
