### ISSUE TITLE
Transferring distribution group from app level to organization level

### ISSUE THREAD

**Issue by lukaskubanek** [microsoft/appcenter#1306]
**Describe the solution you'd like**
I'd like to be able to transfer a distribution group created for a particular app to an organization in order to be able to invite the same testers into another app - without the need to accept another invitation to a new group.

**Describe alternatives you've considered**
Creating a new distribution group on the organization level and inviting the same contacts. This results in sending yet another invite, though. I'd like to prevent it.

**Additional context**
I've migrated my macOS app from HockeyApp to App Center and didn't follow the steps outlined [here](https://docs.microsoft.com/en-us/appcenter/transition/moving/incompatibilities#distribution-groups). On HockeyApp, I didn't have an organization so I transferred the app to my personal account on App Center. I was then able to transfer the app to a newly created organization on App Center but the same wasn't possible for the distribution groups moved together with the app. I contacted support and received the information that it's currently not possible and that I should create a ticket for it. Well, here it is.

**Comment by blparr** [comment]
Thanks for your feature request, we will consider adding this to our upcoming improvements.

**Comment by liyu0013** [comment]
Upvote for this feature!

When transferring from HockeyApp to AppCenter, all apps were moved under my personal account. And all distribution groups became private groups of each app. 

After that I created a organization and moved all app to it. But the distribution groups are still private to 
each app and there's no way to move to organization level.

Now when trying to add new testers, I had to send multiple invites across each app. And  the maintainability of distribution groups becomes worse - previously we have 7 apps and 9 distribution groups in HockeyApp, now we have to maintain 7*9 groups in AppCenter.

**Comment by geoffsdavis** [comment]
Another upvote for this feature! 

Groups should be by org, not app. It's a huge pain to manually create and maintain cloned Groups across Apps.

**Comment by darkforestzero** [comment]
Please implement this feature or at least treat the hockeyapp transitioned organization is a full appcenter organization (which would allow us to create a shared distribution group).  Your roadmap claims the transition is over but our transitioned organization is still in this handicapped state.
