### ISSUE TITLE
Proposal for minor improvements in the diagnostics page

### ISSUE THREAD

**Issue by lukaskubanek** [microsoft/appcenter#1307]
**Describe the solution you'd like**
I'd like to propose two minor changes to the behavior within the diagnostics page in App Center portal. 

1. Most of the time, I'm concerned about the open crashes so after navigating to the diagnostics page I filter the crashes down using the `Status` dropdown to `Open`. Sometimes, I even narrow the filters down using the other dropdowns. However, when I leave the section and return back, the filter configuration is gone. I'd expect to see the same filters as before. Showing only open crashes by default might also be a good idea.

2. When dealing with longer version numbers (e.g. in an alpha phase), the strings in the dropdown are cut off which is very unusable. Please increase the width of the dropdown according to the longest version number string.

<img width="174" alt="Screen Shot 2019-11-04 at 10 09 14" src="https://user-images.githubusercontent.com/533299/68109953-2354ae80-feec-11e9-9e87-67adb7462e2e.png">

**Describe alternatives you've considered**
n/a

**Additional context**
Not sure whether it makes any difference but I'm seeing this behavior when dealing with a macOS app. I assume it's the same for every app kind, though.

**Comment by blparr** [comment]
Thanks so much for sharing that feedback, we are planning to do some improvements to our Diagnostics page and we will add these to the list.
