### ISSUE TITLE
Diagnosis page should retain version & crash sort oder

### ISSUE THREAD

**Issue by iljaiwas** [microsoft/appcenter#1308]
Once I go back to the Diagnosis view from a particular crash view, the version filter and the sort order in the crash view have been reset to the defaults. 

Restoring the version filter and the sort order to my desired values EACH TIME after having viewed a crashed is extremely cumbersome and confusing. Instead, the Diagnosis view should retain my selection between invocations.

![AppCenterLosesVersionAndSortOrder](https://user-images.githubusercontent.com/2284114/68112827-8e08e880-fef2-11e9-83d3-bbba03394068.gif)

**Comment by lukaskubanek** [comment]
@iljaiwas This is funny. I literally submitted a pretty much the same feature request an hour ago. (#1307)

**Comment by iljaiwas** [comment]
> @iljaiwas This is funny. I literally submitted a pretty much the same feature request an hour ago. (#1307)

This is the first issue you'd run into if you were to use the app in earnest. I cannot believe this wasn't caught by internal QA. 🤦‍♂️

**Comment by blparr** [comment]
Thanks for sharing that, as I mentioned on the other issue, we will take care of fixing that.
