### ISSUE TITLE
App Center API release

### ISSUE THREAD

**Issue by ghost** [microsoft/appcenter#131]
**Describe the solution you'd like**
Hi, app center API is still in preview according to this url  https://openapi.appcenter.ms 
When do you plan to release a production ready API ?

**Comment by patniko** [comment]
Hard to tell, but we do have plans for a cleaner API surface and published SDK clients. Will more than likely circle back to this after we finishing shutting down HockeyApp so the whole team can be focused on one service. We'll keep checking in on this feature to see if this is something people want sooner in the mean time.

**Comment by nschild** [comment]
+1

**Comment by jjhampton** [comment]
+1

**Comment by jameson-mcghee** [comment]
+1

**Comment by ferdicus** [comment]
PLEASE, use reactions...
