### ISSUE TITLE
[Feature request] Allow users to create custom implementation of IStorage

### ISSUE THREAD

**Issue by wedol** [microsoft/appcenter#1311]
Allow users to create and set custom implementation of IStorage to mitigate SQLite issues (microsoft/appcenter#876)

Usage like this:
`AppCenter.SetStorage(CustomStorageImplementation)`

**Comment by Lakritzator** [comment]
I think this is a good request, I tried out the pre-release of AppCenter for WPF and noticed that 
SQLite adds multiple challenges to the roll-out of my application. This is one of the things that made me VERY hesitant to use AppCenter.

It would be really great if the storage engine can be replaced so we can for instance use [LiteDB](https://www.litedb.org/) which is fully managed and for instance doesn't force me to deliver x64/x86 libraries and make the user think about what he needs to download.

I must admit that I didn't look into what exactly is being stored, I expect there is nothing special that cannot be stored in a different database.

**Comment by timdinh** [comment]
Love AppCenter but it is causing a fair bit of issues when doing release build with UWP. Mainly complaining about sqlite3
