### ISSUE TITLE
Feature request: Checking For Updates

### ISSUE THREAD

**Issue by blumk** [microsoft/appcenter#1312]
I'm using the [Cordova Plugin for HockeyApp](https://github.com/bitstadium/HockeySDK-Cordova#checking-for-updates) and I use the in-app update feature that HockeyApp provides:

> hockeyapp.checkForUpdate();

This feature should be part of the AppCenter SDK for Cordova.

I understand that I can use CodePush with Cordova Apps, however updating any Cordova plugins requires distributing native packages.

**Comment by chevett** [comment]
I am being forced to migrate my cordova app from hockeyappsdk to appcenter and appcenter doesn't support distribute in cordova?

Isn't reasonable to maintain hockeyapp support until there is something to migrate too?
