### ISSUE TITLE
Duplicate Analytics Logs/Events

### ISSUE THREAD

**Issue by lgauthier** [microsoft/appcenter#1314]
### **Description**

Please describe the issue you are facing or a feature you would like to be added to the SDK.

### **Repro Steps**

I've created a simple sample application to demonstrate the issue. It appears to be some kind of race condition that isn't easy to reproduce, but I've been able to reproduce it with the steps below.

Sample App: [https://github.com/lgauthier/AppCenterDuplicateEventsExample](https://github.com/lgauthier/AppCenterDuplicateEventsExample)

1. Ensure events are being sent via calls to `MSAnalytics.trackEvent(_:withProperties:flags:)` when transitioning between foreground/background states.
2. Open and close the app over and over for maybe 10-15 minutes and you might end up with duplicates.

### **Details**

1. Which SDK version are you using?
    - Originally 1.13.0, but we've now updated and are still seeing the issue on 2.4.0.
2. Which OS version did you experience the issue on?
    - iOS 11, 12, 13
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.6.2
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - A wide variety of physical devices.
5. What language are you using?
    - Swift

### **More Details**

We have our AppCenter analytics events being exported to Application Insights. We first noticed this issue because we have a few events that have UUIDs associated with them that we pass as properties in calls to `MSAnalytics.trackEvent(_:withProperties:flags:)`. We noticed that we had some events that had the exact same timestamp and the same UUIDs which shouldn't be possible.

After running some more queries, I found that most of the duplicate events were coming from a specific subset of our users who, in comparison with our other users, are less likely to have background tasks running to allow the app to continue executing in the background. Furthermore, most of the duplicate events were events that are often logged when transitioning between the foreground/background states.

I've now added an `EventID` property to all of our events so every event has its own UUID. I'm able to reproduce the issue after opening and closing our app many times over the course of at least 10-15 minutes. To confirm that events were duplicated, I'm running this query in AI:

```
customEvents
| where timestamp > ago(1h)
| extend properties = todynamic(tostring(customDimensions.Properties))
| extend eventID = tostring(properties.EventID)
| summarize uniqueEventCount = count() by timestamp, name, eventID
| where uniqueEventCount > 1
| order by timestamp desc
```

In my sample application, I've also set up a timer to log an event every 0.05 seconds. I _think_ this speeds up how quickly/likely I'm able to reproduce the issue. I've also tried turning on the network link conditioner to the default "Edge" preset and I think that might increase the reliability of reproducing as well.

One more thing to note is that when we get duplicate events, I can query for all events with that `operation_Id` in AI and see that all the events with that same `operation_Id` have a duplicate. The corresponding batch of duplicates all have the same `operation_Id` which is different from the original batch's `operation_Id`. I'm guessing that the `operation_Id` I see in AI might relate to the batch of events that gets uploaded? If so, then perhaps the bug is related to how the AppCenter SDK retries batch uploads or how it removes events from the queue after they've been uploaded.

I've found that I can prevent the issue from happening by starting an arbitrary background task every time we send an event and ending the background task 10 seconds after starting it. I'm not sure if that will always prevent the issue, or if it's just making it much more rare. I haven't been able to reproduce the issue with that workaround in place--however, it's definitely a pretty hacky workaround that I'd prefer not to release into production.

Let me know if there's any other information I can provide to help solve this issue.

**Comment by davestjohn** [comment]
I'm running into this same issue but on macOS, what is the status of this bug/request?

**Comment by AndreiApostoiu** [comment]
Any updates?

**Comment by AndreiApostoiu** [comment]
On my side, I've discovered that I am setting a custom URL for logs from the mobile SDK and from that endpoint I'm sending again the body which are causing the duplicates.

**Comment by wldevries** [comment]
We have this problem with the AppCenter for .NET library version 4.2.0. Under heavy load events are duplicated hundreds of times. Is this problem still on the radar?

**Comment by davestjohn** [comment]
The situation has been improved by the backend team (thanks!) but we were informed that there were changes made in the v4.3 SDK, at least in the macOS SDK, that should also help.  We do still see duplicates, far fewer, but we are using v4.1 of the SDK.
