### ISSUE TITLE
Stack Trace is not populated in the Azure DevOps bug after app center bug tracker integration with Azure DevOps

### ISSUE THREAD

**Issue by swathisuvarna1** [microsoft/appcenter#1315]
After integrating App Center bug tracker for crash reporting in Azure DevOps, the stack traces are still missing form the bug repro steps. This is  a bug. the support team has been informed but it hasn't been fixed yet.

Please view the attachment for bug details. Crash report doesn't contain necessary information and it cannot be shared with the developers.

![image](https://user-images.githubusercontent.com/49498677/68162191-bacdf780-ff14-11e9-9dc9-6ada9c18ed3b.png)

**Comment by winnieli1** [comment]
Thanks for reporting this. I found your support ticket and it looks like our team is still investigating this.

**Comment by swathisuvarna1** [comment]
Is there anyway to expedite this? My team is waiting to share this information with the off-shore developers and I'm afraid we can't give access to them.

**Comment by winnieli1** [comment]
Hi @swathisuvarna1 a fix was deployed a few days ago. Looks like this was also communicated via the support ticket but posting here just in case. Closing the issue now. Thanks!

**Comment by swathisuvarna1** [comment]
Hi @winnieli1 : we have tested the fix and it looks like the stack traces in app center are not matching with the stack traces in the Azure DevOps bug. The ADO bug does not have a copy of the full stack trace. Would you like me to create a new feature request for this?
Please see attached for details: 
![Stack Trace Comparision](https://user-images.githubusercontent.com/49498677/68880843-455ae780-06c9-11ea-9ab8-62babe689772.png)
