### ISSUE TITLE
Verify which dSYMs have been uploaded

### ISSUE THREAD

**Issue by dn-paul** [microsoft/appcenter#1316]
**Describe the solution you'd like**
I would like to be able to verify that dSYM files I have uploaded are in fact present and don't need to be uploaded again.

**Describe alternatives you've considered**

**Additional context**

**Comment by cainejette** [comment]
Hey there! 👋 Have you tried using our [API](https://openapi.appcenter.ms/#/crash/symbolUploads_list)?

**Comment by dn-paul** [comment]
I should have been more explicit: I'd like a UI for that.
I'm sure the API is very nice. Here's the thing: I shouldn't have to build out a set of command line tools to use your website.

**Comment by winnieli1** [comment]
@dn-paul we recently added a tab in the UI to see uploaded symbols. Hope that helps!

![image](https://user-images.githubusercontent.com/8868628/69278864-febd2f80-0b97-11ea-8fbd-557bfcbaee65.png)
