### ISSUE TITLE
Clickable Latest release on app Overview page

### ISSUE THREAD

**Issue by RAM237** [microsoft/appcenter#1318]
**Describe the solution you'd like**
Latest release shown on any app Overview page to be clickable and pointing to the release details page.

**Describe alternatives you've considered**
Current alternative is to click "See all releases", then click the row with latest release which is twice longer and is a degradation of experience comparing to HockeyApp.

**Additional context**
Also, maybe show 5 latest releases on Overview like it was on HockeyApp.

Ideally, I want it to be configurable, to show Overview page or always go directly into latest app release details page (Distribute/Releases/Release ###), since Overview page contains 0 useful information for me and what I always have to do - is to do many clicks to get to where I need.

**Comment by blparr** [comment]
Thanks for your feature request! We will review it and consider it for upcoming improvements.
