### ISSUE TITLE
Redirect HockeyApp app download links to AppCenter app download links

### ISSUE THREAD

**Issue by rishimodha** [microsoft/appcenter#1319]
**Describe the solution you'd like**
Currently, after moving our apps to AppCenter, the previously working HockeyApp download links are broken. This is causing dozens of customer support tickets as customers are attempting to re-download their apps via the app order download email they received at the time of purchase. The download link in those emails is now dead and needs to be redirected.

Example of dead link: https://rink.hockeyapp.net/api/2/apps/f92a1845b69540058c1812bd10dc5b22?format=zip

Should redirect to:
https://rink.hockeyapp.net/api/2/apps/f92a1845b69540058c1812bd10dc5b22/app_versions/7?format=zip&avtoken=c58a0347ef91d28e90ed3e5505db71e5c043f351&download_origin=hockeyapp&mctoken=73471b0480becd4897dadf0f55d17e726cef83ba

**Describe alternatives you've considered**
There is no alternative other than redirecting the HockeyApp download links as they are included in the tens of thousands of order emails that have been sent out prior to the AppCenter transition.

**Comment by rishimodha** [comment]
@derpixeldan - any ETA on this request?

**Comment by rishimodha** [comment]
@derpixeldan I know you must currently flooded with a lot of issues to deal with, but we have thousands and thousands of customers with a download link that was sent via email now pointing to a dead URL following our move to AppCenter.

I would greatly appreciate it if you could give us an idea of when this feature is scheduled to be actioned.

**Comment by rishimodha** [comment]
This appears to be fixed, can we get confirmation? @derpixeldan

**Comment by steffandroid** [comment]
Not sure it is fully fixed. If I browse to https://rink.hockeyapp.net/api/2/apps/f92a1845b69540058c1812bd10dc5b22?format=zip while I'm signed in to my HockeyApp account, the link is dead. If I sign out however, the redirect works and the app is downloaded.

**Comment by dipree** [comment]
It was fixed. HockeyApp will be gone very soon and the issue you mentioned @steffandroid should be eliminated that way too.

**Comment by steffandroid** [comment]
@dipree just to clarify, when you say the issue should be eliminated, do you mean that the redirect will work while signed in or that redirects will stop working altogether?

**Comment by dipree** [comment]
@steffandroid once HockeyApp is shut off the forwarding won't work anymore. There's only a generic forward to App Center but it won't point to anything specific. May I ask why you're still relying on this?

**Comment by steffandroid** [comment]
@dipree it's not me that's relying on it, it's Zeplin. They have a short link https://zpl.io/download-mac which points to https://rink.hockeyapp.net/api/2/apps/8926efffe734b6d303d09f41d90c34fc?format=zip, and as long as you're not signed in to HockeyApp this directly downloads the latest version of their Mac app. I've been in touch with their support and apparently they're unable to generate a similar link using the AppCenter API, i.e. a static link which directly downloads the latest version of a particular app.

**Comment by yigitcanyurtsever** [comment]
Hey all 👋 

Yigit here from Zeplin. Thanks for raising the issue @steffandroid! 

Like you mentioned, the issue we have also depends on #1243 as we'll need the direct download link for the latest version, not just the public page. It'd be great if we can find a solution to this before the HockeyApp endpoints are gone as we'll lose some HockeyApp functionality that we rely on. I'd be happy to help in anyway I can.

**Comment by rishimodha** [comment]
As explained previously, the forwarding should remain as order emails received by customers have hard coded links to the original hockey links. Is it not possible to maintain the forwarding for a year or so?
