### ISSUE TITLE
Allow single app entry for cross-platform frameworks

### ISSUE THREAD

**Issue by J-Swift** [microsoft/appcenter#132]
I'd like to have a single app in AppCenter for both iOS and Android versions of a Xamarin app. I currently maintain two entries, duplicating release notes / distribution groups / etc. Crash logs are also split between the two entries, which makes sense when the issue is in framework code, but adds noise when the issue is in shared code.

**Comment by patniko** [comment]
@winnieli1208 has been working on a plan for a new project structure that would start us down this path. It's a pretty fundamental change to the way App Center is laid out today so we'll have to take a few big steps to get us there, but we'll share some plans for feedback in one of the upcoming iterations.

**Comment by J-Swift** [comment]
@patniko @winnie - resurrecting this ticket to see if I missed any updates in the interim.

I have a renewed interest in it with a new app I'm developing, and the pain is going to be even greater since it will target tvOS as well as standard ios/android. I'm really not looking forward to managing the different variants as 3 separate apps. Thanks for any insight you can provide!
