### ISSUE TITLE
[feautre] add "untrack" event to android SDK

### ISSUE THREAD

**Issue by mantinband** [microsoft/appcenter#1320]
#### something like:
```kotlin
Analytics.untrackEvent("video clicked")
```
or
```kotlin
val properties = mapOf("action" to "clicked")
Analytics.untrackEvent("video", properties)
```

#### the overall flow i would like to acheive
```kotlin
fun updateNumberLocations(oldNum: Int, newNum: Int) {
    Analytics.untrackEvent("locations", mapOf("number locations" to oldNum)) 
    Analytics.trackEvent("locations", mapOf("number locations" to newNum))
}
```
This option is already available via [this](https://openapi.appcenter.ms/#/analytics/Analytics_EventsDelete) API and it would be great if you can add it to android SDK.

**Comment by blparr** [comment]
Hi! Thanks for your feature request. This is not in our upcoming plans, but we will leave this feature request open to see if it gets traction.

Thank you!
