### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by AntonLozovskiy** [microsoft/appcenter#1321]
We want to try to use your service, everything seems good and simple. One thing, from what we read your assemblies need to be downloaded from Nuget - they are not signed by a strong name and we cannot connect them because we have everything signed. Can you update your packages and add a signature with a strong name?

**Comment by blparr** [comment]
Let me connect you with one of our PMs who will be able to help you with your question!

**Comment by ranterle** [comment]
Hih there @AntonLozovskiy - can you help us understand which binaries you need to be signed? Is this about the App Center SDK binaries or something else?

**Comment by macamposm** [comment]
I need AppCenter to have a strong-name for use in projects that require a formal distribution (clickonce, msi, etc).
In my project we use a code certificate (Verisign), which requires that all the DLLs linked have a signature with a strong-name.

**Comment by dythim** [comment]
We have the same issue.  Our WPF application is strongly named, and can only reference other strongly named assemblies.

**Comment by NunoPeixotoPrimavera** [comment]
This is a really important issue for those who have strong signed applications.

**Comment by krupineg** [comment]
Also faced this issue with our WPF application

**Comment by jozefizso** [comment]
This is blocker for us. We must release our app with a strong name so we cannot integrate AppCenter SDK with it.

**Comment by jnm2** [comment]
Microsoft's open-source library guidance recommends strong-naming all libraries:

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries

**Comment by Acilec** [comment]
Same problem here. Can't use AppCenter functions since they are not strong named.
Please fix!

Could not load file or assembly 'Microsoft.AppCenter.Analytics, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by ahdbilal** [comment]
Thanks! We are adding this feature to our backlog. I will share more details here when this moves up the queue.

**Comment by WaivedAnswer** [comment]
AppCenter and AppCenter.Analytics both are not strongly named. Thanks for looking into this!

**Comment by Acilec** [comment]
Any news on this?

**Comment by EatonZ** [comment]
Doesn't it take like 5 seconds to link a strong-name key in the project's properties?
Or is there some blocking issue that has made this difficult for this long?

**Comment by hooby3dfx** [comment]
Are there any workarounds until this is done?

**Comment by EatonZ** [comment]
You can strong-name them yourself. Add this to your project and it will handle it: https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/

**Comment by Banzyme** [comment]
Can someone please explain why is this is taking so long to fix??

**Comment by EatonZ** [comment]
[A PR to fix this has been merged today](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1488), so you can close this issue.

**Comment by AnastasiaKubova** [comment]
Hi there! The feature has been released in the [4.2.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.2.0) version of App Center SDK.
