### ISSUE TITLE
I started transition of app from hockey app to appcenter and that takes already 2 hours.

### ISSUE THREAD

**Issue by IstiN** [microsoft/appcenter#1323]
Hi MS Team,

I started transition of app from hockey app to appcenter and that takes already 2 hours and still is not done. How usually that takes? How I can track the progress?

**Comment by derpixeldan** [comment]
@IstiN during rush hour it can sometimes take a little bit longer. There's always engineers monitoring the queue. Please bear with us.

**Comment by IstiN** [comment]
dear @derpixeldan it takes more than 17 hours already. And it's only one app ) we need to migrate 60. Probably you can share with me some contact from support team who can check the issue?

**Comment by derpixeldan** [comment]
@IstiN in case you haven't yet, please reach out through support in App Center so we can further investigate (blue button on the bottom right corner).

**Comment by IstiN** [comment]
Thanks @derpixeldan I asked. No answer yet, will wait.

**Comment by gmerinojimenez** [comment]
It is also happening to us. 90 apps migrated, 255 pending and the job seems to be stuck

**Comment by dipree** [comment]
We're taking care of all the apps.
