### ISSUE TITLE
Need ability for an organization distribution group to have IOS automatic repovisioning

### ISSUE THREAD

**Issue by GimpMaster** [microsoft/appcenter#1324]
**Describe the solution you'd like**
When viewing an IOS application, Appcenter has a great mechanism for Collaborators to have their devices (when registering) to be automatically re provisioned and re-sign my ad-hoc application.

This can be seen under these menus:

App -> Distribute -> Groups -> Collaborators (middle pannel) -> Settings (top right) as seen in the screen shot.

![image](https://user-images.githubusercontent.com/7818200/68232396-3b92ff00-ffba-11e9-9750-fc9e7f172092.png)

However If you click on a distribution group (made of contributors). You dont get that same option as in the image below:

![image](https://user-images.githubusercontent.com/7818200/68232303-0f777e00-ffba-11e9-8f45-ddbad4d05d76.png)

It tells you to go to the Organizations Group settings for other options but I can not find anything in there that would allow me to auto re-provision a device and re-sign it for a distribution group.

**Describe alternatives you've considered**
My only alternative is to place everyone into a collaborator group and NOT use distribution groups.

**Additional context**
Perhaps I am missing something. Please let me know if there are other ways.

**Comment by GimpMaster** [comment]
@ScottArbeit or @dimazaid 

Any thoughts on this? Am I correct in that the only way to have automatic provisioning for an organization is to add them as collaborators and NOT put them into a distribution group?

**Comment by Ajaykn21** [comment]
Hi @GimpMaster,
Thanks for reaching out to us.
Currently AppCenter supports Auto-provisioning for App-specific groups only but not Shared groups in organization.

I guess, the group `Quality Assurance` is a Shared group in your Organization.
We will investigate more on what it takes to support for shared groups and will update you.

cc @Oddj0b

**Comment by Oddj0b** [comment]
Hey @GimpMaster, thank you for your suggestion. Initially, we didn't include this scenario because of how you can add testers to a shared distribution group from multiple apps. Is it correct to assume you are not concerned about reaching the 100 device limit on your Apple account?

**Comment by GimpMaster** [comment]
Thank you @Oddj0b and @Ajaykn21 

Here is what I am hoping to achieve and perhaps you can guide me :)

We are a company that develops multiple white labeled apps in both android and IOS. I have my company: Sales, Developers, Q/A all setup in my organization in different shared distribution groups. Our company is less than 25 employees at this time. 

When we get a customer's white labeled app to a point we want to test them my hope was to create a new shared distribution group for Company A employees and only share them to their app. Thus when they sign up they would get their device automatically provisioned. I wasn't sure if the 100 person limitation was per app or per ios development team.

Any suggestions?

**Comment by danielmartind** [comment]
Hi 
I would be interested in this feature too. I have created a group to allow people to install Android or IOS as the users have a variety of unknown devices. Would really like to auto provision anyone who wants to install IOS.

**Comment by GimpMaster** [comment]
@Oddj0b and @danielmartind 

Just commenting back. After doing more research the 100 person per dev team limitation is actually a hard pill to swallow. You can not remove any phone at random from apple. They basically stick onto your account until the anniversary of your initial signup as a dev team with apple.

So you are right that we can't just add and remove customers devices at will. Thus we have changed our operation such that when we do want to show it to a customer outside our internal team we begrudgingly go through Test Flight and have the Apple Gods deem it worthy of a beta test.

**Comment by Oddj0b** [comment]
Thank you for returning @GimpMaster. I will close this feature request.
