### ISSUE TITLE
Add support for UnitTests(python) in appium

### ISSUE THREAD

**Issue by RiviElfNeura** [microsoft/appcenter#1325]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by blparr** [comment]
Thanks for your feature request, adding @Oddj0b to this thread for further comments.

**Comment by Oddj0b** [comment]
@RiviElfNeura I'm assuming you would want to run this on a build machine and not in App Center Test which does UI Testing, is that correct?
