### ISSUE TITLE
Edit email invites sent to Distribution groups

### ISSUE THREAD

**Issue by trobinson-skyhook** [microsoft/appcenter#1328]
After creating a distribution group in app center by adding the testers and the app, It would be nice to have the feature to send out personalized email invites with attachments. This will help owners to append instructions on how to use the owners app or any other personalized key sent along with the invitation to the app or have a separate feature to push email instructions through the app. 

This feature was available in the HockeyApp and was very helpful.

**Comment by blparr** [comment]
Hello, thanks for your feature request! This is a nice idea. We'll leave the issue open to see how much traction it gets from other users.

Thank you!
