### ISSUE TITLE
Ability to download diagnostics

### ISSUE THREAD

**Issue by kali-muthuswamy** [microsoft/appcenter#1329]
Can we please have the ability to download app diagnostics?  It is mentioned in the documentation, but no "Download" button exists. Perhaps it is a hockey app feature that got missed? 
https://docs.microsoft.com/en-us/appcenter/diagnostics/using-the-diagnostics-ui

**Comment by blparr** [comment]
Hello! What information in the Diagnostics page do you want to download, and in what format? Today, you can already export your Diagnostics data to Blob Storage. Would that suffice?

**Comment by winnieli1** [comment]
@kali-muthuswamy if you're looking to download the raw crash reports, you need to select a specific crash or error report:

![image](https://user-images.githubusercontent.com/8868628/68340344-43cf6500-00b4-11ea-9a7c-30d3b96a6fad.png)
