### ISSUE TITLE
Filter diagnostics and analytics data by build number

### ISSUE THREAD

**Issue by winnieli1208** [microsoft/appcenter#133]
In App Center Diagnostics today, users can filter crash and error groups by recent versions but not by build number. Many developers, especially those with large apps, have multiple builds per versions and need a way to filter this data to help prioritize their most important and relevant issues. 

This feature will allow users to filter their diagnostics data by selecting a version and build number as shown in the mockup below:

<img width="1435" alt="52743641-4f5f8680-2f8f-11e9-8d97-cd858e71b214" src="https://user-images.githubusercontent.com/8868628/53660445-c1340300-3c12-11e9-9574-a92c409de95f.png">

**Comment by transis2** [comment]
waiting for this...

**Comment by winnieli1208** [comment]
We had to delay this feature due to other priorities but we should have this completed by the end of the month. Thanks for your patience!

**Comment by WCByrne** [comment]
Would love to see this for analytics as well. Should I create a separate issue?

**Comment by winnieli1208** [comment]
@WCByrne we're actually building this for analytics too! I'll update the issue to reflect that. Should be enabled today or tomorrow so keep an eye out :)

**Comment by lumaxis** [comment]
Since I talked to @schriftgestalt who requested thiamin #371 too, a quick update: We hit a small road bump while working on implementing this but we‘re still looking to releasing the feature soon 🙂

**Comment by winnieli1208** [comment]
This feature is now enabled for diagnostics! The build dropdown filter will populate as new crashes come in. Unfortunately, we ran into some difficulties for Analytics so we had to scope this out for now. We don't have immediate plans to enable this for Analytics but feel free to create a separate issue to track this feature. 

Thanks!

**Comment by schriftgestalt** [comment]
Unfortunately the "Build" dropdown only shows "All" for me. 
<img width="318" alt="Screenshot" src="https://user-images.githubusercontent.com/174660/60350175-54175b00-99c3-11e9-873d-a6771e8143f0.png">

It still works fine in Hockeyapp so I would think everything is configured correctly on my end.

**Comment by transis2** [comment]
the "Build" dropdown only shows "All" for me too.

**Comment by florianbuerger** [comment]
Same issue for me (Safari & Chrome). If I set a build number in the URL it works—only crashes from that build are shown. Seems the issue only affects the UI.

![](https://share.florianbuerger.com/Screen-Recording-2019-06-30-11-56-09.gif)

**Comment by winnieli1208** [comment]
Apologies for the delay. We have two known limitations on our end:

1. The Build dropdown is only populated if the analytics SDK module is integrated
2. The Build dropdown is only populated with build numbers that have new crashes since we launched this feature

I'm working to get these issues prioritized and fixed. Thanks for everyone's patience!

**Comment by schriftgestalt** [comment]
This is still not working for me. It still looks like in the post from @florianbuerger.

I don’t like to add "analytics SDK module" to my app (as suggested by the last post).

**Comment by schriftgestalt** [comment]
anyone?

**Comment by schriftgestalt** [comment]
I have published a dozen new versions in the last two weeks. 

One thing that might be a problem is that I didn’t move the app to Appcenter. I’ll like to see that everything works before I switch over for good.

**Comment by schriftgestalt** [comment]
I tried that.

**Comment by winnieli1208** [comment]
Hey @schriftgestalt apologies for missing your initial comment. At this time, you'll need to integrate our analytics SDK to use the build filter. Unfortunately we haven't had a chance to remove this dependency but I'll post here if I have any updates.

**Comment by schriftgestalt** [comment]
I’m not sure what the analytics sdk is doing in detail but I don’t like to add it just to get this totally unrelated feature to work.

**Comment by fernandotcl** [comment]
Hi @winnieli1, is there an issue tracking the progress of removing this silly dependency? I don't know if I'm more amused or annoyed.

**Comment by winnie** [comment]
Hi @schriftgestalt @fernandotcl, just want to let you know we recently removed the Analytics SDK dependency for the build number filter in Diagnostics. Thanks for your patience!

**Comment by schriftgestalt** [comment]
This works now. Thanks a lot.
