### ISSUE TITLE
App Center Push to support apns-notification-type header for iOS 13 and watchOS 6

### ISSUE THREAD

**Issue by dk-mushiyoke** [microsoft/appcenter#1330]
**Describe the solution you'd like**
To support the newly added apns-notification-type header for iOS 13 and watchOS 6 so that the different types of notifications are delivered correctly.

**Describe alternatives you've considered**
N/A

**Additional context**
See https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns for official documentation on the header.

**Comment by blparr** [comment]
Thanks for your feature request. Looping in my colleague.

**Comment by jwargo** [comment]
@dk-mushiyoke thanks for this - you should be able to do this now, I'll look into this and get back to you (and make a doc update).

**Comment by mschmidt-healthx** [comment]
Is there any update on this?  How is this done?

**Comment by jwargo** [comment]
@mschmidt-healthx it's handled automatically under the covers. Nothing for you to do.
