### ISSUE TITLE
Deleted Distribution Groups Remain Listed in Distribution Pages

### ISSUE THREAD

**Issue by jbrozen** [microsoft/appcenter#1331]
**Describe the solution you'd like**
Not sure if this is a feature request or an actual bug - due to the oddness (and lack of feature parity in AppCenter) in migrating apps where we had multiple Organizations and Distribution Groups that had cross-Organization access to applications, we had to completely recreate a more simplified structure for our Distribution Groups. After recreating the Distributions Groups in a single Organization, we removed/deleted the older Distribution Groups - and they now return a 404 page

Since the apps migrated over with releases that were distributed to these now removed/deleted Distribution Groups - the `distribute/distribution-groups` page is now a mess with what looks like duplicated and invalid Distribution Groups - this is confusing operationally.

The request: Release Distribution pages should be automatically cleaned up if you remove/delete a Distribution Group - specifically these pages:
`https://appcenter.ms/orgs/<your organization>/apps/<your app name>/distribute/distribution-groups`

**Describe alternatives you've considered**
Manually walking through 100+ apps and removing 10-15 invalid/removed Distribution Groups - no thanks

**Additional context**
N/A

**Comment by blparr** [comment]
Hello, thanks for reporting this, we'll take a look!
