### ISSUE TITLE
Show the app's bundle identifier on the release page

### ISSUE THREAD

**Issue by kaischo** [microsoft/appcenter#1333]
I would really like to see the bundle identifier of an uploaded app alongside other information on the release page, like on hockeyapp.
At the moment you can see info like build number, file size, used provisioning profile or minimum os version, but not the bundle identifier.

**Comment by blparr** [comment]
Thanks for your request, we'll consider your request as part of our upcoming improvements.

**Comment by vivek-bosch** [comment]
This would be a really good feature, as this feature was also in Hockeyapp and it really helps is maintaining the apps.

**Comment by oradyvan** [comment]
Could you please consider implementing this feature? This is really helpful for app developers.

**Comment by mmaslati** [comment]
+1

**Comment by bipin360** [comment]
+1

**Comment by aimore** [comment]
@blparr  2019
"Thanks for your feedback, we'll consider your request as part of our upcoming improvements."

2021 ?
"..."
