### ISSUE TITLE
Allow applications to configure crash bucketing

### ISSUE THREAD

**Issue by gsnook** [microsoft/appcenter#1334]
We would like the ability to refine how our crash issues are bucketed within AppCenter. Often, we find separate issues with similar callstacks that we need to combine, or general buckets masking several issues that we need to break apart. Some ability to refine these bucketing parameters within AppCenter would be ideal. We would like the ability to combine multiple Diagnosis issues into one, or split apart a single issue into multiple issues based on individual callstacks.

**Describe alternatives you've considered**
An alternative would be to allow us to define the bucketing parameters for Diagnosis issues, so we can determine the depth of stack used to constitute a match for bucketing.

**Additional context**
Currently, we have to manage the combination of issues in AppCenter externally. A greater set of tools to combine and divide issue buckets within the tool would be preferred.

**Comment by blparr** [comment]
Hi, thanks for your feature request. This is not in our upcoming plans, but we will consider it for future planning.

Can you describe more how you do this combination of issues externally?

**Comment by gsnook** [comment]
We may, for example, find a set of callstacks in separate buckets which are all below a common scope or cause. We collect these into a single bug within our own database for tracking. We’d prefer to group these within AppCenter so we can more easily track their impact as a whole.

On the opposite side, we sometimes find buckets in AppCenter which contain multiple root causes we would prefer to track separately by their individual callstacks.

As an example of the latter, consider this crash bucket on std::terminate()
https://appcenter.ms/orgs/minecraft/apps/mc_vanilla_android/crashes/errors/2081732835u/overview

Inside that bucket, we find multiple separate occurrences with unique callstacks that coincidentally end in a call to std::terminate. These are distinct issues we would prefer to break apart into separate crash events for AppCenter to track.
https://appcenter.ms/orgs/minecraft/apps/mc_vanilla_android/crashes/errors/2081732835u/reports/2518284377449999999-c3422d2e-edd9-459e-9093-21df6f29bf4d/threads
https://appcenter.ms/orgs/minecraft/apps/mc_vanilla_android/crashes/errors/2081732835u/reports/2518284411609999999-368f2ad4-d486-4969-a9f7-f5dfe85a6891/threads

We assume this is because AppCenter is bucketing on a limited match of lines within a callstack. One potential mitigation is to allow us to specify the depth of the callstack we wish to bucket on for our application. This would help us break apart larger buckets into their discrete parts. If we could then also select multiple crash issues and somehow mark them as a Group, that would be very helpful to us.

Thanks!
