### ISSUE TITLE
Increase Audience member limit to 5000

### ISSUE THREAD

**Issue by kguru10** [microsoft/appcenter#1335]
**Describe the solution you'd like**
Currently the number of devices within an audience is limited to 1000. can this be increased to 5000. We have an audience that refers to employees in the US and with the current limit it will not work for us.

**Describe alternatives you've considered**
We will have to look at Azure Notification Hubs if this is not going to be possible

**Additional context**

**Comment by blparr** [comment]
Hi, thanks for your feature request! Looping in my colleague.

**Comment by jwargo** [comment]
@kguru10 thank you for the suggestion. Unfortunately, we are unable to increase that limit at this time. For larger audiences, we recommend using Azure Notification Hubs.
