### ISSUE TITLE
Add Xcode 11.2.1 support

### ISSUE THREAD

**Issue by beeradmoore** [microsoft/appcenter#1336]
**Describe the solution you'd like**
Add support for Xcode 11.2.1.

**Describe alternatives you've considered**
Not selecting Xcode 11.2 on any of my projects.

**Additional context**
The changelog can be found [here](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_2_1_gm_seed_release_notes/). The most important (and only) change is:
> Storyboards containing a UITextView will cause the app to crash on macOS versions earlier than macOS 10.15.1 if compiled on a Mac running macOS 10.15.1. (56808566)

**Comment by maxim-lobanov** [comment]
Hi, this request is on track and Xcode 11.2.1 will come next week.

**Comment by beeradmoore** [comment]
Awesome. Thanks :)

**Comment by fbonareis** [comment]
Thanks!!

**Comment by gryz** [comment]
Might want to jump on the beta release cycle in the future ....

**Comment by beeradmoore** [comment]
> Might want to jump on the beta release cycle in the future ....

They had 11.2 beta for a long time. I don't believe there was any 11.2.1 beta, it just went GM on the developer downloads page and didn't even hit AppStore for a while after that.

**Comment by maxim-lobanov** [comment]
Xcode 11.2.1 is available!
Currently, it is GM (11B53).
GA(11B500) will be available soon.

**Comment by beeradmoore** [comment]
Awesome, thanks for the update.
