### ISSUE TITLE
Wrong text formatting in email notifications.

### ISSUE THREAD

**Issue by RAM237** [microsoft/appcenter#1337]
Hi,

it seems there's a bug in the logic which constructs the email notification sent to the app users in the distribution group.

Particularly, email text does not match what Release notes contain.

Here's what I have in AppCenter:

----
![EmailFormatting_ReleaseNotes](https://user-images.githubusercontent.com/15870100/68433042-afa1f280-01c6-11ea-8430-1a4fa0ddfc2c.JPG)
----
-- note underscores positions.

And here's what I get in an email:

----
![EmailFormatting_Email](https://user-images.githubusercontent.com/15870100/68433100-d19b7500-01c6-11ea-87f7-d410afb4fe40.JPG)
----

Please note, ALL underscores are missing in the email notification formatting and in SOME places they are resulted in Italics (marked with red).
**This is wrong and distorts the original message significantly.**
Release notes formatting is correct.

Below is the source text passed to **appcenter-cli** in a file (during release distribution run):
```
Built @ commit **bfe587**, URL **git@gitlab.com:example/mobile/myapp_ios.git**
App **iOS Prod v1.0.2_alpha (340027)** AppCenter deploy through Jenkins **GitLab-iPhone_Prod_Alpha--BUILD** job (ProdPN_AdHoc_Alpha scheme).

This is a test message
```

**Comment by RAM237** [comment]
Plz mark it as bug
/label ~bug

**Comment by bealex** [comment]
I do not know, whether it is related to this bug, but we tried to add some release notes in cyrillic, and we've got something completely awkward in an email.

```
What's new
--
 ?@8;>65=885:2878BK AG5B02>=>: 2 10=:03D8:A
```

(It was something like `О приложении...`)
