### ISSUE TITLE
Possibility to grant team admin rights to users in a team

### ISSUE THREAD

**Issue by lauri-rovio** [microsoft/appcenter#1338]
**Describe the solution you'd like**
We would like to be able to give admin rights to some team members so that they could manage their team themselves (Adding/removing users and apps from the team).

**Describe alternatives you've considered**
In our setup we will have good amount of teams and each team will have multiple apps. 
Currently user needs to be admin in the organization to be able to manage teams in organization. There is no possibility to add just admin rights for a team for a person. It would be nice feature as we are planning to have a team for each project and each project will have multiple apps.
If we could give admin rights to some team members they could manage their project team themselves. With current features we would need to have couple of persons from each team as admins in our organization so teams could manage themselves. But we would like to keep organization's admin group smaller and then teams need to always request changes in teams from smaller admin group.

Currently user who created the team will be the maintainer and others will be just members, but we would like to be able to create teams centrally with organization admins and then transfer the management to the team itself.

**Comment by ScottArbeit** [comment]
@lauri-rovio We're actually thinking of moving away from the team maintainer concept, and leaving team maintenance for Organization admins. We're seeing low usage of the Team maintainer role from people who aren't also Org admins, and so we'll likely simplify things in that area. I know that's the opposite of what you're asking for, but I want to be transparent and get your feedback.

At the same time, we have work lined up over the coming months to add support for Azure AD security groups in Organization collaborators, Teams, and Shared Distribution Groups. (We already support Azure AD security groups in app-level distribution groups.)

Are you in an organization that uses Azure AD? Would the ability to do team membership through Azure AD security groups meet your needs?

**Comment by lauri-rovio** [comment]
Thanks for the quick answer. We are not using Azure AD so that won't help.
It's true that current team maintainer role just adds confusion.
I think we need to gather more hands-on experience, as we are still in transition face from HockeyApp, before I can give really strong opinion about this feature. Probably it won't be a huge issue and we will find some other solution.

**Comment by ScottArbeit** [comment]
@lauri-rovio I know it's not ideal, but if you wanted to build your own quick utility to do this for now, we have our [REST API](https://openapi.appcenter.ms/) available for it. I've created a couple of sample utilities that demonstrate how to use the REST API using C# in my personal repos; for instance: https://github.com/ScottArbeit/App-Center-Bulk-Import.

Gonna close this issue for now; when you dive in to AppCenter and have a sense of how Team membership is working for you, please let us know... we're always looking for as much feedback as we can get. 🙂
