### ISSUE TITLE
UDID list and number of provisioned devices in a Release

### ISSUE THREAD

**Issue by RAM237** [microsoft/appcenter#1339]
**Describe the solution you'd like**
Clickable "## devices" link near Provisioning Profile that leads to the full list of UDIDs of all the devices included in this particular Release.

On HockeyApp it was like this:

----
![Capture0](https://user-images.githubusercontent.com/15870100/68436242-8c7b4100-01ce-11ea-8b61-2e97e7fc6862.JPG)
----

\> click & get to >

----
![Capture1](https://user-images.githubusercontent.com/15870100/68436253-9604a900-01ce-11ea-986c-56d5f22c0290.JPG)
...
----

**Describe alternatives you've considered**
Download IPA and retrieve the UDIDs from it.
Even more work to do in AppCenter?
It was very very handy in HockeyApp, too sad it disappeared in AppCenter like many other convenient things...

In-product support also suggested me this:
![image](https://user-images.githubusercontent.com/15870100/68436510-45da1680-01cf-11ea-8ace-dc6badedb54c.png)
but it is a list of devices for Distribution Group while I am talking about **devices included in an app Release**.

**Comment by AlexFolland** [comment]
This should not have been marked stale.  There were several comments here disputing the marking of stale, but they have been silently deleted by an unknown person, censoring them.  This is still relevant and the issue should be reopened.

**Comment by AlexFolland** [comment]
This seems to be the same as https://github.com/microsoft/appcenter/issues/1013 and https://github.com/microsoft/appcenter/issues/1363 .  Maybe it should be merged with https://github.com/microsoft/appcenter/issues/1013 .

**Comment by AlexFolland** [comment]
Just because this hasn't been implemented doesn't mean it should be closed.  That doesn't make sense.

**Comment by AlexFolland** [comment]
Is the bot bugging out?
