### ISSUE TITLE
Add REST API to collect custom artifacts

### ISSUE THREAD

**Issue by sakthiyuvaraj** [microsoft/appcenter#134]
We use AppCenter test for performance tests. The performance tests are now logged to the Nunit tests. We would like for us to write these perf traces to disk. And let app center know about them so that they are collected and stored after test runs. Also, need additional REST API for downloading these custom artifacts.

**Comment by jwhiteDev** [comment]
Hi @sakthiyuvaraj what kind of performance testing are you doing, and for what type of apps?

**Comment by sakthiyuvaraj** [comment]
We use AppCenter for doing performance tests for map control on Android and iOS. We measure and collect data to download, decoding of data, rendering performance to list a few. Our perf runs output about 100MB+ of data in the current text format. Binary format would be much smaller.

**Comment by jwhiteDev** [comment]
Got it, this is some good feedback. Adding some more out of the box support for performance testing scenarios is something we are tossing around as well, but haven't done more than discussed.

**Comment by markgrinols** [comment]
I would like to second and generalize the original request. It's not just about perf - any kind of testing could benefit from the ability to collect arbitrary custom log files etc from the device via some mechanism.
