### ISSUE TITLE
Allow Symbols Zip to be Downloaded

### ISSUE THREAD

**Issue by theeagle** [microsoft/appcenter#1340]
**Describe the solution you'd like**
In HockeyApp you could download the symbols zip files that were uploaded for a given release. AppCenter should also allow this functionality. 

**Describe alternatives you've considered**
Archiving the zips on another store, but this would introduce another storage solution to reference as part of our CI/CD process. 

**Additional context**
With HockeyApp, we included our Sparkle appcast.xml files inside our symbols zip to make it easy for our deployment team to grab the appcast during release time. This was just a really convenient place to locate the xml as both the app binary and appcast xml was available in a single location.

**Comment by cainejette** [comment]
Hey there! 👋 We are discussing when to pick up this work, but in the mean time, this is available through our APIs, which should hopefully unblock you! See [here](https://openapi.appcenter.ms/#/crash/symbols_list) and [here](https://openapi.appcenter.ms/#/crash/symbols_getLocation).

**Comment by theeagle** [comment]
Hey @cainejette, thanks for the calls. Yeah, currently, our QA team is who grabs the zip manually, unarchives and pulls the appcast xml. But we could give them a simple script that grabs them. 

I did test this out, and it looks like that API gives me *every* symbols file that has ever been uploaded... which is a bit unwieldy. I suppose if I include the symbols UUID in the release notes of each build, it'd be easy enough to grab that and run the script, true? 

Anyway, yeah, having a non-dev way to download the symbols zip would still be awesome, so thanks for considering it!!

**Comment by cainejette** [comment]
You can also query [this API](https://openapi.appcenter.ms/#/crash/symbolUploads_list) and find the upload ID to then query [this API](https://openapi.appcenter.ms/#/crash/symbolUploads_getLocation), maybe that would be easier?

But we absolutely hear you that a UI would streamline this for all users!

**Comment by cainejette** [comment]
If you use the API today to upload symbols, we return the symbol upload ID you would use to query that second API directly. If you use the UI to upload symbols, you'd unfortunately need to call that first API to get the right symbol upload ID.

**Comment by theeagle** [comment]
Yeah, we use the API to upload symbols, but it might be days/weeks later that the symbols need to be downloaded, so the upload ID wouldn't necessarily be readily available at that time. But again, I could query it when they are uploaded and store them off for future reference.

**Comment by theeagle** [comment]
I saw this morning that I can now download symbols. Thanks!!

One minor request, would it be possible to include the build number in the download view? It was fairly tricky to match a symbols upload with the respective release.
