### ISSUE TITLE
MSAuthTokenContext authTokenHistory - Failed to retrieve history state or none was found. Note: this is happening only on FIRST launch after install

### ISSUE THREAD

**Issue by Taxi4you** [microsoft/appcenter#1342]
I have severe issue on iOS preventing from app being loaded and stuck on the splash screen. This is the error:

**2019-11-08 12:32:01.751569+0200 MYAPP[2503:103445] [AppCenter] WARNING: -[MSAuthTokenContext authTokenHistory]/210 Failed to retrieve history state or none was found.
Note: this is happening only on FIRST launch after install.**

I am not using any auth service from Appcenter.

**Comment by blparr** [comment]
Hello, would you mind reaching out to our support team? You can contact us from the App Center portal directly. Thank you.
