### ISSUE TITLE
[UWP] Automatically fetch symbols from Microsoft Store Partner Center

### ISSUE THREAD

**Issue by maxkatz6** [microsoft/appcenter#1343]
Hi!
Thanks for better UWP support in AppCenter SDK, so we can leave HockeyApp!
But I have one hope, so it could be even more useful with it.

**Describe the solution you'd like**
High level flow:
1. Link once application in AppCenter with concrete Store app
2. Upload new package to Store in Partner Center as usual
3. AppCenter on new crash/error will request symbols for concrete platform and upload it.
4. On next crash/error AppCenter can use already uploaded by them symbols as usual.

**Describe alternatives you've considered**
I don't see alternative solutions except existing manual work.

**Additional context**
I noticed new message on usymbolicated tab with instructions, how to get symbols from store to upload them in AppCenter. And I thought, that AppCenter can get symbols from store without additional work for developer.
I know, that it is not huge work for us to download from one place and upload in another, but it is annoying to do it every new build.

Thanks!

**Comment by winnieli1** [comment]
Thanks for the feature request! This is something we looked into and would definitely like to support. However, due to other priorities, this isn't on our short term roadmap. We'll keep this feature open to track interest and post here with updates.

**Comment by maxkatz6** [comment]
Hi! Is this feature planned for specific release, so we can wait it?

**Comment by maxkatz6** [comment]
I guess this feature waits until old UWP will be replaced with WinUI 3 for Desktop. 
But, on other hand, there is WinUI 3 for UWP...

**Comment by asierpn** [comment]
Please, we still want this feature, we release new versions of our UWP application frequently and downloading the symbols from the Partner Center to manually upload to AppCenter is a waste of time.
