### ISSUE TITLE
Adding multiple users to distribution groups

### ISSUE THREAD

**Issue by obikanubi** [microsoft/appcenter#1344]
**Describe the solution you'd like**
Add multiple users to a distribution group by uploading a plain text file.

**Additional context**
Screen shot from hockey app: 
![Screen Shot 2019-11-10 at 10 09 06 AM](https://user-images.githubusercontent.com/29720321/68537652-c8ff9600-03a2-11ea-8027-ac602bbda85b.png)

**Comment by ScottArbeit** [comment]
@obikanubi Thank you for the idea! 

I have no specific timeline to offer for when we would do this, but I'm going to leave the issue open to see if we get more feedback about it.

In the meantime, I have a sample app at https://github.com/ScottArbeit/App-Center-Bulk-Import for using the App Center REST API that demonstrates adding users to organizations and teams. It could be easily modified to do the same for distribution groups. I hope it helps (and I should probably at some point expand it's usage for this situation until we have this functionality in App Center). We also have the App Center CLI that might help you quickly write a script to accomplish this task.

**Comment by obikanubi** [comment]
Thank you. The CLI worked like a charm.

> @obikanubi Thank you for the idea!
> 
> I have no specific timeline to offer for when we would do this, but I'm going to leave the issue open to see if we get more feedback about it.
> 
> In the meantime, I have a sample app at https://github.com/ScottArbeit/App-Center-Bulk-Import for using the App Center REST API that demonstrates adding users to organizations and teams. It could be easily modified to do the same for distribution groups. I hope it helps (and I should probably at some point expand it's usage for this situation until we have this functionality in App Center). We also have the App Center CLI that might help you quickly write a script to accomplish this task.
