### ISSUE TITLE
Suggestion for custom event log improvement 

### ISSUE THREAD

**Issue by www0488** [microsoft/appcenter#1348]
**Describe the solution you'd like**
The user can be able to see fully printed JSON output in the custom event log UI. Because currently, AppCenter is not supported to read the whole JSON output string:
[https://docs.microsoft.com/en-us/appcenter/sdk/analytics/android](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/android)
**Describe alternatives you've considered**
If it's not possible, can we have at least one function which can track down what information belongs to which user?
Currently, the event format in AppCenter is like:
**With the current custom event log structure, it's impossible to indetify the indivedual information from each user**
_________________
- UserID
- Message
- Name
- Age
__________________

**Here is the format which I would like to see in this AppCenter**
__________________
- UserID
  - Message
  - Name
  - Age
___________________
**With this format, it's very easy to track the information from each user and it will help the developer a lot to track down bugs.**

**Additional context**
This function will help me a lot with bug tracking. Because In some of these cases, I have to put a lot of time effort to make sure the function is working in every type of device. With this custom event log improvement, it will reduce the time spent during the bug fix test case scenario.

**Comment by Oddj0b** [comment]
Thank you for the feature request, I've assigned colleagues who can investigate it further.
