### ISSUE TITLE
Support Build Filtering In Web UI with Analytics Disabled

### ISSUE THREAD

**Issue by gestrich** [microsoft/appcenter#1349]
On Hockey's website, it was possible to filter crash reports by both version and build. Using AppCenter, this does not seem possible. The dropdown boxes offer version numbers to filter by. But after selecting the version, the build dropdown box will show "All" rather than any build numbers. This is a inconvenient as we can't easily share links with crashes for a particular build.

I contacted support and was advise this is by design as we do not have App Center analytics enabled in our app. Note that you can work around the issue by inputting the build number in the url.

**Comment by elamalani** [comment]
@gestrich Thanks for adding this feature request. We will discuss it with the team for prioritization and keep this thread open for visibility.

**Comment by winnie** [comment]
Hi @gestrich, we recently removed the Analytics SDK dependency for the Diagnostics build filter. Thanks for your patience!
