### ISSUE TITLE
API - Enforce consistency between POST release_id/groups and PATCH release_id

### ISSUE THREAD

**Issue by Brantone** [microsoft/appcenter#1350]
Low priority.

So looking at these 2 API end-points:

1. https://openapi.appcenter.ms/#/distribute/releases_addDistributionGroup (POST `{release_id}/groups`)
2. https://openapi.appcenter.ms/#/distribute/releases_update (PATCH `{release_id}`)

They both have similar functionality in that they distribute a version to a group; however, the first one only allows for group `id`, but the second one allows for group `name` (if `id` not provided).

Sure would be nice to allow the first one to have `name` so don't have to do subsequent round-trip to look up `id`.

**Comment by botatoes** [comment]
Thanks for the request. I will take this back to the team for prioritization.
