### ISSUE TITLE
install.appcenter.ms should have account settings access

### ISSUE THREAD

**Issue by astearns** [microsoft/appcenter#1352]
I was not initially able to figure out how to get to my account settings when I got an email notification with an install.appcenter.ms link. It took some time for me to figure out I needed to log in to appcenter.ms to get to the settings to turn off email notifications.

Steps:
1. Follow an email link to install.appcenter.ms
2. Click on the user profile image (or placeholder)

Actual Result: The only option is to log out
Expected Result: Full account menu as you get on install.ms

**Comment by elamalani** [comment]
@astearns Thanks for adding this feature request. We will keep this issue open for visibility and will let you know once we prioritize to support it.

**Comment by botatoes** [comment]
Hi astearns, I am currently working with the design team to add more functionality to the user settings. I will take email notification settings back to the team for prioritization.

**Comment by lbrownell-gpsw** [comment]
This just hit us, as a whole lot of people just started getting new build availability notifications.

To be very specific, the notifications take the user to https://install.appcenter.ms, where you can go to your profile: https://install.appcenter.ms/profile.  However, your only option there is to log out.

https://appcenter.ms/settings is where your full settings are, which includes opting out of notifications -- which I keep getting asked about.

A link in the install profile page to the appcenter settings page would help a ton.
