### ISSUE TITLE
Select all distributiongroups as destinations on release.

### ISSUE THREAD

**Issue by Daniel-Frid** [microsoft/appcenter#1355]
**Describe the solution you'd like**
When releasing a new version of our Android app i'd like to have the possibility to select `All groups` as destinations. Today you can only select `All-users-of-MyApp` (all distr. groups of hockeyApp) but not all groups made in AppCenter. 

**Describe alternatives you've considered**
Today we have to slecect every distributiongroup manually wich can become tidious and also a high risc of leaving a group outside release.

**Additional context**
HockeyApp have this feature. I've mailed support about it and the feedback was to make a feature request.

**Comment by elamalani** [comment]
@Daniel-Frid Thanks for adding this feature request. We will keep the issue open for visibility and will let you know once we prioritize to support it.
