### ISSUE TITLE
Retry distribution when 2FA is expired

### ISSUE THREAD

**Issue by gunnartorfis** [microsoft/appcenter#1356]
When an iOS build fails and auto publishing is on to the App Store / Testflight, there's no way to re-publish the app without building it again. 

If the build itself succeeds but the publish fails because the **2FA** is expired, I have to reconnect with App Store and then build again from start.

**Comment by Oddj0b** [comment]
@gunnartorfis Thank you for the feature request.

**Comment by gunnartorfis** [comment]
This is still happening.

**Comment by gunnartorfis** [comment]
Still happening.
