### ISSUE TITLE
Why does appcenter distribute SDK needs android.permission.DOWNLOAD_WITHOUT_NOTIFICATION permission ?

### ISSUE THREAD

**Issue by Vikaass** [microsoft/appcenter#1359]
Why does appcenter distribute SDK needs android.permission.DOWNLOAD_WITHOUT_NOTIFICATION permission ? is there any way for distribution SDK to work without this permission? And why is this permission required?

**Comment by elamalani** [comment]
@Vikaass  We are looking at this issue and will get back to you with an update. Thanks!

**Comment by Vikaass** [comment]
Please look into it on priority as we have to make the new version release the next week.

**Comment by Vikaass** [comment]
@elamalani any update ?

**Comment by jwallra** [comment]
Sorry for the delay.  That permissions used to hide system notification for mandatory updates. We display a modal progress dialog instead in the app.  Mandatory updates cannot be postponed or canceled.  The permission does not require user approval and will thus not be listed in permissions on/off settings.

The fact that it doesn't appear in the app settings as a permission is something that the Android OS controls.

If you never distribute updates as mandatory, the permission will never be used.  However, there is no way to use the SDK without this permission.
