### ISSUE TITLE
Configurable granularity for concurrency of devices

### ISSUE THREAD

**Issue by namrog84** [microsoft/appcenter#136]
Enable more configurable granularity of how concurrency is handled for devices.

If we have an account with max concurrency of 5 devices
1. Let us have a test run that limits that test run to use only 1 concurrency.
e.g. appcenter test <snipped> --maxconcurrent=2

2. If we run 2 parallel test runs with 20 devices in each. Enable a round-robin distribution of which test run gets the next phone. (It currently fully allocates to first testrun until its completed)
e.g. via website 'checkbox round-robin device distribution' somewhere

3. Enable high priority test run.  So that even if other testruns were maxing out the concurrent devices. That the high priority testrun will be able be allocated phones fully before the next one.
e.g. appcenter test <snipped> --priority=3
e.g. appcenter test <snipped> --priority=1
(In the case of same priority, fallback to round robin or first in wins)

Current alternatives.
If we want to run 1 test on 10 devices. Instead of using a '1 device set of 10 devices' we can manually queue the same test on 10x device sets of 1 phone each and manage the above required features manually on client side. (Quite troublesome!)

Have more than 1 account in appcenter in which different sets of tests can be run against.

**Comment by Oddj0b** [comment]
@namrog84 Thank you for your suggestion! I can understand your request and keep an eye on this feature.
