### ISSUE TITLE
Generic deobfuscation script support

### ISSUE THREAD

**Issue by marcoburato** [microsoft/appcenter#1360]
**Describe the solution you'd like**
It would be nice if AppCenter could automatically save a deobfuscation map generated during a build and then, when a crash report is received, invoke a custom script to deobfuscate the stacktrace.

The script inputs would be:
- the stacktrace
- the deobfuscation map

and the output would be:

- the deobfuscated stacktrace

This would be a simple solution to support many obfuscation tools that would be time consuming to support natively in AppCenter.

**Describe alternatives you've considered**
The only other way currently is to copy-paste the stacktrace back and forth between AppCenter and an external deobfuscation tool. It's very tedious.

**Additional context**
For a bit of context, I'm using BabelFor.NET for a Xamarin app.

I assume you would probably want to run any user-provided script in a VM for security purposes. It would probably be very inefficient to spawn a VM each time a crash report is received, but I'd say it would be acceptable to run it once per day or on manual command to deobfuscate all the pending crashes.

**Comment by elamalani** [comment]
@marcoburato Thanks for adding this feature request. We will discuss it with the team for prioritization and keep this thread open for visibility.
