### ISSUE TITLE
Be able to see organization public distribution groups of the app

### ISSUE THREAD

**Issue by gmerinojimenez** [microsoft/appcenter#1364]
**Describe the solution you'd like**
We're using a public distribution group, created in the Organization and shared between multiple apps to distribute publicly releases. A developer with access to those apps can publish releases on that group using the API, but he is not able to see the group in the application's group page. We have added him as a tester to the group, but he is still not able to see it.

We would like to be able to see public distribution groups associated with an application. No matter where the distribution group is created.

**Describe alternatives you've considered**
We're not able to see any alternative.

**Additional context**
Don't hesitate to demand additional context if you need it.

**Comment by elamalani** [comment]
@gmerinojimenez Thanks for adding this feature request. We will keep the issue open for visibility and let you know once we prioritize to support it.

**Comment by botatoes** [comment]
Hi, we are currently working on some changes to the install page that will allow users to see all releases a tester has access to. This issue should be addressed by that feature.

**Comment by gmerinojimenez** [comment]
Hi @botatoes. Good to know that you're working on it :)

Then a public group is considered as a group that a tester has access to?
Also I was talking about the site (https://appcenter.ms/apps/...), where developers are not able to see the groups, not the install page
