### ISSUE TITLE
Publish/Subscriber model for Push Notifications

### ISSUE THREAD

**Issue by SteffenBurger** [microsoft/appcenter#1365]
**Scenario**
A backend service wants to send a push notifications to one particular customer. It does only knows the customer ID and the app ID.

The backend service does not know the customers device id or if he/she has an Android or iOS device.

**Describe the solution you'd like**
Azures Notification Hub and AWS Pinpoint provide the possibility to the clients, to register to certain "topics".

As soon as the customer is logged in within the app (Android or iOS), the app registers (subscribe) the client to the topic "app ID + customer ID".

The backend service can now simply publish a message to "app ID + customer ID" which is then send to the client through the aggregator service.

In _MS App Center Push_ I do not see how this publish / subscriber model could work.
Furthermore it seems that the REST API is designed to know the "app name"

/v0.1/apps/{owner_name}/{app_name}/push/notifications

Since there is no way to use the same "app name" for Android and iOS the backend service has to know both identifiers as well.

**Describe alternatives you've considered**
Store the "device ID" to each customer (which is not a good idea, since it is not invariant!)

Add additional logic into the business service :-(

- get customers "device IDs"
- get the app name for Android and iOS
- send the notification to the Android app (hope the user has an Android device)
- send the notification to the iOS app (hope the user has an iOS device) 

**Additional context**
Either I miss something, or the solution is not as competitive as the one in Azure or AWS.

**Comment by jwargo** [comment]
@SteffenBurger you can accomplish this in App Center push today using custom properties (Custom properties in App Center Push are similar to Tags in Azure Notification Hubs). You can set the property, then use it in an audience when sending notifications to users. 

Regarding the API, you're right - the App Center REST API uses the  App Center app name as part of the request URL, so to target devices for multiple apps you must submit multiple API calls. We have an initiative around implementing project groups which should fix this - please give your vote for the feature at https://github.com/microsoft/appcenter/issues/352.

**Comment by SteffenBurger** [comment]
@jwargo thank you for your quick reply!

I simply haven't seen it. Thanks a lot!

**Comment by alex-makarov** [comment]
It's worth mentioning that you can only have up to 200 audiences per app. So if you'd want to target small user groups with topics, that won't work - if I understand correctly.

**Comment by jwargo** [comment]
@alex-makarov that's correct. For more flexible audience options you must use Azure Notification Hubs.

**Comment by jwargo** [comment]
@SteffenBurger @alex-makarov  Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
