### ISSUE TITLE
Avoid App. name truncation

### ISSUE THREAD

**Issue by GLemire** [microsoft/appcenter#1366]
In the Overview page (possibly others) App name is truncated. It would be good to avoid that by simply wrapping the name on a second line...
![unnamed](https://user-images.githubusercontent.com/16034945/68795868-cc538580-061f-11ea-8fd1-49a18d244629.png)

**Comment by elamalani** [comment]
@GLemire Thanks for your feedback. We will keep this issue open for visibility and would let you know once we prioritize this work.
