### ISSUE TITLE
Unable to build macOS 10.15 apps

### ISSUE THREAD

**Issue by OskarGroth** [microsoft/appcenter#1367]
I'm building an app for macOS 10.15 (Catalina) using the latest SDK from Apple. Both of which has been publicly available for over a month. I'm using the latest Xcode 11.2 setting in App Center. However, App Center seems to be running Mojave. As a result, I can not build my app using App Center.

**Describe the solution you'd like**
Upgrade your builder to macOS 10.15 (Catalina).

**Describe alternatives you've considered**
Moving from App Center to another platform.

**Additional context**

```/* com.apple.ibtool.errors */
/Users/runner/runners/2.160.0/work/1/s/SenseiUI/CollectionUI/Views/Nibs/SettingCardViewItem.xib: error: The document "SettingCardViewItem.xib" could not be opened. Failed to unarchive element named "switch".
    Recovery Suggestion: NSSwitch is only available on macOS 10.15 or later.

** ARCHIVE FAILED **

The following build commands failed:
	CompileXIB /Users/runner/runners/2.160.0/work/1/s/SenseiUI/CollectionUI/Views/Nibs/SettingCardViewItem.xib
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65

**Comment by elamalani** [comment]
@OskarGroth Can you please open a support ticket with us by clicking on the blue icon on lower right side of the App Center portal?

**Comment by OskarGroth** [comment]
Right. I did open a ticket the second I created this ticket:

![19A2C280-510C-4A8E-B538-BE5FF36D0F65](https://user-images.githubusercontent.com/1417019/68983802-1188da80-080d-11ea-8629-223f1fb6c0c6.jpeg)

I’m not so sure this is a support issue though - it seems clear to me from the build log that the issue is that your builder is running an old version of macOS.

**Comment by OskarGroth** [comment]
And now I just got a reply from your support saying that "we support macOS 10.15 check our documentation: https://docs.microsoft.com/en-us/appcenter/build/software"

That documentation confirms that your builders are running Mojave which **is not capable of building macOS apps which uses 10.15-only components.**


Let me explain. If the following conditions are met, these are the requirements:

Developer wants to use the 10.15 SDK to make an app for macOS **<=10.15**
_Requires Xcode 11.0 or later._
✅ App Center supports this.

Developer wants to use the 10.15 SDK to make an app for macOS **>=10.15** that uses API's introduced in 10.15 (such as NSSwitch mentioned in my build error log, or NSCollectionViewDiffableDataSourceReference which I'm also using)
_Requires Xcode 11.0 or later **and build machine running macOS 10.15 or later**_
❌ App Center **does not** support this.

You need to upgrade your builders. More customers will start running into this issue. Please escalate this ticket to someone responsible for your build machines.

**Comment by King-of-Spades** [comment]
Reading this I added the "feature request" label just based on the description, before realizing you had added it originally, before being instructed to reach out to support. I'm attempting to double-check this due to the discrepancy.

**Comment by ranterle** [comment]
We are working on getting support for running builds on App Center using macOS Catalina. I can't provide an estimate of when this will ship yet, but we will update this ticket when we know more.

Also adding @nrajpurkar here for visibility.

**Comment by nilofer** [comment]
@OskarGroth we're releasing support for Catalina build agents Feb 1st! You can find more details [here](https://devblogs.microsoft.com/appcenter/updates-to-macos-build-agents/).
