### ISSUE TITLE
In UWP, Crashes.GetErrorAttachments needs an async version

### ISSUE THREAD

**Issue by TradeArcher2020** [microsoft/appcenter#1368]
Often the app will need to store application context information on the filesystem at the time of an unhandled crash.  Then, when the app is opened the next time and the crash is reported to AppCenter, that context file needs to be pulled off the filesystem and sent as an attachment along with the crash.  The proper way to do this in a UWP app is to use `ApplicationData`'s `LocalFolder` file/folder access methods which are all `async`.  Since `Crashes.GetErrorAttachments` is not asynchronous, it doesn't support this.  

Please consider adding an `Crashes.GetErrorAttachmentsAsync` version.

**Comment by elamalani** [comment]
Referencing related issue on App Center SDK repo - 
https://github.com/microsoft/appcenter-sdk-dotnet/issues/338

**Comment by elamalani** [comment]
https://github.com/microsoft/appcenter-sdk-dotnet/issues/338

**Comment by guperrot** [comment]
Hi, this is a legit use case indeed.

There are known work arounds in the meantime.

If you don't use user confirmation callback, by default `Crashes.GetErrorAttachments` is called from a background task from SDK, so it is guaranteed not to do work in UI thread already. You can thus put all your logic in `DoWorkAsync()` and then implement `Crashes.GetErrorAttachments` to call your `return DoWorkAsync().GetAwaiter().GetResult()`.

If you use user confirmation however with `Crashes.NotifyUserConfirmation(SEND)`, then the callback will be executed in the same thread as `Crashes.NotifyUserConfirmation(SEND)`, so the additional work around is to call notify inside a `Task.Run`.

**Comment by chrisaswain** [comment]
This is what we ended up doing that seems to work for our specific case.  This is in the constructor of App.xaml.cs like the docs show:

```
            _ = AttachErrorContextData();

            async Task AttachErrorContextData()
            {
                try
                {
                    byte[] appContext = null;

                    if (await ApplicationData.Current.LocalFolder.FileExistsAsync("appContext.json"))
                    {
                        var appContextFile = await ApplicationData.Current.LocalFolder.GetFileAsync("appContext.json");

                        try
                        {
                            appContext = await appContextFile.ReadBytesAsync();
                        }
                        finally
                        {
                            await appContextFile.DeleteAsync(StorageDeleteOption.PermanentDelete);
                        }
                    }

                    Crashes.GetErrorAttachments = errorReport =>
                    {
                        if (appContext != null)
                        {
                            return new[] {ErrorAttachmentLog.AttachmentWithBinary(appContext, "AppContext.json", "application/json")};
                        }
                        return null;
                    };
                }
                catch
                {
                    //if there is an exception trying to get the context of the last crash from the filesystem, just ignore it
                }
            }
```

However, it would be good to just have an `async` version of this so we don't have to resort to tricks to get it to work.

**Comment by guperrot** [comment]
Yes, I understand this is not ideal and the feature request remains open.

As to comment on your scenario, `Crashes.GetErrorAttachments` is set too late and can potentially be missed if `AppCenter.Start(Crashes)` works in the background faster than your setup code (unlikely to happen but possible in theory). You might need to keep a reference to your background task, set up the event before appcenter.start, then task.Wait() inside the callback.

**Comment by chrisaswain** [comment]
Not sure I follow you.  Could you provide some sample code to show more about what you are suggesting?

**Comment by guperrot** [comment]
Pseudo code based on my understanding of your app, which might be wrong:

```
             var task = AttachErrorContextData();

            async Task AttachErrorContextData()
            {
                try
                {
                    byte[] appContext = null;

                    if (await ApplicationData.Current.LocalFolder.FileExistsAsync("AppContext.json"))
                    {
                        var appContextFile = await ApplicationData.Current.LocalFolder.GetFileAsync("AppContext.json");

                        try
                        {
                            appContext = await appContextFile.ReadBytesAsync();
                        }
                        finally
                        {
                            await appContextFile.DeleteAsync(StorageDeleteOption.PermanentDelete);
                        }
                    }
                }
                catch
                {
                    //if there is an exception trying to get the context of the last crash from the filesystem, just ignore it
                }
            }

            // Assuming AppCenter.Start is right after here, I don't know your app code
            Crashes.GetErrorAttachments = errorReport =>
            {
                task.Wait();
                if (appContext != null)
                {
                    return new[] {ErrorAttachmentLog.AttachmentWithBinary(appContext, "AppContext.json", "application/json")};
                }
                return null;
            };
            AppCenter.Start(...)
```

**Comment by chrisaswain** [comment]
Ah, I see what you're saying.  Thanks.
