### ISSUE TITLE
DeviceSets (n choose k)

### ISSUE THREAD

**Issue by namrog84** [microsoft/appcenter#137]
To help minimize chance of being queued for a DeviceSet of 1 device.
Allow us to have a deviceset of X phones, but only deploy to a subset of them. (10 phone choose 1 phone)

e.g. Deviceset has 10 phones in it, but only deploy the test to any available 1 device among the 10 selected devices.
This would allow the user to minimize the chance of being queued for a test, if multiple phones are supported by the test.  

**Describe alternatives you've considered**
Query the appcenter for device availability and select a different deviceset of 1 phone depending upon allocations. 
Queue the same test on 10 devicesets and if 1 doesn't become queued for the device, cancel the other ones.

**Comment by namrog84** [comment]
Currently, I have never been queued for any device. So if appcenter always has enough phones of each type. This feature request is useless and pointless. However, as a niceness to appcenter and scaling. I would be okay with a scenario like this to be a friendly consumer.

**Comment by Oddj0b** [comment]
@namrog84 Thanks for another feature request. Another suggestion is to run the test on the first available snapshot with criteria like screen size, or operating system version.
