### ISSUE TITLE
Android crash symbolication fails if last stack frame is from android os or other 3rd party library

### ISSUE THREAD

**Issue by amattila** [microsoft/appcenter#1372]
When your app crashes on c++ code, and your own code is the last frame in stack, crashes are shown in UI and symbolicated correctly (using breakpad & dump_syms). BUT, if app bug causes library to crash or throw exception, so that the last frame in stack is from webview, this causes crash not to show up in crashes but in "Unsymbolicated" tab. Error message says it's missing "libwebviewchromium.so.sym".

It makes noi sense to run dump_syms, zip the files and upload every platform library on NDK, just to prepare for scenario where the crash might happen on some platform library.

Crashes should be shown, even if symbols are missing. Showing just the memory address is lot better than not showing the crash at all. This is also how Hockeyapp, Crashlytics and other crash reporting services work.

**Comment by cainejette** [comment]
Hi there! 👋We are working on a fix for this now. Stay tuned!

**Comment by cainejette** [comment]
Are you building/packaging the `.so` files within your app?

**Comment by cainejette** [comment]
If you don't want to upload debug symbols for this library, you can mark these as "Ignored" in the Unsymbolicated tab. See [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk#ignoring-symbols) for how to Ignore symbols you don't plan to upload. This way, the crashes will be shown, only partially symbolicated.

**Comment by cainejette** [comment]
We're also working on showing unsymbolicated crashes side-by-side symbolicated crashes, similar to how HockeyApp does. You can see this in our [iteration plan](https://github.com/microsoft/appcenter/issues/1322).

**Comment by amattila** [comment]
> Are you building/packaging the `.so` files within your app?

No, I’m talking about android os libraries that come with NDK. It does not make sense to symbolicate all platform libraries and send them over, as they are same for all apps. 

And no, I’m not packaging them within the app.

**Comment by amattila** [comment]
> If you don't want to upload debug symbols for this library, you can mark these as "Ignored" in the Unsymbolicated tab. See [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk#ignoring-symbols) for how to Ignore symbols you don't plan to upload. This way, the crashes will be shown, only partially symbolicated.

Instructions say “you can mark them as Ignored by selecting rows in the table and clicking the Ignore versions button.“, but there is no such button. Only “Upload symbols” -button.

**Comment by cainejette** [comment]
If you open a support ticket, we can look more closely at your specific case! There should be rows in that Unsymbolicated table that you can select, and that's when the ignore button appears.

**Comment by amattila** [comment]
> If you open a support ticket, we can look more closely at your specific case! There should be rows in that Unsymbolicated table that you can select, and that's when the ignore button appears.

Got that working. I need to select the app version with checkmark and say ignore version for that, not for the missing symbols. Bit weird UX but at least it works, thanks :)

**Comment by amattila** [comment]
Oh, and you need to have phone in landscape to see that checkbox.

**Comment by Oddj0b** [comment]
hey @amattila are you still having this issue?

**Comment by bhoopathik** [comment]
Hi,
This issue still happening. 

"**_libwebviewchromium.so.sym_**" is of 3rd party Android webview chromium library. 

Our Native crashes not processed to identify the file, line number and function name on which crash happened, even after ignoring the Unsymbilicated missing symbol "_**libwebviewchromium.so.sym**_".

It just saying showing memory addressed. as below 

MAIN THREAD - CRASHED

```
test_lib.so     0x8941928a + 11297419
lib123.so       0xb14257f7 + 2021367
                0xb2cfa82a + 6186
                0x1314998e + 5544334
                0xb2cfa82a + 6186
```

To be sure, i downloaded the same minidumo.dmp from appcenter and used stackwalker tool (https://github.com/mozilla-services/socorro/tree/master/minidump-stackwalk) to symbolification, that is working and able to identify file name,  line number and function where the crash happened.  But same minidump and symbol files, symbolification is not happening in Appcenter.

Please help us to resolve this issue.
