### ISSUE TITLE
Unable to search for testers in a distribution group

### ISSUE THREAD

**Issue by stevem-glu** [microsoft/appcenter#1374]
I need the ability to search for a unique tester in a Distribution Group, be able to sort the distribution group by name and after selecting the tester discover all the projects they have access to.
Currently there is no way to search for a unique tester in a distribution group. Even using the browsers search feature only searches the active screen and not the whole list of testers.
If the list was sorted by name that would help but the order seems to be random.

Also when removing a tester it would be helpful to know what projects they have access to and provide the ability to remove them from those projects rather than having to access all the projects individually.

**Comment by ScottArbeit** [comment]
@stevem-glu, Thank you for opening the issue... and, yes, we have plans to tackle this work over the coming months. Not sure exactly when right now, but it's coming. I'm going to keep the issue open to continue to get feedback about it, and we'll be back here to let you know when we prioritize these features.

In the meantime, I wrote a small sample app to demonstrate some of the App Center REST API functionality that dumps user lists from an App Center organization. You're welcome to check it out and see if it helps in the short-term. https://github.com/ScottArbeit/ListAppCenterUsers

**Comment by teamstap100** [comment]
This is a really important feature to me. I have a distribution group with ~2,000 members and it is an absolute nightmare to find and remove them currently.

**Comment by pranavi9** [comment]
I feel this is very important feature in App Center. Daily I am investing lot of time to revoke access for requested users who left our project. Please let us know if there is any workaround and how soon we can expect this feature?

**Comment by teamstap100** [comment]
I ended up using the [AppCenter REST API](https://openapi.appcenter.ms/) mentioned above, It is pretty convenient for removing users in bulk as well.
