### ISSUE TITLE
Re-allow to create accounts with email

### ISSUE THREAD

**Issue by lacostej** [microsoft/appcenter#1375]
**Our context**

We have about 10000 devices distributed to schools and they are pre-configured with a few hockeyapp accounts we have control over. End users do not know the HockeyApp/AppCenter passwords.

We sometimes have to create accounts for them or invite them into a group, e.g. if they reset or purchase new devices.

But not all our users have github/microsoft/google/facebook accounts. They do have emails.

**Describe the solution you'd like**

We would like to have the ability to create accounts with bare emails again (at least when being invited). It was removed during the migration to AppCenter.

**Describe alternatives you've considered**

**update**: right now we are considering creating new email addresses on our domains for our users, then create new Microsoft accounts associated with these emails.

¯\\_(ツ)_/¯

**Additional context**

**Comment by ScottArbeit** [comment]
@lacostej Hi! Thank you for writing this up.

Currently, in App Center, we have decided to use sign-ins backed by an external authentication provider; as you've seen, those are Azure Active Directory, Microsoft Accounts, Google, GitHub, and Facebook. We're doing this to improve system security, and I'm sorry that it's causing this problem for you. As you've found, the workaround for this is to create Microsoft accounts using the email addresses you want, and then logging into App Center with those Microsoft accounts.

I'm going to leave this issue open for a bit to gather more feedback about it... although I can't promise that we'll be able to prioritize this anytime soon, we've discussed the idea of using Azure AD B2C as our authentication system, which would subsume the other ones and re-allow any email address to be used (although the login would still have to go through Azure AD B2C).

**Comment by DimaElka** [comment]
@ScottArbeit I have over 100 QA engineers that have email boxes on our own self-hosted mail servers. I can't register MS account for them because it's not allowed to create an MS account with a custom domain name. And I can't control the list of one hundred "bigBoy1990" and "pinkRabbitNightmare" engineers nicknames and their personal emails for corporate software testing. What "system security" are you talking about? Do you think that personal emails are more secured than corporate email addresses?

**Comment by ploureiro** [comment]
Same for us, we have several thousands of partners users. And the friction to ask them to use other accounts is pretty high. We are also considering moving away of appcenter. As-is it's not designed to be used as an entreprise app store.
Whats the users want is a simple user/password login. Don't over do over-engineering here. 
Please just bring back the simple login form.

**Comment by marcomoscatiello** [comment]
is there any update on this? 
This issue where users cannot register to appcenter using their personal email and a password is really breaking our workflow. Is there any ETA for this to get fixed?

**Comment by retifrav** [comment]
> This issue will now be closed because it hasn't had any activity for 15 days after stale

Isn't that convenient. The issue nevertheless remains to be valid and unsolved.
