### ISSUE TITLE
See App Center's Deployment ID for Apple Store Groups on Portal Page

### ISSUE THREAD

**Issue by codemillmatt** [microsoft/appcenter#1376]
When setting up a *Deploy to App Center* task within Azure DevOps, you need to specify a unique ID for the App Center distribution group to deploy to.

You can obtain this through the portal by clicking on the wrench in the deployment group's settings.

Those do not appear for any of the Apple Store deployment targets.

It would be nice if you could see those IDs without querying via the REST API.

**Describe alternatives you've considered**
Querying via the REST API.

**Comment by Oddj0b** [comment]
Thank you for your feature request.

**Comment by douglassimaodev** [comment]
What is the api method to get the store id?
