### ISSUE TITLE
Deploy to External Testflight Group Via REST Without First Going Through Portal

### ISSUE THREAD

**Issue by codemillmatt** [microsoft/appcenter#1377]
I want to be able to deploy to a custom external TestFlight group in App Center via Azure DevOps.

To do that, I first need to perform a manual deployment through the App Center portal to that external TestFlight group. Then that group will show up in `distribution_stores` GET endpoint. At which point it can finally be a target from Azure DevOps.

Ideally, it would be nice to not have to manually deploy from the portal at all.

**Comment by Oddj0b** [comment]
Thank you for your feature request. I'm interested in how often you and our organization create new apps or external Test Flight groups?

**Comment by codemillmatt** [comment]
Thanks for the reply Villars. Creating external groups is not an everyday occurrence to be sure. However, if I have an Azure DevOps pipeline that depends on the REST functionality of App Center - wouldn't it make sense to be able to do all of this right from that? That defeats the purpose of a CI/CD pipeline if I have to manually go in and do a manual deployment.

**Comment by Oddj0b** [comment]
@codemillmatt I see and your explanation makes a lot of sense. I can't promise when or if we'll prioritize your feature request as we normally work on the requests with most 👍 or if it's an easy win.
