### ISSUE TITLE
Adding support of Scheduling a notification

### ISSUE THREAD

**Issue by mehul19851** [microsoft/appcenter#138]
**Describe the solution you'd like**
As a business user, i would like to have an ability to schedule a campaign/notification using App Center portal. The notification/campaign should be sent only as per scheduled date/time.

**Describe alternatives you've considered**
Currently, we are exploring the option of implementing the scheduling of notifications at our end. We would handle the scheduling functionality portion and then create/send the notification from the code using the App Center SDK.

**Additional context**
Scenarios could be as below:
- Send a notification after a new build is released as per schedule.
- Send a notification on new feature release as per schedule.

**Comment by jwargo** [comment]
@mehul19851 thanks for the suggestion.

**Comment by jwargo** [comment]
@mehul19851 that feature is in Notification Hubs today, will likely make it into App Center push later.

**Comment by jacob-israel-turner** [comment]
Hey @jwargo, just wondering if you have any updates here.  I'd use scheduled push notifications today if it were available.  Since it's not, I am building the scheduling on my end instead.

Thanks!

**Comment by jwargo** [comment]
@jacob-israel-turner No update yet, I've added it to our requested feature list and I'm working on prioritizing the list now.

**Comment by jacob-israel-turner** [comment]
Great - thanks so much @jwargo!

**Comment by jwargo** [comment]
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

The good news is that Azure Notification Hubs already supports scheduled notifications.
