### ISSUE TITLE
Please add clarity around issue reporting timestamps

### ISSUE THREAD

**Issue by gsnook** [microsoft/appcenter#1383]
**Describe the solution you'd like**
On the Issues dashboard, we often see reported listed as being reported up to two days into the future. We would like more clarity around what these report times mean, and why we would see timestamps listed as future events

**Describe alternatives you've considered**
We currently ignore Reporting Time as a field, as it does not seem to be reported against a consistent base time.

Example image, showing several events reported as two days in the future:
![image](https://user-images.githubusercontent.com/25618525/69095041-604d9480-0a06-11ea-8aa2-573ce63ccee0.png)

**Comment by winnieli1** [comment]
Hi @gsnook - the last report field is based on the device timestamp so you're seeing future times because the user's device time is in the future. We don't have any immediate plans to change this but I'll see if I can make the docs more clear. Thanks!

**Comment by gsnook** [comment]
I can see needing to use the devices local timestamp for capture time and upload time, however those can be subtracted to determine how old the event was at the time of upload in relative time. App center could always display times relative to it's own consistent clock. As in (TimeEventArrivedOnAppCenterClock - EventAgeFromDevice). Hopefully then everything is displayed in a consistent, intuitive manner.
