### ISSUE TITLE
Settings for notifications for each app

### ISSUE THREAD

**Issue by petersanta** [microsoft/appcenter#1386]
Dear App Center Team!

As a tester I would like to turn off/on the notifications for any app on my list.
There are some apps which is needed for me when I want to download them and I'm not interested in the continuous updates. I would like to turn off the notifications for these.

I have access to various apps. Where I am the owner, I can precisely set the notifications when I click on the app (under settings), but for those apps where I am a tester, I can not open the details page and can't access to the settings. For these apps just an install popup appears on the screen for me.

I talked already with the support, they asked me to create a feature request.

Thanks a lot!

**Comment by lauri-rovio** [comment]
We have tens of apps and new ones created constantly so it doesn't make sense that users need to go and disable notifications from each project separately. In addition it's not possible to turn notifications off from the projects you have only tester role. In most of the projects people are just testers.
It would be easiest if you could disable notifications globally as you can do now and enable notifications per app, which doesn't seem to be possible now.
