### ISSUE TITLE
Enable/Disable fingerprint when create a device set on Android

### ISSUE THREAD

**Issue by JanettHolst290490** [microsoft/appcenter#1387]
**Describe the solution you'd like**
When creating a device set in App Center for automated testing, I would like to enable fingerprint on the physical device.
- A fingerprint should be registered. It doesn't matter whose finger. It's fine that the fingerprint is rejected. I just need to see that the scanner appears.

**Describe alternatives you've considered**
I have considered https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-backdoors.
However, since I need it for debugging purposes of problems that users actually have in production, I need the realistic - actual - hardward capabilities.

**Additional context**
In our project we have 2 million users in production. And some users complaint that fingerprint is not working on newer devices.

For IPhone it’s not important, because there are a very limited number of IPhones out there and they don’t differ that much - we have enough devices on the project to cover all scenarios.
But for Android it’s impossible to have all different types of Android as test devices.

This tool would be very useful to see (1) is it really true or just a user problem, (2) did we solve the problem.

**Comment by Oddj0b** [comment]
Hey @JanettHolst290490, thank you for the feature request. I will have to see what we can do about it, as it seems `adb emu -e finger touch 1` isn't enough for your test scenario.

**Comment by longbien** [comment]
Hi! Is there any update on this? I would really need this feature. Thanks
