### ISSUE TITLE
Remote control on Android devices

### ISSUE THREAD

**Issue by JanettHolst290490** [microsoft/appcenter#1388]
**Describe the solution you'd like**
A new type of job in app center that does the following:
1. Install the uploaded app on a chosen device
2. Opens some kind of remote control connection to a user in App Center. Perhaps just a window inside the App Center client where you can click on the UI of a real physical device. Kind of like how the Chrome plugin "Vysor" works. 

**Describe alternatives you've considered**
To buy an Android device every time a user reports a bug that we cant reproduce. 
Not a long term solution. 

**Additional context**
For IPhone it’s not important, because there are a very limited number of IPhones out there and they don’t differ that much.
But for Android, it’s impossible to have all different types of Android as test devices.

**Comment by Oddj0b** [comment]
Thank you for your feature request.

**Comment by caisd1998** [comment]
This is manual test, you can try other cloud testing platform which has this feature.
