### ISSUE TITLE
Bulk remove releases from a distribution group

### ISSUE THREAD

**Issue by murdoch-david** [microsoft/appcenter#1389]
When viewing a group, you can see the Releases tab which shows you all the releases shared with this group. It would be useful if it was possible to bulk remove releases from a group, especially if numerous releases are shared with a group. For example, removing numerous "older" builds.

Currently, you can only remove one release at a time.

**Comment by Oddj0b** [comment]
Hey @murdoch-david, you can go through your release with the API which would help you remove multiple releases in bulk. I do understand it's not optimal compared to working in the portal.

**Comment by BillHoag** [comment]
Related: [Ability to select multiple releases to delete them](https://github.com/microsoft/appcenter/issues/200)
