### ISSUE TITLE
[Feature] default user role for distribution group

### ISSUE THREAD

**Issue by tele-bird** [microsoft/appcenter#139]
Frequently I create groups for users with higher permissions than "tester".  (such as a group of developers)  So, I want to be able to set the default user role for a distribution group.  When I add new users to a group, they should get the default role set for the group, unless I override it.

Alternatively, I can set all users with a custom role manually, but this gets rather repetitive.

**Comment by blparr** [comment]
Hi @tele-bird , thanks for your feedback. We will take into account for future prioritization.

Best regards,
Blanca
