### ISSUE TITLE
Support pagination on Distribute / Releases webpage

### ISSUE THREAD

**Issue by murdoch-david** [microsoft/appcenter#1390]
It would be useful to support pagination on the Distribute / Releases webpage. Currently only 1 page is loaded, which can cause the webpage to take a long time to load if there are numerous releases for an App.

For example we have apps which have over 1000 releases and selecting the page takes a while to load the entire list of releases.

As a suggestion, having a page limit of 50, with the ability to select different pages. Being able to customise how many to show one page would also be useful (20, 50, 100) for example.

**Comment by iageoghe** [comment]
This makes sense; we are looking into it.
