### ISSUE TITLE
Stack Trace is not matching in the Azure DevOps bug after app center bug tracker integration

### ISSUE THREAD

**Issue by swathisuvarna1** [microsoft/appcenter#1391]
Looks like the stack traces in app center are not matching with the stack traces in the Azure DevOps bug. The ADO bug does not have a copy of the full stack trace. Would it be possible to see more details in the bugs like the number of crashes that occured, device types and the time at which the crash occured?
![Stack Trace Comparision](https://user-images.githubusercontent.com/49498677/69169687-02788580-0ab6-11ea-8bbe-5a0889a79772.png)

**Comment by swathisuvarna1** [comment]
[https://github.com/microsoft/appcenter/issues/1315](url)

**Comment by winnieli1** [comment]
Thanks for the feature request! By design, we only show stack traces from app specific code but I can see why having the entire stack trace would be helpful. We'll keep this item open to track interest and prioritize accordingly.
