### ISSUE TITLE
Filter/sort people by role

### ISSUE THREAD

**Issue by petmac** [microsoft/appcenter#1395]
**Describe the solution you'd like**
When viewing the list of People in an organization, I would like to be able to filter or sort by Role.

**Describe alternatives you've considered**
Currently in order to check staff have the correct roles at my organization I have to visit them one by one. I don't think there's another alternative at present.

**Additional context**
We migrated our organization and apps from HockeyApp, and because our tag and app setup there was a bit higgledy-piggledy, the resulting App Center roles were not always a good fit.

Thanks!

**Comment by Oddj0b** [comment]
Thank you for a great feature request.
