### ISSUE TITLE
Unable to download some Android apps for some people with error message "Server data parsing error"

### ISSUE THREAD

**Issue by qchabeaudy** [microsoft/appcenter#1396]
Some of our users fail to download some of our applications with the following error message: "Server data parsing error".
The problem does not seem global because I manage to download this application.
Customers who have the problem see the application but when it clicks on it to see the different versions available, they get the error message and the screen remains blank.
Can you tell me if other Appcenter users also have this problem?
For your information, I migrated all applications from Hockeyapp to Appcenter several months ago and everything worked fine until two days ago.
Thank you in advance for your return
Cordially

**Comment by mbrands** [comment]
I think we have the same problem on some of our devices. I gathered some logs when the issue occurred.
[appCenter crash.txt](https://github.com/microsoft/appcenter/files/3874745/appCenter.crash.txt)

**Comment by MatkovIvan** [comment]
Hi @qchabeaudy ,

Could you please share some additional information that can help us to resolve this issue:

- SDK version
- Platform
- Application logs (change the log level to Verbose (`AppCenter.setLogLevel(Log.VERBOSE);` ) in your application and the SDK will print logs in the console)

**Comment by Oddj0b** [comment]
Is this issue still persisting?

**Comment by qchabeaudy** [comment]
Hello,
after some discussions with Microsoft support team and an application update throug Play store, everything is now ok :-)
Thanks
