### ISSUE TITLE
Lock in Initial MVP Requirements for the Data Sync Service

### ISSUE THREAD

**Issue by patniko** [Microsoft/appcenter#14]
To complement the new identity service and enable developers to easily manage end-user data we'll be developing a new Cosmos DB backed solution over the coming months. This will be initially targeted towards on-line first apps before layering in additional off-line capabilities. We'll share initial API's and screenshots over the coming weeks.

**Comment by Zakeelm** [comment]
Added information regarding our Token exchange service to our [PR](https://github.com/Microsoft/appcenter/pull/19), which will serve as the foundation for security for Data Sync. This service will allow the exchange of an app secret + an optional AAD B2C token for a CosmosDB resource token.

**Comment by myokeeh** [comment]
Is this to replace what used to be Azure Mobile Services with Offline Syncing using SQLite?

**Comment by RichiCoder1** [comment]
^ Same question. How does this compare to Azure Mobile Services?

**Comment by patniko** [comment]
@myokeeh @RichiCoder1 this won't replace Azure Mobile Services in the preview release, but it is our intent to build something those developers will happily transition to over the course of the year.

**Comment by fileman** [comment]
The "CosmosDB" backend could be reachable from external application? (as example ASP.NET or WPF)

**Comment by Zakeelm** [comment]
@fileman Yes, this is possible using the official CosmosDB SDK, but not the App Center SDK. You will need to implement authorization yourself as well to determine which users can read/write

**Comment by Zakeelm** [comment]
We've updated our [MVP Technical Specification](https://github.com/Microsoft/appcenter/pull/19) to now include offline scenarios. We're going to do a basic "Store and Forward" implementation, which is outlined and defined in the updated spec. 

In addition, we've also added mockups to our user scenarios! You can see a lot of the core user scenarios of the Data Sync service in these mockups. Feel free to comment on any of this and let us know your thoughts!
