### ISSUE TITLE
no WPF samples in repo

### ISSUE THREAD

**Issue by ranjan-ranjan** [microsoft/appcenter#1400]
There are no WPF samples in https://github.com/microsoft/appcenter/tree/master/sample-apps and https://github.com/microsoft/appcenter/tree/master/sample-build-scripts

**Comment by winnieli1** [comment]
Hi @ranjan-ranjan - thanks for the feedback! We have plans to improve App Center's sample apps and we'll definitely consider adding a WPF one as well. 

In the meantime, you can find a demo app with App Center already integrated in this repo here: https://github.com/diverdan92/Ignite2019

Hope that helps a bit!

**Comment by ranjan-ranjan** [comment]
Thanks. I got it.
