### ISSUE TITLE
Please stop offering a useless mobile site

### ISSUE THREAD

**Issue by CodingMarkus** [microsoft/appcenter#1401]
If the mobile site only offers a tiny subset of the actual features of the desktop site, its useless. Then either get rid of it altogether or at least allow users to switch to the desktop version. It's certainly okay to have a mobile site to optimize the layout for mobile devices but even with a different layout, all features should be offered. Most analytics info is not available on the mobile site, you cannot view the actual crash reports or their content, and so on. Nothing is personally more annoying to me, than a crippled mobile site. If this is still work in progress, then say on the site that it is WiP and offer a switch to the desktop version, until you are done.

**Comment by cainejette** [comment]
Hey @CodingMarkus ! I’m sorry you haven’t found as much use out of our mobile site as others have. You can switch to the desktop site under the hamburger menu, like so: 
![28CD5E52-CB74-4369-94FC-388DBDE6066E](https://user-images.githubusercontent.com/2633220/69586568-d5394500-0f97-11ea-8c05-04a530c3220e.png)

Hope that helps you while we continue to improve on it!

**Comment by cainejette** [comment]
Hey @CodingMarkus ! I’m sorry you haven’t found as much use out of our mobile site as others have. You can switch to the desktop site under the hamburger menu, like so:

![4F342236-ACDA-49E3-B7CE-E7BEF6C08080](https://user-images.githubusercontent.com/2633220/69586736-65778a00-0f98-11ea-963a-81c10ec9775c.jpeg)

Hope that helps unblock you until it meets your needs more!
