### ISSUE TITLE
Interact with ASWebAuthenticationSession in UI Tests

### ISSUE THREAD

**Issue by FinHorsley** [microsoft/appcenter#1406]
**Describe the solution you'd like**
To be able to interact with the `ASWebAuthenticationSession` browser that is displayed during an OAuth based login on iOS.

The `ASWebAuthenticationSession` browser is presented by the system (it isn't within the app sandbox), so the app doesn't have direct access to it; meaning that it doesn't show up via `REPL`. 

_For clarity, our UI tests are written with Xamarin.UITest_

**Describe alternatives you've considered**
We have considered the following:
- **[Backdoors](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-backdoors):** this sadly isn't an option for us as we solely use the OAuth flow for authentication on mobile devices (iOS). The mechanics of the Oidc Connect Hybrid flow means that we need to initiate the authentication request using the front channel, and then complete it using a backchannel.

**Additional context**
`SFAuthenticationSession` is the older, deprecated version of `ASWebAuthenticationSession`. 

#287 references the same issue, but has now been closed

**Comment by 1umesh1** [comment]
Has anyone got this issue solved,I am having same issue

**Comment by AndreyBespamyatnov** [comment]
Any updates? Have you found any solutions?
