### ISSUE TITLE
Better control of Diagnostics/Analytics

### ISSUE THREAD

**Issue by jerryhalstead** [microsoft/appcenter#1407]
With Hockey I could click on a version # and then the interface was all about THAT version. With App Center I have to click a popdown and select the version, then if I change from Diagnostics to Analytics I have to do it all over.  Also there's just a bunch of "junk" in the popdown, from old versions we don't care about to what look like random #'s (i.e. "324", "295") that I have no idea about.  

I'd like ability to archive old builds so they don't show up ... or, just ability to set the build once and then it "sticks" no matter where I go in the UI until I change it manually.

**Comment by nikiniki9doors** [comment]
+1
