### ISSUE TITLE
customise builds via Fastlane

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [microsoft/appcenter#1409]
**Describe the solution you'd like**
In the [App Center Changelogs](https://docs.microsoft.com/en-us/appcenter/general/changelog#august-23-2017) it says that:

> Use popular command line tools straight from your build: The build VMs come now with Fastlane and the App Center CLI pre-installed, so you can take the customization of your builds even a step further.

now I wonder how one would customise the build process using Fastlane. Specifically I would need to override these defaults from the [App Store upload](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple#set-up-the-connection-between-app-center-and-app-store-connect)

```javascript
 add_id_info_uses_idfa: false
 export_compliance_uses_encryption: false
 export_compliance_encryption_updated: false
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Oddj0b** [comment]
Hi, you can leverage Fastlane with [build scripts](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/).

**Comment by warrify** [comment]
this would mean I have to disable the app-center config for distribution and handle it myself?

**Comment by Oddj0b** [comment]
Yes or else it would make two releases. @warrify

**Comment by Frans-L** [comment]
@Oddj0b @warrify 

Do you have any example for the Post-build script that would upload it to AppStore?
