### ISSUE TITLE
Direct Download Link - Webhooks

### ISSUE THREAD

**Issue by narayan8291** [microsoft/appcenter#141]
I am trying to setup a CI/CD automation pipeline for mobile apps distributed via MS App Center. I configured a SLACK webhook to send POST calls for every version and build published for an app. 

The POST calls made to SLACK when a new version is published has no direct download links which I can use to download the new binary. 

I am trying to get the new binary (.ipa/.apk) file whenever a new version/build is published. Is this something possible via SLACK webhooks. Or is there an alternative approach which can used?

FYI, I can download a specific version by using the following link in App Center => https://rink.hockeyapp.net/api/2/apps/<some random ID>/app_versions/4?format=ipa&pltoken=...&avtoken=...&download_origin=hockeyapp&mctoken=...

I am trying to get the above link via webhooks or some kind of automation.

**Comment by tmdues** [comment]
This would be very useful for me as well, we have a few enterprise apps where we provide a direct download link in HockeyApp.
