### ISSUE TITLE
When is user redirected to web browser (install.appcenter.ms) for registration of In App updates ?

### ISSUE THREAD

**Issue by Vikaass** [microsoft/appcenter#1413]
I have put the code of app center for starting the distribution as follows:

Distribute.setListener(new MyDistributeListener());
AppCenter.start(getApplication(), "App center key", Distribute.class);

in the onResume of my main activity but the user is redirected to the webpage of (install.appcenter.ms) when some other activity is started. Can you please explain to me this behavior of when exactly is user redirected to (install.appcenter.ms) ?

**Comment by Vikaass** [comment]
@Zakeelm @botatoes it has been 7 days now, please reply ?

**Comment by Zakeelm** [comment]
Apologies for the delayed response, our office has been on holiday. Going to circle back with the team and we'll follow up with you shortly.

**Comment by botatoes** [comment]
Hi Vikaass, if you create a support ticket on appcenter.ms and someone from our engineering team can help look through exactly that's wrong.
