### ISSUE TITLE
Missing App Center Free Support - blue chat button

### ISSUE THREAD

**Issue by testshallpasswork** [microsoft/appcenter#1416]
I'm not seeing the "blue chat button" on App Center. I have used it in the past and now not seeing it. I tried on Firefox and Chrome browser. I have been a user since Mobile Center beta and have admin access to the apps I manage. Please let me know. Thanks for your time and help.

**Comment by jwhiteDev** [comment]
Hello! Do you have any adblocker enabled or have you tried to navigate to a new page/refreshing the view? Sometimes it disappears for me on a single page but navigating & refreshing has it appear once more.

**Comment by testshallpasswork** [comment]
@jwhiteDev Hi. Thanks for speedy response. I disabled adblocker (using uBlock origin) and logged in again on Chrome and the button is back. I did the same on Firefox and same result. 👍
