### ISSUE TITLE
How do I access the email address of the user that reported the crash? 

### ISSUE THREAD

**Issue by schriftgestalt** [microsoft/appcenter#1418]
The HockeyApp crash reporter UI has a name and email field. I can’t find the email in the App Center UI.

**Comment by Zakeelm** [comment]
Hi there! While we don't have this exactly replicated in App Center, we don't have means for user identification: https://docs.microsoft.com/en-us/appcenter/diagnostics/features#user-identification

Would this work for your use case?

**Comment by winnie** [comment]
Hi @schriftgestalt - App Center's user ID feature (linked by colleague above) should provide you the same functionality. Let us know if that works for you. Thanks!

**Comment by schriftgestalt** [comment]
What user id do you mean?
<img width="712" alt="Screenshot" src="https://user-images.githubusercontent.com/174660/72073903-2d7e9900-32f1-11ea-8644-b8cedc17b98c.png">
I don’t understand the text at the link. How should the user set its name? Hockeyapp would try to pre-fill the name and email (in their UI) and show that prominently. So I could get in contact.
