### ISSUE TITLE
Add Xamarin UWP as a Platform Selection 

### ISSUE THREAD

**Issue by Akinnagbe** [Microsoft/appcenter#142]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by derpixeldan** [comment]
@Akinnagbe can you please elaborate your request, why do you want a Xamarin UWP selection? Xamarin UWP is just a UWP project inside a Xamarin project, so it's still UWP.

**Comment by Akinnagbe** [comment]
hello, i thought there was a special selection for Xamarin UWP never knew i
could just select UWP.

Thanks

**Comment by derpixeldan** [comment]
@Akinnagbe yes, selecting UWP is sufficient. Which service do you want do use?

**Comment by Akinnagbe** [comment]
@Daniel Adams,  Crashes, Analytics, Distribution.

Thanks

**Comment by derpixeldan** [comment]
@Akinnagbe thank you, closing this issue. In case you have any problems, let us know.
