### ISSUE TITLE
Text on events and log flow is cut off after a certain number of characters

### ISSUE THREAD

**Issue by JamesBaxterSoftware** [microsoft/appcenter#1421]
I would like the text to not be limited and show the entire message attached to the event.
![textcutoff](https://user-images.githubusercontent.com/1244192/69617392-10875280-1030-11ea-8813-373062667bfe.png)

**Comment by Zakeelm** [comment]
Hey there!

Thanks for the feature request. This is something we can definitely look into and investigate further. Going to leave this open to gauge additional user interest for this feature.

**Comment by chesovnik** [comment]
Any results? Passed 4 years and still the same useless behaviour
