### ISSUE TITLE
Add the Distribute>Stores functionality for Windows UWP apps

### ISSUE THREAD

**Issue by tedmatuszewski** [microsoft/appcenter#1422]
I am trying to use App Center to release my UWP app to InTune such that I can distribute the app to my users. As it turns out this is only available if your app was written for Android or IOS. I find this to be very intuitive as you would think that App Center (now Microsoft owned) would support Microsoft technologies first. 

My request is that I would like App Center to be my one stop shop for application distribution regardless of platform. 

Without this feature, I am forced to use the InTune Powershell SDK to write a Powershell script to release the app to InTune within Azure Devops, which I have not proven yet, and is just conceptual. This means that for all my Android apps, I use App Center for dev/test/prod distributions. For my dev Windows apps I use App Center. But, for my prod Windows apps, I use a home grown Powershell script in Azure Devops. This inconsistency doesn't feel great to me. 

I believe this to be heavily related to Issue [#383](https://github.com/microsoft/appcenter/issues/383), but is really taking it up a notch and asking for the ability to release to both Windows Store and InTune.

I had previously spoken to Ali Farahnak, who recommended I submit this issue. He could probably provide even more context, as we had a really great conversation discussing my options.

**Comment by Zakeelm** [comment]
Hi,

Thanks for submitting a feature request. Assigning this to the product area owner, who can follow up with you regarding this request!

**Comment by tedmatuszewski** [comment]
> Hi,
> 
> Thanks for submitting a feature request. Assigning this to the product area owner, who can follow up with you regarding this request!

Thank you for the response Zakeelm.

**Comment by dpaulino** [comment]
Is this feature on the roadmap? I am a bit surprised that a Microsoft product integrates betters with third-party stores than with the Microsoft Store. Need feature would vastly improve my UWP deployment system.

Looking forward to a resposne.

**Comment by tedmatuszewski** [comment]
Thank you for your comments @dpaulino

**Comment by dpaulino** [comment]
@tedmatuszewski did you intend to close this issue or was it an accident?

**Comment by tedmatuszewski** [comment]
@dpaulino woops I did not mean to close. I just re-opened it. Thank you for the follow up.

**Comment by ramondeklein** [comment]
I was amazed to find out that Microsoft does support Apple's AppStore, Google's Play Store, but not its own Windows Store. No wonder that it doesn't become more popular when even MS doesn't take its own store seriously. It's like the people from Coca Cola can only buy Pepsi at work. 😉

**Comment by tedmatuszewski** [comment]
> I was amazed to find out that Microsoft does support Apple's AppStore, Google's Play Store, but not its own Windows Store. No wonder that it doesn't become more popular when even MS doesn't take its own store seriously. It's like the people from Coca Cola can only buy Pepsi at work. 😉
> 
> I am also wondering why I have the option to distribute to a store for an UWP application if it's not supported:
> ![image](https://user-images.githubusercontent.com/6048186/89299173-98fdce80-d666-11ea-9ffc-1b4ecff7f814.png)
> 
> This screenshot is from my UWP application's build settings.

I agree with everything you said in your comment @ramondeklein!

**Comment by hamidAbdalrahmanM** [comment]
Is there any update on this issue? We were planning to use this feature, but we found out that store distribution is not yet supported even though this issue was opened more than a year ago @Zakeelm @Oddj0b @dpaulino

**Comment by dpaulino** [comment]
> Is there any update on this issue? We were planning to use this feature, but we found out that store distribution is not yet supported even though this issue was opened more than a year ago @Zakeelm @Oddj0b @dpaulino 

I'm using Azure Pipelines and releasing to the store directly using a pipeline extension. It does exactly what I need.

**Comment by hamidAbdalrahmanM** [comment]
> > Is there any update on this issue? We were planning to use this feature, but we found out that store distribution is not yet supported even though this issue was opened more than a year ago @Zakeelm @Oddj0b @dpaulino
> 
> I'm using Azure Pipelines and releasing to the store directly using a pipeline extension. It does exactly what I need.

Are you deploying to Microsoft Intune directly from azure? or you mean appcenter?

**Comment by dpaulino** [comment]
I'm deploying to the regular Microsoft Store

**Comment by tedmatuszewski** [comment]
@dpaulino @hamidAbdalrahmanM 
I have been on a few calls initiated by support tickets through Microsoft trying to figure out how to do this or to find a work around. I haven't had much luck. My ultimate goal is also to upload the application to Intune. I would be willing to use App Center to deploy it to Intune, but given the lack of response I doubt that will ever be an option. 

In the calls, the best answer that I have gotten is to use the PowerShell SDK to upload the application to Intune using Azure Devops. A link to the reference documentation below. I gave it a pretty solid effort to adapt and make the sample labelled "Upload iOS LOB Application" to work with an Android application in our environment with no luck. 

I am curious, does the verification time that delays your release to the Windows Store cause any issues in your environment @dpaulino ? 

https://github.com/microsoft/Intune-PowerShell-SDK/tree/master/Samples

**Comment by FrogsLegs** [comment]
I agree with this, it should be a feature that is provided out of the box! How can MS support Play Store, App Store but not it's own offering of Windows Store?!

I know the current roadmap suggests the team are looking to improve the stability of App Center, but its there likely to be any movement on this at all in the (near) future? Seems like any progress has been abandoned...

**Comment by JPTGamesAndApps** [comment]
+1 for this feature request!
