### ISSUE TITLE
Support for Electron applications

### ISSUE THREAD

**Issue by JakeCohenMicrosoft** [microsoft/appcenter#1423]
We are looking for a way to distribute our Electron app for Windows and MacOS to alpha and beta users. 

We will ask internal teams that have built Electron apps how they distributed their apps to users without App Center/HockeyApp. Hope this support gets added!

**Comment by baileybrooks** [comment]
@JakeCohenMicrosoft Thanks for this feature request – This is something our team is looking into but we don't have immediate plans to support Electron apps. I'll keep this feature request open so our team can monitor community interest moving forward.

Thanks!

**Comment by gramland** [comment]
Hi all, any update on this?

**Comment by bppn** [comment]
Vote by me for supporting Electron apps!

**Comment by rachit-anurag** [comment]
Any updates on this topic ?

We use AppCenter as our internal distribution tool and we would like to onboard an electron application to the same.
