### ISSUE TITLE
Shallow Clone Build Support

### ISSUE THREAD

**Issue by daryl-fontaine-iugo** [microsoft/appcenter#1424]
In the App Center Build configuration, requesting the ability to configure a shallow clone rather than the default full clone.

We are connected to a self-hosted Gitlab instance, but our repository is large with a lot of history. A full clone takes upwards of 45 minutes, where a shallow clone takes under 1 minute.

**Comment by rahulatscore** [comment]
We are also facing similar issue due to large history. Is there a way we can use shallow clone instead of full default clone? It's been more than year since this issue is created, is there any progress or alternate solution?

**Comment by jb4e** [comment]
Why would anyone need a full clone here? Seems like this should be the default. Especially with the incredibly slow build servers and 60 minute build cap.

**Comment by jb4e** [comment]
This seems like it should be a 1-line fix and will shave a
significant amount of time for any repo with a large history.

**Comment by bgiacomelli-ebizmarts** [comment]
+1

**Comment by kinigitbyday** [comment]
I realize this just closed, but I feel like it should reopen. I can't think of any reason _not_ to shallow clone by default. Would appreciate an update here.
