### ISSUE TITLE
[Bug] stack traces sent from uploading crashes API cannot be shown on AppCenter portal

### ISSUE THREAD

**Issue by msdof** [microsoft/appcenter#1429]
Hi,

I used the API [Upload custom crashes via API](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-custom-crashes), with optional parameter `stackTrace` in exception.

The payload is like:

`{
    "logs": [
        {
            "type": "managedError",
            "timestamp": "2019-11-25T04:22:23.516Z",
            "appLaunchTimestamp": "2019-11-24T04:22:23.516Z",
            "processId": "123",
            "id": "bca65f46-46ee-451b-83bb-2e358c3f45bf",
            "fatal": true,
            "processName": "com.abc",
            "device": {
                "appVersion": "13.0",
                "appBuild": "1",
                "sdkName": "custom.android",
                "sdkVersion": "1.0.0",
                "osName": "android",
                "osVersion": "9.3",
                "model": "Pixel",
                "locale": "en-US",
                "appNamespace": "com.abc"
            },
            "userId": "TestID",
            "exception": {
                "type": "java.lang.RuntimeException",
                "stackTrace": "at com.google.gson.internal.LinkedTreeMap$LinkedTreeMapIterator.nextNode(LinkedTreeMap.java:544)"
            }
        }
    ]
}`

And I got successful response from API, on App Center portal,  I can find that crash record, but CAN NOT see the detail crash trace:
![image](https://user-images.githubusercontent.com/52813313/69702520-62140800-112a-11ea-8065-3eed1594be75.png)

I assume this's a bug? @winnie

**Comment by winnie** [comment]
Hi @msdof - please start a support ticket (blue chat bubble in App Center) so our team can better investigate. Thanks!

**Comment by Ajaykn21** [comment]
Hi @msdof, This issue has been fixed.
Now you should be able to provide the stack trace and can be seen in AppCenter portal like below
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/40024974/70975635-a83b0680-20ed-11ea-83a3-6ebc040d9496.png">
