### ISSUE TITLE
Group crashes and errors independent of version number

### ISSUE THREAD

**Issue by Brosten** [microsoft/appcenter#1430]
**Describe the solution you'd like**
When looking in the list of crashes and errors under Diagnostic > Issues I get a pretty long list and lots of them are duplicates, just with a different version number. I release a new version of the app pretty often, so filtering just by latest version of the app doesn't give me the complete Picture.

This also brings Another problem. Every time I release a new version of the app, I get e-mails informing me that a new crash Group was reported for all crashes. This makes me kind of "ignore" these emails, since 95% of them doesn't inform about a NEW kind of crash, but of the same crash that also existed in the previous version.

Please make it possible to Group all erros and crashes independent of their version, just like Raygun or mors other crash reporting platforms does.

**Comment by msdof** [comment]
I am encountering the same problem, which is not convenient for us to group crashes and errors, and loses productivity. BTW, this's supported by HockeyApp, so it one of the blockers for us to migrate to AppCenter.
@winnie Hope team can prioritize this feature request.

**Comment by winnie** [comment]
Thanks for the feedback! This is something we hear quite often especially from HockeyApp customers. I don't have an exact ETA but this is something we hope to change early next year. Thanks for the patience!

**Comment by tallior** [comment]
@winnie how are you going to tavkle this? Will there be an option to create a custom grouping based on my own parameters?

**Comment by winnie** [comment]
@tallior our plan is to group all crashes across versions into the same group. We don't have plans for custom grouping yet. What types of parameters would you like to group by?

Thanks!

**Comment by tallior** [comment]
@winnie i am looking at appcenter and wanted to know if we can (via some API) control how errors and crashes are grouped. Many times very similar errors are grouped under a new entry, causing a big headache for managing it.

From what i remember, BugSnag offers an API to control this: https://docs.bugsnag.com/product/error-grouping/

**Comment by easterapps** [comment]
@winnie  planned date for this functionality?

**Comment by akravch** [comment]
@winnie do you have any updates regarding this feature? Do you have it in your roadmap?

**Comment by Brosten** [comment]
still really missing this, but since MS seems to have abandoned AppCenter, I guess hoping for any progress is useless :(

**Comment by easterapps** [comment]
+1

**Comment by easterapps** [comment]
Issue still open.

**Comment by Brosten** [comment]
don't close...

**Comment by TedaLIEz** [comment]
+1 for this issue. We had to maintain storage to mark which reports should be ignored. Besides, we are struggling about how to find out crashes are only different from version number. Doing a full text match about the stacktrace seems expensive as we need to grep the stacktrace details from web api and then save it for comparing. :(

**Comment by easterapps** [comment]
Issue still open and needed.

**Comment by mj999999** [comment]
still very annoying that this is not possible!

**Comment by RL4291** [comment]
It is still an issue, would be cool to have a feature for that.

**Comment by easterapps** [comment]
Still open

**Comment by easterapps** [comment]
Still open and not answered
