### ISSUE TITLE
Edit & delete mappings

### ISSUE THREAD

**Issue by alxkzmn** [microsoft/appcenter#1432]
Currently there is no possibility to delete an uploaded mapping or edit its version settings.

**Comment by cainejette** [comment]
Hi there @alekskuzmin ! 👋 You're right that we don't currently have UI to accommodate deleting (or editing). Thank you for the suggestion! In the mean time, to unblock you, you can use [our API documentation](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-deobfuscation#deleting-a-mapping-file) to at least delete mapping files!

**Comment by tornadko** [comment]
Hello. Any changes here?
