### ISSUE TITLE
Per distribution group editor role

### ISSUE THREAD

**Issue by matsmalmstensc** [microsoft/appcenter#1437]
It would be great if permission to edit distribution groups could also be set per distribution group. Right now we have to give quite broad access to many users and would prefer to only give certain users access to edit certain distribution groups.

Example:
We have DG1, DG2, DG3, DG4
User1 - can edit DG1, DG2 and DG3 but not DG4
User2 - can edit DG1 and DG4 but not DG2 and DG3

**Comment by Zakeelm** [comment]
Thanks for the feature request! I can definitely see why this would be a desirable feature. Assigning to this product owner so that they can take a look at this request.

**Comment by lbrownell-gpsw** [comment]
This is kind of a big deal for us as well. In HockeyApp, this was done by making one or more distribution group members managers of the group.

For us, the only privilege we want that manager to have is the ability to add and remove members; not sure if the HockeyApp version had more power (like adding/removing apps), but if so, that's not wanted (by us--others may differ).

**Comment by jerietve** [comment]
See the MicrosoftDocs/appcenter-docs#739 for some more discussion. It's important this feature covers the ability to give users permission to manage distribution groups without giving them access to anything (including view permissions) of other apps, people or settings of the organization.

**Comment by lbrownell-gpsw** [comment]
As @jerietve says.  I asked, and chat folks explained that an app member can manage an apps distribution list -- but can also change app settings, problematic as described.

Note this needs to work for one-app and shared (multi-app) distribution groups.

And...the ticket @jerietve closed is one I commented on about this, in documentation.  While closed, obvs will need to re-do the documentation once this is implemented, which appears to be slated for first half of 2020.  Happy new year!
