### ISSUE TITLE
App Center: Analytics Section not Displaying Latest Version

### ISSUE THREAD

**Issue by Nupoor101251** [microsoft/appcenter#1439]
Hi App Center Support,

We are using app center for logging Crashes and Analytics. We configured build as per Group created for production in app center. Also, we have deployed our Latest Xamarin App build in Play Store and App Store on 25th November. However it still shows previous version not Latest version.

Also, we observed that crashes is not being logged from last few months. 

Please look into both issues and let us know accordingly.

**Comment by Zakeelm** [comment]
Hey there! 

Thanks for submitting this support ticket. I'm going to loop in our product owner, who can help and provide more insight on this.

**Comment by StefanKoell** [comment]
I have the same issue. I'm not seeing the last version. I also don't get any exceptions.

**Comment by winnie** [comment]
Hi @Nupoor101251 and @StefanKoell - can you please start a support thread via the blue chat bubble in App Center so our team can take a closer look? Thanks!

**Comment by StefanKoell** [comment]
Hi @winnie - I did that already a day ago or two...

**Comment by DmitriyKirakosyan** [comment]
This issue should be fixed now. I'm going to close it, but feel free to bump the thread if anyone still faces it.
