### ISSUE TITLE
The build queue isn't starting anytime soon even if there are no builds before

### ISSUE THREAD

**Issue by mike14u** [Microsoft/appcenter#144]
**What App Center service does this affect?**
Build

**Describe the bug**
Builds are queued for a very long time.

**To Reproduce**
1. Build a branch
2. Cancel the build
3. Try to build again
4. See the build queue for a long time

**Expected behavior**
Should build immediately

**Comment by patniko** [comment]
Hi @mike14u, mind reaching out to intercom support in the main App Center portal for help? We can check out your configuration to see if there is something going on.

**Comment by lklepner** [comment]
Hi @mike14u, @patniko  I believe my team has encountered this bug as well. 

Over the past few months we've found that our single concurrent build queue will become frozen if we cancel a build too quickly after its started. 

We haven't nailed down the exact steps to reproduce it but.. Our build jobs are set to build on push and sometimes we'll push twice in matter of a few seconds then quickly open appcenter and cancel the first build job which had just started... only to find the build queue is now frozen and the second push remains queued for quite a while (60 mins?). The first build will be marked as cancelled.

We've managed to steer clear of this bug by waiting for the "build agent" to appear in build detail before clicking cancel. And of course by canceling prior to start.

**Comment by stefanhk31** [comment]
We have just encountered this issue, too. Started when we set builds to run automatically on push, but still remains a problem after switching builds back to manual. Contacted support via App Center, but not sure what we're supposed to do until then.

**Comment by akhilraja-p** [comment]
Ive faced the exact same problem. Anybody have a solution yet ?

**Comment by Nevvulo** [comment]
I believe this is still an issue as we have also encountered this problem, my latest build is stuck in the queue even though there's nothing pending and other builds have been canceled.

**Comment by ksandiego** [comment]
> I believe this is still an issue as we have also encountered this problem, my latest build is stuck in the queue even though there's nothing pending and other builds have been canceled.

I am facing the same issue right now. Tried to build approximately 1 hour ago and it failed with no logs. Now builds are just stuck in queue.

**Comment by NeilWBruce** [comment]
Yep seem issue for me.  Anyone worked out how to get it to restart or does it eventually fix its self?

**Comment by ksandiego** [comment]
> Yep same issue for me. Anyone worked out how to get it to restart or does it eventually fix its self?

I queued another build about 12 hours ago and that failed randomly without logs as well. However, about 9 hours ago, the system started working fine. I didn't contact support so they were probably doing something.

**Comment by tronin** [comment]
Yeah, the same bug and we have got it since last year

**Comment by ximenaperez** [comment]
how do you build after that??

**Comment by bricepollock** [comment]
I was able to get around this issue by removing the configuration and then setting up the configuration again for the branch. Now my build is running.
