### ISSUE TITLE
UIKitForMac support

### ISSUE THREAD

**Issue by marcocattai** [microsoft/appcenter#1441]
Please make sure App Center works fine with Xcode 11 with UIKitForMac - even including it through Swift Package Manager - 

We cannot deploy our app on MAC without App Center and this is the only library which is not working yet.

Thank you

**Comment by peterstojanowski** [comment]
@iamclement @ahdbilal Any update on this?

**Comment by ahdbilal** [comment]
No updates as of now. But I will bring this up in our next triage meeting and will share the feedback here. Thanks for the follow up!
