### ISSUE TITLE
AppCenter Analytics and Push

### ISSUE THREAD

**Issue by ken-kn** [microsoft/appcenter#1442]
I am currently working on Android App with Xamarin Forms, and Im new to this AppCenter services. I would like to use AppCenter's Analytics, Crashes, and Push services altogether, but for unknown reason, when typeof(Analytics) is included in AppCenter.Start(), the Push services (such as Push.IsEnabledAsync() or Push.SetEnabledAsync()) will stop working.

![Capture](https://user-images.githubusercontent.com/58418536/69944595-ab959600-1522-11ea-8622-23efceceb0f7.PNG)

Is it possible to have all three of them being used together? Am I missing anything to do so?

**Comment by jwargo** [comment]
@ken-kn absolutely, there should be no issue using them together, customers do that all the time.  The example shown [here](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android#41-add-the-start-method) shows using two of them together, all you need to do is add Push and you're good. 

If you have problems getting this to work, just click the blue chat button in the lower-right corner of any App Center page to connect directly with our dedicated support team. They'll help you get through your issues.

**Comment by ken-kn** [comment]
Thanks for the reply, I just realize that the version for the AppCenter's Nugets are not updated to the latest version (was using 2.1.1 Analytics, 2.1.1 Crashes, and 2.6.1 Push). Updated all 3 packages to the latest version and my problem was fixed. Thanks again
