### ISSUE TITLE
AppCenters apps should not be platform or environment specific

### ISSUE THREAD

**Issue by kimbirkelund** [microsoft/appcenter#1446]
# Problem

Having to split an app you're developing into multiple apps in AppCenter makes it more difficult to get a handle on diagnostics and analytics. If you add having to have an app per environment (dev, test, prod, etc.) the amount of apps can explode, especially when developing white label solutions.

# Wanted solution

Make AppCenter apps platform/environment agnostic and provide those dimensions within the app itself. 

When creating a release you would then specify platform and environment, and these dimensions would then be available for filtering along when looking at releases, diagnostics, analytics, etc.

**Comment by bnoffer** [comment]
I think this can be very helpful as specially for cross platform apps.

**Comment by askpatrickw** [comment]
Especially when using cross-platform solutions (reactnative) it does not make business sense or operational sense to have several Apps running off of one repo.

**Comment by farwayer** [comment]
I have already opened a discussion about this feature in https://github.com/microsoft/code-push/issues/460.
Now three years later nothing has changed 😕 I still have to create two applications in appcenter for React Native iOS and Android. Oh just saw that we need to create a separate application even for each env 😮 

Firebase has this feature, Sentry (I use it for crash reporting RN apps now) has but not AppCenter. It is a little surprising.

**Comment by askpatrickw** [comment]
hey Bot. We still want this fixed. ;-)

**Comment by kimbirkelund** [comment]
Still interested.

**Comment by askpatrickw** [comment]
This is a must have feature.

**Comment by askpatrickw** [comment]
Yep.. this still needs to be fixed

Also, do I need to write a 30 day bot to battle the 60 day bot? Is that what it comes to?

**Comment by askpatrickw** [comment]
This issue has been manually updated to indicate it is desirable to fix.

**Comment by askpatrickw** [comment]
This issue has been manually updated to indicate it is desirable to fix.

**Comment by timvandenhof** [comment]
This is still something nice to have for crossplatform (native) Xamarin/MAUI apps, especially diagnostics.

**Comment by askpatrickw** [comment]
This issue has been manually updated to indicate it is desirable to fix.

**Comment by askpatrickw** [comment]
This issue has been manually updated to indicate it is desirable to fix.
