### ISSUE TITLE
I used HockeyApp because of feedback capability. Now it's the only thing that does not exist in AppCenter. I need Feedback functionality, that's it. I could go for variety of other solutions, but shouldn't I rather stay with AppCenter?

### ISSUE THREAD

**Issue by olegnaumenko** [microsoft/appcenter#1447]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by derpixeldan** [comment]
@olegnaumenko unfortunately App Center doesn't support Feedback. You can find alternatives [here](https://docs.microsoft.com/en-us/appcenter/transition/feedback).

Duplicate of https://github.com/microsoft/appcenter/issues/412
