### ISSUE TITLE
Analytics 1 view Android & IOS

### ISSUE THREAD

**Issue by GwnElviin** [microsoft/appcenter#1449]
**Describe the solution you'd like**
is it possible to see an overview of the analytics for android and iOS project
in 1 view instead of separate project views

**Describe alternatives you've considered**
I have considered looking into azure insights but I don't want that because it's a separate solution. I wanted to see if I could get the api calls of both analytics and create my own webpage for analytics web view

**Comment by Oddj0b** [comment]
Thank you for the feature request.
