### ISSUE TITLE
Match Application Insights schema when exporting

### ISSUE THREAD

**Issue by davestjohn** [microsoft/appcenter#145]
**Describe the solution you'd like**
Custom events are exported to Application Insights (when connected via Export) but the data that reaches Application Insights does not match the schema used.  The mismatch results in more data being sent, which is invalid for non-mobile, and the custom event data in a sub-dictionary unlike AI.

**Describe alternatives you've considered**
There are no exposed alternative solutions, the SDK needs modification.

**Additional context**
We are gathering analytics for Windows print drivers and desktop applications.  The use of the AppCenter SDK is to add analytics to the macOS print drivers. The Windows group is using the Microsoft provided Application Insights SDK and the data format it sends is the basis for the data queries already created.

The macOS AppCenter SDK, when exporting to Application Insights, uses a different schema than AI does.  The custom event data from AppCenter is put in root:customDimensions:properties and the custom event data from AI is in root:customDimensions.

In addition, AppCenter sends along fields that are mobile specific and/or empty.  We are sending data from a background process so screen size is always 0x0, is this useful data to send?  The Windows users generate 2 GB of data each day so sending non-useful fields is just wasted bytes.

Attached are 2 screenshots showing the difference in data between macOS and Windows.
![macos](https://user-images.githubusercontent.com/47667503/53810881-f64b9880-3f25-11e9-97c9-9f9571060cfd.png)
![windows](https://user-images.githubusercontent.com/47667503/53810882-f64b9880-3f25-11e9-9c14-b7b61b4aa90b.png)

**Comment by KSemenenko** [comment]
I need this!

**Comment by dahlbyk** [comment]
+1 for merging AppCenter `Properties` into `customDimensions` rather than using a nested object
+1 for not sending invalid data (0x0, lots of "None", etc)

**Comment by davestjohn** [comment]
What does the "reviewed-DRI" tag mean and what is the resolution of this request?  Just closing it without comment is in no way helpful.

**Comment by dahlbyk** [comment]
> +1 for merging AppCenter `Properties` into `customDimensions` rather than using a nested object
> +1 for not sending invalid data (0x0, lots of "None", etc)

Bump?

Plenty of work for this product team, I am sure, but it's hard to tell if this has even been triaged.

**Comment by davestjohn** [comment]
What is the plan for this bug?  It appears no one has even looked at it. Letting a bug go stale and the mfstbot close it is a lame approach to bug management.

This is still an issue and still a desired change.

**Comment by davestjohn** [comment]
Has anyone looked at this yet?

**Comment by davestjohn** [comment]
Post to make this stay alive, why doesn't someone address this issue instead of letting it go stale?

**Comment by davestjohn** [comment]
Post to make this stay alive, why doesn't someone address this issue instead of letting it go stale?

**Comment by davestjohn** [comment]
No addresses this issue, which remains an annoyance, and no one provides feedback on why this hasn't been done or even won't be done, instead it's left idle so it will auto close.

Please address this issue!

**Comment by davestjohn** [comment]
Post to make this stay alive, why doesn't someone address this issue instead of letting it go stale?

**Comment by KSemenenko** [comment]
I don't thnik appcenter in development. so porbaby we need to find something else

**Comment by davestjohn** [comment]
Fix this issue or at least comment if it won't be fixed.


> I don't thnik appcenter in development. so porbaby we need to find something else
Hopefully it's still in development, have you found a different SDK to use?
