### ISSUE TITLE
How to diagnose AppCenter SDK issues

### ISSUE THREAD

**Issue by StefanKoell** [microsoft/appcenter#1450]
I'm not sure if this is a feature request. Maybe there's a way to do what I'm trying to accomplish. If so, please let me know.

I'm using Analytics on WinForms and more than once, I find myself troubleshooting SDK issues. Sometimes it's related to the whole mess with nuget dependencies around sql-lite and sometimes because of bugs in the AppCenter backend or AppCenter UI.

I can see the "Log Flow" section in the UI which shows real time data as they come in. Unfortunately I have no idea what those IDs mean (the id column and the IDs of the start session).

It would be helpful if:
a) you can somehow retrieve the session id from the SDK
b) apply a filter to the Log Flow UI to only show entries from a specific session id

This way I can at least see if what my client reports, arrives at the backend. In a production app, it's impossible to see anything meaningful, except that there's data.

Thanks!

**Comment by winnie** [comment]
Hi Stefan - this is great feedback! I definitely agree the information we show to help troubleshoot SDK issues still leaves users a bit in the dark. We don't have any immediate plans to address this but I've tagged my colleague who manages this experience and will share any updates.
