### ISSUE TITLE
Include ability to specify .cer certs in addition to .p12 certs in iOS build

### ISSUE THREAD

**Issue by jefffhaynes** [microsoft/appcenter#1452]
Currently if developing in Windows for iOS, the process for converting .cer files to .p12 files is somewhat cumbersome and requires running openssl or something similar.  It would be nice if app center allowed the uploading of .cer files (the way Apple provides them) in addition to .p12 files.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @jefffhaynes! Definitely can see how this would be helpful for those developing using Windows.
