### ISSUE TITLE
Create official Github Actions for uploading mobile apps to app center

### ISSUE THREAD

**Issue by giem** [microsoft/appcenter#1453]
It would be really great if there was official support for the [Github Actions](https://github.com/features/actions). Especially for uploading the builds to the app center.

Currently there is an unofficial one, https://github.com/marketplace/actions/app-center-cli.

**Comment by Oddj0b** [comment]
Hi @giem, which destination would you like to push builds to in App Center?

**Comment by giem** [comment]
@Oddj0b  To the Distribution, basically this https://docs.microsoft.com/en-us/appcenter/distribution/uploading as GitHub Action

**Comment by Oddj0b** [comment]
@giem thank you for your feedback. We normally take on feature request based on reactions, the more the better, so I'm hoping for this to receive lots of :+1:

**Comment by harry248** [comment]
Would love to see that too!

**Comment by ahdbilal** [comment]
Thank you all for showing interest in this request. We have started looking into this feature and will love to schedule a few minutes call to understand the use case and expectation of this request. Please click [here](https://outlook.office365.com/owa/calendar/Microsoft2278573@microsoft.onmicrosoft.com/bookings/s/SDCU034kjkmOFHZcG0iKLw2) to schedule the call. Really appreciate your help with this feature request!

Thanks
Bilal
PM appcenter distribute

**Comment by cschembor-ww** [comment]
Definitely interested in this as well! Has there been any update regarding this @ahdbilal ?

**Comment by cbergstrom** [comment]
yeah. anything that helps removed the Microsoft stupidity as party of the deployment process is great. +1 from me. I tried to connect MS crap center with GH today and epic failure.

**Comment by ahdbilal** [comment]
@cbergstrom can you post the error? were you using one of the 3rd party distribute action or were you writing Action yourself.

**Comment by cschembor-ww** [comment]
Not to hijack this thread, but do you know if this issue relates to #159 @ahdbilal , and if there's been any status update on either?

**Comment by guntherpolzin** [comment]
How is the status of this issue? Is it recommended to use https://github.com/marketplace/actions/app-center-cli in between? best regards

**Comment by Syed-RI** [comment]
Hmm has there been any internal progress on this issue? I see the issue is closed despite some promises

**Comment by MarcelReiter** [comment]
Especially since there are already 61 upvotes on this issue @Syed-RI

**Comment by jl-mobitech** [comment]
It's been almost 3 years and still no updates? @Oddj0b @ahdbilal

**Comment by blwinters** [comment]
Odd that Microsoft is sleeping on this given that they own GitHub.

**Comment by Syed-RI** [comment]
Indeed!

**Comment by kobayashi-alec** [comment]
:(
