### ISSUE TITLE
AppCenter Test should report commit status to GitHub

### ISSUE THREAD

**Issue by caiofbpa** [microsoft/appcenter#1456]
**Describe the solution you'd like**
I would like to specify a commit SHA when scheduling tests in AppCenter via the command line, and having AppCenter Test report test status (pending, failure, success) to GitHub when the test finishes.

**Describe alternatives you've considered**
The alternative I have now is to run the tests synchronously, making my CI wait for the tests to complete and then the CI reports the status back to GitHub. But that is cumbersome and makes me waste build time waiting for tests.

**Additional context**
This could be extended in the future to other services like Bitbucket or GitLab

**Comment by Oddj0b** [comment]
Hi @caiofbpa, what an amazing request and it reminds me a little of #318. Where in GitHub specifically do you want to see the status?

**Comment by caiofbpa** [comment]
Hello @Oddj0b and thanks for the quick triage and reply!

This is different than #318 because the web hook for completion is better at notifying failing tests when those tests are triggered in the main branches of a repo, after a merge the code is integrated and then everyone in a team should know if anything fails. My main use case for that is posting to a Slack channel.

This issue is about posting test status to GitHub Commit Status (https://developer.github.com/v3/repos/statuses/) which is better when the tests are triggered in PRs. When everyone is working in their own branches, it's not ideal to having everyone notified in a Slack channel when someone else's test fails. So the commit status shows this information inside GitHub near the commit and also on the PR. This also allows us to mark AppCenter Test status as a required "success", preventing merges of PRs that break UI Tests.

Another remark is that for AppCenter Build there's already a sample build script made by Microsoft that does this commit status reporting: https://github.com/microsoft/appcenter/tree/master/sample-build-scripts/general/github-commit-status Unfortunately that doesn't work with AppCenter Test. This issue here means a more native integration with GitHub, with little or no configuration required by the user, other than connecting to GitHub for source integration and passing the commit SHA when running the tests. This also can mean a better integration for Build too, eliminating the need for a build script just to report commit status.

If you need any other info, I'm here to help!

**Comment by caiofbpa** [comment]
Actually, it just occurred to me: `appcenter-cli` could get the current commit by running `git rev-parse HEAD` and automatically sending the commit SHA over with no user interaction needed. If `git` is not present or `git rev-parse HEAD` fails, just disable the commit status reporting.

Many (if not all) CI solutions on the market offer this commit status integration out of the box. It should be quite trivial to implement.

**Comment by Oddj0b** [comment]
@caiofbpa thank you for the clarification now I have some more to work with. We prioritize feature requests based on :+1: and I hope this will make it to the top.

**Comment by dansiegel** [comment]
@Oddj0b I'd also really love to see this feature. UI Tests can take a long time to complete depending on a number of factors from available devices, concurrency and complexity of the UI Tests. It would be really helpful especially for PR's to see there are pending UI Tests and to be able to update GitHub when the Tests complete with either a Success or Failed status.
