### ISSUE TITLE
In-app update unexpected experience

### ISSUE THREAD

**Issue by msdof** [microsoft/appcenter#1457]
In-app update feature unexpectedly starts a browser to let users sign in with account. We cannot control the time of popping up browser, this’s not a good experience. 

Our selfhosters are complaining this “unexpected” update experience ,and don’t know what's going on when a browser unexpectedly opens up, they even thought it's a bug of host application

**Comment by ahdbilal** [comment]
Thanks for the feedback! We are currently working to it and will release a fix in two phase over the next month. Thanks
