### ISSUE TITLE
[Push] Support Push via Huawei HMS Core

### ISSUE THREAD

**Issue by bnoffer** [microsoft/appcenter#1458]
**Describe the solution you'd like**
Huawei is launching devices with Android Open Source and without Google Play Services. They have introduced their own Push service.
Since we are using App Center Push to unify our push notification backend it would be nice if support would be included.

**Describe alternatives you've considered**
There is none, because FCM is not supported on upcoming Huawei devices.

**Additional context**
The documentation for their push service can be found here: https://developer.huawei.com/consumer/en/service/hms/pushservice.html

**Comment by jwargo** [comment]
@bnoffer thank you very much for this suggestion. Unfortunately, we do not have any current plans to add support for additional Push services to App Center Push, but I'll add this to the list of features we're tracking for future plans.

**Comment by jwargo** [comment]
@bnoffer Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

Azure Notification Hubs does not currently plan on supporting any additional device platforms, but we'll continue to monitor Huawei's market penetration.

**Comment by Zapnologica** [comment]
We also need this feature. Now with the lack of support from google, our Huawei users cannot get pushes..

**Comment by jwargo** [comment]
@Zapnologica We have no plans to make any changes to App Center Push. We announced earlier in the year that we're retiring the service. Please read my previous response for details.
