### ISSUE TITLE
Include ARM64 as a valid architecture for UWP

### ISSUE THREAD

**Issue by rido-min** [microsoft/appcenter#146]
UWP can target ARM64 architectures, however if I build with AppCenter I cannot select ARM64.

**Comment by DerPate2010** [comment]
Any news on that? With the release of the Surface X shouldn't it be a key goal to encourage developers to support this CPU architecture?

**Comment by nrajpurkar** [comment]
@derpate2010 no update to share at the moment, but we are continuing to monitor this feature request.

**Comment by ahdbilal** [comment]
@DerPate2010 We have taken work on this feature and will be releasing the analytics/diagnostics support for ARM64 architecture soon (hopefully in early January if all goes as per the plan)

**Comment by ahdbilal** [comment]
Closing this issue as we have already released the SDK with ARM64 support.

**Comment by ValeraFinebits** [comment]
Arm64 option still unavailable for Build with AppCenter.
How soon it will be added?

**Comment by ahanag22** [comment]
@ahdbilal This should be reopened (or recreated) since we didn't implement it for Build.

**Comment by ValeraFinebits** [comment]
How soon ARM64 will be added?

**Comment by ValeraFinebits** [comment]
Arm64 option still unavailable for Build with AppCenter.
How soon it will be added?
