### ISSUE TITLE
SQLite package conflicts with EFCore 3.1

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/appcenter#1460]
See aspnet/EntityFrameworkCore#19156 .
The package doesn't conflict with EF 2.x, though they are using difference packages for SQLite.

**Comment by Oddj0b** [comment]
Hi @huoyaoyuan, I'm not sure what you're asking for. What service in App Center are you using?

**Comment by huoyaoyuan** [comment]
> What service in App Center are you using?

Crash report of UWP. But SQLite seems to be used by the shared AppCenter component.

**Comment by simader** [comment]
Matt tried explain it and wrote you an workaround. 
https://github.com/aspnet/EntityFrameworkCore/issues/19156#issuecomment-561890817

**Comment by nowheremanmail** [comment]
> Matt tried explain it and wrote you an workaround.
> aspnet/EntityFrameworkCore#19156 (comment)

After applied work around, application start but it doesn't find proper libs ...

`2019-12-09 15:05:34.899 [AppCenter] ERROR: An error occurred while initializing storage
System.IO.FileNotFoundException: Could not load file or assembly 'SQLite-net, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'SQLite-net, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'
   at Microsoft.AppCenter.Storage.StorageAdapter.<InitializeStorageAsync>b__10_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AppCenter.Storage.Storage.InitializeDatabaseAsync()`

**Comment by YZahringer** [comment]
I have the same issue after upgrade from EF Core 2.2 to 3.1 in Xamarin Forms app

**Comment by YZahringer** [comment]
Related issue https://github.com/microsoft/appcenter-sdk-dotnet/issues/569

**Comment by YZahringer** [comment]
I think it's fixed by https://github.com/microsoft/appcenter-sdk-dotnet/pull/1274

**Comment by michaldivis** [comment]
Any updates on this? It still doesn't work for me...

**Comment by simader** [comment]
Same here. We are waiting already for over two months. Seemed not to be too difficult

**Comment by michaldivis** [comment]
@simader This problem seems to be resolved in version 3.0.0. Yaaaay! I've tested it just now.
