### ISSUE TITLE
Feature to delete multiple/all events in list

### ISSUE THREAD

**Issue by vinjegaard** [microsoft/appcenter#1461]
**Describe the solution you'd like**
Option on "Events" page in Analytics to delete multiple/all events in the list.

**Describe alternatives you've considered**
Delete all events one by one, I have hundreds of old events from developing the app in the list so this would take a long time to delete one by one.

**Additional context**
Standard checkbox in first column thead to select all checkboxes in each row.

**Comment by maxmin88** [comment]
Yes this is a good feature.
