### ISSUE TITLE
Be able to view who has downloaded specific release

### ISSUE THREAD

**Issue by vinjegaard** [microsoft/appcenter#1462]
**Describe the solution you'd like**
I would like to be able to see a list with which testers that have downloaded a specific release.

**Describe alternatives you've considered**
n/a

**Additional context**
This feature could be a simple dialog box that appears when hovering over the download count (Total and/or Unique) in Distribute/Releases page.

**Comment by shpakovski** [comment]
Not only testers, it would be great to know everything about the Download e.g. via Azure subscription. Thanks in advance!
