### ISSUE TITLE
Add to Documentation Delete/Remove App

### ISSUE THREAD

**Issue by Buzzker** [microsoft/appcenter#1463]
**Describe the solution you'd like**
I would like the documentation at https://docs.microsoft.com/en-us/appcenter/dashboard/creating-and-managing-apps mention deleting the app.
It was hard to find the option.

**Describe alternatives you've considered**
I tried to googling and couldn't find an answer. Trying to transfer the app via "three dots button" I found the option to delete the app.

**Additional context**
None.

**Comment by jerietve** [comment]
There is a dedicated GitHub repo for App Center documentation where you can submit requests or even make changes yourself: https://github.com/MicrosoftDocs/appcenter-docs/issues

Anyway, we (I) will add this documentation this or next week. Thank you for noticing it is not there.
