### ISSUE TITLE
Is there any rate limiting for uploading custom crashes API

### ISSUE THREAD

**Issue by msdof** [microsoft/appcenter#1466]
There is a rate limiting for Hockeyapp:
`We limit requests to 60 per minute and App ID. If the limit is exceeded, please throttle your scripts.`

https://support.hockeyapp.net/kb/api/api-basics-and-authentication#rate-limiting

I would like to confirm here if there is similar limitation for [App Center uploading crashes API](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes)

**Comment by yoannchaudet** [comment]
There is no limit just yet in App Center but we are porting over the HockeyApp rate limit in the next few days.

Just like in HockeyApp you can expect a 60 crashes per minute (per application) limit.

**Comment by yoannchaudet** [comment]
The HockeyApp limit of 60 crashes per minute (per application) has been implemented. Public documentation around this should be out soon.
