### ISSUE TITLE
Add Team Name option in appcenter_upload

### ISSUE THREAD

**Issue by abhishekbedi1432** [microsoft/appcenter#1467]
**Describe the solution you'd like**
I would like to have an option in the app_center upload command to specify my team name so that the builds can be the identified team name. 
The reason I want this feature is that we work in different teams and would like to upload different features to be tracked a part of a particular team under the same account.

**Describe alternatives you've considered**
As of now, to segregate the builds we use build number series like
100 series for Team A
200 series for Team B, and likewise

Or need to change the version number itself

**Comment by Oddj0b** [comment]
Thank you for another feature request.
