### ISSUE TITLE
Add Release Notes Column to Release History Page

### ISSUE THREAD

**Issue by abhishekbedi1432** [microsoft/appcenter#1468]
**Describe the solution you'd like**
Currently the Release History Page on App Center has various column like Release No., Date, Destination, etc but it does have an associated **Release Notes** Column.

Release Notes Column will help users to easily identify builds especially when we work in multiple teams/squads format and daily each team uploads a build for QA

**Describe alternatives you've considered**
We tried Changing the build version number and release notes info when we upload the app but the release notes are only visible when we tap on a certain release to see the details. It becomes cumbersome when we need to find a particular release when different teams are uploading builds daily.

**Comment by Oddj0b** [comment]
@abhishekbedi1432 What would you like to see in the **Release Notes** column an icon, boolean, or the whole release note?

**Comment by abhishekbedi1432** [comment]
@Oddj0b  Just the text
