### ISSUE TITLE
HockeyApp > AppCenter did not move all the releases for my application

### ISSUE THREAD

**Issue by cristianatolea** [microsoft/appcenter#1469]
Sorry for bothering and writing here, but I encountered an issue after transitioning to AppCenter and I really need to find a solution. The documentation and other resources weren't very clear or helpful.

**Describe the solution you'd like**
AppCenter should migrate all the latest releases that appeared in HockeyApp.

**Describe alternatives you've considered**
A more explicit documentation of what the transition consists of and 

**Additional context**
I have recently migrated an application from HockeyApp and I have seen discrepancies between what appears to be the latest release in HockeyApp and what appears in AppCenter. In HockeyApp the latest release appears to be from October 2019, but in AppCenter I can only find 4 releases from 3 years ago. Can you please help me discover why weren't the other versions transferred to AppCenter? I would very much appreciate an answer on this matter.

**Comment by lumaxis** [comment]
Please contact us via [support](https://docs.microsoft.com/en-us/appcenter/help) so we can take a look at your particular app.
