### ISSUE TITLE
[Feature] add capability of exporting or syncing crash reports 

### ISSUE THREAD

**Issue by JanabiSoft** [microsoft/appcenter#147]
**Describe the solution you'd like**
add capability of exporting or syncing crash report or title as a task to other apps like trello or microsoft todo, directly or through another service like microsoft flow or IFTTT.

**Additional context**
e.g. creating a new card in trello board containg: 
[Bug] ShellPage.SignInAction (Investor.XF.Forms.SignIn arg1) as a title and 
"System.ArgumentException: An item with the same key has already been added. Key: 0" as a description

**Comment by winnieli1208** [comment]
This is a great suggestion! We don't have any direct integrations with Trello or Microsoft Todo but you can configure [webhooks](https://docs.microsoft.com/en-us/appcenter/dashboard/webhooks/) to work with these apps. 

App Center also integrates with Jira, Azure DevOps, and Github to automatically create bugs when there's new crashes come in. You can find more information in our [bugtracker documentation](https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/).

**Comment by JanabiSoft** [comment]
Thanks,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
