### ISSUE TITLE
Add support for tracking Downloads vs Updates

### ISSUE THREAD

**Issue by shpakovski** [microsoft/appcenter#1470]
HockeyApp collected statistics about existing customers who updated their app e.g. via Sparkle. So it was convenient to track adoption of your software. However this feature seems to be missed in the App Center. Could you please add a new column next to the chart “Active users per version”?

I checked your API, and this information is not available. So we have no way to track Updates. These charts look like all installations are new which is not true:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/163410/70371779-87ea9b00-18e8-11ea-8d67-22f6f8caaf76.png">

Thanks in advance!

**Comment by Oddj0b** [comment]
Hey @shpakovski and thank you for the suggestion.

**Comment by dlautz314** [comment]
Without a way to track downloads for applications updates, it is relatively useless other than providing a repository for distribution. Hockey provided this simple feature, which was incredibly useful in distribution of non-store apps (desktop apps), as per the original poster...in providing adoption rates.

This was not a big ask, and we will be looking for an alternative service that can provide these simple analytics.
