### ISSUE TITLE
Searching for a specific release version

### ISSUE THREAD

**Issue by murdoch-david** [microsoft/appcenter#1475]
**Describe the solution you'd like**
Allow the user to search for a specific release of a build. After selecting Releases it would be useful if there was a search field so you can enter the release you are searching for.  Additionally, being able to see autocomplete results for the search would be useful too. Example being entering ".cert" which will filter all releases to ones containing this in the string.

This would be a particular useful feature for Apps which contains hundreds or thousands of releases.

**Additional context**
This was previously available on Hockeyapp, where you can select a version, and there would be a dropdown where you could manually enter a string, showing you auto-complete results for releases you were searching for.

**Comment by Oddj0b** [comment]
Thank you for your feature request.
