### ISSUE TITLE
Upload symbols UI unclear

### ISSUE THREAD

**Issue by viktorszekeress** [microsoft/appcenter#1476]
When uploading symbols of my UWP app, I can't figure out, which architecture version it needs, if it's ARM, x86 or x64. All I can see is name of the app, "unknown" and some guid, see the attached screenshot.

![appcenter_symbols](https://user-images.githubusercontent.com/45604126/70456599-b1552380-1aae-11ea-915d-5951df605b86.jpg)

**Describe the solution you'd like**
A clear and concise description of what symbol version it needs/are missing. I remember that some time ago, there was a dedicated page for that, with the list of all app versions and I could (un)check which version to ignore. I can't recall how I get to that page, now I don't see any button to navigate there.

**Comment by matthiaswenz** [comment]
Thanks for bringing this to our attention - we'll look into this and see whether we can resolve this.

**Comment by TheJoeFin** [comment]
This issue could be resolved with #1343
