### ISSUE TITLE
Run Xamarin UI tests locally in parallel

### ISSUE THREAD

**Issue by olenka93** [microsoft/appcenter#1478]
**Describe the solution you'd like**
Xamarin.UITest runs test cases locally in parallel for more scalability. Now it is not possible to make it run on two or more simulators locally, only using App Center is a solution for parallelization. But with the new XCode, it is possible to launch the app in parallel, so there is no limitation with Instruments utility or Xcode. 

**Describe alternatives you've considered**
The alternative solution is to make Xamarin.UITest open source so people who can not use cloud App Center could make personal investigation in parallelization issue.

**Comment by FinHorsley** [comment]
+1 for having Xamarin.UITest open-sourced 🙂

**Comment by Oddj0b** [comment]
Thank you for your feature request. Let's hope it gets more reaction.

**Comment by MichaelSafro** [comment]
Please re-open, running it on 2 or more emulators would help!
