### ISSUE TITLE
[FEATURE REQUEST] Add support for Visual Studio Extensions for UWP Windows apps

### ISSUE THREAD

**Issue by potudopotudo** [microsoft/appcenter#148]
Currently I have a 10240 app that cannot be built in Appcenter because it relays on a Visual Studio Extension that I cannot reference in the Appcenter build system.

Add first class support for this as there are a lot of apps out there with VSExtension dependencies. Not all the UWP apps have a couple of nuget dependencies, most of the apps have third party dependencies in difficult to integrate with the current Appcenter build pipeline.

**Comment by patniko** [comment]
Hi @potudopotudo, have you tried a post-clone or pre-build script that will install the extension dependencies prior to running a build? Most people use those scripts to install missing dependencies related to their specific projects.

**Comment by potudopotudo** [comment]
Hi Patniko, I reached this page https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/ but this is meant to be for Xamarin, don't locate this for Windows UWP apps there, thanks.

**Comment by potudopotudo** [comment]
Thanks patniko. I'll take a look, but I have a .vsix installed in my PC and I don't know how can I extract the dll from there and reference it into my UWP project
