### ISSUE TITLE
Can't search keyword in 'Attachment text'

### ISSUE THREAD

**Issue by LeoLeeCN** [microsoft/appcenter#1480]
**Describe the solution you'd like**
The filters for search issue don't contains attachment text.

**Describe alternatives you've considered**

**Additional context**

**Comment by Oddj0b** [comment]
Hey @LeoLeeCN, is this a feature request for App Center Diagnostics?

**Comment by Petr-2019** [comment]
Yes, does AppCenter team has a plan for this? It's really useful
