### ISSUE TITLE
Make OpenCV software library available for Appium test runs

### ISSUE THREAD

**Issue by annabutenko** [microsoft/appcenter#1481]
**Describe the solution you'd like**
OpenCV is a library based on machine learning which allows to run visual tests using Appium server. I installed the OpenCV locally using these instructions https://opencv-java-tutorials.readthedocs.io/en/latest/01-installing-opencv-for-java.html and now we want to implement visual tests to our projects.

**Describe alternatives you've considered**
Installing OpenCV on your system

**Additional context**
Our company would like to start executing such visual tests as soon as possible. We use AppCenter for running functional tests on real devices, so it would be perfect for us to continue using your device cloud also for such new type of testing :)

**Comment by nrajpurkar** [comment]
Thanks for the feature request @annabutenko. Tagging in @Oddj0b who can shed some more light on this feature request.

**Comment by Oddj0b** [comment]
Thank you for your feature request. We normally prioritize feature requests based on popularity and hopefully, this one will get enough 👍
