### ISSUE TITLE
Analytics - LogFlow - Toggle to display logs, not in "trimmed / compact" way

### ISSUE THREAD

**Issue by majirosstefan** [microsoft/appcenter#1482]
**Describe the solution you'd like**
![appcenterRequest](https://user-images.githubusercontent.com/44647381/70533305-21b87f00-1b59-11ea-8848-72efbc79377d.png)
)

**Describe alternatives you've considered**
![AppcenterRequestConsole](https://user-images.githubusercontent.com/44647381/70533894-495c1700-1b5a-11ea-880f-2dbe07bd1a90.png)

**Additional context**
It would be really useful to have ability to display all data from row -  I know that appcenter's logs could be easily forwarded to another services for "post-processing", but in some environments developers do not have access to these services and use only appcenter ..)

**Comment by nrajpurkar** [comment]
Thanks for the feature request @majirosstefan. Tagging in @winnie who can shed some more light on this feature request.

**Comment by majirosstefan** [comment]
oi
