### ISSUE TITLE
Keep history of builds on forced/replaced branches

### ISSUE THREAD

**Issue by stvansolano** [microsoft/appcenter#1483]
**Describe the solution you'd like**
If a branch gets pushed/forced/replaced into VCS the build, AppCenter loses track of my previous history/build details even that my branch is back.

- Given that, my only options are to re-configure the build or clone it back from other configuration.

- It would be nice to have a "Previous Build history" option or something similar to keep traceability of my branch (commits are already there) and see previous commits that triggered my builds, so I don't lose traceability from my branch being replaced with a further/fixed branch version.

- For "Distribute" sections, show the "source" branch where the distributed version came from.

**Describe alternatives you've considered**
- Since my build history gets reseted every time a branch is forced/replaced, I had to track separately the dates/versions historically. Excel??

- The "Distribute" option kept somehow a history of what I passed but is somehow 'branch' agnostic.

**Additional context**
My `develop` (and other branches eventually) got replaced in VCS with a rebased version with commits from a merge conflict. Not really a brand new branch but it contains fixed conflicts and commits coming from my GitFlow. Technically and historically, is the same branch that I use with more commits added.

*In case it helps, reach out to me [stvansolano](stvansolano@outlook.com) at Twitter/outlook and I can provide a repo that illustrates the problem*

**Comment by nrajpurkar** [comment]
Thanks for the feature request @stvansolano. I can see how this feature would be helpful. We'll continue to monitor this request for future interest.
