### ISSUE TITLE
Make App Centre part of Azure Access Reviews

### ISSUE THREAD

**Issue by bakerm00** [microsoft/appcenter#1486]
**Describe the solution you'd like**
Integrate App centre into Azure Access Reviews to support large corporate compliance requirements to validate access to App Centre organisations.

**Describe alternatives you've considered**
manual reviews but this would be cumbersome

**Additional context**

**Comment by nrajpurkar** [comment]
Thanks for the feature request @bakerm00. Tagging in @iageoghe who can shed some more light on this feature request.

**Comment by ScottArbeit** [comment]
@bakerm00 Hi! Before I start... I'll just admit that I haven't used Azure Access Reviews before, so I just reviewed them and did some testing in a demo account I have. I am familiar with Azure AD in general.

So... I don't think Azure AD Access Reviews are appropriate for App Center. Access Reviews are a feature meant to audit users and groups at the Active Directory level, not users and groups within an app, even if that app is connected to an Azure AD tenant. It's a feature written by the Azure AD group, and I don't see a way for applications to inject themselves into it at all.

App Center's group constructs (i.e. teams and distribution groups) can include accounts that aren't in an Azure AD tenant, so an access review wouldn't cover them anyway. I would say that if you include an Azure AD Group in a Team or Distribution Group, then that AD Group could be subject to an Access Review, but that work is orthogonal to App Center's group memberships.

If you're using Azure AD groups and users with App Center, I'd recommend using [Conditional Access](https://docs.microsoft.com/en-us/azure/active-directory/governance/conditional-access-exclusion) if you can, to give you further controls on who has access. 

Does that make sense? I'm curious to know if you have another perspective on it. Thanks!

**Comment by bakerm00** [comment]
I’m coming at this from our security team perspective - if we have no means to control externally collaborators (where by they can see / change inner workings of the pipeline - ie not the testing/distribution groups.) we will have problems -  we have already tied down our aws access, azure subscription access,  crowd service to restrict access and we aren’t keen on another “loose” product
Ideally your entire identity framework should be tied direct to an azure subscription Iam model to make life easier in general.

Ultimately the lack of though in this basic security matter will probably see a limited use due to security restrictions until appropriate controls for corporate enterprise are established in product.

Btw Access reviews will include azure subscriptions at some point in 2020.


Mike Baker

________________________________

**Comment by bakerm00** [comment]
following on from this - its interesting that Azure DevOps is now introducing roles that can restrict who can do what.

and restricting alternate credentials that aren't sourced from an organisations Azure AD - https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/access-with-azure-ad?view=azure-devops
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/access-with-azure-ad?view=azure-devops>
Access your organization with Azure AD - Azure DevOps Services | Microsoft Docs<https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/access-with-azure-ad?view=azure-devops>
Important. Azure DevOps will no longer support Alternate Credentials authentication beginning March 2, 2020. If you're still using Alternate Credentials, you have until then to transition to a more secure authentication method, to avoid this breaking change impacting your DevOps workflows.
docs.microsoft.com



________________________________
