### ISSUE TITLE
Some users are not able to change email / notifications

### ISSUE THREAD

**Issue by scibidoo** [microsoft/appcenter#1489]
Please make user preferences easy to subscribe / unsubscribe to Notifications

People in our organisation are not able to click on their profile to modify the email notifications and are subseuently spammed every time a build is added.

Please make this easy for all users.

**Comment by derpixeldan** [comment]
@scibidoo I assume you mean that users can't opt out of notifications for an app they're Tester on? Currently it's only possible to [disable notifications globally](https://appcenter.ms/settings/notifications) for an account in order to avoid getting notifications.
