### ISSUE TITLE
Windows UWP app's version shown as build number

### ISSUE THREAD

**Issue by JuliusSkrisa** [microsoft/appcenter#1490]
UWP app's version is shown in a brackets (as build number for iOS or Android)
And version field is empty. However the version of UWP app should be shown as Version in app details not as build number. Also in a list of releases the version should not be in a brackets which indicates its build number.

![Screenshot 2019-12-11 at 10 16 36](https://user-images.githubusercontent.com/38064776/70607813-6bf43b80-1bff-11ea-94ef-f79279382e3f.png)

![Screenshot 2019-12-11 at 10 17 11](https://user-images.githubusercontent.com/38064776/70608161-f63c9f80-1bff-11ea-8bc4-c372e3cfa459.png)

**Comment by nrajpurkar** [comment]
Hi @JuliusSkrisa, thanks for creating this issue. Tagging in @botatoes to take a look at how this is getting parsed for releases.

**Comment by Brantone** [comment]
bump

**Comment by Brantone** [comment]
So this is gonna be a fun game ...

**Comment by JuliusSkrisa** [comment]
I have a fix which works for me: 
We threw our UWP app into the trash where it belongs.

**Comment by Brantone** [comment]
(bump)

**Comment by Brantone** [comment]
Surprised this still isn't addressed since Windows.

**Comment by Brantone** [comment]
<bump>

**Comment by Brantone** [comment]
.

**Comment by Brantone** [comment]
bump
