### ISSUE TITLE
Test Cloud support for Smartglasses

### ISSUE THREAD

**Issue by asugaya-apx** [microsoft/appcenter#1491]
**Describe the solution you'd like**
We would be interested in on-device testing support for smartglasses and other wearable displays (e.g. Google Glass Enterprise Edition 2, Vuzix M300/M400, RealWear HMT-1, Microsoft HoloLens 2), similar to the devices supported in the list here: https://docs.microsoft.com/en-us/appcenter/test-cloud/devices

**Describe alternatives you've considered**
Our current alternatives are to run tests on these devices manually, or to test these APKs (where applicable) on mobile devices and simulate as much as possible.

**Additional context**
We primarily use Espresso for testing the Android-based devices.

**Comment by nrajpurkar** [comment]
@asugaya-apx thanks for the feature request! Tagging in @Oddj0b to take a further look.
