### ISSUE TITLE
.NET Core 3.1.0 SDK in build servers or fix how NuGet packages are restored

### ISSUE THREAD

**Issue by daltonks** [microsoft/appcenter#1492]
Whenever the build server runs NuGet restore for my mobile apps, it restores projects that are not referenced by the mobile projects:

`[command]/bin/bash -c wget -P '/Users/runner/runners/2.160.1/work/_temp' https://dist.nuget.org/win-x86-commandline/v5.3.1/nuget.exe;/usr/bin/find . -name '*.sln' -type f -print0 | /usr/bin/xargs -0 grep -l 'Scribble.iOS.csproj' | /usr/bin/xargs -I '{}' mono '/Users/runner/runners/2.160.1/work/_temp'/nuget.exe restore '{}' -DisableParallelProcessing;rm '/Users/runner/runners/2.160.1/work/_temp'/nuget.exe`

Because of this, NuGet errors occur on my .NET Core 3.1.0 projects that just happen to be in the same repository:
`/Users/runner/hostedtoolcache/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(127,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 3.0 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/Users/runner/runners/2.160.1/work/1/s/Scribble/Scribble.API/Scribble.API.csproj]`

Note: `Scribble.API.csproj` is not referenced by my mobile projects.

I have not had this problem before with .NET Core 3.0.0 projects because the build servers have 3.0.0.

**Describe the solution you'd like**
Add the .NET Core 3.1.0 SDK to the build servers.

**Describe alternatives you've considered**
Updating NuGet restore to only restore the mobile projects and their project dependencies.

**Comment by daltonks** [comment]
I guess a feature that goes hand-in-hand with this would be to keep the build servers up-to-date with .NET Core SDKs. I surely will be with the other projects in the solution and don't want my builds to break in the future either.

**Comment by juanredondo** [comment]
I think this is not a feature but a bug, Appcenter select the Android.csproj to build but restore all nuget references, including projects that has not reference by mobile.

In iOs, as workaround, you can create a .sln only with your mobile project and builds OK, but in Android there is no way to do this.

**Comment by softlion** [comment]
2 yrs later same issue
