### ISSUE TITLE
Error installing AppCenter 2.5.2

### ISSUE THREAD

**Issue by mspvirajpatel** [microsoft/appcenter#1493]
[!] Error installing AppCenter
[!] /usr/local/opt/curl/bin/curl -f -L -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20191213-902-1j4aw6f/file.zip https://github.com/microsoft/appcenter-sdk-apple/releases/download/2.5.2/AppCenter-SDK-Apple-2.5.2.zip --create-dirs --netrc-optional --retry 2

https://github.com/microsoft/appcenter-sdk-apple/releases/download/2.5.2/AppCenter-SDK-Apple-2.5.2.zip - Missing path

**Comment by derpixeldan** [comment]
Hi, this is a known issue. We're working on solving the problem, until then, please use version 2.5.1.

For reference: https://github.com/microsoft/appcenter-sdk-apple/issues/1918#issuecomment-565338896

**Comment by dermaaarkus** [comment]
Is there any possibility to rollback the Cocoapods version too? thanks

**Comment by MatkovIvan** [comment]
App Center SDK 2.5.3 has been released
