### ISSUE TITLE
Get release notes from text file or build script for automated builds

### ISSUE THREAD

**Issue by ElteHupkes** [microsoft/appcenter#1495]
**Describe the solution you'd like**
I would like to be able to specify the release notes for an automated build through a text file or build script. Pushing to certain branches is almost a one step solution to a distributed build, except right now I still have to go in and manually change the release notes. The latest commit message tends not to be a suitable message to actually display to our users. It would be great if I had some other way of specifying a commit message for automated builds. 

**Describe alternatives you've considered**
I could try something through the API from a build script, although I'm not sure if I can still change the release notes once the build action is already underway, and setting up the tokens would be a hassle. I could also take the latest release notes and create a commit local to the build server that includes them. Depending on the order in which App Center fetches the commit message for the release notes this may be a viable workaround. Came up with this while creating this issue, I'll try ;).

**Comment by alexcnichols** [comment]
Thanks for reaching out @ElteHupkes. Adding some automation around release notes could make distribution easier, I agree. I've seen it done with commit messages over in GitHub and with work items in Azure DevOps before. Adding @botatoes for visibility and consideration with other priorities in this area.

**Comment by ElteHupkes** [comment]
@alexcnichols Thanks! For my potential workaround, do you have any idea exactly how the build fetches the latest commit message? I see at the end of my build log that a distribution task is called:

```
##[section]Starting: Create distribution
==============================================================================
Task         : App Center distribute
Description  : Distribute app builds to testers and ***s via Visual Studio App Center
Version      : 3.158.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
==============================================================================
##[section]Finishing: Create distribution
```

Which from [its documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops) seems to take either a file with release notes or a direct message, but I don't think I can see which one is used or where it comes from. If it uses the message from the exact commit hash that its building with I probably won't be able to change it in the build script, but in any other scenario I may have something to work with.

**Comment by alexcnichols** [comment]
Not sure @ElteHupkes. If you are considering the Azure Pipelines route.. the App Center distribute task does off that ability to reference a file in the repo. Since you mentioned that the commit messages themselves were more internally-facing than customer-facing, updating a CHANGELOG type of file in the repo with the latest release notes prior to distribution could be the way to go. https://docs.microsoft.com/en-us/appcenter/distribution/vsts-deploy

**Comment by ElteHupkes** [comment]
@alexcnichols Thanks, but currently everything is running through App Center and App Center alone, which I like a lot, so I'm probably going to keep on hoping for a workaround in that context - or a feature of course :).

**Comment by shrikanthkr** [comment]
This one seems to be a necessary feature when we totally rely on appcenter for building and distribution.

**Comment by calintamas** [comment]
+1

**Comment by jfrolich** [comment]
It would be very nice to have a way to set release messages during the build process. The latest commit message is pretty bad, and it would be nice to get it from the latest git tag or something. We could do it ourselves if release notes could be set by setting for instance a environment variable in the build process.

**Comment by clemblanco** [comment]
Please make an optional `CHANGELOG.md` or `CHANGELOG` file located at the root the default source for release notes when present rather than the latest commit message.

**Comment by jfrolich** [comment]
@clemblanco: Github releases using git tags are probably a more structured way of doing that (and you can pin a release to a commit).

**Comment by clemblanco** [comment]
@jfrolich I'm not sure I understand. We use Git tags and Github releases once it's all merged but the release notes on AppCenter when distributing or testing purposes are always using the latest commit message by default. Would be nice to have this grabbing the content of a CHANGELOG file instead.

This is what I'm talking about, on AppCenter:

![image](https://user-images.githubusercontent.com/668419/77895056-1a36f600-726e-11ea-932a-8e1fbbbe9bde.png)

![image](https://user-images.githubusercontent.com/668419/77894987-ff648180-726d-11ea-995e-48df7d905fc4.png)

This would be for the people testing a specific build from AppCenter to know what has changed. If we automate the distribution to a specific destination, we can only have one default value or have to manually type it in AppCenter every time.

**Comment by gturedi** [comment]
how can we put last 10 commit messages to release notes on gradle builds?

**Comment by github4es** [comment]
How are people doing the customer-facing release notes via app center now then?  
I see this is supported via the cli
```
appcenter distribute stores publish \
--file /path/to/file.aab \
--store Production \
--app {app_owner}/{app_name} \
--release-notes "Some note."
```

**Comment by ElteHupkes** [comment]
I do them by hand for production releases, and the beta releases just don't have release notes. Calling the API from a build script kinda seems to defeat the purpose to me.

**Comment by clemblanco** [comment]
Any news on this? I can do this using the CLI but I want AppCenter to automate that so I don't have to run any command myself.

```
appcenter distribute stores publish \
--file /path/to/file.ipa \
--store Production \
--app {app_owner}/{app_name} \
--release-notes-file CHANGELOG
```

**Comment by joehanna** [comment]
> Please make an optional `CHANGELOG.md` or `CHANGELOG` file located at the root the default source for release notes when present rather than the latest commit message.

This is a great concept which is also employed by other CI/CD providers. The build should take the release notes from a markdown file from within the repo, but the path to it usually defined in the build configuration (eg Bitrise)

Please, no more “magic” files/scripts in the root of the repo. Build scripts and files should be in a sub folder (`.appcenter`?) so they don’t have to be looked at every time we view the repo. These items are ultimately set-and-forget files.

**Comment by hugo-advizr** [comment]
We also need this for our use case since we distribute multiple apps on behalf of our clients and we’d like to automate the whole distribution process. 

Is there a workaround to programmatically set the release notes today?

**Comment by dkoprowski** [comment]
Hey, @hugo-advizr it is possible to use webhooks. I've created a simple Nodejs service that receives HTTP POST from AppCenter, generates description and edit description trough HTTP callback. 

It takes lots for workaround work and a server but it is possible...

**Comment by ElteHupkes** [comment]
It might be possible to do something with one of the build scripts, changing the release notes through the App Center API post clone. On the other hand, it's possible (likely, actually, when I think about it) that the whole build configuration is already retrieved at that point and it won't make a difference before the next build. That fact combined with how crappy this is to debug (you basically need to do a whole build and distribute to check if your approach is working) has kept me from pursuing this so far. Also, we have release notes in multiple languages, which aren't supported even manually in App Center right now.

**Comment by hugo-advizr** [comment]
@dkoprowski @ElteHupkes thanks a lot for your feedback, it seems any workaround today requires a lot of tinkering and even if possible it'll be flaky at best.

Can anyone from the AppCenter dev team (@botatoes @alexcnichols) give some feedback on the idea of simply allowing an env variable to be set to override the release notes for the current build? this seems pretty easy to implement and it'd allow for any logic to grab the contents on our end.

**Comment by coldacid** [comment]
I'm partial to using a tag message rather than a changelog file, since changelog files tend to have changes for more than just the latest version. A tag message is far more likely to have a list of only what's changed since the last version instead.

**Comment by jfrolich** [comment]
> I'm partial to using a tag message rather than a changelog file, since changelog files tend to have changes for more than just the latest version. A tag message is far more likely to have a list of only what's changed since the last version instead.

100% agree. It will have as the benefit that all those messages are part of the github repo (and easy to see what has been changed for a diff).

**Comment by rodrigomafei** [comment]
I believe reading a changelog file would be a good solution.

**Comment by joehanna** [comment]
Also, not only does the release email to testers not have real release notes, it has the last commit message from the repo. This is terrible, the repo commit messages are technical and could be private. It is not the business of the testers to see what the commit messages are.

**Comment by smakus** [comment]
Please add a feature to specify which file contains the release notes.  Limit it to a simple text file for now if you have to.  Anything is better than what we have now, which is nothing.

**Comment by nadjibus** [comment]
msft bot, go away. +1.

**Comment by coldacid** [comment]
Still waiting.

**Comment by Tchisky** [comment]
still waiting ...

**Comment by maoapp** [comment]
seriously

**Comment by ivanbaraka** [comment]
Doesn't look stale to me at all...

**Comment by FerBastiaens** [comment]
Still waiting for this feature which would be such an improvement.

**Comment by dickiezulkarnaen** [comment]
yes please, i'm waiting tooo

**Comment by coldacid** [comment]
Still waiting for this.

**Comment by EmilAlipiev** [comment]
Appcenter is probably dead. they will not continue developed. Hockeyapp, XamarinInsights and now Appcenter in the list. With Maui I am sure that MS will introduce something cooler 👯‍♂️

**Comment by leohenriquedev** [comment]
I've found a solution for this problem.
just add a cat command to print content of release notes file. For example:

``` 
appcenter distribute release --file app_name.apk --group "Collaborators" --app "user_name/app_name" --release-notes "$(cat release_notes.txt)"
```
**Remember to add a "release_notes.txt" file or whatever file extension that you want on root of project.**

That's it, enjoy everyone! ;)

#Brazil

**Comment by joehanna** [comment]
> Appcenter is probably dead. they will not continue developing. Hockeyapp, Xamarin Insights and now Appcenter in the list. With Maui I am sure that MS will introduce something cooler 👯‍♂️

You're probably right. I cringe when I need adopt their new tech as there is always threat of by them killing it off in a few years. You invest the time and infrastructure around their tools and then they abandon them. I now wish they left HockeyApp alone. It was great for what it was designed to do.

Microsoft have this new charter of a high release cadence and don't seem care about breaking changes, all with little regard to how it upheaves their loyal user base. It took 20 years to get to .NET 4.8, now there is a new major version every year. How are you supposed to keep up? 

With this new MO, it really makes it harder to stay loyal.

**Comment by joehanna** [comment]
So inaction from Microsoft results in tickets being closed. Great dev policy. Keeps the backlog short.

**Comment by Tchisky** [comment]
soo disappointing to see the issue closed without actually solving it
