### ISSUE TITLE
Crash times are wrong sometimes

### ISSUE THREAD

**Issue by martinbonaciugome** [microsoft/appcenter#1497]
### **Description**

Crash time are wrong sometimes, showing in the future on Android. Not sure if it happens on iOS

### **Repro Steps**

no idea

### **Details**

Android SDK 2.4.1

![image](https://user-images.githubusercontent.com/6127051/69458074-65228900-0d23-11ea-99d3-2ea1bf622e9b.png)

**Comment by akravch** [comment]
It would be something if there would be a way to at least see the time when a crash has been received by AppCenter.
