### ISSUE TITLE
App center- Screenshot and video of the test execution.

### ISSUE THREAD

**Issue by Pooja0907** [microsoft/appcenter#1498]
By just seeing the log it is difficult to analysis the issue.
For example if some id is not able to find by cloud appium, we can not predict the issue because it worked fine on local device.
And I get only one screenshot which is the just screen of the device which does not provide any clear picture.

![image](https://user-images.githubusercontent.com/51822374/70954766-9ee87480-20c2-11ea-8cdd-7bf7629906a6.png)

Issue log - which does not give the clear picture,(app crashed or in actually element did not appear because its running completely fine on local device using Maven as per the guidlines mentioned in the official website)
![image](https://user-images.githubusercontent.com/51822374/70954804-c8090500-20c2-11ea-877e-244828bd9203.png)

**Comment by alexcnichols** [comment]
Hi @Pooja0907 -- Thanks for reaching out. I could see how better visuals from App Center Test could better show what is going on during the test. Adding @Oddj0b for visibility.

**Comment by CBuntrock** [comment]
I think this is a very important feature. Screenshots/Video are possible in other frameworks like Cypress. An mp4-file often allows EASY reconstruction of the issue. Even with low fps...
