### ISSUE TITLE
App center: TimeoutException issue while finding the element on iOS device, however same code is running fine on local device using maven.

### ISSUE THREAD

**Issue by Pooja0907** [microsoft/appcenter#1499]
Can any one please look in the issue, I am not able to find out what is wrong here as I followed all the instruction give by app center official web site and still code is not working fine and I tried with the wait time for 250 -300 seconds but still it failed.
When I run the same code it is working fine without error on local device using maven.

![image](https://user-images.githubusercontent.com/51822374/70955866-5c289b80-20c6-11ea-9a67-e03dfa8d1b71.png)

**Comment by alexcnichols** [comment]
Hi @Pooja0907 -- This one could have something specific to your project, which is better handled through a dedicated chat with our support team. You can initiate a chat through that blue chat bubble in the lower-right section of https://appcenter.ms. I'll close the issue for now but we can re-open if you discover something like a feature request through your chat with support.

**Comment by Pooja0907** [comment]
Hi @alexcnichols I did  , but no support from them.As you can see its been more than a month, but still waiting for the reply.

**Comment by alexcnichols** [comment]
Hi @Pooja0907 -- Hmm.. strange that you wouldn't receive a response from the support team. Try starting up a new chat through App Center using the blue chat bubble in the lower-right section of the screen. Maybe your last inquiry was routed incorrectly.
