### ISSUE TITLE
UWP: support handled exceptions

### ISSUE THREAD

**Issue by winnieli1** [microsoft/appcenter#150]
Users would like the ability to track handled exceptions for UWP apps. Currently, this feature is only available for Xamarin and Unity apps.

**Comment by MartinZikmund** [comment]
This would be extremely useful. Crash reporting in Dev Center is not too useful for debugging so App Center would really help here.

**Comment by rdeveen** [comment]
I still think it is wierd that this feature is not implemented yet.

**Comment by cubed-it** [comment]
It is absolutely necessary to be able to send handeled exceptions! shouldn't it be a one-to-one substitute for hockeyapp? somehow this approach is lost to uwp? no sideload? no own exceptions? what the heck? please fix ;)

**Comment by dpaulino** [comment]
This is a must-have feature. @winnieli1208, given the number of reactions to this issue (it is now the top 3 most upvoted issue in the repo), any chance you have any updates? Thanks in advance.

**Comment by braydondavis** [comment]
Is there an estimated timeframe of when this is going to be released? I would really like to get it implemented in my UWP app. Thanks.

**Comment by MartinRichards23** [comment]
This is definitely our top request.

**Comment by winnieli1208** [comment]
@braydondavis  unfortunately I still don't have an ETA. We plan to start the Windows work listed in this [proposal](https://github.com/Microsoft/appcenter/tree/windows/specs/2019-04) around May. Currently, there are too many unknowns to give a reasonable estimate. I expect to have a better answer for you once the engineering work starts. Thanks for the patience!

**Comment by BjoernDreher** [comment]
@winnieli1208: Are there any news to this issue? We are developing an side-loaded app and actually we are  using the HockeyApp. The HockeyApp will be terminated this year and there is no alternative at the moment. That will cause a huge problem for us.

**Comment by winnieli1208** [comment]
@BjoernDreher no updates at this time. Our team is ramping up on the Windows work this week so we'll have a better idea of what work is required to support this very soon. No ETA right now because there are quite a few unknowns at the time. 

On a side note - since we only support handled exceptions for Xamarin apps, some App Center users track their errors using  [custom events](https://docs.microsoft.com/en-us/appcenter/analytics/event-metrics) in our Analytics service as a workaround. I understand this isn't ideal and there are limitations to this approach but it might be useful for some.

I'll keep communications open as our team learns more. I appreciate the patience!

**Comment by bezysoftware** [comment]
> 
> 
> @braydondavis unfortunately I still don't have an ETA. We plan to start the Windows work listed in this [proposal](https://github.com/Microsoft/appcenter/tree/windows/specs/2019-04) around May. Currently, there are too many unknowns to give a reasonable estimate. I expect to have a better answer for you once the engineering work starts. Thanks for the patience!

The link provided returns 404

**Comment by BjoernDreher** [comment]
@winnieli1208: I just want to check if you have any update for this issue meanwhile. Could you provide us the current status?

**Comment by winnieli1208** [comment]
@BjoernDreher no updates on our ETA but our team has committed to supporting handled errors for UWP apps. We're currently working on WPF/WinForms support and will begin the UWP work around August. I expect to have a clearer timeline around then. Thank you for your patience!

**Comment by armyofmarkness** [comment]
We would love to have this feature in App Center.

**Comment by cbttpaul** [comment]
I would also love to have this feature in App Center.

**Comment by mackayn** [comment]
We really need this support as well. It's strange that WPF and..... Winforms have been prioritised over UWP.

**Comment by dpaulino** [comment]
Lots of interest in this feature request. Does the AppCenter team have *any* plans to support this? It seems that the top feature requests all have the `keep` tag except this one... It makes me think AppCenter will never implement this.
![image](https://user-images.githubusercontent.com/7649589/62087883-320a3600-b218-11e9-8798-dd28618d47f5.png)

If AppCenter will never plan to implement this, can you just let us know now and spare us the delay?

**Comment by winnieli1208** [comment]
Hey @dpaulino - we are absolutely committed to doing this. Our engineering team is finishing up some work for supporting WPF/WinForms applications this week and then we'll start the UWP work, including handled exceptions.

I don't have a target date yet but we expect the UWP improvements to be complete around mid Sept. I know this is still a long time away and I will post here when I have any updates. I appreciate the patience!

**Comment by mackayn** [comment]
> Hey @dpaulino - we are absolutely committed to doing this. Our engineering team is finishing up some work for supporting WPF/WinForms applications this week and then we'll start the UWP work, including handled exceptions.
> 
> I don't have a target date yet but we expect the UWP improvements to be complete around mid Sept. I know this is still a long time away and I will post here when I have any updates. I appreciate the patience!

Appreciate the update.

Thanks.

**Comment by jrahma** [comment]
Hope this will be fixed soon

**Comment by jsiemensLatitudegeo** [comment]
+1

**Comment by andrewleader** [comment]
Hey @mackayn, it's mid-September, any updates?

**Comment by EmilAlipiev** [comment]
150 upvotes, most wanted feature but it is always ignored :(

**Comment by winnieli1** [comment]
Hi there! We are actively working on UWP diagnostics, including handled exceptions. The updated target date is early-mid October. Thanks for everyone's patience! I will post here as soon as this is complete.

**Comment by MartinZikmund** [comment]
We love to hear it is actively worked on, it will be awesome and we thank you for listening to feedback :blush:

**Comment by mackayn** [comment]
@winnieli1 

Thanks for the update, our UWP app i no out in the wild and we're flying a bit so this will be really helpful.

**Comment by dpaulino** [comment]
Looking forward to more updates from the appcenter team regarding this issue. I've been waiting more 8 months for this feature, so I hope to hear good news soon.

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/66908497-08afa980-efc0-11e9-8182-64aadfbf66de.png)

https://docs.microsoft.com/en-us/appcenter/general/changelog

**Comment by MartinZikmund** [comment]
Awesome!!!!

**Comment by dpaulino** [comment]
@winnieli1 any chance you'd know when will the v2.5 SDK be available to try out? According to nuget, the latest SDK is v2.4-preview

![image](https://user-images.githubusercontent.com/7649589/66944407-f6565f80-f001-11e9-94dc-2735cff13696.png)

**Comment by winnieli1** [comment]
Hi @dpaulino - we're aiming for next week!

**Comment by ChristopheLav** [comment]
Oh - the new 2.5.0 version seems to be available with the first-class exceptions support for UWP 😀

https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.5.0

I will try it later today!

Nice 👏

**Comment by MartinZikmund** [comment]
No way! You're the best, team!

**Comment by winnieli1** [comment]
We just enabled handled errors support with the 2.5.0 SDK release! You can find docs here: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp#handled-errors

I’m closing this issue but please start a support ticket or post here if you run into any issues. Thanks all!

**Comment by dpaulino** [comment]
Thank you @winnieli1!

**Comment by mackayn** [comment]
@winnieli1 

Thanks for the update.

Great job by the Appcenter team, this will be so useful 👍
