### ISSUE TITLE
Is it possible to reset the build number after a version update?

### ISSUE THREAD

**Issue by cvo-4tell** [microsoft/appcenter#1500]
<key>CFBundleShortVersionString</key>
<string>4.1.0</string>

The build number is 16. When using "Automatically increment version code", CFBundleVersion is 16. When we change CFBundleShortVersionString to 4.1.1, it is possible to reset CFBundleVersion to 1?

**Comment by alexcnichols** [comment]
Thanks for reaching out @cvo-4tell. I could see how more flexibility in that setting could help. Adding @nrajpurkar for visibility with other priorities in this space.

**Comment by nazabalm** [comment]
Hi, @alexcnichols :
Also, I think its good to have the option to set an initial bundle version. e.g: If I have already deployed an app to play store and its version code is 5, if I want to use increment version code automatically I should set the build number to 5.
