### ISSUE TITLE
Allow to pull code from AWS CodeCommit

### ISSUE THREAD

**Issue by ashivyas** [microsoft/appcenter#1501]
Currently, Appcenter only supports repositories hosted on GitLab, Azure DevOps (formerly VSTS), Bitbucket and GitHub. As my codebase is hosted on AWS CodeCommit, I am not able to pull and build on Appcenter.

**Comment by alexcnichols** [comment]
Thanks for reaching out @ashivyas. Adding @nrajpurkar for visibility and tracking this against other priorities in this space. Leaving it open to see if there is other interest as well.

**Comment by DewaldDeJager** [comment]
We would really like to see this feature. Is there any way I can help get this in?

**Comment by DavePilksEnt** [comment]
This feature would also be beneficial to our team. 👍

**Comment by ashaarm** [comment]
Appreciate if you can support for AWS CodeCommit

**Comment by alexleone** [comment]
+1 this feature

**Comment by BoneDust** [comment]
Is there still no news  whether this feature will be implemented or not? My team would really appreciate it.

**Comment by DewaldDeJager** [comment]
Any update on this? Is there any plan for implementing this integration?

**Comment by xoapit** [comment]
It should have an option for other git providers with ssh. I am disappointed because App center doesn't support CodeCommit.

**Comment by Aure77** [comment]
+1 for AWS CodeCommit support.

**Comment by andreifinski** [comment]
Please get it back to work!

**Comment by bekatd** [comment]
+1

**Comment by isinuyk** [comment]
Any updates?

**Comment by alexrodriguezfer** [comment]
+1

**Comment by lamas250** [comment]
+1
