### ISSUE TITLE
Make OS dropdown filter checkable buttons instead

### ISSUE THREAD

**Issue by alexdominte** [microsoft/appcenter#1503]
Transform OS dropdown filter to checkable buttons instead.
It's so annoying to require 2 clicks to switch between all/ios/android.
We have the tehnology (see view type list & grid view). 

If there are too many app types maybe you could fallback to dropdown; but with only 2 app types toggle or checkable buttons will be way cooler

**Comment by alexcnichols** [comment]
Hi @alexdominte -- Thanks for reaching out. I'm unsure which part of the product you're referring to here. Is it the list of apps on https://appcenter.ms/apps? Adding @blanca for visibility since we've been looking at making a few of these kinds of optimizations recently.
