### ISSUE TITLE
Add support for forced in-app updates for Winforms desktop applications

### ISSUE THREAD

**Issue by gradyal** [microsoft/appcenter#1504]
**Describe the solution you'd like**
I would like to be able to configure all Winforms desktop application updates as forced such that the user is notified, the app auto-closes, the app updates, and the app re-launches. All of this out-of-the-box would be great, but at the very least, some methods/APIs to programmatically check for updates and trigger updates would be sufficient. 

**Describe alternatives you've considered**
Right now, we are using MSIX sideloading via app installer deployed to a web location. We have custom logic running on a timer that checks for an update, notifies the user, and triggers the update. This functionality is missing for App Center (at least for Winforms desktop).

**Comment by alexcnichols** [comment]
Hi @gradyal -- Thanks for reaching out. When I attempt to distribute a new release for a Windows app in App Center, I do see the option for making it a mandatory update. Adding @winnie for visibility. To clarify, are you looking for more than what that release option can do? https://docs.microsoft.com/en-us/appcenter/distribution/uploading#mandatory-updates

![image](https://user-images.githubusercontent.com/19493383/71042804-9a7f8400-20e1-11ea-9bcd-2fed8a37ea86.png)

**Comment by gradyal** [comment]
@alexcnichols Thanks for the quick response. I logged this feature request at the recommendation of someone from your App Center support team who told me that in-app updates are not yet supported for Winforms applications. Please see the exported conversation below for reference. 

Conversation with App Center
Started on December 13, 2019 at 10:52 AM Pacific Time (US & Canada) time PST (GMT-0800)

--- December 13, 2019 ---

10:52 AM | andrewgrady: Good afternoon, I'm looking at using App Center as a distribution/deployment alternative to my current setup for my Winforms desktop application. I'm currently building/packaging (to MSIX) through Azure Pipelines and deploying to an Azure App Service. Installation happens through sideloading via the Windows 10 app installer.

10:52 AM | Operator: App Center typically replies in a day.

10:55 AM | andrewgrady: Whoops, sent that last message without an actual question. I'm evaluating the workflow with App Center and it looks like I can use the App Center Distribute task in Azure Pipelines. Is there a way to force an update for a group of users? Perhaps using Sparkle?

--- December 17, 2019 ---

04:24 AM | Anvesh from App Center: Hi There, Thanks for writing to us! If you are asking that you want your users to get an force update\auto update with out downloading manually ? then no, currently in-app update feature was not yet supported in winforms application. 
 Do you mind making your feature request on our Github repo: https://github.com/Microsoft/appcenter/issues (https://github.com/Microsoft/appcenter/issues)
You may also search there to see if it has already been submitted.  In that case, please 👍 the issue to show your interest. 

06:18 AM | andrewgrady: Yes, that's what I'm asking. Do you at least offer any methods or APIs to allow for a) checking for new updates and b) triggering an update while the app is running?

06:23 AM | Anvesh from App Center: Ans to question a: If you want to check the update, goto the install.appcenter.ms from the default browser and  you can see the all releases info, any way when you do anew release, an email will send to the customer who are in the group, saying that a new release was there to test. 
 ex:

 
 [Image "image.png"] 
Ans to b: as i mentioned it is not available the in-app updates for the winforms app,

06:24 AM | andrewgrady: Ok, thank you @Anvesh

06:33 AM | andrewgrady: FYI, I added a feature request here: https://github.com/microsoft/appcenter/issues/1504

---
Exported from App Center on December 18, 2019 at 06:48 AM Pacific Time (US & Canada) time PST (GMT-0800)

**Comment by gradyal** [comment]
@alexcnichols Also, I don't see that Mandatory update checkbox when I upload an Winforms MSIX package and create a release through App Center.

![image](https://user-images.githubusercontent.com/5721295/71104305-36140180-2181-11ea-819a-f911f24f6555.png)

**Comment by winnie** [comment]
Hi @gradyal - we don't support mandatory updates for Windows desktop apps. The feature @alexcnichols mentioned is only supported with our Distribute SDK which we don't have for Windows. We'll keep this feature open to track interest and prioritize accordingly. Thanks!

**Comment by alexcnichols** [comment]
Thanks @winnie -- Not sure if I found a bug then since the screenshot I took was for an app with appType = Windows. Maybe that checkbox is hidden if an MSIX package is uploaded but remains if creating a new release based on a build/branch.

**Comment by gradyal** [comment]
@winnie Thanks for the clarification.
