### ISSUE TITLE
Set the number of events to be displayed as an option under Dashboard in Analytics

### ISSUE THREAD

**Issue by naheed-shamim** [microsoft/appcenter#1505]
**Describe the solution you'd like**
Whenever the Number of Event Items exceeds 10, it clubs into Other

**Describe alternatives you've considered**
There should be an option to list all the events, instead of just showing 10 by default

**Comment by alexcnichols** [comment]
Hi @naheed98 -- Thanks for reaching out. I could see how that could be a pain when the list of events gets large. Adding @baileybrooks for visibility since we've been discussing small tweaks like this recently.

**Comment by yoannchaudet** [comment]
@naheed98 Thanks for the idea. In the meantime, if you are blocked, please take a look at the REST API: https://openapi.appcenter.ms. You can retrieve more information from them than what our portal displays you by default.
