### ISSUE TITLE
Mobile issue view should show the version filter

### ISSUE THREAD

**Issue by adrianthomas** [microsoft/appcenter#1506]
**Describe the solution you'd like**
I want a quick at-a-glance overview that tells me how our latest release is doing. A PM view of the crashes. The mobile view of the website hides the version filter, so it breaks that functionality.

**Describe alternatives you've considered**
Ditching AppCenter? 

**Additional context**

**Comment by alexcnichols** [comment]
Hi @adrianthomas -- Thanks for reaching out. Adding @winnie for visibility since we've been discussing making small tweaks like that to help improve experiences.

**Comment by adrianthomas** [comment]
👋👍
I also just discovered the switch to desktop version option in the hamburger, so that helps! (I was trying to do it via Safari’s option before, which wasn’t working). 

But an at-a-glance “hey your latest rollout needs to be paused” view would be really nice. 

Thanks!

**Comment by winnie** [comment]
Hey thanks for the feedback! We're exploring ways to make it easier for users to see their crashes in their latest release and we'll be sure to keep mobile in mind. I'll post here with any updates. Thanks!
