### ISSUE TITLE
Display app name / branch in distribution list

### ISSUE THREAD

**Issue by Bloodyairtimer** [microsoft/appcenter#1507]
**Describe the solution you'd like**
We have a setup of multiple branches for one app which result in multiple releases. If the testers open the list of apps to install they can only see the difference between an app based on the version number. 

We would like to have way to distinguish which branch the build came from. (Or if it's possible display the name of the app / app icon because that will differ per branch.) So the testers can easily see version x.x.x is the latest version from the master branch. Filtering on branch would also be ideal to have to quickly see all versions for a specific branch.

**Describe alternatives you've considered**
We have already different appnames / icons in our manifest/plist, but you can see them only after you install the app.

We have considered using different apps per branch, but as we have to support around 60 apps with both platforms that would make the list of applications horrible.

**Comment by pineapple216** [comment]
I second this. It would really help my team as well.

**Comment by alexcnichols** [comment]
Hi @Bloddyairtimer -- Thanks for reaching out. I could see how having other filters/columns on that release list would help differentiate. Adding @botatoes for visibility against other priorities in the space.

**Comment by ahdbilal** [comment]
Thank you all for showing interest in this request. We have started looking into this feature and will love to schedule a few minutes call to understand the use case and expectation of this request. Please click [here](https://outlook.office365.com/owa/calendar/Microsoft2278573@microsoft.onmicrosoft.com/bookings/s/SDCU034kjkmOFHZcG0iKLw2) to schedule the call. Really appreciate your help with this feature request!

Thanks
Bilal
PM appcenter distribute
