### ISSUE TITLE
Unauthorized error with Code Push

### ISSUE THREAD

**Issue by Developers-Employwise** [microsoft/appcenter#1514]
I am trying to codepush by command and getting an exception without declaration i.e. Command 'codepush release-react -a Employwise/Employwise-iOS -d Production' failed with exception "4a6f8c9e-4693-4876-82d9-b3e78311e066". When I tried to debug this command then got the api response is unauthorized. Although , I have done codepush many times. But first time facing this type of issue. Please have a look at response - Body: {"message":"e4e9f676-7f80-454c-9456-98d65b4da7e2","statusCode":401,"code":"Unauthorized"} Command Failure at Error: e4e9f676-7f80-454c-9456-98d65b4da7e2.

**Comment by Developers-Employwise** [comment]
Please find below the attached screenshot 

![image](https://user-images.githubusercontent.com/46275741/71150907-a5a8f000-2258-11ea-8b4d-3e1b4d2a5085.png)

**Comment by alexcnichols** [comment]
Hi @Developers-Employwise -- Thanks for reaching out. That's strange that the codepush command wouldn't be working anymore even though you've run it several times. This might mean there is something particular to your account/organization that is contributing to this, which would benefit from some personalized troubleshooting with a member of our support team. Go ahead and start a chat using the blue bubble in the lower-right section of https://appcenter.ms. Closing this issue for now.
