### ISSUE TITLE
Push notifications: Provide feedback details per device/user 

### ISSUE THREAD

**Issue by mcghiem** [microsoft/appcenter#1517]
**Use Case:**
Trying to troubleshoot notifications not being received by an android device.

**Tools we're aware of that are available to use to help troubleshoot:**
App Center web front end (https://appcenter.ms/orgs/<org_name>/apps/<app_name>/push/notifications)
App Center swagger api (https://openapi.appcenter.ms/)

**Steps taken:**
1. Received a call from an end user that an expected notification wasn't received.
2. Checked the app center web front end for the notification. It shows the notification targeting 3 users but being sent to 1/1.
3. Got more notification details using the app center swagger api (/v0.1/apps/{owner_name}/{app_name}/push/notifications/{notification_id})
4. Saw the details of the users that the notification was destined for

**What's missing?**
1. The app center web front end should show the users the notification was destined for so we don't have to go to the swagger api.
2. We can't tell which of the targeted users were sent the notification.
3. We can't tell why 2 of the users targeted didn't receive notifications.
4. We can't tell which devices/users are currently registered to receive notifications.

**Comment by jwargo** [comment]
@mcghiem Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

Azure Notification Hubs supports delivering detailed push telemetry with the standard billing plan.
