### ISSUE TITLE
App Center-Issue-JAR will be empty - no content was marked for inclusion! app center-- Priority issue

### ISSUE THREAD

**Issue by Pooja0907** [microsoft/appcenter#1523]
When I am running my automation code using simple class without any framework(Single independent class contains everything) it is working fine.
But when I am using Page object model and running the same code on local device- no error
using maven- no error
So I executed the same code on app center real device
uploaded package using the given command(instruction of app center website) `-mvn -DskipTests -P prepare-for-upload package`
and then I executed my tests

`appcenter test run appium --app "myBeepr/myBeepr" --devices "app/" --app-path pathToFile.ipa --test-series "trial-test-series" --locale "en_US" --build-dir target/upload`

I got the console message that build is successful and after doing 15 mins of validation executing the code like this (Current test status: Running on 1 device (0 / 1 completed, 0 pending))
I got the error

`Reason: [INFO] Scanning for projects...
Build --
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ run-test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ run-test ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ run-test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ run-test ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ run-test ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[ERROR] There are test failures.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
There was an error in the forked process
com/appCenter/qa/base/BaseClass_appCenter
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
com/appCenter/qa/base/BaseClass_appCenter
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:665)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
     
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ run-test ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: target/run-test-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:2.20:integration-test (default) @ run-test ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO]
[INFO] --- maven-failsafe-plugin:2.20:verify (default) @ run-test ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.757 s
[INFO] Finished at: 2019-12-23T06:16:27+01:00
[INFO] Final Memory: 17M/210M
[INFO] ------------------------------------------------------------------------

Error: Cannot run tests. Returning exit code 2.
`

**My POM file**

`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>AppCenterTestPRoject</groupId>
  <artifactId>AppCenter</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>
  
  <repositories>
        <repository>
            <id>jcenter</id>
            <url>https://jcenter.bintray.com/</url>
        </repository>
 </repositories>
  <name>AppCenter</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      <serenity.version>1.9.36</serenity.version>   
  </properties>
  

  <dependencies>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>6.1.0</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.13.0</version>
        </dependency>
        
<dependency>
    <groupId>log4j</groupId>
    <artifactId>log4j</artifactId>
    <version>1.2.17</version>
</dependency>

        <dependency>
            <groupId>com.microsoft.appcenter</groupId>
            <artifactId>appium-test-extension</artifactId>
            <version>1.5</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>repl</id>
            <dependencies>
                <dependency>
                    <groupId>com.javarepl</groupId>
                    <artifactId>javarepl</artifactId>
                    <version>428</version>
                </dependency>
            </dependencies>
            <build>
                <plugins>
               
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <configuration>
                            <executable>java</executable>
                            <classpathScope>test</classpathScope>
                            <arguments>
                                <argument>-Djansi.passthrough=true</argument>
                                <argument>-classpath</argument>
                                <classpath/>
                                <argument>javarepl.Main</argument>
                            </arguments>
                        </configuration>
                        <executions>
                            <execution>
                                <id>runRepl</id>
                                <phase>process-test-classes</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>prepare-for-upload</id>
            <build>
                <plugins>
                
        <plugin> 
            <artifactId>maven-jar-plugin</artifactId>
            <configuration>
                <classesDirectory>dummy</classesDirectory>
            </configuration>
        </plugin>
    
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>2.10</version>
                        <executions>
                            <execution>
                                <id>copy-dependencies</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>copy-dependencies</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/upload/dependency-jars/</outputDirectory>
                                    <useRepositoryLayout>true</useRepositoryLayout>
                                    <copyPom>true</copyPom>
                                    <addParentPoms>true</addParentPoms>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
        
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M3</version>
				<configuration>
					<excludes>
					
				<exclude>Test_ONBoarding_AndroidByID.java</exclude>
				<exclude>Test_OnBoarding_iOS.java</exclude>
			</excludes>
				</configuration>
			</plugin>
                    <plugin>
                    
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-help-plugin</artifactId>
                        <version>2.2</version>
                        <executions>
                            <execution>
                                <id>generate-pom</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>effective-pom</goal>
                                </goals>
                                <configuration>
                                    <output>${project.build.directory}/upload/pom.xml</output>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>copy-testclasses</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>testResources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/upload/test-classes</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>
                                                ${project.build.testOutputDirectory}
                                            </directory>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>`

**Comment by Oddj0b** [comment]
I would recommend reaching out to support through the blue chat icon in the lower right side of the App Center portal. We primarily are looking for feature requests at this repo.
