### ISSUE TITLE
Add documentation for iPad for "Request Mobile Website"

### ISSUE THREAD

**Issue by nuthatcher** [microsoft/appcenter#1529]
**Describe the solution you'd like**
When the banner pops up for iPad saying, 'If you are using iOS, please enable "Request Mobile Website" for this site', it would be nice to link "Request Mobile Website" to App Center documentation or iOS documentation on how to do so. It isn't immediately obvious. You can either click on the "AA" in the toolbar to "Request Mobile Website", or go to Settings > Safari > Request Mobile Website.

**Describe alternatives you've considered**
I did a search in App Center documentation and found nothing.

**Additional context**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/56733689/71483339-5ffaa300-27d5-11ea-8c99-86bd0fc66a14.png)

**Comment by derpixeldan** [comment]
Thank you for the request, that's definitely good feedback.

**Comment by David-A-RogersHS2** [comment]
I ran into the same issue and would have been lost if not for this post.
