### ISSUE TITLE
User feedback when distribution to app store fails

### ISSUE THREAD

**Issue by struct78** [microsoft/appcenter#153]
**Describe the solution you'd like**
More descriptive errors/statues when submission to app store fails.

**Additional context**
Recently our builds weren't showing up in App Store Connect. When clicking "Distribute" -> "Store", a spinner would appear for around a minute or two, and then silently fail. We had to do a submission from Xcode to find out there was an issue with one of the app icons.

![](https://i.stack.imgur.com/bEloD.png)

After fixing this, the submission to the app store through App Center succeeded.

**Comment by Oddj0b** [comment]
A fix has been implemented, thank you for reporting.
