### ISSUE TITLE
Add download status bar to the update dialog box

### ISSUE THREAD

**Issue by xSky93** [microsoft/appcenter#1530]
**Describe the solution you'd like**
When you get accept the prompt to download an update from an Android app in AppCenter there is no indicator that the download is progressing in the background. The only notice that the update occurred is when it succeeds and then prompts the user to install. 

It would be beneficial to have a notification or prompt of some kind that contains the download status/progression similarly to what you seen when downloading an update from the Playstore.

**Describe alternatives you've considered**
I've been told by your support that I could achieve this for any apps that I manage by [creating a customized update dialog box](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fappcenter%2Fsdk%2Fdistribute%2Fandroid%23customize-or-localize-the-in-app-update-dialog&data=02%7C01%7Ccarlos.aldridge%40microsoft.com%7Cda5de6f024c04870146c08d7877bb059%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637126837625073020&sdata=MkI1OUdGT9F7WYId9%2FCAbC15Fi7RTSphb%2Fz49AiJAYs%3D&reserved=0) and replacing the default box from Appcenter. 

This seems more of a bandage fix however, and should really be supported by the SDK itself.

**Comment by ahdbilal** [comment]
Thanks for the request. This has been added to our feature backlog
