### ISSUE TITLE
I want to see every event of particular user during his session 

### ISSUE THREAD

**Issue by Rcoder0907** [microsoft/appcenter#1538]
**Describe the solution you'd like**
Here I am able to see every event count but not able to see which actions are performed by which user during his session period.
I want to filter event by user wise, so intension is which action are performed in the app by particular user and particular session.
 
**Describe alternatives you've considered**

**Comment by yoannchaudet** [comment]
@Rcoder0907 Take a look at https://docs.microsoft.com/en-us/appcenter/analytics/export#azure-application-insights. This enables the exact scenario you are looking for.

**Comment by derpixeldan** [comment]
@Rcoder0907 does that answer your question?
