### ISSUE TITLE
AppCenter should provide a way to control the crash reason bucket naming

### ISSUE THREAD

**Issue by saurabh-sagrawal** [microsoft/appcenter#1539]
For native stack traces many a times the top of the stack is coming from system libs like libc.so or some common exception logic which is not meaningful if the crash reason name is generated from those stack. This also has a side effect with different crash stack traces merging into same crash reason.
To workaround this hockey engineering team had skipped few common frames for us.
We need a feature to have the same level of capability on the AppCenter side as well.

For example see this crash reason:
https://rink.hockeyapp.net/manage/apps/117923/app_versions/5517/crash_reasons/295743035
Top of the crash call stack is "libplat.so!printLogAndTrap(char const*)" but still the crash reason is formed from the frame 2 of the crash call stack "Mso::Details::FunctionObjectWrapper<(lambda at d:\dbs\el\oct\dev\interprocess\dragdrop\android\..\ShimImplDrop_android.cpp:449:89), void>::Invoke"

Similar example on AppCenter:
https://appcenter.ms/users/k2crep-wmp8/apps/Word/crashes/errors/345824731u/reports/2518258086259999999-c4bd3e58-f058-4e5e-883e-03408c130dc7/raw

**Comment by saurabhagr12** [comment]
Please let us know what is the ETA to fill this gap between Hockey and AppCenter.

**Comment by winnie** [comment]
Hi @saurabhagr12 unfortunately, no ETA at this moment. We don't have plans this quarter to address this but we'll monitor this feature request and post here with updates.
