### ISSUE TITLE
Support iOS/Android Beta Device Configurations for Automated Tests

### ISSUE THREAD

**Issue by chandlermania** [microsoft/appcenter#1542]
Would like to see device support within Test Cloud to allow for test execution on major BETA OS releases.  For example, when iOS/iPadOS 14 Beta starts rolling out mid-2020, being able to run automated tests against the public beta releases on real devices ahead of GA release would be valuable. 

Currently, this type of testing still has a manual component in that testers need to configure and run automated tests against a local simulator/device.

Being able to extend this annual/semi-annual test scenario to the existing automated process within App Center would be a more consistent solution.

**Comment by Oddj0b** [comment]
We're already doing that when it's possible. Multiple circumstances will have to align for us to expose beta OS's
1. The beta OS needs to be stable or else it'll break often and only delay the final release
2. The OS would have minor changes, or else we can't support it
