### ISSUE TITLE
Deleting old symbol files from appcenter

### ISSUE THREAD

**Issue by rolandsmeenk** [microsoft/appcenter#1544]
**Describe the solution you'd like**
I want to be able to remove outdated symbol files that I uploaded while testing the appcenter diagnostics. I would like to select the symbols file I previously uploaded and be able to delete it.

**Describe alternatives you've considered**
Deleting the complete appcenter app and then recreating it, but that is not possible either.

**Additional context**
iOS app built with Unity 2019.1.8f1, Crashes SDK 2.6.0
Note that I also accidentally uploaded the same symbols twice. Could be an impatient user error or the lack of proper feedback. ;)

**Comment by winnie** [comment]
@rolandsmeenk thanks for filing an issue! We've heard similar sentiment regarding lack of feedback in the upload symbols flow. We don't have immediate plans to address this but it's definitely on our radar. 

For now, you can delete symbol files using our APIs:

1) Retrieve the `symbol_id`: https://openapi.appcenter.ms/#/crash/symbols_list
2) Delete the relevant symbol: https://openapi.appcenter.ms/#/crash/symbolUploads_delete

Hope that helps! If you'd like this functionality in the UI, we can re-open this issue. Thanks!

**Comment by andrewlundydev** [comment]
Hello, this is not working for me. I am using MacOS 10.15.3 and am providing my API key when running the command. 

I have used the following command:
`curl -X GET "https://api.appcenter.ms/v0.1/apps/LundyOrg/app-center-test-ios/symbols" -H "accept: application/json" -H "X-API-Token: 1020421a-f679-4c27-af38-df2c76228a77"`

This is indeed my API token, as I checked within the CLI. When I run this, it's producing the following:
`{"message":"51c51365-29ae-4b68-b055-31ac973739e3","statusCode":401,"code":"Unauthorized"}%`

Any ideas on why I'm considered unauthorized?

**Comment by unpaleness** [comment]
Hi!
I have an issue with deleting symbols for Windows builds via this flow.
- I gather `symbols_upload_id` from response on `/v0.1/apps/{owner_name}/{app_name}/symbols/{symbol_id}`
- Then I delete symbol upload via `/v0.1/apps/{owner_name}/{app_name}/symbol_uploads/{symbol_upload_id}` request
- When I call `/v0.1/apps/{owner_name}/{app_name}/symbols/{symbol_id}` it says that this symbol is still connected with the same `symbols_upload_id`
As a result I fail to replace corrupted symbols that have been accidentally uploaded for many of our builds and we don't see correct stack traces to analyze crashes.
Do I miss something in this process? I would be grateful for any assistance.
Thank you!
