### ISSUE TITLE
Bring back HockeyApp

### ISSUE THREAD

**Issue by schriftgestalt** [microsoft/appcenter#1548]
There are so many things that are not working in AppCenter that are hindering my work. I list them again if needed.

**Comment by derpixeldan** [comment]
@schriftgestalt listing them would definitely be helpful for us. Thank you.

**Comment by schriftgestalt** [comment]
- AppCenter doesn’t provide a UI to collect user comments and no UI in the backend to properly display it when I build my own. I can’t see that report have comments. But those are the most valuable report. I have to click each report several times to see my custom attachment. (#1418, #850)

- I can’t filter by build numbers (had a long "conversation" with the chatbot that was not helpful). I was told I need to add the Analytics framework to my app but I still didn’t got it to work. And I don’t know why I need to spy on my uses so that the backend can read and collect the build numbers from the crash report. They are there already????

- I have to constantly re-upload symbols if new crashes come in. I HockeyApp I could upload symbols before any crashes come in. And I could just drag the .zip onto the page. And I don’t get a progress bar (60 MB take a minute at my place). 

- The overall UI looks more pretty on first sight but I was much faster at finding the problems before. I have to click at least twice as much as before.

**Comment by derpixeldan** [comment]
@schriftgestalt thank you for the valuable feedback. We will consider it to further improve App Center's crash reporting.

**Comment by dipree** [comment]
Closing as we won't bring back HockeyApp 😢
