### ISSUE TITLE
Please add Samsung galaxy J7 to your list of supported devices

### ISSUE THREAD

**Issue by manu4rhyme** [microsoft/appcenter#155]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Oddj0b** [comment]
Can you provide information about which OS these should be running?

**Comment by Priskorn** [comment]
Ordered today

**Comment by manu4rhyme** [comment]
@Oddj0b Would it be possible to have multiple OS'es for each device in the future? We're constantly facing scenarios where our customer devices usually have different OS versions, and this would further help with debugging and fixing a lot of test bugs.

@Priskorn Thanks! When can we expect to start using the same on AppCenter?

**Comment by Priskorn** [comment]
Hello,

I was just told that the order is delayed for a couple of days. I will let you know when it arrives.  

It looks like the Galaxy J7 will get Android Pie within the next couple of months. Until then we can have them running Android 8.0.0?

We also have this snapshot available now:

Samsung Galaxy J6 | 8.0.0
-- | --

**Comment by Priskorn** [comment]
Samsung Galaxy J7 arrived today
Model Name: SM-J730F

![image](https://user-images.githubusercontent.com/5525272/58101541-28dd6700-7be0-11e9-844f-6bd046d05ea7.png)

Created the 2 variations currently available
See: https://www.sammobile.com/firmwares/galaxy-j7/SM-J730F/NEE/

Samsung Galaxy J7 (2017) | 7.0
-- | --

Samsung Galaxy J7 (2017) | 8.1.0
-- | --


@manu4rhyme @Oddj0b

**Comment by manu4rhyme** [comment]
Thank you so much!
