### ISSUE TITLE
Fully working Auth User Flow

### ISSUE THREAD

**Issue by SOliasS** [microsoft/appcenter#1550]
Hey @amchew i was wondering if there is a UserFlow which is fully working with auth?
When trying the default Userflows like Register and Login( default/v2) the login and the register is working, but when pressing the back Button when register or when pressing password forgotten the flow crashes....
Now i wondering if it is possible to add a working Userflow to Auth so the basic functionality is working, and the user won't encounter a crashing bug.
Are custom User flows working at the moment? If so an fully working example would be awesome.
(Also at the moment it's not possible to add Auth or Data to new apps in EUW )

**Comment by amchew** [comment]
Hi @SOliasS, happy new year! Good to hear from you again. We currently only support the sign-in and sign-up user flow or custom policy. The user flow which you're referring to is the password reset one which we currently don't support, unfortunately. We don’t have an ETA on this feature yet. If it’s a blocking feature for your apps, I’d advise you to use Azure AD B2C and the MSAL SDK directly.

Custom policies are working, but we only support the sign-in and sign-up flow in the custom policy.

**Comment by SOliasS** [comment]
@amchew does data work when using the MSAL SDK instead of Auth?

**Comment by SOliasS** [comment]
@amchew As it's not possible to switch to msal without breaking data #1561.
Is it possible to mix Auth with msal? 
So basically use the working part of Auth and use Msal for the missing part? 
Can i get the login Token from auth an pass to Msal?

The missing password reset is really killing the whole solution here...

**Comment by SOliasS** [comment]
@amchew happy news for a change ;)
i found a workaround for this issue.
Like i indicated in the last comment i was able to combine Auth with the MSAL SDK.
The Auth returns the errors in the LoginRegister Flow back to the App, where i can catch them and then depending on which error message was thrown i can use msal to open the change password flow, where the user can now change their password...
The problem atm is only that the user has to login again after reseting his password.
With this approach i'm now able to use msal, for all the missing features, while continue using auth for all already integrated features. 

P.s. ad b2c /MSAL docu is really horrible/confusing/complex, after crawling throw this mess i really appreciate appcenter.auth approach to make it plug an play like it should have been from the beginning....

**Comment by askpatrickw** [comment]
> i found a workaround for this issue.
> Like i indicated in the last comment i was able to combine Auth with the MSAL SDK.

I don't find this work around to be acceptable. The point of AppCenter Auth is not have to deal with the underlying auth process and libraries. This is a big gap for my team.

**Comment by SOliasS** [comment]
#1621 Auth is dead
