### ISSUE TITLE
Support Xamarin.Android 10.1.1.0 in Cloud Build Agents

### ISSUE THREAD

**Issue by thisisthekap** [microsoft/appcenter#1553]
Xamarin.Android 10.1.1.0 should be supported using the AppCenter Cloud Build Machines.

**Comment by nrajpurkar** [comment]
@thisisthekap thanks for the feature request! We'll be working to add support for the latest toolsets released with VS for Mac 8.4 soon.

**Comment by thisisthekap** [comment]
@nrajpurkar Great! Will this feature request be updated once the toolset is released?

**Comment by nrajpurkar** [comment]
@thisisthekap yes it will

**Comment by beeradmoore** [comment]
Came here to post the exact same issue. I have as breaking issue with using r8 without Multidex which needs Xamarin.Android 10.1 to fix. I'll try upload/distribute apk manually until this is resolved.

**Comment by thisisthekap** [comment]
As Xamarin.Android 10.1.3.0 is available according to https://docs.microsoft.com/en-us/appcenter/build/software#xamarinandroid.

@nilofer Can you confirm, that the production cloud build agents are using Xamarin.Android 10.1.3.0?

**Comment by nilofer** [comment]
@thisisthekap correct, and Xamarin Android 10.1.3.7 is coming next. Closing this out, but feel free to create a new issue for different toolset.
