### ISSUE TITLE
Want a App center Test result URL made to public

### ISSUE THREAD

**Issue by RaveAutomation** [microsoft/appcenter#1555]
We want our App center test execution report should be available to public or there should be some facility that we can send report via email as an attachment. The report should contains all mobile screen screenshots available.

This will be helpful to express things in front of business users.

Could you please make this change.

Thanks,
Mahendra Bharambe

**Comment by Oddj0b** [comment]
Thank you for your suggestion, would it help if we exposed the endpoints to generate a test result and your CI system could make a pdf?
