### ISSUE TITLE
Migrate crash reports to Custom platforms

### ISSUE THREAD

**Issue by gekas** [microsoft/appcenter#1557]
We started to use Upload Custom Crash reports approach before "Custom" platform type were added. 
Now we need to migrate all issue reports from Android application to newly created Custom application.
We don't use any other features of AppCenter except Custom Crash Reports. Could you add or reference to the ability to migrate reports from one application to another (ex. Android -> Custom)?
Or provide an ability to change type of OS to custom of existing App

**Comment by derpixeldan** [comment]
@gekas please reach out to us via support (the blue circle button in the bottom right corner of App Center) and request to change the OS of your apps. There's no way for us to move data between apps.
