### ISSUE TITLE
Combining analytics from multiple apps

### ISSUE THREAD

**Issue by gunnartorfis** [microsoft/appcenter#156]
**Describe the solution you'd like**
I'm using React Native for a mobile app and therefore have both an iOS and an Android app on App Center. Currently, we have to look at the analytics on App Center separately for those apps but it would be great to be able to view those as a whole. 

So being able to define a project that apps belong to and view analytics on a per-project basis 

**Describe alternatives you've considered**
The only alternative I've considered is to calculate those statistics manually on demand.

**Comment by winnieli1208** [comment]
Thanks for the feature request! This is something we've heard quite a few times and would like to support at some point. Unfortunately, this isn't on our current roadmap but we'll monitor this thread for community support and post here with updates. Thanks!

**Comment by sasivishnu** [comment]
Hi, I too recently encountered same scenarios. Problem is until you release the app and analytics/crash/error logs pile-up, you won't feel the pain to check at both places. But invariably this happens in few months after release depending on app size. It will be nice to have.
