### ISSUE TITLE
Support Running & Displaying of Tests from other Test Frameworks

### ISSUE THREAD

**Issue by lemusthelroy** [microsoft/appcenter#1560]
I think it would be great if App Center supported other test frameworks that are not currently listed, and this could be done in a post-distribution script. This feature request focuses on this specific scenario with the following desired outcomes:

- APK is being built using an external service (in my case Azure DevOps) and distributed to AppCenter ✔️
- Script is run (in my case using Detox - app is written in React Native) running integration tests ❓
- Test results are displayed in the AppCenter UI ❌

Currently it is hard to understand with build scripts how these could link with the current AppCenter tools or whether these scripts are completely detached from any AppCenter process. Also, it isn't clear if these build scripts would be triggered by distributing your APK to AppCenter or are they only triggered when you build via AppCenter.

Hope the above makes sense and let me know if I could be any clearer.

**Comment by Oddj0b** [comment]
Thank you for your contributions.

**Comment by King-of-Spades** [comment]
The App Center **Test beacon** allows you to execute tests on our device cloud when you provide an APK and a UI test suite. The generation of that APK & test suite doesn't have to take place in App Center itself; but the Detox framework specifically isn't currently supported. If that's the core of what you're looking for, it might be more in line with this feature request: https://github.com/microsoft/appcenter/issues/262. 

By contrast, the App Center **Build beacon** does allow some acceptance tests or simulator tests during the build process; but might not have built-in support. For example, in that same issue, users have shared many examples of build scripts designed to execute Detox tests against the iOS simulator post-build. 

Generally speaking they can work, but it's not a directly supported scenario. So we aren't able to provide bugfixes or explicit guidance relating to it, unless the underlying cause of a failure is something else that _is_ supported.

**Comment by gunnartorfis** [comment]
Any news about Detox being supported?
