### ISSUE TITLE
Use .Data without .Auth

### ISSUE THREAD

**Issue by SOliasS** [microsoft/appcenter#1561]
Ii was wondering how i could use Appcenter.Data without Auth.
In the docu it's says Auth is optional for Data, but how do i tell Data which user is logged in?
I want to use the MSAL SDK  to log the user in as Auth is unfortunately lacking some crucial features at the moment.

Atm i also unable to test as i can not add any new connections to Auth or Data in Appcenter...

**Comment by yoannchaudet** [comment]
You need Auth only to access a user partition in Data. If you only need to access the read only partition you can integrate Data without Auth but then the use cases are very limited (e.g. global app read only configuration).

We have no plans at the moment to change that.

**Comment by SOliasS** [comment]
#1621 Data/Auth is dead
