### ISSUE TITLE
Feature: Enable Appcenter In-app updates function without launching web browser

### ISSUE THREAD

**Issue by rtippisetty** [microsoft/appcenter#1564]
Its been annoying to see browser pop-up unexpectedly during app launch to enable in-app updates.
This is a hindrance to testing the app. 
I request to take this as a feature request to enable "in-app updates" functionality in the background without launching a browser.

**Comment by derpixeldan** [comment]
Thank you for noting this, we're working on improving the in-app update experience using the App Center SDK.

**Comment by DmitriyKirakosyan** [comment]
Hi @rtippisetty,

I'm sorry for such a late response and thank you so much for getting in touch with us!

Could you please provide more info about the SDK version you're using, and also iOS version?

If you're distributing not in a public group, then the authorization is required and in that case the browser will pop up for you to authorize in the AppCenter.

If the issue still persists, please let me know.
Thanks.

**Comment by DmitriyKirakosyan** [comment]
You can find more info in the following docs:
- https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#use-private-distribution-group
- https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#use-private-distribution-group
- https://docs.microsoft.com/en-us/appcenter/sdk/distribute/unity#use-private-distribution-group
- https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#use-private-distribution-group
