### ISSUE TITLE
Get rid of inconsistencies between Install and Downloads numbers

### ISSUE THREAD

**Issue by JanithaR** [microsoft/appcenter#1565]
Right now the Installs and the Downloads count doesn't match.
It leads to confusion how many actual users have received the update and installed.

If this isn't an inconsistency then there should be an explanation what the numbers actually mean.

**Additional context**
![Incorrect stats](https://app-center.intercom-mail.com/i/o/174896239/ff3cb2c143da09917498479f/Screen+Shot+2020-01-07+at+12.08.34+PM.png)

**Comment by patniko** [comment]
Downloads come from clicks while installs come from actual InstallID's generated from the app being installed to a phone. A tester can download a release once from the portal for Android, but sideload(install) it 100 times for example.

**Comment by JanithaR** [comment]
I don't think that's what's happening here. My stakeholders have no idea of sideloading anything or I didn't understand what you said.

Anyways, I created this feature request after AppCenter support recommended me to do so. Here's the last message I got,

> I got word back from our DEV team. They reviewed the code here and it completely possible the API in inconsistent way and we don't have significance checks in place to safeguard against mismatched value here. They will investigate changes to this in the future. If you like you could fill out a feature request

And here's what I asked originally.

> Hi, in a Codepush release, the installs count is higher than the Downloads count. Why is that? Can someone help me a understand how can that happen?

**Comment by patniko** [comment]
Ah, sorry I thought that might've been out of the CodePush service instead, but didn't confirm. In that context installs should be the active number of devices on that releases (it can go up and down), but downloads should only increase based on updates being pulled. I usually use the CLI for metrics because the portal is a bit unclear in its current representation.

**Comment by JanithaR** [comment]
Nope.
