### ISSUE TITLE
Xamarin iOS fails to link native code

### ISSUE THREAD

**Issue by ardb-uk** [microsoft/appcenter#1568]
When adding App Centre Analytics to my Xamarin app, I now get errors when linking native code:
MTOUCH : error MT5210: Native linking failed, undefined symbol:
It looks to me like a recent update somewhere has broken this, as I can successfully build older versions. I'm trying to track this down, but have started this as a work in progress.

**Comment by derpixeldan** [comment]
@ardb-uk please reach out to us via support (the blue circle button in the bottom right corner of App Center) so we can better investigate the problem.
