### ISSUE TITLE
UWP Failed to build when solution contains a .net standard 2.0 class library that reference UWP class library 

### ISSUE THREAD

**Issue by TheFo2sh** [microsoft/appcenter#1570]
Building solution that contains a .net standard class library project that references a uwp class library project succeed using visual studio but fails when building with the app center with error

> ##[error]The nuget command failed with exit code(1) and error(NU1201: Project ClassLibrary1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project ClassLibrary1 supports: uap10.0.17763 (UAP,Version=v10.0.17763)

## steps to reproduce 
1- clone https://github.com/TheFo2sh/AppCenterBug
2- Build local using visual studio 
3- application guild successfully
4- build the same solution using app center
5- you will get the previously mentioned error.

**Comment by charlesroddie** [comment]
How can it be correct to reference a uwp class library from a netstandard one?

**Comment by TheFo2sh** [comment]
as it works if you build using vs 2019 , I expect that it should works too on appcenter

**Comment by King-of-Spades** [comment]
This may be related to an item we're investigating internally, but I'm not sure. 

Internal tracking ADO - 75672

**Comment by King-of-Spades** [comment]
I have some updated findings on this issue. VS 2017 is currently the only version available in App Center for UWP builds, other details of the configuration are inherited from here: https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md

I've authored an update to docs to make this clearer. 

> as it works if you build using vs 2019 , I expect that it should works too on appcenter

@TheFo2sh If VS 2019 is a hard requirement for the UWP app, then this is currently a limitation in that scenario. (But I don't know if it's a hard requirement.)

**Comment by King-of-Spades** [comment]
@TheFo2sh following up on my last comment, it looks like a relevant feature request for VS 2019 support is here: https://github.com/microsoft/appcenter/issues/503 

I recommend giving it a thumbs up to show your support.

**Comment by King-of-Spades** [comment]
VS 2019 support was added per #503.
