### ISSUE TITLE
Segregate Crashes and Errors by environment or custom category.

### ISSUE THREAD

**Issue by rlasker3** [microsoft/appcenter#1572]
**Describe the solution you'd like**
When I start up Crashes I would like to have an additional option to supply a custom category code.

AppCenter.Start(
$"android={AppSettings.APPCENTER_KEY_ANDROID};ios={AppSettings.APPCENTER_KEY_IOS}",
"Production",
typeof(Analytics), typeof(Crashes));

This would allow me to segment our crashes for when exceptions are caught in the QA Testing phase or if in production code or any segment I would wish (feature branch etc). 

**Describe alternatives you've considered**
Currently I do this by using a different application key based on the type of build but this method artificially increases the number of "Apps" I have when really the only difference is that I want to record testing bugs vs production bugs.

**Comment by winnie** [comment]
Thanks for the feedback! This is definitely on our radar however we don't have any immediate plans to address it. We'll monitor this thread for community support and update here if anything changes. Thanks!

**Comment by yoannchaudet** [comment]
@rlasker3 In the meantime, since we do version segmentation and support [semantic versioning](https://semver.org/) why not use the pre-release portion to fill in the information you need?

Your versions would look lile: `1.4.0-qa`, `1.4.5-some-branch-name`, etc.
