### ISSUE TITLE
Example available for AppCenter.Distribute with WPF?

### ISSUE THREAD

**Issue by TheElectricCo** [microsoft/appcenter#1574]
Hi!

First of all I want to thank you for this great tool. The Crashes and Analytics module have already spared me lots of frustration and tedious debugging time :-)

Now I would like to take my WPF app a bit further. With Azure pipelines, I have set up a chain where a msi is created and deployed to AppCenter. Users in the distribution list get an email that a new version is available, which is great. However: Can the WPF app auto-detect updates via the AppCenter.Distribute package? I can't really seem to find a good example/walktrough for this on the documents page or anywhere else...

if I try this: 
`Distribute.SetEnabledAsync(true)` 
the Enabled property stays false..

Can someone guide me in the good direction?
Thanks for the help!

**Comment by TheElectricCo** [comment]
Hi @ilyashumihin 

Thanks for the update! 
Any idea when this will be supported?

**Comment by OzBob** [comment]
While I wait for this to be put on the road map...

I will:
copy my msix and appinstaller files to a web site and allow users to install the app from there.

[https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/getting-started/0-overview.md](Auto-Update using wither Squirrel.Windows (https://github.com/Squirrel/Squirrel.Windows))
or
[https://winsparkle.org/](Win.Sparkle (https://winsparkle.org/))

**Comment by OzBob** [comment]
@TheElectricCo Does this example from the [appcenter-sdk-dotenet project ](https://github.com/microsoft/appcenter-sdk-dotnet/tree/develop/Apps)work as the requested example?

**Comment by TheElectricCo** [comment]
Hi @OzBob ,

not sure where to look. In the WPF demos I don't immediately see an implementation of the in-app updates (or I am looking over it, it is still morning). Can you point me where to look in the example?

Thanks,
Lens

**Comment by OzBob** [comment]
Hi Lens/ @TheElectricCo 
my bad, the example doesn't have auto-update.
I am investigating win.sparkle and windows.squirrel  as packages to make my own.
I am searching for an example using the AppCenter 'sparkle' URL or the CI build files pushed to my own webserver.
