### ISSUE TITLE
Support sending JS error to crash report service

### ISSUE THREAD

**Issue by caisd1998** [microsoft/appcenter#1575]
**Is your feature request related to a problem? Please describe.**
If there's a fatal js error, react native app will crash.
So normally we reset the global handler to avoid crash
`ErrorUtils.setGlobalHandler(async (error, isFatal) => {
        // do something with the error
    });`

**Describe the solution you'd like**
In the code above, the "do something with the error" part, we would like to send the error (including isFatal information) to appcenter's crash report service, the service should show the error and use the source map to tell us the exact JS lines, so we can know user is having problem and the root cause.

**Describe alternatives you've considered**
There are no alternatives inside app center itself, except using another RN friendly crash/bug reporting service.

**Additional context**
None.

**Comment by winnie** [comment]
Referencing duplicate request #285 and #358 for tracking.

**Comment by zoontek** [comment]
@ahdbilal Any ETA on this? The roadmap is really opaque for users.
