### ISSUE TITLE
Disable Push notifications at runtime

### ISSUE THREAD

**Issue by MirageMK** [microsoft/appcenter#1576]
As it is written in the documentation
Calling `Push.SetEnabledAsync(false);` will NOT stop your application from receiving push notifications.

Can we get a method that will do that?
This will be helpful in scenarios when the user disables the notifications inside the app, or if he logs out of the app.

**Comment by jwargo** [comment]
@MirageMK you're right, disabling it that way only keeps the service from registering the device at app launch, any previous registration remains.

**Comment by jwargo** [comment]
@MirageMK Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
