### ISSUE TITLE
Independent WatchOS application support?

### ISSUE THREAD

**Issue by ghost** [microsoft/appcenter#1577]
Are there any plans to include support for independent WatchOS applications in the future? I'm mainly thinking about support for analytics and crash reports. 

Or is there a way at the moment to include the SDK in an independent WatchOS application? Cocoapods installation keeps telling me "The platform of the target `XXXXXX` (watchOS 6.1) is not compatible with `AppCenter (2.5.3)`, which does not support `watchOS`.". 

I've also tried integrating the SDK into my project by copying the binaries into the project by following https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#33-integration-by-copying-the-binaries-into-your-project but I can't seem to get this to work either.

**Comment by kattzor** [comment]
Thanks for taking this into consideration and placing it in the feature backlog. As independent WatchOS applications slowly become more common I'm sure I'm not the only one that could benefit a lot from having proper analytics and crash reports through Appcenter.

**Comment by johannes-keinestam** [comment]
I would also love to have support for this. Hope this can be added soon! 👍

**Comment by jrothenbacher** [comment]
@ahdbilal Are there any updates? We would also love to see this. Thanks!

**Comment by docterd** [comment]
Bump :)

**Comment by obrhoff** [comment]
Please don't close :)

**Comment by lrun-cmck** [comment]
It would be great to have such feature. Thank you !

**Comment by tougher** [comment]
Anyone knows if it's possible to add watch support like https://github.com/nor0x/AppCenter-XMac did for mac?

**Comment by DmitriyKirakosyan** [comment]
Hi @tougher , do you mean bindings for Xamarin? Unlike macOS, watchOS is not supported in App Center Apple SDK, so I would not recommend trying to create Xamarin bindings on top of the unsupported platform.
If you want to contribute and add support for watchOS to the native apple SDK, you are always welcome to do so. However, keep in mind that [PLCrashReporter](https://github.com/microsoft/plcrashreporter) doesn't support watchOS either, so you will need to consider contributing to PLCrashReporter as well in order to support Crashes on watchOS.

**Comment by tougher** [comment]
No, not Xamarin, .net 6 is not supporting watchOS anyway. We bundle a SwiftUI watch app with our Xamarin iOS app and I was just looking into a way to collect diagnostics from the watch part. I will look into what it takes to add support in PLCrashReporter first. Thanks!

**Comment by tougher** [comment]
Oh, sorry for the confusion. I thought `AppCenter-XMac` was also building the native AppCenter framwork for macOS, but it was only the bindings.

There are some obvious issues when building for watch that makes it a much bigger task:
![image](https://user-images.githubusercontent.com/10697/149955595-d62d6c29-9f1a-4f9b-abba-e21add9bd62d.png)

**Comment by futuretap** [comment]
Any update on this? It's now 3 years after the original bug report.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for watchOS in the next year, I'm closing this issue.

**Comment by futuretap** [comment]
So my question is even more pressing: Does AppCenter have a future on Apple platforms? Or should we look elsewhere?

**Comment by JagCesar** [comment]
@futuretap I'm guessing no. I considered adding AppCenter to our app which runs natively on all apple platforms, but I guess I'll have to look around for other options.

Maybe there's a business opportunity here? 😄
