### ISSUE TITLE
add reach Badges for ios and android with toolsets info

### ISSUE THREAD

**Issue by gsgou** [microsoft/appcenter#1579]
**Describe the solution you'd like**

It would be a nice to have a badge that could present
also toolsets info for Xamarin projects. Devs could
access the info at a glance in the readme markdown.

iOS: Xamarin.iOS and Mono version
Android: Xamarin.Android and Mono version

relates to API:
https://openapi.appcenter.ms/#operations-build-builds_listToolsets

**Comment by Oddj0b** [comment]
Thank you for the suggestion.
