### ISSUE TITLE
Build from GitHub Enterprise

### ISSUE THREAD

**Issue by simonmcl** [microsoft/appcenter#158]
**Describe the solution you'd like**
Working with a company that uses GitHub Enterprise for its source control. AppCenter would replace several tools that currently require a lot of manual effort to setup and maintain. We have considered using AppCenter, but are unable to connect our repos, stopping us from using the CI or testing tools.

**Describe alternatives you've considered**
Only using AppCenter for distribution. Not enough value add to convince everyone to move over.

**Comment by simonmcl** [comment]
@nrajpurkar any update? is this something that is likely to be picked up?

**Comment by caseyjmorton** [comment]
Bump!

**Comment by johncruz24** [comment]
any update @nrajpurkar ... I would like to use this feature as well.

**Comment by nrajpurkar** [comment]
No update on this at the current time while we have our hands full with [other work](https://github.com/microsoft/appcenter/issues/361).

**Comment by YoungLion** [comment]
+1. As a health tech company, we need to use github enterprise to be compliant with a lot of security protocols. I believe this is typical for a wide range of health/finance/security companies. So please support github enterprise as a build source because we love app center so much.

**Comment by shwanton** [comment]
Now that there is support for [OnPrem Gitlab](https://github.com/microsoft/appcenter/issues/37#issuecomment-514367080), it would be great to have OnPrem Enterprise Github support. There aren't any CI/CD solutions for mobile apps that support enterprise Github (without also installing the Enterprise version ala CirclCI) so AppCenter would be the obvious choice.

**Comment by mikeberlin** [comment]
Any update on this? We are evaluating options for CI/CD and this is the only reason we can’t use App Center.

**Comment by nrajpurkar** [comment]
@mikeberlin no update on supporting GitHub Enterprise at this time

**Comment by ipsonic** [comment]
bump!  john.ipson@mlb.com

**Comment by elamalani** [comment]
@ipsonic No plans to support GitHub Enterprise at this time.
