### ISSUE TITLE
Test Device Sets Bug

### ISSUE THREAD

**Issue by deep-mm** [microsoft/appcenter#1580]
**Describe the solution you'd like**
Currently when I add a new **device set** by the **open api** POST(/v0.1/apps/{owner_name}/{app_name}/user/device_sets)
the device set is visible when I run the GET API but its not visible in the GUI of App Center

App Center GUI:
![image](https://user-images.githubusercontent.com/29853549/72520624-d5f7a480-387f-11ea-97de-c66e4ccf9ae0.png)

App Center API:
![image](https://user-images.githubusercontent.com/29853549/72520772-28d15c00-3880-11ea-8cda-377dd7b18fa1.png)

**Comment by Oddj0b** [comment]
Hi @deep-mm, if you instead navigate to an app owned by yourself and select Test and the device-set submenu. Can you see the newly created set?

**Comment by deep-mm** [comment]
Hey @Oddj0b , no I cannot see the device set in the test sub menu. But the api response says the device set is created.

**Comment by Oddj0b** [comment]
Thank you for testing it out, I'll create a bug for internal tracking.

Den man. 27. jan. 2020 kl. 16.30 skrev DEEP MEHTA <notifications@github.com

**Comment by Oddj0b** [comment]
@deep-mm Can you try end point below for me to see if it appears in the UI?

/v0.1/apps/{owner_name}/{app_name}/owner/device_sets

**Comment by Oddj0b** [comment]
Closing due to low activity.

**Comment by deep-mm** [comment]
Yes @Oddj0b I am able to see in the UI if I add using the owner api. So what exactly is the difference between owner api & user api?

**Comment by Oddj0b** [comment]
Great that it works. The difference is that the /owner refers to the app owners, i.e., organizations. The /user is the logged user and isn't used in the UI.

I'll try and see if we can remove the /user endpoint.
