### ISSUE TITLE
Creating new Auth/Data Connections to Azure broken

### ISSUE THREAD

**Issue by SOliasS** [microsoft/appcenter#1581]
At the Moment it is not possible anymore to make new connections from appcenter Auth or Data to azure...
Old connections are still working fine, but creating new ones is completely broken(EU-West).
I reported this issue back in Dezember and until now all i could get back from the support is, that there is an issue, there's no eta and that if it's urgent i should use msal....
Which defeats the purpose...

I just want to know are you really aware of this problem?
Are you working on a fix?
When can we expect it to work again?
And why does it take so long/why can't you role back to a working version as the only issue is the website which was working in the past?

**Comment by turfday** [comment]
I also reported this issue weeks ago and received virtually no response from Microsoft. This almost tells me that Microsoft has dedicated insufficient resources to Appcenter or nobody is using AppCenter to make a difference.  The solution I am working on now is to do everything that Appcenter does directly through Azure.

**Comment by SOliasS** [comment]
@turfday it's real pitty, as it's was looking like a real nice option to eliminate much of the needless complexity of azure or other cloud services...
And finally make an easy to use/understand feature rich service for data and auth...
For us it was the reason to ditch aws for azure...
But unfortunately it feels like the project is completely abandoned since the start of this year...
Mongo DB Realm looks like the alternative for now...

**Comment by SOliasS** [comment]
#1621 Auth/Data is dead
