### ISSUE TITLE
When adding a 'Tester' to a Group, the website should more easily allow a new email to be entered

### ISSUE THREAD

**Issue by pilcherd** [microsoft/appcenter#1592]
**Describe the solution you'd like**
The website was not permitting a new tester to be added.  When typing an email in the +tester box, the website shows a 'known' user and when you press enter to add, the website selects the popup user instead of the email pasted into the text box.

**Describe alternatives you've considered**
N/A

**Additional context**

Home -> Select App- >Select Distribute -> Select Groups. Select an existing 'testers' Distribution Group.

Select Testers Tab.

In the box 'Add testers', paste a new email.

The website showed a different person.  One elsewhere in the system as a 'popup'.  Both emails were gmail.com ones.  

**Pressing Enter after pasting the email selected the popped up email rather than the one pasted.**

I tried several times and the impression at this point is that you cannot enter a new email as the site keeps just using 'known only emails'.

I discovered that after pasting in the new email that if I pressed Escape it removed the popup email and would then add the new one when Enter was pressed.

**Comment by pilcherd** [comment]
BTW, I'd likely label this as a bug as it was almost impossible to add a new Tester until I realized you had to press Escape.  Browser was Chromium Edge.

**Comment by derpixeldan** [comment]
@pilcherd pressing Enter will add that email. Are you saying it's confusing when the suggestion is open and you first want to dismiss the suggestion dialog?

**Comment by pilcherd** [comment]
The issue is that pressing Enter does not add the email entered (typed).  It uses the email in the popup hint instead, overriding the item that was typed.
