### ISSUE TITLE
Branch based deployment from single repo [Multiple apps for single repo]

### ISSUE THREAD

**Issue by victorkvarghese** [microsoft/appcenter#1595]
I need to deploy apps to app store for each branch. I have DEV, PROD, Staging and UAT environments. Each has a separate branch. What i need to build and deploy each branch to separate app in app store.

The problem is I can only add a single app in app store connect. If i try to add again, it says 'already connected'.

Anyone knows any solution for **branch based deployment to store**?? I couldn't find any articles mentioning these kind of scenarios.

**Scenario**

Single Repo

Dev Branch      ----> Dev_App

Staging branch ----> Staging_App 

I have separate apps in app store for each environment. [For test-flight deployment]

**Comment by victorkvarghese** [comment]
I could add multiple apps in stores section in app center!
If i could do that, i can assign each branch to its own store app
@elamalani @derpixeldan any help??

**Comment by victorkvarghese** [comment]
As of now you can only connect a single app for an app-center project

**Comment by chickdan** [comment]
I am also running into this same issue. We have different environment variables and must be able to differentiate between our staging API for QA testing and our production API for release. To handle this we use two different app identifiers (therefore two different stores) for each environment. Without this capability we have to manage 8 App Center projects for our 4 apps.

**Comment by AndersonVanzo** [comment]
Any update on this?
