### ISSUE TITLE
Preflighted requests in CORS

### ISSUE THREAD

**Issue by epliskovsky** [microsoft/appcenter#1596]
I have customOS application on AppCenter. When I try sending crash - web browser before send POST asked OPTIONS from server(Preflighted requests in CORS). Microsoft server (https://in.appcenter.ms/logs?Api-Version=1.0.0') answer 404 for OPTIONS request.

**Describe the solution you'd like**
Status code 200 for OPTIONS request

**Additional context**
Curl for check working

> curl -X OPTIONS  'https://in.appcenter.ms/logs?Api-Version=1.0.0' -i -v

**Comment by dipree** [comment]
@epliskovsky please also reach out via support so we can better investigate the issue (blue button in the bottom right corner of App Center).
