### ISSUE TITLE
Change Build number

### ISSUE THREAD

**Issue by mamdouht** [microsoft/appcenter#1599]
**Describe the solution you'd like**
I would like to be able to change the build Number.
my case was someone published manually with build number 7100 and automated build is around 100! so now i can not utilize the auto increment because the existing build number is less then the one published to the store.
it would be great if can manually set it to a specific integer and it continues to increment from that number.

**Describe alternatives you've considered**
I tried to write a power shell script to set the build number environment variable but it didnt work.

**Comment by DennisPan** [comment]
Thanks for the feedback. This seems same as #21 . Feel free to re-open if not the case.

**Comment by snios** [comment]
@elamalani will there be a fix for this soon? This was promised a very long time ago.
