### ISSUE TITLE
"DATA" feature on macOS

### ISSUE THREAD

**Issue by stevekellogg** [microsoft/appcenter#1602]
**Describe the solution you'd like**
I'd like to be able to access the data feature of AppCenter on a macOS app.  I'm hoping to be able to use this feature to keep user specific data that I could export to AZURE along with my analytics data to provide a link between my user's experiences (via analytics) and specific data that the user has put into the appCenter data area

**Describe alternatives you've considered**
I could use Apple's CloudKit data layer, but this wouldn't allow the level of integration that I'm hoping for.

**Comment by Zakeelm** [comment]
@stevekellogg  Thank you so much for your feedback on App Center Data. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Data service later this year and recommending customers transition to Azure Cosmos DB instead. Let me know if you have any additional questions about this transition and i'll make sure to get them answered! Closing this issue.
