### ISSUE TITLE
Support for macOS App Store

### ISSUE THREAD

**Issue by clausleanlibrary** [microsoft/appcenter#1604]
**Describe the solution you'd like**
Automated Distribution to macOS App Store

**Describe alternatives you've considered**
Right now we need to manually distribute

**Additional context**
Since you can already distribute to iOS App Store, the macOS App Store would be a logical next step

**Comment by Oddj0b** [comment]
Thank you for your great suggestion @clausleanlibrary

**Comment by stchien** [comment]
Is there plan to support App Center Distribute on MacOS App? Like iOS and Android App? If so, what's the plan and schedule? Thanks.
