### ISSUE TITLE
When marked as "Ignore" issue should stay ignored

### ISSUE THREAD

**Issue by irew** [microsoft/appcenter#1605]
**Describe the solution you'd like**
If an issue is marked as **Ignored** it should stay ignored, even if new crashes arrive.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
No additional context.

**Comment by winnie** [comment]
Hi @irew - thanks for filing an issue! We have a item on our backlog to fix this soon. I'll post here with updates.

**Comment by irew** [comment]
🥰 awesome!

**Comment by octopotato** [comment]
@irew we believe we've identified the issue and have pushed out a fix this morning. Please let us know if you're still running into this issue.

**Comment by matthiaswenz** [comment]
Marking this conversation as closed for now. @irew let us know here or in the App Center customer support should this be happening for you again.
