### ISSUE TITLE
Delete CodePush Releases from the AppCenter console

### ISSUE THREAD

**Issue by ShaharyarMaroof** [microsoft/appcenter#1606]
**Describe the solution you'd like**
There should be an option to delete a specific release from the AppCenter console.

**Describe alternatives you've considered**
The alternate is to run ```appcenter codepush deployment history``` command, which deletes all history.

**Additional context**
I was trying to delete a release I deployed accidentally, which did not have the correct code to be deployed. But there wasn't any way to delete that build from the console. Thankfully it was a test release.

**Comment by Oddj0b** [comment]
Hey, I've CodePush to the title for clarification.

**Comment by pixelknitter** [comment]
Bump - without this feature I'm forced to create a fake release if I cancel a release for Android/iOS after one has already been deployed rather than simply delete the unwanted release to keep the bundle versions in sync.
