### ISSUE TITLE
App Center Push support for collapse id/key

### ISSUE THREAD

**Issue by mschmidt-healthx** [microsoft/appcenter#1607]
Both iOS and Android push notifications (not sure about UWP) support collapsing notifications by sending a collapse key along with the push.  New notifications with the same collapse key replace existing ones, allowing an existing notification to be updated, for example to update an unread message count.

Documentation:
iOS - [apns-collapse-id](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/#2947610)
Android - [collapse_key](https://firebase.google.com/docs/cloud-messaging/concept-options#delivery-options)

**Comment by Oddj0b** [comment]
Hey and thanks for your feature request. A colleague will follow-up with you if necessary.

**Comment by jwargo** [comment]
@mschmidt-healthx thank you for this suggestion, we've had this come up in the past. I'll add this to our feature list.

**Comment by jwargo** [comment]
@mschmidt-healthx Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

Azure Notification Hubs supports adding the collapse ID today.
