### ISSUE TITLE
Export analytics data from last 90 days

### ISSUE THREAD

**Issue by pfedotovsky** [microsoft/appcenter#1608]
According to https://docs.microsoft.com/en-us/appcenter/analytics/export, I can set up export to App Insights and get 2 days of backfilled data. How can I export archive data (90 days old) to App Insights? I've set up export to App Insights, but I don't see any archive data.

**Comment by Oddj0b** [comment]
Your data should always go 28 days back as that is the retention available in App Center. But it sounds like you've been unsuccessful with exporting it to Application Insights. I would suggest reaching out to support inside the App Center portal and they can help you set up a connection.

**Comment by pfedotovsky** [comment]
@Oddj0b thank you! I've reached App Center support and they said that only 2 days of logs are exported to Application Insights. Even if it should be 28 days back, how to export data from 90 days back? The data is visible in App Center, but I can't find functionality to export it.

**Comment by yoannchaudet** [comment]
@pfedotovsky App Center only keeps 28 days worth of raw logs (what we export). What you see in the Analytics section is all aggregated data and it has a 90 days retention but is not exportable other than by calling our REST APIs.

The Export limits we define, 28 days for Blob storage and 48 hours for Application Insights (AI) are driven by our retention policy for the former and AI for the later. AI's ingestion endpoint does not accept logs older than 48 hours as they are optimized for backend telemetry.

**Comment by pfedotovsky** [comment]
@yoannchaudet thank you for the detailed answer!

Is it possible to keep 90 days of raw logs and add an option to exports them to e.g. JSON? As a customer, when I see data in UI for 90 days, I expect that I am able to export the full raw data if needed.

Otherwise, it's probably a good idea to encourage customers to set up continuous export right away.

**Comment by yoannchaudet** [comment]
Unfortunately this is not something we would be looking at for now. I cannot recall the details on top of my head but there are implications around GDPR (General Data Protection Regulation) would we store raw logs for longer than 28 days.

Enabling Export as soon as possible is the best thing I can recommend if you do need more than aggregated data. I see your point and will make a note to mention it in our documentation better.
