### ISSUE TITLE
Better errors when Configure Build doesn't work

### ISSUE THREAD

**Issue by jrr** [microsoft/appcenter#1609]
When _Configure build_ doesn't work, the current UI presents errors like this:

> We couldn’t find any Xamarin iOS projects in your branch.

> We couldn’t find any Xamarin Android projects in your branch.

And links to [this](https://docs.microsoft.com/en-us/appcenter/build/) help page.

**Describe the solution you'd like**

I'd like more detailed error messages. Even if they're technical and jargony, it'd be better than nothing. Some example ideas: 
- "no .csproj or .sln files found."
- "no projects of xamarin ProjectType found."
- "timed out while scanning files."
- "server error while scanning files. Please report this (here), referencing ID #(...)"

**Describe alternatives you've considered**

**Additional context**

In my particular case, the git repo was very large, and moving some files to reduce its size permitted AppCenter to find the projects. We lost some time struggling with this issue, as did AppCenter support.

**Comment by Oddj0b** [comment]
Thank you for the feature request, I've added one of my colleagues to the ticket in case there are follow-up questions.
