### ISSUE TITLE
Be able to distribute to multiple iOS Stores at once

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter#1611]
**Describe the solution you'd like**
On an iOS app when you go to distribute to multiple stores, be able to select multiple. Also on build, if you could select multiple stores this would also be beneficial.

**Describe alternatives you've considered**
You have to either distribute it to one, then in iTunes connect add on your other group.

**Additional context**
We are currently beta testing and have several test flight groups we want to distribute to.

**Comment by Oddj0b** [comment]
Thanks for the feature request @james1301. Can you provide an example of which two stores you would want to select at the same time?

**Comment by james1301** [comment]
I have two different Test Flight groups to distribute to at the moment. Maybe only really makes sense when doing it to multiple Test Flight groups as it will probably be just to the store otherwise.

**Comment by Oddj0b** [comment]
Thank you for clarifying.

**Comment by Heinz12** [comment]
Hi, I also  have several TestFlight groups I want to distribute to. 

My expierence with AppCenter was that you can't do it at once, you have to do it for each TestFlight group. But only the distribution to the first TestFlight group worked. For the second I got a status failed. The first time I tried with no helpful message, the second time the message told me that I have already uploaded a build with the same build number.
So my work around for now is to only upload a build to one TestFlight group from AppCenter and then go to apples App Store Connect to distribute to the other TestFlight group(s). :-((((

It would be fine if I could distribute to all of my TestFlight groups from AppCenter, I think that's the idea ;-)

**Comment by amattice-pfct** [comment]
Same, we're also experiencing this limitation. There are certain cases where we'd like to distribute specific apps through TestFlight which might be building off of different repository branches.
