### ISSUE TITLE
Add a option to select whether or not to display "Unsymbolicated" crashes in "Issues" tab.

### ISSUE THREAD

**Issue by wanja9096** [microsoft/appcenter#1612]
It seems to be changed because of this request : [https://github.com/microsoft/appcenter/issues/939](https://github.com/microsoft/appcenter/issues/939)

But I want to see only symbolicated crashes in Issues because I want to symbolicate all of crashes from public builds, and symbolicate crashes selectively from private builds.

I hope to be added an option that can set simply in the form of a checkbox, or drop-down to change the mode.

Thanks!

**Comment by winnie** [comment]
Thanks for the feature request! This is a great idea and something we briefly explored. We don't have immediate plans to implement this but I'll post here with any updates.

**Comment by wanja9096** [comment]
Thanks for the positive response. I'll look forward to good news about this :)
