### ISSUE TITLE
Problem uploading custom breakpad-style native crashdumps

### ISSUE THREAD

**Issue by astuksnap** [microsoft/appcenter#1615]
**Describe the solution you'd like**
We would like to have crash reporting in our native Windows/MacOs application. For the MacOs there is supported SDK is available however for native Windows we have to resort to the our own solution. It used to work with the Hockey as we were able to upload symbols.zip (breakpad - style) and submit minidump files via REST API and have a proper symbolicated crash reports in Web UI.
However with the AppCenter migration that API was dropped.

**Describe alternatives you've considered**

There are similar feature requests and discussions: #31 #992 #1180 and as a result Appcenter claims it support breakpad style native crashes for windows via https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes#upload-a-breakpad-crash-log-and-minidump

I have tried that API endpoint with the multiple versions of json payload from the documentation as well as hand-crafted based on scheme and despite `{"status":"Success", ... }` reply there are no issues registered on Diagnostics tab.

**Additional context**

- I have tried *Windows / UWP* and *Windows / WFP* application types with no luck.
- Symbols.zip with breakpad compatible layout can be uploaded however UI displays error and 'no symbols found' message. Is it supported?
- Is there a way to diagnose why crash report is dropped? Reports without 'minidump.dmp' attachement processed without problem.

**Comment by Acker2015** [comment]
@winnie 
I also try to upload a minidump file using the crash [api](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes#upload-a-breakpad-crash-log-and-minidump), the response status is a success, but I can not find the crashes in Diagnostics UI part.
