### ISSUE TITLE
[BUG] Build iOS for flutter

### ISSUE THREAD

**Issue by RenanDelfanti** [microsoft/appcenter#1619]
I have problems building my iOS app with flutter.
The same code, with no changes that work when compiling via the app center, is now giving this error.

**Additional context**
[command]/usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/runners/2.164.6/work/1/output/build/archive/Runner.xcarchive -exportPath /Users/runner/runners/2.164.6/work/1/output/build/export/_XcodeTaskExport_Runner -exportOptionsPlist _XcodeTaskExportOptions.plist
2020-01-30 11:32:49.042 xcodebuild[5122:24063] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Runner_2020-01-30_11-32-49.041.xcdistributionlogs'.
error: exportArchive: Failed to verify bitcode in Flutter.framework/Flutter:
error: Linker option verification failed for bundle /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Flutter_gfMKl/Flutter.armv7.xar (unrecognized arguments: -platform_version iOS 8.0.0 13.0.0)

Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in Flutter.framework/Flutter:
error: Linker option verification failed for bundle /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Flutter_gfMKl/Flutter.armv7.xar (unrecognized arguments: -platform_version iOS 8.0.0 13.0.0)

" UserInfo={NSLocalizedDescription=Failed to verify bitcode in Flutter.framework/Flutter:
error: Linker option verification failed for bundle /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Flutter_gfMKl/Flutter.armv7.xar (unrecognized arguments: -platform_version iOS 8.0.0 13.0.0)

}

** EXPORT FAILED **

##[error]Error: /usr/bin/xcodebuild failed with return code: 70
##[section]Finishing: Xcode build (signed)
##[section]Starting: Xcode build (signed)

**Comment by RenanDelfanti** [comment]
And on a machine with xcode I can build normally

Some additional:
xcode 10.3

**Comment by Oddj0b** [comment]
Hey, it looks like you're reporting a bug or having issues. My recommendations are to talk with support through the App Center portal, as this repository is for feature requests.

**Comment by RenanDelfanti** [comment]
Sorry, I'm contact the support!

**Comment by RenanDelfanti** [comment]
Sorry, I will contact support!
