### ISSUE TITLE
UI test recorder

### ISSUE THREAD

**Issue by jiberan** [microsoft/appcenter#162]
**Provide UI test recorder.** 
This functionality was available in[ Xamarin Test Recorder](https://marketplace.visualstudio.com/items?itemName=XamarinInc.XamarinTestRecorder2015) but it was deprecated on March 31, 2018. 

Recording test is a quick way to create a simple smoke UI test in few steps.

**Comment by Oddj0b** [comment]
I'm hoping the feature request gets more reactions, thanks for the feedback.
