### ISSUE TITLE
Iteration Plan for February 2020

### ISSUE THREAD

**Issue by dipree** [microsoft/appcenter#1621]
# February 2020 Plan

### Diagnostics
- [x] Specify .so file path in AzDo App Center release task

### Distribution
- [x] Improve the in-app update experience (phase 1)
- [x] Distribute tvOS apps

### SDK
- [x] UWP/WPF support for ARM 64 architecture

**Comment by SOliasS** [comment]
Is Appcenter Auth/Data dead? Any future plans?
Any alternative planned from Azure?

**Comment by dipree** [comment]
@SOliasS the services will be retired, more about it in this [blog post](https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/).

**Comment by SOliasS** [comment]
@dipree Thanks for the information...
Really not too happy about it so.
The offline sync of data and the easy of using data and auth were definitely features which are missing in azure...

**Comment by patrickdoodyIRL** [comment]
@dipree Concur, the offline sync is a killer feature. 3 months is very short notice for retiring these services.

**Comment by jjchiw** [comment]
It's a shame retiring those services, I was really looking forward to those services (Auth/Data/Push) in AppCenter..... it would really turn the tables with the other services around (firebase, amplify)....

AppCenter with those services would become almost the de facto mobile cloud + devops... mind blown!!!

A good opinionated infrastructure to really focus in what matters... it's really a shame that you didn't want to push this forward...

**Comment by jiberan** [comment]
Appcenter Data was replacement for Azure Mobile Apps. Is there any other Azure service for mobile application with offline support?

Cosmos DB is not really an answer because of lack of offline sync out of the box.

**Comment by valerianb** [comment]
It would really be great to have https://github.com/microsoft/appcenter/issues/192 as Crashlytics is being retired at the end of March and this feature is missing in AppCenter.

**Comment by tipa** [comment]
Is there any chance to get Xamarin.Mac support in one of the upcoming releases? There are quite a few open issues in this repo as well as the AppCenter .NET repo asking for this feature.

**Comment by NunoBem** [comment]
> Appcenter Data was replacement for Azure Mobile Apps. Is there any other Azure service for mobile application with offline support?
> 
> Cosmos DB is not really an answer because of lack of offline sync out of the box.

Did you found a solution for this?

**Comment by SOliasS** [comment]
@NunoBem there is Azure Mobile Apps which have offline sync, BUT ironically it's no longer in active development...
"Please note that the product team is not currently investing in any new feature work for Azure Mobile Apps."
https://github.com/Azure/azure-mobile-apps-net-client

Other then that there is no prebuild solution for CosmosDB, you ether have to connect directly via the Microsoft.Azure.Documents.Client, or build an api.
For the sync part... you have to develop that yourself...

An alternative would be:
If you are just invested in Azure, MongoDB Realm might be interesting for you as you could host it on azure with atlas, but it's in closed beta at the moment...
Other then that there's no azure based cloud service for that on azure anymore.

**Comment by NunoBem** [comment]
> @NunoBem there is Azure Mobile Apps which has offline sync, BUT ironically it's no longer in active development...
> "Please note that the product team is not currently investing in any new feature work for Azure Mobile Apps."
> https://github.com/Azure/azure-mobile-apps-net-client
> 
> There is no other prebuild solution for CosmosDB, you ether have to connect directly via the Microsoft.Azure.Documents.Client, or build an api.
> For the sync part... you have to develop that yourself...
> 
> An alternative would be:
> If you are just invested in Azure, MongoDB Realm might be interesting for you as you could host it on azure with atlas, but it's in closed beta at the moment...
> Other then that, there's no azure based cloud service for that on azure anymore.

@dipree @amchew can you help us?

**Comment by dipree** [comment]
@NunoBem, @jwargo can probably help on that.

**Comment by jwargo** [comment]
@Zakeelm has responsibility for Data questions and @elamalani owns Azure Mobile Apps (ZUMO)

**Comment by jiberan** [comment]
It would be nice if somebody with responsibility from MS could give us some answers. Right now we are in unfortunate situation with one discontinued product and without any clear information about future of mobile development on Azure.

**Comment by msardi23** [comment]
I come here somewhat excited, looking for the latest updates on Auth and Data, only to find the services have been retired!?

AppCenter was providing the right direction for enterprise mobile apps. Providing good support for a variety of SDKs, along with simplifying the enablement of features like Push with the promise to do the same for Auth and Data. 

Killing these off is mind-blowing to me.  What is the MS answer to AWS Amplify? Is there any investment happening in Azure App Service (as there was a statement a few years ago saying no new development was happening with App Service either...).

From an enterprise standpoint, many companies are "forced" down the MS path. With the killing off of important App Center features like Data and Push, it is hard not to justify leveraging AWS and Amplify for all modern app development...

**Comment by Zakeelm** [comment]
@jiberan @NunoBem @SOliasS @msardi23  One potential solution is the Azure client SDKs, which are in active development, but do offer offline sync and auth capabilities. They may serve as a replacement service for your apps. You can find more information using the following links: 

* https://github.com/Azure/azure-sdk-for-ios
* https://github.com/Azure/azure-sdk-for-android

**Comment by SOliasS** [comment]
@Zakeelm might be an option, but i have several problems with it:
1. There's no Xamarin support
2. It's a Preview or even Development like Appcenter data/auth so it can change significantly and/or may be killed of, before it's released 
3. I can't find any good tutorials which would use it and the docu is missing for several projects
4. how could i implement userdata separation?
5. What are the differences between AuzreAuth and MSAL?
6. What is azure mobile?("AzureMobile is an SDK that connects to services deployed using Azure.Mobile." doesn't really answer anything)

**Comment by Zakeelm** [comment]
You are correct, as of today there is just android and ios. As I mentioned it is in active development, so unfortunately i'm not able to ensure there won't be massive changes in how it functions over time.  But, there are a sample project in the repos that could help get started with this.  

For userdata separation, they have a slightly different model than MBaaS had. You use permissions and users. Using both of these, you can create experiences that separate users and their  associated data. The repo has [code snippets](https://github.com/Azure/azure-sdk-for-ios/tree/master/AzureData#permissions) to showcase how this works. 

Azureauth is powered by Azure App services, more information can be found on the [Auth Azure App Services](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) doc. Please note that today, AAD is not supported here. 

And Lastly, per their documentation, Azure mobile  is a framework for rapidly creating iOS and android apps with modern, highly-scalable backends on Azure. It provides APIs for android and ios to do this. It includes a plethora of one-click deployment templates and native SDKs for things such as Auth, Database, and Push. While it does work different than App Center's MBaaS, a lot of the functionality and some entirely new functionality exist within it.

**Comment by msardi23** [comment]
> @jiberan @NunoBem @SOliasS @msardi23 One potential solution is the Azure client SDKs, which are in active development, but do offer offline sync and auth capabilities. They may serve as a replacement service for your apps

The Azure SDK is an answer to a different question. It does not address any of the core needs for the simplified development of mobile applications.  

All I can say is take a look at AWS Amplify. It would great to understand the Microsoft roadmap to get to even 50% of this capability. I just added simple offline support to a ReactJS web app in under 10 min using AWS datastore.

**Comment by allanMoyaM** [comment]
Any future plans to sign two or more Xamarin.iOS app with  different extentions?

**Comment by easterapps** [comment]
hi @dipree, How long are your iterations in 2020. Still February or are the plans no longer public?

**Comment by pkhandelwal-cdl** [comment]
Couldn't find anything regarding upgrade to Xamarin.Android 10.2.0.100 for the AppCenter Build Agents.  Currently we are working around this https://github.com/xamarin/xamarin-android/issues/3852 by doing manual builds for some of our Android projects. 

Is this something that we can expect to be available fairly soon? What is the best place to check for status/timelines on updates to build agents?

**Comment by lumaxis** [comment]
@easterapps They definitely are! We just published a draft for April's iteration plan in #1769
