### ISSUE TITLE
Auto-Update Icon From Latest App Upload

### ISSUE THREAD

**Issue by LowAmmo** [microsoft/appcenter#1624]
**Describe the solution you'd like**
Would like to have the icon of the app that is displayed in app center update with the latest uploaded build of an application.

**Describe alternatives you've considered**
Can manually upload a new icon when it's changed, but would like to have it auto-updated as a helpful confirmation the update has been processed, etc.

**Additional context**
This was an optional feature in Hockey app (could choose whether to update the icon on upload). Would just like similar functionality in App Center.

**Comment by Oddj0b** [comment]
I believe this is an existing functionality of App Center: https://docs.microsoft.com/en-us/appcenter/dashboard/creating-and-managing-apps#uploading-an-app-icon
