### ISSUE TITLE
Make the AppCenter android native app available outside of the Google store

### ISSUE THREAD

**Issue by lacostej** [microsoft/appcenter#1628]
**Describe the solution you'd like**
I want access to the AppCenter apk so that we can install it on devices that don't have Google Play configured.

This link exists today: https://rink.hockeyapp.net/apps/0873e2b98ad046a92c170a243a8515f6 Can't we get the same link from AppCenter once HockeyApp shuts down?

**Describe alternatives you've considered**

* continue using the HockeyApp apk. Not sure if it works after the 10th of February
* download apk from apkmirror or other sites
* use the web interface...

**Additional context**

We have several thousands of users using the HockeyApp app today on devices without google Play. Using the App Center is natural for them.

**Comment by dipree** [comment]
Yes, same app available from App Center here https://install.appcenter.ms/orgs/bitstadium/apps/app-center/distribution_groups/all-users-of-app-center

**Comment by lacostej** [comment]
@dipree that's good.

Questions:
* any reason the version number seems to differ from the Google Play Store version? Are those 2 different products?

* should the documentation (https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android#using-the-app-center-android-app) contain a link to this page?

**Comment by dipree** [comment]
@lacostej
1. Same app different versions. The Play Store variant started at version 1 and we never aligned the two versions. We usually release the self-hosted one a little earlier.
2. Yes, we'll add that.

**Comment by lacostej** [comment]
Closing this in favor of the doc issue I just created.
