### ISSUE TITLE
Support logging of caught exceptions

### ISSUE THREAD

**Issue by joshfriend** [microsoft/appcenter#163]
**Describe the solution you'd like**
I want to be able to log caught exception objects to the crashes list, but be able to filter the list by fatal and non-fatal errors.

**Describe alternatives you've considered**
I currently have to use Crashlytics because it is the only service I know of that supports this

**Additional context**
The hockeyapp sdk let me log exceptions manually, but there was no way to tell which ones were actually causing fatal crashes in the app, so I had to stop reporting them. I often log some non-fatal exceptions that I caught to detect rare or hard to reproduce error behavior.

**Comment by joshfriend** [comment]
Here's a related thread from the hockeysdk for xamarin asking for this feature: https://github.com/bitstadium/HockeySDK-Xamarin/issues/27

**Comment by kuyazee** [comment]
Possible related #160

**Comment by jwhiteDev** [comment]
Hi @joshfriend, what platform(s) are you working with this on? We are looking into this now.

**Comment by joshfriend** [comment]
@jwhiteDev we use native iOS (swift) and native Android (kotlin)

**Comment by danielwilson1702** [comment]
Was there an update on this? I believe this is the one missing piece Crashlytics has that App Center doesn't (I am using Android). 

If I need to log a strange exception with some text, I can't see a way to do that (logging an event using `trackEvent` is a general bucket, so if 10 people have a non-fatal issue I track and I send the info I need as 10 "properties", there is no way to match that to each user

**Comment by winnieli1** [comment]
Hi @danielwilson1702! We have plans to support logging handled exceptions for Android in the upcoming months. No exact ETA yet but I'll post here when I have a better answer.

Thanks!

**Comment by kuyazee** [comment]
> Hi @danielwilson1702! We have plans to support logging handled exceptions for Android in the upcoming months. No exact ETA yet but I'll post here when I have a better answer.
> 
> Thanks!

How about iOS?

**Comment by danielwilson1702** [comment]
@kuyazee looks like an API request for basically this is on the roadmap under https://github.com/microsoft/appcenter/issues/31.

The development ethos to things like road maps and being so active with github issues is great folks, keep up the good work!

**Comment by evanlws** [comment]
I see Android support was prioritized but are there any updates on adding support for non-fatal errors on iOS? This is the only thing I miss from Crashlytics https://firebase.google.com/docs/crashlytics/customize-crash-reports#log-excepts

**Comment by joshfriend** [comment]
(obligatory "bump" comment to keep this thread from being killed by the bot)
