### ISSUE TITLE
iOS code signing automatic without upload certificates

### ISSUE THREAD

**Issue by RenanDelfanti** [microsoft/appcenter#1631]
**Describe the solution you'd like**

The App Center should have an option to automatically sign iOS code, as codemagic has today.
You log into your apple account, and the appcenter would take care of generating and using the certificates.
No certificates upload needed.

**Comment by Oddj0b** [comment]
@RenanDelfanti Where in App Center do you think this should work from?

**Comment by RenanDelfanti** [comment]
@Oddj0b 
In native iOS projects or projects that can compile for iOS, how to react native and xamarin for example.
This feature should be in the build configuration, in the signature part of the application.
You could choose to upload the certificates as they are today, or allow the appcenter to generate the certificates automatically through your apple account.

**Comment by RenanDelfanti** [comment]
This benefits those who don't have a mac today to create their own certificates.

**Comment by Oddj0b** [comment]
@RenanDelfanti thank you for your explanation. I'll add the correct tags and hopefully, this ticket will receive enough :+1: to move forward.
