### ISSUE TITLE
Xamarin.UITest should be Test-Framework-Agnostic i.e. based on TestAdapters infrastructure

### ISSUE THREAD

**Issue by ahmedalejo** [microsoft/appcenter#1632]
**Describe the solution you'd like**
Test cloud should be based be test-framework-agnostic i.e based on Test Adapters infrastructure.
That way it would be able to support several test frameworks like MsTest, xUnit and more.

It´s in particular a shame that **MsTest** isn´t supported at least not that i know of.

This way appcenter wouldn't need to be changed every time a new test framework or framework version is released.

**Additional context**
Test cloud currently only supports NUnit based tests.

Test adapters concept is old:
https://devblogs.microsoft.com/devops/writing-a-visual-studio-2012-unit-test-adapter/

**Comment by ahmedalejo** [comment]
So TestCloud workings is kinda automation framework-agnostic(as in supports several options like Appium, Expresso, Xamarin.UITest Calabash e.t.c.)

But the intended topic was really **Xamarin.UITest should be test-framework-agnostic**.

I´ll update the title and verify if this is still the right repo to open this issue.

**Comment by Oddj0b** [comment]
Thank you for your feature request, it looks really interesting.

**Comment by ahmedalejo** [comment]
@Oddj0b  I´m able to drive **Xamarin.UITest**s with any **.NET Test Framework**.

But when submitted to **TestCloud** the test aren´t discovered unless they are **NUnit** based.

That´s because the **Xamarin.UITest** name is a bit misleading as it isn´t a test framework but instead a **UI Automation Framework** that needs something to _orchestrate_ it.

I **don´t** actually expect the name to be changed though.
