### ISSUE TITLE
[slack app]plz "include incoming Webhooks feature" into app

### ISSUE THREAD

**Issue by birdtomita** [microsoft/appcenter#1634]
https://api.slack.com/messaging/webhooks

As it is now, we have to add two apps to slack for AppCenter. However, the number that can be added is limited. I would be glad if you could put it together if possible.

**Comment by winnie** [comment]
Thanks for the feedback! We don't have plans to address this at the moment but we'll keep this issue open to track community interest and help with prioritization.
