### ISSUE TITLE
Support displaying line numbers about Andorid NDK Crashes

### ISSUE THREAD

**Issue by wanja9096** [microsoft/appcenter#1637]
**Describe the solution you'd like**
Add supporting about displaying line numbers about Android NDK Crashes.

**Describe alternatives you've considered**
Currently, I need to use addr2line to check the line number. This is as inefficient as checking the code file directly, so I hope to support that feature from the AppCenter.

**Additional context**

**Comment by baolongnt** [comment]
It's disappointing to upload symbols and not see line numbers. The stack is pretty useless without them if we need to download the minidump and do the work.
