### ISSUE TITLE
Cancel previous builds when a new build is added to queue

### ISSUE THREAD

**Issue by RishabhTayal** [microsoft/appcenter#164]
**Describe the solution you'd like**
When building from a pull request trigger, if there a new build in the queue, it should cancel the currently running build and cancel the other builds queued in the pipeline.

**Comment by Jensenks** [comment]
How is this not a feature already?

**Comment by foufrix** [comment]
any news on this ? is it something planned ? It's super useful for build optimizations time 
Thanks ! 🙏

**Comment by itfarrier** [comment]
I agree, we need this. Now too many concurrent or pending unnecessary builds.

**Comment by teivienn** [comment]
Is there an update on this?

**Comment by juliancorrea** [comment]
I'm waiting for this feature.

**Comment by justinjoyn** [comment]
This might not get picked up since the feature might hurt the revenue.
