### ISSUE TITLE
iOS Xamarin.UITest OneTimeSetUp: KeyNotFoundException : The given key '13.2' was not present in the dictionary.

### ISSUE THREAD

**Issue by nielscup** [microsoft/appcenter#1640]
Running UITest on iOS results in the following error: 

`OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key '13.2' was not present in the dictionary.`

I have just upgraded to the latest  VS and UITest packages:

1. MacOS Catalina 10.15.3
2. VS 8.4.3 (build 12)
3. Xamarin.UITest 3.0.5
4. Xamarin.TestCloud.Agent 0.21.9
5. XCode 11.3.1

I have found **2 workarounds:** 

1) use `.PreferIdeSettings()` instead of `.InstalledApp(iOSBundleId)` in
```
    ConfigureApp
                .iOS
                .Debug()
                .PreferIdeSettings()
                .StartApp(AppDataMode.DoNotClear);
```
2) install iOS 13.2 simulators (XCode > Preferences > Components > iOS 13.2 Simulator)

Problem is that I am now unable to run UITest on a device with iOS 13.3.

**Comment by Oddj0b** [comment]
Hey @nielscup have you tried contacting App Center support to get help with Xamarin.UITest?

**Comment by nielscup** [comment]
Yes, _8h ago. Not seen yet._ Why the question?

**Comment by Depechie** [comment]
@nielscup I'm facing the same problem, but not seeing the StartApp overload where I can add the isTestSessionStart parameter.
Do you have some gist for this that I can look at? I'm using the https://github.com/xamarin-automation-service/uitest-pop-example pattern though.

**Comment by nielscup** [comment]
@Depechie Good question, turns out this StartApp is a wrapper which does the following:

```
            if (isTestSessionStart) return ConfigureApp
                .iOS
                .Debug()
                .InstalledApp(iOSBundleId)
                .StartApp(AppDataMode.DoNotClear); 
                
            return ConfigureApp
                .iOS
                .Debug()
                .PreferIdeSettings()
                .StartApp(AppDataMode.DoNotClear);
```

So try using `.PreferIdeSettings()` instead of `.InstalledApp(iOSBundleId)`

**Comment by Depechie** [comment]
Thanks @nielscup the PreferIdeSettings() did the trick!
