### ISSUE TITLE
Remember selection of tabs when clicking through issues.

### ISSUE THREAD

**Issue by Bluebeary7** [microsoft/appcenter#1641]
**Describe the solution you'd like**
When I select a tab, for example "Attachments", then select the next issue, I want it to continue showing the tab.  Right now it switches back to "Threads".
![tabselection](https://user-images.githubusercontent.com/14332718/73672648-84665c80-466a-11ea-95ee-3cf9ab3c2a57.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by winnie** [comment]
Hey @Bluebeary7 thanks for filing an issue! This is actually planned work for the quarter. I'll post in this thread with updates. Thanks!
