### ISSUE TITLE
Appcenter Data Auth Migration

### ISSUE THREAD

**Issue by SOliasS** [microsoft/appcenter#1649]
I need information for migration my Data and Auth part of my application.

Especially i need to know, how to connect the AD B2C with Cosomos DB so that the users can only see their own documents(and shared documents in the future).

Is there any good and relevant information?

**Comment by Zakeelm** [comment]
Hi there!

So to do this, you're going to have to re-implement what we called our "Token Exchange Service". To do so, you essentially need to implement your own service that would authenticate a user using AAD B2C, validate that id token thats returned by Azure AD B2C, and then finally use the Cosmos DB client library to generate a resource token.

Cosmos DB doesn't support this behavior out of the box, but the pattern is explained in detail on their [Secure Access to Data](https://docs.microsoft.com/en-us/azure/cosmos-db/secure-access-to-data#resource-tokens-) docs page.

In addition, Cosmos DB doesn't have official mobile SDKS, so you're likely going to have to use AzureData. Here are some helpful links:
- Android: https://github.com/Azure/azure-sdk-for-android/tree/master/azuredata
- iOS: https://github.com/Azure/azure-sdk-for-ios/tree/master/AzureData

I hope this helps. Let me know if you have any additional questions!

**Comment by SOliasS** [comment]
Secure Access to Data  docs page in the example uses App Services which are also as good as dead... i don't want to go from one deprecated solution to the next-.-
And it also isn't really helpful... 
I not soo used to working with azure and so i don't get what to do.

**Comment by SOliasS** [comment]
Found one option:
https://stackoverflow.com
