### ISSUE TITLE
No In App updates until app killed and relaunched

### ISSUE THREAD

**Issue by jeremyeaton89** [microsoft/appcenter#1650]
### **Description**

I integrated the SDK (pretty simple setup) and included the Distribute module. I do get in-app updates, but only after killing the initial build running app center sdk on the device and relaunching. 

The iOS SDK _does_ do this properly, as did our previous Android Hockeyapp SDK powered app. 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. push up a test build to app center
2. install that build on device; launch it to setup in-app updates
3. push up another build with incremented bundle and version
4. expect in app update prompt, but none. background the app, then foreground it — still no in app update
5. kill app; launch again. Now we see the in-app update prompt. 

### **Details**

1. Which SDK version are you using?
    2.5.0
2. Which OS version did you experience the issue on?
    -Android 9
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    Samsung Galaxy S8
4. What third party libraries are you using?
    This is a React Native app if that makes any difference. The RN SDK didn't have support Distribute/in-app-update support, so went native SDK
5. I have done just that but would like to pass this along privately as there may be sensitive info there.

**Comment by ahdbilal** [comment]
The team just took up this feature today. I will share an update once the feature nears completion.

**Comment by ahdbilal** [comment]
Closing this as the the feature branch of this one has been merged. Feel free to reopen it for any follow-up questions.
