### ISSUE TITLE
Would be nice to purge all crashes from a version

### ISSUE THREAD

**Issue by Bluebeary7** [microsoft/appcenter#1654]
**Describe the solution you'd like**
Allow user to select and delete crash logs.

**Describe alternatives you've considered**
Allow individual crashes to be deleted or an entire version.

**Additional context**

**Comment by winnie** [comment]
We don't have immediate plans to support this but you can delete individual crashes via our API here: https://openapi.appcenter.ms/#/errors/Errors_DeleteError 

I'll update this thread if our plans change. Thanks!

**Comment by martinjbaker** [comment]
Another vote for this. When purposely creating crashes on an internal build to test installation, it would be good to have a "Delete" option underneath status of Open/Closed/Ignored, so these fake crashes don't clutter up the data.
