### ISSUE TITLE
Diagnostics > Issues page should default to "Open" issues

### ISSUE THREAD

**Issue by danielwilson1702** [microsoft/appcenter#1655]
**Describe the solution you'd like**
_Every_ time I open the Diagnostics > Issues page, I mildly panic because it is showing me all of the closed issues / crashes. The "Status" filter dropdown is always initialized to "All". I don't really ever want to see issues I have closed again, so either it should "remember" I asked to see only Open issues for the next time, or Open should be the default option. 

**Describe alternatives you've considered**
Fabric would always do a good job of hiding issues you had closed, after all you are done with them so there's little reason to see them again other than to monitor the spread of a problem while your fix is waiting to roll out which is usually not very valuable.

Similar to #1142  and the linked issues in there, I can't find an issue where anyone asks for Open to just be the default though.

**Comment by winnie** [comment]
Hey thanks for the feedback! We don't have immediate plans to change the default  but we have a feature on our backlog this quarter to make the filters persistent. This way, when you select Open, the filters won't be reset next time you land on the Diagnostics page. 

I'll keep this thread updated. Thanks!

**Comment by danielwilson1702** [comment]
Ok that's great thanks! Hopefully it will persist across sessions :)
