### ISSUE TITLE
TestNG support

### ISSUE THREAD

**Issue by kcs-sizarsurani** [microsoft/appcenter#1657]
Hello As you know currently TestNG is trending and it have more feature then junit. 

It will we very helpful for us if you please add this feature.

I my project we are following folder structure but here we have to add every file in same folder which make project very complex. So if you can add this feature it will be very helpful.

**Comment by Oddj0b** [comment]
Thank you for the feature request. We can't fulfill all request and normally features with many :+1: gets prioritized. I'm hoping this will get some attention from App Center users.
