### ISSUE TITLE
Show also distribution status and not only the build status

### ISSUE THREAD

**Issue by s-hintz** [microsoft/appcenter#1658]
**Describe the solution you'd like**
I want easy to see which builds where successfully uploaded to the Apple App Store (TestFlight). 
Please add a red/green icon in the build list for successful distribution.
And please also add the distribution status to the build status mail.
The errors of the distribution log should be visible in build log if automatic distribution is part of the build process.

**Describe alternatives you've considered**
1. Allow to add badges not only for "build" but also for "distribute".
2. Change the existing build status badge to show also the distribution status. 

**Additional context**
The "build/branches/master" pages shows a list of build states.
But we are using automatic upload to the App Store, which can fail for several reasons.
On the build page we see "successful" even when the distribution failed, which is confusing.

**Comment by tompi** [comment]
My company has wasted a lot of time between looking at the build status, then logging into iTunes Connect or play, and only after some time realizing the publish failed

**Comment by s-hintz** [comment]
We still want this feature.

**Comment by s-hintz** [comment]
This feature would still be useful when the build succeeds and the distribution fails.

**Comment by s-hintz** [comment]
This feature would still be useful when the build succeeds and the distribution fails.
