### ISSUE TITLE
We can not run XC tests for iPad only apps.

### ISSUE THREAD

**Issue by s-hintz** [microsoft/appcenter#1659]
**Describe the solution you'd like**
The App Center should also be able to run XC tests for iPad only apps.

**Describe alternatives you've considered**
1. All apps which are the tested in the App Center need to be universal apps.

**Additional context**
Currently we get the following error message:
***build: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:latest, name:iPhone 11 }

**Comment by Oddj0b** [comment]
@s-hintz thank you for your feature request. I'll add the responsible PM. But if I understand you correctly you would like a simulator selector in the Build UI?

**Comment by s-hintz** [comment]
Currently we select the simulator device for local XCtests within Xcode.
We are using one iPad simulator and one iPhone simulator. We chose those devices from what we think that most of our customers are using. From time we update this setting to more modern devices.
Our XCtests generate snapshots of the views of our apps via FBSnapshots. These screenshots are slightly different for each device. 

We also have apps that are iPad only.
We currently can not test this apps with App Center.
App Center tries to use an iPhone simulator, which can not work on an iPad only app.
So the build process fails every time.

We are thinking to be able to select a specific device somewhere will allows us to run XCtests for an iPad only app.

**Comment by smeador** [comment]
+1 to this feature.

We have an Enterprise app which has no iPhone version. I was able to workaround this by adding an internal project configuration with a universal target. This works for internal builds, but will not work for production builds which we need to ship to our customers or the App Store.

**Comment by nvl-agnitio** [comment]
+1 to this feature.

We also have an Enterprise app which has no iPhone version, only iPad, are there any plans to implement this feature?
