### ISSUE TITLE
Sign up using email

### ISSUE THREAD

**Issue by Edudjr** [Microsoft/appcenter#166]
**Describe the solution you'd like**
I want to be able to sign up with an email which is not connected to any of the provided services (github, microsoft, facebook, google).

**Describe alternatives you've considered**
I don't think there are any alternatives.

**Additional context**
No additional context.

**Comment by patniko** [comment]
Hi @Edudjr, excluding this option is a conscious security choice on our part. In the future we'll be aligning more with Azure's authentication model so this more than likely won't be something we ever add to App Center.
