### ISSUE TITLE
HockeyApp for MacOS Upload App

### ISSUE THREAD

**Issue by ehlersd** [microsoft/appcenter#1660]
**Describe the solution you'd like**
Was told the HockeyApp MacOS Upload App would continue to work....would like to see it fixed to work, or a rebranded app made available.

**Describe alternatives you've considered**
Uploading thru the website requires the long Xcode Organizer export, which wasn't required with the HockeyApp MacOS Upload App.

**Additional context**
re: #1074

**Comment by guidedways** [comment]
Couldn't you upload via `appcenter` CLI though? Works fine for me.
