### ISSUE TITLE
Support iOS Deobfuscation

### ISSUE THREAD

**Issue by mpostupaeva** [microsoft/appcenter#1661]
**Describe the solution you'd like**
We need a possibility to upload "mappings.txt" file provided by tools like iXGuard. When mappings file is uploaded it could be used to deobfuscate crash reports.

**Describe alternatives you've considered**
The only alternative currently is to copy the stacktrace and manually deobfuscate it using the mappings file

**Additional context**
This is currently implemented for Android, but not for iOS: https://docs.microsoft.com/en-us/appcenter/diagnostics/android-deobfuscation

**Comment by winnie** [comment]
Thanks for the feature request! This isn't on our roadmap right now but we'll post here if there are any updates.
