### ISSUE TITLE
Force update option for App Center SDK Distribute feature

### ISSUE THREAD

**Issue by kkauppi** [microsoft/appcenter#1664]
**Describe the solution you'd like**
Hey App Center team,
We would like to have forced update option for App Center SDK Distribute feature.

Sometimes when using beta testers on early phase of the development there is a need to introduce breaking API changes. It would be beneficial to have built-in functionality to support forced updates. This would reduce need for maintaining backwards compatibility during development as well as building forced update features within the app.

**Comment by pkhandelwal-cdl** [comment]
@kkauppi - I believe this already exists in AppCenter:

![image](https://user-images.githubusercontent.com/14187883/75211754-d8c89d80-5739-11ea-9aee-fb1763143462.png)

**Comment by DmitriyKirakosyan** [comment]
Hi @kkauppi,

I'm sorry for the super late response and thank you for getting in touch with us! :)

As @pkhandelwal-cdl fairly noted, there is the option "Mandatory update" on the Release Review page.

Closing this issue. Please feel free to reopen it if the problem remains unsolved for you.

Thanks.
