### ISSUE TITLE
Ability to change git repo (including host) for an existing build

### ISSUE THREAD

**Issue by Nick-Lucas** [microsoft/appcenter#1667]
We are transitioning our repositories from GitHub to Azure DevOps and are updating our builds to pick up changes from the new repositories. 

The only way AppCenter provides to do this via the GUI is to entirely delete the build configuration and connect a new repository.

As described in #934 there is a way using the API to patch an app with a new git uri, however, this does not work when trying to move git hosts. When we sent a valid patch request with the new URI (as [described](https://github.com/microsoft/appcenter/issues/934#issuecomment-542289572) and [documented](https://openapi.appcenter.ms/#/build/repositoryConfigurations_createOrUpdate])) the new git connection was added but the build configuration was lost.

~~Additionally #21 is still open, so since we were using the auto-increment feature for the build number, when we do rebuild the pipeline we won't be able to release the app because it will start from 1 again.~~ Nevermind on this point, it looks to have carried over thankfully.

Could a way to connect a new repo from the GUI be provided, while retaining existing build configurations?

**Comment by pyliakm** [comment]
I tried to change url of my git repo and it worked, but all build configuration was displayed with some delay around 3 minutes.
