### ISSUE TITLE
Distribute Debug Android Builds

### ISSUE THREAD

**Issue by akm0012** [microsoft/appcenter#1670]
**Describe the solution you'd like**
I would like to request that Debug Builds be allowed to be Distributed. I think it's a completely valid use case to have only two build variants of an app, Debug and Release. Debug is used for all internal testing and development, while Release is used for what is going on the App Store.

In my situation, our QA Team would test the Debug build internally and it was distributed using HockeyApp, and this worked great. This allowed us to throw exceptions more aggressively by checking if the BuildConfig.Debug == true. It also prevented us from having to create redundant flavors and consequently having to test some weird devRelease variant, which doesn't really make sense and requires us to create yet another keystore. Setting up our resources is also greatly simplified with only a Debug and Release variant.

There's also no reason why you can't have a signing config for a Debug build and have your own in-house Debug Keystore that can technically create signed APKs. Which currently isn't possible in AppCenter today.

Please consider adding this feature as AppCenter is currently forcing us to add more code and add unneeded and unwanted complexity to our code base.

Thanks!

**Comment by artkoenig** [comment]
It is IMHO pointless to prevent debug build distribution in the build process if you allow the distribution of the same binary by manual upload...
