### ISSUE TITLE
Screenshot at time of crash

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter#1675]
**Is your feature request related to a problem? Please describe.**
Our own implementation currently attempts to take a screenshot, and this can be included with the error. If at the time of the crash app center could get this information that would be useful addition.

**Describe the solution you'd like**
At the time of the application crashing, a screenshot is taken. It is then an option to include this to be sent up to app center in the log.

**Describe alternatives you've considered**
Keeping with our own implementation that sends to our support system.

**Additional context**
Useful to diagnose what is going on at the point of error and allows front line support to be able to deal with the problem as they have a screen to look at rather than just an error message.

**Comment by matthiaswenz** [comment]
As mentioned above, there is the option of providing the screenshot capture by yourself and using a binary attachment in your crash report to upload it.
Is your feature request more geared towards the part of the first party SDK support or anything related to the consumption of the potential screenshot in App Center?

**Comment by james1301** [comment]
It's more geared for the process to be geared in, i.e. the framework supports the best way to get a snap shot at the point of crashing. We are allowing the application just to crash now. It would be a useful addition as an option without having to manage that ourselves.

Being able to view them in App Center would then be an option as well I guess, which would also be beneficial.
