### ISSUE TITLE
Why Do you move to Azure and kill the simplicity to integrate AppCenter in our apps?

### ISSUE THREAD

**Issue by biapar** [microsoft/appcenter#1677]
Why Do you move to Azure and kill the simplicity to integrate AppCenter in our apps?
I refer to https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/

**Comment by jwargo** [comment]
@biapar We apologize for the inconvenience of this, but feel we explained that fairly clearly in the blog post. The majority of App Center customers use App Center for DevOps, and we decided to refocus on that.
