### ISSUE TITLE
Support for JUnit Categories with Appium

### ISSUE THREAD

**Issue by misterjunio** [microsoft/appcenter#1678]
**Describe the solution you'd like**
Using `maven-surefire-plugin`'s JUnit categories as described in the last section of [this document](http://maven.apache.org/surefire/maven-surefire-plugin/examples/junit.html) seems to be unsupported at the moment. All the tests run in App Center instead of only the ones annotated with a given category, even when it works locally and the `target/upload/` POM file is correctly configured.
I'd like to be able to run specific sets of tests by category.

**Describe alternatives you've considered**
Only alternative right now is to use inclusion/exclusion of files, but that only works at class level and not test level, which is not enough.

**Additional context**
Nothing to add, seems pretty straightforward to understand.

**Comment by Aubbles01** [comment]
I also would love to see this, so we are not having to pull test cases out into other classes and create duplicate code.
