### ISSUE TITLE
Groups and stores distribution from builds should not be mutually exclusive

### ISSUE THREAD

**Issue by tompi** [microsoft/appcenter#1679]
I would like to be able to distribute to both groups and stores at the same time.

Considering how slow Google play is pushing alpha and beta builds to users devices, we can iterate much more quickly by using the Appcenter groups. However, when testing is done, and we want to release a build, we MUST use google play, and then we manually need to find the correct version in appcenter, and push it to play.

Ideally, once a version is tested and found ok, I would like it to already be in Google Play and ready to be released. Today this is not possible since you have to choose between groups and stores in the build pipeline:

![Screenshot 2020-02-14 at 09 11 28](https://user-images.githubusercontent.com/231717/74513127-2f4c0580-4f0a-11ea-868e-03ce9bfa6ac9.png)

**Comment by Oddj0b** [comment]
@tompi Thank you for your feature request. To me, it seems like a subjective matter when a version is OK, what's your criteria?

**Comment by tompi** [comment]
@Oddj0b Sure, Im not expecting you to setup staged publishing, I just dont see why I shouldnt be able to distribute to both Groups and Store. I mean if you use groups for testing, you WILL need to distribute to a store as well at some point, right? E.g. if every version is pushed to both a group and beta in play, we can just promote the beta to production when testing is complete, instead of having to publish manually from appcenter first.

This is a minor thing though, not that important... Im really happy about how the appcenter builds work, we have some devops builds, but those are a real pain to maintain... To many things to configure :)

**Comment by Oddj0b** [comment]
@tompi now I understand your request. When I read your initial post I wasn't sure if you indeed wanted staged publishing. But having multiple targets makes a lot of sense.

**Comment by chris-cubhub** [comment]
Yes would really love this feature if I can throw a bump on here.
