### ISSUE TITLE
[Feature] Create Distribution Groups using Android IDs or iPhone UDIDs

### ISSUE THREAD

**Issue by marksalpeter** [microsoft/appcenter#168]
**Describe the solution you'd like**
In app center, when I select `Distribute -> Groups -> Testers`, in the "Add testers or groups" field, allow me to enter android ids and iphone udids of the devices I want to add to the group.

**Describe alternatives you've considered**
We use hockey app to distribute a "Dedicated Device" (formerly COSU) android application on hardware that we configure. Currently, we make a new dummy account for every device we deploy. This is obviously not scalable. We've already started to move away from hockey app to our own distribution system. However, the build features of the new app center are very appealing.Its not too late. If you guys decide to work on this, we can halt our own efforts and move thousands of new devices over to app center for our deployment.

**Comment by botatoes** [comment]
Thanks for the suggestion! I think for your scenario, you can utilize public distribution groups. 

For public groups, you don't need to have App Center accounts to download the applications. For iOS specifically, you can add the UDIDs to your provisioning profile and use public groups. 

You can make a distribution group public by clicking on the wrench icon in groups and toggle the public option. Let me know if this will work for you.

**Comment by lumaxis** [comment]
Hey @marksalpeter, did you get a chance to look at public groups like Bo suggested?

**Comment by marksalpeter** [comment]
@botatoes @lumaxis Thank you both for following up. No, unfortunately, public releases do not satisfy our use case. I'll try to break down what we want with as specific of an example as possible:

## Use Case Description
1. We deploy tablet A B and C to three separate stores
2. We want tablet A and B to have build version 1
3. We want table C to have build version 2
4. Once build version 2 is tested we then want tablet A and B to be upgraded automatically
5. Next month we want tablet A to get version 3
6. Then when version 3 is ready we want B and C to be upgraded

We cant do 5 and 6 with public groups. We could rigidly define our groups, but sadly this is not what we want to do. We want to identify specific tablets and install a specific version of our software completely remotely.
