### ISSUE TITLE
Parse apply.from in build.gradle

### ISSUE THREAD

**Issue by bentinata** [microsoft/appcenter#1682]
**Describe the solution you'd like**
Let me know about apply.from build flavor.

**Additional context**
I move out build flavors in different flavors.gradle file, and AppCenter doesn't detect any flavor.

```gradle
# build.gradle
android {
  /* */
  apply.from "flavor.gradle"
}
```

```gradle
# flavor.gradle
android {
  /* */
  flavorDimensions "mode"
  productFlavors {
    x {
      dimension "mode"
    }
    y {
      dimension "mode"
    }
  }
}
```

**Comment by clockworkant** [comment]
@bentinata did you find any work around for this issue? I'd put it down as a bug rather than a feature request 🙁.

**Comment by bentinata** [comment]
@clockworkant I make multiple project back then. Hope that helps.
