### ISSUE TITLE
How to connect private Gitlab repository through API

### ISSUE THREAD

**Issue by larse514** [microsoft/appcenter#1683]
**Describe the solution you'd like**
I would like to config a build for a private Gitlab repository using the AppCenter API.  Is this currently possible?

**Describe alternatives you've considered**
I have tried using the [repo_config API](https://openapi.appcenter.ms/#/build/repositoryConfigurations_createOrUpdate).  This works for public repositories but I have been unable to get the API to work for private repositories.  

**Additional context**
Current error I'm receiving from API:
```json
{"id":"52b4f1df-761d-45bf-9829-8ffd83044f86","message":"Request body requires property: 'repo_id'"}
```

There are various request parameters for the config_repo API; unfortunately I am unclear on what they do.  Nor is there any field level documentation that I can find.  Fields provided in request via the Swagger docs:
``` json
{
  "repo_url": "https://github.com/foo/bar.git",
  "repo_id": "string",
  "external_user_id": "string",
  "service_connection_id": "string",
  "installation_id": "string"
}
```

**Comment by DennisPan** [comment]
@larse514 I'd suggest try connecting the repository once with the portal, while capturing the network trace. You will have a good example of what the portal does, then do the same.

The Swagger docs provide more details about each parameter. For example, for `repo_id`: `The repository id from the repository provider. Required for repositories connected from GitHub App and GitLab.com`

But it is understandable this is still unclear. It's also out dated (e.g. it's required for both self-hosted GitLab as well. Not related to your case though)
