### ISSUE TITLE
Build code in a subfolder

### ISSUE THREAD

**Issue by rrnara** [microsoft/appcenter#1686]
**Describe the solution you'd like**
Consider a repo where the phone code is in a subfolder (in my case the react-native code lives in a separate subfolder and shares code with reactjs web client code and the nodejs server code). Only way to have the phone app built in appcenter is to copy this code to a separate repo with just phone code at the root

**Describe alternatives you've considered**
Having second repo with copy of the code

**Additional context**

**Comment by bitops** [comment]
This is also brought up in https://github.com/microsoft/appcenter/issues/928

**Comment by rrnara** [comment]
Yes, this is dupe of #928
