### ISSUE TITLE
Top devices list is too generic

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/appcenter#1688]
**Describe the solution you'd like**
As seen in the screenshot below, the top used device is Surface Pro. They are tons of SKU and there is no way that our users are using the very first generation of the Surface Pro. The 3rd device, we can see Surface Pro 4. I have a feeling it is a bug instead of a feature.

**Describe alternatives you've considered**
Please provide the right SKU: Surface Pro 4, 5, 6 7, etc.

**Additional context**
![image](https://user-images.githubusercontent.com/1608424/74969837-49df1c80-53eb-11ea-819d-26f224ce6e94.png)

**Comment by ArchieCoder** [comment]
Don't close it!

**Comment by devsmartdok** [comment]
I got more data by finding the GET request and editing top 4 to e.g. top 30.
