### ISSUE TITLE
Specifying Build Configuration for iOS

### ISSUE THREAD

**Issue by berkcoker** [microsoft/appcenter#1702]
**Describe the solution you'd like**
While specifying the build variant for Android is possible on AppCenter, specifying the build configuration for iOS is not. This means that while I can alternate between the "debug", "releaseStaging", "release" options for my Android build, I can't alternate between "Debug", "Staging" and "Release" options for my iOS build. Instead, all I can do with iOS is pick a scheme ("Project", "Project-tvOS" etc). I think specifying the build configuration should be supported for iOS, especially since this is the suggested implementation of ["Multi-Deployment Testing"](https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md) for CodePush. It seems a little bit of an incomplete solution when your own platform does not support the setup that CodePush requires.

**Describe alternatives you've considered**
Having a different Scheme for different build configurations is possible but it defeats the purpose.

**Comment by King-of-Spades** [comment]
Hi, thanks for the feedback! What platform are you using, Swift/Obj-C, React Native, or Xamarin.iOS?

**Comment by ergunkocak** [comment]
We are using Swift 5 and we have configuration which depends on scheme in pbxproj files. Unfortunately AppCenter is not handling these configurations. Is there a plan to support them? Is this task this problem? Best
