### ISSUE TITLE
The UI to view the list of tests should be able to be filtered

### ISSUE THREAD

**Issue by adlee116** [microsoft/appcenter#1703]
**Describe the solution you'd like**
I would like to be able to filter the list of tests either by date or some other factor. Maybe have the ability to upload tests with a tag, or add a tag later? There is no segregation other than test series which doesn't really help. 

**Describe alternatives you've considered**
I open every single different test in different tabs so that I don't have to go back to that list. Chrome as you can imagine loves this. 

**Additional context**

<img width="1616" alt="Screenshot 2020-02-26 at 08 50 49" src="https://user-images.githubusercontent.com/48216789/75327949-1e3db580-5875-11ea-945b-e0bdd041be5d.png">
.

**Comment by Oddj0b** [comment]
Thank you for your request. I'll talk to an engineer to understand the scope of this work. In the mean while I'm hoping we get upvotes to start the work.
