### ISSUE TITLE
Allow definition of environment variables using envfile syntax

### ISSUE THREAD

**Issue by sverps** [microsoft/appcenter#1709]
**Describe the solution you'd like**
I would like to toggle the "Environment variables" feature between the current interface and an editable textinput box that displays the environment variables as they would appear in an envfile. This will make it more fluid and less error-prone to configure the environment variables (I can copy them from my local machine, or from another app on appcenter, rather than having to enter them one by one manually)

**Describe alternatives you've considered**
- Simply uploading an envfile to get an initial configuration combined with the option to download the envfile would yield mostly the same advantages.
- Allowing the copying of the envfile from another app within the project would already make it easier to copy over environment variables where mostly the same data is present

**Additional context**
Currently, when adding a lot of environment variables, it is very easy to make a mistake. Mistakes in the environment variables are hard to detect and often lead to hard to debug issues.

**Comment by elamalani** [comment]
@sverps Thanks for adding this feature request. We will keep this issue open for visibility and would let you know once we decide to support it in App Center.
