### ISSUE TITLE
Can't test multiple apps scenario using Xamarin UITest iOS

### ISSUE THREAD

**Issue by luwed** [microsoft/appcenter#171]
**What App Center service does this affect?**
Xamarin UITest iOS.

**Describe the bug**
Can't test multiple apps scenario on iOS.

**To Reproduce**
1. install two iOS apps on device or simulator. The first app should navigate to the second app (for example after tap on a button). The second app should have some controls (for example a button and a label).
2. Create iOS UITest project.
3. Add test to iOS UITest project with navigation from the first app to the second app after (after tap on a button).
3. Run added test.
4. Can't perform any actions on the second app after navigation from the first app to the second app.

**Expected behavior**
It's possible to perform actions on the second app after navigation from the first app to the second app.

**Screenshots**
MasterApp and SlaveApp apps:

![Screen Shot - iPhone 7 - 2019-03-11 at 16 12 34](https://user-images.githubusercontent.com/48298421/54135094-776cc900-4419-11e9-97fe-cbafb4328fb5.png)
![Screen Shot - iPhone 7 - 2019-03-11 at 16 12 32](https://user-images.githubusercontent.com/48298421/54135109-7dfb4080-4419-11e9-8578-be9d2582af85.png)

**Smartphone**
 - Device: iPhone 7
 - OS: iOS12.1

**Additional context**
I tried to find a way to perform any action on the second app after navigation but without success. Below is the list of things I tried:
1. change the order in which tested apps are started.
2. Use ConnectToApp instead of StartApp.
3. Start and perform actions on the second app on the new thread.
4. Use different app domains to start the first and the second app.
5. Start the second app in a new process.
6. Create two separate tests for multiple apps scenario (run first part of multiple apps scenario in the first test and second part of multiple apps scenario in the second test).
7. Internet research.

**Note**
- it does not matter if test is run on simulator or device (result is the same in both cases).
- **The same scenario described here works on Android (it's possible to perform actions on the second app after navigation from the first app to the second app).**
- Sample apps (including UITest projects) for iOS and Android are available below:
   iOS:
[Apps.zip](https://github.com/Microsoft/appcenter/files/2952878/Apps.zip)
   Android:
[AppsAndroid.zip](https://github.com/Microsoft/appcenter/files/2952880/AppsAndroid.zip)

**Comment by King-of-Spades** [comment]
Currently this is a known limitation of Xamarin.UITest. Xamarin.UITest is not designed to automate multiple apps and change between app contexts. 

It is interesting that you found a way to get something like that process working on Android. As far as I know, again; that's not intended. So if your approach keeps working on Android great, but I don't think that approach is currently QA'd so it might in theory break or be susceptible to changes down the road. 

I believe this should be categorized as a feature request rather than a bug.
