### ISSUE TITLE
Add an option that the build should fail if any custom build scripts have failed or wasn't called

### ISSUE THREAD

**Issue by gsgou** [microsoft/appcenter#1710]
**Describe the solution you'd like**
Add an option that the build should fail if any custom build scripts have failed or wasn't called.

**Additional context**
Recently in a Xamarin project i had an issue that the pre-build script hasn't be called and/or
hasn't been detected. Still the build was successful and a release was done with the staging
environment instead of production. My issue was resolved now by adding the build scripts in
three paths .sln, Android csproj and iOS csproj. Still i think its important that if Appcenter detects
those scripts and they do not run for whatever reason or fail then the hole build should fail as well.

**Comment by elamalani** [comment]
@gsgou Thanks for adding this feature request. We will keep this issue open for visibility and would keep you posted once we decide to support it in App Center.

**Comment by gsgou** [comment]
Thanks a lot for the short message @elamalani. This bug is as important as moving to Azure DevOps or another product the CI.  Without this feature automatic-deployment is not possible as we have to ensure the pre-build was called and was successful manually.
