### ISSUE TITLE
Improve detection of custom build scripts for Xamarin Projects

### ISSUE THREAD

**Issue by gsgou** [microsoft/appcenter#1711]
**Describe the solution you'd like**
Improve detection of custom build scripts for Xamarin Projects

**Additional context**
In Android the pre-build script was not detected from AppCenter while in iOS it was.
The build was stored in the root path together with the .sln file.
After every change on the scripts as described below the Save&Build was pressed to index the script.
- Copying the script also in the location where the csproj in Android is didn't result on execution.
- Then the script was shown as detected but on next build was still not executed.
- After keeping it only in Android csproj path and removing it from the .sln path it was executed.
- Checking the iOS build i noticed it was then no longer executing.
- Removing it from the .sln path and copying it to the iOS csproj as in Android
also did not result in a successful execution in iOS and at the same time was also no longer detected as well.
- Finally re adding it in the .sln path while keeping the copies in Android and iOS
resulted that the pre-build script was running now in both projects.

**Comment by elamalani** [comment]
@gsgou Thanks for adding this feature request. We will keep this issue open for visibility and talk to the team to see how this experience can be improved.
