### ISSUE TITLE
NUnit result XML reports false positive failures

### ISSUE THREAD

**Issue by APIWT** [microsoft/appcenter#1712]
**Describe the solution you'd like**
If you currently run a test on an Android device set, then the NUnit test results XML will report all the tests as failed on the iOS platform. This is because the NUnit test runner skips these tests with the following exception:
`System.Exception : Ignoring iOS test as PLATFORM is not 'ios'. <<XTC-IGNORE-PLATFORM>>`

This will also happen if you run tests on an iOS device set with the following "errors":
`System.Exception : Ignoring Android test as PLATFORM is not 'android'. <<XTC-IGNORE-PLATFORM>>`

The problem, however, is that when you publish the NUnit test results using a tool like Azure DevOps, these "skipped" tests are reported as failures.

I would like to see these tests filtered out of the NUnit results XML.

**Describe alternatives you've considered**
I have considered querying the AppCenter REST API and constructing my own NUnit XML file, however this is cumbersome and it kind of defeats the point.

**Comment by stuarth-inova** [comment]
This would be such a nice fix to get; this problem is really a pain and obscures test result visibility.

**Comment by Oddj0b** [comment]
Thank you for the request.

**Comment by owenniblock** [comment]
Please could you try the latest dev release and let us know if this works for you: https://www.nuget.org/packages/Xamarin.UITest/3.0.8-dev1

After discussion with the folks at NUnit we set the status as `Inconclusive` since they haven't been run.

**Comment by lukashaertel** [comment]
In my opinion that is more a fix of the symptoms, those tests should not be run in the first place. We currently have the situation that sending our Xamarin UI Tests to an App Center app that is configured to run Android. The iOS tests are also included in the test summary. Shouldn't the test execution ignore tests dedicated to an iOS fixture?

**Comment by owenniblock** [comment]
@lukashaertel we use the NUnit console to run your tests, so any valid test will get run unless you specify otherwise (using a Category) - to all intents and purposes, you're saying to NUnit "please run these tests" and we can only augment this process in certain ways.

If you don't want the iOS tests to appear at all, I would recommend either:
- Adding a Category to each test to define the OS and filtering with the Category option.
- Splitting the tests in to separate DLLs and only sending the relevant test DLL.

If that's not possible because you're sharing `Test` methods between Android and iOS - you could split the logic in the method out in to a sub-method and call this method from separate `Test` methods with a Category on each.

**Comment by lukashaertel** [comment]
@owenniblock Of course NUnit should run everything it's told to. The question to ask is where exactly the filtering of test steps should occur.

Should App Center only run tests that are executable on a given platform or should I send a manifest only targeting the platform I'm sending to.

Currently we are using the `appcenter` CLI, first preparing the manifest and then running it. From the parameter options on the steps, it would suggest that the appropriate step is manifest generation, as that one has the options for specifying fixture and including/excluding 
categories, as you mentioned.


I'll try to generate the manifest as follows for now, the unwanted tests seem to be properly excluded. It's a bit of duplication but not too much. In the future it might be nice to have a filter on fixture that allows for wildcards.

```csharp
[TestFixture(Platform.Android, Category = "android")]
[TestFixture(Platform.iOS, Category = "ios")]
```

```
appcenter test prepare uitest [...] --exclude-category ios
```

**Comment by APIWT** [comment]
@lukashaertel 
I agree. The currently proposed solution (https://www.nuget.org/packages/Xamarin.UITest/3.0.8-dev1) seems more like a workaround than a fix to the issue itself.

When I use the `appcenter test` command, I also specify a device set. This device set is bound to an App Center project, which means that it will only ever apply to a single operating system (iOS or Android). Therefore, test results should have zero mention of the alternative platform since the context of my test run is for one platform specifically.

**Comment by owenniblock** [comment]
I get where you're both coming from (and I don't disagree) but I didn't have time to implement anything more complex than the workaround in `3.0.8-dev1`.

I'll leave it up to @Oddj0b whether this Issue remains open for a more comprehensive solution (for reference, that would involve changes in the back-end to add a filter based on the device os selected and then changes in UITest to add a Category based on the TestFixture type - offhand, I don't know how we'd do this exactly so it would need some research before implementation).

In the meantime, I hope the workaround helps alleviate some of this issue for you.
