### ISSUE TITLE
App center won’t let 6th Gen iPad register device or download apps

### ISSUE THREAD

**Issue by nkoteskey** [microsoft/appcenter#1714]
I can’t find how else to raise this issue but my 6th Gen iPad had previously been registered and apps had been able to be downloaded and work from app center. I did not update the iOS since registration and yet when I visited app center to download some updated apps, when I click on them it just reloads the page very fast and nothing happens beyond that. 

I then deleted the iPad from the list of registered devices, along with the profile, to reregister and that’s when I discovered that the register button was completely unresponsive on the iPad. I then updated to the newest iOS and tried to register, same exact issues. 

If you need a screen recording of this behavior I can provide that. 

I can’t seem to attach a video here and screenshots don’t do the behavior justice.

**Comment by lasseOL** [comment]
We had same issue and solved it by turning off Request desktop website in Safari settings

**Comment by ahdbilal** [comment]
We have a bug on out board and are currently looking into it.

**Comment by nkoteskey** [comment]
> We had same issue and solved it by turning off Request desktop website in Safari settings

This was the blocker. Thanks for that and I passed on to some others for iPad tutorial for the time being.
