### ISSUE TITLE
Save build config independently from git repository

### ISSUE THREAD

**Issue by dkoprowski** [microsoft/appcenter#1716]
**Describe the solution you'd like**
I would like to have an option to save my build configuration somewhere.
Now when your token is invalid or you move your repo all configs are gone - there are permanently deleted so even AppCenter administrators cannot retrieve them.

**Describe alternatives you've considered**
Reusable build configuration would be great but maybe even some read-only history of configurations would be helpful? Maybe export to JSON? Something that can be used to restore configuration after repo change.

**Comment by elamalani** [comment]
@dkoprowski Thanks for adding this feature request. We will keep this issue open for visibility and would let you know once we decide to support it in App Center.
