### ISSUE TITLE
Support Tizen platform for crash/error/events

### ISSUE THREAD

**Issue by EmilAlipiev** [microsoft/appcenter#1718]
I would like to see Tizen Platform support for wearables and TV, mobile is also good to have. 
Initially it would be good to have crash/error and events support.

**Describe alternatives you've considered**
I am not sure if possible to use CustomOS in mean time. I couldnt find a precise documentation about it.

**Comment by winnie** [comment]
hey @EmilAlipiev - thanks for the feature request. We don't have plans to support Tizen but I'll keep an eye out for feedback and post here if I have updates. In the meantime, you could create a custom app and manually upload your crash logs here: https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes

**Comment by EmilAlipiev** [comment]
@winnie I am visiting this issue again. I had before chat with appcenter support and i was told that although i can upload custom logs, appcenter is not able to display them in the UI. what is the status today? is there any support for it?

**Comment by Lelelo1** [comment]
It would be nice to have!
