### ISSUE TITLE
Invitation url should only work for the person that it has been sent to

### ISSUE THREAD

**Issue by RalfM1986** [microsoft/appcenter#1721]
**Describe the solution you'd like**
When I add a collaborator to my organization, I only want them to be able to accept the invitation. At the moment I can add user1@mail.com to my organization. User1 forwards the invitation to user2@mail.com. And if user2 accepts the invitation he is added to my organization.

**Describe alternatives you've considered**
The add collaborators option searches AAD users when appcenter is connected to the AAD. And the user is added directly, the invitation mail is only informational for the user to let him know he has been added.

**Comment by ajeesh87** [comment]
agreed. this is a concern for us too. no way to track who was invited and who used the invite link to join.
