### ISSUE TITLE
Improving the flow of the "This device might not be added to your account yet" iOS page

### ISSUE THREAD

**Issue by tfofurn** [microsoft/appcenter#1722]
**Background**
I received this screenshot from a confused tester:
![image](https://user-images.githubusercontent.com/34945253/75791249-ea113b80-5d31-11ea-866f-7148fb5635b0.png)

The user's device had been added already, but the user still got stuck here.  

**Concerns**

* Non-linear flow: the user must read the introductory text, jump down below the action buttons to check the list, then go back up to the action buttons.
* Instructions for the user are smaller than the explanation of why they're on this screen. 
* Language in the instructions ("before continuing") doesn't match language of the corresponding link ("I'm good").
* "I'm good" doesn't read as a path forward for everyone.

**Recommendation**

Structure the page to be read from top to bottom, and have the user pick their device.  

> **Please select your device from this list:**
> * 📱iPhone 11
> * My device isn't shown.

Alternate proposal for the last item: "Add device".  By moving the "add" action to the bottom, the user's gaze proceeds from top to bottom, and the user is more likely to read the whole list before trying to add one that's already there.

**Comment by winnie** [comment]
Thanks for the well thought out suggestion. I definitely see a lot of room for improvement on the screen. Adding @ahdbilal to address this.
