### ISSUE TITLE
Hide build number from emails and app center

### ISSUE THREAD

**Issue by Edgaras91** [microsoft/appcenter#1723]
**Describe the solution you'd like**
An option to hide the build number from email notifications and anywhere inside app center such as Distribute > Releases.
Right now for me, app release version looks like this: 1.0.345 (1)
This (1) is constant for every new release, as there is an auto-deployment set up by azure dev ops, which increments 1.0.345 version with azure dev-ops build number. I don't need this trailing "(1)" that is always 1.

**Describe alternatives you've considered**
Contacted support and was advised to look in the dev-ops build task to edit this build no, but couldn't find anything that removes it or even increments it (I will try to look harder..).

**Additional context**
N/A

**Comment by winnie** [comment]
Adding @ahdbilal who might have some suggestions or workarounds.
