### ISSUE TITLE
View App Expiration and App ID in Releases

### ISSUE THREAD

**Issue by dmak12** [microsoft/appcenter#1724]
Right now when we view the app release we see a lot of helpful information.  App name, build number, size, release notes, provisioning profile and destinations, or which groups we have assigned the app.

It would be very helpful if you could add when the provisioning profile and certificate will expire, and the app ID.

**Comment by winnie** [comment]
This is great feedback! Managing provisioning profiles and certs is defintiely annoying and I can see how this would make the process slightly better. We don't have immediate plans to address this but I'm tagging @ahdbilal who can provide updates.

**Comment by dmak12** [comment]
Hi @winnie and @ahdbilal ,

Is there an update on this request?

Thanks,
Dave
