### ISSUE TITLE
Pipeline/Workflow such as cooperation between jobs and sharing of deliverables.

### ISSUE THREAD

**Issue by gremito** [microsoft/appcenter#1725]
Functions such as cooperation between jobs and sharing of artifacts exist in other CI tools, Jenkins is a pipeline and CircleCI is a Workflow. I want the same function in AppCenter.

**Comment by gremito** [comment]
Maybe there is no function in the free plan?

**Comment by winnie** [comment]
Thanks for the feature request! Adding @elamalani who can better address this.
