### ISSUE TITLE
Check Boxes for viewing crash status

### ISSUE THREAD

**Issue by BillyMartin1964** [microsoft/appcenter#1727]
Instead of having to choose which Crash status to have open by dropdown, can you please put checkboxes so we can have the ones we want...ie Open and Ignored or Ignored and Closed?

**Comment by winnie** [comment]
Thanks for the feedback! We don't have this on our immediate roadmap but we'll monitor for community interest and update the thread when we have a better timeline.

**Comment by BillyMartin1964** [comment]
That's just lame. So my suggestion makes no sense to you? Do you actually use the product?
