### ISSUE TITLE
Bring HockeyApp parity towards AppCenter attachments for custom crash upload

### ISSUE THREAD

**Issue by alamathe1** [microsoft/appcenter#1729]
**Describe the solution you'd like**
HockeyApp used to support the functionality of being able to upload multiple binary attachments along with a text attachment - during custom crash upload. 

Upon migrating to AppCenter we noticed that this functionality does not exist anymore. We currently need to send 2 binary attachment and 1 text attachment - that contains critical information related to an application crash. The custom crash upload followed here is https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes

**Describe alternatives you've considered**
Compress both the binary internally to a single binary file and upload with the text attachment. This requires decompressing multiple times after downloading the attachment from the AppCenter dashboard causing more work for developers when debugging a crash.

**Additional context**
While CI was set up between Hockey and AppCenter - we can see that from crashes pushed to the HockeyApp endpoint and when they were displayed on AppCenter successfully showed 3 attachments.

![image](https://user-images.githubusercontent.com/23223931/76034740-9ac73880-5ef4-11ea-944d-1ba0f6364a22.png)

**Comment by alamathe1** [comment]
@winnie Please take a look

**Comment by winnie** [comment]
Hi @alamathe1 - I might be misunderstanding your scenario but we do support multiple binary attachments along with one text attachment (I know our docs say we only support one - we are working to update that). Did you run into an error when trying to upload multiple attachments?

Thanks!
