### ISSUE TITLE
Use configured build number format in Slack notifications

### ISSUE THREAD

**Issue by kranzky** [microsoft/appcenter#1730]
**Describe the solution you'd like**
We configure builds to auto-increment build numbers and to use the timestamp format. When a build succeeds, the build number shown in the Slack notification does not match the build number shown in TestFlight, or the one that we display in-app. It is therefore not easy for our testers to confirm that they have the latest version. Basically, I would like `${APPCENTER_BUILD_ID}` to appear in the Slack notification.

**Describe alternatives you've considered**
All of the alternatives that we have considered involve manual steps.

**Additional context**
These screenshots are for the same build. They are for: Slack, App Store Connect and TestFlight.

<img width="371" alt="slack" src="https://user-images.githubusercontent.com/38485/76057447-877ba200-5fb4-11ea-9e18-ce1ef3b52e61.png">

<img width="425" alt="Screen Shot 2020-03-06 at 14 07 26" src="https://user-images.githubusercontent.com/38485/76057229-d412ad80-5fb3-11ea-9855-6022476b799d.png">

![Screen Shot 2020-03-06 at 14 08 40](https://user-images.githubusercontent.com/38485/76057324-281d9200-5fb4-11ea-93cb-c5704ba00c14.png)

**Comment by winnie** [comment]
Thanks for the feedback! I can definitely see how this makes it hard for users to find the latest version. Adding our Build PM @elamalani to follow up.

**Comment by kranzky** [comment]
Oh well.
