### ISSUE TITLE
Downloads count for each release should also consider direct downloads (with URL obtained via API)

### ISSUE THREAD

**Issue by mickbyrne** [microsoft/appcenter#1732]
**Describe the solution you'd like**
If a .apk file for an Android app is downloaded using the direct URLs obtained through the API, the count of downloads in the App Center console is not incremented. This was not the case back when Hockey was around, the downloads were incremented.

The reasoning behind this feature is in scenarios where production releases of .apk files are  being downloaded into apps distributed outside the Google Play marketplace. The download counts are a valuable metric for the business owners to measure the uptake of a new update to their app.

**Describe alternatives you've considered**
The alternative is to use a separate analytics system to count these events.

**Additional context**
Nothing else to add.

**Comment by winnie** [comment]
Thanks for the feedback! I'm not sure if we have any plans to address this immediately but I'm tagging @ahdbilal who would know more.
