### ISSUE TITLE
Create API to fetch daily crash counts

### ISSUE THREAD

**Issue by artloder** [microsoft/appcenter#1735]
**Describe the solution you'd like**
The creation of an API to fetch daily crash metrics (the same ones exposed in the "Crashes"
 dashboard available at /crashes/errors). 

**Describe alternatives you've considered**
I'm only interested in the raw counts per day but an API to iterate over the crashes so they can be counted would suffice.

**Additional context**
N/A

**Comment by winnie** [comment]
Hi @artloder - I believe this is the API you're looking for? https://openapi.appcenter.ms/#/errors/Errors_CountsPerDay

Let me know if that works for you!

**Comment by artloder** [comment]
I tried that previously but the data always came back with zero crashes, even though the crashes chart shows over 100 per day. Sample request url (without owner_name/app_name):

```
https://api.appcenter.ms/v0.1/apps/abc/xyz/errors/errorCountsPerDay?start=2020-03-01T00%3A00%3A00&end=2020-03-07T00%3A00%3A00
{
  "count": 0,
  "errors": [
    {
      "datetime": "2020-03-01T00:00:00Z",
      "count": 0
    },
    {
      "datetime": "2020-03-02T00:00:00Z",
      "count": 0
    },
    {
      "datetime": "2020-03-03T00:00:00Z",
      "count": 0
    },
    {
      "datetime": "2020-03-04T00:00:00Z",
      "count": 0
    },
    {
      "datetime": "2020-03-05T00:00:00Z",
      "count": 0
    },
    {
      "datetime": "2020-03-06T00:00:00Z",
      "count": 0
    },
    {
      "datetime": "2020-03-07T00:00:00Z",
      "count": 0
    }
  ]
}
```

**Comment by artloder** [comment]
Looks like when I add an explicit `errorType=unhandledError` parameter, I get counts that match the Crashes dashboard. I figured that no `errorType` filter would return both unhandledError/handledError but that doesn't appear to be working that way; regardless, for my use-case, I am only interested in the unhandled ones, and the counts align when I explicitly query for those.
