### ISSUE TITLE
Top devices showing "iPad11,2" for ipad mini gen 5

### ISSUE THREAD

**Issue by xernaj** [microsoft/appcenter#1737]
**Describe the solution you'd like**
"iPad11,2" is displayed for a device type when it should be "iPad mini 5th Gen".

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by winnie** [comment]
hey @xernaj - can you start a support ticket so our team can investigate? Thanks!

**Comment by yoannchaudet** [comment]
This has been fixed.
