### ISSUE TITLE
rerunFailingTestsCount Maven parameter

### ISSUE THREAD

**Issue by StasGrishaev** [microsoft/appcenter#1739]
**Describe the solution you'd like**
Hi there ! First of all thanks for great service !
Here is my question - as far as i can see Appium tests using _maven-surefire-plugin:3.0.0-M4_ plugin for test task. My question is - can i use _rerunFailingTestsCount_ option for automaticly re-running failed tests ? I was tried set this option in pom.xml file like this...

- in profile section
```
<plugin>
  <artifactId>maven-surefire-plugin</artifactId>
   <configuration>
      <surefire.rerunFailingTestsCount>1</surefire.rerunFailingTestsCount>
   </configuration>
</plugin>
```
- in propertis section
```
<properties>
        <aspectj.version>1.8.10</aspectj.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <surefire.rerunFailingTestsCount>1</surefire.rerunFailingTestsCount>
</properties>
```
...but no luck. according to the running logs in AppCenter there was no re-running for the test.
So, it would be nice if someone can tell me how i can correclty pass re-run count through pom.xml or perhaps throug mvn parameter **-DrerunFailingTestsCount** ( i'm launching tests through CLI btw )

**Describe alternatives you've considered**
Passing rerunFailingTestsCount value through AppCenter-CLI or pom.xml file

**Comment by winnie** [comment]
Thank you for using App Center! I'm tagging our Test PM @Oddj0b who would be able to address this. We might ask you to start a support ticket if further investigation is needed. Thanks!

**Comment by pramodKarande** [comment]
I am also facing the same issue. any update on this?
