### ISSUE TITLE
Analytics: Make flushQueue available externally

### ISSUE THREAD

**Issue by davestjohn** [microsoft/appcenter#1745]
**Is your feature request related to a problem? Please describe.**
I'm using the Analytics framework to gather information about a print job and the minimum send interval results in the print job sticking in the print queue for 3 extra seconds.

**Describe the solution you'd like**
By exposing flushQueue external to the framework, I will be able to skip the minimum interval and the print job will finish promptly.  

**Describe alternatives you've considered**
Allowing a send interval of 'immediate' or even less than 3 seconds are alternatives.

**Additional context**
My request is driven by a macOS only solution (it's a print driver) and there is only one data send per instantiation of AppCenter.  For example, the print job enters the queue, our CUPS filter processes the data, submits it to the printer and then it initializes AppCenter, sends selected analytics, exits.  The use case is much different than an iOS app, website, etc.

**Comment by lovette** [comment]
Related but for a different purpose - I'd like to be able to trigger a queue flush when app telemetry is opted-out. Access to flushQueue directly would be one solution. Another would be flushing the queue when analytics is disabled.

**Comment by davestjohn** [comment]
What is the resolution of this request?  Just closing it without comment is in no way helpful.

**Comment by MrMage** [comment]
FYI, this is the workaround I am using on the Apple version of the framework now:

```swift
	private func forceAppCenterCriticalFlush() {
		// Try ensuring that App Center uploads its logs before the application terminates.
		// App Center does not provide a public API for this, so we have to use private APIs.
		// Tracking issues:
		//
		//  - https://github.com/microsoft/appcenter/issues/1745
		//  - https://github.com/microsoft/appcenter-sdk-apple/issues/2479
		let sharedInstanceSelector = NSSelectorFromString("sharedInstance")
		if Analytics.responds(to: sharedInstanceSelector) {
			let criticalChannelUnitSelector = NSSelectorFromString("criticalChannelUnit")
			if let analyticsSharedInstance = Analytics.perform(sharedInstanceSelector)?.takeUnretainedValue(),
			   analyticsSharedInstance.responds(to: criticalChannelUnitSelector) {
				let flushQueueSelector = NSSelectorFromString("flushQueue")
				if let criticalChannelUnit = analyticsSharedInstance.perform(criticalChannelUnitSelector)?.takeUnretainedValue(),
				   criticalChannelUnit.responds(to: flushQueueSelector) {
					_ = criticalChannelUnit.perform(flushQueueSelector)
				}
			}
		}
	}
```

**Comment by MrMage** [comment]
Still relevant.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
