### ISSUE TITLE
Add search by process type, in Diagnostics

### ISSUE THREAD

**Issue by anteburazer** [microsoft/appcenter#1746]
**Describe the solution you'd like**
A lot of today's desktop apps are Electron multi window apps where each window is a separate process. It would be super useful to know which process has crashed by having an additional search parameter in query builder. Electron uses [breakpad crash log](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes#upload-a-breakpad-crash-log-and-minidump) to upload the crashes and the payload contains **processId** and **processName**. Can you introduce third parameter e.g. **processType** and have an option in query builder to filter based on that?
If one process crashes more than others, this would be helpful tool for distinguishing the errors.

**Describe alternatives you've considered**
If introducing a new param is complicated than the existing ones can be reused - **processId** or **processName**.

**Additional context**
<img width="1384" alt="Screenshot 2020-03-13 at 09 53 05" src="https://user-images.githubusercontent.com/5552682/76608111-6582a200-6515-11ea-8ae1-22b73e518f5e.png">

**Comment by matthiaswenz** [comment]
Can you help me understand the value that would be provided for `processType` in this case? Would this be a custom value or an enum?
This sounds like a very specific use case that might be served by querying for the `processName` instead and standardizing on this.
