### ISSUE TITLE
Show additional download stats details in the release history view of the app center portal

### ISSUE THREAD

**Issue by stiefelkater** [microsoft/appcenter#1748]
Currently the portal only shows total downloads (and total unique users) since the release was published.  I want to be be able to dig down just a bit more into the download numbers from the portal page:
I want to see a daily/monthly trending graph (or at least numbers) of downloads for a given release.
I want to be able to view # downloads by selected date range (e.g., filter by date range)
I want to see # downloads by device segmentation (e.g., iphone 8, iphone 10, iphone 11, etc.) 
I don't want to have to integrate analytics SDK into my app just for these simple stats (e.g., should be universally available vie app center portal)
Would be nice to be able to export/feed download data details into a PowerBI report.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ahdbilal** [comment]
Thanks @stiefelkater for the feedback. We are definitely considering this request and I will share more details with you once there is an update.
