### ISSUE TITLE
Linking failed: The repository URL is not a valid URL.

### ISSUE THREAD

**Issue by kochev** [microsoft/appcenter#1751]
When i try add repository from our instance of gitlab i get error:
appcenter Linking failed: The repository URL is not a valid URL.
Our gitlab instance avaliable on http protocol.
GitLab Enterprise Edition 12.4.2-ee

**Comment by Oddj0b** [comment]
@kochev I would recommend that you contact support from the App Center portal. You can start a conversation from the blue chat icon in the lower right of the screen.

**Comment by BrankoIlic** [comment]
@kochev Have you found a solution? I have the same problem

**Comment by kochev** [comment]
> @kochev Have you found a solution? I have the same problem
@BrankoIlic , no.  Support from the App Center portal sent me here on github. And here is the opposite.
 
If you resolve this problem, please inform me!

**Comment by King-of-Spades** [comment]
@kochev I tried searching in our ticket system for your error message:
> appcenter Linking failed: The repository URL is not a valid URL.

However, I only found two hits from a single user, in both cases the user stopped responding to our support team before we were able to find out much about what happened. 

You can ask the support team for a ticket number, and I can use that to trace your ticket in our system to analyze if there was some confusion about the cause of your issue or something. Posting here, in microsoft/appcenter, is appropriate for scenarios that aren't supported by App Center. For example if it hits one of the limitations noted here: https://docs.microsoft.com/en-us/appcenter/build/connect

**Comment by BrankoIlic** [comment]
My URL was gitlab10.my_company.com:branko.ilic/app_name.git, does that falls under "Subdomains aren't supported"?

**Comment by King-of-Spades** [comment]
@brankollic that's correct, unfortunately.

**Comment by manuelplazaspalacio** [comment]
I have the same problem with this url: http://git.nosi.cv/nhacard/nhacard-android.git, you know what could be the problem?
