### ISSUE TITLE
Additional Role Developer

### ISSUE THREAD

**Issue by pavhub** [microsoft/appcenter#1753]
**Describe the solution you'd like**
Apart from Admin, there should be role for developer so that they can upload the builds.

Admin has more privileges other uploading the builds.

**Comment by Oddj0b** [comment]
Besides the admin, collaborator, and members you would need a developer role?

https://docs.microsoft.com/en-gb/appcenter/dashboard/creating-and-managing-organizations

**Comment by Brantone** [comment]
Can't speak to @pavhub 's use case; however, in our scenario, having a role that is between "Member" and "Distro Group" would be useful. There's lot of nifty features that members could do; however, apprehensive about allowing them to create apps.
It's my understanding that if we want to add a "Viewer" to an app, they much be a collaborator, the lowest level would still allow apps to be created. In a large Org, this has the potential for devs to spin-off their own apps which is ripe for confusion.
