### ISSUE TITLE
The install web page doesn't display properly on Safari

### ISSUE THREAD

**Issue by JoCharlet** [microsoft/appcenter#176]
**What App Center service does this affect?**  
install web page

**Describe the bug**  
When accessing the install page from Safari (iOS and MacOS), the layout of the page doesn't display properly.  
The width of the content block is not taking the full width of the page.  
The height of the content block is overflow by the text from release Notes.

**To Reproduce**  
Acceed to the install page with Safari from an Apple device.

**Expected behavior**  
Width of the content block should take the full width of the page.  
Responsive content block with the length of the text from release Notes.

**Screenshots**  
![iPhone_portrait](https://user-images.githubusercontent.com/20091704/54280942-f89e9a00-4598-11e9-80ef-b5d7943c40f4.png)  
![iPhone_landscape](https://user-images.githubusercontent.com/20091704/54280945-fccab780-4598-11e9-92e2-3463181b15c1.png)
![iPad_portrait](https://user-images.githubusercontent.com/20091704/54280968-0eac5a80-4599-11e9-89f7-8cd4cba60c8c.png)
![iPad_landscape](https://user-images.githubusercontent.com/20091704/54280985-179d2c00-4599-11e9-8a59-9b740ffd74be.png)
![MacOS](https://user-images.githubusercontent.com/20091704/54280991-19ff8600-4599-11e9-9144-64872e08a771.png)

**Smartphone**
* iPhone 6S on iOS 12.1.4 with Safari
* iPad (model A1893) on iOS 12.1.4 with Safari

**Desktop**
* Mac mini (Late 2014) on macOS High Sierra vers. 10.13.6 with Safari 12.0.3

**Additional context**  
This issue is more obvious to observe with a significant amount of text content from release notes. 
No issue by accessing the webpage from Android (Chrome).  
No issue with Mozilla Firefox vers. 65.0.2 (Windows).  
Length issue of the content block with a significant amount of text from release notes in Google Chrome vers. 72.0.3626.121 (Windows)

**Comment by amchew** [comment]
Thanks @jocharlet @DrBeak1 for reporting the bug! @botatoes would you mind taking a look?

**Comment by DrBeak1** [comment]
@amchew not sure why you @'d me here, but I do support this bug being fixed :)

**Comment by amchew** [comment]
@drbeck1 copy paste mistake 🤦🏻‍♀️ But good to have your support to fix this 😉
