### ISSUE TITLE
[UWP] Allow to filter unhandled exceptions

### ISSUE THREAD

**Issue by maxkatz6** [microsoft/appcenter#1779]
**Describe the solution you'd like**
Right now AppCenterSDK will send to dashboard any unhandled exception, which was thrown in application.
For my needs, I want something to filter exceptions:
```csharp
bool FilterException(Exception exception, bool isUnhandled)
```
Or I see better way with Crashes.SendingErrorReport event which have SendingErrorReportEventArgs arguments and it could be updated with one new field
```csharp
public class SendingErrorReportEventArgs : ErrorReportEventArgs
{
    public bool Cancel { get; set; }
}
```
Error will be ignored by SDK, if it was handled with setting Cancel to 'true'.

**Comment by winnie** [comment]
Thanks for the feedback! What kind of exceptions are you looking to filter out?

We have a SDK method that might work for you: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp#should-the-crash-be-processed

Or you can use our search functionality: https://docs.microsoft.com/en-us/appcenter/diagnostics/search

**Comment by maxkatz6** [comment]
@winnie 
Thanks, I didn't found that filter before, my bad.
But still it isn't really suitable for my cases, because it doesn't contains Exception information - it has only Stacktrace, which isn't really friendly.
But anyway, it should be enough.
