### ISSUE TITLE
Failed to publish to store. Release Notes should contain min 10 to max 4000 characters but contain 9 characters.

### ISSUE THREAD

**Issue by andreialecu** [microsoft/appcenter#1780]
**Describe the solution you'd like**

When pushing a commit with a message smaller than 10 characters, the push to Apple's servers will fail for iOS apps.

Apple's servers reject the publish with this error:

```
##[error]{"code":"bad_request","message":"Error: Failed to publish to store. Release Notes should contain min 10 to max 4000 characters but contain 9 characters."}
```

The commit message was `fix build` in this case.

As a possible fix I would suggest adding some padding to commit messages to make them at least 10 characters, and also trimming to 4000 if somehow it goes overboard.

**Describe alternatives you've considered**

Most times this will be fine, but we had to log in to app center and check why the build was failing, so it added a bit of friction to the experience.

**Comment by andrew-lundy** [comment]
This is by the design of Apple, not App Center.
