### ISSUE TITLE
Make download button available on mobile browsers

### ISSUE THREAD

**Issue by kiskunk** [microsoft/appcenter#1781]
**Describe the solution you'd like**
When Appcenter is opened on mobile devices, the download button should be visible.

**Describe alternatives you've considered**
Maybe show a link instead of a button?

**Additional context**
Currently I have to change to desktop mode everytime I want to download an APK.

**Comment by winnie** [comment]
Hey @kiskunk - thanks for the feedback. Are you referring to the appcenter.ms page or the install portal (install.appcenter.ms)?
