### ISSUE TITLE
Webhook For Test Completion

### ISSUE THREAD

**Issue by stefan1407993** [microsoft/appcenter#1783]
**Describe the solution you'd like**
Just to include an option to notify through webhook when tets is completed.

**Describe alternatives you've considered**
Alternative is integrating Zapier to respond on all emails that arrive from Appcenter that include test in subject.
**Additional context**
It's not useful not to have webook feature for test completion if you have an entire testing environment.

**Comment by winnie** [comment]
Thanks for the feature request! We don't have any immediate plans to add this but we'll consider it for our future roadmap.

**Comment by Oddj0b** [comment]
Duplicate of #318

**Comment by corneliu-serediuc** [comment]
I would also be very interested in this feature. Thank you!
