### ISSUE TITLE
Configurable entry-file for "Generate source map" build step

### ISSUE THREAD

**Issue by jeremybarbet** [microsoft/appcenter#1785]
Hi!

**Describe the solution you'd like**
I'm using react-native with typescript and my entry file for my project is `src/index.ts`. Even though the "Generate source map" build step is looking for, confirmed by the Appcenter support:

```bash
INDEX_FILE="index.ios.js"
if [ -f "index.js" ]
then
  INDEX_FILE="index.js"
fi
echo "Found $INDEX_FILE for ReactNative index."
```

It's only happening on iOS, because there isn't such build step on Android. 

Would it be possible to have an environment variable that will allow us to configure the entry file? Something like `APPCENTER_REACTNATIVE_IOS_ENTRY_FILE`.

So in the AppCenter interface I will be able to define `APPCENTER_REACTNATIVE_IOS_ENTRY_FILE=src/index.ts`

Then in the appcenter build step it would look like:

```bash
INDEX_FILE="index.ios.js"
if [ ! -z "$APPCENTER_REACTNATIVE_IOS_ENTRY_FILE" ]
then
  INDEX_FILE=$APPCENTER_REACTNATIVE_IOS_ENTRY_FILE
elif [ -f "index.js" ]
then
  INDEX_FILE="index.js"
fi
echo "Found $INDEX_FILE for ReactNative index."
```

Cheers

**Comment by winnie** [comment]
Thanks for filing an issue! Adding @elamalani who can help address this.

**Comment by seand88** [comment]
same issue

**Comment by abra-ham** [comment]
Hi! Are there any news regarding this issue?
