### ISSUE TITLE
Allow repository path filters for triggers

### ISSUE THREAD

**Issue by ahmedalejo** [microsoft/appcenter#1787]
**Describe the solution you'd like**
```gherkin
Given i have all my code in one repo (i.e. a mono-repo)
  And i want to set up a CI pipeline
 When i choose a trigger option based on changes to a repo
 Then I´d like to be able to specify path filters for the repo to trigger the CI from
```

**Describe alternatives you've considered**
I currently use Azure DevOps path filters and then trigger an AppCenter Build

**Additional context**
This is a simple filter available on azure DevOps
![image](https://user-images.githubusercontent.com/7012074/78563726-cee29180-77f1-11ea-8f6e-ba0eb8ae7e30.png)

**Comment by jantanis** [comment]
Easiest (and most useful) would be if you could have a filter config file per build configuration. There would be no need for a UI.
