### ISSUE TITLE
Add support for Jira Server as bug tracker

### ISSUE THREAD

**Issue by ffittschen** [microsoft/appcenter#1789]
**Describe the solution you'd like**
The documentation of the [App Center bug tracker integration](https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/) states that for Jira one should use an API token instead of the password. This is only possible with Jira Cloud, because Jira Server does not support the generation of API tokens (see https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

Therefore, I'd like to request the support of configuring Jira Server as the bug tracker.

**Describe alternatives you've considered**
n/a

**Additional context**
This issue was also brought up in the AppCenter docs repo: https://github.com/MicrosoftDocs/appcenter-docs/issues/672

**Comment by winnie** [comment]
Thanks for the feedback. Supporting Jira Server isn't on our immediate roadmap but we will continue to evaluate this and post here with updates.

**Comment by arctouch-benogilvie** [comment]
We would like to see this feature as well.
