### ISSUE TITLE
Don't clone cocoapods spec repo on every build run

### ISSUE THREAD

**Issue by chrish10e** [microsoft/appcenter#1791]
**Describe the solution you'd like**

Every time I run a build App Center spends 8-9 minutes cloning the cocoapods spec repo. It's a huge waste of time and of your resources, especially if I haven't made changes to my Podspec. Can you add a way to skip this step?

**Comment by winnie** [comment]
Thanks for the feedback! We've heard similar requests to skip re-building parts of the app that have not been changed. This isn't on our short term roadmap but we will monitor this for community interest and consider prioritizing it in the future.

**Comment by webdevbyjoss** [comment]
+1 for the request, it is clear that we are building our app always on a clean image (similar to how CircleCI, TraviceCI or other solutions do that). At the same time they also offer an ability to cache certain directories hence allow skipping the expensive operations like downloading the 3-rd party dependencies which allow to speed up the build dramatically.

**Comment by mikewoodworth** [comment]
+1
