### ISSUE TITLE
Add filters to exclude/include IP addresses or domains

### ISSUE THREAD

**Issue by ju2pom** [microsoft/appcenter#1792]
**Describe the solution you'd like**
Like it's done in Google Analytics it would be really useful to be able to setup filters to exclude some IP addresses to have more accurate charts. I think filtering on AppCenter side is better than disabling AppCenter on developers/testers computers because there would be no way then to detect potential issue with AppCenter integration.

**Describe alternatives you've considered**
The alternative is to implement a kind of feature toggle to completely disable AppCenter in the application based on environment variable or a user setting.

**Comment by winnie** [comment]
Thanks for the request! Can you elaborate a little bit more on your use case? Would you like this filter for both Analytics and Diagnostics data and would this primarly be used to filter out data from non-production environments?

**Comment by ju2pom** [comment]
Hi @winnie,
Thanks for reviewing my request.
The main goal is to filter out non production environments (mainly on analytics)
