### ISSUE TITLE
organization delete option

### ISSUE THREAD

**Issue by sandeep-tj** [microsoft/appcenter#1793]
**Describe the solution you'd like**
1. Created many organisations as. part of CD integration. Now there is no option to keep my acount clean.
2. Created few organisations with client names, Now there is no option to create the same organization in client account.

**Describe alternatives you've considered**
Considered org creation with my company name as prefix.

**Additional context**
It would be better if we could have delete option for organisations.

**Comment by winnie** [comment]
Hey @sandeep-tj - you can delete an organization by selecting the organization in the left navigation menu and clicking the **Manage** page. 

![image](https://user-images.githubusercontent.com/8868628/81184415-63b9e580-8f7e-11ea-8b7c-7c0796744a81.png)

You can also use our API: https://openapi.appcenter.ms/#/account/organizations_delete

Hope that helps! Closing this issue for now but feel free to reopen if the solution isn't what you were asking for.

**Comment by sandeep-tj** [comment]
Thank you for the response. It helped me a lot.
