### ISSUE TITLE
AppCenter keeps on displaying "No Apps available for your Device"

### ISSUE THREAD

**Issue by muffadal53** [microsoft/appcenter#1797]
Hi AppCenter,

Today I am when I try to browse AppCenter on my Android and iOS the message which I am continuously getting is "No apps available for your device". Can you kindly check this and let me know what needs to be done.

Thanks.

**Comment by bigggge** [comment]
+1 All request return http status 429

**Comment by ahdbilal** [comment]
Are you still getting these errors?

**Comment by ahdbilal** [comment]
Closing this issue because of no response. Feel free to reopen it.
