### ISSUE TITLE
Event Flow has no Filter on Version No , filters only on Major Version no.

### ISSUE THREAD

**Issue by teenahjob** [microsoft/appcenter#1802]
**Describe the solution you'd like**
There is no filter on Version No, Only filters on Major Version for Event Flow
**Describe alternatives you've considered**
There should be filter on Version no for Event Flow just like Crash Reports.

**Additional context**

**Comment by winnie** [comment]
Hey thanks for the request! It seems like you're referring to the Analytics Events page? We have a Versions filter on this page. Can you elaborate on what you'd like to see instead? 

![image](https://user-images.githubusercontent.com/8868628/81183272-f3f72b00-8f7c-11ea-98a9-7d19883fe78a.png)
