### ISSUE TITLE
EventFlow/Crash Reports no Filter on DateTime

### ISSUE THREAD

**Issue by teenahjob** [microsoft/appcenter#1803]
**Describe the solution you'd like**
EventFlow/Crash Reports Should allow filtering on DateTime like Today or Just show Calendar to select Date.

**Describe alternatives you've considered**
EventFlow/Crash Reports Should allow filtering on DateTime like Today or Just show Calendar to select Date.

**Additional context**

**Comment by winnie** [comment]
Hey @teenahjob - thanks for filing an issue. Are you referring to the App Center Diagnostics page and/or the Analytics Event Flow tab?
