### ISSUE TITLE
Feature to organize Apps in Folders

### ISSUE THREAD

**Issue by gmmsantos** [microsoft/appcenter#1804]
**Describe the solution you'd like**
We have a lot of builds in our My Apps pages and it would be great if we could organize the apps inside folders

**Describe alternatives you've considered**
Better experience on Categorize apps

**Additional context**
nothing to say

**Comment by winnie** [comment]
Thanks for the feedback! We don't have any short term plans to add this functionality but we'll consider this in our future planning. 

Linking a few other similar requests:

https://github.com/microsoft/appcenter/issues/1752
https://github.com/microsoft/appcenter/issues/352
