### ISSUE TITLE
Make upload last stage of submission

### ISSUE THREAD

**Issue by leehu** [microsoft/appcenter#1808]
**Describe the solution you'd like**
IIRC in hockeyapp, I used to fill in all the info, e.g. change descriptions, who it was going to etc and the last stage was upload.

**Describe alternatives you've considered**
None, this is a worflow issue and probably isn't a problem for people on super speedy connections, but uploads take minutes for me.

**Additional context**
This has now changed, and upload is the first thing that happens.
The problem with this is that if the upload takes 5 mins for example, I'm constantly checking when it's completed so that I can fill in the other info.
In the past, I knew that even if the upload took ages, I didn't need to monitor it as after it had completed, it would release the version.

**Comment by ahdbilal** [comment]
Thanks for the feature request. I will bring this up with the team during our next triage session.
