### ISSUE TITLE
Remove a bug tracking service before it's fully set up

### ISSUE THREAD

**Issue by joshspicer** [microsoft/appcenter#1813]
**Describe the solution you'd like**
Under `Settings > Services > Bug Tracker` I added the wrong Microsoft account for Azure DevOps. I don't want to continue on in the setup and don't see a way to remove this link from my account.

**Comment by winnie** [comment]
Hey @joshspicer - please contact our support team and we can help remove or reconfigure the bug tracker integration from our side. 

We're also looking to add a feature that allows users to remove the integration themselves. I will keep this thread updated. Hoping to have a better ETA in the next few weeks. Thanks!
