### ISSUE TITLE
Capability to avoid sending crash reports over mobile data / low bandwidth, but resume with Wi-Fi connectivity

### ISSUE THREAD

**Issue by ishita-pandey** [microsoft/appcenter#1814]
**Describe the solution you'd like**
We have an android app that uses App Center's crash and analytics features to send crash reports. When a crash occurs, the report is sent to App Center irrespective of the network connectivity. This leads to a higher mobile data usage of users. We'd like to have a capability where if the crash occurs over mobile data / low bandwidth, it should be preserved and sent only when the user is connected back to the Wi-Fi. 

**Describe alternatives you've considered**
I tried working on the following API -
 

     /**Called from a worker thread to determine whether a crash report should be processed or not.

     *
     * @param report A crash report that will be sent.

     * @return <code>true</code> if it should be processed and sent, otherwise <code>false</code>.

     */

    boolean shouldProcess(ErrorReport report);
But the issue here is that if I return false in case of mobile data, the crash reports will not be preserved for it to be sent when connected back to the Wi-Fi.

**Additional context**
None

**Comment by winnie** [comment]
Thanks for the feature request! We don't support this exact scenario but you can use our SDK methods to notify the user and only send the crash report when on wifi: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#customize-your-usage-of-app-center-crashes

However, if our SDK needs to retry sending the report for some reason, like slow wifi connection or if the network switched, then this might consume network data. 

We'll continue to evaluate this scenario and prioritize it accordingly. Thanks!
