### ISSUE TITLE
Uploading Files Progress Bar

### ISSUE THREAD

**Issue by mahesh-kumbhar** [microsoft/appcenter#1816]
**Describe the solution you'd like**
While Running test for Cloud Execution.
There is step" \ Uploading files... "
we can not understand here how much time it will take to upload file.

what we can see is just " \ Uploading files... "

**Describe alternatives you've considered**
Is there any way to display percentage of Uploaded File. 
Like Progress Bar or in form Of 50 % 60% 70% 80% 90% 100%
Or Remaining time Like 5 Min, 4 Min,3  Min,2 Min,1  Min

**Comment by Oddj0b** [comment]
Thank you for your feature request. Can you elaborate a little on what problem you're trying to solve?

**Comment by mahesh-kumbhar** [comment]
![Screenshot 2020-05-06 at 1 15 42 PM](https://user-images.githubusercontent.com/24523796/81149474-e735ff80-8f9b-11ea-8882-db20ed8d306a.png)

It will be helpful if display percentage of Uploading File Status.
like - Uploading File 10% 20% 30% ....

**Comment by Oddj0b** [comment]
I'm trying to understand when this will be helpful, I'm not saying we should implement it. Do you want progress updates because you experience dropped connections?

**Comment by mahesh-kumbhar** [comment]
Actually Currently I am working with mobile network + VPN .Which is causing Sloness in Network.

In Slow network , we can see only 'Uploading Files...' text. some time it takes more than 30 Min For 150MB Size App File.

By Showing Status we can assure that  Uploading is in progress
