### ISSUE TITLE
Android 11 App exit reasons

### ISSUE THREAD

**Issue by catlan** [microsoft/appcenter#1822]
**Describe the solution you'd like**
It would be nice to have a dashboard widget for the upcoming Android 11 App [exit reasons](https://developer.android.com/reference/kotlin/android/app/ActivityManager#gethistoricalprocessexitreasons).

**Additional context**

> App exit reasons updates - Apps can exit for a variety of reasons, from crash to system kill or user action. Across the many device types, memory configurations, and user scenarios that your app runs in, it’s important to understand why the app exited and what the state was at the time. Android 11 makes this easier with an exit reasons API that you can use to request details of the app’s recent exits. In DP3 we’ve updated the APIs based on your input, so please take a look. If you haven’t had a chance to check out this new API yet, we recommend giving it a try and please let us know what you think here.

https://android-developers.googleblog.com/2020/04/android-11-developer-preview-3.html

**Comment by winnie** [comment]
Thanks for the feature request! We'll take a look at this and monitor the thread for community interest.
