### ISSUE TITLE
Diagnostics - User ID export

### ISSUE THREAD

**Issue by SebC99** [microsoft/appcenter#1823]
**Describe the solution you'd like**
On the diagnostics section, with all the crashes of a specific issue, it would be very useful to be able to download the reports table as a csv, or at list the user IDs list, in case we need to get in touch with those users, or to run background jobs on their data.

**Describe alternatives you've considered**
Select All, Copy All, Paste All :)

**Comment by winnie** [comment]
Thanks for the request! We don't have any short term plans to add any additional export functionality however, you can get a list of user IDs from exporting your crashes data to Azure Blob Storage or Application Insights. You can find more info in our [docs here](https://docs.microsoft.com/en-us/appcenter/diagnostics/features#export-diagnostics-data) and check out [this blog post](https://johnthiriet.com/crashes-and-errors-app-center-application-insights-errors/) written by a community member. 

We'll monitor this thread and post here with any updates.
