### ISSUE TITLE
Build status email notifications

### ISSUE THREAD

**Issue by vmalyi** [microsoft/appcenter#1824]
**Describe the solution you'd like**
I would love to get build status email notifications (passed/failed/etc.)

**Describe alternatives you've considered**
In AppCenter, there is no dashboard with the current build status. If an organization has multiple apps with multiple builds running on a regular basis, checking build status requires visiting each app's build page to see build execution results.

**Additional context**

**Comment by winnie** [comment]
Hey @vmalyi - you can manage your email notifications in your app settings page. 

![image](https://user-images.githubusercontent.com/8868628/81081674-36a6fd80-8ec0-11ea-90ae-aac02c7d3124.png)

It's a bit hidden but the email settings we have should meet the solution requirements you described. Let me know if that's not the case.

I've also linked a few feature requests similar to your note about app dashboards:
https://github.com/microsoft/appcenter/issues/1184
https://github.com/microsoft/appcenter/issues/1567
https://github.com/microsoft/appcenter/issues/937

Feel free to give them a +1. Thanks!
