### ISSUE TITLE
Ability to build WPF apps on app center

### ISSUE THREAD

**Issue by AdamDiament** [microsoft/appcenter#1826]
**Describe the solution you'd like**
At the moment we have to upload a pre-built msi file to our app center for our wpf apps. It would be great if app center was able to build the app for us and run tests on git push, like it can for our native android and xamarin forms android/iOS apps.

**Describe alternatives you've considered**
I've tried adding a build step to our azure dev ops pipelines to build the WPF msi for us, alongside the server build/release pipeline that I have. I've struggled to get it to work. Assuming I eventually do so, it will still be harder to maintain than app center, and it would be great if our client app builds were all in one place.

**Comment by winnie** [comment]
Hey @AdamDiament thanks for the feature request! Unfortunately we don't have any short term plans to add Build support for WPF apps. What are you using to build your WPF app today?

You can use Azure DevOps to automate the build and release pipeline with the App Center deploy task. Here are the [docs ](https://docs.microsoft.com/en-us/appcenter/distribution/vsts-deploy) and a [sample app](https://github.com/diverdan92/DotNetConf2019) that might help you get started.

I understand the ideal scenario would be to manage everything in one place but hopefully using Azure DevOps and the App Center deploy task can help remove some manual steps.

(Tagging a duplicate Issue: https://github.com/microsoft/appcenter/issues/85)

**Comment by AdamDiament** [comment]
Thanks Winnie. At the moment I've got as far as building the WPF on azure dev ops where at least it's packaged in the file structure that matches the git repo. However I want to end up with a certificate signed Microsoft installer package that can be distributed to anyone with either a 32 or 64 bit system, so I still have to do that part. I wasn't aware of the app center deploy task so I'll give that a try. I will also investigate the docs you sent and the sample app. 

@DangerDon @timjamwoo  things to try to build the SMA.

**Comment by AdamDiament** [comment]
Hi @winnie thanks for your help. I've tried the suggested approach of adding a app center deploy task to my build pipeline. I'm having some trouble with it that the documentation doesn't touch upon. Can you help please? I get this message when the app center deploy task runs.

```
##[error]"{\"error\":\"Unable to extract attributes from file., Service id: e3f3f642-1137-4699-8e06-b10635e897cb\"}"
http response code: 422
```
https://gyazo.com/3d5d818dee425f3c6f8afe7249672ae1

Below is a screenshot of my build pipeline task setup. The "path to binary" option is confusing because it only mentions apks and aabs and ipa, suggesting this task is meant only for mobile apps. I put the path to where the exe file will be generated to see if that would work but no luck. In fact that exe file will only exist in the packaged build, not on the repo itself. As this is a build task it isn't giving me the option to access files in the build from the previous step.  Any help would be appreciated!

https://gyazo.com/a560d2597de26b9a39d240bc836a0d6b

**Comment by AdamDiament** [comment]
@winnie I have got this working now, thanks for your help. My issue was that I wasn't zipping up the binary.

**Comment by winnie** [comment]
@AdamDiament sorry I missed your earlier comment but glad to hear you got it working! I will leave this issue open so we can track interest around build support for WPF.
