### ISSUE TITLE
[Feature Request] Real-time analytics

### ISSUE THREAD

**Issue by huyphams** [microsoft/appcenter#183]
Hi Appcenter, I'm migrating from Fabric. Everything is great but I'm missing the real-time analytics so much:

- Ability to view the number of online users.
- Compare to the previous real-time metrics (day, week, month ago).

I can't find this feature on the [Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) or [Iteration Plan for March 2019](https://github.com/Microsoft/appcenter/issues/107), so are you going to add it?

Thank you for your hard work

**Comment by patniko** [comment]
We're looking at better ways to leverage existing Microsoft tools like PlayFab for this. While you wait on us I would highly recommend checking out playfab.com to get started. It's most commonly used with games, but can be used with any app.
