### ISSUE TITLE
Initialize Appcenter sdk in offline mode.

### ISSUE THREAD

**Issue by brijeshthakur** [microsoft/appcenter#1830]
**Initialize Appcenter sdk in offline mode**
In Outlook Mobile, there are couple of OEMs who are very strict about their network policy. Under this policy app should not make any network calls without User consent. Although App can't be used without allowing permission to make network calls but before that App should not make any network calls due to privacy reasons. 

Appcenter makes start service network call during the initialization of AppCenter sdk, which is against the OEMs policy. It's blocking the release for those OEMs. One workaround would be to initialize the sdk after user consent but that way we may loose crashes reported before that which we want to avoid.

**sample log**
```
{
    "logs": [{
        "type": "startService",
        "timestamp": "2020-04-26T04:15:50.065Z",
        "device": {
            "sdkName": "appcenter.android",
            "sdkVersion": "3.2.0",
            "model": "SM-G955U",
            "oemName": "samsung",
            "osName": "Android",
            "osVersion": "8.0.0",
            "osBuild": "R16NW",
            "osApiLevel": 26,
            "locale": "en_US",
            "timeZoneOffset": -420,
            "screenSize": "1080x2094",
            "appVersion": "4.0.0",
            "carrierName": "Verizon Wireless",
            "carrierCountry": "us",
            "appBuild": "237660",
            "appNamespace": "com.microsoft.office.outlook.wip"
        },
        "services": [
            "Crashes"
        ]
    }]
}
```

**Feature Request**
There should be an option/configuration as an API to initialize the AppCenter sdk in offline mode, so that AppCenter doesn't upload any logs in that mode but keep storing it on the disk. And when client turn off offline mode, Appcenter starts uploading logs to service.

**Comment by ljunquera** [comment]
Has this been resolved? I am not seeing offline crashes when devices get back online.

**Comment by DmitriyKirakosyan** [comment]
Hi @ljunquera , yes it should work. You can use [Disallow network requests](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#disallow-network-requests) API for disabling network request. While no data is sent in this mode, the crash reporter will still collect and store crashes.

If this doesn't work for you, please create a separate issue in the repository for the platform you're working with.

**Comment by ljunquera** [comment]
What I would like to do is try to ensure their delivery so when the network is connected, they will go. If it isn't they will wait until connected. Like the [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager) model.

**Comment by DmitriyKirakosyan** [comment]
Yes, that is how it works exactly. Events and crash reports are stored on device until the network is back online.
