### ISSUE TITLE
Better app filtering/search

### ISSUE THREAD

**Issue by lacostej** [microsoft/appcenter#1831]
**Describe the solution you'd like**

I would like the search app function to support exact match, and to have a way to for example search for names containing spaces. Right now it will search for apps containing at least one the words.

It should either return entries containing all words or support adding quotes to restrict search to relevant entries.

In other words to have a 

<img width="810" alt="image" src="https://user-images.githubusercontent.com/24282/80603991-6c1b9900-8a31-11ea-856d-58ab1171946f.png">

to return

only the relevant items

**Describe alternatives you've considered**
Remove spaces from our product names?

**Additional context**

**Comment by winnie** [comment]
Thanks for the feature request! I can see how this is annoying especially for users with a lot of apps. We don't have any immediate plans to improve this search functionality but we'll keep an eye out on this thread and post here if anything changes.
