### ISSUE TITLE
Add ability to identify each Analytic event by unique Id or user Id

### ISSUE THREAD

**Issue by scotthyphen** [microsoft/appcenter#1832]
**Describe the solution you'd like**
Currently, Analytics.TrackEvent() call can't tell from one device to others in App Center Analytics events view.  If I want to track one user's entire events, there is no way to sort or filter by that user.  So the Analytics.TrackEvent() call should add a parameter for unique identifier or user id or app instance id (but still tied to a user).  And add ability to filter or sort from App Center Analytics event view by the aforementioned Id(s).

**Describe alternatives you've considered**
Currently only way I think think of is to add a prefix "user:1234" in front of Event name in Analytics.TrackEvent() call.  Then from the App Center site, filter by "user:1234".

**Comment by winnie** [comment]
Thanks for the feature request! We don't currently support filtering by unique users within App Center but you can export your data into Application Insights which will export a unique user id field. You can then filter your data and create custom visualizations, such as user funnels, using this field.

Instructions can be found here: https://docs.microsoft.com/en-us/appcenter/analytics/export#azure-application-insights. 

I understand exporting to another product isn't an ideal solution. We will monitor this feature request for community interest to help us prioritize. Thanks!

**Comment by wh1t3cAt1k** [comment]
I am also interested in this feature, would be great to have that within App Centre.

This interests me from the perspective of license restriction compliance (for example, that a five-user license is not abused on too many devices).

**Comment by DanielWFrancis** [comment]
+1 also want, with this I wouldn't need Mixpanel for what we do.

**Comment by emathew80** [comment]
I also would like to request this as a feature

**Comment by moshowsJournal** [comment]
I also would like this to be implemented. At the moment, I use heap.io to track user's entire session and use AppCenter for distribution. It would be great to not have to move between different applications to manage these tasks.
