### ISSUE TITLE
Stable url for package managers

### ISSUE THREAD

**Issue by miccal** [microsoft/appcenter#1833]
[Homebrew Cask](https://github.com/Homebrew/homebrew-cask) is an extension of the package manager [Homebrew](https://brew.sh) that installs macOS apps, fonts and plugins and other non-open source software.

Homebrew Cask until recently had a Cask file for [Microsoft Remote Desktop Beta](https://github.com/Homebrew/homebrew-cask-versions/pull/8947), but it was removed because the [download url via App Center is not stable](https://github.com/Homebrew/homebrew-cask/issues/80779#issuecomment-614737874).

I was asked to [file an issue here about this](https://github.com/Homebrew/homebrew-cask/issues/80779#issuecomment-622096418).

Thank you.

**Comment by winnie** [comment]
Thanks for filing an Issue. Adding @ahdbilal who might be able to help.

**Comment by victorhooi** [comment]
@miccal I saw you closed this issue.

Does this mean the issue is fixed?

Or is there an alternative solution for https://github.com/Homebrew/homebrew-cask/issues/80779?

**Comment by dz85** [comment]
I wanna know the result too.  @ahdbilal Is the issue fixed?
