### ISSUE TITLE
Don't display missing symbol warning for jailbroken devices

### ISSUE THREAD

**Issue by techee** [microsoft/appcenter#1834]
Right I get the yellow warning for the current version of my app saying "Symbols are missing for app version..." even though I've uploaded the symbols. This warning comes most probably from the following crash which happens on jailbroken devices:

```
CoreFoundation
__exceptionPreprocess
libobjc.A.dylib
objc_exception_throw
Foundation
+[NSJSONSerialization JSONObjectWithData:options:error:]
SY.dylib
0x0000000102c30000 + 2510832
SY.dylib
0x0000000102c30000 + 2508980
SY.dylib
0x0000000102c30000 + 2485920
libdispatch.dylib
_dispatch_client_callout
libdispatch.dylib
_dispatch_continuation_pop
libdispatch.dylib
_dispatch_source_invoke2
libdispatch.dylib
_dispatch_source_invoke
libdispatch.dylib
_dispatch_main_queue_callback_4CF
CoreFoundation
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
GraphicsServices
GSEventRunModal
UIKitCore
UIApplicationMain
```

Notice that for SY.dylib there are no function names. This seems to be some library specific for jailbroken devices and there will probably be never any symbols for it.

I think that the warning regarding missing symbols shouldn't be displayed if it's because of a crash on a jailbroken device.

**Comment by winnie** [comment]
Hey thanks for filing an issue. We'll look into improving this scenario. In the meantime, you can ignore the missing symbols from the Unsymbolicated tab to remove the notification:

![image](https://user-images.githubusercontent.com/8868628/81078698-8d123d00-8ebc-11ea-9c63-99225a3e5352.png)
