### ISSUE TITLE
Send crash report right after the app crashed 

### ISSUE THREAD

**Issue by schriftgestalt** [microsoft/appcenter#1836]
When an app crashed it should show the crash report dialog right away. Otherwise user can’t send crash reports that happen when the app starts. 
I know that it is not save to run code in an app that just crashed. So it needs a small helper app that is launched from the crash handler. The Sparkle updater has a similar setup that launches an app that relaunches the main app after an update.

**Comment by winnie** [comment]
Thanks for the feature request! App Center can't display thhe dialog until the app is relaunched. We'll continue to monitor this request and look into any improvements.

**Comment by schriftgestalt** [comment]
> App Center can't display the dialog until the app is relaunched.

Why? If the dialog is in a helper app that should work.
