### ISSUE TITLE
dSyms removal, page for unit tests and push notifications

### ISSUE THREAD

**Issue by marekhac** [microsoft/appcenter#1841]
**Describe the solution you'd like**
- Possibility to remove unwanted dSYM files
- Dedicated page to analyze unit tests
- Push Notifications

**Comment by winnie** [comment]
Thanks for the feedback! Can you elaborate on your first point "remove unwanted dSYM files"? 

Are you looking for a way to delete an uploaded dSYM file or a way to ignore certain missing dSYM files?
