### ISSUE TITLE
Tool to export configuration of App/Build to a new app

### ISSUE THREAD

**Issue by ajaykn** [microsoft/appcenter#1846]
This was created on behalf of customer

**Describe the solution you'd like**
 I would like to see a tool created to export/copy configuration from an App/Build.

This would make it easier for those of us who build multiple platforms and environments using App Center from making mistakes during setup.
In our case, we have to do the work of setting up our distribution groups, certificates, passwords, builds, etc. over again for multiple apps.

A tool would really make this easier.

**Comment by nevano** [comment]
Any updates on this feature?  It would be very helpful to be able to save a yml version of the build in version control in case anything happens to the build config.
