### ISSUE TITLE
[REST API] Simple way to get error_groups data for analysis

### ISSUE THREAD

**Issue by ao-rix** [microsoft/appcenter#185]
Hi there!

I'd like to have a simple way to get all error_groups and corresponding errors for particular time range (24 hours in particular), using your http API. Here's the way I see it: I query for error groups, passing the timer ange `start`-`end` as params, and then for every error_group that i've got on previous step, i make another API request to get all errors for the same time range.

I tried to achieve desired result using current API endpoints, and got into several issues:
1. Using `/v0.1/apps/{owner_name}/{app_name}/errors/errorGroups` endpoint I made several requests and collected data for one app for last 30 days. I made one request for one day, using `start` and `end` parameters: `{start: '2019-03-01', end: '2019-03-02'}`. I expected about 90% of errors to be the same from day to day, with the same `errorGroupId` as a primary key, but instead all `errorGroupId` were different, as though every day has it's own unique set of errors, which are never repeated through 30 days.
2. Even if a have an `errorGroupId` it's hard to collect all related errors, because endpoint `/v0.1/apps/{owner_name}/{app_name}/errors/errorGroups/{errorGroupId}/errors` requires device model and os as required parameters. So to collect all errors for particular error_group i would have to get all os versions, all device models and than make a bunch of requests for all those parameters.

Some thoughts on REST API:
* I'd like to see more detailed description of api responses. For example, take a `count` in error_group - is it count of errors for all time or for selected period only? I can find out from data having made couple requests, but why don't you just write a proper documentation?
* I've tried to get data on devices and os versions for the same `errorGroupId` and I've got different `errorCount` number. What does it mean? Why do I get fewer errors If I split errors by device model, than if I split'em by operating system?
* I've made several queries with same start/end parameters for one `errorGroupId` during the week and I've got different `count` results. How can that be, that data for the day from the previous weeks is still changing?

**Comment by winnieli1208** [comment]
Hi @ao-rix,

Thanks for the feedback! Our APIs can definitely use some more documentation/details. I'll spend some time updating these. Regarding your issues:

1. Does the API return the error group IDs you see in the App Center portal? You can find the error group ID by selecting a group and looking at the URL. This might be because you're getting different new crashes from different groups day to day. 
2. I just checked and `/v0.1/apps/{owner_name}/{app_name}/errors/errorGroups/{errorGroupId}/errors` doesn't actually require the device and OS params (contrary to what it says in our API docs). If you remove the `&model=iphone&os=12.1.4` at the end of the API, it should return all errors for the specified group

As for the `errorCount` discrepancies, can you please start a conversation in the blue chat bubble in App Center? This will allow our support and engineering teams take a closer look. Thanks!

**Comment by ao-rix** [comment]
@winnieli1208, thank's for reply!

On 1: I'll take a look
On 2: Fields marked as required in swagger api interface, It's not possible to make requests from web interface without them: https://openapi.appcenter.ms/#/errors/Errors_ListForGroup. I'll try from shell

I will write here as soon as I get results based on your advices.

**Comment by winnieli1208** [comment]
hi @ao-rix - I just updated our page and removed the requirement for the device model and OS field for the API. Hope that helps!

**Comment by ao-rix** [comment]
@winnieli1208 sorry for being idle here, I've been a little bit busy )

I've taken a closer look at the data on the first question. Just to remind: I want to get subset of unique errorgroups, that happened during one day (24h), unrelated to their firs/last occurrence data.
So i run query to api endpoint `/v0.1/apps/{owner_name}/{app_name}/errors/errorGroups`, passing `start=2019-05-05` and `end=2019-05-06` parameters, and expect results to be something like the data from following imaginable query:
```sql
select distinct(errorgroupid) where error_date = '2019-05-05';
```
But instead, I get list of errorgroups that have their `lastOccurrence` at 2019-05-05. After sending 30 queries for each day in month, i can get 30 lists of errorgroups, each contains only unique `errorgroupid`s with `lastOccurrence` for particular day, not the list of whole errrorgroups that happened during that day.

Maybe I got it wrong about `start` and `end` parameters of the api query https://openapi.appcenter.ms/#/errors/Errors_GroupList? Is there a clear way to get the list of error groups i want?

**Comment by ao-rix** [comment]
Is there any update on this?
