### ISSUE TITLE
App Center Build support for Mac Catalyst apps

### ISSUE THREAD

**Issue by a2** [microsoft/appcenter#1850]
As a developer, I would like to build Mac Catalyst apps, or iOS apps that support Mac Catalyst, on App Center Build.

I was originally unable to build my iOS app (that supports Mac Catalyst) on App Center Build because it was looking for a macOS provisioning profile even though the App Center Build app target was configured for iOS.

Until this is resolved, my workaround is to set the following in an `xcconfig` file or through the Xcode project settings UI. (Note that the `default` evaluation operator is only supported by Xcode 11.4 and later.)

```
SUPPORTS_MACCATALYST = "$(OVERRIDE_SUPPORTS_MACCATALYST:default=YES)";
```

Then you can override it through the App Center Build environment overrides:

<img width="514" alt="Screen Shot 2020-05-08 at 7 20 58 PM" src="https://user-images.githubusercontent.com/241156/81456639-16e23480-9161-11ea-9bfb-6faa487ac94d.png">

**Comment by marcosrdz** [comment]
Any updates on this? It would be awesome to have support for automated Mac Catalyst builds.

**Comment by marcosrdz** [comment]
This has not been implemented.
