### ISSUE TITLE
Export full error information from App Center to Application Insights

### ISSUE THREAD

**Issue by TDishop** [microsoft/appcenter#1855]
**Describe the solution you'd like**
The export from App Center to Application Insights currently exports an error as a custom event named "HandledErrorLog", but contains almost no significant information about the error. The export process from App Center to Application Insights should include all error information including short name, stack trace, custom properties, and attachments. Without this information, I can create queries to show a users activities that lead to an error, but I have no idea what the error was (which is almost worthless). With this information, I get a complete picture of activities leading up to a specific error.

**Describe alternatives you've considered**
1. The manual approach is to create a query in application insights that lists a user activities in that lead up to an error and then try to find the error in app center based on timestamp. But the error may have occurred more recently for another user and therefore is difficult to find. This is completely manual process which is very time consuming.
2. Haven't tried this yet, but will likely try sending the same error to App Center and also directly to Application Insights. I imagine it will be difficult to correlate a directly sent error with content exported from app center.
3. Use a different tool for capturing analytics in the cloud.
4. Export content some different way, like blob or selecting download for particular error report.
Note: Received no adequate work-around for this issue from App Center team.

**Additional context**
![QueryShowingEventsWithHandledErrorLog](https://user-images.githubusercontent.com/1929661/81700648-8e98b380-942e-11ea-99c5-6728fdd0fa5d.jpg)
![AppCenterViewOfErrorReport](https://user-images.githubusercontent.com/1929661/81700656-92c4d100-942e-11ea-8540-e409275a3ae2.jpg)

**Comment by TDishop** [comment]
Has anything been done to improve the error content that gets exported from appcenter into application insights or do I need to continue with my errorAsEvent strategy which is less than ideal?

**Comment by manfredczujan** [comment]
Pls. can you imagine, how worthless these messages are in AppInsights, if you don´t provide the necessary information of the exceptions ?
What is your timeline for the Intra-MS-interfaces to enhance ? (also Azure Devops !)
thanks
Manfred

**Comment by mirekkukla** [comment]
I would love to see this implemented.

In the _very_ least, the data exported to application insights should indicate the `errorGroupId` or the `errorId` corresponding to the error event so that we can use the [export API](https://learn.microsoft.com/en-us/appcenter/gdpr/diagnostics-export#call-our-apis-for-specific-crasherror-information) to get the corresponding crash / error info.

**Comment by markbeij** [comment]
Please reopen

**Comment by annieEllenberger** [comment]
There is a "search by UserID" surfaced in App Center's UI... however, it doesn't seem to work, ever, for our applications :(  

@mirekkukla's suggestion is a good one! It would increase our ability to diagnose problems if the `errorGroupId` or `errorId` were included with the App Insights export.
