### ISSUE TITLE
Update plugin to allow a new app to be created as part of the method call

### ISSUE THREAD

**Issue by adrianhill102** [microsoft/appcenter#186]
**Describe the solution you'd like**
We are using this plugin in our CI pipeline. This means that interactive mode is not supported. We want to be able to create a new app and push it to App Center without having to create the app in the console first. This functionality is supported by the HockeyApp plugin.

**Describe alternatives you've considered**
At present out only option is to manually create an app with a specific name in the App Center console before pushing it from our CI pipeline.

**Additional context**
APPCENTER_APP_NAME - App name. If there is no app with such name, you will be prompted to create one

We are using the plugin in our CI pipeline so interactive prompts are not suitable

Can you update the plugin to allow a new app to be created as part of the method call?

**Comment by lumaxis** [comment]
@adrianhill102 Just to clarify, you're talking about our [fastlane plugin](https://github.com/Microsoft/fastlane-plugin-appcenter), right?

**Comment by adrianhill102** [comment]
Yes, the fastlane plugin. So in the sample below, 'app_name' would create the app without prompting the user.

appcenter_upload(
  api_token: "<appcenter token>",
  owner_name: "<your appcenter account name>",
  app_name: "<your app name>",
  apk: "<path to android build binary>"
)
