### ISSUE TITLE
Import all Telemetry data to App Insights

### ISSUE THREAD

**Issue by jeremy-bridges** [microsoft/appcenter#1866]
**Request:**
The App Insights export currently only includes events. It should include all errors and crashes, including unsymbolicated ones. These telemetry artifacts should import to the correct App Insights buckets (error -> exceptions-UserCode, crash -> exceptions-Unhandled, events -> customEvents). And, all properties should be brought over in the telemetry. 

**Alternatives we've considered:**
We've tried using the BLOB export and it doesn't work especially well. It is really meant for archiving. Not centralized alerting, which App Insights is ideally suited for.

**Additional context:**
We centralize our DevOps alerting and monitoring strategy around App Insights. We have Azure services and client-side apps to monitor. Since App Center is taking over the client-side space, it needs to talk the same language as App Insights to allow organizations to leverage each tool for what it does best (App Center for deployment and telemetry gathering, App Insights for monitoring and dashboards). We also manage this environment for multiple tenants. App Insights has more tools to segregate the telemetry for each of our clients. This allows us to contextualize during troubleshooting and prioritization.

**Comment by seb-bartholomew-amcs** [comment]
Sounds same as issue #339 which we would very much like - and have been waiting far too long to be - addressed too!
