### ISSUE TITLE
Show warning that Safari mobile view is required when registering iOS devices on iPad

### ISSUE THREAD

**Issue by joedEXL** [microsoft/appcenter#1871]
**Describe the solution you'd like**
When the my devices page is viewed on an iPad with the desktop view mode enabled, there needs to be a warning that iOS device registration will not work unless you switch to mobile view mode.

**Describe alternatives you've considered**
Support iOS device registration on iPad with either Safari desktop or mobile view mode.

**Additional context**
This issue has wasted a lot of time for our support team - a simple warning would have resolved the problem immediately.

**Comment by Mikilll94** [comment]
I encountered the same problem.
