### ISSUE TITLE
.Net core on test machines

### ISSUE THREAD

**Issue by namrog84** [microsoft/appcenter#188]
**Describe the solution you'd like**
dotnet core installed on the machines that run the tests

**Describe alternatives you've considered**
Rewrite some code in java or something else.

**Additional context**
I want to be able to call into a dotnet core library from my Appium Java Driver class files for Android testing.

We have a dotnet core library that handles providing data for our Android Appium tests and thus we need dotnet core installed on the mac/linux machines that run the appcenter tests.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @namrog84. Tapping in @Oddj0b for further information.
