### ISSUE TITLE
App Center distribute task - Azure DevOps - dSYM path field

### ISSUE THREAD

**Issue by ghost** [microsoft/appcenter#1883]
Hello!

I am actually working with Azure DevOps Pipelines to deploy an iOS app to App Center Service, and I would like to understand how can I send dSYM files to App Center Service.

I saw that App Center Distribute Task offers a dSYM path as input. How can I set up that one?

Could you help me, please?

Thank you for your attention!

**Comment by itsector-esanti** [comment]
Up ?
