### ISSUE TITLE
Support Expo React Native Apps in App Center

### ISSUE THREAD

**Issue by joemellin** [microsoft/appcenter#189]
**Describe the solution you'd like**
I would like to be able to build RN Expo apps in App center (this is the default way of making RN apps in the RN docs.

**Describe alternatives you've considered**
I have moved to building RN apps with the RN CLI instead

**Comment by zanechua** [comment]
Would like to leave a comment that building ejected Expo apps work in the AppCenter build process just that you might have to make a slight modification for the iOS builds.

Apparently the AppCenter team decided to hardcode the generation of source maps for iOS instead of relying on the `main` property inside the `package.json` file. This results in the failure of the generation of the source maps.

One solution would be to add a `index.js` script directly in the repo itself using the contents of the file listed in the `main` property of `package.json`

For my ExpoKit app. The file has the following contents:

```javascript
/* global __DEV__ */
import { registerRootComponent } from 'expo';
import { activateKeepAwake } from 'expo-keep-awake';
import App from './App';

if (__DEV__) {
  activateKeepAwake();
}

registerRootComponent(App);
```

Not sure why they decided to hardcore it to index.js or index.ios.js but that is the current case with regards to building Expo apps in AppCenter

**Comment by glittle** [comment]
When using the "Configure build" button in App Center, it simply says "We couldn’t find any React Native Android projects in your branch."

How can I get App Center to use the expo Reactive Native code?

**Comment by glittle** [comment]
Got a lot further by running "expo eject" to create android and ios folders.  Once committed, the App Center found them and allowed a Build to be created.

**Comment by nrajpurkar** [comment]
Glad you were able to get this working @glittle. At the moment ejecting Expo apps is the only supported way to build in App Center.

**Comment by firrae** [comment]
Is this something MS are looking to add @nrajpurkar? Considering it's the most likely way most people will begin developing (It is the default option in the React Native docs), and it offers likely the best local dev experience, it seems like something that should be supported.

**Comment by hermanthotan** [comment]
I create simple expo reactnative app, and not able to build in appcenter. After 'expo eject' it able to detect. When appcenter support expo.

**Comment by nrajpurkar** [comment]
Expo support did not make it into our iteration plan for this month. I'm interested into digging deeper into the use case here. Feel free to reach out to me via my email on my profile if you're available to chat a little more. Thanks!

**Comment by firrae** [comment]
@nrajpurkar I guess the simplest reason is the fact Expo makes developing React Native apps REALLY simple. Add on the fact that when you go to https://facebook.github.io/react-native/docs/getting-started the fist thing you are greeted with is official documentation guiding you to use the Expo CLI with CRNA being the second (non-default) tab. 

You, I and many others would likely be able to figure out that this isn't a completely React Native app pretty quickly, but to someone looking to put something together it's extremely simple and they might not care to dig further. There are weird things that come up once ejecting from Expo to a "bare Expo" app that someone without access to a Mac, or even without the know-how that someone who started out with the Expo cli would look at and just wonder why they would continue down this path just to use App Centre (I know I am, I don't own a Mac).

At the end of the day, Expo adds a layer of simplicity to getting small apps started. It is officially recognized as such and is the default tab in getting started with React Native. These 2 things alone would, in my mind, make it something of interest to get smaller devs, or devs who don't want extra hassle like me, to be able to use some of the toolings (specifically builds and testing) MS provides through App Centre. It's cool that Expo offers a build service for free, but I'd prefer to have a more dedicated resource. Maybe eventually the rest of App Centre (analytics, crash reporting, etc.) could  be brought over in some capacity (Sentry and Bugsnag work already) to allow the suite to work there, but building and testing are my 2 key areas of interest right now for my small app.

**Comment by alexkyse1** [comment]
I'm also really interested! It's a shame that it's not compatible.

**Comment by jphilipstevens** [comment]
We ended up first ejecting our app and now we are no longer on ExpoKit. It seems this is common practice from asking around our groups.

**Comment by firrae** [comment]
I ended up doing the same as @jphilipstevens for my previous projects, but as I'm about to start another couple of mobile projects I'm also circling back to this. Just having App Center even just know to eject it and then build RN like normal would be extremely helpful as I debug and build apps out.

**Comment by tpae** [comment]
@nilofer There's a clear need here, I think this would make App Center a lot more popular than it is right now. There's no documentation out there that supports Expo with CI/CD and publish to TestFlight or Play Store. Having this feature and closely integrating with RN would greatly benefit a growing community.

**Comment by flieks** [comment]
Indeed, also interested.
Currently using Expo AuthSession which works for the most part. ad-b2c is most important.
I will also try [this ](https://github.com/GSingh01/ad-b2c-react-native/issues/7) solution (with webview) but a truly native solution is better then webview of course

**Comment by rasck** [comment]
We could really use expo integration with app center! Hope you will integrate it with expo one day. I think a lot of react native projects gets started with expo these days, so it would be a good way to pick up new customers!

**Comment by maxxwellfirth** [comment]
@nilofer I too would like expo supported within app center. I've sent you an email to provide more detail 👍

**Comment by AdamDiament** [comment]
Yes please!

**Comment by nelsonvega** [comment]
Is there any plans to add expo support to appcenter?

**Comment by matteo-pennisi** [comment]
+1

**Comment by oliverwhk** [comment]
+1 for expo support to appcenter.

**Comment by lamaalqasem** [comment]
You should do something about it. It's clear that there's a strong need for this support.

**Comment by RWOverdijk** [comment]
I love appcenter as much as the next dev, but bitrise handles this perfectly right now. That might be an option until appcenter supports it?

**Comment by felisio** [comment]
+1 for expo support to appcenter. 💪

**Comment by amngupta** [comment]
+1

**Comment by keerthinathganjam** [comment]
+1 for expo support to appcenter.

**Comment by victorious85** [comment]
+1

**Comment by enriquecapellan** [comment]
+1

**Comment by saurabhCoder** [comment]
+1

**Comment by dsinclairmoore** [comment]
For those using Azure DevOps, you could use the Azure Pipelines to build the expo app [https://medium.com/@raghu1286/react-native-expo-android-ios-ci-builds-for-azure-devops-5458eb0b5e4a](url) and publish the build artifacts to App Center [https://docs.microsoft.com/en-us/appcenter/distribution/vsts-deploy](url).

**Comment by lostchopstik** [comment]
+1 especially with the RN docs directing you to use Expo

**Comment by s1116162** [comment]
+1

**Comment by Jonatthu** [comment]
Did app center team does not care about this topic or is it working on it? @elamalani

**Comment by flieks** [comment]
I also really need this feature. It would greatly simplify the current hack we have to implement to make AD B2C work, which is not stable (using expo sdk's)

**Comment by bhirave** [comment]
AppCenter pipelines outpeform many of app pipelines out there, so does EXPO too. we are definitely interested in AppCenter+Expo support. Expo is being widely recognized one stop dev tool for react-native projects. Interestingly AppCenter has Cordova (preview) available, so why not expo too 👍  we are about to start couple of major projects, and its bottleneck while choosing tech stack.

**Comment by lauratan** [comment]
+1

**Comment by Jonatthu** [comment]
There is a workaround, which is to build your expo app in Azure Devops and send the artifact into App Center, the only problem left would be supporting the SDK for analytics. But that would be on the expo community or app center team making a pull request on expo.

**Comment by Jonatthu** [comment]
https://expo.canny.io/feature-requests/p/support-for-application-insightsapp-center Please support this feature request if you want expo team to notice this. Also please App Center Team try to support this as well. Maybe contributing on this with a Pull Request.

**Comment by bhirave** [comment]
> There is a workaround, which is to build your expo app in Azure Devops and send the artifact into App Center, the only problem left would be supporting the SDK for analytics. But that would be on the expo community or app center team making a pull request on expo.

we have expo app in Azure repos. I mapped azure repos in AppCenter. I get following errors:
**Android**: No android project found
**ios**: package.json is missing (very strange, because there is package.json in expo app)

**Comment by wnz99** [comment]
+1

**Comment by thiagorpereira** [comment]
+1

**Comment by scottjferguson** [comment]
+1

**Comment by geydson** [comment]
+1

**Comment by imhazige** [comment]
+1

**Comment by ajsaule** [comment]
+1

**Comment by flieks** [comment]
+1

**Comment by bencalnan** [comment]
+1

**Comment by MiniMarker** [comment]
+1

**Comment by schempil** [comment]
+1

**Comment by LiamDotPro** [comment]
+1

**Comment by mmskvortsov** [comment]
+1

**Comment by pors** [comment]
+1

**Comment by volcano619** [comment]
+1

**Comment by krillehbg** [comment]
+1

**Comment by white-room** [comment]
+1

**Comment by stevefai** [comment]
Is the Bare workflow supported right now? I tried adding a build configuration for my repository but I get the error: `We couldn’t find any React Native Android projects in your branch.`

**Comment by lostchopstik** [comment]
> Are Bare Expo apps supported right now? I tried adding a build configuration for my repository but I get the error: `We couldn’t find any React Native Android projects in your branch.`

Yes. If your project has an android and ios folder, it should be recognized. I'm currently running with a bare workflow, no issues. I'm not entirely sure of what else App Center may be looking for when determining what counts as a "React Native" project.

**Comment by nandorojo** [comment]
Expo now allows native code to be added to any managed Expo app with the use of Config Plugins. Could this help add App Center support for Expo apps?

**Comment by Jonatthu** [comment]
I already gave up🙃

**Comment by flieks** [comment]
+1

**Comment by DaltonHarvey** [comment]
> +1

+1

**Comment by enesakin1** [comment]
+1

**Comment by willerrodrigo** [comment]
+1

**Comment by nandorojo** [comment]
I’m using Runway for my React Native releases, together with GitHub actions. I recommend it.

**Comment by BloodyMonkey** [comment]
+1

**Comment by firrae** [comment]
This is still not a covered case unless I've missed something.

**Comment by chancesmith** [comment]
+1

**Comment by solarisn** [comment]
+1

**Comment by nimishdm** [comment]
+1

**Comment by all-in-one-bravo** [comment]
+1

**Comment by crjacinro** [comment]
+ 1 !

**Comment by AnastasiaKubova** [comment]
Hi there! Thanks for your interest in the feature! Please use reactions instead of `+1`.

**Comment by RWOverdijk** [comment]
`+1` 

😇

**Comment by charleston10** [comment]
+1

**Comment by nirajhi** [comment]
+1

**Comment by musoxvi** [comment]
+1

**Comment by mandymichel** [comment]
+1

**Comment by dutradotdev** [comment]
+1

**Comment by leventleo** [comment]
+1

**Comment by ammarfaris** [comment]
🙏🏻 please add support for Managed Expo React Apps in App Center

**Comment by tmadej** [comment]
+1

**Comment by ssnyder-lm** [comment]
I find it incredibly common with Microsoft that they see incredible desire for a feature and instead of being customer focused they walk the other way!

**Comment by mrk-han** [comment]
At the bare minimum, it would be nice to be able to more easily support AppCenter Crashes and AppCenter Analytics out-of-the-box with the Expo Managed Workflow.

**Comment by RWOverdijk** [comment]
> At the bare minimum, it would be nice to be nice to support AppCenter Crashes and AppCenter Analytics out-of-the-box with the Expo Managed Workflow.

Use eas and [config plugins](https://docs.expo.dev/guides/config-plugins/) to link the deps _(might also need code mods, all links are there)_. Then share it with the community :)

> +1

Everyone else: +1 clearly doesn't work so just stop it. It has been 3 years, it's not going to happen. The upside is that expo application services works fine: https://expo.dev/eas

After making 3 builds I found the experience very pleasant. Maybe give that a go instead of waiting for daddy microsoft to act on some github comments.

**Comment by mrk-han** [comment]
@RWOverdijk  Being totally reliant on EAS is a bad thing, especially when some core functionality is hidden behind having a paid subscription service.


I'm not sure you can use "eas" and config plugins to link dependencies for the appcenter crash + analytics, have you done this before?  @RWOverdijk

**Comment by RWOverdijk** [comment]
> @RWOverdijk Being totally reliant on EAS is a bad thing, especially when some core functionality is hidden behind having a paid subscription service.

Sure, being totally reliant on _anything_ is a bad thing. At least eas can run locally and doesn't actually depend on anyone. But also the free tier is generous so it can be a real alternative to some. I haven't found any "hidden functionality" myself.

> **Edit** You cannot use "eas" and config plugins to link dependencies with a Managed App

I'm pretty sure you can. Mods allow you to change basically everything. You just need a custom dev client, but you can. Unless you consider a custom dev client to not be managed anymore, because that's not what that means. Take a look at some examples if you're curious about how. [RNFirebase has some decently advanced examples](https://github.com/invertase/react-native-firebase/tree/main/packages/app/plugin).

Also, you can be mad at me, give my comments thumbs down and disagree, that's fine. But I suggested a solution specific to your comment.

**Comment by mrk-han** [comment]
@RWOverdijk Mostly wasn't thrilled with your Daddy Microsoft comment, but thanks for the context.

Will look into config plugin with expo-dev-client to enable AppCenter Crash

**Comment by FRizzonelli** [comment]
Hi folks! I saw this issue and I tried to create my first expo plugin!

https://github.com/BelkaLab/expo-appcenter

I'm still trying it out and it's still WIP, any feedback is super appreciated! I've added only tested it appcenter-crashes and appcenter-analytics right now.

I tried it with eas build --local and it's working :)

**Comment by mrk-han** [comment]
AppCenter Test support would be critical as well, with Appium Javascript and Detox support if possible. 

See: https://github.com/microsoft/appcenter/issues/2446 and https://github.com/microsoft/appcenter/issues/262

These 3 things would enable Expo w/ React Native development to be a great experience within the Microsoft Ecosystem

**Comment by Eigilak** [comment]
Agreed

**Comment by thaiphan** [comment]
I was able to get Expo to run in App Centre by running `npx expo prebuild`

**Comment by chriszs** [comment]
I just went through the process of getting this to work and some of the comments here were helpful. Like others, I used `expo prebuild` (formerly `eject`), adding it to a `postinstall` hook that runs after `npm install`. I used a [more up-to-date fork](@armster/expo-appcenter) of @FRizzonelli's Config Plugin to add the SDK to the generated native code. I added an `index.js` with `registerRootComponent` imported from Expo so that source map generation could work. I added two lines to my post-install script to delete the debug signatures Expo signs Android apps with. Then I hit a snag when I decided to remove my native code directories from Git and got a "package.json not found" error on the iOS build configuration. Presumably it looks for the Xcode project in addition to package.json to know which schemes are available to build. So I added back the directories.

**Comment by jtvargas** [comment]
> I just went through the process of getting this to work and some of the comments here were helpful. Like others, I used `expo prebuild` (formerly `eject`), adding it to a `postinstall` hook that runs after `npm install`. I used a [more up-to-date fork](@armster/expo-appcenter) of @FRizzonelli's Config Plugin to add the SDK to the generated native code. I added an `index.js` with `registerRootComponent` imported from Expo so that source map generation could work. I added two lines to my post-install script to delete the debug signatures Expo signs Android apps with. Then I hit a snag when I decided to remove my native code directories from Git and got a "package.json not found" error on the iOS build configuration. Presumably it looks for the Xcode project in addition to package.json to know which schemes are available to build. So I added back the directories.

The link is not working
