### ISSUE TITLE
Allow testers to download app without signing up for appcenter account ( including auto manage devices )

### ISSUE THREAD

**Issue by thsbrown** [microsoft/appcenter#190]
**Describe the solution you'd like**
I want to allow testers to download my app without having to sign up for app center account. I also want said testers to be auto added to provisioning profile (like is done with automatically manage devices turned on)

**Describe alternatives you've considered**

**Additional context**

Seems like allowing both these buttons being turned on might be what i'm looking for.
![image](https://user-images.githubusercontent.com/2967721/54563579-c620e280-4986-11e9-94e8-e14f9714fa1b.png)

**Comment by botatoes** [comment]
Thanks for the suggestion! There's currently some limitations with automatically managing devices and making the group public. We're keeping a look out on how to bypass this limitation for the future when Apple makes updates to managing provisioning profiles.

**Comment by MaximePost** [comment]
To me this is not a suggestion but a blocker issue. This is possible in HockeyApp and should be possible in AppCenter.
We have tens of thousands of users without app center accounts for which it is not possible to create app center accounts.
As long as this is not fixed we can't migrate any of all our apps.

**Comment by marcomoscatiello** [comment]
is there any chance that this feature gets enabled again ? 
This is blocking us to distribute the app through public urls without forcing users to signup to Appcenter. 
There is a workaround at the moment but it's quite tedious .
How long will it take to get this feature released ?

**Comment by jackdewhurst** [comment]
+1 We would like to see this feature implemented too. Buddybuild handled auto provisioning of tester devices without requiring login long before they were bought by Apple. 

It's really the main disadvantage to using Appcenter at present.

**Comment by binaris-no** [comment]
Any tips on an alternative reliable (service) that also covers Android for distribution? HockeyApp did a great job regarding iOS device registration and ease of access/download, it was probably the main reason why we got on it.
