### ISSUE TITLE
Tasks  validateSigningRelease not found keystore

### ISSUE THREAD

**Issue by stephanoapiolaza** [microsoft/appcenter#1902]
I had the same trouble with any configuration that i did. I was following the next link https://docs.microsoft.com/en-us/appcenter/build/android/code-signing

* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file '/Users/runner/runners/2.170.1/work/1/s/android/app/marketnow.keystore' not found for signing config 'releaseSigningConfig'.

Build.gradle setting

signingConfigs {
		releaseSigningConfig {
			storeFile rootProject.file('app/marketnow.keystore')
			storePassword 'Abcd.1234'
			keyAlias 'marketnow-key'
			keyPassword 'Abcd..1234'
		}
        debug {
            storeFile rootProject.file('app/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
			signingConfig signingConfigs.releaseSigningConfig
            //minifyEnabled enableProguardInReleaseBuilds
            //proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

**Comment by stephanoapiolaza** [comment]
Solved change extension to .jks

**Comment by rossdonald** [comment]
I faced the same error myself and found the `.gitignore` file excludes keystore files by default. So this error might be caused by your keystore file not being included in your git commits. (your keystore is only on your local machine and not in git)

You can edit `.gitignore` and remove `*.keystore` or rename your keystore file to use `.jks` as jks files are not excluded in `.gitignore`

**Comment by fernan256a** [comment]
@andvalsol in most cases the project is not public, so I think you can upload it to your repo
