### ISSUE TITLE
Sparkle multiple RSS Feeds

### ISSUE THREAD

**Issue by davidev-b** [microsoft/appcenter#1906]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidev-b** [comment]
We are using App Center with Sparkle, which works fine. However, all public releases will be listed in the RSS feed for Sparkle.

Is it possible to get multiple RSS feeds (different API request), so I can create public development group, so people can choose in the App wheather the updates is getting fetched from development group or from main group.

Currently only one RSS feed is available and I can not seperate any releases.

**Comment by adirh3** [comment]
Hey,
I also could greatly benefit from something like this, any update?

Thanks!

**Comment by dexterleng** [comment]
Hi! I would love this feature as well.
