### ISSUE TITLE
Please configure the Appcenter apps to work with Android Work Profile

### ISSUE THREAD

**Issue by mwe-microsoft** [microsoft/appcenter#1908]
**Describe the solution you'd like**

Please configure the apps to work with Android Work Profile

https://microsoft.sharepoint.com/teams/meconnection/SitePages/Android-App-publishing-for-use-with-Work-profiles.aspx

For me it is Outlook for Android and Teams Alpha, Beta, Pilot, Dogfood for Android.

Likely it should be configured for all apss

Thank You

**Comment by kattamudi-karthik** [comment]
Hi Team 
We are also looking for similar feature .
