### ISSUE TITLE
Import/Export environment variables for Android iOS

### ISSUE THREAD

**Issue by mufaawan** [microsoft/appcenter#191]
**Add feature to import/export environment variables for Android and iOS**

**Manually added same list of environment variables for both Android and iOS**
If an app that is available for multiple platforms, that app must use same environment variables, for every platform I have to make list of environment variables one by one. it would be great to add some option to make an option to import from file or from any other platform for which I have updated the list of environment variables.

**Comment by nrajpurkar** [comment]
Referncing #376 as a similar issue

**Comment by twom** [comment]
After accidentally browsing back before saving .the 20 environment variables.. I agree with this feature request. 

Even creating the first build can be painful if you use a lot of environment variables. Typically an .env file is already available...

Or maybe an autosave feature like Word would have helped me ...

**Comment by sclavijo93** [comment]
This would be nice to have!
