### ISSUE TITLE
Export visualized test run results from web

### ISSUE THREAD

**Issue by C0D3On3** [microsoft/appcenter#1910]
**Describe the solution you'd like**
Currently, I don't see an option once logged into appcenter to export the test run reports as a pdf or doc file.  The report is visualized already via the web UI so I'd like to just export that report rather than going through the API's, getting the raw data, then writing a utility to visualize that report.

**Describe alternatives you've considered**
Writing a utility to visualize the raw data provided via the APIs.
Write a web crawler to "print" each page of the report via pdf.

**Additional context**

**Comment by Adam-Langley** [comment]
Any updates on this?
Appcenter throws the reports away after a predetermined time, I also want to store these results.
