### ISSUE TITLE
Uploading aab file to appcentre

### ISSUE THREAD

**Issue by Sushmagangaiah** [microsoft/appcenter#1928]
Hi All,
Can anyone help me in uploading aab file to appcenter.
Thanks in advance

**Comment by phillipleblanc** [comment]
@Sushmagangaiah You can follow the documentation here to upload your AAB to Google Play with App Center: https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay#publish-your-aab-to-the-google-play-store
