### ISSUE TITLE
Allow Multiple Build Configurations On a Branch

### ISSUE THREAD

**Issue by paulcsilver** [microsoft/appcenter#1929]
**Describe the solution you'd like**
It would be nice to be able to apply multiple build configurations to a single branch, to allow different targets, distribution destinations, build settings, signing credentials, provisioning profiles, etc.

**Describe alternatives you've considered**
An alternate solution is to have multiple "copies" of the same branch, configured in the desired manner. But, that could quickly generate too many branches that need to be kept up-to-date and managed.

**Additional context**
We have a React Native Project, and our iOS and Android projects define multiple targets/variants. We would like to be able to build and distribute those targets/variants from a single push to a specific branch.

**Comment by AndresTapiero72** [comment]
I would like this issue
