### ISSUE TITLE
Ability to publish apps to InTune Work-Profile Managed iOS/Android devices

### ISSUE THREAD

**Issue by georgge13** [microsoft/appcenter#1934]
**Describe the solution you'd like**
At the moment, LOB Application will only work on device administrator, and apps are not visible in the company portal for installation. For, Android for work sole source for application is manage google play store hence we need to add the applications as private app in managed google Play store if the application is not published.

**Describe alternatives you've considered**
Manually publish apps as described in the documentation links below. No end-to-end automation capabilities that App Center offers i.e. build apps -> publish app-> app is available to install on InTune Managed devices.

https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work#managed-google-play-private-lob-apps
https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-ios

**Additional context**
[Case #:20965144] -  Appcenter App published to InTune does not show in company portal

**Comment by Ajinkya1511** [comment]
Is there any way to update the Private apps in Managed Google Play Store from the Visual Studio Appcenter?

**Comment by mro-pbraswell** [comment]
This is a crucial requirement for our organization. We only use Managed Play Store Apps for our in-house developed Android apps and the lack of this feature prevents us from building an end to end process with App Center.

**Comment by spoelstraethan** [comment]
See #2304 for a request for the same problem that is being bumped periodically to keep it on the radar.
