### ISSUE TITLE
[Appium Test] Support to mock services 

### ISSUE THREAD

**Issue by AndresTapiero72** [microsoft/appcenter#1935]
**Describe the solution you'd like**
We would like as a company to have support for mocking services in the VM side by side with Appium and that the devices can connect to the mock server running in the VM.

**Describe alternatives you've considered**
1) Allow communication between the virtual machine and the real device by enabling a specific port.
2) Allow testing with emulated devices.

**Additional context**
I'm currently using Wiremock Server with Appium running in the VM, and making the test device point to the server's IP, but the Wiremock server does not receive any request, then our test fails.
We're trying to migrate to AppCenter, but it's very important for our company to run the tests with mocked services and to have a universal way of mocking services that will work with any platform without a custom implementation for each one, as Appium provides for tests.

**Comment by xamadev** [comment]
I use the [WireMock.NET](https://github.com/WireMock-Net/WireMock.Net) server in my Xamain.UITest project for mocking a REST-API. I can access it via localhost from iOS simulator or via 10.0.2.2 from Android emulator. Am I understanding this issue right, that's there's no supporting for mock server in UI tests at the moment?

**Comment by AndresTapiero72** [comment]
Yes @xamadev, If at that time I could not "mock-up" my application services because I had no support from AppCenter.

Tip, when you have 1 test, use the 7 days that you get for free and try it.

Note: WireMock.NET server address in AppCenter will be different from your localHost

**Comment by GerardKrupa-Cap** [comment]
Did anything happen with this? The ticket is closed as 'completed' but I've tried using WireMock (Java) and passing the IP address of the build agent to the mobile app using react-native-launch-arguments but it just times out making the connection suggesting there are firewall rules to prevent access. It's less than ideal having to either test against a production service or having to expose an internet-facing mock service to test against.

**Comment by IlyaBausovAkvelon** [comment]
Hi @GerardKrupa-Cap,
Currently, we don't support this feature and there are no plans to implement it in the foreseeable future.
