### ISSUE TITLE
Default build settings at the app level

### ISSUE THREAD

**Issue by cruinh** [microsoft/appcenter#1936]
**Describe the solution you'd like**
I'd like to be able to specify a build configuration (or better yet a set of them) for an app as a whole, which can then be applied to branches of that app's codebase.  I'd then like to be able to choose to override, or not, individual build configuration options on a given branch.  

Alternatively, if we could remove and re-clone a build configuration without losing the build history on that branch, that would help a lot (and I imagine may be easier for you all to implement?)

**Describe alternatives you've considered**
I don't think there are any alternatives that would 100% solve the problem (described below), but we've tried to mitigate difficulties by leaving as much build configuration as possible in our build scripts, by instituting policies on our team to not keep branches alive for any longer than necessary, and by just being very careful any time a global change has to be made to multiple build configurations.

**Additional context**
I'd hope you'd ask specifically for the problem I'd like solved, so I'll put that here.  ;)  The actual problem I'm having, which I think the above would solve, is that I work with a team of developers on multiple apps.   The devs will often start branches to implement new features, or to try fixing bugs, and may want to create builds in AppCenter to confirm that their changes didn't break the build.  This results in many branches, each with a copy of the build configuration.   Whenever we have to make a change to the build configuration, we often have to make those changes on most, if not all of our active branches to keep everything in sync.  Since we can't just remove and re-clone the build configuration without losing the entire build history on a branch, it becomes a lot of manual work to update every active branch individually, and we often find ourselves missing something.  Build configurations get out of sync.  We try to mitigate this by making sure to delete any branch as soon as it isn't needed, but that hasn't been enough.

**Comment by cantide5ga** [comment]
+1

**Another use case:** 
My current release pipeline design is based on feature branches off of master.  Once the PR passes a review, an app is built and distributed internally for verification of that specific branch.  In the case of binary distributions, branches in App Center need to be pre-configured as builds for ad-hoc branches cannot be programatically kicked-off and require manual steps to at least clone an existing configuration.

**Alternatively** (in my case) exposing through the api/cli the ability to clone configurations might be a good stop-gap.

I'm open to rethinking our automated pipeline if anyone wants to share how they are doing something similar or point to where this functionality might already exist.
