### ISSUE TITLE
Capture and display screen resolution and DPI like you do Device name

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter#1944]
**Is your feature request related to a problem? Please describe.**
We have a minimum recommended resolution for out WPF Application but we do not fully know if people are meeting this or this may need to increase/decrease to better satisfy our customers. Obviously other platforms like on iOS you will know this from the device but not for dot net where there could be any resolution device being used.

**Describe the solution you'd like**
If it could store device properties like it does for the kind of model of pc it tries to currently. But expand this to the primary monitor resolution and DPI.

**Describe alternatives you've considered**
Recording this as a manual event ourselves.

**Additional context**
I think it would be a useful built in feature as like I say you get this with other platforms but not on windows.

**Comment by Jamminroot** [comment]
Since that's more of a backend\portal feature request (UI for Screen Resolution), I'm moving this WI there

**Comment by james1301** [comment]
Is this going to be reviewed?

**Comment by manfredczujan** [comment]
Is this going to be reviewed?
thanks
Manfred
