### ISSUE TITLE
Multi Instance of AppCenter in a multiprocess app.

### ISSUE THREAD

**Issue by Zornikachu** [microsoft/appcenter#1946]
Hello,

I have a SDK that I want to monitor crashes with AppCenter.
In my test I created two App Project on AppCenter.ms

I integrated my SDK in a test App with AppCenter SDK as well.

Both my SDK and test App Instantiates AppCenter with each their own secret key.

After a few test I see that the app that integrates the SDK can report crashes from the SDK and the SDK reports crashes from the test App. 

Solution : 
Is it possible to configure the crashReportFolder name with the application PackageName so that each instance of AppCenter look for reports regarding its own crashes ?

-> SDK Crashes report in a error.com.Sdk.Package.name folder
-> App Crashes report in a error.com.App.package.name folder

each instance of the AppCenter SDK would only send what their respective folder contains.

Thanks in advance

**Comment by zlnaga** [comment]
Any update for this so far?
