### ISSUE TITLE
Bitbucket API Migration

### ISSUE THREAD

**Issue by mike14u** [Microsoft/appcenter#195]
**What App Center service does this affect?**
Bitbucket API / connecting to repositories

**Describe the bug**
We experienced yesterday down time of Bitbucket APIs (reached limit) without us doing anything. (was also fixed later that day)

**To Reproduce**
We had no leads how it happened

**Additional context**
Bitbucket will be migrating their APIs soon:
[https://developer.atlassian.com/cloud/bitbucket/bbc-gdpr-api-migration-guide/](https://developer.atlassian.com/cloud/bitbucket/bbc-gdpr-api-migration-guide/)
This could be of help.

**Comment by nrajpurkar** [comment]
thanks for bringing this up @mike14u. Are you still seeing any issues related to Bitbucket APIs? We'll make sure we are squared away from our end on the APIs we call 😄

**Comment by mike14u** [comment]
No longer experiencing it as of the moment, thanks @nrajpurkar, closing the issue.
