### ISSUE TITLE
Amazon FireOS / Fire Tablet device support 

### ISSUE THREAD

**Issue by tamirh** [microsoft/appcenter#1950]
**Describe the solution you'd like**
The [current list](https://docs.microsoft.com/en-us/appcenter/test-cloud/devices/android) of supported devices for App Center testing has a few very old and outdated Amazon Kindle devices.

Would it be possible to add support for some of the newer devices? EX:
FIre HD 10 (9th gen) - KFMAWI
Fire HD 8 (8th gen) - KFKAWI
Fire HD 8 (10th gen) - KFONWI

**Comment by alexanderdp** [comment]
I would like this feature added as well.
