### ISSUE TITLE
Unable to upload APK that doesn't have App Center SDK integrated

### ISSUE THREAD

**Issue by Pulcifer** [microsoft/appcenter#1956]
We have attempted to upload multiple flavors of our app and continually receive "Error: Loading release id failed: A problem occured while extracting your app. (Correlation ID: xxx)". We have attempted to manually sign APKs and using Studio to generate a signed APK with both a debug.keystore and a custom one. Is there a setting we are missing to allow uploads of an APK that doesn't have the App Center SDK integrated into the app or something special the app center is looking for inside the APK?

**Comment by dokun1** [comment]
As an aside, we've had luck uploading `.ipa` files without the SDK integrated into an app. It seems weird that this is localized to Android.

**Comment by RAM237** [comment]
> As an aside, we've had luck uploading `.ipa` files without the SDK integrated into an app. It seems weird that this is localized to Android.

I am having the same issue with `.ipa` right now.

**Comment by Pulcifer** [comment]
Just to provide closure on the issue we were seeing with the .apk in App Center. It turned out to be a missing version code and version  name in the final manifest.

Hope this helps someone.

**Comment by NaagAlgates** [comment]
I agree with @Pulcifer . In my case, I was passing the variable for versionCode & versionName. Those variables were null because the core logic was commented on. Once I cleared it, the problem was resolved.
