### ISSUE TITLE
When deleting HockeyApp Owners should be removed from App Center Admins

### ISSUE THREAD

**Issue by gregwoodsit** [Microsoft/appcenter#196]
**What App Center service does this affect?**
Distribute > Groups

**Describe the bug**
We were a HockeyApp Organisation and last year had 2 users who were Owners and have now left. 

The users have been deleted from HockeyApp but are still in the Admins group in App Center.

**To Reproduce**
1. Go to Organisation > People > Collaborators
/people/collaborators

**Expected behavior**
If an owner has been deleted in HockeyApp they should be removed from App Center

**Comment by derpixeldan** [comment]
To better help you, please reach out to us via support (blue button in the bottom right corner).
