### ISSUE TITLE
[iOS] - Allowing install pod from private podspec via ssh

### ISSUE THREAD

**Issue by pavelreva1998** [microsoft/appcenter#1960]
**Describe the solution you'd like**
I have a development pod, which is using ssh URL in the source to the repo.
When I try to build the project via AppCenter it can't be installed, cause of the ssh key(fair enough)
So, it would be nice if somewhere in the AppCenter it would be possible to generate ssh key and add it to Azure DevOps.

**Additional context**
Azure DevOps as a repository holder

**Comment by pauluhn** [comment]
My workaround using post-clone script:

`sed -i '' -e 's/ssh_string/https_string/g' Podfile`
