### ISSUE TITLE
Check for valid App Store credentials at beginning of iOS build instead of end

### ISSUE THREAD

**Issue by Fammy** [microsoft/appcenter#1961]
**Describe the solution you'd like**
The credentials used for the App Store connection seem to expire every 30 days or so. If don't actively check, I usually find out after a 10-15 minute build that distributes to Test Flight. Have the build failed at the beginning if those credentials are missing or expired.

**Describe alternatives you've considered**
I could make it part of my process to check before starting a build, but that wouldn't cover the case where builds are triggered from git commits.

**Additional context**
Screenshot of the error message when credentials have expired
![image](https://user-images.githubusercontent.com/232259/90183728-fccc7980-dd81-11ea-8aab-561e574f16f7.png)

**Comment by akempe** [comment]
Or allow distributing to a failed target. Right now it prevents you from doing this if you've already tried (regardless of the initial attempt's success).

But we all know effort is being wound down on AppCenter, so I wouldn't expect much.

**Comment by jjhampton** [comment]
This feature is sorely needed. I have multiple builds, all of which get all the way through the build/distribute process, only to fail at the end when my credentials are somehow expired or need re-authentication.  It's a huge waste of time to run builds and only when they fail, see that your credentials need re-authing.

**Comment by yonatanganot** [comment]
It could be solved using [App Store Connect API Key](https://github.com/fastlane/fastlane/pull/17238) feature, which was released in fastlane v2.160, and it is already available in AppCenter.
