### ISSUE TITLE
how can I know statistics on the usage of the android version?

### ISSUE THREAD

**Issue by pengcao1** [microsoft/appcenter#1975]
Hi guys,

As the title,
May I know that is there a way to statistic the android version?
eg:
```
Android 5.0:  6.1k devices
Android 9.0: 503 devices.
```
etc..

**Comment by DmitriyKirakosyan** [comment]
Hi @pengcao1,

Thank you for getting in touch with us!

There is `OS Distribute` section in the `Top devices` section, which, I believe, does what you're searching for:
![Screen Shot 2020-12-28 at 15 46 32](https://user-images.githubusercontent.com/536497/103215245-dd467f80-4923-11eb-9676-8f33f15a13c4.png)

Please let me know if it works for you.
I'm sorry for such a late reply.
Thanks.

**Comment by pengcao1** [comment]
@DmitriyKirakosyan 
Thank you, 
I have found those informations, but, only top 4 devices are listed, and I don't know total number of them,
