### ISSUE TITLE
Element is visible by the UI but not by automation and an error "center not on screen" displays (iOS Only, Xamarin.UITest)

### ISSUE THREAD

**Issue by Moshex** [microsoft/appcenter#1977]
I have an issue with the application that I am doing automation for using Xamarin.UITest. The issue that I will run into sometimes is with an element being visible on the UI but not able to be interacted with via automation code. When I do an app.Repl(); for the element I get in parentheses "center not on screen" for the element. I have only experienced this issue with iOS I have never seen the issue on Android. The application I am automating is a Xamarin Forms application that uses XAML files.

if anyone can help me with this in 2 ways, is there anything I can do via automation code to still interact with the element despite it having this issue? 
OR
is there something that I can tell the developers of this project to do in order to fix the UI so that the issue does not occur?
any insight as to why this happens and how to work with it is much appreciated.
Thank you,

![Screen Shot 2020-09-01 at 1 11 59 PM](https://user-images.githubusercontent.com/6087936/91896331-e6fdf600-ec55-11ea-965b-8b132d5bfbbd.png)

**Comment by evgenyvalavin** [comment]
+1. Cannot perform App.Tap on UIButtonElement. The button is visible on the screen and also has "(center not on screen)".

**Comment by evgenyvalavin** [comment]
> +1. Cannot perform App.Tap on UIButtonElement. The button is visible on the screen and also has "(center not on screen)".

Solved it. Seems like my button was not enabled for perfoming app.Tap().

**Comment by Moshex** [comment]
in my cases, the button is enabled so that does not seem to be the issue.

**Comment by Moshex** [comment]
Why was this close? I still don't have an answer to my question @nikita-bykov Can I please get some help on this issue?
