### ISSUE TITLE
Migrating Push to Azure looses lots of data

### ISSUE THREAD

**Issue by K232** [microsoft/appcenter#1978]
This issue tracker is named as feedback page for [Migration document](https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) from John Wargo. So I just want to let you know, but it's not an issue, at least not for you :-( 

With Azure Push there were lots of data to retrieve after the push was sent, e.g. how many devices were reached. Now, with Azure Notification Hub, it seems that we have to go for the "Standard" Plan which is 200$ per month! That's a large cost increase for us, from 0$ per month to 200$ per month. 

Of course it was great to have it for 0$ in AppCenter, and I would not expect this for a free service. I have no problems with the Basic-Plan for 10$ per month. That's a reasonable price which i would like to pay. But I need to get these notification details via API, and I don't understand why this should not be available for 10$ per month. I'm sure the data is available on your site also for the free and the basic plan, it's just the opening of the API for users where you charge users 190$ per month 👎 Of course, Standard has some more features, but I don't need them. And the one "feature" I need, is not really a feature, it's just setting the "supply the notification id to the customer" from "false" to "true".....

**Comment by tjsomasundaram** [comment]
@K232, we are sorry you are having issues with the migration to Azure Notification Hubs. To your point on telemetry, it is only available on the Standard tier for several reasons, including the fact that the service does not store the telemetry for namespaces on other tiers, so it is more than a matter of exposing available data.
If there is any way the Azure Notification Hubs team can assist in your migration (other than pricing), please let us know!
