### ISSUE TITLE
Email notification for new unsymbolicated crashes

### ISSUE THREAD

**Issue by ladislavklinc** [microsoft/appcenter#198]
It would be great if I could be emailed when new unsymbolicated crashes come in. Right now I have to manually check every once in a while to see if there are unsymbolicated crashes and upload symbols then.

**Comment by amchew** [comment]
Thanks @ladislavklinc for the feature request! We'll discuss this internally and get back again. fyi @winnieli1208

**Comment by akoshkarov** [comment]
Hi, any updates on this request?

**Comment by winnie** [comment]
Hi @akoshkarov - no updates. We're still evaluating this feature along with others. Tagging #1223 as a duplicate.
