### ISSUE TITLE
Add more context to failed build email notifications

### ISSUE THREAD

**Issue by rolfb** [microsoft/appcenter#1981]
When a build fails it would be great to get the following information:

- The error message if identified.
- A button to start rebuild, preferably without having to re-authenticate – especially if the error was due to network connection timeouts when getting third parties
- Which platform the build failed for which is currently not in the email and it's very relevant when working with React Native. This is also relevant for success notifications.

This was prompted by getting the following two emails today which had me confused:

```
(app name)
  | releases/qa
Build #170 succeeded
Duration: 7 minutes 17 seconds
```

and

```
(app name)
  | releases/qa
Build #170 failed
Duration: 12 minutes 43 seconds
```

**Comment by Buthrakaur** [comment]
re "The error message if identified." - it would be great to have environment variable for build scripts too

re "Which platform the build failed" - I just named my apps according to the platform e.g. "MyApp Android" / "MyApp iOS"

**Comment by rolfb** [comment]
> I just named my apps according to the platform e.g. "MyApp Android" / "MyApp iOS"

@Buthrakaur That's one way to do it, but I'd rather not have "implementation" details which are available elsewhere in titles.
