### ISSUE TITLE
Uploading a file along with crash log

### ISSUE THREAD

**Issue by madhus1025** [microsoft/appcenter#1983]
**Describe the solution you'd like**
 A feasibility to add a log file to the crash report, so that the developer while looking at crash log and the app log can debug it better

**Describe alternatives you've considered**
Other than reproducing the crash locally we do not have any other option, most of the times wouldn't be able to reproduce the crash locally.

**Additional context**
As you know the analysis of few crash logs takes lot of time, most of the crashes are unfixed because there isn't much a developer can understand and if we attach the apps log till then to that , it would be very helpful

**Comment by ShreyaA** [comment]
We would find this feature highly useful as well.

**Comment by cskristof** [comment]
There is an attachment feature available for AppCenter: [Add attachments to a crash report](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#add-attachments-to-a-crash-report).

**Comment by ShreyaA** [comment]
We require a feature that enables us to capture data (logs) at the time when the crash occurs. (Since the upload can occur a while after the crash does.) Have submitted a pull request for the same.
