### ISSUE TITLE
Add Feature:  Upload Local User/App Build file to AppCenter.

### ISSUE THREAD

**Issue by alexanderdp** [microsoft/appcenter#1985]
**Describe the solution you'd like**
Add more value to AppCenter!
Add Feature:  Upload Local User/App Build file to AppCenter to avoid wasting time trying to diagnose why remote builds are failing. (Mostly because of trying to script builds to match local machine settings! It's redundant.)

**Describe alternatives you've considered**
My alternative is NOT to use AppCenter. It excessively delays productions because of redundant troubleshooting. If it builds locally and can be uploaded directly to stores for test distribution, why use AppCenter at all?

**Additional context**
I can see some use for AppCenter organizing apps and test users, but losing precious time doing my work twice is counter intuitive and costly.

**Comment by ivankostic85** [comment]
@alexanderdp You can upload your application binary package to App Center to distribute it. If that what you are trying to do.
https://docs.microsoft.com/en-us/appcenter/distribution/uploading#distributing-the-package
