### ISSUE TITLE
Equivalent function for didReceiveMemoryWarningInLastSession

### ISSUE THREAD

**Issue by TLiu2121999** [microsoft/appcenter#199]
**Describe the solution you'd like**
We need `didReceiveMemoryWarningInLastSession` to calculate the app crash metrics. 

**More Information**
I talked with troubleshooting team, they said the replacement in AppCenter is ` - (BOOL)isAppKill`. 
However, that's not entirely equivalent to `didReceiveMemoryWarningInLastSession`, because ` - (BOOL)isAppKill` indicates not only memory warnings, it checks if a crash report contains the SIGKILL symbol which generally indicates that the app was killed by the OS, and there are multiple reasons like:
- high memory usage (likely after receiving the low memory warning)
- app kills by the user
- app kills because the app does not have certain permissions and the dev forgot to check
- other reasons...

**Problem that we have**
Problem is we need to get the crashes that was only caused by memory usage/warnings. 
If they are mixed with "App kills by the user", then we can't use it any more. 
This will be a very big gap for us since we have a large DAU and the tracking each crash reason is very important to us. Without this metric we can't fulling migrate to AppCenter.

**Solution we need**
We need to keep the functionality of `didReceiveMemoryWarningInLastSession`;
Please provide an equivalent function for it in AppCenter so we can different the crash reasons.

**Comment by winnieli1208** [comment]
Hi @TLiu2121999 thanks for the request. This is something we are looking to support. I will update this thread when I have more details.

**Comment by lumaxis** [comment]
Related to https://github.com/Microsoft/AppCenter-SDK-Apple/issues/1406

**Comment by winnieli1208** [comment]
This feature was shipped in the latest SDK release. Closing this issue.
