### ISSUE TITLE
How to enable v2 scheme android signing

### ISSUE THREAD

**Issue by Nikosmonaut** [microsoft/appcenter#1990]
**Describe the solution you'd like**
I would like to be able to select the v2SigningEnabled option to sign builds.
Because v1 scheme is known to be insecure and v2 will be mandatory for android 11.

**Describe alternatives you've considered**
Use gradle signinConfigs. But unlike text files I'm not sure to be able to upload the keystore as env varialbe and restore it with an appcenter-pre-build script.

**Comment by lz233** [comment]
I also encountered the same problem on Android 11, and finally I solved it by modifying the gradle configuration.

This is my configuration: https://github.com/lz233/OneText_For_Android/blob/master/build.gradle

It should be noted that you need to enable "My Gradle settings are entirely set to handle signing automatically" in appcenter.

**Comment by Nikosmonaut** [comment]
Because you keep your keystore in source code then yes it is possible.

I think I've just found the solution though. To use gradle signing config AND not keeping the keystore in source code.

```
openssl base64 -A -in keystore.jks
```

It is in fact possible to store the keystore as text string. Keep it in env variables et restore it on every build with app center build scripts.

Thanks @lz233

**Comment by tdekker** [comment]
We also updated our `targetSdkVersion` to `30`. App Center has no settings for controlling the signature version, like Android Studio does. Publishing to the Play Store does not work anymore in this case. It rejects the binary.
<img width="477" alt="Schermafbeelding 2021-03-23 om 08 44 56" src="https://user-images.githubusercontent.com/9843946/112112703-22dab780-8bb6-11eb-9944-7260eb670d4d.png">

**Comment by pives** [comment]
+1

**Comment by ptsiogas** [comment]
+1

**Comment by jst7-1230** [comment]
Anyone working on this issue yet?

**Comment by nicolgit** [comment]
I have the same issue here with a xamarin forms application I have to upgrade to Android 11 within next november **(last month Google accept apk compiled for Android 10)**

https://developer.android.com/distribute/best-practices/develop/target-sdk#pre11 

any update?

**Comment by barvii** [comment]
tl;dr:
Try to re-upload existing keystore in your AppCenter build configuration. It helped in my case.

I had a conversation with AppCenter Support. Looks like they have fixed the issue and now they do sign with signature v2+.
For existing projects in order to make these changes work, you have to re-upload existing keystore in your AppCenter build configuration.

**Comment by ea-orbital8** [comment]
In my case, re-uploading the keystore did not work. Instead I had to delete the build configuration for the branch and re-create it, but after that it has been working correctly. 

At the start of the build logs, it lists which build tasks it is using. If it lists an older version it will use the jarsigner tool:

`Downloading task: AndroidSigning (1.122.0)`

After recreating the build configuration (or possibly just re-uploading the keystore if you're lucky), it should list the newer version of the AndroidSigning task and it will use the apksigner tool

`Downloading task: AndroidSigning (3.181.0)`

**Comment by StarbuckSapien** [comment]
> tl;dr:
> Try to re-upload existing keystore in your AppCenter build configuration. It helped in my case.
> 
> I had a conversation with AppCenter Support. Looks like they have fixed the issue and now they do sign with signature v2+.
> For existing projects in order to make these changes work, you have to re-upload existing keystore in your AppCenter build configuration.

For me, re-uploading the keystore did make a difference, in that the app that targets Android API 30 will now install on Android 11. Unfortunately, now the app won't install on any version of Android lower than 11.

**Comment by chakrihacker** [comment]
Any update, unable to use apk to push to play store

**Comment by raj-flyfin** [comment]
+1

**Comment by glintpursuit** [comment]
Thanks @barvii , @ea-orbital8

**Comment by Antoine-Mace** [comment]
Hello, I'm currently running through this same issue, reuploading the Keystore does work (almost) for me.

However, the past week we've noticed  that the builds are constantly failing on every new merge, with the same error as before
`ERROR: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme`

re-uploading the Keystore fixes it but seems to be a 1-time thing, realistically I shouldn't have to do this over and over. As anyone experienced this issue?

Based on this open issue thread  I'll give it a go at remove/recreating the build config.

**Comment by glintpursuit** [comment]
@Antoine-Mace 

I have reconfigured the build for V2 error, but distribution section started timing out.

Not uploading build even after hours, keep on showing "Processing"

**Comment by Antoine-Mace** [comment]
@glintpursuit hmm I'm not getting this.

So I try recreating the build config but was still getting the same issue, ended up going for the manual config option.
Using the approach mentioned by @Nikosmonaut.

 Running `openssl base64 -A -in keystore.jks` locally to create a base64 string that is then added as an env variable in the build config on app center.
Then add or update existing pre-build script to run the reverse command `openssl base64 -A -d -out $KEYSTORE_ENV_VARIABLE`.

It's working so far!

**Comment by glintpursuit** [comment]
Ohh @Antoine-Mace, our issue was resolved by recreating build config.
