### ISSUE TITLE
Distribute not working

### ISSUE THREAD

**Issue by TsplayerT** [microsoft/appcenter#1993]
I would like to update my Xamarin.Forms application using the AppCenter Distribute tool, I can't find explanatory videos this year (2020). In addition to the fact that on the website https://status.appcenter.ms/ the distribution service found the status: **Degraded Performance**

![image](https://user-images.githubusercontent.com/6465230/93497658-0ac46b80-f8e7-11ea-92d8-64802ad91c22.png)

Can anybody help me?

**Comment by Tommigun1980** [comment]
Yeah, distribute is broken. When you upload a new build in App Center's UI, it goes to a blank page when the upload is approximately 15% complete.

**Comment by TsplayerT** [comment]
Got it, too bad. I can upload the APK file to an App Center platform, but the application installed on the device via a split link in the distribution tool, there is no PoupUp or Push notification that an update is available.
Can you help me in any way?

**Comment by Tommigun1980** [comment]
> Got it, too bad. I can upload the APK file to an App Center platform, but the application installed on the device via a split link in the distribution tool, there is no PoupUp or Push notification that an update is available.
> Can you help me in any way?

Don't know if there's much more to do than wait until Microsoft fixes it. I really hope they treat service outages as top priority and has a team working on a resolution, but App Center seems pretty abandoned.

**Comment by Tommigun1980** [comment]
@TsplayerT The issue has now been resolved, could you try it again?

**Comment by TsplayerT** [comment]
I actually saw it on the Microsoft Status website and the service is working correctly, but in my app it still doesn't show PoupUp.
Did you take this test and was it successful?
