### ISSUE TITLE
Ability to select multiple releases to delete them

### ISSUE THREAD

**Issue by koystinen** [microsoft/appcenter#200]
**Describe the solution you'd like**
Ability to select multiple releases from the list (Distribute / Releases) and delete them all at ones.

**Describe alternatives you've considered**
Current method of deleting intermittent releases required tapping on each one (three dots) , tapping on delete and answering confirmation dialog which is very time consuming.
Considered alternative is to do it automatically via API, but there are no API to delete release either.

**Additional context**
Our development process pushes multiple CI builds to the AppCenter every day, so by the time application is ready for release, we have hundreds of CI builds that are never going to be used again in the app center. Which is super time consuming to delete manually one at the time.

**Comment by botatoes** [comment]
Hi there, 
Thanks for the suggestion! We'll keep this in mind through the next iteration of UI updates. 

As for the API, there is a delete release API given the release id
https://openapi.appcenter.ms/#/operations/distribute/releases_delete 
Let me know if this will solve your issue via API.

**Comment by brodymerritt** [comment]
Can this feature also include disabling/enabling multiple releases?
Integrating an API is always easy, but it'd be nice for our team analysts (not just devs) to have the ability to Delete, Disable, or Enable more than 1 release at a time.

When we setup a CI/CD "DevOps" build cycle, we get automatic builds at high volumes. so manually having to come groom each AppCenter release, especially by Platform, can become very time consuming.

**Comment by tomduncalf** [comment]
Also interested in this – for now can I confirm there is no issue with having hundreds/thousands of builds for an app in AppCenter?

**Comment by tomduncalf** [comment]
Also interested in this – for now can I confirm there is no issue with having hundreds/thousands of builds for an app in AppCenter?

**Comment by Zaszczyk** [comment]
I also need that

**Comment by David-Sobin** [comment]
Definitely need the ability to bulk delete from the UI.

**Comment by ZsoltMolnarrr** [comment]
Hello! Our team would highly appreciate this feature. We have dosens of builds automatically uploaded from our CI. It is kinda getting hard to find anything.

**Comment by gavransava** [comment]
Need this asap :)

**Comment by hollyoops** [comment]
Use the [appcenter-cli](https://github.com/microsoft/appcenter-cli)

1. `npm install -g appcenter-cli`
2. `appcenter login`
3. run below shell

```
#!/bin/bash
for ((i=1; i<10; i++))
do
  appcenter distribute releases delete -r $i --app {{Your APP}} --quiet
done 
```

**Comment by newShepard** [comment]
Removal via the appcenter cli is pretty slow.
Option for those who have nodejs.

1) Run in your terminal - npm install appcenter-cli -g
2) Run appcenter login
3) The browser will open and show you the token (copy it)
4) Create anywhere script.js
5) Run npm install node-fetch in the script.js directory
6) Copy to your script.js next code

```const fetch = require('node-fetch');

let owner = "";  // application owner
let appName = "";  // application name
let token = "" // your token that you copied;
let from = 0; // from which release number to delete
let to = 0; // by which release number to delete

let url = `https://api.appcenter.ms/v0.1/apps/${owner}/${appName}/releases/`;
let requestInfo = {
	method: "delete",
	headers: { "X-API-TOKEN": token }
};

async function* asyncGenerator() {
	var i = from;
	while (i <= to) {
	  yield i++;
	}
  }

(async function() {
	for await (let num of asyncGenerator()) {
		try {
			await fetch(url + num, requestInfo);
			console.log(`Release ${num} deleted`)
		} catch (err) {
			console.log(err);
		}
	}
})();
```

7) Run node script.js

**Comment by pro100svitlo** [comment]
@botatoes seriously? since 2019????
>Hi there,
Thanks for the suggestion! We'll keep this in mind through the next iteration of UI updates.

**Comment by lemessur** [comment]
This is one of those features that pretty obviously should have been included in the 1.0 release. To still not have it years later is pretty inexcusable.

**Comment by tutipeti** [comment]
@botatoes I'm pretty sure there's been several rounds of UI updates in the meanwhile, any chance this will ever happen? ;)

**Comment by pro100svitlo** [comment]
Shame...

**Comment by koystinen** [comment]
such an easy feature to add... yet, still waiting for it.

**Comment by pro100svitlo** [comment]
Probably the best we can do - migrate from msAppCenter...

**Comment by pro100svitlo** [comment]
NO IT'S NOT,
THIS IS SHAME 💩

**Comment by SaqibS** [comment]
+1 We need to do this and I'm going to have to do this manually - just in case it helps, adding my voice.

**Comment by jacovinus** [comment]
c'mon @microsoft, this couldn't take you more than one week. We are paying microsoft licenses everywhere, and there is also the gihub pro licence active. It's a simple and useful service!

**Comment by kideh88** [comment]
+1 Our appcenter is struggling hard with the amount of releases we have and there is no way for us to bulk delete. We manage apps for multiple companies, we're at above 10.000 releases in various apps - there is no way for us to clean up

**Comment by irongut** [comment]
I'm having to pay for extra storage because my Azure DevOps & GitHub Actions builds ate the storage provided with my Pro account. I have one app with over 400 releases that I need to delete to stop them costing me money!

**Comment by benjaminadrom** [comment]
and it is still not possible, maybe i should write puppeteer which will delete all releases automatically 😅

**Comment by andre-wells** [comment]
Well, this is a sad outcome to find :(

**Comment by thisismyself** [comment]
speechless

**Comment by stachu2k** [comment]
So. It's still not implemented. What a sad news.

**Comment by koraxos** [comment]
How can this be still not implemented almost 4 years later ?

**Comment by kelltom** [comment]
...

**Comment by ridwankustanto** [comment]
still waiting...

**Comment by romanr** [comment]
5 years later… It's not even reopened!

**It's like Lenin said: you look for the person who will benefit… and... you know… you'll… pay Github charges for storage space when you forget to delete releases…** 

![image](https://github.com/microsoft/appcenter/assets/329079/baa59883-81ba-4c04-8ebf-3235eb6f36ae)
