### ISSUE TITLE
Xamarin iOS auto build failure - Xamarin.iOS 14 missing from Build SDK Version list

### ISSUE THREAD

**Issue by DeerSteak** [microsoft/appcenter#2000]
We use AppCenter automated builds for our Xamarin Forms app on both iOS and Android. Ever since Xamarin.iOS 14 was released, the app will no longer build.

MTOUCH : error MT2002: Failed to resolve "UIKit.UINavigationItemBackButtonDisplayMode" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" [/Users/runner/work/1/s/iOS/MyApp.iOS.csproj] 

I see that the UIKit.UINavigationItemBackButtonDisplayMode was added to iOS 14. I updated Xamarin.iOS locally to version 14, and so I can build locally, but the automatic builds fail. 

![image](https://user-images.githubusercontent.com/991752/94598167-2d924080-0254-11eb-9161-0442a12d5b71.png)

**Comment by justintoth** [comment]
:: Bump :: I have the same issue, we need App Center support for Xamarin iOS 14.0.

**Comment by beeradmoore** [comment]
I contacted support on the 24th of September regarding Xamarin.iOS 14.0.0.0 SDK into AppCenter.

Response I got was

> App Center will not be supporting iOS 14 until later this month, possibly into early October. Our engineers know that this is an issue, and are working on getting iOS 14 support added to App Center.

**Comment by JigarM** [comment]
Still the same issue.. Any updates on this problem?

**Comment by justintoth** [comment]
I contacted support and they said the tentative release date is October 14.

**Comment by justintoth** [comment]
It looks like despite them saying it'd be released on the 14th, I just checked this morning and the new Xamarin iOS 14 version is there!

<img width="489" alt="Screen Shot 2020-10-06 at 12 18 09 PM" src="https://user-images.githubusercontent.com/1443831/95229073-21672f80-07ce-11eb-8ef8-6d42da6eaf43.png">

@JigarM @beeradmoore @DeerSteak

**Comment by beeradmoore** [comment]
Thanks @justintoth . Very handy as today was our deadline to go and build+distribute manually. I don't want to go back to doing that again 😂

Thanks AppCenter for getting this sorted.

**Comment by DeerSteak** [comment]
Woohoo! Working for me now too. Gonna close this and Mark resolved.

**Comment by JigarM** [comment]
@justintoth you are right. 
It is working fine now. I am able to generate the build now.
