### ISSUE TITLE
Can you support branch name regex detection

### ISSUE THREAD

**Issue by tansent** [microsoft/appcenter#201]
**Describe the solution you'd like**
If there is a branch name "release/03_20_2019", as long as the name contains "release", regardless of the date, it can trigger a build.

**Describe alternatives you've considered**
Just don't do the plan. Add the date inside the comment.

**Comment by patniko** [comment]
Thanks for the submission! Mind adding a reaction to #26 so we can track interest under one issue?

**Comment by tonyarnold** [comment]
@patniko this isn't the same thing as #26. This feature is asking for limiting builds based upon the Git branch name, not a filesystem folder change.

**Comment by patniko** [comment]
Understood @tonyarnold. Leaving them linked to reference the body of work for now. If we introduce changes to how builds are triggered we'll probably look at multiple items together.

**Comment by AdamGold** [comment]
Any news on this request?

**Comment by nrajpurkar** [comment]
@AdamGold no update on this to report at the moment.

**Comment by mauriciopf** [comment]
Any news??? This will be a great feature, for beta releases

**Comment by nicholascm** [comment]
One work-around for this is is just to clone a template branch configuration via your CI/CD and use the Appcenter API to create a new configuration. Your CI/CD process could check the branch name and create the configured branch from the template as-needed.

Specifically this endpoint: https://openapi.appcenter.ms/#/build/branchConfigurations_create

accepts this payload

`{ cloneFromBranch: "your-branch-name-to-clone-from" }`

https://devblogs.microsoft.com/appcenter/app-center-build-adds-cloning-of-existing-build-configurations/

**Comment by alvindizon** [comment]
Any updates on this?
