### ISSUE TITLE
Custom property value length longer than "128"

### ISSUE THREAD

**Issue by MladenMikic** [microsoft/appcenter#2016]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Darkwonder** [comment]
Describe the solution you'd like:
Allow custom property values which are strings to be longer than 128 characters.
Describe alternatives you've considered:
I could not find any alternatives.
Additional context:
The `setCustomProperties` API only allows string values that are not longer than 128 characters. 
The API can be found here:
https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/macos
The behaviour and limitation is not documented.
