### ISSUE TITLE
There is no options to connect with SVN Repo to configure build .

### ISSUE THREAD

**Issue by XamarinPOC** [microsoft/appcenter#2021]
There is no options to connect with SVN Repo to configure build option.
Is there any alternate way to connect or is feature is not supporting for SVN.

**Comment by sjwaight** [comment]
You could consider using Azure Pipelines for this purpose and the plugging App Center tasks into the pipeline to do certain activities such as App Store / Test Flight publication. https://docs.microsoft.com/azure/devops/pipelines/repos/subversion?view=azure-devops

**Comment by XamarinPOC** [comment]
Thanks Will do that currently we  moved our source code  on github
