### ISSUE TITLE
Bug Build iOS - React Native Please Help

### ISSUE THREAD

**Issue by bytesk** [microsoft/appcenter#2023]
Hai please help me to solve this error, i got error after build in appcenter and i download the log, and like this : 

2020-10-25T07:49:44.2102187Z ##[section]Starting: Prepare job Phase_1
2020-10-25T07:49:44.2352164Z ContinueOnError: False
2020-10-25T07:49:44.2352164Z TimeoutInMinutes: 30
2020-10-25T07:49:44.2352164Z CancelTimeoutInMinutes: 0
2020-10-25T07:49:44.2352164Z Expand:
2020-10-25T07:49:44.2352164Z   MaxConcurrency: 0
2020-10-25T07:49:44.3701960Z   ########## System Pipeline Decorator(s) ##########

2020-10-25T07:49:44.3701960Z   Begin evaluating template 'system-pre-steps.yml'
Evaluating: eq('true', variables['system.debugContext'])
Expanded: eq('true', Null)
Result: False
Evaluating: resources['repositories']['self']
Expanded: Null
Result: False
Finished evaluating template 'system-pre-steps.yml'
********************************************************************************
Template and static variable resolution complete. Final runtime YAML document:
steps: []

2020-10-25T07:49:44.3701960Z   MaxConcurrency: 0
2020-10-25T07:49:44.3752003Z ##[section]Finishing: Prepare job Phase_1

and in my build output my appcenter like this : 

[command]/usr/bin/security delete-keychain /Users/runner/work/_temp/ios_signing_temp.keychain
##[section]Finishing: Install Apple certificate
##[section]Starting: Checkout blablaa-react-native@development to s
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Cleaning any cached credential from repository: blablaa-react-native (ExternalGit)
##[section]Finishing: Checkout blablaa-react-native@development to s
##[section]Starting: Finalize Job
Cleaning up task key
Start cleaning up orphan processes.
##[section]Finishing: Finalize Job
##[section]Finishing: Build

how can i solve this?

**Comment by MNorgren** [comment]
I am getting this same exact error. Build doesnt run more than a couple seconds. What is happening? The logs aren't showing much of anything
