### ISSUE TITLE
Default value of Environment Variable

### ISSUE THREAD

**Issue by azusa** [microsoft/appcenter#203]
**Describe the solution you'd like**

I want to a feature of Default Value Of Environment Value between beaches.

**Describe alternatives you've considered**

When pre-build script create a file described Default Values,  a build process reads as Environment Value.

**Additional context**

When User use a private nuget feed, they writes Username/ClearTextPassword in the `NuGet.config`.  (cf, https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/xamarin#how-do-i-restore-a-private-nuget-feed)

 At this time, each time new branch is created, they need to set same Environment Variables(Username/ClearTextPassword)  in Build configuration of App Center.

So I need this feature request.

**Comment by patniko** [comment]
Referencing #191 as a companion issue to this.

**Comment by DrBeak1** [comment]
+1 on this. There should be a super set of environment vars so that you don't have to add them to every new branch.

**Comment by nrajpurkar** [comment]
@azusa thanks for the input here. We recently shipped #22 which does clone environment variables to new branches in the same app which may help a little here.

**Comment by azusa** [comment]
@nrajpurkar  this is a pretty feature and thanks for your improving experience!

**Comment by vshjxyz** [comment]
Hello, I think this is still required if anyone wants to use Appcenter as a CI tool, I think it should be possible either from the UI to set a branch as the "template" one or via a yaml config (similar to circleci or heroku). Mainly I would expect to be able to set default ENV vars and enable unit tests for all PR pushes, but both of these could be done if we could set a default configuration to clone
