### ISSUE TITLE
Is there a way to upload mappings.txt file for Android using an API instead of AppCenter UI?

### ISSUE THREAD

**Issue by ishita-pandey** [microsoft/appcenter#2033]
**Describe the solution you'd like**
A possible API that allows users to run a script and upload mappings for a particular version name and version code. Currently, we have 3 flavors for our Android APK, each of them has 5 different ABI variants. So for an y APK refresh we end up uploading the same mapping file 15 times which is tedious.
Or alternatively, if the UI could provide a comma separated list of version codes to be submitted for the same mapping file, that would also suffice.

**Describe alternatives you've considered**
UI seemed to be the only alternative I could find. Please let me know if otherwise. 

**Additional context**
N/A

**Comment by DmitriyKirakosyan** [comment]
Hi @ishita-pandey,

I'm sorry for such a late reply and thank you for getting in touch with us!

Here is an API you're looking for: https://docs.microsoft.com/en-us/appcenter/diagnostics/android-deobfuscation#app-center-api

I'm closing it now. Please let me know if you have other questions.

Thanks.
