### ISSUE TITLE
UWP build should use winsqlite3 and NOT embed e_sqlite3.dll

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/appcenter#2039]
### Overview
AppCenter uses SQLite to manage its database, but the issue is that the UWP release of this library includes a reference to `SQLitePCLRaw.bundle_green` instead of using the SQLite library that comes **shipped with Windows 10**:

![image](https://user-images.githubusercontent.com/10199417/98362207-1e5d9a00-202d-11eb-9b94-c538a645ca43.png)

This means that by just referencing AppCenter, every single UWP app ends up with a **1.58MB** library in its package (`e_sqlite3.dll`), **for each architecture**, which is completely unnecessary. The reason why Windows 10 ships with a SQLite library included into it is precisely so that UWP apps can use it directly and avoid shipping their own version in their package.

AppCenter should switch to `SQLitePCLRaw.bundle_winsqlite3` in the UWP release (more info [here](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases)).

**Comment by FrayxRulez** [comment]
I guess that this issue should be moved to https://github.com/microsoft/appcenter-sdk-dotnet

**Comment by MitchBomcanhao** [comment]
A problem with this approach is that different versions of windows 10 include different builds of winsqlite3.dll, so your code may or may not work depending on which operating system version your end user has.

**Comment by leoniDEV** [comment]
Instead of forcing all developers to take a dependency on something that can be avoided and increase the size without a real benefit, let developer decide if it really need to use a different version of SQLite than the one provided by the OS.
