### ISSUE TITLE
Download option in addition to INSTALL as part of PUBLIC distribution

### ISSUE THREAD

**Issue by rughvi** [microsoft/appcenter#204]
**The solution I'd like**
When .IPA files are distributed to PUBLIC access group, there is only INSTALL option against each .IPA file. It would be highly helpful to have DOWNLOAD option for the clients to download the app and distribute using their MDM tools.

**Alternatives**
Right now I have go to the releases and download the .IPA from there and give it to the clients to upload into their MDM.

**Additional context**
<img width="697" alt="Screenshot 2019-03-21 at 12 09 38" src="https://user-images.githubusercontent.com/10544496/54756482-3e361500-4be0-11e9-8dcc-0136af35aa21.png">

**Comment by patniko** [comment]
Hi @rughvi, this one is on our iteration plan for this month already. We'll get it shipped next week most likely.

**Comment by botatoes** [comment]
Changes are in prod, you should be able to download the ipa on any client browser

**Comment by rughvi** [comment]
Hi team,
I still can't see the download option on MAC desktop. 
Expected : On iPad/iPhone INSTALL option, on MAC / WINDOWS desktop DOWNLOAD option.
Actual : On MAC desktop it says 'This app is not compatible with MAC OS' but still shows INSTALL option.
<img width="1278" alt="Screenshot 2019-05-08 at 09 11 01" src="https://user-images.githubusercontent.com/10544496/57360212-7d5cfd00-7171-11e9-8ef0-2a83cd373e4a.png">

**Comment by botatoes** [comment]
This was implemented for Android and currently does not work for iOS. Reopening this issue and creating a bug for it.
