### ISSUE TITLE
Use System.Text.Json instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/appcenter#2040]
### Overview
AppCenter uses `Newtonsoft.Json` to handle the JSON serialization at the moment. It should move to `System.Text.Json`, both because it's faster and more efficient, but also because it comes in-box on runtimes such as .NET Core 3.1, meaning that developers on those platforms will no longer have AppCenter add the extra `Newtonsoft.Json` dependency and binary to their app package. Even for developers on other platforms (eg. UWP), since everyone is already migrating to `System.Text.Json` anyway, it'd be better if adding AppCenter didn't mean they'd still end up with the unnecessary `Newtonsoft.Json` dependency.

You can see an example of the extra dependency here:

![image](https://user-images.githubusercontent.com/10199417/98362207-1e5d9a00-202d-11eb-9b94-c538a645ca43.png)

**Comment by FrayxRulez** [comment]
I guess that this issue should be moved to https://github.com/microsoft/appcenter-sdk-dotnet

**Comment by DmitriyKirakosyan** [comment]
Please keep tracking this feature request here: https://github.com/microsoft/appcenter-sdk-dotnet/issues/1588/#issuecomment-959358310
