### ISSUE TITLE
Error in fetching the Apple service connection details for managing devices

### ISSUE THREAD

**Issue by aelf-hz** [microsoft/appcenter#2044]
On connect to store authentication
Error in fetching the Apple service connection details for managing devices. apple connection is not valid for connectionId: f4d94859-aa63-4b97-9f22-0a76c81d647c

**Comment by aelf-hz** [comment]
Please help me

**Comment by vincentcastagna** [comment]
@aelf-hz Could be great if you could share what was the fix or the issue on this when closing it. I have the same prob, seems related to 2FA failed to fetch.

**Comment by danielleedge** [comment]
I resolved this issue by navigating to https://appcenter.ms/settings/accounts. Under apple accounts it said their was an issue with the user it was trying to connect with. I asked it to re-connect (which prompted me to provide an apple verification code). I was then able to connect as normal without issue.

**Comment by liangwangcm** [comment]
@danielleedge  your solution is the right one.
