### ISSUE TITLE
Browser notifications when build completes

### ISSUE THREAD

**Issue by nschild** [microsoft/appcenter#205]
**Describe the solution you'd like**
Instead of waiting 10-20 minutes, randomly checking on the status of a build, AppCenter could use the browser's Notifications API to display a notification when a build completes.

**Describe alternatives you've considered**
I currently use webhooks to push to a slack channel, but that is cumbersome.

**Additional context**
Include information like app name, branch name and/or commit name

**Comment by nrajpurkar** [comment]
Thanks for the feature request @nschild. Similar to #956. Keeping both open to track further interest.
