### ISSUE TITLE
Xamarin.Forms - UWP solution breaks, because of netstandard2.0

### ISSUE THREAD

**Issue by Grzesik** [microsoft/appcenter#2056]
I created a new Xamarin.Forms solution with iOS, Android and UWP projects. iOS and Android can be build in AppCenter, but the UWP project breaks, because of:

##[error]C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): Error NETSDK1005: Assets file 'D:\a\1\s\ArticleWorkbench\ArticleWorkbench\obj\project.assets.json' doesn't have a target for 'netstandard2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project.

Locally I can build and run the application  in debug and release.

Thanks

[logs_60.zip](https://github.com/microsoft/appcenter/files/5597431/logs_60.zip)

**Comment by randyrenwick** [comment]
My team is having the same problem with UWP projects.

**Comment by gaglia** [comment]
I also encounter the same issue for the Xamarin.Forms UWP project

**Comment by jlewicki-nevo** [comment]
I am also running into this for a Xamarin.Form UWP project.

**Comment by Grzesik** [comment]
Hi, my problem is solved. 5 days ago I got a message in AppCenter, that the Nuget would be  updated to the latest version 5.8, if I save the build configuration. I did it and the buid worked better. I got a problem with too big pictures in the assets and than the build was green!!!

**Comment by gaglia** [comment]
> Hi, my problem is solved. 5 days ago I got a message in AppCenter, that the Nuget would be updated to the latest version 5.8, if I save the build configuration. I did it and the buid worked better. I got a problem with too big pictures in the assets and than the build was green!!!

I confirm that it is enough to save the build configuration and you are able to compile correctly again

Thanks!

**Comment by IndexOutOfLimit** [comment]
App Center build for UWP is showing white screen after launch
