### ISSUE TITLE
Simplify distribution flow (reduce clicks)

### ISSUE THREAD

**Issue by WCByrne** [microsoft/appcenter#206]
**Describe the solution you'd like**

I have some feedback on the distribution flow from the Distribute > Groups page:

1. I always release from a build. It is a little tedious to have to click the "choose a build" button at the bottom. I also missed it the first time since the release option from the build page was recently removed. It would be nice if it would remember how I released last time or default to using a build if the app is be built in AC.
2. Getting through the next few steps requires a lot of clicks. You have to click the branch, next, the build, next, enter message, next... It would be nice if clicking the branch/build would automatically go to the next option – maybe there could be a small → button on the right side of the slats if clicking the entire row doesn't work for some reason. Enter (or cmd-enter) to invoke next would also work (I try it every time out of habit).
3. Related to #2, I only have one branch building for this app, maybe it could skip that step and go straight to the builds in that case.

I always shrug at feedback for "reducing clicks" but improvements here would be greatly appreciated. Releasing many internal builds a day this becomes a very repetitive process. Thanks!

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by botatoes** [comment]
Hi! Thanks for the feedback. Really appreciate the insight. We have an effort on improving distribution UI coming up in the near future. I'll be sure to reference this but it'd also be awesome to be able to reach out to you for feedback if you're open to that. @WCByrne

**Comment by WCByrne** [comment]
Glad to hear! Yup, of course. If you want to talk more feel free to reach out on twitter for more contact info - `@wcbyrne`

**Comment by WCByrne** [comment]
Did anything ever happen to the distribution UI? I never noticed any changes and still have the same complains about it.
