### ISSUE TITLE
[Xamarin-UITest] Apple Silicon Support

### ISSUE THREAD

**Issue by reggiebIV** [microsoft/appcenter#2062]
**Describe the solution you'd like**
Support to run Xamarin UITest on M1 Mac Mini

Currently, when attempting to deploy to a simulator on an M1 Mac mini, the following error causes the test to fail:

Showing Recent Issues

Test target DeviceAgent

DeviceAgent-Runner.app (22448) encountered an error (Failed to load the test bundle.) (Underlying Error: The bundle “DeviceAgent” couldn’t be loaded because it doesn’t contain a version for the current architecture. The bundle doesn’t contain a version for the current architecture. Try installing a universal version of the bundle. dlopen_preflight(/var/folders/t7/lfjtlby93_v87v0vzhm7k6vr0000gn/T/xdb/DeviceAgent.iOS.Dependencies/e1e56773c5a402910487b8f3840b44dd/app/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent): no suitable image found.  Did find:
	/var/folders/t7/lfjtlby93_v87v0vzhm7k6vr0000gn/T/xdb/DeviceAgent.iOS.Dependencies/e1e56773c5a402910487b8f3840b44dd/app/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent: mach-o, but wrong architecture))

Note that the app deploys to simulator, and DeviceAgent-Runner does as well, and I can manually open the DeviceAgent app on the simulated device without error.

I have tried on simulators for iOS 14.2 on an iphone 12 and iphone 12 pro simulator. 

I am running Visual Studio for Mac Professional version 8.8.3 (build 16)
Xcode version: 12.2 (12b45b)
MacOS: Big Sur version 11.0
Mac Mini M1 8GB version

**Comment by gregorymfoster** [comment]
At Screenplay (https://screenplay.dev/) we got this working by updating our UI Test target's build settings "ONLY_ACTIVE_ARCH" to "false".

**Comment by reggiebIV** [comment]
> At Screenplay (https://screenplay.dev/) we got this working by updating our UI Test target's build settings "ONLY_ACTIVE_ARCH" to "false".

Thank you for the tip, but might I ask how you accomplished this? I set the ONLY_ACTIVE_ARCH flag to NO (I think it's no and yes, unless somehow it's different for Xamarin) via terminal, then ran msbuild in terminal to build the application and the UITest, but I still get the same error. I didn't see any way to accomplish it in the UI, so I tried via terminal, as I mentioned, but no dice so far, unless I did something wrong, I've never built this app from the terminal before, I've only used the IDE.

**Comment by DanielGlick45** [comment]
I am running into this as well. Is there a workaround I can use for developing on VS for Mac?

**Comment by Saccomani** [comment]
i am getting the same error on macbook m1...

The bundle “DeviceAgent” couldn’t be loaded because it doesn’t contain a version for the current architecture. Try installing a universal version of the bundle.

**Comment by IlyaBausovAkvelon** [comment]
Hello Everyone!
The Xamarin.UITest 3.1.0 was released. It provides support for developing on Apple Silicon platform.
You are welcome to try it!

**Comment by Saccomani** [comment]
> Hello Everyone!
> The Xamarin.UITest 3.1.0 was released. It provides support for developing on Apple Silicon platform.
> You are welcome to try it!

Amazing!! <3
