### ISSUE TITLE
Xamarin UI Test getting wrong coordinates for item in iPhone XR

### ISSUE THREAD

**Issue by JoshuaLogue** [microsoft/appcenter#2071]
I am using 
Xamarin UI Test v3.0.11
Xamarin Test Cloud Agent 0.22.1
iPhone XR iOS 14.2
Xamarin iOS 14.6.0.15

app.Tap is not working for me. When I run it in repl() it says its tapping the coordinates but nothing happens.
By playing around with app.TapCoordinates I can get it to tap the button but its seems the coordinates found for the button are wrong. 

As anyone else found this issue? I'm now finally able to write tests again in iOS but this is stopping me from creating tests.

**Comment by patkozlowski** [comment]
I'm having the same issue.
