### ISSUE TITLE
Customer issue with App Center 200 event limit and analytics issue with App Insights

### ISSUE THREAD

**Issue by lotinke** [microsoft/appcenter#2075]
Customer has been planning on using App Insights for collecting analytics for a new product we're currently working on. We have three clients: web, iOS, and Android. In the iOS/Android clients we haven't been able to use App Insights directly as those native SDKs have been deprecated in favor of App Center. The problem we're facing though is that App Center has some constraints that App Insights does not which is significantly impacting our ability to leverage the product to capture consistent analytics across all three platforms.
Specifically, App Center has a limitation of 200 unique events, and a limit on the number of user-defined properties that each event can include. These limitations are not present in App Insights.
I was hoping that you could put us in touch with someone from the App Center/App Insights team so that we might better understand the purpose of these limitations and gain some understanding on how we can use these products to support Humana Health. As it currently stands, we have some concerns about the viability of App Center/App Insights for Humana Health because of these constraints.

It is still limited to 200 in App Center” is the problem we need help with.  The apps in question are exporting to App Insights and using App Insights features like funnels and flows, etc.  We do not have a solution to the problem “how do we use App Center + App Insights with more than 200 unique behaviors to track”… options being (1) sacrifice the detail needed by staying under 200 (likely a non-starter), (2) sacrifice use of app-insights analytic tools like funnels and flows (which draws into question the value of exporting to there), (3) look at other non-MS tools.  We’d like to better understand the limitation, whether there is a plan or intent to remove the limitation, and suggestions workarounds if any to meet the needs of tracking behaviors and flows with more than 200 uniquely named events.  Right now we fell boxed in to picking one of multiple bad options.

**Comment by zhisliumicrosoft** [comment]
migrating from HockeySDK, the below two constraint is also causing some loss of data. wonder if AppCenter team has any plan to extend those.
- The maximum number of event properties per event is 20. When more than 20 properties are sent, the first 20 properties are processed, and the rest are automatically dropped.
- The SDK truncates each property key and value to the first 125 characters.
