### ISSUE TITLE
Include branch name on the release in the appcenter

### ISSUE THREAD

**Issue by logicallayer** [microsoft/appcenter#2078]
**Describe the solution you'd like**
I have QA testers that review multiple branches and they need to be able to distinguish which release belongs to witch branch. A branch column that can be sorted on and filtered would be a great addition

**Describe alternatives you've considered**
A simple solution if the main one is too challenging is to add a branch name tag to each release so at least it can be distinguished automatically

**Additional context**
Currently release includes version, date/time and a message from the github commit. I believe there is room for the branch name

**Comment by sylvanaar** [comment]
My team complains about this constantly. Since we do not rebuild the application and it passes through multiple deployments - there is no way to tell them apart unless we remember to add the text or automate it.

**Comment by dimonovdd** [comment]
Why is this issue closed?
