### ISSUE TITLE
Spectate omen beta app

### ISSUE THREAD

**Issue by antoni0215** [microsoft/appcenter#2079]
Omen services have send me a link to donwload their app about spectate omen but when I click app center says that there is not acces for my device or the app doesn't exist

**Comment by DmitriyKirakosyan** [comment]
Hi @antoni0215,

Thank you for getting in touch with us!

What platform are you trying to install the app on?
If it's iOS, it is likely that your device is not included in the profile the app was signed with.

Please contact the app provider and make sure that the app can be installed on your device.
