### ISSUE TITLE
App archieved using the dogfood cert/profile will crash after download to iPhone.

### ISSUE THREAD

**Issue by RichardSunMS** [Microsoft/appcenter#208]
**What App Center service does this affect?**
Appcenter ms dogfood environment for iOS

**Describe the bug**
I requrested the cert from dogfood environment and published the ipa then uploaded to appcenter ms, it can be downloaded to iPhone but failed to run when starting the application. 
After the iPhone Distribution: Microsoft Corporation certificate been trusted on the iPhone, the app will crash and exist soon during starting, quite like some certificate invalid/expire situation.

**To Reproduce**
1. Go to 'https://appcenter.ms/apps?os=iOS'
2. Find the app on 'MScribe'
3. Download it to your local iPhone
4. Trust the cert and start the app.

**Expected behavior**
Our app should be able to start.

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: iOS 12.1

**Comment by derpixeldan** [comment]
@RichardSunMS please open a ticket in support (blue button) or feel free to find and message me directly.

**Comment by RichardSunMS** [comment]
@derpixeldan, I think you can just close it. 
My bad it's a library reference issue, nothing relates to the cert. 

Sorry for any inconvenience. 
Richard.
