### ISSUE TITLE
Webhook to Rocket Chat is just empty

### ISSUE THREAD

**Issue by muellerfa** [microsoft/appcenter#2084]
Hey!

I added a webhook between AppCenter and our Rocket Chat tool, so we can get Notifications, if an app gets distributed. The test ping works fine, but the message for a new distribution is just empty. Other webhooks in Rocket Chat works fine (for example from fastlane or jenkins).

<img width="541" alt="Bildschirmfoto 2020-12-18 um 09 18 22" src="https://user-images.githubusercontent.com/4659321/102592063-37b93200-4113-11eb-921c-2459b73e1499.png">

Am I doing it wrong or is it a bug?

Thanks and have a nice day!

**Comment by ishiharas** [comment]
Any updates on this issue? I would love to see a fix for this one.
