### ISSUE TITLE
Search Errors same as Crashes

### ISSUE THREAD

**Issue by dimitarcnbs** [Microsoft/appcenter#209]
There is a search for Crashes. 
Extend the search to work for Errors too.

**Comment by winnieli1208** [comment]
Hi @dimitarcnbs - thanks for the request! This is actually something we're actively working on #269.

The [search API](https://openapi.appcenter.ms/#/errors/Errors_ErrorSearch) has already been updated to search for errors and we expect to update the UI by end of the week. We'll keep this thread updated when the UI is complete.

**Comment by winnieli1208** [comment]
@dimitarcnbs - good news! You should be able to see an option to search errors for your Xamarin or Unity apps. I'm going to close this request for now but let me know if you have any questions. Thanks!

![image](https://user-images.githubusercontent.com/8868628/56396253-cb29b980-61f2-11e9-9751-5774d7cbb4c2.png)
