### ISSUE TITLE
return code 66

### ISSUE THREAD

**Issue by khanhduy62** [microsoft/appcenter#2091]
I got code 66 when I build the app. Please help me 
[1_Build.txt](https://github.com/microsoft/appcenter/files/5769249/1_Build.txt)
<img width="1006" alt="Screen Shot 2021-01-05 at 4 23 48 PM" src="https://user-images.githubusercontent.com/16585137/103629462-eadab580-4f72-11eb-943b-46339b9770d3.png">

**Comment by MatkovIvan** [comment]
Hi @khanhduy62,

Currently, we're using this repo for feature requests only. Could you please [open the help menu](https://docs.microsoft.com/en-us/appcenter/help) in the upper right corner of the App Center portal: **? > Contact support** to start a conversation where our support team will help you to solve the problem. Thanks.
