### ISSUE TITLE
Log not appear when crash app on Android

### ISSUE THREAD

**Issue by dotd46VietInfo** [microsoft/appcenter#2092]
I using Xamarin Forms Project.
I not understand that why my app crash, log not appear on **Diagnostics - Issues - Crash**.

Note: despite time before my app still log crash normal!

Please help me resolve it!

**Comment by MatkovIvan** [comment]
Hi @dotd46VietInfo,

Currently, we're using this repo for feature requests only. Could you please [open the help menu](https://docs.microsoft.com/en-us/appcenter/help) in the upper right corner of the App Center portal: **? > Contact support** to start a conversation where our support team will help you to solve the problem. Thanks.
