### ISSUE TITLE
Failed to analyze MachO file.

### ISSUE THREAD

**Issue by konstantin-bobkov** [microsoft/appcenter#2099]
**Short description of case**
Test Cloud service is unable to process (upload) MachO files during creating a test run and it causes failures of `appcenter test run` command. The cause of this error is Xcode 12.x changes to the XCUITest related libraries and frameworks containing an arm64e slice.

command: 
`appcenter test run xcuitest --app "APP_PATH" --devices "DEVICE_SET" --test-series "master" --locale "en_US" --build-dir BUILD_DIR`

output:
Preparing tests... done.
Validating arguments... done.
Creating new test run... done.
Validating application file... done.
Uploading files... done.
Starting test run... failed.
Error: Failed to analyze MachO file: Unknown load command: 2147483700

**Possible workaround**
This workaround provided by customer:
For each framework and dylib in the <YourAppName>-UITests-Runner.app Frameworks directory

Namely:
XCTAutomationSupport.framework
XCTest.framework
libXCTestSwiftSupport.dylib

`$ lipo -remove arm64e -output <binary_name> <binary_name>`

Building an app with Xcode 12, and then using the Xcode 11 built runner works.

**Comment by ogezue** [comment]
I would classify this as a bug, because a main feature of AppCenter is not usable. (And customers are paying for it since months).
