### ISSUE TITLE
App Store Connect Rejected when Using App Store Connect

### ISSUE THREAD

**Issue by ensighten-ekolinko** [microsoft/appcenter#2101]
Hi - I'm trying to use App Center to build and distribute an app via App Store Connect. We are trying to integrate a NuGet package (Ensighten.FormsPlugin) that has a bound Swift library and is targeting iOS < 12.2 so it requires SwiftSupport bundled within the IPA. There are several NuGet packages that are designed to provide this but none appear to be compatible with App Center distribution process. Submitting through XCode directly works correctly but our app is deeply integrated with App Center / CI and submitting the package locally through XCode is not an option.

We've created a few sample projects that demonstrate the issue.

**Submitted without Errors but crashes on iOS < 12.2 (Ensighten Only):**
https://bitbucket.org/ensighten-ondemand/xamarintestinng/src/ensighten-only/

**Submission Rejected due to SwiftSupport missing (using Xamarin.iOS.SwiftRuntime):**
https://bitbucket.org/ensighten-ondemand/xamarintestinng/src/ensighten-swift/
Received "ITMS-90426: Invalid Swift Support" error from Apple

**Submission Rejected due to Invalid Signature / Improperly Signed (using Xamarin.iOS.SwiftRuntime and Xamarin.Swift4):**
https://bitbucket.org/ensighten-ondemand/xamarintestinng/src/ensighten-xamarin-swift-runtime/
[invalid-signature-log.txt](https://github.com/microsoft/appcenter/files/5876157/invalid-signature-log.txt)

Is it possible to add support so that Apps targeting iOS < 12.2 that have embedded Swift Support can be distributed through App Center?

**Comment by Muthukumaradappt** [comment]
Hi, @ensighten-ekolinko , Is that issue solved?
