### ISSUE TITLE
Product flavors defined via Kotlin Gradle DSL aren't recognized

### ISSUE THREAD

**Issue by harry248** [microsoft/appcenter#2103]
I would like to get the product flavors that I have defined via the Kotlin Gradle DSL:

```
android {
    flavorDimensions("environment")
    productFlavors {
        create("development") { // or getByName("development")
            dimension("environment")
        }
        create("staging") { // or getByName("staging")
            dimension("environment")
        }
        create("production") { // or getByName("production")
            dimension("environment")
        }
    }
}
```

to be selectable in the Build Configuration like it was available using the Groovy DSL.

There doesn't seem to be an alternative other than moving back to Groovy (but we don't really consider this).

**Comment by harry248** [comment]
Update: It seems as if only `getByName()` isn't recognized, but `create()` is. In our case the product flavor creation is part of a common script in` buildSrc` folder and the app module gradle file only references the created flavors via `getByName()`. So I guess App Center should not only recognize `create()` but also `getByName()` as this is a common practice in a multi-module setup.

**Comment by shinichi495** [comment]
anything change ?, because this issue also happen for me

**Comment by uplusplus** [comment]
I found a resolution：

通过Fiddler可以拦截并修改appcenter的build配置http请求

1、打开fiddler，配置浏览器代理为127.0.0.1:8888
2、打开appcenter的build配置页面，点击save
3、在Fiddler拦截请求列表中查找包含branches/main/config请求
4、修改http请求body的build variant字段，为你需要的值
5、然后resume请求
