### ISSUE TITLE
Support for App Store Connect API

### ISSUE THREAD

**Issue by tsemerad** [microsoft/appcenter#2105]
Is there a timeframe for when App Center will support using the App Store Connect API for connecting to App Store Connect? Currently it looks like App Center only accepts connecting with an Apple ID, which requires us to sign in again every 30 days with a 2 factor code, which is only sent to a specific person on our team, so it's kind of brittle. I'm looking for App Store Connect API support similar to [what Bitrise supports](https://devcenter.bitrise.io/getting-started/configuring-bitrise-steps-that-require-apple-developer-account-data/#ios-auto-provision-with-app-store-connect-api-step).

**Comment by jdinnen** [comment]
I cannot even sign into my Apple ID. I get this "Need to acknowledge to Apple's Apple ID and Privacy statement" but there is no privacy statement in the Apple ID
 https://github.com/fastlane/fastlane/issues/18098

**Comment by nicholascm** [comment]
Same issue here.

**Comment by jernelson7** [comment]
Can AppCenter please add support for App Store Connect API keys?
https://docs.fastlane.tools/app-store-connect-api/#creating-an-app-store-connect-api-key

**Comment by jdinnen** [comment]
> I get a warning that my App Store Connection under the Distributions was Invalid, When I reauthenticate I get the following warnings. I cannot even sign into my Apple ID. I get this "Need to acknowledge to Apple's Apple ID and Privacy statement" but there is no privacy statement in the Apple ID. I tried to authenticate user a different account and get a warning that the 2FA code I entered isn't valid. 
> 
>  https://github.com/fastlane/fastlane/issues/18098

I was able to get connect but needed to create a new Apple ID. One thing I didn't realize was when I removed the old account and added a new one is, the actual apps that had still the old account attached to them. I had to do to Distribute, Stores then hover over the AppStore Connect row, click on the "Delete Connection" then go back through the process of adding it back to the store. At this point it asked me to Authenticate with Apple with 2FA,create an App specific password (which I already had at hand) then enter the app specific password and I was back in business. I had to go delete the connection on my other Apple apps using that ID and reconnect them.

**Comment by sylvanaar** [comment]
No need to do anything drastic. Try going to the Apple ID page, not the App store page.  Also, everyone has to use 2FA now - so perhaps this advice has arrived too late.

**Comment by KBEMobisys** [comment]
> Can AppCenter please add support for App Store Connect API keys?
> https://docs.fastlane.tools/app-store-connect-api/#creating-an-app-store-connect-api-key

+10 for this feature request. AzureDevOps' Apple AppStore Service Connection already supports App Store Connect API keys. So, please also add support in AppCenter.

**Comment by KBEMobisys** [comment]
May someone of the AppCenter Team please answer if you plan to support the App Store Connect API keys?

**Comment by devopspoolcorp** [comment]
Please reopen this AppCenter Team! As others have stated, Fastlane and Azure DevOps already support using App Store Connect API keys which Apple added to resolve this very issue.

**Comment by eabbott2b** [comment]
This blog post implies that it has been implemented and is available via a private preview on request
https://devblogs.microsoft.com/appcenter/private-preview-for-app-store-connect-api-support/
