### ISSUE TITLE
Jcenter is being shut down on May 1st 2021

### ISSUE THREAD

**Issue by apkelly** [microsoft/appcenter#2108]
**Describe the solution you'd like**
Can you please host the App Center gradle dependancies on mavenCentral()

**Describe alternatives you've considered**
none

**Additional context**
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by russelarms** [comment]
Hi @apkelly, thanks for opening the feature request! We have the same request opened in our android repository, so I'm closing this as a duplicate.
https://github.com/microsoft/appcenter-sdk-android/issues/1503
