### ISSUE TITLE
Workaround for linking Apple Developer Account to Appcenter

### ISSUE THREAD

**Issue by jdinnen** [microsoft/appcenter#2109]
Currently we are using a shared Apple ID to link Appcenter to our Apple Testflight, it doesn't have two factor authentication as its shared.

We noticed that we cannot deploy to Apple Testflight. When we go to the logs we get an error when it tries to deploy
```
##[error]{"code":"apple_authentication_error","message":"Error: Failed to publish to store. apple connection is not valid for connectionId: d3353867-3af0-4aa7-82ee-fdda6a1e896a"}
http response code: 400
```

We go into Distribute>Stores and we see "Your Apple App Store Credentials are no longer valid. Please re-authenticate." When we try to reauthenticate, iIt gives us an inaccurate error message. Need to acknowledge to Apple's Apple ID and Privacy statement. We sign in and there is no such privacy statement to acknowledge. Fastlane are suggesting fixes for this but since we are an Appcenter customer we do not implement this software ourselves.
https://github.com/fastlane/fastlane/issues/18098

I tried to authenticate user a different account (my own developer account) and get a warning that the 2FA code I entered isn't valid, yet the code works on Apple's site.

I reached out to Microsoft support and they requested I open a ticket here for a workaround since I don't see how to link Appcenter to an Apple .

**Comment by zeryen** [comment]
We have the same problem

**Comment by chriscoderdr** [comment]
Same problem here

**Comment by jdinnen** [comment]
I was able to get connect but needed to create a new Apple ID. One thing I didn't realize was when I removed the old account and added a new one is, the actual apps that had still the old account attached to them. I had to do to Distribute, Stores then hover over the AppStore Connect row, click on the "Delete Connection" then go back through the process of adding it back to the store. At this point it asked me to Authenticate with Apple with 2FA,create an App specific password (which I already had at hand) then enter the app specific password and I was back in business. I had to go delete the connection on my other Apple apps using that ID and reconnect them.

**Comment by mifi** [comment]
For me the problem was solved by enabling two-factor

**Comment by sylvanaar** [comment]
If i recall - there is something you need to acknowledge - but is isn't in the place you are expecting. I have forgotten exactly where - but try going to the Apple ID portal - not he app store portal.

Also - now everyone has to use 2 factor- but you can put multiple contact numbers

**Comment by rlasker-b2w** [comment]
We solved the problem by using the app specific password but then it returned the subsequent time we went to do a deploy. I hope we will not need to create an app specific password and delete and create the connection each time we need to do a deploy.

**Comment by jbachelor** [comment]
Same issue here. I tried deleting my store connection as mentioned by @jdinnen, but as a lowly developer I do not have access to create new Apple IDs for my company. Perhaps it would have worked if I could have created a new user, but without that, I seem to be stuck in the water here.

<img width="602" alt="2021-03-18_11-33-35" src="https://user-images.githubusercontent.com/19045/111678752-0118b380-87f7-11eb-8ac7-613ef6ccab3f.png">

**Comment by thejustinwalsh** [comment]
This is impacting client work here as well. None of the mentioned workarounds are working, completely blocked.
I guess you need access to a Mac to upload IPA artifacts and this particular client is a Windows shop.

@mihailo-popovic96 any updates on this from the DRI?

**Comment by rlasker-b2w** [comment]
@thejustinwalsh we have been able to delete the connection and recreate it and it will work the first time. It is when you go to do your next deploy it will give you the same message. I can't hardly believe that this has not been fixed.

**Comment by jdinnen** [comment]
Even with the 2FA set up, the connection will need to be re-authenticated on a regular basis and it's very inconvenient. We assume it did it's thing but often it didn't even distribute to TestFlight. Only one person has access to reconnect and the 2FA with Apple only sends to that one person's device to give us the 2FA code. I kinda wish that we just had an API key.

**Comment by architect-aimonkey** [comment]
HI, we need help on this AppCenter, I also have it. Thanks for your time

**Comment by akanksha820** [comment]
Experiencing same issue here:( 
Waiting for a fix soon

**Comment by eduardorfreitas93** [comment]
Experiencing same issue here:(
Waiting for a fix soon

**Comment by ryanAtRite** [comment]
Same issue here

**Comment by efesurekli** [comment]
Same issue here

**Comment by MinaZakaria** [comment]
same issue here !

**Comment by mohed** [comment]
Is it safe to assume that no one on the AppCenter team is working on this?

**Comment by thejustinwalsh** [comment]
Doesn't seem like it.
Working on moving over to [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xcode?view=azure-devops) personally.

**Comment by thejustinwalsh** [comment]
Somehow this got tagged as a feature-request instead of a bug, so probably why it is being ignored.

**Comment by spoelstraethan** [comment]
> Even with the 2FA set up, the connection will need to be re-authenticated on a regular basis and it's very inconvenient. We assume it did it's thing but often it didn't even distribute to TestFlight. Only one person has access to reconnect and the 2FA with Apple only sends to that one person's device to give us the 2FA code. I kinda wish that we just had an API key.

If you are using a distribution only shared account with 2FA enabled, you can sign into that account on multiple macOS machines (as a secondary iCloud account), and you will get the code notification on all the devices with that account signed in.

It is under Settings > Internet Accounts. You will see a message after signing in that not all iCloud features are supported, but that is fine, the 2FA prompts work, and that is typically what you need.
![image](https://user-images.githubusercontent.com/56567427/140665153-e0d8ec36-5acf-4064-836f-3e8127ad3fe9.png)

**Comment by empiteranga** [comment]
having the same issue 
##[error]Error: {"code":"service_connection_not_found","message":"Error: Failed to publish to store. Could not find the Apple Developer account which is set up for the store."}

**Comment by vivekkhetwal** [comment]
Still Facing the issue on linking the Apple Developer Account to Appcenter.

Last week the error was regarding the unavailability of the distribution services:

`##[error]Error: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
  <meta content='text/html; charset=utf-8' http-equiv='content-type'/>
  <style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style>
  <title>Service unavailable</title>
</head>
<body>
  <div id='content'>
    <div id='message'>
      <h2>Our services aren't available right now</h2>
      <p>We're working to restore all services as soon as possible. Please check back soon.</p>
  </div>
</body>
</html> 
http response code: 504`


I thought the issue will get resolve in some time but this week I am getting this error when trying to publish the IPA to App Store TestFlight. Please get this fixed as it has been a long time since we started facing the issue.

`##[error]Error: {"code":"service_temporarily_unavailable","message":"Error: Failed to publish to store. The Apple Login service is temporarily unavailable, please wait a few minutes and try again later."} `

**Comment by Diego-F-Aguirre** [comment]
I'm seeing a similar issue with one app that i haven't been able to deploy through appcenter for over a week. 

`##[error]Error: {"code":"service_temporarily_unavailable","message":"Error: Failed to publish to store. The Apple Login service is temporarily unavailable, please wait a few minutes and try again later."} 
http response code: 400
##[section]Finishing: Create distribution
##[section]Starting: Xcode build (signed)`

I had a team mate reach out to appcenter and apparently one of the issues was that the app had a special character in the name that appcenter doesn't like. We've removed the special character for testing purposes and now are stuck on the error above. 

Anyone have any other suggestions?

**Comment by vivekkhetwal** [comment]
Hi @Diego-F-Aguirre,

If you are still using the old authentication method (Apple Developer Account Credentials) to connect with the App Store and facing issues, try updating the authentication method to the new [Connect API](https://learn.microsoft.com/en-us/appcenter/distribution/stores/apple#set-up-the-connection-between-app-center-and-app-store-connect). This may resolve the issue. I faced a similar problem when using the old method but switching to the App Store Connect API helped me resolve the issue. To generate an App Store Connect API key, refer to this link: 

[https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api](https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api)

**Comment by truedat101** [comment]
> Hi [@Diego-F-Aguirre](https://github.com/Diego-F-Aguirre),
> 
> If you are still using the old authentication method (Apple Developer Account Credentials) to connect with the App Store and facing issues, try updating the authentication method to the new [Connect API](https://learn.microsoft.com/en-us/appcenter/distribution/stores/apple#set-up-the-connection-between-app-center-and-app-store-connect). This may resolve the issue. I faced a similar problem when using the old method but switching to the App Store Connect API helped me resolve the issue. To generate an App Store Connect API key, refer to this link:
> 
> https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api

This is the right answer.  It doesn't appear that vanilla credentials (username, password) will work any longer.  Thank you for posting this.  I wasn't even sure what this api was.
