### ISSUE TITLE
Persist values of filters (Versions, Time, Status) between page navigations

### ISSUE THREAD

**Issue by dimitarcnbs** [microsoft/appcenter#211]
When browsing Diagnostics Issues there are 3 filters at the top of the page: Versions, Time, Status.
While drilling down the issues details and then going back to the Issues page by using the context links at the top of the page: company/project/Diagnostics/Issues the values of these 3 filters are lost. 

It would help enormously for these filters to preserve their values while switching between pages.

**Comment by winnieli1208** [comment]
@dimitarcnbs thanks for the feedback. We've heard this request from quite a few customers and hope to have this fixed in the upcoming months. Keep an eye out on our roadmap :)

**Comment by jrahma** [comment]
This is will be great because it's annoying to change it everytime

**Comment by yunustek** [comment]
Yeah it's annoying.

**Comment by winnie** [comment]
Hey! Just wanted to let you all know we're working on this feature very soon. Should be completed in the upcoming weeks.

**Comment by jrahma** [comment]
Thank you @winnie
