### ISSUE TITLE
Appcenter build automatic distribution have check box for mandatory update

### ISSUE THREAD

**Issue by DimitriVanhaecke** [microsoft/appcenter#2111]
Here i would like to have option to always have a mandatory build

![image](https://user-images.githubusercontent.com/39410964/107033838-29ec6880-67b6-11eb-9859-40ad755ae618.png)

Just the same as if you would manually distribute a build

![image](https://user-images.githubusercontent.com/39410964/107033999-6029e800-67b6-11eb-839e-ca21117d15d1.png)

**Comment by 7RST1** [comment]
Hi, this would've been very useful. Why was this issue closed?
