### ISSUE TITLE
Webhooks for CodePush

### ISSUE THREAD

**Issue by mrousavy** [microsoft/appcenter#2115]
Since CodePush is now part of AppCenter, it would make sense to also allow triggering webhooks when a new CodePush bundle/version is released.

Right now it is only possible to trigger webhooks on full app build (apk, ipa) releases:

![Screenshot 2021-02-05 at 14 57 01](https://user-images.githubusercontent.com/15199031/107042777-6920b680-67c2-11eb-97e4-1f4c3f3c4541.png)

**Comment by Aleksandar-FFWD** [comment]
Reopen! 🗡️

**Comment by ridvanaltun** [comment]
ping

**Comment by Gustavo-Marques19** [comment]
ping
