### ISSUE TITLE
Segment App Version Analytics and Crashes

### ISSUE THREAD

**Issue by rlasker3** [Microsoft/appcenter#212]
**Describe the solution you'd like**
If we have an application in production and are logging analytics and crashes for that application we have no way to log analytics and crashes of that same app while it is in development for the next release without polluting production analytics and crashes. (release cycle segmentation)

**Describe alternatives you've considered**
Seems the only way to do this is to create completely separate applications for development and production (one for iOS and one for Android). This is misleading since it is not a separate application just a non-released version of the app.

**Additional context**

- We publish v1.0 of our app to the app stores and this “in production” app is actively logging crashes and analytics to AppCenter
- Meanwhile we begin development on version 2.0 of the app and the crashes and analytics that occur during QA testing are ALSO being logged to App Center.
- We need a way to segment the crashes and analytics of the v1.0 in production from the v2.0 that is currently in testing.

**Comment by rlasker3** [comment]
Looks like you do offer a version filter that would seem to do what I am asking. I was specifically told that you couldn't do it by support and they told me to add it as a suggestion here.

**Comment by winnieli1208** [comment]
Hi @rlasker3 - this is Winnie from the App Center PM team. Looks like there was some misunderstanding in the support ticket. As you discovered already, App Center allows you to filter diagnostics and analytics by different versions. I think our support team was trying to communicate that you can't filter data across multiple apps (so if your beta and prod versions were two individual apps in App Center). Glad you were able to find what you were looking for! :)
