### ISSUE TITLE
App Center Windows agents have old VS versions: Source Generators and .NET 5 won't work

### ISSUE THREAD

**Issue by clairernovotny** [microsoft/appcenter#2120]
The Windows agents on App Center seem to have VS 2019 16.6 on them. Source Generators and other C# 9 features require VS 2019 16.8 and later. Similarly, .NET 5 requires 16.8 or later to build with VS.

Customers are impacted - as the author of a source generator, a customer reported builds failing when attempting to use it:
https://github.com/reactiveui/refit/issues/1074

**Comment by Alex-Dobrynin** [comment]
Btw, App Center uses Mac agents for Xamarin builds

**Comment by clairernovotny** [comment]
Either way, it needs the latest Mono then.

**Comment by andrii-z4i** [comment]
On App Center we use mono to build the projects. We can't use msbuild from VS4M on our pipelines
Whatever support of C# features it provides in the latest stable version we provide to the customers. https://www.mono-project.com/docs/about-mono/compatibility/ 

As soon mono will support the c# 9 feature it will be available for our customers.

**Comment by Alex-Dobrynin** [comment]
Mono does support c# 9 because I can build this on my PC

**Comment by andrii-z4i** [comment]
@Alex-Dobrynin 

[The official installation of mono ](https://www.mono-project.com/download/stable/#download-lin)

```
mono --version
Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:33:28 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

and now to msbuild version coming with the latest mono
```
msbuild -version
Microsoft (R) Build Engine version 16.6.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.6.0.15201
```

> Mono does support c# 9 because I able to build on my PC Xamarin project which consumes c# 9

I guess you are referring to the msbuild version coming along with the [Visual Studio for Mac](https://visualstudio.microsoft.com/vs/mac/#:~:text=The%20Visual%20Studio%20for%20Mac%20editor%20supports%20powerful,by%20any%20provider,%20including%20GitHub%20and%20Azure%20DevOps.) which we are not using on our build agents.

**Comment by Alex-Dobrynin** [comment]
So, I suppose your build agents should use latest msbuild, to be able to make xamarin builds, because our company paying money for appcenter usage and thus wants to have always up-to-date environment. In our project uses c# 9 and many nugets which uses .net5. You should update your environment when these technologies are under preview, so you can release in time and don`t make you customers wait, because they wasting their money and time

**Comment by andrii-z4i** [comment]
Thank you for your feedback and suggestion.

To use the latest msbuild which is not part of mono will require a huge redesign of the build pipelines. 
Currently App Center is in the [maintenance mode ](https://github.com/microsoft/appcenter/wiki/Roadmap) and we have no capacity to take this feature request.

**Comment by brminnick** [comment]
@andrii-z4i What do you mean by this?

> We can't use msbuild from VS4M on our pipelines

App Center runs on top of Azure Dev Ops, which _can_ use the MsBuild that comes packaged with VS for Mac.

In fact, we use the version of MsBuild that is packaged with VS for Mac for the CI setup for XamarinCommunityToolkit. Here's the code from the Azure Dev Ops Pipeline YAML file that demonstrates how we're doing it:
https://github.com/xamarin/XamarinCommunityToolkit/blob/98aa44b2f6fe9cbfbd3f7f9a8a90a94d609dfb5b/azure-pipelines.yml#L193-L196

**Comment by Alex-Dobrynin** [comment]
> will require a huge redesign of the build pipelines.

It shouldn't be our headache.

> and we have no capacity to take this feature request.

Then find, because customer who paying money doesn't care about such cases.
It's the same, when my customer finds bug in production and I tell him that I cannot fix it. Then he will find a developer who will fix it. And this means - I will not have money any more from this customer

**Comment by lubiepomaranczki** [comment]
I am having the exact same issue. Is there a workaround to use latest MSBuild in AppCenter?

**Comment by noxe** [comment]
Same here - migrated everything to Refit 6 today - just to see now the builds fail on AppCenter...? :(

**Comment by Alex-Dobrynin** [comment]
Similar issue:
#https://github.com/microsoft/appcenter/issues/2136#issue-817400274

**Comment by JunkyXL86** [comment]
OMG cannot believe this is still a thing.

Why isn't there a hint in AppCenter somewhere that warns us about the latest supported C# lang?

**Comment by dansiegel** [comment]
> I image it would just require an environment variable / symbolic link change for msbuild. For example, point msbuild to /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll instead of using the current default msbuild.

@brminnick this seems like a pretty big oversight on the part of the Mono/VS4Mac team... seems to me that they should not be shipping multiple versions of MSBuild and should be ensuring that the version called from the cli is the latest build.

**Comment by mrward** [comment]
FYI - Mono 6.12.0.137 was [updated recently to include MSBuild 16.9](https://github.com/mono/mono/pull/20983).

**Comment by Krusty93** [comment]
Still not working for me. Anyone else?
My agent is still using `MSBuild 16.6.0`

**Comment by chuckgiddens** [comment]
Yes, I still have this issue with my YAML.  Why is this closed?

**Comment by jkapsouras** [comment]
I still have this issue with records and new operator (C# version 9 - https://github.com/microsoft/appcenter/issues/2136)

**Comment by robhardman** [comment]
This issue IMHO should not be marked as closed. It's very much alive in the real world, affecting customers just like me! With the greatest respect to @andrii-z4i if AppCenter is in maintenance mode, it still needs to move with production changes to critical dependencies, such as C# releases and MSBuild. If AppCenter.ms won't support me building my products when I'm using production-ready IDE, languages, packages... I simply can't use it anymore 😞

**Comment by BryanGerre** [comment]
still having this issue as well, should not be closed

**Comment by Ikarus76** [comment]
Built today and have the same issue. Why is the issue still closed?

**Comment by guirodriguezz** [comment]
Today I had the same problem, is there any solution for that?

**Comment by Osmosis311** [comment]
I was having the same issue and I solved it by changing my Mono download URL to the following:
https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.137.macos10.xamarin.universal.pkg

**Comment by hashtobewild** [comment]
> I was having the same issue and I solved it by changing my Mono download URL to the following:
> https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.137.macos10.xamarin.universal.pkg

That's great! How...?

**Comment by Krusty93** [comment]
> I was having the same issue and I solved it by changing my Mono download URL to the following:
> https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.137.macos10.xamarin.universal.pkg

I've added in my `appcenter-post-clone.sh`:

```
# Download Mono 6.12.0.137
wget https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.137.macos10.xamarin.universal.pkg

# Add execution permission
sudo chmod +x MonoFramework-MDK-6.12.0.137.macos10.xamarin.universal.pkg

# Install Mono 6.12.0.137sudo installer -pkg MonoFramework-MDK-6.12.0.137.macos10.xamarin.universal.pkg -target /
```

But it's saying

```
##[section]Starting: Restore Nuget
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
[command]/bin/bash -c /usr/bin/find . -name '*.sln' -type f -print0 | /usr/bin/xargs -0 grep -l 'xxxClient.Droid.csproj' | /usr/bin/xargs -I '{}' nuget restore '{}' -DisableParallelProcessing
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:2623) Warning: Use Cipheriv for counter mode of aes-256-ctr
xargs: nuget: No such file or directory
##[error]/bin/bash failed with return code: 127
##[error]/bin/bash failed with error: /bin/bash failed with return code: 127
##[section]Finishing: Restore Nuget
```

What's is wrong with this?

**Comment by jkapsouras** [comment]
Can you share some more details with us @Osmosis311 ? Maybe your script you used to install the 6.12 version?
Thanks in advance!

**Comment by hashtobewild** [comment]
Ok, so AppCenter is making me cranky... so, to get an actual working build I switched to Azure DevOps (if you want something done right...etc.) 

Anyway...

The "magic, secret sauce" is obviously to install the newest version of stuff, before trying to do the NuGet restore, so something like this worked for me in my YAML:

```

steps:
# Install the newest .Net Core
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    includePreviewVersions: true

# Install Newest Mono
- task: Boots@1
  inputs:
    uri: 'https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.137.macos10.xamarin.universal.pkg'

# Install Newest Xamarin
- task: Boots@1
  inputs:
    uri: 'https://aka.ms/xamarin-android-commercial-d16-9-macos'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

```
Yes, I am allowing preview versions... because I am an unreasonable, bad man. Tough, idc.

I suspect @Krusty93 is pretty close to a solution with that script code and the only issue I immediately see (which I am not sure if it is a post formatting / copy-paste error) is that the command:

```

sudo installer -pkg MonoFramework-MDK-6.12.0.137.macos10.xamarin.universal.pkg -target /

```

is marked as a comment.... also not sure that setting the target path of "/" is the right thing to do here (installing to root seems... excessive), but I honestly don't know.

**Comment by ArtS** [comment]
Just wanted to confirm that downloading the mono pkg and getting it installed fixed the issue for me. However the release readme displayed in the installer lists MSBuild as 15, which is wrong.

**Comment by Alex-Dobrynin** [comment]
> Just wanted to confirm that downloading the mono pkg and getting it installed fixed the issue for me. However the release readme displayed in the installer lists MSBuild as 15, which is wrong.

@ArtS How can I download mono pkg in app center. Should i use some script?

**Comment by ArtS** [comment]
@Alex-Dobrynin apologies no idea re app centre. I was having issues with a bunch of projects no loading locally on MacOS in JetBrains Rider.

**Comment by Akinpellumie** [comment]
> @andrii-z4i What do you mean by this?
> 
> > We can't use msbuild from VS4M on our pipelines
> 
> App Center runs on top of Azure Dev Ops, which _can_ use the MsBuild that comes packaged with VS for Mac.
> 
> In fact, we use the version of MsBuild that is packaged with VS for Mac for our [XamarinCommunityToolkit](https://github.com/xamarin/XamarinCommunityToolkit) library builds.
> 
> Here's the code from our Azure Dev Ops Pipeline YAML file that demonstrates how we're doing it:
> https://github.com/xamarin/XamarinCommunityToolkit/blob/98aa44b2f6fe9cbfbd3f7f9a8a90a94d609dfb5b/azure-pipelines.yml#L193-L196
> 
> > To use the latest msbuild which is not part of mono will require a huge redesign of the build pipelines.
> 
> I image it would just require an environment variable / symbolic link change for `msbuild`. For example, point `msbuild` to `/Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll` instead of using the current default `msbuild`.
> 
> I'm happy to jump on a call with you to discuss this.

Hello Brandon, 
do you mind explaining this further? 
I tried to resolve a similar issue with refit and AppCenter but to no avail.

**Comment by Ikarus76** [comment]
I would like to know, if this issue will be fixed. My company is paying for the build hours and I can't use it. I will cancel my plan if I can't use the build feature. I'm willing to wait until this is fixed, but not forever...

**Comment by brminnick** [comment]
The [App Center team has been clear that they are not going to fix this Issue](https://github.com/microsoft/appcenter/issues/2120#issuecomment-797598264), and I can confirm that the same problem still exists today in App Center Build. 

My recommendation is to move your Continuous Integration Builds to [GitHub Actions](https://github.com/features/actions). 

Here is the GitHub Action that I use for my CI Builds for my App Store app, [GitTrends](https://gittrends.com):
https://github.com/brminnick/GitTrends/blob/main/.github/workflows/mobile.yml

**Comment by Ikarus76** [comment]
Thanks for your hint, brminnick. sure will take a look at it. appcenter was really very easy to set up, but without the ability to build, I cancelled my plan now.

**Comment by brminnick** [comment]
## Workaround

👉 https://twitter.com/piskariov/status/1405541051461292045?s=21

**Comment by dansiegel** [comment]
You shouldn't need any work arounds... the latest stable release of Mono (6.12.0.140) which should either be available on App Center or should be be available soon ships with the newer version of MSBuild that is required for Source Generators

**Comment by j-bbr** [comment]
While this hopefully will be resolved properly soon here is the workaround we're using in our **Azure DevOps Pipeline** to build a Xamarin.Forms App (with the Xamarin.iOS task) using the installed VS4M MSbuild Version (16.10 last I checked)

1. Keep the following Bash Script somewhere in your repository
```
#! /bin/bash

mono "/Applications/Visual studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll" "$@"
```
2. Have a variable with the path to the script
```
- name: msbuildproxy
  value: $(Pipeline.Workspace)/s/your/path/to/scriptname.sh
```
3. Make script executable in Pipeline (Command Line Task)
```
- task: CmdLine@2
  inputs:
    script: 'chmod u+x $(msbuildproxy)'
```
4. Use script as build tool in Xamarin.iOS Task (some configuration omitted but the script should use all task inputs)
```
- task: XamariniOS@2
  inputs:
    solutionFile: '**/*.sln'
    configuration: 'Release'
    packageApp: true
    runNugetRestore: false
    mdtoolFile: '$(msbuildproxy)'
```

**Comment by Alex-Dobrynin** [comment]
@brminnick  after doing this workaround appcenter successfully built android but I cannot install this apk. and iOS build failed because of this issue: error NETSDK1005: Assets file '/Users/runner/work/1/s/*/*/obj/project.assets.json' doesn't have a target for 'netstandard2.1'. Ensure that restore has run and that you have included 'netstandard2.1'
but in my cproj file i have next:

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
    </PropertyGroup>

**Comment by mwerickson** [comment]
@Alex-Dobrynin I am having the exact same issue, did you find a resolution?

**Comment by DeltaJulio** [comment]
@mwerickson I was able to resolve that issue by using a newer version of nuget.

Add the following to your appcenter-pre-build.sh
```
wget https://dist.nuget.org/win-x86-commandline/v5.10.0/nuget.exe
ln -s /Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget nuget
```

**Comment by aherrick** [comment]
Hello - I've tried the **following appcenter-post-clone.sh**

```
#!/usr/bin/env bash

# Download Mono 6.12.0.145
wget https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.145.macos10.xamarin.universal.pkg

# Add execution permission
sudo chmod +x MonoFramework-MDK-6.12.0.145.macos10.xamarin.universal.pkg

# Install Mono 6.12.0.145
sudo installer -pkg MonoFramework-MDK-6.12.0.145.macos10.xamarin.universal.pkg -target /  
```

I'm receiving the following error in appcenter:

```
[command]/bin/bash -c /usr/bin/find . -name '*.sln' -type f -print0 | /usr/bin/xargs -0 grep -l 'Cellar.iOS.csproj' | /usr/bin/xargs -I '{}' nuget restore '{}' -DisableParallelProcessing
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1747) Warning: Use Cipheriv for counter mode of aes-256-ctr
xargs: nuget: No such file or directory
##[error]/bin/bash failed with return code: 127
##[error]/bin/bash failed with error: /bin/bash failed with return code: 127
##[section]Finishing: Restore Nuget
##[section]Starting: Checkout Cellar@master to s
```

**Comment by robfrancis** [comment]
> @mwerickson I was able to resolve that issue by using a newer version of nuget.
> 
> Add the following to your appcenter-pre-build.sh
> 
> ```
> wget https://dist.nuget.org/win-x86-commandline/v5.10.0/nuget.exe
> ln -s /Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget nuget
> ```

This didn't work for me. Does it matter where in the script it is added? 
I tried at both the start and end of the `appcenter-pre-build.sh` script with no luck.

Still getting the follow error

`obj/project.assets.json' doesn't have a target for 'netstandard2.1'. Ensure that restore has run and that you have included 'netstandard2.1' in the TargetFrameworks for your project.`

@mwerickson & @Alex-Dobrynin Did you manage to resolve the issue. If so, how?

**Comment by aherrick** [comment]
Thanks all I finally got this working with `appcenter-pre-build.sh`

Below is my full file:

```
wget https://dist.nuget.org/win-x86-commandline/v5.10.0/nuget.exe
ln -s /Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget nuget

#!/usr/bin/env bash

# Download Mono 6.12.0.145
wget https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.145.macos10.xamarin.universal.pkg

# Add execution permission
sudo chmod +x MonoFramework-MDK-6.12.0.145.macos10.xamarin.universal.pkg

# Install Mono 6.12.0.145
sudo installer -pkg MonoFramework-MDK-6.12.0.145.macos10.xamarin.universal.pkg -target /  

echo "MSBuild restore start"
MSBuild /Users/runner/work/1/s/FormsApp/FormsApp.iOS/FormsApp.iOS.csproj -t:restore
echo "MSBuild restore finish"
```

**Comment by eman1986** [comment]
> Currently App Center is in the [maintenance mode ](https://github.com/microsoft/appcenter/wiki/Roadmap) and we have no capacity to take this feature request.

is that to say that App Center is being replaced by something else? if so I'd like to know as my company is paying for build hours and if there's a new and better platform I'd much prefer they pay for that than something that's broken (and never planned to be fixed) and prevents me from getting a test app out to QA.

**Comment by Alex-Dobrynin** [comment]
@aherrick I have this error in appcenter build logs:

project.assets.json' doesn't have a target for 'netstandard2.1'. Ensure that restore has run and that you have included 'netstandard2.1' in the TargetFrameworks for your project.

How did you resolve this?

**Comment by aherrick** [comment]
@Alex-Dobrynin I never had this error unfortunately. Does your `appcenter-pre-build.sh` look exactly like mine?

**Comment by Alex-Dobrynin** [comment]
@aherrick yep, i have the same. but my pcl project has target netstandard2.1, yours?
but this is only on ios such behavior. android works well

**Comment by DeltaJulio** [comment]
@Alex-Dobrynin My iOS appcenter-pre-build.sh is actually different from my Android script. Boots did not work with Android, and manually installing preview Mono did not work with iOS 🤷

This is my iOS pre-build for about a month now:
```
#!/usr/bin/env bash

export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

# Install preview version of Mono for C# 9 compat
dotnet tool install --global boots --version 1.0.4.624
boots --preview Mono
boots --preview XamarinAndroid
boots --preview XamariniOS
```

**Comment by Alex-Dobrynin** [comment]
@DeltaJulio I've tried to use your script, but withot any success. I have this error:

/Users/runner/hostedtoolcache/dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: Assets file '/Users/runner/work/1/s/.../project.assets.json' doesn't have a target for 'netstandard2.1'. Ensure that restore has run and that you have included 'netstandard2.1' in the TargetFrameworks for your project. [/Users/runner/work/1/s/....csproj]

But my project has target of netstandard2.1

**Comment by DeltaJulio** [comment]
@Alex-Dobrynin I forgot to mention that I also have the following line in my appcenter-post-clone.sh

```
# Update nuget (fixes Error NETSDK1005/NETSDK1047)
sudo nuget update -self
```

I suppose you could also use the symbolic link method that I posted above for Android, but I haven't experimented any further since I got my builds running.

**Comment by Alex-Dobrynin** [comment]
@DeltaJulio Thank you sir, you saved a lot of my time!

**Comment by 15mgm15** [comment]
@DeltaJulio Can you share your android script?

**Comment by jkapsouras** [comment]
> Thanks all I finally got this working with `appcenter-pre-build.sh`
> 
> Below is my full file:
> 
> ```
> wget https://dist.nuget.org/win-x86-commandline/v5.10.0/nuget.exe
> ln -s /Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget nuget
> 
> #!/usr/bin/env bash
> 
> # Download Mono 6.12.0.145
> wget https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.145.macos10.xamarin.universal.pkg
> 
> # Add execution permission
> sudo chmod +x MonoFramework-MDK-6.12.0.145.macos10.xamarin.universal.pkg
> 
> # Install Mono 6.12.0.145
> sudo installer -pkg MonoFramework-MDK-6.12.0.145.macos10.xamarin.universal.pkg -target /  
> 
> echo "MSBuild restore start"
> MSBuild /Users/runner/work/1/s/FormsApp/FormsApp.iOS/FormsApp.iOS.csproj -t:restore
> echo "MSBuild restore finish"
> ```

Thank you! I managed to build my project using this script and also @DeltaJulio 's post-clone script for nuget update.
For aynone who wants to try @aherrick 's script, be very careful with the path of your project in MSBuild line

**Comment by softlion** [comment]
I improved it a little so it's independant of the project. Ty !

#Supports C#9
#https://github.com/microsoft/appcenter/issues/2120
wget https://dist.nuget.org/win-x86-commandline/v5.10.0/nuget.exe
ln -s /Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget nuget

wget https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.macos10.xamarin.universal.pkg
sudo chmod +x MonoFramework-MDK-6.12.0.macos10.xamarin.universal.pkg
sudo installer -pkg MonoFramework-MDK-6.12.0.macos10.xamarin.universal.pkg -target /
 
echo "MSBuild restore start"
MSBuild $APPCENTER_SOURCE_DIRECTORY/$APPCENTER_XAMARIN_PROJECT -t:restore
echo "MSBuild restore finish"

**Comment by ahmedalejo** [comment]
>  Currently App Center is in the [maintenance mode ](https://github.com/microsoft/appcenter/wiki/Roadmap) and we have no capacity to take this feature request.

# Unfortunately this is something that isn´t going to be fixed soon as the plan is to promote Azure DevOps
# As easy as the fix might be, there isn´t just no plan to put man-hours into it.

## This is a common trend for brilliant projects that just don´t pay for themselves or that the company´s strategy has been shifted to a different direction.

## I can assure you there is something different in the works that would be wildly and heavily marketed in the next few months

> # App Center Roadmap 2021
> ## Summary
> Over the past few years our team’s focus has been to deliver a first-class DevOps experience for mobile and desktop developers. A substantial part of this journey involved building the next generation of HockeyApp services for our customers. Earlier this year, we completed the HockeyApp shut down. We are now looking at what's next for the App Center service. 
>
>Just like any software engineering team, as we focused on building and scaling App Center, we accumulated technical debt that can no longer be sustained. Therefore, as we look to what is next, the App Center team will prioritize improving reliability and performance for the service. This means new feature work will be significantly reduced. Switching focus to reliability and performance wasn’t an easy decision, but nevertheless an important one.
>
>We appreciate all the time and efforts that were put into adding and voting for new features in our GitHub repo. We will continue to monitor your feature requests during this period, but will not be able to commit to a timeframe for addressing them. The following will continue to be true and a priority for the team:
>* Customers can continue building, testing, deploying and monitoring their apps.
>* We continue to be committed to our SLAs documented [here](https://azure.microsoft.com/en-us/support/legal/sla/app-center/v1_0/).
>* Framework and OS updates will continue to be supported in a timely manner. 
>* Customer support is still available and free.

**Comment by eman1986** [comment]
And that's why I'm working on switching to GitHub Actions.

I'm hoping app center itself doesn't die as their error logger is really nice and crashlytics doesn't port over well at all with C# exceptions, so I'd be in a tough spot if I had to find a new error logging service.

**Comment by softlion** [comment]
I tried azure logger, but it’s dedicated to ops, not dev at all.
For devs its not usable. Not precise. Too complicated to find any info, when this info is available.

I’m still for appcenter (for aggregated data) and seq (only when the full log of a sequence of event is needed)
