### ISSUE TITLE
Don't Dismiss Upload Window When Clicking Outside Frame

### ISSUE THREAD

**Issue by StuStirling** [microsoft/appcenter#2123]
**Describe the solution you'd like**

When I have uploaded an APK into the upload window that appears on the right side of the screen, it is easy to click off this window and then you lose progress and have to re-upload. I think it would be better to disable this functionality and instead of have to explicitly cancel the process. This would avoid losing progress and wasting time.

**Describe alternatives you've considered**

Instead of the drawer sliding in from the right, it could be a new page in the flow.

**Additional context**

This is the current screen

![Screenshot 2021-02-12 at 09 19 59](https://user-images.githubusercontent.com/4354927/107750128-80582a80-6d13-11eb-9c67-ce357c9e798d.png)

**Comment by Martinedo** [comment]
It happens to me so many times that I accidentally click elsewhere and I have to repeat the same procese again
