### ISSUE TITLE
XCUITest iOS 14 support

### ISSUE THREAD

**Issue by endless-qa** [microsoft/appcenter#2131]
**Describe the solution you'd like**
I saw that there are iOS 14+ devices when creating a new test run for XCUITest. I chose one of them, prepared my binaries properly according to your guidelines and scheduled a test run. However, the test runner wasn't able to start because there is no iOS 14 support yet.

Our app is tightly coupled to iOS 14 features and cannot be run on iOS 13 easily. Please add iOS 14 support. Otherwise, what's the point to have iOS 14 devices in the text matrix. Thanks in advance!

**Comment by andrii-z4i** [comment]
Hi @endless-qa it sounds like some issue with the test runner. We have added support for iOS 14 on Test Cloud recently.
I would recommend contacting our support using the 'Contact support' menu item in the App Center portal.

![image](https://user-images.githubusercontent.com/11600279/110618355-f4f97a00-8196-11eb-82cd-8e7e092f0d70.png)

**Comment by stefanrenne** [comment]
@endless-qa I just had a chat with Patrick from App Center and his solution is to (I quote) "The app can be compiled with the newer versions of Xcode the runner needs to be compiled separately."

**Comment by honkmaster** [comment]
@stefanrenne What does " needs to be compiled separately" concretely mean? Build the App with the iOS 14 SDK and the Runner with the iOS 13 SDK?

**Comment by honkmaster** [comment]
@stefanrenne What does "needs to be compiled separately" concretely mean? Build the App with the iOS 14 SDK and the Runner with the iOS 13 SDK? Do you have an idea, how this can be done for an iOS 14 app?
