### ISSUE TITLE
Analytics Custom Events: Provide a better visualization for high cardinality use-cases.

### ISSUE THREAD

**Issue by sylvanaar** [microsoft/appcenter#2133]
**Describe the solution you'd like**
The current display for custom properties in events is designed for low-cardinality properties. I would like a display that works more like a metric. For example, if I have an event for each network request, and i record the status code, the URL, etc, I want to also put the duration. That is really a metric - but it's pretty valid to put it there still. I might also put a request identifier there or another high-cardinality label. The top 20 may or may not be useful to show.

**Describe alternatives you've considered**
AppInsights. Wow - it's like pulling teeth every time I use it just to find the custom properties, and then none of the features in AppInsights actually work since they don't know how to process the app center events.

**Additional context**
I guess Power BI is a good option.

**Comment by fareshan** [comment]
+1
