### ISSUE TITLE
Support Yarn v2 (berry) as an install step option

### ISSUE THREAD

**Issue by tribou** [microsoft/appcenter#2134]
**Describe the solution you'd like**
I would like to be able to use `yarn` v2 in my AppCenter builds. The benefits and details are outlined in the [migration guide](https://yarnpkg.com/getting-started/migration).

**Describe alternatives you've considered**
Staying with Yarn v1 and switching to NPM are valid options, but I like the [local offline cache](https://yarnpkg.com/features/offline-cache) strategy for caching packages which appears to have the best support using yarn v2.

**Additional context**
If I try to build in AppCenter with yarn v2 currently, I get the following error:

```
(Unknown Syntax Error: Invalid option name ("--network-timeout=600000")
```

It's possible that updating the CLI args passed to `yarn` if `yarn -v >= 2` might solve this issue. Args like `--network-timeout` could be transferred to the [env variable](https://yarnpkg.com/getting-started/migration/#dont-use-npmrc-files) [`YARN_HTTP_TIMEOUT`](https://yarnpkg.com/configuration/yarnrc#httpTimeout), etc.

e.g. to set/check config values using yarn v2:

```sh
YARN_HTTP_TIMEOUT=60001 yarn config
```

**Comment by devshorts** [comment]
I can't believe it takes app center THIS long to move to allow you to write your own install command. This is basic CICD requirements.  But I feel for everyone in the same boat I'll throw in my workaround here. We were able to get yarn 2 working by doing the following

If you version yarn 2 in your repo using `yarn set version berry` the berry source is in `.yarn/releases`.  You can now hijack the release file to de-appcenter the argument list.

Note we have a few hacks in here, because appcenter foolishly doesn't detect yarn worksapces we copy a .yarn.lock into our workspace file, but then because yarn 2 ISN"T stupid, we need to remove it.  Regardless, you can get the idea:

```
#!/usr/bin/env node
const fs = require('fs');

if(process.cwd().includes("/packages/app") && process.env['APPCENTER_BUILD_ID'] !== undefined) {
  console.log("Detected to run in packages app, moving app center yarn lock hack to temp file and using root level lock instead")
  if(fs.existsSync('yarn.lock')) {
    fs.renameSync('yarn.lock', '_yarn.lock.bak')
  }
}

if(process.argv[2] === 'list') {
  console.log("List not supported")
  process.exit(0)
}

if(process.argv[2] === 'install' && process.argv[3] === '--network-timeout=600000') {
  console.log("Popping network timeout yarn flag since its not supported")
  process.argv.pop()
}

module.exports = require('./_yarn-2.4.0.cjs')
```

The file list is this
```
$ ls .yarn/releases
_yarn-2.4.0.cjs <-- the actual yarn file
yarn-2.4.0.cjs <-- the hijack file i posted above
```

Doing this we can now run yarn 2 and workaround appcenters laziness.

For what its worth my org is moving to expo build where this is a total non issue and builds are 5x as fast.

**Comment by penx** [comment]
@msftbot any reason this was closed? 😄

**Comment by Adnan-Bacic** [comment]
i just wanted to come here and mention that i just updated a project from yarn 2(2.4.2) to yarn 3(3.2.0). and i used the answer from @devshorts to get yarn 2 working on appcenter. and the same solution works for yarn 3 as well.

**Comment by tj-mc** [comment]
Still an issue in 2023 on Yarn 3.
To workaround this, you can build the RN bundle manually, then upload that to App Center, as explained in this helpful comment. https://github.com/microsoft/appcenter/issues/278#issuecomment-565466068

**Comment by gust42** [comment]
Heres my fix for yarn v4 using corepack in a monorepo.

**appcenter-post-clone.sh**
```
#!/usr/bin/env bash
echo "Running post-clone script..."

# cd to root dir
cd .. && cd ..

# Use corepack to install yarn
corepack enable

# Install dependencies here instead of the appcenter step 
yarn install 

# change this to your app path
cd clients/app

# Trick App Center into using yarn
touch yarn.lock

# Overwrite yarn.js to stop appcenter from calling it with wrong parameters
echo "console.log('overwritten yarn.js')" > /Users/runner/.cache/node/corepack/yarn/4.0.2/yarn.js
```

**Comment by hexadecy** [comment]
**appcenter-post-clone.sh**
```bash
# Use corepack to install yarn
corepack enable

# Install dependencies here instead of the appcenter step
echo "Install dependencies"
yarn install --immutable

# Overwrite yarn.js to stop appcenter from calling it with wrong parameters
yarnVersion=$(corepack yarn --version)
echo "" > /Users/runner/.cache/node/corepack/yarn/$yarnVersion/yarn.js
```
