### ISSUE TITLE
[BUG] App Center Build fails when record types are used

### ISSUE THREAD

**Issue by jkapsouras** [microsoft/appcenter#2136]
I have a Xamarin iOS project where both shared and iOS projects use c# version 9 and the DTO classes I use, are declared as records.
I can build my project in Visual Studio 2019 for mac without any problems. 
But, the build fails when I try to build the develop branch of my project using AppCenter. The errors I get are all similar to the one below:
` error CS0116: A namespace cannot directly contain members such as fields or methods`
which are referring to record types as I am showing below:
`public record ActivityLevel(int Id, string Title, string Message);`

My question is:
Is there a problem using C# version 9 in AppCenter builds? Why VS for mac builds the project without problems while AppCenter fails? 
If records are not yet supported, does AppCenter plan to support them sometime in the future?

**Comment by jkapsouras** [comment]
Builds also fails when using new operator like this:
`User = new();`
This is a C# 9.0 feature [https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator](url)
and the version of C# is declared 9 in the csproj file. 
How can I use C# 9 in App Center build process?

**Comment by Alex-Dobrynin** [comment]
Same here
#https://github.com/microsoft/appcenter/issues/2120#issue-805853902

**Comment by jkapsouras** [comment]
This is still a thing. Are we supposed to wait for a fix soon?
From today's build try:
`Domain/Base/State.cs(19,30): error CS8124: Tuple must contain at least two elements. [/Users/runner/work/1/s/DietApp/Core/Core.csproj]
  Domain/Base/State.cs(19,31): error CS1526: A new expression requires (), [], or {} after type [/Users/runner/work/1/s/DietApp/Core/Core.csproj]
  Domain/Base/State.cs(20,32): error CS8124: Tuple must contain at least two elements. [/Users/runner/work/1/s/DietApp/Core/Core.csproj]
  Domain/Base/State.cs(20,33): error CS1526: A new expression requires (), [], or {} after type [/Users/runner/work/1/s/DietApp/Core/Core.csproj]
  Domain/Base/State.cs(21,29): error CS8124: Tuple must contain at least two elements. [/Users/runner/work/1/s/DietApp/Core/Core.csproj]`

The above errors are all from records declarations.

**Comment by guirodriguezz** [comment]
Today I had the same problem, is there any solution for that?

**Comment by glintpursuit** [comment]
same here, I went back to c# 8
