### ISSUE TITLE
Opening Branch Configurations to make less API Requests to Bitbucket

### ISSUE THREAD

**Issue by ChristopherMWood** [microsoft/appcenter#2140]
**Describe the solution you'd like**
I am currently experiencing an issue that AppCenter Support has told me to post here after many back and forths with them. The issue has to do with opening branch configurations for projects on AppCenter configured against Bitbucket Repositories.

**The setup:** The project I'm on has 36 apps configured on AppCenter. 17 iOS and 17 Android. We have had this setup for over a year without issues. Originally, each pair of apps (one for each platform) had unique repositories that all synced against Bitbucket. After configuring a large handful of configurations we would get locked out of our account from too many Bitbucket API requests but last year this was only after editing 12+ repos at a time or more so it wasn't too big a deal. Recently we revamped our release to turn all of the 17 unique repositories into one and use pre build and post build scripts to do our app specific branding since all of the apps were just different forms of the same thing. Once we did this, AppCenter locks us out of opening configuration menus after only opening two menus. We hit our Bitbucket API limit almost instantly. So in summary we use 34 AppCenter projects, all configured against the same repository now and the pre-build script handles the swapping of what makes them unique now for release to the App Stores for 16 unique Apps with different bundle ids. We do not get locked out of Bitbucket for any other menu actions I can find. It is only when trying to configure a branch that we get the message in the screenshot included.

**Actions We've Taken: ** I reached out to Bitbucket and they shared my API logs with me showing me that AppCenter was making insane amounts of requests against our repo API making us hit the 1000 request per hour limit in sometimes under a minute from opening configurations. They cannot raise our API limit and we cannot switch from Bitbucket since it is my companies paid repo tool. I have talk to AppCenter Support about all of this and they said I need to open a feature request here even though I do not know what is broken, only that it is, or it is at least very inefficient against our repo setup.

- Tried clearing browser cache with no luck (and private browsing)
- Tried using a different browser with no luck (tried Chrome and Firefox)
- Tried making no requests for over a day and still locked out after two branch configuration menus opened.

How to reproduce
- Go to App Project, go to branch and open configuration menu
- Do this again for another app project and branch
- Try a third time and get locked out from Bitbucket for exceeding API request limit 

**Concerns**
Since this problem just showed up after we revamped our release process, I'm concerned that any more changes we make will lock us out of using AppCenter for good. We can make at least two configuration changes an hour but for 32 apps that becomes days of spread out work. We already took 4 days setting up our new configuration due to this and if it gets worse we will be potentially locked out of our release process. If we need to change our target version or release certificates in a pinch, we currently cannot in a timely manner.

**Thoughts on what it could be**
Our new process uses a pre-build script on AppCenter to swap app naming, branding, colors and images around based on environment variables in AppCenter. So our new "base project" contains configurations for 16 different brands of apps all based on the same base project structure. This has added a directory with tons of files and sub folders. If AppCenter, on opening a branch configuration, is polling the API recursively for any reason to check for certain files without an efficient strategy, it could be spending a lot of API requests on walking directories that do not contain any useful information. So the more complex a project gets, the worse the API requests for Bitbucket get. Given Bitbuckets low API limit of 1000 requests per hour for repository API requests per user account this would be an issue. Any insight into what requests are being made from opening a projects configuration would be very helpful here. Maybe there is something we can do about our projects structure for an easy fix.

**Describe alternatives you've considered**
The only other alternatives are changing how our repo is laid out, but without knowing what is going wrong I can't make an educated decision on this. The other alternative for us it stop using AppCenter since we cannot stop using Bitbucket and AppCenter is the only making the requests for us. I am very willing to try out some ideas if there is more information on what opening the configuration menu is doing against the Bitbucket API. If there are different project structures we can use to mitigate this I'm very willing to try it but only if there is context to try them.

Thanks in advance for any help, this issues is a huge priority for the project I'm and the client I work for so any insight or advice is greatly welcomed and appreciate.

**Additional context**
This is what we see every few times we open a project configuration
![image](https://user-images.githubusercontent.com/1214565/109820838-63709200-7c03-11eb-975a-370399d5c85c.png)

**Comment by Pranav-Dakshina** [comment]
Why is this issue closed ? was this fixed ? I'm still having the same issue

**Comment by grevolution** [comment]
The issue still exists. Why is this issue closed?

**Comment by oguzydz** [comment]
still having this issue!!!
