### ISSUE TITLE
support building React native 0.64

### ISSUE THREAD

**Issue by vonovak** [microsoft/appcenter#2144]
Hello, I'd like to ask for AppCenter to support react native 0.64

Currently, there are 2 issues in AC with regard to this

- Usage of Android Gradle Plugin 4.1.0+ is not supported at the moment.

React Native uses newer plugin now. It works with the older version too, but something that would be nice to have

- NDK version used by RN is not available in AC

```
> Task :app:stripReleaseDebugSymbols FAILED
WARNING: Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:stripReleaseDebugSymbols'.
> No version of NDK matched the requested version 20.1.5948944. Versions available locally: 18.1.5063045, 21.4.7075529, 21.4.7075529, 21.4.7075529, 22.0.7026061
```

Again, it appears that newer NDK can be used as well but would be nice to use the one specified by RN - not sure what implications this can have...

Thank you!

**Comment by gevorgsahakyann** [comment]
I got an error connected to node version :( 

<img width="877" alt="Screen Shot 2021-03-16 at 11 37 19" src="https://user-images.githubusercontent.com/45065751/111273481-4dc08b00-864d-11eb-992f-641d6153bfd6.png">

**Comment by syedquadri1982** [comment]
Is there a workaround for this with react native 0.64?

**Comment by marcshilling** [comment]
@syed I've been using NDK version 21.4.7075529 and Gradle 4.0.2 and everything seems to be working OK for now. I'd still feel a lot better using the RN 0.64 defaults, so hopefully this gets fixed soon.

**Comment by Gitarcitano** [comment]
I just have set the ndkVersion to 22.0.7026061 and that is working fine with RN 0.64 (Android and iOS)

**Comment by maxckelly** [comment]
How have you guys managed to workaround this? I'm getting the below errors for iOS and Android. Would appreciate any help

iOS
```
[!] Invalid `Podfile` file: cannot load such file -- /Users/runner/work/1/s/node_modules/@react-native-community/cli-platform-ios/native_modules.

 #  from /Users/runner/work/1/s/ios/Podfile:2
 #  -------------------------------------------
 #  require_relative '../node_modules/react-native/scripts/react_native_pods'
 >  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
```

Android: 
```
Welcome to Gradle 6.7!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
Gradle 6.7

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/runner/work/1/s/android/settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'aLifeLived'.
> Could not read script '/Users/runner/work/1/s/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Error: /Users/runner/work/1/s/android/gradlew failed with return code: 1
    at ChildProcess.<anonymous> (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/1.128.0/node_modules/vsts-task-lib/toolrunner.js:569:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
##[error]Error: /Users/runner/work/1/s/android/gradlew failed with return code: 1
```

**Comment by douglasjunior** [comment]
Sorry guys, my problem was actually with the `jetifier 2.0.0`: https://github.com/mikehardy/jetifier/issues/67

Everything working with `React Native 0.64.1`, `Gradle Plugin 4.1.0` and `NDK 20.1.5948944`.

**Comment by douglasjunior** [comment]
@marcshilling Unbelievable, but yes. 

I setup two apps, a new app created in `RN 0.64.1`, and another app created 2 years ago and updated to `RN 0.64.1`. Both with default `Gradle Plugin 4.1.0`.

**Comment by maxckelly** [comment]
Has anyone else been able to do this? I still get build failed.

**Comment by yvbeek** [comment]
@MatkovIvan Do you have an update for us on when this going to be fixed?

Third party libraries are now requiring Gradle 4.1+. Which means that we have to use older versions for now and can't get the latest bug fixes.

**Comment by ivankostic85** [comment]
@maxckelly @yvbeek there is a workaround in order to use Gradle 4.1.x

Public documentation has recently been updated
https://docs.microsoft.com/en-us/appcenter/build/android/code-signing#setting-up-code-signing

Another alternative is the latest 4.2.0 version

**Comment by maxckelly** [comment]
@ivankostic85 - Seems to still be failing even with the above suggestions 

```
##[error]Error: Failed find: ENOENT: no such file or directory, stat '/Users/runner/work/1/s/node_modules/@babel/register/node_modules/make-dir/node_modules/.bin/semver'
```

**Comment by victorkvarghese** [comment]
hi any workarounds to this issue
 i tried using jetifier version 1.6.6, but it triggered some other issues

**Comment by cruinh** [comment]
Also looking for any update on this.  My team needs to get RN 0.64+ in place for several reasons but this is blocking us.

**Comment by matt-dalton** [comment]
We're now getting this on React Native 0.63.4 builds. Is the only solution to upgrade two versions to 0.65.x?

**Comment by henrique-c-ladeira** [comment]
I had a problema with RN 0.63.4 builds in AC. Managed to solve it by adding in android > build.gradle:

```
buildscript {
    ext {
        ndkVersion = "20.1.5948944"
    }
    
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
   }
```

and in gradle > wrapper > gradle-wrapper.properties

`
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
`

**Comment by fuchien** [comment]
@henrique-c-ladeira
I put the same config, but here we are using RN 0.63.3 (didn't work), I upgrade now to 0.63.4, is working!!
Thaaank yooou!!

**Comment by Arkan4ik** [comment]
@henrique-c-ladeira @fuchien if you remember could you tell please did you have jetifier? I got an error and your solution does not work for me
![image](https://user-images.githubusercontent.com/23438777/164107510-f41bf501-dda8-46a2-bdb4-8a91303700a1.png)

**Comment by douglasjunior** [comment]
@Arkan4ik try to downgrade your jetifier to the 1.x version.

**Comment by Arkan4ik** [comment]
@douglasjunior yep, 1.68 works fine. Seems like due to console.warn in 2.0.0 version. thanks

**Comment by douglasjunior** [comment]
Version 2.0.0 is incompatible with AppCenter due to `console.warn`.

https://github.com/mikehardy/jetifier/issues/67
