### ISSUE TITLE
Unable to Distribute the App 

### ISSUE THREAD

**Issue by rkhandelwal17** [microsoft/appcenter#2145]
Hi Team,

Since this morning we are unable to upload and distribute our iOS app to the Distribution groups
Is this due to this issue : App Center is encountering issues with AAD. 

Below is the error:-

16-Mar-2021 16:57:27 | Release upload failed
-- | --
16-Mar-2021 16:57:27 | /usr/local/lib/node_modules/appcenter-cli/dist/commands/distribute/release.js:360
16-Mar-2021 16:57:27 | const releaseId = response.release_distinct_id;
16-Mar-2021 16:57:27 | ^
16-Mar-2021 16:57:27 |  
16-Mar-2021 16:57:27 | TypeError: Cannot read property 'release_distinct_id' of undefined
16-Mar-2021 16:57:27 | at ReleaseBinaryCommand.<anonymous> (/usr/local/lib/node_modules/appcenter-cli/dist/commands/distribute/release.js:360:48)
16-Mar-2021 16:57:27 | at Generator.throw (<anonymous>)
16-Mar-2021 16:57:27 | at rejected (/usr/local/lib/node_modules/appcenter-cli/dist/commands/distribute/release.js:12:65)
16-Mar-2021 16:57:27 | at processTicksAndRejections (node:internal/process/task_queues:94:5)

Kindly let me know once this issue will be resolved as our QA's are blocked due to this

**Comment by soulzidda** [comment]
+1 any information would be welcomed. this only started last night

**Comment by ernesernesto** [comment]
also encountering this, getting invalid token today. Changed the token and then getting error with 'undefined'

even manually uploading via web is no go
<img width="589" alt="Screen Shot 2021-03-16 at 19 28 28" src="https://user-images.githubusercontent.com/3048906/111308905-d65f1b80-868d-11eb-8f9e-92e92a6b21bb.png">

**Comment by soulzidda** [comment]
Spoken to support (I don't use twitter so I didn't know of this) They are aware of the issue. a symptom is either an invalid token or a 403 error. so we just need to sit tight for now. keep an eye on https://twitter.com/AppCenterStatus?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor for more info
