### ISSUE TITLE
Xamarin.UITest and .NET Core (.NET 5?)

### ISSUE THREAD

**Issue by LiohAu** [microsoft/appcenter#2148]
Hello,

I do not know if this is still on the roadmap, but would it be possible to have Xamarin.UITest working with .NET Core or .NET 5 ?

**Comment by MihaMarkic** [comment]
Same here, I saw questions around since a couple of years now and ... nothing. If at least it was open source.

**Comment by keozx** [comment]
I don't even know where to post X.UITest issues, I only see silent releases in nuget but this should be open sourced quickly
