### ISSUE TITLE
Add building react native projects in development mode feature.

### ISSUE THREAD

**Issue by tsdmrfth** [microsoft/appcenter#215]
Our biggest problem is changing base server api url depends on __DEV__ flag of react native while testing our app with our company team. Once AppCenter builds our app the __DEV__ flag is changing as false and that's why our base server api url is refers to production url and this is not we want. We should have an option in build config to decide when build react native project in development or production mode.

**Comment by tsdmrfth** [comment]
Any progress? If your team have no time for this job i think i can do it with a pull request because we need this feature in an urgent @nrajpurkar

**Comment by nrajpurkar** [comment]
@tsdmrfth taking a look into this and will update soon!

**Comment by nrajpurkar** [comment]
@tsdmrfth will keep this open as a feature request, but not something the team has the ability to pick up right now 😢 We'll reevaluate in the future!

**Comment by tsdmrfth** [comment]
Still no progress. OMG. This feature is really a need for every developer who uses React Native and AppCenter I think.
