### ISSUE TITLE
Build automatically each new merge request from GitLab

### ISSUE THREAD

**Issue by ericledonge** [microsoft/appcenter#2153]
When I was working on Web Apps, I was using Github + Netlify and I was able to easily setup Netlify to build automatically each new pull request. Since I am working on Mobile Apps (React Native), GitLab + App Center, my team is using a test branch and I have to merge my feature branch in the test branch, which is the only one to be build and published.

Is it possible to setup App Center to build automatically each new merge request from GitLab, please?

<img width="826" alt="Capture d’écran, le 2021-03-18 à 15 02 54" src="https://user-images.githubusercontent.com/6333396/111683972-86eb2d80-87fc-11eb-8359-ba4064874f1e.png">

**Comment by norayr93** [comment]
I am having the same issue. Is there any workaround for this? There are no options in the build configs of app-center.
