### ISSUE TITLE
Add support for .Net Desktop Applications

### ISSUE THREAD

**Issue by digitaldias** [microsoft/appcenter#216]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by digitaldias** [comment]
Hello! 
I've been developing a pure .Net desktop application, and was intrigued by appCenter and its ability to distribute development versions to specific testers. 

So I hooked up my application to the appCenter, chose windows, and tied it all up to my Azure Devops source. 

Now, I'm getting the application to build, even though it is NOT an UWP app. The shortcomings are, as I see them: 

- No unit-test runs
- The build does not execute a publishing step, so the artifacts built are not published
- Since there are no artifacts, there is nothing to distribute

I guess I'm one of those guys who still believe in desktop applications, and would love to be able to use appcenter, MAINLY for the ability to distribute test-versions to specific groups of people, but also for the ability to run the Analytics part.

**Comment by digitaldias** [comment]
I would also add that I'd love the ability to create a ZIP package for distribution that contains the result equivalent of publishing from VS2017 - using the option "Athe application is available offline as well) that creates a self installer. This is something Azure Devops doesen't offer either.

**Comment by patniko** [comment]
Referencing #53 #85

**Comment by rido-min** [comment]
@digitaldias have you looked at the [packaging project](https://aka.ms/wapproj) to produce APPX/MSIX packages? these tachnologies can replace ClickOnce and are easily configured from AzureDevOps.

**Comment by cmielke** [comment]
This issue is preventing us from migrating completely to App Center. We currently distribute our .NET application as an MSI through HockeyApp. I do not think we can use APPX/MSIX at this time because we still support Windows 7, and from my understanding APPX/MSIX is not supported on Windows 7. Please consider including this issue on your roadmap.

**Comment by leoniDEV** [comment]
[MSIX is supported on Windows 7](https://github.com/Microsoft/msix-packaging#windows-7-support)

**Comment by cmielke** [comment]
@leoniDEV I stand corrected. Thank you! I will investigate MSIX and see if it will meet our needs.
