### ISSUE TITLE
AppCenter mobile app in Huawei AppGallery

### ISSUE THREAD

**Issue by Symorp** [microsoft/appcenter#2163]
**Describe the solution you'd like**
Hello, currently there is no way how to download Appcenter application into Huawei phones without GMS. So we can't distribute our application for internal testing into Huawei phones.

**Describe alternatives you've considered**
There are some alternatives, like using Huawei AppGallery internal distribution or simply install APK through Visual Studio. But we would like to have a mostly similar way how to make internal testing across all devices.

**Additional context**
It would be nice if you add AppCenter app into Huawei AppGallery so we can use it like on classical Android phones with Google services.

**Comment by DmitriyKirakosyan** [comment]
hi @Symorp 

Thank you for reaching out to us!

Unfortunately, we are not supporting Android Tester App anymore.
We removed the tester app from Google Play recently as its main functionality violates Google Play policy. In a few words, the app is not allowed to install other apps. See [Device and Network Abuse](https://support.google.com/googleplay/android-developer/answer/9888379) for more info.

Sorry to tell you that, but at this moment there are no plans to distribute the Android Tester App anywhere.
Please use App Center Portal to install your android app releases.

Closing this issue.
Feel free to ping me if you have any additional questions.
