### ISSUE TITLE
Enable "Automatically manage devices" for shared distribution groups

### ISSUE THREAD

**Issue by filipengberg** [microsoft/appcenter#2164]
**Describe the solution you'd like**
I would like to be able to enable "Automatically manage devices" for shared groups.

This would make it possible for us to reuse the shared groups created at the organization level across multiple apps. We can reuse them now but since "Automatically manage devices" cannot be enabled the shared group functionality is unusable for us right now.

**Describe alternatives you've considered**
Right now we either have to manually add device ids and reprovision for each app when new people are added, or we have to create and update separate distribution groups with the same people for each app to be able to set "Automatically manage devices". This is very hard to manage when having many apps that should have the same distribution group setup.

**Additional context**
I understand that there might be some technical limitation if the shared group is set to "public" (enabling anyone with a public link to download the app)? But if I have set the group to "private", shouldn't it be possible to enable "automatically manage devices" then?

I am aware of the 100 devices limit from Apple but in many cases this is not a problem and I think it should be up to the user to be responsible for this.

**Comment by filipengberg** [comment]
Why has this issue been closed?

**Comment by micnguyen-wesdigital** [comment]
Agreed - this is an issue I noticed that was very hard to debug properly. My iOS builds were not being automatically assigned and I went down a rabbit hole of figuring out my Apple Certs/Provisioning profiles only to realise the option of `Automatically manage devices` is only available to groups that are per-app scoped and not Org-scoped.
