### ISSUE TITLE
[security issue] invitations to appcenter do not consider if valid recipient is signed in

### ISSUE THREAD

**Issue by vonovak** [microsoft/appcenter#2165]
hello, I'd like to report a security issue:

steps to repro:

1) sign in to appcenter with my personal account (xyz@gmail.com)
2) get invitation to appcenter to my company email (xyz@company.com)
3) open the invitation link
4) I can access my company's app through my personal account

I don't think this is how it should be. 

Thank you!

**Comment by alexChernyatiev** [comment]
Hi @vonovak!
Thanks for letting us know about this issue
I can't reproduce the issue. Could you please look at my steps and indicate what am I doing wrong?
My steps:
1. sign in to AppCenter with my personal account (xyz@gmail.com)
2. create a new app
3. add my company email (xyz@company.com) to collaborators of app
4. click **Accept invitation** button from the email
5. click **Join app** button
6. I was redirected to the app page (https://appcenter.ms/users/myName-gmail.com/apps/appName)
7. Tried to use the link for my company app (https://appcenter.ms/users/myName-company.com/apps/appName123) and get an error page
8. Tried to get all my company apps (https://appcenter.ms/users/myName-company.com/applications/) and get a page with apps from my **personal account**
