### ISSUE TITLE
Download dsym file via UI for iOS builds created on AppCenter

### ISSUE THREAD

**Issue by nuclearsam** [Microsoft/appcenter#217]
**Describe the problem you are facing**
The iOS build generated on AppCenter only allow us to download .ipa files. There is no way we can download the generated .dsym files. 

.dsym files might be required outside of AppCenter for third party bug reporting tools.

.dsym file is not always available from AppStoreConnect portal.

**Describe alternatives you've considered**
As a workaround a post-build-script can upload the dsym file to third party location.

**Describe the optimum solution you prescribe.**
There should be an option to download the .dsym file anytime from builds list.

**Comment by germangb** [comment]
I was able to locate them under the url `https://appcenter.ms/orgs/{organization}/apps/{app}/crashes/mappings`.

It looks like part of the UX flow is broken for iOS.

**Comment by patniko** [comment]
Referencing #130

**Comment by winnieli1208** [comment]
Hi @nuclearsam we do allow users to download the .dsym file from the builds list. Are you able to see a download option as shown below? 

![image](https://user-images.githubusercontent.com/8868628/54934167-47262f80-4edb-11e9-8195-015ba60ab287.png)

**Comment by nuclearsam** [comment]
Hi @winnieli1208, I see it now.. Thank for the help.

**Comment by winnieli1208** [comment]
Great, I'm going to close this issue for now. Feel free to reach back out if you have any other questions.

**Comment by nuclearsam** [comment]
Hi @winnieli1208 

It seams the option to download the symbol file is not present on the releases page.
<img width="1217" alt="Screenshot 2019-05-13 at 7 02 21 PM" src="https://user-images.githubusercontent.com/4591834/57625698-029d4300-75b2-11e9-9c53-17b1e7b7bc16.png">

 It is available on the Builds page as you mentioned earlier, however, it would a great help if this could also be made available on the releases page directly. As its difficult to find the build from the releases page. 

Thank you.
Sam

**Comment by winnieli1208** [comment]
@nuclearsam great suggestion. We don't have any immediate plans to do this but I will update you if anything changes. Thanks!

**Comment by afreenhossain** [comment]
It would be great for teams who are using appcenter only to distribute builds, but not using the SDK. This is the only reason we are having to use other means to distribute dsym files. Is this going to be implemented in near future?

**Comment by afreenhossain** [comment]
It would be great to add it in the releases page for teams that are using appcenter for build distribution only. We are having to use other means to distribute dsyms just because of this issue.

**Comment by justinairbase** [comment]
@winnie Is there any update on these?

**Comment by nullptr2this** [comment]
Would love to get an update or a fix for this.  As far as I can tell builds are not maintained if their associated branch is deleted for whatever reason.  There go all of those DSym files.

**Comment by justinairbase** [comment]
@nuclearsam Can you please share the post build script you used. I wasn't able to figure out the dsym file path or name of the from the env vars. I'm trying to upload the dsym to firebase console.

**Comment by Kapusch** [comment]
> Hi @nuclearsam we do allow users to download the .dsym file from the builds list. Are you able to see a download option as shown below? I'll confirm with the engineering team to see if there are any known issues with this flow.
> 
> ![image](https://user-images.githubusercontent.com/8868628/54934167-47262f80-4edb-11e9-8195-015ba60ab287.png)

Sadly, if the build succeeds, but the distribution phase failed, then symbols will not be proposed for download.

**Comment by Kapusch** [comment]
I actually found a workaround in that case:
1. copy the link behind "Download symbols",
2. open a new tab and paste the link,
3. replace the build number by the one for which you would like to download the symbols.

**Comment by EmilAlipiev** [comment]
When the build is completed with a release, Build will be removed and you dont have access to the Build and related downloads. 
Thats not a suggestion but this is a bug but probably Appcenter team will not resolve this as they dont add anything on Appcenter any longer
