### ISSUE TITLE
View Crash Rate % 

### ISSUE THREAD

**Issue by ryang1428** [microsoft/appcenter#218]
**Describe the solution you'd like**
In the AppCenter UI, I would like to easily be able to see my apps current crash % (crashes per session), not just the # of crashes. 

The crash rate the most valuable piece of data for our consumer apps. We are looking to move to AppCenter for our crash reporting (currently using Crittercism), but this is a big thing that is missing from AppCenter. We look at our rates daily & strive to stay under a rate of 0.5% (meaning 0.5% of sessions experience a crash). This is a common metric available on all other crash reporters we have looked into. 

**Describe alternatives you've considered**
There may be a way to calculate this from hitting your APIs to get the # of crashes & do some with with the # of sessions, but this is not ideal. 

**Additional context**
We would want to see the crash % per build number / version.

**Comment by winnieli1208** [comment]
Hi @ryang1428 - thanks for the feature request! This is definitely on our radar but not on our immediate roadmap. I'll update this thread if there's any progress. 

In the meantime, you can use our [sessions API](https://openapi.appcenter.ms/#/analytics/Analytics_SessionCounts) to get the total number of sessions in a timeframe and then use the [error counts API](https://openapi.appcenter.ms/#/errors/Errors_CountsPerDay) to get the total number of crashes. 

I understand this isn't an ideal experience but hopefully that helps a bit!

**Comment by baolongnt** [comment]
+1 This is  key metric for us as well.
