### ISSUE TITLE
[ BUG ] react native app startup very slow with enabling hermes building over appcenter

### ISSUE THREAD

**Issue by ebrahimhassan121** [microsoft/appcenter#2189]
**Describe the solution you'd like**
building the app on pc generates apk with startup time 2 seconds
building using appcenter generates apk with startup time 12 seconds

i think that's releated to ndkVersion
as specifiying ndkVersion in app/build.gradle was ignored 
`WARNING: Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Unable to strip the following libraries, packaging them as they are: libucrop.so.
`
RN :0.64
ndkVersion "21.4.7075529"
gradle version com.android.tools.build:gradle:4.0.2
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
build.gradle `// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        googlePlayServicesVersion = "17.0.0"
        ndkVersion = "21.4.7075529" //"20.1.5948944"
        

    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.2")
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0'
        classpath 'com.google.firebase:perf-plugin:1.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
`

**Describe alternatives you've considered**

**Additional context**

**Comment by dtsolis** [comment]
Is there any update on that? I don't know if it's related to the ndkVersion but I do find myself getting a "slower" app when building the app on AppCenter.

When I run gradle tasks `:app:assembleRelease :app:bundleRelease` locally, the app has a high-speed startup time.
