### ISSUE TITLE
Full list of commits on Build

### ISSUE THREAD

**Issue by marcoburato** [microsoft/appcenter#219]
On GIT, it's common to commit locally and only push after a while. This makes sense for a number of reasons, for instance:
- better describe multiple changes that are related but affect separate parts of the program
- working offline
- not trigger a time consuming CI build for trivial changes

When pushing multiple changes, App Center builds only the latest revision, which makes sense. The problem is that the "commits" list in the Build section only shows the commit that was built, skipping all the previous commits that were part of a push.
This means that:

- It's not possible to trigger a build of one of the skipped commits, which could be handy to pinpoint the exact commit that broke the build
- It's not clear what's included in a build. One has to check the version control system.

**Describe the solution you'd like**
It would be nice to see the full list of commits on the Build section, where the skipped commits are shown with "Skipped" as status. The user could then select one of those commits and click a "Build" button to build that commit, if he desires so.

**Describe alternatives you've considered**
The only alternative right now would be to push at every commit AFAIK.

**Comment by aaronrogers** [comment]
While that sounds like a really cool feature, I'd simply like to see the list of commits and their messages in the build.  This feature could be split in two.  The first part simply to show the commits and the second to trigger a build for a specific commit.  Hopefully the first one is pretty easy to do as I don't like build messages that say `Merge branch 'dev'`.

**Comment by nrajpurkar** [comment]
Thanks for the feature request and the additional information on your development lifecycle @marcoburato . I can see how that would add value and thanks for calling out the two separate pieces @aaronrogers. We'll keep tracking this as a potential future improvement.

**Comment by eemshi** [comment]
+1 for ability to build from any commit in a branch 💯
