### ISSUE TITLE
Carry session across multiple on-device sessions

### ISSUE THREAD

**Issue by BenWoodford** [microsoft/appcenter#2197]
**Describe the solution you'd like**
Sessions are great, except for more passive apps. We have an on-location AR app for a client that we'd really like to get session data for, but because the user will usually scan a target, do the activity, then put their phone in their pocket before moving on to the next one (usually with a >5 minute gap between scans) we don't get very good session data for their visit. If there was a way to treat an entire calendar day as one session (as they'd generally only visit once per day) or something like that, even if the app itself is killed and restarted, that'd be much more useful as we could then see data such as the order they do the activities in, etc

This may also tangentially be feedback for Azure Insights, as it's the "User Flows" tool on there that we view this through - as there's no way to Scope by anything except Session or Operation we can't tell how the user users the experience across multiple sessions in one day

Unless there's any way to already do this?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by russelarms** [comment]
Hi @BenWoodford! Thanks for reaching out.
We'll consider this feature request, but I don't have an ETA for this yet.

For reference, similar requests:
https://github.com/microsoft/appcenter-sdk-dotnet/issues/682
https://github.com/microsoft/appcenter-sdk-android/issues/1495
