### ISSUE TITLE
Xamarin.Android 11.2 support in App Center

### ISSUE THREAD

**Issue by lewisgauss** [microsoft/appcenter#2199]
**Describe the solution you'd like**
Able to select Xamarin.Android 11.2 in the build config. 

**Additional context**
Xamarin.Android 11.2 has a lot of improvements and bugfixes that are critical to our application. We cannot target Xamarin.Android 11.1 or 11.0 because of it. This is the issue - https://github.com/xamarin/xamarin-android/issues/5251 

Our project also fails to build using 11.1 and 11.0.

**Comment by russelarms** [comment]
Hi @lewisgauss, where did you face this problem? On the App Center portal or with the SDK?

**Comment by lewisgauss** [comment]
App Center still doesn't have Xamarin.Android 11.2 support when building for Android. 

The issue was with Xamarin.Android, it's since been fixed, and it's been released for a long time now. 

So, the issue is with App Center not having it still, even today. 

Hope that clarifies! 😀

**Comment by ameenaliu** [comment]
Would you happen to have update on this @russelarms? 

Xamarin.Android 11.2 has been released for a while now - [https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.2](https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.2). But it is still not supported as a SDK option.

![image](https://user-images.githubusercontent.com/24752631/120135266-7abf1b80-c202-11eb-8f56-26f72e9ecc74.png)

**Comment by russelarms** [comment]
We have this feature in the backlog, but no ETA yet.

**Comment by roubachof** [comment]
you can use Xamarin.Android 11.2 thanks to Boots: https://devblogs.microsoft.com/xamarin/boots-xamarin-ci/

just create a `appcenter-post-clone.sh` file at the root android project. and add this:

```
#!/usr/bin/env bash
# App Center custom build scripts: https://aka.ms/docs/build/custom/scripts

export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

dotnet tool install --global boots

# Workaround instead of restarting shell
# see: https://github.com/dotnet/cli/issues/9114#issuecomment-494226139
export PATH="$PATH:~/.dotnet/tools"
export DOTNET_ROOT="$(dirname "$(readlink "$(command -v dotnet)")")"

# https://github.com/xamarin/xamarin-android
boots https://aka.ms/xamarin-android-commercial-d16-9-macos
```

**Comment by ameenaliu** [comment]
Thanks  for the suggestion @roubachof. I will try the Boots approach.
