### ISSUE TITLE
[Feature] Clone branch configurations

### ISSUE THREAD

**Issue by SandroMachado** [microsoft/appcenter#22]
**What App Center service does this feature apply to?**
Build system

**Describe the solution you'd like**
We should be able to copy build configurations to other branches. 

**Additional context**
Every time we want to create a build from a branch, we need to copy all the configurations. The objective of this feature is to simplify this process.

**Comment by hitmanmcc** [comment]
Can we please make this happen? It's a useful feature!

**Comment by adcuz** [comment]
This would be very useful, currently it is really difficult when you have many environment variables. I have resorted to building a tool dedicated to mass-updating them via the API.

**Comment by struct78** [comment]
+1a

**Comment by RWOverdijk** [comment]
Yes please, this would be really nice. Feature builds are near impossible without configuring each branch now.

I haven't tried this yet but I think it should be possible using these two APIs:

- https://openapi.appcenter.ms/#/build/branchConfigurations_get
- https://openapi.appcenter.ms/#/build/branchConfigurations_create

**Comment by patniko** [comment]
The issue with those API's are the missing secrets @RWOverdijk. We need to do some work on our end to allow you to clone the configs with secrets, certificate, provisioning profiles, keystores, etc intact.

**Comment by RWOverdijk** [comment]
Maybe configs shouldn't be branch based at all? Maybe build configs should be their own thing. That way you can add powerful features such as wildcard branch names (feature/* for example).

That would be really really neat 😄

Met vriendelijke groet / Kind regards,

Roberto Wesley Overdijk

SpoonX
Founder

M. +31 (0)6 15 55 32 43
W. www.spoonx.nl
E. wesley@spoonx.nl
KvK. 60422696

**Comment by armyofmarkness** [comment]
Being able to clone build configurations would be very useful.

**Comment by patniko** [comment]
Adding this to next months iteration plan so we can start designing a proper solution for this.

**Comment by ogezue** [comment]
On buddy build there is a default configuration that is applied automatically. Developers can override it if needed.
Please copy every feature of buddybuild as this has been the best mobile ci/cd on the market (feedback by screenshot, ...)

**Comment by RWOverdijk** [comment]
Yes. I second that. But, buddybuild has betrayed us all. Leave out the betrayal bit when cloning features.

I cri evrytim :(

**Comment by chrisheninger** [comment]
From what I've been building– the biggest pain point has been needing to re-upload the provisioning profile, certificates, or keystore each time I want to deploy a new branch.

If cloning branch configurations will also pull the signing info over– this feature will be amazing. 🙏

**Comment by appfabtech** [comment]
> Yes. I second that. But, buddybuild has betrayed us all. Leave out the betrayal bit when cloning features.
> 
> I cri evrytim :(

Don't tell me, I met them in october 2017 in Verona for #pragmamark conference. And they convinced me to move on their platform. And they assured me they would never sell...
They already sold to apple.

**Comment by nrajpurkar** [comment]
Added a PR for our initial proposal for this feature - leave any feedback you have on this experience!

**Comment by yyou** [comment]
Instead of implementing something "copying settings from another build configuration" in the build configuration UI (if my understanding is correct), how about create a new UI for users (mainly developer) to maintain a list of build configurations. User can create / edit / delete / copy-from-another a build configuration in this UI.  then in the current branch list UI, we don't need to open the build configuration by clicking the small icon at the right side. We just "link" the branch with a build configuration by selecting a build configuration from a drop-down list.

**Comment by RWOverdijk** [comment]
@yyou take a look at the proposal pr and the comments. I share your opinion and it's written down there already.

**Comment by jjhampton** [comment]
I agree with @yyou 's [comment](https://github.com/Microsoft/appcenter/issues/22#issuecomment-481076575) - it would be useful if build configurations were not strongly coupled to branches.

**Comment by dgobaud** [comment]
:+1: really need this!

**Comment by marstall** [comment]
or configure builds via a file checked into your repo, a la chef?

**Comment by RWOverdijk** [comment]
@marstall There are passwords involved. Please don't put that in your repository.

**Comment by marstall** [comment]
@rwoverdijk - agreed. recommend using ENV vars for sensitive stuff like that. there are more advanced ways - see chef data bags, ansible vault ... worth a dive.

**Comment by abdeweese** [comment]
> or configure builds via a file checked into your repo, a la chef?

This is the answer.  I just created a similar feature request here: 
https://github.com/microsoft/appcenter/issues/437

**Comment by piterwilson** [comment]
Decoupling configurations from branches would be amazing. At the moment i am "cloning" (via `branchConfigurations_get` and `branchConfigurations_create` ) from my `develop` branch but it seems somehow less than ideal. Configurations could be their own thing, which can be applied to branches.

**Comment by nrajpurkar** [comment]
We have shipped the ability to clone existing branch configurations today! Take a look at our [documentation](https://docs.microsoft.com/en-us/appcenter/build/branches) for more info. Happy building! ![bitmoji](https://render.bitstrips.com/v2/cpanel/6ed0a0da-32f3-4473-859a-27dc19fc58eb-1af191b7-95d8-4aed-b96c-2c83e1cb796b-v1.png?transparent=1&palette=1&width=246)
