### ISSUE TITLE
Support dexguard mappings.txt

### ISSUE THREAD

**Issue by kevbry** [microsoft/appcenter#220]
**Describe the solution you'd like**
For Android builds obfuscated using Dexguard, uploading a mappings.txt file has no effect on the readability of stack traces in Appcenter. Appcenter should be able to use dexguard mappings to deobfuscate stack traces. 

**Describe alternatives you've considered**
For now I've built my own tool to use uploaded dexguard mapping files against the appcenter error APIs. This is becoming a source of frustration, as changes to the Appcenter APIs around crashes/errors seem to be ongoing and maintenance of my own tooling to keep up with them is taking up too much time. Other exception tracking tools do support dexguard mappings so we'll probably be forced to move to one of them if Appcenter doesn't add this feature soon.

**Comment by easterapps** [comment]
any progress in this topic?

**Comment by winnieli1208** [comment]
Hey apologies for the delay. No updates yet but I will sync up with our team this week to see what work is required to support DexGuard. Thanks for the patience!

**Comment by easterapps** [comment]
new informations?

**Comment by winnieli1208** [comment]
@easterapp App Center currently only supports deobfuscating crashes for ProGuard. Unfortunately, due to other priorities right now, we don't have immediate plans to add support for DexGuard. 

We will continue to evaluate this feature request and I will post here with any updates.

**Comment by smithaaron** [comment]
@winnieli1208 Thanks for the answer. That rules out App Center for us.

**Comment by lukaville** [comment]
@winnieli1 any updates on this? thanks

**Comment by winnieli1** [comment]
Hi @lukaville - I just added this to our roadmap. I don't think we'll get to it in time for this month but we'll add it to next months iteration plan. Thanks for the patience!

**Comment by winnie** [comment]
We recently added support for DexGuard. Closing this issue for now but feel free to file a support ticket if you have any issues. Thanks!
