### ISSUE TITLE
Have an option to install google-services.json

### ISSUE THREAD

**Issue by dsame** [microsoft/appcenter#2204]
**Describe the solution you'd like**
Many android apps and some ios have to have google-services.json file in the project tree. It contains some sensitive information and should not be stored in repo. Having ability to set its content and path would be nice feature

**Describe alternatives you've considered**
Copy google-services.json to env variable and echo it in the post-clone.sh

**Additional context**
my post-clone script

#!/usr/bin/env bash

# path is MODULE/src/VARIANCE/google-services.json
echo "create app/src/release/google-services.json"
echo $GOOGLE_SERVICES > app/src/release/google-services.json
ls -la app/src/release

**Comment by dougg0k** [comment]
Check out Setup AppCenter forward https://dev.to/adamgold/how-to-setup-appcenter-with-gitlab-without-pushing-secret-files-4mk8

**Comment by dsame** [comment]
@dougg0k yes, this works, but i requested the possibility to upload the google-services.json like we do with the signing keys
