### ISSUE TITLE
Add Multilingual Support for Release Notes/

### ISSUE THREAD

**Issue by ezathashim** [microsoft/appcenter#2207]
**Describe the solution you'd like**
When uploading a new release, currently we only have one option when entering the 'Notes' for the release. This is limited to one single language. Obviously, we can cram different languages within the same 'Notes' field, but this is not ideal when dealing with many different languages or very long notes.

A possible solution would be to have a language picker button in the release 'Notes' view whereby the user can select a language and enter the notes for that target language. In this way, the user can enter notes for various languages for a particular release. English should probably be the default base language. When uploading the app.zip file, AppCenter could look through the app bundle and see what languages are supported by the uploaded application. It would then populate the list of the language picker button based on the supported languages in the app. This is how it works in the Apple AppStore UI. 

If you really want to get fancy, you could offer to translate the default English notes to the supported languages, and the user could review the translations. This is not strictly necessary, but would be a nice added touch.

Of course AppCenter would need to parse for the different languages and properly format the Sparkle.framwework AppCast file to include the different notes.

 

**Describe alternatives you've considered**
The only alternative would be to manage my own Sparkle AppCast, which I really don't want to do.

**Additional context**

**Comment by wisdeom** [comment]
Thanks for sharing your feature request. Unfortunately, our engineering team is prioritizing on improving service performance and availability for the time being. We do not take your feedback for granted, and look forward to returning to our customer request based backlog once our team has finished investments work.

**Comment by jensdev** [comment]
@wisdeom Hi, it's been 2 years. Is this something that might be available in the near future? Our app only has `Dutch` as language but we can not submit via AppCenter. In the fastlane logs we get:

```
32mPlease update using `bundle update fastlane`[0m
bundler: failed to load command: fastlane (/Users/runner/work/r1/a/ios-resign-publish/bundle/ruby/2.7.0/bin/fastlane)
Spaceship::UnexpectedResponse: [31m[!] appStoreVersions with id 'ce6b426b-349f-49ba-bf47-d3dc53aa5bda' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why.
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request[0m
```

Is there a way to pass config to use a different language than English? Or detect the main language from appstore connect and use that in the script in stead of hardcoding English?

Thanks
