### ISSUE TITLE
Display Build# and Branch name in Release History

### ISSUE THREAD

**Issue by sreejithvijayan** [microsoft/appcenter#2208]
**Describe the solution you'd like**
It would be helpful if build# and branch name can be displayed in the Release history. Now there is no way to know the release is from which build# or branch name.

**Additional context**
Pls see screenshot
![appcenter-FR](https://user-images.githubusercontent.com/18568763/120444388-a07e2900-c398-11eb-9275-490798f48151.JPG)

**Comment by wisdeom** [comment]
Thanks for sharing your feature request. Unfortunately, our engineering team is prioritizing on improving service performance and availability for the time being. We do not take your feedback for granted, and look forward to returning to our customer request based backlog once our team has finished investments work.
