### ISSUE TITLE
Default team for all users in an organization, or make org invites include teams

### ISSUE THREAD

**Issue by sander-m** [microsoft/appcenter#221]
**Describe the solution you'd like**
In order to allow new users to view apps in an App Center organization, the following steps are needed:
  1. Send the user an org invite ([orgInvitations_create]( https://openapi.appcenter.ms/#/account/orgInvitations_create))
 2. Wait until the user has accepted the invite
 3. Invite user to an App Center Team that has access to apps within the organization (API: [teams_addUser](https://openapi.appcenter.ms/#/account/teams_addUser))

Because this flow requires user interaction (accepting the invite), it's hard to automate.

I would like to use the [orgInvitations_create]( https://openapi.appcenter.ms/#/account/orgInvitations_create) endpoint to invite users to both the organization and a team as part of the same invitation. Would it be possible to extend this endpoint to take `teams` as an optional argument?

**Describe alternatives you've considered**

There is no alternative to my knowledge.

**Comment by iageoghe** [comment]
That makes a lot of sense. We are in the middle of trying to sort out the best experience around user management and likely will defer such a feature until we have completed our analysis in the next month or so. Thanks for pointing this out.

**Comment by onlywhale** [comment]
Is there any update for this? This is exactly what I want.

**Comment by millanie** [comment]
Is there any update for this? This is exactly what I want.
When the users are located in the different timezones, the required time for completing whole steps increases.

**Comment by tasomaniac** [comment]
I came to here from Google search since I needed similar functionality. Sorry to see that it was closed.
