### ISSUE TITLE
Any plan for Xcode13 support in Visualstudio AppCenter?

### ISSUE THREAD

**Issue by v-hsakamoto** [microsoft/appcenter#2210]
Is there any plan for supporting Xcode13 in Visualstudio AppCenter yet?
If not, I'd like you to consider implementing its support.
A scenario would be a build using Xcode13 on AppCenter.

**Comment by akamenev** [comment]
We are currently looking at supporting XCode 12.5, until then there is no set date for XCode 13

**Comment by v-hsakamoto** [comment]
Thank you for your response.
Once the schedule for Xcode13 is set, please let me know here.
Best regards,

**Comment by sopranolinist** [comment]
The last comment from the AppCenter team in this thread is June 17th, over 2 months ago. Has there been any further progress on XCode 13 support @akamenev? Is this thread the best place to receive updates?

**Comment by wisdeom** [comment]
> The last comment from the AppCenter team in this thread is June 17th, over 2 months ago. Has there been any further progress on XCode 13 support @akamenev? Is this thread the best place to receive updates?

The best place to check updates on this support would be the [Cloud build machines](https://docs.microsoft.com/en-us/appcenter/build/software#operating-system) in our public documentation. To give you the context, we use Azure Pipelines in the backend, so if the mac OS image should be generally available in Azure Pipeline first as it's our dependency. You can check more details about it here:  https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md

**Comment by wisdeom** [comment]
Let me check with the team on this and get back to the thread.

**Comment by andrew-lundy** [comment]
App Center currently supports Xcode 13 beta:
![image](https://user-images.githubusercontent.com/62266789/132259926-b342069c-a145-4fe8-a2ee-17a3e9376105.png)

**Comment by wisdeom** [comment]
Hi @sopranolinist and all, Xcode 13.0 beta is available in App Center. Closing this issue!
