### ISSUE TITLE
Any plan for iOS 15 support in Visualstudio AppCenter?

### ISSUE THREAD

**Issue by v-hsakamoto** [microsoft/appcenter#2211]
Is there any plan for supporting iOS 15 in Visualstudio AppCenter yet?
If not, I'd like you to consider implementing its support.
A scenario would be a device test on iOS 15.

**Comment by akamenev** [comment]
Thanks for the feature request! We are currently looking at supporting iOS 15 in Visual Studio App Center Test.

**Comment by v-hsakamoto** [comment]
Thank you for your response.
Once the schedule for iOS15 is set, please let me know here.
Best regards,

**Comment by mikepattyn** [comment]
Hows it going?

**Comment by sudeepkzd** [comment]
Any updates on this?

**Comment by thehobbit85** [comment]
Any updates?

**Comment by sudeepkzd** [comment]
Hi @akamenev. Thanks for the response. iOS 15 support unfortunately is needed to run the apps on the iOS15. Without this support our users cannot run apps on iOS15. Not having this is a deal breaker for everyone. I assume that since Microsoft is [investing in the reliability and performance of AppCenter](https://github.com/microsoft/appcenter/issues/2234), they'll also be invested in ensuring that it remains usable. 
If the support won't be provided, please let the users know earlier, so they can invest on alternatives.

**Comment by wisdeom** [comment]
Hi, the team is working on this device set, so it should be supported soon. Please stay in tuned with us!

**Comment by aroyzen1983** [comment]
Any update here?

**Comment by givtnl** [comment]
Im guessing it will only be supported after apple releases official version of new xcode ? Tryed building and archiving the IPA but then apple says not allowed cause its built with xcode beta.

**Comment by melissamc26** [comment]
Testing on iOS 15 is very important as the public release approaches in less than a month. Please share an update on when you will be supporting it so we can plan accordingly @akamenev @wisdeom – Thank you

**Comment by wisdeom** [comment]
> @wisdeom thank you for the update. Is this thread the best location to receive updates on your progress towards iOS 15 support?

Any time! For test service, this documentation has a list of devices available with the OS version. The best place to check the support matrix. Does this answer your question? :) 
https://docs.microsoft.com/en-us/appcenter/test-cloud/devices/ios

**Comment by givtnl** [comment]
Still can't build for iOS 15 with Xcode 13 beta

**Comment by melodymorgan** [comment]
@wisdeom we would like to be able to select Xcode version 13 in the build configuration for our iOS app. Is this thread relevant to build configuration as well test devices?

**Comment by JoeW723** [comment]
iOS 15 is listed on the device support matrix. Has anyone confirmed they are able to install new build with AppCenter on iOS 15? I would rather not upgrade and have to downgrade if it still isn't working.

**Comment by koyta** [comment]
> iOS 15 is listed on the device support matrix. Has anyone confirmed they are able to install new build with AppCenter on iOS 15? I would rather not upgrade and have to downgrade if it still isn't working. 

I cannot confirm.

**Comment by JoeW723** [comment]
Update for anyone wondering. https://devblogs.microsoft.com/appcenter/run-tests-on-android-and-ios-beta-versions/

**Comment by sopranolinist** [comment]
13 Beta just showed up as an option in our build config this afternoon.

**Comment by chungweileong94** [comment]
You can set the XCode version to 13 RC on AppCenter in order to test the app on IOS 15 devices. 
If I'm not mistaken, the XCode 13 RC is the same as the official 13 release, I might be wrong.

**Comment by david-j-davis** [comment]
@chungweileong94 where does one set the settings inside of AppCenter, if you will?

**Comment by chungweileong94** [comment]
> @chungweileong94 where does one set the settings inside of AppCenter, if you will?
![Screen Shot 2021-09-24 at 9 33 30 AM](https://user-images.githubusercontent.com/15154097/134605022-ee0a0939-ed15-4fb6-973a-83eac5ee6021.png)
You can set the Xcode version in the build configuration. And seems like AppCenter already add Xcode 13 final version.

**Comment by david-j-davis** [comment]
Thanks!

**Comment by felixelgato92** [comment]
So with iOS 15 already released, I'm seeing that iPhone X cannot run my app builds. I can run my app if I get it from the Apple store, but not from appcenter. Do I just need to wait for iPhone X to be supported? Will that device ever be supported? Is there a roadmap? Thanks.

**Comment by chungweileong94** [comment]
> So with iOS 15 already released, I'm seeing that iPhone X cannot run my app builds. I can run my app if I get it from the Apple store, but not from appcenter. Do I just need to wait for iPhone X to be supported? Will that device ever be supported? Is there a roadmap? Thanks.

You have to change the Xcode version manually in the app center build configuration to Xcode 13.
