### ISSUE TITLE
Be able to use the UserId in Push Notifications

### ISSUE THREAD

**Issue by james1301** [Microsoft/appcenter#222]
**Describe the solution you'd like**
I would like to be able to use the UserId set via AppCenter.SetUserId in Push Notifications. Like you can specify a list of DeviceIds, you should be able to send a list of UserIds. I would have thought it was a common scenario to send to multiple users.

**Describe alternatives you've considered**
Currently I will have to try adding this as a custom property and sending them individually.

**Additional context**
We want to send out on bulk to users who have overdue reminders, we query the database and get the user ids. It would then be good to send this notification to the API in a single call for all of those users.

**Comment by jwargo** [comment]
@james1301 thanks for the feedback, we're working on that feature right now. The API's done and we're finalizing the UI for this. You can find details here: https://github.com/Microsoft/appcenter/issues/15. I'll update the feature spec and publish it as well, most likely next week.

**Comment by james1301** [comment]
Nice work @jwargo looks good. On from this I have since been setting some custom properties, which combined make up a unique user.

Basically we have clients using their own databases as we also share this with our main desktop application, so their user id is not unique so we are using a custom property for the customer as well as the user id to send out notifications currently. Basically creating an audience on the fly targeting these custom properties to just get to an individual user. Would there be scope for being able to send to custom properties without the need to create an audience also? Otherwise I may need to create a combination userid to make that unique instead.

**Comment by mattwill09** [comment]
@jwargo I am setting the User Id property and I am able to target notifications to that user but how do I unset the property if they log out of my application?

**Comment by jwargo** [comment]
@james1301 no immediate plans to enabling pushing directly to custom properties, you'll have to do it through audiences for now.  With some of our long term plans you may see a fix for this.

**Comment by jwargo** [comment]
@mattwill09 I don't really know, that's more of a question for the SDK team. I imagine that you'd just reset the user ID to an empty string, but I'm not sure.

**Comment by jwargo** [comment]
@mattwill09 according to the SDK team, you just set it to null through another call to the SDK method.

**Comment by jwargo** [comment]
@james1301 the feature is live (or will be live today) and the docs published. Please let us know what you think.

**Comment by shnaz** [comment]
@james1301:
> ... we are using a custom property for the customer as well as the user id to send out notifications currently. Basically creating an audience on the fly targeting these custom properties to just get to an individual user. Would there be scope for being able to **send to custom properties without the need to create an audience** also? Otherwise I may need to create a combination userid to make that unique instead.

This is also something we disparately need. 
It is a big overhead having to create and maintain audiences on the fly for each and every notification.  I think that this will benefit alot of people.

**Comment by shnaz** [comment]
@jwargo Should I create a feature request for the above or is there an existing, do you know?

**Comment by james1301** [comment]
@jwargo the new experience with being able to send out to specific UserId's is brilliant, thank you!

The future ability I previously mentioned and @shnaz has detailed to send out to custom properties would still be useful, so we could send to a specific customer.
