### ISSUE TITLE
is there a way to get "AppDataMode.Clear" to work on iOS when running it locally on a physical iPhone?

### ISSUE THREAD

**Issue by Moshex** [microsoft/appcenter#2220]
Right now on the application that I am automating using Xamarin.UITest AppDataMode.Clear when starting the automation code works as intended on Android for all devices. However, on physical iPhones (not simulators) when calling AppDataMode.Clear within ".StartApp()" the application data is not getting cleared every time. it does work on my application from time to time but it's not consistent.
is there another way to make sure that the application is always starting from a fresh state? I am looking for any solutions to this issue to be able to have more stable local runs on iOS. if this is a bug it will also be nice to know that this can get fixed in the future.

Also, if there is something that can be done in the application itself to make sure it's cleared I will take advice on that as well.

Here is the code I use to start the appication:

.iOS .WaitTimes(new CustomWaitTimes()) .InstalledApp("{application bundle id}") .EnableLocalScreenshots() .DisableSpecFlowIntegration() .StartApp(AppDataMode.Clear);

**Comment by wisdeom** [comment]
Hi, could you reach out to our support team to double check this behavior is correct? You can open a ticket in the App Center portal on the right top corner under the help menu. From there, we can better understand your situation and provide a better support with more details. Please let us know!

**Comment by Moshex** [comment]
This was the response from the app center team:
"
Hi there, The app data mode, whether to clear app data or not before app launch. Currently only supported in App Center Test because in the cloud your iOS app is reinstalled before each test so the data is cleared. However, locally, for iOS devices, when using AppDataMode.Auto or AppDataMode.Clear (they work in the same way), no data is ever cleared. So the feature that the iOS app starts from a fresh state locally each time is beyond our scope. You can check below two links for details.

https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/features/appdatamode

https://docs.microsoft.com/en-us/dotnet/api/xamarin.uitest.configuration.iosappconfigurator.startapp?view=xamarin-uitest-sdk

Sorry for any inconvenience caused. Best regards, Jiaping
--
"

My question in response was:
"
Thank you for your response,  I have 2 questions about this.
one, is there any plan on fixing this issue in the future, or giving us an option locally to be able to fresh install the app on ios?  
two, per the link you provided it states. "iOS - No data is ever cleared. In the cloud, your app is reinstalled before each test so the data is cleared. The app can persist data in the iOS keychain between installs, which can sometimes be an issue."
is there a way that devs can prevent "keychain" from persisting data? 
"

I will post the answer to the questions once received.

**Comment by Moshex** [comment]
From App Center:
"

Hi there, From our backend log, we don’t support this feature. You said it used to work so could you please tell us when did it work and the related iOS version? 
Best regards, JP

"

My renounce:
"
This worked for me back in May of 2021 with an iOS version of less than 13.7. once I updated my phone and the Devs updated the application for 14.x.x that was when it stopped working and we needed to come up with alternatives. keep in mind that even if I use a device that is 13.7 or lower at this point the "AppDataMode.Clear"  does not work on any iOS device even older OS versions. Keep in mind that I know this used to be supported since in the test templet for   Xamarin.UITest it still shows this:

            #region command line ConfigureApp un-comment .InstalledApp or .AppBundle(simulator)/.InstalledApp(Device)
            return ConfigureApp
            .iOS
            .WaitTimes(new CustomWaitTimes())
            .InstalledApp("{bundle id}")
            .EnableLocalScreenshots()
            .DisableSpecFlowIntegration()
            .StartApp(AppDataMode.Clear);
            #endregion

if you never supported "AppDataMode.Clear" then why do you have it as an option for iOS? clearly, it worked at one point and now it does not AKA a bug...

"

App Center:
"

Hi there, I'll confirm with our Product Team on this feature. However, can you help give us a screenshot or make a screen record when it works?
Best regards, JP
--

"

**Comment by Moshex** [comment]
@wisdeom can you reopen the issue since it's not fixed?
