### ISSUE TITLE
Calabash not working in React Native 0.64 with Hermes enabled

### ISSUE THREAD

**Issue by curia-damiano** [microsoft/appcenter#2221]
**Describe the solution you'd like**
We want to integrate the Calabash runtime (to allow to execute Xamarin.UITests) in an app written in React Native 0.64 with Hermes enabled.

**Describe alternatives you've considered**
No alternative possible if we want to use Xamarin.UITest to share test code between Android and iOS.

**Additional context**
I have not been able to find docs about integrating the Calabash runtime inside React Native apps.
- I have found this tutorial, that anyway required some changes in the gem file: https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-Link-Calabash-in-Debug-config
- This GitHub sample https://github.com/bamlab/rn-calabash-demo follows the guide at the previous point and it doesn't work as well

**Comment by AlexeyBudynkov** [comment]
Hello, @curia-damiano. 
What problems do you face when you try to integrate Calabash runtime inside React Native app?

**Comment by curia-damiano** [comment]
Hi Alexey, I reply to you in private
