### ISSUE TITLE
App Center API Documentation has incorrect NotificationPlatformType enum

### ISSUE THREAD

**Issue by gbockus** [microsoft/appcenter#223]
**What App Center service does this affect?**
App Center API Documentation

**Describe the bug**
The NotificationPlatformType is inaccurate in the swagger documentation for the REST API.

NotificationPlatformType string
Notification platform type
Enum:
[ apns, gcm, wns ]

**To Reproduce**
See: https://openapi.appcenter.ms/
Search for NotificationPlatformType

**Expected behavior**
I only have an iOS and Android application but those two values should be: 
Enum:
[ apns_token_config, gcm_config, ? ]

**Screenshots**
![Image 2019-03-26 at 9 58 30 AM](https://user-images.githubusercontent.com/771324/55007634-c126e900-4fad-11e9-97ee-4ecdae61c565.png)

**Desktop (please complete the following information):**
- All

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
The rest API doesn't provide any feedback if you have the wrong type provided.  It's just a 400 error so in order to find the correct type you have to contact support.

**Comment by jwargo** [comment]
@gbockus Thanks for pointing this out - we're in the midst of a swagger refresh (including, hopefully, a new rendering engine). I'll get this updated.
