### ISSUE TITLE
Hi my ipad running on ios 14.4 but currently cannot download from app centre.Is shows "this app cannot be installed because its integrity could not be verified." Any ways how to fix it?

### ISSUE THREAD

**Issue by Sayut02** [microsoft/appcenter#2235]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![IMG_0E45FE266950-1](https://user-images.githubusercontent.com/86974056/124495249-76ca7e80-ddea-11eb-8535-c3b220513df0.jpeg)

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
Please make sure that you performed the device registration process to allow installing apps on your device. Please follow this [guideline](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios#adding-your-device).

**Comment by Sayut02** [comment]
> Hi! Thanks for getting in touch with us!
> Please make sure that you performed the device registration process to allow installing apps on your device. Please follow this [guideline](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios#adding-your-device).

Hi Hi AnastasiaKubova 

Thank you for your feedback.

I already follow all the steps in the guideline.So after I install my profile in the setting then it will direct me back to the App Centre.Suddenly, I cannot download all the build that my developer have provide me.Here attach the pic & video

https://user-images.githubusercontent.com/86974056/124559791-ad49dd00-de6e-11eb-915b-8912bce7880c.MOV


![IMG_4473](https://user-images.githubusercontent.com/86974056/124561716-c784ba80-de70-11eb-988b-fd30c4bacf17.jpg)
![IMG_4474](https://user-images.githubusercontent.com/86974056/124561738-ce133200-de70-11eb-8324-efacb5f171c9.jpg)
![IMG_4475](https://user-images.githubusercontent.com/86974056/124561749-d0758c00-de70-11eb-826a-9f5081e4101b.jpg)

**Comment by Sayut02** [comment]
Hi Microsoft/Appcenter

Thank you for your feedback.

I already follow all the steps in the guideline.So after I install my
profile in the setting then it will direct me back to the App
Centre.Suddenly, I cannot download all the build that my developer have
provide me.Here attach the pic & video

**Comment by othorin** [comment]
We have the same issue. Removed and added the device multiple times, installed the profile over and over, built new versions of the app, reset Safari browser cache, restarted device, manually added the UDID to AppStoreConnect, updated the app specific password for the Apple developer account used in Appcenter.

Nothing has worked. It feels like the Appstore-Apple communication is broken as the added device is not showing up on their end.

**Comment by alexChernyatiev** [comment]
Hi there!
It is a general issue of apple.
﻿Could you please verify if you have another app installed with the same ID as the problematic app?
﻿If not could you please delete the app from the device, restart Xcode, and rebuild the app?

**Comment by Sayut02** [comment]
Hi Alex,

Thank you for your email.

We using one Apple ID with few device.Same app can be installed to another
devices, multiple devices.


But iPad in particular, doesn’t have the install button visible.Will try
your suggestion and get back to you.

**Comment by wisdeom** [comment]
You can also reach out to our support team to get a help. In the drop down menu of our portal, there's a button to submit your issue. We'd love to assist you from there.
