### ISSUE TITLE
Not able to configure react native/build works unexpectedly/ no solution from support team from last 6 months

### ISSUE THREAD

**Issue by gurtejsmartdata** [microsoft/appcenter#2236]
**Problem**
From last 6-7 months Im not able to edit configuration/

**Description**
From to last 6-7 Im trying to get solution from App Center support team, they are saying that we are not able to track issue. they provided me swagger links. that also does not work. very cheep service for paid accounts.
 ticket number: #KPF3IR97

**Additional context**

<img width="840" alt="Screenshot 2021-07-12 at 10 06 36 PM" src="https://user-images.githubusercontent.com/38884969/125324471-910dda80-e35d-11eb-85db-f8d70ae4cb3c.png">
<img width="830" alt="Screenshot 2021-07-12 at 10 05 37 PM" src="https://user-images.githubusercontent.com/38884969/125324738-cca8a480-e35d-11eb-9099-9f7092db9c1f.png">

**Comment by akamenev** [comment]
Hi @gurtejsmartdata, we are investigating the issue with GitLab and in the meantime the workaround was provided to you in the support ticket. We'll keep you updated through the support ticket.
