### ISSUE TITLE
Xcode 12.5 Support

### ISSUE THREAD

**Issue by cquanu** [microsoft/appcenter#2237]
App is unable to install on iOS 15 if it was built with Xcode 12.4.

When installed, the user will see an error prompt on iOS "The developer of this app needs to update it to work with this version of iOS."

Can we at least have a timeline or official announcement on this?

Same issue as https://github.com/microsoft/appcenter/issues/2185

**Comment by akamenev** [comment]
Hi @cquanu, please continue the discussion in #2185. 
Closing as a duplicate.
