### ISSUE TITLE
Censorship in these github issues

### ISSUE THREAD

**Issue by AlexFolland** [microsoft/appcenter#2239]
In https://github.com/microsoft/appcenter/issues/1339 there were several comments updating the issue, including comments after it was marked stale, explaining why it should not be marked stale.  Those comments were silently deleted, and the stale status was repeatedly replaced.

Why is commentary being deleted and issues being allowed to be closed from staleness when several users have posted comments explaining how the issue is still relevant, with well-worded rationale, screenshots, and comparisons with HockeyApp?

**Comment by akamenev** [comment]
Hi @AlexFolland, I don't see any comments in the original issue after the bot marked it as stale. I will reopen the original issue, thanks for bringing it up!

**Comment by AlexFolland** [comment]
Thanks.  I know this happened because I saw my own comment on that issue deleted after having posted it, and I remember that issue having plenty of commentary from several people.
