### ISSUE TITLE
Xamarin.UITest after we move to MAUI? 

### ISSUE THREAD

**Issue by rs-memosoft** [microsoft/appcenter#2241]
Apologies if this is not exactly the right forum for this question but I am looking into our organization making use of Xamarin.UITest and so far I have not seen anything that would help me to confirm if this is going to be supported in MAUI.  If you have any information on this matter it would be much appreciated.

**Comment by pm90pl** [comment]
Hi, could someone confirm that there is no issue with MAUI and Xamarin.UITest?

**Comment by IlyaBausovAkvelon** [comment]
Hi there! There are no support for MAUI in Xamarin.UITest. We are still working on updates for this.
