### ISSUE TITLE
msftbot closed non-stale issue

### ISSUE THREAD

**Issue by breyed** [microsoft/appcenter#2242]
msftbot closed #151 with this comment:
> This issue will now be closed because it hasn't had any activity for 15 days after stale. Please feel free to open a new issue if you still have a question/issue or suggestion.

It did this even though there was activity (including upvotes) after the bot had marked the issue stale. #151 should be reopened and the bot fixed.

**Comment by akamenev** [comment]
Reopened, thanks @breyed!
