### ISSUE TITLE
Distribution to TestFlight has been in Processing status

### ISSUE THREAD

**Issue by mcastros12** [microsoft/appcenter#2243]
the distribution to TestFlight has been in Processing status for hours and has not yet been uploaded to App Store Connect. Is there a problem currently?

**Comment by wisdeom** [comment]
Hi this can happen when the App Store on Apple side hasn't completed their process. If you reach out to our support team in the portal, they can give you more information with your release number on that specific time. Please open a support ticket and reach out to us! we'd love to assist you further there.

**Comment by Arkan4ik** [comment]
@mcastros12 have you solved this issue? I have the same. I can't see uploaded build from appcenter in testflight
