### ISSUE TITLE
No App Center Appium Java Test Extensions in Maven Central Repository

### ISSUE THREAD

**Issue by valentinmakov** [microsoft/appcenter#2246]
Hi,

There is no App Center Appium Java Test Extensions sources in Maven Central Repository. We need com.microsoft.appcenter:appium-test-extension:1.5, but it only exists in JCenter:

https://mvnrepository.com/artifact/com.microsoft.appcenter/appium-test-extension?repo=jcenter

It is crucial for us to have this dependency in Maven Central Repository

**Comment by valentinmakov** [comment]
Hi,

Is any actions planned on this issue? Thank you.

**Comment by LindsayRoseRyan** [comment]
I am also facing this issue - it is specific to the test center module from what I can tell. I found version 1.3 in the Spring repo but everything I read from MS indicates that this module should have been migrated to Maven Central:

This article indicates everything would be migrated to Maven Central: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android#3-add-the-app-center-sdk-modules

This closed issue indicates that everything was moved: https://github.com/microsoft/appcenter-sdk-android/issues/1503

This documentation also suggests that this was done for all modules that aren't deprecated: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android#3-add-the-app-center-sdk-modules

**Comment by LindsayRoseRyan** [comment]
Happy to say I just heard back on the ticket I submitted when I was facing this issue and the extension is now published in maven central 👏 

https://search.maven.org/artifact/com.microsoft.appcenter/appium-test-extension/1.6/jar
