### ISSUE TITLE
Grouping event properties by event rather than by property name.

### ISSUE THREAD

**Issue by rlasker3** [microsoft/appcenter#225]
**Describe the solution you'd like**
We are currently tracking data sync times using AppCenter Analytics. Each sync event contains the following properties in the dictionary. Table being synced, time it took that table to sync and the user's id who initiated the sync.

When we go to view the data in App Center all of the sync table names are grouped together and all of the sync times are grouped together and there is no way to correlate the data.

For instance if we see a long sync time there is no way to tell which user and for which table that long sync time belongs to.

**Describe alternatives you've considered**
Not sure if this is able to be correlated in Analytic Insights

In the image ... which TimeSpan belongs to which Sub Process?

![image](https://user-images.githubusercontent.com/185889/55012913-87aaa980-4fbe-11e9-8008-7f4d0aacc95a.png)

**Comment by hamswan** [comment]
Thanks for pointing this out. We have made a note of this request added this in our backlog.
