### ISSUE TITLE
Webhooks on successful CodePush release

### ISSUE THREAD

**Issue by ButchMonkey** [microsoft/appcenter#226]
**Describe the solution you'd like**
The ability to set up webhooks for on successful CodePush release. In a team of developers, it would be nice to see when a deployment has been updated. I would like to see all the codepush information available: 
- Deployment pushed to
- Notes
- App Name & Icon
- User that pushed

**Describe alternatives you've considered**
Pushing code via the api and then on callback manually firing off a webhook. This solution worked but was not ideal and would need work if there were changes to the api. The api also had issues that were resolved with the cli, such as committing bad or empty files.

**Comment by botatoes** [comment]
Thanks for the suggestion. We do recommend using CLI for CodePush but I will take note of this feature request and prioritize it after we finish the electron support effort.

**Comment by abdullahizzuddiin** [comment]
Hi, any update on this feature request?

**Comment by ridvanaltun** [comment]
ping
