### ISSUE TITLE
Build React Native apps for Windows 10

### ISSUE THREAD

**Issue by michaelaliotti-nuvolo** [microsoft/appcenter#2264]
**Describe the solution you'd like**
We'd like AppCenter to provide the ability to build a Windows 10 app using React Native. 

**Describe alternatives you've considered**
We don't want to move off of AppCenter (as it provides so many great tools for building, testing, and distributing apps), but the only alternatives seem to be either building a separate native Windows 10 app or moving to a different build pipeline setup such as Azure.

**Additional context**
One of the best parts of using React Native is being able to write once and build for many platforms. Giving the ability for developers to use the same codebase and provide an app to Android, iOS, and Windows users would be a huge win!

**Comment by akamenev** [comment]
Hi @michaelaliotti-nuvolo and thanks for the feature request! As we are currently prioritizing the availability and reliability of service we are not planning to add any additional platforms to App Center Build in the near future. In the meantime, please check if you can achieve the desired configuration through GitHub Actions, [here ](https://github.com/microsoft/react-native-windows-samples/blob/main/samples/ContinuousIntegration/README.md) is an example CI configuration for the React Native Windows app.
