### ISSUE TITLE
Option for a QR code on the install web page https://install.appcenter.ms/

### ISSUE THREAD

**Issue by RadkaSYBO** [microsoft/appcenter#2265]
**Describe the solution you'd like**
Add the option to scan a QR code next to each build on the install web page  https://install.appcenter.ms/
¨
**Describe alternatives you've considered**

**Additional context**
Same option which is already available on the https://appcenter.ms/ page under Company name/App Tittle/ Distribute/ Releases

**Comment by akamenev** [comment]
Hi @RadkaSYBO, thanks for the feature request! Could you please describe how you use install page today? Do you open a link from the email notification? Step by step workflow would be useful for us to understand your usecase.

**Comment by RadkaSYBO** [comment]
Hi @akamenev, sure!
Currently, we use the install page on the mobile devices we test on. We dont use any emails notifications.
So the workflow would be:
1. Confirm that the build is done on the CI/CD tool we use.( builds are configured to automatically upload to Appcenter)
2.  open https://install.appcenter.ms/ in a browser on a mobile device
3.  navigate to the app title 
4. Scroll to the build ( not always the latest one). & install it.

However, when the build is ready, an install page link is also generated, on the CI/CD tool, which we often share across the team. Since the link is opened on the web, it would be great to have the QR code option, so we dont have to scroll through builds on the install page on the device. 
I hope this answers your question. Let me know if additional info is needed.

**Comment by akamenev** [comment]
Thanks for the clarification! We'll take a look at possible install portal enhancement but unfortunately cannot grab this work item anytime soon. Appreciate your feature request!
