### ISSUE TITLE
To fix vulnerable dependency SQLitePCLRaw.lib.e_sqlite3.2.0.4

### ISSUE THREAD

**Issue by Arivazhagan-s** [microsoft/appcenter#2267]
Hi,
We are developing a project in .net framework WPF application for windows. In that application we have implemented AppCenter to track analytics and diagnostics.
We use three packages for AppCenter implementation,
**Microsoft.AppCenter - version 4.3.0
Microsoft.Appcenter.Analytics - version 4.3.0
Microsoft.AppCenter.Crashes - version 4.3.0 .**
Some of the dependency packages were also installed along with the AppCenter packages like
**SQLitePCLRaw.lib.e_sqlite3.2.0.4
SQLitePCLRaw.core.2.0.4
SQLitePCLRaw.bundle_green.2.0.4
SQLitePCLRaw.provider.dynamic_cdec1.2.0.4.**

When we try running the OWASP dependency check report for vulnerabilities in our project. We got ten vulnerable dependencies due to these packages (screenshot_1 attached below),
**SQLitePCLRaw.lib.e_sqlite3.v110_xp.1.1.14
SQLitePCLRaw.lib.e_sqlite3.2.0.4**

<img width="789" alt="1" src="https://user-images.githubusercontent.com/89505044/130732116-a9c49ec1-14f4-4ad0-9d65-302a1fb85a67.png">

we tried to install the AppCenter packages with Lowest Dependency behavior, which removes SQLitePCLRaw.lib.e_sqlite3.v110_xp.1.1.2 package from the report.
Now it is showing eight vulnerable dependencies due to (screenshot_2 attached below)
**SQLitePCLRaw.lib.e_sqlite3.2.0.4.**

<img width="820" alt="2" src="https://user-images.githubusercontent.com/89505044/130732183-26662f72-7c33-4428-9265-bf561dfbdde6.png">

**Please suggest us how to fix this vulnerability, since AppCenter is not working without this packages.**

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Could you tell me please where I can find information about this vulnerability? Also, you can leave the report about this issue in [SQLitePCLRaw repository](https://github.com/ericsink/SQLitePCL.raw) directly.

**Comment by DmitriyKirakosyan** [comment]
I agree with @beeradmoore, the App Center SDK uses SQLitePCLRaw.bundle_green of version `2.0.2`. We don't have any other dependencies which may install the vulnerable sqlite packages from the security reports mentioned above.

@Arivazhagan-s do you have any other dependencies that use `SQLitePCLRaw` or `sqlite3`?
Could you try to remove AppCenter SDK dependency from your project and check if the alerts disappear.
You can also try to create an empty project with AppCenter SDK integrated and perform the security check on it.

**Comment by Arivazhagan-s** [comment]
@DmitriyKirakosyan Only AppCenter uses SQLitePCLRaw.bundle_green in our project. But when we install the SQLitePCLRaw.bundle_green package with **Dependency Behaviour** option as Highest, It install the some other packages along with it. 

Will try create an empty project with AppCenter SDK integrated and perform the security check and let the output know here. Thanks !!!!

**Comment by Arivazhagan-s** [comment]
@DmitriyKirakosyan I have a created an empty WPF project and integrated AppCenter to it. I have installed the latest version of AppCenter and its dependencies. Still I am getting the same vulnerability list along with some new items. 

I am attaching the report here in the command for your reference. 
[report.zip](https://github.com/microsoft/appcenter/files/7113895/report.zip)

**Comment by DmitriyKirakosyan** [comment]
Hi @Arivazhagan-s 

It does seem like a problem is in the utility you use to check the dependency vulnerabilities.
I'm closing this issue since the one in SQLitePCLRaw was [closed](https://github.com/ericsink/SQLitePCL.raw/issues/438#issuecomment-908019328).

**Comment by Arivazhagan-s** [comment]
Hi @DmitriyKirakosyan, 
As per the suggestion from SQLitePCLRaw, we have tried updating SQLitePCLRaw to 2.0.5 through NuGet Packages UI. AppCenter integration works fine.

Can you advise on one thing
- We tried updating **AppCenter4.4.0**, but it requires **PackageReference** format. Packagereference is not compatible with our installer project. 
- Can we install **Appcenter4.3.0** which supports **Package.Config** format, and update SQLitePCLRaw to 2.0.5 through NuGet Packages UI. Will it lead to any security issue.

**Comment by DmitriyKirakosyan** [comment]
Hi @Arivazhagan-s , Yes you can use AppCenter SDK 4.3.0 without any issues. And yes, your approach of updating SQLitePCLRaw Nuget should work.
