### ISSUE TITLE
Xamarin.Android 11.3 support in App Center

### ISSUE THREAD

**Issue by beeradmoore** [microsoft/appcenter#2270]
**Describe the solution you'd like**
I would like AppCenter to add support for Xamarin.Android 11.3, just like how it recently got [Xamarin.iOS 14.16 support](https://github.com/microsoft/appcenter/issues/2185#issuecomment-906355970) (which is still 2 months out of date). Xamarin.Android 11.2 was previously requested [here](https://github.com/microsoft/appcenter/issues/2199).

Version | Release date
--------|--------------
11.3.0.4 | 2021-06-15
11.3.0.1 | 2021-06-02
11.2.2.1 | 2021-05-03
11.2.0.21 | 2021-03-09
11.2.0.0 | 2021-03-02 
11.1.0.26 | 2021-01-12      

Version and dates pulled from Visual Studio for Mac update manifest, manifest url obtained via [boots](https://github.com/jonathanpeppers/boots/blob/375eaa453d9623c2b7d8ebe372a492c414610f43/Boots.Core/MacUrlResolver.cs#L11).

**Describe alternatives you've considered**
I have attempted to use boots to install latest Xamarin.Android with boots but that prevented my sample app from building due to Java SDK not being updated.

**Additional context**
I believe there may be additional work required other than installing an updated pkg into the build system as at some point Java SDK 11.0 or above became required when using Android SDK Build-Tools 30.

I am not sure if this is blocking the new Android 11 requirements for the Google Play Store as I am not sure if Xamarin.Android 11.1.0.26 can target Android 11. Requirements for Google Play Store can be found [here](https://developer.android.com/distribute/best-practices/develop/target-sdk), which require new apps to target Android 11 by August 2021 (already passed) and existing apps to target Android 11 by November 2021.

**Comment by joemather** [comment]
Xamarin.Android 11.2 has appeared.  Hopefully Xamarin.Android 11.3 is coming soon.


<img width="524" alt="Xamarin Android 11 2" src="https://user-images.githubusercontent.com/13467576/134238847-f31805da-a83a-4a22-a86f-3cb3fb4c98ef.png">

**Comment by dragan-novakovic** [comment]
Fresh from the oven  🍪 🍪.  😄 

![image](https://user-images.githubusercontent.com/23102374/136565356-aed45e75-9881-4647-b27f-b34b9026d049.png)
