### ISSUE TITLE
Faster integration and better communication around SDK updates

### ISSUE THREAD

**Issue by beeradmoore** [microsoft/appcenter#2271]
I am coming at this issue as a Xamarin.iOS and Xamarin.Android developer, but I believe similar things should be in place for React and any other systems AppCenter supports.

Recently there has been large delays in getting latest SDKs for building apps. I am not sure if the delays are related to AppCenter going into [maintenance mode](https://github.com/microsoft/appcenter/wiki/Roadmap) (previously listed as to going through to mid-2021), issues [out of your control](https://github.com/actions/virtual-environments/issues/2486), both, or neither. 

As mentioned on my other feature request regarding [Android 11.3 support](https://github.com/microsoft/appcenter/issues/2270), 

Version | Release date
--------|--------------
11.3.0.4 | 2021-06-15
11.3.0.1 | 2021-06-02
11.2.2.1 | 2021-05-03
11.2.0.21 | 2021-03-09
11.2.0.0 | 2021-03-02 
11.1.0.26 | 2021-01-12

With the latest available in AppCenter being 11.1.

Xamarin.iOS versions available currently are,
Version | Release date
--------|--------------
14.20.0.24 | 2021-07-14
14.20.0.3 | 2021-06-09
14.20.0.1 | 2021-06-02
14.16.0.5 | 2021-05-03
14.14.2.5 | 2021-03-02

Before the [recent update](https://github.com/microsoft/appcenter/issues/2185#issuecomment-906114307) the latest SDK was 14.14 with Xcode 12.4, now we have Xcode 12.5 the latest SDK being 14.16 which is still 3 months out of date.

**Describe the solution you'd like**
I can see two things that individually (or both at the same time) can help with the friction of issue:

1. More clear communication about the plans of supporting SDKs. If a new SDK is available (eg. Xamarin.Android 11.3.0.4) a new GitHub issue is created where for people to give a 👍 and subscribe for updates. That way if there are delays, we can also be notified "hey everyone, 11.3.0.4 is going to take longer than usual as we need to have our environments include JDK 11". This is much more preferable than the communication we got earlier in the year [from support](https://github.com/microsoft/appcenter/issues/2185#issuecomment-837881791) which was "At this time there are no plans to update support for Xcode 12.5", followed by the lack of updates going forwards. The updates on Xcode 12.5 over the past 48h has been fantastic.

2. Same week support for Xamarin.iOS and Xamarin.Android updates (where possible¹) as they are released into Visual Studio for Mac². The faster update cycle allows developers to keep their development environment in line with their AppCenter configs to ensure everything is available and works as expected.

¹ If the update requires installing newer Xcode, newer JDK, etc, it's completely understandable that AppCenter may not have support within the same week.

² I say VS4Mac because AppCenter builds these particular apps on macOS, and because as mentioned below its possible to get the current released versions.

**Describe alternatives you've considered**
Running my own CI/CD pipeline. I had used Jenkins in the past to create my own app building pipeline on a spare Mac Mini. While it was functional, it was not user friendly. There was no support (at least from my setup) for supporting multiple environments allowing me to swap SDKs as easily as I can with a dropdown in AppCenter.

Adding new apps from git sources (+ provisioning profile, + keystore, etc) was also nowhere near as streamlined and easy to do in AppCenter.

I had also played with Azure Pipelines but again, the process was not as clean and simple as AppCenter.

**Additional context**
I would assume internally AppCenter are tracking SDK updates where possible. This can be a pain when there are so many platforms targeted. If the teams were not aware (and were not getting notified internally by the Xamarin team) then this may be of use. I had come across a link to the VS4Mac [update manifest](https://software.xamarin.com/Service/Updates?v=2&pv964ebddd-1ffe-47e7-8128-5ce17ffffb05=0&pv4569c276-1397-4adb-9485-82a7696df22e=0&pvd1ec039f-f3db-468b-a508-896d7c382999=0&pv0ab364ff-c0e9-43a8-8747-3afb02dc7731=0) (via [boots](https://github.com/jonathanpeppers/boots/blob/375eaa453d9623c2b7d8ebe372a492c414610f43/Boots.Core/MacUrlResolver.cs#L11)). Simple cron can parse this and ping Teams/Slack channels to get the ball rolling, or even create the GitHub issues mentioned above.

**Comment by beeradmoore** [comment]
Xcode 13.1 is now available in virtual environments. 
Xamarin.iOS 15.2 isn't in there yet, but if the runners were updated we could use Xcode 13.1 and install Xamarin.iOS 15.2 via boots.

**Comment by softlion** [comment]
I need Xamarin.iOS 15.4, is there a way to install it using a prebuild step ?

**Comment by beeradmoore** [comment]
You should be able to use [boots](https://github.com/jonathanpeppers/boots/), however if Xamarin 15.4 has a dependency on a newer version of Xcode then you are out of luck.

**Comment by softlion** [comment]
Ty @beeradmoore I knew there was a way but was unable to find it anymore. That is working fine, even if a warning that xcode 13.2 is preferred to 13.1:

```
dotnet tool install --global boots
boots --stable Xamarin.iOS
```
