### ISSUE TITLE
Private SPM GitlabRepo

### ISSUE THREAD

**Issue by MaxenceMax** [microsoft/appcenter#2273]
With Apple announcing support for Swift Package Manager for iOS in the next release of Xcode, I would like to see this support added here as well for repo from private Gitlab server.

**Comment by MaxenceMax** [comment]
@ptsiogas 

I've just found a solution. we have SP in a private gitlab repo, so I added a read-only token access in those repos and added them like that in SPM :

``https://<TokenName>:<Token>@gitlab.private.com/url/to/repo.git```

Of course our app repo is private so the token is safe.

**Comment by AnatolyPristensky** [comment]
Hello @MaxenceMax , thank you for getting touch with us!
Unfortunately, we can't start working on your feature request right now as the AppCenter project is in maintenance mode.
Here is more information: https://github.com/microsoft/appcenter#planning
