### ISSUE TITLE
App Center Device Registration Service Certificate - Expired August 27, 2021

### ISSUE THREAD

**Issue by carmanj** [microsoft/appcenter#2277]
I noticed recently that using the 'Add device' from install.appcenter.ms downloads a App Center Device Registration Service Profile that lists the signing certificate for install.appcenter.ms as expired on August 27, 2021.

![image](https://user-images.githubusercontent.com/30543806/131896771-87b28245-53a1-48ad-8a44-a251e4b0a829.png)

**Comment by DmitriyKirakosyan** [comment]
Hi @carmanj , the certificate is fixed now, could you please check it again?

**Comment by carmanj** [comment]
> Hi @carmanj , the certificate is fixed now, could you please check it again?

Hey Dmitriy - That took care of it! Thanks!
