### ISSUE TITLE
Building iOS 15 apps in Appcenter using Xcode 13 RC and Xamarin.iOS 14.20+

### ISSUE THREAD

**Issue by lversluijs** [microsoft/appcenter#2279]
We need to rebuild and test 20+ enterprise apps for the iOS 15 release since the current deployed Xamarin apps are not supported by iOS 15 on our managed iOS devices. Those apps are build using appcenter.
Can you please add support for the XCode 13 RC and Xamarin.iOS 14.20+ so we can rebuild and test our apps using stable software. This would solve our problem.

**Comment by sopranolinist** [comment]
XCode 13 Beta just showed up as an option in our AppCenter build configs this afternoon.

**Comment by wisdeom** [comment]
Hi! Let me get back to you when I have updates on the work in progress. Thanks for opening the issue!

**Comment by wisdeom** [comment]
Hi @lversluijs, these versions are almost ready, but we're still testing them in our dev environment. We'll give another update once we shipped to production.

**Comment by beeradmoore** [comment]
Hey @wisdeom , slightly off topic but are you able to see where progress is for the later Android SDK options are? (RE: #2270)

**Comment by joemather** [comment]
Xcode 13.0 RC and Xamarin.iOS 14.20 are available.


<img width="524" alt="Xcode 13 0 RC" src="https://user-images.githubusercontent.com/13467576/134237670-b322fa60-0348-4ef2-9b1c-abce78a42282.png">

**Comment by beeradmoore** [comment]
It isn't officially recommended to use Xcode 13 yet. 
https://github.com/xamarin/xamarin-macios/issues/12778

**Comment by wisdeom** [comment]
@beeradmoore If you're looking for Xcode 13 stable, that should be already available. If you believe this is not the case, can you open a support ticket or let us know here?

**Comment by lversluijs** [comment]
It is available. Thx for the service. We start rebuilding our apps using
this stable version.

Met vriendelijke groet,

Leendert Versluijs
IT Architect Mobile



........................................................................
Belastingdienst/ IV-organisatie / Generieke Business Services / MCC
John F. Kennedylaan 8 | 7314 PS | Apeldoorn | Gebouw G begane grond
........................................................................
M +31655277546
E ***@***.***






Van:	"Jihye Eom" ***@***.***>
Aan:	"microsoft/appcenter" ***@***.***>
Cc:	"lversluijs" ***@***.***>, "Mention"
            ***@***.***>
Datum:	29-09-2021 11:54
Onderwerp:	Re: [microsoft/appcenter] Building iOS 15 apps in Appcenter
            using Xcode 13 RC and Xamarin.iOS 14.20+ (#2279)



[EXTERNE E-MAIL] Dit bericht is afkomstig van een externe afzender. Wees
voorzichtig met het openen van linkjes en bijlagen.



@beeradmoore If you're looking for Xcode 13 stable, that should be already
available. If you believe this is not the case, can you open a support
ticket or let us know here?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.





------------------------------------------------------------------------
De Belastingdienst stelt e-mail niet open voor aanvragen, aangiften, bezwaarschriften, verzoeken, klachten, ingebrekestellingen en soortgelijke formele berichten.
Dit bericht is uitsluitend bestemd voor de geadresseerde. Het bericht kan vertrouwelijke informatie bevatten waarvoor de fiscale geheimhoudingsplicht geldt. Als u dit bericht per abuis hebt ontvangen, wordt u verzocht het te verwijderen en de afzender te informeren.

The Dutch Tax and Customs Administration does not accept filings, requests, appeals, complaints, notices of default or similar formal notices, sent by email.
This message is solely intended for the addressee. It may contain information that is confidential and legally privileged. If you are not the intended recipient please delete this message and notify the sender.

**Comment by beeradmoore** [comment]
@wisdeom , AppCenter released Xcode 13 into the Xamarin iOS build pipelines when there is not a stable version of Xamarin.iOS that supports Xcode 13 (Xamarin.iOS 15.0.0.6 is latest in preview AFAIK)

We rolled back to 12.5.1 until there is actual support from the Xamarin side.
