### ISSUE TITLE
Click the app should navigate to app release

### ISSUE THREAD

**Issue by shalinasanga** [microsoft/appcenter#228]
**Describe the solution you'd like**
when we click the app, we simply need to upload a new build or do a release. the current UI navigate us to app overview page which is not quite important as developer. bring distribution tab up and make it much easy to interact with.

**Describe alternatives you've considered**
or navigate to distribution tab, or add New Release button in overview page

**Comment by derpixeldan** [comment]
Related to https://github.com/Microsoft/appcenter/issues/206
