### ISSUE TITLE
AppCenter dependency store 

### ISSUE THREAD

**Issue by bilicio** [microsoft/appcenter#2285]
**Describe the solution you'd like**
Right now, each app takes too long to build because it needs to download the same dependencies everytime and over and over again. The idea is to create a local dependency store to quick access those already downloaded dependencies instead of looking for them everytime.

**Describe alternatives you've considered**
Storage for dependencies like mavencentral, but local. 

**Additional context**

**Comment by dgellow** [comment]
That would be great... as of now downloading dependencies is so slow building a very simple app on AppCenter almost always pass the 30min limit.

**Comment by bilicio** [comment]
+1

**Comment by dgellow** [comment]
@msftbot Please don't.
