### ISSUE TITLE
Publishing to Amazon Appstore

### ISSUE THREAD

**Issue by LouisStAmour** [microsoft/appcenter#2287]
Now that [Amazon Appstore is added to Windows 11](https://developer.amazon.com/blogs/appstore/post/a7583854-9367-4480-99c4-15f91456558c/amazon-and-microsoft-create-new-opportunities-for-developers-and-increase-return-on-investment-in-the-amazon-appstore), can we please get functionality to publish to it? See #816.

More about the Amazon Appstore: https://developer.amazon.com/apps-and-games

**Comment by LouisStAmour** [comment]
Please reopen.

**Comment by LouisStAmour** [comment]
Still relevant.

**Comment by alexmartinezm** [comment]
Agreed

**Comment by valentinsecades-lifx** [comment]
Yep, relevant Github, wake up

**Comment by tmadej** [comment]
+1

**Comment by vsecades-whitepages** [comment]
Not stale, wake up!
