### ISSUE TITLE
Distribute - Automatic resigning does not work

### ISSUE THREAD

**Issue by tahirmt** [microsoft/appcenter#2288]
**Describe the solution you'd like**
Whenever a new user is added to an app center organization group and they try to download one of the apps or if they get a new iOS device and try to download an old build, the ipa should automatically be resigned and distributed to them since we already have the certificates configured.

**Describe alternatives you've considered**
The only possible alternative is to manually go to a release and click distribute and under devices section for a group click resign manually. But this is a tedious manual process

**Additional context**
We are using fastlane to create the builds and upload to app center. We are not using app center to build. I think I read that it is available for app groups but it's just as tedious to maintain all users for each app. We would instead like to use organization groups.

**Comment by wisdeom** [comment]
might be related to #1072

**Comment by tahirmt** [comment]
It is not related. I’ll update my description. But basically we are only using distribute. The builds are produced by our CI using fastlane.

**Comment by wisdeom** [comment]
Hi @tahirmt! Do you mind opening a support ticket and leave the id here so that our engineering team can take a look into this? Thank you!

**Comment by tahirmt** [comment]
I used the contact support form to send a message about this. I did not receive any email immediately following that regarding created ticked so I suspect I will know about it once someone replies to it. I will update the thread here once that happens. Thank you.

**Comment by tahirmt** [comment]
Hi @wisdeom I created a ticket on app center. #KU3WRJ9D. The response I got is that the option is not available for org level groups and it is only available for app level groups. I would like it if it can be available for org level groups too.

**Comment by caolong24** [comment]
i still get error
