### ISSUE TITLE
drop down to select any app on top of any page

### ISSUE THREAD

**Issue by shalinasanga** [microsoft/appcenter#229]
**Describe the solution you'd like**
like in current hockey app, i would like to have top drop down to select apps from any view. then navigate to them.

**Comment by derpixeldan** [comment]
For reference:
![Screenshot 2019-03-27 at 10 19 54](https://user-images.githubusercontent.com/3369400/55064254-ee40cd80-5079-11e9-9bdf-7b9571e8b26d.png)

**Comment by blparr** [comment]
Thanks for your feedback! We will consider your feature request for upcoming improvements.
