### ISSUE TITLE
Move apps from HockeyApp to App Center

### ISSUE THREAD

**Issue by derpixeldan** [microsoft/appcenter#230]
The [Stage 2 of the HockeyApp Transition](https://docs.microsoft.com/en-us/appcenter/transition/) will enable to move apps from HockeyApp to App Center. It will remove the synchronization with HockeyApp, and give full control of the app in App Center.

Moving an app starts with a check indicating potential incompatibilities.
<img width="1792" alt="Screenshot 2019-03-27 at 10 45 28" src="https://user-images.githubusercontent.com/3369400/55066599-6b6e4180-507e-11e9-996f-24f51fb2783b.png">

Afterwards we inform about what data exactly is being moved from HockeyApp to App Center.
<img width="1792" alt="Screenshot 2019-03-27 at 10 46 49" src="https://user-images.githubusercontent.com/3369400/55066659-8b9e0080-507e-11e9-85c9-066ab023709a.png">

**Comment by lisional** [comment]
Hello,
Really cool, we are looking forward to this.

From [what I read](https://devblogs.microsoft.com/appcenter/a-new-year-ahead-the-hockeyapp-cutover-experience/) it was initially planned for end of march.

Any idea when it will be available? End of this iteration (== end of April) ?

Thanks!

**Comment by grevolution** [comment]
What's the current ETA on this one?

**Comment by derpixeldan** [comment]
The internal testing period was longer than initially expected but we're confident to open it to a limited audience this week before enabling it to anyone.

**Comment by nickfrollo** [comment]
Any update on when this is available? We're in a frustrating position where we want to move over to AppCenter due to things like HockeySDK not being maintained and blocking our move to Swift 5 (see https://github.com/bitstadium/HockeySDK-iOS/issues/548) All the support docs mention this move from HockeyApp to AppCenter button but I can't find it anywhere.

**Comment by derpixeldan** [comment]
@nickfrollo it's currently in closed beta. I can include you, either shoot me a DM on Twitter or reach out in support on App Center (the blue button) and ping me here so I can find the conversation.

**Comment by nickfrollo** [comment]
@derpixeldan Thanks, I've contacted you through AppCenter!

**Comment by herbig** [comment]
Hey @derpixeldan, I sent a message via Twitter.  Let me know if it's possible to get into the beta as well.  Thanks!

**Comment by lisional** [comment]
@derpixeldan I contacted you on twitter as well. Looking forward to testing this 🚀

**Comment by Jon889** [comment]
Is there an update on when it will be available to everyone?

**Comment by derpixeldan** [comment]
Update: During the closed beta, we've been moving apps successfully for a few weeks now. We're still monitoring each request independently. That way we've discovered a few smaller issues related to the validation mechanism. Those aren't a real problem for as long as we can manually step in. However, we're working on resolving the issues and improve the overall performance. We can't set a definitive ETA but it will be a few more weeks.

**Comment by Jon889** [comment]
@derpixeldan Thanks for the update!

**Comment by herbig** [comment]
@derpixeldan any updates on this?  And could I get in on the beta?  Thanks!

**Comment by ngreeney** [comment]
@derpixeldan any ETA on when it might be ready for the public?

**Comment by derpixeldan** [comment]
Update: We're pretty close, last missing piece is about GDPR compliance, which we're already working on.

**Comment by tompidom** [comment]
@derpixeldan do you have any update or ETA on this?

**Comment by rhinoid** [comment]
Am I right that this is a blocker for anyone wanting to migrate?  If so, it might be worth it actually highlighting this somewhere on am more visible page. I'm just bumping into this accidentally because I was browsing through the roadmap.

Also makes me wonder if there are more blockers which we have to wait for before we can actually move

**Comment by derpixeldan** [comment]
The option to [move apps from HockeyApp to App Center](https://appcenter.ms/hockeyapp-transition-center) is generally available now ⛴

**Comment by ngreeney** [comment]
@derpixeldan  This does not appear for me. I am an Admin for a "HockeyApp organization". Would the issue possibly be due to that? I can't find any way to move an app to App Center still.

**Comment by rbanker** [comment]
> The option to [move apps from HockeyApp to App Center](https://appcenter.ms/hockeyapp-transition-center) is generally available now ⛴

@derpixeldan We are not seeing the 'Move Apps' option either.  I've created a new organization in App Center, but looking at 'Overview' for any of our HockeyApp apps, I do not see of the options listed at the beginning of this ticket.

**Comment by rfree18** [comment]
@derpixeldan I saw the option to move apps briefly yesterday, but it seems to be gone today. Was this rolled back for some reason?

**Comment by msifniotis-bbc** [comment]
@derpixeldan Could you confirm please whether GDPR compliance step is also resolved?

**Comment by alexmanie** [comment]
> @derpixeldan I saw the option to move apps briefly yesterday, but it seems to be gone today. Was this rolled back for some reason?

same here :(

**Comment by derpixeldan** [comment]
Apologize for the radio silence, there was a huge rush on Monday and an API was getting slow causing timeouts. It wasn't a big deal and we limited the audience while fixing the issue. Long story short the fix influences the states in the UI and we're working on resolving that last piece before opening the gates again.

@msifniotis-bbc yes!

**Comment by derpixeldan** [comment]
It's back for everyone.

**Comment by nfox513** [comment]
I am having an issue where I click on the "Move this app" button but absolutely nothing happens in the UI. I am communicating with support but that have been unable to tell me anything, besides "try it again". Is there a bug in this feature?

**Comment by derpixeldan** [comment]
@nfox513 it's working. Can you please mention this thread in support and ask for escalation?

**Comment by inPhilly** [comment]
I can't figure out how to specify the beta version of my app as beta. It doesn't seem like AppCenter makes any distinction between a live version and a beta version of an app. Also, there is no tool like Hockey App to upload an archive once it has been created.
