### ISSUE TITLE
Live Chat or Phone Support

### ISSUE THREAD

**Issue by devinm-hrbl** [microsoft/appcenter#2308]
I'd like to request the ability to chat live or call someone from appcenter support. We are in an urgent time-sensitive situation and cannot wait an unknown amount of time to hear back from someone, only to email them back and hope they receive it, understand it, and can help us to respond in yet another unknown amount of time.

For urgent requests, we would like the ability to communicate live with a human.
Thank you

**Comment by akamenev** [comment]
Hi @devinm-hrbl and thanks for the feedback! Unfortunately, that's not something we will implement in the near future. In a mission-critical and time-sensitive environment, our customers usually rely on Microsoft Premier Support which can handle cases with high severity, including cases related to App Center. You can find more info about it [here](https://www.microsoft.com/en-us/unifiedsupport/premier).
