### ISSUE TITLE
Access to Build Id via environment variables

### ISSUE THREAD

**Issue by Giorgi** [microsoft/appcenter#2309]
AppCenter can set the build number to an auto-incrementing number but we cannot customize the format of the version. For example, we can not set the build number as 1.0.{BuildId}

AppCenter exposes several environment variables but we do not have access to Build Id as an environment variable.

Either give us a way to set build number format or expose Build Id as an environment variable so that we can set format using custom build script.

**Comment by ahmedalejo** [comment]
Hi @Giorgi, if I'm not mistaken `APPCENTER_BUILD_ID` is available as an environment variable. 

For a full list of supported variables please go to  [Build Environment variables](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/).
Also, take a look at [VS App Center Custom Build Scripts for Production Apps](https://montemagno.com/vs-app-center-custom-build-scripts-for-production-apps/) by @jamesmontemagno for how you could use it in your [custom build scripts](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts).

Send your feedback afterwards.
