### ISSUE TITLE
Support Xcode 13.1 + Xamarin.iOS 15.2.0.1

### ISSUE THREAD

**Issue by beeradmoore** [microsoft/appcenter#2316]
**Describe the solution you'd like**
Updated SDKs as described in #2271 

**Describe alternatives you've considered**
Installing Xamarin.iOS 15.2.0.1 via boots, but we have problems that require the Xcode 13.1.
Migrating to GitHub actions for build and only using AppCenter for distribution.

**Additional context**
Xcode 13.1 has been out since October 25th (a little over 2 weeks since writing of this issue)
Xamarin.iOS 15.2.0.1 has been out since November 3rd-ish (about 9 days since writing of this issue)

Xcode 13.1 was added to GitHub actions a little while ago, Xamarin.iOS 15.2.0.1 was added yesterday.

**Comment by iXyles** [comment]
We're also experiencing issues regarding this combination, but locally instead - which makes writing tests & doing tests on iOS not possible for the current time being.

**Comment by beeradmoore** [comment]
![Screen Shot 2021-11-17 at 2 42 40 pm](https://user-images.githubusercontent.com/904737/142130847-7fde7252-dcba-48f3-ac5e-9cec57893e23.png)


Xamarin.iOS 15.2.0.1 has rolled out, but the build system is apparently using Xcode 13.2 which as of writing this is beta 2. [Virtual Environments](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode) lists that as 13.2 beta 1.

My build log says:
>   Xamarin.iOS 15.2.0.1 (xcode13.1: 8fd9e6289) using framework: /Applications/Xcode_13.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk

I don't know enough about this setup to know if its using xcode13.1 with some parts from 13.2b1, or is this just using 13.2b1 or what.

**Comment by pgiacomo69** [comment]
Hi, currently I'm not using Xamarin, so I don't know how appcenter scripts work in this case, but I'll take a longshot anyway:
Compiling a IOS App using "React native" configuration I saw that the XCode Version is at step "8_Set Xcode path" , subsequently, at step "13_Pre Build Script" the "appcenter-pre-build.sh" user script is called, before actual build.
You can try to put such script in the repository, containing this command:

`sudo xcode-select -switch /Applications/Xcode_13.1.app`

and activate it from build options. If this doesn't conflict with steps between 8 and 13, it could work!

**Comment by beeradmoore** [comment]
This has now been resolved and Xcode 13.1 and Xamarin.iOS 15.2 is now available.
