### ISSUE TITLE
Add supporto to Xamarin.Android 12

### ISSUE THREAD

**Issue by scherici** [microsoft/appcenter#2317]
**Describe the solution you'd like**
Actually I cannot build xamarin app that target API level 31 (Android 12)

**Describe alternatives you've considered**
No alternative...project i blocked due to this issue

**Additional context**
As stated here https://github.com/actions/virtual-environments/blob/macOS-11/20211106.1/images/macos/macos-11-Readme.md#xamarin-bundles it seems that xamarin.android 12 is already installed on build agent, but whe i run the buil I get this error:
`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(261,5): error XA0000: Could not determine API level for $(TargetFrameworkVersion) of 'v12.0'.`

**Comment by pavshr** [comment]
@scherici
Did you try to add `<AndroidUseLatestPlatformSdk>True</AndroidUseLatestPlatformSdk>` in your Android project file for the configuration you are building in App Center? It seems to solve the same issue when building the app in Azure Pipelines with the newest Microsoft-hosted macOS agent.

**Comment by scherici** [comment]
Hi, yes I tried but the error still the same. 
As a workaround at the moment (but I don't like that...) I add in pre build script this code:
`/Users/runner/runners/2.195.0/scripts/select-xamarin-sdk.sh 6_12_11`

Because I've seen that there is a task (just before the build task) that perform this: 

```
##[section]Starting: Set Xamarin SDK Bundle
==============================================================================
Task         : Shell script
Description  : Run a shell script using Bash
Version      : 2.193.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/shell-script
==============================================================================
[command]/bin/bash /Users/runner/runners/2.195.0/scripts/select-xamarin-sdk.sh 6_12_9
Set Xamarin SDK to 6_12_9
Set Current folder for /Library/Frameworks/Mono.framework/Versions
Set Current folder for /Library/Frameworks/Xamarin.iOS.framework/Versions
Set Current folder for /Library/Frameworks/Xamarin.Android.framework/Versions
Set Current folder for /Library/Frameworks/Xamarin.Mac.framework/Versions
##[section]Finishing: Set Xamarin SDK Bundle
```

and version 6_12_9 does not support Xamarin.Android  12 but 11.3 - see here: [xamarin-bundles](https://github.com/actions/virtual-environments/blob/macOS-11/20211106.1/images/macos/macos-11-Readme.md#xamarin-bundles).

Note...this is not a solution...just an horrible workaround

**Comment by bricefriha** [comment]
Can we reopen the issue unless this one has really been fixed? please

**Comment by justintoth** [comment]
It has NOT been fixed, I'm running into the same issue with AppCenter. Setting AndroidUseLatestPlatformSdk to true is not an option, as this setting has been deprecated.

**Comment by scherici** [comment]
Hello, I've remove the "ugly" command on my pre build script and update SDK version in the build definition to Android 12.0

<img width="242" alt="image" src="https://user-images.githubusercontent.com/89917471/161920437-a367705b-9081-406a-971f-aa3fe8e3b5c8.png">

Now the build work good.
NOTE: I do not use AndroidUseLatestPlatformSdk in project file.

Hope it helps
