### ISSUE TITLE
App Center and Hockeyapp show different set of app releases

### ISSUE THREAD

**Issue by dfiggtns** [Microsoft/appcenter#232]
**What App Center service does this affect?**
The Releases page in App Center.

**Describe the bug**
App Center and Hockeyapp show a different set of app releases.

Hockeyapp shows the full set of releases I've uploaded, but App Center is missing quite a lot of them.

Also, the Releases page in App Center only shows the last 10 releases, whereas Hockeyapp shows all the releases.

**To Reproduce**
N/A

**Expected behavior**
App Center should show the same set of releases as Hockeyapp.

App Center should give the option of showing all releases or at least the ability to page through them.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by derpixeldan** [comment]
@dfiggtns can you please reach out to us in support (blue button in App Center) so we can have a closer look at this? App Center is lazy loading the releases on the release page and it's definitely more than 10 for apps synced from HockeyApp.

**Comment by patniko** [comment]
Hi @dfiggtns, closing this for now assuming you reached out to our direct support. Please let us know if you have any trouble contacting us through our main support channels. Thanks!
