### ISSUE TITLE
Support for existing cordova app from April 2022

### ISSUE THREAD

**Issue by manhstore** [microsoft/appcenter#2323]
Hello,

We are using the App Center for crash reporting in our enterprise app, which is built using ionic/cordova, utilising the cordova sdk plugin provided by App Center, both on Android and iOS platform.

We are not pushing the crash reports to the App Center portal, instead we get the report from SDK and use it in our internal reports, by setting the APPCENTER_CRASHES_ALWAYS_SEND as false.

Since the cordova support is getting dropped from April 2022, what are the options we have if we want to continue using app center? 

After April 2022, will the cordova plugin initialize and collect the crashes or even that wont happen? Please let us know so that we can plan accordingly.

**Comment by manhstore** [comment]
We have raised an support ticket in app center portal, we got a response, asking to raise a ticket here

**Comment by AnastasiaKubova** [comment]
If you will use the App Center Cordova SDK after April 2022 then it continue to work as usual on the client side. But we cannot guarantee how it will work on the new Android and iOS versions.

I’m closing this issue but feel free to reopen this issue if you have additional questions.
