### ISSUE TITLE
Allow setting manageAppVersionAndBuildNumber when building iOS apps

### ISSUE THREAD

**Issue by RubenCouckeACA** [microsoft/appcenter#2324]
Since XCode 13, every appcenter build changes the app version and build number of the frameworks in our iOS application. This causes issues for some of our frameworks because they depend on a correct version number of that framework. This started happening since Xcode 13 because Apple silently added a flag (or maybe it was already there but default FALSE) called `manageAppVersionAndBuildNumber`.  See https://developer.apple.com/forums/thread/690647 for more context. We need to be able to set this parameter to FALSE in order to continue building correct ipa's using appcenter.

**Comment by YarKaras** [comment]
Critical issue in our case.

**Comment by cesarAugustoButchershop** [comment]
is there any workaround to disable this setting? We are having app crashes because of this setting being enabled by default and we cannot downgrade the Xcode version.

**Comment by jbagaresgaray** [comment]
Any news on this? How are we going to disable it on AppCenter?

**Comment by Syamnath-Vis** [comment]
I have come across the same issue, and written to app center team and got this thread.

How to deselect Manage version and build number when we distribute the build ? (this option is available on xcode manual build)

This is bit urgent as there is a serious issue reported from one of our high rated app, Looking forward for an advise on this

**Comment by andreslopezsarmiento** [comment]
We are also affected by this. It would be nice to get a fix or workaround since this is potentially the root cause for blocker issues.

**Comment by CesarSanchez-87** [comment]
> We are also affected by this. It would be nice to get a fix or workaround since this is potentially the root cause for blocker issues.

This is the workaround i did and it's working for me.

- Create on your repo a file called appcenter-post-build.sh with the following content
```
if [ "$APP_CENTER_CURRENT_PLATFORM" != "android" ]
then
  echo "Add manageAppVersionAndBuildNumber to the exportOptionsPlist that the Pipeline always create to build"
  /usr/libexec/PlistBuddy -c 'Add manageAppVersionAndBuildNumber bool 0' _XcodeTaskExportOptions.plist

  echo "Run the build process again but this time with manageAppVersionAndBuildNumber as false on the exportOptionsPlist"
  /usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/output/build/archive/bittrexMTrade.xcarchive -exportPath /Users/runner/work/1/output/build/export/_XcodeTaskExport_bittrexMTrade -exportOptionsPlist _XcodeTaskExportOptions.plist

  echo "The build has finished move the IPA file to the place where it should be to be uploaded to the AppStore"
  mv /Users/runner/work/1/output/build/export/_XcodeTaskExport_bittrexMTrade/Bittrex.ipa /Users/runner/work/1/a/build/Bittrex.ipa

  echo "The process has completed successfully"
fi

exit
```

Understanding the script:
 The pipeline build process creates a temporary exportOptionsPlist file called _XcodeTaskExportOptions as this is not being deleted on this point, we can reuse it and just add the flag we are needing "manageAppVersionAndBuildNumber" with the value we need(false) then we re-run the build process, at the end of the build process we just move the generated IPA file to where the previous build process moved the previous IPA. The next step is to upload the ipa to Apple App Store connect and that process is the normal behavior of the pipeline, so it will upload the IPA we just created with the flag we need.

Note the xcodebuild command and the mv command are exactly the same than the pipeline runs both were copied from the pipeline logs.

**Comment by abdulahad96** [comment]
> > We are also affected by this. It would be nice to get a fix or workaround since this is potentially the root cause for blocker issues.
> 
> This is the workaround i did and it's working for me.
> 
> * Create on your repo a file called `appcenter-post-build.sh` with the following content
> 
> ```
> if [ "$APP_CENTER_CURRENT_PLATFORM" != "android" ]
> then
>   echo "Add manageAppVersionAndBuildNumber to the exportOptionsPlist that the Pipeline always create to build"
>   /usr/libexec/PlistBuddy -c 'Add manageAppVersionAndBuildNumber bool 0' _XcodeTaskExportOptions.plist
> 
>   echo "Run the build process again but this time with manageAppVersionAndBuildNumber as false on the exportOptionsPlist"
>   /usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/output/build/archive/YOUR_APP.xcarchive -exportPath /Users/runner/work/1/output/build/export/_XcodeTaskExport_YOUR_APP -exportOptionsPlist _XcodeTaskExportOptions.plist
> 
>   echo "The build has finished move the IPA file to the place where it should be to be uploaded to the AppStore"
>   mv /Users/runner/work/1/output/build/export/_XcodeTaskExport_YOUR_APP/YOUR_APP.ipa /Users/runner/work/1/a/build/YOUR_APP.ipa
> 
>   echo "The process has completed successfully"
> fi
> 
> exit
> ```
> 
> Understanding the script: The pipeline build process creates a temporary exportOptionsPlist file called _XcodeTaskExportOptions as this is not being deleted on this point, we can reuse it and just add the flag we are needing "manageAppVersionAndBuildNumber" with the value we need(false) then we re-run the build process, at the end of the build process we just move the generated IPA file to where the previous build process moved the previous IPA. The next step is to upload the ipa to Apple App Store connect and that process is the normal behavior of the pipeline, so it will upload the IPA we just created with the flag we need.
> 
> Note the xcodebuild command and the mv command are exactly the same than the pipeline runs both were copied from the pipeline logs.
> 
> Change where it says YOUR_APP by your App Ipa name. You can find what your pipeline is using by downloading the logs and searching for those lines and then substitute it on your own script.

Hi there.
I followed your suggestion but facing issue of build failed in appcenter can you please look at the log .
**APP CENTER LOG** 
 `Add manageAppVersionAndBuildNumber to the exportOptionsPlist that the Pipeline always create to build
File Doesn't Exist, Will Create: _XcodeTaskExportOptions.plist
Run the build process again but this time with manageAppVersionAndBuildNumber as false on the exportOptionsPlist
error: archive not found at path '/Users/runner/work/1/output/build/archive/App.xcarchive'
** EXPORT FAILED **
**SCRIPT IN postbuild.sh**
The build has finished move the IPA file to the place where it should be to be uploaded to the AppStore
mv: rename /Users/runner/work/1/output/build/export/_XcodeTaskExport_App/App.ipa to /Users/runner/work/1/a/build/App.ipa: No such file or directory
The process has completed successfully`
if [ "$APP_CENTER_CURRENT_PLATFORM" != "android" ]
then
  echo "Add manageAppVersionAndBuildNumber to the exportOptionsPlist that the Pipeline always create to build"
  /usr/libexec/PlistBuddy -c 'Add manageAppVersionAndBuildNumber bool 0' _XcodeTaskExportOptions.plist

  echo "Run the build process again but this time with manageAppVersionAndBuildNumber as false on the exportOptionsPlist"
  /usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/output/build/archive/$PRODUCT_NAME.xcarchive -exportPath /Users/runner/work/1/output/build/export/_XcodeTaskExport_$PRODUCT_NAME -exportOptionsPlist _XcodeTaskExportOptions.plist

  echo "The build has finished move the IPA file to the place where it should be to be uploaded to the AppStore"
  mv /Users/runner/work/1/output/build/export/_XcodeTaskExport_$PRODUCT_NAME/$PRODUCT_NAME.ipa /Users/runner/work/1/a/build/$PRODUCT_NAME.ipa

  echo "The process has completed successfully"
fi

exit
assist me

**Comment by CesarSanchez-87** [comment]
> > > We are also affected by this. It would be nice to get a fix or workaround since this is potentially the root cause for blocker issues.
> > 
> > 
> > This is the workaround i did and it's working for me.
> > 
> > * Create on your repo a file called `appcenter-post-build.sh` with the following content
> > 
> > ```
> > if [ "$APP_CENTER_CURRENT_PLATFORM" != "android" ]
> > then
> >   echo "Add manageAppVersionAndBuildNumber to the exportOptionsPlist that the Pipeline always create to build"
> >   /usr/libexec/PlistBuddy -c 'Add manageAppVersionAndBuildNumber bool 0' _XcodeTaskExportOptions.plist
> > 
> >   echo "Run the build process again but this time with manageAppVersionAndBuildNumber as false on the exportOptionsPlist"
> >   /usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/output/build/archive/YOUR_APP.xcarchive -exportPath /Users/runner/work/1/output/build/export/_XcodeTaskExport_YOUR_APP -exportOptionsPlist _XcodeTaskExportOptions.plist
> > 
> >   echo "The build has finished move the IPA file to the place where it should be to be uploaded to the AppStore"
> >   mv /Users/runner/work/1/output/build/export/_XcodeTaskExport_YOUR_APP/YOUR_APP.ipa /Users/runner/work/1/a/build/YOUR_APP.ipa
> > 
> >   echo "The process has completed successfully"
> > fi
> > 
> > exit
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Understanding the script: The pipeline build process creates a temporary exportOptionsPlist file called _XcodeTaskExportOptions as this is not being deleted on this point, we can reuse it and just add the flag we are needing "manageAppVersionAndBuildNumber" with the value we need(false) then we re-run the build process, at the end of the build process we just move the generated IPA file to where the previous build process moved the previous IPA. The next step is to upload the ipa to Apple App Store connect and that process is the normal behavior of the pipeline, so it will upload the IPA we just created with the flag we need.
> > Note the xcodebuild command and the mv command are exactly the same than the pipeline runs both were copied from the pipeline logs.
> > Change where it says YOUR_APP by your App Ipa name. You can find what your pipeline is using by downloading the logs and searching for those lines and then substitute it on your own script.
> 
> Hi there. I followed your suggestion but facing issue of build failed in appcenter can you please look at the log . **APP CENTER LOG** `Add manageAppVersionAndBuildNumber to the exportOptionsPlist that the Pipeline always create to build File Doesn't Exist, Will Create: _XcodeTaskExportOptions.plist Run the build process again but this time with manageAppVersionAndBuildNumber as false on the exportOptionsPlist error: archive not found at path '/Users/runner/work/1/output/build/archive/App.xcarchive' ** EXPORT FAILED ** **SCRIPT IN postbuild.sh** The build has finished move the IPA file to the place where it should be to be uploaded to the AppStore mv: rename /Users/runner/work/1/output/build/export/_XcodeTaskExport_App/App.ipa to /Users/runner/work/1/a/build/App.ipa: No such file or directory The process has completed successfully` if [ "$APP_CENTER_CURRENT_PLATFORM" != "android" ] then echo "Add manageAppVersionAndBuildNumber to the exportOptionsPlist that the Pipeline always create to build" /usr/libexec/PlistBuddy -c 'Add manageAppVersionAndBuildNumber bool 0' _XcodeTaskExportOptions.plist
> 
> echo "Run the build process again but this time with manageAppVersionAndBuildNumber as false on the exportOptionsPlist" /usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/output/build/archive/$PRODUCT_NAME.xcarchive -exportPath /Users/runner/work/1/output/build/export/_XcodeTaskExport_$PRODUCT_NAME -exportOptionsPlist _XcodeTaskExportOptions.plist
> 
> echo "The build has finished move the IPA file to the place where it should be to be uploaded to the AppStore" mv /Users/runner/work/1/output/build/export/_XcodeTaskExport_$PRODUCT_NAME/$PRODUCT_NAME.ipa /Users/runner/work/1/a/build/$PRODUCT_NAME.ipa
> 
> echo "The process has completed successfully" fi
> 
> exit assist me

Seems like App.ipa is not your ipa name. When you build your app on Xcode it creates a file in a folder called Products. Take a look at that name and try with that same. Also i'm seeing this on your code XcodeTaskExport$PRODUCT_NAME and it should be XcodeTaskExport_$PRODUCT_NAME. Check that and try again.

**Comment by CesarSanchez-87** [comment]
No, it will not work. My suggestion to make this right is to download the log of the pipeline, any can work a fail or success log, and then just open it with any text editor and look for the text of each line that is failing like this `/usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/output/build/archive/` and complete it with the right file names. That what i did and it worked for me.

**Comment by djMax** [comment]
This workaround didn't seem to work for our app, I'm not yet sure why. It runs successfully, but the version number of contained frameworks is still mangled.

**Comment by jbagaresgaray** [comment]
Hi @CesarSanchez-87 I would like to say thank you... because your suggestion definitely work on my end
![image](https://user-images.githubusercontent.com/3625802/175565641-3de33b00-4f53-4826-946a-14f436cc9a4f.png)

In fact mine has multiple scheme setup.. but the key there is to check the logs to make sure you are using the correct App Name and other namings.

Kudos mate...

**Comment by andreslopezsarmiento** [comment]
any news about this? Even if workaround works (which for some reason doesn't seem to do in our case), it is still a workaround. A proper solution would be appreciated.

**Comment by djMax** [comment]
"This issue has been marked stale because nobody really maintains AppCenter anymore and we're not interested in actually making it build apps or be any sort of... center for... apps."
