### ISSUE TITLE
appcenter.ms  analytics/overview/Top devices

### ISSUE THREAD

**Issue by kingnight** [microsoft/appcenter#2327]
**Describe the solution you'd like**
In appcenter.ms,  At analytics/overview/Top devices, OS Distribution data only show other, please show complete detailed data, percent of OS Distribution

**Describe alternatives you've considered**

**Additional context*
<img width="401" alt="截屏2021-11-23 14 43 54" src="https://user-images.githubusercontent.com/3960032/142980938-79ea33ef-b2ed-445d-9728-d4a3b69889c2.png">
*

**Comment by ryanholden8** [comment]
Our team is experiencing the same issue.  
An extremely important question any mobile app team asks:

> **_Which OS versions can we drop or need to support?_**

The current graph does not answer it in the slightest since the useful info is lost in the "Other" part of OS distribution.

Thank you App Center Team for considering.

**Comment by ryanholden8** [comment]
@AnastasiaKubova - Would it be possible to request a roadmap for this request? Seems like low hanging fruit which answers a question every app developer needs to know.

**Comment by kingnight** [comment]
yes， need so much

**Comment by ryanholden8** [comment]
@AnastasiaKubova - Please let us know if there is anything we can do to help move this request along..
