### ISSUE TITLE
React native build for android get error when Distribute builds switch on

### ISSUE THREAD

**Issue by lejng** [microsoft/appcenter#2329]
I get error for build React Native app (Android)
#[error]Error: Found multiple files matching /Users/runner/work/1/a/build/**/*.apk.
But when I switch off Distribute builds works fine
Could you help me with this?
![image](https://user-images.githubusercontent.com/17721125/143439665-470d6b10-7e21-4b56-876d-f6c574eddf6b.png)
![image](https://user-images.githubusercontent.com/17721125/143439772-f933e7b6-9948-47e8-934a-d7476555afd9.png)

**Comment by spsaucier** [comment]
I'm having this issue as well. Unsure what the cause is. @lejng Did you resolve this on yours?

**Comment by ashish-d-hh** [comment]
Facing same one for my Flutter code
