### ISSUE TITLE
add post-distributon build script

### ISSUE THREAD

**Issue by vonovak** [microsoft/appcenter#233]
Currently, [post-build](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#post-build) script is available to run things after the build.

However, I'd like to be able to run custom script *after* a successful app distribution has happened.

This is useful for automating tasks in our ticketing system - when I run the task in post-build script, there is no guarantee of a successful app distribution. I would like to know the app was distributed successfully before running the tasks.

Perhaps the script could simply run at the very end of the build - not necessarily after distribution - and would be named accordingly.

**Comment by kuyazee** [comment]
Related #69

**Comment by nchase** [comment]
is this on the App Center roadmap?
