### ISSUE TITLE
HockeyApp Feedback Service

### ISSUE THREAD

**Issue by petero-dk** [microsoft/appcenter#2333]
In Hockey App there is the possibility to have a feedback service, we have started integration with AppCenter (not upgraded from HockeyApp) but would like to have user feedback in-app. 

It is not possible to have AppCenter and HockeyAppSDK sidebyside because of the crash reporting native libraries in iOS, however the AppCenter roadmap does not have any indication of the HockeyApp Feedback/Chat system.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
