### ISSUE TITLE
Multiple public distribution groups

### ISSUE THREAD

**Issue by AlphaNERD-** [microsoft/appcenter#2334]
**Is your feature request related to a problem? Please describe.**
I wish to use the AppCenter Distribute module in my app. Currently we have multiple different means to deploy our app and AppCenter would make this easier for us. At least on paper.

We would like to not have our customers create a Microsoft Account in order to get updates via Appcenter. We can do that using public distribution groups but then EVERY user would get an update. We prefer to not send updates to all customers at once.

**Describe the solution you'd like**
I suggest a property in the Distribute SDK that allows me to set a distribution group to check updates on. Something like `Distribute.DistributionGroup = "Contoso";`. That would give me full control on who receives an update without having to get all our users to create Microsoft Accounts.

**Describe alternatives you've considered**
I was looking into checking the `ReleaseNotesUrl` to determine whether the update is supposed to be installed on the customers phones. However for some reason the callback `OnReleaseAvailable` doesn't seem to work (see microsoft/appcenter-sdk-dotnet#1510). I also tried to set the group url using `SetInstallUrl()` but it didn't seem to work either.

**Additional context**

**Comment by MikhailSuendukov** [comment]
Hello, thank you for reaching out to us. Could you please provide a detailed description of how this feature is implemented from your perspective?

**Comment by brzezinol** [comment]
> Hello, thank you for reaching out to us. Could you please provide a detailed description of how this feature is implemented from your perspective?

I have on-premise solution so I need to control which installation have been updated API to version which is sufficent to do update on its mobile devices. I use app center distribute OnReleaseAvailable event, and I ask my common server for conditions for upcoming build version. If conditions are met for such installation, I showing update message for user. 
App also send intallation id in request so update server could check if update is available for particular installation.

**Comment by lucen-ms** [comment]
Thanks @brzezinol for reaching to us but we do not plan to implement this feature.
