### ISSUE TITLE
Adding Specific properties to "native" logs

### ISSUE THREAD

**Issue by sescandell** [microsoft/appcenter#2335]
Hi,

**Context**: Xamarin for iOS and Android.

Is there any way to add custom properties to auto-generated logs like the `StartSession` one?
We would like to add some "contextual" informations to all of these events as we can do with TrackEvent and the `properties` parameter.

Is this possible?

Thanks,

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
