### ISSUE TITLE
I have this problem with iOS build

### ISSUE THREAD

**Issue by cmartinezglbnt** [microsoft/appcenter#2337]
I have this problem with iOS build and it's so anoying. 

I don't why, but my distribution to the Appstore Testflight it's failing with error "distribution store with id xxxx does not exist", but the App build it's ok, it's only the distribution step. 

_Originally posted by @francovp in https://github.com/microsoft/appcenter/issues/587#issuecomment-764954593_

**Comment by miroslavmatovic** [comment]
Hi @cmartinezglbnt, first make sure that you have created your store connection in Distribution > Stores page, and then go to your branch configuration under Build, and first unselect and then select again one of your existing Store connections as target in the "Distribute builds" section.
This error you're seeing probably comes from last branch configuration with a previous store connection, that may no longer exist.

**Comment by miroslavmatovic** [comment]
Hi @cmartinezglbnt . May I ask if your issue is resolved?

**Comment by cmartinezglbnt** [comment]
Hi @miroslavmatovic yes is resolved, thanks. I've changed the distribution user profile and the distribution store config was reloaded.

**Comment by kub1x** [comment]
Would it be possible to warn user about unset Stores configuration a bit sooner? Like before he waits an hour for the build to finish ;)
