### ISSUE TITLE
Add an ability to upload Certificates & Provisioning Profiles for App Clips target

### ISSUE THREAD

**Issue by antoniosdev123** [microsoft/appcenter#2340]
**Describe the solution you'd like**
App Center will provide an option to upload additional Certificates & Provisioning Profiles in case if Xcode project contains App Clips target. Because currently, since your project has it - you can not use App Center for iOS builds (an error: "Xcode couldn't find any iOS App Development provisioning profiles matching 'com.xxx.xxx.Clip'.")

**Additional context**
[Closed, but not fixed issue with the same problem](https://github.com/microsoft/appcenter/issues/2118)
[App Clip documentation](https://developer.apple.com/documentation/app_clips)

**Comment by antonioberetini** [comment]
Any update on this?? App Clips have been out on iOS since 2014 and you guys still dont support this.

**Comment by akamenev** [comment]
Hi @antoniosdev123, thanks for the feature request! 
As we are currently prioritizing reliability and stability of service, unfortunately, we cannot grab this work item any time soon.

**Comment by dohyeonio** [comment]
Out team had to use other tools since we do have App Clips target and could not use MS App Center anymore. Sad day...
