### ISSUE TITLE
Got the error "Installed Build Tools revision 31.0.0 is corrupted."

### ISSUE THREAD

**Issue by hungkoala** [microsoft/appcenter#2341]
> Configure project :voxeet_react-native-voxeet-conferencekit
Resolved com.android.tools.build:gradle:4.2.1 in :voxeet_react-native-voxeet-conferencekit:classpath 
Project voxeet_react-native-voxeet-conferencekit at :voxeet_react-native-voxeet-conferencekit is either no Android app project or build version has not been set to override. Skipping...
Resolved org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50 in :react-native-agora:kotlinCompilerClasspath 
Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
Build-tool 31.0.0 is missing DX at /Users/runner/Library/Android/sdk/build-tools/31.0.0/dx
Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
File /Users/runner/.android/repositories.cfg could not be loaded.
Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
Build-tool 31.0.0 is missing DX at /Users/runner/Library/Android/sdk/build-tools/31.0.0/dx

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':notifee_react-native:compileReleaseAidl'.
> Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 51s

**Comment by IonoclastBrigham** [comment]
Get this for both 31.0.0 and 32.0.0.

**Comment by benmagos** [comment]
Experiencing this issue as well.

**Comment by Albermonte** [comment]
Still happening, don't close this

**Comment by IonoclastBrigham** [comment]
@Arkan4ik 

You can patch the build tools from a script named `appcenter-pre-build.sh` in the root of your repo. The issue is that the build tool `dx` was renamed, so any older dependencies that rely on it directly no longer work. Since you're on 32, a naïve implementation could look something like:

```bash
#!/bin/bash
ln -s "$ANDROID_HOME/build-tools/32.0.0/d8" "$ANDROID_HOME/build-tools/32.0.0/dx"
ln -s "$ANDROID_HOME/build-tools/32.0.0/lib/d8.jar" "$ANDROID_HOME/build-tools/32.0.0/lib/dx.jar"
```

**Comment by HagarAyad** [comment]
> @Arkan4ik
> 
> You can patch the build tools from a script named `appcenter-pre-build.sh` in the root of your repo. The issue is that the build tool `dx` was renamed, so any older dependencies that rely on it directly no longer work. Since you're on 32, a naïve implementation could look something like:
> 
> ```shell
> #!/bin/bash
> ln -s "$ANDROID_HOME/build-tools/32.0.0/d8" "$ANDROID_HOME/build-tools/32.0.0/dx"
> ln -s "$ANDROID_HOME/build-tools/32.0.0/lib/d8.jar" "$ANDROID_HOME/build-tools/32.0.0/lib/dx.jar"
> ```

Thanks , this solution worked with me

**Comment by glennweb** [comment]
Yeah, I am also having this issue with out RN Build. For me adding those scripts does not seem to help. 

Build-tool 31.0.0 is missing DX...

**Comment by SaadBinWaheed-empglabs** [comment]
Still facing the same error.

**Comment by HoangNgocThang** [comment]
A problem occurred configuring project ':react-native-appearance'.
> Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.

**Comment by machiapply** [comment]
This solution used to work
```
#!/bin/bash
ln -s "$ANDROID_HOME/build-tools/33.0.0/d8" "$ANDROID_HOME/build-tools/33.0.0/dx"
ln -s "$ANDROID_HOME/build-tools/33.0.0/lib/d8.jar" "$ANDROID_HOME/build-tools/33.0.0/lib/dx.jar"
```
but not anymore when I try to use Xcode version above 14.2, says 
```
[command]/bin/bash /Users/runner/work/1/s/appcenter-pre-build.sh
ln: /Users/runner/Library/Android/sdk/build-tools/33.0.0/dx: No such file or directory
ln: /Users/runner/Library/Android/sdk/build-tools/33.0.0/lib/dx.jar: No such file or directory
```
I needed to upgrade for other reasons, but the build fails for the error above, thought to leave it in 14.2, but Apple started warning that we must build with  Xcode 15 or later soon anyways (April 24). Any solution?

using `"appcenter": "^5.0.1"` and `"appcenter-crashes": "^5.0.1"`

**Comment by machiapply** [comment]
Having this in `appcenter-pre-build.sh` worked well in the past:
```
#!/bin/bash
ln -s "$ANDROID_HOME/build-tools/33.0.0/d8" "$ANDROID_HOME/build-tools/33.0.0/dx"
ln -s "$ANDROID_HOME/build-tools/33.0.0/lib/d8.jar" "$ANDROID_HOME/build-tools/33.0.0/lib/dx.jar"
``` 
Until recently tried to build with later version of Xcode 1.4.2, getting this error now:
```
[command]/bin/bash /Users/runner/work/1/s/appcenter-pre-build.sh
ln: /Users/runner/Library/Android/sdk/build-tools/33.0.0/dx: No such file or directory
ln: /Users/runner/Library/Android/sdk/build-tools/33.0.0/lib/dx.jar: No such file or directory
```
Using `"appcenter": "^5.0.1"` and `"appcenter-crashes": "^5.0.1"`. Any idea?

**Comment by bhatvinayak** [comment]
This issue is still happening for me.
**Error: Installed Build Tools revision 33.0.0 is corrupted. Remove and install again using the SDK Manager.**

I have the file and the contents in `appcenter-pre-build.sh` already and still it is not working.
Using grade 4.2.2

Any solution for this?

**Comment by machiapply** [comment]
In my case, I had to change `33.0.0` to `33.0.2` while using Xcode 15.2, which has either `33.0.2` or `33.0.3`.

**Comment by bhatvinayak** [comment]
> In my case, I had to change `33.0.0` to `33.0.2` while using Xcode 15.2, which has either `33.0.2` or `33.0.3`.

Tried this seems to be working but I'm getting some random error on the first build, If I try second time I'm getting same corrupted build tool error.
