### ISSUE TITLE
Logging metrics using custom events 

### ISSUE THREAD

**Issue by degant** [microsoft/appcenter#2343]
The properties object in the custom events tracking lets us track useful properties and aggregate them (and show count and other useful data). Would love to see the same being extended to metrics as well. Similar to what the Application Insights SDK supports. 

Our scenario involves sending a few important numbers as metrics for an event. We're using properties as a workaround right now but that isn't useful since numeric values have a larger range and don't show up how we would like them to.

Essentially looking for something like this:
`TrackEvent("My Event", Dictionary<string, string> properties, Dictionary<string, double> metrics)`

Links for AI SDK TrackEvent with metrics:
https://social.technet.microsoft.com/wiki/contents/articles/31192.custom-telemetry-events-with-trackevent-in-microsoft-application-insights.aspx
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#trackevent

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
