### ISSUE TITLE
Distribution issues - Failed to upload iOS binary to appcenter 

### ISSUE THREAD

**Issue by marcomoscatiello** [microsoft/appcenter#2344]
Bitrise is failing to upload ipa files to appcenter, seems something from on Appcenter API. 
we currently get an error like this:

Release created with ID: -1
2021/12/14 14:46:10 [DEBUG] GET https://api.appcenter.ms/v0.1/apps/TDA-Organization/iOS-BE-TF-Develop/releases/-1
Failed to create new release, error: invalid status code: 400, url: https://api.appcenter.ms/v0.1/apps/TDA-Organization/iOS-BE-TF-Develop/releases/-1, body: {0           false 0     []       [] [] [] false false {  } false  false : }

Can someone please investigate?

**Comment by joemather** [comment]
The AppCenter website is also failing.  Pages are very slow to load, or fail completely.

Clearly an outage has begun.

**Comment by joemather** [comment]
[Status page](https://status.appcenter.ms) says systems are operational, except for Distribution which has "Degraded Performance".

That is inaccurate.  Distribution is completely down.  Whether you do Build -> ... -> Distribute or you do Distribute -> Releases, the release is not created.  No email is sent, and no build is available on install.appcenter.ms.

**Comment by brettins** [comment]
I am seeing build times of more than an hour for 10-15 minute build cycles, which then fail out.

**Comment by joemather** [comment]
Distributions from ~6 hours ago are starting to come through now.

Maybe AppCenter has been resurrected.

**Comment by viktorVlakh** [comment]
The same issue. Can't upload iOS build via appcenter-cli and via appcenter web site. 
Errors:
1.  WebSite - "File upload error"
2. appcenter-cli - "failed with exception "undefined""

**Comment by dbhurewar** [comment]
+1

**Comment by AnastasiaKubova** [comment]
Hi there! We have an ongoing incident affecting uploading iOS builds. Please follow our status page for any updates https://status.appcenter.ms/

**Comment by viktorVlakh** [comment]
> 

Thank you

**Comment by dbhurewar** [comment]
> Hi there! We have an ongoing incident affecting uploading iOS builds. Please follow our status page for any updates https://status.appcenter.ms/

Thank You

**Comment by AnastasiaKubova** [comment]
The issue was resolved, so I'm to closing the issue. Thanks for using App Center.
