### ISSUE TITLE
Implement an AppCenter C++ SDK

### ISSUE THREAD

**Issue by JD31** [microsoft/appcenter#2347]
**Describe the solution you'd like**
I would like the AppCenter SDK to be available for C++ Windows applications (might be packaged as APPX)

**Describe alternatives you've considered**
No alternatives found so far.
We are developping a crossplatform application running on iOS and Windows in C++/Qt.
AppCenter SDK can be used on iOS through the AppDelegate in Objective-C, but no solutions found for Windows.

**Additional context**
NA

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for your feature request!
We already gave a similar request in our dotnet repository, so I'm going to close this issue. Let's track it [here](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1524).
