### ISSUE TITLE
Distribution issues - Failed to upload iOS binary to appcenter 16.12.21

### ISSUE THREAD

**Issue by didovych-anton** [microsoft/appcenter#2348]
Bitrise is failing to upload ipa files to appcenter, seems something from on Appcenter API.
we currently get an error like this:

Release created with ID: -1
2021/12/16 15:44:53 [DEBUG] GET https://api.appcenter.ms/v0.1/apps/iOS-Development/releases/-1
Failed to create new release, error: invalid status code: 400, url: https://api.appcenter.ms/v0.1/apps/Development/releases/-1, body: {0           false 0     []       [] [] [] false false {  } false  false : }
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | appcenter-deploy-ios@2 (exit code: 1) 

Can someone please investigate?

**Comment by Jrodseth** [comment]
https://status.appcenter.ms/incidents/7v2h87r8swb2

**Comment by AnastasiaKubova** [comment]
The issue has been resolved so I'm closing it. Thanks for using App Center.
