### ISSUE TITLE
Support for Appium WD.js

### ISSUE THREAD

**Issue by savaughn** [microsoft/appcenter#235]
**Describe the solution you'd like**
I would like the ability to use WD.js for automated testing react native apps.

**Additional context**
We currently use the node webdriver library, 'wd', to write our automated testing running on browserstack, but we would like to switch over to app center testing for DevOps build pipeline integration.

[https://github.com/admc/wd](https://github.com/admc/wd)

**Comment by Oddj0b** [comment]
I'm the program manager responsible for App Center Test and I'm working on a new idea which will support more frameworks in Test, allow unit testing, and browser testing. I would like to talk to you about it and understand your needs better.

Below is a link where you can sign-up for a 30-minute call with me. The agenda will be about the value of testing for you and your organization, and my new idea to allow more frameworks and testing styles in App Center Test.

Link to choose https://calendly.com/vigimm/appcenter-test

**Comment by savaughn** [comment]
Thank you for reaching out to me. I have forwarded this to my manager, and we will assemble a few other developers also involved in our automated testing to include on the call.

**Comment by JofArnold** [comment]
Still required,
