### ISSUE TITLE
Will existing Apache Cordova app continue to work after Cordova support is retired.

### ISSUE THREAD

**Issue by Distinctlyminty** [microsoft/appcenter#2352]
Firstly, I was advised to raise this issue here by App Centre support - Doesn't seem the right place but I'm fresh out of options!

I'm working with a global financial organisation with 17 applications deployed across 20+ different countries.  
All of these apps are written in Apache Cordova.

Cordova support in AppCentre is due to be retired in April 2022.

We only use app centre for distribution and are not using the AppCentre SDK.

So the question is this: Will we be able to continue pushing Cordova builds to app centre and distributing them to stores after April 2022?

For context, this is the message I received from support:

"Thank you for contacting App Center Support. Applications that are already created in Apache Cordova will continue to work! But we cannot confirm yet if this is true or not, so It's better if you can ask this directly to the development team in GitHub since they are the ones that can give you a correct answer.
Here is the link [Click here]
They might help you out if you open an issue in GitHub and ask about it to the development team since we didn't take this decision and they are the ones that could give you a correct answer!"

**Comment by akamenev** [comment]
@Distinctlyminty, thanks for your feature request! Could you please clarify, do you use the Codepush functionality or do you upload new versions' APKs to distribute to stores?

**Comment by Distinctlyminty** [comment]
Yes we push code from devops directly to app centre and then distribute from there to browser stack the App Store and Google play

**Comment by akamenev** [comment]
We don't have any plans to change the Distribution side of things, so if you do not use any Cordova-specific SDKs/plugins, your workflow should be okay.

**Comment by rayelward** [comment]
Hello @akamenev, 

What about the codepush functionality? What happens there. I was also pointed over here by app center support. 

For a little background we are a small company. We create an application that is templated out and whitelisted in over 50+ listings in both Apple's app store and Google's play store. Code push allows us to push up one packaged Cordova bundle that gets distributed to all of the applications without having to go through 100+ store reviews every time we need to fix a simple bug.

Prior to codepush we used https://github.com/nordnet/cordova-hot-code-push, which suited our needs but was a lot buggier and lost support once cordova was moved to WKWebView on iOS.

Are there alternatives you can point us to?

Thanks,

Ray.
