### ISSUE TITLE
[Question] Analytics.TrackEvent and Crashes.TrackError in a Task

### ISSUE THREAD

**Issue by AlleSchonWeg** [microsoft/appcenter#2356]
Hi,

should i run the above commands in a task to not block the UI? Like this:
```C#
	internal async Task TrackEventAsync(string eventName) {
			await Task.Run(() => {
				Analytics.TrackEvent(eventName);
			});
		}
```
I don't know how the commands work and if the commands thread safe. 
Thank you

**Comment by DmitriyKirakosyan** [comment]
Hi @AlleSchonWeg , thank you for reaching out to us!
All App Center commands are thread safe, so calling  `Analytics.TrackEvent` on the main thread is totally fine. It performs async operations inside and it will not block the UI.
