### ISSUE TITLE
Fix "fastlane-plugin-appcenter" to support Ruby 3.0

### ISSUE THREAD

**Issue by rewgoes** [microsoft/appcenter#2357]
**Describe the solution you'd like**
Please, take a look at the following issues and PRs on the fastlane-plugin-appcenter: 
- https://github.com/microsoft/fastlane-plugin-appcenter/issues/283
- https://github.com/microsoft/fastlane-plugin-appcenter/issues/279
- https://github.com/microsoft/fastlane-plugin-appcenter/pull/287

**Describe alternatives you've considered**
The only alternative to make fastlane-plugin-appcenter it to work with Ruby 2.x

**Additional context**
fastlane-plugin-appcenter uses methods that were marked as deprecated on Ruby 2.x and removed on Ruby 3.

PS: I'm opening this issue here because I was instructed to do that through the email that I've received

**Comment by konstantin-bobkov** [comment]
Hello, @rewgoes! We have released fastlane-plugin-appcenter 2.0.0. Please try it!

**Comment by DmitriyKirakosyan** [comment]
Closing this issue, but feel free to reopen if you have additional questions.
