### ISSUE TITLE
Build not showing branches and asking to reconnect

### ISSUE THREAD

**Issue by madhanagopal78** [microsoft/appcenter#2358]
We are having application named "Corin Android". When we point to Build it is not showing the branches and it is saying Azure DevOps token is no longer valid and asking us to reconnect. But after reconnect also situation is same. If we try to Disconnect and Connect, we will be loosing all build configurations. Unfortunately we have lost our Keystore file which used to Build and Distribute and it is acting as new app. 

Please help us to recover the build configuration back to release the app as upgradable version

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
You can open a [support ticket](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) on the App Center portal with this question.
