### ISSUE TITLE
Split Android apk/aab building 

### ISSUE THREAD

**Issue by clyneshi** [microsoft/appcenter#2359]
Is there any chance to support building the aab file only? currently aab can only be built in addition to apk, which potentially doubles the build time hitting the time limit.
![image](https://user-images.githubusercontent.com/47553868/148007075-57684515-789c-4ece-9b68-02b87c04e9b1.png)

**Comment by pavshr** [comment]
+1, this is a very desired feature

**Comment by prijupaul** [comment]
+1 . It would be wonderful if AppCentre can support aab file distribution.

**Comment by chenop** [comment]
@prijupaul Not sure it answering your need but you can download the aab file from appCenter.
Build --> click the relevant branch --> click the build --> Download --> Download Bundle

**Comment by Noitham** [comment]
Any solution here? Still an issue
