### ISSUE TITLE
Show user who ran the build

### ISSUE THREAD

**Issue by daniel-leal** [microsoft/appcenter#236]
**Describe the solution you'd like**
Shows user who ran the build.

**Describe alternatives you've considered**
When builds finished, shows the user who executed the build and distribuited to the store.

**Additional context**
In my institution, we have outsourced the service and we need to know who performed the build. In cases of failures that user needs to be notified.

**Comment by nrajpurkar** [comment]
Thanks for this issue @daniel-leal. Similar to #154, this sort of history is valuable for the build process for non-automated actions.
