### ISSUE TITLE
Add xamarin ios 15.4 plz

### ISSUE THREAD

**Issue by softlion** [microsoft/appcenter#2361]
**Describe the solution you'd like**
Add xamarin ios sdk 15.4

**Describe alternatives you've considered**
With 15.2 the build fails. Locally i have 15.4 stable on VS mac 2019.

**Additional context**
I'm experiencing build error on iOS on Appcenter:
```
MTOUCH : error MT2101: Can't resolve the reference 'System.Void ObjCRuntime.DisposableObject::Dispose()', referenced from the method 'System.Void A.B::Parse(System.Xml.XmlReader,System.Threading.CancellationToken)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. [/Users/runner/work/1/s/mobile/Watchium.iOS/Watchium.iOS.csproj]
```

**Comment by joemather** [comment]
Along with Xamarin.iOS 15.4, we need support for Xcode 13.2.1.

**Comment by joemather** [comment]
Xcode 13.2.1 and Xamarin.iOS 15.4 are now available.  This ticket should be closed.

**Comment by Balu2** [comment]
I had the same error with Xcode 13.2.1 and Xamarin.iOS 15.4 and the latest nuget package of Xamarin.Forms 5.0.0.2401. I had to downgrade Xamarin Forms package to 5.0.0.2337 to get rid of the error
