### ISSUE TITLE
Add App Version to the Error object

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/appcenter#2362]
**Describe the solution you'd like**
It would be super useful to have the App Version to the Error object. On the website, the App Version is everywhere, it is as important as the user email.

**Comment by Panda-Sharp** [comment]
I'd love this too!

**Comment by ArchieCoder** [comment]
Don't kill it! This should be super easy to do since the website shows it.

**Comment by Panda-Sharp** [comment]
Ping
