### ISSUE TITLE
Request: Allow Xamarin.UITest to have a App.config and support System.ConfigurationManagner

### ISSUE THREAD

**Issue by Moshex** [microsoft/appcenter#2373]
After working with the app-center support team it was brought to my attention that System.ConfigurationManagner is not supported when running tests in the app-center device cloud. This has made it an issue to have an App.config file for my automation project that would be nice to have to set certain configurations via the config file instead of using hardcoded strings. 

Here is an example of code that does work just fine locally but not in app-center:

```
        /// <summary>
        /// Get and set for Android Bundle Id
        /// </summary>
        public string AndroidBundleID
        {
            get
            {
                _androidBundleId = ConfigurationManager.AppSettings["AndroidBundleId"].Trim();
                if (!string.IsNullOrWhiteSpace(_androidBundleId))
                    return _androidBundleId;
                else
                    throw new ArgumentNullException("\t\tMissing Android Bundle Id info.");
            }
            set
            {
                _androidBundleId = value;
            }
        }
```

I hope to see this supported in the feature, thank you, app-center team!

**Comment by konstantin-bobkov** [comment]
Hello, @Moshex! Thank you for the feature request. Just want to confirm some points.

If you desire to create a config file for MyTest.dll you should name it accordingly: MyTest.dll.config. Also, to make that file accessible in App Center Test, you should provide it in the CLI command with **--include** option.

**Example**
ProjectName: ConfigurationTests

**Tests.cs**

***
using ConfigurationManager = System.Configuration.ConfigurationManager;

namespace ConfigurationTests
{
    [TestFixture]
    public class Tests
    {
        AndroidApp app;

        [SetUp]
        public void BeforeEachTest()
        {
            app = ConfigureApp
                .Android
                .ApkFile ("/path/to/apk")
                .StartApp();
        }

        [Test]
        public void DisplaySettings()
        {

            TestSettings settings = GetSettingsFromXML();    // From XML with System.Configuration.* -> Works fine with --include

            Console.WriteLine(settings.BrandName);
            Console.WriteLine(settings.BrandGuid);
            Console.WriteLine(settings.TestUsername);
            Console.WriteLine(settings.TestPassword);
            Console.WriteLine(settings.ApiKey);
            Console.WriteLine(settings.ApiSecret);
            Console.WriteLine(settings.ServerName);

            Assert.AreEqual(settings.BrandName, "NameOfTheBrand");
            Assert.AreEqual(settings.BrandGuid, "11111-2222-3333-4444");
            Assert.AreEqual(settings.TestUsername, "my_email@outlook.com");
            Assert.AreEqual(settings.TestPassword, "12345");
            Assert.AreEqual(settings.ApiKey, "221151672");
            Assert.AreEqual(settings.ApiSecret, "a12312lkjh4khj");
            Assert.AreEqual(settings.ServerName, "https://server.name.com");

            app.Screenshot("Settings were set");
        }
    }

    public class TestSettings
    {
        public string BrandName { get; set; }

        public string BrandGuid { get; set; }

        public string TestUsername { get; set; }

        public string TestPassword { get; set; }

        public string ApiKey { get; set; }

        public string ApiSecret { get; set; }

        public string ServerName { get; set; }
    }
}

**ConfigurationTests.dll.config**
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <appSettings>
        <add key="BrandName" value="NameOfTheBrand" />
        <add key="BrandGuid" value="11111-2222-3333-4444" />
        <add key="TestUsername" value="my_email@outlook.com" />
        <add key="TestPassword" value="12345" />
        <add key="ApiKey" value="221151672" />
        <add key="ApiSecret" value="a12312lkjh4khj" />
        <add key="ServerName" value="https://server.name.com" />
    </appSettings>
</configuration>

Also, please find useful info here: https://stackoverflow.com/questions/5190539/equivalent-to-app-config-for-a-library-dll/5191101

**Comment by Moshex** [comment]
@konstantin-bobkov I hear what you are saying by making the config file a .dll but how does that change the fact that System.Configuration.ConfigurationManager as a line of code does not work in app center? I could use the" --include option."  for just a .config file however it still does not make System.Configuration.ConfigurationManager work, which your code example posted also uses the same line of code.

**Comment by konstantin-bobkov** [comment]
@Moshex, sorry for the long response. I tested that code in App Center Test Cloud and it works. Could you provide more details, please? Because from my side I can't reproduce the issue you are facing.

**Comment by Moshex** [comment]
2 things on this,
1. Can a file with just the name "App.config" work in app-center
2. In the config file, are you able to store the application's bundle id you wish to point the automation code to a project you would like to execute your automation code on?

**Comment by konstantin-bobkov** [comment]
@Moshex,

1. App.config is not used for .dll files by ConfigurationManager. Please, find that [conversation](https://stackoverflow.com/questions/5190539/equivalent-to-app-config-for-a-library-dll). If you intend to use App.config or another file you can read settings without using ConfigurationManager. E.g. for me it's convenient to use .json file and read all necessary values from it using newtonsoft library.

Or you use App.config file for your **app**, not **test .dll**?

2. You can provide and automate only one app in a specific test run. Xamarin.UITest will replace your local settings, for example path to application or app id, with parameters of application file in the CLI command. Thereby, you are able to automate only app provided in AppCenter CLI argument.
