### ISSUE TITLE
Git Shallow Clone

### ISSUE THREAD

**Issue by aparedes** [microsoft/appcenter#2378]
**Describe the solution you'd like**
Having the option on the build config on if the cloning should be shallow and defining the depth
Doing a shallow clone would reduce bandwidth and build times as there is not always the need of having the whole history when only building one branch at the last commit.
In our case a shallow clone would go from 2.5gb to 750mb that is quite considerable.
Also the unpacking of git would be faster as it means less to unpack.

**Describe alternatives you've considered**
That the default be a shallow clone

**Comment by ioiooi** [comment]
+1

Also it kinda makes sense because App Center Builds are limited in their config/functionality (which is ok).
They're _based_ on branches and on that branch it just takes the _latest_ commit anyway.

So having the default behaviour be a single branch, shallow clone would be nice.

**Comment by aparedes** [comment]
This still an issue

**Comment by aparedes** [comment]
This is still a in issue

**Comment by aparedes** [comment]
This is an issue

**Comment by aparedes** [comment]
We have moved away from appcenter because of this issue.
