### ISSUE TITLE
Multiple Appium versions on the App Center test cloud

### ISSUE THREAD

**Issue by LiorW1** [microsoft/appcenter#2380]
Hi
I think having multiple Appium versions on the App Center test cloud with the ability to switch between them when starting your test run can be very useful.
There is times that specific appium version doesn’t work well with android/ios os versions so if you can add the ability to let the user decide which appium version to use can help us in such.

**Comment by LiorW1** [comment]
Anyone ?

**Comment by aleksandr-dorofeev** [comment]
Hello @LiorW1, thank you for the feature request. 
Unfortunately, we do not have ETA for this. 
We have a [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#app-center-roadmap-2022) where you can see the team's priorities for the year.
