### ISSUE TITLE
`AppCenter.trackError()` should throw, when the `exception` argument is `null`.

### ISSUE THREAD

**Issue by Bombo** [microsoft/appcenter#2382]
We noticed a bunch of missing events in AppCenter with our Android solution. Turns out this was caused by the AppCenter backend responding with a 400 NoValidLogsFoundInLogContainer error and the message indicated that "'exception' cannot be null".

The documentation should clearly indicate, that you are not supposed to call `AppCenter.trackError` with a `null` exception argument. Additionally it would be great, if either the method would be annotated accordingly, or itself throw a `NullPointerException`, to increase the visibility of the misuse of the API.

**Comment by DmitriyKirakosyan** [comment]
Hi @Bombo , thank you for bringing this issue to our attention!
I marked it as a bug.
We will add an error log from appcenter sdk, instead of trying sending a request with exception being null.

Could you also clarify which platform do you experience this issue on?

**Comment by Bombo** [comment]
Of course, and thanks.

This is on Android, and we're currently running version 4.4.1 of the SDK.
