### ISSUE TITLE
Add ability for organization admins to delete user test devices

### ISSUE THREAD

**Issue by jtoce** [microsoft/appcenter#2385]
**Background**
Currently only a user may delete their *own* test devices. To remove the device,

- You could delete the device by call this API: [https://openapi.appcenter.ms/#/distribute/devices_removeUserDevice](https://openapi.appcenter.ms/#/distribute/devices_removeUserDevice) with the device's UDID.
- The device owners can delete the device on their side: Account Settings->My devices->Click the device which need to be deleted->click on the 3 dots to delete

There is no way for an organization to remove user test devices.

**Describe the solution you'd like**
Add ability for organization admins to delete user test devices:

- Via the API with a call like: DELETE /v0.1/users/{user_id}/devices/{device_id}
- Through the UI: https://appcenter.ms/orgs/{org_name}/apps/{app_name}/distribute/distribution-groups/{group_name}/devices and Click the device which need to be deleted->click on the 3 dots to delete

NOTE: the user would have to be authenticated as an organization admin

**Describe alternatives you've considered**
We considered asking all of our users to remove their old devices, but this is impractical because:

1. We're a large enterprise organization and there are too many users
2. There is no enforcement mechanism, so if a user doesn't complete the action we have no means to make them comply

**Additional context**
At the end of the year, we disable and then remove any old test devices from our Apple developer account in order to stay below their allowed device limits. Often testers in our distribution groups lose or upgrade their old devices and get new ones. However, even after we remove the devices from our Apple developer account and associated profiles, they still show up in MS App Center as un-provisioned devices.

So the problem there is that if users don't remove their old devices once a year, then after the Apple Developer account refresh- even if the devices are removed from Apple, they remain in App Center. The old devices appear as unprovisioned.

And it's problematic for us, because we can no longer use the functionality to automatically register devices. If we were to do that, App Center would attempt to re-register the deleted devices.

Considering that our account is corporate and therefore all users are managed, we should have the ability to remove test devices.

**Comment by victorBaro** [comment]
Are there any updates here? Any way for admins to manage devices?
