### ISSUE TITLE
Support for XCode 13 Swift UI projects (no Info.plist by default)

### ISSUE THREAD

**Issue by brendanmckenzie** [microsoft/appcenter#2386]
**Describe the solution you'd like**

XCode 13 Swift UI projects don't use Info.plist files by default.  This causes issues with the "Automatically increment build number" feature, resulting in the following error.

```
##[section]Starting: Set Bundle version
==============================================================================
Task : Command Line
Description : Run a command line with arguments
Version : 1.1.3
Author : Microsoft Corporation
Help : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
(node:2458) Warning: Use Cipheriv for counter mode of aes-256-ctr
[command]/usr/bin/find . -name *Info.plist -exec /usr/libexec/PlistBuddy -c Set :CFBundleVersion 8 {} ;
Set: Entry, ":CFBundleVersion", Does Not Exist
##[section]Finishing: Set Bundle version
```

**Describe alternatives you've considered**

* Manually updating the build number
* fastlane

**Additional context**

It appears as though the build number is stored in the `CURRENT_PROJECT_VERSION` property in the `project.pbxproj` file.

**Comment by pyanierothef** [comment]
XCode 13 generates its own Info.plist, so this task steps doesn't find a real plist file. 

In case it's useful for someone, I found a workaround. 

In Xcode, you can go to Build Settings -> Packaging -> Generate Info.plist file and set it to NO. Then you can add your own Info.plist file into the project. Just remember setting the path to "Info.plist File" in Build Settings too.
