### ISSUE TITLE
Package installation should use npm ci instead of npm install 

### ISSUE THREAD

**Issue by Subv** [microsoft/appcenter#2394]
This is a re-opening of #1260 as that one was closed by the bot. That issue contains more context.

**Describe the solution you'd like**
React Native builds should use `npm ci` or `yarn install --frozen-lockfile` to install packages instead of `npm install` / `yarn install`. 

Alternatively provide a way to configure this so that existing behavior can be kept.

The reason is that `npm install` checks `package.json` and installs **the latest compatible version** of the dependant packages, whereas `npm ci` installs **the exact package versions** listed in `package-lock.json`.
 
In other words, running `npm ci` will always result in the same set of packages being installed, but `npm install` may randomly upgrade packages, depending on the version specified.

**Describe alternatives you've considered**
Could add a pre-build script to delete the node_modules folder and run the install command again, but this would increase build times by a lot and we're already at 12-14 minutes per build.

**Additional context**
Build logs where `npm install` is run:
```
##[section]Starting: yarn/npm install
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3398) Warning: Use Cipheriv for counter mode of aes-256-ctr
[command]/bin/sh -c if [ -f yarn.lock ]; then { yarn install --network-timeout=600000 && yarn list --depth=0; } else npm install; fi
```

**Comment by jack828** [comment]
Anti stale bot bump - this has the potential to reduce our already painfully slow builds by quite a lot.

**Comment by Zakyyy** [comment]
anyupdates?

**Comment by SorenKruseHolm** [comment]
A way to configure this would be appreciated, since pre-scripts is executed after npm install :)

**Comment by jack828** [comment]
anti stale bot bump - we've abandoned appcenter now but other users may benefit from this if it ever gets done.

**Comment by hassaans** [comment]
We decided to use .yarnrc to fix this issue
https://classic.yarnpkg.com/lang/en/docs/yarnrc/#toc-cli-arguments

```
--install.frozen-lockfile true
```

**Comment by jack828** [comment]
Bumping for fun but an official comment would be nice thanks
