### ISSUE TITLE
Detect ANRs (+ breadcrumbs)

### ISSUE THREAD

**Issue by andres-decagames** [microsoft/appcenter#2396]
**Describe the solution you'd like**
It would be incredibly useful if AppCenter SDK detected and reported **ANRs** the same way it detects and reports crashes. Special mention to **Breadcrumbs** feature, which is great for us to have some kind of "steps to reproduce", and would be incredibly useful having those on ANR reports as well. 

**Describe alternatives you've considered**
We found other reporting tools like Instabug that claim to be able to detect ANRs, but we would like to avoid integrating yet another SDK that might (ironically) increase the ANR/crash rates.

Another alternative would be detecting the ANRs ourselves and sending an Error log through the AppCenter SDK. However, [Errors seem to be very limited](https://docs.microsoft.com/en-us/appcenter/diagnostics/limitations#handled-errors) and won't have associated **breadcrumbs**.

**Additional context**
ANR rate is very important for the Play Store ASO, but ANRs are very difficult to fix with the reports provided by Google. Having AppCenter SDK to detect and report them, with associated breadcrumbs, will help a lot to fix these ANRs.

**Comment by DmitriyKirakosyan** [comment]
Hi @andres-decagames , Thank you for reaching out to us!

What platforms are you using SDK for?
Actually we already have a similar feature request for Android SDK here: https://github.com/microsoft/appcenter/issues/1293.

**Comment by andres-decagames** [comment]
Hi @DmitriyKirakosyan. We use it on iOS and Android. 
I saw that other feature request you link, but it's stale :(

**Comment by DmitriyKirakosyan** [comment]
Agree, thank you for opening a new one.

Actually I don't think it is possible to catch ANR on iOS with in-process crash reporter, except of detecting memory warning and you can check it using API `Crashes.hasReceivedMemoryWarningInLastSession'.
As for Android, we have this feature on our board. I will update you once we implement it.

**Comment by andres-decagames** [comment]
@DmitriyKirakosyan Yes, I know ANRs aren't a thing on iOS. This feature request only makes sense for Android I guess. 
Thank you, will be looking forward to any updates on this 🙌

**Comment by normanhh3** [comment]
Would love this as well.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
