### ISSUE TITLE
Email invitations take an extended time to be delivered

### ISSUE THREAD

**Issue by jessejjohnson** [microsoft/appcenter#2398]
**Describe the solution you'd like**
Inviting new people (Collaborators) presents a message that an invitation was sent, however that's not the case. Most cases the email doesn't arrive for hour(s), if ever. This is an issue as it has new team members stuck awaiting for an invite code which nobody knows when/if will arrive.

Email invitations should be sent in near real-time.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
Screenshot below is very misleading as an invite was _not_ sent. Fifteen minutes later and the invite has yet to be received.
![Incorrect messaging](https://user-images.githubusercontent.com/1378172/158648823-9645fc46-1b93-4cb1-9b0c-94e09a0f1b7c.png)

**Comment by jsauve** [comment]
I'm seeing the same problem. Invited several people within the last hour, and no one has received the invite emails.

**Comment by jsauve** [comment]
@[jessejjohnson](https://github.com/jessejjohnson)
Looks like MSFT is aware and the issue is being tracked:
https://status.appcenter.ms/
