### ISSUE TITLE
[Feature] GitLab as bug tracker service

### ISSUE THREAD

**Issue by WebDucer** [microsoft/appcenter#24]
**What App Center service does this feature apply to?**
Services (Bug tracker)

**Describe the solution you'd like**
At this moment only GitHub, Jira and Azure DevOps are available as bug tracker. Hockey App allows more types.
For our transition form Hockey App to App Center it is required to have GitLab as bug tracker service included in App Center.

**Describe alternatives you've considered**
No alternatives

**Comment by amchew** [comment]
Hi @WebDucer! Thank you for reaching out and sharing this feature request as you transition to App Center. 

We're starting with those 3 bug trackers in App Center as we're currently working on the cutover experience and will be looking at other bug trackers in the future. We'll keep this issue open to gauge interest - if others have the same need, please add a +1 to this issue!

**Comment by WebDucer** [comment]
Hi @amchew are there any development on GitLab integration?

**Comment by daimlerrdusn** [comment]
Daimler is also interested in a integration of the bug tracker for gitlab. Will it be integrated?

**Comment by WebDucer** [comment]
@amchew Hello. Is this feature somewhere on the roadmap? The source control integration with GitLab is working. Only the issue tracker integration is missing now.

**Comment by rudyrichter** [comment]
My team would like gitlab issue tracker support on AppCenter as well.

**Comment by manishkungwani** [comment]
Hi,

We also would like to use Gitlab as the BugTracker connected with AppCenter.

Is there any plan for its implementation.

**Comment by rudyrichter** [comment]
This is still an active request and a point of pain for our continued use of AppCenter. don't you dare close this @msftbot!
