### ISSUE TITLE
Enable to set stage rollout before uploading the Google play 

### ISSUE THREAD

**Issue by BarFingerman** [microsoft/appcenter#240]
i will like request the ability to set the stage rollout percentage before the app gets submitted to review.

Rollout config in the Google play dashboard:
![image](https://user-images.githubusercontent.com/11498591/55162451-891bd380-5170-11e9-96c6-10173ffa8325.png)

**Comment by botatoes** [comment]
Thanks for the suggestion. We'll be looking into this in the upcoming weeks.

**Comment by zanechua** [comment]
Ping @Oddj0b any updates on when this feature will be made available?

**Comment by vitorreis** [comment]
+1 for this feature

**Comment by marcomoscatiello** [comment]
+1 for this feature
