### ISSUE TITLE
Retry build when: 2FA expired or "Release Notes should contain min 10 to max 4000"

### ISSUE THREAD

**Issue by gunnartorfis** [microsoft/appcenter#2407]
**Describe the solution you'd like**
Build failed due to commit message being too short.
`##[error]{"code":"bad_request","message":"Error: Failed to publish to store. Release Notes should contain min 10 to max 4000 characters but contain 6 characters."}`

Could you please detect this sooner, before the build starts so we don't have to wait for 30+ minutes to get this error. 

This also applies when 2FA is expired and reconnecting is required with App Store Connect. 

Ideally, if archive is successful, we should be able to retry submitting without rebuilding. 

**Describe alternatives you've considered**
An AppCenter pre-build script would be sufficient for the commit message part but not the 2FA with App Store Connect.

**Comment by billnbell** [comment]
make this optional.
