### ISSUE TITLE
Support for Xcode 13.3

### ISSUE THREAD

**Issue by mortenjust** [microsoft/appcenter#2408]
**Describe the solution you'd like**
Xcode 13.3 was released 14 days ago. Appcenter supports 13.2.1. By adding support for 13.3, AppCenter's users would benefit from 
- Important Java security patches
- Being able to compile with AC. It currently crashes, specifically for me on Swift packages. 

**Describe alternatives you've considered**
- I tried deleting resolved packages and compiling with 13.2.1, but could not. 
- I tried installing 13.2.1 in parallel, but the 13.3 project was not backwards compatible
- My only working workaround was to compile locally and upload to AC, which means I'll miss symbols and CI in general.

**Comment by tomcondon** [comment]
This is a must have. New Swift language features and all kinds of bug fixes come with most new Xcode releases. You cannot be in a position where your CI/CD system gets broken by a new IDE version for platforms you care about.

**Comment by joemather** [comment]
Current status of the Monterey / Xcode 13.3 environment is [here](https://github.com/actions/virtual-environments/issues/3649).

Right now, it's in private beta for GitHub Actions only.  No timeframe yet for Azure DevOps or App Center.

This situation is very similar to the [Big Sur fiasco last year](https://github.com/actions/virtual-environments/issues/2072).

It's disappointing that Microsoft has months to prepare for these major macOS/Xcode upgrades, yet fails to do so.

**Comment by mspasov** [comment]
There are issues with Xcode 13.2.1 (latest available in appcenter atm), that builds broken binary - crashes on iOS 12.x and below.

ref: https://developer.apple.com/forums/thread/696960

**Comment by ian-hubbard-alcolizer** [comment]
I am unable to install any builds from App Center on any device running iOS 15.3+ (Enterprise Distribution certificate) due to this, which is causing major issues for our Sales staff as their devices have just updated.

Based on the Apple supported SDK list: https://developer.apple.com/support/xcode/#minimum-requirements

**Comment by pedrolopessh** [comment]
Do you have any prediction on when XCode 13.3 will be available to App Center build options?

**Comment by pedrolopessh** [comment]
It would be great to have at least some feedback to know if you're working on this

**Comment by channeladam** [comment]
My iPhone test device was updated to iOS 15.4 (and can't be downgraded), which due to Apple's minimum requirements then forced me to upgrade from Xcode 13.2 to 13.3, and also forced me to upgrade from Big Sur 11.3 to Monterey 12.
And now Microsoft App Center doesn't support Xcode 13.3?  Unbelievable.
Why are we paying for App Center?

**Comment by Banley** [comment]
> My iPhone test device was updated to iOS 15.4 (and can't be downgraded), which due to Apple's minimum requirements then forced me to upgrade from Xcode 13.2 to 13.3, and also forced me to upgrade from Big Sur 11.3 to Monterey 12. And now Microsoft App Center doesn't support Xcode 13.3? Unbelievable. Why are we paying for App Center? (and no feedback here from Microsoft)

Same exact issue here, just waiting for another update. We don't pay for app center, so I was humbly waiting my turn like a 2nd rate citizen... But I can't imagine the frustration that paying people are having over this. I see they updated issue 2319, maybe they'll pop in over here if we comment/react enough.

**Comment by channeladam** [comment]
FYI, here is a statement received directly from the AppCenter support team.

"I am sorry for the inconvenience. I understand your feeling. For paid service, there should be at least an ETA for our customers. At present, Xcode 13.3 support in App Center is blocked by the required Build agent. It absolutely relies on the working progress of Product team. We have no idea on it. I am sorry about that again."

**Comment by smakus** [comment]
We pay a ton of money to Azure.  Please make this issue a priority.

**Comment by andyboyd** [comment]
Adding another vote to prioritising this. The format of Swift Package Manager's Package.resolved file has changed in Xcode 13.3, so adding packages now results in a file format that Xcode 13.2 cannot understand, which breaks App Center builds.

2 months for the latest version to become available is completely unacceptable for a paid service. This is effectively getting close to 20% downtime for certain users now.

**Comment by vforvasile** [comment]
any ETA on this?

**Comment by tdekker** [comment]
I feel Microsoft is not paying attention to this issue on GitHub. My suggestion is to submit a support request through the App Center portal (using the **?** icon on the top right), especially those that have a paid account.
<img width="613" alt="AppCenterSupportRequest" src="https://user-images.githubusercontent.com/9843946/168532531-39bbf1b6-955b-4356-bece-b9511f9b892d.png">

**Comment by dhayaljaswantapollo** [comment]
Hello, When we can see Xcode 13.3 version, any tentative date?

**Comment by pasha-o** [comment]
Hello - is there an update on including Xcode 13.3 ?

**Comment by tomcondon** [comment]
Hey, look, its Xcode 13.4 as of today. You guys need to keep up better with the latest toolsets.

**Comment by joemather** [comment]
Sent this to App Center support:

> When will Xcode 13.3 (or higher) be supported?  Xcode 13.4 has been released by Apple, which means App Center is now *three* versions of Xcode behind (13.3, 13.3.1, and 13.4).

Received this reply:

> Currently Xcode 13.3 is blocked due to macOS 12.0+ requirement. The Azure DevOps engineering team is working on this but no ETA at the moment. I have requested an update from engineering for an ETA and will follow up soon.

**Comment by joemather** [comment]
**ETA for Xcode 13.3 is next week.**

Sent this follow-up to App Center support:

> According to this thread, macOS 12 is available for Azure DevOps:
>
> https://github.com/actions/virtual-environments/issues/3649#issuecomment-1125184824
>
> So what’s holding things up?

Received this reply:

>  I received an update from engineering. macOS 12 has indeed been added to App Center , ETA for Xcode 13.3 is next week.

**Comment by pedrolopessh** [comment]
I wonder if xcode 13.4 will also be added at the same time, I'm guessing that since the solve the macOS 12.0+  issue, it would mean that they won't have the same issues that they had on xcode 13.3

**Comment by noelstieglitz** [comment]
We started having this issue today after upgrading to 13.4. 🤞 that 13.4 will be supported.

**Comment by dayanruben** [comment]
macOS 12 is already available for AppCenter's build agents and now we can use Xcode 13.3.1 in build configurations.

`
...
##[group]Virtual Environment
Environment: macos-12
Version: 20220516.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-12/20220516.1/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-12%2F20220516.1
...
`

**Comment by ciberbob-007** [comment]
> macOS 12 is already available for AppCenter's build agents and now we can use Xcode 13.3.1 in build configurations.
> 
> ```
> ...
> ##[group]Virtual Environment
> Environment: macos-12
> Version: 20220516.1
> Included Software: https://github.com/actions/virtual-environments/blob/macOS-12/20220516.1/images/macos/macos-12-Readme.md
> Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-12%2F20220516.1
> ...
> ```

Just test it, Working fine !!! Thanks

**Comment by andyboyd** [comment]
Great, we've got 13.3.1 now, but 13.4 has been out for a while now, so that needs added as well! Should be a quicker one to add though, since it doesn't require an OS update

**Comment by joemather** [comment]
**No ETA for Xamarin.iOS with Xcode 13.3.1.**

Sent this to App Center support:

> I don’t see Xcode 13.3.1 as an option for Xamarin.iOS apps. Is a Xamarin.iOS update coming soon?

Received this reply:

> yes for Xamarin there will be an update coming, no eta yet but I will follow up

**Comment by oliver-ep** [comment]
I have experienced the same problem with the latest iOS that everyone is on now. It was released last week, I believe; and now nothing the team builds and distribute from AppCenter can be tested or deployed.

On AppCenter we need XCode 13.4 supported and it's not available. (I'm building Xamarin.Forms so Xamarin.iOS build really) and the support team message was along the lines of:

"Our team was already working on to add support for xcode 13.4, currently there is no ETA, I will let you know once avalible."

It's not like Apple suddenly dropped this update, was it?

Having no ETA to me sounds like there was and currently is no plans to support this.

I find this whole situation disappointing, and as a business it's not safe to rely on this level of uncertainty. I have recommended my team to stop using AppCenter and we're looking for alternatives after this experience.

**Comment by channeladam** [comment]
We moved to Bitrise for that same reason.

**Comment by fredrikburman** [comment]
It is possible to use Xcode 13.3 and 13.4 in an Azure pipeline.

This is the relevant parts from one of my pipelines.

```yml

trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
      - clientstaging*

pr: none

pool:
  vmImage: macos-12

steps:
  - script: |
       echo "Selecting xcode 13.4.1"
       sudo xcode-select -s /Applications/Xcode_13.4.1.app
    displayName: Selecting xcode version
    
.......    
`

And these are the different versions of Xcode you can use for the macos-12 image.

```bash
2022-07-06T18:21:02.5286530Z ls -la /Applications/
2022-07-06T18:21:02.5389400Z ========================== Starting Command Output ===========================
2022-07-06T18:21:02.6019730Z [command]/bin/bash --noprofile --norc /Users/runner/work/_temp/57f74261-4253-4cb8-b05a-2783e3ec149a.sh
2022-07-06T18:21:02.6045250Z total 0
2022-07-06T18:21:02.6096660Z drwxrwxr-x  24 root    admin  768 Jun 27 21:06 .
2022-07-06T18:21:02.6144370Z drwxr-xr-x  20 root    wheel  640 May  9 21:30 ..
2022-07-06T18:21:02.6175330Z -rw-r--r--   1 root    wheel    0 May  9 21:30 .localized
2022-07-06T18:21:02.6197710Z drwxr-xr-x   3 runner  staff   96 Jun  8 19:36 Firefox.app
2022-07-06T18:21:02.6224820Z drwxr-xr-x@  3 runner  staff   96 Jun 15 04:47 Google Chrome.app
2022-07-06T18:21:02.6263750Z drwxr-xr-x   3 runner  staff   96 May 25 13:20 Julia-1.7.app
2022-07-06T18:21:02.6341030Z drwxr-xr-x   3 runner  admin   96 Jun 27 21:05 Microsoft Edge.app
2022-07-06T18:21:02.6440420Z drwxr-xr-x   3 root    wheel   96 Jun 27 18:24 PowerShell.app
2022-07-06T18:21:02.6520840Z drwxr-xr-x@ 11 root    wheel  352 Jun 27 18:26 Python 2.7
2022-07-06T18:21:02.6560420Z drwxr-xr-x@  3 root    wheel   96 May  9 21:30 Safari.app
2022-07-06T18:21:02.6596070Z drwxr-xr-x   3 root    wheel   96 May  9 21:30 Utilities
2022-07-06T18:21:02.6622800Z drwxr-xr-x   3 root    admin   96 Jun 27 18:47 VirtualBox.app
2022-07-06T18:21:02.6671150Z drwxr-xr-x   3 runner  admin   96 Jun 15 17:41 Visual Studio 2019.app
2022-07-06T18:21:02.6701510Z drwxr-xr-x   3 runner  admin   96 Jun 15 16:44 Visual Studio.app
2022-07-06T18:21:02.6741250Z lrwxr-xr-x   1 runner  admin   30 Jun 27 20:22 Xcode.app -> /Applications/Xcode_13.3.1.app
2022-07-06T18:21:02.6773180Z lrwxr-xr-x   1 runner  admin   28 Jun 27 20:17 Xcode_13.1.0.app -> /Applications/Xcode_13.1.app
2022-07-06T18:21:02.6774140Z drwxr-xr-x   3 runner  wheel   96 Oct  6  2021 Xcode_13.1.app
2022-07-06T18:21:02.6827830Z drwxr-xr-x   3 runner  wheel   96 Dec 14  2021 Xcode_13.2.1.app
2022-07-06T18:21:02.6867360Z lrwxr-xr-x   1 runner  admin   30 Jun 27 20:17 Xcode_13.2.app -> /Applications/Xcode_13.2.1.app
2022-07-06T18:21:02.6899790Z drwxr-xr-x   3 runner  wheel   96 Mar 31 03:50 Xcode_13.3.1.app
2022-07-06T18:21:02.6926870Z lrwxr-xr-x   1 runner  admin   30 Jun 27 20:17 Xcode_13.3.app -> /Applications/Xcode_13.3.1.app
2022-07-06T18:21:02.6957990Z lrwxr-xr-x   1 runner  admin   28 Jun 27 20:17 Xcode_13.4.0.app -> /Applications/Xcode_13.4.app
2022-07-06T18:21:02.6984390Z drwxr-xr-x   3 runner  wheel   96 May 18 04:10 Xcode_13.4.1.app
2022-07-06T18:21:02.7009110Z drwxr-xr-x   3 runner  wheel   96 Apr 30 05:27 Xcode_13.4.app
```

**Comment by joemather** [comment]
This issue should be closed.  

Xcode 13.4.1 and Xamarin.iOS 15.10 are available in App Center:

<img width="530" alt="XCode 13 4 1" src="https://user-images.githubusercontent.com/13467576/177655807-8eb73fa5-4b7c-420f-9b33-6ec4046c9de9.png">
