### ISSUE TITLE
Please have XCode 13.3 option available for the React Native IOS build process

### ISSUE THREAD

**Issue by vmarcel** [microsoft/appcenter#2409]
**Describe the solution you'd like**
An option to select version 13.3 for XCode for React Native build configuration

**Describe alternatives you've considered**
I don't know any other alternatives unless I downgrade my version, but that will conflict with the other developer setup

**Additional context**
It is possible that the builds in App Center are failing for our Org because of that configuration difference

**Comment by DmitriyKirakosyan** [comment]
Closing as duplicate of https://github.com/microsoft/appcenter/issues/2408.
