### ISSUE TITLE
Please support Xcode 13.3.1 for builds.

### ISSUE THREAD

**Issue by tomcondon** [microsoft/appcenter#2414]
**Describe the solution you'd like**
support Xcode 13.3.1 for builds.

**Describe alternatives you've considered**
Fall back to using xCode 13.2.1

**Additional context**
Apparently Apple change the format of their Package.resolved file which is generated by Xcode for the Swift Package manager. Using Xcode 13.2.1 does not recognize this format therefore you cannot build on AppCenter if you have been developing with 13.3+

Output:

Resolve Package Graph
xcodebuild: error: Could not resolve package dependencies:
  Package.resolved file is corrupted or malformed; fix or delete the file to continue: unsupported schema version 2

##[error]Error: /usr/bin/xcodebuild failed with return code: 74

**Comment by bhagirathgudi** [comment]
Moreover XCODE version 13.2.1 has the log4j vulnerability. We were also looking into using XCODE version 13.3.

**Comment by tomcondon** [comment]
Here is a discussion of the security vulnerability: https://developer.apple.com/forums/thread/696785

**Comment by DmitriyKirakosyan** [comment]
This is a duplicate of #2408, please follow the progress in the original issue.

**Comment by hexadecy** [comment]
@tomcondon, you can also ignore "Package.resolved". It's used by SPM as a lock file.
