### ISSUE TITLE
Rebuild the Xamarin.TestCloud nuget for .NET 6

### ISSUE THREAD

**Issue by JohnHDev** [microsoft/appcenter#2416]
**Describe the solution you'd like**
We need a new build of the Xamarin.TestCloud nuget for .NET 6. This is to allow .NET Maui projects to use UI tests on iOS.
.NET Maui is now in RC and is a supported product byMicrosoft, so dependencies like this need to be updated.

**Describe alternatives you've considered**
There isn't an alternative other than dropping Xamarin UITest and AppCenter altogether.

**Comment by AlexeyBudynkov** [comment]
@JohnHDev, hello. You mean Xamarin.TestCloud.Agent nuget package or Xamarin.UITest nuget package?

**Comment by AlexeyBudynkov** [comment]
@JohnHDev Okay, thank you your request. We created a task for that.

**Comment by AlexeyBudynkov** [comment]
> Excellent thank you! Any idea when this might be available?

It's in our plans, but we don't have ETA for now.

**Comment by JohnHDev** [comment]
Thanks Alexey.
If there is anything you can do to push this forward, that would be appreciated. Migrating to .NET Maui is a high priority and we need to get all our dependencies updated, including this one. We have extensive UI testing that will need to support .NET 6, and all we need to do that is this updated nuget. I would do it myself if it were open source.

**Comment by AlexeyBudynkov** [comment]
> Thanks Alexey. If there is anything you can do to push this forward, that would be appreciated. Migrating to .NET Maui is a high priority and we need to get all our dependencies updated, including this one. We have extensive UI testing that will need to support .NET 6, and all we need to do that is this updated nuget. I would do it myself if it were open source.

We will reply to you when we'll finish the estimation

**Comment by kdharani** [comment]
Our organization has a plan to migrate to MAUI soon. I upvote this feature.

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon any news on this pls?

**Comment by Slm0nB** [comment]
We would love this feature :-)

**Comment by JohnHDev** [comment]
Any update on this? .NET MAUI is now GA and we still can't run UI tests on iOS.
'Soon' obviously means different things to different people...

**Comment by dgerding** [comment]
Just weighing in with my strong, enthusiastic hope for this feature to arrive soon :-) thanks

**Comment by johnathan-s** [comment]
A client is deciding on a tech stack.  
I **cannot** advise to the client to go with .net MAUI until there is a clear and clean automated test solution to testing .net MAUI.
Please put this at the top of the priority list.
Thanks

**Comment by dgerding** [comment]
Yes, please make this a top priority. We can't move to Maui without a replacement for automated ux testing.

**Comment by JohnHDev** [comment]
@AlexeyBudynkov it is now 3 months since we asked for this and we still can't create UI tests for iOS.
Would you advise dropping Xamarin UITest and AppCenter all together? We need better support than this.

If this isn't going to happen can you ask for it to be made open source pls, without seeing the source I suspect we might be able to do this ourselves in a day or 3.

**Comment by akamenev** [comment]
Hi @JohnHDev, thank you for your patience! Unfortunately, this feature takes more time to implement than we expected. It is currently in development and we will update everyone here once it is available.

**Comment by dgerding** [comment]
Hi @akamenev, we need some kind of eta, please. This year? Thanks

**Comment by dgerding** [comment]
Hi @akamenev, please provide an answer about Maui test support with some kind of real timeline or date estimations. thanks!

**Comment by mnxamdev** [comment]
Are we able to build .Net MAUI apps in App Center Build yet?

**Comment by AlexeyBudynkov** [comment]
@mnxamdev Hello. We're still working on it

**Comment by LarsNymand** [comment]
Upvote for .net maui support

**Comment by osieber** [comment]
Upvote for .net maui support

**Comment by JohnHDev** [comment]
And now .net 7 is in preview for release in November…
This was raised 5 months ago.

**Comment by johnathan-s** [comment]
Hello,

Some mention in the tubes that this is ongoing -> https://youtu.be/Bz1XLecJlXc?t=997

**Comment by evgenyvalavin** [comment]
.NET 7 is GA now. 
Still waiting for Xamarin.TestCloud.Agent to be updated

**Comment by bvbellomo** [comment]
Also waiting on this

**Comment by JohnHDev** [comment]
So, its 8 months since I reported this and we still can't run UI tests on .NET Maui iOS apps.
Other than 1 comment in a YouTube video from Gerald Versluis that 'something' was coming, we are no further forward.
@AlexeyBudynkov, @IlyaBausovAkvelon, @akamenev is there anything you can share on this? There are many of us that can't or just won't start migration to Maui without this.

**Comment by IlyaBausovAkvelon** [comment]
We are planning to release Xamarin.TestCloud.Agent package soon.

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon any progress on this?

If it helps, I tried adding Xamarin.TestCliud.Agent nuget to a .NET 6 and .NET 7 iOS project, the underlying error reported is:
Package Xamarin.TestCloud.Agent 0.23.1 is not compatible with net6.0-ios16.0 (.NETCoreApp,Version=v6.0). Package Xamarin.TestCloud.Agent 0.23.1 supports: xamarinios (Xamarin.iOS,Version=v0.0)

The nuget needs to be updated to support .NET 6 and .NET 7 iOS runtimes.

**Comment by pm90pl** [comment]
What is the status? Is it possible to use Xamarin.UITest with iOS MAUI?

**Comment by MikhailSuendukov** [comment]
@JohnHDev @pm90pl  We are still working on the release of Xamarin.TestCloud.Agent.

**Comment by TheresasAccount** [comment]
Are there any pre-release builds? Can we help test this?

**Comment by JohnHDev** [comment]
> Hello @TheresasAccount , we are still working on a fix, and will only be able to share an official release when done. Thank you!

It's good to know this is being worked on, it would be even better to have this resolved before this ticket is 1 year old. ;)

**Comment by krzbbaranowski** [comment]
Hey, I assume you have some high-level estimation for NuGet release. Could you please share this information with us? :)

My team is under the migration to .net 6 and this is a serious blocker for us.

**Comment by johnathan-s** [comment]
@jfversluis Did you hear anything from your end?  
When it is released, can you do an in-depth video on MAUI testing (as I suspect a lot of it will be updated/different)?
thanks

**Comment by IlyaBausovAkvelon** [comment]
@krzbbaranowski hello! No, please wait for an official release!

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon 
We have been waiting.
For 10 months.

Any idea of how much longer we need to wait would be helpful and not an unreasonable thing to ask for.

**Comment by IlyaBausovAkvelon** [comment]
@JohnHDev we are working on it. Please wait for release.

**Comment by anxkha** [comment]
I definitely agree that at least a rough timeline would be better than "please wait for a release"...

That being said, I noticed that there was a 4.1.0 release of Xamarin.UITest 14 days ago that claims to target net6.0 now as well as net462. I have not had a chance to try this out, yet, but I will be soon!

https://www.nuget.org/packages/Xamarin.UITest/

**Comment by krzbbaranowski** [comment]
Guys, I assume we will wait many months for an update (or never :)). So, my team probably will decide to use the other tool.
Question to everyone, do you know any suitable alternative to AppCenter and TestCloud?

**Comment by pm90pl** [comment]
BrowserStack - but that cloud supports only Appium

**Comment by bvbellomo** [comment]
I don't know of any alternatives to AppCenter for iOS beside Apple's store, but would be interested if anyone had one.

**Comment by akrol95** [comment]
Any update on this?

**Comment by vvechkanov** [comment]
@akrol95  W we are still working on that task. Unfortunately no ETA yet. Thank you for your patience.

**Comment by miszu** [comment]
+1 for that, we invested quite a lot of time in these UI Tests and now simply can't run them. Happy to beta test a package early :)

**Comment by evgenyvalavin** [comment]
any news?

**Comment by weitzhandler** [comment]
This one is a blocker

**Comment by krzbbaranowski** [comment]
My team is considering replacing TestCloud with local machines. I wonder how many teams will do the same.
We are almost done with the migration to .NET 7 so we can't wait for the new version of TestCloud indefinitely...

My biggest concern is the fact that MS team has no ETA.

**Comment by JohnHDev** [comment]
@krzbbaranowski what will you replace the test framework with? Ideally looking for a replacement for Xamarin.UITest in its entirety, but still be able to create UI tests with C#.

**Comment by johnathan-s** [comment]
To any who have ended up on this thread that have an alternative, please
post them here.

Thanks

**Comment by joshardt** [comment]
> To any who have ended up on this thread that have an alternative, please post them here. Thanks
> […](#)

Appium with BrowserStack in C# with NUnit. No backdoors though.

**Comment by e1T** [comment]
Our team has started the transition to Appium with C# and xUnit. We've added up an interface to abstract platform-specific drivers so we can use a single code base for the UI tests. Benefit of Appium is that it works with Xamarin Forms app and our future MAUI version as well.
We're also planning on implementing parallel testing on multiple devices locally.

**Comment by JohnHDev** [comment]
@e1T How does Appium deal with automation on iOS? Xamarin UITest requires the iOS app is built with the Xamarin.TestCloud nuget installed with an initialiser for the library, is there not the same requirement with Appium?

Looks like we will most likely go the same route as you.

**Comment by e1T** [comment]
The iOS (or Android) app project doesn't need to include references to Appium itself. With Appium you can automate any application. For iOS it uses a Web Driver Agent installed on the device which runs the commands sent from the Appium server. 
The architecture looks like this:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/23559848/230038254-54e4cf17-7a33-48d6-841f-5f9dc024cd00.png">

**Comment by anxkha** [comment]
I was able to successfully get my application to have a basic test run against it today with Xamarin.UITest 4.1.3 in an NUnit 3 project targeting .NET 7. I'm not sure where the disconnect is between the MS dev team working on this and their inability to post a meaningful update in this issue, but I suspect this has been fixed on .NET 6/7 for a little while now. I don't have any super complicated test cases to try out with this at this time, but I'm curious if others can try Xamarin.UITest 4.1.3 and let me/us all know if your more advanced tests just work!

**Comment by JohnHDev** [comment]
@anxkha I presume you are referring to a UI test with an Android app, the issue here is that to run a UI test on iOS we need to install the TestCloud nuget, which we can't yet without it being rebuilt. Let us know though! :)

**Comment by anxkha** [comment]
@JohnHDev Ah yes, that's a fair point my bad on not fully understanding some of the concerns here (there's confusion earlier on in the thread about which package specifically). Our app is pretty specialized and only on Android so I was only concerned about that. That's disappointing that TestCloud hasn't been updated yet :(

**Comment by JohnHDev** [comment]
@vvechkanov any news? we are about to invest resources into moving from Xamarin UITest to Appium. We need to do this to be able to move to .NET Maui before Xamarin is deprecated.

If it is no longer supported just say so. At the moment Microsoft is just wasting our time.

**Comment by amrara** [comment]
Any news? 
Running Android or iOS build on .NET 6, with XamarinUITest 4.1.3 on App Center still not possible for me.
WARNING: Testing tests built for .NET 6 and above is not yet supported on Test Cloud.
Any workaround please?

**Comment by IlyaBausovAkvelon** [comment]
Hi All!
Thanks for your patience. The new TestCloudAgent with .NET 6 and above support will be released tomorrow.

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon thank you for the update.
I have just tried the new Xamarin.TestCloud nuget on a .NET Maui project and I am now able to successfully write UI tests that include iOS.
Please congratulate the team on a job well done. It is unfortunate it has taken a year (- 6 days) to complete.

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon I have spotted an issue with the nuget, release builds appear to be including the nuget and they fail on uploading to TestFlight. The Calabash.Start() code is wrapped in a ifdef for DEBUG, but I have worked around the issue with the following in the .csproj:

`	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-ios' AND $(Configuration) == 'Debug'">
		<PackageReference Include="Xamarin.TestCloud.Agent" Version="0.23.2" />
	</ItemGroup>
`

the error in the upload is:
[08:13:08]: [altool]         detail = "The app references non-public selectors in Payload/AppDev.xxx.app/AppDev.xxx: setOrientation:animated:";

**Comment by evgenyvalavin** [comment]
Same Issue with non-public selectors

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon any comments on this? ideally need a fix, having to put conditions in the csproj isn't really ideal.

**Comment by IlyaBausovAkvelon** [comment]
@JohnHDev could you please clarify do you need Release configuration to test app on TestFlight?
Does TestFlight accept Debug builds?

Answering your question: This is by design. We don't think that calabash and TestCloud.Agent package should be in release configurations. I think in your case it's better to customize the project file.

@DmitriyKirakosyan

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon The builds we are uploading to TestFlight are release builds.

The Xamarin.Calabash.Start(); code is wrapped in an IFDEF DEBUG && IOS, so isn't being called on a release build.

However, something in the nuget means it is being included in the Release build when it should be linked out if there aren't any references.

**Comment by evgenyvalavin** [comment]
What if it's actually a dotnet trimmer's (Linker) issue? Looks like it's the trimmer's responsibility to not include assemblies wrapped in DEBUG or AD-HOC etc.
.NET 7 Linker has lots of issues which were not released yet: https://github.com/dotnet/linker/issues/3160

**Comment by JohnHDev** [comment]
> What if it's actually a dotnet trimmer's (Linker) issue? Looks like it's the trimmer's responsibility to not include assemblies wrapped in DEBUG or AD-HOC etc.
> .NET 7 Linker has lots of issues which were not released yet: [dotnet/linker#3160](https://github.com/dotnet/linker/issues/3160)

I believe you are correct, I have updated Xamarin iOS projects to the latest Xamarin.TestCloud nuget and Im not seeing the same issue with Release builds.

Im going to close this issue as the TestCloud nuget has now been updated to support .NET 6.
