### ISSUE TITLE
Xcode 13.3.x support

### ISSUE THREAD

**Issue by smaljaar** [microsoft/appcenter#2417]
**Describe the solution you'd like**
I would like to be able to select Xcode 13.3.x for building my iOS project, so that I can properly test my apps using the same build tools as I wish to develop and release them with. Xcode 13.3 solves a big problem with releasing apps that support iOS 12, see https://forums.swift.org/t/swift-concurrency-back-deploy-issue/53917/28 , that's why I'm extra eager to get Xcode 13.3 as option in app center sooner than later. 

**Describe alternatives you've considered**
Keep building using Xcode 13.1 which also supports iOS 12 app releases.

**Additional context**
Xcode 13.3 came out March 14, 2022, Xcode 13.3.1 followed on April 11.
I wish to be able to select Xcode 13.3.x here: 
![image](https://user-images.githubusercontent.com/2170746/165099535-955dfa5d-cb15-45b3-ac7d-85e50c6d38ae.png)

**Comment by DmitriyKirakosyan** [comment]
Hi @smaljaar , thank you for reaching out! Please follow the progress in #2408.
Closing as duplicate.
