### ISSUE TITLE
Support for React Native 0.68+

### ISSUE THREAD

**Issue by lostchopstik** [microsoft/appcenter#2419]
**Describe the solution you'd like**
React Native from 0.68 is now using Java 11. A version selector similar to the Node version selector should be added to handle this. Currently, I don't think there is a way for me to build my app, so for Android, I have to push it manually to the store.

**Describe alternatives you've considered**
There is no alternative for future versions of RN.

**Additional context**
From the RN docs at [https://reactnative.dev/docs/environment-setup](https://reactnative.dev/docs/environment-setup)
`If you have already installed Node on your system, make sure it is Node 14 or newer. If you already have a JDK on your system, make sure it is version 11 or newer.`

**Comment by aleksandr-dorofeev** [comment]
Hi @lostchopstik thank you for getting in touch with us! 
You can't build your React Native project on the portal?

**Comment by lostchopstik** [comment]
Hey there. No, I currently get this error when running a build on Android:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

**Comment by sabun123** [comment]
Hey @lostchopstik you can set the JAVA_HOME variable in AppCenter to 11 to overcome this. 

In App Center, under your Build Configuration you can set the `JAVA_HOME` to `$(JAVA_HOME_11_X64)`
<img width="497" alt="image" src="https://user-images.githubusercontent.com/3523483/167800003-2bcd633d-37d9-4f59-9c93-d3563fb0cfff.png">

Save and Build, and you're good to go.

You can ignore the other names I have in the build configuration, those are specific to my project.

I recently moved my projects' compileSdkVersion  to 31 and basically anything 31 and above for Android requires Java 11, so I ran into what you're facing too. The above did the trick, hope it helps

**Comment by lostchopstik** [comment]
Thanks for the workaround @sabun123!

**Comment by harrymash2006** [comment]
setting JAVA_HOME as $(JAVA_HOME_11_X64) is not working anymore. It is throwing unknown error. Any suggestion ?
