### ISSUE TITLE
Support EXE/MSI Installers for WPF

### ISSUE THREAD

**Issue by adammarks** [microsoft/appcenter#242]
Looked at the proposed windows Plan and have feedback https://github.com/Microsoft/appcenter/blob/windows/specs/2019-04/Windows-Plan.md

**Describe the solution you'd like**
Include support for zipped EXE/MSI installers for WPF

**Additional context**
In theory MSIX can work on Win7 with [this](https://github.com/Microsoft/msix-packaging/tree/master/preview/Win7Msix) but most customers, beta testers, test machines won't have that.

**Comment by patniko** [comment]
Hi @adammarks, instead of leaving it up to the feature request we have a PR open right now for comments and discussions. Feel free to request changes or additions to our plan directly. https://github.com/Microsoft/appcenter/pull/193/files

**Comment by adammarks** [comment]
@patniko Thank you I didn't see the PR, very helpful,  I'll close this for now

**Comment by winnieli1208** [comment]
Hi @adammarks just wanted to let you know we just released distribution, diagnostics, and analytics support for WPF and WinForms apps. Distribution supports including releasing .msi files. 

Thanks!

**Comment by adammarks** [comment]
excellent :+1:  We will try uploading msi files.  I'm assuming this means that EXE installers are not supported

**Comment by adammarks** [comment]
I just tried it and we can upload a .EXE installer as long as it is in a .zip file, just like HockeyApp. 

Thank you, Excellent work,  we can begin migrating to AppCenter! 👍

**Comment by NLI-KelbyHunt** [comment]
@winnieli1 - Sorry to revive a closed issue, can we not get support for .EXE? I tend to use 7Zip SFX (self extracting archive) to release my software internally. Especially with .NET Core self-contained release, my SFX .EXE archives are amazingly simple.

**Comment by adammarks** [comment]
I agree with @NLI-KelbyHunt we are successfully uploading .zip's of WPF EXE installers and now everyone is asking why do they need to download then unzip to get the installers.  Could be simplified to just allow uploading EXE directly,  that would reduce the amount of steps needed before upload and after download.

**Comment by winnieli1** [comment]
Thanks for the feedback! I can see why that extra step is not an ideal experience. Due to other priorities at the moment, we don't have immediate plans to add support for EXE but we'll keep this issue open to track interest and prioritize accordingly. Thanks!

**Comment by NLI-KelbyHunt** [comment]
@winnieli1 - Thanks, if AppCenter ever extends certain sections of its code base to opensource, myself and my company would happily submit a pull request under contribution guidelines. Please consider my voice at least 10 people who are interested in this feature. Thanks!
