### ISSUE TITLE
User unable to access the apps

### ISSUE THREAD

**Issue by tomsonyeungaia** [microsoft/appcenter#2421]
Hi, I have granted access right to one of our employee of our UAT mobile app. But she is not able to access to it. 
The error message is "Account with this email is already associated with another identity provider: aad"
May I know the reason and how to solve it?
![image](https://user-images.githubusercontent.com/104827602/168022267-5f40c6d2-b99b-4b0c-a4ca-8e2b4fa9497b.png)

**Comment by tomsonyeungaia** [comment]
this is my first time to visit here and post a question. Please forgive and guide me if I made in the wrong place. Thank you.

**Comment by tomsonyeungaia** [comment]
I tested with few accounts, it seem related to login accounts with Microsoft and Github. Some ac can access with Github, but shows the error when access with Microsoft with same email address, vice versa. Anyone know if there is any affect and how to cancel one of the account?

**Comment by AnatolyPristensky** [comment]
Hi! Thanks for getting in touch with us!
You can open a [support ticket](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) on the App Center portal with this question.
