### ISSUE TITLE
See how many users have multiple apps installed.

### ISSUE THREAD

**Issue by alexrest** [microsoft/appcenter#2423]
I have two apps on the App Store. I'd like to know how many people with App A also have App B installed.

No alternatives are apparent.

Thanks!

**Comment by DmitriyKirakosyan** [comment]
Hi @alexrest , you can setup data export in and perform some custom queries to get the required statistics. For that purpose, you can rely on the "StartSessionLog" event. If you set a user id using `AppCenter.setUserId` API, it will be present in your event logs. Also, you can use custom events with additional properties if needed.

As for the feature request to make it work right on the AppCenter portal, we don't have any plans for implementing such functionality. But let's keep it open and see how many people are interested in this feature.
