### ISSUE TITLE
Add Appium Gradle support 

### ISSUE THREAD

**Issue by namrog84** [microsoft/appcenter#243]
**Describe the solution you'd like**
Right now appcenter+appium supports maven(pom.xml)
but appcenter+espresso supports gradle.

gradle is the more popular build thingy nowadays.  Please add support
or a very well detailed createpom mechanisms in the meantime. 

**Describe alternatives you've considered**
createpom from gradle to generated the maven pom.xml, but its blah 

**Additional context**

**Comment by nrajpurkar** [comment]
Thanks for the feature request @namrog84! We'll keep this open to track interest in this.

**Comment by smaikk** [comment]
when this functionality is born!

**Comment by namrog84** [comment]
I don't understand why suggestions/feature requests require activity? Shouldn't they be held open?
