### ISSUE TITLE
What is the Mircosoft's roadmap for app center development

### ISSUE THREAD

**Issue by UniperMaster** [microsoft/appcenter#2434]
Does Microsoft have a new application in the pipeline has there haven't been any updates for nearly a year to the app center  , particularly the annoying feature of not being able to refresh an intune distribution token not being resolved #407

**Comment by aleksandr-dorofeev** [comment]
Hi @UniperMaster 
At the moment, our team is focused on the goals of the [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#app-center-roadmap-2022).
