### ISSUE TITLE
Don't fail a build if the distribution step fails

### ISSUE THREAD

**Issue by will-gluwa** [microsoft/appcenter#2435]
**Describe the solution you'd like**
It would be great if you didn't completely fail a build if distribution fails with a message like this:

```
##[error]{"code":"two_factor_authentication_error","message":"Error: Failed to publish to store. apple connection is not valid for connectionId: 9c0c5785-f466-4a94-b1ce-27015849b01d"}
http response code: 400
##[section]Finishing: Create distribution
```

It would be *much* more helpful if the build marked as "Warning" rather than "Failed" and the build artifacts were stored for the release so that I could fix the auth issue, then distribute the build to the store manually (or via a "Retry distribution" option) without the need to rebuild the entire application again.

**Describe alternatives you've considered**
Currently the only alternative is to restart the entire build or remove the distribute step and manually distribute it afterward

**Additional context**
With 2FA enabled, distributing apps will often fail, as the existing session expires and there's no warning of this ahead of time.

**Comment by will-gluwa** [comment]
Why would you close it if it's still an issue?

**Comment by will-gluwa** [comment]
Wish you wouldn't close this

**Comment by RachelNaane** [comment]
would like to have this feature too
