### ISSUE TITLE
.NET 6 Support

### ISSUE THREAD

**Issue by kondareddy** [microsoft/appcenter#2444]
Looks like we don't have .net 6 supporting nuget package?

Any timeline for same?

**Comment by DmitriyKirakosyan** [comment]
Hi @kondareddy , thank you for reaching out!
Are you talking about AppCenter SDK Nugets or Xamarin.UITest Nugets?

**Comment by kondareddy** [comment]
Thanks for reply.

I am migrating our app from .NET 4.6 to .NET 6 and referring to AppCenter SDK.

to be precise
AppCenter.Analytics.Metrics.dll
Microsoft.AppCenter.Analytics.dll
Microsoft.AppCenter.Crashes.dll

**Comment by DmitriyKirakosyan** [comment]
Thank  you for the clarification.
We are working on .NET 6 support, but no ETA at this moment.

As for `Microsoft.AppCenter.Analytics.Metrics.dll`, this is not an official AppCenter SDK dll and thus it is not under our control.

I'm closing it as a duplicate of https://github.com/microsoft/appcenter-sdk-dotnet/issues/1660 and https://github.com/microsoft/appcenter-sdk-dotnet/issues/1647.

**Comment by MatkovIvan** [comment]
@kondareddy .NET 6 cannot consume existing (in our package) TFMs only on iOS/macOS platform, in case of Windows (based on your .NET Framework 4.6 mention) it should pickup existing .NET 5 binaries
