### ISSUE TITLE
Flutter build iOS on AppCenter get stuck at Running Xcode build

### ISSUE THREAD

**Issue by Abisheik-IAN** [microsoft/appcenter#2445]
# Short description
I am trying to build my flutter app on AppCenter but the build process get stuck at Running Xcode build.... After the building time arrive at 30 mins i get a lot of CompileC ... messages and an error: ##[error]The operation was canceled..

I mention that in Xcode on my local machine the project is build successfully.
# Steps to Reproduce

1. Press build now button on AppCenter 😸
2. Wait 30 minutes...

# Post-clone script

`#!/usr/bin/env bash

set -e

set -x

cd ..

git clone --branch 2.10.5 https://github.com/flutter/flutter.git

export PATH=`pwd`/flutter/bin:$PATH

flutter doctor

echo "Installed flutter to `pwd`/flutter"

flutter build ios --release --no-codesign`
# Logs
Here is flutter doctor -v output:

Here is my entire [log:]
[1_Build (1).txt](https://github.com/microsoft/appcenter/files/9146934/1_Build.1.txt)

I would be more tha grateful if someone would help me to solve this building problem 😄! Thanks!

**Comment by DmitriyKirakosyan** [comment]
Hi @Abisheik-IAN , unfortunately Flutter is not supported yet. Please follow the progress on this feature request https://github.com/microsoft/appcenter/issues/67.
Closing as duplicate.
