### ISSUE TITLE
Support WebDriverIO + Appium for React Native Applications on AppCenter Test (JS + Appium)

### ISSUE THREAD

**Issue by mrk-han** [microsoft/appcenter#2446]
**Describe the solution you'd like**

Enable the testing of React Native Applications with WebDriverIO + Appium on Physical Devices in AppCenter Test. 

React Native Automation w/ AppCenter is in a really bad spot right now. AppCenter only supports Java based Appium, so we cannot use WebDriverIO or write our automation in the same language as the app code, Javascript/Typescript. And Detox is only possible in AppCenter Build (post-build script) on emulator/simulators. This is because Detox does not yet support iOS physical devices.

**Describe alternatives you've considered**

Java w/ Appium is supported, but that means no WebDriverIO and also means our JS/TS friendly RN developers will be in less familiar territory. Both are very bad.

Detox can run with RN apps, but they are currently not supporting iOS Physical Devices. Which means AppCenter can only run Detox on emulator/simulators spun up in a post-build script after AppCenter Build. 

SauceLabs supports WebDriverIO + Appium.

**Additional context**

https://github.com/wix/detox/issues/95 Detox Issue on no support for iOS Devices

https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/ Supported Frameworks with AppCenter listing Java Appium support with JUnit only. (TestNG support would be nice)

https://github.com/microsoft/appcenter/issues/262 AppCenter Issue on Detox Support

https://webdriver.io/docs/appium-service/ WebDriverIO Appium Service

**Comment by IlyaBausovAkvelon** [comment]
Hello @mrk-han!
We need to discuss it with the team. I will write you here when there will be updates.

**Comment by mrk-han** [comment]
@IlyaBausovAkvelon Was there ever a discussion?

**Comment by mrk-han** [comment]
The latest macos runners for azure/github dont have haxm installed out of the box. This is 2 major versions (macos 11 and macos 12) of having poor emulator support on CI. 

Since AppCenter Test doesn't support RN Expo or Webdriverio Javascript appium, there's not a great way to write automation for RN on Azure's VMs or on real devices. 

It's a really bad ecosystem right now for UI testing.

Webdriverio or vanilla appium with javascript would be so much better than java appium. There is less context switching between languages, the pipelines are easier to set up because they share similar dependencies, the devs and testers can both fix and write tests in the same language. Please consider this on your roadmap.

**Comment by aleksandr-dorofeev** [comment]
Hey @mrk-han
We don't have any ETA for this feature at this moment. Let's keep it open and see how many upvotes it gets.
See more info in our [Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#app-center-roadmap-2022).

**Comment by mrk-han** [comment]
Thank you so much @aleksandr-dorofeev , I'll see if I can reach out to other teams who are requesting this as well that can chime in for the benefits it would bring them. Appreciate you linking the roadmap, too.

**Comment by albert17** [comment]
This would be awesome!

**Comment by vincecoleman** [comment]
This would be really useful for our team as well!

**Comment by ramespra** [comment]
I also support this

**Comment by oesahan** [comment]
Describe the solution you'd like

Enable the testing with WebDriverIO + Appium on Physical Devices in AppCenter Test.

AppCenter only supports Java based Appium, so we cannot use WebDriverIO or write our automation in the same language as the app code, Javascript/Typescript. Our team completely using Javascript/Typescript as the main language. This feature is highly on demand.

This discussion is relatively old and I was wondering if there are any developments on this topic.

Also Appium version used in the App Center is also an older version which is 1.22. Right now with Appium 2.1 there are a lot of changes introduced to mobile testing. Is there a plan to update/modernize the App Center mobile testing structure?
