### ISSUE TITLE
"appcenter test run uitest" fails on Xamarin.UITest v3.2.8

### ISSUE THREAD

**Issue by wi-ry** [microsoft/appcenter#2447]
```
/ Preparing tests... Test chunking failed: Failed to execute: C:\Users\Will\AppData\Local\Temp\uitest\a-6864F5FA871391821D9AB4A4274B7E6B939BE9B2\nunit3\Xamarin.UITest.Integration.NUnit3.exe "Y:\SRC\AzDO\CdUtils\Xamarin.UITest\GluwaPro.UITest\bin\Release\GluwaPro.UITest.dll" --include=Temp - exit code: -532462766

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'DocoptNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=7a38c71da49a547e' or one of its dependencies. The system cannot find the file specified.
   at Xamarin.UITest.Integration.NUnit3.Program.Main(String[] args)

Preparing tests... failed.
Error: Failed to prepare UI Test artifacts using command "test-cloud.exe prepare" with error message:
Test chunking failed.Please try to delete dlls which are not necessary from the path provided in the --build-dir argument.If this error happens again, please contact support.
```

Works fine on the same environment with Xamarin.UITest 3.2.7.

Windows 11 22H2 (OS Build 22621.232)
Xamarin.UITest 3.2.8
NUnit 3.13.3
NUnit.Engine 3.15.2
NUnit3TestAdapter 4.2.1

**Comment by IlyaBausovAkvelon** [comment]
Hello @MrAusnadian.
I am taking a look at this. I will write you back when I will find the root cause.

**Comment by IlyaBausovAkvelon** [comment]
@MrAusnadian which VisualStudio version you use to build the project?

**Comment by will-gluwa** [comment]
VS 2022 17.2.6

**Comment by AlexeyBudynkov** [comment]
@MrAusnadian, can you, please, provide us the appcenter cli command?

And a little question, did you try to rebuild the Xamarin.UITest application?

**Comment by AlexeyBudynkov** [comment]
Sorry, I accidentally closed this ticket. It's active again

**Comment by MrAusnadian** [comment]
`appcenter test run uitest --app Acme/Android --devices deviceList --app-path app.apk --test-series UITests --locale en_US --build-dir Y:\SRC\Xamarin.UITest\bin\Release --uitest-tools-dir C:\Users\Will\.nuget\packages\xamarin.uitest\3.2.8\tools --include-category Temp --async`

**Comment by AlexeyBudynkov** [comment]
I tested it locally on Mac OS and everything works fine. We'll test it on a Windows machine

**Comment by IlyaBausovAkvelon** [comment]
We are currently working on this issue.

**Comment by IlyaBausovAkvelon** [comment]
It's a known one.

**Comment by MrAusnadian** [comment]
Cool beans

**Comment by IlyaBausovAkvelon** [comment]
@Moshex Could you please tell if you have the DocoptNet.dll in tools/ directory where the Xamarin.UITest NuGet package files are extracted?

**Comment by IlyaBausovAkvelon** [comment]
Because issues with test-cloud.exe dependencies should be resolved in 4.0.1.

**Comment by IlyaBausovAkvelon** [comment]
All required dependencies for running test-cloud.exe should be in /tools directory with test-cloud.exe. That's strange. Let me double check it.

**Comment by Moshex** [comment]
okay,  I found it,

Do you know why there is such a big change to having all the dll's stored in this folder? and with that file being there what do I need to do to get the app center to work with version 4.0.1?

![Screen Shot 2022-12-16 at 7 32 39 AM](https://user-images.githubusercontent.com/6087936/208121081-21f0a4c9-60cb-4241-be2d-8e356f048f97.png)

**Comment by IlyaBausovAkvelon** [comment]
@Moshex previously test-cloud.exe build process used ILMerge to pack all DLLs in executable. Currently due to the .NET 6 changes we decided to remove this step.
The issue here probably with appcenter-cli. Maybe it could not find the test-cloud.exe dependencies and is not trying to move it to working directory.

**Comment by will-gluwa** [comment]
I'm having similar failures with v4.0.1 of tools:
```
- Preparing tests... Tried to parse non-string value as a string

Run ' help prepare' for more details.

Preparing tests... failed.
Error: Failed to prepare UI Test artifacts using command "test-cloud.exe prepare" with error message:
There was an unknown error preparing test artifacts, please try again. If you can't work out how to fix this issue, please contact support.
```

The same command works fine by changing the tools-dir:
`--uitest-tools-dir "C:\Users\Will\.nuget\packages\xamarin.uitest\3.2.9\tools"`

**Comment by IlyaBausovAkvelon** [comment]
@will-gluwa Could you please provide more details or logs on this error?

**Comment by will-gluwa** [comment]
> @will-gluwa Could you please provide more details or logs on this error?

What information do you need, or would be helpful?

Ximei has the environment information from a ticket I submitted (_Test Cloud Issue #LCJLTGNE_). His response was:
> Thanks for getting in touch. Please don't use the latest version, it has some issue. Currently our team is still working on this issue but there's no update yet. Sorry for the inconvenience about.

**Comment by b4ssk3y** [comment]
Hello, I have the same issue on Xamarin.UiTest v4.0.1

AppCenter cli command:
C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.214.0\node_modules\.bin\appcenter.cmd test prepare uitest --artifacts-dir D:\a\1\a\results --app-path D:/a/1/Application/Android/com.xxxxxxx.xxxxxx.apk --build-dir D:\a\1\Tests\Mobile.Tests\Android --uitest-tools-dir D:\a\1\Tests\Mobile.Tests\Android --include-category xxxxxxxxxxxx --debug --quiet"

Using appcenter-cli version: 2.11.0

Error:
Unhandled Exception: 
System.IO.FileNotFoundException: Could not load file or assembly 'DocoptNet, Version=0.8.1.0, Culture=neutral, PublicKeyToken=7a38c71da49a547e' or one of its dependencies. The system cannot find the file specified.
   at Xamarin.UITest.CLI.Program.Main(String[] args)


Same command works fine on Xamarin.UiTest v3.2.9

**Comment by IlyaBausovAkvelon** [comment]
@will-gluwa ok, we are working on this.
@b4ssk3y I will try to reproduce it. By the way do you have the docopt.net assembly in the /tools directory of .nuget folder?

**Comment by b4ssk3y** [comment]
![image](https://user-images.githubusercontent.com/94126337/212383919-dc21aa8a-c2ee-4415-939b-ce923181cf81.png)

Seems so

**Comment by IlyaBausovAkvelon** [comment]
We will try to fix this.

**Comment by Moshex** [comment]
When I updated to version Xamarin.UITest 4.1.0 and try to run the tests on the app center it gets stuck on
"/ Preparing tests... " and never progresses past that below is the log when I run "npm i -g appcenter-cli " not sure what I can do.



mmoadeb@Moshes-MacBook-Pro-4 ~ % npm i -g appcenter-cli 
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'chalk@5.2.0',
npm WARN EBADENGINE   required: { node: '^12.17.0 || ^14.13 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'has-yarn@3.0.0',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'is-npm@6.0.0',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'chalk@5.2.0',
npm WARN EBADENGINE   required: { node: '^12.17.0 || ^14.13 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lowercase-keys@3.0.0',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'mimic-response@4.0.0',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated superagent@5.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated azure-storage@2.10.7: Please note: newer packages @azure/storage-blob, @azure/storage-queue and @azure/storage-file are available as of November 2019 and @azure/data-tables is available as of June 2021. While the legacy azure-storage package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Migration guide can be found: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/MigrationGuide.md

added 2 packages, removed 7 packages, changed 502 packages, and audited 505 packages in 18s

83 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New major version of npm available! 7.6.3 -> 9.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.4.0
npm notice Run npm install -g npm@9.4.0 to update!
npm notice 
mmoadeb@Moshes-MacBook-Pro-4 ~ % npm install -g npm@9.4.0
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'npm@9.4.0',
npm WARN EBADENGINE   required: { node: '^14.17.0 || ^16.13.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'agentkeepalive'
npm ERR! Require stack:
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/agent.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/index.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/pacote/lib/remote.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/pacote/lib/git.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetcher.js
npm ERR! - /usr/local/lib/node_modules/npm/node_modules/pacote/lib/index.js
npm ERR! - /usr/local/lib/node_modules/npm/lib/utils/update-notifier.js
npm ERR! - /usr/local/lib/node_modules/npm/lib/cli.js
npm ERR! - /usr/local/lib/node_modules/npm/bin/npm-cli.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mmoadeb/.npm/_logs/2023-01-26T18_01_05_206Z-debug.log
mmoadeb@Moshes-MacBook-Pro-4 ~ % npm i -g appcenter-cli  
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'chalk@5.2.0',
npm WARN EBADENGINE   required: { node: '^12.17.0 || ^14.13 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'has-yarn@3.0.0',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'is-npm@6.0.0',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'chalk@5.2.0',
npm WARN EBADENGINE   required: { node: '^12.17.0 || ^14.13 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lowercase-keys@3.0.0',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'mimic-response@4.0.0',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated superagent@5.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated azure-storage@2.10.7: Please note: newer packages @azure/storage-blob, @azure/storage-queue and @azure/storage-file are available as of November 2019 and @azure/data-tables is available as of June 2021. While the legacy azure-storage package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Migration guide can be found: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/MigrationGuide.md

changed 504 packages, and audited 505 packages in 11s

83 packages are looking for funding
  run `npm fund` for details

**Comment by IlyaBausovAkvelon** [comment]
@Moshex Thank you for reporting that. We know about this issue and currently working on the fix.

**Comment by Moshex** [comment]
@IlyaBausovAkvelon Thank you for looking into it!

**Comment by rory-bloomerang** [comment]
Any update on this? I can't upgrade to 4.1.2 without this issue breaking our pipelines.

**Comment by IlyaBausovAkvelon** [comment]
Hi All.
This issue hasn't been resolved yet. We are working on the fix.

**Comment by b4ssk3y** [comment]
Just tested with Xamarin Ui Test 4.1.2 and the same issue on Docop.Net library still appears.

**Comment by b4ssk3y** [comment]
> Just tested with Xamarin Ui Test 4.1.2 and the same issue on Docop.Net library still appears.

Some more information that may help in investigating the issue...
Knowing this issue with Docopnet.dll, yesterday I looked at possible workarounds. I created locally an environment similar to the one I have Azure pipeline based on which the app center CLI command are created.
In the test artifacts folder, as they come out of the build pipeline, the Docopnet.dll is **not** included, and that causes the exception already mentioned:

`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'DocoptNet, Version=0.8.1.0, Culture=neutral, PublicKeyToken=7a38c71da49a547e' or one of its dependencies. The system cannot find the file specified.
   at Xamarin.UITest.CLI.Program.Main(String[] args)

Preparing tests... failed.
Error: Failed to prepare UI Test artifacts using command "test-cloud.exe prepare" with error message:
Returning exit code 3762504530.`

But if I add that DLL in the test artifacts folder, along with all the other Dlls, the same test prepare command remains stuck endlessly, without errors, warnings or message whatsoever: the prompt stays there saying "Preparing tests..." 

This is the command I run:

`appcenter test prepare uitest --artifacts-dir C:\workspace\MyApp\AppCenter\results --app-path C:\workspace\MyApp\AppCenter\Application\IOS\MyApp.ipa --build-dir C:\workspace\MyApp\AppCenter\Tests\Mobile.Tests\iOS --uitest-tools-dir C:\workspace\MyApp\AppCenter\Tests\Mobile.Tests\iOS --include-category MY-CATEGORY-TAG --debug`

Hope it helps

**Comment by EllaVader** [comment]
Nuget 4.1.3 is out and fixes the issue with the missing DocoptNet.dll as it now is in the bin folder of your build output.  Also update appcenter-cli to version 2.13.4
So now running the tests appear to be happening, however there tests come back with 0 ran, 0 passed, 0 failed with no helpful information as to why?

`Current test status: Done!
Total scenarios: 0
0 passed
0 failed
Total steps: 0
`

and there are NO logs or any helpful info as to what is wrong in AppCenter

![image](https://user-images.githubusercontent.com/8941982/230452248-6ef73e86-177e-40d3-9fed-54cdf58a6be4.png)

**Comment by wi-ry** [comment]
Closing ticket. I don't even work for the company that I opened this ticket for anymore, haha
