### ISSUE TITLE
How about support AWSCommit

### ISSUE THREAD

**Issue by alexrodriguezfer** [microsoft/appcenter#2450]
AppCenter currently supports building apps in Git repositories, I would love to have App center accessing my AWS Code Commit repositories.

**Comment by mrodzim** [comment]
I can not wait for it! that would be super helpful

**Comment by alexrodriguezfer** [comment]
As in [this issue](https://github.com/microsoft/appcenter/issues/1501), reported some time ago, I think that several people will appreciate if AppCenter could work with other repositories like AWS CodeCommit.

**Comment by mustafa-malayawala** [comment]
When will this feature be available, is it taken into consideration?

**Comment by alexrodriguezfer** [comment]
Any update from Microsoft team? Are you planning this feature in the product roadmap?
