### ISSUE TITLE
Support for react native's new architecture

### ISSUE THREAD

**Issue by PritishSawant** [microsoft/appcenter#2451]
**Describe the solution you'd like**
From React native v0.68 we can enable the new architecture. I would like app centre to support it as well

**Describe alternatives you've considered**
No alternatives as of yet

**Additional context**
[New architecture](https://reactnative.dev/docs/new-architecture-intro)

**Comment by DmitriyKirakosyan** [comment]
Hi @PritishSawant , are you talking about [ReactNative AppCenter SDK](https://github.com/microsoft/appcenter-sdk-react-native)?
If yes, please provide more context on what exactly is not working after you upgrade to the new architecture.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue due to the inactivity.

@PritishSawant , please reply to my question above if you're still interested in this feature.
