### ISSUE TITLE
Need support for changing font size on app center device

### ISSUE THREAD

**Issue by IlyaDhtvzGhbltn** [microsoft/appcenter#2464]
Hello Team, 
AppCenter is a very useful tool for UI testing. But despite the wide possibilities there isn't possible to change font size on devices while tests. I use Xamarin UI test framework and I can change only system locale via CLI command **--locale "en_US"** before test run. It will be great if you add support font size changing on devices, example something like this **--font-size XXS** or **--font-size XS** or **--font-size XXL** etc

**Comment by AlexeyBudynkov** [comment]
Hello @IlyaDhtvzGhbltn , thank you for the feature request.
Unfortunately, we do not have ETA for this.
We have a [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#app-center-roadmap-2022) where you can see the team's priorities for the year.
