### ISSUE TITLE
Send custom properties to Application Insights in a format that can be parsed

### ISSUE THREAD

**Issue by Gabelken** [microsoft/appcenter#2467]
Custom properties on events/errors exported to Application Insights are sent as a single custom property named "Properties" which contains the entire dictionary. Because the properties are not split like the other telemetry fields, it is difficult to work with the data in Insights.

**Describe the solution you'd like**
I would like to see custom properties from App Center exports to appear as separate custom properties in Application Insights.

**Additional context**
Current:
![Screen Shot 2022-09-06 at 4 53 23 PM](https://user-images.githubusercontent.com/20609647/188755136-cedfb8d1-0f1f-458f-88d3-9b115d8eef8a.png)

Expected:
![Screen Shot 2022-09-06 at 4 53 23 PM](https://user-images.githubusercontent.com/20609647/188755951-210f12aa-80bf-4af7-940f-3d66b4016668.png)

**Comment by Gabelken** [comment]
still active

**Comment by cosminstirbu** [comment]
You can use [parse_json](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/parsejsonfunction) from Kusto to parse the properties.

**Comment by mdivkovic-speech** [comment]
@cosminstirbu is there a way to map those properties from App Center to individual values as they arrive in Application Insights, instead of having to rely on a custom query in a workbook. What we want is to have the properties visible in the built-in reports. Is this possible? Otherwise it kinda sucks.

**Comment by lucen-ms** [comment]
Unfortunately, I'm not aware of possibility to transform AppInsight data during ingestion stage.

**Comment by lucen-ms** [comment]
We do not have plans to add support for this feature in the next year.

**Comment by gireeshsahu** [comment]
Pack your properties in dictionary like below and then use it.

        Dictionary<string, object> customProps = new Dictionary<string, object>
        {
               { "User", "John.Doe"},
               { "another", "value"}
        };

**Comment by mdivkovic-speech** [comment]
> Pack your properties in dictionary like below and then use it.
> 
>         Dictionary<string, object> customProps = new Dictionary<string, object>
>         {
>                { "User", "John.Doe"},
>                { "another", "value"}
>         };

I' not sure how this is any different than what AppCenter already does automatically. These properties won't be accessible in standard reports as custom properties would be if you used application insights directly (e.g. in web), will they? Extracting them by parsing json in a custom query is not the point. We need them to be filterable and usable in reports by non-developers.
