### ISSUE TITLE
Enable app developers to view and search for the list of app users authenticated to the app

### ISSUE THREAD

**Issue by amchew** [microsoft/appcenter#247]
[Identity MVP Technical Specification](https://github.com/microsoft/appcenter/blob/master/specs/Identity/Identity-Spec.md)

In the month of Apr, we are working on enabling app developers to view and search for the list of app users authenticated to the app in App Center.

Let us know if you have any feedback, or would like to be a part of our private preview!

Here are some designs: 
![image](https://user-images.githubusercontent.com/33160470/55199488-680ab100-5177-11e9-8d76-5afdc3c4f611.png)

**Comment by fiannaca** [comment]
The link to your spec is broken. The spec was moved up out of the month directory.

**Comment by amchew** [comment]
Thanks @fiannaca for letting us know, and nice catch! I've updated the link to the spec.

**Comment by amchew** [comment]
Closing this issue - we reduced the scope and did not implement this in our public preview. If you have any feedback, please let us know. You can [learn more about Auth](https://devblogs.microsoft.com/appcenter/introducing-visual-studio-app-center-auth/)!
