### ISSUE TITLE
Xamarin.UITest

### ISSUE THREAD

**Issue by RavindraRP-Xamarin** [microsoft/appcenter#2472]
Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent

ExitCode: 70

iOS-16.0.2(20A380)
Xcode-14.0.1(14A400)
Mac OS-12.6(Monterery)
Xamarin.iOS
Version: 15.6.0.3 (Visual Studio Enterprise)

**Comment by DmitriyKirakosyan** [comment]
Hi @RavindraRP-Xamarin , please contact our [support team](https://learn.microsoft.com/en-us/appcenter/help). They will able to check your test run and will do their best to help with resolving it.

**Comment by RavindraRP-Xamarin** [comment]
@DmitriyKirakosyan Thanks
