### ISSUE TITLE
AppCenter Build - When can we expect support for Maui?

### ISSUE THREAD

**Issue by EdwardMcFlurry** [microsoft/appcenter#2478]
![9FD1DBF8-88A4-4C05-BAA7-D1A88475FA5E](https://user-images.githubusercontent.com/46613832/194997521-941542ae-fc81-4314-bcb1-8615ec56314d.jpeg)

**Comment by aleksandr-dorofeev** [comment]
Hello @EdwardMcFlurry 
It looks like a [duplicate](https://github.com/microsoft/appcenter/issues/2360). I'm closing this issue, and you can follow all the necessary information in the thread that I attached.
