### ISSUE TITLE
Allow exporting diagnostics to Application Insights

### ISSUE THREAD

**Issue by asierpn** [microsoft/appcenter#2479]
**Describe the solution you'd like**
Allow exporting diagnostics to Application Insights as is done with analytics, data retention in App Center is being decreased and we need to retain the information longer to better analyze some errors.

**Comment by DergachevE** [comment]
@asierpn Could you please clarify more on which Diagnostics data you are missing during export?
Currently export of Diagnostics data to Application Insights is supported as common log messages:
You can find your crashes/handled errors details in `customEvents` table.

**Comment by asierpn** [comment]
@DergachevE Yes, we cannot see our crashes/handled errors even in the customEvents table, but on the other hand we expected to find them in the exceptions table for a better analysis experience in the Azure Portal.

**Comment by DergachevE** [comment]
@asierpn Could you please create a support ticket via App Center portal in this case? This will help us to investigate your issue faster as you can share more details about your application there.

**Comment by asierpn** [comment]
@DergachevE Done!

**Comment by asierpn** [comment]
I get this response from App Center support:

> Diagnostics data is not exported to Application Insights, only Analytics data is exported: 
> https://learn.microsoft.com/en-us/appcenter/analytics/export
> 
> If you wish to export diagnostics data, you can export it to Azure Blob Storage. Here are the instructions to do the same:
> 
> https://learn.microsoft.com/en-us/appcenter/gdpr/diagnostics-export#use-azure-blob-storage

They have confirmed that only a basic error event should be exported to AI for each exception, but it doesn't contains the exception details, like stacktrace, so it is not very useful. They are looking why even this event is not being exported.

The response confirms that this feature suggestion makes sense, exporting exceptions to blob storage is not useful as we cannot analyse them in AI in combination with the events registered.

**Comment by DergachevE** [comment]
@asierpn Thanks for your response.
Yes, error events are exported to AI as basic log event without details about stacktrace, symbolication, etc.
Currently App Center does not support export of symbolicated crashes with stacktrace, crash group assignment, etc.

**Comment by asierpn** [comment]
@DergachevE There is no sense in this behavior, because we can manually track  an event for each exception handled with all this information in custom properties to get this information available in AI, but the space usage in App Center will increase duplicating all this information in App Center, and considering that you have reduced the retention period of data in App Center this is not desirable for you.

**Comment by DergachevE** [comment]
@asierpn Technically you can do this but if your application will handle all exceptions then no crashes (UnhandledErrorLog) should be sent by SDK. Regarding sending errors information as custom event properties please refer to the official documentation about the limits: https://learn.microsoft.com/en-us/appcenter/analytics/event-metrics#limits
