### ISSUE TITLE
Fastlane issue - Add a possibility to specify -asc_provider option

### ISSUE THREAD

**Issue by alex-mironov** [microsoft/appcenter#2480]
Since recently Appcenter builds for iOS are failing to distribute:
```
[0m
[15:20:25]: [33m[iTMSTransporter] 		Cannot obtain the content provider public id. Please specify a provider short name using the -asc_provider option.
[0m
[15:20:25]: [33m[iTMSTransporter] [2022-10-20 15:20:24 UTC] <main> DBG-X: Returning 1
[0m
[15:20:25]: iTunes Transporter output above ^
[15:20:25]: [31mCannot obtain the content provider public id. Please specify a provider short name using the -asc_provider option.
Return status of iTunes Transporter was 1: Cannot obtain the content provider public id. Please specify a provider short name using the -asc_provider option.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m

#######################################################################
# fastlane 2.210.1 is available. You are on 2.208.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
[31m
[!] Error uploading ipa file: 
 [0m

```

That's probably due to the fact I belong to multiple teams. Here is the original issue in fastlane project https://github.com/fastlane/fastlane/issues/20756#issuecomment-1283773210
Any ideas how to make it work?

**Comment by mikequ-taggysoft** [comment]
Same error here. Cannot distribute to App Store.

**Comment by velancio** [comment]
Same here. Started using transporter to upload builds as a workaround.

**Comment by mljlynch** [comment]
Same here. This just started today. I don't think this is a feature request this is a blocking bug.

**Comment by divyameher** [comment]
Any update regarding this?

**Comment by mikequ-taggysoft** [comment]
@divyameher This issue just started around yesterday so it may take a bit of time to resolve on MS side. In the meantime we can still build with App Center, but upload the ipa via Apple's Transporter app.

**Comment by AnatolyPristensky** [comment]
Hello all, 
I want to inform you that currently we have an active incident with this issue. 
It should be mitigated soon.

**Comment by esaffer** [comment]
None of you guys have managed t omake it work? I have a build machine with github actions and fastlane configured and suddently they stop uploading for this same error.

**Comment by aureosouza** [comment]
Seems to be working now in AppCenter for test flight publishing

**Comment by AshrafAkon** [comment]
I was setting up an old app with Fastlane and encountered this issue. My old Fastlane configs are working as of yesterday.

**Comment by wisnhusurya** [comment]
Any update regarding this issue?

**Comment by maxine-96** [comment]
Try this one to your fastFile : 

before_all do 
         ...
         ...
         ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-asc_provider YourTeamID"
end

**Comment by DavidStryfe** [comment]
> Try this one to your fastFile :
> 
> before_all do ... ... ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-asc_provider YourTeamID" end

This works like a charm! Thank you very much!

**Comment by wisnhusurya** [comment]
> Try this one to your fastFile :
> 
> before_all do ... ... ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-asc_provider YourTeamID" end

Thankyouuuu this is work for me, but need some adjustment in my case.

**Comment by batrinuvlad** [comment]
> > Try this one to your fastFile :
> > before_all do ... ... ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-asc_provider YourTeamID" end
> 
> Thankyouuuu this is work for me, but need some adjustment in my case.

what adjustment?

**Comment by wisnhusurya** [comment]
> > > Try this one to your fastFile :
> > > before_all do ... ... ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-asc_provider YourTeamID" end
> > 
> > 
> > Thankyouuuu this is work for me, but need some adjustment in my case.
> 
> what adjustment?

In my case, need to add this:
`ENV['FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT'] = '1'`

and inside pilot add this -> itc_provider: YourTeamID

**Comment by aimatme** [comment]
In our case final fix is like (in CI shell script)
`
ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD="true" DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-asc_provider PROVIDER" fastlane pilot upload --verbose ..........`

**Comment by niallwatchorn** [comment]
Any updates on this?

**Comment by msaraac** [comment]
any updates ?

**Comment by Web3Platforms** [comment]
Still getting this issue

**Comment by mdivya-symplr** [comment]
where should we add `itc_provider` information in this task AppStoreRelease@1 ?
Tried adding itc provider in `Additional fastlane arguments`
<img width="817" alt="Screenshot 2022-12-19 at 6 01 59 PM" src="https://user-images.githubusercontent.com/92149473/208426955-372d4cb4-97ce-4cf3-b057-736c3601d1b9.png">

how can we find app `shortName` ?

I have tried adding following environment variables, but nothing worked for me :
DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS = -asc_provider <TeamID>
FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT = 1
ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD = true
