### ISSUE TITLE
Add support for TypeScript in React Native iOS build configurations

### ISSUE THREAD

**Issue by volodymyrpo** [microsoft/appcenter#2489]
**Describe the solution you'd like**
We want to be able to build React Native TypeScript for iOS.

TypeScript support is built into Metro and React Native. This does not require additional support from the App Center. In fact, the React Native Android build configuration works great with TypeScript. In the React Native iOS configuration, there is a special restriction on the use of JS only. We ask that you remove this restriction and allow TypeScript, as we believe that this restriction was added by accident.

**Describe alternatives you've considered**
I contacted support and was told what I am trying to achieve is not possible and I should make the request here.

**Additional context**
We believe that the problem in the following step of React Native iOS build configuration:
```yaml
      - task: CmdLine@2
        displayName: Generate source map
        inputs:
          script: >-
            #!/bin/sh

            INDEX_FILE="index.ios.js"

            if [ -f "index.js" ]; then
              INDEX_FILE="index.js"
            fi


            echo "Found $INDEX_FILE for ReactNative index."


            node --max_old_space_size=8192
            node_modules/react-native/local-cli/cli.js bundle --entry-file
            $INDEX_FILE --platform ios --dev false --reset-cache --bundle-output
            dummy-sourcemap-main.jsbundle --sourcemap-output index.ios.map
          failOnStandardError: false
```
The exact location is here:
```yaml
            INDEX_FILE="index.ios.js"

            if [ -f "index.js" ]; then
              INDEX_FILE="index.js"
            fi
```
So App Center only supports two types of input files for React Native: `index.ios.js` and `index.js`. While all React Native projects support the following list of files for iOS:
- `index.js`
- `index.ts`
- `index.native.js`
- `index.native.ts`
- `index.ios.js`
- `index.ios.ts`

In our case, we use index.ts as the entry file since we use the standard [react-native-template-typescript](https://reactnative.dev/docs/typescript) project template.

Also, React Native allows you to configure the input file for each platform separately. Which is also not taken into account in the existing configuration.

We suggest replacing the configuration with the following:
```yaml
      - task: CmdLine@2
        displayName: Generate source map
        inputs:
          script: >-
            #!/bin/sh

            declare INDEX_FILE
            SUPPORTED_FILES=(
              "${REACT_NATIVE_IOS_ENTRY_FILE}"
              "${REACT_NATIVE_ENTRY_FILE}"
              "index.ios.js"
              "index.ios.ts"
              "index.native.ts"
              "index.native.js"
              "index.js"
              "index.ts"
            );

            for fileName in "${SUPPORTED_FILES[@]}"
            do
              if [ -f "${fileName}" ]; then
               INDEX_FILE="${fileName}"
               break
              fi
            done

            if [ -n "${INDEX_FILE}" ]; then
              echo "Found $INDEX_FILE for ReactNative index."
            else
              echo "Not found index file for ReactNative."
              exit 1
            fi

            node --max_old_space_size=8192
            node_modules/react-native/local-cli/cli.js bundle --entry-file
            $INDEX_FILE --platform ios --dev false --reset-cache --bundle-output
            dummy-sourcemap-main.jsbundle --sourcemap-output index.ios.map
          failOnStandardError: false
```

**Comment by yevgeniusr** [comment]
Same issue here

**Comment by User0111** [comment]
Yes yes yes.

**Comment by WolfyUK** [comment]
Related to https://github.com/microsoft/appcenter/issues/1785
