### ISSUE TITLE
Add QR code to distribution page for easy installation

### ISSUE THREAD

**Issue by caphun** [microsoft/appcenter#249]
**Describe the solution you'd like**
On the public distribution page add a QR code so that if the page is opened in a desktop browser the user can scan the QR code with their mobile to install the ipa/apk

**Describe alternatives you've considered**
Alternative is to copy the public url and  use an online qrcode generator. Not a very good alternative.

**Comment by botatoes** [comment]
Thanks for the suggestion! Will take this into account when we look into improving the overall install experience.

**Comment by neville-nazerane** [comment]
Any progress on this? As of now, I am manually generating QR codes on my readme. This feature would be quite useful for public links.

**Comment by wolfgang-hau-fiduciagad** [comment]
Any progress on this? Also looking for a solution to easily install an app with QR-Code
