### ISSUE TITLE
Choose which simulator IOS version the app will be built on

### ISSUE THREAD

**Issue by maoryadin** [microsoft/appcenter#2494]
I cannot choose which simulator version the app will be built on.

my ios min version is 12, but AppCenter keeps try building on the simulator with ios version 11.4...

I can't find any resource to modify or choose which simulator or iOS version I want.

**Comment by MikhailSuendukov** [comment]
Hi @maoryadin and thanks for reaching us. It looks like you are using the wrong device or device set when you start your tests. You can select a device with the version you need at the first stage of `New test run`.

![Screenshot 2022-12-01 at 15 05 05](https://user-images.githubusercontent.com/110986399/205073018-1d6c2fef-ede6-45f5-a6d2-c1d564d23827.png)

**Comment by MikhailSuendukov** [comment]
Close this issue, please feel to reopen it, in case problem still persist, or you have any questions.
