### ISSUE TITLE
[Feature] add automated UI test for UWP apps

### ISSUE THREAD

**Issue by JanabiSoft** [microsoft/appcenter#25]
**What App Center service does this feature apply to?**
Testing

**Describe the solution you'd like**
add automated UI test for UWP apps.

**Describe alternatives you've considered**
none.

**Comment by Oddj0b** [comment]
Thanks for request @JanabiSoft. As I'm not familiar with the UWP UI Testing scene, is there a specific testing framework you would prefer?

**Comment by JanabiSoft** [comment]
hi @Oddj0b i'm not sure about the cloud but locally can be done with windows application driver and appium
https://medium.com/@yostane/automated-ui-testing-of-a-uwp-app-using-appium-dc10d8df6631

**Comment by Oddj0b** [comment]
@JanabiSoft Thanks for the input, having UWP devices available is only half the work the other half is supporting a testing framework. Getting input from customers is an important step in making the right choice.

**Comment by cosminstirbu** [comment]
Appium already has support for UWP, but unfortunately AppCenter doesn't support the C# Appium client. (as per - https://github.com/Microsoft/appcenter/issues/102)

An alternative would be to add UWP support to Xamarin.UITest.

Either way, currently there is no possibility to write C# UI automated tests that can run on all three platforms: iOS, Android and UWP.

**Comment by rido-min** [comment]
Can you consider the [WinAppDriver](https://github.com/Microsoft/WinAppDriver) ?

**Comment by cosminstirbu** [comment]
I'm not sure I understand the question. WinAppDriver is basically Appium, since it is used by Appium under the hood on UWP.

**Comment by JanabiSoft** [comment]
@cosminstirbu You mentioned earlier that it is not possible to write C# UI automated tests that can run on all three platforms, what about writing 2 test systems one for mobiles and one for windows, is it possible?

**Comment by cosminstirbu** [comment]
Well, right now we do in fact write C# UI automated tests for all three platforms using Appium and the .NET Appium Client.

However, we run the iOS and Android ones on emulators created on Azure Devops hosted macOS Agents and the UWP on a OnPremise Windows 10 Agent.

However, it would be great if we could run the iOS and Android tests on real devices on AppCenter.

Writing two UI tests codebases, one for iOS / Android and one for UWP is not an option for us - too much maintenance overhead.

**Comment by mzhukovs** [comment]
Yes would be fantastic to use Xamarin UI Test for a Xamarin Forms project for all 3: iOS, Android, and UWP - seems logical. Will this be taken on any time soon?

**Comment by JKennedy24** [comment]
Xamarin.UI test can work with UWP.

The Xamarin.Forms team implemented Xamarin.UI test for UWP:
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs

It just hasnt been merged into the official Xamarin.UITest.

The way I see it working is using Xamarin.UITest as the testing framework and WinAppDriver, exactyl how the forms team currently do it:
https://github.com/xamarin/Xamarin.Forms/tree/master/Xamarin.Forms.Core.Windows.UITests

If you want to run on physical deviced attached you can run via an ethenet cable:
https://tomsoderling.github.io/Wired-Debugging-on-Surface/

Be nice if the appcenter team could play around with the idea of supporting UWP automated testing

**Comment by JohnH-FF** [comment]
Any movement on this? As a company we need to decide if we will go 'all-in' on Xamarin.UITest, but we will need test coverage in iOS, Android **and** UWP.

**Comment by AvaJV** [comment]
Any update on this?
Is this expected to be in soon or are there any alternatives?

**Comment by winnieli1** [comment]
Hi @AvaJV no updates yet but it's something we're considering. in the meantime, we recommend trying out WinAppDriver: https://github.com/microsoft/WinAppDriver. Happy to connect you to that team if you'd like to learn more. 

Thanks!

**Comment by JKennedy24** [comment]
@winnieli1  I've got UWP UI tests (using the WinAppDriver and the Xamarin.Forms implementation of the UWP wrapper https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs)

but I haven't found a way to automate them using Visual Studio Online.

Even following this: https://github.com/microsoft/WinAppDriver/wiki/WinAppDriver-in-CI-with-Azure-Pipelines

Still can't get them to automate

**Comment by hassanuz** [comment]
Hi @JKennedy24,

What kind of errors are you running into? Are you using a public "MS-hosted" agent or a private one?

**Comment by jmegner** [comment]
> The Xamarin.Forms team implemented Xamarin.UI test for UWP:
> https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs
> 
> It just hasnt been merged into the official Xamarin.UITest.

Is there an issue or pull request that I can follow so I can be alerted when the merge completes?
