### ISSUE TITLE
TestFlight upload fails

### ISSUE THREAD

**Issue by kseniya-hydric** [Microsoft/appcenter#250]
Builds to TestFlight always fail with error: "SDK Version Issue. This app was built with the iOS 12.0 SDK. All iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later" I think AppCenter need to update their xCode as this version is now required to upload to App Store.

**Comment by rhysdavies1994** [comment]
I'm getting this same error. I can see xcode 10.1 as an option when creating a new React Native iOS project, but when I select my package.json, I can only select up to 9.4.1.

Therefore my current app is stuck on 9.4.1 and I can't release to app store

**Comment by rhysdavies1994** [comment]
**UPDATE**

This should help If you are getting this issue where you are unable to select Xcode 10.1 as a React Native project.

I contacted App Server support and they responded with:

```Please note that Xcode 10 support for React Native apps is only available for React Native 0.56+. If you are using RN 0.56+ you should be able to select Xcode 10 from the build configuration in App Center.```

So ensure RN is 0.56 or higher and you should be able to select Xcode 10.1 to build for iOS 12.1 SDK

**Comment by Oddj0b** [comment]
@kseniya-hydric @rhysdavies1994 Have you tried building on a newer Xcode and uploading?

**Comment by kseniya-hydric** [comment]
The option for 10.1 was not appearing for me the other day but it is now! Thanks.
