### ISSUE TITLE
Support MacCatalyst in .NET MAUI apps

### ISSUE THREAD

**Issue by spatialdude** [microsoft/appcenter#2500]
**Describe the solution you'd like**
The .NET `AppCenter.Start()` crashes with a `System.TypeInitializationException` in .NET MAUI apps targetting MacCatalyst.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/7235583/206049118-b9edee36-65cc-40a9-9bec-f6f1bdff3705.png">

Please support MacCatalyst :smile:

**Describe alternatives you've considered**
There is no workaround other than to not use App Center analytics or crash reporting for .NET MAUI apps running on MacCatalyst.

**Additional context**
Works very nicely with Windows, iOS and Android.

Attached is a simple app that can reproduce the crash behaviour on macOS. This is simply a .NET MAUI app created from the template in Visual Studio with the App Center packages and initialisation added to the App constructor.

[AlohaAppCenter.zip](https://github.com/microsoft/appcenter/files/10171452/AlohaAppCenter.zip)

**Comment by spatialdude** [comment]
https://github.com/microsoft/appcenter-sdk-dotnet/issues/1702

**Comment by DmitriyKirakosyan** [comment]
Closing as duplicate of https://github.com/microsoft/appcenter-sdk-dotnet/issues/1702.
