### ISSUE TITLE
[Feature] Request React Native New Architecture

### ISSUE THREAD

**Issue by nicolascavallin** [microsoft/appcenter#2502]
**Describe the solution you'd like**

In the current AppCenter service, it's impossible to build React Native Apps with the New Architecture enabled.

In terms of Android, if I enable the new arch, it takes more than 60 minutes to make the build, and automatically it's stopped because 60 min is the maximum time in the paid tier (30 mins in the case of the free tier).

In iOS is impossible to run the `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install` command because the `pod-install` step is called automatically by the AppCenter pipeline and it's not possible to modify it.

**Describe alternatives you've considered**

- Increase the maximum build time.
- Allow to modify the `pod-install` step.

**Comment by CamBowes** [comment]
+1

**Comment by selvamariappant2s** [comment]
+1

**Comment by CamBowes** [comment]
+1
