### ISSUE TITLE
Can we get confirmation of end of life or end of support please ?

### ISSUE THREAD

**Issue by stephenhauck** [microsoft/appcenter#2505]
@wisdeom , @jamesmontemagno , @maddymontaquila , @davidortinau, @jfversluis , @jrahma, @mphill, @IeuanWalker, @BenEdelstain, @FreakyAli, @MobileDev327, @varyamereon, @dgerding, @Transatranticism, @dmccolloughOneGas, @Bowman74, @Brosten, @trevortirrell

I was referred to this repo by @thewulf7 

Support through the AppCenter portal has historically not yielded results except in confirming a feature is non functional.

If there is no interest in supporting MAUI and AppCenter PLEASE positively indicate such in writing so we can inform customers and management.

We as developers and supporters of XAMARIN and MAUI (some of us since MonoTouch) are being forced to move to other less mature toolsets like Flutter because management sees them making forward progress while it seems  the Xamarin toolchain is degrading and declining and we have no ammunition with which to dispel those perceptions.

it seems people are more interested in "where" problems are posted rather than solving them ...
https://github.com/dotnet/maui/discussions/3333

**Comment by Bowman74** [comment]
If I were to take an educated guess at this I’d look at the history of AppCenter and Microsoft’s other products. AppCenter was one of the last major products created by the Xamarin team while they were still independent of Microsoft.

Outside of the mobile test suit there are a lot of overlaps with other Microsoft offerings. Even at the time of it’s release there was perhaps a 60% overlap with Azure DevOps (VSTS at the time). One of the major areas of overlap was in build services. Azure DevOps is much more configurable while AppCenter is far simpler for easier build scenarios.

At some point something had to give. They have been supporting multiple build services for over five years which is where I think the normal pain point happens with this sort of redundancy.

It would be nice if Microsoft ended the lack of information and announced a roadmap here. No one likes uncertainty. Bit if we are wondering if Microsoft provides build services for .Net MAUI today, I’d say the answer is yes. They do in Azure DevOps. If I were to take a guess as to the future of .Net MAUI build services, I’d give the same answer Azure DevOps. If I were to go a step further and suppose that .Net MAUI build support came to AppCenter, my answer would still remain the same even then.

**Comment by stephenhauck** [comment]
@DmitriyKirakosyan how do we get a tag added that is related to "answer" or "fix" 

I gotta move to something that works and ISN'T Azure ....

**Comment by stephenhauck** [comment]
@davidortinau I asked for confirmation here and no one will answer or address the issue ...

**Comment by varemenos** [comment]
It doesn't seem like they are allowed to give an answer. I'd imagine it's extremely frustrating for them as well. We've decided to move on from Appcenter and in general from Microsoft's services because of this, the lack of communication is really unnerving.

**Comment by somoreingold** [comment]
I think @jfversluis all but spells out the future of AppCenter MAUI support (especially build support) in this video: https://www.youtube.com/watch?v=Bz1XLecJlXc 

Build support isn't ever coming to AppCenter IMHO. Was I confused when I saw stuff like ReactNative builds still being supported but not Microsoft's own MAUI? Yes. 

But I don't claim to understand any of the decision-making of MS. All we can do is evaluate pros/cons/risks of continuing with MAUI based on the signals and track record that we can see from the outside...I personally think MAUI has beautiful potential, but I can understand how some developers are receiving opposite signals and jumping ship given the lack of public responses to stuff like this. It's always tough when management steers you in another direction despite how much you like a platform.

**Comment by stephenhauck** [comment]
@wisdeom , @jamesmontemagno , @maddymontaquila , @davidortinau, @jfversluis 

Yeah .. I'm still using it when I can for stuff but the lack of response to serious issues with MAUI is telling me not to bet heavily on it.

It seems they have a skeleton crew on MAUI and AppCenter and all their effort is being put into tools like Blazor ...

Just not interested in Blazor or Azure in any way .. lots of people aren't .. that's why Flutter is growing so fast ..

I'm playing with https://codemagic.io/start/ because it does Flutter and MAUI ... 

Now I just need a crashlytics service like AppCenter for Flutter .. no NOT Firebase !

**Comment by mphill** [comment]
@stephenhauck sentry.io is good.
