### ISSUE TITLE
org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction

### ISSUE THREAD

**Issue by ranshine** [microsoft/appcenter#2508]
I am trying to generate release build through appcenter but in local setup i am able to generate android apk.
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 14m 52s

**Comment by MikhailSuendukov** [comment]
Hi @ranshine  and thanks for contacting us, could you please tell me how exactly are you trying to generate the build?

**Comment by Oleg-Karoza** [comment]
@ranshine please contact our customer support with this issue.
