### ISSUE TITLE
App center seems do not support iphone 5s with ios 12.2

### ISSUE THREAD

**Issue by AlphaWong** [microsoft/appcenter#251]
# Story
I would like to install the Application in iPhone 5s ( iOS 12.2 ) via app center
## iPhone 5s
![img](https://media.giphy.com/media/27uhCEcwZNxBIAilxg/giphy.gif)

## iPhone X
![Imgur](https://media.giphy.com/media/BMew8KNkiLYw4FwtyX/giphy.gif)

# Expected
iPhone 5s should able to download the ipa like iPhoneX

# Actual
iPhone 5s do not have download button

**Comment by botatoes** [comment]
Hi, a fix for this was deployed yesterday. Are you still experiencing the issue? @AlphaWong

**Comment by AlphaWong** [comment]
@botatoes 
Thx, I am currently sick leave. May I reply u at 8APR2019 HKT?:smile:

**Comment by AlphaWong** [comment]
> Hi, a fix for this was deployed yesterday. Are you still experiencing the issue? @AlphaWong

@botatoes 
Same result.

**Comment by AlphaWong** [comment]
iPhoneXs iOS 12.0 and IPhoneXR iOS 12.0 missing button also

**Comment by AlphaWong** [comment]
iphone 7 12.1.2 missing button also

**Comment by botatoes** [comment]
Hi, sorry for the late reply @AlphaWong, this issue got lost in my list of reponses. Can you open an intercom ticket if you are still experiencing this?
