### ISSUE TITLE
AppCenter Xamarin iOS app is not getting installed.

### ISSUE THREAD

**Issue by SravanthiKare** [microsoft/appcenter#2510]
After we started using MacOS 12 azure hosted pipelines and upgraded to visual studio 2022. Application is not getting installed. We tried archiving from our developer machines and installing on devices. It works perfectly. But only if we do it from AzureDevOps pipelines and AppCenter, iOS app is not getting installed.

Using below:
Visual Studio for Mac 2022
Azure DevOps - MacOS 12 hosted piepline
AppCenter

Below are the tasks:
1. Install App Certificate
2. Install Apple Provisioning Profile
3. Xamarin iOS - Build

We have verified Apple certificate and provisioning profiles are valid till April 2023. Also, the same code build using macOS 11 hosted pipelines and visual studio 2019 dont have this issue. Please help as we couldnt find a way to solve this issue.
#866
https://github.com/microsoft/appcenter/issues/866

**Comment by SravanthiKare** [comment]
@DmitriyKirakosyan 

Can you please let me know if you have any update on this issue?

**Comment by lucen-ms** [comment]
@SravanthiKare please contact our customer support with this issue.
