### ISSUE TITLE
Repl failed with exception: Table setup of type ICSharpCode.NRefactory.TypeSystem.CecilLoader+DummyAssemblyResolver failed

### ISSUE THREAD

**Issue by Sam-IExpress** [microsoft/appcenter#2514]
Environment: 
Visual Studio For Mac version 17.4.3
Xamarin.UITest version 4.1.0

When I run app.Repl() for a Xamarin.iOS app, the following exception appears on the terminal.
`Execution failed with exception: System.TypeLoadException: VTable setup of type ICSharpCode.NRefactory.TypeSystem.CecilLoader+DummyAssemblyResolver failed
  at Xamarin.UITest.Repl.Repl.NRefactoryCompletionEngine..ctor () [0x00087] in <6c3cd503f8d3482f88076fcdd083c9d2>:0 
  at Xamarin.UITest.Repl.Repl.ReplFacade..ctor () [0x00012] in <6c3cd503f8d3482f88076fcdd083c9d2>:0 
  at Xamarin.UITest.Repl.Program.Main (System.String[] args) [0x0008c] in <6c3cd503f8d3482f88076fcdd083c9d2>:0 
Press any key to exit.`

<img width="583" alt="image" src="https://user-images.githubusercontent.com/98374338/215386913-f4863cda-6dd7-49ae-80f5-daf0a7616b81.png">

**Comment by AnatolyPristensky** [comment]
Hello @Sam-IExpress, this is a known issue, that described in release notes of XamarinUITest - https://www.nuget.org/packages/Xamarin.UITest#release-body-tab

The fix of this issue is in progress.

**Comment by evgenyvalavin** [comment]
Still exists in version 4.1.2

**Comment by evgenyvalavin** [comment]
> 4.1.3

There's no 4.1.3 for now
