### ISSUE TITLE
'Xamarin' could not be found after upgrading Xamarin.UITest to 4.x

### ISSUE THREAD

**Issue by Sam-IExpress** [microsoft/appcenter#2515]
It works fine on 3.x.
After upgrading the nuget package to 4.0.1 or 4.1.0, namespaces 'Xamarin' could not be found.

I tried it on both windows and mac. Please help. 

![image](https://user-images.githubusercontent.com/98374338/215932394-666cc2de-1e90-4b20-8eb6-a4c6649c5091.png)

**Comment by Sam-IExpress** [comment]
never mind, just needed to change the target framework to 4.7.2

**Comment by Fariz-fx** [comment]
> never mind, just needed to change the target framework to 4.7.2

Can you elaborate how you resolved this issue by changing to 4.7.2
