### ISSUE TITLE
Trimming support

### ISSUE THREAD

**Issue by HavenDV** [microsoft/appcenter#2517]
**Describe the solution you'd like**
When trying to publish an application with `<PublishTrimmed>true</PublishTrimmed>`, this library produces the following:
```
  Microsoft.AppCenter.dll: [IL2104] Assembly 'Microsoft.AppCenter' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries
```
I guess it doesn't support net6.0/net7.0 trimming - https://aka.ms/dotnet-illink/libraries

**Describe alternatives you've considered**

**Additional context**

**Comment by MikhailSuendukov** [comment]
Hello @HavenDV and thanks for contacting us, is this issue blocking you or is it just a suggestion?

**Comment by HavenDV** [comment]
Hello @MikhailSuendukov. It's just a suggestion. I'm not sure if the current way of initialization is compatible with Trimming

**Comment by IlyaBausovAkvelon** [comment]
@HavenDV, Thank you for reporting one again. I will create a feature request for that.

**Comment by JasonWei512** [comment]
This is a blocking issue for me.

I am using App Center SDK in a WinUI 3 project.

If I disable .NET IL trimming, everything works fine. In Fiddler I can see my app sending network request to App Center.

If I enable trimming and set `TrimMode` to `partial`, I can't see any network traffic to app center in Fiddler. When the app tracks an event with App Center SDK, I can see `System.MissingMethodException” in System.Private.CoreLib.dll` in Visual Studio's debugger output.

Could this be related to `Newtonsoft.Json`?

**Comment by JasonWei512** [comment]
Any news?

**Comment by JasonWei512** [comment]
Ping

**Comment by IlyaBausovAkvelon** [comment]
@JasonWei512 we have issue on the board but yet hadn't started working on it due to priorities.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Comment by tipa** [comment]
Very disappointing. There is about zero progress in improving the AppCenter SDK. Other solutions are [going through the effort](https://github.com/getsentry/sentry-dotnet/pull/2732). Will strongly consider switching...

**Comment by JasonWei512** [comment]
@tipa 
How is your experience with [Sentry](https://sentry.io/) and WinUI 3? 
I am considering migrating to Sentry too if it supports trimming.
