### ISSUE TITLE
Connecting to Self-Hosted Bitbucket

### ISSUE THREAD

**Issue by Cubix1** [microsoft/appcenter#2519]
**Describe the solution you'd like**
I would like to connect the App Center to a self-hosted Bitbucket account.

**Additional context**
A request was already attempted with #2411 and was closed. This is a second attempt.  
Connecting to Self-Hosted bitbucket Instances.

**Comment by wisdeom** [comment]
Hi @cubix1 Thank you for reaching out and sharing you feedback. Unfortunately, a self-hosted Bitbucket support won't be included in the coming roadmap or in the near future. However, we'll reopen this when we have something to share with you later. Thanks again!
