### ISSUE TITLE
Visual Studio for Mac 2022 - Debugging UI Tests using Xamarin.UITest 

### ISSUE THREAD

**Issue by seangriffin2** [microsoft/appcenter#2523]
Is Visual Studio for Mac 2022 capable of debugging UI Tests using Xamarin.UITest?

Visual Studio For Mac 2019 had the "Test Apps" Configuration option accessible from the Unit Test Pane

[https://learn.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/xamarin-forms?tabs=macos#writing-uitests](url)

<img width="223" alt="Learn More" src="https://user-images.githubusercontent.com/19562538/223176532-162a6c9c-c809-418b-a4ee-4f88a921e464.png">

However, Visual Studio for Mac 2022 does not seem to have the same feature. Is there is another approach for debugging UI Tests from Visual Studio for Mac using Xamarin.UITest...

**Comment by MikhailSuendukov** [comment]
Yes, Visual Studio for Mac 2022 has the ability to run Xamarin.UITests. This can be done using the Tests tab.

![Screenshot 2023-03-13 at 13 46 12](https://user-images.githubusercontent.com/110986399/224705906-b2617c30-bf1b-4763-82a6-e072219f766c.png)

![Screenshot 2023-03-13 at 13 57 03](https://user-images.githubusercontent.com/110986399/224708323-b5181957-a3bc-4b43-b995-33aa596aff34.png)

![Screenshot 2023-03-13 at 13 55 58](https://user-images.githubusercontent.com/110986399/224708266-0fa2bc87-aecb-42e7-a5d6-f5f33f35866b.png)

I will close this issue now and if you have any further questions feel free to reopen this issue.
