### ISSUE TITLE
Xamarin.UITest - UI Test fails to execute - when debugging from Visual Studio for Mac 8.10.25 (build 2)

### ISSUE THREAD

**Issue by seangriffin2** [microsoft/appcenter#2524]
### **Environment Info**
MacOS Monterey 12.6.3

Visual Studio for Mac - 8.10.25 (build 2)

Xamarin.UITest - 4.1.2

Target Framework: .NET Framework 4.6.2

Physical Devices for debugging UI Tests:
- iPhone6s - iOS 14.8.1
- Pixel 5 - Android 13

### **Issue**
When debugging a UI Test from Visual Studio for Mac 8.10.25 (build 2) against physical Android and iOS devices:

**UITest fails to launch- seemingly without any error message** 
- Android behavior: Visual Studio will constantly show as "running" without any output
- iOS Behavior: UI Test run will stop as if the user clicked the "stop" button

It almost seems as if the NUnit test was simply never executed
To the best of my knowledge, this failure to executed was immediately after updating to Visual Studio 8.10.25 (build 2)

**Comment by DmitriyKirakosyan** [comment]
Hi @seangriffin2 , thank you for reaching out!
May I also know your NUnit version?

Have you tried to upgrade VS to 2022?

If upgrading to VS 2022 doesn't help, may I ask you to create a new test project with a 1-2 tests and try to reproduce the issue on it?

**Comment by Slackwise** [comment]
My team recently updated our Xamarin.UITest nuget package from `3.2.9` to `4.1.2`, and our tests on AppCenter spin endlessly on startup, timing out after 60 minutes. Seeing as AppCenter runs macOS VMs, I presume this is related.

**Comment by MikhailSuendukov** [comment]
Could you please provide a small demo project that reproduces this behavior?

**Comment by MikhailSuendukov** [comment]
Hi do you have any progress with this problem? If it is still present, please contact [AppCenter support](https://learn.microsoft.com/en-us/appcenter/help)
