### ISSUE TITLE
Dev Tunnel or Virtual USB

### ISSUE THREAD

**Issue by matiasreina** [microsoft/appcenter#2528]
**Describe the solution you'd like**
I want to get some valuable information from the device like it where connected to my computer. I need to run ADB in android or USBMUX in iOS.

**Describe alternatives you've considered**
In others providers (like AWS device Farm or perfecto) I have this kind of solutions.

**Additional context**
I want to use this tool in MS App Center: www.apptim.com

**Comment by MikhailSuendukov** [comment]
Hi @matiasreina  and thanks for contacting us. Could you please describe in more detail what specific functionality you are talking about?

**Comment by matiasreina** [comment]
Hi! thanks for your reply!
I want a feature that enables developers to run ADB commands in Android devices. That enables a wide range of possibilities to debug device status and apps, for example getting device-performance stats, filtering logcat and a wide range of possibilities. Here you have technical documentation for this feature in perfecto which is a wrapper built on top of open-source technology: https://help.perfecto.io/perfecto-help/content/perfecto/advanced/devtunnel___debug_on_real_perfecto_devices.htm

**Comment by MikhailSuendukov** [comment]
Your request is very similar to [this](https://github.com/microsoft/appcenter/issues/2463) feature request if I understand you correctly.

**Comment by mellimatias** [comment]
It is in the same way/need

**Comment by matiasreina** [comment]
It is in the same way/need

**Comment by MikhailSuendukov** [comment]
Thank you very much for your request, but unfortunately there is no ETA for this feature request yet.

**Comment by matiasreina** [comment]
Thanks for your answer. 
Is there any other way to work with Microsoft as a partner to develop this kind of integration?
[This](https://partner.microsoft.com/en-GB/marketing/azure-isv-technology-partners) program, related to ISV Technology Partners is focused on sales/management, is there any way to talk first about these technical needs?

Any help is welcome and thanks again!

**Comment by MikhailSuendukov** [comment]
Unfortunately, you do not have the opportunity to somehow help us in the development of this feature, because the repositories responsible for this functionality are private. Thank you for your willingness to help us.

**Comment by mellimatias** [comment]
Hello

Do you have this in your 2024 roadmap? Or any alternative?

**Comment by lucen-ms** [comment]
We don't have this feature on 2024 roadmap.

**Comment by mellimatias** [comment]
> We don't have this feature on 2024 roadmap.

thanks for your reply
