### ISSUE TITLE
App center is down

### ISSUE THREAD

**Issue by ibrahim7elmasry** [microsoft/appcenter#2535]
App center website is down, first codePush servers were down many times and now app center is down, is there any fix to those issues

**Comment by iantasker** [comment]
Its been down for at least 5 hours.

**Comment by timvandenhof** [comment]
They are/were down quite a while (17.5 hours) and it seems it's still intermittend, you can check their status page at: https://status.appcenter.ms/

> Apr 03, 2023 - 21:47 UTC
> Investigating - We apologize for the inconvenience caused as our Appcenter portal is currently down. Our team is investigating the issue and we'll update you as soon as possible. Thank you for your understanding.

> Apr 04, 2023 - 15:14 UTC
> Monitoring - We have taken steps to mitigate the issue, but the problem is not fully resolved and may reoccur. As of now, our portal is accessible and we're actively monitoring the situation. Thank you for your patience and understanding.

**Comment by craigwi** [comment]
Appcenter is down again, but their status page does not indicate there is a problem.

**Comment by sanjidbillah** [comment]
It is down again.

**Comment by MikhailSuendukov** [comment]
Hi, and thanks for reaching us out. For more insight into potential issues, I recommend visiting the [AppCenter Status](https://status.appcenter.ms/) page, where you can identify any existing problems. Additionally, for queries regarding crashes or other concerns, feel free to reach out to [AppCenter support](https://learn.microsoft.com/en-us/appcenter/help) team for prompt assistance.
