### ISSUE TITLE
Need script to add configutation for branch.io in androidmenfifiest file as we have multiple app with same code base

### ISSUE THREAD

**Issue by rajscet** [microsoft/appcenter#2543]
<meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_kaFuWw8WvY7yn1d9yYiP8gokwqjV0Sw" />
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_hlxrWC5Zx16DkYmWu4AHiimdqugRYMr" />
        <meta-data android:name="io.branch.sdk.TestMode" android:value="false" /> 

   
            <intent-filter>
                
                <data android:scheme="yourapp" android:host="open" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>

            
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="example.app.link" />
                
                <data android:scheme="https" android:host="example-alternate.app.link" />
            </intent-filter>

**Comment by aleksandr-dorofeev** [comment]
Hi @rajscet,  thanks for reaching us! 
Could you describe the request in more detail?

**Comment by AnatolyPristensky** [comment]
@rajscet, we haven't heard from you for a while, so I'm closing this issue. Please feel free to reopen it in case of new information.
