### ISSUE TITLE
Raise rate limit when creating apps via script

### ISSUE THREAD

**Issue by sarn0ld** [microsoft/appcenter#2545]
My company usually creates 3-6 apps per customer for different Platforms(Android/iOS) and different staging environments (Alpha, Beta, Production). We do this via a script that uses the AppCenter rest api.

In the last month you have added a rate limit. According to the docs we can only create 5 apps per day.
Additionally, (I did not find that in the docs, but it was stated by your support team) there is also a 5-minutes-limit: One can only create 1 app per 5 minutes.

This is an annoying blocker for us when we are setting up apps for new customers.

Can we work around this limit somehow? Or can you remove the 5 minutes check at all?

(Additionally: When I try to create more than one app via the UI I do not even get an error message about what is going wrong. I suggest to implement a specific text that informs about the rate limit if you can not abolish it.)

**Comment by Oleg-Karoza** [comment]
Hello @sarn0ld, thanks for reporting about it!
I will keep this issue updated and share details about changes in the limits
