### ISSUE TITLE
Feature Request: Add Ability to Customize Git Clone Function (Git Shallow Clone)

### ISSUE THREAD

**Issue by abgaryanharutyun** [microsoft/appcenter#2549]
**Describe the solution you'd like**
My repository is very old and large, so when I clone it using Git, it takes a lot of time. Additionally, the build process itself takes over 60 minutes. Due to this limitation, my builds fail every time because AppCenter has a 60-minute restriction per deployment.

**Describe alternatives you've considered**
That's why I'm suggesting adding the ability to use a custom Git clone function, such as supporting shallow cloning with the command `git clone --depth=1`. This would help optimize the cloning process and reduce the time it takes to clone the repository."

**Additional context**
Currently, I'm using Bitrise for my CI/CD process, and I'm using the same Git clone method. However, I want to switch to AppCenter for my CI/CD, but I'm facing difficulties because the Git clone operation takes a significant amount of time.

**Comment by lucen-ms** [comment]
As this is a feature request, please consider using Azure DevOps for your builds where you have bigger control of your build process.
