### ISSUE TITLE
Unable to distribute the cordova apps to appcenter

### ISSUE THREAD

**Issue by lavanyak10** [microsoft/appcenter#255]
Unable to distribute the cordova apps to appcenter. Getting error "release binary file uploading failed: HTTP 422 Unprocessable Entity". App uploading without code push plugin. What am I missing? I tried appcenter-cli and manual upload to appcenter.

**Comment by botatoes** [comment]
Thanks for letting us know. I created a bug and is in the backlog for the CodePush team.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
