### ISSUE TITLE
Raise rate limit for creating apps using script or manually

### ISSUE THREAD

**Issue by ygchun** [microsoft/appcenter#2552]
We recently noticed that there is a hard limit on the number of apps that can be created per hour and per day. We typically create around 40-60 apps in App Center for each Application/Title we are working on and this delays a huge portion of our working process. If we were to have multiple Applications/Titles that require App Center apps it could potentially take us a week before we could have all the App Center apps created. 

Could we increase the rate limit for the amount of apps we can create? The current limits that are in place hinders our teams from utilizing App Center and wanted to see if the rate limit be increase.

**Comment by lucen-ms** [comment]
We will not increase limits for creating applications. If you need more applications at once, I recommend reusing previously created applications.
