### ISSUE TITLE
Support Android Test Orchestrator

### ISSUE THREAD

**Issue by ynsok** [microsoft/appcenter#2553]
**Describe the solution you'd like**
Give support for [Android Test Orchestrator](https://developer.android.com/training/testing/instrumented-tests/androidx-test-libraries/runner#use-android). 

**Additional context**
https://github.com/microsoft/appcenter/issues/1208

**Comment by lucen-ms** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
