### ISSUE TITLE
Support Android Source Maps for React Native apps

### ISSUE THREAD

**Issue by daniel-parlapan** [microsoft/appcenter#2561]
**Describe the solution you'd like**
I would like to see useful crash logs for Android React native projects

**Describe alternatives you've considered**
Different products. Sentry etc. 

**Additional context**
The initial feature request was https://github.com/microsoft/appcenter-sdk-react-native/issues/208

I was initiated in 2019 and we still have the note in the documentation stating this is not supported. 
The ticket had significant tracking along the time but no allocation from the team. 

Can we please have this prioritised?

**Comment by DmitriyKirakosyan** [comment]
@daniel-parlapan , thank you for bumping this feature request. I've reopened the https://github.com/microsoft/appcenter/issues/75, so closing this one.
