### ISSUE TITLE
Update appium server to version 2

### ISSUE THREAD

**Issue by pramodKarande** [microsoft/appcenter#2564]
Hi Team,
Appium 2 has been available for more than a few months at this point.
Is it planned to update Appium 1.22 to Appium 2?
if it is not possible to remove v1.22, at least allow some settings/flags to select appium 2 for users who want to use the latest version.

**Comment by IlyaBausovAkvelon** [comment]
@pramodKarande Hi there!
We need to discuss it with the team. I will write back when we have decision on that.

**Comment by lucen-ms** [comment]
Hi @pramodKarande!
We don't have concrete plans for upgrading to Appium 2 at this point in time, but we may decide to do that later.

**Comment by lucen-ms** [comment]
As we do not have plans to add support for Appium 2 in the next year, I close the issue.
