### ISSUE TITLE
It will delete release after uploading automatically

### ISSUE THREAD

**Issue by davidch2021** [microsoft/appcenter#2566]
I know it is wrong to commit this request here, I am sorry, but I don't know where should I commit. Currently, our appcenter will delete release after uploading automatically. please see https://appcenter.ms/orgs/Whispers/apps/Whispers_CN_Dev-1/distribute/releases?top=false, 1040---1043 had been deleted automatically. Meantime, I had upload some release to this link, for example, 1045---*, they are all losed.

**Comment by MikhailSuendukov** [comment]
Hi @davidch2021 and thanks for reaching us out.  Please contact [AppCenter support](https://learn.microsoft.com/en-us/appcenter/help) with this question. I close this issue, but if you still have some questions, feel free to reopen it.
