### ISSUE TITLE
Versions filter menu in Analytics section is sorted in random order

### ISSUE THREAD

**Issue by gaspesla** [microsoft/appcenter#259]
**What App Center service does this affect?**
Website

**Describe the bug**
The dropdown menu of app versions in the Analytics section is in random (incorrect) order.  Note that the version filter in the Diagnostic section is sorted correctly.

**To Reproduce**
1) Go to Analytics and view the VERSIONS Dropdown
2) See completely random order  of versos.

**Expected behavior**
1) Versions are ordered in ascending or descending order, and match the order in the Diagnostic section.

**Screenshots**
Analytics (random):
<img width="219" alt="image" src="https://user-images.githubusercontent.com/470563/55346509-af978280-5480-11e9-9f48-04b9c44a32f1.png">
Diagnostics (correct):
<img width="216" alt="image" src="https://user-images.githubusercontent.com/470563/55346547-c76f0680-5480-11e9-8315-e5edc0476f33.png">

**Desktop (please complete the following information):**
  macOS 10.14.4, Safari 12.1

**Comment by hamswan** [comment]
We allow custom formats, however the use of version number in this case with a combination of numbers and letters has created this order. 
We recommend to use numbers , and if done in that manner, we can guarantee the right sorting.

**Comment by gaspesla** [comment]
What order is it in? Look at the top screenshot.

**Comment by hamswan** [comment]
From the screenshot I see that for Analytics - I see versions like 3.0.2a1, 3.1b1a etc which is throwing the order off, but for diagnostics even though you are using combination of letter and number it is not the sample apples to apples comparison as I do not see the same 3.1.b1a etc versions used.

**Comment by yoannchaudet** [comment]
To clarify, what's not a proper [semantic version](https://semver.org/) is not guaranteed to be sorted properly. Closing.
