### ISSUE TITLE
Add support for XCode 14.3.1 and XCode 15

### ISSUE THREAD

**Issue by cjrvdev** [microsoft/appcenter#2597]
**Describe the solution you'd like**
Add more recent xamarin iOS versions and support newer XCode versions

**Describe alternatives you've considered**
There is no alternative

**Additional context**
My project uses libraries which do not work under XCode 14.2 anymore and the application crashes if built on appcenter using these versions. As there arent any newer versions available Im forced to manually release new versions using my Mac which defeats the purpose of paying for AppCenter...

**Comment by spsaucier** [comment]
This is preventing us from being able to deploy to iOS at all now.

<img width="640" alt="Screenshot 2023-11-02 at 16 09 25" src="https://github.com/microsoft/appcenter/assets/596143/535a7221-1da0-44bf-a4ea-c7b90d21ddba">

**Comment by rwalker-bluebeck** [comment]
+1 for this. I have a project that needs a newer version of Xcode to build/deploy.

**Comment by cjrvdev** [comment]
Support told me they would upgrade this the first week of december but that is both too late and with no guarantee that it will happen like that.. Seriously we are paying for a service which doesnt care at all anymore

**Comment by spsaucier** [comment]
It has updated to 15.0.1 for me.

**Comment by cjrvdev** [comment]
> It has updated to 15.0.1 for me.

Native right?
Mine is Xamarin iOS, so unfortunaltely not for us yet
