### ISSUE TITLE
Unity Windows standalone support

### ISSUE THREAD

**Issue by windeye** [microsoft/appcenter#2598]
Hi:
    I I used AppCenter in my Unity project, then export data to ApplicationInsights. But I can only get Android build target's data, Windows platform doesn't work.  Does appcenter  support that or are there any ways for me to obtain data from the Windows platform?

Thanks,
Xu

**Comment by DmitriyKirakosyan** [comment]
@windeye , App Center Unity SDK supports iOS, Android and UWP. See [Get Started with Unity](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/unity).
