### ISSUE TITLE
[Feature] Trigger new builds only upon commits to certain folders within repo 

### ISSUE THREAD

**Issue by vpavlushkov** [microsoft/appcenter#26]
**What App Center service does this feature apply to?**
This is a feature for git/GitHub integration that would provide more flexibility in build-trigger configurations. I would consider it to be a standard CI feature but apparently App Center is still missing its implementation.

**Describe the solution you'd like**
When adding an integration to a repository, it should be possible to specify the updates in which folders within the repository should trigger a new build and which not. The configuration should be done in a form of a white-list/black-list (include/exclude) filled with comma-separated folder names. Wild-cards (*) should be available as well.

For every code commit to the build repository, the system would check if there is at least one file from a white-listed folder or at least one file that is not from a black-listed folder. If such a file found, the new build will be started; otherwise the code commit would be ignored as irrelevant to the binary.

**Describe alternatives you've considered**
Alternative solution would be to separate the code into two repositories--one for the build and one for auxiliary materials--but that introduces additional maintenance overhead. Current setup triggers a new build for every documentation update within the repo, which can potentially cause a queue of useless builds and slow down the development process. 

**Additional context**

**Comment by patniko** [comment]
Thanks for the feature request! Path filters are something we use ourselves on a daily basis. We'll continue to track interest on this one.

**Comment by vpavlushkov** [comment]
I understand that the feature is quite clear and there is not much to discuss about it, but closing it due to inactivity sounds like a wrong call to me. I'd rather have it implemented. 😉

**Comment by ranterle** [comment]
@vpavlushkov Thanks for reminding us about this. While this is currently not on our immediate roadmap, how important is a fully customizable path filter setting for the build configuration to you, rather than say - a pre-defined path filter based on the folder in your repository where we found your project?

**Comment by vpavlushkov** [comment]
@ranterle "importance" is a relative term. 😉 

We can certainly survive without that feature as it only causes extra build time but no real harm. Even if App Center starts a build which is totally redundant, one can cancel it manually. Hence, I'd say it is "nice to have" feature. However, I am so used to have this feature in different CI servers that not having this basic feature is odd.

I would also presume the complexity of implementing this feature is pretty small. Why would not we add it to the queue, without adding it to a certain milestone? Then somebody could pick it up while being free between bigger tasks.

**Comment by ranterle** [comment]
Agree, this can definitely be improved so we are better supporting mono repo scenarios etc.
In terms of putting this on the roadmap there is definitely multiple factors that we look for, effort required is one thing, but also customer interest in general and how the solution we can think of plays with other items on our roadmap and our existing feature set.

It'd be great to get more clarity on the feature set you all would like to see us support. To get a better understanding of this (of course, not making any promises about an ETA or exact feature set):

- React with 🎉if you would be happy with a solution where we allow you to restrict builds to only be triggered when a commit is within the path of the project that we found in your repo, 
- React with 🚀 if you need an option to configure path filters matching certain patterns, i.e. using wildcards, per build configuration

**Comment by rnystrom** [comment]
We have iOS, Android, and documentation all in one repo. Kicking off multiple builds for a `README.md` seems wasteful and noisy. We could split the repo into 3, but that adds a bit more project-mgmt overhead.

**Comment by anthonyhumphreys** [comment]
Hi, on a similar note I've just opened an Issue here: https://github.com/microsoft/appcenter/issues/930

This issue makes me think about the situation from a different angle though. It would be amazing if I could specify that only changes to the android/* or ios/* for example would trigger a native build. If my JS changes I already have CI set up which triggers a codepush rollout.

Will be keen to track this one.

**Comment by anthonyhumphreys** [comment]
> We have iOS, Android, and documentation all in one repo. Kicking off multiple builds for a `README.md` seems wasteful and noisy. We could split the repo into 3, but that adds a bit more project-mgmt overhead.

Agree with this. This is the norm with React Native projects especially and I know lots of orgs who are moving towards monorepos so this would be a huge win for users who fit those use-cases.

**Comment by caiofbpa** [comment]
> React with 🎉if you would be happy with a solution where we allow you to restrict builds to only be triggered when a commit is within the path of the project that we found in your repo,

About this, we have a Xamarin solution where we have an Android project, an iOS project and a Shared project. If any files in Shared change, I want both Android and iOS to be built. So it's much better if I can manually specify the paths to be watched for changes that trigger a build.

**Comment by CatalinVoss** [comment]
Would still love to see this in December 2020
