### ISSUE TITLE
Codepush vs. Native distribution strategy

### ISSUE THREAD

**Issue by tonyxiao** [microsoft/appcenter#261]
I'd love to see some recommended setup of codepush vs. native distribution strategy. When to use each, and how do they integrate with each other? It's amazing that App Center has code push built in (in fact it's what brought us to app center in the first place) however it's been really difficult to figure out how everything fits together.

**Comment by tonyxiao** [comment]
Related to https://github.com/Microsoft/appcenter/issues/65

**Comment by botatoes** [comment]
Hi @tonyxiao, thanks for the feedback. By native distribution strategy do you mean App Center's distribution or OS specific distribution (testflight/playstore)

**Comment by tonyxiao** [comment]
@botatoes both. What makes it challenging is that there are so many different ways to distribute and it's hard to think about how to get them to work together. In this particular case tho, it's more about code push vs. native (whether App center or os specific)
