### ISSUE TITLE
Support detox as a testing framework

### ISSUE THREAD

**Issue by tonyxiao** [microsoft/appcenter#262]
**Describe the solution you'd like**
We use detox for testing react native applications because of its speed and reliability. This is currently not supported on App Center testing. 

**Describe alternatives you've considered**
Appium

Wix’s Detox works similar way as Appium but important difference here is a Gray box testing. One of the reason why Detox was born is to solve “flakiness” problem — it will wait until action in app is finished and will continue only when app is idle. This is possible because of other framework called EarlGrey.

**Additional context**
https://medium.com/reactive-hub/detox-vs-appium-ui-tests-in-react-native-2d07bf1e244f

**Comment by Oddj0b** [comment]
Thank you for your contribution.

**Comment by sergiomap** [comment]
Any news about this? 
This would be very helpful.

**Comment by johnhiggs** [comment]
+1 want to make sure subscribed to this... id adding detox support to appcenter on the rpaf map at all?

**Comment by Manuel7AP** [comment]
Hellooo, this is a feature that we would love to see!

**Comment by zevmo** [comment]
+1 we are anxiously waiting for this, in addition to the support for moving everything over from azure (ios builds) to appcenter proper.

**Comment by bernardoflynn** [comment]
Curious as to how the other supported test frameworks were chosen compared to Detox. Seems Detox is a more stable framework than Appium. Seems a logical choice for a testing framework to support.

**Comment by Oddj0b** [comment]
I'm the program manager responsible for App Center Test and I'm working on a new idea which will support more frameworks in Test, allow unit testing, and browser testing. I would like to talk to you about it and understand your needs better.

Below is a link where you can sign-up for a 30-minute call with me. The agenda will be about the value of testing for you and your organization, and my new idea to allow more frameworks and testing styles in App Center Test.

Link to choose https://calendly.com/vigimm/appcenter-test

**Comment by sergiomap** [comment]
Any news about Detox integration with Appcenter?

**Comment by ariniastari** [comment]
I might consider subscribing the test platform if it supports detox.

**Comment by GutteApps** [comment]
We would also love to see Detox support on App Center.

**Comment by PvanHengel** [comment]
Agreed detox would be great

**Comment by sebastianmalcolm** [comment]
👍 for adding Detox support into App Center's Test service. The build script example at https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/detox/appcenter-post-build.sh Microsoft's unofficial support for using Detox.

Detox can run on App Center by referring to this simple React Native app example, that I updated 6 months ago to build using Detox 9.1.2 & Xcode 10.1:
https://github.com/patniko/detox-appcenter

💡Initial official support for Detox could be just verifying that each new build machine image successfully runs _one_ recent version of Detox?

**Comment by zuhair-naqvi** [comment]
Any news on the official support? When can we expect to see some out-of-the-box support for Detox? It's the only thing holding us back from migrating to AppCenter

**Comment by tindn** [comment]
+1 for this

**Comment by leotm** [comment]
I've tried the past couple days but unable to get a successful build in App Center.

> The build script example at https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/detox/appcenter-post-build.sh Microsoft's unofficial support for using Detox

Node v8.5.0 currently results in: `detox is not installed in this directory`

Node v13.1.0 gets Detox building, but results in:

```sh
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/runner/runners/2.160.0/work/1/s/ios/build/Build/Intermediates.noindex/AppCenterReactNative.build/Release-iphonesimulator/AppCenterReactNative.build/Objects-normal/i386/AppCenterReactNative.o AppCenterReactNative/AppCenterReactNative.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
detox[4181] ERROR: [cli.js] Error: Command failed: xcodebuild -workspace ios/<Name>.xcworkspace -scheme <Name> -configuration Release -sdk iphonesimulator -derivedDataPath ios/build
```

With:
- `"detox": "^14.7.1"`
- `"@types/detox": "^14.5.1"`

I've even taken our `appcenter-post-clone.sh` and run it locally with environment variables entered manually in the file with no problems whatsoever.

Unfortunately giving up at this point and going to try BitRise then TravisCI.

**Comment by gusgard** [comment]
@leotm I'm doing the following in the `appcenter-post-build.sh`, I hope it helps you.

```
  echo "iOS: Installing applesimutils..."
  brew tap wix/brew
  brew install wix/brew/applesimutils

  echo "iOS: Installing detox cli..."
  npm install -g detox-cli

  echo "iOS: Building the project..."
  yarn detox build --configuration ios.sim.release

  echo "iOS: Cleaning cache..."
  yarn detox clean-framework-cache && yarn detox build-framework-cache

  echo "iOS: Executing tests..."
  yarn detox test --configuration ios.sim.release
```

**Comment by leotm** [comment]
Thanks @gusgard , but I tried this to no avail.

Out of curiosity, why are we not doing `yarn global add detox-cli` in your snippet?
I found this works.

---

Further:

> The build script example at https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/detox/appcenter-post-build.sh Microsoft's unofficial support for using Detox

States:

> 4) If you're using yarn, make sure to use it instead of npm, to avoid clashes in dependencies

**Comment by gusgard** [comment]
@leotm  We are using node v10.x (I don't think detox works with v6), it should work well with `yarn global add detox-cli` too.

**Comment by leotm** [comment]
Cheers @gusgard , just gave node v10.17.0 a shot but still not luck

**Comment by artemvs** [comment]
How to configure appcenter-post-clone.sh for Android and when run android emulator?

**Comment by artemvs** [comment]
How to configure appcenter-post-clone.sh for react native (Android) and how to run android emulator via MS App Center?

**Comment by samlucax** [comment]
Any updates about the official support?

**Comment by shawnhong1** [comment]
+1 for this too

**Comment by helciofranco** [comment]
> Any updates about the official support?

https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/detox/appcenter-pre-build.sh

**Comment by gusgard** [comment]
Not a solution but here is a custom script to run it on Android.
https://github.com/patniko/detox-appcenter/commit/d8084fbdddf74060eb55d6540e42fef005bbab8b

**Comment by chenliez** [comment]
Please add the support for Detox. Our team is considering to move away from App Centre for lacking of this support.

**Comment by newah** [comment]
So at least it's possible to run Detox with custom scripts. But how do you guys detect whether tests succeeded or not? I only see running the tests which is fine, but what about actually using the results? :)

And if they fail, do you report it to slack and cancel the build?

**Comment by lhuria94** [comment]
Hi, Is it preferred to run your test i post build or pre build?

Also how do we cover different devices as a part of test suite?

Can anyone suggest?

**Comment by sseppola** [comment]
I started running Detox tests in Github Actions following https://github.com/reime005/react-native-spaceviewer/blob/master/.github/workflows/iOS.yml

With the right setup you can integrate it into your PR flow, just note:
- Macos container pricing is 10x that of Linux
- Workflows triggered from PRs do not have access to the "commit" that triggered it without a workaround.

**Comment by ioannisGiak89** [comment]
We managed to get detox running in App center but it would be great to see official support

**Comment by hsavit1** [comment]
Is there a public roadmap for appcenter? and if so, is this on there?

**Comment by proverbface** [comment]
+1

**Comment by proverbface** [comment]
> We managed to get detox running in App center but it would be great to see official support

@ioannisGiak89 anything worth sharing to the community?

**Comment by ioannisGiak89** [comment]
@proverbface sorry for the late reply 

```
if [ "$APPCENTER_BRANCH" = "dev" ]; then

    export RN_SRC_EXT=e2e.js

    if [ "$OS" = "iOS" ]; then
        echo "iOS: Installing cocoapods..."
        npm run pod-install

        echo "iOS: Building the project for Detox tests..."
        npx detox build --configuration ios.sim.release --loglevel verbose

        echo "iOS: Executing Detox tests..."
        npx detox test --configuration ios.sim.release --cleanup --loglevel verbose
    else

        echo "Android: Building the project for Detox tests..."
        npx detox build --configuration android.emu.release --loglevel verbose

        echo "Android: Downloading android image..."
        /Users/runner/Library/Android/sdk/tools/bin/sdkmanager "system-images;android-27;default;x86_64"

        echo "Android: Accepting licenses for android images.."
        echo N | /Users/runner/Library/Android/sdk/tools/bin/sdkmanager --licenses
        touch /Users/runner/.android/repositories.cfg

        echo "Android: Creating AVD.."
        echo no | /Users/runner/Library/Android/sdk/tools/bin/avdmanager create avd -n Pixel_API_27_AOSP -d pixel --package "system-images;android-27;default;x86_64"
        cp app-center/config.ini /Users/runner/.android/avd/Pixel_API_27_AOSP.avd/config.ini

        echo "Android: Executing Detox tests..."
        npx detox test --configuration android.emu.release --headless --loglevel verbose
    fi
fi
```

**Comment by Yann-OAF** [comment]
+1 - we'll subscribe as soon as we have Detox support...

**Comment by armartinez** [comment]
I'm trying to setup a post build script to run the tests using the generated build but I'm getting the following error

`detox[17288] ERROR: [exec.js/EXEC_FAIL, #8] An error was encountered processing the command 
(domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request was denied by service delegate (SBMainWorkspace).
Underlying error (domain=FBProcessExit, code=64):
	The operation couldn’t be completed. The process failed to launch.
	The process failed to launch.`

Rings any bells ?

**Comment by ioannisGiak89** [comment]
@armartinez But how are you going to run detox test with a generated build? Doesn't need this to be built with detox first?

**Comment by armartinez** [comment]
@ioannisGiak89 Yes you are right, I found out that AppCenter builds for arm64 which can't be used on the Simulator so I have to trigger a build for Detox.

**Comment by dzaiats** [comment]
I'm getting this error:
`Error: Exceeded timeout of 180000ms while handling jest-circus "setup" event`
every time I try to launch the tests.
Maybe simulators are not available or limited somehow?
@ioannisGiak89 did you have such?

**Comment by tsemerad** [comment]
@ioannisGiak89 Would you mind sharing the `config.ini` you're using in the above script you posted? I'm having issues with the Android emulator failing. I see that you're running the following:

```bash
cp app-center/config.ini /Users/runner/.android/avd/Pixel_API_27_AOSP.avd/config.ini
```

**Comment by ioannisGiak89** [comment]
Hi @tsemerad, I can share our `config.ini` , however the way I did is to create a emu from the AVD manager and then copy the config file. I would  recommend for you to do the same. As an example here is our `config.ini` file

`
AvdId=Pixel_XL_API_29_AOSP
PlayStore.enabled=false
abi.type=x86_64
avd.ini.displayname=Pixel XL API 29 AOSP
avd.ini.encoding=UTF-8
disk.dataPartition.size=800M
fastboot.chosenSnapshotFile=
fastboot.forceChosenSnapshotBoot=no
fastboot.forceColdBoot=no
fastboot.forceFastBoot=yes
hw.accelerometer=yes
hw.arc=false
hw.audioInput=yes
hw.battery=yes
hw.camera.back=none
hw.camera.front=none
hw.cpu.arch=x86_64
hw.dPad=no
hw.device.hash2=MD5:f78477654d5471c3d7f705251d14e72f
hw.device.manufacturer=Google
hw.device.name=pixel_xl
hw.gps=yes
hw.gpu.enabled=no
hw.gpu.mode=off
hw.initialOrientation=Portrait
hw.keyboard=no
hw.lcd.density=560
hw.lcd.height=2560
hw.lcd.width=1440
hw.mainKeys=no
hw.ramSize=1536
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images/android-29/default/x86_64/
runtime.network.latency=none
runtime.network.speed=full
sdcard.size=512M
tag.display=Default Android System Image
tag.id=default
vm.heapSize=384
`

**Comment by lucianonickelpay** [comment]
> @proverbface sorry for the late reply
> 
> ```
> if [ "$APPCENTER_BRANCH" = "dev" ]; then
> 
>     export RN_SRC_EXT=e2e.js
> 
>     if [ "$OS" = "iOS" ]; then
>         echo "iOS: Installing cocoapods..."
>         npm run pod-install
> 
>         echo "iOS: Building the project for Detox tests..."
>         npx detox build --configuration ios.sim.release --loglevel verbose
> 
>         echo "iOS: Executing Detox tests..."
>         npx detox test --configuration ios.sim.release --cleanup --loglevel verbose
>     else
> 
>         echo "Android: Building the project for Detox tests..."
>         npx detox build --configuration android.emu.release --loglevel verbose
> 
>         echo "Android: Downloading android image..."
>         /Users/runner/Library/Android/sdk/tools/bin/sdkmanager "system-images;android-27;default;x86_64"
> 
>         echo "Android: Accepting licenses for android images.."
>         echo N | /Users/runner/Library/Android/sdk/tools/bin/sdkmanager --licenses
>         touch /Users/runner/.android/repositories.cfg
> 
>         echo "Android: Creating AVD.."
>         echo no | /Users/runner/Library/Android/sdk/tools/bin/avdmanager create avd -n Pixel_API_27_AOSP -d pixel --package "system-images;android-27;default;x86_64"
>         cp app-center/config.ini /Users/runner/.android/avd/Pixel_API_27_AOSP.avd/config.ini
> 
>         echo "Android: Executing Detox tests..."
>         npx detox test --configuration android.emu.release --headless --loglevel verbose
>     fi
> fi
> ```
> 
> We run the above script in our pre build script

could share your detox config ?

**Comment by janpieterz** [comment]
@msftbot I don't think the feature request this issue raises has gone stale/is unwanted. 
CC @elamalani

**Comment by whalemare** [comment]
Bump, still needed and relevant

**Comment by luissantana** [comment]
+1 to the need for detox support. AFAIK is not supported by AWS either and could be a great advantage

**Comment by pacozaa-paloit** [comment]
@ioannisGiak89 Is it the pre-build script?

**Comment by whalemare** [comment]
Bump, still needed and relevant

**Comment by andac-ozcan** [comment]
Also needed here, workaround solution during builds not helping much because it have 1 hour limit.

**Comment by oliviasv** [comment]
+1 for this too

**Comment by danielfamiyeh** [comment]
+1

**Comment by ggilchrist-ledger** [comment]
+1 🙏

**Comment by mrk-han** [comment]
Any official update on this?

**Comment by carl0shd** [comment]
+1

**Comment by mrk-han** [comment]
Bump!

**Comment by rikur** [comment]
@mrk-han FYI, There's a release candidate of Detox that supports physical iOS devices: https://github.com/wix/Detox/issues/3208

**Comment by DaanDeMot** [comment]
+1

**Comment by lucen-ms** [comment]
We do not plan to support Detox in App Center.
