### ISSUE TITLE
Appcenter CLI not working

### ISSUE THREAD

**Issue by strongdev6** [microsoft/appcenter#2620]
I have been having an issue with commands not working when I updated to the newest version of the appcenter cli. 

With the commands I am receiving an error that states the commands are invalid.

The commands previously worked with my mobile distribution. After consulting with Appcenter support, they were able to verify that there was an issue with the CLI. To avoid a rewrite to use the API directly, correcting the CLI is preferable.

**Comment by MikhailSuendukov** [comment]
Hello and thanks for reaching out to us!
Could you please clarify which commands you are referring to, and which versions of appcenter-cli you have tried?

**Comment by DmitriyKirakosyan** [comment]
Closing. Please reopen if you are still interested.
