### ISSUE TITLE
Connection is not private appcenter website

### ISSUE THREAD

**Issue by LeoJHarris** [microsoft/appcenter#2632]
![image](https://github.com/microsoft/appcenter/assets/5468757/c64742ff-f964-4863-b449-9abdc9ea46d2)

**Comment by LeoJHarris** [comment]
Am I the only one seeing this issue?

**Comment by jyling** [comment]
Hi @LeoJHarris, Im also experiencing the same issue, this is annoying

**Comment by LeoJHarris** [comment]
@jyling guess we cant rollout new build to public groups or remove existing ones.

**Comment by jyling** [comment]
<img width="541" alt="image" src="https://github.com/microsoft/appcenter/assets/11886327/55bcd25b-c389-4ce0-b7ac-9c6c31d785ef">

The certificate expired 2 hours ago

**Comment by LeoJHarris** [comment]
@jyling I think that's a clear sign Microsoft has well and truly forgot about this project 🤦

**Comment by jyling** [comment]
This seems to be resolved, i can access the site now
