### ISSUE TITLE
Continue support for Xamarin.UITest and add .NET 8 support

### ISSUE THREAD

**Issue by JohnHDev** [microsoft/appcenter#2635]
**Describe the solution you'd like**
Needs .NET 8 support

**Describe alternatives you've considered**
Open source Xamarin.UITest so that the community can fix the issues

**Additional context**
Support for Xamarin.UITest has always been quite ropey, often waiting for months for fixes to come through. Please, either prioritise this or open source it. Many of us pay for Visual Studio, Azure DevOps (we have 20 concurrent build servers), and that is just in my team. We have other development teams that use similar tech stacks within my organisation as well.

**Comment by IlyaBausovAkvelon** [comment]
Hi @JohnHDev,
Thank you for reporting this. Have you tried Xamarin.UITest 4.3.5 with fix for Simulators runtime that was blocking users from running tests on .NET 8 target framework?
Do you face any other issues with running .NET 8?

**Comment by JohnHDev** [comment]
Thanks @IlyaBausovAkvelon I have updated but now getting the following error:
	Message	"One or more errors occurred. (Failed to launch simulator: An error occurred trying to start process 'idb:' with working directory '/Users/xxxxxx/bin/Debug/net8.0'. No such file or directory)"

Has there been any discussions on open sourcing Xamarin.UITest?

Thanks
John

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon Installed idb and have tests running locally, I have also updated ADO pipelines to install idb via CLI and now have UI tests running there as well.
