### ISSUE TITLE
Can Xamarin.UITest work on .net 8? when updating my project I get the following error on Android

### ISSUE THREAD

**Issue by Moshex** [microsoft/appcenter#2637]
Is there a way to get Xamarin.UITest to work on .net 8? When I updated my project to .net 8 I got the following error when running Xamarin.UITest on Android:

```
System.Exception : Android SDK not found. Please install it and if it is still not located, please set the ANDROID_HOME environment variable to point to the directory.

Searched locations: 
(No path) - Not set. [ Source: ANDROID_HOME ]
/Users/mmoadeb/Library/Developer/Xamarin/android-sdk-mac_x86 - Does not exist. [ Source: Xamarin < 3 install path ]
/Users/mmoadeb/Library/Developer/Xamarin/android-sdk-macosx - Does not exist. [ Source: Xamarin 3 install path ]
/usr/local/Cellar/android-sdk/ - Does not exist. [ Source: Homebrew install path ] 
```

is there a way to fix this error? To fix this I have to downgrade my project to .net 6 then the error goes away. from my testing the update to . net 8 does work on iOS which is cool.

**Comment by Moshex** [comment]
I was able to fix this issue by moving my whole SDK folder to the file path in the error. This was a pain to do, but using Android Studio, I was able to move the SDK folder to the new location needed for Xamarin.UITest. I am happy to report that with this workaround, I can run Xamarin.UITest to work on .NET 8.

in the image, it shows the folder I needed to make.

![Image](https://github.com/user-attachments/assets/48cab591-beed-4538-a4f6-9c215ef120fa)

**Comment by IlyaBausovAkvelon** [comment]
Hi @Moshex, good to hear.
I want to ask you was the ANDROID_HOME environment variable set prior to test run?

**Comment by Moshex** [comment]
ANDROID_HOME variable being set is a Windows only thing, I have never had to do that on Mac. I could be wrong on this but that is my experience.

**Comment by IlyaBausovAkvelon** [comment]
@Moshex,
I've double checked that. ANDROID_HOME should be set in zsh.rc/bash.rc on macOS/Linux as well as on Windows.

**Comment by Moshex** [comment]
in my case, it's a .zprofile and you are correct it is set there. Thank you for pointing that out!

![Image](https://github.com/user-attachments/assets/a81b88d8-30e4-4b61-a6b5-c1e6d9b77b42)
