### ISSUE TITLE
Support for Xcode 10.2

### ISSUE THREAD

**Issue by arasu01** [Microsoft/appcenter#264]
**What App Center service does this affect?**
AppCenter Build

**Describe the bug**
My code was in swift 5.0 and I was not able to distribute through Appcenter. Because Xcode version support is Xcode 10.1

**To Reproduce**
1. Commit code with swift 5.0
2. Generate a build in app center
3. Getting below error

Check dependencies
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

**Expected behavior**
It should compile for swift 5.0 without error.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lumaxis** [comment]
Thanks for letting us know about your need for Xcode 10.2 @arasu01 !
We're actually already working on this and hope to have it ready soon 😊

**Comment by shawnmay** [comment]
+1, stuck in limbo, was surprised to see this support missing.

**Comment by joshbillions** [comment]
@lumaxis Just curious, how long should we expect between Xcode releases and App Center support in the future? I would have figured you'd have quicker support since the Xcode 10.2 betas have been available for some time already.

**Comment by nrajpurkar** [comment]
@joshbillions we aim to get support for stable updates out as fast as we can. We don't have an SLA around these updates today, but typically we have landed updates within a week of release.

**Comment by joshbillions** [comment]
@nrajpurkar Thank you. My team is new to App Center and we're just trying to figure out how this will look in the future. In general, is your team tracking with the beta releases of Xcode, or just on public release?

**Comment by nrajpurkar** [comment]
@joshbillions we commit to full support for stable releases. With Xcode 10 we began releasing beta support as well. This got a little tricky with Xcode 10.2 only running on Mojave which led to no support for Xcode 10.2 betas.

**Comment by lfkwtz** [comment]
any update here? been over two weeks since 10.2 was released and this is hindering our development.

**Comment by nrajpurkar** [comment]
Thank you all for the patience on this! Xcode 10.2 is now available for native iOS and React Native projects. Also take note that from now on any builds using Xcode 9.4.1 or above (including 10.2) will run on [macOS Mojave](https://docs.microsoft.com/en-us/appcenter/build/software#operating-system).

**Comment by lemessur** [comment]
We have a Xamarin Forms app and we are still only seeing Xcode 10.1 as the latest supported version. Any word on when 10.2 will be supported for Xamarin Forms? This is hindering our workflow. We need to be able to target iOS 12.2. Our current workaround is to run builds on our development machines.

**Comment by nrajpurkar** [comment]
@lemessur Xcode 10.2 for Xamarin apps will be available soon! We're working on rolling some Mono and Xamarin SDK updates at the moment to unblock you there. We're tracking this on our iteration plan for the month at #227

**Comment by isangines** [comment]
Many thanks for the update @nrajpurkar! Another Xamarin dev, when you are saying soon, are we are talking about hours, days or weeks?

**Comment by nrajpurkar** [comment]
@isangines it's our top priority right now 😄 much faster than weeks.

**Comment by yangmie** [comment]
@nrajpurkar Now Apple released Xcode 10.2.1... Could you support 10.2.1 as well?

**Comment by nrajpurkar** [comment]
@yangmie we'll be getting 10.2.1 in as well.

**Comment by nrajpurkar** [comment]
@lemessur @isangines you should now see Xcode 10.2 available for Xamarin apps!

**Comment by r79** [comment]
> Thank you all for the patience on this! Xcode 10.2 is now available for native iOS and React Native projects. Also take note that from now on any builds using Xcode 9.4.1 or above (including 10.2) will run on [macOS Mojave](https://docs.microsoft.com/en-us/appcenter/build/software#operating-system).

I don't see the support for Xcode 10.2 in my list, using a react native iOS project. Can someone confirm to me that this should be there / that it isn't there or explain to me how I can access it?

**Comment by r79** [comment]
> > Thank you all for the patience on this! Xcode 10.2 is now available for native iOS and React Native projects. Also take note that from now on any builds using Xcode 9.4.1 or above (including 10.2) will run on [macOS Mojave](https://docs.microsoft.com/en-us/appcenter/build/software#operating-system).
> 
> I don't see the support for Xcode 10.2 in my list, using a react native iOS project. Can someone confirm to me that this should be there / that it isn't there or explain to me how I can access it?

For anyone that's also looking for this: I found the reason / solution for this problem here: https://github.com/MicrosoftDocs/appcenter-docs/issues/353

**Comment by galfonso777** [comment]
When will Xamarin.UITest support Xcode 10.2? https://github.com/Microsoft/appcenter/issues/274

**Comment by Oddj0b** [comment]
@galfonso777 Have you tried updating to 3.0.0.dev, we are still QA'ing the final release but you can use that until then.

**Comment by galfonso777** [comment]
@Oddj0b I have not tried the 3.0.0.dev release yet, I was more inquiring about the next official release of Xamarin.UITest package since this Support for Xcode 10.2 ticket has been officially closed.

**Comment by Oddj0b** [comment]
@galfonso777 you can get it today 😄
