### ISSUE TITLE
Indicate unsaved or automatically save build scripts to build configuration

### ISSUE THREAD

**Issue by RWOverdijk** [microsoft/appcenter#265]
In build settings (for branches) you can see the build scripts. maybe it's a nice idea to replace the checkmark with an exclamation mark if the script isn't going to be applied yet. A simple alt-text would do the trick. _"You have to hit save to apply the build script to this branch"_.

<img width="105" alt="Screenshot 2019-04-02 08 54 32" src="https://user-images.githubusercontent.com/781745/55382051-f8087c00-5524-11e9-9392-75dfa3b33409.png">

Replace checkmark with exclamation mark.

The amount of time I spent chasing this is not funny. 😄 

Related: https://github.com/MicrosoftDocs/appcenter-docs/issues/53

**Comment by nrajpurkar** [comment]
Thanks for the suggestion @RWOverdijk. A UI indicator could definitely clear up some confusion here. We'll take a look into this and see how we can make this experience better. @plainspace, penny for your thoughts on this too

**Comment by RWOverdijk** [comment]
What the hell? @plainspace gets paid a penny for his thoughts and I only get a _thanks_? Shameful!

Thanks for the response 😄

**Comment by nrajpurkar** [comment]
😛 For context, @plainspace works on App Center's design

**Comment by RWOverdijk** [comment]
Oh cool! Nice job so far 😎
