### ISSUE TITLE
When publishing to AppStore, allow to modify all Fastlane settings (IDFA)

### ISSUE THREAD

**Issue by hannta** [microsoft/appcenter#267]
**Describe the solution you'd like**
When I publish my app from appcenter to Apple AppStore review, I need to set the advertising id settings (idfa) for publish. That is not possible as appcenter defaults to `add_id_info_uses_idfa: false`

Fastlane supports these properties (`add_id_info_uses_idfa`, `add_id_info_tracks_install`, `add_id_info_tracks_action` etc) but I can not configure these from appcenter.

**Describe alternatives you've considered**
Because I can not specify these IDFA settings, I can not publish my app from appcenter to AppStore and I need to do the publish process manually using Apples Application loader tool etc.

**Comment by amchew** [comment]
Thanks for your feature request @hannta! @Oddj0b would you be able to take a look please?

**Comment by Frans-L** [comment]
@hannta 
Have you found any solution for this?

**Comment by hannta** [comment]
@Frans-L Not really, though when im publishing the app to TestFlight from AppCenter, I do not need to set IDFA. When the app is in TestFlight I can submit it to App Store review from App Store Connect.

**Comment by Frans-L** [comment]
@hannta Thanks :)
