### ISSUE TITLE
[Bug] Incomplete stack traces ("hidden" references) in App Center builds (iOS)

### ISSUE THREAD

**Issue by istvanp** [microsoft/appcenter#27]
**Describe the bug**
I am encountering a lot of hidden stack trace lines in my crash reports when I build my binaries using the build feature.

**To Reproduce**
1. Build an iOS app with App Center for internal distribution (an AdHoc provision profile).
2. Produce a crash in the app.
3. Go to the crash report, observe "_hidden#00000_" references.

**Expected behavior**
A full stack trace with file, function names and line numbers.

**Screenshots**
![screen shot 2019-02-04 at 18 13 23](https://user-images.githubusercontent.com/179335/52244890-74783900-28ad-11e9-93a1-4afb94ac4dc0.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
My application has bitcode generation ON. From [the documentation](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication), it is recommended to turn this feature off as Apple reserves the discretion to rebuild your app which might invalid the stack trace. However, in my case this was an internal build, not for the App Store. I also made sure that the debug dSYM files are generated (`DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym"`). Builds from the App Center also don't allow you to download the full archive, only the ipa file, so there is no way to reconcile the missing references. What are the steps and settings needed to produce a full stack trace when crashes happen from builds made in App Center?

**Comment by patniko** [comment]
Hi @istvanp, there are issues when bitcode is enabled for builds that requires us to do some additional implementation work. For now it's recommended to turn that option off if you'd like to use diagnostics in App Center together per the docs, but we are tracking this item to see if others would like this support as well.

**Comment by istvanp** [comment]
Ah, I see! Thanks for the clarification @patniko! I feel like the language can be improved a little bit on the [App Center Crashes (iOS) page](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios) however. This requirement is a little bit lost in the preamble. Maybe add the purple Note box around 
> Also note that crash logs on iOS require Symbolication, please check out the App Center Diagnostics documentation that explains how to provide symbols for your app.

and mention Bitcode should be disabled directly in there. Just my two cents :)

**Comment by patniko** [comment]
Totally fair and noted. We’ll make some changes to highlight that this is more of a hard requirement for now.

**Comment by DanChua-Limeade** [comment]
Hi. I was referred to this issue by App Center support. Can this be reopened? We recently switched one of our apps to use the App Center crash reporting capability. We also have Bitcode enabled. This inability to show complete stack traces is making it hard for us to investigate crashes. The same symbols downloaded from iTunes Connect works just fine in Crashlytics, but not in App Center. Do you have an estimate on when this can be fixed?

**Comment by juansanzone** [comment]
Any update? @DanChua-Limeade

**Comment by ali-raza** [comment]
hello, i am facing same _hidden# for my app, please guide how i can get full crash tracing

**Comment by JagCesar** [comment]
One of my clients is also having this issue, any updates on this @patniko?
