### ISSUE TITLE
Configure new Cosmos DB Database in App Center 

### ISSUE THREAD

**Issue by Zakeelm** [microsoft/appcenter#270]
[Data MVP Technical Specification](https://github.com/Microsoft/appcenter/blob/master/specs/2019-02/Data-Sync/Overview.md)

This would enable developers to configure a new Cosmos DB database for use with the Data service. Users will be required to connect their app to an azure subscription and then enter a resource name, database location, and the desired throughput for pricing. Doing so will enable the developer to start using the Data service with their newly configured database. 

Here are the latest iteration of the designs for this feature:

<img width="996" alt="Screen Shot 2019-04-02 at 3 24 04 PM" src="https://user-images.githubusercontent.com/31293287/55440077-6b2ce500-555b-11e9-87b4-8b27833c2d79.png">

Let us know if you have any feedback, or would like to be a part of our private preview!

**Comment by sagostini** [comment]
Hello,

it looks like App Center is not able to keep the relation with the newly created CosmosDB.
Once it is visible as fully created on Azure, it doesn't show properly on App Center
![image](https://user-images.githubusercontent.com/17493212/58029169-58c33680-7b1c-11e9-8dbe-3c52be7a1716.png)

and it returns an error when called from Xamarin.Forms:

`Microsoft.AppCenter.Data.DataException: com.microsoft.appcenter.data.exception.DataException: Call to App Center Token Exchange Service succeeded but the resulting payload indicates a failed state: {"tokens":[{"partition":"user","dbAccount":null,"dbName":null,"dbCollectionName":null,"token":null,"expiresOn":null,"accountId":null,"status":"Unauthenticated"}]}`

**Comment by Zakeelm** [comment]
Interesting, can you confirm you have admin access to that app and the subscription used to provision the database?

**Comment by sagostini** [comment]
Hello, it looks like it depends on the fact that the AppCenter user is not able to see the CosmosDB. When I used the same user on both AppCenter and Azure, it worked fine

**Comment by Zakeelm** [comment]
Awesome, glad this issue was resolved. Seems to be the same issue in our other [thread](https://github.com/microsoft/appcenter/issues/271#issuecomment-497610473). Going to close this! Feel free to open a new issue if you have feature requests, bugs, or general feedback!
