### ISSUE TITLE
Connect existing Cosmos DB database in App Center

### ISSUE THREAD

**Issue by Zakeelm** [microsoft/appcenter#271]
[Data MVP Technical Specification](https://github.com/Microsoft/appcenter/blob/master/specs/2019-02/Data-Sync/Overview.md)

This would enable developers to connect an existing Cosmos DB database for use with the Data service. Users will be required connect their app to an azure subscription (or connect via a primary connection string) and then select their desired cosmosDB account, database, and then collection. Doing so will enable the developer to start using the Data service with their configured database. 

Here are the latest iteration of the designs for this feature:

**1. Connecting existing database via azure subscription**

![image](https://user-images.githubusercontent.com/31293287/55441766-daf19e80-5560-11e9-9521-2f3258121b74.png)

**2. Connect existing database via primary connection string**

![image](https://user-images.githubusercontent.com/31293287/55441856-21df9400-5561-11e9-84ab-13e05a2f77e3.png)

Let us know if you have any feedback, or would like to be a part of our private preview!

**Comment by sagostini** [comment]
Hello,

I cannot see any CosmosDB from AppCenter, even if I created one in my Azure subscription
![image](https://user-images.githubusercontent.com/17493212/58027626-590e0280-7b19-11e9-8d4f-21cb099fe3e9.png)

![existing](https://user-images.githubusercontent.com/17493212/58027633-5f03e380-7b19-11e9-9f1d-0127dbf29c31.png)

Am I doing anything wrong?

**Comment by Zakeelm** [comment]
Hey there! Can you confirm that the Cosmos DB instance uses the SQL API when created? Only those are visible in this list.

**Comment by sagostini** [comment]
Hello, it looks like it depends on the fact that the AppCenter user is not able to see the CosmosDB. When I used the same user on both AppCenter and Azure, it worked fine

**Comment by Zakeelm** [comment]
Ah, yes. In order to view instances, the current logged in user must have access to that azure subscription

**Comment by sagostini** [comment]
The strange thing is that actually a different login user can be used to access Azure, but then nothing is visible on AppCenter. If the only access with the same user is allowed, don't let people login with another user to Azure...

**Comment by Zakeelm** [comment]
I can see why that would cause some confusion. We'll definitely look into a solution for this. Thanks for the note!
