### ISSUE TITLE
Create the "Getting Started" page for the Data service

### ISSUE THREAD

**Issue by Zakeelm** [microsoft/appcenter#273]
[Data MVP Technical Specification](https://github.com/Microsoft/appcenter/blob/master/specs/2019-02/Data-Sync/Overview.md)

This goal of this is to create a "Getting Started" page that will serve as a landing page and starting point for the Data Service. This page will include instructions on getting started with using the Data service and the SDK usage instructions, enabling developers to easily onboard onto this service. 

Let us know if you have any feedback, or would like to be a part of our private preview!

**Comment by fiannaca** [comment]
The link to your spec is broken

**Comment by Zakeelm** [comment]
Apologies for that, we moved these onto another branch. Technical specs are available on the specs branch.
