### ISSUE TITLE
ARM64 Wont Create for UWP

### ISSUE THREAD

**Issue by chriskellor** [microsoft/appcenter#280]
I cant not create a working package without errors for UWP. I can build the package but when I try to create my bundle for the store I get 100+ errors. All are centered around e_sqlite3.dll. If I take out AppCenter then my bundle is created with no errors. Here is some of the errors:
API sqlite3_aggregate_context in e_sqlite3.dll is not supported for this application type.
API sqlite3_aggregate_count in e_sqlite3.dll is not supported for this application type.
API sqlite3_backup_finish in e_sqlite3.dll is not supported for this application type.
API sqlite3_backup_init in e_sqlite3.dll is not supported for this application type. 
API sqlite3_backup_pagecount in e_sqlite3.dll is not supported for this application type. 
API sqlite3_backup_remaining in e_sqlite3.dll is not supported for this application type.
API sqlite3_backup_step in e_sqlite3.dll is not supported for this application type. 
API sqlite3_bind_blob in e_sqlite3.dll is not supported for this application type. 
API sqlite3_bind_double in e_sqlite3.dll is not supported for this application type. 
API sqlite3_bind_int in e_sqlite3.dll is not supported for this application type. 
API sqlite3_bind_int64 in e_sqlite3.dll is not supported for this application type. 
API sqlite3_bind_null in e_sqlite3.dll is not supported for this application type. 
API sqlite3_bind_parameter_count in e_sqlite3.dll is not supported for this application type. 
API sqlite3_bind_parameter_index in e_sqlite3.dll is not supported for this application type. 
API sqlite3_bind_parameter_name in e_sqlite3.dll is not supported for this application type. 
API sqlite3_bind_text in e_sqlite3.dll is not supported for this application type.
API sqlite3_bind_text16 in e_sqlite3.dll is not supported for this application type.

**Comment by chriskellor** [comment]
Any chance of fixing this? I had to remove appcenter from my apps since I can not create ARM64 Version. Please update appcenter for ARM64. Thanks.

**Comment by dhei** [comment]
App Center SDK doesn't yet support ARM64 for UWP and the feature request is tracked at https://github.com/microsoft/AppCenter-SDK-DotNet/issues/727.

**Comment by patniko** [comment]
Closing this issue as it's already being tracked as a feature request.
