### ISSUE TITLE
[Android][Espresso] Test runs with @SdkSuppress are marked as failed.

### ISSUE THREAD

**Issue by serj-lotutovici** [microsoft/appcenter#281]
**Describe the solution you'd like**
Test runs that contain tests that should be skipped(ignored) on certain API levels (or devices) should not be marked as failed.

**Additional context**
Currently, when running tests that are annotated with SdkSuppress (instructs Espresso to skip tests on API levels below or above specified one) the console output returns a non-zero value, which marks the entire run as failed. In the AppCenter console, the test run is also marked as failed, altho there are no failed tests.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @serj-lotutovici. @Oddj0b can provide further information here.

**Comment by Oddj0b** [comment]
@serj-lotutovici It's an interesting case I wasn't aware of, thank you for the feature request.

**Comment by King-of-Spades** [comment]
Tracking: ADO - 65021

**Comment by gusgard** [comment]
This is also happening for Appium tests the skipped counts as failure.
