### ISSUE TITLE
Two Factor Authentication (2FA)

### ISSUE THREAD

**Issue by devology-rob** [microsoft/appcenter#282]
**Describe the solution you'd like**
To login to App Center only requires the username and password.  Given that the portal can be used to initiate push notifications to user devices I would like to protect the login further with two factor authentication.

It would be great to use the Google Authenticator app for this, or SMS for each login from an untrusted browser.

**Describe alternatives you've considered**
Moving to another provider could solve this, but after integrating and quite liking the service I have no intention of moving providers just because of 2FA.

**Additional context**
Not applicable

**Comment by iageoghe** [comment]
Hi Rob,

We like this idea and are looking into it.

**Comment by devology-rob** [comment]
> We like this idea and are looking into it.

That's great news - thanks for the update.

**Comment by sphanley** [comment]
Any movement on this? If this still isn't in place, it would be a great move to adopt a common security practice, and would be greatly appreciated.

**Comment by bakerm00** [comment]
you can integrate into conditional access within azure if you have the licensing
but as app centre doesn't integrate fully into Azure iDP is relatively pointless as anyone can be added.
