### ISSUE TITLE
[Android][Espresso] Test runs with @Parameterized tests are marked as failed.

### ISSUE THREAD

**Issue by serj-lotutovici** [microsoft/appcenter#283]
**Describe the solution you'd like**
AppCenter should be able to properly read parameterized test results.

**Additional context**
At the moment test runs that contain parameterized tests are marked as failed, altho all tests passed. It looks like the tool is not able to properly read the report, thus it marks the entire run as failed (See the console output below):

```
...

INSTRUMENTATION_STATUS: numtests=19
INSTRUMENTATION_STATUS: stream=.
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=someTestFuncName
INSTRUMENTATION_STATUS: class=some.package.name.SomeTestName
INSTRUMENTATION_STATUS: current=19
INSTRUMENTATION_STATUS_CODE: 0
INSTRUMENTATION_RESULT: stream=

Time: 481.489

OK (18 tests)


INSTRUMENTATION_CODE: -1
```

All tests were running previously on Firebase locally on similar devices and where passing.
Disabling the parameterized tests makes the test run pass, and the report is properly read.

**Comment by serj-lotutovici** [comment]
Any news on this issue?

**Comment by maxxkrakoa** [comment]
We would like to get a better understanding of your test suite, so can you share a link to a recent test run so we can have a closer look? Alternatively start a support ticket via the blue chat bubble on the bottom left or from the question mark icon on the top right in App Center?

**Comment by Oddj0b** [comment]
@sejr-lotutovici Did you get help?

**Comment by Oddj0b** [comment]
@serj-lotutovici did chat help you?

**Comment by serj-lotutovici** [comment]
Yes, I did. Sorry for the long reply.
