### ISSUE TITLE
Forward app store distribution message

### ISSUE THREAD

**Issue by LouwrensK** [microsoft/appcenter#284]
Hi there,

I was trying to distribute my app to the google play store as part of my build, but i kept getting messages like this in my log: 

##[error]{"mandatory_update":false,"release_notes":"{text}","destinations":[{"id":"1234567890","name":"Alpha","message":"Failed to publish to store. support_id: [object Object]","code":"internal_server_error"}],"code":"partially_succeeded","message":"Failed to publish to store. support_id: [object Object]"}
http response code: 400

##[error]{"code":"internal_server_error","message":"internal error (Support ID: 1234567890)"}
http response code: 500

When I go to the Google Play Store and add my APK manually or use the distribute option in App Center manually, I get errors with the actual source of the error. Could you please forward this message to the build log, so I know why my distribution in my build is actually failing?

**Comment by Oddj0b** [comment]
Thank you for reporting the bug.

**Comment by Oddj0b** [comment]
We've investigated this with the engineers and are displaying the message we're getting from Googles API. At this point we can't do anything about it.
