### ISSUE TITLE
Improve Firebase Integration

### ISSUE THREAD

**Issue by ajchili** [microsoft/appcenter#288]
**Describe the solution you'd like**
I would love to see a way to provide a google-services.json and GoogleService-Info.plist file within the App Center UI. This would remove the requirement of having them within my repository, it would allow projects to have simple integration with Firebase and would prevent the google-services.json and GoogleService-Info.plist files from being accessible within a repository.

**Describe alternatives you've considered**
Based on the [App Center Push for Android](https://docs.microsoft.com/en-us/appcenter/sdk/push/android#prerequisites) documentation page. It appears that the only way to add Firebase integration is by including the google-services.json file within a repository. I have also looked into the environment variables section of App Center but it does not appear to provided the indended results.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @ajchili. Tapping in @jwargo to take a deeper look at this.

**Comment by jwargo** [comment]
@ajchili I apologize for our late response to this, I try to stay on top of the suggestions we get from customers. This is an interesting suggestion, I'll add it to the list of requested features and look into it.

**Comment by ajchili** [comment]
@jwargo no worries, thanks for looking into this.

**Comment by ram95krishh** [comment]
This is very much needed and would be very helpful if you guys can come up with something. Thanks for raising this request @ajchili

**Comment by luketgriffith** [comment]
Just want to add that this would be awesome, particularly if you could specify different files for separate build branches

**Comment by jwargo** [comment]
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
