### ISSUE TITLE
Failed to build and sign macOS app with plugins

### ISSUE THREAD

**Issue by simonas** [microsoft/appcenter#291]
**What App Center service does this affect?**
AppCenter Build

**Describe the bug**
We are unable to build macOS app with plugins and frameworks within AppCenter. After contacting support we were told that this issue fix needs `bigger size of the customer request since this would require a good number of changes and planning`.

We double-checked what exactly is not supported in App Center and we got: `signing framework and plugin is not currently supported in App Center, which I just confirmed with the Program Manager internally.`

At this moment our project has 20+ frameworks and plugins that should be signed, but all of them are failing with similar lines:

```
2018-12-16T14:02:04.5075640Z error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "XXXXXXXX" with a private key was found. (in target 'SpotlightPlugIn')
```

When removed from our project Spotlight, QuickLook plugins and Automator actions such stub app succeeds to build even with frameworks. Hopefully this issue is more connected with code signing broken with plugins only. 

Would be great to have support from fellow macOS developers on this one as this is requirement for many apps to integrate with macOS via system plugins.

**Comment by nrajpurkar** [comment]
Hi @simonas, thanks for opening up an issue for this. I've changed this to a feature request as this is something that isn't supported at the moment. Looks like this issue has already gotten some favorable support and we'll keep this open for further tracking.

**Comment by dstik** [comment]
Hi @simonas - this is not an issue with AppCenter as we have been able to successfully sign and ship MacOS app with AppCenter.

You can solve this by adding a build phase that signs the binaries you need with your Mac Development or Mac Developer ID signing cert:
`codesign --timestamp --verbose --force --deep -o runtime --sign IDENTITY FRAMEWORK_OR_APP`

You can find the identity you need with this: `security find-identity -p codesigning -v`

I recommend reading up on CodeSigning for MacOS if you have additional questions about how this works. Hope this helps!
