### ISSUE TITLE
Update homebrew

### ISSUE THREAD

**Issue by nschild** [microsoft/appcenter#293]
**What App Center service does this affect?**
Build app

**Describe the bug**
Our current build process is taking around 20 minutes per app, most of which seems to be waiting for homebrew to update. What makes things worse is that each time we submit an app to build, either the updated homebrew from the last save is reverted or we are assigned a new build instance and it has to update again.

**To Reproduce**
Create an app that uses homebrew in appcenter-post-clone.sh

**Expected behavior**
Build to compile without updating homebrew

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by nschild** [comment]
As a possible alternative, in case you need to keep brew at version 2.0.6 can you set the environment variable `HOMEBREW_NO_AUTO_UPDATE=1` by default. 
I am going to add `export HOMEBREW_NO_AUTO_UPDATE=1` to our scripts in the meantime

**Comment by nrajpurkar** [comment]
Hi @nschild this is related to how we're building our agent images. We're going to take a look at turning off the auto-update behavior by default

**Comment by nrajpurkar** [comment]
@nschild sorry for the delay in update, but we fixed this a while back. Closing this out.
