### ISSUE TITLE
Programmatically include provisioning profiles and certs

### ISSUE THREAD

**Issue by nschild** [microsoft/appcenter#295]
**Describe the solution you'd like**
It would be great if we could specify and import the keystore / provisioningProfiles / certs via the `appcenter-post-clone.sh` or similar file. We are going to be publishing many apps using the same codebase with different profiles (ad-hoc/app store) and it would save a lot of time if this could be automated.

A possible solution would be to for us to import the required files into a folder like this: 

    /.appsigning/app.mobileProvision
    /.appsigning/notifications.mobileProvision
    /.appsigning/cert.p12
    /.appsigning/certkey.txt
    /.appsigning/app.keystore
    /.appsigning/keystorekey.txt

**Describe alternatives you've considered**

**Additional context**

**Comment by rogueturnip** [comment]
+1

**Comment by frenkelor** [comment]
+1
