### ISSUE TITLE
Additional options when deploying from App Center to App Store Connect

### ISSUE THREAD

**Issue by dj-dev** [microsoft/appcenter#297]
**Describe the solution you'd like**
When deploying an iOS app directly from App Center to App Store Connect, we would like options in App Center for:

1. Enabling/disabling Automatic submission to Apple for review
2. Switching between Version Release options "Manually release this version" and "Automatically release this version"

Currently when we deploy from App Center to App Store Connect, the release is automatically sent to Apple for review and the Version Release option is set to "Automatically release this version". This is not the desired behavior since we often upload the binary in advance to see if it passes the automated checks. And we often need to release the app to market at a specific time which is why we need the "Manually release this version" option.

**Describe alternatives you've considered**
All we can think of for now is developer rejecting the build, setting the version release option to "Manually release this version", then re-releasing when we are ready. This is not ideal since there is a high risk of Apple approving an app and it being automatically released to market before we are ready.

**Additional context**
We see that App Center uses fastlane for automating deployments to App Store Connect. Here is a relevant page of their API related to this request:
https://docs.fastlane.tools/actions/upload_to_app_store/
See the following parameters:
submit_for_review
automatic_release

Thanks

**Comment by Libranner** [comment]
+1

**Comment by kuyazee** [comment]
Another option to just upload the `ipa` file would be nice. This could be beneficial for internal Testflight usage.

**Comment by Oddj0b** [comment]
This is great feedback, thank you. I hope this will get enough attention so that we can start working on it.

**Comment by dj-dev** [comment]
Hi @Oddj0b, does it look likely that this solution will be implemented any time soon? We have an internal ticket open waiting for this functionality. Thanks

**Comment by lemessur** [comment]
The automatic release option should definitely not be enabled by uploading a build from App Center. Why would anyone think that is a good idea? Never mind that that option shouldn't even exist in the first place. Most apps have some kind of backend they need coordinate deployment with. This could have disastrous consequences if someone does not realize that auto-release has been turned on.

**Comment by lemessur** [comment]
I strongly support adding these flags and turning them off by default. The app store submission process is full of highly consequential steps that can't be undone. Most mobile releases include a backend deployment step that must be carefully coordinated with the release of the app.

I can't imagine very many developers would want to have their apps released whenever Apple finishes approving them, even if they don't have a backend component to worry about. This has marketing and business implications as well.

**Comment by Frans-L** [comment]
This feature is a deal-breaking for many teams, at least for us.
Unfortunately, it seems like this feature is not coming 🙁

**Comment by RachelNaane** [comment]
This is a much needed feature! Please open this issue and work on this
