### ISSUE TITLE
Automatically increment build number is updating all Info.plist

### ISSUE THREAD

**Issue by booker-dragon** [microsoft/appcenter#298]
**What App Center service does this affect?**
`Automatically increment build number` in build configuration

**Describe the bug**
I have a third party SDK which it will check against its own version number in runtime
If I have `Automatically increment build number` turned one, it will modify all version number in all Info.plist in the project

**To Reproduce**
1. Have a third party SDK that will check against its own version number in run time
2. Trigger a build with `Automatically increment build number` turned on
3. Trigger the SDK which will check against its own version number in plist

**Expected behavior**
`Automatically increment build number` should only update the app target version number instead of all

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - 73.0.3683.86 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Any iOS device
 - Any
 - Any
 - Any

**Additional context**
I have talked to Appcenter customer service before but the fix is not in sight

**Comment by vincentcastagna** [comment]
This is an issue that I meet too when building my iOS app and setting autoincrement. Prob is, my pre build script that updates my app version can not find Info.plist when autoincrement is ON.

**Comment by booker-dragon** [comment]
I would suggest to `find` `Info.plist` from `$APPCENTER_XCODE_PROJECT` instead of `.`

And also we can limit the depth of `find` to 2 level by setting `-maxdepth 2`

**Comment by tonyarnold** [comment]
Automatically incrementing all `Info.plist` files seems like a very "unsafe" feature, to be honest. Perhaps it would be better to provide instructions on adding a build phase to your Xcode project to do this for individual targets?

**Comment by DennisPan** [comment]
@tonyarnold Do you mind explaining more on what you mean by "unsafe"?

**Comment by cvo-4tell** [comment]
up

**Comment by gaborvass** [comment]
Hi,
this issue is still happening, are you going to fix it? It is breaking all the apps using frameworks defining version number in their Info.plist file.

**Comment by jdarosaj** [comment]
I'm also having this issue. I'm having to use manual version increment for now.

**Comment by delasign** [comment]
Hello !

I found the fix. The New Xcode Project does not automatically add the following to your info.plist:

Key: Bundle version
Value: $(PRODUCT_BUNDLE_IDENTIFIER)

Please confirm it works for you !
