### ISSUE TITLE
[Feature] Xamarin.iOS extension signing

### ISSUE THREAD

**Issue by lassana** [microsoft/appcenter#30]
**What App Center service does this feature apply to?**
We would like to use VS AppCenter to build our Xamarin.iOS application for iOS devices (Ad-Hoc or AppStore builds, to be technical). Our application includes two iOS extension packages that require additional provisioning profiles to be present during the build process. Unfortunately, at the moment it is not possible: AppCenter allows me to upload only a single provisioning profile:
![](https://user-images.githubusercontent.com/2004960/52179321-1c2c3300-27ea-11e9-8e46-0cb06b463d5e.png)
It was discussed a few times earlier:
- https://github.com/MicrosoftDocs/appcenter-docs/issues/48
- https://github.com/MicrosoftDocs/appcenter-docs/issues/55

**Describe the solution you'd like**
As a solution: adapt the same approach currently you use in native Obj-C/Swift builds: https://blogs.msdn.microsoft.com/vsappcenter/announcing-ios-app-extension-and-watchos-support-in-visual-studio-app-center/

**Describe alternatives you've considered**
As an alternative: do not limit clients with a single provisioning profile.

**Comment by nrajpurkar** [comment]
@lassana thanks for opening this feature request as an issue in this repo. I know it would be great to see the same support for app extensions in Xamarin apps that we have for Obj-C/Swift apps. We'll keep this issue open to track total interest in having this supported.

**Comment by JeroenBer** [comment]
We also really need this. We have a Xamarin app with extensions

**Comment by travisnielsen** [comment]
I need this feature as well. App extensions are a core part of user experience nowadays. Would love to see this prioritized.

**Comment by JeroenBer** [comment]
Can we vote for this somewhere because we cannot build without. Extensions are used by most professional apps.
I don't understand why it would be supported for iOS and not Xamarin.iOS. It feels more and more like MS is letting Xamarin down?

**Comment by gzarkovic-livly** [comment]
We also seem to be hitting the same roadblock, we use an app extension for rich/enhanced notifications. I have also tried many things in Azure DevOps that all seem to fail as well.

Is there anywhere we can vote for this in order to make it a higher priority backlog item?

**Comment by nrajpurkar** [comment]
@JeroenBer @gzarkovic-livly please vote directly on this issue. This repository is helpful for our team to keep tabs on overall interest in feature requests.

**Comment by hytea** [comment]
👍 My team uses xamarin iOS extensions and would like to see support for multiple provisioning profiles built into app center.

**Comment by Carbaholic** [comment]
Same here. We have two apps with extensions and would love to use app center build but cannot until this feature is available.

**Comment by Klim-Shoptagr** [comment]
This feature is also needed for our team. We're using iOS extension too.

**Comment by se** [comment]
Hi guys.

Is there any update? Because we needed it urgent :-/ Sorry but without it App Center doesn't work for us...

**Comment by nrajpurkar** [comment]
@se No update to share at the moment. We've had our hands busy with [other work this month](https://github.com/Microsoft/appcenter/issues/227) and haven't been able to get to this.

**Comment by eclipsed4utoo** [comment]
Please add

**Comment by jessejiang0214** [comment]
Please add, or give us some workaround like from PreBuildScript

**Comment by beeradmoore** [comment]
I run a local jenkins server which gets a web hook from our git, builds the app, and then uploads it to AppCenter for distribution.

AppCenter config screens are so much easier than having to deal with Jenkins. I'd really like to retire this build machine :P

**Comment by brianlanger** [comment]
We had to configure our Xamarin iOS app targets to disable the extension project for testing in appCenter and we can't build there for production at the moment. Would love to have this added so we can stop depending on building locally and have the whole process automated.

**Comment by lassana** [comment]
For everyone who needs this feature: iOS extension signing is possible in Azure DevOps: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=azure-devops

**Comment by dlbroadfoot** [comment]
This is a blocker for us too. We really need support for Xamarin iOS extensions otherwise we need to move away from AppCenter and look at solutions like Bitrise or Azure DevOps

**Comment by rOBloOm** [comment]
i would appreciate this feature!

**Comment by shushilshahukhal** [comment]
Yeah we would like to see this feature coming to AppCenter. It has been a road block for us.

**Comment by ElteHupkes** [comment]
I hate to be another "me too" guy - but yeah clearly App Center build is useless in this form for apps with a share extension.

By the way, can the OP (@lassana) or anyone else rename this issue so the title says "extension" rather than "entension"? It'll make it easier to find (and upvote ;)) for other people.

**Comment by skywalkerlol** [comment]
Stuck in the same boat. Followed the OneSignal push notifications tutorial that appcenter shows as an option. The OneSignal tutorial walks through the iOS extension for notifications. Now my builds are broken because of this limitation. please fix this. Love AppCenter and how it makes things super easy. This would become very problematic. Is there any timeline yet on making this available?

**Comment by patniko** [comment]
We're queuing the work now @skywalkerlol. Will take a bit to get done, but this will be active soon enough.

**Comment by rachael-ross** [comment]
Please, please, please add this feature for Xamarin iOS app extensions.

**Comment by claitonlovato** [comment]
+1 here!

**Comment by meliheran** [comment]
+1 please !

**Comment by olegfresh** [comment]
Can't build Xamarin.iOS with a Siri Shortscuts extension. What's the latest on supporting it?

**Comment by nrajpurkar** [comment]
🚨 We'll be starting implementing support for this very soon! We estimate support for this to come by the end of September.

**Comment by nrajpurkar** [comment]
We've completed support for this! Please try it out, and let us know if you have any feedback 😁

**Comment by beeradmoore** [comment]
> We've completed support for this! Please try it out, and let us know if you have any feedback 😁

I was super pumped to try this but AppCenter appears to be down :( 

![Screen Shot 2019-10-02 at 7 35 20 am](https://user-images.githubusercontent.com/904737/66002720-a9de3080-e4e7-11e9-8781-db15ff5e0362.png)

**Comment by willbuildapps** [comment]
> We've completed support for this! Please try it out, and let us know if you have any feedback 😁

Awesome thanks for the update @nrajpurkar

**Comment by bo3po** [comment]
Did anyone try this? I get the same error as before... Like before the UI sees that I have a extension in my code. I upload the provision profile, appstore ready. The UI seems to forget the profile. I run the build. And I get the same error as before. Any thoughts?

Regards
Bo

**Comment by DennisPan** [comment]
@bo3po could you reach out to support via App Center portal? Would be great to collect more information and dig deeper into what you are seeing

**Comment by bo3po** [comment]
> @bo3po could you reach out to support via App Center portal? Would be great to collect more information and dig deeper into what you are seeing

I have done so. When I get it working I will share it here. Might be something easy. But the error is the same that the build system is unable to find the provision profile even after I have uploaded it. The UI seems to forget the profile also. When I return to the build to see the configuration the profile is gone. No idea why. I can try with another browser. I use Chrome.

**Comment by bo3po** [comment]
Good news! In collaboration we have found the error. Seems to be related to Bitbucket repos. They will fix it soon and deploy the fix...

**Comment by evkhramkov** [comment]
@bo3po thanks for reporting! We deployed a fix, and everything should work fine no. If anyone else experienced similar problems with configuring Bitbucket repositories, please try reconfiguring your branch (you might need to re-upload signing credentials)

**Comment by ElteHupkes** [comment]
I had to adjust my pre-build script some 8 times, but I just managed to build successfully :D.

**Comment by bo3po** [comment]
@ElteHupkes that sound great. is the script something you could share perhaps? What did the trick?

**Comment by ElteHupkes** [comment]
@bo3po These are mostly things very specific to my app (swapping out icons in Info.plist for production/beta builds and stuff). Something I can recommend paying attention to is whether you're building the solution or the project. We have a library with some unsafe code that wouldn't build when selecting the project in the configuration, because the project-level setting allowing unsafe code for the library wouldn't be picked up. When selecting the solution instead, the pre-build file needs to be in the same directory as the solution file, not the project file, that was messing with my brain a bit.

**Comment by bo3po** [comment]
@ElteHupkes Ok. That is probably not relevent for my or other apps. I thought that you might have some provision magic in the file that would allow me to build with an ios extension project. Yes. Support was also asking where the plist was in releation to the csproj file. And that was ok. It was beside on the same folder level.

**Comment by bo3po** [comment]
It's working now thanks to the skilled team at microsoft that helped me diagnose the problem which was something wired with my build configuration on the server. I told the config not to sign. Save the config. And then re-added everything. That reset my config somehow and made it work.

Great support. KEEP IT UP :)

**Comment by Klim-Shoptagr** [comment]
Hi guys, is it possible to add the same logic for building whole *.sln?
Because when I tried to create build of whole solution with iOS project, which contains extension, I faced with the same issue: I can't add more than 1 Provision Profile...

**Comment by skywalkerlol** [comment]
Same for me. Solution doesn’t build. Fails on provisioning profile mismatch

**Comment by bryansmi** [comment]
@Klim-Shoptagr and @skywalkerlol  Thanks for reaching out! We actually intentionally added support for building Xamarin.iOS projects with extensions from `.sln` configuration in App Center. If that isn't working, please open a support ticket with us through Intercom on https://appcenter.ms. We can start looking into it that way.

It'll be helpful to include the file structure of your repository (or if you're extra adventurous, a sample repository with the same structure as your project which reproduces the issue that you can share with us). Something like:

```
.
+-- Foobar.sln
+-- Foobar
|   Foobar.csproj
|   Info.plist
+-- FoobarExtension
|   FoobarExtension.csproj
|   Info.plist
```

We'll have some of this information from telemetry, but oftentimes it's useful to see our issues from the customer perspective as well :) Thanks!

**Comment by ElteHupkes** [comment]
For what it's worth, I'm building from the solution level and for me it's working.

**Comment by skywalkerlol** [comment]
This is what i have

.
+-- Foobar.sln
+-- Foobar
    +-- Foobar.iOS
        | Foobar.csproj
        | Info.plist
    +-- FoobarExtension
        | FoobarExtension.csproj
        | Info.plist

**Comment by dmariogatto** [comment]
For those that are not having their extension detected, ensure that the reference in your container app csproj matches the extension's project Guid exactly.

For example, 
- Extension csproj has a project Guid _`<ProjectGuid>{15A3D6ED-A6FB-46B3-A8E3-204A609AC023}</ProjectGuid>`_
- Container app reference to the extension must also be _`<Project>15A3D6ED-A6FB-46B3-A8E3-204A609AC023</Project>`_

Mine was _`<Project>15a3d6ed-a6fb-46b3-a8e3-204a609ac023</Project>`_, and was not detected.

**Comment by King-of-Spades** [comment]
@dmariogatto For your GUID observations, 
1. Does it work even with the different case locally?
2. You had to modify just the case to get it working in App Center?

I'm double-checking, because if that's correct it sounds like a bug in App Center, notwithstanding you've identified a workaround.

**Comment by dmariogatto** [comment]
@King-of-Spades 

1. Yes, it works with different case in both Visual Studio & VS for Mac
2. Correct

It seems that Visual Studio (Windows) uses the lower casing when creating an extension, while VS for Mac uses upper.

**Comment by softlion** [comment]
@dmariogatto So is a "bug" opened on this either on appcenter or on visual studio ?

**Comment by dmariogatto** [comment]
@softloin Not that I know of... I did have a chat with AppCenter support, who said they were going to fix it in the near future.

**Comment by softsan** [comment]
Any updates on this? Having same issue not showing extension project Provisional profile on iOS project in appcenter.

**Comment by softlion** [comment]
It is fixed sinced a long time. AppCenter does not discover your extension. Look at appcenter doc on why it does not discover your extension.

**Comment by softsan** [comment]
Its a xamarin.ios project it was showing couple of days ago but not now.

**Comment by King-of-Spades** [comment]
@softsan It sounds like the original issues discussed in this thread, even if similar to what you're encountering, were confirmed addressed. So I'd recommend reaching out to the App Center Support channel directly. You can feel free to cite this issue to say "my symptoms look similar to this," though I recommend giving as much detail as reasonable as well as any relevant data to support it. 

That way the support team has the best chance of being able to accurately identify and help with your issue. 

You can find the support form in the App Center portal in the upper right hand corner **? > Contact Support**

**Comment by softsan** [comment]
@King-of-Spades Okay thanks. I've created a support ticket with AppCenter.
