### ISSUE TITLE
Provide feature to download a report of user's who had downloaded the app

### ISSUE THREAD

**Issue by Ravikant02** [microsoft/appcenter#304]
It just gives me information about unique downloads and total downloads for every releases. Can you please provide a way that I can download that data or report?

**Comment by botatoes** [comment]
Thanks for the suggestion. We'll look into this but what kind of info would you want?

**Comment by Ravikant02** [comment]
If you can give few detail like user email address, OS version for their mobile, mobile model details, country etc then that's more enough.

**Comment by l3ender** [comment]
Starting with just the user details (name/email) would be a great start. This is comparable to Test Flight which shows users and which build they have most recently downloaded (and when).

**Comment by KRA2008** [comment]
HockeyApp also did this.

**Comment by brentonhouse** [comment]
@botatoes - Should this be added to the roadmap here as it was a popular feature in HockeyApp? https://github.com/Microsoft/appcenter/wiki/Roadmap

**Comment by awray** [comment]
Would love an update on this - it's incredibly useful to be able to see who has which version installed (and who hasn't installed at all). Thanks!

**Comment by leehu** [comment]
Hi, really want this feature too. thx

**Comment by l3ender** [comment]
Not stale.
