### ISSUE TITLE
Question: Does this service support real-time, interactive testing, with phone calls, on normal Android apps?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [microsoft/appcenter#306]
We need to decide if we can use this service or not.
I can't find anywhere to ask this, and I can't find an email address to send to.

My question:
We already have an Android app working (made APK file), and we want to test it ourselves (without automatic tests) , live and in interactive way, including phone calls (incoming and outgoing).

Is it possible using this service?

**Comment by Oddj0b** [comment]
Hi @AndroidDeveloperLB,

Unfortunately, we do not support a scenario where you lock a  device and use it through the browser. Our focus is on automated testing using Appium, Espresso, Xamarin.UITest, or XCUITest.

**Comment by AndroidDeveloperLB** [comment]
I don't understand what you mean by "lock a device and use it through the browser" , but according to what you wrote later, I think you mean that you provide only automatic tests.
Is that right?

**Comment by Oddj0b** [comment]
That is correct we only support automatic tests.

**Comment by AndroidDeveloperLB** [comment]
OK thanks
