### ISSUE TITLE
Android HockeyApp: Sort By Date

### ISSUE THREAD

**Issue by dfbarone** [microsoft/appcenter#307]
**Describe the solution you'd like**
As an MS AppCenter user I would like to sort builds by 'date' instead of 'version number'. AppCenter only shows the 20 most recent builds available and If I want to access older builds I am not able to. 

**Describe alternatives you've considered**
Other options such as search functionality can also help with the above case.

**Comment by botatoes** [comment]
@dfbarone, is this an origin HockeyApp app? If so there is a limitation for how many builds you can see. As for the sorting, this is already in our backlog. Thanks for the suggestion though, I'll see about this getting prioritized even more.

**Comment by dfbarone** [comment]
@botatoes Yes, I am currently using the HockeyApp to access my AppCenter/HockeyApp builds. At the moment sorting is more important to me than increasing the total number of visible builds. It sounds like this feature request already exists so you can probably close this issue. Thank you.
