### ISSUE TITLE
Drop support for Xcode 8 and 9 in the App Center SDK

### ISSUE THREAD

**Issue by elamalani** [Microsoft/appcenter#308]
App Center team is launching two new mobile backend services – [Auth](https://github.com/Microsoft/appcenter/wiki/Roadmap#identity) and [Data](https://github.com/Microsoft/appcenter/wiki/Roadmap#data-sync) on May 6. With these services going live in a few weeks, we have decided to drop the support for Xcode 8 and 9 and bump the SDK major version to 2.0.0. Going forward, all the new features, bug fixes, and SDK updates will be supported on this major version. You can continue to use the older SDK versions, but the new services won’t be supported, and we won’t make any fixes on those versions.

**Upcoming changes in SDK v2.0.0**
* New SDK modules for Auth and Data services 
* Drop support for Xcode 8 and 9 

This is a heads up so that you can prepare for the upcoming SDK version change to modify your apps accordingly.

**Comment by patniko** [comment]
This is shipping in the next release early May.
