### ISSUE TITLE
Integrate application logs to Azure ELK and EventHubs - companies need the event logs for user data to be integrated with Azure ELK or EventHubs

### ISSUE THREAD

**Issue by swathisuvarna1** [microsoft/appcenter#310]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hamswan** [comment]
Thanks for opening this, would you mean sharing some specific use cases.

**Comment by swathisuvarna1** [comment]
I was requested to add all the analytics logs to Azure Eventhubs or Azure ELK. Is this possible?

**Comment by hamswan** [comment]
@swathisuvarna1 Appcenter Analytics data can be exported to Application Insights or Azure Blob. In order to add the analytics data to EventHubs , you need to export from AI, but this is a two step export not the most ideal. I would like to understand your requirement more better.

**Comment by hamswan** [comment]
@swathisuvarna1 Can you share your specific use cases? If it is easier you can email me hamsab@microsoft.com?

**Comment by swathisuvarna1** [comment]
my team is looking to export all appcenter logs specific to some of our apps into Azure ELK or Azure EventHubs. My team doesn't want to use the export to Blob or App Insights option. What is the easiest way to get some of the logs like login and some other event specific data logs into Azure EventHubs or Kibana?

**Comment by swathisuvarna1** [comment]
We'd like to track the number of logins on the app and the device details as part of logging. Does this help as a use case?
