### ISSUE TITLE
Removing a version from the dropdown is not a feature on App Center

### ISSUE THREAD

**Issue by amrutha786** [Microsoft/appcenter#312]
**Removing a version from the dropdown is not a feature on App Center** 
Even after I delete a version from Releases, I still see the version number in the dropdown in Analytics OverView & Events. 

Would like to see that deleted/ have an ability to delete the Version number from the dropdown.

**Comment by patniko** [comment]
Hi @amrutha786, the values in that drop down come from events that are stored and not the release list in the distribution service. Developers can pick and choose what services they want to use in App Center so we will more than likely always keep these separate. Versions in the drop down should auto-purge when all their events exceed the 90 day retention period.
