### ISSUE TITLE
Allow storing build scripts somewhere other than the project root

### ISSUE THREAD

**Issue by tonyarnold** [microsoft/appcenter#313]
I'd like to be able to hide my CI/build scripts away from the root directory, purely so it doesn't become too cluttered. Other services allow using hidden directories like `.github` and `.buildkite` - it'd be great it AppCenter could search for the various pre/post scripts in `.appcenter` (or allow us to specify an alternate, customisable location).

**Comment by phoney** [comment]
I also would like the build scripts to be able to go into another folder but I don't particularly want it to be hidden. I'd prefer bin/ or app center/ at the root of the project.
