### ISSUE TITLE
Support tests for macOS targets

### ISSUE THREAD

**Issue by tonyarnold** [microsoft/appcenter#314]
One of the documented limitations of macOS targets is that AppCenter doesn't support testing. I could really use this - could you consider adding it, please?

**Comment by Oddj0b** [comment]
Hi @tonyarnold,

Can you elaborate on why the tests in our Build system isn't enough? 
https://docs.microsoft.com/en-gb/appcenter/build/macos/first-build#35-tests

**Comment by tonyarnold** [comment]
It's right there in your documentation: 

> App Center does not support launch tests for Mac builds.

That's… pretty much all testing on macOS, isn't it?

**Comment by tonyarnold** [comment]
It also appears that iOS targets get a dedicated Test tab in the AppCenter UI. That doesn't seem to appear for macOS targets. 

I'm looking for parity of features, and support for all testing approaches in a macOS-based project.

**Comment by Oddj0b** [comment]
I understand. The Test tab for iOS and Android is for UI testing on real devices, and no other operating systems are supported. The launch test is a UI test that runs on a random device and asserts if the app can start.
But running unit tests with XCTest in Build is still a possibility, for MacOS.
If you have a use-case for cloud UI testing for MacOS I would love to hear about it.

**Comment by charlesroddie** [comment]
> @Oddj0b If you have a use-case for cloud UI testing for MacOS I would love to hear about it.

This question is strange. The use case is the same for Mac OS and Windows as it is for iOS and Android. It makes sure that app functions work automatically which makes releases a lot safer. We pay for App Center UI testing, for a Xamain Forms app, but only supporting 2 of the 4 OSes we deploy to makes a limited and IMO overpriced service.
