### ISSUE TITLE
Push notifications to web apps

### ISSUE THREAD

**Issue by jsprklst** [microsoft/appcenter#315]
**Describe the solution you'd like**
Push notification support for web apps. Either with integrated support (which I noticed is a stretch goal on the roadmap) or through Firebase.

**Describe alternatives you've considered**
Use Firebase directly instead of App Center.

**Additional context**
Firebase provides push notifications for web apps out-of-the-box. Notifications sent from App Center to Android apps through Firebase are not sent to web apps linked to the same Firebase project.

**Comment by jwargo** [comment]
@jsprklst thanks for suggesting this. Push to browser is definitely something we want to add to the Push service.

**Comment by jwargo** [comment]
@jsprklst I'm working on a proposal for this now, would you (or anyone else watching) be interested in having a Teams conversation with me about the requirements for this feature? I'm curious about your use cases and how you would see this service working.

**Comment by jsprklst** [comment]
Sure, no problem! How do we setup a meeting?

**Comment by jwargo** [comment]
send me an email at my first dot last at Microsoft dot com and we'll work it out.

john.wargo

**Comment by jwargo** [comment]
If anyone's interested in this feature, please vote here for this and reach out to me privately to arrange a discussion about the app or apps you're building that need this feature. I want to make sure I know as much as possible about your needs as we craft the requirements for this feature.

**Comment by jwargo** [comment]
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

The good news is that this is a highly requested feature and it solidly on the Notification Hubs roadmap.
