### ISSUE TITLE
Analytics - Support Xamarin Track Screenviews

### ISSUE THREAD

**Issue by mhalt** [microsoft/appcenter#316]
It would be nice to be able to track screen transitions to events in App Center without having to create custom events. Products like Google Firebase already offer this feature. 

If your app uses a XAML page for each screen, App Center Analytics should be able to automatically track every screen transition and generate a report of user engagement broken down by screen.

**Comment by KSemenenko** [comment]
Or you can add special type of event "TrackScreenView" or "TrackView"

**Comment by KSemenenko** [comment]
@annakocheshkova I really need this function, now I use just events, maybe I can help you with the realization of this function?

**Comment by mhalt** [comment]
> @annakocheshkova I really need this function, now I use just events, maybe I can help you with the realization of this function?

That would be nice.
