### ISSUE TITLE
Webhooks on test completion

### ISSUE THREAD

**Issue by caiofbpa** [microsoft/appcenter#318]
**Describe the solution you'd like**
I want to start a Webhook when a test run succeeds or fails.

**Describe alternatives you've considered**
Right now the only way to check whether a test has passed or not is through the UI or consuming an API.

**Additional context**
In the end I want the test result to be posted to a Slack channel, and a Webhook is maybe a more flexible way to do just that.

It could work just like the Build trigger:

<img width="574" alt="Captura de Tela 2019-04-12 às 14 44 17" src="https://user-images.githubusercontent.com/507356/56056053-8228bf80-5d31-11e9-91d5-4f980429ff40.png">

With a trigger for when the test succeeds and another for when the test fails, with a link to AppCenter's page to see more details about the test run.

**Comment by jdpennell** [comment]
I too would greatly appreciate this feature. We've had some luck with e-mail signals and IMAP-IDLE, but of course setting up an IMAP email account is a lot of overhead and introduces an unneeded fault point, and our system will break completely if test run IDs stop showing up in the URI that shows up in emails, which makes this solution unacceptably fragile.

**Comment by luisresende247** [comment]
Any updates on this?

Thanks

**Comment by Oddj0b** [comment]
@luisresende247 Sorry, we haven't committed to a timeline yet.

**Comment by peduardo25** [comment]
I do appreciate this feature. It is something we really need

**Comment by RaghadSy** [comment]
Any updates on this?

Thanks

**Comment by 4ntoni4** [comment]
We would also very much appreciate this feature!

**Comment by sakthiyuvaraj** [comment]
This will be a very handy feature. Please let me know if this is in the roadmap.

**Comment by Naweap** [comment]
I would also very much appreciate this feature ! Any updates ?
