### ISSUE TITLE
Build fails with React hooks RN 0.59.3

### ISSUE THREAD

**Issue by shivrajkumar** [microsoft/appcenter#319]
### **Description**

App center build fails after upgrading to RN 59 and using react hooks

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Use React hooks with useState from react for the components

### **Details**

1. Which version of the App Center SDK are you using?
    - 1.5.0
2. Which OS version did you experience the issue on?
    - Android 8.1.0, iOS 11
4. What third party libraries are you using?
    - example

output:

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Place output here

```
N/A: version "N/A -> N/A" is not yet installed.

You need to run "nvm install N/A" to install it before using it.
Now using node v8.10.0 (npm v5.6.0)
default -> node8 (-> v8.10.0 *)
##[error]Bash wrote one or more lines to the standard error stream.
```

**Comment by nrajpurkar** [comment]
@shivrajkumar sorry for the late response here. Are you still experiencing this issue?

**Comment by DennisPan** [comment]
@shivrajkumar I'm closing this. If you are still experiencing the failure, I'd suggest reach out to App Center support so that we can take a deeper look at your app.
