### ISSUE TITLE
Additional options when deploying from App Center to Google Play

### ISSUE THREAD

**Issue by dj-dev** [microsoft/appcenter#320]
**Describe the solution you'd like**
When deploying an Android app directly from App Center to Google Play, we would like an option in App Center for "Rollout to production". Currently when deploying an app from App Center to Google Play, the release is automatically rolled out to production. This is not the desired behavior since we often upload the binary in advance to see if it passes the automated checks. And we often need to release the app to market at a specific time which is why we need to control the "Rollout to production" option from Google Play.

**Describe alternatives you've considered**
Manually downloading the APK from App Center and uploading to a new release that was manually created in Google Play developer console.

**Additional context**
The feature request is an Android equivalent of the iOS request we created here: https://github.com/Microsoft/appcenter/issues/297

**Comment by Libranner** [comment]
+1

**Comment by winnicki** [comment]
+1

**Comment by dj-dev** [comment]
Hi @Oddj0b, does it look likely that this solution will be implemented any time soon? We have an internal ticket open waiting for this functionality. Thanks

**Comment by RachelNaane** [comment]
Hope to see some progress with this issue
