### ISSUE TITLE
Post Build Script was ran when Build Failed

### ISSUE THREAD

**Issue by kuyazee** [Microsoft/appcenter#321]
**What App Center service does this affect?**
Build

**Describe the bug**
I updated my repository's directory structure and forgot to set the new location for the `.xcwokspace`. Since the setup is built to run on every push, app center ran the Build.

**To Reproduce**
1. Create an Xcode project link it to App Center
2. Setup the build settings
3. Place the Xcode project in a different directory.
4. Run the build
5. The post build script will run

**Expected behavior**
 The post build script should not run if the build failed

**Screenshots**
<img width="895" alt="Screen Shot 2019-04-16 at 1 58 37 PM" src="https://user-images.githubusercontent.com/17846698/56185328-c37ddf80-604f-11e9-87d2-c199fd63acdb.png">

**Desktop:**
 - OS: Mac OS 10.14.4
 - Browser Safari
 - Version 12.1

**Comment by lumaxis** [comment]
@kuyazee Thanks for the report but this is actually intentional. Some people want to run certain code, even if the build failed.
If you want your code to only run if the build actually succeeded, you can use a gate like this in your post-build script:
```bash
if [ "$AGENT_JOBSTATUS" == "Succeeded" ]; then
 …
fi
```

**Comment by kuyazee** [comment]
Thank you so much for the reply, I'm not sure if this is in the documentation I haven't checked in a while. If not please consider placing this on the documentation.

**Comment by lumaxis** [comment]
Good idea, we'll look into that. Thanks! 🙂
