### ISSUE TITLE
Ability to add user that not accepted invite yet to teams

### ISSUE THREAD

**Issue by ufna** [microsoft/appcenter#322]
**Describe the solution you'd like**
I've sent invites to users and I want to add them to team immediately.

**Describe alternatives you've considered**
Now I have to wait until users accept invite. And there is no notification about it, so I had to wait manual request from them.

**Comment by blparr** [comment]
Hello, we are considering some changes to the concept of teams and shared distribution groups, which will cover your scenario. Once we finish our current investigations, we will have a more concrete timeline.

Thank you!

**Comment by Slin** [comment]
Just wanted to say that this is the part that is quite annoying when adding someone as I need to wait for them to signup and tell me that they did before I can add them to a team.

This would improve the onboarding of new team members quite a bit.

**Comment by adamkhazi** [comment]
I have run into the same issue.
