### ISSUE TITLE
The dashboard only shows older versions of our app on mobile devices

### ISSUE THREAD

**Issue by hannes1991113** [microsoft/appcenter#323]
**What App Center service does this affect?**
This is about the downloadable versions of our app on the dashboard, but only on mobile devices.

**Describe the bug**
The newest version of our app on the dashboard is months old, although we upload new versions almost every day. The weird thing is that this only happens in the HockeyApp app or the mobile website. If you instruct the browser to get the desktop version of the website, the newer versions appear.
On the App Center website it's a mixed bag. Some devices show the newest versions, some not even if you request the desktop website.
If the bug appears, the version that is wrongfully shown as the newest is always from the 30th January, maybe this date has something to do with it. 

**Expected behavior**
The available verisions of our app should be the same, no matter if you use the HockeyApp app, the mobile website or the desktop website.

**Comment by botatoes** [comment]
Hello, can you please open an intercom ticket for this bug so someone on DRI can take a look at this? The intercom button is on the lower right-hand corner of the appcenter.ms website. 

Closing this.
