### ISSUE TITLE
Add XUnit Support for Xamarin.UITest

### ISSUE THREAD

**Issue by brminnick** [microsoft/appcenter#329]
**Describe the solution you'd like**
Give developers the option to use XUnit as a test framework for Xamarin.UITest.

Xamarin.UITest is currently limited to NUnit.

**Describe alternatives you've considered**
NUnit is currently the only alternative

**Additional context**
XUnit is one of the most popular test frameworks for .NET developers. The [XUnit NuGet package](https://www.nuget.org/packages/xunit) has over 33 Million downloads to date (compared to [NUnit's](https://www.nuget.org/packages/NUnit/) 39 Million downloads).

**Comment by Juansero29** [comment]
Is there any date for when this will be available for Xamarin developers?

**Comment by Oddj0b** [comment]
I'm the program manager responsible for App Center Test and I'm working on a new idea which will support more frameworks in Test, allow unit testing, and browser testing. I would like to talk to you about it and understand your needs better.

Below is a link where you can sign-up for a 30-minute call with me. The agenda will be about the value of testing for you and your organization, and my new idea to allow more frameworks and testing styles in App Center Test.

Link to choose https://calendly.com/vigimm/appcenter-test

**Comment by sharwell** [comment]
@Oddj0b Please feel free to loop me in if this type of testing flexibility is new for you. I've participated in a number of similar efforts in the past and may be able to spot areas in the design where we can avoid future problems.

**Comment by vincentcastagna** [comment]
Hello all,

Some updates about this feature request ? I would also like to run my unit test in a appcenter-post-build.sh script with the dotnet test command. 

Regards.

**Comment by sasivishnu** [comment]
any update on this?

**Comment by glucaci** [comment]
any news ?

**Comment by adamhill** [comment]
@brminnick  @Oddj0b Any progress on this request?
