### ISSUE TITLE
[AppCenter Web] Promote overlay include rollout percentage

### ISSUE THREAD

**Issue by nspector** [microsoft/appcenter#330]
**Describe the solution you'd like**
When I am promoting on codepush, I do not have the ability to set rollout percentage on the UI. Would like to have that, currently it goes 100% no matter what.

**Describe alternatives you've considered**
I believe this is possible from CLI

**Additional context**
![image](https://user-images.githubusercontent.com/1923696/56326858-98b58900-612c-11e9-9dff-8d799a722371.png)

**Comment by botatoes** [comment]
Thanks for the suggestion. This is already on our backlog. Will update when this is prioritized.

**Comment by peltax** [comment]
Why is it closed? This is not implemented.
