### ISSUE TITLE
Add Application Name to the application details

### ISSUE THREAD

**Issue by pirhano** [microsoft/appcenter#331]
To distribute an application you will need a full application name format and it confusing with the display name, and its only available from the url or CLI.

**Describe the solution you'd like**
I believe its highly important to add it to the Application details somewhere under the "application display name".
When you go to the Settings > App details. i Think its the right place for it

**Comment by blparr** [comment]
Thanks for describing your issue. We'll consider it for future improvements.

Thank you!
