### ISSUE TITLE
Add NUnit as a NuGet Dependency to the Xamarin.UITest NuGet Package 

### ISSUE THREAD

**Issue by brminnick** [microsoft/appcenter#332]
**Describe the solution you'd like**

NUnit should automatically be installed when the [Xamarin.UITest NuGet Package](https://www.nuget.org/packages/Xamarin.UITest/3.0.0-dev1). 

**Describe alternatives you've considered**

Today, developers who add the Xamarin.UITest NuGet Package must manually add the NUnit NuGet Package to the same csproj. 

This creates a poor onboarding experience for developers who are new to Xamrain.UITest who may not know that Xamarin.UITest has a dependency on NUnit and to know which version(s) of NUnit is/are compatible with Xamarin.UITest. 

**Additional context**
[To add a dependency to NUnit](https://docs.microsoft.com/nuget/reference/package-versioning#examples), add the following  to the Xamarin.UITest nuspec file:

    <dependencies>
          <dependency id="NUnit" version="3.11.0" />
    </dependencies>

Currently, the Xamarin.UITest NuGet package says it has "No Dependencies" which is misleading.
<img width="952" alt="Screen Shot 2019-04-18 at 9 42 07 AM" src="https://user-images.githubusercontent.com/13558917/56377068-5a68aa00-61be-11e9-91ae-b540b934ea72.png">

**Comment by Oddj0b** [comment]
Hi @brminnick,

this is by design as Xamarin.UITest doesn't have a hard coupling with NUnit or a specific version of NUnit. And because of the loose coupling we are not interested in forcing anything on the users.

**Comment by brminnick** [comment]
My goal is to create a better onboarding experience when developers add the Xamarin.UITest NuGet package to their project for the first time. We are unfairly putting the onus onto the developer to know exactly which testing frameworks are supported, and exactly which versions of those testing frameworks are supported.

I'm also curious to understand more about the impact of adding a NuGet dependency to NUnit:
- Which other frameworks does Xamarin.UITest support?
  - Can developers use XUnit? ([This is the 8th most requested feature when sorting AppCenter Issues by '👍'](https://github.com/Microsoft/appcenter/issues/329))
- How many developers are using Xamarin.UITest without NUnit?

Both the [Microsoft docs](https://docs.microsoft.com/appcenter/test-cloud/uitest/?WT.mc_id=none-github-bramin) and [Xamarin University](https://university.xamarin.com/classes/track/testing#xtc101-intro-to-testing) explicitly state that NUnit 2.6.3 or 2.6.4 must be used with Xamarin.UITest:

> Xamarin.UITest is a testing framework that enables Automated UI Acceptance Tests written in C# using the NUnit unit testing framework to be run against iOS and Android applications.... Xamarin.UITest is the Automation Library that allows the NUnit tests to execute on Android and iOS devices.... Xamarin.UITest requires NUnit 2.6.3 or 2.6.4 to run tests. Xamarin.UITest is not compatible with NUnit 3.x.

The Xamarin community is also following this recommendation, using NUnit for their Xamarin.UITest framework. Here are the top google search results for Xamarin.UITest:
- https://www.jimbobbennett.io/ui-testing-your-xamarin-apps/
>  Xamarin UITest is based off a testing framework called Calabash which was written in Ruby and is fully open source and maintained by Xamarin. UITest is a layer on top of this that allows you to write your tests in C# and run them using NUnit
- https://medium.com/@frankiefoo/xamarin-forms-how-to-perform-automated-ui-test-254a01c87648
> Xamarin.UITest project requires NUnit 2.6.3 or 2.6.4 to manage & run the test, and is incompatible with NUnit 3
- https://medium.com/@gavination2/automated-ui-testing-with-xamarin-uitest-and-the-page-object-pattern-53bd9541cb27
> Xamarin.UITest is an automated testing framework based on Calabash that allows developers to write acceptance tests written in NUnit. Calabash is the core framework written in Ruby that enables developers to write Automated UI Acceptance Tests. Finally, NUnit is a unit-testing framework for .NET-based languages. Developers can use NUnit and Xamarin.UITests to run tests against iOS and Android applications.
- https://www.youtube.com/watch?v=3x7chLZv-UY
> Xamarin.UITEst is a testing framework that enables Automated UI Acceptance Tests written in NUnit

**Comment by brminnick** [comment]
Another way we can improve the onboarding experience is to include a [`readme.txt` in the NuGet Package](https://docs.microsoft.com/nuget/create-packages/creating-a-package#adding-a-readme-and-other-files) that displays text when the NuGet package is added to let the users know the recommended test frameworks and which versions are supported. The [Xamarin.Essentials NuGet package currently does this](https://github.com/xamarin/Essentials/blob/master/nugetreadme.txt) to help developers add the required code to their `MainActivity.cs`

**Comment by brminnick** [comment]
<img width="580" alt="Screen Shot 2019-07-24 at 5 47 44 PM" src="https://user-images.githubusercontent.com/13558917/61837794-2d6e0800-ae3b-11e9-867a-be619a23d36a.png">

From the #test-cloud channel in the Xamarin Chat Slack: https://xamarinchat.slack.com/archives/C06DTEX0S/p1563917077000800

**Comment by King-of-Spades** [comment]
@brminnick As of Xamarin.UITest 3.0 and higher, the latest version of NUnit is now supported. The messages you cite were accurate for many years though about the maximum versions supported. 

In this sense, I agree that it should probably be clearer that users can use NUnit 3.
