### ISSUE TITLE
Misleading build status

### ISSUE THREAD

**Issue by mattleibow** [microsoft/appcenter#333]
**Describe the solution you'd like**
It would be better if the build status / branches more accurately displayed the build status. When I click the "Build" section on the sidbar, the build log appears to have build all the latest code. But, when clicking on that branch, I can see the build has not actually run for the latest commit.

I attached some images, the first is the deafult view when selecting the build section. The second is when I click on a particular branch. THe third is after I click build now.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Build view:
![image](https://user-images.githubusercontent.com/1096616/56387365-2d0b1300-6235-11e9-9dd3-d7b7492c2bd8.png)

Detail view:
![image](https://user-images.githubusercontent.com/1096616/56387390-3a280200-6235-11e9-9d0d-5ba8ab9fed5a.png)

After build now:
![image](https://user-images.githubusercontent.com/1096616/56387405-490eb480-6235-11e9-9e48-c609d90261c6.png)

**Comment by nrajpurkar** [comment]
Hi @mattleibow, is this for a build that doesn't build on push and build on you manually clicking the button instead? The color coding shows status for the latest build that ran. If you're not building on every push, then this may not be the latest commit.
