### ISSUE TITLE
xcode10.2  issue

### ISSUE THREAD

**Issue by sinss** [microsoft/appcenter#334]
iOS Xcode10.2 will force running pod install , but the project didn't use cocopoads

**Comment by nrajpurkar** [comment]
Thanks for reporting this @sinss. Do you have any more information here? Any repro steps?

**Comment by DennisPan** [comment]
Close this as we don't have more information to investigate. I just tried a new build with Xcode 10.2.1 and don't see cocoapods used. Doesn't look like a common issue. Feel free to reach out to support (the blue chat bubble at bottom right corner) with which we can take a deeper look.
