### ISSUE TITLE
Archive Analytics to AWS 

### ISSUE THREAD

**Issue by jdeitchler** [microsoft/appcenter#337]
Is there a way to setup a Custom Connection to our instance of AWS.
I appears that is only points to and Azure instance.
Let me know if this is the case?

Thanks
Jason Deitchler
jason.deitchler@pfhq.com
763-370-2006

**Comment by patniko** [comment]
Hi @jdeitchler, we don't currently support this without exporting to Azure first. Will convert this to a feature request to track additional interest.

**Comment by kavithachandramohan-okta** [comment]
Any update on this feature request? or any recommendation on how data can be exported to Aws or inhouse data lake?

**Comment by bplattenburg** [comment]
I'd also be interested in any movement on this (or even a guide on the double export path if Azure needs to be the first export step here)
