### ISSUE TITLE
[Bug] Root Gradle build script prevent Appcenter from detecting Android build type

### ISSUE THREAD

**Issue by lacasseio** [Microsoft/appcenter#34]
**Describe the bug**
Given a react native application, having a root Gradle build script which `includeBuild` (composite build) the `android` build cause appcenter to not detect properly the build type of android application thus breaking the UI.

**To Reproduce**
Create a root Gradle build at the base of a react-native application.

**Expected behavior**
Appcenter should parse the build properly and identify the build type for the android application.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lacasseio** [comment]
Appcenter should be using the tooling API for parsing the build properly.

**Comment by patniko** [comment]
Is this issue part of [#35]? Happy to triage, but want to make sure there is only one thread.

**Comment by lacasseio** [comment]
I would say it's two issues. The other one was worked around by avoiding the plugin block. This issue seems to be related to detecting the android project by detecting where the `gradlew` script is located. This is an issue as we are actively trying to centralized around Gradle for automation and the proper detection is failing (aka not detecting any build types). So far, if I remove the wrapper script from the root the detection seems to be working.

**Comment by lacasseio** [comment]
To help to reproduce, the project is configured as `package.json` with `gradlew` script side-by-side to the `package.json` file.

**Comment by nrajpurkar** [comment]
Hi @lacasseio thanks for bringing this to our attention. We're taking a look at this and will update here.

**Comment by bryansmi** [comment]
Hey @lacasseio, this limitation is very similar to the limitation we have in issue #35 (see @ranterle's response here: https://github.com/Microsoft/appcenter/issues/35#issuecomment-462903407).

Thanks for bringing this to our attention! These issues will inform our discussions regarding our Android repo analysis.
