### ISSUE TITLE
Active Devices count has to be reset.

### ISSUE THREAD

**Issue by wolfcode** [microsoft/appcenter#342]
**What App Center service does this affect?**
This is common problem

**Describe the bug**
Active Devices count under Distribute > Code Push > Active Devices(table column)
This is the count of the sessions, this keep increasing. when we do code push by default It applies to bigger set of people.

**To Reproduce**
Distribute > Code Push > Active Devices(table column)

**Expected behavior**
Active Device count should re-evaluated based on active(last) session count.

**Screenshots**
![image](https://user-images.githubusercontent.com/2655300/56711313-d8412e00-6747-11e9-9564-72295ae69616.png)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
 NA

**Additional context**

**Comment by amchew** [comment]
Thanks @mahe-m for the screenshots and feature request! @botatoes could you please take a look?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
