### ISSUE TITLE
iOS 12.2 new Certificate installation flow

### ISSUE THREAD

**Issue by henriqueranj** [microsoft/appcenter#343]
**Describe the solution you'd like**
Now, in iOS 12.2 any certificates downloaded via a website or email needs to be manually installed with the Settings app. The AppCenter Installation webpage should give better instructions to the tester when adding their device.

Currently testers get very confused over why they cannot install the certificate and do not understand the iOS popup stating "Profile downloaded - Review the profile in Settings app if you want to install"

**Describe alternatives you've considered**
It would be a big improvement if the App Center installation website would should a message before/after telling the iOS 12.2 user how to install the Certificate in the Settings after it is downloaded.

**Additional context**
Currently the users with iOS 12.2 must do the following to install an iOS build from AppCenter:
1. User opens App Center Install webpage in Safari.
2. User presses `Add Device` button
3. User accepts to download Certificate
4. NEW: The device shows the message "Profile downloaded - Review the profile in Settings app if you want to install". Note: The profile will only be kept for 8 minutes. If a profile is not installed within 8 minutes of downloading it, it is automatically deleted.
5. NEW: User opens the `Settings `app
6. NEW: Usergoes to `Profile Downloaded`
7. NEW: Tap on AppCenter certificate
8. Press install and confirm
9. User is brought back to the App Center Installation page
10. User can finally have their device added and install apps.

**Comment by botatoes** [comment]
Thanks for the suggestion. I filed a bug for this. We will get this fixed soon.

**Comment by mertnesvat** [comment]
In my case it didn't install the certificate instead it opens website directly, and I've tried with different phones

**Comment by sdermanffs** [comment]
I have the same issue.  Touch install on the cert/profile takes me to the website.  Doesn't install the cert/profile.
iOS 12.4.1
