### ISSUE TITLE
[codepush] Show original_deployment and original_label in web UI and CLI

### ISSUE THREAD

**Issue by maxschmeling** [microsoft/appcenter#344]
**Describe the solution you'd like**
I would like  to be able to determine the original source for a release when using the web UI and when using the CLI.

When a release is promoted, it gets a new label under the new deployment name. The API will return `original_deployment` and `original_label` fields to say where it was promoted from, but I don't see those anywhere outside of the API.

**Describe alternatives you've considered**
Manually querying the API to get the information.

**Additional context**
I'm really trying to figure out how to easily determine the exact git tag matches which CodePush release. I'm uploading releases to my `Staging` deployment and tagging github with `{appname}/{appversion}-{codepushlabel}` but once it is promoted to the `Production` deployment it becomes more cumbersome to match it up to the git tag because I have to figure out which label it came from originally.

**Comment by botatoes** [comment]
Thank you for the suggestion. Will take this into consideration for future code push improvements.
