### ISSUE TITLE
Support metadata for exceptions

### ISSUE THREAD

**Issue by novalain** [microsoft/appcenter#345]
**Describe the solution you'd like**
Currently App Center treats unhandled exceptions as errors and there is no way to attach metadata (.jpeg, .txt) or any other relevant information to these.

In our project we consider unhandled exceptions as crashes (where we make Unity trigger a real crash through the `Fast but no Exceptions` option in ther Player settings). This does not play well with App Center as all these crashes gets lumped together into a single `SIGABRT` with no meaningful call stack or info.

What we'd like is the possibility to consider unhandled exceptions as crashes with relevant call stacks and be able to attach metadata to these, alternatively treat crashes, exceptions and errors differently.

**Describe alternatives you've considered**
Some sort of hack to first catch the unhandled exception in `ShouldProcessErrorReport` and then override the unmeaningful crash data with the callstack/id of the exception together with metadata in `GetErrorAttachments` - when Unity triggers the crash.

**Additional context**
To clarify, what we'd like to see in the dashboard:
`Crashes` -> Here goes pure native crashes and crashes triggered by Unity with relevant info/callstack/metadata.
`Errors` -> Log errors, exceptions.

Or something like:
`Crashes` -> Pure native crashes, possible to add metadata
`Exceptions` -> All exceptions, possible to add metadata
`Errors` -> Errors with no metadata. 

Further note: In HockeyApp we could actually attach a metadata blob to unhandled exceptions which does not seem possible in App Center.

**Comment by winnieli1208** [comment]
@novalain can you elaborate on how App Center treats your unhandled exceptions as errors? App Center distinguishes handled vs. unhandled exceptions as errors vs. crashes for Xamarin and Unity apps and they should visually be different. Are you seeing your crashes listed as errors?

You can attach a binary or text [attachment](https://docs.microsoft.com/en-us/appcenter/diagnostics/features#attachments) to your crash reports or [customize properties](https://docs.microsoft.com/en-us/appcenter/diagnostics/features#key-value-pairs) for your handled errors.

**Comment by novalain** [comment]
Hi @winnieli1208, thanks for your response. If what you say is correct then that is exactly the behaviour we want. I've attached a screenshot showing three errors (two log errors and one exception) and a crash generated by `Crashes.GenerateTestCrash()` 
![exception](https://user-images.githubusercontent.com/7224052/56807527-693f0480-682f-11e9-9882-bc2b3fd88548.png)

Here you can see that the unhandled exception is shown as en error and not a crash. 

Further, your documentation says:

> By default, the App Center SDK doesn't report unhandled exceptions thrown in your app that don't cause a fatal crash. To enable this functionality, call the following method: Crashes.ReportUnhandledExceptions(true);

This only seems to send the unity logs to AppCenter as errors, nothing else. This is very confusing - how can I get my unhandled exceptions to be sent to AppCenter as crashes?

**Comment by winnieli1208** [comment]
@novalain thanks for the additional details. As you mentioned in your note, Unity puts a catch-all around unhandled exceptions. So even though these might be considered "crashes", the application never actually exits so our SDK treats these exceptions as handled (or errors). I understand this might not be an ideal experience and unfortunately this is a unique limitation for Unity apps. I'll update our docs to make this more clear. 

As for your feature request on handled errors attachments - this is definitely on our radar but not on our immediate roadmap. I'll monitor this thread for community support and post here with any updates.

Thanks and let me know if you have any other questions!

**Comment by novalain** [comment]
Hey @winnieli1208 thanks for explaining this. Unfortunately the limitation of 20 properties per error and 125 characters per key/value is way to low for us. In HockeyApp we could attach a big chunk of JSON to these, which is a requirement from our side in order to be able to do the migration. If support for this is not on your immediate road map we'd have to consider alternative solutions.

**Comment by winnieli1208** [comment]
@novalain we are discussing this internally and will get back to you with updates. We understand this is a major limitation for Unity developers and we will explore what we can do to improve this experience. Thanks for your patience!
