### ISSUE TITLE
Specify component with JIRA integration for crash reporting

### ISSUE THREAD

**Issue by tharlinsmith** [microsoft/appcenter#346]
The JIRA component value is not supplied by AppCenter when recording crashes.  This means your JIRA project must have component optional as discovered in issue #302.  It also makes automatic assigment difficult.  It would be better if the component could be set within AppCenter in the JIRA integration settings.

**Comment by winnieli1208** [comment]
@tharlinsmith thanks for filing this! I can definitely see the value in this. This isn't currently on our roadmap but I will monitor this thread and post if I have any updates.

**Comment by kevindelord** [comment]
This is an issue for us. We need to change our complete JIRA setup to make sure AppCenter's reports actually appear in our instance. Very annoying
