### ISSUE TITLE
Additional info about crash in webhooks

### ISSUE THREAD

**Issue by ufna** [microsoft/appcenter#351]
**Describe the solution you'd like**
More info about crash in webhook. Even just a crash group will be great.

**Describe alternatives you've considered**
No alternatives, I have to open each crash from Slack separately.

**Additional context**
Example list of notifications that are completely useless.
![1DD59E2A-438C-4D40-AD9F-5E07B696DEDD](https://user-images.githubusercontent.com/271578/56850580-3ec37900-690d-11e9-8774-1d3abd47c45e.png)

**Comment by winnieli1208** [comment]
@ufna thanks for the feature request! What type of additional information would you like to see in the webhook? We don't have immediate plans but this is something we hope to improve in the future.

**Comment by ufna** [comment]
@winnieli1208 , most valuable addition will be crash group, f.e.:
> **FPhysXSimEventCallback::onContact(physx::PxContactPairHeader const&, physx::PxContactPair const\*, unsigned int)** PxBase.h line 189`

**Comment by winnieli1208** [comment]
Got it, thanks for the additional details. I'll monitor this thread for community support and comment here if I have any updates.

**Comment by FranzBusch** [comment]
We migrated recently to AppCenter and integrated the crash Webhooks into slack. We were also a bit surprised to only see this little information. It would be great if you can make it more detailed  like mentioned above. This way we could immediately send the new crash to the right team in a lot of cases.
