### ISSUE TITLE
Groups Apps into folders

### ISSUE THREAD

**Issue by developer9969** [microsoft/appcenter#352]
**Describe the solution you'd like**
Ability to group applications into folders . EG:

ClientA (Folder)   

- App1Dev
-    App1UAT
-    App1Prod

 MyStuff (Folder)
   

- AppSpike1
-    AwesomeApp  etc...

Simply please add/consider a concept of folders!

many thanks

**Comment by winnieli1208** [comment]
Thanks for the request! Our team is exploring the concept of app projects that will help users better manage their apps. I don't have an ETA at this time but I'll share any updates when I have them. Thanks!

**Comment by DarkSpikeX** [comment]
Any status update for this?

**Comment by SpaceApeGamesSy** [comment]
Hey guys, I'll +1 this kind of thing. For our particular use case we have various flavours of our builds for each environment, and each can also have different release types.

```
Fastlane (Int)
Fastlane (Staging)
Fastlane (Prod)
```

With enough projects and enough environments it starts to get a little messy. It would be quite useful to be able to group the various flavours of builds together to reduce clutter in the app page.

I can also think of using them to categorise apps, say a place for our Game Jam prototypes to live.

**Comment by JamesRandall** [comment]
I'd also want to be able to target APIs at the folder e.g. to send a push notification.

**Comment by winnieli1** [comment]
Thanks for the feedback. I can definitely see how a folder like concept would be useful for these scenarios. Unfortunately, I don't have any updates at the time. You can follow our roadmap and iteration plans to see what our team is working on and we'll continue to use this thread to track interest.

Thanks!

**Comment by SteffenBurger** [comment]
I would have an additional use case for this (see #365).

The current REST API is designed to provide the "app name", but App Center does not allow the same "app name" for iOS and Android.

/v0.1/apps/{owner_name}/{app_name}/push/notifications

For any backend service, which does not know wether the user has an iOS or Android device, this currently results in one or more additional requests and some logic within the backend service (or one further abstraction between the backend service and App Center). In any case, this is not optimal.

If apps could be grouped and also if the REST API would be redesigned to take the "folder" or "app group" as input, this general issue would be solved.

e.g. 
/v0.1/apps/{owner_name}/{app_group}/push/notifications

**Comment by jwargo** [comment]
@SteffenBurger yes, that's something we're hoping to fix with app groups/projects.

**Comment by colejd** [comment]
Related: #1393
