### ISSUE TITLE
Add Checkmarx Support

### ISSUE THREAD

**Issue by ilaiyarajak** [microsoft/appcenter#353]
**Describe the solution you'd like**
I want to analyze my code with Checkmarx tool

**Describe alternatives you've considered**
I am trying to export my code to checkmarx tool i have installed in my own machine and trying to process there. I am not sure it works.

**Additional context**

**Comment by amchew** [comment]
Thanks @ilaiyarajak for your request! @nrajpurkar would you mind taking a look?

**Comment by nrajpurkar** [comment]
Thanks for the feature request @ilaiyarajak. We don't have plans at the moment for any kind of code coverage or scanning tools in Build. We'll keep this open to track additional interest.

**Comment by ilaiyarajak** [comment]
Thank you @nrajpurkar for taking a look. Checkmarx is a good code analyzing tool, so I am expecting many people will show interest on this.
