### ISSUE TITLE
AppCenter is not creating bug tickets on Azure DevOps

### ISSUE THREAD

**Issue by samuelbigos** [microsoft/appcenter#354]
**What App Center service does this affect?**
Bug Tracker

**Describe the bug**
Everything appears to be hooked up correctly in the AppCenter services settings, I also see AppCenter as an authorised app on the Azure DevOps side. However, when I get a crash appearing in AppCenter, it doesn't create a ticket in Azure DevOps.

**To Reproduce**
1. Hook up Azure DevOps as a bug tracker in AppCenter.
2. Make a new crash appear on AppCenter diagnostics.
3. Notice that a new bug ticket doesn't get created in Azure DevOps.

**Expected behavior**
New bug ticket is created in Azure DevOps.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A (this is a service issue not OS/browser)

**Smartphone (please complete the following information):**
N/A

**Additional context**
In Azure DevOps, under Service Hooks, I see an item for AppCenter.

Thanks.

**Comment by winnieli1208** [comment]
@samuelbigos can you start a conversation in the blue chat bubble on the bottom right corner of App Center? You can link this Github issue so our support and engineering teams can take a closer look. Thanks!

**Comment by alexcnichols** [comment]
Did this get resolved? One thing I've found is that if the process template being used by the project in Azure DevOps doesn't have the Bug work item type, it can have this symptom.

**Comment by winnieli1** [comment]
I just checked the support thread and it looks like removing System.Tags from payload fixed this issue. @samuelbigos closing this issue for now. Thanks!
