### ISSUE TITLE
Email address stuck on old GitHub address

### ISSUE THREAD

**Issue by sdarveau** [microsoft/appcenter#356]
**What App Center service does this affect?**
Settings / Profile

**Describe the bug**
Email address remain the one that was used when connection to github was made. Even after changing profile information in hockeyapp, it doesn't refresh and continue to send notification to the old/unused email address.

**To Reproduce**
1. Log on to App Center using github
2. Notice the email in settings / profile
3. Change the email in github account
4. Click "Edit in HockeyApp" button and change it there also
5. Come back to App Center and notice the old email is still there and it is not possible to edit or redo the connection with github. 

**Expected behavior**
settings / profile email address should reflect what is configured in hockeyapp or github.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by lumaxis** [comment]
Hey @sdarveau, have you already reached out to us via our support system? It would be really helpful to be able to look at your specific account for this issue to better understand what's wrong.

**Comment by sdarveau** [comment]
Not yet, will do. Thanks.

**Comment by derpixeldan** [comment]
@sdarveau earlier today I found your ticket in support being un-responded. Apologize for that, I've replied.
