### ISSUE TITLE
Support for RUNNING_IN_APP_CENTER environment variable in Android

### ISSUE THREAD

**Issue by dolafn** [microsoft/appcenter#357]
**Describe the solution you'd like**
The `RUNNING_IN_APP_CENTER` environment variable available for the application when the device is running in App Center Test on Android devices.

**Describe alternatives you've considered**
We have tried using [getArguments](https://developer.android.com/reference/android/support/test/InstrumentationRegistry.html#getArguments()) but it doesn't work for us.

**Additional context**
We run tests in App Center for iOS using the `RUNNING_IN_APP_CENTER` environment variable in the objective-c layer of our code. Although that specific solution isn't required for our Android code, we do need a way to determine that we are running a test through App Center available to the Java layer or C++ code of our application.

**Comment by kamstrup** [comment]
Which test framework is this?

**Comment by dolafn** [comment]
We are running our own testing framework in engine, and are using AppCenter to send and receive information from the application through backdoors.

**Comment by kamstrup** [comment]
By that I take it you mean you're using Xamarin.UITest to launch things, but then orchestrate everything via backdoor methods?

What exactly about getArguments() is not working for you?

**Comment by dolafn** [comment]
Yes, we are using Xamarin.UITest to launch it.

As far as the specifics on our issues go, unfortunately I am not aware. I am picking up the task to follow up on this after the person who was working on this left our team, and we only have records of some of the communications around it. However, in the communications he was adamant about not being able to use getArguments.

In my attempts to use getArguments, I was unable to use it due to android.support.test not being found. My research into it showed results involving changing the testBuildType in gradle. We are not using gradle for our builds and I am unaware of a similar way to define test builds in Ant.

**Comment by owenniblock** [comment]
@dolafn - please could you send us a link to the test run where this is happening so we can check it out. If you don't want to paste the link here - please reach out to us through the support in the App Center portal (with a link to this GitHub issue as well).

We'll discuss this internally and see what we can come up with.

**Comment by dolafn** [comment]
This doesn't get to a test. The build is not succeeding. I got a recommendation from someone to use XAMARIN_TEST_CLOUD but I've not been able to try that yet.

**Comment by kamstrup** [comment]
The envvars XAMARIN_TEST_CLOUD and APP_CENTER_TEST are set to 1 when running in App Center Test. **But only in the test code, not the app**. Some customers have used [backdoor methods](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-backdoors) to ping the app and tell it it's in test mode.

**Comment by dolafn** [comment]
We've tried that previously. For what we're trying to do, the application needs to know if it's running tests sooner than we can reliably get the first backdoor called from App Center.

**Comment by owenniblock** [comment]
@dolafn - we're looking at (and discussing) a possibility with the App Center SDK at the moment but that's not ready yet. We have some Java code we use in the Test Cloud which does access the InstrumentationRegistry [which you can see here](https://github.com/microsoft/AppCenter-Test-Espresso-Extensions/blob/7610ea64ffd4709beeebe038fed4a2bdb84057ab/src/main/java/com/microsoft/appcenter/espresso/Factory.java#L36) if you want some inspiration.

Alternatively you could wait for our discussions and I'll update you here as soon as we know something concrete.

**Comment by owenniblock** [comment]
Work in progress PR for this is here: https://github.com/microsoft/appcenter-sdk-android/pull/1171#discussion_r287551290

**Comment by owenniblock** [comment]
The PR for adding `isRunningInAppCenterTestCloud()` to the App Center SDK has been merged and is expected to be in the `2.2.0` release.

If you can't wait for it or don't want to include the SDK in your app for some reason - I'd advise taking the code we've written (maybe directly referencing the namespace as you'll know what classes you're using) and applying it to your own system.

Sorry that no-one responded to your question about `ant` earlier - we must have missed this. I'm not sure the best way to solve this but you could consider using `ivy`? http://ant.apache.org/ivy/history/2.5.0-rc1/tutorial/conf.html to set up a `test` build with the dependencies you need.

**Comment by Oddj0b** [comment]
This should have been merged and fixed by now, if not please re-open and ping me.
