### ISSUE TITLE
Support handled errors in react native

### ISSUE THREAD

**Issue by diegoddox** [microsoft/appcenter#358]
It may be that I've missed something in the doc but I'm not able to find how I can manually send an error.

**Comment by winnieli1208** [comment]
@brynjar this isn't on our immediate roadmap. Our team is currently focused on HockeyApp parity items so unfortunately, we don't have the bandwidth to work on this at the moment. It's definitely on our radar and something we'd love to support in the future. I'll keep an eye on this thread and post here with any updates!

**Comment by brynjar** [comment]
Thanks for the update. Just to make sure we are both talking about the same thing, since you mention parity items and this is already supported on hockey. I'm talking about https://support.hockeyapp.net/kb/api/api-crashes#post-custom-crashes

**Comment by winnieli1208** [comment]
Oh thanks for the clarification! I think you're referring to this feature request #31 ? If so, feel free to give the issue a +1. This is on our roadmap and we expect to have it completed in the upcoming months. I'll post in that thread when I have a better ETA.

**Comment by leonardo2204** [comment]
@winnieli1208 I'm also looking forward to this functionality.
In the meantime, does it make sense to user Analytics to track handled Errors or is there a better workaround for now?

Thanks

**Comment by winnieli1208** [comment]
@leonardo2204 definitely! We have some customers using Analytics events to track errors. Just note that there is a limit of 200 distinct events and 256 characters per event name. We are also looking to increase those limits but using events would be the best workaround for now. Thanks!

**Comment by leonardo2204** [comment]
Cool, @winnieli1208, thanks for the quick reply and information! I'll do that :)

**Comment by tindn** [comment]
+1 for this feature. Due to this, we have to use other SaaS for error reporting and as a result, we're under pressure to move away from AppCenter.

**Comment by nmilcoff** [comment]
Hey there! Are there any plans for implementing this?

**Comment by winterdouglas** [comment]
+1

**Comment by jaltin** [comment]
This issue is still relevant so don't close it @msftbot.

**Comment by DmitriyKirakosyan** [comment]
Hi folks, the feature is implemented and included in the recent [release 4.3.0](https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/4.3.0).
Here is the [Handled Errors API documentation](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native#handled-errors).
I'm closing the issue but feel free to reach out if you have additional questions.
