### ISSUE TITLE
Include Build Variables for Webhooks

### ISSUE THREAD

**Issue by tamarianBen** [microsoft/appcenter#359]
**Describe the solution you'd like**
Allow build variables like build number, branch name, or download url as a variable to use in a webhook.

**Comment by amchew** [comment]
Thanks @tamarianBen for your request! @nrajpurkar, could you please take a look?

**Comment by triplef** [comment]
I’d like to second this request. With HockeyApp, Slack notifications via Webhooks included the build number, but App Center seems to only include the app version, which for us usually stays the same for a while while we run multiple builds with increasing build numbers during development.

These screenshots from Slack notifications prior and after the App Center transition illustrate the difference.

<img width="454" alt="Ohne Titel 2" src="https://user-images.githubusercontent.com/6037/67958603-b98c8a00-fbf7-11e9-985d-f96b90d30fff.png">
<img width="368" alt="Ohne Titel 3" src="https://user-images.githubusercontent.com/6037/67958615-bc877a80-fbf7-11e9-8e40-157eae113474.png">
