### ISSUE TITLE
Remove support for TLS 1.0 and 1.1

### ISSUE THREAD

**Issue by iageoghe** [Microsoft/appcenter#36]
The industry is moving away from the baseline of TLS 1.0 and 1.1 support onto TLS 1.2. A broader description of support for the protocol can found on our [Microsoft Secure blog](https://cloudblogs.microsoft.com/microsoftsecure/2017/06/20/tls-1-2-support-at-microsoft/).

**Comment by patniko** [comment]
Officially shipped this change today.
