### ISSUE TITLE
App push stopped working after I deleted the old administrator user

### ISSUE THREAD

**Issue by jfalameda** [microsoft/appcenter#365]
After I deleted the old app administrator, the notifications stopped working. I get invalid token on the notifications.

![image](https://user-images.githubusercontent.com/287670/57034572-2e363a00-6c50-11e9-920c-bc4b2f96fb19.png)

This is a confusing behaviour and it is totally unclear how to solve this issue.

Thanks,
José.

**Comment by jwargo** [comment]
@jfalameda are you sure this is a bug? Have you worked with our support team on this issue?  Changing the administrator for an app in App Center shouldn't remove the service's ability to send notifications - it could be that two things happened at once.  Please use the blue chat button in the bottom-right corner of any app center page and get our dedicated support team to help you further triage this issue.
