### ISSUE TITLE
Can not close the cookie message

### ISSUE THREAD

**Issue by 0xaryan** [microsoft/appcenter#366]
**What App Center service does this affect?**
App Center Website

**Describe the bug**
The cookie message does not have any close button, and is always pinned at top.

**To Reproduce**
1. Open the website
2. Enjoy the pinned cookie message

**Expected behavior**
Ability to close the cookie message box

**Screenshots**
![image](https://user-images.githubusercontent.com/9091958/57038348-f4286080-6c6e-11e9-96b8-9c641c66ecd5.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge Insider]
 - Version [75.0.139.1 (Official build) dev (64-bit)]

**Additional context**
(nothing)

**Comment by patniko** [comment]
Hi @0xaryan, does it go away on refresh? It should be persistent for one session, but should disappear after that on your device.

**Comment by 0xaryan** [comment]
@patniko Nope, it seems nothing can kill that beast.

**Comment by 0xaryan** [comment]
Juste tested this on Firefox Developer 67.0b15 (64-bit) and Edge (UWP app), same issue.

**Comment by 0xaryan** [comment]
Sorry, it doesn't happen on UWP Edge for in the dashboard (only happens in Website's main page).

Edge:
![image](https://user-images.githubusercontent.com/9091958/57039293-7d409700-6c71-11e9-861b-a04f48d696fe.png)

Firefox Dev
![image](https://user-images.githubusercontent.com/9091958/57039311-8fbad080-6c71-11e9-9936-20156a91e122.png)

**Comment by 0xaryan** [comment]
List of cookies created for the website:

**Edge:**
```
_csrf
_ga
_gid
ai_session
ai_user
intercom-session-******** (some random letters and numbers at the end)
MSCC
session
session.sig
```

**Edge Insider:**
```
_csrf
session
session.sig
```

**Firefox Developer:**
```
_csrf
session
session.sig
```

**Comment by 0xaryan** [comment]
It is happening on other Microsoft websites as well.

![image](https://user-images.githubusercontent.com/9091958/57071363-79535a00-6cef-11e9-8459-cae6ea5fbf29.png)

**Comment by patniko** [comment]
Sorry this dropped off my radar @0xaryan. Adding @iageoghe who handles some of this area for our team. That component is central to MS so we don't have very much control over it, but he might have a pointer to the right location for an answer or to file a bug.

**Comment by 0xaryan** [comment]
@iageoghe Any progress on this? This is really annoying!
Maybe I should install some CSS tweaker extension and "display:none" it myself.

![image](https://user-images.githubusercontent.com/9091958/59568501-c0738f80-9090-11e9-8a56-8c42300e45d1.png)

**Comment by iageoghe** [comment]
@0xaryan That _is_ really annoying; I am sorry. Do you have your browser set to clear all cookies on shutdown like I do? That brings back the banner for me each morning in Firefox. Any HTTP filter type add-ins that might cause this behavior? In my other browsers where I haven't established comparable settings I am unable to reproduce the behavior you are describing.

**Comment by 0xaryan** [comment]
> Any HTTP filter type add-ins that might cause this behavior? 

That was it. On every browser that I had "uBlock Origin" extension installed, I had this issue.
Blocking "msecnd.net" and "optimizely.com" caused this actually.

> That is really annoying; I am sorry.

Well, It was my fault actually, not from your side. Sorry to bother you 😅
