### ISSUE TITLE
WPF App support in App Center after Nov 16, 2019

### ISSUE THREAD

**Issue by rheuser** [microsoft/appcenter#367]
**Describe the solution you'd like**
I have WPF apps that currently use the HockeyApp SDK for User reporting, Event reporting and Unhandled exception reporting. I have enrolled them in AppCenter which now reports very nicely on the User data and the Event data. However Unhandled Exceptions are not showing but instead are "Coming Soon". Can you tell me when? Will it be before Nov 16, 2019?

Further, after Nov 16, 2019 will the data from the HockeyApp SDK continue to show in the AppCenter or do I have to convert to using the AppCenter SDK? If so, when will the AppCenter SDK be available for me to integrate into my WPF apps. Our product managers are getting very nervous that we will be left without a solution after Nov 16, 2019.

**Describe alternatives you've considered**

**Additional context**

**Comment by winnieli1208** [comment]
@rheuser we plan to support WPF apps for distribution, diagnostics, and analytics prior to the HockeyApp shutdown. You can find the full plan [here](https://github.com/Microsoft/appcenter/blob/windows/specs/2019-04/Windows-Plan.md). I don't have an exact ETA right now but we expect to start work in the upcoming weeks so I'll have a better timeline for you then.

Once we build out WPF support, you will eventually need to transition to the App Center SDK. We'll add the documentation explaining how to do so in the [SDK Migration docs](https://docs.microsoft.com/en-us/appcenter/transition/sdk-migration) section.

Thank you and your team for your patience; we haven't forgotten about our Windows users :) I'll be sure to post in this thread when I have updates!

**Comment by winnieli1208** [comment]
Hi @rheuser - we just publically enabled WPF/WinForms support for distribution, diagnostics, and analytics. You should see an option to create a new WPF/WinForms app and configure your HockeyApp app as an WPF or WinForms app. 

I'm closing this issue but feel free to reach out at anytime if you run into any issues. Thanks!
