### ISSUE TITLE
I am testing react native android and ios apps with appium using python and pytest. So do appcenter supports appium -python-client.If yes where is the documentation

### ISSUE THREAD

**Issue by Veris-Mansi** [Microsoft/appcenter#368]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Oddj0b** [comment]
App Center only supports Appium Java, you can read more in our docs: https://docs.microsoft.com/en-gb/appcenter/test-cloud/preparing-for-upload/appium

If you want this to be a feature request please re-open with more details.
