### ISSUE TITLE
Include Crash Free User % Metrics 

### ISSUE THREAD

**Issue by FarahaDadvarDeveloper** [microsoft/appcenter#370]
HockeyApp provides Crash Free Users % Per Day, this is a vital piece of information we as team review on a daily basis to reduce the number of crashes.

Would be nice to have the same crash metrics in the App Center.

**Comment by blparr** [comment]
Hi @FarahaDadvarDeveloper , thanks for reaching out. App Center provides a graph for Affected Users, which is the complement of Crash Free users. Do you not find this information useful?

Thanks!

**Comment by winnieli1208** [comment]
@FarahaDadvarDeveloper we also have an API that will return the crash free users % per day: https://openapi.appcenter.ms/#/errors/Errors_ErrorFreeDevicePercentages 

Just make sure you specify the `errorType` parameter as "unhandled" so the API returns the right value. Hope that helps!

**Comment by allen-zeng** [comment]
This is relevant to my interest as well... @winnieli1208 I did look into the API you mentioned, but the numbers that it returns are different from the "Crash Free Users % Per Day" section in HockeyApp, are the 2 things really meant to be exactly the same?

I made sure that there is no filtering of versions etc.

**Comment by FarahaDadvarDeveloper** [comment]
Hi,

This was an issue I raised in March this year. I have attached the email regarding this issue.

"Hockey App shows crashes by date received where App Center shows crashes by date when they happened on the customers device."

Many thanks,

Faraha Dadvar

Developer: Ecommerce Systems Mobile Apps
Next Plc | Desford Road | Enderby | LE19 4AT
Tel: (0116) 429 0581 | Ext: 7581 | Mobex: 4824
