### ISSUE TITLE
Filter crashes by `CFBundleVersion`

### ISSUE THREAD

**Issue by schriftgestalt** [Microsoft/appcenter#371]
I have a Mac app.

In HockeyApp I could filter crashes by `CFBundleVersion`, Appcenter only allows filtering by `CFBundleShortVersionString`. For beta versions, I only increase the build number in `CFBundleVersion`. So it makes it very difficult to find the relevant crashes.

**Comment by derpixeldan** [comment]
@schriftgestalt thanks for bringing it up, fortunately it's already planned and tracked here https://github.com/Microsoft/appcenter/issues/133.

**Comment by schriftgestalt** [comment]
thanks
