### ISSUE TITLE
Configuring a new branch should allow for a copying of settings from another branch

### ISSUE THREAD

**Issue by bobber205** [Microsoft/appcenter#372]
**Describe the solution you'd like**
When I wanna build/test a new branch on app center it's sometimes because I wanna change how it builds on the platform and/or check to make sure it builds ok.

It's inconvenient to have to manually copy over the build settings and make super sure I'm not doing anything wrong to prevent false negatives when testing the build. Something like "Import build settings from X branch?" would be a HUGE timesaver.

**Comment by nrajpurkar** [comment]
Hey @bobber205, definitely agree here! This is actually identical to #22 and something we've committed to working on this month in our [Iteration Plan](https://github.com/Microsoft/appcenter/issues/361). Closing this out as we're tracking the other issue. Thanks for opening up an issue and create more in the future for any other feature requests or bugs you run into.

**Comment by bobber205** [comment]
😀
Thanks!
