### ISSUE TITLE
iOS CI CD

### ISSUE THREAD

**Issue by anil-appface** [microsoft/appcenter#373]
Please add the Continuous integration(iOS Apps) for Team Foundation Version Control (TFVC)

**Comment by patniko** [comment]
Hi @anil-appface, in full transparency, we'll support git and possibly a few other popular options like Mercurial and Perforce in the future. There has been a general shift occurring from TFVC to Git so we're committed to supporting that tooling in App Center for other internal groups at MS and external developers like yourself. TFVC is something we've elected not to support with our team already spread very thin.
