### ISSUE TITLE
Crash reporting for Windows Application Packaging Projects written in C++

### ISSUE THREAD

**Issue by sseyod** [microsoft/appcenter#374]
I write Windows apps using C++, which rely on use of "Windows Application Packaging Projects" for distribution through the Windows Store. See https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net for info on this, if that helps explain how such apps work.

However - it is not yet possible to add AppCenter crash reporting support to C++ apps written in this way to Visual Studio, and I can't see this on your roadmap.

I’ve fed this back to the Visual Studio team probably 3 times in the past year, but nothing seems to have happened.

This would be a game-changer for C++ apps and games for Windows, in my opinion - adding crash reporting support for a potentially vast number of apps.

Thanks for your consideration!

**Comment by winnieli1208** [comment]
@sseyod thanks for the request! We don't have immediate plans to support crash reporting for Windows C++ apps. We are planning to support crash reporting for WPF/WinForms (.NET Framework) and improve our current support for UWP (.NET native) later this summer. I'll keep an eye out on this thread and we can reevaluate this with enough community support. Thanks!

**Comment by sseyod** [comment]
Note this is related to https://github.com/microsoft/appcenter/issues/436

**Comment by markghayden** [comment]
AppCenter should learn about a company called Microsoft (http://microsoft.com).  For several decades, everyone wrote software for Microsoft using C/C++.  There are thousands or millions of programs written this way. Many developers still write software this way. Maybe it would be helpful for those developers if AppCenter could help Microsoft C/C++ software developers in AppCenter?

**Comment by mayenjoy** [comment]
Is there any progress? Our whole company is waiting for this matter.

**Comment by archilanfedorov** [comment]
Hello there! Our company is waiting for this too.

**Comment by hamadycisse** [comment]
We would like to have it too!

**Comment by sseyod** [comment]
Hi @winnie!

Is there any more news on this?

Thanks, Pete

**Comment by winnie** [comment]
Hey @sseyod! Unfortunately, no updates on this one. We did add a [upload custom crashes API](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes) so you can now upload your crashes from a Windows C++ app so you can view and manage those reports in App Center. We also support symbolicating those crashes ([docs here](https://docs.microsoft.com/en-us/appcenter/diagnostics/unmanaged-code-crash-support)).

We don't have any immediate plans to build an crashes SDK for Windows C++ apps but I hope this helps a little. I'll update this thread if anything changes. Thanks!

**Comment by sseyod** [comment]
Hi folks,

Just to let you know that Sentry.io have now got crash reporting working for C++ Windows 10 apps. Very well done to them!

More info here:

https://github.com/getsentry/sentry-native/issues/190

@winnie surely it would make sense for AppCenter now to offer a similar feature?

If a 3rd party can do this, you'd have thought that Microsoft could do it too?

Best wishes to all,

Pete

**Comment by triplef** [comment]
This is still very much needed, especially now that Win32 apps are fully supported on the Windows Store.

**Comment by sseyod** [comment]
I couldn't agree more! I'm still using Sentry.io, which is perfectly fine, but it'd be more convenient to use AppCenter - just like I can already do for my iOS, macOS, Android apps...!

Hi again @winnie - this is my yearly request to ask if somebody at Microsoft could possibly schedule this in ... ASAP!

Pete

**Comment by bruno-garcia** [comment]
Sentry also supports macOS, iOS, Android and most other for t end and backend technologies. Curious why would it be less convenient (disclaimer: I maintain some Sentry SDKS).

**Comment by sseyod** [comment]
Hi @bruno-garcia

I can only answer for myself, but my main reason from a convenience perspective is what we also use AppCenter for Beta App distribution - something not offered by sentry.io (unless you can tell me otherwise), and that just makes AppCenter more convenient. We upload the files, distribute them, and it is all done - apps are distributed for testing (and live use) and we capture the crash reports.

Historically, I've come-over as a HockeyApp user (so I have residual brand loyalty!) - and would like Microsoft to make this a better product! But - I've also done what I can to help sentry.io and support for their Microsoft app crash reporting known about, as it is a great thing to have. Of course: on a related note, AppCenter also doesn't support Beta app distribution for native C++ apps - so that is another "hole" in their offering...

Pete
