### ISSUE TITLE
Global environment variables

### ISSUE THREAD

**Issue by Bloodyairtimer** [microsoft/appcenter#376]
**Describe the solution you'd like**
I'm having alot of apps in App Center which are all using the same variables to access to private nugetfeed. Right now I have to add these variables to every app (Android & iOS) and to all my branches that i build (3 per app). That's alot of work to create and also alot of work to maintain as the token is only valid for one year. 

I would like to have the same variables as I have in Azure Devops that could be used across multiple builds. So I only have to configure the value in 1 place and reference it in the different builds.

**Describe alternatives you've considered**
So far the environment variables are the only alternative I see, but that would mean lot's of configuration and maintenance.

**Comment by nrajpurkar** [comment]
@Bloodyairtimer thanks for the feature request. We'll keep this issue open to track further interest for supporting this to help us prioritize in the future.

**Comment by cgat** [comment]
Any possibility to reopen this? This is a pretty big sore point in AppCenter

**Comment by sclavijo93** [comment]
This would be nice to have!

**Comment by jensdev** [comment]
Any update on this? Would be really nice to have
