### ISSUE TITLE
Migrate to Azure Dev Ops

### ISSUE THREAD

**Issue by nschild** [microsoft/appcenter#378]
Hello,
I am trying to migrate to Azure DevOps and am having an issue. There appears to be a configuration issue between AppCenter and Dev ops as the same repo is giving me an error with an unsatisfiable dependancy. Would it be possible to get the generated .sh files from AppCenter to see what flags are being passed to the build steps so I can replicate them on DevOps?

Thank you,
Nick

**Comment by patniko** [comment]
I'll see if I can get these definitions added to this repo so developers can grab the same ones we use out of the repo for their own DevOps implementations. Will circle back once I track them down.

**Comment by pachuka** [comment]
I'd say for the future would be really neat if we could have a button in the UI that could convert it into the DevOps build pipeline automatically, but for now the definitions in the repo would be great!

**Comment by beeradmoore** [comment]
Was just wondering if there would be any easy way to port project to Azure Pipelines. Doesn't look like it yet.

I have an open source project, and if I start hitting its limits I'll need to move it to Azure Pipelines as they [have free unlimited minutes](https://azure.microsoft.com/en-au/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/) for open source projects.
