### ISSUE TITLE
Xamarin.iOS Solution Not Found For Build

### ISSUE THREAD

**Issue by RobertMcCoy** [microsoft/appcenter#379]
**What App Center service does this affect?**
AppCenter Build Configuration

**Describe the bug**
Neither the iOS Solution file nor the iOS csproj are being detected by the build configuration wizard. 

**To Reproduce**
1. Go to `Build`
2. Select a branch with an iOS Solution or Project file and references to `.NET Standard 2.0` libraries
3. Ensure build configurations are setup correctly for the solution/project references
4. Wait for the build wizard to finish searching for projects

**Expected behavior**
The iOS Solution appears in the wizard as a buildable project. 

**Actual behavior**
Message appears that says `We couldn’t find any Xamarin iOS projects in your branch.`

**Screenshots**
Here is the screenshot showing that my Solution is only 1 folder deep from the root folder, so it should be detected by the AppCenter searcher. You can also see the build configurations for each of the projects referenced by the `.sln`.
![image](https://user-images.githubusercontent.com/2020529/57234844-8f169700-6fef-11e9-888f-a24a9b49022d.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 73.0.3683.103 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
This is a relatively large solution with a UWP, Android, and iOS projects, as well as several domain and business layer projects. This app is also built on top of MvvmCross. I have tried modifying the `.csproj` for the iOS project as well, but that didn't seem to get anywhere. The libraries this solution file references are all `.NET Standard 2.0` libraries. The individual `.csproj` is not being found for the build either.

**Comment by DennisPan** [comment]
@RobertMcCoy do you mind reaching out to support (the blue bubble at bottom right of the portal), so that we can dig into more details? We can circle back on this Issue about what happened, which may helper others who run into the same. But for us to perform deeper investigation, we need to acquire more information about your account, app, etc.

**Comment by DennisPan** [comment]
Close this as this requires support to be involved for the specific case.
