### ISSUE TITLE
[Feature] Support the Kotlin DSL, build.gradle.kts

### ISSUE THREAD

**Issue by joshuarose** [microsoft/appcenter#38]
**What App Center service does this feature apply to?**
The CI/CD build pipeline

**Describe the solution you'd like**
Instead of only looking for build.gradle files update the project analyzer to also look for build.gradle.kts files.

**Describe alternatives you've considered**
We're likely looking to move to Travis temporarily for building this app until this feature becomes available. The other alternative would be to revert back to using groovy for build files, but the autocompletion and strong typing of Kotlin DSL are something our team has seen value in.

**Additional context**
https://github.com/gradle/kotlin-dsl

**Comment by nrajpurkar** [comment]
Thanks for adding this feature request @joshuarose. Looks like it has gotten some community support already - we will keep it open to track further interest.

**Comment by harry248** [comment]
@nrajpurkar Any update on this topic? We just converted our groovy based build files to the gradle kotlin dsl and now we can't build on app center anymore. Considering that almost 4 months have passed since the official release we would have expected that a serious CI solution (we are paying for) is a) aware of such development and b) has working support within an adequate time frame.

**Comment by nrajpurkar** [comment]
Hi @harry248, no immediate updates to share at this moment, but this continues to be functionality myself and my team are aware of and tracking.

**Comment by ranterle** [comment]
Hi there @harry248 and everybody else interested in using the Kotlin DSL for configuring your Android projects. We're currently working on support for this and would love your feedback.
If you are interested, feel free to send me a message (email is in my profile) and I'll get back to you.

**Comment by ranterle** [comment]
Just a quick update: We have shipped and enabled the feature to analyze Kotlin DSL based Gradle configurations for your Android Java/Kotlin and Android React Native apps.
There is no extra work in order for you to use this, your app and its build variants should now automatically appear when configuring a build. If you're encountering any problems with this, please do let us know here or through support in the App Center portal.

**Comment by rohitgarg2022** [comment]
Command 'codepush release-react -a rohit.garg.com/housingnative --entry-file index.js --sourcemap-output index.map -d rewrite -b index.android.bundle' failed with exception "Unable to find gradle file "android/app/build.gradle"." The file is basically android/app/build.gradle.kts but it is not picking that file.
