### ISSUE TITLE
Build Queue Display For all Apps under a team

### ISSUE THREAD

**Issue by kuyazee** [microsoft/appcenter#380]
**Describe the solution you'd like**
I'd like a new screen where I can see the current build queue for all my projects.

**Describe alternatives you've considered**
Nothing at the moment

**Comment by Bloodyairtimer** [comment]
Yes, would love to have the same screen. Also some actions being available on this screen would be awesome:

- Change priority of build in the queue.
- Cancel a build

**Comment by zarko-via** [comment]
+1

Will want to add that we have dozens of apps, with multiple teams starting builds.
Currently there is no method to globally know what is building and in what order.
We would also like a single web page showing the current build queue of all apps, ability to cancel specific builds and reorder the queue.

Following discussions with support no solution was provided.

It is not realistic to enter one by one into dozens of apps and understand state.

**Comment by nrajpurkar** [comment]
Thanks for this request and additional context! We'll track this as a potential feature for the future.

**Comment by zarko-via** [comment]
To our take in a large organization where many people can do builds under many apps.
It is very much not visible what build tasks are running or why another build is queued.

A visible queue of build jobs (and ability to cancel them, re-priorities) is a key mandatory thing in any other build queue based system. Mainly if the build and billing system is based on concurrent queues.
