### ISSUE TITLE
App Crash notifications- sent via Email to the developers will help them easily make fixes in the next releases.

### ISSUE THREAD

**Issue by swathisuvarna1** [microsoft/appcenter#382]
**Describe the solution you'd like**
be able to notify users about app crashes.
**Describe alternatives you've considered**
an option to import crash logs

**Additional context**

**Comment by kpiteira** [comment]
Hello, 
You can already do that in App Center: head to the app settings then Email Notifications and check the box "When a new crash group is created".
I'll close the issue but feel free to re-open if you believe that was not what you were looking for

**Comment by misternopps** [comment]
This functionality doesn't really exist on a per-crash basis. It only exists on a per-crash-group basis, making it pretty meaningless if you want to actually monitor for something crashing through appCentre, as you never know if it might have crashed silently from an error which it might have crashed on earlier
