### ISSUE TITLE
Missing Windows Store support for UWP publishing

### ISSUE THREAD

**Issue by jjindrich** [microsoft/appcenter#383]
We are using Xamarin for mobile app development. Xamarin supports Android, iOS and UWP.  We are submitting app in stores but Windows is missing.

Because there is no native integration with Windows Store, I'm trying to find some workaround to to extend pipeline to publish to Windows Store.

**Comment by winnieli1208** [comment]
@jjindrich thanks for the request! We'd like to support App Center releases to the Windows store but this isn't currently on our immediate roadmap. I will monitor this thread for community support and post updates here.

**Comment by devedse** [comment]
For me this would be the single most important feature of the platform. Being able to automatically publish releases to the "public" stores. Part of every build/release lifecycle should be a way to automatically publish a nightly build to a beta store (or whatever) so that those can be tested by the user base.

After that I don't mind to have a single manual step to promote a specific package to the "Production" state, but without this, you're still managing everything manually.

**Comment by leoniDEV** [comment]
Would be useful also the ability to publish to the Business Store and support the package flights system of the Windows Store

**Comment by jamers99** [comment]
@winnieli1 any status update on this? This would be very nice, giving us one place to go for all our apps.

**Comment by tedmatuszewski** [comment]
Any updates on this @winnie or @Oddj0b ? I just posted a very similar issue #1422. Also, I would be happy to meet to discuss my use case with either or both of you. I tried clicking on your calendar link above but it did not have any openings.

**Comment by mzimdars-gms-online-de** [comment]
Is this considered in the roadmap somewhere?
I wonder if it makes sense to invest into using the Microsoft store publishing or if this will be abandoned like UWP more or less is when Microsoft products themselves do not support it. Does not express much confidence into the own platform :-/
Is there an alternate solution?

Would be nice to get a hint whether it is worth to wait for it :-) or to build an own solution :-(

**Comment by asierpn** [comment]
This feature must be implemented, you support App Store and Google Play but not your own store?

**Comment by manfredczujan** [comment]
Its your own store ! 
Its your platform !
Pls. implement this feature !!!

**Comment by antonioberetini** [comment]
This is very needed considering that windows is taking app developers serious again, any update on this?

**Comment by mzimdars-gms-online-de** [comment]
It shouldn't be stale, it should be added to a future release ;-)

**Comment by mzimdars-gms-online-de** [comment]
This is still an issue and it would be great if you could add it to your roadmap

**Comment by mc0re** [comment]
Looks like MS cares not about Windows Store. Why?..

**Comment by mc0re** [comment]
Community - add your votes. This issue is blatantly ignored by Microsoft.

**Comment by mzimdars-gms-online-de** [comment]
> Community - add your votes. This issue is blatantly ignored by Microsoft.
Seems so..

**Comment by mzimdars-gms-online-de** [comment]
@winnie Could you please add this to the backlog or clearly state that this is considered out-of-scope for App Center so that we can give up hope?

**Comment by mzimdars-gms-online-de** [comment]
and please reopen - it was closed by the bot despite there _was_ activity

**Comment by asierpn** [comment]
This feature will clearly never be implemented for UWP or WinUI, it seems that this project is in maintenance mode.

**Comment by mzimdars-gms-online-de** [comment]
@asierpn that is my impression as well.
I saw an announcement previously where the devs said 'we do a feature stop to overhaul the internals and then continue with development' which would be a temporary 'maintenance mode', but I am also missing some kind of feedback what is going to happen after the overhaul - so your suspicion that they will never leave that phase is quite a high probability
