### ISSUE TITLE
ApplicationInsights configuration options to existing resource

### ISSUE THREAD

**Issue by OHjeffhudson** [microsoft/appcenter#384]
Add the ability to select an existing ApplicationInsights instance when exporting data.  If one does not already exist give the ability to name the resource group and insights instance.

I would like to be able to monitor my API layer, Android mobile application, and iOS Application from the same ApplicationInsights instance.

**Comment by kpiteira** [comment]
Did you try providing the App Insights key when you set up your export? That should achieve what you're trying to do
