### ISSUE TITLE
Heat map

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/appcenter#385]
For analytics, I would like to be able to see the heat map.
This can be a screenshot of the screen with a heat map by clicking on the screen.
For example, as in the picture.
![heatmaps-1024x676](https://user-images.githubusercontent.com/4385716/57328482-3b549c80-711a-11e9-848d-8a2dd8a0bafb.jpg)

**Comment by hamswan** [comment]
Thanks @KSemenenko for requesting this feature. Heatmaps indeed help understand user interaction patterns and user navigation. I will add this in our feature request.
