### ISSUE TITLE
Userflow

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/appcenter#386]
It would be great if you could build a userflow. and see how the application is used.
Use for this diagram event, crashes, exceptions and display views.

![User-Flow-City](https://user-images.githubusercontent.com/4385716/57328628-98e8e900-711a-11e9-9363-4d324b94bc33.png)

**Comment by KSemenenko** [comment]
Screen like this #316

**Comment by hamswan** [comment]
Thanks @KSemenenko , tracking this as a feature request.
