### ISSUE TITLE
[PLCrashReport] MSplcrash_log_writer_init:352: Could not retreive parent process name: Operation not permitted

### ISSUE THREAD

**Issue by DwightHyde** [microsoft/appcenter#387]
**What App Center service does this affect?**
AppCenter 1.14.0

**Describe the bug**
I'm seeing this in my VS2017 Debug Output Window:
Loaded assembly: /private/var/containers/Bundle/Application/1C8C0777-A74A-40F2-B7BF-C799C7217263/UCH.MHC.Mobile.iOS.app/Microsoft.AppCenter.Crashes.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/1C8C0777-A74A-40F2-B7BF-C799C7217263/UCH.MHC.Mobile.iOS.app/Microsoft.AppCenter.Distribute.dll [External]
[PLCrashReport] MSplcrash_log_writer_init:352: Could not retreive parent process name: Operation not permitted
2019-05-07 14:21:35.413 UCH.MHC.Mobile.iOS[2684:35548838] [AppCenterDistribute] ERROR: -[MSDistribute buildTokenRequestURLWithAppSecret:releaseHash:isTesterApp:]/483 Custom URL scheme for Distribute not found.
2019-05-07 14:21:35.413 UCH.MHC.Mobile.iOS[2684:35548838] [AppCenterDistribute] ERROR: -[MSDistribute buildTokenRequestURLWithAppSecret:releaseHash:isTesterApp:]/483 Custom URL scheme for Distribute not found.

**To Reproduce**
1. Added AppCenter, Analytics, Crashes, and Distribute packages
2. Added AppCenter.Start(.... to app.xaml
3. Switched over to Analytics.TrackEvent... in my code
4. Ran app from VS onto iPhone XR

**Expected behavior**
No Errors

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 12.2
 - Browser safari

**Additional context**
Working on migrating from HockeyApp.  Thanks for any help you can provide.

**Comment by winnieli1208** [comment]
@DwightHyde do you mind creating a support ticket via the blue chat bubble on the bottom right corner of App Center? Our engineering team can take a closer look for you. Thanks!

**Comment by DwightHyde** [comment]
Actually I'm good now.  I just didn't have everything setup correctly.  I forgot to add Distribute.DontCheckForUpdatesInDebug(); in the AppDelegate.  Thank you for reaching out.
