### ISSUE TITLE
App Center Auth in early preview

### ISSUE THREAD

**Issue by amchew** [microsoft/appcenter#388]
We’re really excited to launch App Center Auth in early preview today! 🚀 

For the past few months since our initial designs on [Jan 24](https://github.com/Microsoft/appcenter/issues/11), the team has been working with our users to develop a seamless identity management service to easily manage user identities at scale in App Center. 

App Center Auth is a cloud-based identity management service that enables developers to authenticate users and manage user identities. Our preview will support native iOS, Android and Xamarin, with additional platforms planned in the future. App Center Auth is powered by Azure Active Directory B2C. 

Learn more about App Center Auth in the [docs](https://docs.microsoft.com/appcenter/auth/) or [blog post](https://devblogs.microsoft.com/appcenter/introducing-visual-studio-app-center-auth/) and our new [Mobile Backend as a Service](https://devblogs.microsoft.com/appcenter/visual-studio-app-center-preview-welcoming-auth-and-data-to-the-portfolio/) offerings.

This is an early preview and the beginning of App Center Auth, so try Auth out, and share your feedback below!

**Comment by quincycs** [comment]
Hi 👋, exciting times, I’ve been waiting for this glorious moment 🎉

One bit of quick feedback is the signout story.  I’m not seeing the documentation speak about signing out.  I’d like to test and see what the UI looks like when signing out. Specifically if it requires a web view to pop open to signout.

**Comment by amchew** [comment]
Hey @quincycs! Ah yes, I'll add the sign-out experience in the Auth Getting Started docs. You can read more about the [`signOut()` experience](https://docs.microsoft.com/en-us/appcenter/sdk/auth/android#sign-out) in the meantime. Calling the `signOut()` method clears all associated authentication tokens from Auth & Data and signs the user out. We do not provide an out of the box UI for signing out currently.

**Comment by sdg85** [comment]
Hi
Thanks for the great feat. Just wanted to ask if you have a sample on how to use it. We're just getting back a app_id, where do i find the user info (claims)?

**Comment by amchew** [comment]
Hey @quincys, an update, I've made a PR to update the docs about the signOut() method, you should see it updated shortly. :)

Hey @sdg85, thanks for the support! Calling signIn() now only returns the [accountId](https://docs.microsoft.com/en-us/appcenter/sdk/auth/android#sign-users-into-the-app), which allows you to identify the signed in user and use this accountId in other App Center services like Data and Push. We are working on a feature to [return the JWT and expose the claims](https://github.com/microsoft/appcenter/issues/393), and it should get picked up soon. I'll update again when it's done!

Regarding the samples, could you share more what you're looking for? For example, sample code snippets of how to use the accountId with Push/Data etc.

**Comment by amchew** [comment]
Hey all, 

An update: we completed the work to expose the access and id token yesterday and this will be released in the next version of our SDK - before the end of June. You can 

We'll be sharing in our documentation how to parse the access and id token, what actions to take if the user is signed in or not. You can track the progress of the [feature to expose the JWT](https://github.com/microsoft/appcenter/issues/393).

**Comment by amchew** [comment]
Hey @QuincyS, @sdg85, you can now get the access and id tokens for Auth in the 2.1.0 SDK release!

Here are the repos and documentation for the following platforms:-

**Xamarin**
- [Xamarin repo](https://github.com/microsoft/appcenter-sdk-dotnet/releases)
- [Xamarin documentation](https://docs.microsoft.com/en-us/appcenter/sdk/auth/xamarin#get-access-token-and-id-token)

**iOS**
- [iOS repo](https://github.com/microsoft/appcenter-sdk-apple/releases)
- [iOS documentation](https://docs.microsoft.com/en-us/appcenter/sdk/auth/ios#get-access-token-and-id-token)

**Android**
- [Android repo](https://github.com/microsoft/appcenter-sdk-android/releases)
- [Android documentation](https://docs.microsoft.com/en-us/appcenter/sdk/auth/android#get-access-token-and-id-token)

Try it out, and let us know what you think! :)

**Comment by winnieli1208** [comment]
Hi all,

The App Center team is exploring other backend services to bring to App Center. We would love to hear directly from you to help us shape these ideas. If you're interested in chatting with us, you can find a time [here](https://outlook.office365.com/owa/calendar/VisualStudioAppCenter2@microsoft.onmicrosoft.com/bookings/). Thanks!

**Comment by incedo** [comment]
I'm trying out appcenter auth with react native. But i cannot see the tenant. It's there but when I try to connect to it it defaults to the wrong default directory. I'm not known with azure that much but some more documentation would be great

**Comment by askpatrickw** [comment]
@incedo This is a known issue and the officially MSFT response is to use the direct library (i.e., they said App Center Auth isn't reliable yet).

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries

For ReactNative, I'm looking at : https://github.com/FormidableLabs/react-native-app-auth
