### ISSUE TITLE
Minimum supported Gradle version is 5.1.1. Current version is 4.6.

### ISSUE THREAD

**Issue by ceteongvanness** [microsoft/appcenter#389]
Hi guys,

I having issue about

and here is the log.

Thanks for helping hand.

May I ask about how to solve this issue.
``
##[section]Initializing the Microsoft-hosted agent
Requesting an agent from the Microsoft-hosted agent pool
Hosted Agent successfully assigned.
Configuring connection settings for Hosted Agent
Starting Hosted Agent
##[section]Starting: Build
##[section]Starting: Initialize job
Current agent version: '2.150.3'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: ShellScript
Downloading task: Gradle
Downloading task: CopyFiles
Downloading task: PublishBuildArtifacts
Downloading task: CmdLine
Start tracking orphan processes.
##[section]Finishing: Initialize job
##[section]Starting: Checkout
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Syncing repository: android (ExternalGit)
##[command]git version
git version 2.21.0
##[command]git lfs version
git-lfs/2.7.2 (GitHub; darwin amd64; go 1.12.4)
##[command]git init "/Users/vsts/agent/2.150.3/work/1/s"
Initialized empty Git repository in /Users/vsts/agent/2.150.3/work/1/s/.git/
##[command]git remote add origin https://hauliov1.visualstudio.com/Haulio%20Communicator%20Driver%20App/_git/android
##[command]git config gc.auto 0
##[command]git config --get-all http.https://hauliov1.visualstudio.com/Haulio%20Communicator%20Driver%20App/_git/android.extraheader
##[command]git config --get-all http.proxy
##[command]git remote set-url origin https://***:***@hauliov1.visualstudio.com/Haulio%20Communicator%20Driver%20App/_git/android
##[command]git remote set-url --push origin https://***:***@hauliov1.visualstudio.com/Haulio%20Communicator%20Driver%20App/_git/android
##[command]git lfs install --local
Updated git hooks.
Git LFS initialized.
##[command]git config remote.origin.lfsurl https://***:***@hauliov1.visualstudio.com/Haulio%20Communicator%20Driver%20App/_git/android.git/info/lfs
##[command]git config remote.origin.lfspushurl https://***:***@hauliov1.visualstudio.com/Haulio%20Communicator%20Driver%20App/_git/android.git/info/lfs
##[command]git fetch --tags --prune --progress --no-recurse-submodules origin
remote: Azure Repos        
remote: 
remote: Found 26755 objects to send. (323 ms)        
Receiving objects: 100% (26755/26755), 77.49 MiB | 8.67 MiB/s, done.
Resolving deltas: 100% (18682/18682), done.
From https://hauliov1.visualstudio.com/Haulio%20Communicator%20Driver%20App/_git/android
 * [new branch]      PsaSmsApi               -> origin/PsaSmsApi
 * [new branch]      bugfix                  -> origin/bugfix
 * [new branch]      cancelJob               -> origin/cancelJob
 * [new branch]      chat                    -> origin/chat
 * [new branch]      cleanHistory            -> origin/cleanHistory
 * [new branch]      createpusherimplement   -> origin/createpusherimplement
 * [new branch]      develop                 -> origin/develop
 * [new branch]      feature/chat            -> origin/feature/chat
 * [new branch]      feature/completedjobs   -> origin/feature/completedjobs
 * [new branch]      feature/completejobs    -> origin/feature/completejobs
 * [new branch]      feature/forgot_password -> origin/feature/forgot_password
 * [new branch]      feature/geofencing      -> origin/feature/geofencing
 * [new branch]      feature/history         -> origin/feature/history
 * [new branch]      feature/jobs            -> origin/feature/jobs
 * [new branch]      feature/login           -> origin/feature/login
 * [new branch]      feature/primemover      -> origin/feature/primemover
 * [new branch]      feature/profile         -> origin/feature/profile
 * [new branch]      feature/registration    -> origin/feature/registration
 * [new branch]      feature/setting         -> origin/feature/setting
 * [new branch]      feature/support         -> origin/feature/support
 * [new branch]      feature/vehicle         -> origin/feature/vehicle
 * [new branch]      jobDetailRecycler       -> origin/jobDetailRecycler
 * [new branch]      master                  -> origin/master
 * [new branch]      newfeatures             -> origin/newfeatures
 * [new branch]      notificationService     -> origin/notificationService
 * [new branch]      signInError             -> origin/signInError
 * [new branch]      testing                 -> origin/testing
 * [new branch]      tripFormAmount          -> origin/tripFormAmount
 * [new branch]      uatbugfix               -> origin/uatbugfix
 * [new branch]      updateJobs              -> origin/updateJobs
 * [new branch]      vehicleUI               -> origin/vehicleUI
 * [new tag]         0.1.0                   -> 0.1.0
 * [new tag]         0.2.0                   -> 0.2.0
 * [new tag]         0.2.1                   -> 0.2.1
 * [new tag]         0.3.0                   -> 0.3.0
 * [new tag]         0.4.0                   -> 0.4.0
 * [new tag]         0.5.0                   -> 0.5.0
 * [new tag]         0.9.5.7.1               -> 0.9.5.7.1
 * [new tag]         0.9.5.7.2               -> 0.9.5.7.2
##[command]git lfs fetch origin fd2eec46da210760300ad2083e7498dbfcab016b
fetch: Fetching reference fd2eec46da210760300ad2083e7498dbfcab016b
##[command]git checkout --progress --force fd2eec46da210760300ad2083e7498dbfcab016b
HEAD is now at fd2eec46 update chat
##[command]git submodule sync --recursive
##[command]git submodule update --init --force --recursive
##[command]git remote set-url origin https://hauliov1.visualstudio.com/Haulio%20Communicator%20Driver%20App/_git/android
##[command]git remote set-url --push origin https://hauliov1.visualstudio.com/Haulio%20Communicator%20Driver%20App/_git/android
##[command]git config --unset-all remote.origin.lfsurl
##[command]git config --unset-all remote.origin.lfspushurl
##[section]Finishing: Checkout
##[section]Starting: Tag build
==============================================================================
Task         : Shell Script
Description  : Run a shell script using bash
Version      : 2.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613738)
==============================================================================
[command]/bin/bash /Users/vsts/agent/2.150.3/scripts/emit-tags.sh android,manual
##[section]Async Command Start: Add Build Tag
Build '4' has following tags now: android, normal
##[section]Async Command End: Add Build Tag
##[section]Async Command Start: Add Build Tag
Build '4' has following tags now: android, manual, normal
##[section]Async Command End: Add Build Tag
##[section]Finishing: Tag build
##[section]Starting: Gradle Task
==============================================================================
Task         : Gradle
Description  : Build using a Gradle wrapper script
Version      : 1.128.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613720)
==============================================================================
SYSTEMVSSCONNECTION exists true
[command]/Users/vsts/agent/2.150.3/work/1/s/app/gradlew -p app clean :app:assembleDevDebug
Starting a Gradle Daemon (subsequent builds will be faster)
Gradle 4.6
Download https://jcenter.bintray.com/io/realm/realm-gradle-plugin/5.7.0/realm-gradle-plugin-5.7.0.pom
Download https://jcenter.bintray.com/com/akaita/android/easylauncher/1.3.1/easylauncher-1.3.1.pom
Download https://jcenter.bintray.com/org/jetbrains/dokka/dokka-android-gradle-plugin/0.9.17/dokka-android-gradle-plugin-0.9.17.pom
Download https://dl.google.com/dl/android/maven2/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api.pom
Download https://jcenter.bintray.com/io/realm/realm-transformer/5.7.0/realm-transformer-5.7.0.pom
Download https://jcenter.bintray.com/org/jetbrains/dokka/dokka-gradle-plugin/0.9.17/dokka-gradle-plugin-0.9.17.pom
Download https://jcenter.bintray.com/io/realm/realm-annotations/5.7.0/realm-annotations-5.7.0.pom
Download https://jcenter.bintray.com/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.pom
Resolved com.android.tools.build:gradle:3.4.0 in :classpath 
Resolved org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21 in :classpath 
Resolved io.realm:realm-gradle-plugin:5.7.0 in :classpath 
Resolved com.google.gms:google-services:4.2.0 in :classpath 
Resolved io.fabric.tools:gradle:1.25.4 in :classpath 
Resolved com.akaita.android:easylauncher:1.3.1 in :classpath 
Resolved org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.17 in :classpath 
Download https://jcenter.bintray.com/com/akaita/android/easylauncher/1.3.1/easylauncher-1.3.1.jar
Download https://jcenter.bintray.com/org/jetbrains/dokka/dokka-android-gradle-plugin/0.9.17/dokka-android-gradle-plugin-0.9.17.jar
Download https://jcenter.bintray.com/io/realm/realm-transformer/5.7.0/realm-transformer-5.7.0.jar
Download https://dl.google.com/dl/android/maven2/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api.jar
Download https://jcenter.bintray.com/org/jetbrains/dokka/dokka-gradle-plugin/0.9.17/dokka-gradle-plugin-0.9.17.jar
Download https://jcenter.bintray.com/io/realm/realm-annotations/5.7.0/realm-annotations-5.7.0.jar
Download https://jcenter.bintray.com/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar
Download https://jcenter.bintray.com/io/realm/realm-gradle-plugin/5.7.0/realm-gradle-plugin-5.7.0.jar
Project s at : is either no Android app project or build version has not been set to override. Skipping...
Project app at :app is either no Android app project or build version has not been set to override. Skipping...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/vsts/agent/2.150.3/work/1/s/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in /Users/vsts/agent/2.150.3/work/1/s/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Error: /Users/vsts/agent/2.150.3/work/1/s/app/gradlew failed with return code: 1
    at ChildProcess.<anonymous> (/Users/vsts/agent/2.150.3/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/1.128.0/node_modules/vsts-task-lib/toolrunner.js:569:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
##[error]Error: /Users/vsts/agent/2.150.3/work/1/s/app/gradlew failed with return code: 1
##[section]Finishing: Gradle Task
##[section]Starting: Checkout
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Cleaning any cached credential from repository: android (ExternalGit)
##[section]Finishing: Checkout
##[section]Starting: Finalize Job
Start cleaning up orphan processes.
Terminate orphan process: pid (760) (java)
##[section]Finishing: Finalize Job
##[section]Finishing: Build

``

**Comment by nrajpurkar** [comment]
Hi @ceteongvanness, can you reach out to support via the blue bubble at the bottom right corner of App Center? We'll be able to engage directly and troubleshoot this issue there. Thanks!
