### ISSUE TITLE
Unit tests for Apple Watch target fails

### ISSUE THREAD

**Issue by helloniklas** [microsoft/appcenter#392]
**What App Center service does this affect?**
CI Build

**Describe the bug**
We have units tests and Apple Watch target. Switching on testing then fails the build.

**Expected behavior**
Able to build and run tests

**Comment by alex-benoit** [comment]
@patniko @nrajpurkar any updates on running unit tests with apple watch target? Thanks!

**Comment by nrajpurkar** [comment]
Hi all, this is related to issue #426. Today we target iPhone 6 as the simulator. We are regarding this as a feature request to be able to change the simulator to work with unit tests for Apple Watch targets.
