### ISSUE TITLE
Add access_token property to UserInformation

### ISSUE THREAD

**Issue by fileman** [microsoft/appcenter#393]
**Describe the solution you'd like**
Since MSAL is used under the cover, if AuthenticationResult has access_token value add to new property in UserInformation.

**Describe alternatives you've considered**
Continue to use MSAL to AzureAD B2C

**Additional context**
even AcquireTokenSilent with refresh_token... if not handled inside the SignInAsync method

**Comment by amchew** [comment]
Hi @fileman, thanks for commenting about this! I'd like to learn more about your scenario for the right fix, would you be available to hop on a call with me this week? Email me at amchew [at] microsoft [dot] com please.

**Comment by guperrot** [comment]
Hi, to rephrase you want UserInformation to have the AccessToken property being available?

As for refresh token, it is already handled, if you call SignInAsync again (after a successful first time), the second time it will be a silent sign-in.

**Comment by fileman** [comment]
Yes, so I can use it when I have to invoke bearer protected web api, azure functions, odata endpoint, etc... something like I do now with azure mobile apps.

**Comment by amchew** [comment]
Thanks @fileman, I've added this feature request to our backlog. Others - feel free to give a thumbs up if this is a feature you'd like to see.

**Comment by amchew** [comment]
Hey @fileman! Just wanted to let you know that we’re created a feature to return and expose the access token (JWR) to users in the signIn() method, and will be working on it shortly. Will update again when it’s live.

**Comment by futie** [comment]
I also need the ability to retrieve the JWT if the user is already signed in or can be signed in silently. Ideally a call to SignIn with a (bool silent=True) parameter - this can then be called when the UI is being rendered - to display a 'Login' or 'Logout' button as appropriate.

**Comment by amchew** [comment]
Hi @futie, thanks for the feedback, and got it on your feature request to return whether silent sign-in is true. I've added this to our backlog. 

For both @futie and @fileman, we're always looking for feedback to improve Auth, would you be available to hop on a call with me to learn more about your experience? Email me at amchew [at] microsoft [dot] com.

**Comment by brad302** [comment]
@amchew @guperrot 

**> As for refresh token, it is already handled, if you call SignInAsync again (after a successful first time), the second time it will be a silent sign-in.**

Just in relation to the above, yes, my experience is that it will pass straight through but if you have more than one identity provider enabled, the user will be presented with the provider selection screen and then once selected and if previously authenticated, it will silently pass through.

It would be nice to have a refresh token for the last successful login with the relevant provider so we can pass that straight through without even prompting the user to open the b2c webview login control.

Maybe I'm missing something but that's been my experience and a more seamless one would be really handy.  Apologies if this enhancement is being handled as a part of a future release already but I just wanted to get my 2 cents in.

I also concur re: the bearer token, to have that would be absolute gold.  Specifically for Azure AD in a corporate sense, to be able to use that token (if possible) to other O365 and Azure based services has some serious benefits.

Again, I hope I'm not speaking out of turn.

**Comment by amchew** [comment]
Hey @brad302, in our next release of the SDK (sometime in the third week of Jun - will keep y'all updated!), we will be exposing the access token and id token. You should be able to determine based on the token whether to show the user the login UI or not. 

For example, 
```var user=null;
try {
    user = Auth.SignIn();
} catch() {...}

if (jwt != null) // detect signin
doWork();```

Would that work for your scenario?

Not sure if you really need the refresh token for this scenario. Let us know if you do, and what you're using it for. 

Don't apologize. We really appreciate all the feedback! 👯‍♂

**Comment by amchew** [comment]
Hi @fileman, @futie, @brad302 (and @landrzz, @sdg85)! 

An update: we completed the feature to expose the access and id token and this will be released in the next version of our SDK - before the end of June. 

We'll be sharing in our documentation how to parse the access and id token, what actions to take if the user is signed in or not. Also, with today's current feature set, you can determine if the user is signed in or not by calling `SignInAsync` again. If you do that, the SDK will not show the sign-in UI again, it will only do so if the saved sign-in information has expired or has been revoked by the authentication server.

**Comment by brad302** [comment]
@amchew you guys rock, massive thanks!  I'll keep an eye out for it and feedback where appropriate.

**Comment by fileman** [comment]
@amchew is there appcenter nightly/myget CI build?

**Comment by amchew** [comment]
Hey @fileman, @futie, @brad302, @landrzz, @sdg85, @masatoru, @damienaicheh, you can now get the access and id tokens for Auth in the 2.1.0 SDK release!

Here are the repos and documentation for the following platforms:-

**Xamarin**
- [Xamarin repo](https://github.com/microsoft/appcenter-sdk-dotnet/releases)
- [Xamarin documentation](https://docs.microsoft.com/en-us/appcenter/sdk/auth/xamarin#get-access-token-and-id-token)

**iOS**
- [iOS repo](https://github.com/microsoft/appcenter-sdk-apple/releases)
- [iOS documentation](https://docs.microsoft.com/en-us/appcenter/sdk/auth/ios#get-access-token-and-id-token)

**Android**
- [Android repo](https://github.com/microsoft/appcenter-sdk-android/releases)
- [Android documentation](https://docs.microsoft.com/en-us/appcenter/sdk/auth/android#get-access-token-and-id-token)

Try it out, and let us know what you think! :)

**Comment by fileman** [comment]
@amchew is exactly what I need!
I close this issue because it is solved, if someone need something else, please open a new issue.

**Comment by supreettare** [comment]
Hey Guys, 
Am I missing something? 

I am using the latest stable version of Auth 2.6.1 on both Xamarin Android & iOS head projects as well is in my .Net Standard project (mine is a Xamarin Forms solution) 

I am calling SignInAsync every single time the app starts. Here is what I observe: 
On Android: The first time I get a login screen, I enter my credentials & hit Login, I get the tokens. 
On the 2nd run onward, SignInAsync is still called, but I do not get a Login UI. It just auto logs in. 

On iOS: First run shows login window & when correct credentials are added, it authenticates successfully. However. it keeps showing the login window on every subsequent calls as well. 

Am I missing something? Should I not call SignInAsync every single time & make it conditional based on certain conditions? If yes, what conditions? 

Your help on this is really appreciated. 

Thanks 
ST
