### ISSUE TITLE
Don't force Carthage builds when repo has a Cartfile

### ISSUE THREAD

**Issue by tonyarnold** [microsoft/appcenter#395]
Currently, it appears that if there's a `Cartfile` in the project root, `carthage bootstrap` will be run on every build. 

Here's my use case:

I use Carthage to refer to private repositories that aren't available to App Center, but I check the sources of all of my Cartfile dependencies into `Carthage/Checkouts`. Carthage is only used to update the project sources - I do not ever build the dependencies directly. Please read this post for information on how it works: https://www.mokacoding.com/blog/carthage-no-build/

I use the Xcode projects from this folder directly as subprojects, and let Xcode manage the build and integration of the Products from these dependencies. 

I do _not_ want App Center to automatically do anything related to Carthage, so for now I've added the following to my `appcenter-post-clone.sh`:

```bash
#!/usr/bin/env bash

set -ex

# Empty out Cartfile so that App Center doesn't attempt to build the dependencies.
echo '' > Cartfile
echo '' > Cartfile.resolved
```

Obviously this isn't ideal - Carthage still gets run, taking up valuable build time. Removing the Cartfile from the repo breaks the build entirely - it seems that App Center decides at some earlier point that it needs to run Carthage.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @tonyarnold. Understand that the workaround isn't ideal. We'll watch this to track additional interest as a potential future improvement.

**Comment by gadu** [comment]
a big +1 for this feature as well. we currently have scripts that download cached builds and only build invalid dependencies, then upload again so the next person won't have to build anything. Rome makes this very easy (https://github.com/tmspzz/Rome).

while we can get these scripts to run and and function as expected, the fact that `carthage bootstrap` is called every single time means we aren't able to leverage this to dramatically speed up our build times.

It seems like the least complex way towards giving devs their own path to solve requests for caching: https://github.com/microsoft/appcenter/issues/442

**Comment by mgoldin** [comment]
any updates?
