### ISSUE TITLE
Possibility to set the priority  of push messages to high

### ISSUE THREAD

**Issue by studeruss** [microsoft/appcenter#396]
**Describe the solution you'd like**
Add the possibility to increase the priority for push messages to high. On some Android versions, push messages are not received when the app is not running.

**Describe alternatives you've considered**
Alternatively set priority to high per default

**Comment by jwargo** [comment]
@studeruss thanks for that suggestion. This is something we want to add support for, and hope to be able to add this in a future SDK update.

**Comment by broderm** [comment]
@jwargo adding to @studeruss request, would be great to have that in a feature release soon.
We identified that the function **"Doze"** on certain Android mobile devices leads to the issue, that they d**o not receive push notifications**, as the priority of the push notification is sent with **"normal"**. We would love to be able to set that to **"high"** priority (either per default or configured) in order to reach everyone no matter if "Doze" is setup or not.

Thx for your update!

**Comment by shnaz** [comment]
This is also something we have issues with. Could be very useful.

**Comment by jwargo** [comment]
OK, so help me out here - how would you see this working. My concern is that if we let users set priority, they'll set everything to high and we may get kickback from the target PNS. How do we implement this while at the same time keeping it from being abused?

**Comment by shnaz** [comment]
@jwargo I don't think appcenter should do anything as FCM already handles over-usage or abusing of the high priority notifications.
https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message

**Comment by adrianknight89** [comment]
@jwargo Any update on this? Android notifications are sometimes delivered literally MINUTES later. I need much faster delivery, especially for a chat app that falls back to push notifications when websockets cannot / should not be used.

**Comment by jwargo** [comment]
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
