### ISSUE TITLE
Generate New Appcenter Secret

### ISSUE THREAD

**Issue by johnxy84** [microsoft/appcenter#397]
**Describe the solution you'd like**
Often times users can have their secrets compromised. There should be an option to generate a new  secret for an app rather than creating a whole new project entirely as have  happened several times. Usually because a lot of  other things  like build configs and signing  keys  and  store accounts are already configured
**Describe alternatives you've considered**
Creating new Projects  and reconfiguring everything

**Comment by patniko** [comment]
Hi @johnxy84, we've debated on renaming App Secret to something else because it isn't really intended to be a true secret. Users can only send analytics/crash logs to our ingestion service with that key to generate fake event data and/or perform certain update checks for public distribution groups. Rather than allow for new regeneration, would it be better for us to clarify that we don't view that guid as something that exposes any risk if compromised?

**Comment by johnxy84** [comment]
I'm sort of the opinion that spamming the developer with wrong analytical data or crash events poses as a form of risk as decisions can be carried out due to this data.

**Comment by oliver-eastpoint** [comment]
Hi All,
I was re-directed to here from the App center support team. I would like to +1 on this feature request.

Often when we use AppCenter to release to customers/users, we want analytics/crash reports. 
However we don't want the dev/tester usage to be included in that -- so It would be great to be able to create multiple secrets in the one project on AppCenter to separate the two environments. Or at least filter the analytics outcome to separate the two somehow.

We use AzureDevOps as a repository and mostly everything is handled with our CICD pipeline. Just for convenience sake we have a branch for releasing to our devs/testers, and another branch for releasing to respective app stores. It would work great for us if we can assign a different AppCenter Secret for each of those branches so the analytics gathered is clearly separated.

**Comment by georgegillams** [comment]
> it isn't really intended to be a true secret
I agree that documenting its purpose is a good move, but having an option to regenerate/revoke still seems pretty important functionality.
