### ISSUE TITLE
Cannot select a current app for Appcenter Github app

### ISSUE THREAD

**Issue by booker-dragon** [microsoft/appcenter#398]
**What App Center service does this affect?**
Appcenter Github app

**Describe the bug**
After reinstall Appcenter github app, there is no way to select an existing app for Github check

**To Reproduce**
1. Install Appcenter github app and complete setup for build configuration
2. Uninstall Appcenter github app and reinstall it
3. Cannot connect to the original app

**Expected behavior**
I should allow to make appcenter github app connecting to any app instead of creating a new one

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Any

**Smartphone (please complete the following information):**
 - Any

**Additional context**
I wanted to change the subscription and appcenter support suggested to uninstall the github app because the plan was managed by github

**Comment by granttj01** [comment]
On a similar topic, existing appcenter account holders (not created through the github app) should be able to set up their checks on a branch from within their existing appcenter account and branch configuration. Making users set up new accounts / branch configurations just to use the github app is not user friendly.

**Comment by nrajpurkar** [comment]
Thanks for bringing these issues up. I've changed this from a bug to a feature request as this is a [known limitation](https://docs.microsoft.com/en-us/appcenter/build/github-app#connecting-existing-apps). At the current time, you cannot connect the GitHub App Center app to existing apps in App Center. You have to create a new app.

**Comment by granttj01** [comment]
@nrajpurkar how likely is this to be looked into? As you can see from the link you posted, this has been a concern for Appcenter users for over a year now. What would be needed to create this feature?

**Comment by granttj01** [comment]
@nrajpurkar Here is another [link](https://github.com/MicrosoftDocs/appcenter-docs/issues/223) regarding the issue from almost a year ago.
Does Microsoft need support? I would be interested in taking a look.

**Comment by nrajpurkar** [comment]
@granttj01 It's definitely something we're aware of as an issue and a place where we can improve the experience. We're constantly balancing the issues and feature requests we see coming in to prioritize what comes next and this issue is included in that process.

**Comment by booker-dragon** [comment]
@nrajpurkar it is so disappointed to hear this
We wanted to subscribe more concurrent builds and followed your support team instruction to uninstall appcenter app on github and now we lost control over our existing apps

Can you provide support to make some changes maually to connect our github repo and existing app?

**Comment by putuyoga** [comment]
This should be a basic feature, to be honest.

**Comment by zarko-via** [comment]
In need of this, very risky if someone drops the GitHub app connection to GitHub.

**Comment by hannta** [comment]
I started to use appcenter before there was github app available, now im unable to connect github app to my existing appcenter app 😢

**Comment by philtomblin** [comment]
Are there any plans yet to implement this?

**Comment by enigmaturing** [comment]
I am also looking forward to see this issue solved ;(

**Comment by rddewan** [comment]
why it's taking so much time to fix this .. facing so much of trouble with this

**Comment by ashoemaker-penlink** [comment]
> In need of this, very risky if someone drops the GitHub app connection to GitHub.

May not work for your situation, but we just created apps in app center just for the github continuous integration, separate from the real build ones.  At least for us then, it's not big deal if we have to just drop and recreate those.

**Comment by hannta** [comment]
@ashoemaker-penlink your solution sounds interesting and may work for my use case too!

Could you describe your setup bit more detailed, how you did get it running? I have the same issue, my Appcenter apps are configured a way back and Im not able to connect them to github app. I want to get the build status report working for new pull requests.

What I did so far:
- I already have app configured in appcenter and it is connected to my repo in github.
- Create new app in Appcenter (which I try to use for build status)
- I configure branch/build for this new Appcenter app, to connect my Github repo
- How to connect github to newly created Appcenter app?
- Shoud I first remove Appcenter Aithub app? And hope it does not reset anything in Appcenter side?

I tried to follow this guide: https://docs.microsoft.com/en-us/appcenter/build/github-app

**Comment by Samit-BTE** [comment]
Any update on when this will be fixed?

**Comment by Fraserhardy** [comment]
This is also causing us problems too. We have AppCentre setup before Github, and our billing is handled via Azure. 
It seems we'd need to stop our subscription via Azure, start a new one via Github (which creates a new org) then set everything up again (and in the process loosing our build history). 

I really don't understand why its so complicated to just be able to make a OAuth connection to an existing AppCentre organisation, then choose which projects should be used for the CI in pull requests. 

Is there a plan to fix this anytime soon?

**Comment by isax5** [comment]
I'm interested in this feature too
What is going on?
I'm having many problems in pull requests > checks trying to integrate these things

**Comment by spourteymour** [comment]
Has anyone found an answer to this? I'm interested in this too. Thanks

**Comment by ELTEGANI** [comment]
Hey would you please solve it

**Comment by zarko-via** [comment]
Please allow connecting to repos via the App Center GitHub app.
This also do not increase the repo GitHub webhooks, important for repo general latency of work.
Also important if one has already too many other webhooks where another can not be established due to GitHub amount restriction.

**Comment by ghasemikasra39** [comment]
Any update on when this will be fixed?

**Comment by isax5** [comment]
Hey!, this is still not possible 🤷‍♂️

**Comment by isax5** [comment]
Are you serious?
Why no one fix this?

**Comment by narojunagaraju** [comment]
We need this feature

**Comment by isax5** [comment]
Is someone working here?

**Comment by malhobayyeb** [comment]
Is someone working here?

**Comment by dvertovsek** [comment]
3 year anniversary soon! I might be organizing a celebration or something, let me know who is keen to come ...

**Comment by NKalganov** [comment]
Hi! Does anybody know whether this feature was actually completed or it was just auto-closed due to inactivity?

**Comment by mohamedfarees** [comment]
Is someone working on this

**Comment by Fariz-fx** [comment]
Is someone working on this

**Comment by phuongthaodo0919** [comment]
It's like it hasn't fixed
