### ISSUE TITLE
AppCenter Dark Theme

### ISSUE THREAD

**Issue by Kaakati** [microsoft/appcenter#40]
**Describe the solution you'd like**
- Dark Theme

**Describe alternatives you've considered**
- Fabric Crashlytics Dark Theme

**Additional context**
- Screen Shots:

<img src="https://static1.squarespace.com/static/54ac6f9ae4b0cf1d82a4b59e/t/58d32fb6414fb50a6b3ab5f8/1490287074964/New-Fabric-Dashboard-Growth-Page?format=1000w">

<img src="https://cdn.dribbble.com/users/1262414/screenshots/4331791/dashboard-crypto.png"> 

<img src="https://i.stack.imgur.com/CXekL.png">

**Comment by patniko** [comment]
In case you were curious what that would look like - here's a previous exploration into an App Center dark mode @smockle did. More than a few people on our team would be open to actually making it happen if enough others want it.

![image](https://user-images.githubusercontent.com/26906478/52377651-5da32500-2a1a-11e9-9ffa-8b433e6a64cd.png)
![image](https://user-images.githubusercontent.com/26906478/52377662-63006f80-2a1a-11e9-9081-b6366d5c90e6.png)

**Comment by Kaakati** [comment]
@smockle Looking forward to it, the brown is a bit weird tho.

**Comment by mkgitalia** [comment]
I'ma a Dark theme fan, make it please !

**Comment by eman1986** [comment]
I want this so badly, every other dev web service I use has a dark mode so it's a big shock when I go to app center and get this bright dose of white

**Comment by blparr** [comment]
Hello all, I have great news - we have been working on some designs for App Center Dark Mode, and we will soon start with the implementation.

Here are some screens and components in Dark Mode - let us know if you have any feedback!

<img width="315" alt="Screen Shot 2019-05-08 at 2 32 31 PM" src="https://user-images.githubusercontent.com/22063767/57409832-26215180-719e-11e9-9652-0fc44511153b.png">

<img width="552" alt="Screen Shot 2019-05-08 at 11 59 11 AM" src="https://user-images.githubusercontent.com/22063767/57409843-2d485f80-719e-11e9-96ae-dfc7fd07957d.png">

Components in dark mode:
<img width="315" alt="Screen Shot 2019-05-08 at 2 32 31 PM" src="https://user-images.githubusercontent.com/22063767/57409851-31747d00-719e-11e9-84b1-55e3fa6f4816.png">

**Comment by tonyarnold** [comment]
Could you please also consider adding support for automatically switching between light and dark modes based upon the user's system setting in browsers that support it: https://webkit.org/blog/8840/dark-mode-support-in-webkit/

**Comment by RyanBuzzInteractive** [comment]
I almost forgot that App Center isn't dark, as I have the DarkReader plugin for Chrome which does a great job at intelligently auto theming pages. Obviously better if the site has a native mode though. This is how I see it
![image](https://user-images.githubusercontent.com/10651463/58806581-6691b500-860e-11e9-85e1-940ee89f4e7d.png)

**Comment by blparr** [comment]
Hi everyone! The team has been working hard to provide a preview of the dark mode version of App Center. We still have some work left to do, but if you would like to try it early on, I can enable it for your account.

Kindly let me know if you'd like to try it out!

Thank you,
Blanca

**Comment by tonyarnold** [comment]
@blparr I'd love to take a look, thanks!

**Comment by xkel** [comment]
@tonyarnold Yes, in browsers that support adapting to the OS theme an option will be present to 'auto-theme'!

**Comment by patniko** [comment]
Closing this now that preview has been shipped. https://twitter.com/VSAppCenter/status/1162469527671717890
