### ISSUE TITLE
Allowing App center Report to download locally with screenshots for a complete test run 

### ISSUE THREAD

**Issue by jayanths469** [microsoft/appcenter#402]
good to have -*It would good if user can download complete test reports including screenshots as PDF file 

This will help us with uploading test run data/Reports into defect life cycle or somewhere everyone can access.

**Comment by Oddj0b** [comment]
@jayanths469 would it be enough to serve you test results and screenshot so that you could produce your own PDF?

**Comment by ThejovathiS** [comment]
If we can download Test results and screenshots, we can create our own PDF too
