### ISSUE TITLE
Support Crash Metadata for UWP apps

### ISSUE THREAD

**Issue by chrisaswain** [microsoft/appcenter#403]
We currently use HockeyApp for crash reporting for our UWP apps. It allows us to add extra `description` data for each crash and we use that to provide more context about what the user was doing when the crash happened. According to your documentation for AppCenter, adding this extra data for crashes is not supported. We really need this feature to help us debug crashes because it gives us enough context to be able to recreate the the scenario that caused the crash for the user.  

Example API from HockeyApp (`SetExceptionDescriptionLoader`):
https://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/how-to-instrument-applications-on-windows-for-crash-reporting#2-1-crash-description-api

**Comment by lumaxis** [comment]
Hey @chrisaswain! We have posted a proposal for our plans for upcoming improvements to App Center's Windows support at https://github.com/microsoft/appcenter/pull/193

Among other things:
>- Crash reporting capabilities for store and sideloaded UWP (.NET Native), WPF and WinForms (.NET Framework) apps aligned with other platforms supported in App Center.

Please check it out and leave any feedback you might have 🙂

**Comment by chrisaswain** [comment]
This issue can be closed.  `Crashes.GetErrorAttachments` provides what is needed.
