### ISSUE TITLE
iOS Pushkit Voip Notification

### ISSUE THREAD

**Issue by DouglasMarq** [microsoft/appcenter#405]
Hello,

I would like to request a feature, which i don't know why no one has requested since yet.

I am developing a complete voip app, while i am adding callkit feature into the app, i was wondering how do i re-activate my killed/suspended app to receive an incoming call, and then apple came with Pushkit API, it re-activate (non-forced killed) apps, refresh the data whenever push notification arrives and goes back into "sleep" mode.

But i could not find a way to make a voip push notification through Appcenter.

Push notification =/= Voip push notification

Apple allows up to 4kb of payload inside a voip push notification, among with other things, which is great.

**Comment by jwargo** [comment]
@DouglasMarq interesting suggestion - I'll take a look and discuss this with the Engineering team.

**Comment by jwargo** [comment]
@DouglasMarq I looked into this a bit and I'm a little unclear on something, can you fill in a blank for me? Do you use this push type to initiate the VOIP call, or does all data get delivered through it?

**Comment by DouglasMarq** [comment]
I am using it to wake up both the application and the device whenever there is a call incoming. Asterisk receives a call, then it triggers a code to send the device pushkit token to the apple server, so apple sends a pushkit notification to the device, then my app starts in the background and receives any incoming call.

I use pushkit along with callkit, so it shows native call screen before my application call screen (which can be swapped from native call screen).

Currently, i am not using it to deliver data, i am not sure if i will ever have to.

I use push notification from appcenter to send notifications to the android, it would be nice to have pushkit in appcenter, so i could have both in the same platform,  that's kinda good, because i don't have to maintain two different codes. And i'm developing with Xamarin.Forms.

**Comment by jwargo** [comment]
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
