### ISSUE TITLE
Test Crashes not being submitted to AppCenter

### ISSUE THREAD

**Issue by comply365dev** [microsoft/appcenter#406]
**What App Center service does this affect?**
Microsoft.AppCenter.Crashes

**Describe the bug**
Following the SDK installation instructions, and using "Microsoft.AppCenter.Crashes.Crashes.GenerateTestCrash();" 
the test crash does not push to AppCenter

**To Reproduce**
1. Create new app in AppCenter
2. Create new Xamarin.Android app in visual studio
3. Follow SDK install instructions
4. use "Microsoft.AppCenter.Crashes.Crashes.GenerateTestCrash();" to generate crash (can also just throw an exception too, that doesn't work either)
5. re-open App and see error in "Debug" section below when it tries to upload it.

**Expected behavior**
Should send the test crash to AppCenter

**Debug**
05-14 13:14:14.413 E/AppCenter(14236): Sending logs groupName=groupErrors id=16622a48-51d4-47f2-8ecc-3c9c9ddbdef5 failed
05-14 13:14:14.413 E/AppCenter(14236): com.microsoft.appcenter.http.HttpException: 400 - CorrelationId: 6d8935db-4db6-4d64-9180-d4a794952333  ReasonCode: NoValidLogsFoundInLogContainer 
05-14 13:14:14.413 E/AppCenter(14236): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:305)
05-14 13:14:14.413 E/AppCenter(14236): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:319)
05-14 13:14:14.413 E/AppCenter(14236): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:47)
05-14 13:14:14.413 E/AppCenter(14236): 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
05-14 13:14:14.413 E/AppCenter(14236): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-14 13:14:14.413 E/AppCenter(14236): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-14 13:14:14.413 E/AppCenter(14236): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-14 13:14:14.413 E/AppCenter(14236): 	at java.lang.Thread.run(Thread.java:762)

**Further Debug info**
1. Using AppCenter.LogLevel = LogLevel.Verbose
 "App Center SDK configured successfully." is printed and the payload doesn't look malformed, it's just the default "type":"Microsoft.AppCenter.Crashes.TestCrashException","message":"Test crash exception generated by SDK"

**Comment by winnieli1208** [comment]
@comply365dev do you mind starting a conversation in the blue chat bubble on the bottom right of App Center and link this conversation? This will connect you to our support and engineering team who can take a closer look at this for you. Thanks!

**Comment by comply365dev** [comment]
done

**Comment by comply365dev** [comment]
Figured it out w/ the help of Jorge Medellin.  Local device timestamps was set ahead of local time.  Putting this here in case anyone has this issue and searches for NoValidLogsFoundInLogContainer

**Comment by winnieli1208** [comment]
Glad to hear! Thank you for the update and for sharing the solution. I will close this issue for now but people can still refer/reopen this if they face the same problem.
