### ISSUE TITLE
Binary attachment

### ISSUE THREAD

**Issue by antbe80** [microsoft/appcenter#409]
**What App Center service does this affect?**
AppCenterCrashes

**Describe the bug**
Binary attachment is inaccessible for native (c++) crashes on android platform. There is only minidump.dmp on ATTACHED BINARY tab.
A quote from correspondence with support engineer "I've just checked that the SDK sends binary attachment besides native crash as expected. But it looks like the backend treats minidump as usual user's attachment. I'm going to file another bug to our board for it. We have to add a special note in the docs at least.
You can use only text attachment with native crashes at the moment."

**Expected behavior**
An ability to attach binary data to crashes is very important feature. Please fix it.

**Comment by eyenie** [comment]
Hello, any ETA for this to be implemented? We in "Playrix" use binary attachments for native crashes in all of our applications in HockeyApp. We really need it, because it helps us to analyze issues.
It blocks our transition to App Center.

**Comment by winnieli1208** [comment]
@antbe80 thanks for your patience. Due to other priorities, we haven't had a chance to look into this. We have a bug item on our board to fix this and expect it to be picked up in the next few weeks. I'll keep you posted when I have a better ETA. 

Thanks!

**Comment by winnie** [comment]
Hi @antbe80 - we recently implemented a fix so you should now be able to add attachments with your Android native crash reports. Closing this issue but please reach out to our support team if you run into any issues. Thanks!
