### ISSUE TITLE
AppCenter Test + Device Leases

### ISSUE THREAD

**Issue by cofitz1** [microsoft/appcenter#411]
Are there any plans to support "leasing" a device for use in a DevOps pipeline for a period of time instead of only supporting test workloads that run directly on the device unassisted? I have scenarios where using adb directly on a device is necessary to orchestrate testing - ideally a DevOps task could be used to get a device that is accessible for all of the remaining tasks in the pipeline.

**Comment by winnieli1208** [comment]
Thanks for the feature request! This isn't currently on our roadmap but I'll let @Oddj0b jump in if we have any future plans to support this scenario. 

Thanks!
