### ISSUE TITLE
Please create user feedback tools

### ISSUE THREAD

**Issue by instantiator** [microsoft/appcenter#412]
**Describe the solution you'd like**
It would be great to be able to add features to App Center enabled apps, so that users can leave feedback, comments and bug reports directly from the app. These are then collated and managed inside App Center as conversations between the user and developer.

**Describe alternatives you've considered**
There are also existing third-party systems, but they lack the benefits of integration with the app distribution centre (such as being able to tie versions of the app to the comments, for instance). It would be superb to be able to conduct all testing, including user-acceptance testing through App Center.

**Additional context**
HockeyApp provided this capability, and it was really valuable: https://hockeyapp.net/best-practices/users-know-best.html

I recently emailed App Center about it, and was asked to leave a FR here for consideration. Thank you!

**Comment by botatoes** [comment]
Thank you for the suggestion. Will keep this in mind for future distribution related features.

**Comment by sathukorale** [comment]
Would love to have this as well (was somewhat worried to discover that it is not), because this was the biggest selling point of HockeyApp for me. 

Even though auto-generated/collected bug reports are usefull (Fabric has the same feature doesn't it), I have faced many issues that I wouldn't have been able to fix, yet alone recreate without the help of users. And aside from simple bug fixing, this opens a channel for feature requests as well. 

All-in-all this single feature let me communicate with my clients to deliver more user-friendly and intuitive fixes and features.

**Comment by Iomegan** [comment]
I am shocked to realise that there is no user interface for my Mac users to add comments and an email address for further questions from the developer. Many bugs only happen with certain configurations or workflows and often the only way to figure that out is to get in contact with the user.

Please add a crash report window as we know it from HockeyApp. It should be fairly simple and adds great value to App Center.

**Comment by gugelcec** [comment]
Hi
feedback is a great functionality in Hockeyapp, please add also to AppCenter, would be good to have it also for the windows app!

**Comment by nweigl** [comment]
+1 for feedback. We're currently using Instabug (which I'm not a big fan of, btw) for feedback, but it would be nice to have feedback integrated into appcenter so that we can get off instabug.

**Comment by ilset** [comment]
This is an incredibly important feature for our team that is currently in HockeyApp. I hope App Center supports this feature as missing it is a downgrade for us. Please support it, thank you!

**Comment by jesusvms** [comment]
This is a fairly significant regression in functionality from hockeyapp.  Please do not force us off of hockeyapp until you add this in AppCenter.

**Comment by Iomegan** [comment]
Well it was easier than thought using the attachment API and the MSUserConfirmationHandler.

A simple implementation for macOS would be:

```
MSCrashes.setDelegate(self) // NOTE: You must set the delegate before calling [MSAppCenter start], since App Center starts processing crashes immediately after the start.
MSCrashes.setUserConfirmationHandler { (errorReports: [MSErrorReport]) in
     self.crashNameTextField.stringValue = self.defaults.string(forKey: "CrashUserName") ?? ""
     self.crashEmailAddressTextField.stringValue = self.defaults.string(forKey: "CrashEmailAddress") ?? ""

     let alert: NSAlert = NSAlert()
     alert.messageText = "Sorry about that!"
     alert.informativeText = "Do you want to send an anonymous crash report so we can fix the issue?"
     alert.addButton(withTitle: "Send")
     alert.addButton(withTitle: "Don't send")
     alert.alertStyle = .warning
     if errorReports.count == 1 {
         alert.accessoryView = self.crashView
     }
     else {
         // no support for multiple crashes. Might not be useful because the user does not know which crash happened when
     }
     switch alert.runModal() {
     case .alertFirstButtonReturn:
         self.defaults.set(self.crashNameTextField.stringValue, forKey: "CrashUserName")
         self.defaults.set(self.crashEmailAddressTextField.stringValue, forKey: "CrashEmailAddress")
         self.crashUserProvidedDescription = "Name: \(self.crashNameTextField.stringValue)\n\nEmail Address: \(self.crashEmailAddressTextField.stringValue)\n\nDescription: \(self.crashDescriptionTextFiew.string)\n\n"
         MSCrashes.notify(with: .send)
     case .alertSecondButtonReturn:
        MSCrashes.notify(with: .dontSend)
     default:
         break
     }
            
    return true
 }
```


`crashView` is a custom view with name and email textfield and a textview for user comments.

Don't forget these delegates:

```
 private var crashUserProvidedDescription: String?
 func attachments(with crashes: MSCrashes, for errorReport: MSErrorReport) -> [MSErrorAttachmentLog] {
     guard crashUserProvidedDescription != nil else {
         return []
     }

     let attachment1 = MSErrorAttachmentLog.attachment(withText: crashUserProvidedDescription!, filename: "UserProvidedDescription.txt")
     return [attachment1!]
    }
    
 func crashes(_ crashes: MSCrashes!, didFailSending errorReport: MSErrorReport!, withError error: Error!) {
     crashUserProvidedDescription = nil
 }
    
 func crashes(_ crashes: MSCrashes!, didSucceedSending errorReport: MSErrorReport!) {
     crashUserProvidedDescription = nil
 }
```

This is how it will look on AppCanter:

<img width="380" alt="Screenshot 179" src="https://user-images.githubusercontent.com/1634465/69230074-ebee2f00-0b86-11ea-84d4-fb1b49cd00c2.png">

**Comment by nishiarya** [comment]
Hi,
Feedback is very important and useful feature please include this to your roadmap.

**Comment by srgiitd** [comment]
It's terrible that we were forced to switch to the appcenter from Hockeyapp without this feature available! It's not practical to make some arrangements to get feedback or bug reports from testers especially if they are externals.
Is there any plan to add this feature or we should explore alternatives to appcenter?

**Comment by Iomegan** [comment]
Why not use the attachment for user feedback?  It’s not difficult at all.

**Comment by nishiarya** [comment]
> Why not use the attachment for user feedback? It’s not difficult at all.

Are you sure that attachment you are talking about not more intended to the crash reporting attachment? Because here every one is looking for general feedback form which can be utilise for several situations like Simple App Feedback or Rating Feedback etc.

**Comment by Iomegan** [comment]
Sorry,
You are right. There was a general feedback feature in HockeyApp. My approach only covers feedback the user can send alongside a crash report.
