### ISSUE TITLE
Update Build Configuration if any of post-clone, pre-build, or post-build scripts gets added or removed.

### ISSUE THREAD

**Issue by MichaelMackendMS** [microsoft/appcenter#414]
**Describe the solution you'd like**
It is a known issue (https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/general#when-do-i-have-to-update-my-build-configuration-manually-through-save--build) that build configurations do not update when custom build-phase scripts are added or removed.  This is particularly problematic for those of us leveraging your service for CI/CD.  I would like to not have to use the web portal any time a build-phase script is added or removed.  It should just happen automatically.

**Describe alternatives you've considered**
Another option would be to provide in the CLI or API some mechanism for manually triggering a refresh of the build script detection. 

**Additional context**
I added a post-clone script to my repo and triggered a CLI build.  It failed because it didn't run the script.  I went to the portal, opened the config, saved it, and built again.  The build ran the post-clone script as expected.  I only knew that this was necessary after some 2 hours of debugging and ultimately turning to your troubleshooting docs in desperation.  I was one step away from an email with our AppCenter contact. :)

Let's see some of that customer obsession in action! 💯

**Comment by nrajpurkar** [comment]
Thanks for the feature request here @MichaelMackendMS. Related to #265, we can make it clearer that you need to save the build configuration for scripts to be triggered. We'll take a deeper look into improving this experience.
