### ISSUE TITLE
Feedback requested on vulnerability report in an app that uses the App Center SDK

### ISSUE THREAD

**Issue by tiesmaster** [microsoft/appcenter#415]
We're working on an app that's going to go live in a couple of weeks. We will be issuing an external pen test on the app, but we wanted to be proactive, and check the app beforehand. I've run the app through a free vulnerability scanner (Quixxi), and a number of things are caused by adopting the App Center SDK (we're on Xamarin).

I don't think these are a security risk, but wanted to check with the App Center development team. Probably, this is on your radar, but if not, it might be good to have a discussion on this (and put it on `docs.microsoft.com` to improve visibility of this).

---

These are the things from the report (I can't upload the report, because of disclaimer):

 * 1.8.1 File unsafe Delete Check (High)
   * Risk: Everything you delete may be recovered by any user or attacker, especially rooted devices. 
   * Thread: When you delete a file using file.delete(), only the reference to the file is removed from the file system table. The file still exists on disk until other data overwrites it, leaving it vulnerable to recovery.
   * Technical Details:
> This app uses file.delete() to delete file,File deleted using file.delete() may be recovered by any
user or attacker, especially rooted devices. Please make sure do not use "file.delete()" to delete
essential files.This app uses file.delete() in following methods

````
1.com.microsoft.appcenter.crashes.Crashes$9.run()
2.com.microsoft.appcenter.crashes.Crashes.processMinidumpFiles()
3.com.microsoft.appcenter.crashes.Crashes.processPendingErrors()
4.com.microsoft.appcenter.crashes.Crashes.saveErrorLogFiles()
5.com.microsoft.appcenter.crashes.Crashes.applyEnabledState()
6.com.microsoft.appcenter.persistence.DatabasePersistence.deleteLog()
7.com.microsoft.appcenter.persistence.DatabasePersistence.deleteLogs()
8.com.microsoft.appcenter.utils.storage.FileManager.delete()
````

 * 1.9.1 Outputting Logs to logCat/ Logging Sensitive information (Medium)
   * Risk: Logging sensitive information can leak sensitive information to malicious apps. 
   * Thread: Android provides capabilities for an app to output logging information and obtain log output. Applications can send information to log output using the android.util.Log class. To obtain log output, applications can execute the logcat command. 
   * Technical Details:
> Android provides capabilities for an app to output logging information and obtain log output.
Applications can send information to log output using the android.util.Log class. To obtain log
output, applications can execute the logcat command

````
1. com.microsoft.appcenter.utils.AppCenterLog.debug()
2.com.microsoft.appcenter.utils.AppCenterLog.info()
3.com.microsoft.appcenter.utils.AppCenterLog.verbose()
4.com.microsoft.appcenter.utils.AppCenterLog.warn()
````

 * 1.10.3 Unencrypted Credentials in Databases (sqlite db) Vulnerability check (Low)
   * Risk: Unencrypted Credentials in Databasesexposes credentials that allow unauthorized individuals to act with the identity and permission of trusted individuals and systems.
   * Thread: SQLite is an in-process library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
   * Technical Details:
> This app is not using SQLCipher(http://sqlcipher.net/) to encrypt or decrypt databases.Usage of
SQLiteDatabase classes found in following methods

````
1.com.microsoft.appcenter.utils.storage.DatabaseManager.getDatabase()
2.com.microsoft.appcenter.utils.storage.DatabaseManager.clear()
````

----

Let me know if you have any additional questions. Thanks for the great service, already enjoying using App Center!

**Comment by patniko** [comment]
Hi @tiesmaster, these are definitely on our radar, but we view them as low-risk given the type of services we provide in App Center. Regarding `File.delete()` and logging we do make sure there isn't information in the crash payload worth compromising and work hard to make sure we aren't sharing sensitive information in logcat. We'll definitely explore things like SqlCipher as we add scenarios to our new Auth/Data services in the future that directly manage your customers data, but it's not something currently on our backlog.

**Comment by tiesmaster** [comment]
@patniko Thanks for the reply. Good to know this is on your radar (didn't expect anything less :wink). Do you have any GitHub issues I can subscribe to?

I don't really see anything concrete for a `docs.microsoft.com` contribution, do you?
