### ISSUE TITLE
 Support for Appium with TestNg

### ISSUE THREAD

**Issue by SVCAppCenterGit** [microsoft/appcenter#418]
**Describe the solution you'd like**
AppCenter Support for Appium with TestNG

**Describe alternatives you've considered**
We considered Appium with JUnit which is supported - we have our testing framework already built in TestNg and that leverages TestNg specific features not available in JUnit such as parameterized test and dependency test

**Additional context**
Our automation testing framework based on TestNG is around 10 years old with lots of features implemented unrealistic to convert to JUnit.

**Comment by Oddj0b** [comment]
I'm the program manager responsible for App Center Test and I'm working on a new idea which will support more frameworks in Test, allow unit testing, and browser testing. I would like to talk to you about it and understand your needs better.

Below is a link where you can sign-up for a 30-minute call with me. The agenda will be about the value of testing for you and your organization, and my new idea to allow more frameworks and testing styles in App Center Test.

Link to choose https://calendly.com/vigimm/appcenter-test

**Comment by suankan** [comment]
I'm also interested int this feature. I'm working on a UI testing codebase which uses TestNG and there is a huge appetite in my client to use Appcenter Test. But migrating to Junit seems to be a bit overkill.

Are there any roadmap or plans for supporting TestNG?
