### ISSUE TITLE
Web-based UI upload

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/appcenter#419]
**Describe the solution you'd like**
I want to upload apps directly like in HockeyApp.
**Describe alternatives you've considered**
Hockeyapp.
**Additional context**

**Comment by botatoes** [comment]
Hi, can you elaborate a little bit more on what you mean by uploading apps directly? What kind of apps?

You should be able to upload apps directly into App Center now.

**Comment by sseyod** [comment]
From my perspective - I want an app like the current native HockeyApp client for macOS. I hope this helps...

**Comment by kayvonkamyar** [comment]
![IMG_3776](https://user-images.githubusercontent.com/43690204/60400461-d5d4c900-9b28-11e9-9768-cbe96d5edf7d.png)
When you click new app, it will look something like this.

**Comment by sseyod** [comment]
Hi @kayvonkamyar,

Thanks for that. You're showing the Web-based UI.

I'm referring to an AppCenter equivalent of the native "HockeyApp app" for macOS, which was *great* for uploading builds.

Best, Pete

**Comment by kayvonkamyar** [comment]
> Hi @kayvonkamyar,
> 
> Thanks for that. You're showing the Web-based UI.
> 
> I'm referring to an AppCenter equivalent of the native "HockeyApp app" for macOS, which was _great_ for uploading builds.
> 
> Best, Pete

**Comment by kayvonkamyar** [comment]
> Hi @kayvonkamyar,
> 
> Thanks for that. You're showing the Web-based UI.
> 
> I'm referring to an AppCenter equivalent of the native "HockeyApp app" for macOS, which was _great_ for uploading builds.
> 
> Best, Pete

I don’t have a Mac. 🥺 I want web upload.
There is actually a way to upload files But it’s a pain in the ass.

**Comment by kayvonkamyar** [comment]
> Hi @kayvonkamyar,
> 
> Thanks for that. You're showing the Web-based UI.
> 
> I'm referring to an AppCenter equivalent of the native "HockeyApp app" for macOS, which was _great_ for uploading builds.
> 
> Best, Pete

Sorry 4 that.

**Comment by lumaxis** [comment]
@kayvonkamyar Thanks for the screenshot! I think I better understand what you're referring to.
Would you mind improving the title and description of this issue a little so it better reflects and describes in more detail what exactly you are asking for? Thanks!

**Comment by lumaxis** [comment]
@sseyod Would you mind opening a separate, [new feature request](https://github.com/microsoft/appcenter/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=) for this? 
Maybe also include details for what about the upload process through the Mac app you like better than the web UI and if you've already checked out our [CLI tool](https://github.com/Microsoft/appcenter-cli)?

**Comment by sseyod** [comment]
Hi @lumaxis - have done, thanks for the suggestion - https://github.com/microsoft/appcenter/issues/664
I hope somebody at Microsoft reads it and sees where I'm coming from!

The CLI tool seems almost entirely lacking in documentation and examples! Am I missing something?
