### ISSUE TITLE
Cannot remove HockeyApp nor unlink HockeyApp

### ISSUE THREAD

**Issue by RZeff** [Microsoft/appcenter#42]
After migration to App Studio, I cannot delete the HockeyApp app in App Studio.

**Comment by patniko** [comment]
Hi @RZeff, are you referring to the ability to cut the side by side experience so you can complete your migration to App Center and discontinue use of HockeyApp? If so, that is an experience we are working on right now and will share details around in the near future.

**Comment by derpixeldan** [comment]
We're currently working on a migration option for apps so they're exclusively available on App Center afterwards. Is that what you're looking for @RZeff ?

It's noted in our [Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#hockeyapp)

**Comment by RZeff** [comment]
Yes, I have migrated from HockeyApp

**Comment by derpixeldan** [comment]
@RZeff currently you can't migrate anything from HockeyApp to App Center yet. But we're working on that. If you have re-created things on App Center and want to get rid of the HockeyApp apps, you have to delete them on HockeyApp. However, we're offering to move apps very soon.

**Comment by derpixeldan** [comment]
A first step to move apps from HockeyApp to App Center is described and tracked here https://github.com/Microsoft/appcenter/issues/230
