### ISSUE TITLE
Will installing Github app override my subscription in billing?

### ISSUE THREAD

**Issue by booker-dragon** [microsoft/appcenter#420]
**What App Center service does this affect?**
Build

**Describe the bug**
We followed the instruction from appcenter engineer to uninstall github app and subscribe more concurrent build in appcenter billing section
I lost build status report in my repo now because github app is uninstalled

**To Reproduce**
1. Install appcenter github app in Github marketplace
2. Configure build for target branch and build status appear in PR checks
3. Uninstall github app and upgrade subscription (4 concurrent builds)
4. No connection any more for my new PR

**Expected behavior**
I should allow to get build status with 4 concurrent build

**Screenshots**
N/A

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
We upgrade our plan because we have loads of PR which 2 concurrent builds from github app plan is not enough for us
We upgrade it to 4 but now we are afraid installing github app will override the scubscription and thus we cannot leverage from more concurrent build to boost our development

Please let me know if I install github app, could I have 4 concurrent build?

**Comment by jwhiteDev** [comment]
Hello! Based on my understanding, just setup the GitHub app with the free tier, as it should use the billing that App Center already has. You should not need to setup a paid plan on the GitHub side if you already have it set in App Center. If there is an issue please let us know and we can investigate but that is the behavior that should take place.
