### ISSUE TITLE
URL to refer Code Coverage or any custom Badge generated during AppCenter build process

### ISSUE THREAD

**Issue by sasivishnu** [microsoft/appcenter#423]
**Describe the solution you'd like**
Hi, Thanks for continuously improving AppCenter. 

Currently from AppCenter we get badge for build status if configured.
![image](https://user-images.githubusercontent.com/23331470/57774496-4de15e00-7738-11e9-90d0-2e2d03107c21.png)

I understand that AppCenter currently doesn't have in-built support for unit testing and calculating code coverage. I am currently using Coverlet tool to generate code coverage file and I can get "code coverage % badge" generated using "Report Generator" tool. 

If we get an option where we can place our generated badges at predefined location and AppCenter provides URL to get those badges, then it will be very cool.

**Describe alternatives you've considered**
CodeCov and other CI/CD gives this kind of badges. But we are using AppCenter for our entire CI/CD process.

Let me know if you need any more details.

**Comment by sasivishnu** [comment]
Any update on this?

**Comment by nrajpurkar** [comment]
@sasivishnu Hi there, no update on this from our side but we will continue to track this as a potential feature
