### ISSUE TITLE
Cannot create app with non-english name through API

### ISSUE THREAD

**Issue by devinkav** [microsoft/appcenter#424]
**What App Center service does this affect?**
App Center API

**Describe the bug**
I cannot create an App that contains a non-english character in the "name" field using the API. When imported from HockeyApp or using the App Center web interface it will translate a Chinese character to the pronunciation (EG: zheng1-ba4-ji2) but it does not work with the API 

**To Reproduce**
1. Use the '/v0.1/orgs/{org_name}/apps' POST API
2. use this for the request data:
{
	"description": "test description ",
	"display_name": "api - test - display name",
	"name": "争超漫-test",
	"platform": "Unity",
	"os": "Android"
}

3. Notice the error returned is:
{
  "error": {
    "code": "BadRequest",
    "message": "Validation error: Validation is failed"
  }
}

Not only does it fail - it does not tell you exactly why it failed.

4. Use the same API with this data:
{
	"description": "test description ",
	"display_name": "api - test - display name",
	"name": "english-test",
	"platform": "Unity",
	"os": "Android"
}
4. Notice how it successfully creates the App

**Expected behavior**
1. Using a non-english character in the name should still allow the app to be created.
2. Validation error should be more descriptive as to what failed and why. 

**Desktop (please complete the following information):**
 - OS: Mac OSX 14.14
 - Browser: Firefox
 - Version: 66.0.4

**Additional context**
Also happens if you use arabic language instead of the chinese characters

**Comment by lumaxis** [comment]
@devinkav I believe this is correct behavior. The content of the `name` field has to be URL-compatible, i.e. basically ASCII.
If you want the behavior from the web UI, try passing in just the `display_name`, that should create convert the Chinese characters to the pronounceable version automatically.

For 3., we can definitely look into improving the error message here 😅

**Comment by devinkav** [comment]
Thanks for the quick response. I've tested using display_name without a 'name' and it seems to work. I'll go ahead with using that. Thanks for the help!
