### ISSUE TITLE
ARM64 Support for Crashes (UWP)

### ISSUE THREAD

**Issue by DominicMaas** [microsoft/appcenter#425]
### **Description**

Visual Studio 15.8 was released a few days ago which provides ARM64 support for UWP. I managed to target my project to ARM64, and setup the appropriate "RuntimeIdentifiers", but when I build the project I get the following error:

`Please build your project specifically for one of the following platforms: x86, x64, ARM`

### **Repro Steps**

1. Create a new UWP Project (Visual Studio 15.8)
2. Install the `Microsoft.AppCenter.Crashes` nuget package (1.8.0).
3. Create a new configuration based off ARM called ARM64.
4. Add `<RuntimeIdentifiers>win10-arm64</RuntimeIdentifiers>` to the .csproj file to allow building.
5. See `Please build your project specifically for one of the following platforms: x86, x64, ARM` error on build.

### **Details**

- **App Platform:** UWP (ARM64)
- **SDK Version:** 1.8.0

**Comment by cjw1115** [comment]
We need ARM64 support!

Our product will ship to arm64 device, and we use AppCenter to monitor  something. If AppCenter is not support arm64, it will block our product. May we only use other analytic service.

**Comment by myokeeh** [comment]
Almost a year ago, ARM64 support was added to UWP.

**Comment by myokeeh** [comment]
FYI, it seems I can now use `Crashes` and have the Store accept ARM64 submissions with the help of this NuGet package: https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlite3/2.0.1-pre20190815133105.

https://github.com/ericsink/SQLitePCL.raw/issues/254

**Comment by tipa** [comment]
Any updates on this?

**Comment by ahbilal-ms** [comment]
We are seriously considering this and will have an update for you all. Expected release timeline is end of this year or early next year. Apologies that this got dragged for a long time.

**Comment by dpaulino** [comment]
Hey appcenter team, any updates on this? The Surface Pro X is out and my customers are asking for an ARM64 build in order to take full advantage of their device. Can you increase the priority of ARM64? My goal is to deliver a good experience on Surface Pro X. This issue is blocking me

**Comment by ahbilal-ms** [comment]
@dpaulino: This feature is next in line and the team will take it on after completion of existing workstream. Once there is more clarity(expected within next few days), I can update you with a more concrete timeline.

**Comment by dpaulino** [comment]
@ahbilal-ms I appreciate the response. Looking forward to the concrete timeline.

**Comment by cjw1115** [comment]
The reason is clear.
* AppCenter  dependent on sqlite-net-pcl (>= 1.3.1)
* sqlite-net-pcl (>= 1.3.1) dependent on SQLitePCLRaw.bundle_green (>= 1.1.2)
* SQLitePCLRaw.bundle_green (>= 1.1.2) dependent on SQLitePCLRaw.lib.e_sqlite3.v140 (>= 1.1.2)

SQLitePCLRaw.lib.e_sqlite3.v140 (>= 1.1.2) only supports x86,x64 and arm32.

But for now,  SQLitePCLRaw.bundle_green latest version is 2.0.2,
SQLitePCLRaw.bundle_green (>=2.0.2) dependent on SQLitePCLRaw.lib.e_sqlite3 (>= 2.0.2)

SQLitePCLRaw.lib.e_sqlite3 (>= 2.0.2) support ARM64 now.

So we can try to update the version of SQLitePCLRaw.bundle_green to 2.0.2 to resolve this issue.

**Comment by tipa** [comment]
@cjw1115 I have the feeling that simply installing that Nuget package doesn't resolve the problem. Yes - the app can be built successfully and passes Store certification, however AppCenter seems to stop working, e.g. I dont receive analytics data any more. I think it is related to this exception that can be observed when manually installing `SQLitePCLRaw.bundle_green v2.0.2`

```
2019-11-13 12:58:51.591 [AppCenter] ERROR: An error occurred while initializing storage
Microsoft.AppCenter.Storage.StorageException: The storage operation failed ---> SQLite.SQLiteException: Could not open database file: Microsoft.AppCenter.Storage (CannotOpen)
   at SQLite.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
   at SQLite.SQLiteConnectionWithLock..ctor(SQLiteConnectionString connectionString, SQLiteOpenFlags openFlags)
   at SQLite.SQLiteConnectionPool.Entry..ctor(SQLiteConnectionString connectionString, SQLiteOpenFlags openFlags)
   at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString connectionString, SQLiteOpenFlags openFlags)
   at SQLite.SQLiteAsyncConnection.<CreateTablesAsync>c__AnonStorey0.<>m__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AppCenter.Storage.StorageAdapter.CreateTableAsync[T]()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Storage.StorageAdapter.CreateTableAsync[T]()
   at Microsoft.AppCenter.Storage.Storage.InitializeDatabaseAsync()
```

**Comment by dpaulino** [comment]
@ahbilal-ms any updates for a more concrete timeline? I want my app to fully support Surface Pro X customers, and this issue is a major blocker.

**Comment by jmvillagra** [comment]
@dpaulino @ahbilal-ms same thing here :S

**Comment by ahdbilal** [comment]
The team has started work on it. The work will happen in two phases where in first phase we are removing the dependency on sqlite-net-pcl and in second phase we will remove other blockages that is restricting us to support Arm 64. As pointed earlier, if indeed sqlite-net-pcl is the only hurdle, we might be able to release SDK support in early December. Otherwise we might need more days for the release. I will keep you folks updated once I get any new information.

**Comment by niels9001** [comment]
@ahdbilal Any updates since the last post? As mentioned above by e.g. @dpaulino , this is a major show stopper for supporting Surface Pro X customers with ARM64 versions of my apps.

**Comment by nowheremanmail** [comment]
I don't know why they didn't publish source as opensource, we could fixed ourself

**Comment by ahdbilal** [comment]
This is under active development and expected to release soon (early January if everything goes as per the plan). The team has removed dependency on sqlite-net-pcl but there are other libraries that needs to be changed as well. Sorry that it took time but we are very near. Thanks

**Comment by jaymin93** [comment]
Yes we need support for arm 64all thing up and working  and declining that does not make any one happy

**Comment by bruzkovsky** [comment]
>I think it is related to this exception that can be observed when manually installing SQLitePCLRaw.bundle_green v2.0.2

@tipa did you come any further with this? We are having the same exception right now and will create a new issue here if you didn't already do that?

**Comment by tipa** [comment]
@bruzkovsky no I did not. I decided to wait until there is official support for ARM64 without any workaround/hacks needed

**Comment by bruzkovsky** [comment]
@tipa okay thank you. BTW I guess this will be fixed with https://github.com/microsoft/appcenter-sdk-dotnet/pull/1274

**Comment by jmvillagra** [comment]
Any updates here?

**Comment by ahdbilal** [comment]
This should be available in the February release of the SDK, which is expected to be released soon!

**Comment by dpaulino** [comment]
I'm using appcenter v2.6.4 and I'm able to successfully create a store package for my app. However, the app's ARM64 build fails store certification due to some unsupported sqlite binaries.

Does the fix coming in February include a fix for that store certification issue? I really need this fix now.

**Comment by DominicMaas** [comment]
Looks like we should now be good (I have not yet tested) - https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/3.0.0

**Comment by albertomandlate** [comment]
> Looks like we should now be good (I have not yet tested) - https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/3.0.0

Yes, I updated to the last version of App Center SDK, and it's working now.

**Comment by ahdbilal** [comment]
Thanks to all for your feedback! Since the work is now complete, I am closing this issue. Feel free to reopen it or create a new one if you are running into issues with  ARM64.
