### ISSUE TITLE
Modify default build device

### ISSUE THREAD

**Issue by DrBeak1** [microsoft/appcenter#426]
**Describe the solution you'd like**
Currently for iOS (and possibly Android as well) there is a static default device used for all build process which is not modifiable. It would be nice to be able to change this in the build configuration. For example, for iOS, on every build process it uses an iPhone 6. Which will fail certain tests if newer device specific capabilities are being tested.

**Describe alternatives you've considered**
Finding a new platform for CI/CD

**Additional context**
NA

**Comment by amchew** [comment]
Thanks @DrBeak1 for the request! @nrajpurkar would you mind taking a look?

**Comment by DrBeak1** [comment]
@amchew Thanks for having a look at this. Another individual filed a request for this. When I created this ticket I hadn't run into a problem **yet** - but now my team has. See here: https://github.com/microsoft/appcenter/issues/881
