### ISSUE TITLE
'Organization' screen incorrectly shows no organizations

### ISSUE THREAD

**Issue by mickbyrne** [microsoft/appcenter#429]
**What App Center service does this affect?**

The 'Settings' section within the 'AppCenter' website.

**Describe the bug**

Viewing the 'Organizations' screen within the AppCenter website shows that my account is not a member of any organizations. This is incorrect, as I'm a member of multiple organizations.

**To Reproduce**

1. Sign in to the AppCenter website
2. Click on the account avatar in the top right, then 'Account Settings'
3. Click on 'Organizations' in the settings menu

A message on this screens says:

> Nothing to see here.<br />It looks like you're not a member of any organizations yet.

This is incorrect, my account is a member of multiple organisations.

**Expected behavior**

The organisations I'm part of should be listed, indicating my role in each organisation.

**Desktop (please complete the following information):**

 - OS: MacOS
 - Browser: Chrome
 - Version: (latest as at 16 May 2019)

**Comment by blparr** [comment]
Thanks a lot for reporting this issue - we will take a look as soon as possible.
