### ISSUE TITLE
Crash Log Support for HoloLens

### ISSUE THREAD

**Issue by thegoldenmule** [microsoft/appcenter#43]
**Describe the solution you'd like**
Much like HockeyApp supported crash logging for iOS and Android projects (including crash log capture, aggregation, symbolication, etc), we are in desperate need of crash logging for HoloLens.

**Describe alternatives you've considered**
We have tried a couple things:

* MS Store crash logging - The app store can capture crash logs. However, in our scenario we use Intune to manage deploying a line of business app to specific devices in Kiosk mode. These builds cannot go on the store. There is also a way to deploy from the app store to specific private segments-- but this has little support and does not seem to be compatible with Intune. Also, the MS Store does not have graph api endpoints so we cannot automate anything.
* CoreApplication - There's an API that can catch some unhandled errors-- unfortunately it does not catch them all. This is also not a complete solution.

**Additional context**
Our HoloLens application is used by the public, not by trained users. We have over 6000 visitors per month at a single location (and we are expanding to more). This is not a typical use case for HoloLens but it's proving to be a very engaging one. In order to support more locations, which may be on different versions of the application, different Intune accounts, etc we need to be able to scale the HoloLens software. Crash-logging is a desperate need in this case.

**Comment by winnieli1208** [comment]
Hi @thegoldenmule,

This is Winnie from the App Center PM team. Are you using UWP or Unity for your HoloLens app? We have some [known limitations](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp) for Windows, namely, your app needs to be distributed through the Windows store in order for us to detect any crashes. We understand this isn't a great experience and are committed to improving this experience in the upcoming months.

However, if you're using Unity, you can track [handled exceptions](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/unity#handled-exceptions-in-unity) in your apps which should circumvent this limitation.

**Comment by thegoldenmule** [comment]
Thanks for the reply @winnieli1208. Yes, we are using UWP for HoloLens dev. As stated, the Windows store is not a good option for our use case.

**Comment by thegoldenmule** [comment]
Sorry, accidentally closed.

In addition, handled exceptions are fine, but there are classes of exceptions that cannot be caught, including memory exceptions. As stated in the original ticket, even using CoreApplication unhandled exceptions, we are not seeing them all.

**Comment by winnieli1208** [comment]
@thegoldenmule thanks for the additional context! The Windows store requirement is definitely a major blocked for many customers and we're committed to changing this in the upcoming months. I don't currently have an ETA but I expect our team to start working on Windows sometime around March. You can check out our [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) and [iteration plan](https://github.com/Microsoft/appcenter/issues/1) to see what our team is working on. 

I'll also update this thread once I have a more specific timeline. Thanks for your patience!

**Comment by winnieli1208** [comment]
Update: the improvements for UWP will come later this year, ideally around the end of summer. We plan to start work on WinForms and WPF first.
