### ISSUE TITLE
Appcenter's init tutorial shows incomplete/deprecated configuration commands

### ISSUE THREAD

**Issue by dkocich** [microsoft/appcenter#431]
**Describe the solution you'd like**

- show command for installation using yarn together with `npm` (slightly different command; using different app lock)
e.g. `yarn add appcenter appcenter-analytics appcenter-crashes --exact` 

- Show command for direct linking using previously installed package names?

**Additional context**

This screen shows to me when I init new react native project through the https://appcenter.ms .

![image](https://user-images.githubusercontent.com/6165660/57848898-4377a080-77da-11e9-944d-a7b483a53c89.png)
 

When I follow the guide, I see warning in my console... 

```
david@HPdk:~/it/xyz-app$ react-native link
warn Running `react-native link` without package name is deprecated and will be removed in next release. If you use this command to link your project assets, please let us know about your use case here: https://goo.gl/RKTeoc
```

It is not obvious to me if there are any restrictions for using `npm`/`yarn` and if direct package linking behaves differently than general `react-link`...

**Comment by guperrot** [comment]
Hi,

For now you can still call `react-native link`.
In a future version of react-native the command will simply have to split by module:

```
react-native link appcenter
react-native link appcenter-analytics
react-native link appcenter-crashes
react-native link appcenter-push
```
