### ISSUE TITLE
Add error handling support to android sdk

### ISSUE THREAD

**Issue by joshspoors32** [microsoft/appcenter#432]
Support for Handled Errors need to be added to the Android SDK, we used hockeyapp in Xamarin now transferring to Kotlin and native android we cannot report full exceptions and stack traces to app centre.

Tried to do it via normal analytics but with the character limit on the property values we get truncated data. This is extremely important to our business and application.

**Comment by winnieli1208** [comment]
Unfortunately, this isn't on our short term roadmap but bringing handled errors to other platforms outside of Xamarin and Unity is definitely on our radar. I'll post here with any updates. Thanks!

**Comment by winnieli1** [comment]
Hi all! We just released this with the Android SDK Version 2.5.0.
You can find the docs here: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#handled-errors.
