### ISSUE TITLE
Add AppCenter crash reporting to a C++ app for the Windows Store

### ISSUE THREAD

**Issue by sseyod** [microsoft/appcenter#436]
**Describe the solution you'd like**
Can you please clarify how I can add AppCenter crash reporting to a C++ app for the Windows Store. Thanks!

**Describe alternatives you've considered**
I can't find any alternatives.

**Additional context**
This should be self-explanatory!

**Comment by winnieli1208** [comment]
@sseyod thanks for the request! The App Center SDK doesn't work with C++ apps at this time. However, if your app is in the Windows store, you should have crash reports in [Partner Center](https://partner.microsoft.com/dashboard).

**Comment by sseyod** [comment]
Hi Winnie,

There are no crash reports in Partner Center - just failures reported as "Unknown".

Pete

**Comment by sseyod** [comment]
Hi again @winnieli1208 - is there any further update on this? Thanks, Pete

**Comment by winnieli1208** [comment]
Apologies for the delay. I've reached out to the Partner Center team to learn more. I'll post updates as soon as I have them. Thanks!

**Comment by sseyod** [comment]
Thanks! There is at least one third party company that offers crash reporting for C++ apps for Windows, so it can certainly be done technically. Clearly, it'd make sense if I can do this through App Center, just like I can do for my iOS, macOS and Android/NDK apps! Pete

**Comment by winnieli1208** [comment]
@sseyod can you start a chat in the blue chat bubble on the bottom left hand side of App Center and provide us your app's seller ID from Partner Center? The team would like this information to help troubleshoot. Feel free to link this GitHub thread and our support team will be able to triage the message appropriately. Thanks!

**Comment by sseyod** [comment]
Hi

Pete is on holiday now and will respond when he gets back.

Kind regards

Tim

**Comment by sseyod** [comment]
Hi @winnieli1208 - I'm now back from holiday, and have created that chat on AppCenter as requested! Thanks for your help, Pete

**Comment by mayenjoy** [comment]
Is there any progress? Our whole company is waiting for this matter.

**Comment by sseyod** [comment]
Hi @winnie!

Is there any more news on this?

Thanks, Pete

**Comment by winnie** [comment]
Hey @sseyod - cross posting my response from #374.

_Unfortunately, no updates on this one. We did add a upload custom crashes API so you can now upload crashes from a Windows C++ app to view and manage those reports in App Center. We also support symbolicating those crashes (docs here).

We don't have any immediate plans to build an crashes SDK for Windows C++ apps but I hope this helps a little. I'll update this thread if anything changes. Thanks!_

This thread reminded me that we were chatting with the Partner Center team last year. Were you able to work with them to get your C++ crashes in Partner Center?

**Comment by sseyod** [comment]
Hi @winnie, thanks for remembering. Alas, no. This is one of the problems - if there were a way to access and interpret log files from the Windows Store, we could work around the lack of a crash SDK from Microsoft. But without at least of these approaches working/available, we're completely blind as to what might be the cause of crashes on user machines. Which isn't a good position to be in :)

Best wishes, Pete

**Comment by sseyod** [comment]
Hi folks - any update yet?! Regards, Pete

**Comment by nmr8acme** [comment]
absolutely despicable
