### ISSUE TITLE
build configuration: change control - would settle for bld cfg import/export to json/xml/etc.

### ISSUE THREAD

**Issue by abdeweese** [microsoft/appcenter#437]
Purpose:
Build configuration change control (e.g. in a git repo)

Scope:
Applies to all App Center builds on a per branch basis

Proposed Solution:
Support import/export to json/xml/whatever.  Anything I can store in a txt file and stick in a git repo would do.

Alternatives:
Alt 1) As of this writing the bld config is only editable through a GUI which is not an acceptable solution from a change control standpoint.
Alt 2) A bld config API would solve the problem but be a pain to manage because we would have to write a script to read the bld cfg via that API and then call that script as a pre build step (or similar).  Build config import/export via json is the ideal solution.

**Comment by marstall** [comment]
this would help us a lot on our team. We currently have 8 build configurations in regular use:

- 2 apps x 2 platforms (ios/android) x 2 modes (dev/staging)

that will only increase as you include feature branch builds, app store branch builds, etc.

I don't think that's too atypical. 

Bonus: still be able to use the GUI to do per-branch spot modifications for the checked-in build config.

**Comment by RWOverdijk** [comment]
yaml is used quite a bit for this stuff now too.
