### ISSUE TITLE
HoloLens Device Lab

### ISSUE THREAD

**Issue by thegoldenmule** [microsoft/appcenter#44]
**Describe the solution you'd like**
iOS and Android device labs with CI/CD make it trivial to automate testing across device families. For HoloLens, no such tools exist. The dream would be able to test builds against different permutations of HoloLens configurations:

* Windows Holographic version (it's currently impossible to downgrade a HoloLens, and pricey to purchase enough to have one at each recent version)
* Commercial Suite (we've found issues that are specific to the commercial suite edition of windows holographic).
* Kiosk Mode options (we have identified and reported numerous confirmed issues that are specific to single app kiosk mode).

With the next HoloLens just around the corner, it's going to multiply the increasingly numerous HoloLens configurations.

**Describe alternatives you've considered**
We have tried a couple of things, but they simply don't scale. It's possible to keep a HoloLens at a specific Windows version by simply not upgrading. But you quickly run out of devices. It's also possible to install and uninstall commercial suite-- but it takes a very long time. Switching devices in and out of kiosk mode also takes a lot of time (there's also an open bug on this not process being broken to begin with).

**Additional context**
As we try to support more configurations, the task of testing the configurations is growing too fast. One of our deployments of 75 HoloLenses is constantly struggling to support multiple configurations at once-- the reason being that getting all 75 configured exactly the same at the same time is impossible, even when automating with Intune.

**Comment by jwhiteDev** [comment]
Hi @thegoldenmule 

HoloLens support is an area we have definitely seen growing interest in, especially since shipping our Unity SDK. It would be great to explore further and learn more about your needs and setup. Could you reach out to me directly via email?

**Comment by thegoldenmule** [comment]
Sure, I've sent you an email.
