### ISSUE TITLE
Is deployment to Windows Store Supported through AppCenter?

### ISSUE THREAD

**Issue by dbnex14** [microsoft/appcenter#440]
### **Description**

Is deployment to Windows Store supported through AppCenter?

### **Repro Steps**

NA

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Deploying of Xamarin.Forms on all 3 platforms (Android, iOS and UWP) to their app stores, is it supported?

2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.0.

2. Which SDK version are you using?
    - NA
4. Which OS version did you experience the issue on?
    - NA
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - NA
6. What third party libraries are you using? 
    - NA
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
NA

**Comment by dinobu** [comment]
anyone???

**Comment by dbnex14** [comment]
? anyone alive here?

**Comment by dimazaid** [comment]
Thank you for opening this feature request. 

To answer your question, no we don’t currently support distribution to Windows Store.
 Just like any feature requests, we will keep an eye on the votes from customers and prioritize it against our backlog in the future. Thanks again for submitting it. 

Sorry for the delay 🙏🏻

**Comment by mnxamdev** [comment]
Any word on support for this? We're just transitioning our UWP app to use the Xamarin.Forms code already used by iOS and Android and we will be ready for a Store release soon of our Xamarin.Forms UWP app. App Center is great and we love the ability to distribute to the Google Play Store and Apple App Store from App Center and would be convenient to distribute this from App Center. If this is not possible or not on the road map, please provide guidance on how to do this with an existing build/release that was done in App Center (e.g. re-signing etc.). What we want to avoid is having tested on builds from App Center then say use a completely different build server (local dev machine) to run builds to be released to the Windows Store. Thanks!
