### ISSUE TITLE
Add option to allow user on/off screenshot taking on demand

### ISSUE THREAD

**Issue by khoivonvg** [microsoft/appcenter#443]
**Describe the solution you'd like**
When I use XCTContext.runActivity, azure automatically takes a screenshot at the end of activity although I didn't call any taking screenshot method.
I would like to have an option to disable this feature on running time, and screenshot is only taken and sent to azure when I call taking screenshot.

**Comment by Oddj0b** [comment]
@khovionvg this is interesting, and I'm surprised it hasn't received more interest. If more users are voting for this issue, it's possible it will be started.
