### ISSUE TITLE
ios - set extensions bundle id based on its provisioning profile

### ISSUE THREAD

**Issue by simonetodisco** [microsoft/appcenter#444]
**Describe the solution you'd like**
Main app bundle id is set at build runtime by using the one specified into provisioning profile. As confirmed by support, extensions bundle id is taken from source repository and can't be changed at build runtime. Would be very useful if the behaviour of extensions bundle id is like the main app's one.

**Comment by nrajpurkar** [comment]
@simonetodisco Thanks for this feature request! We'll keep this open as a possible enhancement for extensions.

**Comment by akempe** [comment]
@nilofer @simonetodisco any idea where the extension's bundleid is grabbed from? i have a case where we specify the bundleid using a target/scheme combination and the build scripts don't seem to be respecting this. instead they appear to be using the value from the first buildsettings node they find in the xcode config

**Comment by chandlerroth** [comment]
I'm seeing the same thing, @akempe -- frustrating!!

**Comment by kesavan49** [comment]
do we have any solution for this ?
