### ISSUE TITLE
Add back the timestamp for builds created  from Azure pipelines

### ISSUE THREAD

**Issue by DwightHyde** [microsoft/appcenter#446]
We are not using AppCenter builds.  We use Azure.  In the past with HockeyApp we could see the timestamp and now we can't with AppCenter.  When going to https://appcenter.ms/apps?iOS is see my DEV app. When I view it to install it has a Version,Date, and Size but no Timestamp. How do we get Timestamp to appear on that screen. Even though they get an email it's sometimes easier to go directly there and it's helpful to identify to them by the specific time.

**Comment by botatoes** [comment]
Thanks for pointing this out. I will make sure to include this in our installation revamp effort.

**Comment by DwightHyde** [comment]
Awesome!
