### ISSUE TITLE
Set client_CountryOrRegion based on client_IP addr 

### ISSUE THREAD

**Issue by jmoore4xrx** [microsoft/appcenter#447]
Our telemetry is coming from MacOS, so CarrierCountry is not getting set (as expected). 

Would like for the App Center to do an IP lookup prior to stripping it (set to 0.0.0.0) & set the client_CountryOrRegion accordingly.     Similar to what Application Insights does: https://github.com/Microsoft/ApplicationInsights-Home/issues/116.   Would also like client_StateOrProvence & client_City set similarly.

**Comment by hamswan** [comment]
Thanks @jmoore4xrx for the suggestion, I have added this to the feature request.

**Comment by VaibhavMisraEZ** [comment]
I would love this feature as well. My app is targeted for both iPhone and iPad most of them don't use SIM. Hence, most of my events have no location (coutry, region, state) bound to them.

I was hoping somehow get IP using client_IP and map them to some region using KQL. However, for all my cutom events client_IP is 0.0.0.0. I saw similar issue logged [here] (https://github.com/microsoft/appcenter/issues/2027) for same problem.

 Also, if we can get an API to set country/region from code, that would be awesome as well.
