### ISSUE TITLE
Extend AAD groups support to Org level

### ISSUE THREAD

**Issue by dexter31** [microsoft/appcenter#448]
AAD Groups are currently supported at distribution groups within individual apps. Consider extending this to the distribution groups at the org level.

**Comment by blparr** [comment]
Hello! Glad you ask that. We are currently working on adding AAD to organizations and then we'll he adding AAD to distribution groups in Orgs. Stay tuned!

**Comment by flatherskevin** [comment]
Noticed it has been a few months since this issue was last updated. Any news on this feature?

**Comment by GinaK1** [comment]
integration with AAD is really limiting if you have to invite users via email and only have the integration as a DG.  Seems like this could be an easy integration.
