### ISSUE TITLE
When inviting someone to a team, there is no indicator that the invitation was successfully sent

### ISSUE THREAD

**Issue by srungta** [microsoft/appcenter#449]
**Describe the solution you'd like**
The page should give a message saying "Your invitation was sent successfully"

**Describe alternatives you've considered**

**Additional context**
When adding someone, after pressing enter, a loading bar appears briefly. But there is no message that the invitation was sent. The only way to confirm is to try to send the invitation again, in which case, the page shows an error message shown below.
<img width="1105" alt="Screenshot 2019-05-21 at 4 22 58 PM" src="https://user-images.githubusercontent.com/31416811/58090568-1ade1500-7be5-11e9-80aa-d2e80446b301.png">

**Comment by botatoes** [comment]
Hi, thanks for pointing this out. It is mostly by design that we only show error under the textbox. Can you tell me which page you are on? There should be a way for you to confirm whether your invitation was sent.

**Comment by srungta** [comment]
@botatoes This is the page to add collaborators to my team.
