### ISSUE TITLE
Android versionCode does not auto increment

### ISSUE THREAD

**Issue by iamcam** [microsoft/appcenter#45]
**What App Center service does this affect?**
Android release builds

**Describe the bug**
AppCenter fails to auto increment the `versionCode`

**To Reproduce**
1. Open the branch/build configuration
2. Toggle ON Automatically increment version code
3. select the timestamp option
4. Save & Build
5. Build again

**Expected behavior**
I expect each successive build to update the version code, however the number from the gradle file is used no matter what the version code build setting is

**Screenshots**
![screen shot 2019-02-08 at 8 20 14 pm](https://user-images.githubusercontent.com/51949/52516393-25990f00-2bdf-11e9-8a2d-a688a014645e.jpg)
![screen shot 2019-02-08 at 8 21 03 pm](https://user-images.githubusercontent.com/51949/52516394-2631a580-2bdf-11e9-8dba-670c309a047e.jpg)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser n/a
 - Version 28.0.3

**Additional context**
I've tried builds with the toggle on and off, using the incremented build number vs timestamp... everything. I just won't come unstuck.

**Comment by patniko** [comment]
Hi @iamcam, do you mind reaching out through the chat feature in the App Center web portal to get your configuration looked at by someone from our team? It's difficult for us to triage issues with peoples build configurations here, but we would be happy to give you some 1 on 1 support there.

**Comment by iamcam** [comment]
@patniko Sure thing, thanks.

**Comment by sm1th** [comment]
I received 1 on 1 support in App Center for this today. Auto increment for versionCode doesn't work with Android gradle plugin version 3.3.0 or higher. Downgrade to 3.2.1 and you should be good.

**Comment by nrajpurkar** [comment]
@iamcam still hitting this issue or was support able to help you out?

**Comment by patniko** [comment]
Closing this for now as there hasn't been follow up from the original reporter.

**Comment by ramasamyprabakaran** [comment]
The solution is just a workaround, so what is the status of the issue? is that fixed? @patniko

**Comment by fenwalt** [comment]
@patniko, what is the status of this issue?

**Comment by Ryanauger95** [comment]
@ramasamyprabakaran @patniko have either of you found a solution?

**Comment by tronin** [comment]
still doesn't work

**Comment by zoontek** [comment]
This is still happening. Please reopen the issue.

**Comment by zoontek** [comment]
I have a solution if you use timestamp based versionCode:

**appcenter-post-clone.sh**
```sh
#!/usr/bin/env bash -e

cd $APPCENTER_SOURCE_DIRECTORY

if [[ -z "$APPCENTER_XCODE_PROJECT" ]]; then
  node ./appcenter-post-clone.android.js
fi
```

**appcenter-post-clone.android.js**:
```js
const path = require("path");
const fs = require("fs");

const buildFilePath = path.join(__dirname, "android", "app", "build.gradle");
const buildFile = fs.readFileSync(buildFilePath, { encoding: "utf8" });
const versionCodeRegExp = /versionCode (?<versionCode>\d+)/g;
const buildFileMatch = versionCodeRegExp.exec(buildFile);

if (!buildFileMatch) {
  console.error("Could not increment versionCode");
  process.exit(1);
}

const nextVersionCode = Math.floor(Date.now() / 1000).toFixed(0);

fs.writeFileSync(
  buildFilePath,
  buildFile.replace(versionCodeRegExp, `versionCode ${nextVersionCode}`),
  { encoding: "utf8" },
);
```

It should also work with pre-build script, but I didn't tested it, and I'm not sure the difference matter.
This is still a workaround, I hope this will be fixed 🙂

**Comment by saamerm** [comment]
Not a solution, but I figured out an alternative to Automate Build numbering & App versioning for Android WITHOUT shell scripting while using Microsoft AppCenter CI/CD pipelines!
You can create environment variables and then use them in the build.gradle file like this:
```
versionCode System.getenv("VERSION_CODE") ? System.getenv("VERSION_CODE").toInteger() : 201
versionName System.getenv("VERSION_NAME") ? System.getenv("VERSION_NAME").toString() : "1.2.1"
```
[More details in this article](https://dev.to/saamerm/android-version-code-name-from-appcenter-environment-variables-2a3a)
