### ISSUE TITLE
iOS Xamarin.Forms App success in AppCenter but fail on device

### ISSUE THREAD

**Issue by MPusch** [microsoft/appcenter#450]
I have a Xamarin.Forms app that Testes well on AppCenter. I can see the test report image with the login screen.

When I download the App to my IPhone, it installs, but it stays grayed out. It is not listed in Settings—> Apps.

Provisioning is done with an AdHoc Distribution Profile, the IMEI of the device is added to the profile.

**Expected behavior**
Either the App should fail during testing or it should work on the device or it should at least work enough to send a crash report to AppCenter.

**Smartphone:**
 - Device: IPhone X
 - OS: 12.3 (failed also on previous version)

**Comment by patniko** [comment]
Hi @MPusch, can you download the release manually from the developer portal release details page on your computer and try to sideload it? If it can't be sideloaded than there is more than likely something wrong with your provisioning profile.

**Comment by botatoes** [comment]
If you open an intercom issue on appcenter.ms, one of our customer support or engineers can help you with this. Closing this for now.
