### ISSUE TITLE
High availability testing for App Center 

### ISSUE THREAD

**Issue by swathisuvarna1** [microsoft/appcenter#452]
**Describe the solution you'd like**
Some way to disable app center without loosing any data so that the mobile apps we are building using App Center can be tested for availability and the app's response or error can be captured.

**Describe alternatives you've considered**
The App Center support team suggested that I could disable the firewall settings for App Center or remove all the App Center url's which were white listed by our organization.

**Additional context**
Our project would like to perform High availability testing on mobile apps built using App Center to test platforms like Azure DevOps and App Center so that the app's response to a system failure can be captured. The intent is to break the platforms temporarily or create a failure like situation.

**Comment by Oddj0b** [comment]
I'm not sure I understand what you are requesting. If I understand it correctly, would it not be better to mock your backend with a 500 response?

**Comment by swathisuvarna1** [comment]
What happens if App Center goes down? how will I know? What impact does it have on my apps and how soon can App center be back up and running?

**Comment by swathisuvarna1** [comment]
We are doing high availability and DR readiness testing as we are getting closer to release of our mobile applications via App center.

**Comment by Oddj0b** [comment]
I'm not sure I understand, are you trying to test App Center or your mobile app?
