### ISSUE TITLE
Support Appium in a language agnostic way

### ISSUE THREAD

**Issue by jhandel** [microsoft/appcenter#453]
**Describe the solution you'd like**
Allow any Appium driver/platform to connect to an Appium service based on capabilities requested and execute their tests
**Describe alternatives you've considered**
The ability to upload a self contained testing package (Javascript, Ruby, Python, C#) with an execution script that uses environment variables (or another method) to request an appium instance and connect the tests to it... 

This scenario may include the need to run package management or clear specs on what we are building for could be shared.

Perhaps borrowing from the YAML pipeline tech in Azure DevOps...

(Perhaps even a Appium server task in Azure Pipelines that we can orchestrate running testing againt ourselves so AppCenter is not having to build out systems that are to complex)

**Additional context**

**Comment by fabiodamasceno** [comment]
+1 . React Native users are not able to use a decent ui test framework at this time because there isn't support to Detox, Appium nor any functional high-level UI test frameworks (unless to be XCUITest, that is native and not the case). This make unfeasible AppCenter to React Native projects to make continuous delivery.  So, if we've got Appium support, you guys will not just enable UI Tests for React Native, but any mobile application development technology, because Appium is platform agnostic.

**Comment by Oddj0b** [comment]
I'm the program manager responsible for App Center Test and I'm working on a new idea which will support more frameworks in Test, allow unit testing, and browser testing. I would like to talk to you about it and understand your needs better.

Below is a link where you can sign-up for a 30-minute call with me. The agenda will be about the value of testing for you and your organization, and my new idea to allow more frameworks and testing styles in App Center Test.

Link to choose https://calendly.com/vigimm/appcenter-test

**Comment by chrisumitratech** [comment]
@Oddj0b - I need to choose a long-term framework for UI Automation for Mobile and would ideally like to choose Appium in C# as this covers more products other than AppCenter.

Can you indicate when (Year and Quarter will suffice), you think this support might be added to AppCenter Test?

**Comment by Oddj0b** [comment]
@chrisumitratech It's unfortunately too early to say when we can roll it out. In your case, I would choose Xamarin.UITest and integrate the calabash server into your app, Xamarin.UITest have the benefit of being both cross-platform and C#.

**Comment by fabiodamasceno** [comment]
Sorry for being late here, can we make this call still?

**Comment by craig95** [comment]
@Oddj0b Do you have any update on this? We would like to use Appium with Webdriver.io. We are using React Native so it would be nice if we could also write our tests in JS.

**Comment by Oddj0b** [comment]
@fabiodamasceno @craig95 Sorry, I still don't have an update.

**Comment by GwnElviin** [comment]
I also want to apply ui test in App Center with Appium but I cannot find a good tutorial for react-native projects.
I find the docs kinda confusing.
does anyone know of a good tutorial that I can follow.

**Comment by joelneubert** [comment]
This feature would be great! It would also change our decision to use a different service for testing. The available options for app center would force us to diverge from the approach of our developers.

**Comment by fabiodamasceno** [comment]
@joelneubert 
 A lot of my custumers tend to choose browserstack instead app center for testing, this is a killer feature.

@Oddj0b
There's something community can contribute to make this happen? Would be nice if we could know what are challenges, or at least, know if this feature have low priority. With no signal of milestone makes our app center defense as ms partner hard. :(

**Comment by jcummings2** [comment]
Adding a comment to remove the stale label.

**Comment by pm90pl** [comment]
Any progress on that one? The current Appium support is just not good enough. Having .NET as a technology of choice, not being able to write tests in the same tech stack is a big inconvenience.

**Comment by IlyaBausovAkvelon** [comment]
Hi all!
Currently we don't planning to add support for Appium for different platform.

**Comment by pm90pl** [comment]
So unsafe of AppCenter is pointless
