### ISSUE TITLE
Allow grouping of crash reports by call stack *across* build numbers

### ISSUE THREAD

**Issue by jaybaxter-ms** [microsoft/appcenter#454]
![crashes](https://user-images.githubusercontent.com/49453180/58129110-e1e67600-7bcd-11e9-8522-853e4eab3860.PNG)
**Describe the solution you'd like**
We (Minecraft Genoa) would like to be able to group crashes reports that share a call stack *even if they have different versions*.

**Describe alternatives you've considered**
We have been closing crashes against old builds and adding a comment to matching crash reports in new builds with a count.  However, we are bad about this, and forget or drop numbers.  Consequently, our numbers are inaccurate and the bugs look less significant to our development teams than they ought.

**Additional context**
Please see screenshot, which shows a randomly chosen example of the same crash on three different builds.

Thanks for your help!

**Comment by winnieli1208** [comment]
@jaybaxter-ms thanks for the feedback! This is a great point and I've heard quite a few customers wanting to group their crash groups across versions to also help diagnose when a crash type first occurred and was fixed. At this time, we don't have any immediate plans to address this due to other priorities but I'll update here if I have any more details. 

Thanks!

**Comment by jaybaxter-ms** [comment]
@winnieli1208 are there any creative workarounds you could recommend to us in the meantime?  This has become a significant impact to measuring our product's health.  For example: are there APIs we could query to create our own dashboard?  Is there another way of reporting these crashes so that they would collate under the current system?  Can you help us think of a creative workaround to this challenge?

**Comment by winnieli1208** [comment]
Hmm this isn't the exact scenario you're looking for but I would recommend trying our search feature in our [UI](https://docs.microsoft.com/en-us/appcenter/diagnostics/search) or via [API](https://openapi.appcenter.ms/#/errors/Errors_ErrorSearch) to query for crashes across different versions. For example, you can search by method, class, and reason to get a list of different crash groups across multiple versions all with similar stack traces. 

We also have an [API](https://openapi.appcenter.ms/#/errors/Errors_GroupList) that returns a list of all crash groups. You might be able to take the output of this API and see where exception type, message, class, method, etc. are the same and sum the counts for all of them. 

I hope that helps a bit! Happy to hop on a call to brainstorm more ideas. In the meantime, I'll also update this thread if I think of anything else.

**Comment by ndahlquist** [comment]
We (Leia, Inc) are in the process of transitioning from HockeyApp to App Center, and would also love to see support for this feature. Since we use App Center for regular (nightly) builds, our App Center diagnostics dashboard is quite difficult to manage without this. Thank you!

**Comment by jaybaxter-ms** [comment]
@winnie Disappointed to see this request closed.  The Mojang team is still slowed down by the absence of the ability to see aggregated counts by call stack.  We would still like to see this simple sorting UI added.  Please re-open the issue.
