### ISSUE TITLE
The Events page fails to load when an AdBlocker is active

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/appcenter#455]
**What App Center service does this affect?**
The issue is with the [https://appcenter.ms/users/\<USER\>/apps/\<APP\>/analytics/events](https://appcenter.ms/) page.

**Describe the bug**
The page just fails to load _when an AdBlocker is active_: I can see the blue progress bar at the top getting stuck at around 90%, and I can only see the placeholders for the items to load.
If I open the F12 dev console, I can see a bunch of errors: 

![image](https://user-images.githubusercontent.com/10199417/58168820-76fd7380-7c8f-11e9-9343-a194efc6f676.png)

This happens both in Chrome and Chromium Edge.

> **NOTE:** turns out this is caused by the AdBlocker. Now, I know this isn't 100% an issue with AppCenter per se, but since many people use an AdBlocker you might want to look into this to figure out what rule is causing the connection to be blocked. Or, at least show a popup asking the user to disable the AdBlock. Otherwise many other users might find themselves in the same situation, without knowing what's causing the page to fail to load.

**To Reproduce**
1. Just go to the [https://appcenter.ms/users/\<USER\>/apps/\<APP\>/analytics/events](https://appcenter.ms/) page.

**Expected behavior**
The page should correctly load and display the recorded events.

**Screenshots**

![image](https://user-images.githubusercontent.com/10199417/58168950-cd6ab200-7c8f-11e9-9f0e-3af083f4b0ba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 build 18362.116
 - Browser: both Chrome and Chromium Edge (dev)
 - Version: latest for both

**Additional context**
The events used to work for for me up to a couple weeks ago or so, then the page just stopped working for me. As mentioned, the other pages work fine.
I know that the page is working fine for other users, so I'm not sure why it's just failing for me.

**Comment by hamswan** [comment]
Thanks @Sergio0694 for bringing this to our attention. Our team will take a look at this.

**Comment by Sergio0694** [comment]
Hi @hamswan - thank you for the quick reply, glad I could help! 😊
Also, just to clarify, I can confirm that disabling the AdBlocker on the site completely solves the issue, everything works just fine now. Also, to be precise, I'm using uBlock origin (not AdBlock Plus).

**Comment by hamswan** [comment]
Thanks for the details, we are looking into this

**Comment by hamswan** [comment]
@Sergio0694 We have added this in our feature backlog, we don't have an ETA yet, you can track this through the GitHub issue

**Comment by taspeotis** [comment]
The feedback widget at the bottom right of the page also appears blocked by (at least) uBlock Origin.
