### ISSUE TITLE
HockeyApp crashes are missing in AppCenter

### ISSUE THREAD

**Issue by krebbl** [microsoft/appcenter#456]
**What App Center service does this affect?**
HockeyApp / AppCenter synchronization

**Describe the bug**
While transitioning from HockeyApp to AppCenter we noticed that some errors are missing in AppCenter. So it seems like there is a bug in the HockeyApp to AppCenter synchronization.
For example we can't find the corresponding error for HockeyApp crash reason 268708738 in app 25474. 

**Expected behavior**
All crashes should be synced to AppCenter.

**Comment by derpixeldan** [comment]
@krebbl thanks for reporting, can you please reach out to us via support additionally so we can better investigate the issue?

**Comment by patniko** [comment]
Closing this one as it requires some 1:1 triaging through our in chat support option.

**Comment by lumaxis** [comment]
@krebbl Do you know if the symbols you uploaded should include the symbols from the HockeySDK framework?

**Comment by krebbl** [comment]
@lumaxis I think they are not included because also in HockeyApp the method calls for the SDK are not resolved in the logs.

**Comment by allen-zeng** [comment]
I'm looking into the transition as well, and the App Centre dashboard reports different numbers of crashes every day compared to HockeyApp... some days the differences are bigger than others. Do we know why that might be?

**Comment by lumaxis** [comment]
@allen-zeng Would you mind also opening a support request with your specific app details so we can take a look at your actual data? Thanks!

**Comment by lumaxis** [comment]
Closing this since it's been a while and there have been no recent reports of missing crashes 🙏🏼
