### ISSUE TITLE
Incorrect .apk path during Android build

### ISSUE THREAD

**Issue by Watersdr** [microsoft/appcenter#457]
**What App Center service does this affect?**
AppCenter React Native Android Build

**Describe the bug**
Trying to build my RN android but I can see that it has an incorrect path to my .apk files and so the build fails. I can't tell if this is something wrong with my config or in my own files or if this is an issue in appcenter itself.

**Screenshots**
You can see in the screenshots below that it's looking in the folder `android/app/app/build`. That extra `/app` is the issue but I can't pinpoint where it is.
![image](https://user-images.githubusercontent.com/6473620/58179394-1d3c7f80-7c76-11e9-9961-53c20677fa6c.png)

And you can see here that it happens on both the Post Process and the Code Signing task:
![image](https://user-images.githubusercontent.com/6473620/58179498-4f4de180-7c76-11e9-9cdd-32dca8cac1e1.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by DennisPan** [comment]
@Watersdr Could you reach out to support (the blue bubble at bottom right of the portal) for this? We likely will need to collect information like your app etc. to dig deeper

**Comment by patniko** [comment]
Closing this for now as it requires 1:1 support through our in product help to diagnose.
