### ISSUE TITLE
AppCenter cannot deobfuscate Android R8 code

### ISSUE THREAD

**Issue by DeweyReed** [microsoft/appcenter#458]
**What App Center service does this affect?**
Crashes.

**Describe the bug**
With Android Studio 3.4, R8 becomes the default code shrinker. But AppCenter cannot deobfuscate R8 code with mappings.txt.

For example, the real stacktrace from logcat: `at d.a.a.a.onClick(Unknown Source:0)` which can be deobfuscated but the stacktrace that AppCenter captures is `at d.a.a.a.onClick`. Without the postfix, the stacktrace cannot be deobfuscated by AppCenter.

**To Reproduce**
1. Create a basic application using Android Studio 3.4 or higher
2. Add AppCenter Android SDK dependency
1. Throw an exception anywhere
3. Enable code shrink
4. Build the APK
1. Trigger the crash, compare stacktraces and retrace them manually.

**Expected behavior**
AppCenter should be able to deobfuscate the code after I switch from proguard to R8.

**Smartphone (please complete the following information):**
 - Device: All Android Devices
 - OS: All Android OS

**Comment by kevbry** [comment]
Dexguard is not supported either #220

**Comment by winnieli1208** [comment]
Thanks for filing an issue. App Center only supports ProGuard at this time. I've changed this to a feature request type so our team can monitor community support and better prioritize this in the future. We don't have any immediate plans to address this but we'll post here if there are any updates. Thanks!

**Comment by DeweyReed** [comment]
I don't think this is feature because AppCenter Crashes for Android won't work out of box.🤔
Something like "Use Proguard instead of R8 or the crash reports can't be deobfuscated" probably should be added to Android docs.

**Comment by easterapps** [comment]
the same with us, that's very important to us @winnieli1208 
and should be fixed as soon as possible.

**Comment by mike14u** [comment]
Shouldn't really be a feature request btw, it is already a persisting issue, we should be able to read crash logs from diagnostics in AppCenter even if the output APK is obfuscated via proguard / r8 method. The reason behind this is, AppCenter is the one building the apps, so it should contain the necessary file to map the obfuscation... Really should be fixed otherwise will consider other alternatives to AppCenter.

**Comment by DeweyReed** [comment]
It seems postfixing the stacktrace with a `()` can fix the problem for now.

1. Get stacktrace from AppCenter: `at p.a.e.a.f.b.l.k`
1. Add a `()` => `at p.a.e.a.f.b.l.k()`
1. Deobfuscate manually. Ta-da!

**Comment by poldz123** [comment]
Having the same issue here. R8 should be supported when obfuscating the crash report since it is now the default code shrinker for android.

Looking forward to this issue to be fixed.

**Comment by maksim-m** [comment]
I join this feature release. R8 is the default code shrinker and should be supported.

**Comment by msdof** [comment]
any plan for this request? @winnieli1

**Comment by winnieli1** [comment]
Hi all! Thanks for the patience. We added this to our iteration plan this month and expect to finish this in a few weeks. We'll post here with updates. Thanks!

**Comment by lukaville** [comment]
@winnieli1 do you have plans to support DexGuard mappings (#220) this month as well?

**Comment by winnieli1** [comment]
Hi all - we completed the work needed to support R8 deobfuscation. Your new crashes will be deobfuscated when you upload the right mappings file. Thanks!

**Comment by winnieli1** [comment]
(@lukaville - we might not get to it this month but we're discussing internally where this falls on our timeline. Thanks!)

**Comment by filipkowicz** [comment]
@winnieli1  do we need to reupload mappings to make it work for old releases ?

**Comment by winnieli1** [comment]
@filipkowicz - I'm double checking with the team but I believe you'll need to reupload mappings.  Also note only new crashes will be processed and deobfuscated.

**Comment by goupilapps** [comment]
I still have some issue with de-obfuscation with R8.

Our app uses a SDK that is developed by us and is uploaded into our internal maven repo.
We have two mapping files: one for the SDK and one for the app.
We merge them together by appending the content of the sdk mapping file to the app mapping file. Then we upload this to appcenter.
When a crash occurs, we expect to have the stack-trace de-obfuscated for both the app and the SDK. However, only the app part of the stack-trace is de-obfuscated, not the SDK part.

It work fine locally with the official pro-guard tool: https://support.bugfender.com/en/articles/1744985-deobfuscating-a-stacktrace but it does not work on appcenter.

**Comment by winnie** [comment]
Hey @goupilapps do you mind starting a support ticket (blue chat bubble on the bottom right) so our team can take a closer look for you? Please include your app details and a sample mappings file. 

Thanks!

**Comment by Nutriz** [comment]
Hi,

I'm still having an issue with R8, but only for the subtitle part, all the rest of the stack trace is deobfuscate :

![image](https://user-images.githubusercontent.com/7358899/89040811-a2282c00-d344-11ea-8ff8-1e4e9959e8ce.png)

**Comment by winnie** [comment]
Hey @Nutriz  - can you please open a support ticket (select the Help icon "?" by upper right corner) so our team can investigate? Thanks!

**Comment by Nutriz** [comment]
Hi, still have the issue and no answer from the support ticket (help icon)

**Comment by winnie** [comment]
Hi @Nutriz - I found your support ticket and saw that our team responded a few times. Can you please check your Junk inbox? We've seen some cases where our responses end up there. I also just responded to the thread. Hopefully that'll bump it up. 

Thanks!

**Comment by Nutriz** [comment]
I guess the mail was blocket by our main anti-spam (I have nothing under my client spam folder). 
I have searched here https://intercom.help/appcenter/ but I don't have found my ticket, can you please give me the url ?

**Comment by loymtshali** [comment]
Can someone please assist. 

Our app is obfuscated using R8. I have uploaded the mappings.txt (From the app/build folder in the pipeline drop folder). I have the correct version name and number for the build but our crashes are still obfuscated.
