### ISSUE TITLE
UWP full crash support, publish to Windows store and UI automation

### ISSUE THREAD

**Issue by dbnex14** [microsoft/appcenter#459]
### **Description**

I am interested in finding more about AppCenter support for .NETStandard 2.0 Xamarin.Forms (all 3 platforms Android, IOS, and UWP).  Is this supported?  I am bit confused because I have been finding lots of links, even MS ones that are confusing on this topic especially when it comes to Xamarin.UWP support and need clear answer.

### **Repro Steps**

Please list the steps used to reproduce your issue.

NA

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Interested only in Xamarin.Forms on all 3 platforms (Android, iOS and UWP).

2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.0.

2. Which SDK version are you using?
    - NA

4. Which OS version did you experience the issue on?
    - NA

5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - NA

6. What third party libraries are you using? 
    - NA, none for reporting

7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
NA

**Comment by dhei** [comment]
> In the meantime you can consult [Microsoft/appcenter:specs/2019-04/Windows-Plan.md@`windows`](https://github.com/Microsoft/appcenter/blob/windows/specs/2019-04/Windows-Plan.md) [](/Microsoft/appcenter/blob/HEAD@{2019-05-21T21:42:48Z}/specs/2019-04/Windows-Plan.md).

The link is broken, now is https://github.com/microsoft/appcenter/blob/specs/specs/2019-04/Windows-Plan.md.

**Comment by mzhukovs** [comment]
https://github.com/microsoft/appcenter/issues/25 - UWP UI Testing
https://github.com/microsoft/appcenter/issues/383 - UWP Store Support

**Comment by dinobu** [comment]
> In the meantime you can consult https://github.com/Microsoft/appcenter/blob/windows/specs/2019-04/Windows-Plan.md.

I am unable to open that link
