### ISSUE TITLE
Disable in-app update when in guided access mode

### ISSUE THREAD

**Issue by florianbuerger** [Microsoft/appcenter#46]
Hi AppCenter team,

When guided access is enabled on iPad, e.g., for a kiosk application, it would be great if the in-app update mechanism is disabled since it won't work. The system will kill the app to install the update but as soon as the app is killed, guided access relaunches it, and it will present the “Update available” alert again.

I know I could disable the update check for that specific use case but the developer has to think about that, and that particular situation might not arise during development. Would be great if that is handled on the SDK level. There is [official API](https://developer.apple.com/documentation/uikit/1615173-uiaccessibilityisguidedaccessena) to check if guided access is enabled.

Thanks 🙏

**Comment by patniko** [comment]
PR is opened up @florianbuerger. Should get merged fairly soon, but will be a little while until we ship a new SDK with all the work going on right now.

**Comment by patniko** [comment]
HI @florianbuerger, going to move this to next month. Before merging the PR change to disable in-app updates in guided access mode we'd like to investigate a possible fix for it.

**Comment by patniko** [comment]
@florianbuerger - this has been merged into our master branch and should be shipped in the next SDK release early May. Thanks for submitting the issue!
