### ISSUE TITLE
AppCenter fails signing in with a blank page on Android if the user reached max api-token

### ISSUE THREAD

**Issue by lacostej** [microsoft/appcenter#460]
**What App Center service does this affect?**
appcenter.ms 

**Describe the bug**
AppCenter appears to have a limit of max 200 devices per user (something we didn't have with HockeyApp). This is because every sign in from an (Android) new device creates a new api token in the backend.

If a user signs in with a new device and his api token max count is already reached, signing in fails miserably.

**To Reproduce**

Given an android device on which you have never signed up and a user on which you have reached your max number of api token

* start hockeyapp
* When clicking Sign in
* The browser opens https://appcenter.ms/cli-login?hostname=HockeyApp%20Tester%20App&tester=1
* fill email/password and sign in
* browser redirects

**What happens**
page fails to load (blank page)

One of the queries the browser does returns a 400 error with this message:
```
{"error":{"code":"TooManyAPITokens","message":"Each user account only allow to create 200 api tokens"}}
```

See screenshot for extra troubleshooting

**Expected behavior**

1. no error, and a successful login
2. or if an error, a display of the issue so that we save some time finding what is going wrong.

**Screenshots**

![image](https://user-images.githubusercontent.com/24282/58189120-251e1300-7cba-11e9-887a-6148e8ae32af.png)

**Smartphone (please complete the following information):**
 - Device: Huawei T3 7 inches (BG2-W09)
 - OS: Android 6.0
 - Browser: chrome 71.x
 - Version 
 - HockeyApp 4.0.5

**Additional context**

Please see mail sent to support@hockeyapp.net. 

**We need help now!**

**Comment by blparr** [comment]
Hi @lacostej, thanks for bringing this up. We are looking into this and I will update this thread once we have a clear path going forward.

Thanks for your understanding,
Blanca

**Comment by lacostej** [comment]
Just to say that this issue was just about the server not able to display the error that the limit was reached. Last time I tried, the process still ended in a white page which is disconcerting for the user.

**Comment by blparr** [comment]
Hi @lacostej The number of API tokens has been increased from 200 to 5000. This should fix your issue. please, let us know if it doesn't. 

Thanks!
