### ISSUE TITLE
Ability to allow more than 200 devices per user

### ISSUE THREAD

**Issue by lacostej** [microsoft/appcenter#461]
**Describe the solution you'd like**

We are processing thousand of devices using custom scripts to pre-install them with HockeyApp. Those tablets are configured with the same AppCenter user. This means that this user will be assigned several thousand devices in AppCenter.

Unfortunately AppCenter has now set a max 200 devices per user and this breaks our use case. (See #460)

We are supposed to ship the tablets on the coming Thursday (in 2 days) and this issue has delayed us a a few days and putting strain on our installation team.

**Describe alternatives you've considered**

* ask for a custom override for the few users who need to go above this limit (see our mail to support@hockeyapp.net)
* create several users and start rotating them in our install scripts. A bit unpractical from a support perspective.
* hack appcenter?

**Additional context**

See our mail to support@hockeyapp.net

**Comment by lacostej** [comment]
@botatoes can the 200 devices limit be overriden per user? 

Great if we can get an answer to this one within the next 12h. This regression compared to the HockeyApp service is seriously affecting us. See our mail to support. Thanks

**Comment by lacostej** [comment]
Another related issue is what happens to our existing users with more than 200 devices.

**Comment by blparr** [comment]
Hi @lacostej , I addressed your question via other channels. Thanks!

**Comment by lacostej** [comment]
Buenos dias @blparr

I didn't get an answer that I can use today to solve our problems. The issue is marked as feature request but it is a regression from the previous set of features of HockeyApp which we have used for over 5 years now.

Our customers were told long ago that **tomorrow** (June 1st) they would be able to update apps using HockeyApp. For one group of users, we have 1600 tablets connected to the same HockeyApp account. Several other large groups will follow in the coming weeks.

We have no idea what will happen if/when they try to do the updates or even just open the HockeyApp client.

**A simple fix would be to bump the limit of the maximum number of tokens to at least 3000.** This is the kind of fix that can be rolled out pretty quickly. **Is there anything on your side that prevents this from being done?**

If not, what kind of solutions do you advise?

**Comment by blparr** [comment]
Hi @lacostej , I understand your frustration.

As I mentioned before, our team is looking into this. We will be doing a spike to understand the effect of this limit increase. Once we have the outcome, I'll communicate with you the decision.

While we advise our customers to start migrating from HockeyApp to App Center, we know there are still some gaps between the products, and we are actively working on addressing them. This is one of them.

Thanks,
Blanca

**Comment by lacostej** [comment]
> While we advise our customers to start migrating from HockeyApp to App Center, we know there are
> still some gaps between the products, and we are actively working on addressing them. This is one
> of them.

Hence the reason we **haven't migrated yet** !!! All our apps are still managed by HockeyApp.

> I'd advise you keep using HockeyApp.

As far as I know we are still using it. The login process uses appcenter but this doesn't seem to be something I can control.

**Comment by blparr** [comment]
Hello @lacostej - Good news, we have increase the number of API Tokens allowed per account from 200 to 5000. Please, give it a try and let us know if you're still running into issues.

Thank you!
