### ISSUE TITLE
Add support in Codepush for React Native for Windows vNext 

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/appcenter#463]
The Codepush service needs to be updated to support the [React Native for Windows - vNext](https://github.com/microsoft/react-native-windows/blob/master/vnext/README.md) effort. This is high priority ask from the React Native for Windows team in Microsoft to ensure our customers have access to service delivered experiences through Codepush and the E2E orchestration provided by App center.

**Comment by winnieli1208** [comment]
Hi @harinikmsft thanks for filing this request. As far as I know, we don't have any immediate plans to support this (@botatoes please correct me if I'm wrong) but I'd love to learn more about this. Let's set up some time between you and the App Center team to chat more about this!
