### ISSUE TITLE
Custom OS

### ISSUE THREAD

**Issue by sdermanffs** [microsoft/appcenter#464]
**Describe the solution you'd like**
The ability to support apps that don't fit into the supported OSes (iOS, Android, Windows, macOS).  Please add **Custom** similar to how HockeyApp supports Custom. For example, Hololens.

**Additional context**
We have a number of apps migrated from HockeyApp. Many of these are not one of iOS, Android, Windows, macOS apps and therefore we use the "Custom" OS setting.

**Comment by lacostej** [comment]
We will need this as well.

**Comment by derpixeldan** [comment]
Thanks for bringing it up, we have it tracked on our [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#distribution)
>  Custom apps platform support

**Comment by lbrownell-gpsw** [comment]
One of our "apps" is a plugin (for Mac and Win), that is installed via a .pkg on Mac and .exe on Win.  It is not an app -- it is a single file of a specific odd type required by the app for which it is a plugin.  Right now, I can't upload it to App Center.

Thanks.

**Comment by derpixeldan** [comment]
@lbrownell-gpsw on HockeyApp, does it currently reside as a custom app?

**Comment by lbrownell-gpsw** [comment]
@derpixeldan Not yet.  

This is new, thought I'd try creating our first native App Center app, epic fail!

We do have some custom apps in HockeyApp -- for example, Windows apps that install via an .exe, not an .msi, and some mobile SDKs that are in a .zip file, containing frameworks, documentation and sample apps.  We also used to package up build artifacts/logs and save them as custom "apps" as well, but we push all that to Artifactory now.

**Comment by Bart-Verdonck** [comment]
Can we expect this feature to be present once HockeyApp is no longer available. _(16 November?)_
Otherwise we'd have to look for a temporary solution as we also use HockeyApp to host standalone-installers (*.deb, *.dmg and *.msi; each packaged in a *.zip)

**Comment by derpixeldan** [comment]
Yes, everything on the roadmap will be available before the shutdown.

**Comment by martinarvaiaccedo** [comment]
Hi! Any update on this? Besides Android, we work with Samsung Tizen and LG WebOS applications. It would be good to either support these or simply support the "Custom Platform". Both smart TV platforms are javascript applications.
 
Parsing the version would be fairly easy for both of the platforms. Both provide an unzippable archives:
- Tizen contains a config.xml with the version in it
- WebOS contains an appinfo.json with the version.

Thank you in advance!

**Comment by gautamkrishnar** [comment]
For more info 
* Tizen: https://developer.tizen.org/development/tizen-studio/web-tools/configuring-your-app/configuration-editor
* LG: http://webostv.developer.lge.com/sdk/tools/ide/setting-project/

It's better if you can implement signing of lg and tizen applications in appcenter.

**Comment by lbrownell-gpsw** [comment]
Re: my comment above, we have rid ourselves of all our custom apps *except* the plugins I described above.  They are currently in HockeyApp as custom apps.  

When I look at them in App Center, it asks me to classify them as one of the supported types.  

So, obviously not there, and it's a bit scary that in the October Iteration, "Custom apps platform support" is an unchecked box without an issue number (which is, apparently, this one).

November will be a short iteration...unless the demise of HockeyApp is put off for this (and the other remaining features).

So...how's it going?

**Comment by gautamkrishnar** [comment]
I think you guys should add a CI like platform that uses containers so that anyone can add their own custom tools via cli to build the projects. For example: if i need to use gcc i can install it from apt repository and do whatever operations i need on my app, i just need to specify the tasks via commands. This is the only way to support the infinite number of custom OSes.

**Comment by del314** [comment]
So I am catching up here, but HockeyApp supported the upload for our Linux applications (.zip right now) under Custom OS, so I am hoping you guys get this supported on server (and CLI tool is necessary) BEFORE the transition completes. An ETA would be reassuring :)

On that note, I am not sure why you don't support a Linux OS type anyway, as it would be nice to support other installers like .rpm and .deb directly (although we can package inside zip for now).

**Comment by niezbop** [comment]
For documentation purpose, this appears to be supported as of today, at least.

We got a bit worried that our Linux projects got migrated automatically on a platform that wasn't supported (or so we thought).

It would be great if you could document such features becoming supported, closing this issue, and updating #1322 for example!

**Comment by derpixeldan** [comment]
@niezbop the forwarding of crashes from the HockeyApp custom crash upload API wasn't fully completed yet but it is now.

Support for "Custom" OS is supported in App Center now. Please let us know in case you're experiencing any issues.

**Comment by EmilAlipiev** [comment]
Ok, i see that there is Custom how to use this? for example, I have tizen projects. can i install any nuget package or is there an api, i can post http requests? any good documentation usage of crash reports especially?

**Comment by EmilAlipiev** [comment]
Last time I checked this it wasn't working. iMessage able to upload crash and event reports using the rest API but nothing was displayed in the AppCenter. When I asked the support they told me that it is not implemented. What is the status today?
