### ISSUE TITLE
cannot set node version in post-build script

### ISSUE THREAD

**Issue by nschild** [microsoft/appcenter#465]
**What App Center service does this affect?**
Appcenter build

**Describe the bug**
Cannot install a different version of node from post-build script

**To Reproduce**
1. Create a project with React Native
2. Create a file named appcenter-post-build.sh
3. add the lines: 
`    brew install n;
    sudo n 11.11.0;
    node -v`
4. build your app
5. When it comes to run this code, it says it is installing version 11.11.0, but node -v still says 8.16.0

I have also tried the commands:
`sudo installer -pkg "node-v12.3.1.pkg" -target / ; node -v` - 8.16.0

`brew uninstall node@8; 
NODE_VERSION="11.11.0"; 
curl "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}.pkg" > "$HOME/Downloads/node-installer.pkg"; 
sudo installer -store -pkg "$HOME/Downloads/node-installer.pkg" -target "/";
node -v` - 8.16.0

`nvm install 11.11.0` - command not found

`npm install nvm`- nvm is already installed in /Users/vsts/.nvm

`./Users/vsts/.nvm/nvm install 11.11.0` - no such file or directory.

`ls -ls /Users/vsts/.nvm`-  no such file or directory.

It does install with the first command above if I put it into `appcenter-post-clone.sh` but as the app builds, it runs a process labeled "Select Node version" that changes it back to 8.16.0 and I get the above error.

**Expected behavior**
`node -v` outputs 11.11.0

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by nrajpurkar** [comment]
@nschild thanks for opening an issue. Taking a look into this!

**Comment by nrajpurkar** [comment]
Hi @nschild, take a look at this [article](https://intercom.help/appcenter/build/react-native/react-native-builds-fail-with-the-engine-node-is-incompatible-with-this-module-expected-version-xxx-error-found-incompatible-module) on how to set the node version using a post-build script. Reach out again if this doesn't solve your issue.

**Comment by nschild** [comment]
@nrajpurkar This is the exact code I posted in my second example under "I have also tried the commands". Although, in my example, I changed it to uninstall node v8 instead of v6 as the article is severely outdated.
Also, the last code sample from that article will not work as we do not have access to nvm. See examples 3-7 under my "I have also tried" section.

**Comment by dinbtechit** [comment]
> Hi @nschild, take a look at this [article](https://intercom.help/appcenter/build/react-native/react-native-builds-fail-with-the-engine-node-is-incompatible-with-this-module-expected-version-xxx-error-found-incompatible-module) on how to set the node version using a post-build script. Reach out again if this doesn't solve your issue.

```
/Users/runner/work/1/s/app/appcenter-post-clone.sh: line 9: nvm: command not found
```
