### ISSUE TITLE
support for UI Automator based test scripts written in Python

### ISSUE THREAD

**Issue by gautamkrisna** [microsoft/appcenter#468]
Request support for UI Automator based test scripts written in Python. Is there a way we can run those tests on Appcenter ?

**Comment by Oddj0b** [comment]
I'm the program manager responsible for App Center Test and I'm working on a new idea which will support more frameworks in Test, allow unit testing, and browser testing. I would like to talk to you about it and understand your needs better.

Below is a link where you can sign-up for a 30-minute call with me. The agenda will be about the value of testing for you and your organization, and my new idea to allow more frameworks and testing styles in App Center Test.

Link to choose https://calendly.com/vigimm/appcenter-test
