### ISSUE TITLE
Hide "Download" button, if latest version already installed

### ISSUE THREAD

**Issue by amonszpart** [microsoft/appcenter#469]
**Describe the solution you'd like**
Hide "Download" button, if latest version already installed. 

**Describe alternatives you've considered**
Add build number to app name.

**Additional context**
On Android, right now, there is no way to be sure, whether you have the latest build of an app, if the version numbers don't update between builds. This results in an app being downloaded and installed multiple times and a constant insecurity, whether you have updated and are giving feedback to the devs on the latest version of an app, or not.

**Comment by winnieli1208** [comment]
Thanks for the feature request! This isn't listed on our roadmap at the moment but I'll let @botatoes chime in with any suggestions or more details regarding upcoming plans.
