### ISSUE TITLE
Invitation emails use the Organization URL suffix rather than the Name

### ISSUE THREAD

**Issue by andrew-codechimp** [Microsoft/appcenter#47]
**What App Center service does this affect?**
App Center Website/Invitation emails

**Describe the bug**
My organization name is two words (e.g. Mega Corp)
When sending invitation emails the user receives an email with the hyphenated URL suffixed version (Mega-Corp) rather than proper organization name.  My organization is very security conscious and receiving an email with the organization name incorrectly punctuated will cause test users to raise phishing attack flags.

**Expected behavior**
The organization name should be used within invite emails.

**Comment by botatoes** [comment]
Hi Andrew, 

Can you create an intercom ticket so we can take a look at it with more info about your org/account? 
It's the blue button in App Center on the bottom right-hand corner. 

Closing this to move to Intercom.
