### ISSUE TITLE
Updating HockeyApp releases has been temporarily disabled

### ISSUE THREAD

**Issue by Reedyuk** [microsoft/appcenter#470]
**What App Center service does this affect?**
fastlane-plugin-appcenter 0.1.7

**Describe the bug**
When uploading an iOS ipa file, we are getting the following:
Error adding to group 400: {"code"=>"bad_request", "message"=>"Error: Updating HockeyApp releases has been temporarily disabled. Please use HockeyApp for changes."}
And when i go to hockeyapp, the build is not present in hockeyapp.

**To Reproduce**
1. use fastlane and app center fastlane plugin
2. build and upload build to app center
3. See error

**Expected behavior**
Build should be uploaded to app center and any distribution groups should be added to the build.

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave 10.14.1(build server), iOS 12(ipa file)

**Smartphone (please complete the following information):**
 - Device: iPhone and iPad

**Additional context**
When will my builds appear in hockeyapp / app center and when will the temporary disabling of functions be enabled again?

**Comment by derpixeldan** [comment]
This is an unintended side effect. Please see our status page for updates https://status.appcenter.ms/

**Comment by derpixeldan** [comment]
Releasing to apps originated on HockeyApp is working again.
