### ISSUE TITLE
Add support for Android TV

### ISSUE THREAD

**Issue by wsadurski** [microsoft/appcenter#471]
I think you should add support for Android TV. This is a platform which is getting traction nowadays, more and more apps are being developed and there is no good internal app distribution tool available yet. The only one I found is TestFairy but the UX of it on Android TV is not very well but due to lack of alternative we'll probably proceed with it. If you add support for Android TV you can easily extend it onto Fire TV OS which is AOSP-based.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @wsadurski! Keeping this open to track further interest.

**Comment by Nutriz** [comment]
Hi,

Any news ?

**Comment by timoknapp** [comment]
Hi @nilofer, @wsadurski,

is there any news on providing App Center for Android TV or Fire TV?
It would be super awesome to use AppCenter for those platforms too :)

**Comment by nilofer** [comment]
@elamalani to provide an update.
