### ISSUE TITLE
GitHub commit link is broken

### ISSUE THREAD

**Issue by gmsantos** [microsoft/appcenter#472]
**What App Center service does this affect?**
Build service

**Describe the bug**
In the build report, we have a link to the corresponding commit where the build is based in GitHub. 

This link is missing one url part. The link has this pattern `https://github.com/<repo><commit> `but the corret to link back to github is `https://github.com/<repo>/commit/<commit>`

**To Reproduce**
1. Go to a build page
2. Click on the commit link
4. See a github 404 error

**Expected behavior**
An example broken commit link is https://github.com/gmsantos/TailwindTraders_6495qzpadb35eb0547b80de4c6e4275a7cb1625559e6d27b

Actually it should be 
https://github.com/gmsantos/TailwindTraders_6495qzpa/commit/db35eb0547b80de4c6e4275a7cb1625559e6d27b

**Screenshots**

![image](https://user-images.githubusercontent.com/1991286/58257088-97d4d000-7d46-11e9-86cd-ec618cd06fd9.png)

![image](https://user-images.githubusercontent.com/1991286/58257648-acfe2e80-7d47-11e9-86bc-836186b21eec.png)

**Comment by DennisPan** [comment]
@gmsantos Thanks for reporting the bug! I wasn't able to reproduce the bug myself. We get the commit url from GitHub, which seems odd that this would happen. Let us investigate this a bit and I will get back to you.

**Comment by gmsantos** [comment]
I have created this repo using the [App Center Demo Generator](https://appcenterdemogenerator.azurewebsites.net/). I hope that help with the bug reproduction or the investigation.

**Comment by nrajpurkar** [comment]
@gmsantos are you still running into this issue? We were unable to repro this. Will close this out, but feel free to reopen if you still have the issue.
