### ISSUE TITLE
I am trying to Test Run but failed. Please see the error

### ISSUE THREAD

**Issue by rayhan007** [microsoft/appcenter#478]
PS C:\Github\MowlaMobileApp> appcenter test run uitest --app "rayhan.cse.ewu-gmail.com/JMC-android-Test" --devices "rayhan.cse.ewu-gmail.com/samsungset" --app-path "C:\Github\MowlaMobileApp\MowlaMosqueRev\MowlaMosqueRev.Android\bin\Debug\com.mowla.myapp.apk"  --test-series "master" --locale "en_US" --build-dir C:\Github\MowlaMobileApp\MowlaMosqueRev.Test\bin\Debug
/ Preparing tests... Android SDK not found. Please install it and if it is still not located, please set the ANDROID_HOME environment variable to point to the directory.

Searched locations:
Windows Registry
(No path) - Not set. [ Source: ANDROID_HOME ]

Preparing tests... failed.
Error: Cannot prepare UI Test artifacts using command: C:\Github\MowlaMobileApp\packages\Xamarin.UITest.3.0.0\tools\test-cloud.exe prepare "C:\Github\MowlaMobileApp\MowlaMosqueRev\MowlaMosqueRev.Android\bin\Debug\com.mowla.myapp.apk" --assembly-dir "C:\Github\MowlaMobileApp\MowlaMosqueRev.Test\bin\Debug" --artifacts-dir "C:\Users\Rayhan\AppData\Local\Temp\appcenter-upload119425-6768-4b3e4v.hk1ko".

There was an unknown error preparing test artifacts, please try again. If you can't work out how to fix this issue, please contact support.

Further error details: For help, please send both the reported error above and the following environment information to us by going to https://appcenter.ms/apps and starting a new conversation (using the icon in the bottom right corner of the screen)

    Environment: win32
    App Upload Id: rayhan.cse.ewu-gmail.com/JMC-android-Test
    Timestamp: 1558806636884
    Operation: RunUITestsCommand
    Exit Code: 1
    User Email: rayhan.cse.ewu@gmail.com
    User Name: rayhan.cse.ewu-gmail.com
    User Id: d2a97a3d-9008-4b6b-9522-f85dc28d0b44

PS C:\Github\MowlaMobileApp>

**Comment by ahanag22** [comment]
@rayhan007 Looking at the error message, 
/ Preparing tests... Android SDK not found. Please install it and if it is still not located, please set the ANDROID_HOME environment variable to point to the directory.

It looks like either the machine does not have Android SDK installed, or the path does not have the location for ANDROID_HOME set. 
Can you try installing the Android SDK and try again? :)

**Comment by ahanag22** [comment]
After installing SDK, you might have to restart the Command prompt and try again :)
