### ISSUE TITLE
Cannot take a screenshot using Xamarin.UITest 3.0

### ISSUE THREAD

**Issue by DimaOrdenov** [microsoft/appcenter#479]
**What App Center service does this affect?**
Xamarin.UITest 3.0

**Describe the bug**
I'm trying to call `app.Screenshot("name")` method in test, but gets an error during test run:
_Exception: System.Exception: Failed to create C:\Windows\system32\screenshot-1.png. You may need to set the working directory, which can be done using System.IO.Directory.SetCurrentDirectory()._

**To Reproduce**
1. Enable taking screenshots via `ConfigureApp.EnableLocalScreenshots()`. Write test and call method `app.Screenshot("name")`.
2. Run or Debug test
3. Wait for running

**Expected behavior**
Test passed. Screenshot made.

**Screenshots**
https://monosnap.com/file/lkHIqS8cJfaoRGjhykmfG2NGldoGuN

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 9

**Additional context**
I've also tried to call `System.IO.Directory.SetCurrentDirectory(@"my\best\path");`. But I've also got that error with new path:
_Exception: System.Exception: Failed to create my\best\path\screenshot-1.png. You may need to set the working directory, which can be done using System.IO.Directory.SetCurrentDirectory()._

**Comment by DimaOrdenov** [comment]
@Oddj0b Hello, any updates on this?

**Comment by jonstoneman** [comment]
There is now a pre-release version of UITest which changes the behaviour of screenshot creation: https://www.nuget.org/packages/Xamarin.UITest/3.0.1-dev1

Screenshots are saved to the current directory by default but falls back to the directory that `Xamarin.UITest.dll` is in, which is typically your `bin/Debug` or `bin/Release` directory.

Please try it and let us know if it fixes the problem for you.

**Comment by DimaOrdenov** [comment]
> There is now a pre-release version of UITest which changes the behaviour of screenshot creation: https://www.nuget.org/packages/Xamarin.UITest/3.0.1-dev1
> 
> Screenshots are saved to the current directory by default but falls back to the directory that `Xamarin.UITest.dll` is in, which is typically your `bin/Debug` or `bin/Release` directory.
> 
> Please try it and let us know if it fixes the problem for you.

So, I've tried two times with different configurations:
- w/o setting _System.IO.Directory.SetCurrentDirectory()_ I've got same error
https://monosnap.com/file/TUiWq6oatYjw2h2MzQRU9X7UdYt4Z4
It's trying to save in bin/Debug as you've said, but unsuccessfully
- w/ setting _System.IO.Directory.SetCurrentDirectory()_ to some common folder
`System.IO.Directory.SetCurrentDirectory(@"C:\Users\dmitry.ordenov");`
the result is
https://monosnap.com/file/DDG2SpD9wb4GdvU0jRRxKWpjbeBIxC
So, like previous try - no changes at path

**Comment by jonstoneman** [comment]
Could you add code immediately before you call `Screenshot()` which creates files in `bin/Debug` and `C:\Users\dimitry.ordenov` please?

If your test is unable to create these files then you'll need to use another directory which your tests can write to or to run them in a way that they do have permissions.

**Comment by DimaOrdenov** [comment]
@jonstoneman 
Here is how I initialize app:
```
public class AppInitializer
    {
        public static IApp StartApp(Platform platform)
        {
            if (platform == Platform.Android)
            {
                System.IO.Directory.SetCurrentDirectory(@"C:\Users\dmitry.ordenov");

                return ConfigureApp
                    .Android
                    .InstalledApp("com.smartseeds.forwarder")
                    .Debug()
                    .EnableLocalScreenshots()
                    .DeviceSerial("d999fec8")
                    .StartApp();
            }

            return ConfigureApp.iOS.StartApp();
        }
    }
```

Here is my set-up and test-method:
```
[SetUp]
        public void BeforeEachTest()
        {
            _app = AppInitializer.StartApp(_platform);
        }

[Test]
        public void TestTakeScreenshot()
        {
            _app.Screenshot("Test_Screenshot");
        }
```

**Comment by DimaOrdenov** [comment]
@jonstoneman 
Here is how I initialize app:
```
public class AppInitializer
    {
        public static IApp StartApp(Platform platform)
        {
            if (platform == Platform.Android)
            {
                System.IO.Directory.SetCurrentDirectory(@"C:\Users\dmitry.ordenov");

                return ConfigureApp
                    .Android
                    .InstalledApp("<MY_PACKAGE_NAME>")
                    .Debug()
                    .EnableLocalScreenshots()
                    .StartApp();
            }

            return ConfigureApp.iOS.StartApp();
        }
    }
```

Here is my set-up and test-method:
```
[SetUp]
        public void BeforeEachTest()
        {
            _app = AppInitializer.StartApp(_platform);
        }

[Test]
        public void TestTakeScreenshot()
        {
            _app.Screenshot("Test_Screenshot");
        }
```

**Comment by jonstoneman** [comment]
We just need to confirm that the test really does have permission to create files in either `bin/Debug` and in `C:\Users\dimitry.ordenov`. Could you add some code to `TestTakeScreenshot()` (before the call to `_app.Screenshot()`) which creates new files in those locations please? Just a file named `dummy.txt` containing `"Success"` would do.

**Comment by DimaOrdenov** [comment]
@jonstoneman Got you
This one creates **test_file.txt** in `C:\Users\dimitry.ordenov`  if I am setting System.IO.Directory.SetCurrentDirectory(@"C:\Users\dmitry.ordenov") :
```
private string _filePathToWrite => @"C:\Users\dmitry.ordenov\TestTextFile.txt";

[Test]
        public void TestTakeScreenshot()
        {
            File.WriteAllBytes(
                Path.Combine(System.IO.Directory.GetCurrentDirectory(), "test_file.txt"),
                File.ReadAllBytes(_filePathToWrite));

            _app.Screenshot("Test_Screenshot");
        }
```

And another one (w/o setting current directory) creates test_file.txt in Debug folder:
```
private string _projectPath = @"C:\Users\dmitry.ordenov\<MY_PATH_TO_UI_TEST_PROJECT>";
        private string _filePathToWrite => @"C:\Users\dmitry.ordenov\TestTextFile.txt";

        [Test]
        public void TestTakeScreenshot()
        {
            File.WriteAllBytes(
                Path.Combine(_projectPath, @"bin\Debug\test_file.txt"),
                File.ReadAllBytes(_filePathToWrite));

            _app.Screenshot("Test_Screenshot");
        }
```

**Comment by jonstoneman** [comment]
Those look good - what happens when you run them? Does it successfully create the files and then still throw and Exception at `_app.Screenshot("Test_Screenshot")`?

**Comment by DimaOrdenov** [comment]
@jonstoneman 
Yep, *.txt files crates successfully, which cannot be said about screenshots.

**Comment by jonstoneman** [comment]
How very odd. Would you be able to share your app and test code with me so I can see if I experience the same problem? You can send files to us securely by crating a new conversation with support in https://appcenter.ms (button is bottom right of the screen).

**Comment by DimaOrdenov** [comment]
If we are talking about this button https://monosnap.com/file/jg8boLI1ARWnGkAG8CfYe5SbeOr2M6 , I've created new conversation there and linked this issue and your profile.

**Comment by Oddj0b** [comment]
Closing here, to keep all the communication through the support chat.

**Comment by codrinamerigo** [comment]
Did you managed to find a solution for this problem ? I am facing the same...

**Comment by DimaOrdenov** [comment]
@codrinamerigo 
Nope. I was trying on Windows 7, possibly this is the problem.

**Comment by codrinamerigo** [comment]
> @codrinamerigo
> Nope. I was trying on Windows 7, possibly this is the problem.

I am trying on Windows 10 and for the Android ui tests, is not wotking...

**Comment by cocowalla** [comment]
Having the same issue on Xamarin.UITest 3.0.3, on Windows 7 if it makes any difference

**Comment by SShaw1985** [comment]
This is still an issue, was there ever a resolution to this
