### ISSUE TITLE
Add build support for UWP C++/winrt

### ISSUE THREAD

**Issue by RobMeyer** [microsoft/appcenter#480]
App Center supports building UWP C# codebases, but not UWP C++/winrt. 

Additionally, the 'build app' page states, "We couldn’t find any UWP projects in your branch." -- It would be more helpful if it could detect that an unsupported codebase/configuration and display a more specific error message such as, "Sorry, automated builds for UWP C++/winrt apps aren't currently supported. You can manually upload an appx or appxbundle [here]."

**Comment by nrajpurkar** [comment]
Thanks for the feature request @RobMeyer. We'll keep this open to track further interest in this support.
