### ISSUE TITLE
Display provisioning profile expiry date against App version

### ISSUE THREAD

**Issue by dman-github** [microsoft/appcenter#481]
In hockey against every ios app version there is a snippet of information displaying the provisioning profile expiry date.

This is quite useful and should be ported over to app center

**Comment by nrajpurkar** [comment]
Thanks for the feature request @damitha1984. Understand how this would be useful to catch expiring provisioning profiles on your distributed apps. We'll continue to track this feature request.

**Comment by zeinabch** [comment]
@nrajpurkar do you know when this feature will be available again????

**Comment by nrajpurkar** [comment]
@zeinabch this hasn't been prioritized for work in this month's iteration plan. We'll continue to evaluate this amongst other feature requests in the future.

**Comment by zeinabch** [comment]
@nilofer why keep ignoring this issue!!!

**Comment by nilofer** [comment]
@zeinabch I no longer work on App Center. Perhaps @wham can help here.

**Comment by zeinabch** [comment]
@wham could you help??

Thanks 

Z
