### ISSUE TITLE
"New release" dialog should not close when clicking outside its frame

### ISSUE THREAD

**Issue by stschwar** [microsoft/appcenter#482]
**Describe the solution you'd like**
The dialog that slides in when a new release is to be submitted should not close when clicking outside the frame of said dialog.

**Describe alternatives you've considered**
Alternatively, it should keep a draft of what has been edited so far, so it can be recovered when it the dialog was closed by accident.

**Additional context**
It is irritating that all progress (e.g. extensive release notes) is lost when the user accidentally clicks outside the frame and the dialog closes.

**Comment by botatoes** [comment]
This is a design pattern across all App Center. Will discuss with our design team to improve the user experience around this.

**Comment by MasterOfTouch** [comment]
pls, current behavior annoying. You need to upload and write description again after random click outside.
