### ISSUE TITLE
Ability to create custom groups in the OS popup for filtering

### ISSUE THREAD

**Issue by gwootton** [microsoft/appcenter#483]
**Describe the solution you'd like**
Ability to create groups for sorting in App page.  Currently there is only 3 platforms and custom.  Within Android there are alot of platforms that are really separate.  Also support for PS4 and Roku is key

**Describe alternatives you've considered**
Another popup called tags, which we could then tag our apps and have the filter work there.
Similar to HA.

**Additional context**

**Comment by winnieli1208** [comment]
@gwootton thanks for the feature request! We don't have any immediate plans to support this but we'll monitor this feature request to help our team prioritize in the future.
