### ISSUE TITLE
add a Distribution Groups to another Distribution Group

### ISSUE THREAD

**Issue by amarcuse** [microsoft/appcenter#484]
**Describe the solution you'd like**
When added testers to a distribution group, the prompt is "Add testers or groups", yet only emails work.  I want to add another distribution group.

**Describe alternatives you've considered**
Manually added each tester, but this is a pain since we have multiple apps
Using teams, which would be fine, but also doesn't work

**Additional context**
![image](https://user-images.githubusercontent.com/48565781/58501860-56cc2980-8153-11e9-97c9-67c447340f12.png)

**Comment by botatoes** [comment]
Hi, 

This is a bug, I will file it and get it fixed. As for the tediousness of adding emails to multiple apps, you can create a shared distribution group for that. 

Go to Org -> Manage -> People -> Shared distribution groups 

There you can create a distribution group and add multiple apps to it. 

--Bo

**Comment by patniko** [comment]
Closing this for now as we support some variant of this and believe shared groups is the best way to manage this information. If you'd like to see an enhancement to our shared groups feel free to reopen the issue with further clarifications.
