### ISSUE TITLE
Allow searching of crash reports by exception type

### ISSUE THREAD

**Issue by tauntz** [microsoft/appcenter#485]
**Describe the solution you'd like**
We'd like to be able to search for crash reports based on the exception type.

**Describe alternatives you've considered**
Tried to search for crashes based on other parameters but for some types of crashes the only unique and common thing between them is the thrown exception itself.

**Additional context**
The best example of a crash type that's impossible to group/find overall statistics for at the moment is `java.lang.OutOfMemoryError` (but it's not limited to that). It will be thrown from whatever method is failing to allocate memory so the method, class and reason will never be the same and these crashes will never be grouped in the current UI. It's also impossible to get an overview about how many `OutOfMemoryError` crashes have happened per version/across versions/frequency etc due to the fact that it's not possible to search for them in any other way than to manually click through all the crash report pages and search the browser window for the exception class.

**Comment by tauntz** [comment]
@winnieli1208 any update on if it's something that you want to support eventually? If yes, would that be in the near/med/far-term roadmap?

**Comment by jwhiteDev** [comment]
HI @tauntz, Winnie and I have chatted about this functionality a few times. I would say it is definitely something we hope to do at some point. I don't know when but I believe it is safe to say we intend to do this one in the near/med term. A loose spec for it is written up at least ;)

**Comment by ewgenius** [comment]
Hello @tauntz. We just released search by Exception Type, feel free to use it. It is available as part of text search and as a separate filter:

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/827338/66527291-6cae0b80-eab0-11e9-8660-5c1729860e5e.png">

**Comment by tauntz** [comment]
@ewgenius I see the filter but I have not managed to get it actually to filter anything for Android projects. It works however perfectly fine for iOS. Could it be that this was only implemented for iOS projects?
@octopotato - I think this should be re-opened.

Android:
The crash report:
![Screenshot 2019-12-05 at 14 48 52](https://user-images.githubusercontent.com/55713/70236888-87c69000-176e-11ea-8f38-9caa33b85995.png)

Searching for the exception gives no results:
![Screenshot 2019-12-05 at 14 49 43](https://user-images.githubusercontent.com/55713/70236922-9ad96000-176e-11ea-8581-4df1fae51ee5.png)

Filtering for the exception gives no results:
![Screenshot 2019-12-05 at 14 49 24](https://user-images.githubusercontent.com/55713/70236938-a4fb5e80-176e-11ea-9f20-0a7833a0fe35.png)

**Comment by winnie** [comment]
Hi @tauntz - this was implemented for all platforms so it should work fine for Android. Can you start a support thread (blue chat bubble on the bottom right) so our team can take a closer look? Thanks!

**Comment by DennisPan** [comment]
Upon further investigation, what @tauntz mentioned indeed is a bug. When the exception doesn't contain an application exception type, we use the OS exception type as a fallback for the error group's exception type. Unfortunately we didn't realize that for the Search implementation, so only the application exception type is used. With the holidays, I doubt we will have a fix by end of the year. But hopefully we can work on this in the beginning of the new year.

Thanks for reaching out!
