### ISSUE TITLE
Missing feature under versions "Ignore Crashes" operation

### ISSUE THREAD

**Issue by moon1978** [microsoft/appcenter#488]
On HA we have a feature to ignore specific version from collecting crashes. "Ignore Crashes". this feature is missing on App Center

**Comment by winnieli1208** [comment]
@moon1978 thanks for the feature request. We don't have any short term plans to build this feature but you can ignore specific crash groups from a version in App Center by selecting the crash group and marking the status as ignored:

![image](https://user-images.githubusercontent.com/8868628/58822118-9380a080-85eb-11e9-8b77-5d0641f6183b.png)

I know that requires a bit more work than just ignoring all crashes from a specific version but I hope that helps a bit!

**Comment by moon1978** [comment]
Hi
But on HA I have the option to ignore all crashes on specific version so crashes won’t be uploaded

Sent from my iPhone

On 3 Jun 2019, at 20:44, Winnie Li <notifications@github.com<mailto:notifications@github.com>> wrote:


@moon1978<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmoon1978&data=02%7C01%7C%7C1d6b9f1da837470c95df08d6e84b2529%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636951806770488718&sdata=1Anctm5ruP4vz3T7ilBB55O9yTlY6HCGy76HEfnSIfA%3D&reserved=0> thanks for the feature request. We don't have any short term plans to build this feature but you can ignore specific crash groups from a version in App Center by selecting the crash group and marking the status as ignored:

[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F8868628%2F58822118-9380a080-85eb-11e9-8b77-5d0641f6183b.png&data=02%7C01%7C%7C1d6b9f1da837470c95df08d6e84b2529%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636951806770498723&sdata=F8EyFH2wBEqUkErieeVQ89KmiDNtkIYBX9PWqJjS%2F58%3D&reserved=0>

I know that requires a bit more work than just ignoring all crashes from a specific version but I hope that helps a bit!

**Comment by winnieli1208** [comment]
Yep, we recognize this is as a feature gap. Due to other priorities at the moment, we don't have any immediate plans to address this in the upcoming months. I'll post here when I have any updates. Thanks!
