### ISSUE TITLE
[Feature] The Ability to Send Images in Push Notifications

### ISSUE THREAD

**Issue by bobber205** [microsoft/appcenter#489]
**Describe the solution you'd like**
When I get a push notification from Instagram and Youtube (for instance) there is sometimes an image attached. I'd love the ability to do this in a push notification sent via the App Center SDK.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jwargo** [comment]
@bobber205 thank you for this suggestion.  It's not something you can do today, but I'll add it to our wish list. I'm checking to see if you can set an image URL as a custom property and have it displayed.

**Comment by bobber205** [comment]
Actually an image URL would be the preferred way of implementing this that
sounds great

**Comment by bobber205** [comment]
@jwargo Have you had a chance to look into this? The custom property solution?

**Comment by bobber205** [comment]
FWIW I've done the old college try and this doesn't work

![image](https://user-images.githubusercontent.com/5841107/59057774-02f6ca00-8850-11e9-8986-a3f90625c348.png)

Notification sends fine but no image is displayed

**Comment by jwargo** [comment]
@bobber205 You're sending the URL, but your app still needs to retrieve the URL from the notification, download the image, and display it somewhere. This isn't something the SDK does for you now. 

If you want something more than that, can you please describe exactly how it would work?

**Comment by bobber205** [comment]
My ideal use case would to be able to send a push notification like Instagram or Youtube does where the image appears IN the notification.

**Comment by jwargo** [comment]
@bobber205 OK, thanks for that information. I'm building a feature list for a future SDK refresh and I know I want to get more client-side capabilities added to the SDK. I'll keep this in mind as I work on that.

**Comment by dev-abcdevelopers** [comment]
@jwargo FCM does support Image sending. You can type a valid HTTP or HTTPS URL in image and Notification will display it on Client device. It would be much better if it will be added in appcenter, too.

**Comment by kevinjpetersen** [comment]
Any update on this? @jwargo 
For people that need this functionality (Like me) we're kinda forced to go away from AppCenter and directly to say Firebase because AppCenter doesn't support it yet. Is there no other way?

**Comment by jwargo** [comment]
@kevinjpetersen No, I'm sorry - no update.

**Comment by adrianknight89** [comment]
Grr... Is there a way to expedite this? A lot of us need this functionality. As always, Microsoft delivers a half-baked product.

**Comment by jwargo** [comment]
@adrianknight89 @kevinjpetersen @bobber205 Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

The good news is that this is something you can do in Azure Notification Hubs today.

**Comment by bobber205** [comment]
@jwargo Is there going to be a way to use the current app tokens that we have in our databases with Azure or it is going to require a deploy/app update to retrieve new tokens and invalidating all existing tokens?

**Comment by jwargo** [comment]
@bobber205 I'm assuming you mean device tokens? That's one of the transition items we're working on, validating our plan to make that seamless (register devices for both services for a while until ACP retires).

**Comment by bobber205** [comment]
@jwargo Good to know thanks! 
A transition plan is vital -- users don't always update their app as fast as we'd like so this is super important.
