### ISSUE TITLE
Allow deletion of builds

### ISSUE THREAD

**Issue by scriptam** [microsoft/appcenter#492]
Allow deletion of cancelled / failed builds.

Currently builds can be started and cancelled, however they cannot be removed via the portal or via the API.

**Comment by nrajpurkar** [comment]
Thanks for this request @scriptam. Is your use case here to clear up clutter from the list of builds?

**Comment by scriptam** [comment]
Hi and thanks @nrajpurkar. 

The use case leading for this request is as follows:
1) Customer automates and schedules builds via a script
2) One or more builds are cancelled
3) New builds will be queued
4) For resuming scripts (and for reporting), fetching all builds is cumbersome as they need to be filtered out by status every time
5) Customer wishes to only retain builds that completed, succeeded or failed (since they contain logs and meaningful data) but not cancelled ones (since they are empty)

De-cluttering will be a secondary but valuable benefit.
