### ISSUE TITLE
Analytics -> Events not loading.

### ISSUE THREAD

**Issue by frags51** [microsoft/appcenter#493]
**What App Center service does this affect?**
Analytics ( Events web page)

**Describe the bug**
Using Analytics.trackEvent() to track button clicks. The registered events show up fine in the Log Flow tab on the website.
(https://appcenter.ms/users/t-susin-microsoft.com/apps/RNTest/analytics/events)
However, the Events Tab keeps loading indefinitely. Seems to be stuck and not making any progress (stuck, see screenshot)

**To Reproduce**
Track event (button onPress) using Analytics.trackEvent().
Try to open the events tab on your app page. (Eg: https://appcenter.ms/users/t-susin-microsoft.com/apps/RNTest/analytics/events)

**Expected behavior**
The webpage to load,

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
- Version  74.0.3729.169

**Smartphone (please complete the following information):**
 - Device: Emulator - Android 9
![appcneter re](https://user-images.githubusercontent.com/25797471/58622008-4d27fa80-82e8-11e9-98ab-5bef78a3e7ba.PNG)

**Additional context**

**Comment by hamswan** [comment]
@frags51 We will take a look at this issue.

**Comment by YiMysty** [comment]
Hi there, have you installed anything like adblocker? since our api contains `events` or `event_logs` as part of route, it is in a blacked list of these extensions. :( 

We are going to work for a fix for that, but in the meantime, try to disable such extensions and give a try thanks!

**Comment by frags51** [comment]
@YiMysty Yes, that was the issue. Thanks! Hopefully this can be fixed, since these days many end-users do have adblockckers installed.

**Comment by NaagAlgates** [comment]
> Hi there, have you installed anything like adblocker? since our api contains `events` or `event_logs` as part of route, it is in a blacked list of these extensions. :(
> 
> We are going to work for a fix for that, but in the meantime, try to disable such extensions and give a try thanks!

I can confirm that even today this works only if I disable the ad blocker.
