### ISSUE TITLE
My apps configs suddenly got reverted

### ISSUE THREAD

**Issue by dmishra2019** [microsoft/appcenter#495]
**What App Center service does this affect?**
android-prod

**Describe the bug**
I have configured my bitbucket branch in my android-prod app but now its all configurations gone.

**To Reproduce**
1. Go to android-prod
2. choose 'production'
3. See there is no configs

**Expected behavior**
My config changes should retain.

**Comment by DennisPan** [comment]
@dmishra2019 Could you reach out to support via the chat bubble at bottom right of the portal? Given I haven't heard similar reports from other customers, we will need more information to look into what happened.

**Comment by DennisPan** [comment]
Closing this as this would require support.
