### ISSUE TITLE
Show release number

### ISSUE THREAD

**Issue by clivejefferies** [microsoft/appcenter#497]
Currently the release number given in App Centre is not shown in Hockey App. That means in Android we have to put the release number in the release notes as the build number coming from Android does not change with each test build.

**Comment by derpixeldan** [comment]
@clivejefferies please help me understand why you’re still using HockeyApp when it works for you in App Center? We won’t add the release ID to HockeyApp, however, I believe the intention of the version code is to change whenever the code changes.

**Comment by clivejefferies** [comment]
I am talking about the Hockey app app on the device. It does not show the release number that you see in the App Center listing e.g release 1, release 2 etc. With Android we are not able to change the version code easily on the our CI server and this is only really used for Google Play. It does not make sense to update it just for test builds.

On 30 May 2019 15:42, Daniel Adams <notifications@github.com> wrote:

@clivejefferies<https://github.com/clivejefferies> please help me understand why you’re still using HockeyApp when it works for you in App Center? We won’t add the release ID to HockeyApp, however, I believe the intention of the version code is to change whenever

**Comment by derpixeldan** [comment]
@clivejefferies ok, thanks for explaining. I'd recommend to run a beta app with its own versioning.

**Comment by clivejefferies** [comment]
Hi,
     Is that really a good solution when all you need to do as add one number to the Hockey app apps, which would make it easier for people to use? I have attached screenshots to show what I mean. In app centre you can see the release history number, yet it is not visible the app.

Clive
________________________________

**Comment by derpixeldan** [comment]
@clivejefferies it's a valid feature request. However, I just mentioned that the version code is supposed to be a distinct number indicating any code changes. Otherwise it'll be hard to identify crashes or get build specific analytics data.

**Comment by clivejefferies** [comment]
I see, the problem with that is that we would have to commit that single change every time we wanted a new build which seems counter intuitive. It's purpose is the increment on Google Play, which means you wouldn't necessarily change it on every test build. It would also be problematic if we had different people working on different branches as the last known value may change without the developer knowing.

On 31 May 2019 13:17, Daniel Adams <notifications@github.com> wrote:

@clivejefferies<https://github.com/clivejefferies> it's a valid feature request. However, I just mentioned that the version code is supposed to be a distinct number indicating any code changes. Otherwise it'll be hard to identify crashes or get build specific analytics data.
