### ISSUE TITLE
Push notifications requires new setup on all iOS apps and fails

### ISSUE THREAD

**Issue by Sebastian1989101** [microsoft/appcenter#498]
All of my iOS app require a new setup for the push notifications for some reason within AppCenter. But even if I fill the required data it always reports an error and I'm no longer able to use the push service (even on apps where it was working before).

**Comment by jwargo** [comment]
@Sebastian1989101 can you please provide more information? You're telling us you receive an error, but have not provided the error message. 

Have you open an issue with our support team? I'd like to ensure you've worked through the issue with the support team before we look at this as a bug. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by Sebastian1989101** [comment]
@jwargo It seems like it was a temporarly issue with AppCenter. 2 friends of mine and the company I work for had all the same issue at that time (AppCenter was requesting a new setup für Push which always failed). About 4h after reporting it magicly starts working again for everyone.
