### ISSUE TITLE
Releasing directly to Android store Production suddenly doesn't work anymore using AppCenter CLI

### ISSUE THREAD

**Issue by devedse** [microsoft/appcenter#499]
Hi all,

In december last year I fully automated the release of my Android application to the App Store using AppCenter. See for example this build:
https://ci.appveyor.com/project/devedse/deveblockstacker/builds/21288368

However when I just triggered a new build it failed with the error:
`Error: Could not find group Production`

I'm now trying to investigate what is going on, I tried executing the following command locally:
```
appcenter distribute release -g Production -f "C:\XKanWeg\Block\deveblockstacker_android.deveblockstacker_android-Signed (1).apk" -a Devedse/DeveBlockStacker.Android -r "This is a test" --token ****************
```

However this now also returns the error:
`Error: Could not find group Production`

![image](https://user-images.githubusercontent.com/2350015/58654034-53819b00-8317-11e9-9b33-d4f41470025c.png)

Does anyone have an idea on how to fix this?

```
C:\XKanWeg\Block>appcenter distribute release -g Production -f "C:\XKanWeg\Block\deveblockstacker_android.deveblockstacker_android-Signed (1).apk" -a Devedse/DeveBlockStacker.Android -r "This is a test" --token ******************************** --debug
Using appcenter-cli version: 1.1.18
| Loading prerequisites...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/distribution_groups/Production/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": null
}
/ Loading prerequisites...Response status code: 404
Body: {"error":{"code":"NotFound","message":"Could not find distribution group Production in this app"}}
| Creating release upload...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/release_uploads",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": null
}
| Creating release upload...Response status code: 201
Body: {"upload_id":"********************************","upload_url":"https://rink.hockeyapp.net/api/sonoma/apps/********************************/app_versions/upload?upload_id=********************************"}
| Finishing release upload...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/release_uploads/********************************",
  "method": "PATCH",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": "{\"status\":\"committed\"}"
}
- Finishing release upload...Response status code: 200
Body: {"release_id":"44","release_url":"v0.1/apps/Devedse/DeveBlockStacker.Android/releases/44"}
| Updating release details...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/releases/44",
  "method": "PUT",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": "{\"release_notes\":\"This is a test\"}"
}
- Updating release details...Response status code: 200
Body: {"release_notes":"This is a test"}
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/distribution_groups/Production",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": null
}
Response status code: 404
Body: {"error":{"code":"NotFound","message":"Could not find distribution group with name Production"}}
Error: Could not find group Production
```

**Comment by devedse** [comment]
@Oddj0b, I saw you were assigned to this issue. Do you have any update on this?

**Comment by Oddj0b** [comment]
@devedse Instead of using production you will need a connection ID. You find the connection ID using the following endpoint: https://openapi.appcenter.ms/#/distribute/stores_list

**Comment by devedse** [comment]
@Oddj0b , can you get that using appcenter-cli as well?

**Comment by devedse** [comment]
@Oddj0b , just executed the command which gave me this result:
```
[
  {
    "id": "2f3fd2e1-e13f-44a7-b582-f3052421bb9e",
    "name": "Alpha",
    "type": "googleplay",
    "track": "alpha",
    "created_by": "ee2b7d7f-c028-46e9-80a6-30e6bb6dc77c",
    "service_connection_id": "b0b26c08-b8a5-ef40-8fb4-547b7806cd87"
  },
  {
    "id": "a0fc91df-41b8-4e81-a05b-959e43d17619",
    "name": "Beta",
    "type": "googleplay",
    "track": "beta",
    "created_by": "ee2b7d7f-c028-46e9-80a6-30e6bb6dc77c",
    "service_connection_id": "b0b26c08-b8a5-ef40-8fb4-547b7806cd87"
  },
  {
    "id": "ff30917b-0718-4a3c-9d9a-304c4f5578bf",
    "name": "Production",
    "type": "googleplay",
    "track": "production",
    "created_by": "ee2b7d7f-c028-46e9-80a6-30e6bb6dc77c",
    "service_connection_id": "b0b26c08-b8a5-ef40-8fb4-547b7806cd87"
  }
]
```

Then I tried to publish it to this group but it still failed :
![image](https://user-images.githubusercontent.com/2350015/59516135-f3672900-8ec0-11e9-99c7-df597f45e46a.png)
https://ci.appveyor.com/project/devedse/deveblockstacker/builds/25284955

Any idea?

**Comment by devedse** [comment]
@Oddj0b, is there an update on this? My release pipeline has been broken for a while now and I'd like to fix it :)

**Comment by Oddj0b** [comment]
@devedse Sorry for the lack of response. There's some confusion about this whole workflow, I'll return with more information.

**Comment by devedse** [comment]
@Oddj0b , thanks :)

**Comment by devedse** [comment]
@Oddj0b, is there an update on this already? It's somewhat frustrating that there doesn't seem to be a way to get any support on Microsoft tooling like AppCenter directly.

Is there a way to get some visibility on this?

**Comment by Oddj0b** [comment]
@devedse Sorry for the slow response, this is what we have discovered so far:
- It's a surprise that some store connections have worked at all
- It appears that production connection never works as it is right now
- **You can use our APIs** to connect to stores instead of our CLI
- There is also an option of using our Fastlane plugin.

Again sorry for the inconvenience.

**Comment by devedse** [comment]
@Oddj0b,

I've been going through the API's a bit and don't quite understand what calls I have to make to be able to submit to the store.

Could you maybe share some guidance with me on what sequence of call to make to push a package to the store?

Or would it simply be this one?:

```
/v0.1/apps/{owner_name}/{app_name}/distribution_stores
```

and if so, is the Intune block required?:
![image](https://user-images.githubusercontent.com/2350015/61278507-9ce95500-a7b4-11e9-9b4c-7653231b55d2.png)

I guess it shouldn't be too hard to add this to the AppCenter-CLI either right?

**Comment by jpeg-ms** [comment]
Hi @devedse,

I agree with @Oddj0b that it's a surprise it even worked at all.

I believe the easiest solution right now for you would be to use Fastlane and our plugin. You can find some information at: https://github.com/microsoft/fastlane-plugin-appcenter

And for a reference of `fastlane/Fastfile`, you can use this configuration:

```
# Load variables from .env file in the root if it exists
if File.exist?('../.env')
  open('../.env', 'r').readlines.each do |l|
    kv = l.split('=')
    ENV[kv[0]] = kv[1].chomp
  end
end

default_platform(:android)

platform :android do
  desc "Release through AppCenter Stores"
  lane :appcenter do
    appcenter_upload(
      # api_token can be omitted if token is in env var APPCENTER_API_TOKEN
      api_token: ENV["TEST_APPCENTER_API_TOKEN"], 
      owner_name: "Devedse",
      app_name: "DeveBlockStacker.Android",
      apk: "./app/release/app-release.apk",
      release_notes: "Your release notes",
      destinations: "Production",
      destination_type: "store"
    )
  end
end
```

I hope this helps, and I'm sorry we don't have support for Stores publishing in our CLI yet.
