### ISSUE TITLE
Support Update Prompt in App Store / TestFlight builds

### ISSUE THREAD

**Issue by tonyxiao** [microsoft/appcenter#502]
**Describe the solution you'd like**

App Center's in-app update feature is incredible for keeping testers always using the latest version of the app. We'd love to be able to have a similar mechanism to force update actual customers in either TestFlight or App Store. I understand that in-app update won't work because install has to be through the app store, but it would be super handy to pop up an alert and take user directly to TestFlight / app store page to update upon pressing "ok", or force a mandatory update as need be. 

**Describe alternatives you've considered**
Building a custom micro-service that talks to the App Center API and figures out what's the latest build for a given install. This is quite a bit of work and also not re-usable for other developers using app center. 

**Additional context**

**Comment by nrajpurkar** [comment]
Thanks for the feature request @tonyxiao! Tapping in @botatoes to take a further look on this.
