### ISSUE TITLE
NodeJS selection for JS applications

### ISSUE THREAD

**Issue by mdere-unbound** [microsoft/appcenter#507]
**Describe the solution you'd like**

I would find it actually really convenient if we can select the Node versions for our builds. Is it possible to get some sort of node version selection in the build settings?

**Describe alternatives you've considered**

Ran them in pre scripts for appcenter

**Additional context**

**Comment by nrajpurkar** [comment]
@mdere-unbound thanks for opening this request! This isn't available today, but it is something we're actively working on. I'll update here when we release this soon!

**Comment by nrajpurkar** [comment]
@mdere-unbound this is now available! Refer to our [documentation](https://docs.microsoft.com/en-us/appcenter/build/react-native/nodejs) for more information.

**Comment by mdere-unbound** [comment]
You all are awesome!!! I'll mess around with it today.

Thanks!!
