### ISSUE TITLE
Unable to build iOS with Cocoapod 1.7.0

### ISSUE THREAD

**Issue by KovalM** [microsoft/appcenter#508]
**What App Center service does this affect?**
AppCenter - BUILD/Branches

**Describe the bug**
It doesn't build react-native-maps pod for iOS. There is next error: 
'Google-Maps-iOS-Utils/GMUKMLParser.h' file not found.
![image](https://user-images.githubusercontent.com/8680298/58789504-f88dc380-85f6-11e9-9f36-8ec54574621e.png)
I already found the solution of this issue here: https://github.com/react-native-community/react-native-maps/issues/2876#issuecomment-495337558
But it helped for the local environment and I can't apply it in AppCenter because it is issue of cocoapods. It was fixed in Cocoapods 1.7.1. 

**Desktop:**
 - OS: MacOS 10.14.4
 - Browser Chrome
 - Cocoapods 1.70

**Comment by nrajpurkar** [comment]
@KovalM Thanks for reporting this. We'll be updating to Cocoapods 1.7.1 soon on the hosted machines so this shouldn't be an issue. You can also add in [this script](https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/general/cocoapods-rollback/appcenter-post-clone.sh) to use 1.7.1 until that rolls out to the machines.

**Comment by KovalM** [comment]
@nrajpurkar Very thanks!
