### ISSUE TITLE
Analytics Funneling

### ISSUE THREAD

**Issue by gunnartorfis** [microsoft/appcenter#509]
**Describe the solution you'd like**
I would like to be able to funnel the custom analytics events.

**Describe alternatives you've considered**
Firebase Analytics supports this.

**Additional context**
Here's more to read about it: https://en.wikipedia.org/wiki/Funnel_analysis

**Comment by hamswan** [comment]
Hi @gunnartorfis ,
Thanks for reaching out to us. Have you tried exporting the App center Analytics data to Azure Application Insights?  You can set up continuous export and leverage some of the features in Azure Application insights and you can create funnels and do detailed analysis.
https://docs.microsoft.com/en-us/azure/azure-monitor/learn/mobile-center-quickstart
