### ISSUE TITLE
Inject files that can't be in repo

### ISSUE THREAD

**Issue by struct78** [microsoft/appcenter#51]
**Describe the solution you'd like**
Inject files at build time. We have a few files that contain either sensitive or branch-related information that we don't want to include in our repo, but do need to be there at build time.

It would be good to be able to either inject/attach files at the pre-build step, or be able to target a list of files that require environment variable string replacement.

**Describe alternatives you've considered**
Creating files with appcenter-pre-build.sh and injecting environment variables, which becomes unwieldy.

**Additional context**
N/A

**Comment by nrajpurkar** [comment]
@struct78 thanks for this feature request! Understood that the alternative can be a lot to manage after a while. We'll keep this request open to track further interest.
