### ISSUE TITLE
Include Crash Free Sessions % Metric

### ISSUE THREAD

**Issue by freddyhm** [microsoft/appcenter#510]
Our team finds examining sessions much more useful than simply looking at how many users have experienced x amount of crashes. Knowing that a user has experienced 100 sessions with 1 session crashed is more useful than simply knowing they experienced 1 crash.  

We've looked at the API but Microsoft Support says crash free session information has been deprecated.

**Comment by winnieli1208** [comment]
@freddyhm thanks for the request! We don't have an API that returns this information directly but as a workaround you can use [this API](https://openapi.appcenter.ms/#/analytics/Analytics_SessionCounts) to get the total number of sessions in a given time range and then use the [crashes API](https://openapi.appcenter.ms/#/errors/Errors_CountsPerDay) call to get the number of crashes in that same time range to calculate a percentage. I know this isn't an ideal experience for your scenario but I hope that helps!

**Comment by freddyhm** [comment]
Awesome! That helps a lot, thanks @winnieli1208 . I hope it'll be integrated in the main dashboard later on or have a way to create our own graphs in app center. 

Also, for those interested, we managed to pull the same data by exporting our data to Application Insights and executing the following query:

let TotalSessions = toscalar(
    customEvents
    | summarize dcount(session_Id));
customEvents
| where name == "UnhandledErrorLog"
| summarize ErrorSessions = dcount(session_Id)
| project (todouble(ErrorSessions) / todouble(TotalSessions) * 100)
