### ISSUE TITLE
Crash: Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by mhalt** [microsoft/appcenter#511]
**What App Center service does this affect?**
appcenter.xamarin

**Describe the bug**
Our mobile application is crashing on startup. There is no error message but app center shows the following error message:

**MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status)
SIGABRT: Authentication failed because the remote party has closed the transport stream.**

**To Reproduce**
1. Open the app
2. App crashes
3. Re-open app and it's fine.
4. We disabled appcenter in the code and we are no longer getting the issue.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 12.2

[report-2518431571970009999-a8bcb2ae-bd97-4fc3-871b-31e49cf27fab (2).txt](https://github.com/microsoft/appcenter/files/3247880/report-2518431571970009999-a8bcb2ae-bd97-4fc3-871b-31e49cf27fab.2.txt)

**Comment by winnieli1208** [comment]
@mhalt thanks for reporting this. Can you start a thread in the blue chat bubble on the bottom right corner in App Center? This will put you in touch with our support and engineering team so they can take a closer look for you. Thanks!

**Comment by AnastasiaKubova** [comment]
HI, @mhalt ! It does not look like the problem of our SDK. How I see from your crash report the problem appeared in API which not used our SDK. Could you please describe in details reproducing steps.
