### ISSUE TITLE
Splitting quick sign-in from login with email broke android app broke signing in...

### ISSUE THREAD

**Issue by lacostej** [microsoft/appcenter#512]
**What App Center service does this affect?**
Distribution

**Describe the bug**
The sign-in process from the Android app uses a callback mechanism to return to the app and complete the sign in. This allows the HockeyApp app to refresh itself, remove the sign-in page and display the available applications.

There was a change in the past few days on appcenter.ms that broke this.

The change was to split the quick sign in (Github/Personal/...Facebook/Google) sign ins from the email signins. The latter flow now requires to press on a link "Sign in with email" to go to the next screen.

Unfortunately this "Sign in with email" link doesn't pass the URL parameters necessary for the callback to the native app to happen properly. So when the sign in completes, the user is left on https://appcenter.ms/hockeyapp-transition-center instead of being redirected to the HockeyApp app. When looking at the app it seems like the user isn't logged in as the Sign-in button it displayed once again.

You can reproduce this on a browser by simulating the flow used on the Android app.

**To Reproduce**
1. Go to 'https://appcenter.ms/sign-in?original_url=%2Fcli-login%3Fhostname%3DHockeyApp%2520Tester%2520App%26tester%3D1'
2. Click on 'Sign-in with email'
3. Look at the URL, it lost the parameters. This will break the Android sign-in flow.

**Expected behavior**
Sign in process redirects to app

**Screenshots**
<img width="646" alt="image" src="https://user-images.githubusercontent.com/24282/58812993-386aa000-8623-11e9-8910-b45729d2f143.png">

See the difference between the create account link and the sign in one.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
One can press sign in again and if the the sign in was successful, the sign in process will be skipped. For us this is a bit unpractical as we are using automated tools to sign in.

**Comment by blparr** [comment]
Hello @lacostej , this should now be fixed. Please try it out and let me know if it works now. Closing unless I hear otherwise. Thank you!
