### ISSUE TITLE
Notarization for Mac apps

### ISSUE THREAD

**Issue by WCByrne** [microsoft/appcenter#514]
**Describe the solution you'd like**
App notarization was announced last year but not enforced. With [the announcement](https://developer.apple.com/news/?id=06032019i) that this will be required for macOS 10.15. Will it be possible for AppCenter to handle this before distributing apps?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by botatoes** [comment]
Hello, we are investigating the impact this week and will update this issue when we know more.

**Comment by shpakovski** [comment]
Notarization is impossible without having access to your Apple ID and the Team that the app belongs to, if multiple. I doubt this can be done via the App Center. $0.02

**Comment by jkocherhans** [comment]
Not sure if this will make things easier or even possible, but it looks like there are some new options in altool 4.0 with Xcode 11b3.
https://mjtsai.com/blog/2019/07/03/altool-4-0/

**Comment by WCByrne** [comment]
Any updates on this? No dates yet but we are getting closer... 😬

**Comment by WCByrne** [comment]
@botatoes Catalina is out, any hope of this being handled by App Center? I was so excited to have a seamless release flow with sparkle support finally landing 😞.

**Comment by iseebi** [comment]
I wrote a post-build script for workaround.
https://github.com/iseebi/TransporterPad/blob/master/appcenter-post-build.sh

**Comment by WCByrne** [comment]
FWIW, I ended up writing a script to run locally that fetches the build, sends it off for notarization, polls for the successful response, then when completed finishes the notarization and re-uploads the build. 

That said, I'm currently only re-uploading a DMG to my own server that is made available for new users of my app to download. I'm still releasing the un-notarized updates  via app center and they seem to work find via sparkle. 

I'm thinking I could download and re-upload the notarized build to AC for distribution via a script as well but I haven't made it that far yet. I believe that will mean also having to bring the symbols along as well.

It crazy that Apple thinks sending an email is a good as the only way to let you know a potentially lengthy operation is done. It's 2019, a webhook would be nice 😄. I've had a notarization take over 12 hours. At that point, polling in an AppCenter script doesn't really seem feasible which is why I'm sticking with the download/re-upload approach for now.

**Comment by mikewoodworth** [comment]
This request is getting pressing as more of our users move to catalina. We aren't able to use any of the deployment functionality in app center because we need to download and notarize the app before sending even simple test builds to users.

**Comment by davidev-b** [comment]
Any update on this?

**Comment by davidev-b** [comment]
> I wrote a post-build script for workaround.
> https://github.com/iseebi/TransporterPad/blob/master/appcenter-post-build.sh

Did it work? Did you include your credentials in that file than?
