### ISSUE TITLE
add a new column in crash reporting "Issues" that provides a ref# 

### ISSUE THREAD

**Issue by SogoGolf** [microsoft/appcenter#516]
**Describe the solution you'd like**
want to be able to quickly/easily get a "reference #" for each crash item so we can include it in our commits (ie. that fixes the given issue)

**Describe alternatives you've considered**
go up to the address bar in browser; highlight the URL in appcenter (of the crash). copy and paste that into the commit....yuk

**Comment by winnieli1208** [comment]
Thanks for the request! I agree it's a pretty yucky experience. Due to other priorities at the moment, we don't have immediate plans to address this. We'll keep this issue open to keep track of community support and I'll post here if we have any updates. Thanks!
