### ISSUE TITLE
Add support for Xcode betas (e.g. Xcode 11)

### ISSUE THREAD

**Issue by fernandotcl** [microsoft/appcenter#517]
**Describe the solution you'd like**
I'd like to request support for Xcode betas in the Microsoft-hosted agents. The rationale is that between June and September, iOS/macOS developers will be using Xcode betas to get ready for upcoming iOS/macOS releases, so Xcode beta support is essential to be able to continue using e.g. Azure Pipelines for CI throughout this time period.

**Describe alternatives you've considered**
The alternative is, of course, to not provide Xcode betas. This means that Azure Pipelines is nearly useless for 1/4th of the year for a lot of iOS/macOS developers.

**Additional context**
Xcode betas can be installed at the same time as non-beta Xcode versions -- developers just have to `xcode-select` the right app.

It's also important that later betas are also timely provided as they're made available by Apple because APIs change throughout the beta process, for instance.

Competitors such as Travis have provided beta versions of Xcode in a timely manner in the past.

**Comment by nrajpurkar** [comment]
Hi @fernandotcl, we began supporting Xcode betas with Xcode 10 and will continue to add the betas with Xcode 11. We do caution that as these are betas, we do expect some bugs along the way 😄 will have this out soon for you to test your build with!

**Comment by fernandotcl** [comment]
Thanks for the getting back to me, @nrajpurkar. Is there any chance we could get an estimate of when Xcode 11 will be available? I see it's on the plan for July, but it was also in the plan for June and got bumped.

I'm sure you guys are aware of how time-sensitive this is, but just to reiterate: now is exactly when we need CI as a lot of code changes are happening. Having access to the betas later is very much less valuable.

(Travis already supports Xcode 11, btw.)

**Comment by nrajpurkar** [comment]
Apologies on the delay @fernandotcl. We ran into issues and were seeing several failing builds on the first beta. We weren't happy with shipping a broken experience with the first beta. We've been working through the issues and believe they're almost all resolved at this point. Pending no issues with some final pieces, Xcode 11 beta support should come shortly!

**Comment by nrajpurkar** [comment]
@fernandotcl and by shortly, I mean it is available now! Happy building 😄

**Comment by JPSiller** [comment]
@nrajpurkar Hi! Given that Xcode 11 is in production release now, do you have an ETA to be available for Xamarin builds? 
Thanks

**Comment by nrajpurkar** [comment]
@JPSiller yep, we're tracking this in #1096 and was just enabled today!

**Comment by JPSiller** [comment]
@nrajpurkar Awesome thank you!
