### ISSUE TITLE
Runtime Environment variables for iOS 

### ISSUE THREAD

**Issue by Zhipeng-Chang** [microsoft/appcenter#519]
**Describe the solution you'd like**
I'm trying to build an iOS using app center, but I could get the environment variables to work. I wonder. I just wonder in order for iOS to recognize the env vars, what should I do in the code?

**Describe alternatives you've considered**

**Additional context**

**Comment by nrajpurkar** [comment]
Hi @Zhipeng-Chang, we do support environment variables for iOS already. Take a look at the [documentation](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/) and let us know if you have a more specific question.

**Comment by derpixeldan** [comment]
@Zhipeng-Chang
> Environment variables can be consumed during the build process.

They cannot be used at runtime. I assume you're looking for device variables that can be consumed at run time. That currently doesn't exist. A potential solution would require to integrate the SDK. In case this is what you're looking for, please update the issue accordingly so it can be treated as a feature request.

**Comment by Zhipeng-Chang** [comment]
Hi @derpixeldan, 
Thank you for getting back! Yes, that's exactly what I'm looking for. I'm trying to set an environment variable that same with the Android environment variable listed in the app center documentation. 
e.g. `buildConfigField("String", "API_KEY", "\"${System.env.API_KEY}\"")`, so that I can use it at both runtime and build time. Another question: if the app center support environment variables during the build time, when I download the build from the app center, the app doesn't work because there are no variables I need. So what's the point that the build process can consume the Environment variables? Thank you!

**Comment by Zhipeng-Chang** [comment]
Hi @derpixeldan,
I think I got what do you mean in the previous post. So what I'm trying to do is that I have some secret keys in my code and I don't want to upload them to Github, so I defined them as the environment variables in my code. In App Center, there is no problem to build the app, but when I download and install the build to my phone, it shows it doesn't have the API key in the app. 

Based on my understanding of your previous posts, the reason for this problem is that the device running the app doesn't have the environment variables I need and the Env Vars didn't bind to the app when it's built in the app center. 

If I understood correctly, do you any recommendations for this problem?

Thank you.

**Comment by Zhipeng-Chang** [comment]
Hi, I end up using the pre-build script to add the env vars to my app. So losing the issue ...

**Comment by tarun29061990** [comment]
Hey
I am getting *** instead of the value in pre-build script for environment variables in ios? please help

**Comment by NetPumi2** [comment]
> Hey
> I am getting *** instead of the value in pre-build script for environment variables in ios? please help

because you click on the lock next to this variable in the config

**Comment by p0x6** [comment]
> Hi, I end up using the pre-build script to add the env vars to my app. So losing the issue ...

how are you using pre-build script to add envs? are you just like writing a .env file? could you share a sample script with me?

**Comment by p0x6** [comment]
yea, writing it to .env file worked for me. had to go to settings and save then build before app center registered the prebuild script though.

**Comment by MaxenceMax** [comment]
can someone share a sample to achieve that ! I'm stuck with it to !
