### ISSUE TITLE
Support Distribution of Windows applications using MSIX/APPX and .AppInstaller files

### ISSUE THREAD

**Issue by rido-min** [microsoft/appcenter#52]
VSAC already support APPX/MSIX packages to distribute UWP applications. Because there is no difference between the packaging of a UWP app or any other app (e.g. Win32/WPF) packaged with MSIX this scenario is already supported.

With .NET Core 3 supporting WPF and WinForms, the preferred distribution method will be MSIX, including the ability to manage automatic updates using the .Appinstaller file. (see [this doc](https://docs.microsoft.com/en-us/windows/msix/app-installer/app-installer-root) for more information)

The .appinstaller file and the actual packages can be hosted in VSAC at a known location, so users don't need to setup a custom web server to host those files.

**Comment by onovotny** [comment]
It's more than distribute. We need the appcenter SDK to support .NET Core 3 as well so we can get proper crash dumps and analytics.

**Comment by winnieli1208** [comment]
Hi all, 

Thanks for the feedback. I'm syncing with our engineering teams to see what kind of work this would require and will update this thread with any updates. This isn't currently on our short term roadmap but we're definitely interested in supporting distribution, diagnostics, and analytics for other Windows platforms as well.

Thanks!

**Comment by dleeapho** [comment]
@winnieli1208 any update after syncing with engineering?

**Comment by winnieli1208** [comment]
@dleeapho thanks for the reminder! Our engineering teams looked into this and due to some unique requirements for supporting the .appinstaller scenario this scenario would require a non-trivial amount of work. Since our engineering teams are focused on HockeyApp transition work this quarter, we don't have the bandwidth to work on this feature.

That said, this is definitely on our radar and something we want to support. Unfortunately, I just don't have an ETA yet. I encourage everyone to follow our roadmap and iteration plan for any updates. Thanks!

**Comment by gavinwilliams** [comment]
+1 appinstaller with automatic updates is a must have

**Comment by OzBob** [comment]
@winnie please confirm AppCenter now supports Packaging Projects and .appinstaller distribution.(Packaging Project creatie APPX/MSIX packages. [https://aka.ms/wapproj](https://aka.ms/wapproj))

@onovotny  there was a dotnetcore3.1 announcement: ["Get Started with DevOps for .NET Windows Desktop Apps and Visual Studio App Center by Daniel Jacobson, Matt Korwell"](https://channel9.msdn.com/Events/dotnetConf/NET-Conf-2019/B105) at dotnetconf2019

Is there in 'in app' auto-update or 'you have an update' message from App Center? or do we have to use Win.Sparkle or Windows.Squirrel?

**Comment by harvinders** [comment]
Is there any update on this? I don't think we would be able to leverage app center if this is not supported. This is probably the only way we can actually distribute windows LOB apps.

**Comment by leoniDEV** [comment]
@harvinders have you tired https://businessstore.microsoft.com/en-us/store

**Comment by harvinders** [comment]
@leoniDEV The IT has decided against the store access to employees. Also, some of the apps needs to be made available to outside very targeted customers, who again may not have access to microsoft store.

**Comment by leoniDEV** [comment]
The IT department can disable the access to the public Microsoft Store but enable the access to the the Microsoft Store for Business which is a sort of private instance of the Microsoft Store for the organization where users can find only apps approved from the IT department.
The Microsoft Store for Business is based on AAD, every users in the AAD tenant of the organization can access the same Microsoft Store for Business with the same apps, even external guests.

Another option is to build your private repository where you can host and publish your AppInstaller files and use AAD (or whatever identity system you prefer) to enable the orgs to access their apps.

And last option is to leave to the organizations the responsibility to share the AppInstaller files with the users, even using a simple network share (if they don't want to use some MDM solution or build their own web repository).

To be clear I don't won't to convince anybody to use this specific solution, I'm only try to provide a possible solutions.

**Comment by follesoe** [comment]
Any updates around this? Would be great if it were possible to at least build `. appinstaller` packages. The distribution I could do manually. Right now it looks like a custom Azure DevOps pipeline with an onsite build-agent is needed?

I.e.: https://mazeez.dev/posts/uwp-devops

**Comment by SA5NNN** [comment]
I'm interested in this functionallity, has it already been implemented from some other issue or is it still not done? It looked like there was in interest 2 years ago...
I'd like to see the simplest possible solution so we can get started, more features can get built on later.

**Comment by harvinders** [comment]
Any updates?

**Comment by OzBob** [comment]
@dipree @ilyashumihin @winnieli1208 any updates on appcenter offering WPF apps updates. or any Roadmap updates at all (#2234  https://github.com/microsoft/appcenter/issues/2234)

**Comment by OzBob** [comment]
@dipree @ilyashumihin @winnieli1208 any updates on appcenter offering WPF app updates. 

Any Roadmap updates at all (#2234 #2234)
