### ISSUE TITLE
Auth Twitter returns error on login

### ISSUE THREAD

**Issue by YsFred4** [microsoft/appcenter#520]
**What App Center service does this affect?**
Auth

**Describe the bug**
Login with Twitter was working but after changing the layouts, Twitter is not logging in.

**To Reproduce**
Have not tried creating a new application.
Had login working with Twitter on Auth and then changed layouts, and other settings in B2C and now I cannot login.  It is returning the error in the screenshot.  Also changed from the Sign Up/Sign In user flow to the Sign Up/Sign In v2 user flow on B2C.

**Expected behavior**
Expect Twitter to login again.

**Screenshots**
![Screenshot_1559706280](https://user-images.githubusercontent.com/982377/58929715-47864680-8726-11e9-98fe-2f070404f599.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Insider Edition
 - Browser Edge (Chromium edition)

**Smartphone (please complete the following information):**
 - Device: Android Emulator (VS2019)
 - OS: 8.1

**Additional context**

**Comment by amchew** [comment]
Hey @ysfred4, thanks for letting us know! We may need to troubleshoot more and get your app sensitive details. Would you mind going to https://appcenter.ms, clicking the blue chat button at the bottom right of the screen and copy pasting this GitHub issue? Ping here when you’ve done that and I’ll make sure we will look at your ticket.

**Comment by YsFred4** [comment]
Done

**Comment by amchew** [comment]
Thanks! Just responded on the chat button.

**Comment by amchew** [comment]
Hey @YsFred4, we responded in the ticket, we tried using V2 user flow with our sample app and it seems to work fine. Could you try running your V2 user flow via the Azure Portal again?
