### ISSUE TITLE
Push to more than 100 devices

### ISSUE THREAD

**Issue by ricavir11** [microsoft/appcenter#522]
**Describe the solution you'd like**
Be able to send push notification to more than 100 devices

**Describe alternatives you've considered**
I'm considering to split requests but didn't test it yet.
Is it possible to split push notification request (with more than 100 devices) in several requests ? (eg : a notification has to be sent to 350 devices, then 4 requests will be created and sent to appcenter server)

**Comment by jwargo** [comment]
@ricavir11 yes, that's how you have to do it.
