### ISSUE TITLE
Distribution step in build fails with "Error: App specific password is mandatory for 2fa enabled account in service connection id"

### ISSUE THREAD

**Issue by FunkyLambda** [microsoft/appcenter#523]
**What App Center service does this affect?**
Distribution

**Describe the bug**
I have a build configured to distribute to TestFlight. However, it fails with the error in the title.

**To Reproduce**
1. Connect to App Store Connect Users (TestFlight) using an Apple ID with 2FA setup.
2. Setup an app-specific password following instructions at https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple#adding-two-factor-authentication.
3. Configure a build using provisioning profile and p12 cert to publish to TF.

**Expected behavior**
Assuming the build passes, the IPA should get uploaded to TF.

**Screenshots**
None.

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
None.

**Comment by Oddj0b** [comment]
@FunkyLambda sorry for the lack of response here. Is this still a problem? If it still is a problem, can I ask you use our support system (the blue chat icon) in the App Center portal?
The reason for this is that we will have to get URLs from your build where it fails.
