### ISSUE TITLE
Allow downloading of analytics event data to .xls and/or .csv

### ISSUE THREAD

**Issue by markymc** [microsoft/appcenter#525]
**Describe the solution you'd like**
We have a simple use case that I'd suspect others do too. We're tracking simple events with parameters (e.g. ids of objects viewed), and want to be able to view the counts of each id in an Excel or CSV file for easy sharing with non-techies. This seems to be a fairly standard feature for analytics platforms, so I'm very surprised to see that it's not available in AppCenter.

**Describe alternatives you've considered**
We've looked at connecting to Application Insights and it's very difficult to understand how to do this simple task. Also having to create an Azure subscription just to do this seems a bit ridiculous.

**Additional context**
none

**Comment by hamswan** [comment]
Thanks @markymc for suggesting this, we will add this to our feature request backlog.
