### ISSUE TITLE
Getting Stalled Error during test run.

### ISSUE THREAD

**Issue by avanti-deodhar** [microsoft/appcenter#526]
**What App Center service does this affect?**
App center xamarin uitest test runs

**Describe the bug**
Getting "Current test status: Stalled error (contact support for more info)" message when trying to run tests.

**Expected behavior**
The same tests were running without any error before and expecting the same.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Apple iPhone XS Max (12.3.1)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Apple iPhone XS Max (12.3.1)

**Additional context**

**Comment by Oddj0b** [comment]
@avanti-deodhar it's faster to contact our support through the blue chat icon in the App Center portal.
