### ISSUE TITLE
API Endpoint to list a user's teams

### ISSUE THREAD

**Issue by catkin24** [microsoft/appcenter#527]
**Describe the solution you'd like**
API endpoint to list all teams for a specific user within an org.

**Describe alternatives you've considered**
Making a call to get all teams in an org, then making a subsequent call for each team to get the user list, then parsing those lists to search for a given user.

**Additional context**
This would also seem to help with appcenter.ms, where the "Apps" column under Teams all contain dashes unless you click in to inspect a team that you have access to.

**Comment by iageoghe** [comment]
@catkin24 This request seems pretty straightforward. I really curious about the use case here, is this for some auditing scenario? Thanks in advance.

**Comment by catkin24** [comment]
@iageoghe We effectively want to know what existing teams a given user is NOT a part of. We have a list of all existing teams, and currently we're making (then caching the aggregation of) separate calls for each team to get the users on each team. We then filter out all of the teams that the user is a part of to determine which ones they aren't a part of.

It'd be a lot more efficient if we could just make a single call to get a user's teams, then filter out the ones that are returned, rather than making a call for every single team to get their member lists.
