### ISSUE TITLE
Feedback UI / Shake to Send

### ISSUE THREAD

**Issue by mcmar** [microsoft/appcenter#530]
**Describe the solution you'd like**
Support for HockeyApp's Feedback UI (aka "Shake to Send")
https://support.hockeyapp.net/kb/general-account-management-2/invoking-feedback-ui-with-a-shake-gesture
This is something that HockeyApp supports, but isn't supported by app center. I'm very upset that you're killing HockeyApp while providing an inferior product to replace it 😡 

**Describe alternatives you've considered**
HockeyApp is the primary "alternative", but it's being mercilessly slaughtered by the Gods of Microsoft.
InstaBug is another alternative that my CEO wants us to adopt, but I would strongly prefer HockeyApp or AppCenter.

**Additional context**
We're very happy with Codepush and AppCenter's CI pipeline. We would love to also adopt both analytics and diagnostics to replace Sentry/Amplitude, but our CEO is pushing hard for Instabug or equivalent. I'd also be happy if you let us use HockeyApp and didn't force a move to AppCenter

**Comment by derpixeldan** [comment]
@mcmar regardless of your frustration, we don't accept any abusive language. If you want this to be a proper feature request, re-think your wording, otherwise I'll close it.

We're working hard to make App Center the successor of HockeyApp and we've intentionally decided to not support the Feedback functionality. There's a [recommendation site](https://docs.microsoft.com/en-us/appcenter/transition/feedback) in our docs.

The purpose of this repository is to inform of our users about upcoming work and offer them a way to raise issues or request features publicly. The more precise the use case is described the better it is for other users to discover and upvote a request.

**Comment by mcmar** [comment]
@derpixeldan Can you define what you consider abusive language? I re-read it and can't find anything that a reasonable person would characterize as abusive

**Comment by mcmar** [comment]
As far as the feature request goes, this is a straightforward feature request asking for implementation of a new feature that's already supported in an "alternative product" if you can call it that. Thank you for the documentation showing that this was at least intentionally omitted. Hopefully I'm not the only user who disagrees with this decision. Part of my reason for disagreeing is not simply because it's useful functionality, but also because the team responsible for the decision not to support it is also responsible for killing an existing product that does support it, which feels very unfair to customers.

Maybe one way to fulfill this feature request without doing any new work would be to simply not kill HockeyApp? That way existing users can continue happily using the in-app Feedback UI. Ot at least any decision to kill HockeyApp could be delayed until existing functionality is supported by the successor product

**Comment by sathukorale** [comment]
Yup you are not the only one. I can't believe this feature didn't make it into AppCenter. Honestly most bug reports (the big one that makes your head hurt) are simply useless without user feedback (atleast this has been the case for me). And as for simple bug reports I always went with Fabric.io. Until now I thought this was in the roadmap, or perhaps might be put into later on, but after seing that documentation, I have got to say, I am dissapointed.

They have every right to kill any of these features, and I suppose I have to consider other options.

**Comment by derpixeldan** [comment]
@mcmar even though I had to chuckle I think it's not the right place for sarcasm.
> mercilessly slaughtered by the Gods of Microsoft

We have carefully weight on this decision and won't support a transition experience for Feedback. However, if the feature request becomes popular enough, we're re-considering adding a similar functionality to App Center in the future.

**Comment by victorbondar** [comment]
The companies of Avistar and InFocus have many products that relays on feedbacks including Windows/IOS/Android/MacOS OSes. This was one of the key things that supports products real life stability.
If this feature removed the most of the enterprise products will lose this kind of feedbacks including automated logs/dumps reporting in case of failure on customer's side.

Most of the options given by MSFT as a reasonable and possible replacement in fact have limitations in a range of different OSes support or does not provide ability to attach and store custom data. Most of them just mobile oriented.

Please take all above into account while planning. We were contacted Anvesh and he asked us to have a note in this thread.

**Comment by petero-dk** [comment]
+1 but is this not a duplicate of #412 ?

**Comment by nishiarya** [comment]
+1 Because 12 of our apps are using Feedback UI feature and we are waiting for the same to be included in AppCenter. We are not able to migrate due to unavailability of this very important and useful feature.
