### ISSUE TITLE
New release date shows up in the past

### ISSUE THREAD

**Issue by faisal-fls** [microsoft/appcenter#532]
**What App Center service does this affect?**
Release / Distributing the app

**Describe the bug**
We have created the new release in the app yesterday June 06th 2019 - the public page on the app shows the date as Dec 04 2018.

**To Reproduce**
1. Go to public page of the app.

**Expected behavior**
The release date should be the date when the release is being created.

**Screenshots**
Please find attached
<img width="1118" alt="Screen Shot 2019-06-07 at 6 35 37 AM" src="https://user-images.githubusercontent.com/35715867/59101436-95e64180-88ee-11e9-8403-e18c9243ae9d.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by derpixeldan** [comment]
@faisal-fls can you please reach out to us in support (blue button in App Center) so we can have a closer look?

**Comment by dimazaid** [comment]
@faisal-fls were you able to follow up on this via the support channel?
