### ISSUE TITLE
Tag option for builds

### ISSUE THREAD

**Issue by spiridonkopicl** [microsoft/appcenter#533]
We would like to have the possibility to tag each build. During the build our script should be able to tag i.e. add some unique identifier to the build. Then you should expose REST API endpoint which we can trigger using that tag to download .apk or .ipa. It would really help to automate whole process. Our QA would be able to integrate it into their testing pipeline to call your API to download that tagged build. There will be n builds with the same tag but endpoint should return always the last successful. We have thousands app and this will simplify much our automated testing pipeline and I hope it will benefits other colleagues with similar use cases.

**Comment by nrajpurkar** [comment]
Thanks for this feature request @spiridonkopicl. To clarify, you'd like to add some sort of tag onto a build such as ```QA Build``` and bucket all builds with that tag separately? Does that sound correct or are you asking for something different?
