### ISSUE TITLE
Can't use binding library in Xamarin UITest project

### ISSUE THREAD

**Issue by luwed** [microsoft/appcenter#535]
**What App Center service does this affect?**
Xamarin UITest Android/iOS.

**Describe the bug**
I have Android and iOS libraries with helper functions for automation tests. I want to use these libraries in Xamarin UITest project so that I've prepared binding library (only Android for now).
I try to use a method from that binding library in Xamarin UITest project, but I get an error: error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

**To Reproduce**
1. Create Xamarin Android project
2. Create Android binding library with helper functions for automation testing
3. Try to use one of the helper functions from binding library

**Expected behavior**
Can use helper functions from binding library

**Screenshots**
![1](https://user-images.githubusercontent.com/48298421/59106692-509a3200-8937-11e9-8084-c25f1234ce35.png)
1. ATSL - binding library
2. GDInteraction - project under test
3. PressHome() - helper function

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - IDE: Visual Studio for Mac 8.0.9 (build 5)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 Android emulator
 - OS: Android API 26

**Additional context**
I also tried to invoke method from binding library not directly so that I used .NET standard library, Xamarin Android project and Unity (Unity was added to ATSLInterface, Atsl.Android and test.ui projects) to register type and invoke proper method. It compiles fine but when a method is called by Unity I get runtime exception:

{System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' or one of its dependencies.
File name: 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
  at testui.Tests.AppLaunches () [0x00014] in [...]

![2](https://user-images.githubusercontent.com/48298421/59106994-fc438200-8937-11e9-937d-f4be4ff08bef.png)
1. Atsl.Android - Xamarin Android project with reference to binding library
2. ATSLInterface - .NET standard library with interface which is registered in Unity (done in Config.cs)
3. GDInteraction - app under test

Unfortunately I haven't found a way to use binding library with helper functions in Xamarin UITest project and I haven't found any info that using binding library in Xamarin UITest is not possible. 

1. Is it possible to reference somehow binding library in Xamarin UITest project. 
2. If not, are there any plans to add such feature to Xamarin UITest?

**Comment by Oddj0b** [comment]
Thank you for reporting the bug.

**Comment by Oddj0b** [comment]
@luwed We have created a bug on our backlog and will update here when there is progress.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
