### ISSUE TITLE
App center Android and Ios daily user data is not correct too much variation(User:- FRAAO@ascensia.net)

### ISSUE THREAD

**Issue by jagdishnagar** [microsoft/appcenter#538]
User :- FRAAO@ascensia.net

**What App Center service does this affect?**
Daily user data and session data too much variation 

**Describe the bug**
Android and ios session and daily user data too much variation like 4 june daily user is 4000 and 5th June data is 18000.

**To Reproduce**
1. Go to '...' App center 
2. Click on '....' Apps android or iOS app. 
3. Click on App analytics 
4. Daily user data variation is too much.

**Expected behavior**
Data should be in form , should not vary too much

**Screenshots**
Sure Adding screesnhot

**Desktop (please complete the following information):**
 - Window
 - Microsoft Edge
 -  Common issue coming all other version and other browser too.
![4JuneDaily](https://user-images.githubusercontent.com/4545518/59143682-fce92080-89ea-11e9-9273-c0bdceedeec9.PNG)
![5JuneData](https://user-images.githubusercontent.com/4545518/59143683-fd81b700-89ea-11e9-870b-f67ba41fba21.PNG)
![6junedata](https://user-images.githubusercontent.com/4545518/59143684-fd81b700-89ea-11e9-8a70-98d52e5e0b0f.PNG)

**Additional context**

**Comment by hamswan** [comment]
@jagdishnagar We are looking into this.

**Comment by yoannchaudet** [comment]
@jagdishnagar What specific version are you filtering the view on for your Android application? Also if you look at the same graph today, do you still see a gap for June 5th?

We do not have a known "variation" or data loss issue.

I looked at your application's raw logs and noticed an interesting pattern:

![image](https://user-images.githubusercontent.com/14911070/59394216-b3bf0680-8d33-11e9-822c-0cb93132c9dd.png)

For the last 7 days, 50% of your logs were sent to our backend within 4 minutes (of being generated by our SDK), 95% under ~21 hours, 99% < 1 day and 99.9% under ~ 4 days. This is significantly higher than an application where all devices have good network connectivity.

If I may ask, is your application used in special conditions where devices' network connectivity is either bad or can be unavailable for long period of time?

**Comment by jagdishnagar** [comment]
I am filtering 2.6.20. yes still gap is there and please check daily
session graph as well too much variation.
Yes application will work in offline mode too but usually this much data
variation we never feel.

Please Check data/graph prior to 29 may 2019. only 252 user is showing
actual data should be in range 16k to 20k.

Regards
Jagdish Nagar

**Comment by yoannchaudet** [comment]
I do not have access to your analytics portal, only raw data. Screenshots of the daily sessions per user graph could help.

The active users graph from your screenshot seems to indicate your version 2.6.20 was only widely adopted after 5/29. If that's not the case you may have an integration issue with our SDK. The analytics you are seeing are matching the raw logs we receive from your application.

Would you mind opening a support ticket from our portal (using the bottom right blue button)? This will be easier to track.

**Comment by jagdishnagar** [comment]
We have done integration long back , earlier it was working fine suddenly
it stop working.
Now its working fine but what about those days client is asking about wrong
data reason.

Please find attached app daily session data graph.

**Comment by yoannchaudet** [comment]
I do not see your attachment.

Please open a support ticket from our portal.
