### ISSUE TITLE
Building of UWP application that targeted to Windows 10 SDK (10.0.18362.0) finishing with error

### ISSUE THREAD

**Issue by mnikonov** [microsoft/appcenter#539]
**Service**
"Build" service

**Description**
Building of UWP application that targeted to last windows 10 SDK  (10.0.18362.0)  finishing with error 

Error MSB3774: Could not find SDK "WindowsDesktop, Version=10.0.18362.0"

1. Target to appcenter UWP application that pointer to last Windows 10 SDK version
2. Navigate to Build section and start it 
3. After build would be finished check status and output window
4. Status of build would be "failed"  and outpot window will containe error message "Could not find SDK "WindowsDesktop, Version=10.0.18362.0""

**Expected behavior**
Build finished successfully

**Desktop**
 - OS: Windows 10
 - Version 1903

**Additional context**
for a tests Windows 10 SDK can be downloaded with the next link
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

**Comment by mnikonov** [comment]
is it possible to get any comments on this issue? For me this issue breaks (stops) whole testing process of application!

**Comment by DennisPan** [comment]
@mnikonov Apology about the lack of response. This doc lists the software installed on the Windows machine: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md . If Windows 10 SDK is missing, have you tried installing it via the [build scripts](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/)?

**Comment by mnikonov** [comment]
From Vs2017-Server2016-Readme.md document

An addition the following optional components are installed:

Microsoft.VisualStudio.Component.Windows10SDK.10240
Microsoft.VisualStudio.Component.Windows10SDK.10586
Microsoft.VisualStudio.Component.Windows10SDK.14393
Microsoft.VisualStudio.Component.Windows10SDK.15063.Desktop
Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop.arm
Microsoft.VisualStudio.Component.Windows10SDK.17134
Microsoft.VisualStudio.Component.Windows10SDK.17763

But, what actually missed is 

SDK that was released with last Windows 10 version
Windows 10 SDK (10.0.18362.0)

https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

Do you have any example that describes how to add Visual Studio Component with build script? That by the way requires 3GB of storage and installes over 20min

**Comment by mnikonov** [comment]
Ok, I was able to install SDK and compile appication. @DennisPan, Thanks for your help.

The PowerShell script that installed SDK was next

appcenter-pre-build.ps1

`
echo **Custom_AppCenter_Script**
echo **Installing Microsoft Windows SDK for Windows 10 and .NET Framework 4.7 10.1.18362.1...**
choco install windows-sdk-10.1
echo **Cloning completed.**
`

But, probably would be nice if it possible to include this SDK to Vs2017-Server

**Comment by DennisPan** [comment]
Yup agree. Feel free to open a new Issue in [the GitHub repo](https://github.com/Microsoft/azure-pipelines-image-generation). 

BTW, the link to App Center doc regarding images is [here](https://docs.microsoft.com/en-us/appcenter/build/software#operating-system), which has a link to the above mentioned Windows image details.

**Comment by nrajpurkar** [comment]
@mnikonov glad you were able to get this working via a build script. I'm going to close out this bug.
