### ISSUE TITLE
Allow metadata to be added to Test Runs

### ISSUE THREAD

**Issue by Naishy** [microsoft/appcenter#540]
**Describe the solution you'd like**
In order to help identify test runs within AppCenter it would be useful to be able to tag Test Runs with extra metadata when they were created via the CLI. This could be Key/Value pairs or just a text string. An example would be to include the build number and/or commit from within Azure Devops/CI.

**Describe alternatives you've considered**
Currently we're using Test Series to break up Test Runs created from different builds, but this doesn't provide information down to the level of detail required.

**Comment by Oddj0b** [comment]
@naishy thanks for the feedback. This isn't on the current backlog, but it is a great idea.
