### ISSUE TITLE
Scheduled Analytics Reports by Emails

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#544]
Hi,

Please add an option to schedule the following analytics reports by email.

User can send to multiple emails and can define the subject and **From** email

Schedule can be set as Daily, Weekly, Monthly, Yearly and user can set the exact date for example every 1st of the Month or every 1st Jan, etc

1. Active Users
2. Daily Users
3. Monthly Users
4. Top Devices
5. Users by Country
6. Active Users by version
7. etc....

Thanks,
[Jassim](https://www.softnames.com)

**Comment by hamswan** [comment]
Thanks @jrahma we have added this as a feature request.

**Comment by jrahma** [comment]
Is there any schedule for this feature? I can sadly say that the portal never had any major update for more than a year now..
