### ISSUE TITLE
Other options for update delay time than "ask me in a day" for Distribution module

### ISSUE THREAD

**Issue by ufna** [microsoft/appcenter#545]
**Describe the solution you'd like**
When the new version of app is available, it'll be great to have ability to change the option "Ask me in a day" to something like "Ask me next launch" or "in 5 minutes", etc.

**Describe alternatives you've considered**
Manual update via AppCenter website.

**Additional context**
![appcenter_distribute](https://user-images.githubusercontent.com/271578/59251824-622f5280-8c33-11e9-85d3-6e821e120dcf.png)

**Comment by botatoes** [comment]
Thanks for the suggestion. Will speak with our designers about delaying options.

**Comment by lgsoftgit** [comment]
And what with this sugestion?

**Comment by p-nordlund** [comment]
Ping. This dialog really needs a "Ask me next time" option or "Skip"
