### ISSUE TITLE
[Feature] Clone branch configurations via API with secret env variables

### ISSUE THREAD

**Issue by alexpopaconst** [microsoft/appcenter#546]
**Describe the solution you'd like**
We would like to be able to somehow clone environment variables that are marked as secret when cloning build configurations via the AppCenter API .

**Describe alternatives you've considered**
An alternative would be to not mark Environment Variables as secrets, avoiding the encryption and then they can be exposed by the API call.
This is however not a good solution, as we cannot afford to leave sensitive information unencrypted.

**Additional context**
We are aware that this feature was recently added in the UI of AppCenter, but in a completely automated process it is still a limitation, as it is still a manual process. 
We are triggering the cloning of configurations via the AppCenter API from GitHub Actions in order to replicate the configurations on the creation of new feature branches.

The issue we are facing is that Environment Variables that are marked as secret have the value: '__protected__' and are not being exposed, and  thus cannot be copied to new branches.
It is perfectly understandable that something that is encrypted should not be exposed via a simple API call, but the UI solution seems to be able to copy the encrypted values to new branches, and we would like to see an implementation of that via the API as well.

**Comment by DennisPan** [comment]
@alexpopaconst I'm assuming you are not using `cloneFromBranch` when creating the branch configuration. When cloning a branch configuration on the portal, this is what's used. Could you give that a try?

If you are already using it, but still not seeing secret variables copied, that would likely be a bug (and please let us know if that's the case)

**Comment by alexpopaconst** [comment]
Many thanks! I missed that, ups.
Works as expected.
