### ISSUE TITLE
Provide a user-friendly test report for unit tests

### ISSUE THREAD

**Issue by RedRoses1234** [microsoft/appcenter#547]
**Describe the solution you'd like**
A user-friendly report generated for unit tests that are ran as part of the build, showing the pass and fail status. Maybe the report could be made available as part of the "Download" button. Currently, we have to scroll through the build logs to find the information. A bonus would be the ability to automatically email the report to a list of recipients.

**Describe alternatives you've considered**
Looking through the logs to see the details.

**Comment by piterwilson** [comment]
It should be straight forward by using the `xccov` command or by allowing the download of the .xccovreport file. 

Alternatively, Xcode 11 will provide a result bundle in `xcresult` format that be easily parsed.

**Comment by DrBeak1** [comment]
This is especially helpful with parallel testing enabled. Because the logs provide no details about what happened in the case of a failed test.
