### ISSUE TITLE
Custom Sound in AppCenter Push

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#548]
Hi,

The custom sound is not available from Android 8.0+ as per AppCenter support team and as per this link:

[https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms#android](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms#android)

This is a dramatic limitation especially when this feature is already provided by all other Push Notification portals, e.g. OneSignal (attached) then I strongly believe Microsoft must have it.
![OneSignalPush](https://user-images.githubusercontent.com/6236241/59285066-6c2a7300-8c7e-11e9-84d3-bd7a6c1e16b6.png)

Thanks,
[Jassim](https://www.softnames.com)

**Comment by jwargo** [comment]
@jrahma thanks for the suggestion. As I understand it, beginning with Android 8, Google put ownership of the notification sound in the hands of its users. What you're seeing other notification platforms do is enable custom sounds through their SDKs. This is probably something we can add to our SDK as well; I'm curious how important this feature is to other App Center customers.

**Comment by jrahma** [comment]
Well, for example, for prayer apps we need to play prayer sound not the normal notifications app and for reminders app of national day we need to play the national anthem sound not the default notification app

If other apps are having this feature this Microsoft must have it :) 

because we move from better to **Best**

**Comment by jwargo** [comment]
Removed the `bug` label as the product is working as expected. This is more of a feature request.

**Comment by RioFiveJack** [comment]
i'll need this also, if we can use channel for Android, i can separate notification channel and sound for important / less important notification for my apps.

**Comment by kevinjpetersen** [comment]
+1

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
