### ISSUE TITLE
Add Data - API to Cordova SDK

### ISSUE THREAD

**Issue by PhilippRoessner** [microsoft/appcenter#549]
I'd like to use the App Center features, especially the Sync functionality inside a cordova app.

I looked at Xamarin but HTML and Typescript is just my preferred platform.

**Comment by Zakeelm** [comment]
Hey there! 

While we don't currently have immediate plans to support Cordova, it's something we can definitely look into. I'll keep this open for a while in case others are interested in this. 

The next platform on our roadmap for Data is React Native, which may be able to fulfill that requirement of yours!

**Comment by jjgriff93** [comment]
Very interested in this - likewise features like sync and auth would be immensely useful for Cordova

**Comment by Zakeelm** [comment]
We don't have immediate plans to support Cordova, so i'm going to close this for now. But this is something we can definitely revisit given enough interest.
