### ISSUE TITLE
AppCenter losing all the new line information in release notes from hockeyapp. 

### ISSUE THREAD

**Issue by abhilonline** [microsoft/appcenter#550]
**Describe the bug**
AppCenter losing all the new line formatting  in release notes from hockeyapp. The release notes is not easier to read as a result.

**To Reproduce**
1. Go to 'Releases'
2. Click on 'Release number'
3. Look at the release notes

**Expected behavior**
The new line in hockeyapp release notes has to be preserved while showing in App center UI.

**Screenshots**

**Comment by derpixeldan** [comment]
Please reach out to us in support so we can have a closer look.
