### ISSUE TITLE
Not able to register a particular User device

### ISSUE THREAD

**Issue by shamprasadrh** [microsoft/appcenter#551]
**What App Center service does this affect?**
App center device registration

**Describe the bug**
The device shows as UNPROVISIONED and after registering the device we get confirmation for successful registration but not user is not able to download the app on device and test it.

**To Reproduce**
1. Go to 'Distribute'
2. Click on 'Collaborators'
3. Scroll down to 'Devices'
4. And register the UNPROVISIONED device

**Expected behavior**
The device should show as provisioned and allow user the download the app and test it. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: [ iOS12.2]

**Comment by botatoes** [comment]
Can you go to appcenter.ms and create a support ticket for this? It will give us more details to help troubleshoot.
