### ISSUE TITLE
Android push notifications

### ISSUE THREAD

**Issue by engin2018** [microsoft/appcenter#552]
**What App Center service does this affect?**
Push notifications

**Describe the bug**
We successfully receive push notifications to our cross platform Xamarin ios and android devices however using your apis we only receive them on ios and not on android.  

**To Reproduce**
Using the api

https://api.appcenter.ms/v0.1/apps/myorderbox/driverapp/push/notifications

Please see image below

**Expected behavior**
The Android device to receive the push notification using your api

**Screenshots**
![image](https://user-images.githubusercontent.com/37217708/59345260-abe96d00-8d07-11e9-8a42-c42427811c13.png)

X-API-TOKEN also included but removed from image

Body contents

{
    "notification_target": {
        "type": "devices_target",
        "devices": [
            "********************************************"
        ]
    },
    "notification_content": {
        "name": "Delivery Group id 3018",
        "title": "Delivery Group",
        "body": "{'delivery_groups': [1189]}"
    }
}

Device token removed from example above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Samsung A5
 - OS: Android 8.0.0.0
 - Browser Chrome
 - Version 75.0.3770.67

**Additional context**

**Comment by jwargo** [comment]
@engin2018 have you worked through this issue with our support team? There are several issues that could affect this.  For example, is the app running when you send the notification? How are you getting the device token you're using? What are you seeing in the logs, etc.

**Comment by engin2018** [comment]
Thanks for your response. We've now resolved the issue.
Kind regards Engin
