### ISSUE TITLE
Validate device token

### ISSUE THREAD

**Issue by swigrid** [microsoft/appcenter#553]
I would use API Endpoint for device token validation to make sure device token is valid. If not I would remove it from our database.

**Comment by patniko** [comment]
Do you mind elaborating on this a bit more @swigrid?

**Comment by swigrid** [comment]
here is an example

when there is one invalid token as below

{
	"notification_target": {
		"type": "devices_target",
		"devices": [
			"0f1ea4a3-caee-4980-8de2-91908e8fe32b",
			"aaaa"
		]
	},
	"notification_content": {
		"name": "Delivery Group id 81",
		"title": "Delivery Group",
		"body": "aaaaa"
	}
}


we’re getting response
{
  "error": {
    "code": 400,
    "message": "body parameter is invalid or empty."
  }
}

Which is not correct, body has valid string. Is push delivered to other valid tokens?

Regards
Roman

**Comment by swigrid** [comment]
in other words, from time to time can happen, there is an invalid token saved from whatever reason. We would like to clear those tokens

**Comment by patniko** [comment]
Makes sense! Thanks for the clarity. We'll take a look on our side.

**Comment by jwargo** [comment]
@swigrid I'm checking to see if we can provide a better error message for this.

**Comment by jwargo** [comment]
@swigrid how would you use this?  Validate each token before any send events, or a scheduled task you run periodically validating all the tokens?  Would this be a per token API call, or would you send in batches?

**Comment by swigrid** [comment]
I am not sure yet. I just wanted to get rid of invalid tokens. Since this feature haven’t been available I haven’t really thought about logic. But if there was an array response with statuses after push was sent, this way we could remove those invalid ones. Just a thought perhaps.

**Comment by jwargo** [comment]
@swigrid OK, thanks for that feedback, that makes sense. I'll track this and see what other customers have to say about this one as well.

**Comment by jwargo** [comment]
@swigrid would you be willing to have an email or voice conversation to talk about your push needs beyond this feature? I don't see your email associated with this profile, mine is, so you can email me directly.

**Comment by swigrid** [comment]
I’m sorry, I forgot to reply to this one.

I could have spare few minutes tomorrow in the morning London time.

but in the mean time…
how would suggest deal with given scenario:

User logs in one device, there is one token registered
User logs in in second device, there is another token registered

user will receive push on both devices

User uninstalls app on first device, token is left on the device (developers claiming, there is no callback when uninstalling app, to remove token from backend server)
user installs app again later, and we have 3 tokens in DB and one of the token is for uninstalled app.

how can we get rid of this token?

Regards,
Roman

**Comment by jwargo** [comment]
@swigrid the token will be deleted automatically on our side, but I understand your need to validate it on your server side. What I'm proposing to engineering is that when you check push status, we return a list of invalid tokens. this works, I think, because we get that back from the PNS, so we'll know those tokens are bad. 

Regarding a chat, can you email me using the email address on my GitHub account so we can arrange a time and I can send an invite?

**Comment by swigrid** [comment]
That’s good, this way we can clean up our tokens.

Thanks

Roman

**Comment by swigrid** [comment]
regarding email, this what I have

**Comment by jwargo** [comment]
If you click on my name, it should show my email address. it's firstname dot lastname at Microsoft.

**Comment by jwargo** [comment]
@swigrid Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
