### ISSUE TITLE
CLI getting 500 (Internal Server error) after renaming app

### ISSUE THREAD

**Issue by skadecl** [microsoft/appcenter#558]
**What App Center service does this affect?**
Code-push

**Describe the bug**
After realizing two of my apps were misnamed, I renamed them using the CLI. After that, I am getting a **500 Internal Server Error** response for anything I try to do with those two apps.

Also, both deployments (Staging and Production) disappeared.
Everything is working fine for the rest of my apps.

**To Reproduce**
1. Rename an app using the CLI
2. Try anything on that app (exmaple: code-push deployment ls APP_NAME)
4. See error (500)

**Expected behavior**
The app should keep working normally after being renamed

**Screenshots**
![image](https://user-images.githubusercontent.com/978101/59453224-6f884080-8ddd-11e9-841c-36fb85a73c10.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser:  I was using the console.
 - Version N/A

**Comment by owenniblock** [comment]
@skadecl - please could you rerun the command with `code-push deployment ls Ticketplus/eventbrain.netlink.fitran.ios --debug` and post the results here? This should help us identify which API call is returning a 500 error.

Also, you can check what value we have for the `APP_NAME` in the system by going to the appcenter.ms portal, finding the app, going to the Test section and running through the `New Test Run` screens. At the end of the process it will give you an example test run command which includes the `APP_NAME` - it would be interesting to see what this returns.

**Comment by jmazier-j2d** [comment]
Running into a very similar issue after renaming both my Android & iOs app (was named the same, causing clash in names), I'm running this command to release my codepush
`code-push realease-react <AppName> android`
I can't figure how to run it with --debug option, could you please tell me more about it ?
The weirdest is that I can still access my app with the "old name".. :(
