### ISSUE TITLE
Unable to create new release

### ISSUE THREAD

**Issue by iamnotaturtle** [microsoft/appcenter#559]
**What App Center service does this affect?**
appcenter.ms

**Describe the bug**
When selecting `New Release` I am redirected to the url below (replace `username` and `app`):
>https://appcenter.ms/users/username/apps/app/distribute/distribution-groups/new-release?parent=2

**To Reproduce**
1. Select your app
1. Select `Distribute` on left hand pane
1. Select blue `New Release` button
1. Observe blank screen

**Expected behavior**
Popup from left hand side to prompt me to upload the ipa/apk should show up

**Screenshots**
![blank](https://user-images.githubusercontent.com/6349311/59453764-95faab80-8dde-11e9-8323-b070589382d9.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Browser Chrome
 - Version 74

**Additional context**
I was able to submit a release earlier today
Navigating back with the browser back button still keeps that blank page present

**Comment by derpixeldan** [comment]
The issue was mitigated in the meantime. Thank you for reporting.
