### ISSUE TITLE
Support running Appium for Cordova based applications

### ISSUE THREAD

**Issue by galsc** [microsoft/appcenter#56]
**Describe the solution you'd like**
Support Cordova based apps to run Appium.
Currently this feature is not supported.

**Comment by joemellin** [comment]
Hello @galsc! Thanks for posting this feature request. We will keep this issue open to track further interest in providing this feature.  For other users, please upvote the initial message with a 👍 if you would like this feature as well.

**Comment by Oddj0b** [comment]
@galsc What is missing from our current Appium implementation for it to support Cordova apps?

**Comment by Oddj0b** [comment]
I'm the program manager responsible for App Center Test and I'm working on a new idea which will support more frameworks in Test, allow unit testing, and browser testing. I would like to talk to you about it and understand your needs better.

Below is a link where you can sign-up for a 30-minute call with me. The agenda will be about the value of testing for you and your organization, and my new idea to allow more frameworks and testing styles in App Center Test.

Link to choose https://calendly.com/vigimm/appcenter-test

**Comment by Oddj0b** [comment]
@galsc I would like to understand what is the blocker for you to run Cordova apps in App Center Test?

**Comment by galsc** [comment]
@Oddj0b - our project is based on Angular and wrapped as Cordova application which allows us to deploy our Angular app to the Appstore & Google Play Store.

We would really like to be able to use Protractor for writing end to end tests and run the tests using Appium on App Center.

As far as I know you only currently support native apps and not hybrid apps (Angilar + Cordova) to use Appium.

Please let me know if you have any questions.

Thanks

**Comment by Oddj0b** [comment]
@galsc You should be able to run vanilla Appium tests on Cordova apps, it's a change me made in the last month or so. However, it's not possible to use Protractor. Can I change the name to support Protractor instead?
