### ISSUE TITLE
Support for building iOS app with Swift Package Manager

### ISSUE THREAD

**Issue by WarSunsOfPeace** [microsoft/appcenter#560]
With Apple announcing support for Swift Package Manager for iOS in the next release of Xcode, I would like to see this support added here as well.

**Comment by lumaxis** [comment]
@w0mba7 What exactly are you looking for? App Center's SDKs being available through Swift Package Manager?

**Comment by w0mba7** [comment]
I was just actually looking to be able to build an iOS project using Swift Package Manage to pull in dependencies, the feature added in Xcode 11.  Support for being able to add the SDK using SPM would be nice as well.

**Comment by nrajpurkar** [comment]
@w0mba7, we're taking a look at adding this support for Build. Does that sound like what you are looking for?

**Comment by w0mba7** [comment]
yup, thanks.

**Comment by tkm-hc-suhas** [comment]
<img width="400" alt="1" src="https://user-images.githubusercontent.com/52993441/61360467-1e67e280-a89c-11e9-9776-ee8b0522e616.png">

Current error.

**Comment by egfconnor** [comment]
Has there been any work on this?

**Comment by nrajpurkar** [comment]
Hi @egfconnor, this hasn't been added in yet.

**Comment by DennisPan** [comment]
@w0mba7 are you seeing errors building an iOS app with swift packages using App Center? If so, could you show me the error? Would be the best to have a sample project that reproduces the issue. From our testing, it resolves the dependencies correctly and built successfully. 

For all that follows along the Issue, I'm scoping this down to supporting iOS app with swift packages in *Build* service. If you are looking for support of adding App Center SDK through Swift Package Manager, they are tracked in #1168 and #1295

**Comment by christianhuck** [comment]
@DennisPan I'm facing the same issue trying to **build** an Xcode project on app center which relies on a local (same git repo) swift package. The error I'm getting is the following:


```/usr/bin/xcodebuild -workspace /Users/runner/runners/2.160.1/work/1/s/my.xcodeproj/project.xcworkspace -scheme staging archive -archivePath /Users/runner/runners/2.160.1/work/1/output/build/archive/my CODE_SIGN_STYLE=Manual
User defaults from command line:
    IDEArchivePathOverride = /Users/runner/runners/2.160.1/work/1/output/build/archive/my

Build settings from command line:
    CODE_SIGN_STYLE = Manual

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: Missing package product 'MyLocalSwiftPackage'

** ARCHIVE FAILED **

##[error]Error: /usr/bin/xcodebuild failed with return code: 65```


What I tried is following Apples [SPM CI Article](https://developer.apple.com/documentation/swift_packages/building_apps_that_use_swift_packages_in_continuous_integration_workflows) resulting in the following post-clone script:

```
#!/usr/bin/env bash

git submodule update --init --recursive; 
xcodebuild -resolvePackageDependencies -forceResolvedPackageVersions
``

which is not working unfortunately. Is there any way to pass xcbuild arguments directly via the configuration? If that is not the case what could be another approach to make that work?

**Comment by tapwork** [comment]
I am trying to build the Swift-Package directly in the Appcenter Build pipeline. 
Appcenter detects the package workspace (probably in the `.swiftpm` folder) but does not find the shared scheme that includes the test target.
<img width="579" alt="Screenshot 2019-12-18 at 09 03 28" src="https://user-images.githubusercontent.com/397342/71067738-5ccc3b00-2175-11ea-9970-1aa94e31a333.png">
<img width="681" alt="Screenshot 2019-12-18 at 09 05 04" src="https://user-images.githubusercontent.com/397342/71067893-b3397980-2175-11ea-8bd5-c1abbd3923f9.png">

Did you consider supporting SwiftPM directly (without any real Xcode project)? There is this hidden Xcode workspace in `.swiftpm`  though

**Comment by DennisPan** [comment]
@christianhuck Regarding the question

>which is not working unfortunately. Is there any way to pass xcbuild arguments directly via the configuration?

That's not configurable at the moment.

@tapwork No immediate plan on supporting building Swift package at the moment. Feel free to submit a new feature request (I don't recall we have one tracking that)

**Comment by tapwork** [comment]
@DennisPan that's a pity! The community is currently switching to Swift PM . Preferred over CocoaPods and Carthage. 
I totally like the nice and clean App Center interface. But due to the lack of real a CLI and missing Swift package support it is not usable for real projects right now.

**Comment by DennisPan** [comment]
@tapwork To clarify, we do support build iOS app using Swift packages. Just don't support building the packages only.

**Comment by Bendetta** [comment]
I'm unable to build my app that has a Swift Package. The cocoapods packages get pulled in fine, but during the build I get
```
Resolve Package Graph
Fetching git@github.com:dmytro-anokhin/url-image.git

xcodebuild: error: Could not resolve package dependencies:
  The server SSH fingerprint failed to verify.

##[error]Error: /usr/bin/xcodebuild failed with return code: 74
```

**Comment by DennisPan** [comment]
@Bendetta could you see if the suggestion here works for you? https://stackoverflow.com/questions/58125659/github-actions-xcodebuild-fails-due-to-server-fingerprint

**Comment by christianhuck** [comment]
For anyone using an Azure DevOps Repo with temporary tokens instead of SSH, following this worked for me: 

https://confluence.atlassian.com/fisheye/permanent-authentication-for-git-repositories-over-http-s-960155789.html

**Comment by i-schuetz** [comment]
I'm not sure I understand this issue, the problem is that if the project uses SPM as dependency manager it will not pull dependencies, i.e. will not be buildable in app center?

From what I can see in the [docs](https://docs.microsoft.com/en-us/appcenter/build/ios/first-build#38-cocoapods) it only work CocoaPods, is this correct?

**Comment by RiviElfNeura** [comment]
@DennisPan  Hi, i'm also trying to compile ios app using spm in app center, and the build failed (swift compile generation...)

**Comment by DennisPan** [comment]
@RiviElfNeura Sorry for late response. Could you reach out to support about the build failure?

**Comment by rjhaveri1** [comment]
I have a similar issue building my app in AC using PM to bring in the Facebook SDK - getting this error: 
`xcodebuild: error: Could not resolve package dependencies: because no versions of facebook-ios-sdk match the requirement 7.0.2..<8.0.0 and root depends on facebook-ios-sdk 7.0.2..<8.0.0, version solving failed.`

It seems that this should be supported by AC, but not sure how to solve this problem.  Anything I should try?

**Comment by NannaML** [comment]
> I have a similar issue building my app in AC using PM to bring in the Facebook SDK - getting this error:
> `xcodebuild: error: Could not resolve package dependencies: because no versions of facebook-ios-sdk match the requirement 7.0.2..<8.0.0 and root depends on facebook-ios-sdk 7.0.2..<8.0.0, version solving failed.`
> 
> It seems that this should be supported by AC, but not sure how to solve this problem. Anything I should try?

Have anyone found a solution? I have the same error

**Comment by AntonioCarrascoGBM** [comment]
@DennisPan I have a similar issue building my app in **appcenter** using Swift Package Manager from private repository, getting this error:
`xcodebuild: error: Could not resolve package dependencies:`
`  Authentication failed because no credentials were provided.`
`##[error]Error: /usr/bin/xcodebuild failed with return code: 74`
Any suggestion! my CI process is stopped

**Comment by ptsiogas** [comment]
We have the issue. We have a swift package in private Github repository A and a project-iOS app in a Github repository B that uses the Swift package at repository A.
When trying to build the project-iOS app at App Center we get an authentication error.

`xcodebuild: error: Could not resolve package dependencies:
  The server SSH fingerprint failed to verify.`
  
  We have contacted the App center's support without any answer yet. 
  Can you provide detailed steps to resolve this issue?

**Comment by anfriis** [comment]
@AntonioCarrascoGBM @ptsiogas 
I had the same issue but found a solution based on these posts:
https://discuss.bitrise.io/t/spm-gitlab-the-server-ssh-fingerprint-failed-to-verify/15592/3
https://github.com/microsoft/appcenter/issues/237#issuecomment-527991036
#237 

Add the following to the `appcenter-post-clone.sh` file (this example is for Bitbucket but should work for GitHub as well):

```
# Add Bitbucket fingerprint to known_hosts
mkdir -p ~/.ssh

# Find Bitbucket IP's for adding to App Center's ssh known hosts: https://discuss.bitrise.io/t/xcode-11-resolving-packages-fails-with-ssh-fingerprint/10388/2
# To avoid this error: 
#   xcodebuild: error: Could not resolve package dependencies: 
#   The server SSH fingerprint failed to verify.
echo "Adding bitbucket to ssh known hosts"
for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts

# Print out ssh known hosts for debugging
echo "Known hosts:"
cat ~/.ssh/known_hosts

# Add Bitbucket ssh key
echo "Adding bitbucket SSH key:"
echo $SSH_KEY | base64 -D > ~/.ssh/bitbucket-ssh
chmod 600 ~/.ssh/bitbucket-ssh
ssh-add ~/.ssh/bitbucket-ssh
```

Generate a base64 formatted SSH key like this:
```base64 -i ~/.ssh/my_private_key | pbcopy```

Add the SSH key to App Center -> Build Settings -> Environment Variables:
`SSH_KEY` = {key}

**Comment by ptsiogas** [comment]
> @ptsiogas
> 
> we have same issue, do you found any solution ?
> 
> if not, can this one be re opened ?

@MaxenceMax no we did not found a workaround. We switched to private Cocoa pod libraries.

**Comment by MaxenceMax** [comment]
@ptsiogas 

I've just found a solution. we have SP in a private gitlab repo, so I added a read-only token access in those repos and added them like that in SPM :

``https://<TokenName>:<Token>@gitlab.private.com/url/to/repo.git```

Of course our app repo is private so the token is safe.

**Comment by jonas-simkus-mw** [comment]
@MaxenceMax 
Where did you save such URL?
Does not seem Xcode Package Dependency GUI would allow you to set such URL.

Is there a way to use `git@github.com:dmytro-anokhin/url-image.git` type URLs instead of `https://github.com/dmytro-anokhin/url-image.git` in **Xcode 13** ?

**Comment by dlargen33** [comment]
I am having the same issue; private repo in GitLab that contains our Swift Package.  I am getting no errors in the logs, just times out.   I don't see away to provide a url in the form of https://<TokenName>:<Token>@gitlab.private.com/url/to/repo.git with in Xcode 13.  

Has anyone found a solution?

**Comment by MinaAshna** [comment]
I am facing the same issue here using Xcode 13.3

**Comment by interhub** [comment]
Same problem !

**Comment by lucasecf** [comment]
Anyone else having problems with AppCenter's Xcode 13.3.1+ and SPM?

If I use Xcode 13.2.1 the build works fine and all SPM dependencies are properly downloaded and installed
But if selecting newer Xcode versions, the build always gets stuck forever while downloading a random dependency, until it timeouts after 1h and fails  .

![Screenshot 2022-06-24 at 14 58 50](https://user-images.githubusercontent.com/1894401/175893190-c047dc0c-a5e3-45b7-bb15-e331afbfd8e3.png)

Any workarounds for this? AppCenter support basically said they cannot do anything because "SPM is not officially supported" 😓

**Comment by sidneivl** [comment]
I'm facing a problem with publickey using a private repository.

```
xcodebuild: error: Could not resolve package dependencies:
  Failed to clone repository git@github.com:Infoglobo/ui-globo-apps.git:
    Cloning into bare repository '/Users/runner/Library/Developer/Xcode/DerivedData/app-globo-mais-one-ios-fahhdoxaguehuoejpaevgcrhkaty/SourcePackages/repositories/ui-globo-apps-a8107c52'...
    git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.

Skipping cache due to an error: Failed to clone repository git@github.com:Infoglobo/ui-globo-apps.git:
    Cloning into bare repository '/Users/runner/Library/Caches/org.swift.swiftpm/repositories/ui-globo-apps-a8107c52'...
    git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.

```

How can I add a publickey to use it in appcenter?

Regards
