### ISSUE TITLE
Integration with Shields.io

### ISSUE THREAD

**Issue by rnystrom** [microsoft/appcenter#561]
[Shields.io](https://shields.io/) is a clever way to generate project "shields" (build status, code coverage, etc). I was browsing it today to see if there was an App Center config. It's probably not the highest-impact feature to add, but it would be nice to see App Center listed along with other major CIs.

The project is [community-run on GitHub](https://github.com/badges/shields), so adding an App Center badge might not be that difficult.

Just a thought!

**Comment by patniko** [comment]
Thanks for the feedback @rnystrom. I'll check it out.
