### ISSUE TITLE
Prioritize install link over QR code for non-mobile OSes

### ISSUE THREAD

**Issue by davisjms** [microsoft/appcenter#564]
While trying to install an app, the QR code takes up center stage even for apps on macOS. The link to install is a bit hard to notice and I need to search for it in the UI. It would be worth giving more priority to the link for such apps - may be in the form of an Install button.

**Comment by derpixeldan** [comment]
@davisjms thanks for your feedback. This will be improved as part of "Integrate install page with developer portal" which is on the [Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#hockeyapp).

**Comment by witaly-iwanow** [comment]
This whole QR thing is very annoying. I'm on macOS trying to download macOS app (or Win/Win), what's exactly the point of "Scan the code with you device camera..."? Even if I'm on Linux downloading Win app the QR code scan scenario is very very unlikely. Did you ever try to scan a QR code from a laptop/desktop screen with a built-in camera of your other laptop? This is just plain ridiculous
