### ISSUE TITLE
Set a better App name in the API URL

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#566]
Hi,

Currently if I create an iOS app called Wahoo the name in the URL when using CLI/API will be Wahoo and if add Android then the name will be Wahoo-1 then Wahoo-2, etc

This numbering doesn't make sense and it's confusing so user needs to go and check what's 1 and 2 in case of troubleshooting

I suggest you set a better, something like this:

/Wahoo-ios/
/Wahoo-android/
/Wahoo-UWP/

**Comment by lumaxis** [comment]
@jrahma As a workaround, you can change the URL name of an app through our API or [CLI](https://github.com/microsoft/appcenter-cli): `appcenter apps update --app jrahma/Wahoo-1 --name 'Wahoo-iOS'`

**Comment by blparr** [comment]
Thanks for the feedback @jrahma , hopefully Lukas' workaround above helped. We will consider your suggestion for future improvements.
