### ISSUE TITLE
API doesn't return the app created by API

### ISSUE THREAD

**Issue by dtropanets** [microsoft/appcenter#567]
The issue is with the API. I'm investigating migration to App Center from HockeyApp, where our team is creating an app per branch. But we've encountered an issue that apps created by new API are not returned by apps endpoint.

1. Create an app using POST /v0.1/apps endpoint
2. Ensure that https://appcenter.ms/users/~/applications displays the app on UI
3. Get list of apps using GET /v0.1/apps endpoint
4. The app is missing from the list

The issue may be cause by the amount of apps we have in App Center. Since we create an app per branch, we have a lot of apps created. Hockeyapp currently shows that we have ~3000 apps, but AppCenter API returns only ~1300. This may be the cause of the issue, because on couple of tests, the app was successfully created and returned, but mostly it's missing from returned apps list.

**Comment by derpixeldan** [comment]
Please reach out to our support in App Center so we can better investigate the problem. You can refer to this ticket.

**Comment by blparr** [comment]
Closing this issue as it will be handled by support. Thanks!
