### ISSUE TITLE
Uploading Output of External Build

### ISSUE THREAD

**Issue by aolszowka** [microsoft/appcenter#568]
**Describe the solution you'd like**
We're currently using HockeyApp and we're looking for a way to transition to AppCenter. However I am having a hard time finding a direct replacement for the Upload Version API (https://support.hockeyapp.net/kb/api/api-versions#upload-version)

**Describe alternatives you've considered**
It looks like at least one other user might have been asking for something similar (at least I assume it was similar): #419 

This API might be what I want; but it is not clear if it really will allow me to upload an IPA/APK for distribution. Can the documentation be improved to indicate that this is the intended replacement for the existing HockeyApp API? https://openapi.appcenter.ms/#/distribute/releaseUploads_create

**Additional context**
It might help to understand how our process works: Right now we have an in house build system that produces our binaries and then uses HockeyApp only to provide a distribution mechanism to our developers.

While the features of AppCenter look like they aim to replace our CI System internally we do not have anything on the horizon planned to make a transition (but would be interested in kicking tires). We have seen many Microsoft DevOps products come and go and have had better luck rolling our own and then switching as needed (for example we came to HockeyApp from TestFairy).

**Comment by derpixeldan** [comment]
@aolszowka sorry for the delay. We're aware that the App Center API isn't ideal. How to use it is documented [here](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#uploading-using-the-apis). Please let me know if that helps. We're currently also exploring options to use a similar API design HockeyApp has for App Center.

**Comment by aolszowka** [comment]
If I understood the linked documents correctly the single upload API has been replaced with 3 APIs? Is that really the case?

**Comment by derpixeldan** [comment]
@aolszowka yes.

**Comment by aolszowka** [comment]
I am sorry to reopen this but reading the Documentation Here: https://docs.microsoft.com/en-us/appcenter/transition/api#upload-api it appears like this API will:

> Uploading a version via POST /api/2/apps/APP_ID/app_versions/upload will still work after you moved your app.

@derpixeldan Is this new? If so how long is this API Available to us? Long term we'll invest in converting to the 3 API's (if needed) but if this will work in the medium term we'll look more towards investing in other ares of the product.

**Comment by aolszowka** [comment]
@derpixeldan Just checking in; we've converted our apps to App Center utilizing the old Upload API and it appears to work. Are we living on borrowed time?
