### ISSUE TITLE
Push Notifications not working to device Id list

### ISSUE THREAD

**Issue by RaymondBull** [microsoft/appcenter#569]
App Center Push

When using the App Center API, Portal, or Postman, pushing a notification to a device list shows status 202 Accepted but the portal shows 0/0 sent and I never receive the notification. Broadcasting to all devices works just fine.

**Smartphone (please complete the following information):**
 - Device: iPhoneXS
 - OS: 12.3.1

![PostmanResults](https://user-images.githubusercontent.com/36246261/59554200-f3206980-8f64-11e9-8ea1-54b81afe163a.jpg)
![PortalResults](https://user-images.githubusercontent.com/36246261/59554203-f7e51d80-8f64-11e9-9800-f4ae2a5c220a.jpg)

**Comment by mpodwysocki** [comment]
@RaymondBull We'd like to know some more information.  Can you please open a support ticket via the AppCenter website?  It's the little blue chat icon which leads to Intercom.  There, our team can help you diagnose the problem.

**Comment by RaymondBull** [comment]
I started a conversation on there. It says that App Center will be back tomorrow.

**Comment by mpodwysocki** [comment]
@RaymondBull Great, thank you! We will get back to you as soon as possible!  The best way to reach our team is by Intercom.  Can we close this issue and move it to Intercom?

**Comment by adrianknight89** [comment]
@mpodwysocki @guperrot @jwargo @botatoes

Guys, there are several related issues with respect to push notifications not working. This is a major roadblock for us as we cannot release an app without push. It'd be great if you can prioritize this work.

#551 #552 #505 #506 #537

**Comment by adrianknight89** [comment]
Thanks, Raymond. If your issue if resolved, you may want to close it. The other issues are still present. As mentioned in #552, I can't send anything to Android. `setUserId` in #505 doesn't seem to be working well either.
