### ISSUE TITLE
AppCenter building stopped working

### ISSUE THREAD

**Issue by mondagoar** [microsoft/appcenter#576]
Recently (Sat 15th Jun 19), our iOS app building stopped working and now produces this error in the log (below).

Did something change on the AppCenter on this date? In case it's relevant, we don't use a YML file in our build.

-----

(lldb) detach
Process 818 detached
(lldb) quit
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
##[error]Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/5_18_2/bin/msbuild failed with return code: null. For guidance on setting up the build definition, see https://go.microsoft.com/fwlink/?LinkId=760847.

**Comment by DennisPan** [comment]
@mondagoar We update the images about weekly but it's hard to tell if your build failed because of that. If you can follow up with App Center support, that'll allow us to dig deeper. Closing this.
