### ISSUE TITLE
Building from a project (for iOS) doesn't appear to use compiler directives from child projects

### ISSUE THREAD

**Issue by mondagoar** [microsoft/appcenter#577]
We are building using AppCenter an iOS project (.csproj) and it uses other projects as references. We select the correct build "Configuration" but it's not obeying the compiler directives in child projects. 
We had recently been building using a solution (.sln) file instead (this did obey directives) but this has recently (three days ago) stopped working with no changes from us, so we're now trying to build from a project instead.

**Comment by DennisPan** [comment]
@mondagoar Could you provide more details on what stopped working for building with solution? We may need you to reach out to support to take a deeper look at your build

**Comment by mondagoar** [comment]
Thanks for the reply. I reported the problem with the "solution" separately, but you closed it. See here: https://github.com/microsoft/appcenter/issues/576

I raised this issue because we're having problems building from a project now (which we're using instead). We have one master project (Xamarin / iOS) and it references another library project. The library project has compilation directives but the build doesn't seem to recognize them, despite us using the correct "Configuration".

**Comment by mondagoar** [comment]
I closed the issue in error.

**Comment by DennisPan** [comment]
Ah got it. Thanks for the clarification. Please follow up with support as I suggested regarding the "solution" problem. As for the issue with building the "project", could you mention it in the same support ticket? I'd like to have better idea about specifics. Or feel free to describe here if that works for you.

**Comment by mondagoar** [comment]
Please could you guide me a little more about what specifics you need. I don't really know what information is relevant (and don't really want to inadvertently post private data).

**Comment by DennisPan** [comment]
Let's go through Support in this case then. If we find something that will be helpful to others, we can post an update here to share the findings.

**Comment by mondagoar** [comment]
Ok. Thanks. Should I give you access to our build? Or how else can I help provide information?

**Comment by DennisPan** [comment]
Once you reach out to Support (from the portal), in the conversation, you can provide the link to the failed build, and probably the link to the last successful build for comparison

**Comment by stephan-markovic** [comment]
Moved to CSS
