### ISSUE TITLE
Ability to share environment variable configurations across multiple projects

### ISSUE THREAD

**Issue by yoshikischmitz** [microsoft/appcenter#580]
**Describe the solution you'd like**
We maintain an iOS and Android branches of our react-native projects, and they have a fair number of shared configurations. I think it'd be handy if we could create environment variable configurations and share them across projects, allowing for project specific overrides, perhaps through some "stacking" and overwriting mechanism.

**Describe alternatives you've considered**
Having less env vars :)

**Comment by nrajpurkar** [comment]
Thanks for the feature request @yoshikischmitz. We did recently ship the ability to [clone](https://docs.microsoft.com/en-us/appcenter/build/branches#cloning-build-configurations) your build configuration including your environment variables. This doesn't however keep your variable values in sync which may be one of your goals here.

**Comment by yoshikischmitz** [comment]
Hi @nrajpurkar I did notice the cloning feature recently, in my case this definitely addresses one big part of the pain point, so was happy to see that. I haven't had an immediate use case for syncing, as the only environment variables I store are URLs and tokens, that all are by their nature fairly long lived.

**Comment by dgobaud** [comment]
really need this one too

**Comment by ArkadiGiniApps** [comment]
you ppl are insane, this a real issue for real ppl that use your product and instead of solving it you have your bot close the issue.....
