### ISSUE TITLE
Documentation for manual linking of appcenter-push (Native+React-native)

### ISSUE THREAD

**Issue by frags51** [microsoft/appcenter#582]
**Describe the solution you'd like**
I'd like a clear documentation on how to link appcenter-push in the react-native part of my Android app, which has both native and react-native code. 

My project structure is like this: 
root/ : settings.gradle, gradlew etc.
root/P1/ : Native code, and also React-instance managers for the react-native part.
root/rn/ : the react-native module.  

I have tried to find the files which are modified by react-native link, but I am not really sure which directory should those changes be made to: P1 or rn.

**Comment by jwargo** [comment]
@frags51 I'll see what we can do.

**Comment by jwargo** [comment]
@frags51 engineering is pushing through a docs update now that shows how to manually link the SDK. This is at the SDK level right now, but I'll see if I can get it updated for Push as well.

**Comment by frags51** [comment]
Good work! Wish you will do that. I feel it will enable higher adoption of AppCenter!

**Comment by jwargo** [comment]
@frags51 Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
