### ISSUE TITLE
Cannot Upload IPA Files Anymore

### ISSUE THREAD

**Issue by LGE-AUGMENSYS** [microsoft/appcenter#583]
**What App Center service does this affect?**
AppCenter -> 'Distribute'

**Describe the bug**
After uploading an IPA file (a Xamarin iOS app) to the app center, the page stays at 'Upload a build' even though the progress bar has run to the end. Cannot proceed to the next step.

**To Reproduce**
1. Go to AppCenter -> 'Distribute'
2. Select a group
3. Click 'New release'
4. Drag & drop an IPA file below 'Upload a build'
5. See bug description

**Expected behavior**
The upload should be finished once the progress bar runs to the end and the 'Next' button should become available.

**Screenshots**
![app_center_ipa_upload_stuck](https://user-images.githubusercontent.com/51995996/59761544-67c11400-9295-11e9-98aa-01c49ef03b64.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Version 1903 OS build 18362.175
 - Browser: Edge Insider Version 76.0.182.6 (Official build) dev (64-bit), also Opera Version 60.0.3255.170

**Additional context**
The same files could be uploaded without problems last week, but not anymore now.

**Comment by derpixeldan** [comment]
We have an ongoing incident affecting uploading iOS builds. Please follow our status page for any updates https://status.appcenter.ms/

**Comment by LGE-AUGMENSYS** [comment]
Thanks for the quick response.

**Comment by Shakya-Ruhunage** [comment]
Hi,
 I am experiencing this issue again today.
