### ISSUE TITLE
Appcenter (cli) distribute release fails with HTTP 500 for iOS app / CORS?

### ISSUE THREAD

**Issue by Frostregen** [microsoft/appcenter#584]
The corresponding android app just works fine.
Yesterday it was still working fine with appcenter-cli. Uploading the same .ipa (the one which worked yesterday) again manually through the website will just hang forever with the upload bar at 100%.
Checking the browser console shows a suspicious CORS line:

(sorry for the german)
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://rink.hockeyapp.net/api/sonoma/apps/1ec52d99-9e13-45a8-a477-b6d87270e326/app_versions/upload?upload_id=910240a0-74bb-0137-81d1-061f30a48c6e. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

"Reason: CORS-Header 'Access-Control-Allow-Origin' missing"

Any idea why this happens for one project (iOS) but not for another (android) of the same organization?

**Comment by derpixeldan** [comment]
We have an ongoing incident affecting uploading iOS builds. Please follow our status page for any updates https://status.appcenter.ms/

**Comment by derpixeldan** [comment]
Resolved.
