### ISSUE TITLE
Previously working AppCenter / iOS project stopped building

### ISSUE THREAD

**Issue by mondagoar** [microsoft/appcenter#588]
A previously working iOS project has stopped building. Below is an extract from the log. Sorry, I don't know what other information you going to need. Did something change recently (today)?

File upload succeed.
Upload '/Users/vsts/agent/2.153.2/work/1/a/symbols' to file container: '#/791889/symbols'
Associated artifact 144 with build 101
##[section]Async Command End: Upload Artifact
##[section]Finishing: Publish symbols
##[section]Starting: Create distribution
==============================================================================
Task         : App Center distribute
Description  : Distribute app builds to testers and users via Visual Studio App Center
Version      : 3.154.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
==============================================================================
##[error]"<!DOCTYPE html>\n<html lang='en' class=\"full_height\">\n  <head>\n    <meta charset='utf-8'>\n    <title>Server Error</title>\n    <meta content=\"authenticity_token\" name=\"csrf-param\" />\n    <link href=\"/assets/application-default.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\n    <link href='/favicon.ico' rel='shortcut icon'>\n  </head>\n  <body class='full_height'>\n    <div class='container-fluid full-height full-width'>\n      <div class='row-dialog'>\n        <div class='centered-vertical'>\n          <div class='centered-horizontal'>\n            <div class='well'>\n              <h3>Ooops…</h3>\n              <p class=\"pad-top\">\n                We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly. If you want to provide more information, please file a support ticket.\n              </p>\n              <p>\n                <a href=\"/\" class=\"btn btn-ha-primary\">Home</a>\n                <a href=\"mailto:support@hockeyapp.net\" class=\"btn\">Support</a>\n              </p>\n            </div>\n          </div>\n        </div>\n      </div>\n      <div class='clear'></div>\n    </div>\n    <script src=\"/assets/application-default.js\" type=\"text/javascript\"></script>\n  </body>\n</html>\n"
http response code: 500
##[section]Finishing: Create distribution
##[section]Starting: Checkout

**Comment by derpixeldan** [comment]
We have an ongoing incident affecting uploading iOS builds. Please follow our status page for any updates https://status.appcenter.ms/

**Comment by mondagoar** [comment]
Thanks for the fast response.
