### ISSUE TITLE
Configuration as Code (CaC) for App Center Build

### ISSUE THREAD

**Issue by alicejgibbons** [microsoft/appcenter#589]
The ability to describe the Build definitions in a language like YAML or JSON would be hugely valuable for many reasons: 
* Consistency across branches and distributions (Beta testers, etc)
* Ability to reproduce Build pipelines across apps
* Ability to view a complete history and change-log of the pipeline
* To ensure App Center is adhering to best DevOps practices
... (and all the other main benefits of CaC)

There is a similar solution in place for [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema) using YAML.

**Comment by ranterle** [comment]
Thank you @alicejgibbons for your request. It is something we have been looking into. #437 is very similar in its nature. I think this request is more concrete with what we have been considering.

We don't have anything to announce at the moment. I would like to keep this discussion open to see what kind of solutions would help you and how you would want to see those integrated with App Center.

**Comment by dgobaud** [comment]
please!!

**Comment by hameno** [comment]
This is a requirement for any modern build infrastructure. I just started to migrate from Hockey and keep stumbling onto these blockers :/

**Comment by nrajpurkar** [comment]
@hameno is there a specific scenario you are blocked on that you are unable to do with App Center's current UI approach to configuration?

**Comment by dgobaud** [comment]
@nrajpurkar we can't build every branch for example. makes it hard to detect configuration changes etc really not optimal...

**Comment by dgobaud** [comment]
creating new branch builds takes a lot of time too

**Comment by ranterle** [comment]
@dgobaud Is the ability to [clone existing configurations](https://docs.microsoft.com/en-us/appcenter/build/branches#cloning-build-configurations) helping in this case? Or not enough? Not saying this solves all problems, but it has done for quite a few.

**Comment by dgobaud** [comment]
that might help a bit but it can't be automated right? the idea is build every branch like circleci

**Comment by joehanna** [comment]
I think having a YAML build script is essential, particularly one that is contained in the repo you are building. This way everything is together and you get source control on the build script.  I used this with Bitrise.io before and it works well.

**Comment by Maverick1st** [comment]
Is there any news on this? Today I tried to build my app from AppCenter with the YAML Build script I have created in Azure DevOps, but there is no option for me to select that build script in AppCenter build process.

**Comment by nilofer** [comment]
@Maverick1st no update on this for App Center. Currently, Azure DevOps is a better option for CaC with the YAML build configuration
