### ISSUE TITLE
Ability to publish your own test report files

### ISSUE THREAD

**Issue by johnhiggs** [microsoft/appcenter#590]
**Describe the solution you'd like**
Until more test frameworks are supported we really need the ability to publish your own test automation report result files such as a .html, .xml etc...

**Describe alternatives you've considered**
Maybe a webhook that can push custom test result reports to a slack channel etc

**Additional context**
I'm using an appium, webdriver.io, and playing around various test report package (such as allure)for automated UI testing a react-native project and can't publish test results to appcenter, for example like jenkins I can configure bash etc to push any html, xml, json etc file i want to a test results section for each build.  Mainly webdriver.io is not an option for the test framework options

**Comment by Oddj0b** [comment]
Hey @johnhiggs, just to clarify do you want to publish test results to App Center Test?

**Comment by johnhiggs** [comment]
Hi @Oddj0b! Yes i want to publish my own test result files such as .html etc, ideally I want to use different than the current supported test frameworks hence the request to be able to publish our own test results and stay within app center to view them.

**Comment by Oddj0b** [comment]
@johnhiggs Makes sense, thank you for your feedback, I hope more users want this feature.

**Comment by Gwayaboy** [comment]
@johnhiggs how did you manage to run your appium, webdriver.io UI tests from AppCenter?
Did you use custom (pre and/or post) build? I'd be curious if you can share
