### ISSUE TITLE
Oh no! Build 10 failed to distribute. Error: Internal Server Error: undefined

### ISSUE THREAD

**Issue by GreenEggsAnHam** [microsoft/appcenter#592]
**What App Center service does this affect?**
Name of service or sdk with the issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DennisPan** [comment]
Thanks for reaching out. There is an ongoing incident affecting distribution: https://status.appcenter.ms/ .

**Comment by derpixeldan** [comment]
Resolved.

**Comment by morelgarisi** [comment]
> Resolved.

issue not resolved yet.
