### ISSUE TITLE
cannot distribute build to a certain group

### ISSUE THREAD

**Issue by jbuiYUM** [microsoft/appcenter#593]
**What App Center service does this affect?**
distribution

**Describe the bug**
Error message "Oh no! Build 10 failed to distribute. Error: Internal Server Error: undefined" shows up when distributing a build to group.

**To Reproduce**
1. Go to branch with build.
2. Click on 'Distribute' dropdown -> 'Groups/Testers' -> Click on input field and choose a group -> Click 'Next' -> Click 'Next' -> Click 'Distribute'
3. See error "Oh no! Build 10 failed to distribute. Error: Internal Server Error: undefined"

**Expected behavior**
Build distributes to chosen group.

**Screenshots**
<img width="1676" alt="Screen Shot 2019-06-19 at 5 58 24 PM" src="https://user-images.githubusercontent.com/47568004/59807544-03667a80-92be-11e9-9c9b-7777207a3fa6.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Browser: Chrome
 - Version: 75.0.3770.90

**Comment by DennisPan** [comment]
Thanks for reaching out. There is an ongoing incident affecting distribution: https://status.appcenter.ms/ .

**Comment by derpixeldan** [comment]
Resolved.
