### ISSUE TITLE
Build without an Xcode or Android Studio project in source-control

### ISSUE THREAD

**Issue by xv-matt-u** [microsoft/appcenter#594]
**Describe the solution you'd like**
I have a repository that builds a cross-platform library with CMake. It includes a binary with a test suite that must run on a real device.

Since CMake is generating the xcode project based on configuration options given to it, I should *not* check that into source control.

When I go to add my project, App Center can't find an Xcode project and simply gives up.

I already have scripts that configure, build and test on a real device locally, but I can't run them in App Center. I can't run them in Azure Pipelines either because they need a connected iOS device.

Therefore the feature I request is seemingly rather simple: *Allow me to use my own build script for building and running my app*

**Describe alternatives you've considered**
Only competitors have a solution (e.g. Amazon Device Farm)

**Comment by DennisPan** [comment]
@xv-matt-u Thanks for the suggestion! App Center Build is actually built from integration with Azure Pipelines. If Azure Pipelines doesn't work for you case, mostly likely there is limited room for App Center to create something that will.

**Comment by xv-matt-u** [comment]
Thanks @DennisPan
The only part of Azure Pipelines that doesn't work for my case is the requirement of having an actual iOS or Android device.

In that case here's a couple of solutions:
1. App Center Build can simply have a "pipelines mode" which is basically "Azure Pipelines plus attached devices"; or
2. Azure Pipelines adds support for various devices - e.g. choice between "building on a mac" versus "building on a mac with device X attached"

**Comment by ranterle** [comment]
@xv-matt-u We continue to look into options of how we can leverage the flexibility of Azure Pipelines for App Center Build, thanks for your suggestion as well.
In the meantime, you can combine the flexibility of Pipelines and the on device testing capability of App Center: You could write an Azure Pipeline to build your application project, then have a task in there which queues a device test run in App Center Test based on the build output using the App Center Test APIs.

Does that sound reasonable?
