### ISSUE TITLE
Build failed. iOS.

### ISSUE THREAD

**Issue by Laapi** [microsoft/appcenter#595]
**What App Center service does this affect?**
App centr build system

**Describe the bug**

format error

##[section]Async Command Start: Upload Artifact
Uploading 3 files
File upload succeed.
Upload '/Users/vsts/agent/2.153.2/work/1/a/symbols' to file container: '#/4040973/symbols'
Associated artifact 12 with build 21
##[section]Async Command End: Upload Artifact
##[section]Finishing: Publish symbols
##[section]Starting: Create distribution
==============================================================================

Task         : App Center distribute
Description  : Distribute app builds to testers and users via Visual Studio App Center
Version      : 3.154.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
==============================================================================

##[error]"{\"status\":\"error\",\"message\":\"Version could not be created from build. Please make sure that your .ipa file has the correct format.\"}"

**To Reproduce**
1. Go to 'build with distribute to store'

**Comment by DennisPan** [comment]
@Laapi Could you reach out to support (from App Center portal) for this? We can then look into your app and help.

**Comment by 2upmedia** [comment]
This is an issue with Xcode. Make sure that it's picking up your provisioning profile. For some reason mine didn't want to pick up the provisioning profile so I had to manually assign it.
