### ISSUE TITLE
Long Build times iOS

### ISSUE THREAD

**Issue by GreenEggsAnHam** [microsoft/appcenter#596]
**What App Center service does this affect?**
iOS Build

**Describe the bug**
Builds take a long time 20+ mins.

**To Reproduce**
1. Click Build Now

**Expected behavior**
Build to take a reasonable amount of time

**Screenshots**
![Screen Shot 2019-06-20 at 7 25 23 AM](https://user-images.githubusercontent.com/48684003/59849294-d4d3b880-932c-11e9-931e-053fc43b3ed6.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3 (18D42)
 - Browser: Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by DennisPan** [comment]
@GreenEggsAnHam Could you take a look at this and see if it helps? https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/general#longer-build

**Comment by ranterle** [comment]
@GreenEggsAnHam If the information posted by @DennisPan does not explain why your builds are slow, I would recommend to contact our support in the App Center portal with this question, from there you will be able to share details about which app and which builds you're experiencing this with, which will be vital information to help us understand why your builds are not performing as fast as you expect them to.

**Comment by DennisPan** [comment]
@GreenEggsAnHam I'm closing this. Feel free to re-open if needed.

**Comment by GrillAndChill** [comment]
@ranterle @DennisPan 

We have the same issue... our build takes longer than 30min then it gets cancelled.

We are using React Native, and it seems like App Center doesn't cache the packages. It runs fresh install for npm packages and Cocoapods too every time we build.

**Comment by ranterle** [comment]
@GrillAndChill Correct, App Center currently only performs fresh a clean build for your app every single time, i.e. it does not cache previous build results.
That does not mean however, that it downloads all the packages every singe time. We do provide pre-installed versions of most popular packages - with the plethora of packages and versions out there, there is no guarantee a package will be preinstalled though. If you're encountering slow builds which are timing out it would actually be good to reach out to our support team to get an understanding of what's taking longer and what could be done about it.

For caching results or dependencies between builds, this also seems similar to #473.

**Comment by gabrielmoncea** [comment]
> @GreenEggsAnHam Could you take a look at this and see if it helps? https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/general#longer-build

@DennisPan this link is dead. Do you have a new endpoint for it?

**Comment by param-finder** [comment]
It's taking painfully long to build as 35 minutes!

**Comment by eaigner** [comment]
I am not suprised. Have you seen what a truckload of garbage is inside the `AppCenter` package? All I want is crash reporting and for that you have to compile 2000 things you're never ever going to use.

**Comment by billnbell** [comment]
My build is > 60 minutes! On Expo it was 20 minutes.

**Comment by gabrielmoncea** [comment]
I've moved away from AppCenter to github actions, where the build times are incredibly high too. Unless they are willing to switch to the `arm64` architecture these performance drawbacks with keep existing
