### ISSUE TITLE
Clicking on Testing Group Gives 404 Error

### ISSUE THREAD

**Issue by jessbe** [microsoft/appcenter#598]
**What App Center service does this affect?**
Distribute app to group of testers

**Describe the dbug**
Click App, click Distribute -> groups -> one specific group comes back as 404

**To Reproduce**
1. Click app
2. Click on 'Distribute'
3. Click on 'Group'
4. Click UAT - comes back 404 error

**Expected behavior**
Be able to see UAT group of testers

**Screenshots**
<img width="1592" alt="Screen Shot 2019-06-20 at 8 43 25 AM" src="https://user-images.githubusercontent.com/50628394/59854020-ac04f080-9337-11e9-9eae-559488af6eea.png">

iOS and Android App

**Additional context**

**Comment by botatoes** [comment]
Hi, can you create an intercom ticket for this on appcenter.ms? We'll get more info about your app from there and can help you troubleshoot.
