### ISSUE TITLE
Unable to Register Devices

### ISSUE THREAD

**Issue by thomasonb** [microsoft/appcenter#600]
**What App Center service does this affect?**
Distribution

**Describe the bug**
When releasing our app it shows 9 Unregistered devices. After clicking Register Devices AND Resign the app it just gets stuck and has been stuck for ~30 minutes. If choosing just Register Devices it says it is successful but never shows those devices as having been registered and when attempting to install them on the unregistered devices it doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/3091040/59863644-1e36fe80-9353-11e9-8a74-886eebb62983.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by thomasonb** [comment]
This did eventually finish, it took about 30 minutes though.

**Comment by ntodd** [comment]
Same here. The device is added to the devices list in developer.apple.com, but stays "unprovisioned" on App Center.

**Comment by Oddj0b** [comment]
We've been seeing some issues with our machines running the service. But it should have been mitigated by now.
If you still experience delays, please re-open this bug.

**Comment by rodrigofeijao** [comment]
I'm still having this bug @Oddj0b 
Do I need to change anything on my configs?

**Comment by Oddj0b** [comment]
Hey @rodrigofeijao,

Can you create a support ticket under the **?** in the upper-right of the App Center portal, I think they can help you.
![Support image](https://user-images.githubusercontent.com/40024974/80818383-b1d29000-8bf0-11ea-8a04-f0dcbfa48bfd.png)
