### ISSUE TITLE
Unable to create a database through the portal

### ISSUE THREAD

**Issue by hovsepm** [microsoft/appcenter#601]
**What App Center service does this affect?**
Seems to be portal issue
**Describe the bug**
Created a new user, then new org and then am trying to create a new database for the app through portal. selected my personal subscription (513d6415-42d7-400e-b852-e81fa65a7bdd - MSDN Ultimate) and selected "somename" as a name of db. then "I'm just getting started" option. Now on the last screen I push "Create database" button. It shows some marching ants for a second and then nothing happens. I'm able to push the same "create" button several times - nothing works. 

**To Reproduce**

**Expected behavior**
Some information if my provided values or selections are invalid. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hovsepm** [comment]
Server returns 401 without any info.

**Comment by hovsepm** [comment]
the problem may be related to the fact that I've created a new user with my gmail account but was trying to use my MSDN subscription from outlook account.

**Comment by patniko** [comment]
@hovsepm we have some improvements coming for error handling. Are you able to create the database with your MSA/AAD account?

**Comment by hovsepm** [comment]
yes I am. The frustration is that there is no user friendly message. I figured that server returns 401 only when I checked the network traffic.

**Comment by Zakeelm** [comment]
Interesting, there should be an error message that says you must be logged in with an MSA account when using the wizard. I'm going to investigate this further.
