### ISSUE TITLE
App Center Auth B2C

### ISSUE THREAD

**Issue by Pita95** [microsoft/appcenter#603]
**What App Center service does this affect?**
Auth (Azure AD B2C)

**Describe the bug**
Trying to configure Auth for Azure AD B2C, after selecting the Subscription in step #1 and moving to step #2 to select a Tenant it says there are No tenants found. If I hit F12 for browser debugging I can see its returning a 400 when retrieving Tenants. However, if I take the same exact API call and use the same exact bearer token and ac-authorization-arm header with Postman it retrieves the tenants just fine.

**To Reproduce**
1. Go to App Center and select an application
2. On the left hand navigation click on 'Auth'
3. Click 'Connect your Azure Subscription'
4. Select your Azure subscription and click 'Next'
5. See 'No tenants found' message. If you had F12 debugging open when you performed step #4 then you will see the 400 response in the network tab.

**Expected behavior**
I am expecting to see the tenants that are available from stop #5 above so I can proceed to the next step of configuration.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, edge

**Additional context**

**Comment by amchew** [comment]
Hey @pita95, thanks for letting us know! Would you mind going to App Center (https://appcenter.ms), clicking on the blue chat button at the bottom right of the screen and copy pasting this issue? We may have to ask you some app sensitive questions to investigate further. Ping here when you’ve done so and I’ll find the conversation.

**Comment by Pita95** [comment]
Good Morning! I pasted this issue into the App Center chat.

**Comment by amchew** [comment]
Hi @pita95! Saw your message, we will investigate.

**Comment by amchew** [comment]
Hi @Pita95, an update: unfortunately this is still an ongoing investigation and is taking a little while to solve. We will continue to update.

**Comment by amchew** [comment]
Hi @pita95, sorry for the delay. Our team figured out and fixed the issue, we think it is resolved now and would really appreciate it if you would try it again and let us know.

**Comment by amchew** [comment]
Hey @pita95, I'll be closing this issue as the bug is resolved now. Feel free to reach out and open this ticket again if not. Thanks!

**Comment by ithiredguns** [comment]
bug came back

**Comment by ithiredguns** [comment]
Bug came back

**Comment by brianhenk0147** [comment]
This is happening to me as well, just like the original poster.

**Comment by lanceking** [comment]
I'm having this same issue.
