### ISSUE TITLE
Get information about who have received Push notifications

### ISSUE THREAD

**Issue by cansado2930** [microsoft/appcenter#605]
**Describe the solution you'd like**
When I send a Push notification, I would like to know what users & devices have tried to send and what of them and received it. In addition, I would like to send a "push" to X users and App Center send it to Android, iOS, Windows on the same request. I want to say, Some way in order to unify push notifications of different OS.

**Describe alternatives you've considered**
Other options is to use Azure, Firebase or developing my own function to identify users-devices and send it I directly.

**Additional context**
My Case I working with send to users ( I don't need to identify the device) but on other context, it may be necessary.

**Comment by jwargo** [comment]
@cansado2930 thank you for the suggestions. On sending across multiple app projects in App Center, we're aware of that one and we're planning on an update that will enable that. No concrete date for that one, but having grouped projects and being able to share resources across them is a highly requested feature.

**Comment by jwargo** [comment]
@cansado2930 Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
