### ISSUE TITLE
Send Push to iOS, Android and Other [Multiple Platforms]

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#607]
Hi,

Currently when sending Push through API we have to specify the app_id which is a platform specific but this this is not the case when you mostly sending Push because usually you'll send to all users of your app regardless of the platform.

I suggest you add an option to Send to all platforms AND another option to send to multiple platforms without having to call the API multiple times

Thanks,
[Jassim](https://www.softnames.com)

**Comment by jwargo** [comment]
@jrahma thanks for the suggestion, yes, we have this in our plans, see my response to #605

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
