### ISSUE TITLE
Recipients Geo Distribution Reports & Chart

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#608]
In AppCenter Push, Please add a report & chart to show the recipients Geo distribution to explain where in the world my message as received with a percentage

**Comment by jwargo** [comment]
@jrahma how will we know where the device is located? We don't currently have that information today.

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
