### ISSUE TITLE
Report: List of Recipients

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#609]
In App Center Push, Please add a a list of recipients with device ID AppCenter.GetInstallIdAsync with the status (received or not), date / time received, click or not with date / time

When you click on the recipient it should show more details, e.g. device model, geo location, time, etc..

**Comment by jwargo** [comment]
@jrahma thanks for the suggestion.

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
