### ISSUE TITLE
Azure DevOps Build Pipeline Task

### ISSUE THREAD

**Issue by dannythomas13** [microsoft/appcenter#61]
I was excited to see the task to deploy to Visual Studio App Center and successfully entered the majority of the required info, however I am unsure what to place as a Binary file path for the UWP instance of my Xamarin Forms app, can you please advise whether this is something that is not supported...if so for now I will have to continue to have a duplicate task within App Center to deploy the UWP version.

**Comment by daltonks** [comment]
@dannythomas13 
Here's what I figured out for anyone looking for a workaround:
The .appxupload is the file you're looking to upload. The problem with this is that the name of it is in the form of (APP_NAME)\_(VERSION)\_(TARGETS).appxupload.

To get around this, I created a powershell script that gets run before deploying to App Center. Its working directory should be the same as your MSBuild "/p:AppxPackageDir":
```
$packageFile = Get-ChildItem $dir -filter *.appxupload
$packageFileName = $packageFile.Name
Rename-Item -Path $packageFileName -NewName package.appxupload
```

It finds the .appxupload file and renames it to "package.appxupload". In your App Center deployment step, you can simply point to the "package.appxupload" path.
