### ISSUE TITLE
Percentage of Received vs Clicked

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#610]
Please add a report and chart to show the percentage of push notifications messages received vs clicked messages

**Comment by jwargo** [comment]
@jrahma thank you for the suggestion, we don't capture clicks today, but this is something we can consider.

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
