### ISSUE TITLE
Custom Push Notification Sound

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#611]
Please add the custom sound in the AppCenter Portal

**Comment by jwargo** [comment]
@jrahma to clarify, you mean add support for sending custom sounds to devices, right?

**Comment by jrahma** [comment]
Yes, the sound will be stored locally and the user will choose which sound or the system will decide (depends) then AppCenter will send the message using that sound to the device itself.

**Comment by jwargo** [comment]
@jrahma thank you for the suggestion.

**Comment by jwargo** [comment]
@jrahma custom sounds are supported today, see these sections of the docs: https://docs.microsoft.com/en-us/appcenter/sdk/push/android#custom-data-in-your-notifications and https://docs.microsoft.com/en-us/appcenter/sdk/push/ios#custom-data-in-your-notifications. What is it you're trying to do that you can't do using the built-in features?

**Comment by jrahma** [comment]
@jwargo This is the [problem](https://docs.microsoft.com/en-us/appcenter/sdk/push/android#reserved-keywords-in-android-platform):

> This is effective only for devices running or targeting an Android version lower than 8. Sound is set by default on Android 8 and user can change notification settings for the group of notifications coming from AppCente


when all other platforms provide this feature for all android versions then I believe for Microsoft it should piece of cake

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
