### ISSUE TITLE
Rich Media Attachment

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#613]
Please add Rich media attachment. Image, sound, or video to show when 3d touching the push notification.

**Comment by jwargo** [comment]
@jrahma thanks for the suggestion

**Comment by adrianknight89** [comment]
I need this as well. I can't find any useful information in your documentation with respect to media attachments.

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
