### ISSUE TITLE
Action Buttons 

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#614]
Please add action buttons for AppCenter Push for iOS and Android

**Comment by jwargo** [comment]
@jrahma can you please describe in more detail the feature you're looking for? I'm assuming action buttons in the SDK (client-side), but how do you expect them to work?

**Comment by jrahma** [comment]
> @jrahma can you please describe in more detail the feature you're looking for? I'm assuming action buttons in the SDK (client-side), but how do you expect them to work?

This is what I mean John:

[https://documentation.onesignal.com/docs/action-buttons](https://documentation.onesignal.com/docs/action-buttons)

**Comment by jwargo** [comment]
@jrahma pointing me to our partner's documentation doesn't help me understand your specific needs.  Our goal is not to duplicate features of other products in the market, we're interested in them, but what we build our features on is our customer's requirements for the feature.

**Comment by jrahma** [comment]
@jwargo Please see Android documentation

[https://developer.android.com/training/notify-user/build-notification](https://developer.android.com/training/notify-user/build-notification)

and iOS:

[https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types](https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types)

Thanks John

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
