### ISSUE TITLE
Remove default plural text when the device count is 1

### ISSUE THREAD

**Issue by adrianknight89** [microsoft/appcenter#616]
When the device count is 1 on the Push Notifications page, I should see "1 device" instead of "1 devices".

![Capture](https://user-images.githubusercontent.com/16855542/59965753-e6a58f00-94d7-11e9-8325-618f16f2f20d.PNG)

**Comment by jwargo** [comment]
@adrianknight89 thanks for pointing that out, I'll get this fixed.

**Comment by marstr** [comment]
Looks like this issue didn't get cleaned up after it was fixed on July 9th. It is now safe to say that this issue is dealt with.
