### ISSUE TITLE
Build not start

### ISSUE THREAD

**Issue by mkgitalia** [microsoft/appcenter#618]
**What App Center service does this affect?**
Build

**Describe the bug**
Manual Build not starts and only "*** Waiting for data from the build agent ***" only at the end I can see all log

**Expected behavior**
log scrolling down

**Desktop (please complete the following information):**
 - OS: WinX
 - Browser chrome
 - Version 75.0.3770.100 (Build ufficiale) (a 64 bit)

**Comment by DennisPan** [comment]
@mkgitalia  Thanks for reporting this! We indeed introduced a bug on Friday which regressed the behavior on this. A hotfix was just deployed. Please let us know if you still experience any issue.

**Comment by voxoid0** [comment]
Still seeing this issue today.

**Comment by DennisPan** [comment]
@voxoid0 Do you mind reaching out to support via App Center portal? Then we can look into your specific app. I just tried and log is streaming. So it's likely something unique is happening in your case.
