### ISSUE TITLE
Page Views Analytics

### ISSUE THREAD

**Issue by joshuaclicks** [microsoft/appcenter#619]
In order to adequately track where the Customer or User is using the most on a mobile app, there should be a way for the SDK to track the **pages viewed** on the mobile app and the **time spent on each of the pages**.

This information will help to know what features the Users are using the most and so that the business can pivot using that piece of information.

**Comment by hamswan** [comment]
@joshuaclicks I would like to understand your use case, I will add this also in our discussion when we talk.

**Comment by KSemenenko** [comment]
And after we can build #386 Userflow

**Comment by jrahma** [comment]
Also it should be possible to track every ContentPage and ContentView by Page and View names (without having to TrackEvent)
