### ISSUE TITLE
Number of App Downloads 

### ISSUE THREAD

**Issue by joshuaclicks** [microsoft/appcenter#620]
Since the AppCenter tool helps to distribute apps to the AppStore, PlayStore and In-tune, it should be open to receiving via its API, a means of **_aggregating the data from these different platforms_** especially data like the **number of downloads** the app has received from all of the different distribution channels.

As a business that is subscribing to the AppCenter for Analytics, I will like to have all **analytic data in one place** rather than being scattered on different platforms.

**Comment by hamswan** [comment]
@joshuaclicks Totally agree that it is easier to have a unified Analytics view on one single dashboard. We are currently thinking about creating this experience, we are working on it there is no ETA currently.  We would love to get inputs from customers like yourself. Let me know if you have some time to talk to us, I can set up a call so I can better understand your use cases for Appcenter Analytics.

**Comment by joshuaclicks** [comment]
Thanks for the response. I will however be available between the hours of
9:00 to 17:00 and 21:00 to 23:00 daily. You can plan the schedule around
these times.


Regards.

**Comment by hamswan** [comment]
Thanks, Can you email hamsab@microsoft.com so I have the email you want me to communicate with you.
