### ISSUE TITLE
Consolidate Multiple Apps Data in Analytic View

### ISSUE THREAD

**Issue by joshuaclicks** [microsoft/appcenter#621]
I had to create different apps on AppCenter for a mobile app built for both the Android and iOS versions. And when I try to analyse the data, I had to do it for the different apps independently even though it is the same app which was created as separate apps on AppCenter. 

**For an easy and comprehensive analysis**, the **_data for the different apps should be consolidatable_** so that all analysis can be done in one place.

**Comment by hamswan** [comment]
@joshuaclicks Thanks for the input, if you need this immediately you can export Analytics to Application Insights and run custom queries on Log Analytics to aggregate the data. I have added this in our feature request.

**Comment by joshuaclicks** [comment]
Thanks for the response. I will make do with that for now and will like to
see the full feature in the future.


Regards.

**Comment by hamswan** [comment]
@joshuaclicks Can you email me your app secret, so we can take a look?
