### ISSUE TITLE
Log Flow Sub-Feature very slow in loading

### ISSUE THREAD

**Issue by joshuaclicks** [microsoft/appcenter#622]
In comparison to the **Event** sub-feature under the **Analytics** feature, the **Log Flow** sub-feature loads up readily slow.

**Comment by hamswan** [comment]
@joshuaclicks Log flow is showing what you receive in the backend, depending on the number of events, it might take   few seconds or sometimes a min to show up. Can you tell us how long it takes for you to show up? How many custom events do you for your app?

**Comment by joshuaclicks** [comment]
I recently just integrated AppCenter for the first time and I'm on Dev test
now. I have just about 6 Custom Events logged and it takes more than 2
minutes to load them up. Sometimes it fails and shows up nothing on the
board.


Regards.

**Comment by hamswan** [comment]
@joshuaclicks Can you email me your app secret, so we can take a look?

**Comment by yoannchaudet** [comment]
Like Hamsa said, if you can get us your app secret via email (our support request from our portal) we could look into it.

Also note that Log Flow does not show you past logs. When you display the page from our portal, the first thing it does is register itself to receive flow of logs. Typically if you are using a test application, you will want to interact with it after opening Log Flow from our portal.

**Comment by joshuaclicks** [comment]
Ok, I'm clear about it. You can close this ticket.


Regards.
