### ISSUE TITLE
Unable to add App Center Push to Android Project

### ISSUE THREAD

**Issue by galfonso777** [microsoft/appcenter#624]
**What App Center service does this affect?**
App Center Push

**Describe the bug**
Unable to add two packages to Android Project due to dependencies:
- microsoft.appcenter
- microsoft.appcenter.push

Error: (in vs for mac)
Could Not Add Packages:
Resolving conflicts for MonoAndroid,Version=v9.0...
Detected package version outside of dependency constraint: Xamarin.Android.Support.v4 26.0.2 requires Xamarin.Android.Support.Compat (= 26.0.2) but version Xamarin.Android.Support.Compat 28.0.0.1 was resolved.
Detected package version outside of dependency constraint: Xamarin.Android.Support.v7.MediaRouter 26.0.2 requires Xamarin.Android.Support.v7.AppCompat (= 26.0.2) but version Xamarin.Android.Support.v7.AppCompat 28.0.0.1 was resolved.
Detected package version outside of dependency constraint: Xamarin.Android.Support.Media.Compat 26.0.2 requires Xamarin.Android.Support.Compat (= 26.0.2) but version Xamarin.Android.Support.Compat 28.0.0.1 was resolved.
Detected package version outside of dependency constraint: Xamarin.Android.Support.v7.Palette 26.0.2 requires Xamarin.Android.Support.Compat (= 26.0.2) but version Xamarin.Android.Support.Compat 28.0.0.1 was resolved.
Version conflict detected for Xamarin.Android.Support.Core.UI. Install/reference Xamarin.Android.Support.Core.UI 28.0.0.1 directly to project SDCrew.Android to resolve this issue.

**To Reproduce**
Attempt to add both packages when using the following packages.
- mvvmcross (6.3.0)
- mvvmcross.droid.support (6.3.0)
- xamarin.android.support (28.0.0.1)

**Expected behavior**
Ability to Add packages

If known dependency issue document in https://github.com/MicrosoftDocs/appcenter-docs/issues/new

**Comment by JelleDamen** [comment]
I got this same issue, I've fixed it by manually adding these Android libs myself.

Xamarin.Android.Support.Core.Utils Version=28.0.0.1
Xamarin.Android.Support.v7.AppCompat Version=28.0.0.1
Xamarin.Android.Support.v4 Version=28.0.0.1
Xamarin.Android.Support.Design Version=28.0.0.1
Xamarin.Android.Support.v7.MediaRouter Version=28.0.0.1

Not sure if they're all needed in your case.

**Comment by dtrabo** [comment]
Hi @galfonso777 ! 
This issue will be resolved in next release, please follow up to updates. 
Thank you for using AppCenter!

**Comment by ColdstarJoey** [comment]
Is this fixed as i am getting this for 28.0.0.3?
