### ISSUE TITLE
Problem re-signing application due to provision profile name inconsistency

### ISSUE THREAD

**Issue by Spartanace1024** [microsoft/appcenter#625]
**What App Center service does this affect?**
Name of service or sdk with the issue.

**Describe the bug**
If provision profile in app center is not named exactly that of the application on iOS it will fail to resign app for a tester ( I think ).

Further info found here
https://github.com/MicrosoftDocs/appcenter-docs/issues/608

**Comment by Oddj0b** [comment]
@Spartanace1024 this shouldn't happen we match the provisioning profile in the app with one in your developer portal. We don't store the provisioning profile, only download them from Apple's developer portal.

Can you share the error message or a screenshot?
