### ISSUE TITLE
Invite testers to test flight / play store from appcenter api

### ISSUE THREAD

**Issue by thsbrown** [microsoft/appcenter#627]
**Describe the solution you'd like**
Make an app center API call, with a provided email / several emails in order to invite those emails to a test flight / google play build as testers. 

**Describe alternatives you've considered**
Using fastlane to invite testers to google play / test flight build. However because we are already using appcenter (and like the api) this would be a much more optimal approach. 

**Additional context**

**Comment by Oddj0b** [comment]
Hi @Spartanace102,
Thank you for your feedback. Hopefully, this request gets more reactions so we can start the work.
