### ISSUE TITLE
In-App Updates for sideloaded Apps

### ISSUE THREAD

**Issue by tomh4** [microsoft/appcenter#628]
We are using AppCenter to provide our clients with updates of our app as the app is not distributed over any store. Up to now we need to grab every client device, browse to AppCenter, log in, install the app from there and start the app once to init the In-App Update process. This is very tedious as we have a large amount of client devices so we want to be able to sideload the apps onto those devices and still have in app updates without any further doing from our side. 
The initialization in the code should be used to identify the app in the AppCenter and grab the updates. 

We evaluated providing our apps directly over the app stores but decided against it because we do not want to have them publically available. Our previous workflow was to flash a backup image to every device to have everything set up. 

Our main target OS is Android.

**Comment by chongchungyin** [comment]
I am facing the same issue as above. Knowing that you guys have started looking into this feature, can i know roughly what's the workflow after this feature implemented?
Thanks.

**Comment by tomh4** [comment]
Any updates on this ?
We tried working with public links, but this does still not allow in app updates when sideloaded, even if no login is necessary...

**Comment by shahid-riaz** [comment]
Exactly the same scenario here as the original posters.

Guys, we'd appreciate if you provide some update on this. How long before this becomes a reality?

**Comment by botatoes** [comment]
Hi all, we are currently working on stabilizing and scaling in-app updates to handle more load. Once we are done with the current set of work on scaling, we have a set of in-app update improvements in the backlog. One of the prioritized features will be supporting in-app updates on publicly distributed apps. 

We currently support in-app updates if testers install them through the browser on the install portal for private releases. I will put sideloaded in-app update support on our backlog as well. Will update when prioritized.

**Comment by chongchungyin** [comment]
Thanks for the update

**Comment by AndrewBryanScott** [comment]
Hi Botatoes, any update on this? we also need in app updates to work as we do distribute our app via an mdm package as apk to over 2000 users.

**Comment by tomh4** [comment]
@botatoes any news? We have a large amount of tablets and it is really not practible to install the apps through the browser, sideloading through adb would be much more comfortable :)

**Comment by tomh4** [comment]
Any chance this is being worked on ?

**Comment by tomh4** [comment]
@botatoes any updates on this? 
We are still provisioning our tablets manually which is very tedious... Sideloading them would facilitate things for us
