### ISSUE TITLE
iOS Build failed by 'iCloudContainerEnvironment'

### ISSUE THREAD

**Issue by surez0812** [microsoft/appcenter#629]
**What App Center service does this affect?**
iOS Project Build

**Describe the bug**
Build failed by 
Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided}

**To Reproduce**
Each time building

**Expected behavior**
Build success

**Comment by DennisPan** [comment]
@surez0812 Thanks for reaching out! We've seen similar issue from other customers before. This workaround helped:

1. Enable the iCloud capability and CloudKit for the extension
![image](https://user-images.githubusercontent.com/14064342/60115545-0385d080-972b-11e9-82bb-c8e4d7c56444.png)
2. Commit the change. Push to the branch.
3. Drag and drop the extension's new provisioning profile to the Desktop:
![image](https://user-images.githubusercontent.com/14064342/60115642-392ab980-972b-11e9-9f7d-aa80b97e0fcf.png)
4. In AppCenter's build settings, use the new provisioning profile for the extension.
5. Attempt to build.

Could you give this a try?

**Comment by JeanetteMueller** [comment]
i have the same problem but the solution doesn't help.

**Comment by indraneely** [comment]
any update on this ?

**Comment by vBoykoGit** [comment]
Any solution here?

**Comment by phatmann** [comment]
Same here

**Comment by vBoykoGit** [comment]
I have added iCloud capability to all my targets and now  it's working!

**Comment by phatmann** [comment]
@vBoykoGit I have iCloud capability in my targets. Did you also add Cloudkit?

**Comment by phatmann** [comment]
Adding CloudKit entitlement did not solve my issue

**Comment by chihimng** [comment]
To everyone having the same problem (there are probably app extensions in you project), note that you need to enable iCloud capability and associate a iCloud Container **to the app extensions** even if you don't need them.

If you use manual signing config, you will need to visit developer.apple.com and **edit each of your extension app ids**:
- Enable iCloud capability
- Associate a iCloud container id (even if you don't need it in extensions)
- Enable push notification (not sure if this is required)
Then, regenerate all provisioning profiles and upload them to App Center.
(Associating container id is to make sure that `com.apple.developer.icloud-container-environment` exists in your provisioning profile, more on this next...)

Most importantly, you will need to **add the following lines to your `.entitlements` files** (for all app extensions!)
```
<key>com.apple.developer.icloud-container-identifiers</key>
<array/>
<key>com.apple.developer.icloud-services</key>
<array>
	<string>CloudKit</string>
</array>
<key>com.apple.developer.icloud-container-environment</key>
<string>Production</string>
```

Note that you don't actually need to specify container id in `.entitlements` if you don't use them in extensions at all. 
The **key to solve this problem** is the `com.apple.developer.icloud-container-environment` value, which is only included in your provisioning profile if you associate a iCloud container id.

**Comment by asleepace** [comment]
For those using Fastlane and Gym the following fixed the issue for me:

In the `Fastfile`:
```ruby
gym(
  export_method: "ad-hoc",
  export_options: {
    iCloudContainerEnvironment: "Production"
  } 
)
```
