### ISSUE TITLE
Build Zip, unable to unzip or build issue

### ISSUE THREAD

**Issue by ranjithshanmugam** [microsoft/appcenter#630]
**What App Center service does this affect?**
Build Service
**Describe the bug**
After taking the build, build succeeds but the build zip whoch was downloaded not getting unzipped properly. It says unknown file format. Same thing happens for both iOS and Android.  
Can you please help me this issue?

AppName : Budocode (has both iOS and Android).
Platform : Xamarin forms app

<img width="407" alt="Screenshot 2019-06-25 at 5 07 33 PM" src="https://user-images.githubusercontent.com/41289023/60095252-bfff8680-976b-11e9-90a7-007dcbdd2bde.png">

**Comment by DennisPan** [comment]
@ranjithshanmugam Could you reach out to support (via App Center portal)? We will be able to look into your app details from there.

**Comment by nrajpurkar** [comment]
@ranjithshanmugam are you still seeing this issue? Closing this for now, but feel free to reopen if you still need help

**Comment by ben-palmer** [comment]
I am seeing this issue now
