### ISSUE TITLE
Submit a private issue Report Whitelisting distrbution email

### ISSUE THREAD

**Issue by davidbuckleyni** [microsoft/appcenter#631]
Hi, We are trying to white list the following. I xxx out the domain as did not want that public if you have a private message forum for app center please let me no it appears to be the emails that are being created by the distribution area of the process.

The customer is using 

Our Mimecast service is catching the AppCenter Distribution emails and deferring some of them.
But we cant appear to whitelist 

@BNC3 address added to Microsoft whitelists

We think there is an issue with the @BNC3 
From Address                          85cb3780.caaaaenwbrkcaaaaaaaaaargmwmaaaa6pnmaaaaaaavpoqbdegbq@bnc3.mail.appcenter.ms
To Address (Pre Checks)         handset1@xxx.com
To Address (Post Checks)       Rejected prior to DATA acceptance

**Comment by davidbuckleyni** [comment]
Our Mimecast service is catching the AppCenter Distribution emails and deferring some of them.
no-reply@mail.appcenter.ms is accepted but @bnc3.mail.appcenter.ms is not accepted.

Futher detail of the customer information

Mimecast Deferring Definition:

Deferred messages: These are messages that tried to connect to Mimecast, but weren't initially successful (e.g. the message is subject to greylisting). These messages may subsequently be accepted, depending on the reason for the initial temporary failure. If a message is legitimate, you can use the information displayed to address the issue and ensure the message is successfully delivered on the next send attempt.
The next connection attempt must be made by the mail server between one minute and 12 hours after the initial connection attempt to be successful.

**Comment by patniko** [comment]
Hi @davidbuckleyni, mind e-mailing me at the address on my Github profile so I can see if we can help you out? Closing this out with the expectation we'll work direct with you.
