### ISSUE TITLE
Updated Xamarin.iOS version

### ISSUE THREAD

**Issue by svrooij** [microsoft/appcenter#632]
**Describe the solution you'd like**
I would like to be able to use the same sdk version in AppCenter as I can in my local visual studio. [stackoverflow question](https://stackoverflow.com/questions/56752587/choose-latest-version-ios-build-in-appcenter-build)

Currently I installed Xamarin.iOS 12.10.0.157 and in AppCenter I can only choose the 12.08 branch, the first 12.10 release was of somewhere in April.

**Describe alternatives you've considered**
Without this feature it’s kinda silly, with AppCenter I got the nice thing of auto deployment to Play store and AppStore (TestFlight). But I cannot use the latest fixes or improvements from the sdk.

**Comment by DennisPan** [comment]
@svrooij This is being worked on. Hopefully you will have this within next couple weeks.

**Comment by svrooij** [comment]
@DennisPan Any updates on the subject? 29 days is more than a couple of weeks right?

**Comment by nrajpurkar** [comment]
Apologies on the delay @svrooji, we've hit some issues in adding support for this. We'll still working on adding support for the latest Xamarin.iOS versions

**Comment by beeradmoore** [comment]
Update on what versions that @svrooij had mentioned. Xamarin.iOS is now up to version 12.14, and 12.16 is in Visual Studio for Mac 8.3 preview 1.

**Comment by nrajpurkar** [comment]
We've released support for Xamarin.iOS 12.10 today! We're working on support for 12.14 for the moment.

@beeradmoore We only add support for Xamarin.iOS and Xamarin.Android that coincides with stable VS for Mac releases.

**Comment by beeradmoore** [comment]
Haha, I was just updating my builds to 12.10 when the email notification from this github thread just came through.

@nrajpurkar that makes sense, was just double checking that AppCenter was aware that 10.16 is on the horizon.

**Comment by nrajpurkar** [comment]
We've updated to Xamarin.iOS 12.14. Thanks for your patience in getting this supported!
