### ISSUE TITLE
Building flutter project

### ISSUE THREAD

**Issue by calvinmuller** [microsoft/appcenter#633]
**What App Center service does this affect?**
iOS & Android build

**Describe the bug**
Console is just stuck at *** Waiting for data from the build agent ***

**To Reproduce**
1. Trigger build

**Expected behavior**
Should output the build progress

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser Chrome

**Additional context**
I am using this script i my project https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/flutter/ios-build/appcenter-post-clone.sh

**Comment by calvinmuller** [comment]
30 minutes later it fails with 
```
Building flutter tool...
Downloading Material fonts...                                       0.3s
Downloading android-arm-profile/darwin-x64 tools...                 0.2s
Downloading android-arm-release/darwin-x64 tools...                 0.2s
Downloading android-arm64-profile/darwin-x64 tools...               0.2s
Downloading android-arm64-release/darwin-x64 tools...               0.2s
Downloading android-x86 tools...                                    1.0s
Downloading android-x64 tools...                                    0.9s
Downloading android-arm tools...                                    0.3s
Downloading android-arm-profile tools...                            0.2s
Downloading android-arm-release tools...                            0.2s
Downloading android-arm64 tools...                                  0.3s
Downloading android-arm64-profile tools...                          0.2s
Downloading android-arm64-release tools...                          0.2s
Downloading ios tools...                                            1.6s
Downloading ios-profile tools...                                    1.3s
Downloading ios-release tools...                                    1.1s
Downloading Gradle Wrapper...                                       0.0s
Downloading package sky_engine...                                   0.1s
Downloading common tools...                                         0.5s
Downloading common tools...                                         0.4s
Downloading darwin-x64 tools...                                     1.6s
Doctor summary (to see all details, run flutter doctor -v):
##[error]The operation was canceled.
```

**Comment by solaamy** [comment]
I am running into the same issue today. The project works locally but every time build on AppCenter it stops processing at the same step as you show above.

**Comment by DennisPan** [comment]
@calvinmuller @solaamy Are you on free tier? Each build is [limited to 30 minutes for free accounts](https://docs.microsoft.com/en-us/appcenter/general/pricing#the-free-tier). 

This actually isn't related with Flutter. Flutter isn't officially supported, though there are [workarounds](https://www.rocksolidknowledge.com/articles/using-appcenter-for-flutter-projects). If you are interested in Flutter support, you can upvote #67 . 

Closing this.

**Comment by calvinmuller** [comment]
30 minutes to build a flutter app - it's clearly something wrong as apposed to "do i pay"

**Comment by calvinmuller** [comment]
and btw yes I used that article to setup my project - so i'd either disable it or update it to maybe make it work ;)

**Comment by DennisPan** [comment]
Do you mind taking a look at the build log and see where the time are spent? If you download the logs, it should give you more details on each step and the timestamps.

**Comment by williemaster** [comment]
Same problem here. How can I download the logs?

**Comment by DennisPan** [comment]
@williemaster If you view the build details, there should be a Download Logs button

**Comment by calvinmuller** [comment]
my guess is that flutter doctor is waiting for some kind of human input on first run of flutter doctor, tried yes | flutter doctor but that also didn’t seem to work. unfortunate.

**Comment by PawelSkwaraEuvic** [comment]
Is this kind of joke? Building flutter was working perfectly 2 days ago. Now it doesn't and it's for sure a flutter issue? :D well done ms, bravo!

**Comment by calvinmuller** [comment]
I know right.

**Comment by PawelSkwaraEuvic** [comment]
quickfix is to comment out "flutter doctor" from appcenter-post-clone.sh file and it builds like a charm again.

**Comment by calvinmuller** [comment]
Mine then gets stuck at
```
Running "flutter pub get" in s...                                  19.4s
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building blah.blah.appid for device (ios-release)...
```

**Comment by quenna999** [comment]
hi there,we need apple enterprise account...
would like to pay for it.
contact me freely....
fanboer@gmail.com
skype:live:fanboer

**Comment by DennisPan** [comment]
@PawelSkwaraEuvic @calvinmuller Sorry I didn’t realize you are reporting a Flutter build that was working before. In this case, could you reach out to support (via App Center portal) so that we can look into your app details? You may refer this Issue and have the support folks transfer this to me. Otherwise, this can get the same “not supported” answer. It is still true that we don’t have official support for Flutter. But I’d be interested in comparing the differences and understand what changed

**Comment by ksielyov** [comment]
Same problem with payed account

...
                                      _Nullable 
/Users/runner/work/1/s/node_modules/react-native-reanimated/ios/Nodes/REANode.h:22:29: note: insert '_Nonnull' if the pointer should never be null
- (instancetype)initWithID:(REANodeID)nodeID config:(NSDictionary<NSString *, id> *)config NS_DESIGNATED_INITIALIZER;
                            ^
                                      _Nonnull 
/Users/runner/work/1/s/node_modules/react-native-reanimated/ios/Nodes/REANode.h:22:83: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
- (instancetype)initWithID:(REANodeID)nodeID config:(NSDictionary<NSString *, id> *)config NS_DESIGNATED_INITIALIZER;
                                                              
**##[error]The operation was canceled.**
##[section]Finishing: Xcode build (signed)
##[section]Starting: Xcode build (signed)
==============================================================================
Task         : Xcode
Description  : Build, test, or archive an Xcode workspace on macOS. Optionally package an app.
Version      : 4.130.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613730)
==============================================================================
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25405) Warning: Use Cipheriv for counter mode of aes-256-ctr
##[section]Finishing: Xcode build (signed)
##[section]Starting: Install Apple provisioning profile
==============================================================================
Task         : Install Apple Provisioning Profile
Description  : Install an Apple provisioning profile required to build on a macOS agent
Version      : 0.124.0
Author       : Microsoft Corporation
Help         : 
==============================================================================
(node:25413) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25413) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25413) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25413) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25413) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25413) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25413) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25413) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:25413) Warning: Use Cipheriv for counter mode of aes-256-ctr
##[warning]Deleting provisioning profile: /Users/runner/Library/MobileDevice/Provisioning Profiles/5930ec04-5727-4a3d-baa1-54acbb8a1e1b.mobileprovision
[command]/bin/rm -f /Users/runner/Library/MobileDevice/Provisioning Profiles/5930ec04-5727-4a3d-baa1-54acbb8a1e1b.mobileprovision
##[section]Finishing: Install Apple provisioning profile
##[section]Starting: Install Apple certificate
==============================================================================
Task         : Install Apple certificate
Description  : Install an Apple certificate required to build on a macOS agent machine
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/install-apple-certificate
==============================================================================
[command]/usr/bin/security delete-keychain /Users/runner/work/_temp/ios_signing_temp.keychain
##[section]Finishing: Install Apple certificate
##[section]Starting: Checkout publife_fork_local@master to s
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Cleaning any cached credential from repository: publife_fork_local (ExternalGit)
##[section]Finishing: Checkout publife_fork_local@master to s
##[section]Starting: Finalize Job
Cleaning up task key
Start cleaning up orphan processes.
Terminate orphan process: pid (25446) (clang)
Terminate orphan process: pid (25445) (clang)
Terminate orphan process: pid (25444) (clang)
Terminate orphan process: pid (25443) (clang)
Terminate orphan process: pid (25439) (clang)
Terminate orphan process: pid (25438) (clang)
Terminate orphan process: pid (11541) (XCBBuildService)
##[section]Finishing: Finalize Job
##[section]Finishing: Build

Build time - 60 min 24 sec

**Comment by mrnmilutinovic** [comment]
@ksielyov per this [link](https://docs.microsoft.com/en-us/appcenter/general/pricing#the-free-tier) limit is still present just bumped to 60 minutes even though you pay. 

I just saw this myself.

**Comment by bradstiff** [comment]
iOS builds are unbelievably time consuming.
