### ISSUE TITLE
simctl command is hanging

### ISSUE THREAD

**Issue by thabemmz** [microsoft/appcenter#636]
**What App Center service does this affect?**
AppCenter iOS

**Describe the bug**
In my iOS build, my `post-clone.sh` script contains a `simctl` command: `/usr/bin/xcrun simctl list`.

When this command is invoked in my AppCenter build, it hangs until I cancel it. The command itself gives no output.

**To Reproduce**

1. Create a `appcenter-post-clone.sh` file in your repository and put the following contents in it:

```
#!/usr/bin/env bash
/usr/bin/xcrun simctl list
```

2. In AppCenter, create a build configuration that looks as follows:
- Project: `package.json`
- Xcode version: `10.2.1`
- Node.js version: `8.x`
- Use legacy build system: `off`
- Automatically increment build number: `on`
- Run unit tests: `off`

3. After 20 minutes, cancel the test

4. See the Build Output:

```
+ /usr/bin/xcrun simctl list
Running iOS build
Diagnose simctl
Install Started
##[error]The operation was canceled.
```

**Expected behavior**
I would either expect `simctl` to work or to give an error if something went wrong.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Comment by DennisPan** [comment]
@thabemmz This might be related to a bug we introduced two days ago, and fixed an hour ago. Do you mind giving it another try?

**Comment by thabemmz** [comment]
Just did and the issue is fixed! Thanks for your quick reply @DennisPan !

**Comment by DennisPan** [comment]
Sorry about the trouble. Good to know it's working now!
