### ISSUE TITLE
Refresh Token to extend authentication lifetime beyond 24 hours

### ISSUE THREAD

**Issue by brad302** [microsoft/appcenter#638]
The addition of the access token and claims delivered via this feature request ... [Issue #393](https://github.com/microsoft/appcenter/issues/393) ... provided some much needed and appreciated functionality but I'd like to see if it can be extended a bit further.

We have a requirement in our organisation (given rosters and based on fairly consistent user feedback) to extend the life of the access token beyond the maximum **24** hour (**1440** minutes) period offered up by Azure B2C to help improve the authentication experience when using Azure AD with on-prem ADFS ...

![image](https://user-images.githubusercontent.com/14899088/60220994-4e365280-98bb-11e9-9caa-f42e505da22e.png)

... to do that, the refresh token looks to be the catalyst for a solution.

This same functionality was available in the Azure Mobile Apps space but it was hidden away in the configuration and took a previous developer quite some time to track down but it did exist ...

[Microsoft.Web sites/config - tokenRefreshExtensionHours](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2018-11-01/sites/config-authsettings)

... the best thing about B2C is that it's all there and configurable through the Azure Portal.

**EDIT**

**The use case I am referring to is very much directed at the corporate AD world so if the solution for the upcoming Azure AD integration doesn't go through B2C, the requirement still exists but less so on the B2C side for social media providers, at least, that's my view and not my current concern/priority.  Others may have another opinion but I think I could live with the current experience for the social media IDP's.**

**That means, this feature request may not be a change to the current version of auth but may just be a consideration for the future Azure AD inclusion.**

**Comment by amchew** [comment]
Hey @brad302, thanks for the feedback! We spoke briefly just now, and we see your use case. Leaving this post up to gather more feedback, and we’ll investigate on a potential solution.

**Comment by amchew** [comment]
Hey @brad302, I recorded this ticket in our backlog, but unfortunately, there's no ETA for now. I'll be closing this ticket for now. Feel free to re-open this ticket if it comes up again or is a blocking issue.
