### ISSUE TITLE
Android Gradle Build flavorDimensions support

### ISSUE THREAD

**Issue by surez0812** [microsoft/appcenter#639]
**What App Center service does this affect?**
Android Gradle Builsd

**Describe the bug**
Our Android project is using "flavorDimensions" to combine different flavors in one build variants.
For example:
`
productFlavors {
        flavorDimensions "country", "type"
        us {
                dimension "country"
        }
        uk {
                dimension "country"
        }
        free {
                dimension "type"
        }
        paid {
                dimension "type"
        }
}
`

**To Reproduce**

**Expected behavior**
In Build Configuration -> Build Variant, we want to see usfreeDebu, usfreeRelease, ukfreeDebu, ukfreeRelease variants.

Thanks
Sure Zhang

**Comment by DennisPan** [comment]
@surez0812 Is this the same as #32 ?

**Comment by surez0812** [comment]
@DennisPan, yes! They are same requests. Checked your "Iteration Plan for July 2019", still no plan for this change. We have to pending our Android project migrating to App Center.
