### ISSUE TITLE
Add Environment Field for Diagnostics

### ISSUE THREAD

**Issue by mike14u** [microsoft/appcenter#64]
**Describe the solution you'd like**
An application could contain different schemes, variants / environments. Hopefully we can have a field to distinguish where the crash happened e.g. on production, staging etc.

**Describe alternatives you've considered**
Bugsnag offers this capability

**Comment by winnieli1208** [comment]
Hey @mike14u,

Thanks for the feedback! We don't have any short term plans to support this feature but I'll note this as a feature request to help our team prioritize this in the future. In the meantime, I would suggest creating separate apps in App Center for each environment. 

I know this isn't an ideal experience and our team is actually exploring an App Projects concept (not exactly what you're asking for) to help users better manage their multi-platform apps or their apps with multiple environments. You can follow our [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) and [iteration plan](https://github.com/Microsoft/appcenter/wiki/Iteration-Plans) to see the progress if you're interested. 

Thanks!

**Comment by mike14u** [comment]
Hi @winnieli1208 

This is sad to hear, well it could really be a big help for my team if this is actually implemented and it is also quite simple implementing it on a technical perspective. Anyways I wouldn't go about doing the suggested workaround of creating separate apps for a single app that we have just to cater the environments, will just have to wait till this request or a similar solution goes into AppCenter.

**Comment by winnieli1208** [comment]
Reopening so we can keep track of this feature request.
