### ISSUE TITLE
Can't see symbol file in the AppCenter under /Distribute/Release. This is possible in HockeyApp next to the apk.

### ISSUE THREAD

**Issue by mikaelengver** [microsoft/appcenter#641]
**What App Center service does this affect?**
In the view Distribute/Releases it is not possible to download the symbol file. That is possible in HockeyApp.

**Describe the bug**
The symbol file is needed to be uploaded to Google Play Console when releasing, in order to get get better stacktraces from obfuscated code.

**To Reproduce**
1. Go to 'Distribute/Releases' 
2. Click on a specific release
3. Now it is not possible to download symbol file.

**Expected behavior**
Have the possibilty to download symbol file.

**Screenshots**
![image](https://user-images.githubusercontent.com/3327284/60258332-3a97e580-98d5-11e9-976f-74859efc3c12.png)

![image](https://user-images.githubusercontent.com/3327284/60258444-6fa43800-98d5-11e9-843a-a024f9415a48.png)

**Desktop (please complete the following information):**
chrome browser

**Comment by lumaxis** [comment]
@mikaelengver For Android apps, this should be possible, it will just be in the "Diagnostics" section. Have you checked under https://appcenter.ms/users/larsa71/apps/Fotbollskanalen/crashes/mappings ?

**Comment by mikaelengver** [comment]
Thanks @lumaxis
