### ISSUE TITLE
Display the HResult as well as Message for TrackErrrors

### ISSUE THREAD

**Issue by ndastur** [microsoft/appcenter#642]
**Describe the solution you'd like**
In the track errors tab the Exception Message is shown, but it would be useful for the HResult value to be shown too.

**Describe alternatives you've considered**
I currently have to add a dictionary item for every call to trackerror

**Additional context**
Some handled exception reports could be managed better by checking in code. At the moment I would have to do a string compare on the message which seems like a bad way to implement checking. int compare would be better and so showing me the int value would help

**Comment by winnieli1208** [comment]
Thanks for the feature request! We don't have immediate plans to address this but we'll incroporate this feedback into our planning and post here with any updates. 

I understand attaching custom properties to your errors might not be an ideal solution but that's the best suggestion I have at the moment. Thanks!
