### ISSUE TITLE
internal_server_error 500

### ISSUE THREAD

**Issue by ernesto-handy** [microsoft/appcenter#644]
**What App Center service does this affect?**
Name of service or sdk with the issue.
Handy Sales

**Describe the bug**
I pushed the QA branch and worked fine, then I pushed the master branch and I am getting an internal_server_error, here is the screenshot
![image](https://user-images.githubusercontent.com/46498948/60293552-ac276200-98dc-11e9-9c86-69404bcab213.png)

**To Reproduce**
1.- Build the branch
2.- It´s fails
3.- See the error

**Expected behavior**
It should build

**Screenshots**
I included an image above

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 75.0.3770.100 (Build oficial) (64 bits)

**Comment by DennisPan** [comment]
@ernesto-handy This could be a transient error. Do you mind trying again? If it persists, I'd suggest reach out to support (via App Center portal) so that we can look into your app's specifics. The support ID there will also be helpful. I'd suggest copy that and provide it to support.

**Comment by kumartc** [comment]
> **What App Center service does this affect?**
> Name of service or sdk with the issue.
> Handy Sales
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> I pushed the QA branch and worked fine, then I pushed the master branch and I am getting an internal_server_error, here is the screenshot
> ![image](https://user-images.githubusercontent.com/46498948/60293552-ac276200-98dc-11e9-9c86-69404bcab213.png)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1.- Build the branch
> 2.- It´s fails
> 3.- See the error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> It should build
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> I included an image above
> 
> **Desktop (please complete the following information):**
> 
> * OS: iOS
> * Browser: Chrome
> * Version 75.0.3770.100 (Build oficial) (64 bits)

Hi @ernesto-handy  Did you fix that one!
