### ISSUE TITLE
Changing platform of existing project (e.g. ObjC/Swift -> Xamarin.iOS)

### ISSUE THREAD

**Issue by arek-avanade** [microsoft/appcenter#645]
**Describe the solution you'd like**
I have 2 apps in AppCenter which were originally created as native iOS and Android apps (Swift and Kotlin, respectively). Later we decided to switch to Xamarin.Android and Xamarin.iOS. Unfortunately it's not possible now to change the platform in AppCenter once the app is created.

**Describe alternatives you've considered**
As an alternative, I would need to create new apps in AppCenter, but this means I need to invite members again and I would not be able to have release history in one place.

**Comment by jBijsterboschNL** [comment]
Are there already plans for implementing this? As inside the App Settings page on App Center it states "Editing OS and Platform will be supported soon.".

**Comment by blparr** [comment]
Hi @jBijsterboschNL and @arek-avanade ! Thanks for your feature request. This is not in our near-term plans, unfortunately. It is however, a great suggestion, so we will work to see when it can get added to our backlog. 

Thanks a lot,
Blanca

**Comment by rjschnorenberg** [comment]
This is a useful feature for people who have been using UWP as their platform in order to track their WPF/WinForms applications and need to change it to the correct platform now that WPF/WinForms are supported.

**Comment by kpatwa** [comment]
This is going to be really helpful. I have the same scenario like **@arek-avanade** mentioned.

**Comment by alexeSGN** [comment]
Migrated HockeyApp Apps seem to default to the OS native platform types, which hides managed errors reported by the App Center Unity SDK on the app Diagnostic page. Platform switching should be enabled for all projects, or facilitated (and explained) during migration.

**Comment by lauri-rovio** [comment]
Would like to be able to change platform for existing projects as we have many apps with wrong platform type after migration from HockeyApp.

**Comment by derpixeldan** [comment]
@lauri-rovio please reach out to us, we can fix it for you.

**Comment by jacksonkr** [comment]
We started a React Native project that we then wanted to move to web so we ported it over to ReactJS yet AppCenter still thinks the app is a React Native app.

It looks like talented developers setup this portal so I have a hard time understanding why switching the app type isn't simpler - which is suspect to say the least.

**Comment by matheus-inacio** [comment]
I've migrated my app from HockeyApp and for some reason it is set as WPF instead of UWP. Now i can't upload the .appxsym necessary to get a proper error/crash report.

Since it doesn't seems like this feature (changing platform) will be implemented any time soon, can we at least have a documentation page on github with instruction on how/who to contact (with an email or something) in order to get this problem solve.

**Comment by varbex** [comment]
Any news on this feature? wanted to change a project platform and its just not possible yet.

**Comment by paulstelzer** [comment]
Same here :D Switched from Cordova to another platform, but cannot change it, so the message for deprecated cordova still appear although we are not using it anymore

**Comment by Daniel-Frid** [comment]
Any news on this one? This would really be an appreciated feature.

**Comment by iolabs-will** [comment]
Would like this feature!

**Comment by olmin** [comment]
I have the same problem :-(
