### ISSUE TITLE
Support for testing in Norwegian on iOS devices

### ISSUE THREAD

**Issue by rickarddahlffcg** [microsoft/appcenter#646]
**Describe the solution you'd like**
When doing ui testing on iOS, I'd like to be able to use Norwegian as system language ('nb-NO'). Currently, this language is not among the selectable languages.

**Comment by jwhiteDev** [comment]
@rickarddahlffcg my understanding is this is actually supported today, though not provided in the default dropdown. Update your CLI upload to be -locale "nb_NO".

What I don't remember is if you need to sideload that localization settings as well, but I think it may work with just the above as it will set the device settings. If it does not work could you email support@appcenter.ms or open a ticket from our portal? Our team should be able to help with this.

**Comment by Oddj0b** [comment]
@rickarddahlffcg did you get it to work?

**Comment by rickarddahlffcg** [comment]
Yes, it works 😊 Thanks!

Vänligen,
Rickard

[cid:image002.png@01D43AE6.2A049720]
Rickard Dahl
FOREFRONT CONSULTING GROUP
Ågatan 35 / 582 20 Linköping
+46 702 80 17 69 / www.ffcg.se<http://www.ffcg.se/>


Från: Villars Gimm <notifications@github.com>
Svara till: microsoft/appcenter <reply@reply.github.com>
Datum: måndag 1 juli 2019 09:33
Till: microsoft/appcenter <appcenter@noreply.github.com>
Kopia: Rickard Dahl <rickard.dahl@ffcg.se>, Mention <mention@noreply.github.com>
Ämne: Re: [microsoft/appcenter] Support for testing in Norwegian on iOS devices (#646)


@rickarddahlffcg<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frickarddahlffcg&data=02%7C01%7Crickard.dahl%40ffcg.se%7Cf2c22057ae53408546bc08d6fdf66a14%7C481cb5c3c38b45ce976a32cfaad9c160%7C0%7C0%7C636975632120290666&sdata=GZRn0tsLp3Two4Tl2DQDgh%2FLiJjXgeVD29rn6N2gAtI%3D&reserved=0> did you get it to work?
