### ISSUE TITLE
Please support server level badge function and support on cordova project

### ISSUE THREAD

**Issue by faulfish** [microsoft/appcenter#647]
**Describe the solution you'd like**
Keep badge number in server side
setBadge()
resetBadge()

**Describe alternatives you've considered**

**Additional context**

**Comment by amchew** [comment]
Hey @faulfish, apologies for the late reply. Mind if you elaborate more on what you mean by badge number and your user scenario please? Is this the build badge number?

**Comment by jwargo** [comment]
@faulfish I agree with @amchew; I would like to know more about what you're looking for. We haven't had a lot of customers asking for badge tracking, I always assumed you would just track this on the backend with the rest of your app data. What's the use case for pushing this storage up to App Center?

**Comment by jwargo** [comment]
@faulfish please?

**Comment by faulfish** [comment]
In my case, we send the same message to many device, just like news. I need to send badge count (+1) to everyone. So I don't need to record count for anyone. The count will keep in server side (appcenter side). I call it server badge count. In the case, it'll easy to show correct badge count without any app/server implement loading.

**Comment by jwargo** [comment]
@faulfish OK, thanks for the clarification - in my initial review, I didn't realize you wanted this as a system-wide setting.

**Comment by jwargo** [comment]
@faulfish Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
