### ISSUE TITLE
[Feature] Add filter option for failed tests

### ISSUE THREAD

**Issue by rmarinho** [microsoft/appcenter#649]
**Describe the solution you'd like**
When i visit a test run i can filter for the failed tests

**Describe alternatives you've considered**
We should have a icon to filter for passed and failed tests, i think when we have more than 1 device there's a filter altered , so use something similar for this screen

**Additional context**
I have 2 failed in almost 600, is impossible to get to the failures from this screen 
/testseries/testrun
![image](https://user-images.githubusercontent.com/1235097/60373560-81323080-99f8-11e9-9041-2dbc3ca20aab.png)

**Comment by Oddj0b** [comment]
Thanks for the feedback @rmarinho, let's hope we can get more reactions.

**Comment by PureWeen** [comment]
This is also important because even doing a page search doesn't work to locate down to the failed test

![image](https://user-images.githubusercontent.com/5375137/60530898-06e30400-9cb7-11e9-980c-2d8b02d417c7.png)
