### ISSUE TITLE
Builds independent of branches

### ISSUE THREAD

**Issue by mike14u** [microsoft/appcenter#65]
**Describe the solution you'd like**
A way for us to create builds without having to rely on repository branches e.g. similar to Azure DevOps.

**Describe alternatives you've considered**
I have tried Azure DevOps but AppCenter is mobile apps friendly, so if we can achieve the same solution it would be a big win.

**Comment by lupiter** [comment]
This is a deal breaker for us. Having to go into appcenter and add every feature branch is just not going to fly.

**Comment by sdinnes** [comment]
Likewise, during development we operate from feature branches; it would be greatly beneficial to be able to choose which branch for a build. instead of having to create a new app every time it changes.  It would mean continuity of the build number as well!

**Comment by umair-me** [comment]
Really need this! Similar to how its done on Azure DevOps where we select a branch for building.

**Comment by DrBeak1** [comment]
+1

**Comment by TJTorola** [comment]
We've managed to work around this by setting up long lived "App Center" branches, like `ac-staging` and `ac-production` that we have configured for their appropriate environments. Then we just force push to those in order to kick off the build process without ever needing to re-configure app center. It's pretty hacky, but it's gotten the job done.

**Comment by zarko-via** [comment]
Makes much sense to us also, branch first is strange for manual ad hoc builds.
We will want to create a build configuration and then select what branch to compile.
Also make sense to keep builds history for a config, currently when a branch dies also the unpublished builds die with it.

**Comment by dgobaud** [comment]
please!!

**Comment by zarko-via** [comment]
Most "right" use cases for building is one branch of code in time that one wants from it a Development variation and another Production variation.
App Center current flow mandate creating more and more branches and basically to double it up to have this basic functionality of build variations (this also doubles the Git work and sync work).

**Comment by artdent** [comment]
Still an issue
