### ISSUE TITLE
Push: Support local pushes

### ISSUE THREAD

**Issue by janpieterz** [microsoft/appcenter#651]
Using React Native, it'd be great to be able to trigger local pushes through the one library instead of having to resort to react-native-push-notification to trigger a local push if it's received while the app is in the foreground. This'd ideally include a notification sound.

**Describe alternatives you've considered**
Alternative would be to use another library to trigger local push notifications.

**Comment by jwargo** [comment]
@janpieterz what do you mean by `local pushes`?

**Comment by janpieterz** [comment]
On iOS it's this API for example:

https://developer.apple.com/documentation/usernotifications/scheduling_a_notification_locally_from_your_app

This would allow scheduling as well as triggering a native notification while the app is in foreground (getting native, default sound set by user etc).

**Comment by jwargo** [comment]
@janpieterz OK, but from that example, that's just code your app executes to submit a scheduled or local notification. It's on-device, doesn't use an external service or even make a call to APNS to do it as far as I can tell.

**Comment by janpieterz** [comment]
@jwargo Correct, yeah, I don't think it requires any network.

**Comment by jrahma** [comment]
I think this will be part from Xamarin Essentials but if not then it will be great to have it from App Center

**Comment by jwargo** [comment]
@jrahma but what's the task here for App Center Push? There's already an API for this in the local OS, all that you'd need is a React Native extension/plugin that exposed a common API. 

I'm not seeing what value add we provide in this scenario.

**Comment by jrahma** [comment]
@jwargo there is always things on Native John and all the things available on Xamarin Essentials for example are still possible to have on Native.. but there is always a space for improvement and making things easier for developer and that is the purpose of having Xamarin Forms :)

**Comment by jwargo** [comment]
@jrahma I'm not sure that answers the question. I'm trying to understand what the purpose is of doing this in App Center. This is a purely client-side API that has nothing to do with any of the App Center services.
