### ISSUE TITLE
Support Application Map view when using Application Insights integration

### ISSUE THREAD

**Issue by yaprigal** [microsoft/appcenter#652]
**Describe the solution you'd like**
When I am exporting the telemetry to Application Insights from my mobile app. If my app is working with Azure back-ends (like: storage, tables, cosmos-db, azure sql) 
I would like to have the visibility of all my dependencies using the Application Map feature in the Application Insights.
The current situation is that when I am going into the Application Insights service -> Application Map - I don't see anything.

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by hamswan** [comment]
When Analytics data from Appcenter is exported to Application Insights, only the "Usage" section is pertinent for mobile apps.
