### ISSUE TITLE
Build config not saved when clicking outside panel

### ISSUE THREAD

**Issue by ghost** [microsoft/appcenter#654]
**What App Center service does this affect?**
AppCenter build config

**Describe the bug**
When configuring app build if I accidentally click outside the build panel, it close loosing all the settings inserted and I've to refill all the info. if a click outside build panel occours and current config is not saved would be nice to have an alert that say "Would you save settings before exit ?"

**To Reproduce**
1. Add a new app
2. Configure a source
3. Open config panel
4. Add some config
5. Click outside the config panel
6. ReOpen config panel

**Expected behavior**
A warning message that says that the are unsaved changes

**Screenshots**
![Schermata 2019-07-01 alle 10 04 28](https://user-images.githubusercontent.com/37268333/60420297-b18bf180-9be7-11e9-8460-6f1916e5f732.png)

**Comment by DennisPan** [comment]
@stefano-corricelli This is the current design. Hence I removed the "bug" label. Following up with design team to see if any additional comments to be added.
