### ISSUE TITLE
Events page in Analytics not loading in Safari

### ISSUE THREAD

**Issue by djyates** [microsoft/appcenter#655]
**What App Center service does this affect?**
Events page in Analytics.

**Describe the bug**
The page does not load in the Safari browser.

**To Reproduce**
1. Submit events in your app.
2. Go to Analytics > Events in Safari browser.
3. See progress bar never reaches the end and the page never loads.

**Expected behavior**
That the events page loads on the Safari browser, as it does on Chrome.

**Desktop:**
 - OS: macOS 10.14.5
 - Browser: Safari
 - Version: 12.1.1

**Comment by hamswan** [comment]
@djyates Can you send us an email to support@appcenter.ms and also provide details of your Application such as the app secret.

**Comment by yoannchaudet** [comment]
Are you using an ad blocker by any chances (in Safari)? This could be related to: https://github.com/microsoft/appcenter/issues/455.

**Comment by djyates** [comment]
> Are you using an ad blocker by any chances (in Safari)? This could be related to: #455.

Yes, and turning it off for AppCenter.ms has fixed the issue.

As there is already an issue open for this, I will close this one.

Thanks for you help - much appreciated.
