### ISSUE TITLE
Getting error during Android & iOS build since App Center Distribute updated to version 3.154.1

### ISSUE THREAD

**Issue by qwerqy** [microsoft/appcenter#656]
**What App Center service does this affect?**
App Center Distribute v3.154.1

**Describe the bug**
on Android (we seem to have found out the issue in iOS as it shows the erorr message clearly):
```
==============================================================================
Task         : App Center distribute
Description  : Distribute app builds to testers and users via Visual Studio App Center
Version      : 3.154.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
==============================================================================
##[warning]Cannot find any file based on /Users/vsts/agent/2.153.2/work/1/a/mapping/**/mapping.txt.
##[error]"{\"message\":\"Forbidden\",\"statusCode\":403,\"code\":\"Forbidden\"}"
http response code: 403
```

**To Reproduce**

**Expected behavior**
I noticed the past builds that were successful, App Center distribute was at version 3.150.1 .
Once the version bumped to 3.154.1, thats where the builds began to fail. 
After looking into the chain of failed builds i noticed they all share the similar version 3.154.1

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: Chrome v75

**Additional context**
the project is built on react native after ejecting from expo. 
appcenter npm version is 1.8.1

**Comment by qwerqy** [comment]
Hi, i resolved the issue. I built a post-build script based on the comment https://github.com/microsoft/appcenter/issues/75#issuecomment-493184790 . From there, the error still shows, but now it also shows what is wrong. turns out my dev team did not set a destination for the new config.

**Comment by DennisPan** [comment]
@qwerqy Are you distributing to distribution groups or store? Likely there is some improvements we can make in the task, at least for better error message.

**Comment by guschilds** [comment]
We've started getting these errors within the last 2 days on all iOS builds. The first failure on a branch will involve a 404 and all subsequent errors are 403s. Both are pasted below.

```
##[section]Starting: Create distribution
==============================================================================
Task         : App Center distribute
Description  : Distribute app builds to testers and ***s via Visual Studio App Center
Version      : 3.154.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
==============================================================================
##[error]"{\"message\":\"Not found. Context ID: d4b8ab79-f48c-42e4-9047-50a07276c3fe\",\"statusCode\":404,\"code\":\"Not Found\"}"
http response code: 404
##[section]Finishing: Create distribution
```

```
##[section]Starting: Create distribution
==============================================================================
Task         : App Center distribute
Description  : Distribute app builds to testers and ***s via Visual Studio App Center
Version      : 3.154.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
==============================================================================
##[error]"{\"message\":\"Forbidden\",\"statusCode\":403,\"code\":\"Forbidden\"}"
http response code: 403
##[section]Finishing: Create distribution
```

This is happening on 3 different branches and all Android builds still work. The iOS builds do not share code in a way that would have caused all of these to start failing at the same time. It also did not correspond with a bump in App Center Distribute, as this issue suggests, because we've had plenty of successful builds on `3.154.1`. I've contacted App Center support, but was only pointed to this issue.

Any chance anyone would have insight into this? Thanks in advance!

**Comment by DennisPan** [comment]
@guschilds Most likely the user who originally setups the build lost access to the app. Do you mind reach back to customer support and ask to have the ticket transfer to me? I can help work with support to take a deeper look

**Comment by qwerqy** [comment]
> @qwerqy Are you distributing to distribution groups or store? Likely there is some improvements we can make in the task, at least for better error message.

apologies for the late reply. we distribute to store.

**Comment by DennisPan** [comment]
@qwerqy hmm... that's odd. I double-checked configuring a build with distribution or use the Azure DevOps task directly in an Azure DevOps account. Both require selecting a destination.

**Comment by qwerqy** [comment]
> @qwerqy hmm... that's odd. I double-checked configuring a build with distribution or use the Azure DevOps task directly in an Azure DevOps account. Both require selecting a destination.

Are you saying an error will show saying that the user has selected the option to use Store but did not specify destination right after clicking Save/Save & Build? i do not recall facing that warning.

**Comment by DennisPan** [comment]
@qwerqy You shouldn't be able to save the build configuration without specifying a destination. Could you try to reproduce that (save without having a destination)?

**Comment by Ajaykumar02** [comment]
I am currently facing the issue on 
Task         : App Center distribute
Description  : Distribute app builds to testers and ***s via Visual Studio App Center
Version      : 3.160.0
Author       : Microsoft Corporation

this is the error it is showing for the latest merged pull requests.
##[error]"{\"message\":\"Not found. Correlation ID: ea022ec3-aaa-bbb...\",\"statusCode\":404,\"code\":\"Not Found\"}"


can anyone help on this?

**Comment by wellavelino** [comment]
Same error here :( 
com.betomorrow.gradle.appcenter.infra.AppCenterUploaderException: Can't prepare release upload, code=401, reason={"message":"Not found. Correlation ID  (TOKEN),"statusCode":401,"code":"Unauthorized"}

**Comment by phanthelam** [comment]
@wellavelino  i'm having same issue,Do you have any solution ??

**Comment by andrew-skrypnyk** [comment]
same error here:
```##[error]"{\"message\":\"Not found. Correlation ID: 5e2cf393-650e-4ea5-b713-6e3759573be9\",\"statusCode\":404,\"code\":\"Not Found\"}"```

**Comment by DennisPan** [comment]
Most likely the user who originally setup the build configuration lost access to the app. Re-save the configuration may fix it. If not, please reach out to support who will need your app information to investigate.

**Comment by andrew-skrypnyk** [comment]
@DennisPan thanks, solved ✅

**Comment by AadilMehrajBhat** [comment]
@DennisPan Can you elaborate a little about what do you mean by re-saving build configuration?

**Comment by DennisPan** [comment]
@AadilMehrajBhat Open the build configuration then click "Save" or "Save & Build"

**Comment by AadilMehrajBhat** [comment]
I had two app in my account that I transferred to organisation account, then I delete the former two apps in my account bt  now my apps in orgz. are listed bt all the other build, distribute page shows error

`code: "Not Found"
message: "Not found. Correlation ID: d34f056e-a6e1-42f3-adc5-d18c8f0a02a9"
statusCode: 404`

**Comment by josoma03** [comment]
Check that the "APP ID" is correct

**Comment by dikako** [comment]
if your problem to upload .apk to app center with jenkins `403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}
`
Solution:
You Must Change **App Name** on your **Jenkins Configuration** sama with your **App Center Project**

References : https://www.logcg.com/en/archives/3290.html

**Comment by miktav** [comment]
I was getting the same error today trying to upload an .ipa built in Azure DevOps to App Center:

##[error]"{\"message\":\"Not found. Correlation ID: 7fc91062-2788-4118-b062-72bf8d76675b\",\"statusCode\":404,\"code\":\"Not Found\"}"

Previously this same upload had been working without issues for months. 

I noticed in App Center > Settings > App API Tokens that there were no API tokens. I followed the steps here to add an API token: https://docs.microsoft.com/en-us/appcenter/api-docs/. I then created a new Service Connection in Azure DevOps with this API token, and changed my build to use the new service connection. That fixed the issue for me.

**Comment by jedicoder88** [comment]
Getting the same issue, already tried a API token and User Token with no difference. Still getting this error:
##[error]"{\"message\":\"Resource not found: /v0.1/apps/https://appcenter.ms/users/{user name}/apps/{app name}/release_***s. Correlation ID: de46694e-bf0f-4b30-8fd9-460d109c092e\",\"statusCode\":404,\"code\":\"Not Found\"}"

Does anybody have a solution. Already tried re-saving the configuration as well

**Comment by mdenieffe** [comment]
I was getting the same error and turns out that my 'App Slug' was incorrect, I was only supplying the **{app_identifier}**

It has to be in the format of either:

**{username}/{app_identifier}**

Or if you using an Azure organisation

**{orgname}/{app_identifier}**

Hope this helps...

**Comment by pqtuan86** [comment]
> Most likely the user who originally setup the build configuration lost access to the app. Re-save the configuration may fix it. If not, please reach out to support who will need your app information to investigate.

For me, this comment has shed some light on my case, turns out the APP_API_TOKEN is suddenly invalid and i lost access to the app.
To solve it, i have to create a new App API token and use it when making api call.

**Comment by creativemind1** [comment]
> Most likely the user who originally setup the build configuration lost access to the app. Re-save the configuration may fix it. If not, please reach out to support who will need your app information to investigate.

This has fixed for me as well. After stumbling for so many hours, it's finally fixed for me.
