### ISSUE TITLE
failed with return code: 65 react native

### ISSUE THREAD

**Issue by PrathyushaPeddakadiri** [microsoft/appcenter#657]
Hi, trying to the build app from appcener but it is showing this error.

CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/BuyBackBazaar-fbiwenairxllrraonosawxtlxjfa/Build/Intermediates.noindex/ArchiveIntermediates/BuyBackBazaar/IntermediateBuildFilesPath/React.build/Release-iphoneos/double-conversion.build/Objects-normal/armv7/strtod.o /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/strtod.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target: double-conversion)
    cd /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/React
    export LANG=en_US.US-ASCII
    /Applications/Xcode_10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu++11 -stdlib=libc++ -fmodules -fmodules-cache-path=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wmissing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter ...
error: Build input file cannot be found: '/Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/strtod.cc'

CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/BuyBackBazaar-fbiwenairxllrraonosawxtlxjfa/Build/Intermediates.noindex/ArchiveIntermediates/BuyBackBazaar/IntermediateBuildFilesPath/React.build/Release-iphoneos/double-conversion.build/Objects-normal/armv7/fixed-dtoa.o /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/fixed-dtoa.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target: double-conversion)
    cd /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/React
    export LANG=en_US.US-ASCII
    /Applications/Xcode_10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu++11 -stdlib=libc++ -fmodules -fmodules-cache-path=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wmissing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter ...
error: Build input file cannot be found: '/Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/fixed-dtoa.cc'

CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/BuyBackBazaar-fbiwenairxllrraonosawxtlxjfa/Build/Intermediates.noindex/ArchiveIntermediates/BuyBackBazaar/IntermediateBuildFilesPath/React.build/Release-iphoneos/double-conversion.build/Objects-normal/armv7/fast-dtoa.o /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/fast-dtoa.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target: double-conversion)
    cd /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/React
    export LANG=en_US.US-ASCII
    /Applications/Xcode_10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu++11 -stdlib=libc++ -fmodules -fmodules-cache-path=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wmissing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter ...
error: Build input file cannot be found: '/Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/fast-dtoa.cc'

CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/BuyBackBazaar-fbiwenairxllrraonosawxtlxjfa/Build/Intermediates.noindex/ArchiveIntermediates/BuyBackBazaar/IntermediateBuildFilesPath/React.build/Release-iphoneos/double-conversion.build/Objects-normal/armv7/double-conversion.o /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/double-conversion.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target: double-conversion)
    cd /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/React
    export LANG=en_US.US-ASCII
    /Applications/Xcode_10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu++11 -stdlib=libc++ -fmodules -fmodules-cache-path=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wmissing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter ...
error: Build input file cannot be found: '/Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/double-conversion.cc'

** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/BuyBackBazaar-fbiwenairxllrraonosawxtlxjfa/Build/Intermediates.noindex/ArchiveIntermediates/BuyBackBazaar/IntermediateBuildFilesPath/React.build/Release-iphoneos/double-conversion.build/Objects-normal/armv7/strtod.o /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/strtod.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/BuyBackBazaar-fbiwenairxllrraonosawxtlxjfa/Build/Intermediates.noindex/ArchiveIntermediates/BuyBackBazaar/IntermediateBuildFilesPath/React.build/Release-iphoneos/double-conversion.build/Objects-normal/armv7/fixed-dtoa.o /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/fixed-dtoa.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/BuyBackBazaar-fbiwenairxllrraonosawxtlxjfa/Build/Intermediates.noindex/ArchiveIntermediates/BuyBackBazaar/IntermediateBuildFilesPath/React.build/Release-iphoneos/double-conversion.build/Objects-normal/armv7/fast-dtoa.o /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/fast-dtoa.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/BuyBackBazaar-fbiwenairxllrraonosawxtlxjfa/Build/Intermediates.noindex/ArchiveIntermediates/BuyBackBazaar/IntermediateBuildFilesPath/React.build/Release-iphoneos/double-conversion.build/Objects-normal/armv7/double-conversion.o /Users/vsts/agent/2.153.2/work/1/s/node_modules/react-native/third-party/double-conversion-1.1.5/src/double-conversion.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65

 - OS: iOS
 - Browser: Google Chrome

Can you guys please help me out!!

**Comment by DennisPan** [comment]
@PrathyushaPeddakadiri Please reach out to support via App Center portal about this. We can collect more details of your app and build for a deeper look.
