### ISSUE TITLE
No error shown why push notification is not sent

### ISSUE THREAD

**Issue by divyamakkar26** [microsoft/appcenter#658]
**What App Center service does this affect?**
Name of service or sdk with the issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jwargo** [comment]
@divyamakkar26 thanks for this, but can you please provide a detailed description of the issue? We provided the issue template for you to populate with the data we need to understand the problem.
