### ISSUE TITLE
Robot Framework + Appium support for Automated Testing

### ISSUE THREAD

**Issue by mike14u** [microsoft/appcenter#66]
**Describe the solution you'd like**
Since we already have appium support in AppCenter, I would like to suggest an integration with RobotFramework that can run automated tests using an Appium Server.

**Describe alternatives you've considered**
Haven't considered any alternatives.

**Comment by CmosII** [comment]
I'd like to renew this request.

**Comment by vitorandrietta** [comment]
me too, this will come in handy for my company projects.

**Comment by neothXT** [comment]
Same here. It'd be very much anticipated to have the possibility to upload RobotFramework tests to AppCenter

**Comment by lofi96** [comment]
same here. this feature would be very helpful!

**Comment by IlyaBausovAkvelon** [comment]
Hi All! Thanks for reaching out.
We are not planning to add support for this in the near future.
