### ISSUE TITLE
AppCenter Data Support for macOS

### ISSUE THREAD

**Issue by vineetchoudhary** [microsoft/appcenter#662]
Is there any planning to bring **[AppCenter Data](https://docs.microsoft.com/en-us/appcenter/data/)** for **macOS**?

**Comment by Zakeelm** [comment]
While we currently don’t have any plans to share regarding macOS support for Data, it’s something we can definitely look into if enough people are interested. I will leave this thread open for visibility, in case others are interested as well!

**Comment by Zakeelm** [comment]
I’m very curious about your scenario though. Could you elaborate on how you plan to use data with macOS support and what you would be trying to accomplish?

**Comment by Zakeelm** [comment]
Closing this for now, as we don't have immediate plans to support macOS. We can revisit this in the future given enough interest!
