### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Gabrielstabile** [microsoft/appcenter#663]
**What App Center service does this affect?**
Name of service or sdk with the issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kpiteira** [comment]
Please provide more details. Closing this for now.
