### ISSUE TITLE
Please release a native AppCenter.app equivalent to HockeyApp.app for macOS

### ISSUE THREAD

**Issue by sseyod** [microsoft/appcenter#664]
**Describe the solution you'd like**
An AppCenter replacement for the HockeyApp.app native client for macOS

NB I'm sure I've seen this requested more than once; sorry if this request is a duplicate.

**Describe alternatives you've considered**
The CLI interface to AppCenter is a *real* pain to use - look at https://github.com/Microsoft/appcenter-cli, there are no examples on how to do things; the documentation is pretty much non-existent.

When using HockeyApp.app; when an export completes in Xcode, the build is presented *automatically* in HockeyApp.app window; all I need to do is select distribution and add some release notes, and the .app and accompanying symbols are uploaded automatically. This is *so* easy. HockeyApp.app also allows me to upload from a history of the builds on the hosting mac - again, this is brilliantly easy to use.

When I open an apl file for Android;  the build is presented automatically in HockeyApp.app window; all I need to do is select distribution and add some release notes, and the .app its uploaded automatically. This is *so* easy. Furthermore, I can see no reason why you couldn't add some "smarts" to build and upload the symbols.zip for any included .so files automatically.

**Additional context**
Nothing to add here.

**Comment by derpixeldan** [comment]
@sseyod unfortunately it's not on our current roadmap so it won't work anymore after the shutdown. I would like to understand better what is so bad about the [CLI](https://github.com/microsoft/appcenter-cli) all the commands are either documented in the repo or in the tool itself and it provides you with the usage pattern. Are you looking for specific examples?

**Comment by sseyod** [comment]
Hi - sorry for the delay in reply, but I've been on holiday.

It is a *really* great shame that the native UI as suggested isn't on your roadmap - for many people, a GUI like this is simply the easiest way to work - scripts appeal to some people / developers, but not to all.

Anyhow: I looked at the CLI documentation and simply couldn't figure-out how to do what I wanted. If you look at the CLI document from the perspective of a developer such as myself with no knowledge of using your CLI, you'll see that the outer level commands are listed, but with no detailed information on how to use them (if this information is available, I can't see it!).

So far as I can tell, the only way to find out how to do things, would be to invest a lot of time in trial-and-error usage; my time is too short to do that. So yes, I think the documentation is probably missing a lot of example usages. I'd suggest that every command needs at least one concrete example. For what it is worth, I presume that Microsoft uses the CLI on a regular basis internally, so would hope that you could quickly populate a lot of examples with commentary as to what each example sets-out to do, and how the parameters in the examples map-on to that.

Anyhow: hoping this feedback helps! Pete

**Comment by mkubista** [comment]
I agree with @sseyod 
Im using native app most of the time when interacting with HoskeyApp.
The build upload isn't much pain on our main project - it is using automated build scripts, which uploads builds automatically with symbols and changelog. 
But we have other small projects which are distributed manually and Im not using anything else but Native Mac App.

Also Crash browser is much much better than crash browser in web app. 
In native app I can see summary of the app with number of crashes per version. On the website I must gues, which version and build is having some crashes and which not.... :(

When I select one version of app I can see what percentage of crashes and crashes groups are solved. On the web where is nothing like that. Even the states of the crashgroups are distinguished only by Status text, which is visually so small element, that the whole list of crashes is total mess... :(

And finally native app can link the version of app to its git repository - so one can see relevant code lines with whole the sourcecode around. In Appcenter I must download the crash as text, rename the file to having .crash extension and open it in xcode manually. Also I must have the right branch checkouted...

So Im really disappointed and dont understand, why the whole service has been redesigned and rewritten so much with cutting good features out :(

The native app was one of the main feature, why we were using HockeyApp. Now the feature will be gone.

**Comment by kjteske** [comment]
We also use the native app a lot - especially for viewing stack traces linked to the git repository with relevant code.

**Comment by smpeleato** [comment]
+1 for this. I really value the native app, especially for reviewing crash reports, and it'll be a big loss when it's not available.
