### ISSUE TITLE
Problems with uitests when running tests in Appcenter #bug

### ISSUE THREAD

**Issue by bjodybvi** [microsoft/appcenter#665]
Hi,

My name is Bjorn Arne Dybvik. I work in a company called Skog-Data as an developer.

I have created an app which I want to test in Appcenter. The app runs on both IOS and Android but for now I only wants to test it on Android devices.
In my project I have created an UITest-project which runs some simple tests on the UI and I use the following command to run the tests:

"appcenter test run uitest --app "skog-data/TrSjafor" --devices "skog-data/skogdataandroid" --app-path C:/Users/bad/Downloads/no.vsys.trdriver.apk --test-series skogdataandroid--locale "en_US" --build-dir C:\Users\bad\source\repos\TrSjaafor\TrApp\UITestProjectAndroid\bin\Release"

Every thing seems to go OK but the tests always fails whatever I do.

I have added the test logfile below. Can you please help me figure out what is the problem?

Kind regards
Bjorn Arne Dybvik
 
[TestresultAppcenter.txt](https://github.com/microsoft/appcenter/files/3353826/TestresultAppcenter.txt)

**Comment by bjodybvi** [comment]
Hi, Any progress in this case?

**Comment by King-of-Spades** [comment]
Hi, I noticed in the logs it looks like there's error of some kind during either the installation or the app startup:
> SetUp : System.Exception : Failed to execute: /Volumes/Data/xamarin/pipeline/versions/478a9ece8421fbdd147bc96c16fce1d4b9ec0f87/adt/sdk/platform-tools/adb_uitest -s ecc0dc24 install -g "/xamarin/workspaces/a4b5563a-1a09-45c7-ae3c-5b31dc60ad9a/workspace/app.apk" - exit code: 1

Based on this I have some questions:
1. Does your test suite work locally?
2. For your local test suite, are you running on an emulator or a physical device?
3. What is the Android version and model for the emulator/device you're running on locally?
4. What is the Android version and model of the device(s) you're running on in App Center?
5. Has this app or test suite worked for you in the past in App Center Test? If they have worked before, was it on the same device/model you were targeting here? 
6. Are you able to reproduce the symptoms using this sample? https://github.com/King-of-Spades/AppCenter-Samples/tree/master/Xamarin.UITest/UITestDemo

**Comment by King-of-Spades** [comment]
Since this was a bug report, I want to clarify that if further help is needed you can reach out to AppCenter support by logging into https://appcenter.ms/apps and clicking the chat icon in the lower right corner of the screen. https://www.screencast.com/t/uF8S5o0o0
