### ISSUE TITLE
Support custom notification type show in status bar when app in then foreground

### ISSUE THREAD

**Issue by faulfish** [microsoft/appcenter#666]
**Describe the solution you'd like**
Support custom notification type show in status bar when app in then foreground

**Describe alternatives you've considered**
Need different mode for UX

**Additional context**

**Comment by jwargo** [comment]
@faulfish thanks for the suggestion, can you share some more details? What platforms are you looking for here?

**Comment by jwargo** [comment]
@faulfish Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
