### ISSUE TITLE
Support BitBucket issue tracker

### ISSUE THREAD

**Issue by pfandrade** [microsoft/appcenter#667]
**Describe the solution you'd like**
We’re migrating from HockeyApp which supports BitBucket as an issue tracker. 

Appcenter doesn’t support BitBucket for issue tracking but all of our code and issues are on BitBucket. This is really important for a smooth migration.

To make matters worse, the current HockeyApp integration with BitBucket is failing due to API changes…

**Describe alternatives you've considered**
None.

**Comment by winnieli1208** [comment]
Thanks for the feature request! We don't have immediate plans to address add support for BitBucket but I'll keep the issue open to track interest. We understand this is an important feature and I'll post here if I have any updates.

**Comment by pfandrade** [comment]
Just wanted to add my +1 to thi, and also note that's a bit odd you support Bitbucket for source control but not issues.

PS: HockeyApp had support for issues as well.
