### ISSUE TITLE
More Details OS distribution analytics

### ISSUE THREAD

**Issue by InquisitorJax** [microsoft/appcenter#668]
#### Feature
It's great to know what your most popular OS distribution is, but one of the key decision points for app distribution is also what is the minimum OS to support - which requires analytics on what is the percentage of least popular OS.
For example, for iOS, if my analytics are showing that only 2% of my users are on iOS 8 and below, then I can consider making the minimum supported OS 9+ the next time I make a release.

**Comment by yoannchaudet** [comment]
You can actually get that information via our [REST API](https://openapi.appcenter.ms/#/analytics/Analytics_OperatingSystemCounts).

Our portal only display the top 4 OS but our API does not have this limitation.
