### ISSUE TITLE
Allow Automatic Rerun of Failed Tests

### ISSUE THREAD

**Issue by MrAusnadian** [microsoft/appcenter#670]
**Describe the solution you'd like**
I'd like to see Xamarin.UITest and App Center add support for the Retry attribute of NUnit so that failed tests are automatically retried a specified number of times or some other implementation for automatically retrying failed tests.

**Describe alternatives you've considered**
We've tried adding various levels of error handling into some of our tests, however, the ability to simply retry failed tests would be a lot easier and make our test code a lot cleaner by getting rid of try/catches and do/while loops.

**Additional context**
Here's how similar functionality is implemented in Visual Studio test steps in Build Pipelines:
![image](https://user-images.githubusercontent.com/9650258/60608967-78818780-9d75-11e9-9fb7-8c9fa5ab1a27.png)

NUnit wiki page about retry attribute:
https://github.com/nunit/docs/wiki/Retry-Attribute

**Comment by Oddj0b** [comment]
@MrAusnadian And the retry option should be in Azure DevOps or as part of the test script, just asking to be sure?

**Comment by MrAusnadian** [comment]
@Oddj0b I would like it to be an option in the App Center test UI.

**Comment by Naweap** [comment]
I would also really appreciate this feature for my test cases ? Do you have any updates on this ?

**Comment by will-gluwa** [comment]
Would still like this functionality
