### ISSUE TITLE
UWP Data support

### ISSUE THREAD

**Issue by petercustance** [microsoft/appcenter#673]
**UWP support for Data as per iOS/Android**
We are currently starting to use the Data preview. Our applications often have a UWP Windows version so Ideally we would like support for this in Data.

**Comment by JanabiSoft** [comment]
I agree with you, please app center team you are a Microsoft team and Microsoft frameworks should be first class.

**Comment by myokeeh** [comment]
Yes, please have Windows/UWP features available quickly--not an afterthought.

**Comment by skolesni** [comment]
Yes, please, this is required, especially in the Enterprise scenarios.

**Comment by TheJoeFin** [comment]
Is there any update on this issue? I am trying to decide if I should do my own thing or wait for AppCenter Data to come to UWP.

**Comment by winnieli1** [comment]
Hi @TheJoeFin this isn't on our short term roadmap and due to other priorities at the moment, we most likely won't get to this for at least another few months. I wish I could give you a better answer.

**Comment by myokeeh** [comment]
Great! Apparently, this has been tabled. Coming from "Azure Mobile Service" and don't have a clear replacement from Microsoft.
