### ISSUE TITLE
Support Azure Germany AD Federation

### ISSUE THREAD

**Issue by chrkaatz** [microsoft/appcenter#674]
**Describe the solution you'd like**
We are hosting our AD through the german Telekom Cloud and use that to authorize apps with AD Federation. Until 3 months ago, everything worked fine but not anymore. Whenever we invite a new user with his enterprise credentials we get an error message. I would love to have the AD Federation working properly again.

**Describe alternatives you've considered**
We can't move to another AD for our enterprise due to regulatory reasons.

**Additional context**
Support answer for additional context:
> Unfortunately, we do not support Azure Germany for the time being, and that prevents us from identifying your AD users during sign in. The only way to unblock you at the moment is to use a different (non-Telekom Cloud-hosted AD) account option for account creation and login.

**Comment by amchew** [comment]
Thanks for your feature request @chrkaatz! @iageoghe @blparr would you be able to take a look?

**Comment by blparr** [comment]
Hi @chrkaatz! Thanks for your patience, we are looking into this offline. We'll get back to you as soon as we have an update.

**Comment by blparr** [comment]
Hi again @chrkaatz! We would like to ask you some follow up questions - if you don't mind, we will be reaching out to you via the in-portal support to do so, and I'll be closing this issue to avoid duplication.

Thank you!

**Comment by amchew** [comment]
Thanks @blparr!
