### ISSUE TITLE
[Push] Show notifications permission dialog a second time

### ISSUE THREAD

**Issue by adrianknight89** [microsoft/appcenter#675]
**Describe the solution you'd like**
I'm using Xamarin Forms to send and receive push notifications. When the app is installed for the first time, executing `AppCenter.Start(typeof(Push));` is asking for push notifications permission. 

- My question is, what happens if the user decides not to allow this permission but `AppCenter` called the `Start()` method already? Do you internally stop this service?

- Second, is there a way to ask for this permission **again** by using your SDK? Calling `AppCenter.Start(typeof(Push));` a second time upon user action does not show the permission dialog again.

What I'm trying to accomplish is, if the user disallows notification permission and later on decides to allow it, I want to show the dialog popup again.

**Comment by lumaxis** [comment]
@adrianknight89 Did you already figure out answers to your questions? Let us know if there's still anything we can do!

**Comment by adrianknight89** [comment]
Yeah. I've found out iOS does not allow the same prompt to be shown again, so looks like there is nothing the SDK can do. Thanks!
