### ISSUE TITLE
Cannot connect to AppStore Connect

### ISSUE THREAD

**Issue by twittemb** [microsoft/appcenter#676]
**What App Center service does this affect?**
AppCenter website

**Describe the bug**
I want to connect an application to AppStore Connect to release it. 
I've added the developer account in the settings of AppCenter
I've configured a app-specific password both in AppleID side and AppCenter side
When I want to connect AppCenter to AppStore I have an error message after selecting my developer account: "The Apple Login service is temporarily unavailable, please wait a few minutes and try again later."
Is there really a problem of availability ? I've been trying for few hours now with the same error.

**To Reproduce**
See the description.

**Expected behavior**
A working connection to the AppStore Connect that allows to pick the app I want to publish.

**Screenshots**
Error message: "The Apple Login service is temporarily unavailable, please wait a few minutes and try again later."

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: Mojave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by twittemb** [comment]
seems to be working now.

I close the issue.

**Comment by shaunsaker** [comment]
I'm experiencing the exact same issue except that my browser is Brave (Chrome).

**Comment by El-Sy** [comment]
From time to time they fail. Looks like today it is not working as well.
