### ISSUE TITLE
Push in iOS sandbox production management

### ISSUE THREAD

**Issue by bo3po** [microsoft/appcenter#678]
**Describe the solution you'd like**
In iOS - I would like to be able to use sandbox and production push certificates on one application. Not having to create two. One for production and one for push only. I think that the same would apply for Android. Having a push channel for production and sandbox. I imagine that we could have multible push accounts connected to a single app. And then when we want to do a push the api could have a argument saying what account should be used.

**Describe alternatives you've considered**
I have to create two application in AppCenter. One for production. One for development. But the development application has a sole purpuse which is to run push locally. That seems odd to me that I have to create an extra app just for that.

**Additional context**
This is for local development when I play around with the push on my local device. I need a sandbox certificate for that. It's working in Azure Notification Hub by having two hubs. A free and a paid hub. And then I switch in the code in my backend that when the registration is occuring is sending the registration to the dev or the prod hub. The flow is:

App -> Backend -> Notification Hub (deveopment or production)

**Comment by jwargo** [comment]
@bo3po thank you for this suggestion, it's not something I've considered for App Center Push. Notification Hubs has this built in, but it's not something we can support in App Center. I'll track this as a feature request to see how other customers feel about it.

**Comment by jwargo** [comment]
@bo3po Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
