### ISSUE TITLE
Supporting cohort view in Analytics page

### ISSUE THREAD

**Issue by allanjsx** [microsoft/appcenter#679]
**Describe the solution you'd like**
Cohort (https://en.wikipedia.org/wiki/Cohort_analysis) is an essential data analysis to help developers understand their users retention rate. Cohort view has been supported on other analytic platforms such as Google Analytics, Facebook Analytics, and Mixpanel. I hope App Center can add a cohort view to the Analytics tab.

For example, Cohort view can help developer understand information like: "Out of the 100 new users I got on January 1st, how many of them come back to use my app again in the first week, second week, and third week".

**Comment by hamswan** [comment]
Thanks @allanjsx for reaching out to us, I will add this to our Feature request.

**Comment by yunustek** [comment]
Yes, I think it should be a cohort analysis too.
