### ISSUE TITLE
Trigger new builds only upon adding tags within a repo

### ISSUE THREAD

**Issue by kuyazee** [Microsoft/appcenter#68]
**Describe the solution you'd like**
This is a feature many ci/cd tools have. By having this we can have better flexibility on creating builds.

**Describe the solution you'd like**
I'd like to have atleast one of the following features

1. If I were to push a tag **3.0.0-staging** or **3.0.0-production** I'd like it to build on a specific scheme (for iOS) and build variant (for Android), depending on the format of the tag. 

2. If I were to push a tag on a specific commit, appcenter would build the app on that specific commit.

**Describe alternatives you've considered**
An alternative I have done is to create specific branches that builds everytime I push code, but that's too hacky.

**Comment by patniko** [comment]
Closing this out as a dupe for #23. Please add reactions there to share interest in adding this in.
