### ISSUE TITLE
Issue installing appCenter via cocoa pods. Install fails with error.

### ISSUE THREAD

**Issue by fareast555** [microsoft/appcenter#680]
**What App Center service does this affect?**
AppCenter CocoaPod install on Mac for iOS (Formerly Hockey App)
Podfile contents below

**Describe the bug**
Unable to install or update via Cocoapods. Doing so gives the following error in git

Installing AppCenter (2.1.0)

[!] Error installing AppCenter
[!] /usr/bin/curl -f -L -o /var/folders/m2/vxzmsqqx5nx05f3qw6hk_nwr0000gn/T/d20190706-62574-1hdvm6d/file.zip https://github.com/microsoft/appcenter-sdk-apple/releases/download/2.1.0/AppCenter-SDK-Apple-2.1.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   619    0   619    0     0    179      0 --:--:--  0:00:03 --:--:--   179
 64 43.1M   64 27.6M    0     0  27256      0  0:27:40  0:17:44  0:09:56     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**To Reproduce**
Unsure if this is reproducible, but this is what I was working on
1. Break off test branch from develop
2. Run pod update. App Center 2.1.0 updates as expected
3. App builds. 
4. After one commit, checkout develop 
5. Reset --hard HEAD
6. Delete test branch
7. Run pod update (fails to install 2.1.0)

**Repair attempt**
1. Remove AppCenter from Podfile
2. Run pod update to remove. Successful and app builds.
3. Attempt to install AppCenter 2.1.0 again (fails)
4. Attempt to install AppCenter 2.0.1 again (fails)

**Expected behavior**
Expect to be able to update pod after removal via cocoapods

**Screenshots**
<img width="788" alt="Screen Shot 2019-07-06 at 16 17 06" src="https://user-images.githubusercontent.com/4649188/60754377-49d00f00-a00a-11e9-93f0-83c3c2c3d4ba.png">

**Desktop (please complete the following information):**
- Mac OS 10.14.5 Mojave
- Terminal Version 2.9.5
- Xcode 10.2.1

**Additional context**
 - Pod environment:
  ### Stack

```
   CocoaPods : 1.7.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/Mike/.rbenv/versions/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c008fdc6225c77805f2d3f8981769a0a056d65f1
```

### Installation Source

```
Executable Path: /Users/Mike/.rbenv/versions/2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source "https://github.com/CocoaPods/Specs.git"

platform :ios, "11.2"
inhibit_all_warnings!

target 'SICController' do
    use_frameworks!
    pod 'AppCenter'
    pod 'MPC_Notification', '~> 1.1.3'
    pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.1.0'
end

**Comment by Jamminroot** [comment]
Hey, @fareast555, sorry for late response and thanks for getting in touch!

As far as I can see, it looks more like a problem either in **curl** \ **LibreSSL** util or proxy\firewall behind your connecition - curl either can't reach repo or verify secure connection.

Also, I've tried to reproduce your problem - just to be sure - and could not reproduce with given versions of applications\IDEs (OS matches, too).

Can you, by any chance, verify points I mentioned above?

**Comment by fareast555** [comment]
Hi @Jamminroot  Thanks for the reply. Yeah, I guess it was some mystery issue, because I just tried to install it now, and there were no issues. 

It may be due to before I was using pod update...this time I did a pod update, committed everything in the staging area, then added AppCenter to the pod file and did a pod install. It worked. 

Not sure why it suddenly is working though. I tried it over the course of a few days and finally gave up. Did you jiggle a wire? lol Anyway, thanks. I'll close this off here. 

Much appreciated! :)

**Comment by Jamminroot** [comment]
You are welcome!
Feel free to contact us if you need asisstance with SDK

**Comment by justinairbase** [comment]
I got it to work by removing appcenter with `yarn remove appcenter` then doing `pod install` and again installing appcenter `yarn add appcenter` and then again doing `pod install`

**Comment by Arwantys** [comment]
Same problem, I tried everything, uninstall, reinstall, change network ... I have no proxy.
