### ISSUE TITLE
[ios] Can't release app – Publishing operation timed out

### ISSUE THREAD

**Issue by MikePodgorniy** [microsoft/appcenter#684]
**What App Center service does this affect?**
react-native, ios

**Describe the bug**
_Publishing to TestFlight failed:_
Publishing operation timed out. You can verify the actual publishing status from the official store portal or try again later. Support Id: 0f1b40e3-e983-44a6-840b-XXXXXXX

All Appcenter and itunesconnect statuses are green.

**Question**
How to check detailed information by _Support Id_ ?

**Comment by MikeDaniel18** [comment]
@MikePodgorniy We're receiving this error too and can't find anything on Apple's end. How did you resolve this?

**Comment by MikePodgorniy** [comment]
@MikeDaniel18 I received a later from itunesconnect with some errors, but I can't find it now

**Comment by MikeDaniel18** [comment]
@MikePodgorniy ahh, excellent, thank you. Just received an email. Oddly the build vanished off the face of the earth in AppStoreConnect.
