### ISSUE TITLE
Provide option to Resend Push Notification

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#685]
Hi,

When opening sent Push notification message in the portal, please provide an option to resend selected message instead of typing the same message again..

Thanks,
Jassim

**Comment by jwargo** [comment]
@jrahma Good suggestion, I’ll add it to the feature list. I’m looking forward to hear how many other customers would like to see this feature added.

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
