### ISSUE TITLE
AppCenter fails to handle custom data

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#686]
Hi,

I am getting this error when sending Push Notification with custom data:

> 07-09 04:28:14.792 I/ViewRootImpl(32532): jank_removeInvalidNode all the node in jank list is out of time
> Thread finished: <Thread Pool> #18
> Thread started: <Thread Pool> #20
> The thread 0x12 has exited with code 0 (0x0).
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): Error while parsing timestamp in GCM event
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): java.lang.NumberFormatException: s == null
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): 	at java.lang.Integer.parseInt(Integer.java:577)
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): 	at java.lang.Integer.valueOf(Integer.java:801)
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source:60)
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): 	at com.google.firebase.messaging.zzd.zzg(Unknown Source:26)
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:160)
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): 	at com.google.firebase.iid.zzg.run(Unknown Source:26)
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 07-09 04:28:16.287 W/FirebaseMessaging(32532): 	at java.lang.Thread.run(Thread.java:784)
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): Error while parsing timestamp in GCM event
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): java.lang.NumberFormatException: s == null
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): 	at java.lang.Integer.parseInt(Integer.java:577)
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): 	at java.lang.Integer.valueOf(Integer.java:801)
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source:60)
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): 	at com.google.firebase.messaging.zzd.zzj(Unknown Source:2)
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:201)
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): 	at com.google.firebase.iid.zzg.run(Unknown Source:26)
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 07-09 04:28:16.295 W/FirebaseMessaging(32532): 	at java.lang.Thread.run(Thread.java:784)
> 07-09 04:28:18.993 I/ViewRootImpl(32532): jank_removeInvalidNode all the node in jank list is out of time
> 07-09 04:28:24.999 I/ViewRootImpl(32532): jank_removeInvalidNode all the node in jank list is out of time
> 

My AndroidManifest.xml looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="100" android:versionName="1.0" package="com.jafaria.app" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="27" android:targetSdkVersion="28" />
	<application android:label="الأوقاف الجعفرية" android:icon="@drawable/icon" android:supportsRtl="true" android:largeHeap="true">
		<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_notification" />
    <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id" />
    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
				<category android:name="com.jafaria.app" />
			</intent-filter>
		</receiver>
	</application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
	<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.MEDIA_CONTENT_CONTROL" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
</manifest>

```

and my PushNotificationReceived:

```
protected override void OnStart()
{
    if (!AppCenter.Configured)
    {
        Push.PushNotificationReceived += (sender, e) =>
        {
            if (e.CustomData != null)
            {
                if (e.CustomData.ContainsKey("Ad"))
                {
                    System.Diagnostics.Debug.WriteLine("CUSTOM-DATA The Ad is ... " + e.CustomData["Ad"]);

                    App.Current.MainPage.Navigation.PushAsync(new AdDetails(Convert.ToInt32(e.CustomData["Ad"])));
                }
                else if (e.CustomData.ContainsKey("News"))
                {
                    System.Diagnostics.Debug.WriteLine("CUSTOM-DATA The News is ... " + e.CustomData["News"]);

                    App.Current.MainPage.Navigation.PushAsync(new NewsArticle(Convert.ToInt32(e.CustomData["News"])));
                }
                else if (e.CustomData.ContainsKey("Profile"))
                {
                    System.Diagnostics.Debug.WriteLine("CUSTOM-DATA The Profile is ... " + e.CustomData["Profile"]);
                }
                else if (e.CustomData.ContainsKey("Site"))
                {
                    System.Diagnostics.Debug.WriteLine("CUSTOM-DATA The Site is ... " + e.CustomData["Site"]);
                }
                else if (e.CustomData.ContainsKey("Library"))
                {
                    System.Diagnostics.Debug.WriteLine("CUSTOM-DATA The Library is ... " + e.CustomData["Library"]);
                }
                else if (e.CustomData.ContainsKey("Service"))
                {
                    System.Diagnostics.Debug.WriteLine("CUSTOM-DATA The Service is ... " + e.CustomData["Service"]);
                }
                else if (e.CustomData.ContainsKey("Board"))
                {
                    System.Diagnostics.Debug.WriteLine("CUSTOM-DATA The Board is ... " + e.CustomData["Board"]);
                }
                else if (e.CustomData.ContainsKey("BoardMember"))
                {
                    System.Diagnostics.Debug.WriteLine("CUSTOM-DATA The Board Member is ... " + e.CustomData["BoardMember"]);
                }
                else if (e.CustomData.ContainsKey("Calendar"))
                {
                    System.Diagnostics.Debug.WriteLine("CUSTOM-DATA The Calendar is ... " + e.CustomData["Calendar"]);
                }
            }
        };
    }

    // Handle when your app starts
    AppCenter.Start("ios=xxxxx;android=xxxx",
                    typeof(Analytics), typeof(Crashes), typeof(Push));
}

```

**Comment by jwargo** [comment]
@jrahma have you worked through this with our support team? I’d rather support helps you resolve the issue before we classify this as a bug here. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jwargo** [comment]
@jrahma Have you worked with our support team to resolve this error? App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
