### ISSUE TITLE
Add diagnostics (crashes) support for iOS extensions

### ISSUE THREAD

**Issue by GusevAndrey** [microsoft/appcenter#687]
**Describe the solution you'd like**
The key feature of our app is a VPN extension.

We need a way to collect descriptive diagnostics for the extension as for the main app including crash reports, app logs, attachments, user ID e.t.c. And have it available in the same app item as the main app in AppCenter console.

Now we are using HockeyApp SDK which is supports this feature and it is great.
But considering migration to AppCenter we've, unfortunately, faced absence of the feature which is an issue for us to proceed.

**Describe alternatives you've considered**

Speaking to a support engineer we've figured out that there is no workaround or something we can use for now as an alternative solution to the problem

**Comment by winnieli1208** [comment]
@GusevAndrey thanks for the request. We understand this is a major limitation and I've added this feature to our roadmap. I don't have an ETA at the moment but I will update this thread as soon as I have a clearer timeline. 

Thanks for your patience!

**Comment by vkrasnov** [comment]
We are trying to use 2.5.0 with a VPN extension, and it crashes on init surpassing the memory limit, right after the first crash. It then gets into infinite OOM crash loop.

**Comment by GusevAndrey** [comment]
@Oddj0b clarify please if the memory limit issue mentioned by @vkrasnov was fixed now (AppCenter SDK 3.0.0)?

**Comment by Oddj0b** [comment]
@GusevAndrey I'll check with my colleagues.

**Comment by GusevAndrey** [comment]
@Oddj0b Any news so far?)

**Comment by winnie** [comment]
Hey @GusevAndrey - apologies for the delay. Can you start a support thread (blue chat bubble) so our team can take a look? Our engineering team would like some more details to help with thier investigation.

We will update this thread for others after the investigation. Thanks!
