### ISSUE TITLE
Push item in the sidebar is useless for Mac apps

### ISSUE THREAD

**Issue by shpakovski** [microsoft/appcenter#688]
**What App Center service does this affect?**

Portal.

**Describe the bug**

Sidebar items Build and Push are useless in my case, it would be nice to remove them from the sidebar in App Settings.

**To Reproduce**

1. Go to the App Center
2. Click on the Mac App
3. Check the sidebar
4. Items Build and Push are placeholders

**Expected behavior**

I’d like to disable Build and Push unless I’m using them.

**Screenshots**

<img width="1241" alt="Push" src="https://user-images.githubusercontent.com/163410/60874189-4de57200-a240-11e9-850e-85787188ad37.png">

**Additional context**

The Push functionality is not even available in the macOS SDK.

**Comment by elamalani** [comment]
@shpakovski App Center Push service works for [macOS ](https://docs.microsoft.com/en-us/appcenter/sdk/push/macos) apps. We show services in the left navigation only if they are available for use in App Center. Both [Build ](https://docs.microsoft.com/en-us/appcenter/build/macos/) and [Push ](https://docs.microsoft.com/en-us/appcenter/sdk/push/macos) can be used for macOS apps.

**Comment by shpakovski** [comment]
@elamalani Thanks for the reply, indeed I missed this, thanks! What about hiding these items from the sidebar anyway, as an option in the App Settings?

**Comment by elamalani** [comment]
@shpakovski That would be a new feature request in App Center. I'll close this issue for now but please feel free to open a new issue for this feature request.
