### ISSUE TITLE
Separate release and debug diagnostics

### ISSUE THREAD

**Issue by GusevAndrey** [microsoft/appcenter#689]
**Describe the solution you'd like**
In HockeyApp was a very useful feature which allows to separate uploaded debug builds being internally tested and diagnostics (crash reports and e.t.c) collected from them from data, collected with real production users and released builds.

AppCenter SDK, according to [the docs](https://docs.microsoft.com/en-us/appcenter/transition/ios-sdk-migration?tabs=objc), does not have any equivalents for `[[BITHockeyManager sharedHockeyManager] configureWithBetaIdentifier:liveIdentifier:delegate]
`
It is very useful to have a built in way to separate diagnostics collected from released builds and all others as it was available in HockeyApp

**Describe alternatives you've considered**
Speaking to a support engineer we were assured that now there is the only way to do what we want and it's to create 2 different app items in AppCenter and implement diagnostics separation by ourself.

**Comment by winnieli1208** [comment]
Hey thanks for the feature request! This isn't on our immediate roadmap but we will continue to monitor this issue for feedback and interest.

**Comment by andredoubleu** [comment]
I second this feature request.  Creating 2 separate apps in App Center for each app that my company publishes seems like a hassle.  It would be much better to just be able to filter diagnostics by debug or release.
