### ISSUE TITLE
More Script Entry Points

### ISSUE THREAD

**Issue by kuyazee** [microsoft/appcenter#69]
**Describe the solution you'd like**
Add a post-test-script, that will run if tests passed.

**Describe alternatives you've considered**
Simply run the post-build-script even though testing hasn't been completed

**Comment by mike14u** [comment]
I would even add a post-distribution script. so it could be

- pre-build
- post-build
- post-test
- post-distribution

**Comment by Oddj0b** [comment]
@kuyazee Thanks for the great suggestion. Would the post-test-script be after unit-test or test on a real device?

**Comment by kuyazee** [comment]
@Oddj0b hello, I suggest we have separate scripts for those, and one final post test script when both are finished. I think it would really be helpful to have many entry points. Just like what @mike14u suggested.

**Comment by Oddj0b** [comment]
I might have initially misunderstood this request. At first, I was thinking of it in the context of our Build service, but now I think it's a stand-alone test feature where a script will be executed when a test is successfully completed. Which of the two options are you requesting?

**Comment by kuyazee** [comment]
Hi, can you explain what you mean by “a script will be executed when a test is successfully completed” did you mean the *test* step of appcenter? 

My request now is to have more entry points for build scripts. As of the moment there are only three build scripts, if we were to add a *pre* and *post* script on more of AppCenter’s steps it would be great.

**Comment by Oddj0b** [comment]
> Hi, can you explain what you mean by “a script will be executed when a test is successfully completed” did you mean the test step of appcenter?

My thought was that it would be independent of the other three scripts and part of the Test section in App Center. The reason for this is that you can run Test independently of our Build service using our command line tool.

@kuyazee Thank you for clarifying I have understood the feature request now.

**Comment by mike14u** [comment]
A pre- and post- to each of AppCenter's step is nice. It'll definitely be the preferred one vs all the other alternative tool out there.

I envision it to have:
**Build**
- pre-build
- post-build

**Test**
- pre-unit-test
- post-unit-test
- pre-ui-test
- post-ui-test

**Distribute**
- pre-distribute
- post-distribute
