### ISSUE TITLE
Distribute to App Store or TestFlight build no longer appearing

### ISSUE THREAD

**Issue by mifi** [microsoft/appcenter#690]
**What App Center service does this affect?**
Buildserver

**Describe the bug**
I had my react native app (iOS) always build on commits on a release-branch, and then I could go to the last built job and press "Distribute->Store->Production (App Store) or TestFlight" and it would automatically appear in TestFlight or under available build when drafting a new release in AppStoreConnect. However since yesterday the builds no longer appear. The new draft version appears but no build gets uploaded.

**To Reproduce**
- Bump version in Info.plist
- Commit to release branch and push
- Wait for build to successfully finish
- Distribute->Store->Production
- Observe notification "Build 22 distributed." - no error message

**Expected behavior**
The build should appear under "Build" or TestFlight in AppStoreConnect

**Screenshots**

<img width="695" alt="Screenshot 2019-07-09 at 11 58 55" src="https://user-images.githubusercontent.com/402547/60882998-f4ca0e00-a240-11e9-996e-97f8b657b30b.png">

<img width="197" alt="Screenshot 2019-07-09 at 12 00 13" src="https://user-images.githubusercontent.com/402547/60883194-702bbf80-a241-11e9-9bcd-7415ca71c8cc.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 75.0.3770.100

Additional question:
Is it possible to see somewhere some debug log output of the "Distribute" operation?

**Comment by mifi** [comment]
I have found the cause of the issue. When trying to upload the generated IPA with Application Loader I'm getting "Invalid App Store Icon, can't be transparent nor contain an alpha channel" error from Apple. Turns out I had RGBA PNGs. After resolving this it works also in AppCenter.

It would however be **extremely helpful if appcenter reported this error instead of just showing that the Build was distributed successfully.**

**Comment by Oddj0b** [comment]
Hi @mifi, thanks for reporting the error. I will work with the team to implement the error message, instead of returning a success.

**Comment by joabalea** [comment]
@mifi Did you check under _Distribute > Stores > Production_ your release details.
We do report publishing errors from Apple there.
_Build 22 distributed_ message does not guarantee success. 
Here is an example of what you should see in the release details information page:
![Screen Shot 2019-09-02 at 11 04 49](https://user-images.githubusercontent.com/39932946/64086999-11348380-cd76-11e9-8c01-93ead38f26c8.png)

**Comment by Lucas-Geitner** [comment]
Thanks @joabalea !

**Comment by mifi** [comment]
Gotcha! Thanks. I found the error there. It would be extremely helpful for new users if the the simple "Build 22 distributed" message would show link to this page, or at least say "Build 22 distributed - go to distribute menu to see the status"

**Comment by Buthrakaur** [comment]
Also this should be part of the build pipeline - if the distribution fails, the build should fail and the build log should contain the error message. Other mobile app CI solutions do it this way too.
