### ISSUE TITLE
Support hosted builds that leverages Android 9.0 (API level 28)

### ISSUE THREAD

**Issue by nativenolde** [microsoft/appcenter#691]
I run an Xamarin Forms App that is available on iOS and Android.
Currently it leverages Android 8.1 (API level 27), which works fine.

Since Google has introduced the following requirement for publishing apps, I need to upgrade to Android 9.0 (API level 28):

> As of August 2019, new apps must target at least Android 9.0 (API level 28).
> As of November 2019, app updates must target Android 9.0 (API level 28).

Your support staff told me that it's currently not supported, to run such a hosted build on AppCenter.

Please support hosted builds that leverages Android 9.0 (API level 28).

**Comment by nativenolde** [comment]
@nrajpurkar Can you estimate a time window for an investigation or implementation?
As you may know, Google has set the deadline to August 2019 ...

**Comment by nrajpurkar** [comment]
Hi @nativenolde, we support building Xamarin.Android 9.0+ which includes support for Android 9.0 (API level 28). Are you having a particular issue with your build where you are unable to build using this?

**Comment by nativenolde** [comment]
Currently my App targets Framework Version v8.1 with Android Sdk Level 27, which compiles perfectly fine... Since Google requires 9.0 or newer, I switched to Target Framework version 9.0 with Android Sdk Level 28, which no longer compiles on App Center, but locally does. Therefore i contacted you support staff which told me, that this is currently not supported.

Manifest file
`<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="28" />`

Project file
`<TargetFrameworkVersion>v9.0</TargetFrameworkVersion>`

Since that change, every build failes with the following error:
MSB6006: "java" exited with code 2

**Comment by nativenolde** [comment]
@nrajpurkar After researching all the day, i luckily was able to find the root cause.
There were too many field references to fit in one dex file :/
Thank you for your quick response.

**Comment by nrajpurkar** [comment]
No problem, glad you were able to resolve!
