### ISSUE TITLE
Xamarin.UITest 3 searches for local APK in Visual Studio folder, when targeting NUnit 3

### ISSUE THREAD

**Issue by curia-damiano** [microsoft/appcenter#692]
**What App Center service does this affect?**
Xamarin.UITest

**Describe the bug**
When running UI Tests **that target NUnit 3**, the APK is searched from the Visual Studio folder.

**To Reproduce**
1. Create a new Xamarin.Android app
2. Add a new Xamarin.UITest project
3. Reference NUnit 3
4. With relative path, the APK is searched inside the Visual Studio folder

**Expected behavior**
I would expect that the APK is loaded from the relative folder.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 to compile, Android 9 to run
 - Browser: none
 - Version: none

**Smartphone (please complete the following information):**
 - Device: Pixel 3 and emulator
 - OS: Android 9
 - Browser: none
 - Version: none

**Additional context**
If needed, I am available in teams. I can also provide you a solution with a sample project and test case.

**Comment by Oddj0b** [comment]
Hi @curia-damiano, thanks for reporting the bug I have created a bug, and I will work with the team to prioritize it.

**Comment by curia-damiano** [comment]
Hi Villars, if you need I have a repro project for you to test

**Comment by Oddj0b** [comment]
Thank you @curia-damiano, the bug is still sitting the backlog. But we will get to it.

**Comment by curia-damiano** [comment]
Hi, trying after 6 months, still referencing an APK via relative folder doesn't work.
Now it searches in the Desktop folder.
Can you please fix this bug? Otherwise how can I make my tests to work both in local and in App Center?

**Comment by Maverick1st** [comment]
I also encounter this issue. Still one year after reporting this issue nothing has happened? Not even a response? 
This is not how support should work.
Could you please do something against this issue? obviously entering a hardcoded path is not a solution for this issue!!

**Comment by curia-damiano** [comment]
+1

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
