### ISSUE TITLE
Foreground Notification

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#694]
Hi,

Currently the app does not receive push notifications  because AppCenter does not support as per the support team.

It will be great if you include this so message will be shown as popup on the app

Thanks,
Jassim

**Comment by jwargo** [comment]
@jrahma I'm sorry, I don't understand the request, can you please elaborate? What specifically are you looking for?

**Comment by jrahma** [comment]
Currently when you send a push notification and the app is closed the user will be able to receive it

but if you send a message while the user is using the app then the user will receive nothing

so I am suggesting the message should show on a dialog or alert box when the user is using the app **if receiving the normal push notification is not possible**

**Comment by jwargo** [comment]
@jrahma what type of app are we talking about here? As I understand it, it depends on which type of notification is sent to the device and how the app processes notifications when they arrive.

**Comment by jrahma** [comment]
Any typical app, any notifications

If you open the app and send the notifications whilst the app is open the it won’t show anything

**Comment by jwargo** [comment]
@jrahma Android? iOS? Xamarin? React Native? On what platform are you trying to do this for?

**Comment by jrahma** [comment]
Currently trying it on Android 9 on Honor 10 Lite

**Comment by Mrnikbobjeff** [comment]
This occurs on my OnePlus 5T  with android 9 devices as well as on the Emulator, also with android 9.
While the app is in the foreground, push notifications are not displayed. Once the app is either completely stopped or closed and put in background, the notifications appear as expected.

**Comment by pfedotovsky** [comment]
@jwargo I have the same issue with Xamarin.Forms app.

Notifications are not received if the app is in the foreground.

**Comment by jwargo** [comment]
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
