### ISSUE TITLE
App distribution security

### ISSUE THREAD

**Issue by dexter31** [microsoft/appcenter#695]
App distribution security

The concept of Managing Distribution Groups is nullified based on the final download link published in install.appcenter.ms - which is a static one where no authorization checks are performed.

The expectation is, if I add a group of users who are authorized to access a specific app - at ALL given user interactions, the authorization must be checked. But the final download link points to a static resource URL that anyone can use to download the app and bypass security completely

Eg. Via a link like - https://rink.hockeyapp.net/api/2/apps/{application_identified}/app_versions/1?format=ipa

**To Reproduce**
1. Setup a dummy ipa on app center.
2. Create a distribution group for the app with only one user.
3. Open an incognito window and use the URL above substituting the app identifier.
4. You will be able to download the app without authorization.

**Expected behavior**
Authorization checks need to be enforced prior to download.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
All devices

**Additional context**
I think this is a critical security flaw that needs immediate addressing. Otherwise the platform can be used only for public apps.

**Comment by derpixeldan** [comment]
@dexter31 thanks for reporting this. We are aware of the behaviour. App Center is currently still using HockeyApp for distribution, however, we're almost done with an App Center independent solution that has superior security mechanisms.

With regards to what you describe above, I agree that knowing the app id gives access to the releases, however, the id itself is not guessable. We're working on a short term fix to not grant access to versions without the correct token.

**Comment by derpixeldan** [comment]
@dexter31 the fix was deployed and to download a version it requires the correct token now.
