### ISSUE TITLE
App Center Support for Xamarin Forms UWP - AppCenter.Crashes Not Working

### ISSUE THREAD

**Issue by dinobu** [microsoft/appcenter#697]
Even though I have added Analytics and Crashes nuggets in my .NETStandard project and all 3 head projects (Android, iOS, UWP) and then in App.xaml.cs OnStart() of my .NETStandard project, added below as you suggested by replacing my app secret appropriately:

AppCenter.Start("ios={Your App Secret};android={Your App Secret};uwp={Your App Secret}", typeof(Analytics), typeof(Crashes));

The Crashes are not reported on UWP at all but they are reported on Android and IOS.

**Comment by elamalani** [comment]
@dinobu There are certain limitations for UWP crashes. Please make sure that the following [criteria](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp) is met for UWP crashes to be reported in App Center portal.

**Comment by dinobu** [comment]
> @dinobu There are certain limitations for UWP crashes. Please make sure that the following [criteria](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp) is met for UWP crashes to be reported in App Center portal.

I am aware of that document, it is also confusing as per ticket I created there.  Thanks

**Comment by annakocheshkova** [comment]
Hi @dinobu, we addressed your issue in another thread.

**Comment by hamswan** [comment]
@dinobu Is this resolved on your side?
