### ISSUE TITLE
D8/R8 Support

### ISSUE THREAD

**Issue by NunoBem** [microsoft/appcenter#698]
**Describe the solution you'd like**
After migrating our app from DX/Proguard to D8/R8, the app had several problems. Contacting AppCenter chat, I was informed that it isn't supported and to open a new feature request.

R8 became the default code shrinker for Android and should be supported.

**Describe alternatives you've considered**
Building the apk on our Visual Studio, results in a working app. But breaks our CI/CD.

**Comment by winnieli1208** [comment]
Hi @NunoBem - thanks for the feature request. App Center diagnostics only supports deobfuscation with the ProGuard at the moment. We don't have immediate plans to support D8/R8 but I will monitor this request for interest. 

(Note: similar request #458)

**Comment by filipkowicz** [comment]
D8/R8 is becoming standard in Android world. @winnieli1208 please consider supporting it soon

**Comment by brcinho** [comment]
Since R8 is becoming de-facto standard from Android side, and is supposed to replace proguard. In recent versions of Android Studio and gradle it is enabled by default. I suppose that tells you that there will be interest for this.

Why the need to explicitly show the interest with comments and up-votes?

**Comment by NunoBem** [comment]
> Contacting AppCenter chat, I was informed that it isn't supported and to **open a new feature request**.

I suppose microsoft is driven by community feedback too and defines it's priorities.

**Comment by NunoBem** [comment]
> Contacting AppCenter chat, I was informed that it isn't supported and **to open a new feature request**.

@brcinho I suppose microsoft is driven by community feedback too and defines it's priorities.

**Comment by brcinho** [comment]
@NunoBem I completely agree with you. The problem occurs when someone is shutting down the service to push their own service but they didn't match the quality, pro-activeness and feature set of the previous service. Then they can not rely that product roadmap depends on the community feedback solely, they need to show some initiative and pro-activeness on their own.

**Comment by ranterle** [comment]
@NunoBem Were your problems with R8/D8 related to only building your app on App Center or also diagnosing crash reports? I'll look into the conversations on why it might have failed for you, but feel free to share more details here or with me personally (email is in bio) if needs be - at least in general it should work for App Center Build.

**Comment by brcinho** [comment]
@ranterle Related to inability for app center to de-obfuscate the stack trace based on the mapping.txt uploaded.

**Comment by brcinho** [comment]
#458

**Comment by NunoBem** [comment]
What's the feedback about this? @winnieli1

**Comment by winnieli1** [comment]
Hi all! Our team is starting this very soon. No exact ETA yet but we expect to have this done in a few 
weeks. Thanks for the patience! We'll post here with updates.

**Comment by winnieli1** [comment]
We added support for this last week (see #458). Thanks!
