### ISSUE TITLE
Multiple Distribution and Signing Paths

### ISSUE THREAD

**Issue by kuyazee** [Microsoft/appcenter#70]
**What App Center service does this feature apply to?**
Build and Distribute system

**Describe the solution you'd like**
Currently the build system is possible with one signing and distribution method per branch. If we'd like to distribute a build from a branch to multiple services we'd either have a very time consuming since we also don't have a clone configuration feature #22 

I'd like an option to add another signing and distribution block so I can distribute to multiple services. 

Why also the signing? For iOS distributing to specific services requires different provisioning profiles and certificates. So it is absolutely necessary to include signing

**Describe alternatives you've considered**
One branch multiple Build Configurations, combined with #22 this could also work. The only problem with this is since the app will need to be rebuilt every time, it will take more time. Unlike the option above where the app only needs to be built once and archived multiple times.

This is related to #10

**Comment by botatoes** [comment]
We're updating build configuration to allow distribution to multiple groups as a part of [#10]

**Comment by botatoes** [comment]
This has been deployed to Prod. :)

**Comment by kuyazee** [comment]
Thank you for this! How about the Multiple Signing Paths though?
