### ISSUE TITLE
master is waiting to be built : No progress 

### ISSUE THREAD

**Issue by v2Nitesh** [microsoft/appcenter#700]
**What App Center service does this affect?**
Name of service or sdk with the issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots 
<img width="1675" alt="Screenshot 2019-07-12 at 11 19 32 AM" src="https://user-images.githubusercontent.com/7920123/61105515-b5492f00-a497-11e9-8f82-3e81b3cbb991.png">
**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Application is not building and there is no error is displaying and it's only showing progress like "master is waiting to be built..." from more than 20 min.

**Comment by DennisPan** [comment]
@v2Nitesh We are currently aware of issue with very first build of an app. If you cancel the build, then all future builds will work.

**Comment by v2Nitesh** [comment]
@DennisPan - I was not aware of this - So as per above comment we have to cancel every first build and when we push next build it will automatically build and distribute the application?

**Comment by DennisPan** [comment]
Sorry about the inconvenience. For each new App Center app, the very first build may run into it. The next build (and builds afterwards) should work as expected.

We are working on the fix.

**Comment by v2Nitesh** [comment]
Hi Dennis,

Yes it’s working fine for Test (Native-iOS App) application but after integration with actual app it’s giving me error while building the code.

Actual application is Flutter based application.

Error details:

PhaseScriptExecution Run\ Script /Users/vsts/Library/Developer/Xcode/DerivedData/Runner-emuvnsfaoizvsegonkoohmlhzhko/Build/Intermediates.noindex/ArchiveIntermediates/qa/IntermediateBuildFilesPath/Runner.build/Release-qa-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65


Kindly suggest the workaround to fix this issue.

--
Thanks and Regards,
Nitesh Meshram
V2Solutions | The Next Level of Innovation
o : +91 22 4153 0200 x.415
m : +91 8319014326

**Comment by lumaxis** [comment]
Let's keep this open while @DennisPan and team are working on a fix for the issue with initial app builds but continue the conversation about the Flutter issue in #701 👍🏼

**Comment by v2Nitesh** [comment]
Hi Team,

Thank you for your quick response.


--
Thanks and Regards,
Nitesh Meshram
V2Solutions | The Next Level of Innovation
o : +91 22 4153 0200 x.415
m : +91 8319014326

**Comment by DennisPan** [comment]
@v2Nitesh The issue with very first build of an app has been fixed now. Let us know if you see anything else.

**Comment by EJohnF** [comment]
@DennisPan 
Hi
now I experience a similar issue.
The very first build was in progress for about 30 mins (including test on real device). So I decided to cancel it and run without tests. 
But now the build is queued for a long time. (android project)

But the good news is that my ios build was finished successfully for the very first launch.
