### ISSUE TITLE
Issue while building the Flutter application iOS Version. 

### ISSUE THREAD

**Issue by v2Nitesh** [microsoft/appcenter#701]
**Describe the bug**
While building the Flutter application we are facing below issues : 

PhaseScriptExecution Run\ Script /Users/vsts/Library/Developer/Xcode/DerivedData/Runner-emuvnsfaoizvsegonkoohmlhzhko/Build/Intermediates.noindex/ArchiveIntermediates/qa/IntermediateBuildFilesPath/Runner.build/Release-qa-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65

**Comment by Jamminroot** [comment]
Hey, @v2Nitesh, thanks for getting in touch - can you elaborate a bit, and provide some context about what is going on?
From what you provided it is quite troublesome to understand the problem.

**Comment by v2Nitesh** [comment]
> Hey, @v2Nitesh, thanks for getting in touch - is it the [same problem](https://github.com/microsoft/appcenter/issues/700)?

No This is not the same problem. Both are diffrent. 

https://github.com/microsoft/appcenter/issues/700
https://github.com/microsoft/appcenter/issues/701

**Comment by nrajpurkar** [comment]
@v2Nitesh thanks for opening the bug, we'll take a look at this. As an FYI, App Center Build does not officially support Flutter today.

**Comment by nrajpurkar** [comment]
@v2Nitesh I'm removing the bug label on this as we don't officially support Flutter.

**Comment by stephan-markovic** [comment]
App Center Build does not officially support Flutter.
