### ISSUE TITLE
Cannot change date range in analytics for my app

### ISSUE THREAD

**Issue by arao-izo** [microsoft/appcenter#702]
**What App Center service does this affect?**
HockeyApp 3.8.6

**Describe the bug**
The date range does not update when I select a range

**To Reproduce**
1. Go to Crashes
2. click on bar graph
3. select any range

**Expected behavior**
Range automatically updates or updates upon refresh
**Screenshots**

<img width="1900" alt="Screen Shot 2019-07-12 at 12 04 25 PM" src="https://user-images.githubusercontent.com/52832233/61142232-4078f380-a49d-11e9-8eb5-8973d73243e9.png">

<img width="1897" alt="Screen Shot 2019-07-12 at 12 05 14 PM" src="https://user-images.githubusercontent.com/52832233/61142269-5b4b6800-a49d-11e9-919d-c4ccd5ca3247.png">
 Look at the mismatch between date range and histogram, does not update automatically or upon refreshing
**Desktop (please complete the following information):**
 macOS: Mojave 10.14.3 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winnieli1208** [comment]
@arao-izo thanks for opening a bug. Our team will take a look at this and get back to you shortly.

**Comment by derpixeldan** [comment]
@arao-izo it's not reproducible for me, please reach out to us in support so we can better investigate the issue. Provide the information what system and browser this is happening on.
