### ISSUE TITLE
[QUESTION] Recover keystore

### ISSUE THREAD

**Issue by hugodantas** [microsoft/appcenter#703]
Hi guys!

Is there any way to recover the keystore configured on Android build?
I lost the keystore on my PC and there's only one place that keystore is saved is on AppCenter build configuration.

If I lose the KeyStore, I need to publish another app with another packagename and I can't do this.

Thank you so much.

**Comment by nrajpurkar** [comment]
@hugodantas we don't allow downloading the signing credentials stored in App Center. They're securely stored on our end, but you should still hold onto it locally. Sorry for the inconvenience!

**Comment by muneneevans** [comment]
Hello
Same problem here. I understand that the keystores have to be secured but is there a way, even if it's a support ticket to get the file and use our accounts as proof of authenticity

**Comment by nrajpurkar** [comment]
@muneneevans there isn't a way to do this today. Feel free to rename this issue or create a new one for a feature request to be able to do this.
