### ISSUE TITLE
Metro from RN 0.60.0 warns that rnpm config is deprecated and will stop working in the next release

### ISSUE THREAD

**Issue by charleycesar** [microsoft/appcenter#704]
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - appcenter: https://github.com/Microsoft/appcenter-sdk-react-native/blob/master/appcenter/README.md

**Comment by hamswan** [comment]
Thanks @charleycesar for reporting this, we will look into this.

**Comment by annakocheshkova** [comment]
Hey @charleycesar we are working on the RN 0.60 support and it is planned in our July SDK release. Thank you for the patience!

**Comment by AnastasiaKubova** [comment]
Hi there! This issue has been fixed.
I'm closing this issue but feel free to open a new issue on the [appcenter-sdk-react-native](https://github.com/microsoft/appcenter-sdk-react-native) repository if this issue still persists.
