### ISSUE TITLE
Make overview page more useful

### ISSUE THREAD

**Issue by vonovak** [microsoft/appcenter#708]
hi! I have a piece of feedback - when I go to appcenter - url like https://appcenter.ms/orgs/org/apps/appName I'll land at overview page that contains "Getting started" instructions. It's also the page people get to upon tapping the app name in upper left part of screen.

After the set up is done, that page is pretty much useless and I think that 99.9% of people who go to that page immediately go to some other page (probably builds). Would you consider making "builds" the main page or at least include some "recent builds" widget in the overview page?

**Comment by blparr** [comment]
Hello @vonovak, we completely agree with your feedback. We are planning to make major improvements to our landing experience. If that's fine with you, we will contact you once we have some progress for feedback. 

Thanks for your suggestion!
Blanca

**Comment by jrahma** [comment]
I agree, Overview is just for Getting Started so why it should still show after years of adding the app?!

I suggest to replace it with **Dashboard** and you move the Getting Started to the Settings once the app starts feeding data to the app or if the user clicked (Do not show this again).

Now, talking about Dashboard.... :)

User should select any data or chart from any screen and Pin to to the dashborad, for example if the user wants to show the Analytics Active users and total crash for t day then he should be able just to click somewhere on the data or char where it says Pin to Dashboard and it will be then shown on his Dashboard


Thanks,
[Jassim](https://www.softnames.com)

**Comment by codeithuman** [comment]
Hello,

Being new to App Center, I expect the "Getting Started" page to morph into a dashboard that displays analytics once App Center SDK is correctly installed/set up. When I see "Getting Started" after setting up App Center, it lowers my confidence in App Center and makes me wonder if I have App Center set up correctly.

Thanks,
AJ
