### ISSUE TITLE
SDK 2.1.0 Analytics - Unity Xcode bool max storage size error

### ISSUE THREAD

**Issue by d-ocean** [microsoft/appcenter#709]
**What App Center service does this affect?**
2.1.0 Analytics

**Describe the bug**
Building from Unity to Xcode. When archiving; AppCenterStarter.m has 'bool' instead of 'BOOL' and is throwing an error (it is fine when building a local build to device). Fixing the 'typo' and saving will allow the archive/ipa to build successfully.

**To Reproduce**
1. Turn on Analytics
2. Build to  Xcode
3. Archive project in Xcode

**Expected behavior**
Archiving should build without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/35927936/61186510-39e5aa00-a65e-11e9-9a25-b03f96c4e78d.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.14.5
- Unity 2019.1.6
- Xcode 10.2.1

**Comment by hamswan** [comment]
@d-ocean Thanks for reporting, we will take a look at this.
