### ISSUE TITLE
Distribution method that will only upload an ipa to AppStoreConnect

### ISSUE THREAD

**Issue by kuyazee** [microsoft/appcenter#71]
**What App Center service does this feature apply to?**
Distribution

**Describe the solution you'd like**
Currently when AppCenter uploads ipas to AppStoreConnect, it automatically proceeds with sending the build for review, which is great for external testing. But I also want a way for AppCenter to just upload an ipa to AppStoreConnect and do nothing else. 

**Describe alternatives you've considered**
I currently have a post-build-script that will upload the ipa I created to AppStoreConnect

**Additional context**
This will be extremely helpful for internal testing using TestFlight.

**Comment by Oddj0b** [comment]
Thank you for feedback I can see a more popular request have come in with #297. If you haven't already I would be happy if also you have time to upvote the newer feature request.
