### ISSUE TITLE
Upload dsym file did not create a release version

### ISSUE THREAD

**Issue by findyam** [microsoft/appcenter#710]
**Describe the solution you'd like**
Upload dsym file should create a release version

**Describe alternatives you've considered**

**Additional context**
Upload a dsym file will create a new build in hockey,  but in appcenter not work.
We use fastlane hockey action upload the dsym file,  and it not working now.
we find the issue after replace hockey with appcenter
we need not the distribute feature, and we need a way to manage the dsym files

**Comment by winnieli1208** [comment]
Hey @findyam can you elaborate on why you need a new version to be created when you upload your symbol files? 

You can upload your symbol files to App Center by following the instructions [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#uploading-symbols). 

Thanks!

**Comment by findyam** [comment]
> Hey @findyam can you elaborate on why you need a new version to be created when you upload your symbol files?
> 
> You can upload your symbol files to App Center by following the instructions [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#uploading-symbols).
> 
> Thanks!

I need a list about dsym files where can delete or update them,  and I can confirm which version has not been uploaded.
