### ISSUE TITLE
App Users' Location not comprehensive enough

### ISSUE THREAD

**Issue by joshuaclicks** [microsoft/appcenter#712]
After making use of the rich telemetric features that AppCenter offer, I discovered that the Country of an App User was captured but details such as city, and county of the Country was not captured and for apps that are localized to a particular country, there will be the challenge of identifying where the different Users' are using the app from as the country will only be shown.

With the location detail specified, there will be data that can be used for Marketing purposes in order to make good marketing decisions by the marketing team of the organization.

Kindly add this feature to the next release of AppCenter.

**Comment by hamswan** [comment]
Thanks @joshuaclicks for requesting this. Added this to feature request.
