### ISSUE TITLE
AppCenter.Crashes.TrackError hangs in unhandled exception handler

### ISSUE THREAD

**Issue by missy-bowles** [microsoft/appcenter#713]
**What App Center service does this affect?**
Diagnostics

**Describe the bug**
In the Android project for a Xamarin.Forms app, we created a handler for unhandled exceptions in MainActivity.cs: 
`AppDomain.CurrentDomain.UnhandledException += CurrentDomainOnUnhandledException;`

In the handler we attempt to log the exception using `public static void TrackError (Exception exception, IDictionary<string, string> properties = null);`
In this case, that method hangs and does not complete the call. When it is called elsewhere outside of the unhandled exception handler, it does work.  

**To Reproduce**
1. Create unhandled exception handler and assign in OnCreate of MainActivity.cs
2. In handler, track exception using `public static void TrackError (Exception exception, IDictionary<string, string> properties = null);`
3. Cause a crash

**Expected behavior**
The app does not hang on that method call and the error is reported and viewable in App Center

**Additional context**
AppCenter Nuget packages: 2.0.0
Affects Android only

**Comment by winnieli1208** [comment]
Hi @missy-bowles - thanks for the detailed bug report. Do you mind starting a conversation in the blue chat bubble on the bottom left? This will allow our support and engineering teams to take a closer look for you. 

Thanks!

**Comment by nourben** [comment]
Hi, this is style here in the version 4.4.0 

Any news on this ?

**Comment by AnastasiaKubova** [comment]
Hi, @nourben ! Thanks for getting in touch with us! I'm trying to reproduce this issue following steps from the description, but for me all work well. Could you please share a code snippet with reproducing of this issue and [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin)?

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
