### ISSUE TITLE
AppCenterLog.Error (System.String p0, System.String p1)

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#714]
Hi,

Why I am getting this error and it crashes my app?

It works fine when I deploy the app on device or use emulator but it crashes when I uploaded it to Google Play 

> AppCenterLog.Error (System.String p0, System.String p1)
> Java.Lang.OutOfMemoryError: Failed to allocate a 5117915496 byte allocation with 6291456 free bytes and 509MB until OOM, max allowed footprint 8916760, growth limit 536870912
> 

> JniEnvironment+Strings.NewString (System.Char* unicodeChars, System.Int32 length)
> JniEnvironment+Strings.NewString (System.String value)
> JNIEnv.NewString (System.String text)
> AppCenterLog.Error (System.String p0, System.String p1)
> AppCenterLog.Error (System.String tag, System.String message)
> AppCenterLog.Error (System.String tag, System.String message, System.Exception exception)
> Crashes.OnUnhandledException (System.Exception exception, System.String source)
> Crashes.OnUnhandledException (System.Object sender, Android.Runtime.RaiseThrowableEventArgs e)
> AndroidEnvironment.UnhandledException (System.Exception e)
> (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.72(intptr,intptr,intptr,intptr,intptr)
> (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.72(intptr,intptr,intptr,intptr,intptr)
> java.lang.OutOfMemoryError: Failed to allocate a 4918158640 byte allocation with 6291456 free bytes and 510MB until OOM, max allowed footprint 8117640, growth limit 536870912
> md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(Native Method)
> md58432a647068b097f9637064b8985a5e0.FragmentContainer.onCreateView(FragmentContainer.java:33)
> android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
> android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
> android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
> android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
> android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
> android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
> android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
> android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
> android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
> android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
> android.os.Handler.handleCallback(Handler.java:891)
> android.os.Handler.dispatchMessage(Handler.java:102)
> android.os.Looper.loop(Looper.java:207)
> android.app.ActivityThread.main(ActivityThread.java:7539)
> java.lang.reflect.Method.invoke(Native Method)
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
>

**Comment by hamswan** [comment]
@jrahma our team will look at this

**Comment by russelarms** [comment]
@jrahma could you please specify platform and the SDK version you are using?

**Comment by jrahma** [comment]
It's Android and I am using AppCenter 2.1.1

This problem happens only when installing the app from Google Play Store:

[https://play.google.com/store/apps/details?id=com.jafaria.official](https://play.google.com/store/apps/details?id=com.jafaria.official)

but I run the app locally on emulator or deploy the app from visual studio to my device then no issue

You can try downloading the app from Play Store and click on any of the highlighted icons then you'll see the app crashing

Just one note here, all these pages which are crashing are having SqlConnection but open any other page without SqlConnection has no issue

**Comment by russelarms** [comment]
I tested this problem with your apk on the emulator and this is what the stack trace shows. Basically, it seems to be a problem with the view rather than an error in Crashes module.
Could you disable Crashes and verify that the problem exists?
Btw, have you tried to build the app in release mode to reproduce the error?

```
JNI DETECTED ERROR IN APPLICATION: negative jsize: -258104976
    in call to NewIntArray
    from android.view.View md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle)
"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 flags=0 obj=0x748e0f60 self=0xf025c000
  | sysTid=6679 nice=-10 cgrp=default sched=0/0 handle=0xf4e7f494
  | state=R schedstat=( 2479975528 235100389 1530 ) utm=193 stm=54 core=0 HZ=100
  | stack=0xff6fe000-0xff700000 stackSize=8MB
  | held mutexes= "mutator lock"(shared held)
  native: #00 pc 004152f6  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+198)
  native: #01 pc 0051048e  /system/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+382)
  native: #02 pc 0050b743  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+83)
  native: #03 pc 0031a8b0  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1088)
  native: #04 pc 0031ad21  /system/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, char*)+113)
  native: #05 pc 000d60f7  /system/lib/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+71)
  native: #06 pc 000d5d8a  /system/lib/libart.so (art::(anonymous namespace)::ScopedCheck::CheckNonHeapValue(char, art::(anonymous namespace)::JniValueType)+554)
  native: #07 pc 000d4617  /system/lib/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+135)
  native: #08 pc 000d3bdb  /system/lib/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+811)
  native: #09 pc 000df8b7  /system/lib/libart.so (art::(anonymous namespace)::CheckJNI::NewPrimitiveArray(char const*, _JNIEnv*, int, art::Primitive::Type)+903)
  native: #10 pc 000cb74b  /system/lib/libart.so (art::(anonymous namespace)::CheckJNI::NewIntArray(_JNIEnv*, int)+43)
  native: #11 pc 0000e787  /data/app/com.jafaria.official-KwVWRgAPT2RTH0-6g6Xi9A==/lib/x86/libmonodroid.so (java_interop_jnienv_new_int_array+39)
  native: #12 pc 00014637  <anonymous:d4620000> (???)
  at md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(Native method)
  at md58432a647068b097f9637064b8985a5e0.FragmentContainer.onCreateView(:33)
  at android.support.v4.app.Fragment.performCreateView(:2439)
  at android.support.v4.app.FragmentManagerImpl.moveToState(:1460)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(:1784)
  at android.support.v4.app.FragmentManagerImpl.moveToState(:1852)
  at android.support.v4.app.BackStackRecord.executeOps(:802)
  at android.support.v4.app.FragmentManagerImpl.executeOps(:2625)
  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(:2411)
  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(:2366)
  at android.support.v4.app.FragmentManagerImpl.execPendingActions(:2273)
  at android.support.v4.app.FragmentManagerImpl$1.run(:733)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6669)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Runtime aborting...
```

**Comment by jrahma** [comment]
it's the same when I disable Crash

so how AppCenter Diagnostic can help me here to understand where is the problem? especially when it's perfectly working on Emulator and on Device but crahses only when installing from Play Store

**Comment by antoiodragos** [comment]
By any chance, does your app crashes on a page with a Syncfusion ListView (v 17.2.0.35)? In my app that was the case. After updating from 17.1.0.53 to 17.2.0.35 I started to encounter crashes on pages that are using SfListView. Downgraded back to 17.1.0.53, everything works like charm...

**Comment by jrahma** [comment]
@antoiodragos Yes I am using 17.2.0.35! oh no! I didn't expect Syncfusion will make such terrible problem for me

I'll try downgrading and publish to Google Play and let you know

**Comment by russelarms** [comment]
@jrahma do you have any updates?

**Comment by antoiodragos** [comment]
The issue is not reproducing anymore with Syncfusion 17.2.0.36.
@jrahma Can you confirm also on your side?

**Comment by jrahma** [comment]
> The issue is not reproducing anymore with Syncfusion 17.2.0.36.
> @jrahma Can you confirm also on your side?

I'll have to check it later because the issue happens when installing from Google Play Store but not when deploying to device.

I have uploaded my updated app to Play Store and will check it tonight and confirm

**Comment by jrahma** [comment]
Yes, latest version 17.2.0.36. has fixed the problem.

Thank you
