### ISSUE TITLE
[DOUBT]It's possible to be notified when some error occurs?

### ISSUE THREAD

**Issue by aismaniotto** [microsoft/appcenter#715]
I would like to know if has some way to be notified about new errors by the webhook (on my case, using the slack). I only got it when the app crash, but I also need to know when getting some error. 

I'm trying with `TrackError`.

Thanks a lot.

**Comment by winnieli1208** [comment]
Hi @aismaniotto - are you referring to unhandled errors (crashes) or handled errors? 

We support [webhooks](https://docs.microsoft.com/en-us/appcenter/dashboard/webhooks/) and [e-mail notifications](https://docs.microsoft.com/en-us/appcenter/dashboard/email-notifications/) so you can get notified when a crash occurs. You can also use our [Slack app](https://docs.microsoft.com/en-us/appcenter/dashboard/slack/) to get more information about your crashes. Note these features only work for unhandled errors (crashes) at the time.

**Comment by aismaniotto** [comment]
Uhmm, ok. That's answer my question. Maybe you have some ideia if has some prediction to handled errors feature?

**Comment by winnieli1208** [comment]
I don't have an estimated date at the moment but I will update you when I have more details. Thanks!

**Comment by charlesroddie** [comment]
+1
We think it's very important to be notified of errors as well as crashes.

**Comment by charlesroddie** [comment]
activity
