### ISSUE TITLE
Get notified/alerted when there's a high number of rollbacks in Codepush

### ISSUE THREAD

**Issue by gianpaj** [microsoft/appcenter#717]
**Context on issue**
I realised after a few days that our last React Native CodePush build had an issue and was being rolled back. An important feature blocked users as they needed to be on the latest version.

**Describe the solution you'd like**
Would be good to be notified if a high number of rollbacks are happening and nobody is activating the last version of the app. Maybe if the number of rollbacks is almost the same number of active devices. Or a % of them.

<img width="839" alt="Screen_Shot_2019-07-16_at_10_50_28" src="https://user-images.githubusercontent.com/899175/61275944-b0e28600-a7b7-11e9-9770-cc67d9e08868.png">

**Comment by botatoes** [comment]
Thanks for the suggestion. Will add this to the list of future improvements.
