### ISSUE TITLE
Ability to specify repo for Build by URL/ssh address

### ISSUE THREAD

**Issue by sapieneptus** [microsoft/appcenter#718]
**Describe the solution you'd like**

Would be nice if, instead of needing to wait for a potentially long list of repos to load and filter through them, we could just type/paste the git URL or ssh address. 

**Describe alternatives you've considered**
The current solution (navigating the hierarchy) also works, but it'd be nice to have other options. 

**Additional context**
_This is feedback from a dogfooding exercise_

**Comment by amchew** [comment]
Thanks @sapieneptus for your feature request! @nrajpurkar could you please take a look?

**Comment by nrajpurkar** [comment]
@sapieneptus, thanks for the request. This isn't currently on our roadmap, but we'll track this request for future interest.
