### ISSUE TITLE
Android Studio integration to App Center Test

### ISSUE THREAD

**Issue by sapieneptus** [microsoft/appcenter#719]
**Describe the solution you'd like**
It would be great to be able to upload directly from Android Studio (etc.) to App Center Test. This allows a less interrupted experience if one is actively developing features/tests in an IDE and wants to submit them to run on real devices. 

**Describe alternatives you've considered**
The only alternative is the CLI. 

**Additional context**
_This is output from a dogfooding exercise_

**Comment by nrajpurkar** [comment]
Thanks for the feature request @sapieneptus! Keeping this open to track future interest in this feature.
