### ISSUE TITLE
Database doesn't show up - at all

### ISSUE THREAD

**Issue by warrendodsworth** [microsoft/appcenter#724]
**What App Center service does this affect?**
Name of service or sdk with the issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by patniko** [comment]
Hi @warrendodsworth, mind elaborating a bit more so we have better context?
