### ISSUE TITLE
iOS automatic manage devices fails

### ISSUE THREAD

**Issue by hegra** [microsoft/appcenter#725]
**What App Center service does this affect?**
Automatically manage devices (ios)

**Describe the bug**
Enabling automatically manage devices and trying to upload p12 certificate says incorrect password. The upload of the same p12 file and password in the automatic signing for the build process works.

**To Reproduce**
0. Go to distribute/group/settings
1. Enable automatic manage devices
2. Add certificate
3. upload p12
4. input password

**Expected behavior**
The p12 cerificate should be approved by the password in the dialog box

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 75.0.3770.100

![appcenter-error](https://user-images.githubusercontent.com/2109380/61332122-c1304a80-a823-11e9-8e76-7871d2cc7eaa.png)

**Comment by amchew** [comment]
Thanks @hegra for the request! @Oddj0b and @botatoes could you please take a look?
