### ISSUE TITLE
Crash Report device string doesn't match crash report

### ISSUE THREAD

**Issue by mikewoodworth** [microsoft/appcenter#726]
**What App Center service does this affect?**
Diagnostics

**Describe the bug**
Crash reports from this machine are being tagged with the wrong device name in the report header:

<img width="488" alt="Screen Shot 2019-07-16 at 3 54 36 PM" src="https://user-images.githubusercontent.com/208050/61335346-0cc20480-a7e2-11e9-872d-d7c11b1be61a.png">

However in the Raw Report:
Hardware Model:      MacBookPro13,3

https://everymac.com/ultimate-mac-lookup/?search_keywords=MacBookPro13,3

**Comment by winnieli1208** [comment]
Hi @mikewoodworth - apologies for the delay. Can you start a support thread (blue chat bubble) so our support and engineering teams can get some more details? Thanks!

**Comment by mikewoodworth** [comment]
You mean in appcenter? I don't see a way to do that anymore.

**Comment by winnieli1208** [comment]
ah if you click on the ? icon in the upper right hand corner, you can file a support ticket via e-mail and which will then be triaged by our team. Thanks!

**Comment by DanRigby** [comment]
Hi @mikewoodworth, I can confirm that this is a bug in how we're reporting that device model.  I've implemented a fix but it may take some time for it to be deployed. I'd like to continue this conversation in the support thread that you've opened, so if it's alright with you, I'm going to close this GH issue in favor of that thread. Thanks!
