### ISSUE TITLE
Handle orphaned Install IDs

### ISSUE THREAD

**Issue by alexthekid07** [microsoft/appcenter#727]
It would be nice to have a method of knowing when an Install ID is expired or invalid upon sending.

A common scenario:
1. User "logs in"
2. You store the Install ID in a database
3. You send a push notification to a list of Install IDs
4. User uninstalls the app suddenly (without "logging out")
5. You now have an orphaned Install ID in your database

As it stands, since we're responsible for keeping a mapping of Install IDs in many scenarios, there is no straight-forward way to filter out which IDs are expired or invalid versus which are still active. I could potentially be sending push notifications to dozens of invalid IDs if a user uninstalls the app abruptly (never giving my server a chance to be notified to remove it).

For example, in Firebase FCM, you will immediately be returned a "NotRegistered" or "InvalidRegistration" for an Install ID/token immediately after POSTing to their API. This gives you the chance to recognize which IDs need to be removed and which are still usable.

As far as I'm aware this is not currently possible in App Center. All we really get in response to creating a push notification is the notification_id, of which does not seem to give a very accurate representation of expiration or validity. I would have to first record every single notification_id and then have some sort of scheduled reoccurring task pinging each notification_id to check if it failed or not...

I feel this is a pretty vital feature to a sustainable push notification system. Otherwise over time our databases of Install ID's (when applicable) will grow endlessly with garbage data. I realize the ability to Send-to-User is a thing, but this is for those of us who have to keep a mapping of IDs for the sake of things like ceasing push notifications when a user has clicked "log out" in their app.

**Comment by hamswan** [comment]
Thanks @alexthekid07 , we have added this to our feature request.
