### ISSUE TITLE
[Feature] GitLab (on perm) as source code service

### ISSUE THREAD

**Issue by WebDucer** [microsoft/appcenter#728]
**Describe the solution you'd like**
Currently only the GitLab.com is planed. We need the support of on permise installations of GitLab as a source code service in App Center to be able to use AppCenter for builds and not only distribution / crash reporting.

**Describe alternatives you've considered**
No alternatives

**Additional context**
There is already a feature request (#24) to use GitLab (on perm) as a bug tracker service, that would extend the support we need.

**Comment by nrajpurkar** [comment]
Thanks @WebDucer, this is related to #37 and something we are tracking for the future.

**Comment by nrajpurkar** [comment]
Closing this as we closed out #37
