### ISSUE TITLE
[Feature](codepush): ability to delete/ remove releases

### ISSUE THREAD

**Issue by ferdicus** [microsoft/appcenter#729]
**Describe the solution you'd like**
We currently amassed quite a number of releases on our codepush releases page.
It would be nice to trim that list as older releases are obsolete.

**Describe alternatives you've considered**
Filter options on `/distribute/code-push` to show only releases that are targeting specific version or something similar would already help a lot to mitigate the issue.

**Comment by amchew** [comment]
Thanks @ferdicus for the feature request! @botatoes would you mind taking a look please?

**Comment by ferdicus** [comment]
I'm still here, waiting

**Comment by ferdicus** [comment]
nope

**Comment by ferdicus** [comment]
.
