### ISSUE TITLE
Automatically create issues in GitHub from crashes

### ISSUE THREAD

**Issue by clairernovotny** [microsoft/appcenter#73]
It would be very useful if there was a rules-based way to create linked GitHub issues to crash reports. There should be a two-way link, so it's easy to get to the github issue from app center and to the crash report from GitHub.

Rules should enable things like specifying only unhandled exceptions and exceptions from the latest version, etc.

**Comment by amchew** [comment]
Hi @onovotny! Thanks for reaching out. We do have that functionality today to automatically create GitHub issues when there is a new crash group (https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/). You mention certain rules that are interesting! Right now we don’t have such rules. Could you elaborate on what rules you are looking for?

**Comment by onovotny** [comment]
I'm comparing this to what I use today with Bugsnag.

Here's some screen shots that may help:

Top level integration. Here I can specify labels that should be added to the issues created. I can optionally have it add a label for the version or release stage. Bugsnag uses "release stages" as an environment, so I can easily have a single view that spans dev, stage, prod and CI channels. I can apply views and rules based on those.
![image](https://user-images.githubusercontent.com/1427284/52811958-658b4680-3064-11e9-83cc-c43a5dd565c0.png)

I can configure my automation options, so issues close or reopen on either end appropriately:
![image](https://user-images.githubusercontent.com/1427284/52812074-a4b99780-3064-11e9-8384-5c958cbfbd71.png)

I can choose which severity levels to filter on (in this case, I want any):
![image](https://user-images.githubusercontent.com/1427284/52812107-b69b3a80-3064-11e9-9c9c-c850a0627181.png)

As some of the reporting may contain handled exceptions (exceptions sent from within a catch block), vs unhandled, I can filter on that. Here, I choose to only create issues based on unhandled exceptions:
![image](https://user-images.githubusercontent.com/1427284/52812150-d5013600-3064-11e9-9d68-5cef26add120.png)

Here, I decide which environments/stages I want to create issues for. As I have five channels for distribution, can opt to exclude ones that are developer ones from creating issues:
![image](https://user-images.githubusercontent.com/1427284/52812212-f7934f00-3064-11e9-85d7-c079688bc1f6.png)

**Comment by marksalpeter** [comment]
seconded

**Comment by amchew** [comment]
Thank you @onovotny (and @marksalpeter) for sharing all the details and the screenshots! I kept your feature request in our backlog, but we unfortunately don’t have an ETA to create this feature yet. I'll be keeping this bug open, and if others are interested in this feature, please give a thumbs up!
