### ISSUE TITLE
'Electron Framework' in stack is never symbolicated

### ISSUE THREAD

**Issue by torycl** [microsoft/appcenter#732]
**What App Center service does this affect?**
macOS crash dump symbolication in app center diagnostics

**Describe the bug**
There is native crash which contains 'Electron Framework' in the stack. Lines with 'Electron Framework' are never symbolicated even if correct dSYM bundle with symbols is uploaded.

**To Reproduce**
1. Find a native crash which contains some lines with 'Electron Framework'
2. Check these lines are not symbolicated. They look like: Electron Framework
0x107418000 + 622489.
3. Upload dSYM file for that used Electron Framework. Make sure it is the right one.
4. Check the same crash report again and it will still not be symbolicated.

I have tried that with libnode.so(.dSYM) and similar libraries and symbolication did work ok. I see this issue only with file "Electron Framework.framework.dSYM". 

**Expected behavior**
Show symbolicated stack trace with functions and lines.

**Screenshots**
![no-symbols-1](https://user-images.githubusercontent.com/3928694/61374314-5f5ff700-a89c-11e9-92bb-ac9f70cc754d.png)
![no-symbols-2](https://user-images.githubusercontent.com/3928694/61374346-71419a00-a89c-11e9-9164-f75294c5dadf.png)

**Desktop (please complete the following information):**
 - OS: macOS all versions
 - Browser: Google Chrome

**Comment by winnieli1208** [comment]
@torycl - thanks for filing an issue. App Center doesn't currently support Electron so what you're seeing is expected. This is something our team is looking into but we don't have immediate plans to support Electron. I'll change this issue to a feature request so our team can monitor community interest. 

Thanks!

**Comment by deepak1556** [comment]
@winnie what is the status on this one ? VS Code is also interested in this feature, it would be great to have this feature support for Electron apps transitioning from hockey app.

**Comment by winnie** [comment]
Hey @deepak1556! We don't have plans to officially support Electron but similar to HockeyApp, you can now upload your Electron crashes via the [upload crashes API ](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes). Hope that helps!

**Comment by deepak1556** [comment]
@winnie I was able to upload crashes but for macOS but they appear under the unsymbolicated tab even when the symbols are uploaded, also tried to select and ignore the versions for partial symbols following https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk#ignoring-symbols but doing that resulted in the app no longer displaying crashes from that version.

<img width="1670" alt="Screen Shot 2020-02-20 at 11 54 24 AM" src="https://user-images.githubusercontent.com/964386/74973193-db449380-53d7-11ea-9601-f98296552520.png">


The payload was

```json
{ 
   "logs":[ 
      { 
         "appLaunchTimestamp":"2020-02-20T19:50:41.676Z",
         "architecture":"X64",
         "device":{ 
            "appBuild":"7.1.12",
            "appNamespace":"com.microsoft.electron",
            "appVersion":"1.43.0",
            "carrierCountry":"us",
            "locale":"en-US",
            "model":"MacBookPro15,1",
            "oemName":"Apple",
            "osBuild":"10.14.6",
            "osName":"macOS",
            "osVersion":"10.14.6",
            "screenSize":"42x42",
            "sdkName":"appcenter.uwp",
            "sdkVersion":"2.4.1-SNAPSHOT",
            "timeZoneOffset":-480,
            "wrapperSdkName":"custom.ndk"
         },
         "exception":{ 
            "type":"minidump",
            "wrapperSdkName":"custom.ndk"
         },
         "fatal":true,
         "id":"0d8134dc-4df1-4b6b-b201-2ccf8ca50e68",
         "processId":62416,
         "processName":"VSCode",
         "sid":"8193f132-ad07-4812-b866-c283a0949a6d",
         "timestamp":"2020-02-20T19:51:08.593Z",
         "type":"managedError",
         "userId":"506029d2-5e57-473e-a2d5-75c678f97956"
      },
      { 
         "contentType":"application/octet-stream",
         "data":"", // some base64 encoded minidump goes here
         "device":{ 
            "appBuild":"7.1.12",
            "appNamespace":"com.microsoft.electron",
            "appVersion":"1.43.0",
            "carrierCountry":"us",
            "locale":"en-US",
            "model":"MacBookPro15,1",
            "oemName":"Apple",
            "osBuild":"10.14.6",
            "osName":"macOS",
            "osVersion":"10.14.6",
            "screenSize":"42x42",
            "sdkName":"appcenter.uwp",
            "sdkVersion":"2.4.1-SNAPSHOT",
            "timeZoneOffset":-480,
            "wrapperSdkName":"custom.ndk"
         },
         "errorId":"0d8134dc-4df1-4b6b-b201-2ccf8ca50e68",
         "fileName":"minidump.dmp",
         "id":"fc94e069-4201-439a-9d4d-c250724e901b",
         "sid":"8193f132-ad07-4812-b866-c283a0949a6d",
         "timestamp":"2020-02-20T19:51:08.593Z",
         "type":"errorAttachment"
      }
   ]
}
```

One thing to note is, I am creating the app with OS Android and platform Java/Kotlin on app center for testing my macOS electron app. Is this correct ?
