### ISSUE TITLE
Display user(s) affected for a given crash

### ISSUE THREAD

**Issue by jterhorst** [microsoft/appcenter#733]
**Describe the solution you'd like**
When viewing crash reports, our QA and staff engineers would like to be able to see the affected users for that crash, or the user for each crash report. We're able to search by user to find their crashes, but that info isn't clearly visible when viewing a crash from the Diagnostics section. This is an important part of the QA process when we work with our support team.

**Describe alternatives you've considered**
Searching works, but our current workaround is using the HockeyApp UI instead.

**Comment by winnieli1208** [comment]
@jterhorst thanks for the feature request! 

Are you referring to the "reports" page that has list of crash reports after you select a crash group? I want to make sure I understand what you're looking for. Thanks!

**Comment by jterhorst** [comment]
@winnieli1208 Yes, after I select the crash group. Under "reports", I can see "2 users" and "2 reports", but only one crash appears to be listed - when I click it, it only displays one of the user names. We're hoping for more details when we click on the crash group, and maybe username or other details on each of those crash rows.

Thank you!

**Comment by winnieli1208** [comment]
Got it, thanks for the clarification. I can definitely see why more information upon selecting a crash group would be valuable.

We don't have any immediate plans to address this but I will monitor this thread to help our team prioritize this in the future. Thanks!
