### ISSUE TITLE
Tags in Hockey app are missing in AppCenter

### ISSUE THREAD

**Issue by udayvalluri** [microsoft/appcenter#734]
Hokckey app allows me to create new tags and tag them to a group of similar apps which will help to filter the apps while I am seeing a big list. In my case we use multiple apps for multiple releases. So I want to filter the apps based on the release that I am currently in and the old release. Just filtering using the platform doesn't help in this situation. 

Please include this feature in AppCenter also which will help lot of people during their filter.

**Comment by derpixeldan** [comment]
@udayvalluri thank you for bringing this up. We won't be supporting this until the HockeyApp shutdown but we will keep the ticket and consider doing it in the future.

**Comment by udayvalluri** [comment]
@derpixeldan and @blparr. Hockey app is shut down now, do you have any near plan to consider this?

**Comment by udayvalluri** [comment]
@derpixeldan and @blparr : any update on this.

**Comment by dipree** [comment]
@udayvalluri sorry for the late reply. Unfortunately this is not a priority at the moment but we will definitely consider it.
