### ISSUE TITLE
AppCenter : Streamline Push Setup And Placement

### ISSUE THREAD

**Issue by bo3po** [microsoft/appcenter#735]
**Describe the solution you'd like**
Regarding push and layout structure in AppCenter. In AppCenter there should only be one app displayed. Not one for each platform. That is confusing. A app name "MyAwsomeApp" and underneath there should be all the platforms apps. Push should be pr platform. It should be possible to have multiple hubs foreach platform. In iOS there are typical two certificates. Prod and development. I can not add them very logical to the AppCenter right now. Does not make sense to me how it is today. I would suggest that each platform should have a list of notification hubs attached/underneath them. One for prod one for dev. And in iOS this would make a lot of sense since there are two certificates for that purpose.

**Describe alternatives you've considered**
I should make multiple apps that are 100% identical. A MyAwsomeApp-iOS-Development and a MyAwsomeApp-iOS-Production that would have the right keys attached. Then the production pipeline would be the one that should sign and deliver the app to the AppStore. The development is not building or delivering anything. All I need for that pipeline is the push which does snot make sense to me.

**Additional context**
None

**Comment by jwargo** [comment]
@bo3po Thank you for your suggestion, we’ve heard this many times from customers and the team is working on designing a solution.

**Comment by winnieli1208** [comment]
Related issue - #132

**Comment by bo3po** [comment]
Hi,

wow! that sounds great. thanks for the quick feedback.

  - bo

**Comment by jwargo** [comment]
@bo3po Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
