### ISSUE TITLE
Make version info and release notes available for apps submitted via HockeyApp

### ISSUE THREAD

**Issue by shidem** [microsoft/appcenter#736]
I was invited to a HockeyApp project, which I accepted. I then noticed that build artifacts were available to me in AppCenter (great!) and I can install from AppCenter.

Unfortunately, AppCenter does not provide build version info or release notes. I can only get those from the HockeyApp site. I would like this info available in AppCenter.

**Comment by lumaxis** [comment]
@shidem Thanks for reporting this! Both the version info and the release notes should actually be available in App Center too.
Could you send us a support request with a link to a specific release that has this issue and also mention this Issue? Then we can take a look at the data and see what's up.
