### ISSUE TITLE
We couldn’t find any Xamarin Android projects in your branch.

### ISSUE THREAD

**Issue by thomhubers** [microsoft/appcenter#737]
This issue is related to https://github.com/microsoft/appcenter/issues/379, but since that one was redirected to support it isn't resolved.

While using App Center Build tools, no configuration could be made because: "We couldn’t find any Xamarin Android projects in your branch."

Our solution lives at a deeper level `/x/y/z.sln` in a bit bigger repository. I'd suspect to be able to tell the tool where the android project resides. In another project a text box asked for the project name, so I thought that would be possible.

Can we avoid the "Searcher" and just tell App Center what project to build?

**Comment by nrajpurkar** [comment]
Hi @thomhubers, we don't currently have the ability to skip the analysis that App Center does and hardcode that. Feel free to rename this issue or create a feature request for this. I recommend reaching out to support to dig into this particular issue in your repo. I'm closing this out for now.

**Comment by toanxyz** [comment]
> This issue is related to #379, but since that one was redirected to support it isn't resolved.
> 
> While using App Center Build tools, no configuration could be made because: "We couldn’t find any Xamarin Android projects in your branch."
> 
> Our solution lives at a deeper level `/x/y/z.sln` in a bit bigger repository. I'd suspect to be able to tell the tool where the android project resides. In another project a text box asked for the project name, so I thought that would be possible.
> 
> Can we avoid the "Searcher" and just tell App Center what project to build?

We faced the same problem, it was the default behavior of project discovering process of AppCenter for Xamarin.Android limit 4 level of folder that they have mentioned here:  [For best performance, the analysis is currently limited to four directory levels including the root of your repository.](https://docs.microsoft.com/en-us/appcenter/build/xamarin/android/index#32-project-and-configuration)

The solution is moving up the project to upper folder.

**Comment by CDBridger** [comment]
I know this has been set to closed, but I have the solution in the top level of the folder (and all the projects are one folder deep), but the solution is not being discovered (only the projects). Is there a maximum number of folders in breadth the project discovery does? (We have separate folder for each project).

**Comment by TeddyAlbina** [comment]
> > This issue is related to #379, but since that one was redirected to support it isn't resolved.
> > While using App Center Build tools, no configuration could be made because: "We couldn’t find any Xamarin Android projects in your branch."
> > Our solution lives at a deeper level `/x/y/z.sln` in a bit bigger repository. I'd suspect to be able to tell the tool where the android project resides. In another project a text box asked for the project name, so I thought that would be possible.
> > Can we avoid the "Searcher" and just tell App Center what project to build?
> 
> We faced the same problem, it was the default behavior of project discovering process of AppCenter for Xamarin.Android limit 4 level of folder that they have mentioned here: [For best performance, the analysis is currently limited to four directory levels including the root of your repository.](https://docs.microsoft.com/en-us/appcenter/build/xamarin/android/index#32-project-and-configuration)
> 
> The solution is moving up the project to upper folder.

So AppCenter is a mess
