### ISSUE TITLE
App Center is not able to create Keystore file online

### ISSUE THREAD

**Issue by jingweihaha** [microsoft/appcenter#738]
I have Xamarin forms APPs in App Center, App Center currently is not able to create a Keystore file online, I have to generate one locally and upload it. Is it possible to make it happens on App Center?

**Comment by nrajpurkar** [comment]
@jingweihaha App Center does not create the keystore for you today. We will keep this open as a feature request for the future

**Comment by Jjagg** [comment]
While the App Center web interface does not support generating a keystore and key it would be nice to have the docs point devs to the JRE `keytool` (which they'll definitely have installed) to create the keystore and key. The [docs](https://docs.microsoft.com/en-us/appcenter/build/android/code-signing#generating-a-keystore) point us to Android Studio, which I did not have installed. It's a very bloated program to install just for the keytool.
