### ISSUE TITLE
Diagnostics not working

### ISSUE THREAD

**Issue by hugo0991** [microsoft/appcenter#739]
**What App Center service does this affect?**
It is not possible to upload the .zip file in Diagnostics section

**Describe the bug**
The page reload every time that I want to upload the .zip file 

**To Reproduce**
1. Go to 'Diagnostics.'
2. Click on 'upload symbols'
3. Click on 'Debug symbols ... upload a zip'
4. See error (same page is display it)

**Expected behavior**
See the crashes that my app has.

**Screenshots**

![Screen Shot 2019-07-17 at 4 04 57 PM](https://user-images.githubusercontent.com/49957111/61411822-e2894900-a8ac-11e9-81c7-affe3b14aefe.png)

**Desktop (please complete the following information):**
 - Browser: chrome, safari, edge

**Comment by winnieli1208** [comment]
Hi @hugo0991 can you please start a support ticket (blue chat bubble) so our support and engineering can take a look? Thanks!
