### ISSUE TITLE
Creating Custom Html Report after test run is over

### ISSUE THREAD

**Issue by GokulVijayan** [microsoft/appcenter#741]
I want to generate a custom report after the test run in app center.I have written code for that using the help of included files.But the problem is that the report is not being generated.It is generated when run locally.

Please find the code block used for generating the report after test run is over.

public static void WriteResultToHtml(List<TestReportSteps> listItems, List<string> filepath, string testObjective)
        {
            try
            {

                string currentDateTime = ConfigFile.getCurrentDateTime();
                int pathCounter = 0;
                StringBuilder color = new StringBuilder();
                StringBuilder status = new StringBuilder();
                // define a HTML String Builder
                StringBuilder actualResult = new StringBuilder();
                StringBuilder htmlStringBuilder = new StringBuilder();
                // append html header and title
                htmlStringBuilder.Append(
                        "<html><head><link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n"
                                + "<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script><title>Selenium Test </title></head>");

                // append body
                htmlStringBuilder.Append("<body>");
                // append table

                htmlStringBuilder.Append("<table class=\"table table-striped table-bordered\">");
                htmlStringBuilder.Append("<tr><th style=\"background-color:#a6a6a6\">Date Time</th><td>"
                    + currentDateTime
                    + "</td><th style=\"background-color:#a6a6a6\">Environment Tested</th><td>QC</td></tr><tr><th style=\"background-color:#a6a6a6\">OS</th><td>"+ "Android" +"</td><th style=\"background-color:#a6a6a6\">Model</th><td>"+ "Samsung" + "</td></tr><tr><th style=\"background-color:#a6a6a6\">Script Name</th><td> iMAAP Mobile App</td><th style=\"background-color:#a6a6a6\">Platform Version</th><td>"+ "8.0" + "</td></tr><tr><th style=\"background-color:#a6a6a6\">Objective</th><td colspan=\""
                    + 3 + "\">" + testObjective + "</td><tr><tr></table>");

                // append row
                htmlStringBuilder.Append("<table class=\"table table-striped\">");
                htmlStringBuilder.Append(
                        "<thead style=\"background-color:#a6a6a6\"><tr><th><b>TestObjective</b></th><th><b>StepName</b></th><th><b>StepDescription</b></th><th><b>ExpectedResult</b></th><th><b>ActualResult</b></th><th><b>Status</b></th><th><b>Screenshot</b></th></tr></thead><tbody>");
                // append row
                foreach (var a in listItems)
                {
                    if (!(string.IsNullOrEmpty(a.getActualResultFail())))
                    {
                        status.Append("Fail");
                        color.Append("red");
                        failedSteps++;
                        actualResult.Append(a.getActualResultFail());

                    }
                    else
                    {
                        status.Append("Pass");
                        color.Append("green");
                        passedSteps++;
                        actualResult.Append(a.getActualResultPass());

                    }
                    string check = a.getStepDescription().ToLower();
                    if (a.getStepDescription().ToLower().Contains("screenshot"))
                    {
                        htmlStringBuilder.Append("<tr><td style=\"font-weight:bold\">" + a.getTestObjective() + "</td><td>" + a.getStepName()
                                + "</td><td>" + a.getStepDescription() + "</td><td>" + a.getExpectedResult() + "</td><td>"
                                + actualResult + "</td><td style=\"color:" + color + ";font-weight:bolder;\">" + status
                                + "</td><td><a href=\"" + filepath[pathCounter++] + "\">Click here</a></td></tr>");
                    }

                    else
                    {
                        htmlStringBuilder.Append("<tr><td style=\"font-weight:bold\">" + a.getTestObjective() + "</td><td>"
                                + a.getStepName() + "</td><td>" + a.getStepDescription() + "</td><td>"
                                + a.getExpectedResult() + "</td><td>" + actualResult + "</td><td style=\"color:" + color
                                + ";font-weight:bolder;\">" + status + "</td><td></td></tr>");
                    }
                    actualResult.Remove(0, actualResult.Length);
                    color.Remove(0, color.Length);
                    status.Remove(0, status.Length);
                }

                // close html file
                htmlStringBuilder.Append("</tbody></table></body></html>");

                // write html string content to a file

                htmlFilepath = "Configuration/TestReport.html";
                

                WriteToFile(htmlStringBuilder.ToString(), htmlFilepath);

            }
            catch (IOException e)
            {
                Console.WriteLine("Exception" + e);
            }
        }

        /**
        * Write html report to file
        */
        public static void WriteToFile(string fileContent, string fileName)
        {
            using (FileStream fs = new FileStream(fileName, FileMode.Create))
            {
                using (StreamWriter w = new StreamWriter(fs, Encoding.UTF8))
                {
                    w.WriteLine(fileContent);
                    Console.WriteLine(fileContent);
                    Console.WriteLine(Directory.GetCurrentDirectory());
                    Console.WriteLine("Writing to file "+ fileName);
                }
            }

        }

Here Configuration/TestReport.html file have been added as a included file and i have set the property as Copy to Output Directory > Copy if newer.
Also i have added the screenshot for the solution explorer in visual studio and the task to be run in the azure pipeline for running tests in app center.

The html file will get created after all the steps in the test has been executed,ie only at the last step the report gets generated.I have written methods for generating the html file.The problem i am facing is that the file is not being generated when it is run via app center.I think it has to do with the way in which file can be accessed.
Please find the code block used for calling the generate report method.
Report.WriteResultToHtml(report, screenshotList, testObjective);

![appcentertask](https://user-images.githubusercontent.com/37167275/61424222-801b6180-a91b-11e9-93af-89de40c86ce6.PNG)
![AppCenter](https://user-images.githubusercontent.com/37167275/61424223-801b6180-a91b-11e9-883f-f9f17a05f23d.PNG)

**Comment by amchew** [comment]
Hi @GokulVijayan, thanks for reaching out with your feature request! We'll get back again. fyi @Oddj0b

**Comment by Oddj0b** [comment]
@GokulVijayan This sounds promising, would you prefer to get the file through API, CLI or something third?

**Comment by GokulVijayan** [comment]
@Oddj0b Yes Please
