### ISSUE TITLE
When I use Xamarin.UITest 3.0.0 tools and execute tests on Appcenter, test run is allways empty

### ISSUE THREAD

**Issue by emrah-dautbegovic-sleepnumber** [microsoft/appcenter#742]
**What App Center service does this affect?**
Name of service or sdk with the issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nrajpurkar** [comment]
Thanks for opening this bug - are you still facing this issue? @Oddj0b will be able to take a further look and assist.
