### ISSUE TITLE
Unable to upload a new IPA for the new application

### ISSUE THREAD

**Issue by mugunth87** [microsoft/appcenter#743]
Unable to upload the IPA file

Getting an error Upload Failed, Please try again

<img width="598" alt="Screen Shot 2019-07-18 at 10 55 32 AM" src="https://user-images.githubusercontent.com/16566598/61476698-de136d80-a94a-11e9-811f-452166d55d50.png">

**Comment by kfcampbell** [comment]
Hello! Would you mind reaching out via Intercom, the support channel on the App Center site? We're better able to provide personalized attention that way!
