### ISSUE TITLE
AppCenter doesn't handle TCP connection errors on macOS

### ISSUE THREAD

**Issue by davestjohn** [microsoft/appcenter#744]
**What App Center service does this affect?**
AppCenter and Analytics

**Describe the bug**
Occasionally while submitting an event the data never gets to the server.  Digging through the log files reveals a TCP connection issue which isn't handled.  The trackEvent call silently fails and leads to missing data.

**To Reproduce**
Not sure how to reproduce, this happens sporadically.  

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 10.14.5
 - AppCenter SDK 2.1.0

**Additional context**
The error logged is:  TIC TCP Conn Connected [1:0x7faf95c14ed0]: Err(16)

Here is the sequence from the console log.  XRAnalyticsCommunications is a XPC service that submits the event and is linked to the AppCenter and AppCenterAnalytics libraries.

default	14:34:57.682401 -0400	XRAnalyticsCommunications	nw_endpoint_flow_protocol_connected [C1.1 IPv4#012a0149:443 in_progress socket-flow (satisfied)] Output protocol connected
default	14:34:57.682510 -0400	XRAnalyticsCommunications	nw_connection_report_state_with_handler_locked [C1] reporting state ready
default	14:34:57.682788 -0400	XRAnalyticsCommunications	TIC TLS Event [1:0x7faf95c14ed0]: 20, Pending(0)
default	14:34:57.682842 -0400	XRAnalyticsCommunications	TIC TCP Conn Connected [1:0x7faf95c14ed0]: Err(16)
default	14:34:57.683037 -0400	XRAnalyticsCommunications	TIC TCP Conn Event [1:0x7faf95c14ed0]: 1
default	14:34:57.683092 -0400	XRAnalyticsCommunications	TIC TCP Conn Event [1:0x7faf95c14ed0]: 8
default	14:34:57.683131 -0400	XRAnalyticsCommunications	TIC TLS Handshake Complete [1:0x7faf95c14ed0]
default	14:34:57.683376 -0400	XRAnalyticsCommunications	Task <1F4704A0-0C82-442D-92D5-7CAD003364C0>.<1> now using Connection 1
default	14:34:57.684539 -0400	XRAnalyticsCommunications	nw_endpoint_flow_protocol_connected [C1.1 IPv4#012a0149:443 ready socket-flow (satisfied)] Output protocol connected
default	14:34:57.685159 -0400	XRAnalyticsCommunications	Task <1F4704A0-0C82-442D-92D5-7CAD003364C0>.<1> sent request, body S
default	14:34:57.709798 -0400	XRAnalyticsCommunications	Task <1F4704A0-0C82-442D-92D5-7CAD003364C0>.<1> received response, status 200 content K
default	14:34:57.709908 -0400	XRAnalyticsCommunications	Task <1F4704A0-0C82-442D-92D5-7CAD003364C0>.<1> response ended
default	14:34:57.709969 -0400	XRAnalyticsCommunications	Task <1F4704A0-0C82-442D-92D5-7CAD003364C0>.<1> done using Connection 1

**Comment by nrajpurkar** [comment]
Thanks for this bug report @davestjohn. Tapping in @hamswan to take a look at this.

**Comment by davestjohn** [comment]
Hi, I've upgraded to v4.1.0 of the SDK and haven't looked into this issue since this report.  I haven't had reports of missing data from testers in a while so I would suspect this may have been an issue in either the v2 SDK or macOS 14.x (which I no longer support). Thanks.

**Comment by AnastasiaKubova** [comment]
Hi! Glad to hear that your issue was resolved. 
I'm closing this issue but feel free to reopen this issue if you have additional questions. 
Thanks for using App Center!
