### ISSUE TITLE
How do I use my executables version as my package version?

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/appcenter#745]
**What App Center service does this affect?**
Build of WPF+`.wapproj` apps.

**Describe the bug**
I'm not storing versions for my `.wapproj` in source control, my application is generating its version using the [gitversion](https://gitversion.readthedocs.io/en/latest/more-info/variables/) msbuild plugin.

Unfortunately, when my app builds, it's coming out with version `0.0.0.0`. Is there any way to tell app center to provide a version based on the executable?

**Comment by nrajpurkar** [comment]
App Center doesn't support building WPF apps today. We only support building [UWP apps in C#](https://docs.microsoft.com/en-us/appcenter/build/windows/).

**Comment by atrauzzi** [comment]
I'm building a new msix project right now?

**Comment by stephan-markovic** [comment]
The action is unsupported.
