### ISSUE TITLE
All Builds cancelled

### ISSUE THREAD

**Issue by jkobow** [microsoft/appcenter#747]
**What App Center service does this affect?**
Builds

**Describe the bug**
When we run a build it starts but is cancelled immediately 

**To Reproduce**
1. Go to builds -> branches 
2. Click on the gear on a branch
3. Build Now

**Expected behavior**
Run a build

**Comment by nrajpurkar** [comment]
Looks like the same as #746, we're aware of this and looking into the issue.

**Comment by DennisPan** [comment]
@jkobow Thanks for reaching out. This issues should be fixed now. Let us now if you see anything else.

**Comment by IljaCuvasov** [comment]
@dennispan the issue is back, same with #746

**Comment by dennispan** [comment]
@IljaCuvasov sorry I no longer work on App Center
