### ISSUE TITLE
Support Cocoapods Source Podspec

### ISSUE THREAD

**Issue by lickel** [microsoft/appcenter#748]
**Describe the solution you'd like**
HockeyApp used to provide a source distribution of their library. AppCenter should similarly offer that as a Podspec. This prevents issues where we cannot enable the library due to binary incompatibilities. New architectures are held back when there's a binary-only distribution.

**Describe alternatives you've considered**
N/A

**Additional context**
This is particularly relevant for us now as Catalyst apps can't currently use AppCenter.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @lickel. Tapping in @hamswan to take a deeper look at this.
