### ISSUE TITLE
[Feature] Support Android Source Maps for React Native apps

### ISSUE THREAD

**Issue by Eyesonly88** [microsoft/appcenter#75]
**Describe the solution you'd like**
Support source maps on Android for React Native apps. Currently only supported on iOS. 
See https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/208

**Describe alternatives you've considered**
Without the source maps on Android, we can't understand crash logs because the stack traces don't trace back to the JavaScript side.

**Additional context**
This feature works for iOS already and it is very useful to know which line of code and file is causing the crash. No idea how this is not done already.

**Comment by Eyesonly88** [comment]
Hey @patniko @winnieli1208, can you please comment regarding this issue? all the other top voted requests have comments/follow-ups.

**Comment by winnieli1208** [comment]
Hi @Eyesonly88, thanks for submitting the feature request. We understand this is a crucial feature for React Native developers and it's definitely on our radar. I am actively monitoring community interest to help our team prioritize and will post here with any updates.

**Comment by gchiacchio** [comment]
Any chance to workaround this with a post build script? My client has a paid account and crash reports are not useful at all. I'm close to recommend him to switch to other service.

**Comment by winnieli1208** [comment]
@gchiacchio you might be able to use a build script to retrieve the source map file but our diagnostics service doesn't support uploading/processing these files so I'm not sure that would work. 

Our team is busy working on the HockeyApp transition features which is why we haven't prioritized this yet. We do understand this is a major limitation and we hope to address this in the future but unfortunately, I don't have an ETA at this time.

**Comment by gchiacchio** [comment]
@winnieli1208 That would be an improvement.

- Can you provide a way to retrieve the source map out of the server with a build script? 

- Please let me know what options you can think of... like email, ftp, dropbox, gdrive, or even the iOS upload symbols API [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/iOS-symbolication#app-center-api)

**Comment by gchiacchio** [comment]
@winnieli1208 @Eyesonly88 after my last message, I've been trying to upload the generated file by using the upload symbols API, and found a way.

Hope this help others.

Snippet for the post build script...
```bash
    if [ "$AGENT_JOBSTATUS" == "Succeeded" ]; then

#Step1
        mappingData=$(curl -X POST "https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/symbol_uploads" \
            -H "accept: application/json" \
            -H "X-API-Token: $MY_APPCENTER_API_TOKEN" \
            -H "Content-Type: application/json" \
            --fail \
            -d '{
                    "symbol_type": "AndroidProguard",
                    "file_name": "mapping.txt",
                    "build": "'"$versionCode"'",
                    "version": "'"$versionName"'"
                }')

        if [[ $? == 0 ]]; then
#Step2
            mappingSymbolUploadId=$(echo ${mappingData} | python -c "import json,sys;obj=json.load(sys.stdin);print obj['symbol_upload_id'];")
            mappingUploadURL=$(echo ${mappingData} | python -c "import json,sys;obj=json.load(sys.stdin);print obj['upload_url'];")

            curl -X PUT \
            "$mappingUploadURL" \
            -H 'x-ms-blob-type: BlockBlob' \
            -T "$APPCENTER_SOURCE_DIRECTORY/app/build/outputs/mapping/develop/release/mapping.txt" \
            --silent \
            --show-error \
            --fail

            if [[ $? == 0 ]]; then
                mappingUploadStatus="committed"
            else
                mappingUploadStatus="aborted"
            fi
#Step 3
            curl -X PATCH "https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/symbol_uploads/$mappingSymbolUploadId" \
                -H "accept: application/json" \
                -H "X-API-Token: $MY_APPCENTER_API_TOKEN" \
                -H "Content-Type: application/json" \
                -d '{ "status": "'"$mappingUploadStatus"'"}'
        else
            echo "Couldn't upload mapping file"
        fi

    fi

```

## Reference
Build scripts - [post puild](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/index#post-build)
Build scripts - [variables](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#app-center-variables)
Acquiring an App Center - [API token](https://docs.microsoft.com/en-us/appcenter/api-docs/#acquiring-an-app-center-api-token)
Upload symbols with App Center API 
- [Guide](https://docs.microsoft.com/en-us/appcenter/diagnostics/iOS-symbolication#app-center-api)
- [Step 1](https://openapi.appcenter.ms/#/crash/symbolUploads_create)
- Step 2 you can see in the snippet above
- [Step 3](https://openapi.appcenter.ms/#/crash/symbolUploads_complete)

**Comment by ranterle** [comment]
@gchiacchio I think your latest comment refers to uploading Android ProGuard mappings. Thanks for providing a sample post build script which can achieve this. This is part of our June iteration plan #466 and while we can't promise any immediate availability date, we're excited to share more about this soon.

**Comment by hccoelho** [comment]
Hi @winnie, did you guys have a chance to prioritize this one? This seems a big deal breaker for all os us who want to leverage appcenter for crashes. Since it has been several months since your last update, I was wondering if the team had the chance to look into it. Thanks

**Comment by winnie** [comment]
Hey @hccoelho thanks for checking in. Unfortunately I don't have an ETA for you but this is on the top of our list after we finish the rest of the HockeyApp features on our roadmap, around early next year. I know this is a top requested feature and we hope to address this very soon. Thanks for the patience!

**Comment by barnabyc** [comment]
Hello @winnie, it's been a couple months, just checking in again. Is it possible to understand how long the remaining HockeyApp roadmap is scheduled to run until? Any sense of timeframe will greatly help my team evaluate alternate solutions to resolving this situation. Thanks!

**Comment by Eyesonly88** [comment]
One year later and more than 150 votes and still not even started 👏

**Comment by tdekoning** [comment]
I was hoping we could use AppCenter for our crash logging, then i ran into this issue...

Any idea when it will be added?

**Comment by wildseansy** [comment]
FWIW I am likely going to just use [bugsnag](https://www.bugsnag.com/) or [Sentry](https://sentry.io/). They seem to have much better support for RN traces.

**Comment by adammcarth** [comment]
Just to be clear to anyone else reading this... at the present time Visual Studio App Centre is **virtually useless** for reporting crashes on Android React Native. All it's going to tell you is that there _was_ a crash, but give zero context of where or how it happened. It's a very painful discovery to make - especially after investing so much time in setting up App Center as our core analytics/crash logs tool.

Compare an identical crash report on iOS vs. Android below...

### iOS

![iOS App Center Crash Report](https://imgkk.com/i/8jj0.png)

### Android

![Android App Center Crash Report - Useless](https://imgkk.com/i/an2y.png)

**Comment by NourAbdelAal** [comment]
@Eyesonly88 I totally get your point about supporting source map files on both iOS and Android for the react native platform, which in essence is the quality and stability of your app.

Aside from missing such a critical feature in AppCenter, for your app crashes to show up with a fully symbolicated/deobfuscated stack trace, at **Instabug**, we will **automatically** generate the source map files and upload them to your dashboard on release build in **both** Android and iOS sides for JavaScript crashes.

I recommend you have a look at this particular part in our docs through this [link](https://docs.instabug.com/docs/react-native-symbolication-obfuscation) and please don’t hesitate to reach out to me on "nour.abdelaal@instabug.com" for further details. I’d be more than happy to accommodate a quick demo and show you this in action.

**Comment by zanechua** [comment]
First of all, sorry for everyone who's subscribed to this issue.

@NourAbdelAal 

I'm not sure if you've used GitHub before so maybe there's some benefit of doubt to be given? But this is a ticket for AppCenter. I don't think it's appropriate coming onto a repo's ticket to start selling your service. If you have something to contribute to the particular ticket, I'm sure everyone wants to hear about it but otherwise it would be nice to keep the tickets relevant to the topic at hand.

**Comment by winnie** [comment]
👋 Hey all! Sorry for the long delay. We have not been able to prioritize this in the last few months - after finishing the HockeyApp transition and feature gaps, we shifted our focus on some engineering improvements around stability and scalability. Unlike many other crash reporting products in the market, we offer a free service and need to make some hard prioritization decisions.

I hear you and know it can be extremely frustrating to see little movement on this after an entire year. I will avoid committing to a timeline but this is something our team is actively considering. You will all be the first to hear when I have good news to share!

**Comment by m-ruhl** [comment]
@winnie Any news.. another 6 months have gone by..

**Comment by normenster** [comment]
@winnie we`re considering using AppCenter Analytics for our react native app, but missing sourcemaps on Android ist a major blocker. Is there some kind of roadmap regarding the release of this feature?

**Comment by mblaschak-clinone** [comment]
App Center has been very exciting to explore for my organization, but this is definitely a gap that needs filled for real production use in react native applications

**Comment by barnabyc** [comment]
@m-ruhl @normenster looks like @winnie isn't with Microsoft any longer, so we're back to perhaps finding another Product Manager on the AppCenter team. I'd suggest you use the Contact Us within AppCenter itself and see if you can get traction/insights on product roadmap plans. That's my plan. 🤞

**Comment by nidheeshdas** [comment]
@barnabyc ... or switch to another service like Sentry.

**Comment by wildseansy** [comment]
I highly recommend Bugsnag for crash reporting for react native apps. Their sourcemap support is very comprehensive.

**Comment by normenster** [comment]
@wildseansy Yeah, we`re switching completely to Bugsnag. Besides the Sourcemapping Feature, there are a lot more other features that are very useful.

**Comment by kokeksibir** [comment]
Any thoughts on instabug, has anyone tried it?

**Comment by tdekoning** [comment]
We've switched to Crashlytics, it reports the JS traces minified, but we can apply source maps manually to determine the cause of an issue. 
Native crashes (both iOS and Android) are properly managed in Crashlytics.

**Comment by Eyesonly88** [comment]
@ahdbilal can you please let us know the state of this feature request? or tag any other PM who may know what's happening with this?

**Comment by ahdbilal** [comment]
@Eyesonly88 While I am no longer working on App Center, I will pass it internally to the right team.

**Comment by RobinTD** [comment]
We are evaluating App Center for our organisation, and this is a deal breaker.

**Comment by slimCODE** [comment]
The obligatory reply to keep this alive.

Is React Native really not important for Microsoft?

**Comment by zanechua** [comment]
obligatory bump

**Comment by anutting** [comment]
Setting up source maps for my react-native project. Has anybody had success yet? Do I upload a zip with the index.bundle.android.map, mappings.txt, and an index.android.map generated by react-native?

**Comment by Eyesonly88** [comment]
The obligatory reply to keep this alive.

Is React Native really not important for Microsoft?

**Comment by tsdmrfth** [comment]
Came this issue thread 2 years later and all I see is the feature is not finished yet!

**Comment by andac-ozcan** [comment]
This could be a game changer since all Firebase, Datadog and Sentry don't have this feature for RN yet. I'm telling because I test all.

**Comment by liamjones** [comment]
Sorry, slightly OT since this isn't about App Center's lack of support:

>This could be a game changer since [...] Sentry don't have this feature for RN yet.

@andac-ozcan are you talking about the JS sourcemaps? Because Sentry does support those on Android via RN - we make use of them daily. Sentry's gradle plugin uploads them automatically when you do a release build (if you have a standard RN project, it needs a bit of config if you have a non-standard project).

>Is React Native really not important for Microsoft?

I don't think that's necessarily true. Microsoft, as an entity, invests in RN quite a lot. See all the work they do on [react-native-windows](https://microsoft.github.io/react-native-windows/) and the stuff Microsoft employees commit back to the core RN project as well. Whether or not it's not important to the App Center team specifically is a different question.

**Comment by andac-ozcan** [comment]
> Sorry, slightly OT since this isn't about App Center's lack of support:
> 
> > This could be a game changer since [...] Sentry don't have this feature for RN yet.
> 
> @andac-ozcan are you talking about the JS sourcemaps? Because Sentry does support those on Android via RN - we make use of them daily. Sentry's gradle plugin uploads them automatically when you do a release build (if you have a standard RN project, it needs a bit of config if you have a non-standard project).
> 
> > Is React Native really not important for Microsoft?
> 
> I don't think that's necessarily true. Microsoft, as an entity, invests in RN quite a lot. See all the work they do on [react-native-windows](https://microsoft.github.io/react-native-windows/) and the stuff Microsoft employees commit back to the core RN project as well. Whether or not it's not important to the App Center team specifically is a different question.

Yeah my bad, did a mistake on Sentry configuration. Now source maps are uploading during build. Seems Sentry and BugSnag have the real support for React Native crash tracking. DataDog says it'll be available before the end of 2022, Firebase not giving any estimation at all.

**Comment by zanechua** [comment]
obligatory bump

**Comment by muhamedzeema** [comment]
any update on this

**Comment by AngeeelD** [comment]
is there any update on this?

**Comment by joseduran-hrbl** [comment]
HI guys, I was testing a way to create the source maps using custom appcenter scripts and upload them in a separated server or put them in the output folder, and I just noted this new option on my iOS pipelines:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/44730649/187277440-fc6c2e9e-61b5-44ff-b20f-c8b2995f317a.png">

**Comment by AngeeelD** [comment]
Hi guys, I was testing a way to create the source maps using custom app center scripts and upload them to a separated server or put them in the output folder, and I just noted this new option on my iOS pipelines:
![image](https://user-images.githubusercontent.com/8499195/187280016-1ca2fc53-3727-45bd-ac9f-35598a15c30d.png)

**Comment by TripleSpeeder** [comment]
*bump* Just to let you know people are still waiting for this feature...

**Comment by tpisto** [comment]
What is best alternative for AppCenter? Seems MS has pretty much abandoned it, or there is some summer intern working on it occasionally. AppCircle?

**Comment by mickey35vn** [comment]
plz tell me about the status of this feature...

**Comment by sjarvela89** [comment]
Hi all! I ran into this on the hard way as I have tried to create mapping files and bundles for few days. I would say it is still an open case.

**Comment by daniel-parlapan** [comment]
@winnie Not sure why this item was closed. May be just people losing hope and moving to other tools. 

We still have this  `Note: At this time, App Center doesn't support source maps to unminify JavaScript stack traces for Android React Native apps.`

What are your thoughts after more than 3 years? 
Can you at least reopen the issue and track it?

**Comment by unstoo** [comment]
Dear, App Center team!

Thank you for the great product. Many of us still do believe that the source maps would be a great improvement.

**Comment by ls-barnaby-claydon** [comment]
Sadly at this point I think it's pretty clear Microsoft has abandoned AppCenter. The last commit to master was over a year ago: Aug 17, 2022.

I'd suggest everyone switch to a different product. I've been looking at Google Firebase's Crashlytics.
