### ISSUE TITLE
Crash Geographical Map

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#750]
Hi,

Please provide crash geographical map so it will be clear and easy to know where is the most problems coming from. For example if the service ip or port is blocked in one country then it will be shown that all users having problems are coming from that country

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by winnieli1208** [comment]
Thanks for the feature request! We don't have immediate plans to add this but I will monitor this thread for community interest. I'll post updates here if I have any.
