### ISSUE TITLE
Missing app icon in distribution email.

### ISSUE THREAD

**Issue by alexeyvolkov-dev** [microsoft/appcenter#751]
**What App Center service does this affect?**
Distribution email.

**Describe the bug**
Recently I have added an icon to my iOS Project. 
However, the distribution email still has a default image.

**Expected behavior**
I believe the distribution email should show my icon instead of the default one. 

**Screenshots**

<img width="363" alt="Screen Shot 2019-07-21 at 21 38 59" src="https://user-images.githubusercontent.com/44066599/61595469-49d23080-ac00-11e9-8c21-7f90f63e1adb.png">

Thanks in advance.

**Comment by botatoes** [comment]
Hi, did you upload the image on App Center? Does your .ipa have an image in it?

**Comment by alexeyvolkov-dev** [comment]
Hello, sorry for the delay. 
Yes, I need help with that. Yes, I've uploaded the icon to the app center, which is visible on the web. 
Also, the icon is added to the IPA (to iPhone App, iPad Pro, AppStore) 
But email contains no icon. As on the screenshot. 
Please, reopen.

Thanks in advance.

**Comment by botatoes** [comment]
Can you open a support ticket on intercom on appcenter.ms? We'll get more info about your app and someone from the engineering team will be able to help you out.
