### ISSUE TITLE
Ability to add comments to UWP crashes like on iOS

### ISSUE THREAD

**Issue by RaulRus** [microsoft/appcenter#752]
Hi there,

Currently there is no possibility to add comments to crashes on UWP crashes.
Can we get that feature like on iOS?

**Comment by winnieli1208** [comment]
Hi @RaulRus - thanks for the request! We plan to add this in the upcoming months (target date is around September) as part of our Windows support improvements. I'll post here when I have updates.

**Comment by winnieli1** [comment]
Hi @RaulRus! We just enabled the new diagnostics experience for UWP with the 2.5.0 SDK release which includes adding comments to your crashes and errors. 

Closing this issue for now but let me know if you run into any problems. Thanks!
