### ISSUE TITLE
Cordova - Re-sign app & upload new release fails

### ISSUE THREAD

**Issue by ciaranmccaughey** [microsoft/appcenter#753]
**What App Center service does this affect?**
Cordova Re-sign app & upload new release constantly says validating.

**Describe the bug**
Cordova registering 2 unprovisioned devices for a new release fails when Re-signing the app. Constantly says validating.

**To Reproduce**
1. States "There are 2 unprovisioned devices"
2. Click on "Register Devices"
3. Check Resign App
4. Click Register

**Expected behavior**
App should Re-signs and I can distribute app to these users.

**Screenshots**
![Distribution_progress_·_Build_Inspection_Beta_·_App_Center](https://user-images.githubusercontent.com/7217500/61642155-56a26300-ac98-11e9-8714-ab932b20ef63.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser Chrome & Firefox

**Comment by winnieli1208** [comment]
Hi @ciaranmccaughey - thanks for opening an issue! Can you start a support thread via the blue chat bubble on the bottom left? This will put you in touch with our support and engineering team so they can help troubleshoot. 

In the meantime, @Oddj0b can jump in if there are any suggestions.

**Comment by Oddj0b** [comment]
@ciaranmccaughey did you get help through our support channel?
