### ISSUE TITLE
Moving our app from HockeyApp is failing

### ISSUE THREAD

**Issue by lickel** [microsoft/appcenter#755]
**What App Center service does this affect?**
Overview / Move Apps

**Describe the bug**
The panel for moving the app is 500-ing the `/hockeyapp_compatibility` API call.
The error message is `ESOCKETTIMEDOUT`
with a stack trace pointing to `/home/node/data/node_modules/request/request.js:816:19`

**To Reproduce**
1. Go to an app overview page
2. Click on "Move this app"
3. Wait on the compatibility check in the side panel
4. See error "Something went wrong, please try again"

**Expected behavior**
"No Issues" message, allowing us to proceed

**Screenshots**
<img width="1278" alt="Screen Shot 2019-07-22 at 12 14 43 PM" src="https://user-images.githubusercontent.com/263461/61658478-4e3b2f80-ac7a-11e9-932e-d92b45eea175.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 13

**Additional context**

**Comment by derpixeldan** [comment]
@lickel thanks for bringing it up, we're looking into it. Is it happening all the time or just occasionally?

**Comment by lickel** [comment]
Our App Store app has failed every time. Our CI build initially kept failing, but randomly worked so I immediately proceeded

**Comment by tanhuynhngoc** [comment]
@derpixeldan Our app has encountered the same issue at this moment. Seem like it just occurred some days ago.

**Comment by derpixeldan** [comment]
We've deployed an optimization which should solve the problem. Please let me know if it's working for you now.

**Comment by lickel** [comment]
That worked for me, thanks!

**Comment by tanhuynhngoc** [comment]
> We've deployed an optimization which should solve the problem. Please let me know if it's working for you now.

Hi @derpixeldan, I still got this issue while submit moving an iOS app from HockeyApp to AppCenter.

**Comment by derpixeldan** [comment]
@tanhuynhngoc it's a different issue than what this ticket is about. However, we've improved the error you're getting in that case. When you can't submit to move the app, you don't have sufficient permission as an owner of the organization on HockeyApp. You need to have control over "All Apps" (which is an owner flag in HockeyApp) to be able to move apps.
