### ISSUE TITLE
Push notifications are not being processed or are delayed

### ISSUE THREAD

**Issue by peter-raehse** [microsoft/appcenter#756]
**What App Center service does this affect?**
Android Push via appcenter GUI or via Xamarin.Forms SDK

**Describe the bug**
Since 2019-07-22 about 18:00 UTC Android push notifications seem not to be processed at all or they are delayed. If I send a notification manually via GUI it is accepted but after that it doesn't  appear in the list of sent notifications, neither as success nor as failed.  Also they are not being delivered to the device.

iOS Push seems to be operational.

**Comment by jwargo** [comment]
@peter-raehse thank you for reporting this. When you have an issue with the service, please contact our dedicated support team. We are not aware of an issue yesterday, are you still experiencing it?

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
