### ISSUE TITLE
can you please help me to integrate app center crash report form ionic 3 ? 

### ISSUE THREAD

**Issue by Dipeshjayswal** [microsoft/appcenter#757]
can you please help me to integrate app center crash report form ionic 3 (in ios platform)?

**Comment by jwargo** [comment]
@Dipeshjayswal Ionic is not a supported platform, but as Ionic 3 is based on Apache Cordova and we support Apache Cordova, it should be possible (for most Cordova plugins).  My suggestion is you build an Apache Cordova project using the docs, then apply what you learn there to your Ionic project. 

The best way to get help for supported platforms (like Apache Cordova) is through our dedicated support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
