### ISSUE TITLE
How to disable "App update available" prompt

### ISSUE THREAD

**Issue by archerfob** [microsoft/appcenter#758]
**What App Center service does this affect?**
Distribute of AppCenterEditorExtensions-v1.1.2.unitypackage on Android

**Describe the bug**
Cannot disable default "App update available" prompt for both mandatory and optional update.

**To Reproduce**
1. Make a build with Distribute.ReleaseAvailable returning true 
2. Upload a build 1 to App Center and distribute
3. Install build 1 on a device by link
4. Upload build 2 to App Center and distribute
5. Launch the app on device
6. Observe and default "App update available" prompt is shown

**Expected behavior**
Default prompt should not be appeared. 

**Screenshots**
https://drive.google.com/file/d/15elK9hRmmafcA5z7Jvbsh7qxKefX9okO/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: Nokia 6
 - OS: Android 7.1

**Comment by jwhiteDev** [comment]
Thanks for reporting this, ill take a look.

**Comment by jwhiteDev** [comment]
@archerfob to confirm, the second build does not have In App Updates enabled, but the prompt shows anyways?

**Comment by archerfob** [comment]
Hi James,

Thanks for the considering the bug. I have reported this on App Center
console and it was addressed reproducible by Surjyo on 25 July. Also Dmitry
said SDK team fixed it and asked me to wait for next release on 30 July.
Could you verify this is valid? Thanks.

Regards,
Archer

**Comment by AnastasiaKubova** [comment]
Hi there! This issue has been fixed.
I'm closing this issue but feel free to open a new issue on the [appcenter-sdk-unity](https://github.com/microsoft/appcenter-sdk-unity) repository if this issue still persists.
