### ISSUE TITLE
UWP app can't see crashes and always show "Coming soon"

### ISSUE THREAD

**Issue by FatJohn** [Microsoft/appcenter#76]
**What App Center service does this affect?**
Diagnostics

**Describe the bug**
UWP original use hockeyapp and then auto-sync into AppCneter. But can't see  any crashes information in Diagnostics function.

**To Reproduce**
N/A

**Expected behavior**
Can view all crashes and the same as those in Hockeyapp

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 65.0.1

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by patniko** [comment]
Hi @FatJohn! This sounds like something our support team can help troubleshoot with you over Intercom in our main portal. Mind opening up a request there so someone from our team can converse directly with you about your issue?

**Comment by FatJohn** [comment]
@patniko OK~ Does Main Portal mean App Center Main Portal ?

**Comment by patniko** [comment]
It does. Someone should be able to look into your account specifically to see whats going on. Going to close this for now, but feel free to reopen it if you have any troubles reaching out to our support team.
