### ISSUE TITLE
Clickable links in comment

### ISSUE THREAD

**Issue by db2222** [microsoft/appcenter#760]
**Describe the solution you'd like**
HockeyApp automatically recognized URLs in comments and made them clickable. Probably simply by scanning for "http://" and "https://".

**Describe alternatives you've considered**
Yes, it's possible to copy and paste manually but it's not as convenient as in HockeyApp and therefore a step back.

I couldn't find any existing tickets for this.

Thanks in advance.

**Comment by nrajpurkar** [comment]
Thanks for this feature request @db2222! Understand the additional convenience of the clickable links. We'll keep this open as a potential future improvement.
