### ISSUE TITLE
Automatically expand comment box

### ISSUE THREAD

**Issue by db2222** [microsoft/appcenter#761]
**Describe the solution you'd like**
HockeyApp automatically adjusted the height of the comment box in the overview so that the saved comment was completely visible straight away.

**Describe alternatives you've considered**
Currently one has to click on the comment to see the comment completely.

I could not any existing tickets for this.

Thanks in advance.

**Comment by lumaxis** [comment]
@db2222 Thanks for the suggestion! Just to clarify, this is for the comment box when you add an annotation to a crash, right?

**Comment by db2222** [comment]
Correct, in the overview of a crash report that has an added annotation.
Furthermore I noticed that the problem does not seem to occur if manual line breaks are added (expands).
So an automatic line wrap would probably be useful.
