### ISSUE TITLE
PowerBI or Export to Excel for analytic data

### ISSUE THREAD

**Issue by ghost** [microsoft/appcenter#762]
**Describe the solution you'd like**
Currently today the reports provided by the analytic events page are extremely limited - it would be nice to export this data to Excel so we can build custom reports or provide a connector to PowerBI so that this information can be displayed in custom dashboards.

**Describe alternatives you've considered**
We currently export the information to App Insights but this is time consuming and requires manual management of the data.

**Additional context**
Export to Excel is flexible as it doesn't require a lot of work from the App Center team to build custom dashboard pages.  PowerBI connector requires licensing for PowerBI, but is the best possible solution to this problem as its dashboards allow us to link information from multiple systems to provide powerful dashboards.

**Comment by yoannchaudet** [comment]
We are taking note.

Out of curiosity, since you currently export your data to Application Insights, have you given a try at there [export to Power BI functionality](https://docs.microsoft.com/en-us/azure/azure-monitor/app/export-power-bi#export-analytics-queries)? This would let you achieve one of your scenario now.

**Comment by myokeeh** [comment]
To chime in on this: I have a solution that export the logs to Azure storage and I pull the files to OneDrive using Microsoft Flow so I can analyze using Power BI.

I'd say the method to get the export to work is very tedious as it requires some interacting with the API to configure. I feel like that part could be simplified more.

**Comment by biozal** [comment]
> We are taking note.
> 
> Out of curiosity, since you currently export your data to Application Insights, have you given a try at there [export to Power BI functionality](https://docs.microsoft.com/en-us/azure/azure-monitor/app/export-power-bi#export-analytics-queries)? This would let you achieve one of your scenario now.

That works for people that can afford App Insight subscriptions, which for my .work projects that works really good. But when you have open source personal projects, I can't afford the PowerBi or App Insight cost.  This is where exporting to Excel is really nice and what almost every system on the planet allows.
