### ISSUE TITLE
How to run Appium C# tests in Microsoft Appcenter

### ISSUE THREAD

**Issue by Yurazato** [microsoft/appcenter#763]
Is it possible to run Appium C# tests in Microsoft Appcenter?

**Comment by Oddj0b** [comment]
Sorry, we don't support Appium C# at this moment, but you can use Xamarin.UITest which works for all app types, don't be frightened by Xamarin.

If you still want Appium C# support show your love here: #102

**Comment by Eduardo-DBC** [comment]
@Oddj0b  I don't know if you've noticed that XamarinUITest doesn't support Google's Flutter technology even using Repl, since the new Appium update has the inspect element for Flutter for java and CSharp.
App center is doing like AWS Device Farm rejecting C# language and same with Appium
