### ISSUE TITLE
App icons uploaded via dashboard not visible in API

### ISSUE THREAD

**Issue by crejer** [microsoft/appcenter#765]
**What App Center service does this affect?**
API.

**Describe the bug**
When adding an App Icon from dashboard to an appcenter App without any builds, the app_icon in the api remains "null".

**To Reproduce**
1. Choose an app
2. Go to settings
3. Edit App Details
4. Pic an Icon for the app
5. click Save
6. call API for app details
7. app_icon field is still null

**Expected behavior**
Url to added app_icon is filled in in app_icon

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: safari, chrome

**Comment by blparr** [comment]
Thanks for your report, we will look into this issue as soon as possible!

**Comment by crejer** [comment]
Hi,

do you have any new information about this issue?

Kind regards.

**Comment by blparr** [comment]
We have a team looking into this - I'll let you know once this is fixed!

**Comment by crejer** [comment]
Ok, thank you 👍

**Comment by blparr** [comment]
This should be totally fixed now. Let us know if you still run into issues. Thanks!
