### ISSUE TITLE
Adding Github app creates new organisation, cannot select existing organisation

### ISSUE THREAD

**Issue by RossWilliams** [microsoft/appcenter#766]
**What App Center service does this affect?**
App Center Github Marketplace
**Describe the bug**
When trying to add the Github marketplace app, after authorising the connection with App Center, I am directed to a page to setup my app. It does not let me select my existing organisation with existing apps and billing setup. A new org is created while I am on this screen, and there is no way to merge these orgs.
**To Reproduce**
Go to github marketplace
Select App Center and install (I am both the github and app center account owner)
Authorise connection to AppCenter
See screen with a new org created and asking to setup a new app.
There is no way to connect into existing org.

**Expected behavior**
I already have apps and billing setup in App Center. I want to use my same org when I setup App Center in the Github marketplace so that it can use my paid account.

**Screenshots**
<img width="567" alt="Screenshot 2019-07-24 at 17 32 18" src="https://user-images.githubusercontent.com/1443442/61811266-0ca4b300-ae39-11e9-832d-85ecb3210591.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MAc
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nrajpurkar** [comment]
Hi @RossWilliams, this is the expected behavior for how the App Center Marketplace app works. You can transfer the app to the correct organization in App Center after it is created. I've marked this as a feature request.

**Comment by RossWilliams** [comment]
And how do you transfer an app? i've been looking around all the pages and menus and can't find this option.

**Comment by nrajpurkar** [comment]
@RossWilliams Check out this [step-by-step](https://docs.microsoft.com/en-us/appcenter/dashboard/creating-and-managing-apps#transferring-an-app) on how to do this!

**Comment by bryandevvv** [comment]
Being able to select WHICH organization in appcenter you are connecting is a really important feature.  I have NO clue how appcenter is selecting an organization when you set up through github marketplace (it seems almost random).  I am in three appcenter organizations, but have no way to select which one I want to use in the screenshot above.

**Comment by King-of-Spades** [comment]
@bryandevvv based on the documentation here: https://docs.microsoft.com/en-us/appcenter/build/github-app#onboarding-repositories-using-the-github-app

It looks like the organization is selected based on the org that owns the repository itself on GitHub.

**Comment by ria-globetrotter** [comment]
still an issue
