### ISSUE TITLE
Multi-Language release notes

### ISSUE THREAD

**Issue by AChevallier** [microsoft/appcenter#77]
**Describe the solution you'd like**
I would like to add multi-language in the release notes when i want to distribute the new version.

**Describe alternatives you've considered**
Using the Google Play Console or App center connect to release the versions.

**Comment by botatoes** [comment]
Can you elaborate a bit more? We currently support different languages in release notes 
<img width="202" alt="image" src="https://user-images.githubusercontent.com/7900087/54728801-32454700-4b3d-11e9-8d75-d025752f626d.png">

**Comment by kiliankoe** [comment]
Not sure if it's what @AChevallier meant, but I'd love support for localized release notes, not using multiple languages in the text field for release notes as I believe you're talking about @botatoes. 

I have an app localized to multiple languages in the App Store, but using App Center to push builds to the store there's only one field I can enter text in. Obviously there's another issue here regarding auto-filling this based on the latest commit message, not sure what the best option would be, but I'd love for it to be on the list 🙈

**Comment by felixpp** [comment]
Yes, we also need this.

**Comment by hydrixos** [comment]
+1

**Comment by dominik-weber** [comment]
@botatoes could you please reopen the ticket? While different languages are of course possible (as you stated above) it is not possible to specify multiple languages at the same time - meaning you'll be unable to publish to production if your app store listing contains multiple languages.

**Comment by ezathashim** [comment]
I would love this. I use Sparkle.framework to push releases through AppCenter and I have never been able to have localized release notes. I think what might work is having a 'target language' menu drop down in the panel view where release notes are typed in. AppCenter would then need to process this properly when creating the Sparkle AppCast. It works this way in the Apple AppStore UI.
