### ISSUE TITLE
React Native - Expo app - Build iOS failed Bash exited with code '1'

### ISSUE THREAD

**Issue by manolobattista93** [microsoft/appcenter#770]
**Describe the bug**
React Native - Expo app - Build iOS failed Bash exited with code '1' on generating script (Generate source map)
[9_Generate source map.txt](https://github.com/microsoft/appcenter/files/3433299/9_Generate.source.map.txt)

I not understand what is index.ios.js, I haven't it on my project, locally on xcode (10.1) it build correctly 

on AppCenter I set node 8.1 and xcode 10.1

==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /Users/vsts/agent/2.154.3/work/_temp/1e732b42-f2d6-4ec8-a06f-56fe8b7d0d9e.sh
Found index.ios.js for ReactNative index.
warning: the transform cache was reset.

The resource `/Users/vsts/agent/2.154.3/work/1/s/index.ios.js` was not found.

Error: The resource `/Users/vsts/agent/2.154.3/work/1/s/index.ios.js` was not found.
    at /Users/vsts/agent/2.154.3/work/1/s/node_modules/metro/src/Server.js:572:58
    at Generator.next (<anonymous>)
    at step (/Users/vsts/agent/2.154.3/work/1/s/node_modules/metro/src/Server.js:11:1077)
    at /Users/vsts/agent/2.154.3/work/1/s/node_modules/metro/src/Server.js:11:1307
    at new Promise (<anonymous>)
    at /Users/vsts/agent/2.154.3/work/1/s/node_modules/metro/src/Server.js:11:988
    at Server._buildGraph (/Users/vsts/agent/2.154.3/work/1/s/node_modules/metro/src/Server.js:572:991)
    at /Users/vsts/agent/2.154.3/work/1/s/node_modules/metro/src/Server.js:570:639
    at Generator.next (<anonymous>)
    at step (/Users/vsts/agent/2.154.3/work/1/s/node_modules/metro/src/Server.js:11:1077)

##[error]Bash exited with code '1'.
##[section]Finishing: Generate source map
##[section]Starting: Xcode build (signed)

**To Reproduce**
"expo": "^32.0.6",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",

React native expo project with standalone apps ios/android (expo eject)

**Comment by DennisPan** [comment]
Unfortunately Expo app isn't currently supported. #189 tracks the feature request.

**Comment by manolobattista93** [comment]
> Unfortunately Expo app isn't currently supported. #189 tracks the feature request.

Do you know why on the same project Android built correctly? is it a ios problem?

**Comment by DennisPan** [comment]
To be honest we haven't looked into the details. Hard to tell just from the build log.

**Comment by manolobattista93** [comment]
@DennisPan I solved creating a index.js file in the main root of the project, the index.js is a simple React component that import the default main react native route App.js

```
import React, {Component} from "react";
import App from "./App";

class Index extends Component {
    render() {
        return (
            <App/>
        );
    }
}

const styles = StyleSheet.create({});

export default Index;
```

This solved the Bash exited
