### ISSUE TITLE
AppCenter Build: Only Target One Branch

### ISSUE THREAD

**Issue by Iron-Ham** [microsoft/appcenter#771]
### **Description**

I want to use AppCenter on a single branch only. However, when I open a pull request pointed at `master`, the AppCenter hook will trigger and mark the check as failed. I don't have a configuration set for master, and I don't intend to run anything pointed at master. 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Make a config for a branch other than master
2. Open a pull request pointed at master. 

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
iOS
2. Which SDK version are you using?
2.0.1

**Comment by nrajpurkar** [comment]
@Iron-Ham are you using the GitHub Marketplace App for App Center or trying to run builds directly in App Center?

**Comment by Iron-Ham** [comment]
We're using the marketplace app

**Comment by nrajpurkar** [comment]
Thanks for clarifying! You'll need to specify a configuration for the master branch if you are opening PRs against it. The PR build runs with the same configuration of the target branch. Please see more details in our [docs](https://docs.microsoft.com/en-us/appcenter/build/github-app#onboarding-repositories-using-the-github-app).

**Comment by Iron-Ham** [comment]
@nrajpurkar I specifically don't want a build to run against master. I want to open PRs against master and for the app center build feedback check to not be included onto the branch.

I _do_ want to trigger deploys on merges to the `beta` branch -- which is currently working.

**Comment by nrajpurkar** [comment]
To clarify, you want to _exclude_ a build running on PRs opened against master? This is not possible at the current time as builds occur on all PRs for apps configured through the GitHub app. If PR builds are not important to you on any branch, I recommend configuring your branch just through the App Center UI which does not currently support PR builds at all.

Feel free to alter the title on this issue to represent the feature request you're looking for or open a new issue for it.

**Comment by Iron-Ham** [comment]
> To clarify, you want to exclude a build running on PRs opened against master?

Exactly! 
I can re-configure the app through the App Center UI. 👍

**Comment by nrajpurkar** [comment]
No problem. You'll need to create a new app in App Center as the old one will retain the connection to the GitHub app and keep triggering PR builds. Closing this out, but feel free to reopen if you need more help!

**Comment by gabrielmoncea** [comment]
Hi @nilofer. Is there no other way to configure build checks? I would also like to keep them only for one branch, while doing release builds for all the branches

**Comment by tien** [comment]
@gabrielmoncea same here, need to disable PR check for our releases branch. Can't feasibly create configuration for all releases branch since we have a lot of them.
