### ISSUE TITLE
Not able to see/click "Next" button in AppCenter - Add the Push SDK to your app

### ISSUE THREAD

**Issue by amrutha786** [microsoft/appcenter#772]
**What App Center service does this affect?**
Add the Push SDK to your app

**Describe the bug**
Not able to see/click "Next" button in AppCenter - Add the Push SDK to your app

**To Reproduce**
1. Go to 'Push' in AppCenter
2. Click on 'Continue with AppCenter'
3. Scroll down to 'bottom of screen' and I am not able to click on the next button

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave Version 10.14.6 (18G84)
 - Browser : Safari 
 - Version : 12.1.2 

**Additional context**
attached screenshot 
<img width="1440" alt="Screen Shot 2019-07-25 at 3 42 37 PM" src="https://user-images.githubusercontent.com/21096553/61913880-64075980-aef3-11e9-855d-da2a94ad0b0d.png">

**Comment by jwargo** [comment]
@amrutha786 Thanks for pointing this out, I’ll get it fixed.

**Comment by kkamperschroer** [comment]
Hi, @amrutha786! Thanks for reporting this. Do you know what your browser zoom level is when you saw this issue? Thanks!

**Comment by amrutha786** [comment]
Hi @kkamperschroer ; I was using Safari on a actual zoom size, i haven't changed the zoom levels

**Comment by jwargo** [comment]
@amrutha786 this was fixed a while back, closing the issue.
