### ISSUE TITLE
ld: library not found for -lappcenter

### ISSUE THREAD

**Issue by hpelitebook745G2** [microsoft/appcenter#773]
**What App Center service does this affect?**
Name of service or sdk with the issue.

**Describe the bug**
I successfully integrated in Android but in iOS, I encountered:
`Apple Mach-O Linker Error`
`Linker command failed with exit code 1 (use -v to see invocation)`
`ld: library not found for -lappcenter`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**To Reproduce**
1. yarn add appcenter appcenter-analytics appcenter-crashes --exact
2. react-native link appcenter
react-native link appcenter-analytics
react-native link appcenter-crashes
3. Added `# Pods for ` in Podfile
4. Ran `pod repo update`
5. Clean Xcode
6. Deleted Xcode DeriveData

**Expected behavior**
Build successfully in iOS

**Screenshots**
<img width="230" alt="Screen Shot 2019-07-26 at 12 23 27 PM" src="https://user-images.githubusercontent.com/27658429/61925757-4217e080-afa0-11e9-9627-651e8f2d305b.png">
<img width="513" alt="Screen Shot 2019-07-26 at 12 23 22 PM" src="https://user-images.githubusercontent.com/27658429/61925760-47752b00-afa0-11e9-82ae-df96c4de32b8.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6

**Additional context**
From the setup guide, I added:

react-native link appcenter
react-native link appcenter-analytics
react-native link appcenter-crashes

but when I ran `react-native link`, it auto-added:
  pod 'AppCenter/Crashes', '~> 2.2.0'
  pod 'AppCenter/Analytics', '~> 2.2.0'
  pod 'AppCenterReactNativeShared', '~> 2.2.0'

**Comment by Jamminroot** [comment]
Hey, @hpelitebook745G2, thanks for getting in touch.
Can you please tell me, which file are you opening in XCode? It looks like you are opening xcodeproj file, is that correct?

**Comment by hamswan** [comment]
@hpelitebook745G2 we have been looking into this.

**Comment by Jamminroot** [comment]
Hi, @hpelitebook745G2, we haven't heard from you for a while, so Im closing the thread. Feel free to reopen if you need our assistance

**Comment by ebeling** [comment]
If I choosed the *.xcodeproj - file to open the project in XCode same error occured. Open the project with *.xcworkspace - file work for me! Thanks @Jamminroot !

**Comment by genesisemmloh** [comment]
but @Jamminroot  , how do i tell appcenter to use the xcworkspace , instead of the xcodeproj ?

**Comment by nibblesnbits** [comment]
+1 at @genesisemmloh.  I have the same problem.

**Comment by nibblesnbits** [comment]
@genesisemmloh, if you check the build log you'll see (at least in my case, app center already uses the .xcworkspace file for a build.
