### ISSUE TITLE
Tests on multiple devices should be independent

### ISSUE THREAD

**Issue by falkospaeh** [microsoft/appcenter#776]
**Describe the solution you'd like**
When running tests on multiple devices and a test crashes on a specific device, it should be possible to view a form of test report. Testing may halt after the crash, but results of prior crash-free runs on other devices should be reported. It would also be good to know on which device the tests crashed. 

**Describe alternatives you've considered**
At least device logs should be accessible.

**Additional context**
I test a library which depends on the implementation of the graphics driver and the behavior varies between devices. That in case of crash reports are not published for any device, forces me to test only on small sets of devices. This minimizes the risk of loosing minutes and information.

**Comment by Oddj0b** [comment]
That's good feedback, thanks for suggesting it.

**Comment by falkospaeh** [comment]
Is there any chance of someone looking at possible realizations of this feature soon?

**Comment by Oddj0b** [comment]
@falkospaeh  We are building test reports as the devices finish their run whether the failed or passed doesn't matter. But it sounds like you're not seeing that at all. Is that correct or am I misunderstanding you?
