### ISSUE TITLE
Exclude/filter Simulator in Analytics

### ISSUE THREAD

**Issue by rnystrom** [microsoft/appcenter#777]
**Describe the solution you'd like**
Active users and daily session reports should not include simulators, or at the very least we should be able to filter out simulators.

**Describe alternatives you've considered**
We're exploring using other analytics libraries since it doesn't seem like we can filter or export App Center analytics?

**Additional context**
<img width="460" alt="Screen Shot 2019-07-26 at 3 23 33 PM" src="https://user-images.githubusercontent.com/739696/61976416-bca12a00-afb9-11e9-871c-270541e6877b.png">

Our app is unreleased, so including simulators is really confusing.

**Comment by amchew** [comment]
Thanks @rnystrom for your request! @hamswan, could you please take a look?

**Comment by hamswan** [comment]
Thanks @rnystrom we will add this as a feature request.

**Comment by alexcnichols** [comment]
I'd agree. Things like including simulator and emulator numbers can really cloud up the Analytics reports. Having a way to filter those out (probably by default) would be nice. 

I see #805 in a similar way since Build launch tests and Test runs have a similar consequence.
