### ISSUE TITLE
Ability to brand/customize distribution screens.

### ISSUE THREAD

**Issue by dexter31** [microsoft/appcenter#778]
Ability to customize pages such as install.appcenter.ms/orgs/my-org so organization users are confident of app downloaded

No alternatives considered.

Branding and customization

**Comment by nrajpurkar** [comment]
Thanks for this feature request! Definitely understand how this could be helpful when distributing your apps. Any thoughts on the items you'd like to see customized? Logo, colors, etc?

**Comment by dexter31** [comment]
I'm not an expert on UX, but going through similar pains in the past -

- Logo 
- Primary and Secondary color
- Font family

**Comment by fmavdb** [comment]
This would definitely help us as well! The ability to customize the branding of our application distribution page would help too.
