### ISSUE TITLE
Junit test case report not available.

### ISSUE THREAD

**Issue by prashantrane123** [microsoft/appcenter#779]
**Describe the solution you'd like**
Currently, when we turn on, Run Junit test case switch on the build configuration. While the build is in progress user can only see that Junit test cases ran. But there is no details about how many test cases ran, how many succeeded/failed, what is code coverage etc.

**Comment by nrajpurkar** [comment]
That's for this feature request @prashantrane123! We'll keep this open and track interest.

**Comment by pchmielowski** [comment]
Do I understand correctly, that currently, if my build fails with the message:
```
* What went wrong:
Execution failed for task ':app:testQaReleaseUnitTest'.
> There were failing tests. See the report at: file:///Users/runner/runners/2.160.0/work/1/s/app/build/reports/tests/testQaReleaseUnitTest/index.html
```
there is no way to get this `index.html` file and therefore spot the issue?

**Comment by prashantrane123** [comment]
> track interest.

Sorry, but I did not get the meaning of track interest?
