### ISSUE TITLE
More details in “New Crash Group” email

### ISSUE THREAD

**Issue by florianbuerger** [microsoft/appcenter#780]
It would be great if the email contains some additional information, for example at least the track trace where the crash occurred or how many users are affected.

![Screen Shot 2019-07-29 at 11 58 24 AM](https://user-images.githubusercontent.com/119219/62039781-9ddca680-b1f8-11e9-905b-972328ab5804.png)

**Comment by winnieli1208** [comment]
Hi @florianbuerger - thanks for feature request! We have plans to improve our e-mail notifications for crashes in the upcoming months (Related to #715 #198 ). I don't have an exact target date but I will keep you posted. 

In the meantime, you can check out the mockups we're working on: https://devdiv.invisionapp.com/share/EMOEZRX5CS4#/screens/323824547

Feel free to share any thoughts of feedback. Thanks!
