### ISSUE TITLE
_CompileToDalvikWithDx "java" exited with code 2

### ISSUE THREAD

**Issue by NVentimiglia** [microsoft/appcenter#781]
**What App Center service does this affect?**
Build

**Describe the bug**
When building on Android I receive the following error :

> 
> "/Users/vsts/agent/2.154.3/work/1/s/Client/***.Android/***.Android.csproj" (PackageForAndroid target) (1) ->
> (_CompileToDalvikWithDx target) -> 
>   /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2721,3): error MSB6006: "java" exited with code 2. [/Users/vsts/agent/2.154.3/work/1/s/Client/***.Android/***.Android.csproj]

This issue is AppCenter only and does not replicate on my local machine.

**To Reproduce**
Create an Android project targeting monodroid9.

**Comment by King-of-Spades** [comment]
Might be this issue: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/troubleshooting/questions/maps-compiletodalvik-error

**Comment by NVentimiglia** [comment]
Heap size is 2G. Again, not an issue on local machines, only in AppCenter. Maybe related to recent SDK  updates? Maybe the build server needs new packages?

**Comment by nrajpurkar** [comment]
@NVentimiglia can you reach out directly to App Center Support so we can dig into the issue there please? Thanks!

**Comment by BenCamps** [comment]
I seem to be having a similar issue. 
My app center build fails with the following error message but runs fine locally.

> "/Users/vsts/agent/2.155.1/work/1/s/source/FScruiser.Droid/FScruiser.Droid.csproj" (PackageForAndroid target) (1) ->
(_CompileToDalvikWithDx target) -> 
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2521,3): error MSB6006: "java" exited with code 2. [/Users/vsts/agent/2.155.1/work/1/s/source/FScruiser.Droid/FScruiser.Droid.csproj]

For the _CompileToDalvikWithDx target, I get the following output in my build log

> _CompileToDalvikWithDx:
  Creating directory "obj/Release/proguard".
  /usr/bin/java -Xmx1G -jar /Users/vsts/Library/Android/sdk/build-tools/27.0.3/lib/dx.jar --dex --no-strict --output obj/Release/android/bin /Users/vsts/agent/2.155.1/work/1/s/source/FScruiser.Droid/obj/Release/android/bin/classes.zip ... rest of line truncated
  
>   trouble writing output: Too many field references to fit in one dex file: 66866; max is 65536.
>   You may try using multi-dex. If multi-dex is enabled then the list of classes for the main dex list is too large.
>   References by package:
>       29 android.app
>     3066 android.arch.core
>        8 android.arch.core.executor
>       14 android.arch.core.internal
>     3161 android.arch.lifecycle
>     3066 android.arch.lifecycle.livedata
>     3066 android.arch.lifecycle.livedata.core
>     3066 android.arch.lifecycle.viewmodel
>       34 android.content.pm
>       10 android.content.res
>       55 android.graphics
>  ::: rest of log entry truncated :::

When I use [ClassyShark](https://github.com/google/android-classyshark) to analize my localy built apk I get the following method counts from my local built apk. [https://i.imgur.com/Nfm1zWD.png](https://i.imgur.com/Nfm1zWD.png)

**Comment by King-of-Spades** [comment]
@BenCamps If you go to "Project options > Build > Android Build" in VS4Mac, you should see an option "Enable multi-dex" you can activate, which is what the error message "You may try using multi-dex" is referring to. Can you give that a try?

Come to think of it, I think I do remember encountering some issues where multidex only triggered failures when running in the Build VMs but not locally, but I don't remember the exact error message. It's only the later part of the error message that really highlights that...

@NVentimiglia Might be worth taking a quick check with that as well. 

I also have a sample I maintain here that uses multi-dex: https://github.com/King-of-Spades/AppCenter-Samples/tree/master/Xamarin.UITest/UITestDemo

**Comment by NVentimiglia** [comment]
Was able to resolve the issue. Problem was on my end. The solution was to upgrade the targeting in the environment-specific AndroidManifest
