### ISSUE TITLE
Xamarin UITest REPL doesn't work anymore

### ISSUE THREAD

**Issue by akamud** [microsoft/appcenter#782]
**What App Center service does this affect?**
Xamarin UITest REPL

**Describe the bug**
Running App.Repl() opens the console with an exception

**To Reproduce**
1. Just run App.Repl() with Xamarin UITest. Tried on Android and iOS with same results.

**Screenshots**
![image](https://user-images.githubusercontent.com/954102/62054540-2d318c00-b1f0-11e9-80a6-6f9181cdd54b.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Xamarin UITest 3.0.1
- XCode 10.2

**Additional context**
There is no extra information available, AFAIK, it just throws this exception that doesn't help me at all.

I tried calling the repl manually and got the same error.

```bash
mono /private/var/folders/q8/s_v05xsx5_x3ryh2cb4b840c0000gq/T/uitest/repl/xut-repl.exe android "/Users/mahmoud/.nuget/packages/xamarin.uitest/3.0.1/lib/net45/Xamarin.UITest.dll" "http://127.0.0.1:56958/" "emulator-5554" "/Users/mahmoud/Library/Developer/Xamarin/android-sdk-macosx"
```

**Comment by jmoody** [comment]
Hello.  There is a new dev release that fixes this problem.  

https://www.nuget.org/packages/Xamarin.UITest/3.0.2-dev2

**Comment by King-of-Spades** [comment]
Xamarin.UITest 3.0.2 has now been released as a stable release; so I believe the fix for this issue should now itself be in the stable channel.

**Comment by nhussain16** [comment]
For me I fix this issue by providing the permanent environment variable. I did not had Bash profile so I created file and create following environment variable
![image](https://user-images.githubusercontent.com/66728414/101983211-6dde5800-3cb4-11eb-8ad3-35acff913300.png)

**Comment by King-of-Spades** [comment]
@nhussain16 Given this bug was fixed over a year ago, if similar symptoms are occurring, it's probably a separate issue unless you're running an extremely outdated version of Xamarin.UITest. The steps that work for you I don't think should normally be required to be handled manually.
