### ISSUE TITLE
Outlook App dogfood

### ISSUE THREAD

**Issue by Lorenzog0917** [microsoft/appcenter#783]
**What App Center service does this affect?**
Outlook App for Android

**Describe the bug**
After the latest update, the app will not start.  the app hangs, causes my phone to lock up and then crashes.

**To Reproduce**
1. Go to Outlook app
2. Click on Outlook app
3. Nothing happens. Hangs and causes phone to hang

**Expected behavior**
Launch the app and have my email and calendar available

**Screenshots**
No screenshots.  

**Desktop (please complete the following information):**
 
**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 9

**Additional context**
None

**Comment by lumaxis** [comment]
Thanks for reaching out @Lorenzog0917. However, HockeyApp and App Center are only the distribution mechanism for the app, please reach out to the Outlook team directly for any issues with their app itself.

Just as an idea, have you tried completely uninstalling and reinstalling the app?
