### ISSUE TITLE
Add consolidated list of uploaded releases which can be distributed from

### ISSUE THREAD

**Issue by dsditt** [microsoft/appcenter#784]
**Describe the solution you'd like**
I'd like to be able to get to a list of all uploaded releases, so I can select which build to distribute when a feature is done. Currently, after uploading a build you get a json response containing a url to manage the release of the build you just submitted. I don't want to track and manage these urls. Just give me a list, easily accessible from the dash, of all uploaded builds so I can select which build to distribute once a feature has been completed. 

**Describe alternatives you've considered**
Hockeyapp (the service I used before it was acquired by MS) does this. TeamCity does this. Buddybuild does this. Every distribution platform I've ever used does this.

**Comment by botatoes** [comment]
Hi, can you explain your scenario a little more? You should be able to access a list of all the releases in the main portal.
