### ISSUE TITLE
Add new app build repo connection via AppCenter Github App instead of Github webhook.

### ISSUE THREAD

**Issue by zarko-via** [microsoft/appcenter#786]
**Describe the solution you'd like**
As of now, adding a new app via App Center and connecting a build to a specific Github repository creates only a webhook instead of connecting it via the installed AppCenter GitHub App (connected to the organisation).
This results in general repository slowness using git when multiple App Center apps are connected to the same repository (due to many webhooks). Also Github repositories are bound to only 20 webhooks, not allowing scale of more connections to apps.

**Describe alternatives you've considered**
We are currently using a GitHub dance of adding the same repo, saving and then using the save link to add a new App Center app via Github so the app build will be connected via the Github Marketplace app and not via a Github webhook. 

**Additional context**
We are concerned this dance is not safe or will break in the future and seek for a solid solution that will use the GitHub app connection only and not a webhook.
Worth nothing current workaround can only be done by a Github admin and not by lower permission users.

**Comment by DennisPan** [comment]
>We are currently using a GitHub dance of adding the same repo, saving and then using the save link to add a new App Center app via Github

>Worth nothing current workaround can only be done by a Github admin and not by lower permission users.

@zarko-via do you mind help me understand more about this? What steps are taken when you onboard a new App Center app and connect with GitHub marketplace app?

**Comment by jarrrgh** [comment]
I've been also struggling with this. Finally I was able to connect an app with the following dance steps:

1. Uninstall App Center app in GitHub
2. Find App Center app in Marketplace and select "grant this app access"
3. Select repository, and use the wizard to create a new app based on the repository

Funny thing to note is, that you could choose multiple operating systems (for example Android and iOS), which is not possible while creating an app via the dashboard.

Now that I have my **alpha** Android app connected to my repository, I'm wondering how would it be possible to build a **beta** Android from the same repository...

**Comment by DennisPan** [comment]
>you could choose multiple operating systems (for example Android and iOS), which is not possible while creating an app via the dashboard.

**Comment by jarrrgh** [comment]
> This is a bit tricky. We've been meaning to improve this flow, but haven't been able to. If you go to GitHub, find your account setting or organization setting, you should be able to find the installed App Center app, and edit the repository list granted access. Each time you edit the list, it triggers the flow, during which you can create new apps with same repository again

Ah, awesome! This works - just not too obvious 😄Thanks for the tip!

**Comment by zarko-via** [comment]
You shall not close bot!
