### ISSUE TITLE
cordova-plugin-appcenter-shared/AppCenterShared.m already exists!

### ISSUE THREAD

**Issue by alexcroox** [microsoft/appcenter#787]
Cordova

```
cordova plugin add cordova-plugin-appcenter-analytics   
Installing "cordova-plugin-appcenter-analytics" for android
Installing "cordova-plugin-appcenter-shared" for android
Subproject Path: CordovaLib
Subproject Path: app
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-appcenter-analytics" for browser
Plugin dependency "cordova-plugin-appcenter-shared@0.3.6" already fetched, using that version.
Installing "cordova-plugin-appcenter-shared" for browser
Installing "cordova-plugin-appcenter-analytics" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.3.6" already fetched, using that version.
Installing "cordova-plugin-appcenter-shared" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-appcenter-shared': CordovaError: Uh oh!
"/Users/alex/Projects/hectare-src/app/src-cordova/platforms/ios/****/Plugins/cordova-plugin-appcenter-shared/AppCenterShared.m" already exists!
```

Tried re-installing after removing after I installed cocopods.

**Comment by alexcroox** [comment]
This looks like a duplicate of https://github.com/microsoft/appcenter-sdk-cordova/issues/83

**Comment by alexcroox** [comment]
Resolved by deleting my entire src-cordova and starting again 🤷‍♂️

**Comment by SimonGolms** [comment]
I just run into this bug too with my ionic project after updating to MacOS Catalina.
I was able to solve the issue following these steps:

1. Install/Update/Start Xcode and install/agree the open pending changes/license
2. Install/Update Cocoapods: `$ sudo gem install cocoapods`
3. Remove and recreate dependencies and generated files: `$ ionic repair`
4. (Optional) Delete the folders `platforms` and `plugin` and start the build process with `ionic cordova build ios`

**Comment by mgatto** [comment]
Same frustrating error for me. Ticket is closed...but not solved. So...how can we update our AppCenter plugins?

**Comment by epetre** [comment]
Why is this closed? It sounds like a pretty major bug to not be able to install the plugin normally.
Why would the solution be to repair anything or reinstall the platform and plugins?

**Comment by luce78** [comment]
Same for me. I use CI/CD and it is failing every time it tries to add the platform although it just adds the plugins for the first time. I use the crashes and the analytics plugin.

**Comment by SebasWebDev** [comment]
What worked for me was adding packages cordova-ios@5.0.0 and cordova-common. The latter is to avoid another potential issue related to modules not found.
