### ISSUE TITLE
Add support for deleting Crash Groups, at least using API

### ISSUE THREAD

**Issue by shpakovski** [microsoft/appcenter#788]
**Describe the solution you'd like**

At the moment, for any Diagnostics / Issues selection, we have only “Mark as…” commands.

<img width="205" alt="image" src="https://user-images.githubusercontent.com/163410/62115690-80bfda80-b2c1-11e9-8599-4d3ed5cf9e28.png">

What is missed however, is an option to delete the Crash Group. Most of our builds are internal and intended only for QA. Once we’re sure that the problem is fixed, we’d like to completely erase any stack traces and associated reports, which is impossible at the moment.

**Describe alternatives you've considered**

In order to delete inner reports, we are using an API request like `
curl -X DELETE "https://api.appcenter.ms/v0.1/apps/user.name/app.name/errors/errorGroups/1234567u/errors/123456789-3456-4567-567-4567-546789" -H "accept: application/json" -H "X-API-Token: zxcvbnmlkjhgfdsawertyuio"`. However, the “parent” crash group remains in the App Center, and there’s no REST command to delete it.

**Additional context**

Deleting API crashes from the command-line is so, so, so inconvenient. Please consider to add this feature to the web portal, maybe as a button “Delete…” next to the “Mark as…”.

**Comment by LAguido** [comment]
Would like this as well! With Hockey this was a very nice feature for internal QA.

**Comment by fheidenreich** [comment]
Just ran into this while trying to delete an error group of an error that only appeared in QA. 

Deleting the individual errors via the API was possible w/o problems, but the error group remains — which seems kind of odd.

**Comment by Nickjgniklu** [comment]
I would like this also!
