### ISSUE TITLE
My Android app is crashing and AppCenter gives no details

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#789]
Hi,

I am testing my app on Debug mode and it's working perfectly and then when I install the apk (from Release mode) to my device then the app crashes immediately.

I am getting no crash log in AppCenter

This is the log I get from Android Device Monitor

Thanks,
[Jassim](https://www.jassimrahma.net)

[log.txt](https://github.com/microsoft/appcenter/files/3448225/log.txt)

**Comment by JakubOleksy** [comment]
Is this still an issue?

**Comment by jrahma** [comment]
Problem is resolved

Thank you

**Comment by eddyoc** [comment]
What was the resolution? It would be good to capture this for others experiencing the same problem.
