### ISSUE TITLE
Cannot access several apps in AppCenter Dashboard

### ISSUE THREAD

**Issue by hypherion2** [microsoft/appcenter#790]
**What App Center service does this affect?**
AppCenter Dashboard/HockeyApp Syncronization

**Describe the bug**
I have 9 apps configured in HockeyApp, and while I have not yet migrated them to AppCenter, I can view their data including crashes, releases etc in the dashboard. This seems to work EXCEPT for 4 of them. They are shown in the list same as the other apps, but clicking them only brings up a "Configure app" popup with basic information like Name, OS and a disabled "Configure" button. They are a mix of Windows and Mac apps and I can't find anything strange in either HockeyApp or AppCenter that would cause only these 4 to show up like this.

**To Reproduce**
1. Go to All Apps in Dashboard
2. Click on one of the 4 apps
3. See "Configure App" view opens up, with a disabled configure button.

**Expected behavior**
For other apps, clicking them brings me to an Overview page with all of their data.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 75

**Additional context**
As I'm planning switching from HockeyApp to AppCenter for these apps, I'd like to make sure that they will be migrated properly once I integrate the new SDK. Currently I cannot even view their app secret - I understand it's same as the HockeyApp except in a different format but I should be able to see it in the dashboard myself.

**Comment by lumaxis** [comment]
@hypherion2 The "Configure app" popup is actually scrollable and you need to select a "Platform" there too, then the button should become enabled 🙂

@blparr Some design/discoverability feedback!
