### ISSUE TITLE
Upload APIs stopped working

### ISSUE THREAD

**Issue by davidhartley** [microsoft/appcenter#791]
**What App Center service does this affect?**
The app center upload APIs described in the 4-step process in this doc:
https://docs.microsoft.com/en-us/appcenter/distribution/uploading

**Describe the bug**
The upload appears to succeed based on the API response but no new build appears in either App Center or HockeyApp.

**To Reproduce**
Upload a new build (reproduced with a new APK) via the 4-step API process described in the doc above.

**Expected behavior**
A new build should appear in the Releases list for that app in App Center.

**Additional context**
This was working yesterday. Last success as a little before 5:00PM EST July 29th.

**Comment by Stephanie-Dover** [comment]
Hi David,

Please reach out to appcenter support by following the steps in the doc: https://intercom.help/appcenter/en/articles/1698824-getting-help-with-app-center

We will be able to provide better support through that outlet by getting more information that can help us troubleshoot this issue.

**Comment by davidhartley** [comment]
I did submit a support request which I am waiting on but I'll add some more context here. The final step detailed here is returning an undefined distribution ID error:
https://docs.microsoft.com/en-us/appcenter/distribution/uploading

The error is "Distribution Group with id undefined does not exist."

The doc above doesn't have anything about a distribution group. I am currently submitting to the API with a destination_name of Public. It seems like something in the releases_update changed without the doc updated to reflect it:
https://openapi.appcenter.ms/#/distribute/releases_update

**Comment by Kumi4u** [comment]
Hello david,
I am currently facing similar issue. The uploading was working nicely from the script I wrote and I could see the builds on the Appcenter. However next morning it stopped working and I am getting following error in the console

`{"code":"no_upload_resource","message":"upload_id is not recognized. An Upload resource should be created first."}`

Was your problem fixed and can you shed some light on what might be the issue I am facing

**Comment by martinarvaiaccedo** [comment]
Hi, @Kumi4u did you solve the issue you mentioned above? I'm facing the same...

**Comment by stijnvdb88** [comment]
For people using PHP to call the api: there is an issue in PHP 7.4.2 which can cause this error if you use curl:

https://bugs.php.net/bug.php?id=79013
https://bugs.php.net/bug.php?id=79289

I downgraded for now, but looks like it'll be fixed in 7.4.4
