### ISSUE TITLE
Free Tier for App Center Auth

### ISSUE THREAD

**Issue by amchew** [microsoft/appcenter#794]
Throughout our various customer and market research, we’ve realized that we’re lacking in one core functionality that developers have asked for and other products in the MBaaS space provide: the ability to onboard onto the App Center MBaaS services and try them out for free. 

To that end, we'll spend the month of Aug speaking with developers to learn about your needs for a free tier for Auth. 

With the Auth free tier, developers will be able to:
1. set up an Azure AD B2C tenant, 
2. configure their identity providers (i.e. email/password, Facebook, Google, MSA)
3. search from the list of authenticated users
4. edit their sign-in user flow 

seamlessly, without an Azure subscription and directly in App Center Auth.

**We're actively looking for developers to speak with and help us shape our product** - whether you work for an enterprise, a startup or are an indie developer. Please leave a comment below if you'd like to collaborate together! 

Work in progress designs:

![image](https://user-images.githubusercontent.com/33160470/62172174-43217880-b2e6-11e9-9814-6e8f437e930a.png)

![image](https://user-images.githubusercontent.com/33160470/62172202-5cc2c000-b2e6-11e9-80e7-b9982b67a913.png)

![image](https://user-images.githubusercontent.com/33160470/62172235-73691700-b2e6-11e9-873e-25bb7359087e.png)

**Comment by SOliasS** [comment]
Hey,
I work for a startup and we are in the process of integrating Authentication and Datasync in out Xamarin App.
This looks very promesing to us so we would love to collaborate with you.

**Comment by amchew** [comment]
Hi @SOliasS, good to hear from you! Would you mind emailing me at amchew [at] microsoft [dot] com? Would love to set up some time with you to learn about your scenarios. Thanks!

**Comment by Zakeelm** [comment]
We announced this week in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Auth and Data services later this year and recommending customers transition to Azure Active Directory B2C and Azure Cosmos DB instead. Let me know if you have any additional questions about this transition and i'll make sure to get them answered! Closing this issue.
