### ISSUE TITLE
Finer granularity Analytics and Issues 'Time' filter

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#795]
Hi,

In Analytics Time Filter, Please add:

Today

Thanks,
[Jassim](https://www.softnames.com)

**Comment by amchew** [comment]
Thanks @jrahma for your request! @hamswan, could you please take a look?

**Comment by King-of-Spades** [comment]
Merging https://github.com/MicrosoftDocs/appcenter-docs/issues/966 into this one; which also requests a time filter of 1 day, as well as 1 hour.
