### ISSUE TITLE
Support for building Xamarin iOS apps with Xcode 11 beta

### ISSUE THREAD

**Issue by sgreifeneder** [microsoft/appcenter#796]
**Describe the solution you'd like**
Building iOS apps with Xcode 11 beta needs to be enabled for Xamarin projects as well. Currently only native iOS projects are supported. 

**Describe alternatives you've considered**
Changing the CI, but I don't want to do that now. 

**Additional context**

**Comment by nrajpurkar** [comment]
@sgreifeneder thanks for this request. We're working on adding support for Xamarin toolsets that came with VS for Mac 8.2 at the moment. This version has preview support for Xcode 11.

**Comment by jamesmontemagno** [comment]
Checkout Boots from @jonathanpeppers  https://github.com/jonathanpeppers/boots he has App Center scripts you can add :)

**Comment by jonathanpeppers** [comment]
boots can install any pkg (macOS) or vsix (Windows) file. So it can install Mono, Xamarin, etc. just not Xcode itself.

Unfortunately apple doesn’t have public URLs for Xcode, if that ever existed would be great.

**Comment by jamesmontemagno** [comment]
Ahhh good call! Thanks Peppers <3

**Comment by nrajpurkar** [comment]
We continued to roll out betas and are supporting the GA release. Closing this out!
