### ISSUE TITLE
Mono.framework Versions 5_12_0

### ISSUE THREAD

**Issue by suleman-jalil-devbox** [microsoft/appcenter#797]
[logs_72.zip](https://github.com/microsoft/appcenter/files/3451906/logs_72.zip)
**What App Center service does this affect?**
Name of service or sdk with the issue.
java" exited with code 2
**Describe the bug**
-> Issue arise when building a branch for creation of APK for android.
-> We are using Android version 9.0, Multi-Dex is enabled, Java Max Heap Size is 1G.
-> Support Architecture are armeabi, armeabi-v7a, x86, x86_64, arm64-v8a
-> We are using Xamarin.
**To Reproduce**
1. Go to 'https://appcenter.ms/orgs/Sweet-Spot-LLC/apps/Sweet-Spot-Parking-1/build/branches/OPEXA-005'
2. Click on 'Build now'
(_CompileToDalvikWithDx target) -> 
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2521,3): error MSB6006: "java" exited with code 2. [/Users/vsts/agent/2.154.3/work/1/s/ParkAhead.Droid/ParkAhead.Droid.csproj]

    7 Warning(s)
    1 Error(s)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16875661/62213863-594e3800-b3bd-11e9-8986-c6174c0a85f1.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nrajpurkar** [comment]
@suleman-jalil-devbox can you please reach out to App Center support with this issue so we can better help troubleshoot the issue? Thanks!

**Comment by suleman-jalil-devbox** [comment]
> App Center support

oks. Thank you
