### ISSUE TITLE
Display billing history for services

### ISSUE THREAD

**Issue by Zakeelm** [microsoft/appcenter#8]
Enable users to easily see what their monthly usage was for billed services along with relevant billing metrics such as start date, end date, remaining hours, total hours, concurrent devices, etc.

**Comment by jwhiteDev** [comment]
This work has been postponed and will be picked up either in March or April when some bandwidth allows.

**Comment by lachlanwp** [comment]
It would also be great if I could see exact dates for the billing cycle (e.g. February 24th 2020 - March 23rd 2020 in each of the headings in the mock up).
