### ISSUE TITLE
Migrating app releases and the puck command line tool from HockeyApp

### ISSUE THREAD

**Issue by 0xced** [Microsoft/appcenter#80]
The [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) about migrating from HockeyApp is currently quite vague:
> :runner: Continue to improve support for the current HockeyApp user scenarios
> :runner: Create a migration path into App Center for current HockeyApp users

I'd like to know if building iOS apps outside of the App Center then uploading the ipa + dSYM files will be a supported scenario. I am currently uploading ipa and dSYM files with the `puck` command line tool and then I’m able to see all releases that I uploaded on rink.hockeyapp.net with associated ipa + dSYM + embedded provisioning profile (also with the date of when the provisioning profile expires).

Currently on App Center, I see no releases at all. I also tried the API https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/releases?published_only=false but it returned an empty array `[]`. Is this going to be a supported scenario?

**Comment by patniko** [comment]
You can use our App Center CLI to upload an ipa with symbols from your local system automatically by using the distribute command. If you don't want to send it to actual testers just create a distribution group with no testers in it or send it to the app collaborators.

We have talked about adding an additional command to just upload a release for crash processing. Will keep this open so @derpixeldan can track the feature request.

**Comment by 0xced** [comment]
Thanks, so I tried to use the [appcenter cli](https://github.com/Microsoft/appcenter-cli) to list the releases of an existing application (`appcenter login; appcenter apps set-current owner_name/app_name; appcenter distribute releases list`) and as expected, there was no error and no output at all, matching my experience of using the [API](https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/releases?published_only=false).

So, are you going to migrate existing HockeyApp releases or will only the releases created through App Center be available in App Center? If existing apps will be migrated, is there an estimated time of arrival?

**Comment by derpixeldan** [comment]
@0xced there seems to be an issue with your app on App Center, can you please reach out via the blue chat button at the bottom right and refer to this conversation? We'll look into it more closely then.

**Comment by patniko** [comment]
Was our support team able to help you out with the issue with your releases @0xced ?

**Comment by 0xced** [comment]
I haven't asked the support team yet. I will try soon.

**Comment by derpixeldan** [comment]
@0xced have you asked support and was the issue resolved?

**Comment by derpixeldan** [comment]
We've updated the [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap).

**Comment by 0xced** [comment]
For reference, here's how I replaced my `puck` command with `appcenter` commands
```bash
export APPCENTER_ACCESS_TOKEN = redacted
appcenter distribute release --group Collaborators --app "my/appname" --file "path/to/MyApp.ipa"
appcenter crashes upload-symbols --app "my/appname" --symbol "path/to/MyApp.app.dSYM.zip"
```
