### ISSUE TITLE
Support for on-premises repositories, like TFS/TFVS. 

### ISSUE THREAD

**Issue by lxshertz** [microsoft/appcenter#801]
**Describe the solution you'd like**
We currently use Azure DevOps Server for version control and would like to use App Center build and test module to build and test our Xamarin.iOS and Xamarin.Android Apps.

**Describe alternatives you've considered**
None at the moment.

**Additional context**

**Comment by nrajpurkar** [comment]
Thanks for this feature request @lxshertz! We'll keep this open to track interest for the future.

**Comment by tonykchan** [comment]
How can this still be an outstanding issue with App Center?  I just migrated a couple of my hockeyapp mobile apps over to App Center, and I'm no longer able to access my source controlled files in Azure DevOps (TFVC repo)???  If we are being forced off HockeyApp, shouldn't the functionality of the latest option be the same or better?

**Comment by nrajpurkar** [comment]
Hi @tonykchan, what specific functionalilty are you looking for that is available in HockeyApp related to this? This feature request is around the Build/CI service which isn't available in HockeyApp and is an additional service in App Center.

**Comment by farlop** [comment]
I think that what we need here is to be able to connect an App Center app to a 'Azure DevOps Server' (on-premises) repository. At this moment only 'Azure DevOps' (cloud) is allowed.

Is there any update on this?

**Comment by nrajpurkar** [comment]
@farlop, no update on this at the moment. We're continuing to track interest in this feature request.

**Comment by msallmen** [comment]
@nrajpurkar  We are currently using Hockey App, but there is no path forward with App Center with our on-prem TFS.

**Comment by nrajpurkar** [comment]
@msallmen can you be specific about what scenarios you are blocked on coming from HockeyApp? This issue refers to Build support requiring on-premises repo support, but HockeyApp didn't have a build service. Thanks!

**Comment by nbelley** [comment]
This feature should be a minimum. We are using TFS locally here and we can't use AppCenter to distribute our apps because of this.

**Comment by farlop** [comment]
What we ended up doing is building locally in Azure DevOps Server and then push the resulting apk to App Center

**Comment by Going-Gone** [comment]
Very odd that tfs isn't supported. This would be very beneficial.

**Comment by Big-al** [comment]
Agreed, we need on premise support for app center.

**Comment by williamvasconcelos** [comment]
@nilofer any news on this request??? even gitlab(self-hosted) has support for app center.

**Comment by nilofer** [comment]
I no longer work on App Center. Tagging in @elamalani to provide further answers.
