### ISSUE TITLE
"Build this branch on every push" option does not work

### ISSUE THREAD

**Issue by ekimlinger** [microsoft/appcenter#802]
**What App Center service does this affect?**
Build 

**Describe the bug**
Although the option is selected for "Build this branch on every push" we are still having to manually press the button every time that we want to create a build. There are some times where it does automatically do this, however it is rare/inconsistent. Screenshot is proof that we have not had an automatic build for our last PR, however it should have been automatically triggered.

**To Reproduce**
1. Set up a branch under the Build tab
1. Make sure to check the box for "Build this branch on every push" on the branch options
1. Create a pull request in Azure Dev Ops with some changes
1. Complete the pull request
1. See that the commit shows up in AppCenter, but there is no build that is triggered.

**Expected behavior**
I would expect that every time there is a PR made into Azure Dev Ops, which we have connected to AppCenter, that it creates a new build for our Development branch.

**Screenshots**

**Desktop:**
- Mac OS Mojave version 10.14.3

**Smartphone:**
- Android & iOS deployments

**Comment by ekimlinger** [comment]
Wow. Github is not letting me upload a 55k PNG file right now... will try again later.
Basically it shows that the last build happened 3 weeks ago even though we had a completed PR a few hours ago.

**Comment by DennisPan** [comment]
Hey @ekimlinger this definitely sounds like a bug. Do you mind reaching out to support via App Center portal? We will need additional details to dig deeper.

**Comment by ekimlinger** [comment]
Will do.

**Comment by jason-system1** [comment]
@DennisPan I'm experiencing the same issue, though this has only stopped working for me today, but was fine yesterday and I've been using "on push" for builds for many weeks successfully and very consistently.

How do I reach out to support via the App Center portal? I've had a quick look, but nothing is jumping out at me? I'd thought it'd be under the "?" on the top right hand corner of the portal, but nope.

**Comment by jason-system1** [comment]
Surprise, surprise, this is now working. Triggering "on push" builds much later after the fact isn't ideal, as I've wasted plenty of time trying to "fix" it and diagnose it for sharing here and I could have been doing something useful.

Anyway, when something doesn't work in App Center, my advise to you is like when you feel under the weather, if it's still dodgy after a few days, then see your doctor.

**Comment by DennisPan** [comment]
@jason-system1 I'd like to take a look at your repository's webhook request history for better understanding of what happened. Could you check if you see the blue chat bubble at bottom right of portal? That's how you can reach out to support. You can ask support to assign the conversation directly to me.

![image](https://user-images.githubusercontent.com/14064342/63531366-3810d100-c4bd-11e9-93b0-dd2cf97ddc9f.png)

**Comment by jason-system1** [comment]
> @ekimlinger @jason-system1 are you still experiencing this issue? Similar issue just came in #948

@nrajpurkar As you can imagine from my response above, no, no I'm not experiencing this behaviour anymore.

@DennisPan I've contacted the Blue Support Bubble people and I hope you can get linked up with my logs to help identify what was going on. For clarity, I didn't do anything that I think would have fixed it.

**Comment by nrajpurkar** [comment]
Thanks for the updates! Closing this out, but reach out again if anything comes up.

**Comment by plaa** [comment]
I'm having the same issue.  In Azure DevOps I see two service hooks configured for App Center (both created by an ex-employee).  When I try to test those hooks, both return a 404 error from App center.  I can find no documentation on how service hooks between Azure DevOps and App center should be set up.

Is there some way I can delete the connections and re-create them?  Is this documented somewhere?

**Comment by plaa** [comment]
I contacted App Center support using the chat button in the lower corner.  They did a soft reset on the projects on their back end and the service hooks started working.
