### ISSUE TITLE
Test on real device (Free) from Azure DevOps pipeline

### ISSUE THREAD

**Issue by rodbassatgatech** [microsoft/appcenter#803]
@amchew
I have have migrated my CI builds from App Center Build to Azure DevOps build pipeline.  In App Center I can do a free launch test on a real device.  

![image](https://user-images.githubusercontent.com/19650216/62254000-a6cea300-b3c5-11e9-98c6-9dbad1349b2c.png)

I am trying to launch the same test from DevOps using the Xamarin UI Test tool 'test-cloud.exe'.  How do I specify the device set for that test?  Is there a way to get the free launch test from DevOps a build pipeline?

![image](https://user-images.githubusercontent.com/19650216/62253722-d4671c80-b3c4-11e9-8861-5353ceea09ef.png)

**Comment by amchew** [comment]
Thanks @rodbassatgatech for the comment! @nrajpurkar, would you know?

**Comment by nrajpurkar** [comment]
@rodbassatgatech hi there, thanks for the feature request! The free launch test is not available for builds in Pipelines. In App Center, we pick up the bill for ya on that 😉 Feel free to leave this open as a feature request and we'll continue to track it as something we could work with the Pipelines team to offer.

**Comment by nrajpurkar** [comment]
In terms of actually using the task and specifying the device set @Oddj0b or @dimazaid may be able to help you there

**Comment by bmacombe** [comment]
I would really like this feature, I do all my builds in Dev Ops but would really like just a launch test.

**Comment by elamalani** [comment]
@bmacombe You can use launch test feature by using this command "appcenter test generate uitest" in App Center CLI but it wont be free if you are using Azure Pipelines.

**Comment by bmacombe** [comment]
@elamalani Thanks, so I would need to get the App Center UI test subscription?  Which I've been thinking about anyway.
