### ISSUE TITLE
Push.Subscribe(bool value)

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#804]
Hi,

Please add **Push.Subscribe(bool value)** command to the AppCenter Push instead of using the [DELETE](https://openapi.appcenter.ms/#/push/Push_DeleteInstallId)

This will make it easier for developer just to call Push.Unsubscribe() and then AppCenter will delete it synchronously 

This is very helpful for settings page for example if the user wants to switch off Push Notifications then he will just turn it off from the setting page and at the backend it will call:

`Push.Subscribe(true)`

and later if he decided he wants to receive the Push Notifications he will just turn it on and at the bakend it will be:

`Push.Subscribe(true)`

Thanks,
[Jassim](https://www.softnames.com)

**Comment by jwargo** [comment]
@jrahma thanks, that's a great suggestion.

**Comment by jrahma** [comment]
This is what I got from the support  team which is just a workaround and hope the Push.Subscribe(bool value) will be implemented soon because it's a basic requirement for any app.

```
// To unsubscribe call
Push.setEnabled(false);
FirebaseInstanceId.getInstance().deleteInstanceId();
// To re-subscribe
Push.setEnabled(true);

```

**Comment by jrahma** [comment]
![image](https://user-images.githubusercontent.com/6236241/62567833-17316480-b89d-11e9-96e1-119ab7f0a292.png)


👎

**Comment by jwargo** [comment]
> ![image](https://user-images.githubusercontent.com/6236241/62567833-17316480-b89d-11e9-96e1-119ab7f0a292.png)
> 
> 👎

@jrahma I don't understand the point of this response, can you clarify?

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
