### ISSUE TITLE
Exclude Test Devices

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#805]
Hi,

In Analytics, can you please add an option to exclude the Test devices because otherwise it will be the top device in the Analytics..

It should not be counted at at all in any measurement

Thanks,
[Jassim](https://www.softnames.com)

**Comment by winnieli1208** [comment]
Thanks for the feature request! This isn't on our roadmap but we'll leave this issue open to track community interest. 

In the meantime, you can [export your data to App Insights](https://docs.microsoft.com/en-us/appcenter/analytics/export) to filter out specific data points or use our [analytics APIs](https://openapi.appcenter.ms/#/analytics) for more customizability. Ill let @hamswan jump in with any other suggestions. Thanks!

**Comment by alexcnichols** [comment]
I agree that it can cloud the Analytics reports when Build launch tests and Test runs are included. Would be helpful to have a way to filter those out (probably by default).
