### ISSUE TITLE
Change the format of export iOS device UDIDs

### ISSUE THREAD

**Issue by timcolla** [microsoft/appcenter#807]
Apple have changed the format of the file you can use to import multiple devices to your Apple developer account. App Centre still uses the old format.

Change format from:
`Device ID	Device Name`
To:
`Device ID	Device Name	Device Platform`

Thanks,
Tim

**Comment by nrajpurkar** [comment]
Thanks for the issue @timcolla. Tapping in @botatoes and @Oddj0b to take a further look
