### ISSUE TITLE
Page tracking roadmap

### ISSUE THREAD

**Issue by nak5ive** [microsoft/appcenter#808]
I noticed a protected method in the source of the Android SDK for tracking page views...
https://github.com/microsoft/appcenter-sdk-android/blob/624de03b2b728822412207524d46249b7bb6e8da/sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java#L292

It indicates that the backend does not support it yet, but will in the future. However, I'm not seeing page tracking in the roadmap.

Could we expect to see this feature soon?

**Comment by amchew** [comment]
Hi @nak5ive, thanks for reaching out! We'll get back shortly.

**Comment by hamswan** [comment]
Hi @nak5ive, 
It is not supported yet, we don't have an ETA. I will leave this request open so you can track it from here.

**Comment by jrahma** [comment]
Yeah this will be great if we can have Page View on the Dashboard instead of doing it manually in Events

It will be awesome if you click on the Page View for every page then get the more details for it, for example, visitors, duration, geo source, devices, etc
