### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by PostImpatica** [microsoft/appcenter#809]
Can we please have support for us to host progressive web apps within app center?  I would think this would be really easy to support.  

This may sound like a ridiculous request you can already host PWA's within Microsoft Store and we have certain reasons why we want to be able to do this with App Center for non-Microsoft devices.

**Comment by patniko** [comment]
We're talking to developers about what SPA and PWA support should/would look like in App Center right now. Would love to chat if you're up to tossing me an email: panikole [at] microsoft.com

**Comment by CKGrafico** [comment]
+1

**Comment by matzter** [comment]
+1

**Comment by mhrastegari** [comment]
+1
