### ISSUE TITLE
iOS Build - large mobileprovision file - Unknown error (request entity too large)

### ISSUE THREAD

**Issue by hiraldesai** [microsoft/appcenter#810]
**What App Center service does this affect?**
App Center iOS Build configuration

**Describe the bug**
I am unable to configure iOS Device build with a large .mobileprovision file.

**To Reproduce**
1. Go to any of your iOS app -> Build
2. Configure the build to be "Device build", upload a mobileprovision file which is fairly big (Microsoft's internal file is 3.8 MB)
3. See the error message "Oh no, we couldn’t configure your branch! Unknown error"

**Expected behavior**
It is normal for bigger organizations to have large development provision file. Microsoft itself is a good example. App Center should accept bigger size files.

**Screenshots**
![image](https://user-images.githubusercontent.com/1005174/62335388-7ef04580-b480-11e9-9183-f63a4e84467d.png)

![image](https://user-images.githubusercontent.com/1005174/62335405-92031580-b480-11e9-9ebb-bc887708538e.png)

**Comment by nrajpurkar** [comment]
Hi @hiraldesai, is this a Xamarin.iOS app?

**Comment by hiraldesai** [comment]
It's an iOS build of a Xamarin.Forms app.

**Comment by nrajpurkar** [comment]
@hiraldesai, this is a known issue with Xamarin apps at the moment. We're going to be taking a look at fixing the upload mechanism for Xamarin signing credentials so there isn't a size limitation.

**Comment by hiraldesai** [comment]
Thanks @nrajpurkar - do you know when the fix will be available in prod?

**Comment by bryansmi** [comment]
Hi @hiraldesai! We've rolled out a fix for this issue. Could you test it our and let us know if you have any issues? Thanks!

**Comment by hiraldesai** [comment]
I think it went one step further, however I don't know if the error is related to the file size or something else about my build configuration. It is throwing a timeout error of some sort as per the screenshot below.

![image](https://user-images.githubusercontent.com/1005174/64466459-0e63c680-d0c7-11e9-9609-98e4273a108d.png)

![image](https://user-images.githubusercontent.com/1005174/64466466-19b6f200-d0c7-11e9-89c6-6b9c89482a1d.png)

**Comment by hiraldesai** [comment]
It looks like it was transient indeed. However I just realized that my certificate has expired so even though I was able to upload a big file successfully, I was not able to save the build configuration. But that's not related to this particular issue, I'm closing this now. Thank you for your help!

**Comment by bryansmi** [comment]
Glad we could get it resolved :)

**Comment by hiraldesai** [comment]
Actually - I just tried it with a new valid certificate and I hit a timeout error again. Not sure if it's specific to my account or more widespread. Can you help?

```
{
  "message": "internal error",
  "err_message": "[Breaker: api-service-build-prod-east-us-build.prod.avalanch.es] Request Timed out",
  "err_stack": "Error: Request Timed out\n    at Timeout.setTimeout [as _onTimeout] (/home/node/data/node_modules/brakes/lib/Circuit.js:111:16)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at unrefdHandle (timers.js:520:7)\n    at Timer.processTimers (timers.js:222:12)"
}
```

**Comment by hiraldesai** [comment]
Closing this as this is now handled by the AppCenter Intercom support.
