### ISSUE TITLE
Cannot install app on ios device

### ISSUE THREAD

**Issue by jeremye416** [microsoft/appcenter#811]
**What App Center service does this affect?**
ios release

**Describe the bug**
I cannot install app on a registered device. In App center, the device shows as provisioned. When I click "Get", is errors and says "Oops, the app cannot be built". The app is built in Azure DevOps and worked until yesterday afternoon.

**To Reproduce**
Select a release
Click "Get"

**Expected behavior**
The app should install

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 12.3.1
 - Browser Safari

**Comment by botatoes** [comment]
Hi, can you create an intercom ticket on appcenter.ms (? on top right corner or blue button on buttom of screen)? Someone from the dev team will be able to help you.

**Comment by koystinen** [comment]
Experiencing same issue with iPhone XS Max

**Comment by pgorzelany-objectivity** [comment]
We are facing same issue.
