### ISSUE TITLE
Can't download crash report

### ISSUE THREAD

**Issue by rmarinho** [microsoft/appcenter#812]
**What App Center service does this affect?**
Test

**Describe the bug**
When looking at a test report failure for a particular test, the download crash report button doesn't work.

**To Reproduce**
1. Go to 'TestRun'
2. Click on 'StackTrace.'
3. Click on 'Download crash report.'
4. See the file that was downloaded is just a 404.html

**Expected behavior**
Should be able to download the crash report
**Screenshots**
<img width="1504" alt="Screenshot 2019-08-02 at 11 34 11" src="https://user-images.githubusercontent.com/1235097/62364612-e0b0be00-b519-11e9-9b9a-e6a2b5a21a27.png">

**Additional context**

**Comment by winnieli1208** [comment]
Hi @rmarinho can you please start a support ticket either in the blue chat bubble on the bottom left? This will put you in direct contact with our support and engineering team. Thanks!

**Comment by Oddj0b** [comment]
@rmarinho did you get help?
