### ISSUE TITLE
"Next" button is covered by the chat support button

### ISSUE THREAD

**Issue by andrewleader** [microsoft/appcenter#815]
**What App Center service does this affect?**
App Center website

**Describe the bug**
The chat support button incorrectly covers the "Next" button

**To Reproduce**
1. With a new app, go to the Push Notifications page and start setting up the push notifications
1. On one of the pages, notice that the Next button gets blocked by the chat support floating action button, as seen below

![image](https://user-images.githubusercontent.com/13246069/62385093-fbc70200-b508-11e9-995c-329057b45dd8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Canary (chromium)

**Comment by jwargo** [comment]
@andrewleader thank you for this, we are aware of the issue and have added this work to our backlog - it should be fixed soon.

**Comment by jwargo** [comment]
@andrewleader this has been fixed.
