### ISSUE TITLE
Distribute to Amazon App Store

### ISSUE THREAD

**Issue by Redth** [microsoft/appcenter#816]
**Describe the solution you'd like**
Amazon has an App Store which is the primary store for Kindle Fire devices.  It would be great if we could have support for distributing releases to this app store just like we can for Google Play store.

https://developer.amazon.com/apps-and-games

**Comment by botatoes** [comment]
Thanks for the feature request! I have a proposal for this for some upcoming stores updates. I will keep an eye out on this issue to gage further interests.

**Comment by jefftindall** [comment]
I am also looking for this capability.  Any suggestions for a semi automated solution in the interim?
