### ISSUE TITLE
Audience Interests

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#817]
Hi,

It will be great if you add user Interests from the activities the do on their mobile and desktop to understand what the app user are interested in..

We have the same feature in Firebase and hope to get it in AppCenter

![Interest](https://user-images.githubusercontent.com/6236241/62404207-907e3e00-b5a3-11e9-9da7-9e78a8ed3432.png)

Thanks,
Jassim

**Comment by amchew** [comment]
Thanks @jrahma for your feature request! We can see how this will be important, also how this is present in Firebase. We currently don't have this planned in our roadmap, and I'll let @hamswan share more details.
