### ISSUE TITLE
Diagnostics Time Filter

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#818]
Hi,

In Diagnostics Time Filter, Please add:

Today

Thanks,
[Jassim](https://www.softnames.com)

**Comment by winnieli1208** [comment]
@jrahma thanks for the feature request. We don't have immediate plans to add this but we'll keep an eye out on this request. In the meantime, you can use [our APIs](https://openapi.appcenter.ms/#/errors/Errors_GroupList) to filter through crashes by a more specific date.
