### ISSUE TITLE
Cannot install Android App "App not installed"

### ISSUE THREAD

**Issue by Xxax** [microsoft/appcenter#819]
**What App Center service does this affect?**
AppCenter without SDK

**Describe the bug**
I have an Android Ionic 4 app and try to publish it manually via AppCenter.
When I try to install it on a phone  I get the message "App not installed".

If I publish the same apk on the hockey app it works as expected.

I tried to disable Play Protect. Without success

**Smartphone (please complete the following information):**
 - Device: Android

**Comment by botatoes** [comment]
Hello, can you go on appcenter.ms and open an intercom ticket? We'll be able to get some info for debugging purposes. You can create a ticket by going to the ? on the top right of the screen or the blue button on the bottom right of the screen.

**Comment by wamry** [comment]
i'm facing the same issue, can't the issue be resolved here instead of opening a ticket ?

**Comment by vyasknellutla** [comment]
Hi @wamry we usually only provide direct support through our support portal since there we can troubleshoot the issue while also keeping your application data private in the process (something we can't do on a public form like this).

However, we do have documentation and guides posted on our [docs page](https://docs.microsoft.com/en-us/appcenter/) if you are looking to troubleshoot the issue independently or looking for solutions to common problems.

**Comment by wamry** [comment]
@vyasknellutla thanks for your reply, i figured out the solution, it's got something to do with the release signing option in gradle file, your doc page are missing a lot of information.

**Comment by Sakarisson** [comment]
@wamry Can you please tell me the steps that you took to resolve the issue?

**Comment by Xxax** [comment]
With me it was like this, if you uninstall the app via the SmartLauncher (https://www.smartlauncher.net/), not everything is deleted and you can't install the app via AppCenter anymore. You have to uninstall the app with ```adb uninstall xxxx ```. 

If you uninstall the app using the native function, the installation will work without problems.

**Comment by wamry** [comment]
@Sakarisson 
in app/build.gradle file, make sure that in buildTypes -> release, there is no signingConfig

example:
```
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
```

and ofc in app center make sure to choose the correct keystore file and input the alias and passwords
