### ISSUE TITLE
Make distribution of APK files platform agnostic for 'testers'

### ISSUE THREAD

**Issue by UnreachableCode** [Microsoft/appcenter#82]
**Describe the solution you'd like**
At the moment, APK files for users added as testers are only downloadable on an Android device. It would be convenient to download them through a desktop browser as another distribution option.

**Describe alternatives you've considered**
Local archiving from Visual Studio and then using email, Dropbox or We Transfer, but this obviously is more steps than just having a URL to re-use.

**Additional context**
This is what our testers see now. The button is grayed out when viewing the link on Windows.
![capture43](https://user-images.githubusercontent.com/1167553/53005756-c67f9980-342b-11e9-802d-9141171bbb47.PNG)

**Comment by patniko** [comment]
Hi @UnreachableCode, you should be able to download APK's from desktop browsers now. Please let us know if there is anything else you'd like to see. Thanks!

**Comment by UnreachableCode** [comment]
Thank you, Patniko
