### ISSUE TITLE
Rearrange Menu Items

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#820]
Hi,

In current menu, the following comes in this order:

- Overview
- Build
- Test
- Distribute
- Diagnostic
- Analytics
- .......
- ......
- 

Please add an option to rearrange and save the new arrangement because for some users, Build and Test might not be done in AppCenter or Diagnostics and Analytics are more important so they need to make it on top.

Thanks,
[Jassim](https://www.softnames.com)

**Comment by blparr** [comment]
Hi @jrahma , thanks for your feature request! We will consider it for future improvements. Thanks!
