### ISSUE TITLE
Enabling WPF Crash Support in the UI?

### ISSUE THREAD

**Issue by TimberRaft** [microsoft/appcenter#821]
I started investigating using App Center for crash reporting and implemented some sample code.  I created a "UWP" app in App Centre and tried using the provided Guid, but could not see any results for a Crashes.GenerateTestCrash().  Does there need to be something else for a WPF (Framework 4.8) application?

The documentation for WPF/Winforms states:
"The WPF and WinForms UI hasn't been released yet. If you would like to try out the analytics and diagnostics SDK, please reach out to our support team and we can enable this experience for you."

I was not sure if this was the correct place to reach out. I did not see any other support links in the App Center UI.

Thanks,

**Comment by winnieli1208** [comment]
Hi @TimberRaft - can you start a support ticket in App Center with your email address so I can enable the UI for you? Thanks!

**Comment by TimberRaft** [comment]
Thanks for the response.

My question is where in the App Center?  The only menu item  is “Submit an Issue” which puts me back here?

**Comment by winnieli1208** [comment]
Hi @TimberRaft thanks for your patience! We just globally enabled the feature flag so you should be able to create a new WPF/WinForms app in the App Center UI.

Closing this issue but let me know if you have any questions or issues. Thanks!
