### ISSUE TITLE
Does AppCenter upload the mapping.txt file to the Play Store automatically?

### ISSUE THREAD

**Issue by Zee-day** [microsoft/appcenter#823]
I have app center building and pushing my apps tot the Play Store beta channel but Im not sure what happens to the mapping.txt file. I have tried to look through the documentation but I cant find an answer to this, only that the file gets uploaded to the app center diagnostic panel automatically.
Thanks

**Comment by jwargo** [comment]
@Zee-day the best way to get answers to questions like this is through our dedicated support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by Zee-day** [comment]
Thanks I will ask them
