### ISSUE TITLE
Granular Control over Permissions for CodePush

### ISSUE THREAD

**Issue by CT-8CatsEngineering** [microsoft/appcenter#824]
We would like to be able to set which role has permission to push or promote a build to a deployment in CodePush. 

For example, developers can push or promote a build to a QA deployment or a Staging deployment but only Managers can push or promote a build to a Production deployment.

I would envision this to be configurable at the deployment level when creating or editing the deployment.

**Comment by botatoes** [comment]
Thank you for the feature request. I have added this to our backlog for prioritization after our current set of work on the new version of CodePush.

**Comment by laurenwilliams** [comment]
Hi there, @botatoes! I was wondering if there was any updates on this feature request - it is something my team is looking for as well.
