### ISSUE TITLE
react-native remote update

### ISSUE THREAD

**Issue by drakonkat** [microsoft/appcenter#831]
When i call the function "release-react" of the appcenter-cli to update react-native app, i can update the code but it will not work if i added new library that require "react-native link LIBRARY". So it's useful if i can update my react app with new library.

The alternative that i use now is hockeyapp and the user will download the new APK with new linked library... but it will be deprecated so maybe can be useful a new app with notification when new version is avaiable?

**Comment by nrajpurkar** [comment]
Thanks for opening this issue @drakonkat. Tapping in @botatoes to take a further look

**Comment by drakonkat** [comment]
Any news?
