### ISSUE TITLE
Upload mapping.txt file to the Play Store automatically

### ISSUE THREAD

**Issue by Zee-day** [microsoft/appcenter#832]
I would like to request a new feature to upload the Android mapping.txt file to the Play Store automatically so that we don't have to do it manually. The Play Store has an API to allow this feature but it is non-trivial to implement this using either Groovy or the post build bash script. https://developers.google.com/android-publisher/api-ref/edits/deobfuscationfiles/upload

**Comment by Oddj0b** [comment]
Hey Zee-day, thank you for your suggestion. I get the gist of it but I have a question regarding the automatic part, can you elaborate on how it would work, i.e. where does the file come from and when would it be uploaded?

**Comment by Zee-day** [comment]
Hey @Oddj0b thanks for the reply.

- The mapping.txt file is generated when an Android app is built with proguard enabled. App Center already knows about this file as there is an option to download it once the build is complete.

- I image the file would be uploaded to the Play Store after the APK has been successfully uploaded using App Centers distribution mechanism
