### ISSUE TITLE
Build uploaded to AppCenter missing in HockeyApp 

### ISSUE THREAD

**Issue by daehn** [microsoft/appcenter#833]
**What App Center service does this affect?**
Syncing of builds uploaded to AppCenter back to HockeyApp.

**Describe the bug**
We are uploading our iOS builds to AppCenter using [fastlane-plugin-appcenter](https://github.com/microsoft/fastlane-plugin-appcenter) and until a couple of days ago these builds also showed up on HockeyApp and it was possible to download them from there. 

**To Reproduce**
1. Upload a new build to AppCenter.
2. Check HockeyApp for the build.

**Expected behavior**
We expected the build to also appear in the list of builds on HockeyApp.

**Comment by derpixeldan** [comment]
@daehn we've recently changed this to simplify the syncing because it caused a lot of trouble. I would like to understand better why you still need HockeyApp in this scenario?

**Comment by daehn** [comment]
A lot of people where are accessing our releases through HockeyApp, but we don't necessarily need it and will accelerate moving everyone over to use AppCenter in that case.
