### ISSUE TITLE
Multiple build configurations per branch

### ISSUE THREAD

**Issue by antpuleo2586** [microsoft/appcenter#834]
**Describe the solution you'd like**
We would like to be able to configure multiple builds per branch, so we can distribute to different environments i.e. dev, uat, production.

**Describe alternatives you've considered**
Multiple branches for multiple builds, but we don't want to have to maintain a branch per environment build configuration.

**Additional context**
I've seen something similar requested [here](https://github.com/Microsoft/appcenter/issues/50) but the issue is now closed.

p.s. I was advised by one of the App Center chat agents to open a new feature request for this.

Thanks!

**Comment by lumaxis** [comment]
@antpuleo2586 Let's reopen #50 again then and continue to track general interest there 🙂
Make sure to give it a ":+1:" there!
