### ISSUE TITLE
[Feature Request] - Velocity alerts to stay informed about critical stability issues

### ISSUE THREAD

**Issue by cosminstirbu** [microsoft/appcenter#835]
**Describe the solution you'd like**
Provide stability / velocity alerts about crashes / errors (similar to Fabric - http://fabric.io/blog/7-crashlytics-tips/)

**Describe alternatives you've considered**
http://fabric.io/blog/7-crashlytics-tips/ - 6. Pay attention to velocity alerts to stay informed about critical stability issues

**Additional context**
Over the weekend we had a crash in production that occurred when our users attempted to sign in (caused by a backend issue). 

It occurred for all of our users, so we had over 4000+ occurrences. It would've been useful to receive some sort of velocity / stability alert.

**Comment by amchew** [comment]
Thanks @cosminstirbu for your request! @winnieli1208 would you mind taking a look?

**Comment by winnieli1208** [comment]
Thanks for feature request and additional context. I can definitely see the value in this feature especially in a scenario like the one you provided. Unfortunately, due to other priorities at the moment, this isn't on our roadmap. We'll keep an eye out on this thread for additional interest to help us prioritize in the future. 

Thanks!

**Comment by cosminstirbu** [comment]
Hello,

It's been a while since I've reported this feature request.
There has been some interest expressed on it but I'd like to add to my initial argument.

One of the practices of the DevOps culture is monitoring - and for proper monitoring we need proper alerting systems - which I believe that AppCenter currently lacks and could address by implementing the proposed feature.

Please reconsider the priority of this feature.

Thank you,
Cosmin

**Comment by winnie** [comment]
Hey thanks for the feedback! We're actively looking at improvements to our alerting capabilities (including adding custom rules, thresholds, and velocity alerts). Unfortunately, I can't commit to a timeline right now but would love to hear your thoughts when we have more details and mockups to share.
