### ISSUE TITLE
Dropdown for Campaign and make it optional

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#837]
Hi,

In most of the scenarios, campaign is not a must because normally the user sends regular messages so please make it optional and don't force the user to enter campaign.

Also, please make it optional DROPDOWN list instead of text with an option to add so if the user sends regular **Marketing** Campaign then why he needs to type the word Marketing every time and sometimes he will have spelling mistake so it will come under two campaign.so best option is...

1. Keep it an dropdown list
2. Allow the user to add items to the drop down list
3. and Make it optional not mandatory

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by nrajpurkar** [comment]
Thanks for the feature request @jrahma. Tapping in @jwargo to take a closer look at this one.

**Comment by jwargo** [comment]
@jrahma what we're considering doing is enabling customers to resend a notification - would that work for you?

**Comment by jrahma** [comment]
Yes, that will be great..

**Comment by jwargo** [comment]
@jrahma Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
