### ISSUE TITLE
Group Push Notifications by Campaign

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#838]
Hi,

Currently when the user opens the Push Notifications page it will list individual sent messages with a campaign column..

I suggest the following..

1. Remove the campaign column from the Push page and keep the Target, Sent and Date columns
2. if the message was sent without the optional campaign #837 then it will open the message details and report
3. if the message was sent with a campaign the it will open the message details with the clickable campaign name
4. when the user clicks on the campaign name then it will list all the past history sent under that campaign 
5. 

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by nrajpurkar** [comment]
Adding in @jwargo to take a look at this one as well

**Comment by jwargo** [comment]
@jrahma thanks for the suggestion, we're in the middle of a redesign of the portal to address some missing information.
