### ISSUE TITLE
[Push notifications] Audience limit to first 1000 devices

### ISSUE THREAD

**Issue by jzeferino** [microsoft/appcenter#839]
**Describe the solution you'd like**
Currently, App Center allows you to create an Audience of any size, but will only send notifications to the first 1,000 devices in the audience. This is a limitation.

**Describe alternatives you've considered**
We are considering change to another provider.

**Comment by amchew** [comment]
Thanks @jzeferino for reaching out and letting us know! I'll let @jwargo comment more about this.

**Comment by jwargo** [comment]
@jzeferino thank you for that feedback, it is something we're looking to address, but right now the only option you have for larger audiences is to use Azure Notification Hubs instead.
