### ISSUE TITLE
Pick columns on apps list

### ISSUE THREAD

**Issue by nscherer** [microsoft/appcenter#840]
It would be helpful to be able to choose what fields to display in the list of apps.  The one I'm thinking of in particular is most recent release.  Hockeyapp has this as "Last updated".  Maybe if choosing fields is too complicated, just add that one?

**Comment by winnieli1208** [comment]
Thanks for the feature request! This isn't on our immediate roadmap but we've definitely heard similar requests like this. We'll keep an eye out on this thread for community interest and post here with any updates. 

Thanks!

**Comment by blparr** [comment]
Hi @nscherer! Thanks a lot for your feature request! This is on our radar, but don't have immediate plans to implement it. Let me ask you a follow up question - how would you define 'Last Updated' in App Center (given that there are several services you might be updating)? 

Thank you so much!
