### ISSUE TITLE
Re-authenticate Apple App Store Credentials 

### ISSUE THREAD

**Issue by OneQMobile** [microsoft/appcenter#841]
**What App Center service does this affect?**
App Center - Distribute - Stores

**Describe the bug**
I get the error message "_Your Apple App Store Credentials are no longer valid. Please re-authenticate._"
However, when I try to re-authenticate I am not allowed. I am logged in with the user tsl@oneq.tech 

**To Reproduce**
1. Go to 'a specific app'
2. Click on 'choose Distribute and then Stores'
3. Push 'Reconnect'
4. See error (attached picture)

**Screenshots**
is attached

**Desktop (please complete the following information):**
 - Using Mac Book Air
 - Using Safari

**Additional context**
<img width="1193" alt="Screenshot 2019-08-08 at 08 43 12" src="https://user-images.githubusercontent.com/52155431/62683326-6fac5300-b9be-11e9-99fc-0c58c0b4a275.png">

I don't know what I should do to authenticate.
I had our external app-developer look into the issue. He had the conclusion that it must be a Platform-error.
Pleas advice

**Comment by phillipleblanc** [comment]
Hey! Thanks for reporting this issue. In order to provide a better support experience, please visit the appcenter.ms portal and open a support ticket. We'll be able to get some more for debugging purposes and better help you resolve your issue. You can create a ticket by going to the ? on the top right of the screen or the blue button on the bottom right of the screen.

**Comment by OneQMobile** [comment]
Hi Philip. That seems weird to me. 

The reason why I made the support ticket at this site, is that I got directed to this site from appcenter.ms where I selected "?" and then "Submit an issue". 
When I try to open a conversation by selecting the "blue Botton" on appcenter.ms - it is a chat window, and is not really fitting for describing an issue.

**Comment by Thunderbird7** [comment]
I have the same issue now.

**Comment by b-m-p** [comment]
Would be great if a solution was posted as I am having a hard time figuring this out and there must be others running into this issue.

**Comment by ToniVilar** [comment]
Issue is not solved, at least for me, why is this ticket closed?

**Comment by declan-dowling** [comment]
We are also experiencing this issue. Multiple users in the Admin role can see this Reconnect option but cannot enter a password or press connect. 

I have contacted AppCenter via the floating chat button, will see what they say. It may be that this is known issue and the only way to resolve it for now is to contact AppCenter support directly via your account.

I will update this ticket when I have spoken to someone and it is (hopefully) resolved.

**Comment by declan-dowling** [comment]
After speaking with someone from AppCenter support, I was able to resolve this issue.

Remove your apple account here:
https://appcenter.ms/settings/accounts

Go to your app's store connection page and re-select your connection:
https://appcenter.ms/orgs/<your-org-here>/apps/<your-app-here>/Production/releases/settings

**Comment by declan-dowling** [comment]
@Oddj0b should this issue be re-opened and a fix looked for in AppCenter that doesn't require contacting support? Even if it's the instructions given to me adding to a troubleshooting/FAQ page?

**Comment by Oddj0b** [comment]
@declan-dowling I've added it to the FAQ and it should appear tomorrow in the documentation. Thank you for the advice.

**Comment by allengreer-latero** [comment]
Still have an issue, doesn't matter is user is manager or not. Still get "You don't have access to update this connection." when trying to re-auth

**Comment by davidperrenoud** [comment]
Yes, it is the user that originally added the Apple account that needs to remove it.

**Comment by meiryasuda** [comment]
I'm having the same problem, can we reopen this issue?

**Comment by ameenaliu** [comment]
I am also experiencing this issue. Can this issue be reopened? Why can users admin role reconnect the connection?

**Comment by michaelcamdencommon** [comment]
I just ran into this issue. In order to resolve it, I followed the 'reconnect to github' button workflow (logged in, auth'd, etc), error didn't clear. I then cleared my localStorage and sessionStorage using the browser's dev tools reloaded, logged back in and the error was cleared.

**Comment by jmlp1327** [comment]
After asking for support to App Center, they mention that it is not their fault. That this occurs at least once a month because Apple requires that. They mentioned that there are other factors like detection of change location/login of the account. :(
