### ISSUE TITLE
Fast app switch button

### ISSUE THREAD

**Issue by mikaoelitiana** [microsoft/appcenter#842]
**Describe the solution you'd like**
I have multiple apps on AppCenter and it would be helpful to have a dropdown to switch between project in the left menu. It would bring to the current screen but on other apps, for instance, quickly switching to Distribute > Release of another app.

**Describe alternatives you've considered**
I have an external markdown file with quick links to screen I often go to and use it instead of goind to AppCenter home page and select one app.

**Additional context**
<img width="273" alt="Capture d’écran 2019-08-08 à 10 44 49" src="https://user-images.githubusercontent.com/674667/62688959-2a8e1e00-b9ca-11e9-8796-b1af00c4ab73.png">

**Comment by derpixeldan** [comment]
Duplicate of https://github.com/microsoft/appcenter/issues/229

**Comment by blparr** [comment]
Thanks for your feedback! We will consider your feature request for upcoming improvements.

**Comment by mikaoelitiana** [comment]
I am closing this ticket as it is a duplicate of #229.
