### ISSUE TITLE
WPF build support

### ISSUE THREAD

**Issue by VladislavAntonyuk** [microsoft/appcenter#85]
It would be great to have a possibility to build WPF/WF applications

**Comment by lumaxis** [comment]
Hey @VladislavAntonyuk! Good news 🙂 This is indeed already on our Roadmap: https://github.com/Microsoft/appcenter/wiki/Roadmap#platform-support
For now, there is no more detailed ETA but it will show up in our [Iteration Plans](https://github.com/Microsoft/appcenter/wiki/Iteration-Plans) once our plans around it become more concrete.

**Comment by VladislavAntonyuk** [comment]
Great! Waiting for release

**Comment by lumaxis** [comment]
@VladislavAntonyuk It appears that there was a mistake in our internal communication. While we have a lot of good work planned to better support WPF apps, support for building them in App Center is not something we have currently committed to.
We updated the Roadmap to more clearly reflect this and will obviously take note of your request for future work prioritization 🙂

My apologies for the mistake!

**Comment by lumaxis** [comment]
If anybody else reading this is also interested in WPF build support, please upvote the original comment to help us understand the demand for this Thanks!

**Comment by VladislavAntonyuk** [comment]
I think it is already implemented, because you have uwp builders. All that you need is to setup .net framework and .net core if they not installed

**Comment by rido-min** [comment]
You can build and distribute WPF/WinForms applications if they are packaged with the Windows Application Packaging Project (available in the UWP workload in VS)

**Comment by VladislavAntonyuk** [comment]
@rido-min I wanna distribute my application as executable .net framework, not uwp

**Comment by ridomin** [comment]
@VladislavAntonyuk with the Packaging Project you can distribute your .net framework apps creating APPX/MSIX packages. https://aka.ms/wapproj

**Comment by VladislavAntonyuk** [comment]
But I want to get exe instead of appx

**Comment by ridomin** [comment]
@VladislavAntonyuk WPF applications could require more than the EXE. The APPX package is a zip file with the EXE and all additional files that also enables an installation experience and other goodies.

**Comment by VladislavAntonyuk** [comment]
Of course I don’t know all required steps to add support more projects

As I understand the Visual Studio, msbuild and other tools and plugins are installed on the build machine. And when user setup app’s build, he choose sln or csproj and other steps - the same settings which he has on his own dev machine. So if you have the same tools installed on build machine you can get build output and project output directory for distribution

**Comment by VladislavAntonyuk** [comment]
any updates?

**Comment by VladislavAntonyuk** [comment]
T

**Comment by VladislavAntonyuk** [comment]
any updates?

**Comment by VladislavAntonyuk** [comment]
B
