### ISSUE TITLE
Comments from users are difficult to find

### ISSUE THREAD

**Issue by schriftgestalt** [microsoft/appcenter#850]
The overview in hockeyapp showed what report has a comment. 
<img width="391" alt="Screenshot" src="https://user-images.githubusercontent.com/174660/62770928-5974c480-ba9c-11e9-8bca-f7ba62fbc84b.png">
in App Center, I need to click each report and then click "ATTACHMENTS" to see if there is a comment:
<img width="654" alt="Screenshot" src="https://user-images.githubusercontent.com/174660/62771095-af496c80-ba9c-11e9-9e3b-e725fff3c4ff.png">

**Comment by winnieli1208** [comment]
Thanks for the request! We're looking at ways to improve our crash reports UI including making relevant information easier to find. I don't have an ETA at this time but will post here with updates. 

(Reference #925 similar request but for User ID)

**Comment by macmade** [comment]
+1 for this, as I was about to open a similar issue.

An icon on individual reports would be nice, but **ideally I think the text attachments should be displayed on the overview page. Or at least the latest ones**.

Clicking on every report to see the attachments is not an efficient way to identify an issue.

**Seeing all text attachments at once would be a huge benefit for us developers**.

**Comment by Iomegan** [comment]
A column would help a bit, but seeing all text attachments per issue would be a great improvement over hockeyapp.

**Comment by winnie** [comment]
Hi @schriftgestalt - we just added a few new columns to the crash report table view including one that indicates if your crash report has an attachment:

![image](https://user-images.githubusercontent.com/8868628/76965023-000a2900-68fa-11ea-87c5-eaccfd1ed41f.png)

I will keep this issue open since there are also requests to include attachments in the overview page but hope this helps a bit!

**Comment by macmade** [comment]
Issue is not fixed…

**Comment by macmade** [comment]
Issue is not fixed…

**Comment by schriftgestalt** [comment]
It is not solved, yet.

**Comment by schriftgestalt** [comment]
It is not solved, yet.

**Comment by schriftgestalt** [comment]
This is not solved, yet.

**Comment by schriftgestalt** [comment]
Stil not solved.

**Comment by schriftgestalt** [comment]
But it is not fixed, yet.

**Comment by schriftgestalt** [comment]
But it is not fixed, yet.

**Comment by schriftgestalt** [comment]
Still not fixed.

**Comment by macmade** [comment]
Still not fixed.
