### ISSUE TITLE
Daily crash report E-Mails

### ISSUE THREAD

**Issue by BlackWolf** [microsoft/appcenter#853]
**Describe the solution you'd like**
It would be great to have a daily e-mail notification about how many crashes occured for which apps in your AppCenter account and about the most common crashes and how many users were affected.

**Describe alternatives you've considered**
We turned on "e-mail for new crash groups" in AppCenter, but this is not very helpful to us, since it will send emails when a crash first appears, while we are more interested in crashes that affect a lot of users, e.g. after a new version was released.

**Additional context**
N/A

**Comment by PGHM** [comment]
I'd like this too, just like Hockeyapp used to do it

**Comment by rbanker** [comment]
This is an important one for us.  We have 30+ apps and reviewing each individually everyday is untenable.  The HockeyApp email was perfect.

**Comment by Istiakmorsalin** [comment]
This one is very crucial for us. We need this feature for team-wise monitoring.

**Comment by winnieli1** [comment]
Hi all - thanks for the feature request and feedback! This feature is committed on our roadmap. I don't have an ETA at the moment but will post here when I have more information.

**Comment by winnieli1** [comment]
Hi all! We're starting work on this very soon and would love some feedback. 

I know HockeyApp displays all new crashes in the daily email but we're thinking of showing just the top 3 crashes (based on number of occurence) to make these emails more readable. Here are the WIP design:

![image](https://user-images.githubusercontent.com/8868628/66868747-c69c4e80-ef52-11e9-8b33-79b827947b3f.png)
 

What does everyone think? What crash information would you expect to see in these emails?

**Comment by VaibhavMisra** [comment]
Hi. 

First of all, I'd really like thank for you and your team. We are switching to AppCenter for most of our needs around automation, analytics and distribution.

We were using Crashlytics and now migrating to AppCenter for crash reporting. I'd like if we can something similar to daily emails from Crashlytics where we get the following information for each app of our organization: 

1. Monthly active users
2. Daily active users
3. Daily new users
4. Crash free users
5. Total sessions
6. Time in App per user

All these stats are available with percentage change as well. It would be great, if we can also top 1 or top 3 crashes and a link to dashboard for each app along with it.

Really looking forward to this feature. Could you share an ETA for this, so that I can share this with my managers.

**Comment by BlackWolf** [comment]
@winnieli1 Looks great. For us, what would be great is to not only have top **new** crash groups, but also the top crash groups yesterday. This could help us noticing if a crash suddenly is having an unusual number of occurences (say, because a date format on some remote service has changed and we didn't properly plan for that or something).

**Comment by winnieli1** [comment]
Thanks for all the helpful feedback! 

@VaibhavMisra the first version of this email will just include crash metrics only (and releases information if applicable) but your other ideas are great. We'd love to have an all up dashboard / email that reports other metrics including analytics and crash free users. Feel free to create another feature request for better tracking.

@BlackWolf also great idea! I believe you're looking for something like "velocity alerts"? Feel free to give issue #835 a thumbs up if that matches what you're looking for. 

We'll keep this thread updated on our progress. Thanks all!

**Comment by edensche** [comment]
We need as well the daily crash reports. We have more than 60 apps and the tool on hockey app allows us to catch quickly severe issues. 3 top crashes would not serve the purpose since our apps are largely used so critical issues could not be seen if only the top 3 would appear

**Comment by winnieli1** [comment]
Hi there! We recently enabled support for daily digest for crashes. To enable this for your apps, go to the **Settings** page, select **Email Notifications** section, and choose the **Daily** option under Crashes:

![image](https://user-images.githubusercontent.com/8868628/69456098-b9773a00-0d1e-11ea-807c-91a9aedaec50.png)

Note: we only display the top three crashes to maintain readability of these emails but we are more than happy to iterate on the design based on your feedback. I'm closing this issue but please create a seperate issue if you have other requests. Thanks!

**Comment by stephent** [comment]
If, like me, you're looking for something closer to the old HockeyApp email (total crashes, new and existing crash groups, not just new), please look at #1378.
