### ISSUE TITLE
Separation of crashes and errors in closed, open and ignored.

### ISSUE THREAD

**Issue by MathewLC** [microsoft/appcenter#854]
**Describe the solution you'd like**
When we talk about production apps, that is a lot of erros going on, tiny and big ones. I would like to have a better separation of erros that I already closed to rigthely choose the one that i should attend first. Today is all together an mix and this is very annoing.

**Describe alternatives you've considered**
Maybe the functionallaty of tag errors and separating then by that would resolve all the problems. But the tag that already occurs is really good, i just need a visual separation of closed and ignored from open ones, like the TABS for erros and crashes.

**Comment by amchew** [comment]
Thanks @MathewLC for reaching out and sharing this request! I'll let @winnieli1208 comment more about this.

**Comment by MathewLC** [comment]
I'm still waiting to know if the feature was implemented, best regards
