### ISSUE TITLE
pre build script: buildId variable ?

### ISSUE THREAD

**Issue by softlion** [microsoft/appcenter#858]
**Describe the solution you'd like**
Appcenter displays near a build for example:
```
Build 158
Manual build
```

It uses a variable during the build script that has this number "158".  
But it is not exposed in the official documentation.

What variable holding this buildId can be used in a pre build script ?  
Note that i don't want the value generated by the "Build number format" setting.

**Comment by amchew** [comment]
Thank you @softlion for reaching out! Adding @nrajpurkar to share more details.
