### ISSUE TITLE
AppCenter Windows not Logging

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#861]
Hi,

I have added the AppCenter to my WinForm application.

![image](https://user-images.githubusercontent.com/6236241/62831026-d5504780-bc29-11e9-9664-2ea0622068b0.png)

and I have added few Events as well and used all of the screens for the past 3 days but until now nothing has been logged to the AppCenter portal

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by hamswan** [comment]
Hi @jrahma, our team is looking at this.

**Comment by AnastasiaKubova** [comment]
Hi, @jrahma! Thank you for contacting us! Could you please clarify:
- What version of SDK do you use?
- Could you please share the verbose logs? Please add `AppCenter.LogLevel = LogLevel.Verbose;` before `AppCenter.Start`.

**Comment by Jamminroot** [comment]
We haven't heard from you for a while now. Closing the issue, but feel free to reopen in case the problem is not resolved.
