### ISSUE TITLE
Auth: Keep user logged in

### ISSUE THREAD

**Issue by knasher** [microsoft/appcenter#862]
First, I just want to say that you guys rock, App Center is a great product!

I've been playing around with Auth and I wanted to know how you guys plan on keeping users logged in? Could users be silently logged in if they've already been logged in between sessions, or could we get the refresh_token so we could do it ourselves?

I'm looking at writing an app that would allow users to be logged in the moment they reopen the app but I cannot see how that can be achieved without extending the life of the access_token or having the refresh_token to hand.

**Comment by SOliasS** [comment]
#860 I think this two issues could be connected  => More granular control over Auth

**Comment by SOliasS** [comment]
The Current behavior(i think):
If your user logged in(await Auth.SignInAsync();) once he keeps being logged in until he logs out(Auth.SignOut();).
You don't need to/can handle anything by your own.

**Comment by jwallra** [comment]
Hi @knasher !

@SOliasS Is correct; you shouldn't need to do anything to keep users signed in.  See the notes on this section in our documentation: https://docs.microsoft.com/en-us/appcenter/sdk/auth/xamarin#sign-users-into-the-app

If you're observing different behavior please reopen and let us know
