### ISSUE TITLE
Not possible to connect github organizations via dashboard

### ISSUE THREAD

**Issue by tedgonzalez** [microsoft/appcenter#863]
**What App Center service does this affect?**
AppCenter Dashboard

**Describe the bug**
https://appcenter.ms/orgs/_owner_name_/apps/_app_name_/build/connect/github
Doesn't show my organizations so it is impossible to connect github

**To Reproduce**
1. Pick one organization
2. Pick one app
3. Click Build
4. Click github > it shows my github repos without organization repos

**Expected behavior**
It should show my github repos with organization repos

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser chrome and safari

**Comment by nrajpurkar** [comment]
Hi @tedgonzalez, two questions to hopefully solve this:

1. Are you an admin for the org? You need to grant App Center permission to the org and authorize the OAuth connection.
2. If you are an admin, please make sure you have granted App Center permission to the org in your GitHub settings. Navigate to your [Application Installations](https://github.com/settings/installations) > Authorized OAuth Apps > App Center > and then Grant Access to the organization you expect to see in App Center.

Let me know if this works!

**Comment by tedgonzalez** [comment]
Yes I am admin and yes I have AppCenter in Authorized OAuth apps and Authorized GitHub app. Note that my organization repositories are shown when connecting with AppCenter github app for the first time. I had to use this link to repeat that process
https://appcenter.ms/github-app/setup/repositories?installation_id=<redacted>&access_token_id=<redacted>5&github_user_name=tedgonzalez&github_user_id=<redacted>

**Comment by nrajpurkar** [comment]
Ah, you're trying to do this via the GitHub App. Each organization on GitHub has a separate GitHub App Center App installation. Have you installed the GitHub App Center App on that specific organization? You'll need to check the Settings > Installed GitHub Apps of the organization you are expecting to see the repos for. Additionally, each GitHub organization has it's own installation ID so you'll need to select the URL above that is specific for the organization you're trying to connect a repo from.

**Comment by tedgonzalez** [comment]
I removed the GitHub app center, and I'm trying to do this using the appcenter dashboard. Just went to github app while debugging because of this issue

**Comment by nrajpurkar** [comment]
Hmm the permissions issue for OAuth app to the orgs would be the biggest blocker here. I'd recommend you reach out to App Center support for a deeper look into the issue if this doesn't solve your problem.

**Comment by ilyeSudo** [comment]
@tedgonzalez I managed to that by signing out from Appcenter and reconnection through OAuth to GitHub. Then I got the option to "grant" access to my organization and have its repos listed as well. Hope this helps.
