### ISSUE TITLE
Shared Partions for Data

### ISSUE THREAD

**Issue by SOliasS** [microsoft/appcenter#864]
At the Moment there are 2 Types of Partions:
- Private Partions
- Public Partions

It would be nice if it were possible to create Shared Partions with shared ownership.
So the Data does not only exist in the Private partion and gets shared with others(upcoming feature), but is truly separated from one person.  
For example:
One user creates a Shared Partion and invites multiple other users.
Every added user can create/delete or update the ressources in the shared partion.
The partion continues to exist even if the inital user get's removed,

**Comment by yoannchaudet** [comment]
This is item `Collaborate on collection documents` on our [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap)!

**Comment by SOliasS** [comment]
@yoannchaudet  Isn´t that planned as sharing access to an object on private partition between people instead of creating a separate partition for multiple users to use?

**Comment by yoannchaudet** [comment]
While the work has not started and we have not specified it yet, I don't see anything wrong with your scenario.

We plan on making it possible to share documents between users and we definitely plan to allow for more than our current two predefined partitions.

**Comment by patniko** [comment]
This is one of the most frequently requested scenarios. We're planning on delivering a free Data tier and real-time device updates before moving on to this scenario, but it'll be coming. Just to clarify

1. End users should be able to create partitions that multiple users have access to read/write all documents to.
2. End users should be able to create partitions that multiple users have access to read, but only the document originator can update and delete their documents in the partition.
3. End users should be able to give multiple users access to read/write specific documents under a users partitions.

Sound about right @SOliasS?

**Comment by SOliasS** [comment]
@patniko Sounds perfect.
Any indications when it might be available?
Would like to develop our new application with this, if the timing would allow it.

**Comment by patniko** [comment]
We're in design discussions now on this one before we do some more interviews with customers. We'll share a spec in the not too distant future before we start the actual work. Still working through edge cases and other scenarios. If you have time, reach out to the email on my Github profile so we can chat a bit about your specific needs @SOliasS.

**Comment by patrickdoodyIRL** [comment]
@patniko Do you think this will make the September iteration? This feature is critical for an application we are developing. How close are you to starting the actual work?

**Comment by patniko** [comment]
We're working through our proposed designs for real time updates and document sharing right now but we'll share specs with you all this month for additional early feedback while we jump start development. Shared documents was identified as one of the biggest needs very early on so it's right at the top of the list right next to real time updates. We plan to take our time to do things right, but it's coming.

**Comment by SOliasS** [comment]
@patniko Hey i wrote an email to your github email adress some time ago. Unfortunately it looks like it has fallen through the cracks. Should i try it again?

**Comment by Zakeelm** [comment]
Hi all, following up on this thread. We're still currently looking into this and doing some of the investigatory work to figure out we can accomplish shared partitions/shared data in App Center Data. We don't have an ETA for this item, but it's something that's definitely on our radar that we would like to bring to the App Center Data feature set. We'll be sharing specs with you as soon as the team has solidified the technical pieces of this.

**Comment by SOliasS** [comment]
#1621 Data is dead
