### ISSUE TITLE
Cannot install iOS app from App Center

### ISSUE THREAD

**Issue by dctoai** [microsoft/appcenter#866]
**What App Center service does this affect?**
Install App from App Center

**Describe the bug**
I have exactly the same behaviour of bug [Cannot install App Center Profile on iPhone XS (iOS 12.3.1)](https://github.com/microsoft/appcenter/issues/615). When I install the application, it is greyed out and cannot open.

**To Reproduce**
1. Log into App Center
2. Add new device
3. Click "Allow"
4. Go to Settings, Profile Downloaded
5. Click "Install"
6. Enter PIN
7. Click "Install"
8. Install application from App Center
9. Application is greyed out and cannot be open.

**Expected behavior**
I expect the application should be opened after installation is finished.

**Screenshots**
![image](https://user-images.githubusercontent.com/11269658/62840727-7f8ba600-bce2-11e9-9bf6-04220fd2576b.png)
![image](https://user-images.githubusercontent.com/11269658/62840733-8f0aef00-bce2-11e9-9dbb-4ad3d4262fcd.png)
![image](https://user-images.githubusercontent.com/11269658/62840737-992ced80-bce2-11e9-8fbb-646c5b1ec1c5.png)
![image](https://user-images.githubusercontent.com/11269658/62840740-a053fb80-bce2-11e9-89fb-fea9f3a6604b.png)
![image](https://user-images.githubusercontent.com/11269658/62840742-a6e27300-bce2-11e9-9c1f-69cdd9721192.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 7, Iphone 7 Plus, iPad pro 10.5, iPhone XS
 - OS: iOS 12.3.1, 12.4
 - Browser: Safari

**Comment by lassecapel** [comment]
Facing the same issue:

- Device: Apple iPhone X
- OS: 12.4
- Browser: Safari (private) and chrome

**Comment by marcos-calis** [comment]
Same issue here with several devices.

**Comment by vjlomocso** [comment]
Same issue. Provisioning profiles added to all tested devices. Not a provisioning problem.

**Comment by turanuk** [comment]
Hey folks we apologize for the inconvenience here.

So we apologize for the inconvenience here. For the time being however, even though the device profile doesn't install, the UDIDs should still be in App Center and from an end to end perspective you should not be blocked. For the actual application you are attempting to distribute, as long as users have started the device registration flow and the device shows up under "devices" in install.appcenter.ms, that means you can extract their UDID and include it in your build, either manually, or via our auto-provisioning feature.

The fact that the device registration flow doesn't finish is confusing and we are looking into it in parallel, but providing this information here to ensure that folks aren't blocked in the meantime.

**Comment by marcos-calis** [comment]
The main issue is that the profile with the certificates is not getting installed.

And the application is not allowed to run .

Many thanks

Marcos

Marcos.

On Aug 13, 2019, at 11:07 AM, Jim Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey folks we apologize for the inconvenience here.

So we apologize for the inconvenience here. For the time being however, even though the device profile doesn't install, the UDIDs should still be in App Center and from an end to end perspective you should not be blocked. For the actual application you are attempting to distribute, as long as users have started the device registration flow and the device shows up under "devices" in install.appcenter.ms, that means you can extract their UDID and include it in your build, either manually, or via our auto-provisioning feature.

The fact that the device registration flow doesn't finish is confusing and we are looking into it in parallel, but providing this information here to ensure that folks aren't blocked in the meantime.

**Comment by turanuk** [comment]
Hey Marcos, let's continue this part of the discussion on the support case that we have open right now. We are investigating both your issue on the support case as well as the broader problem in parallel.

**Comment by davetownsend** [comment]
@turanuk is this a public a support case we can follow?  Our team is facing same issue with all our apps on iOS 12.4.

**Comment by turanuk** [comment]
It is not a public support case given the issue Marcos is experiencing we don't believe is related to this issue. This particular issue is actively being investigated and we will update this GitHub issue once it is resolved.

**Comment by olgv** [comment]
We have the same problem here, using HockeyApp with an Enterprise Apple Dev. account mainly to distribute iOS apps.

In the middle of a deployment phase now we are cut out of this basic function. 
Imagine explaining to the client that the new AppCenter platform we transited from HockeyApp which is supposed to be better does not allow us to deploy the latest update, days before their event.

I can't believe you guys did not test this in all this transition time.

Can you advise on an urgent fix?
Thanks.

**Comment by turanuk** [comment]
Hey @olgv can you open up a support case? We do not believe this impacts enterprise provisioning profiles so would love to get a closer look at your setup. You can let support know to route to "Distribution" and link to this GitHub conversation.

To be clear, this was working and was tested but we are trying to understand why it stopped as nothing changed on our end. As I mentioned previously I would not expect this to affect an Enterprise provisioning profile, so we would love to learn if we are missing something.

**Comment by JohannesNylund** [comment]
Im having the exact same issue also. Testing on Iphone 7 latest ios version.

**Comment by joncodo** [comment]
@turanuk " that means you can extract their UDID and include it in your build, either manually, or via our auto-provisioning feature."

Can you explain how to do this? Or link to a guide?

**Comment by clpolet** [comment]
@joncodo the [Device registration and app re-signing](https://docs.microsoft.com/appcenter/distribution/auto-provisioning) could be the documentation you are looking for.

I feel like there is some confusion in this thread about profiles. The configuration profile used in the device registration flow is not to be confused with the provisioning profile required by your application for distribution.

Also keep in mind that registering the device on Apple and adding it to the application provisioning profile through App Center or not is not enough for a successful installation. The application needs to be [re-signed](https://docs.microsoft.com/en-us/appcenter/distribution/auto-provisioning#what-is-re-signing) with the updated provisioning profile.

Lastly, the failure installing the application on a device is likely to be a provisioning profile / signing issue but the causes are multiple (Provisioning profile and/or certs invalidated/revoked, provisioning profile missing the device...). So it's a case by case, you can have a personalized support 
 by contacting us directly on the portal (blue button; bottom right).

**Comment by Ronaldoh1** [comment]
I'm having the same problem with 12.4

**Comment by Ronaldoh1** [comment]
any updates?

**Comment by botatoes** [comment]
Hi there, we have investigated this issue and found that while the user experience for this is terrible, not installing the profile will not block you from any App Center flows. We have investigated the cases in this issue in private support tickets and found them to not be related. 

Please open up a support ticket on intercom in App Center if you experience this and we will investigate your specific case.

**Comment by dwasyluk** [comment]
Easier to just use TestFlight than to put users through these hoops and terrible UX.

**Comment by ECDev01** [comment]
Any solution for this? My case was something like this: 

1. Previous to iOS 12.4.1 I had issues with my app icons, during installation in progress my icon look like this: 
![IMG_0861](https://user-images.githubusercontent.com/45864586/64929296-cd5a7780-d867-11e9-82c7-68d3c852df41.jpg)
Then when finished my app icon looked like this:
![IMG_0860](https://user-images.githubusercontent.com/45864586/64929322-422db180-d868-11e9-8e00-ad3920fc8e75.jpg)

However the app worked normally, only issues with displaying app icon.

2. After update to iOS 12.4.1 I uninstalled my app and then I installed it again when installation finished the app icon look like this:
![IMG_0870](https://user-images.githubusercontent.com/45864586/64929412-0c3cfd00-d869-11e9-9e7a-7c632aab12d5.jpg)

And the app does NOT open, not working at all.

**Comment by marklanhamhc** [comment]
I have exactly the same issue, my client can download the app but it remains *greyed out*. I've double checked that the *device has been provisioned*, I've installed the latest provisioning profile and rebuilt the app but he still can't open it. I also checked that he has the *App Center Profile* installed — no issues there either.

This is not a great user experience and I have some high profile clients that need to see the beta version of my app and I have to keep making excuses. I never had these issues when it was Hockey App, don't understand why it had to change. Seriously considering just using *TestFlight* and the Closed track testing feature in the *Google Play Console* instead if this doesn't get resolved soon.

**Comment by joncodo** [comment]
@marklanhamhc @ECDev01 I spent so much time trying to fix this issue and discussed it with their devs. the workarounds they gave me did not seem to work. We were forced after a week to switch to testflight. There simply was no way around it. 

I think that a service like this will always have issues with keeping up with compatibility with Apple. Apple releases changes that break code constantly. When this happens, services like this need to update as well and that delay sucks. However, I dont know how they get around it.

**Comment by marklanhamhc** [comment]
Ok thanks for the update @joncodo, it seems we'll have to do the same as we can't afford to wait and there doesn't seem to be any first line support (which we'd happily pay for). Another ruined service from Microsoft.

**Comment by ECDev01** [comment]
> I have exactly the same issue, my client can download the app but it remains _greyed out_. I've double checked that the _device has been provisioned_, I've installed the latest provisioning profile and rebuilt the app but he still can't open it. I also checked that he has the _App Center Profile_ installed — no issues there either.
> 
> This is not a great user experience and I have some high profile clients that need to see the beta version of my app and I have to keep making excuses. I never had these issues when it was Hockey App, don't understand why it had to change. Seriously considering just using _TestFlight_ and the Closed track testing feature in the _Google Play Console_ instead if this doesn't get resolved soon.

Bro, in regards of the "Greyed Out" issue, you know this is because the cert in the provisioning profile is different with the provided to provision the device, is that clear? Well, now you know the problem however you probably have checked your provisioning profile and the cert to provision your client device and you are pretty sure they are the same, I would say it seems they are the same but no man, tragically they are not, at least in my case they were not. I found that in my case was the CSR the cause of this issue, since I had to deploy and also enable push notifications I created 2 certs and both were installed in my mac and becasue both were created using the same CSR the key generated was linked to the latest certificate in my case to the push notifications service (APN). Yup was a big and a stupid mistake. Just have a look in your mac in the keychain access expand your key and see what cert you see there, it should say the name of your distribution cert. 

In regards of the app icon, so far no idea how to fix it.

**Comment by marklanhamhc** [comment]
Hi @ECDev01, thanks for your response, we have since managed to resolve this issue. 

It seems there was a problem with the **iOS Team Provisioning Profile** not being updated. To fix I opened **Xcode** and went to **Preferences**. I then went to **Manage Certificates** and then added a new **Apple Development** and **Apple Distribution** signing certificate (plus sign, bottom left of the drop down). 

I also went to **Library** > **MobileDevice** > **Provisioning Profiles** and **deleted all the iOS Team Provisioning Profiles** then rebuilt my apps. This seemed to regenerate the iOS Team Provisioning Profiles.

One more thing to check as well is in your Apple Developer account, as tis has alos caught me out in the past. Make sure any new devices have been added to the **Device list** (the new iPhone 11 range have a 24 character format rather than  40) then go into **Profiles** and select your **development profile** (if you have one setup already). Next click **Edit** and make sure you have all the correct **Certificates** ticked in the list as well as all the **relevant devices**. Hit **Save** then **Download** and **open/install the certificates** on your machine.

Hope this helps!

**Comment by ECDev01** [comment]
> Hi @ECDev01, thanks for your response, we have since managed to resolve this issue.
> 
> It seems there was a problem with the **iOS Team Provisioning Profile** not being updated. The app Provisioning Profile was showing the new devices however the iOS Team Provisioning Profile wasn't as it was out of date.
> 
> To fix I opened **Xcode** and went to **Preferences**. I then went to **Manage Certificates** and then added a new **Apple Development** and **Apple Distribution** signing certificate (plus sign, bottom left of the drop down).
> 
> I also went to **Library** > **MobileDevice** > **Provisioning Profiles** and **deleted all the iOS Team Provisioning Profiles** then rebuilt my apps (we are using Nativescript and Angular). This seemed to regenerate the iOS Team Provisioning Profiles.
> 
> One more thing to check as well is in your Apple Developer account, as this has also caught me out in the past. Make sure any new devices have been added to the **Device list** (the new iPhone 11 range have a 24 character format rather than 40) then go into **Profiles** and select your **development profile** (if you have one setup already). Next click **Edit** and make sure you have all the correct **Certificates** ticked in the list as well as all the **relevant devices**. Hit **Save** then **Download** and **open/install the certificates** on your machine.
> 
> Hope this helps!

Great you fixed it! Good to know this as well, thanks.

**Comment by chandu612** [comment]
SOLVED! We had the same issue. By selecting "Private" browsing in safari did the trick. Also most importantly, on AppCenter when it says "Add Device" select "I'm good".
After that we are able to install our apps.

**Comment by AndrewSpiteri-FS** [comment]
We still have the same issue. It works on versions of IPhone below X. On iPhone X and X Pro it does show the install progress icon. Once it almost completes, it exists and if you try to click on the icon it says "Unable to install, Please try again later". 

We have tried all advice above with no success.

**Comment by SMJ93** [comment]
I am getting the same problem on the iPhone 11 Pro too

**Comment by oleksandryevdokymov** [comment]
I have the same issue with iPhone 11. I added UDID into provisioning profiles. But a have problems with installation like this:
![i'm good](https://user-images.githubusercontent.com/24473400/74742714-bfba7b00-5267-11ea-96e3-c362d1d5dfc0.jpg)
![not able ](https://user-images.githubusercontent.com/24473400/74742736-c943e300-5267-11ea-93d5-700ea70b91a3.jpg)
![nable to install](https://user-images.githubusercontent.com/24473400/74742743-ccd76a00-5267-11ea-9151-6e0e106cdde9.jpg)

**Comment by SMJ93** [comment]
Looking at the device UUID's here: https://developer.apple.com/account/resources/devices/list

It looks like apple have a new format for the iPhone 11?

iPhone X: `a6fd4c7a76a564ef9a62b9292f8b91a5c0fb1111`
iPhone 11 Pro: `11118529-000D01362A33803D`

Might be causing the issue?

**Comment by oleksandryevdokymov** [comment]
@SMJ93 Yes I double checked and I added new format with 24 symbols and "-" like in your iPhone 11 Pro.

**Comment by raghuramratan** [comment]
Any solution, I am facing the same error. App installs, greys out and on trying to launch it, it says "Unable to install app, please try again later"

**Comment by ahdbilal** [comment]
@oleksandryevdokymov Did the new format solve the issue?

**Comment by oleksandryevdokymov** [comment]
@ahdbilal new format is already chosen. And with new format UDID issue reproduces.

**Comment by SMJ93** [comment]
Looks like it was a cache issue for me. I cleared all history/cookies on my iPhone and it started working!

**Comment by raghuramratan** [comment]
This issue is resolved for me, the problem was that, the provisioning profile was not having the UDID of the device that I was trying to install the app.

**Comment by SaurabhBisht** [comment]
I face the same issue..Any updates ?

**Comment by SaurabhBisht** [comment]
SOLVED:
 I checked the logs in device console and there it was showing provisioning  profile expired but the profile had'nt, but anyways we created a new build, uploaded to App Center again and downloaded and it started  working :)

**Comment by SkogenSturla** [comment]
I have also a problem with installing ios app from App Center. The downloading seem ok. I can see the .ipa file in Files.
The blue dot appears beside the app logo but there is no installation of the new file. On the installation page I get this message "App Center requires JavaScript" I have enabled the JavaScript in the browser, but nothing happens.
