### ISSUE TITLE
show in the Push tab if we've linked with OneSignal 

### ISSUE THREAD

**Issue by SogoGolf** [microsoft/appcenter#867]
We're using OneSignal for the time being for push. Would be great if you could reference this in the Push tab UI somewhere and redirect us to the linked OneSignal account. Similar to the redirect you provide to (for example) Application Insights.

**Comment by amchew** [comment]
Thanks @sogogolf for the request! @jwargo would you mind taking a look please?

**Comment by jwargo** [comment]
@SogoGolf that's an interesting suggestion, we don't actually do any integration with OneSignal except for that redirect you already saw, so we have no way of knowing that you have OneSignal configured. I'll file this as a feature request as we see what we do next here.

**Comment by jwargo** [comment]
@SogoGolf would you be willing to have an email conversation or chat about how you use push in your app(s)

**Comment by SogoGolf** [comment]
Hi John, yes of course would love to help. Call would probably be best/most efficient.
