### ISSUE TITLE
Customize distribution for App Store

### ISSUE THREAD

**Issue by mihaierosx2** [microsoft/appcenter#868]
### **Description**

Is there any way I can customize the distribution of a build to App Store?

For example I would like to set 'Manual release this version', at the moment I see that by default AppCenter will use 'Automatically release this version', is there any way I can achieve this? 

My bet would be that I can use something like this:

```
 add_id_info_uses_idfa: false
 export_compliance_uses_encryption: false
 export_compliance_encryption_updated: false
```

From [here](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple).

Any help or guidance would be much appreciated!

**Comment by Frans-L** [comment]
@mihaierosx2 
Have you found any solution for this? :)

**Comment by mihaierosx2** [comment]
@Frans-L No solution at the moment. 

As a workaround you could configure the 'release' branch to distribute the build  to App Store Connect Users (TestFlight), not Production (App  Store), and from there you have to do it manually, but at least it won't go rogue by itself and submit the build with automatically release and the entered release notes - which I would love to customize per build, not per branch 🙄.

Many of these options could be done already, Fastlane suppors many of them right now, I have no idea why these are not working 😞.

**Comment by Frans-L** [comment]
Thanks @mihaierosx2 :)
