### ISSUE TITLE
Why suddenly getting Expired Channel?

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#872]
Hi,

Why suddenly I am getting Expired Channel when trying to send Push messages and none of the device received my message?

Why do i need to re-issue the token everytime?

If the user has the Push notifications enabled on his device for long time without any changes then he should be able to continue receiving it without any issue?

Thanks,
[Jassim](https://www.zeera.online)

**Comment by jwargo** [comment]
@jrahma as we've explained before, please use App Center support to resolve issues using App Center. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

We're happy to address bugs, but only after you've worked with the support team to validate that it is actually a bug. The reasons for this error are documented in our [docs](https://docs.microsoft.com/en-us/appcenter/push/troubleshooting#bad-channel), have you worked through the guidelines there to help you resolve your issue?
