### ISSUE TITLE
Swift macOS app fatalError() results in EXC_BAD_INSTRUCTION?

### ISSUE THREAD

**Issue by dwmatteson** [microsoft/appcenter#873]
**What App Center service does this affect?**
AppCenterCrashes

**Describe the bug**
Whenever I call fatalError() in my macOS Swift app I get an EXC_BAD_INSTRUCTION in the debugger. Running it outside of XCode I just get a Diagnostic log on the machine, but no crash report in App Center

**To Reproduce**
1. Create a Swift App and add the App Center framework
2. Call fatalError("...")
3. See the debugger give you EXC_BAD_INSTRUCTION on that line

**Expected behavior**
Expecting a crash with a crash report sent to App Center

**Screenshots**

**Desktop (please complete the following information):**
 - macOS
 - 10.14.6

**Additional context**
Calling MSAnalytics works normally and I can track custom events, so in general the framework seems to be working. But fatalError() doesn't result in a crash report?

**Comment by dwmatteson** [comment]
Nevermind got it working! Sorry for the false report, feel free to delete.

**Comment by markst** [comment]
@dwmatteson care to share how?
