### ISSUE TITLE
Unify the use of "Release" within appcenter

### ISSUE THREAD

**Issue by goiditdev** [microsoft/appcenter#874]
**Describe the solution you'd like**
Currently, and confirmed after a chat with appcenter support, the "Latest Release" version shown for an app is based solely on the list of releases that were pushed to distribution groups through appcenter. If an app is built using appcenter and pushed to a store for distribution (testflight or google play beta) without going to a distribution group, then those are not considered as a release version, which seems inconsistent, since appcenter lists all builds as "Releases" under "Distribute", independent of the channels for distribution.
What I would like to suggest is to improve that. Ideally, appcenter could query the app stores to see which were actually released to which channel and then listing multiple types under Latest Release on the app overview page (latest build, latest push to testflight, etc.).

**Describe alternatives you've considered**
Alternatives to that could be renaming releases to builds, or just checking the public release version of the app through the app stores to check what is public, or some other approach that is more consistent across appcenter.

**Additional context**
n/a

**Comment by botatoes** [comment]
Thanks for the suggestion. We are working on future improvements to the App Center stores experience and will keep this in mind as a fix when we touch the codebase.
