### ISSUE TITLE
Request to support fastlane match

### ISSUE THREAD

**Issue by jozan** [microsoft/appcenter#875]
**Describe the solution you'd like**
`fastlane match` is a tool to fully automate handling of provisioning profiles and signing keys in iOS projects (works also in React Native projects). I'd imagine that having a section in build settings to set up git repo url etc or detecting `fastlane/Matchfile` in project directory could work.

**Describe alternatives you've considered**
Currently workaround is to custom build scripts to handle code signing manually.

**Additional context**
May be useful for teams migrating from local build systems using fastlane or other CI-solutions to App Center. This could also be the first step to get first class support for fastlane. Related issue #83.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @jozan! We'll keep this open as potential future feature. Do you have a custom build script working for this? We have a [folder](https://github.com/microsoft/appcenter/tree/master/sample-build-scripts) with several build script examples for others to use if you'd be interested in sharing what you've got!

**Comment by skaldo** [comment]
I managed to retrieve the certificate and provisioning profile in the post clone script, but could not find a way how to use them in the signing process.
Theoretically, it would be possible to run `/Users/runner/runners/2.163.1/scripts/build-xcproject-analyzer/node_modules/@build/xcproject-analyzer-script/script/bin.js` with the correct params.
But it is not possible to control the installed version of this script (breaking changes).
Another issue would be that it is not possible to run a script directly before the xcbuild.

Anybody succeeded?
@nrajpurkar does your team plan to support fastlane match (give user a way to define signing configuration programatically)?

**Comment by ricsantos** [comment]
Jumping in here with a 'me too' as I'd really like to get setup with App Centre with my iOS project(s), and as I use `fastlane match` for code signing, adding support for this is a requirement as once you get used to `match` there really is no desire to manually configure profiles and certificates.

**Comment by smalomo** [comment]
One more "me too" for this request - using fastlane match to manage certificates and profiles via a private repo but looking to use App Center for the build.

**Comment by almo-ltoeroek** [comment]
us too

**Comment by bschory** [comment]
same here, we want to use match for certs/profiles but build in app center

**Comment by ferdicus** [comment]
sorry to be that person in 2021, but is there any movement concerning this?

**Comment by AndreasBoehm** [comment]
I would really like to see that feature in appcenter

**Comment by ferdicus** [comment]
@nilofer, is there any update on this that you could share with us?

**Comment by ferdicus** [comment]
> @ferdicus, apologies as I no longer work on App Center. @wham do you know where to route this?

Oh, sorry and congrats - so @wham is the person to bug now :)

**Comment by ferdicus** [comment]
Maybe @wham is also no longer responsible?  
Is this an exercise of screaming into the void?

**Comment by ferdicus** [comment]
*sigh*

**Comment by sbycrosz** [comment]
In case anyone is here, we made a [fastlane script](https://gist.github.com/sbycrosz/e15aff82a6500d2e8aaf10714a486d76) to export fastlane match into p12/mobileprovision file to be used in AppCenter 🎉
