### ISSUE TITLE
Incompatibilities with WPF projects that already reference an SQLite library

### ISSUE THREAD

**Issue by chrisforte** [microsoft/appcenter#876]
**Setup:**
New WPF .Net Framework 4.7 project, created in VS 2019. Following the App Center SDK setup instructions [here](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms).

**Repro Steps**
In a new, blank project, I have no issues following the setup and connection with the App Center SDK; everything works as expected. 

I have an existing WPF project that references several libraries and nuget packages, including the System.Data.SQLite nuget package and dependencies (package [here](https://www.nuget.org/packages/System.Data.SQLite)). On this existing project, I get the following error at runtime:

`2019-08-13 11:04:03.685 [AppCenter] ERROR: An error occurred while initializing storage `
`System.MissingMethodException: Method not found: 'System.String SQLitePCL.raw.sqlite3_column_name(SQLitePCL.sqlite3_stmt, Int32)'.`
   `at SQLite.SQLite3.ColumnName16(sqlite3_stmt stmt, Int32 index)`
   `at SQLite.SQLiteCommand.<ExecuteDeferredQuery>c__Iterator01.MoveNext()`
   `at System.Collections.Generic.List1..ctor(IEnumerable1 collection)`
   `at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)`
   `at SQLite.SQLiteConnection.GetTableInfo(String tableName)`
   `at SQLite.SQLiteConnection.MigrateTable(TableMapping map)`
   `at SQLite.SQLiteConnection.CreateTable(Type ty, CreateFlags createFlags)`
   `at SQLite.SQLiteAsyncConnection.<CreateTablesAsync>c__AnonStorey0.<>m__0()`
   `at System.Threading.Tasks.Task1.InnerInvoke()`
   `at System.Threading.Tasks.Task.Execute()`
`--- End of stack trace from previous location where exception was thrown ---`
`   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(`)
`   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)`
`   at Microsoft.AppCenter.Storage.StorageAdapter.<CreateTableAsync>d__41.MoveNext()`
`--- End of stack trace from previous location where exception was thrown ---`
`   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`
`   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)`
`   at Microsoft.AppCenter.Storage.Storage.<InitializeDatabaseAsync>d__19.MoveNext() `

It seems that the App Center libraries are looking for specific methods and functions from their own dependency libraries (sqlite-net-pcl), which is causing issues when another library with similarly named methods and classes is present.

**Comment by winnieli1208** [comment]
Hi @chrisforte - can you start a support ticket via the blue chat bubble on the bottom left or from the question mark icon on the top right in App Center? Our support team can help you out there. 

Thanks!

**Comment by amartens181** [comment]
@chrisforte did you figure out the problem? This is still happening in 2.4.0-preview.

**Comment by wedol** [comment]
Same for me. I am using EF Core 3.0 with sqlite provider (witch uses SQLitePCLRaw.bundle_e_sqlite3 (2.0.0)) and AppCenter crashing on  
`[AppCenter] ERROR: An error occurred while initializing storage
System.MissingMethodException: Method not found: 'System.String SQLitePCL.raw.sqlite3_column_name(SQLitePCL.sqlite3_stmt, Int32)'.`

With this sqlite dll hell give us a way to change default storage used in AppCenter.

**Comment by chrisforte** [comment]
> @chrisforte did you figure out the problem? This is still happening in 2.4.0-preview.

I submitted this through AppCenter support as well, hopefully they'll look into it. In the mean time, here's how I've been getting around this issue:

On projects that have a pre-existing dependency on SQLite (`System.Data.SQLite`), use the Nuget PowerShell command line to install the AppCenter packages and dependencies with the following commands (in this order):
`Install-Package Microsoft.AppCenter.Analytics -Version 2.2.1-preview -IgnoreDependencies`
`Install-Package Microsoft.AppCenter.Crashes -Version 2.2.1-preview -IgnoreDependencies`
`Install-Package Microsoft.AppCenter -Version 2.2.1-preview -IgnoreDependencies`
`Install-Package sqlite-net-pcl -IgnoreDependencies`
`Install-Package sqlitepclraw.bundle_green -Version 1.1.14`
(changing the AppCenter package versions to the most recent, in this case `2.4.0-preview`). This has been working for me so far.

**Comment by wedol** [comment]
@chrisforte This workaround not working for me. Maybe because EF core uses SQLitePCLRaw.bundle_e_sqlite3

**Comment by EatonZ** [comment]
Any updates on this? I am getting this after upgrading to 2.5.0.
I removed all NuGet packages and redownloaded AppCenter with non-prerelease DLLs and now this has started happening.

**Comment by EatonZ** [comment]
I fixed it by installing the beta/prerelease version of sqlite-net-pcl in my project.

**Comment by ranjan-ranjan** [comment]
I am experiencing this in WPF application
I am using latest NuGet packages
This is a bug

**Comment by EatonZ** [comment]
@ranjan-ranjan Check "Include prerelease" when updating your NuGet packages and update to the latest sqlite-net-pcl.

![2019-11-25_14-05-44](https://user-images.githubusercontent.com/3020941/69569951-c00ae900-0f8c-11ea-9131-ecbc140ec832.png)

**Comment by Jamminroot** [comment]
Hey guys, an update for folks who's facing this and looking at this page: this issue was addressed in release 3.0.0 of App Center SDK for DotNet.
