### ISSUE TITLE
Allow reporting custom errors

### ISSUE THREAD

**Issue by liortal53** [microsoft/appcenter#88]
Originally reported as this ticket: https://github.com/Microsoft/AppCenter-SDK-Unity/issues/220

In our apps, we log different types of "errors":

- Crashes - these are errors that cause the game to crash (exit). With Unity this usually means native stuff that throws an unhandled exception (e.g: on Android, some null reference exception at the Java level), since a NRE in Unity will not cause the app to crash.

- Unhandled or handled exceptions - an actual Exception object that is thrown and we report (e.g: inside the Catch clause)

- Custom errors - this can be anything basically, for example - some sort of argument validation that fails and we'd like to log as an error to keep track of. Also, with Unity it's easy to set up a "global" error reporter by hooking to the Application.logMessageReceived. This will get called whenever a new message is logged (for example - an error or an exception). In this case, however, we do not get the actual Exception object so we cannot report this using the current APIs.

The 2nd and 3rd options are what i am looking for: i do not have an Exception object, but i would still like to report the error to AppCenter.

**Comment by pratyushnigam** [comment]
Is this feature present in the backlog ?
