### ISSUE TITLE
MACOS Xamarin (C#) Analytics. 

### ISSUE THREAD

**Issue by NawazSyed** [microsoft/appcenter#880]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hamswan** [comment]
Hi @NawazSyed  Can you add some details on your use case?

**Comment by scriptam** [comment]
@hamswan I think this is a duplicate of issue [#143](https://github.com/microsoft/appcenter/issues/143) - Xamarin.Mac Support

Looks similar to wanting App Center Analytics SDK work with Xamarin.Mac applications.
https://github.com/microsoft/appcenter-sdk-dotnet/issues/529

Currently you can add the App Center NuGet packages for a Xamarin.Mac project and the solution will compile however no events or crashes are tracked, they will be silently ignored. You will however get a warning that the platform is unsupported in logs at `AppCenter.Start` method.

@NawazSyed you may want to check @elamalani's reply on the related issue:
https://github.com/microsoft/appcenter-sdk-dotnet/issues/615#issuecomment-436347378

And check the status of the Mac support on the [roadmap](https://docs.microsoft.com/en-us/appcenter/general/roadmap)

Alternatively, @apparentvisuals made a fork of the App Center SDK for .NET platforms 2 years ago and did the bindings for Xamarin Mac on this repo:
https://github.com/apparentvisuals/AppCenter-SDK-DotNet.git

If that works for you, you may want to encourage a pull request to merge back to source.

Last but not least, ensure you vote for the issue on [iterations plans](https://github.com/Microsoft/appcenter/wiki/Iteration-plans)

**Comment by Suplanus** [comment]
Please don't close this issue, bot 🤖

**Comment by Suplanus** [comment]
Bump
