### ISSUE TITLE
Need option to specify -destination option in xcodebuild command in Build step

### ISSUE THREAD

**Issue by szuchunhung** [microsoft/appcenter#881]
**Describe the solution you'd like**
We are trying to use AppCenter build to build and test against an iPad app. However, it looks like the default xcodebuild command specified the option "-destination platform=iOS Simulator,name=iPhone 6", which would use iPhone 6 as the simulator to run the tests on. The app is designed for iPads, but if I specify "Targeted Device Family" to iPads in my project and target, the build still use the same xcodebuild command and would return an error "Unable to find a destination matching the provided destination specifier:
{ platform:iOS Simulator, OS:latest, name:iPhone 6 }"
Could we add ways to customize the xcodebuild options?

**Describe alternatives you've considered**
We've tried using pre-build and post-build scripts to run UI tests, but it doesn't seemed to affect the build output. Unsure if that should be expected as there's no logs of the script executing.

**Additional context**
N/A

**Comment by DrBeak1** [comment]
+1 @patniko this is a real pain point for my team right now. Our app is a kiosk style application and our builds fail due to the device being an iPhone and not an iPad.

**Comment by amchew** [comment]
Thanks @szuchunhung and @DrBeak1 for the request! This is currently not on our backlog, but I see your use case. I'll let @nrajpurkar share more details.

**Comment by DennisPan** [comment]
Thanks for the input. We are looking into this. We've received feedback on different needs on `destination` or `sdk`. Will investigate if this is something we can determine better in the repository analysis

**Comment by DennisPan** [comment]
@piotrpoz We looked at this. Current thought is to use `DeviceFamily` in project setting to determine the destination. Let us know if this sounds reasonable.

**Comment by piotrpoz** [comment]
@DennisPan Thanks for the reply. Please have a look at the attached screenshot. If this is `DeviceFamily` setting you've mentioned, then it does not change the bahaviour. It still complains about 'My Mac'. It has been set this way already when posting my first comment.

![Screenshot 2019-10-22 at 12 34 39](https://user-images.githubusercontent.com/5487682/67278204-cf4bd200-f4c8-11e9-8d9a-ca6aecdee546.png)

**Comment by DennisPan** [comment]
@piotrpoz We haven't made the change yet (adding `-destination` to `xcodebuild` command). Was reaching out if we set destination to what matches device family will work for your case.

**Comment by piotrpoz** [comment]
@DennisPan Hi Dennis, sorry for my late reply! I did not follow with all these github notifications, my apologies. 

It might work, but I cannot really tell for sure (need to test it first). 
There was an update of XCode (11.3), however it fails to build the app in th same manner as 11.2.

**Comment by AaronTunney** [comment]
I'm having the same issue: our app is iPad-only but App Center is trying to compile it to run on an iPhone 11 simulator.

My device family was automatically set to "iPad" by Xcode so hopefully your proposed fix will work @DennisPan .

**Comment by King-of-Spades** [comment]
Potentially related to #570. They might even be duplicates of each other, but I'm not 100% sure.

**Comment by shadone** [comment]
It is ridiculous if one cannot specify which destination to run. We develop an iPhone app but our tests are expected to be run on a certain simulator - only on "iPhone 11 Pro" simulator running iOS 13 - as we do snapshot tests and that is device specific.

It is a basic need for many projects and should be configurable by the developer as it's done on all other CI systems

**Comment by King-of-Spades** [comment]
@shadone One possibility to consider is App Center Test, because it allows you to select devices you execute on (except for launch testing which automatically selects a device): https://docs.microsoft.com/en-us/appcenter/build/build-test-integration

Though one key difference is App Center Test uses physical iOS devices rather than simulators. There are some other things to be aware of that are covered in the doc (I'm the main author of it); but I wanted to highlight that since iOS device & simulator builds aren't cross-compatible.
