### ISSUE TITLE
apps won't open when released to "All-users-of-xxxx" group

### ISSUE THREAD

**Issue by markghayden** [microsoft/appcenter#882]
**What App Center service does this affect?**

Problem with distributing IOS apps.

**Describe the bug**

I am trying to release an app to the 'All-users-of-xxxx' distribution group.  Everything works except when installing the app, the app is left grayed out and won't run.  The exact same app on same device works if I release an app to the 'Collaborators' distribution group.  What is different?

**To Reproduce**

Distribute an app to 'Collaborators' group.
Install on device.
Works correctly

Update version number.
Distribute an app to the 'All-users-of-xxxx' group.
Install on device.
App is greyed out and won't run.

**Expected behavior**

**Screenshots**

NA

**Desktop (please complete the following information):**

MacOS 10.14.6

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 12.4

**Additional context**

NA

**Comment by derpixeldan** [comment]
@markghayden please reach out to us in support so we can better investigate the problem.

**Comment by derpixeldan** [comment]
Note: Probably related to https://github.com/microsoft/appcenter/issues/866 even though the issue description is wrong. The ultimate problem is that users can't download the releases.

@markghayden have you reached out to us in support already and if yes, can you please mention the url of this ticket?

**Comment by derpixeldan** [comment]
Please reach out in support when the issue still occurs.
