### ISSUE TITLE
Custom GIT server

### ISSUE THREAD

**Issue by zek** [microsoft/appcenter#883]
We use a custom gitlab server. Is it possible to use gitlab.company.com as git provider?

**Comment by amchew** [comment]
Thanks @zek for your quesiton! @nrajpurkar would you mind taking a look please?

**Comment by nrajpurkar** [comment]
@zek we're actually tracking this work in #37 and are [inviting](https://github.com/microsoft/appcenter/issues/37#issuecomment-526398616) people to try out the early preview of this.

Closing this out as a duplicate.
