### ISSUE TITLE
Extract symbols from .so files

### ISSUE THREAD

**Issue by m-yukio** [microsoft/appcenter#884]
**Describe the solution you'd like**
A function to extract symbols on the AppCenter side when the obj directory generated when building Android is compressed and uploaded.

**Describe alternatives you've considered**
I tried to build and generate dump_syms command from Google Breakpad repository.
In macOS used for development and CI, dump_syms command that supports only Mach-o was generated, and it was difficult to generate commands that supported Android ELF.

**Additional context**
I was migrating from HockeyApp and HockeyApp had this feature.

**Comment by winnieli1208** [comment]
Thanks for the request! Right now, we only support extracting symbol files if you use App Center build and distribute. We don't have any immediate plans to change this but I'll monitor this thread for support and post here with any updates. Thanks!

**Comment by m-yukio** [comment]
Hi,
My name is Yukio Murakami.

Thank you for your reply.
Future trends will be monitored!

**Comment by winnieli1** [comment]
Hi @m-yukio - we just enabled support for this. You can find the docs here: https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk#generate-a-zip-file-to-upload

Give it a try and let me know if you run into any issues.
