### ISSUE TITLE
Ability to run .NET code as part of pre or post build task

### ISSUE THREAD

**Issue by knightmeister** [microsoft/appcenter#885]
**Describe the solution you'd like**
As I understand it at present, pre & post build scripts need to be Bash or Powershell (iOS & Android, UWP respectively). It would be great if we could also run .NET Core .dlls or maybe even .NET .exes during this process.

**Describe alternatives you've considered**
I can do this at present with Azure DevOps with the build pipelines. It would be great to do it directly from App Center.

**Comment by DennisPan** [comment]
@knightmeister Which task in Azure DevOps do you use?

**Comment by knightmeister** [comment]
@DennisPan I'm in the process of setting it up, but it's right there in the tasks list at the top:

![image](https://user-images.githubusercontent.com/1528425/62997205-d512af00-beaa-11e9-87f1-d36836ab8263.png)

**Comment by DennisPan** [comment]
@knightmeister I assume that's using the .NET Core CLI? Have you tried running `dotnet` in pre $ post build scripts?
