### ISSUE TITLE
Submitting MacOS app releases

### ISSUE THREAD

**Issue by markghayden** [microsoft/appcenter#886]
**What App Center service does this affect?**

Distributing apps for MacOS

**Describe the bug**

Unable to submit a MacOS release to AppCenter

App Center Add Release for MacOS Beta apps says to submit a .app.zip file.  We have been submitting MacOS apps in .pkg files to HockeyApp and Apple MacOS app store for years. 

The App Center documentation says that we can find .app.zip file in our Xcode-generated Archive.  We don't use Xcode for packaging our archives.  However, when we create a simple MacOS app in Xcode and archive it, we don't find a .app.zip file.

We tried zip'ing the .pkg file in an .app.zip file but this does not work.

What is the supported format for AppCenter for MacOS apps?  Why are .pkg files not accepted as before with HockeyApp?  Why does the AppCenter documentation for MacOS refer to .app.zip file that is not present in Xcode archives?

**To Reproduce**

Go to MacOS app
Press Add Release
Select a .pkg file

**Expected behavior**

A new release should have been added

**Screenshots**

NA

**Desktop (please complete the following information):**

 - OS: MacOS 10.14.6
 - Browser: Safari
 - Version: 12.1.2

**Smartphone (please complete the following information):**

NA

**Additional context**

NA

**Comment by derpixeldan** [comment]
@markghayden we're aware of this and looking into supporting .dmg and .pkg soon. I'll keep you posted.

**Comment by markghayden** [comment]
It would be helpful if you could document this so that people are not left wondering whether it is or isn't supported.  Also, it seems like an unnecessary use of our time make a transition to AppCenter (with warnings that HockeyApp is going to be closed in 100 days) when AppCenter is half-done.  Ie, doesn't support the standard MacOS package formats.

**Comment by derpixeldan** [comment]
@markghayden I agree and I apologize. Currently a lot of things are running in parallel and in this case it didn't end up being done around the same time. Now that the horse has bolted we're focusing to support it on App Center.

**Comment by derpixeldan** [comment]
Both .dmg and .pkg are now supported.

**Comment by tu-trankilo** [comment]
> @derpixeldan
