### ISSUE TITLE
Can not set up Azure Dev Ops as bug tracker (automatically transferred HockeyApp account)

### ISSUE THREAD

**Issue by brcinho** [microsoft/appcenter#888]
For both my colleague and me, we can not hook Azure Dev Ops as bug tracker service for Android project
We are both admins of the app in AppCenter
I am admin of the project on Azure Dev Ops, he is admin of the whole organization in Azure Dev Ops, so the issue shouldn't be there even if we receive error that we don't have permissions
Maybe the issue lies in the fact that our accounts initially existed on HockeyApp, and we used HockeyApp login there, while to Azure Dev Ops and App Center we log in with organization Azure AD
Even if the AppCenter gives us ability to login with Azure AD account SSO, maybe it still treats it as HockeyApp account and that is why we don't have sufficient permissions (we see that it says HockeyApp account in profile in AppCenter)

**Comment by brcinho** [comment]
We used steps from https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/

**Comment by brcinho** [comment]
I succeed to list the projects and when I get to final step to click "Add" I get the user 'XXXXXXXX-7a39-61c3-b81c-XXXXXXX' is not authorized to access this resource.

**Comment by winnieli1208** [comment]
Hey @brcinho - have you moved your HockeyApp apps to App Center? There are some settings that can't be managed or changed in App Center until you officially migrate your apps over: https://docs.microsoft.com/en-us/appcenter/transition/moving/

Let me know if that works!

**Comment by brcinho** [comment]
That app wasn't transferred from HockeyApp, it was newly created in AppCenter, the user account on the other hand was transferred and that is what could be causing the issue. Can someone from your support team flag the account as Azure AD account in AppCenter (instead of being marked as HockeyApp account) even if I loose the links in AppCenter to things in HockeyApp.

We will not use "Transfer app" feature in AppCenter because we have enterprise clients which have very slow pace of moving to newer version of apps. We already created all new apps in AppCenter for our needs.

**Comment by derpixeldan** [comment]
@brcinho whether your account originates from HockeyApp or not has nothing to do with Azure DevOps. It simply is a flag that shows or hides certain functionality from the UI. However, your problem is not connected to your account but to the app level.

Please reach out to us in support so we can better investigate the issue.

**Comment by brcinho** [comment]
Hi @derpixeldan Where to reach you in support? I already utilized the chat button in AppCenter to report this issue and currently am participating in one thread with support. Is that what you meant?

**Comment by derpixeldan** [comment]
@brcinho yes, that's what I meant. I found your ticket and will follow up there.

**Comment by derpixeldan** [comment]
Closing as it was addressed via support.
