### ISSUE TITLE
Custom date range selection in analytics

### ISSUE THREAD

**Issue by onasipim** [microsoft/appcenter#889]
**Describe the solution you'd like**
Select custom date range from a calendar popup to be used in the analytics overview and events view. For example it should be possible to select a from and a to date, so that users can make a selection for the past three days, or the past two weeks, or all available data.

**Comment by hamswan** [comment]
@onasipim Thanks for reaching to us. The Analytics Overview on Appcenter has a basic view. If you export the Analytics data to Application Insights, you can also run your own custom query and have a wider range of options for analysis.
Refer to our documentation for export -
https://docs.microsoft.com/en-us/appcenter/analytics/export

**Comment by Brosten** [comment]
+1 from me for this request. In case it's tricky with a free range I personally mostly miss just looking one day back. Currently 7 Days is minimum. Looking one day back would make it easier to see how meny of my users are on the latest version of the app.

**Comment by hibob224** [comment]
+1, having at least a last 24 hour option would be very helpful when rolling out new app versions
