### ISSUE TITLE
Cordova app build support in app center

### ISSUE THREAD

**Issue by bkali** [microsoft/appcenter#890]
**Describe the solution you'd like**
It will be great if we can build cordova apps online at app center. Ideally we should be able to upload a zip file using command line and trigger the builds to generate builds targeting iOS, Android and Windows mobile platforms.

**Describe alternatives you've considered**
 https://build.phonegap.com/ has a similar service that breaks frequently and it lacks professional support.

**Additional context**
We have started using App Center for distributing the developer/QA versions of our Cordova app on iOS and Android. We have also tried the Codepush and like it so far. It would be great if we can move more of the build operations to App Center to make this our central dev-ops service for the hybrid apps.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @bkali! We'll keep this open to track the future interest.

**Comment by nghiacc** [comment]
I have a couple of products developed on Ionic/Angular/Cordova and is using AppCenter for distribution and Jenkins to build. It would be great if AppCenter support build for Cordova apps so that I can move the build services to AppCenter.

**Comment by andysousa** [comment]
i will second this, would be nice to use AppCenter for all its features.  Right now its just a distribution platform for all our ionic apps

**Comment by Perh0rd** [comment]
Yes it will be definitily be helpful, will centralise everything and avoid us to use third parti software.

**Comment by adupo** [comment]
This would be great for my organization as well. Any update on Cordova build support in App Center timeline?

**Comment by EenPOOL** [comment]
As the pipeline Cordov Build in DevOps is no longer maintained, I was hoping that the AppCenter would take over this role. 
We are really searching for a nice and easy way to build mobile hybrid applications (read as: continous integration)

Any timeline about the Cordova build functionality in AppCenter? (or DevOps, I'm fine with both) 😊

**Comment by nrajpurkar** [comment]
No update at this time for Cordova build support in App Center, but we'll continue to monitor this feature request!

**Comment by Taxi4you** [comment]
Agree that can be great

**Comment by rikoz** [comment]
Any updates on this feature?.. I would appreciate if this can be added soon enough.

**Comment by LambyPants** [comment]
Our organization is also interested in this

**Comment by rahulinaction** [comment]
Yes would appreciate the addition of this feature as our app is built using IONIC

**Comment by tushar28** [comment]
yes there is demand in market for cordova/ IONIC based application. It will be good to have the build feature unlike other platforms in Appcenter.

**Comment by rahulinaction** [comment]
Are we going to have support for it anytime soon. Might need to pivot to another platform.

**Comment by damsorian** [comment]
Does anyone know of any alternative to AppCenter to support cordova builds? It is seen that there is no news here

**Comment by robertoandrade** [comment]
I personally use Azure DevOps to build my ionic apps now so would think one
would have no trouble building native cordova apps either. Using Azures
free offering Im able to build both iOS and Android versions and push to
the respective app stores as well as AppCenter for internal
distribution/testing.

**Comment by dotNetkow** [comment]
Hi everyone, Matt from Ionic here. Microsoft recently announced that they are discontinuing support for Cordova. If you are still supporting Cordova apps, check out Ionic's [Appflow](https://ionic.io/appflow) service. It supports Cordova apps (and Capacitor apps, a modern native runtime tool that is 99% backward compatible with Cordova) and includes native iOS and Android builds in the cloud as well as a CodePush alternative (called Live Updates). Learn more in [this blog post](https://ionicframework.com/blog/moving-from-microsoft-app-center-to-ionic-appflow/) and check out our [migration guide](https://ionic.io/docs/appflow/cookbook/appcenter-migration). Cheers.
