### ISSUE TITLE
Error: Cannot prepare UI Test artifacts using command: mono (Android Studio)

### ISSUE THREAD

**Issue by aminpinjari** [microsoft/appcenter#891]
I have imported project into App Center,
When I try to build with normal process it builds successfully,

But whenever I tried to build with "Test on a real deviceFree"
Build fails with below error

[Preparing tests... failed.
Error: Cannot prepare UI Test artifacts using command: mono /Users/vsts/agent/2.155.1/work/1/a/GeneratedTest/packages/Xamarin.UITest.3.0.3/tools/test-cloud.exe prepare "/Users/vsts/agent/2.155.1/work/1/a/build/app-release.apk" --assembly-dir "/Users/vsts/agent/2.155.1/work/1/a/GeneratedTest/AppCenter.UITest.Android/bin/Release" --artifacts-dir "/Users/vsts/agent/2.155.1/work/1/a/Artifacts".

There was an unknown error preparing test artifacts, please try again. If you can't work out how to fix this issue, please contact support.
##[error]Error: /usr/local/bin/appcenter failed with return code: 3](url)

**Comment by Oddj0b** [comment]
You're seeing this issue in App Center Build or what exactly do you mean by importing the project into App Center?
Looking at the error it looks like you're using the old test-cloud.exe cli `/Users/vsts/agent/2.155.1/work/1/a/GeneratedTest/packages/Xamarin.UITest.3.0.3/tools/test-cloud.ex` Can you try and use the App Center CLI? [Read here how to install the App Center CLI](https://docs.microsoft.com/en-gb/appcenter/cli/index)

**Comment by zyead** [comment]
.

الحصول على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: no-response[bot] <notifications@github.com>
‏‏تم الإرسال: Monday, September 16, 2019 2:59:19 PM
إلى: microsoft/appcenter <appcenter@noreply.github.com>
نسخة: Subscribed <subscribed@noreply.github.com>
‏‏الموضوع: Re: [microsoft/appcenter] Error: Cannot prepare UI Test artifacts using command: mono (Android Studio) (#891)


Closed #891<https://github.com/microsoft/appcenter/issues/891>.

**Comment by Oddj0b** [comment]
@zyead Do you want to keep this issue open?

**Comment by Oddj0b** [comment]
@DevLalla you should be able to run it without preparing first.
