### ISSUE TITLE
Distributing multipe Android apps via Appcenter with Same Playstore account

### ISSUE THREAD

**Issue by rishikeshsr** [microsoft/appcenter#892]
**What App Center service does this affect?**
Dashboard 

**Describe the bug**
Not able to distribute multiple apps from Appcenter linked to a single account.

**To Reproduce**
1. Go to AppCenter ==> Distribute ==> Store
2. Click on Link ==> Connect to store ==> Upload JSON
3. Enter package name after uploading.
4. See error - Package you entered exists, but not accessible through playstore.

**Expected behavior**
As we have Playstore account with multiple apps. We need to distribute the app with Same Service Account JSON, even if not, we get an error. 

**Screenshots**
<img width="581" alt="Screenshot 2019-08-14 at 6 16 25 pm" src="https://user-images.githubusercontent.com/22723616/63023446-c637f680-bec2-11e9-86cd-7b8578a511c2.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version:  76.0.3809.100 

**Additional context**

**Comment by Oddj0b** [comment]
@rishikeshsr thanks for reporting the bug, I'm working with the product team to prioritize it.

**Comment by Oddj0b** [comment]
@rishikeshsr Can you check if the service account in the Google Play APIs is an owner? And that you have granted access to the API in Google Play Console?

**Comment by rishikeshsr** [comment]
Hi. I am the owner for both the accounts.

**Comment by rishikeshsr** [comment]
And yes. It worked for one app in the account. Not others.
