### ISSUE TITLE
iPhone unable to install apps via appcenter

### ISSUE THREAD

**Issue by TylerHartzheim** [microsoft/appcenter#894]
**What App Center service does this affect?**
Mobile appcenter website.

**Describe the bug**
I have one co worker that is unable to install .ipa files to their iphone ONLY from appcenter. If they go to Hockeyapp, they are able to install. The user has their device registered on the site.
I've tried signing in to my account as well, and it still does not work.
When the user clicks install, it brings you to the "check your home screen" page but never prompts the user to install.

**To Reproduce**
1. Click the app you wish to install
2. Click install for the newest build
3. see the new tab that is presented saying your app is installing.
4. never see prompt to install.

**Expected behavior**
The user should be seeing the prompt to install the .ipa

**Screenshots**
Working Instance
![Working](https://user-images.githubusercontent.com/18602983/63041036-bfd25c00-be7b-11e9-878c-f0bf48f70f4a.PNG)
Not working status
![notWorking](https://user-images.githubusercontent.com/18602983/63041056-cc56b480-be7b-11e9-8e45-37012054dbbe.PNG)
This never shows the modal asking to install

**Desktop (please complete the following information):**
 - OS: -
 - Browser: -
 - Version: -

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 1.12.4
 - Browser safari
 - Version newest

**Additional context**
As mentioned before, hockeyapp has no issue on this device, but appcenter cannot install.

**Comment by botatoes** [comment]
Thanks for letting us know. Please create an intercom ticket on appcenter.ms so we can get some info to help. To create a ticket, go to the ? on the top right corner or the blue button on the bottom right corner.

**Comment by TylerHartzheim** [comment]
Hello!
What do I click to make an intercom ticket
![image](https://user-images.githubusercontent.com/18602983/63180719-b4aa3800-c003-11e9-8e5c-0ea96af30cc9.png)
I dont see any option like that
