### ISSUE TITLE
Release Notes – Markdown Support

### ISSUE THREAD

**Issue by mylesbarros** [microsoft/appcenter#895]
**What App Center service does this affect?**
App Center Release Notes

**Describe the bug**
App Center release notes functionality doesn't appear to match HockeyApp. Specifically HTML break tags aren't supported and standard Markdwon links don't seem to be parsed correctly.

**To Reproduce**
1. Add release notes in HockeyApp with Markdown Links or <br/> statements.
2. Find the same build in App Center.
3. The release notes will not be formatted correctly.

**Expected behavior**
I would expect `<br/>` tags to create line breaks ala HockeyApp and GitHub.

**Screenshots**

#### HockeyApp
<img width="1011" alt="HockeyApp" src="https://user-images.githubusercontent.com/4069415/63049759-b7a90980-bed9-11e9-9262-b69008b9d43e.png">

#### App Center
<img width="662" alt="AppCenter" src="https://user-images.githubusercontent.com/4069415/63049763-ba0b6380-bed9-11e9-8497-e4231c23dacb.png">

Note in the above screenshot the way that App Center erroneously captures any trailing instance of bracketed text in the URL such as **[ASL]** and **[iOS]**.

**Desktop (please complete the following information):**
 - OS: macOS
 - Safari & Firefox

I can't seem to get the related issues beta working but this may be related to [this bug](https://github.com/microsoft/appcenter/issues/550).

**Comment by mylesbarros** [comment]
Here's the (slightly edited) Markdown source if it helps:

```
Build `8338` (Git Tag: `xxx-Beta-8338`)

#### Recent Changes:
🐛 [GITHUB-10229](https://www.microsoft.com/cs-cz/) [ASL] [iOS] RC widget doesn't work<br/>
🐛 (No JIRA task) Fix Changelog Markdown Format<br/>
🐛 (No JIRA task) Ipinfo Bugs<br/>
🐛 (No JIRA task) xxx Crash Rating<br/>
🐛 [GITHUB-10193](https://www.microsoft.com/cs-cz/) [iOS][ASL] push notification - subscription expired<br/>
🐛 [GITHUB-10214](https://www.microsoft.com/cs-cz/) [ISL] Stuck in creating account<br/>
🐛 (No JIRA task) xxx Rating Crash<br/>
✨ (No JIRA task) Beta Changelogs<br/>
✨ (No JIRA task) Add New Account Version

Thank you for reviewing our builds! Your work is invaluable in helping to make our work something that our whole team can be proud of. Keep up the great work! 🧡🎉
```

**Comment by botatoes** [comment]
Hi, App Center only support markdown right now. I will add HTML support to our backlog for tracking purposes.

**Comment by mylesbarros** [comment]
Okay, cool, thanks for looking into it!

Any update on the URL parsing spilling beyond `[]()` pairs into `[]()[]`?

**Comment by botatoes** [comment]
Yes please open another bug. :) I'm closing this one.
