### ISSUE TITLE
WPF set User on SDK for Analytics

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter#897]
**Describe the solution you'd like**
WPF set User on SDK for Analytics, like you do for other application types.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by winnieli1208** [comment]
Thanks for the feature request! We plan to add user ID support for WPF apps in next few months. I'll let you know when I have a more exact ETA. Thanks!

**Comment by james1301** [comment]
Thanks @winnieli1208.

**Comment by winnieli1** [comment]
Hello! We added support for User ID in the latest SDK release last week. You can find the docs here: https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/wpf-winforms#identify-users

Closing this issue for now but let me know if you run into any issues. Thanks!
