### ISSUE TITLE
WPF Support for Push Notifications

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter#898]
**Describe the solution you'd like**
Push Notifications for WPF applications

**Describe alternatives you've considered**
Currently use PubNub.

**Additional context**
Currently we use PubNub for WPF and App Center for our Xamarin Forms app, but would be great to use App Center for both. I think this would be a massive boost for Microsoft Developers also, for a good way to implement Push Notifications for all applications.

**Comment by james1301** [comment]
Thanks @winnieli1208, shame it's not in any short term plans because I think it would be a great addition, scheduled in a call so can discuss then.

**Comment by NLI-KelbyHunt** [comment]
@winnieli1 - I would personally like to have push notifications similar to UWP. We are starting to use it for UWP, but have applications we cannot port away from WPF. It would be nice if the users that use our WPF app on Windows 10, could get a notification for whatever reason we send out similar to that of UWP. I would also assume with .NET Core 3.0's amazing release including WPF, you may find more users that will potentially want this feature.

**Comment by jwargo** [comment]
@james1301 @NLI-KelbyHunt Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

**Comment by james1301** [comment]
@jwargo is there a link to a feature request for Azure Notification Hubs?

**Comment by jwargo** [comment]
@james1301 https://feedback.azure.com/forums/218849-notification-hubs
