### ISSUE TITLE
Remove push billing plan options to clarify positioning

### ISSUE THREAD

**Issue by jwargo** [Microsoft/appcenter#9]
App Center Push supports both the Free and Paid billing plans. With the service in **Preview**, we've never billed customers for Push usage in the Paid tier. Our long term goals include aligning App Center Push with Azure Notifications Hubs, both of which have free and billable usage plans. To simplify things for our customers, App Center Push will become a free service (with the current limitations on Push Audience and batch Push processing). When the customer's needs exceed the capabilities of App Center Push, we'll streamline the customer's shift to using Azure Notification Hubs.

**Comment by patniko** [comment]
This was shipped today.

**Comment by jwargo** [comment]
This work is complete.
