### ISSUE TITLE
Share Build Credit from Azure DevOps to appcenter.ms

### ISSUE THREAD

**Issue by ppongsakorn** [microsoft/appcenter#90]
**Describe the solution you'd like**

I paid for Azure DevOps for stored code, agile tool, build, deploy and use appcenter.ms for distribute the mobile app.

I think build tool on appcenter.ms easy more than Azure DevOps.

Is possible to share credit from Azure DevOps to appcenter.ms?

Thank you.
Pongsakorn.

**Comment by nrajpurkar** [comment]
@ppongsakorn It's not possible to share this credit today, they require separate plans.
