### ISSUE TITLE
Add feature for manually creating bug tickets

### ISSUE THREAD

**Issue by dj-dev** [microsoft/appcenter#902]
**Describe the solution you'd like**
Add a feature for manually creating bug tickets, if a bug tracker system is linked to an app. 

Suggest making this work similar to the equivalent feature in HockeyApp where:

1. There is a UI associated with a crash group that shows a "Tracked" tag that indicates if the crash group is linked to a crash ticket:
![image](https://user-images.githubusercontent.com/31782421/63070731-7d3e7b80-bf70-11e9-9745-514144aa87e2.png)

2. If the crash group is not tracked, there is an option for "Create ticket", where the UI is similar to HockeyApp where you can preview/edit the ticket before it's created:
![image](https://user-images.githubusercontent.com/31782421/63070815-d3abba00-bf70-11e9-88fe-138ebfd73bbf.png)

3. If the crash group is already tracked, i.e. as described under 1, there is an option for viewing the tracked ticket details, including an option to untrack the ticket. Example from HockeyApp:
![image](https://user-images.githubusercontent.com/31782421/63070993-72d0b180-bf71-11e9-995d-47d96c8ca508.png)

**Describe alternatives you've considered**
Use the App Center feature for automatically generated tickets. We tried this but it does not work if the 'Number of crashes' setting is > 1. This bug is tracked in https://github.com/microsoft/appcenter/issues/901

**Comment by EmilAlipiev** [comment]
this is a must feature. please add this as priority. thank you

**Comment by winnieli1208** [comment]
Hi all - thanks for the feature request. We have an item on our backlog to support manual linking of bug trackers. I don't have an ETA at the time but I will post here if I have any updates.


In the meantime, you can find the WIP mockups [here](https://devdiv.invisionapp.com/share/8NNZ8P442QR#/screens). Note the UI is a bit outdated and also doesn't include a input text field like HockeyApp does. Let me know you have any feedback.

 Thanks!

**Comment by elgato-tschnitzler** [comment]
Definitely a quite important feature I'd really like to see getting added to App Center very soon.

**Comment by stephent** [comment]
Agreed - this is a big gap. Without it, MS App Center diagnostics are a rather a dead end for crash reports. I'm disappointed not to see it in place prior to having migrated from HockeyApp, where we'd had this capability for years.

**Comment by awBSH** [comment]
Hello, also for us this is a very important feature since the auto-creation results in lots of duplicates in our JIRA :-(

**Comment by sarahyc** [comment]
Any ETA for this after 3 months? Is it tracked as a P1 item?

**Comment by winnieli1** [comment]
Hi there - unfortunately no updates. This is being tracked but due to other priorities at the moment, this isn't on our immediate roadmap. We understand the importance of thihs feature and will post here with any updates. Thanks!

**Comment by dj-dev** [comment]
Hi @winnieli1, is the roadmap here https://github.com/Microsoft/appcenter/wiki/Roadmap what you are referring to as the "immediate roadmap"? If so, can we assume the unticked items are being treated as higher priority than this one? Thanks

**Comment by winnieli1** [comment]
@dj-dev correct, that is our short term roadmap. The items listed are higher priority at the moment but we continuously update our plans based different factors including customer feedback.

**Comment by dj-dev** [comment]
Ok thanks @winnieli1. This is a very important feature to have so hopefully the community will keep giving this issue a thumbs up :wink: :wink:

**Comment by joehanna** [comment]
I don’t understand why we were forced out of HockeyApp app a week ago and feature parity is not even close. We should been allowed to stay there longer.

**Comment by ffittschen** [comment]
Why is there even a toggle to enable _"Auto create ticket"_, if there is no manual way to create tickets? Manually creating tickets is a MUST HAVE, especially because AppCenter will create duplicates of each crash group for every app version (https://github.com/microsoft/appcenter/issues/1430)...
