### ISSUE TITLE
Ability to run UnitTests after compiling the project.

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/appcenter#903]
Ability to run Unit Tests (not UI) after compiling the project.
And also access the test results.

Now we run UnitTests in a different environment. and if their success compile the build in AppCenter.
It would be nice for UnitTests to work in AppCenter too.

And it would be nice to see information on them, like code coverage, execution time and all that.

**Comment by amchew** [comment]
Thank you @KSemenenko for the feature request! @Oddj0b, could you please take a look?

**Comment by Oddj0b** [comment]
Depending on your app we have unit testing available in build, here is an example of how to configure XCTest for iOS apps: https://docs.microsoft.com/en-gb/appcenter/build/ios/first-build#35-tests

**Comment by KSemenenko** [comment]
I mean some nUnit tests

**Comment by alexshikov** [comment]
+1 for that. Running simple xUnit as a post-build step out of the box would be awesome!

**Comment by TomSoderling** [comment]
Yes please!

**Comment by adamzucchi** [comment]
+1 (xUnit)!

**Comment by Oddj0b** [comment]
Basically this script (https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/xamarin/nunit-test/appcenter-post-build.sh) as part of the build settings?
