### ISSUE TITLE
ServiceHost/Named Pipe Not Listening

### ISSUE THREAD

**Issue by thehoglet** [microsoft/appcenter#904]
**What App Center service does this affect?**
Microsoft.AppCenter.Analytics
Microsoft.AppCenter.Crashes

**Describe the bug**
Configuring and starting AppCenter before starting a WCF ServiceHost seems to interfere with a named pipe endpoint. Clients report that no endpoint is listening at net.pipe://...

Switch the start order around (open ServiceHost first, then start AppCenter) and all seems to be okay (clients can connect, AppCenter can track and report).

**To Reproduce**
The code is:

```
      using static Microsoft.AppCenter.AppCenter;
      using static System.Globalization.RegionInfo;

      var countryCode = CurrentRegion.TwoLetterISORegionName;
      SetCountryCode(countryCode);

      Start(
        appCenterSecret,
        typeof(Analytics),
        typeof(Crashes)
        );
      
      using (var host = new ServiceHost(typeof(Service)))
      {
        var endpoint = host.AddServiceEndpoint(
          typeof(IService),
          ServiceHelper.MakeNetNamedPipeBinding(),
          ServiceHelper.GetServiceNamedPipeAddress(_serverID)
          );
        endpoint.EndpointBehaviors.Add(new ProtoEndpointBehavior());

        host.Open();
        Application.Run();
        host.Close();
      }
```

**Expected behavior**
Order of starting components to be irrelevant or else a warning in the docs.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home

**Additional context**
.NET 4.7.1
AppCenter 2.2.1-preview

**Comment by hamswan** [comment]
Thanks for reporting this our team will take a look at this.

**Comment by AnastasiaKubova** [comment]
Hi, @thehoglet! Thank you for contacting us! Could you please share the verbose logs? Please add this ` AppCenter.LogLevel = LogLevel.Verbose;`  before `AppCenter.Start`.

**Comment by thehoglet** [comment]
Attached are two files containing the debugging output to the VS2019 console. One for the successful start-up (ServiceHost ctor before AppCenter.Start()), one for the failed start-up.

Note that, as written, debugging was required to be terminated in both cases with a Shift+F5 in VS in order to break the server app out of its message loop (i.e. the call to the blocking Application.Run()).

[startup-success.txt](https://github.com/microsoft/appcenter/files/3530410/startup-success.txt)
[startup-failure.txt](https://github.com/microsoft/appcenter/files/3530411/startup-failure.txt)

**Comment by AnastasiaKubova** [comment]
Hi, @thehoglet! Thank you for providing logs. I need more time to investigate it. Thank you for your patience.

**Comment by thehoglet** [comment]
@jwallra 

The issue occurs with a start-up of just Crashes, and just Analytics.

The endpoint address is formed using ```$"net.pipe://localhost/rvis{id}/service"``` where ```id``` is a positive integer.

The ctor for the binding is this:

```
new NetNamedPipeBinding()
      {
        MaxReceivedMessageSize = 100000000,
        MaxBufferSize = 100000000,
        SendTimeout = TimeSpan.FromMinutes(10),
        ReceiveTimeout = TimeSpan.FromHours(9)
      }
````

The single endpoint behavior in use by client and server is this:

[ProtoEndpointBehavior](https://github.com/protobuf-net/protobuf-net/blob/master/src/protobuf-net/ServiceModel/ProtoEndpointBehavior.cs)

via the protobuf-net nuget pkg.

More info here:
[Protocol Buffers and WCF](https://blogs.msdn.microsoft.com/dmetzgar/2011/03/29/protocol-buffers-and-wcf/)

**Comment by achocron** [comment]
Hey @thehoglet, we don't have an immediate fix planned for this so I advise that you start the services in the manner that already works. Thanks for bringing it to our attention, though!
