### ISSUE TITLE
More information about which branch and commit a Release came from

### ISSUE THREAD

**Issue by andrejacobs** [microsoft/appcenter#905]
**Describe the solution you'd like**
On the "Distribution / Releases / Individual Relase info page" it would be very handy to see exactly from which branch and commit the release was build and distributed from.

At the moment the Release info only shows an MD5 checksum.

I know that technically you can do a release by uploading a binary, but our workflow is to always do a release by clicking the Distribute button after a branch was built.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by botatoes** [comment]
Thanks for the feedback. Can you share exactly what you would like to see in the details?

**Comment by andrejacobs** [comment]
@botatoes When I view a release by visiting install.appcenter.ms I can see the branch the build came from as well as the git commit hash along with the git commit message.

However as an administrator on the desktop browser (ie. appcenter.ms) when I view releases, none of the information is shown to me, only some MD5 checksum (which I guess is the md5 of the binary).

So for example, lets say I build 5 times from the same branch, but different commits.
As an Admin I have no way to verify which of the builds I want to keep around for a bit or to distribute them even further.

**Comment by botatoes** [comment]
Got it! Thanks for that :) 
I'll keep note of this and share the feedback with our design team. We are currently working on merging the two portals for a better tester experience. I believe we should be able to add this in as well.
