### ISSUE TITLE
Different release pages when set to "Automatically manage devices"

### ISSUE THREAD

**Issue by dominicmh** [microsoft/appcenter#906]
**Describe the solution you'd like**
When having App Center automatically manage devices for testers, I'd like to have an option to get different release links for each distribution group or a switch on the releases page. 
If a tester is in two distribution groups he doesn't know which build to install.

**Describe alternatives you've considered**
* Have the testing coordinator tell testers which build numbers they need to install
* Add all testers' device's UDID to provisioning profile
* Use enterprise provisioning profile to sign the app and do a release to the group

**Additional context**
In our project we have a setup where testers get their test releases via App Center. In Android, pushes to dev are built for a specific distribution group and pushes to master to another distribution group. This way we can have two different public links, so testers know which releases come from master (releases) and which ones from dev (features).
For iOS, we couldn't use public links because we want test devices to be managed by App Center. After we switched from public links to automatically managed devices, we only have only link and testers can only differentiate dev/branch by build numbers.

**Comment by botatoes** [comment]
Hi, I'm currently working on improvements to the tester experience. This will be addressed in the improvements which will allow private distribution group links.

**Comment by dominicmh** [comment]
Hi @botatoes, is this feature still on the horizon?
