### ISSUE TITLE
WPF version not reported correctly when using ClickOnce

### ISSUE THREAD

**Issue by moshegutman** [microsoft/appcenter#907]
**Describe the solution you'd like**
It looks like the WPF analytics module is using the Assembly file version for "version" when viewing data in App Center.

**Describe alternatives you've considered**
I would like it to use the ClickOnce publish version, or better yet, let me set the version myself.

**Additional context**
ClickOnce is an installation technology for deployment of WPF apps.

**Comment by JakubOleksy** [comment]
@hamswan FYI

@moshegutman might be better to put this on SDK repo itself:
https://github.com/Microsoft/AppCenter-SDK-DotNet

**Comment by moshegutman** [comment]
@JakubOleksy Done!

**Comment by MatkovIvan** [comment]
ClickOnce was fixed in SDK [2.4.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.4.0-preview)
Manually set version feature request - #1313
