### ISSUE TITLE
Before building, first check for valid connection to App Store Connect

### ISSUE THREAD

**Issue by jvandenaardweg** [microsoft/appcenter#909]
**Describe the solution you'd like**
It would be great that, before building, testing and releasing the build, to check if the connection to App Store Connect is still active. I've already had several times that the login to App Store Connect is expired for some unknown reason. You only get that warning at the end of a build, which is in my case 15-20 minutes later.

It's better to know this upfront, so you can re-connect your account before building. This could possibly save an extra 15-20 minutes in my use case, as I don't have to run the whole build twice.

**Describe alternatives you've considered**
The only alternative would be to manually check on the Distribute > Stores page if the connection is still active or expired.

**Additional context**
This problem usually happens in step 23 of the build:

```
2019-08-16T09:37:54.4007730Z ##[section]Starting: Create distribution
2019-08-16T09:37:54.4012570Z ==============================================================================
2019-08-16T09:37:54.4012700Z Task         : App Center distribute
2019-08-16T09:37:54.4012840Z Description  : Distribute app builds to testers and ***s via Visual Studio App Center
2019-08-16T09:37:54.4012940Z Version      : 3.156.0
2019-08-16T09:37:54.4013010Z Author       : Microsoft Corporation
2019-08-16T09:37:54.4013110Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
2019-08-16T09:37:54.4013200Z ==============================================================================
2019-08-16T09:44:50.7225470Z ##[error]{"code":"two_factor_authentication_error","message":"Error: Failed to publish to store. Error: apple connection is not valid for ***: XXXX"}
http response code: 400
2019-08-16T09:44:50.7243110Z ##[section]Finishing: Create distribution

```

**Comment by mylesbarros** [comment]
This is unrelated to the actual feature request but [fastlane](https://fastlane.tools), an open-source mobile build automation tool, handles this really well by managing your App Store Connect session and automatically logging back in if it's broken.

**Comment by Oddj0b** [comment]
@jvandenaardweg Thank you for the feature request, this is good feedback and I hope we get some traction on it so we can implement it.

**Comment by Sutil** [comment]
@jvandenaardweg , how do I renew the token?

**Comment by jvandenaardweg** [comment]
@Sutil Select your app in AppCenter, then: on the left sidebar: Distribute -> Stores. Then you should see a red banner like the one below, which allows you to sign in again to the app store. After doing that, you can build again.

<img width="1115" alt="Screenshot 2020-03-24 at 14 48 58" src="https://user-images.githubusercontent.com/5155373/77432623-9b117000-6dde-11ea-8d22-4d8136289576.png">

**Comment by Sutil** [comment]
@jvandenaardweg Thanks! Works fine!

**Comment by petegivens** [comment]
Or at least the build shouldn't completely fail. Just because the distribution step fails doesn't mean that there's anything wrong with the app package. I could reconnect my store and publish it in 30 seconds, but instead I have to repeat the 30 minutes build process...

**Comment by benmagos** [comment]
I just had this error today and would love to see a solution similar to the one suggested.

**Comment by IonoclastBrigham** [comment]
Maybe also send an email that the auth token is _going_ to expire, or at least that it has done?

**Comment by edersonmberti** [comment]
Hello guys, there's any way to don't need re-authenticated every month?

**Comment by rdgout** [comment]
I second this, it shouldn't be very hard to check the connection and it would save a bunch of time. I can imagine this would be great for the resources of the build servers too since they don't need to needlessly build something multiple times.

**Comment by mifi** [comment]
Still getting this error. after 29 min the build is finished and then it crashes with this error, very unnecessary. Alternatively if it could flag the build as successful, then we can manually re-publish it after fixing the issue without having to run another full build.

**Comment by mifi** [comment]
🤖

**Comment by TimOnyx** [comment]
We're maintaining an app together with another company. Due to security reasons, we don't have access to their account with 2FA. It happens often that the person triggering the build does not have permissions to update the connection. To top it off, this person will also not get an email saying the build has failed.

It would be great if at least this banner is visible somewhere on the pages used to trigger a build.

**Comment by benmagos** [comment]
No, this is still an outstanding and frustrating issue.

**Comment by sjransom** [comment]
Can confirm this is still an issue.

**Comment by IonoclastBrigham** [comment]
This hit our team just the other day.

**Comment by elirangoshen** [comment]
same here.. is there away to solve it ?

**Comment by IonoclastBrigham** [comment]
@Oddj0b

**Comment by kalipersyn** [comment]
would love to see any of the solutions above! 👀

**Comment by lorddusk** [comment]
And 3 months later... Still the same.

**Comment by gustavolsilvano** [comment]
Still happens! It's a constant issue, our team is very small so everyone has a bunch of issues to solve. Having one issue not being tested by this is very frustating.

**Comment by FernandoLooplan** [comment]
This issue is still here in 2024.

**Comment by rdgout** [comment]
We have actually moved away from appcenter since they don't seem to care. We're using bitrise now.
Good luck everyone!
