### ISSUE TITLE
UWP and WPF with intune support

### ISSUE THREAD

**Issue by superjamel** [microsoft/appcenter#91]
Hi Everyone,

I saw on the roadmap the following: Add first-class UWP and WPF support, is this combined with intune support for UWP and WPF? Can somebody confirm this?

Thank you. :)

**Comment by winnieli1208** [comment]
Hi @superjamel,

I responded to your e-mail as well but I'll re post for visibility: we haven't committed to supporting Intune for WPF and UWP apps but are definitely considering this. I'll monitor this feature request to gauge public interest and update you if we have more details on the timeline. Thanks!
