### ISSUE TITLE
ErrorReport is missing getAppVersionName that was in CrashDetails in HockeyApp

### ISSUE THREAD

**Issue by martinbonaciugome** [microsoft/appcenter#910]
With HockeyApp, for our own analytics, we used CrashDetails.getAppVersionName() to discern the version that crashed when an update is released to our App, and user crashed in the previous release. Is there any way to know which version generated the report in AppCenter?

**Comment by martinbonaciugome** [comment]
i see it in getDevice

**Comment by JakubOleksy** [comment]
Yep, you can find it here for exampe:

https://github.com/microsoft/appcenter-sdk-apple/blob/bdbc01cb8607a57fcf2d8d0abbfd731f99db4fcb/AppCenter/AppCenter/Model/MSDevice.h#L68
