### ISSUE TITLE
Android AAB settings showing up for iOS solution

### ISSUE THREAD

**Issue by beeradmoore** [microsoft/appcenter#911]
I have a Xamarin.Forms app but attached in the screenshot is the iOS build config using the iOS csproj, but the option to enable Android App Bundles is displayed. If the build config knows its a Xamarin.iOS project then this should not be available.

![appcenter_ios_aab](https://user-images.githubusercontent.com/904737/63231960-4d3ff280-c266-11e9-9870-20989c92acca.jpg)

**Comment by DennisPan** [comment]
Definitely a bug 😅 Thanks for reporting this @beeradmoore ! We will address this soon

**Comment by nrajpurkar** [comment]
This is fixed. Thanks for reporting @beeradmoore 😄
