### ISSUE TITLE
Mouse-up outside of the distribute wizard dismisses the wizard

### ISSUE THREAD

**Issue by SuicideLeaf** [microsoft/appcenter#912]
**Describe the solution you'd like**
This is a small, niggly annoyance when doing manual distributions

When distributing a build and stepping through the wizard, quite often on step # 2 (Notes) I will highlight the pre-filled commit notes and replace them with a list of changes. When highlighting, it is common to drag from the right-to-left and release the mouse button. However since the edge of the modal is so close to the start of the text, I often release the mouse button outside of the modal, which triggers the dismissal of the whole distribution wizard, losing all changes.

Solution would be to not have the dismissal trigger when mouse-up occurs.

**Describe alternatives you've considered**
Changes made during the distribution wizard could be saved as a draft if leaving the wizard.

**Additional context**
![2019-08-19 12_02_32-Distribute build 65 · Property Manager · App Center](https://user-images.githubusercontent.com/35824573/63232185-8897ec80-c279-11e9-95d5-54f3079f37ee.png)

**Comment by botatoes** [comment]
Thanks for the feature request! :) We've heard this feedback before and I will definitely discuss this with the design team in our upcoming UX improvement session.
