### ISSUE TITLE
iOS app distribution from Build screen fails with GATEWAY_TIMEOUT error

### ISSUE THREAD

**Issue by alefurman** [microsoft/appcenter#913]
When I click "Distribute" button from within a successful build screen it always fails with the following error "Oh no! Build XX failed to distribute. Error: GATEWAY_TIMEOUT"
That does not happen when ipa file size i relatively small. However, in my case ipa file is roughly 130 MB and the distribution always fails with GATEWAY_TIMEOUT error

**Steps to reproduce:**
1. Login to AppCenter
2. Connect Azure DevOps/Github project
3. Configure iOS build including mobileprovision and p12 certificate.
4. Click "Save and Build" - run build on AppCenter
5. Make sure the build is successful 
6. Make sure ipa file size is 130 Mb or more
7. Click "Distribute" button
8. Go through distribution wizard

**Actual result:** In ~2-3 minutes "Oh no! Build XX failed to distribute. Error: GATEWAY_TIMEOUT" error pops up
**Expected result:** Build is successfully distributed and available from Releases menu

**Comment by DennisPan** [comment]
@alefurman We are currently investigating a fix for this. Will get back to you soon. In the meantime, if you can reach out to support via App Center portal, we can enable the fix for your app only and see how that works.

**Comment by DennisPan** [comment]
@alefurman We just deployed a fix for this. Could you give that another try?

**Comment by DennisPan** [comment]
We have a customer confirmed this is working, so I'm closing this. Feel free to re-open if needed.
