### ISSUE TITLE
Support for using AppCenter in plugins

### ISSUE THREAD

**Issue by mcetkovsky** [microsoft/appcenter#914]
**Describe the solution you'd like**
Our product is a plug-in to an existing third-party macOS application. The application uses HockeySDK/AppCenter for its purposes. We would like to use (our own) AppCenter inside our plugin without messing with the app's HockeySDK/AppCenter.

**Describe alternatives you've considered**
We found no alternative as each solution is app-wide and requires a registration in start:withServices:-like method.

**Comment by hamswan** [comment]
Thanks for contacting us. Our team will take a look at this.

**Comment by hamswan** [comment]
Currently we don't support this , I have added this as a feature request. you can track this through this GitHub issue.
