### ISSUE TITLE
[Feature] Support not reinstalling app between tests

### ISSUE THREAD

**Issue by Naishy** [microsoft/appcenter#92]
**Describe the solution you'd like**
Currently when running Xamarin.UITests via NUnit the App being tested is uninstalled between tests. Please can you allow this to be configured so that tests can connect to an App that is already running.

**Describe alternatives you've considered**
I've tried using [ConnectToApp()](https://developer.xamarin.com/api/member/Xamarin.UITest.Configuration.iOSAppConfigurator.ConnectToApp()/) but it's not supported within App Center.

**Additional context**
I asked App Center support if this was supported and they told me it wasn't and suggested I should raise a feature request.

**Comment by jwhiteDev** [comment]
Hi @Naishy what specifically do you need when connecting to an app already running? Have you tried passing AppDataMode.DoNotClear as a parameter into StartApp() when you initialize a test? It helps preserve app data from test to test.

https://intercom.help/appcenter/test/xamarinuitest-using-appdatamode-to-control-how-your-app-is-reset-between-individual-test-cases

**Comment by Naishy** [comment]
I have a specific requirement for testing an onboarding process within an
App (React Native on iOS), where I need to verify that particular answers
made by the user result in the correct outcomes. There are 256 different
combinations... The way the App is constructed there's an email
verification step plus a lot of screens that need to be navigated through
to reach the questions. Ideally the App would of been written in a more
testable way...but it's not.
I guess it may be possible for me to do something with the AppDataMode but
I'll also need to implement a backdoor to jump to the correct page.

**Comment by Oddj0b** [comment]
@Naishy sorry for the slow response.

You should be able to use `StartApp(appDataMode: Xamarin.UITest.Configuration.AppDataMode.DoNotClear)` That makes sure your apps doesn't uninstall between `StartApp` calls.
If you want to use the app across tests you must only call `StartApp` once and store the reference.
