### ISSUE TITLE
Analytics Custom Properties Casing

### ISSUE THREAD

**Issue by myokeeh** [microsoft/appcenter#920]
The logs.v1.data files seem to have inconsistencies for letter-casing for custom properties I've setup like PageName and LoadTime.

Most of the .data files have those recorded as pageName and loadTime, then for some files, they're recorded as PageName and LoadTime. The majority is the former, so I'd rather stick with that.

**Comment by yoannchaudet** [comment]
We used to have a bug in our Export service which was transforming properties' name. See https://github.com/microsoft/appcenter/issues/94.

We fixed the issue a while ago and kept both behaviors in place for 90 days. Last week we removed the old erroneous behavior.

From now on, your custom properties should be exported just the way they were emitted from our SDK.

**Comment by myokeeh** [comment]
I'm looking at an exported log from a ~15 minutes ago and it's still PageName -> pageName.

My app is emitting "PageName" using the SDK.

**Comment by yoannchaudet** [comment]
@myokeeh My mistake, the deployment from last week was actually rolled back (for unrelated reasons).

We just sent back to production that removed the casing erroneous behavior.

Starting now (August 21th at 1:12am UTC), you should see a consistent "PageName" in your exported logs.

**Comment by mitsuakiwatanabe** [comment]
If using ApplicationInsights for export.
A workaround is required.

in Kusto

```
customEvents
| extend Properties = todynamic(tostring(customDimensions.Properties))
| where Properties.YourProperty != "" or Properties.yourproperty != ""
| project YourProperty = tostring(iif(Properties.YourProperty != "", Properties.YourProperty, Properties.yourproperty)), timestamp, name

```


I misunderstood that it was a bug in ApplicationInsights, but it was different.
I hope it helps.
