### ISSUE TITLE
Remove user from release

### ISSUE THREAD

**Issue by lisional** [microsoft/appcenter#921]
**Describe the solution you'd like**
Being able to remove a single user from a release.
Currently after distributing a release to testers you can only remove the release from groups. There is no way to remove a release from a specific user.
To remove a release from a group:
- Go to Distribute section, groups tab
- Select the group you want to remove from a release
- Go to the RELEASES tab
- Choose "Remove from group" from the three dots menu

Either remove the option to distribute the app to a single user, or support removal would be appreciated.

**Describe alternatives you've considered**
Create a distribution group for this user and distribute to this group instead

**Comment by botatoes** [comment]
Thanks for the feature request. This is already in our backlog of things we need to do! Distribution is focusing on security, tester experience, in-app updates, and device management right now. Will definitely keep you posted when we move forward with this.

**Comment by alanleedev** [comment]
@botatoes I support the feature request as well. Also, add in the documentation on how to remove a release from a group. I only found out after reading this feature request how that was possible.

**Comment by ghugues** [comment]
Hello,
Could you reopen this issue ? This is still a very much needed feature. For security reasons it should be possible to remove all access to a user after they leave a company.

**Comment by skadookkunnan** [comment]
> Hello,
> Could you reopen this issue ? This is still a very much needed feature. For security reasons it should be possible to remove all access to a user after they leave a company.

Yes. It would be great to have this feature!
