### ISSUE TITLE
Allow using Active Directory groups in global distribution groups

### ISSUE THREAD

**Issue by lisional** [microsoft/appcenter#922]
**Describe the solution you'd like**
AD groups can only be added to an app distribution group. When I try to add an AD group to a global distribution group I don't see them.
This causes quite a lot more setup for us. We have different groups we try to maps for each of our apps: QA, iOS dev, Android dev, Team A, Team B...

We have all these entities mapped in our Active Directory.. It would have been easier to setup distribution groups once for our AppCenter organisation and link apps to each of these groups.

**Describe alternatives you've considered**
Right now I have to manually go to each app and recreate Distribution groups mapped to AD groups. We have other 15 apps, this is a lot of additionnal setup.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @lisional - I can definitely understand how the alternative is tedious. @botatoes or @blparr may be able to help out here.

**Comment by blparr** [comment]
Hi @lisional , thanks a lot for your feature request. This is definitely something in our radar. I don't have an ETA I can share with you just yet, but I'll keep this feature request open to make sure we update you when we do.

Thanks!
Blanca

**Comment by lisional** [comment]
We had no update on this issue from the team, but I discovered today that it seems to have been implemented.
I was able to create global distribution group and add an Active Directory group as a tester
