### ISSUE TITLE
Manage organisation distribution groups

### ISSUE THREAD

**Issue by Nalocar** [microsoft/appcenter#924]
**Describe the solution you'd like**
I want to be able to manage organisation distribution groups and distribute releases to organisation groups managed by the organisation without Admin/Owner rights on the AppCenter Portal. 

**Additional context**
A couple of days ago I was able to manage People and Distribution Groups in the AppCenter portal. This function now seems to be only available for Admin/Owner. As a developer I'm no longer able to access the People settings for my organisation. This also has the effect that I can't distribute releases to distribution groups that are part of the organisation. Instead only distribution groups that are created for each app can be added and I would have to create and manage all distribution groups for all apps separately. I'm able create groups and add apps using the API but not on the AppCenter Portal.

**Comment by blparr** [comment]
Hello! We added a new role called Member, to ensure that not everyone added to your apps, can change your org settings and org distribution groups. However, you should still be able to do so being an org collaborator (no need to be an admin).

It sounds like you are a Member for the org now. To change so, you need to ask the org admin to change your permissions back to Collaborator or Admin.

Hope this helps!

**Comment by Nalocar** [comment]
Is this working for organisations that are transitioned from Hockey? There is no way to manage users for our organisation and we've also not been able to find anything related on Hockey.

**Comment by nevalenny** [comment]
@Nalocar can you try managing your HockeyApp organization users now in App Center? This was recently enabled for adding/removing collaborators.

**Comment by derpixeldan** [comment]
Can be done as a Collaborator now.
