### ISSUE TITLE
Add UserId column to every table of AppCenter

### ISSUE THREAD

**Issue by martinbonaciugome** [microsoft/appcenter#925]
**Describe the solution you'd like**
UserId should be a column on every table of AppCenter. HockeyApp had it for Crash Logs.

**Additional context**
![image](https://user-images.githubusercontent.com/6127051/63444250-19daa080-c3eb-11e9-8d36-f12dcb78dbb6.png)

**Comment by winnie** [comment]
Hey @martinbonaciugome ! We just added a few columns to the crash reports table view including  one that displays the User ID. 

![image](https://user-images.githubusercontent.com/8868628/76964935-e0730080-68f9-11ea-99b2-aaaf7e773e71.png)

Hope that helps! Closing this issue for now but feel free to reach back out if you have any questions.
