### ISSUE TITLE
All columns should be sortable in AppCenter

### ISSUE THREAD

**Issue by martinbonaciugome** [microsoft/appcenter#926]
**Describe the solution you'd like**
All columns should be sortable in AppCenter. HockeyApp had it.

**Additional context**
![image](https://user-images.githubusercontent.com/6127051/63444402-632af000-c3eb-11e9-9806-fa6181bc784a.png)

**Comment by nrajpurkar** [comment]
Thanks for the feature requst @martinbonaciugome! I understand how sorting throughout the product could make your interactions better. We'll keep tracking this as a potential improvement in the future.
