### ISSUE TITLE
Failed to apply settings: push configuration is invalid.

### ISSUE THREAD

**Issue by LauriRantasalo** [microsoft/appcenter#927]
What App Center service does this affect?
App Center - Push notifications

Describe the bug
Cannot add Package SID and Security Key

To Reproduce

Go to Microsoft partner center -> copy application SID and secret key and paste to app center.

See error: "Failed to apply settings: push configuration is invalid"

Found a matching issue from earlier that was apparently fixed, but it seems to be back now.
https://github.com/Microsoft/appcenter/issues/290
![Sieppaa](https://user-images.githubusercontent.com/26435468/63453390-3f9a9080-c451-11e9-8325-fe4311cda95d.PNG)

**Comment by jwargo** [comment]
@LauriRantasalo thanks, I'll take a look.

**Comment by jwargo** [comment]
@LauriRantasalo I just tested it with an app I created and it works as expected. The field names are wrong, I copied the Application ID and Application Secret and it worked for me. Can you try again?

**Comment by LauriRantasalo** [comment]
Yeah I was using the Package SID before. Works now with application ID and secret. Thanks.

**Comment by jwargo** [comment]
@LauriRantasalo trying to understand what we need to do to fix this, isn't Package SSID and Application ID the same thing?

**Comment by LauriRantasalo** [comment]
No, for me when configuring the Appcenter push notifications it asked for Package SID and Application secret. When viewing the application details from Mircosoft Partner Center, the package SID can be found under Product Identity, where as the application ID is under WNS/MPNS --> Live Services link. (Above the Application Secret).

**Comment by jwargo** [comment]
@LauriRantasalo We made some additional docs updates last week (multiple places) to address this issue. Can you please take another look and let me know if what's there works for you?
