### ISSUE TITLE
Issue with AppCenter not seeing React Native apps in subfolders

### ISSUE THREAD

**Issue by dluc** [microsoft/appcenter#928]
I have a React Native app (not using Expo) in my DevOps repository, and the src code is not in the root folder, e.g: `/frontend/mobileapp/reactnative` is the root folder of the RN app, so `package.json` is in `/frontend/mobileapp/reactnative/package.json`.

Given this setup, when I try to configure a build, AppCenter shows an error:

![image](https://user-images.githubusercontent.com/371009/63461403-6b942280-c40d-11e9-8a0a-52c460dc0ace.png)

if I move the same code to the root (so `package.json` is in `/reactnativeapp/package.json`) instead everything works fine:

![image](https://user-images.githubusercontent.com/371009/63461653-ed844b80-c40d-11e9-8aa1-b1a3a9d12c9a.png)

Looks like I need to restructure my repository just for AppCenter, which is far from ideal.  

Is this a known limitation or a bug?  

Any workaround to setup the build manually so I can specify where these files are?

**Comment by nrajpurkar** [comment]
Hi @dluc, we look for the `package.json` within the first 4 layers of your repo. No way to set the path manually today. This may be a similar feature request to #278.

**Comment by dluc** [comment]
hi @nrajpurkar how many layers is `/frontend/mobileapp/reactnative/package.json` relatively to the root of the repo? isn't it 3 ?

**Comment by DennisPan** [comment]
@dluc Do you mind reaching out to support from App Center portal? You can ask support team to assign to me. I'd like to take a closer look at your app, which hopefully can help

**Comment by b-barry** [comment]
@dluc Do you find any workaround? I am facing the same issue.

**Comment by DennisPan** [comment]
@b-barry It ended up being that certain files the repository analysis was looking for is deep in the repository, for example, gradlew. If you can reach out to support, we can figure out if your case is something similar.

**Comment by b-barry** [comment]
@DennisPan Could you give the support address?

**Comment by DennisPan** [comment]
@b-barry This hopefully helps: https://intercom.help/appcenter/en/articles/1698824-getting-help-with-app-center

**Comment by GoMino** [comment]
This is really an annoying issue!

**Comment by bitops** [comment]
Agree that this is a major limitation on the part of App Center Build. It should be a well-supported feature to build apps that are not stored in the root of the repository.

**Comment by rrnara** [comment]
I have a scenario where the repo has the nodejs server, web-client and react-native code are in single repo. Without specifying the subfolders creating a build environment is impossible. I currently have a separate repo where I duplicate the react-native code to get the build working. It would be nice if path to react-native code can be specified

**Comment by JulianBissekkou** [comment]
@rrnara How did you solve the issue?

**Comment by rrnara** [comment]
> @rrnara How did you solve the issue?

I created a separate repo to which the subfolder gets pushed on commit using git subtree split command. And that mobile only repo is what is used for building apps in appcenter
