### ISSUE TITLE
2FA to App Store missing option for "did not receive code"

### ISSUE THREAD

**Issue by vance** [microsoft/appcenter#929]
Standard flow for App Store Connect 2FA has a link with the option "I did not receive a code" from that link, the user is prompted with 3 alternative options. This link is not available when connecting to the App Store account. This is required because we have multiple enterprise users on the same account, we need to select to which authorized phone number to send the code.

**Comment by nrajpurkar** [comment]
Thanks for filing this issue @vance. Tapping @botatoes for further information on this.
