### ISSUE TITLE
[Feature] allow push notification send report /API if the token still active or not

### ISSUE THREAD

**Issue by RioFiveJack** [microsoft/appcenter#932]
Hi when i'm using Firebase i can know if the token still active or not when i'm sending notification, I'm using that info to deregister token / installation ID so i don't need to resend every push if it's not active.

**Comment by jwargo** [comment]
@RioFiveJack Can you share some details on how you see this working?  How would you like it to work?

**Comment by RioFiveJack** [comment]
@jwargo i would like when we send push notification to 
/v0.1/apps/{owner_name}/{app_name}/push/notifications
we could know error like when we're using Firebase ,
ex : 
{
  "error": {
    "code": "UnregisteredDevice",
    "message": ["146fbdde-0aaf-444d-bcc0-6d84520c9080"]
  }
}

**Comment by RioFiveJack** [comment]
great thanks @jwargo

**Comment by jwargo** [comment]
@RioFiveJack would you be willing to have an email conversation or chat about how you use Push? I'm working on the future plans for App Center Push and want to learn more about how you use it and how you want to use it?  My email address is in my profile.

**Comment by jwargo** [comment]
@RioFiveJack  Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
