### ISSUE TITLE
Group errors and crashes by version name and not by version number

### ISSUE THREAD

**Issue by maxkoshevoi** [microsoft/appcenter#933]
**Describe the solution you'd like**
Currently errors and crashes are grouped by version **name**, and this is a little inconvinient for me since one version of my app consists of 4 apk (one for each platform) to reduce overall apk size for my users.
![image](https://user-images.githubusercontent.com/6609929/63495003-a3f83700-c4c7-11e9-8367-8ed312b4b930.png)

So if there is as error occurring in some version I could see up to 4 groups with it, which makes statistics wrong and complicates error tracking.

**Describe alternatives you've considered**
Could you please implement grouping my version **name**? Or maybe some switch in the settings that will enable it.

**Comment by chrishonson** [comment]
In hockeyapp we're able to see all of the crashes for a specific version (number or name). That's usually the place I spend the most time as I'm most interested in the crashes on the latest released version. This feature will be missed.
