### ISSUE TITLE
Change git repo

### ISSUE THREAD

**Issue by andreasbergqvist** [microsoft/appcenter#934]
I moved my app from a private Bit Bucket account to an organization.

This means that the URL has changed.
But there is no way to change an repo URL.

The only way seems to be to delete the build setting and recreate, loosing all previous build information.

**Comment by nrajpurkar** [comment]
Hi @andreasbergqvist, this is correct. At this time, connecting to a new repo (or changed URL) in the same app will delete your prior build history. Another option to keep the history would be to create a new app connected to the new repo URL. However, this would require reconfiguring everything which I understand is less than ideal. I've added the feature request tag to this issue and we'll monitor this for the future.

**Comment by nrajpurkar** [comment]
@andreasbergqvist can you reach out to App Center support regarding this and have them connect you to Build support? You can reference this GitHub issue so they have context. We may have a workaround for this change.

**Comment by andreasbergqvist** [comment]
Hi, I started with reaching out to the support. They asked me to create an issue here =)

**Comment by nrajpurkar** [comment]
Apologies on the back and forth 🙁 Found your support thread and reached out there!

**Comment by DennisPan** [comment]
Close this as we are handling it via support

**Comment by anka-213** [comment]
So, is the current suggested path to do this by contacting support?

**Comment by andreasbergqvist** [comment]
> So, is the current suggested path to do this by contacting support?

I have an API endpoint that I received from support that did work. Not sure if the people at appcenter wnat me to share it? 😬

**Comment by DennisPan** [comment]
@anka-213 Working on a documentation update with the public API endpoint mentioned by @andreasbergqvist . In short you can use an API client to call `PATCH https://appcenter.ms/api/v0.1/apps/{owner_name}/{app_name}/repo_config`, with request body like:

```
{
   "repo_url": <new git url>
}
```

If unsure about the url format, check the response from `GET https://appcenter.ms/api/v0.1/apps/{owner_name}/{app_name}/repo_config` as a starting point. 

Other general information about App Center APIs: https://docs.microsoft.com/en-us/appcenter/api-docs/

Feel free to reach out to support if any question.

**Comment by aaronrogers** [comment]
When I perform a `GET` on `repo_config` I get an empty array back. 🤔Shouldn't I get back my current `repo_url`?

**Comment by tdevere** [comment]
Message from App Center support - if your URL is updated but you're still not seeing the change during build, make sure to hit "save & build" again from the build configuration page in the portal

**Comment by Hirurgo** [comment]
> @anka-213 Working on a documentation update with the public API endpoint mentioned by @andreasbergqvist . In short you can use an API client to call `PATCH https://appcenter.ms/api/v0.1/apps/{owner_name}/{app_name}/repo_config`, with request body like:
> 
> ```
> {
>    "repo_url": <new git url>
> }
> ```
> 
> If unsure about the url format, check the response from `GET https://appcenter.ms/api/v0.1/apps/{owner_name}/{app_name}/repo_config` as a starting point.
> 
> Other general information about App Center APIs: https://docs.microsoft.com/en-us/appcenter/api-docs/
> 
> Feel free to reach out to support if any question.

it's not work already =/

**Comment by gsgou** [comment]
@dennispan seems only GET, POST, DELETE are currently only available.

**Comment by milankamilya** [comment]
The correct curl is here. 
```sh
curl -g -X 'PATCH' \
'https://api.appcenter.ms/v0.1/apps/{owner}/{app}/repo_config' \
-H 'Content-Type: application/json' \
-H 'accept: application/json' \
-H 'X-API-Token: xxxxxxxxx' \
-d '{"repo_url": "https://github.com/{owner}/{repo}.git"}'
```

FYI, now, you can change GitHub url by disconnecting the previous url from the `build` tab.
