### ISSUE TITLE
[Question] Difference between Distribute > Groups and People > Distribution groups

### ISSUE THREAD

**Issue by gerjandev** [microsoft/appcenter#936]
Sorry if this is not the correct place, but: 

What is the difference between Org > People > Distribution groups and Org > App > Distribute > Groups?

**Comment by gkonterman** [comment]
And maybe a related question:

I have the following situation:

Customer A
Customer B

App A
v1.0
v1.1
 
Customer A should get App A v1.0
Customer B should get App A v1.1

What is the best way to do this?

**Comment by jwargo** [comment]
@gkonterman App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by patniko** [comment]
Hi @gkonterman , the org -> people -> groups section will create a distribution group across your apps underneath an org while the app one will only create a group specific to a single app.
