### ISSUE TITLE
Dashboard that will show all apps within an org and their current build progress/status

### ISSUE THREAD

**Issue by svenza** [microsoft/appcenter#937]
**Describe the solution you'd like**
A dashboard that will show all the apps within an org and their current status for if they are building/build time and also will show once it successfully builds or if it fails. Preferably with some sort of green/red color indicator so it is easy for anyone glancing up or walking by to see if there is a problem or not.

**Describe alternatives you've considered**
With how we are set up, we have 4 apps (which in reality is 4 configs of the same app), since everything for the builds is housed in App Center, we would have to open 4 different browser tabs and use a 3rd party tab rotator to show similar data, which even then the build screen with multiple branches can be a little tricky to tell if there's an issue or not.

**Additional context**
We have multiple monitors throughout the building showing dashboards of our websites pipeline status and health. We'd like to do the same for the mobile app so problems can be easily identified.

**Comment by amchew** [comment]
Thanks for your suggestion @svenza! I can see that being important. This is not currently on our roadmap, but we'll keep this ticket open to gauge community interest. In the meantime, I'll let @baileybrooks and @nrajpurkar comment with more details.

**Comment by akiwarheit** [comment]
I believe this is possible with the current APIs - surely someone out there has made some dashboard.

**Comment by phatmann** [comment]
The build statuses are buried deep within each app/Build/branch screen. An overview would be soooo helpful.

**Comment by phatmann** [comment]
All we need is are 2 additional columns on the Overview page, one that shows current release number and one that shows build status. The build status should be either "success" if there are no failures in any branches or "fail" if any branches have failed.
