### ISSUE TITLE
Xamarin App's PackageId/BundleId is not shown.

### ISSUE THREAD

**Issue by pkvaranasi** [microsoft/appcenter#938]
As the Apps are being moved from HockeyApp, and AppCenter is not asking for PackageId/BundleId, suggested to show the PackageId/BundleId in the Overview/Settings of the app in AppCenter.

**Comment by amchew** [comment]
Thanks for the suggestion! Would you mind elaborating on why getting the PackageId/BundleId is important and your user scenario? In the meantime, I'll let @baileybrooks jump in with any additional details or suggestions.

**Comment by pkvaranasi** [comment]
Hi,
As we have multiple environments, and the name of the Apps are same, it would be good to differentiate by the PackageId/bundleId.
I knew that there is a drop-down - Release Type, but we have different env under each Release Type.
