### ISSUE TITLE
"Unsymbolicated" "Issues" aren't included in "Crashes", and there is no filtering/sorting available

### ISSUE THREAD

**Issue by martinbonaciugome** [microsoft/appcenter#939]
**Describe the solution you'd like**
"Unsymbolicated" "Issues" aren't included in "Crashes", which makes it incorrect in assessing app health. "Unsymbolicated" "Issues" also can't be sorted by date or filtered by build, so its impossible to find if there are new issues with a new build

**Comment by adriavernetta** [comment]
We're facing the same issue on our side, having transitioned forcedly to App Center and losing the diagnostics capabilities of accurate crash gathering (we see discrepancies of having "lost" 80% of crashes). 

We consider that, at least, we should be given the option to add or not the unsymbolicated crashes in the data metrics.

**Comment by winnie** [comment]
Hello! You can now view unsymbolicated crashes in the Diagnostics page and these will be reflected in the total count. The same filtering and sorting behavior applies to all crash groups, both symbolicated and unsymbolicated.

You can also continue to manage missing symbols in the Unsymbolicated tab and we will symbolicate crashes once we have the right symbol files. Hope this improves your experience using App Center. Thanks for the patience!
