### ISSUE TITLE
Incorrectly transforming the case in properties keys in event and custom-property logs

### ISSUE THREAD

**Issue by hamswan** [microsoft/appcenter#94]
**What App Center service does this affect?**
App Center Analytics

**Describe the bug**
Currently App Center incorrectly transforms the properties keys in event and custom-property logs.

This can be seen in the pipeline:  LogFlow, Export.

This mainly affects when customers are using Export.

Few examples:
•	Test -> test
•	TEST -> tEST
**Expected behavior**
The case should not be changed and should be left as is.

**Comment by hamswan** [comment]
For customers affected by this issue, The casing issue has been fixed. We are providing 90 days to ensure that you have enough time to validate your queries.
Please test and adjust your existing queries accordingly. If you run into issue, please contact us through our support team (blue chat bubble on the bottom right).

**Comment by myokeeh** [comment]
I'm seeing a similar issue where custom properties I've set are changed to pageName -> PageName, loadTime -> LoadTime in the logs.v1.data files between Aug 13 and Aug 14 and returned to normal after.
