### ISSUE TITLE
Allow adding GitHub submodules to build settings

### ISSUE THREAD

**Issue by zippo227** [microsoft/appcenter#942]
**Describe the solution you'd like**
The Build tab will allow you to connect to multiple repositories to ensure that private submodules can be used.

**Describe alternatives you've considered**
I tried setting up separate builds for the submodules in hopes that the added webhook would allow my project to be built.

**Additional context**
We share a few private submodules between our projects, and we need to be able to clone those during the build.

**Comment by jmzorko** [comment]
Also, github requiring 2FA now means that user / pw in a build script won't work. While it's possible to clone via SSH, that requires that the private key be stored in some persistent env variable on AppCenter, which gives me pause.

**Comment by johnnyzen** [comment]
Any update on this? I am unable to use appcenter build process because of submodule errors?

**Comment by mochsner** [comment]
Why was this closed as completed...?

**Comment by amsmokefree** [comment]
This will be really handle for projects with multiple repos, please consider it.
