### ISSUE TITLE
Windows Service App Center support for Crashes/Errors

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter#943]
**Describe the solution you'd like**
Windows Service App Center support for Crashes/Errors. Basically we have a windows service that does a few different actions. Such as e-mailing reports on a schedule. the errors for this are currently entered into event log, but as this is often installed on a server, it can be hard to know there have been any errors.

**Describe alternatives you've considered**
Currently get logged in Event Viewer for our background service.

**Additional context**
If this worked we would be aware of current errors, versions etc and be able to fix them sooner.

**Comment by winnieli1208** [comment]
Hey @james1301 which SDK are you currently using for your Service app? We don't currently support "services" but I'd be interested in learning more about your scenario. We can chat more in our call or via this thread. Thanks!

**Comment by james1301** [comment]
Hi @winnieli1208 we are created a c# Console Application essentially. Using the Visual Studio 'Windows Service' Template. If that answers your question?

**Comment by james1301** [comment]
But yeah can discuss more on our call.

**Comment by mheijkant** [comment]
With your coming support for windows WPF, i would also like to have support for windows service app's. Our client/server (service) solution for internal use will then have full diagnostic and analytics support.

**Comment by thudugala** [comment]
Hi @winnie, It would be nice to have this feature. As I have many c# Console Application

**Comment by james1301** [comment]
Any more feedback on this issue would be hgood

**Comment by waltergrimmvie** [comment]
Has there been any further updates on how to add the app center for .net Windows services please, I could really use this

thanx
