### ISSUE TITLE
Be able to set thresholds for crash group email notifications

### ISSUE THREAD

**Issue by svenza** [microsoft/appcenter#945]
**Describe the solution you'd like**
Currently, when crash group email notifications are enabled, you get an email when one single crash occurs. There should be an option to set how many crashes need to occur before it is considered a 'group'

**Describe alternatives you've considered**
From what support has informed me, there aren't any other options than turning the notification off and manually checking it from the site each day, which I'd rather know when there is a serious problem in real-time by setting thresholds, especially for folks monitoring email after hours.

**Additional context**
Getting an email for each crash can get a bit 'spammy' and hard for us to tell when there's a serious problem. Each org should be able to determine what thresholds they consider a true problem or is a one-off user with an older device having issues or some strange edge case that can be reviewed during normal business hours.

**Comment by yoannchaudet** [comment]
Closing as "duplicate" to: https://github.com/microsoft/appcenter/issues/901.

**Comment by florianbuerger** [comment]
Where do I find that setting? The linked issue #901 is about connected bug trackers not email notifications, so is the linked documentation. So I believe this is should be re-opened.

I would love to see a setting that email notifications are only sent when the number of crashes in a group crosses a defined threshold.

**Comment by winnie** [comment]
Hi @florianbuerger - you're right, this isn't available for email notifications. I'm re-opening this issue and modifying the title to be more clear. Thanks!
