### ISSUE TITLE
Make different payment options available

### ISSUE THREAD

**Issue by malouly** [microsoft/appcenter#949]
**Describe the solution you'd like**
As Azure subscriptions is ONLY available on 88 countries, this deprives many users from the ability to leverage VS App Center. We would like to be able to create an account from regular credit cards like many other Microsoft platforms do (Office365, Skype) OR have the link to Microsoft Store
 
**Describe alternatives you've considered**
We have no alternative solution as the link to Azure is the unique way by which you can subscribe to build/test plans .

**Additional context**
N/A

**Comment by amchew** [comment]
Hi @malouly, thanks for reaching out, and I see your point. [Azure billing is currently commercially available in 140 countries and regions ](https://azure.microsoft.com/en-us/free/free-account-faq/), and most of what App Center offers is backed by Azure. May I ask what region you are currently in?

In the meantime, I'll let @ricduong and @Zakeelm add more details about billing.

**Comment by malouly** [comment]
Thank you very much,

 

I’m from Mauritania (west Africa :  <https://en.wikipedia.org/wiki/Mauritania> https://en.wikipedia.org/wiki/Mauritania ) and we don’t see our country name in the supported countries list. We appreciate very much your help to include it to the list.

 

 



 

Cordialement / Best regards

LOULY  Mohamed-Abdallahi

Directeur Général / CEO

GTI international (GTI)

Tel : (+222)  26 300 300 

ma.louly@gti-intl.com <mailto:ma.louly@gti-intl.com>    |   http://www.gti-intl.com <http://www.gti-intl.com/> 

 

De : Amanda Chew <notifications@github.com> 
Envoyé : jeudi 29 août 2019 22:52
À : microsoft/appcenter <appcenter@noreply.github.com>
Cc : malouly <ma.louly@gti-intl.com>; Mention <mention@noreply.github.com>
Objet : Re: [microsoft/appcenter] Make different payment options available (#949)

 

Hi @malouly <https://github.com/malouly> , thanks for reaching out, and I see your point. Azure billing is currently commercially available in 140 countries and regions  <https://azure.microsoft.com/en-us/free/free-account-faq/> , and most of what App Center offers is backed by Azure. May I ask what region you are currently in?

In the meantime, I'll let @ricduong <https://github.com/ricduong>  and @Zakeelm <https://github.com/Zakeelm>  add more details about billing.
