### ISSUE TITLE
More flexibility around device provisioning (single registration / deletion)

### ISSUE THREAD

**Issue by andysousa** [microsoft/appcenter#951]
As it currently stands, you are only able to register/provision all un-provisioned devices or none at all.  The ability to register individual devices or even simple be able to delete un-provisioned devices would be huge beneficial.

Apple only gives us 100 device registrations a year and many times I have testers out there who add devices that they shouldn't be.  Once this happens, I am stuck and can't provision devices that need to be because I don't want to burn through apple registrations.

Had a great convo on twitter with @lbcpat, here is a link for further details.
https://twitter.com/lbcpat/status/1166494141880029184

So the ask here:
1) Add the ability to provision/register (and resign) individual devices
2) Delete devices
3) (NICE TO HAVE, not sure its feasible) - manually sign the app... if someone registers in the apple dev site

**Comment by Oddj0b** [comment]
Thank you for the feature request.

Regarding the device deletion, it's only possible once a year. So I would propose to have a system that removes all devices and only add that is in distribution groups that has **Automatically manage devices** enabled. Would that work for you?

**Comment by andysousa** [comment]
just checking in to see if there was ever any movement on this?

**Comment by Oddj0b** [comment]
@andysousa Sorry, but the main work have been put into Hockey App. I will talk to the responsible people to find out what is possible.

**Comment by GoMino** [comment]
this is a real limitation

**Comment by iolabs-will** [comment]
Is this implemented or why is it closed?

**Comment by ProfMStoica** [comment]
Developers can remove their own devices from their User Profile->Account Settings->My Devices. This helps if it is your own dev device that you want to register. The development team however should have the possibility of removing any device that is no longer necessary or used. Examples are old devices, or devices from testers that are no longer part of the time. Lastly, it is useful to test deployment devops pipelines.
