### ISSUE TITLE
Rename “Closed” in Crash Groups to “Resolved”

### ISSUE THREAD

**Issue by shpakovski** [microsoft/appcenter#952]
**Describe the solution you'd like**

What do you think about renaming a “Closed” status name of a Crash Group to “Resolved”?

**Comment by amchew** [comment]
Thanks @shpakovski for the suggestion! @winnieli1208 could you please take a look?

**Comment by winnieli1208** [comment]
I think that's a valid suggestion! @shpakovski what does "Resolved" mean to you compared to "Closed"?

**Comment by shpakovski** [comment]
Thanks for getting back to me!

1. It means that code was Fixed or Rewritten.
2. It means that it is **not** Ignored.
