### ISSUE TITLE
No support for Custom Platforms

### ISSUE THREAD

**Issue by gautamkrishnar** [microsoft/appcenter#953]
In Hockeyapp there were an option to use custom platform if we need to add any apps/sdks that are not supported by it, App Center doesn't have that option.

Please see the screenshot below:
![Screenshot 2019-08-28 at 2 38 37 PM](https://user-images.githubusercontent.com/8397274/63842182-c85d8300-c9a1-11e9-90ef-c21aef680c13.png)

This was a crucial feature of hockeyapp, I can't see it anywhere in the roadmap of the appcenter. It was extensively used by us to upload artifacts and sources of the platforms that are not supported by the hockeyapp for example: Tizen,  LG WebOs etc. I think this feature must be included in the appcenter as well.

**Comment by nrajpurkar** [comment]
@gautamkrishnar thanks for the feature request. Tapping in @derpixeldan to take a closer look. Additionally, when creating a new app in App Center, there's a place at the bottom to let us know if you'd like to see a platform that isn't available. This doesn't let you add the app, but certainly helps us understand what other platforms to support. 
![image](https://user-images.githubusercontent.com/12765610/63979487-d8429900-ca6d-11e9-9486-31dab7d97a00.png)

**Comment by derpixeldan** [comment]
@gautamkrishnar closing this as it's tracked here https://github.com/microsoft/appcenter/issues/464
