### ISSUE TITLE
Distribution of .aab files

### ISSUE THREAD

**Issue by msioen** [microsoft/appcenter#955]
**Describe the solution you'd like**
Follow-up issue of released feature https://github.com/microsoft/appcenter/issues/194

We're currently not yet using App Center for running our builds, nor to distribute artifacts to the stores. We are however using it to track and distribute builds to the team and testers.

It's currently already possible to upload a .aab file to a release through the api. It's impossible to make this file visible to anyone. (The release exists and if you go to the url with the release number it does show the release where you're able to download the .aab but distribution is not possible)

We're not looking to be able to install this .aab file through app center, we would however like to be able to make it visible somehow so it can be downloaded later on in the process so we can keep all our bits in one place to avoid having artifacts all over the place.
This also allows us to analyze the files afterwards to see the difference between versions for example.

The distribution we'd love to have is not to testers or externals but just to the project collaborators. It's ok if it's not visible on 'install.appcenter.ms' but would ideally be visible on 'appcenter.ms' somehow.

**Comment by amchew** [comment]
Thanks for your feature request @msioen! @dimazaid @botatoes would you be able to take a look?

**Comment by randomaspirer** [comment]
We use app center to distribute builds to our collaborators it would be nice if they can have option to install .aab file instead of .apk as we want app center to be replicate our google playstore builds which uses android app bundles.

**Comment by jahmai** [comment]
I would also like to distribute .aab's through appcenter for testing like you can with .apk's. Whether that's converting the .aab to .apk behind the scenes and distributing the appropriate .apk for a particular device, or somehow be able to distribute the .aab itself to devices.

**Comment by glintpursuit** [comment]
This feature is already available & we are using to get react base android app .aab to >> play store from App Center. 

But unfortunetly Xamarin Android build breaks on enabling .aab to true :-(.

**Comment by jahmai** [comment]
@glintpursuit This feature request is for distributing .aab from AppCenter to AppCenter test users, not from AppCenter to Google Play.

**Comment by afreenhossain** [comment]
We also use app center to just distribute builds, and waiting for the ability to upload .aab files. We are not looking into installing it yet, but we want testers to be able to download it at least.

**Comment by ieduardogf** [comment]
Hi!
Any news about this? As many others, we were also using App Center as a way to upload .abb files and distribute them (using the custom project type) but that not longer works.
Any plan to support upload and distribute to other testers .abb files?
Thanks!

**Comment by gmerinojimenez** [comment]
Same here, 

we were using HockeyApp to distribute aab files and now that important feature is missing. Can you allow to upload them?

Thanks!

**Comment by Charis1331** [comment]
Do we have an ETA on this?

**Comment by VictorCorchezFortech** [comment]
any news on this? looking forward to have this in app center. also a good idea would be to permit the user/tester to choose which abi/screen density wants to have it generated from the aab. If the tester only has a 64bit phone to be able to test the 32bit as well

**Comment by Charis1331** [comment]
Anything on this?

**Comment by alexsorokoletov** [comment]
That would be a great feature!
AppCenter can already build AAB files but the distribution gets the APK files only :(

**Comment by Krzysztof-Kabala-Gain** [comment]
There is a new requirement on Google Play Store: from August 2021 only .aab files can be uploaded, therefore can we expect this will be resolved until that time?

**Comment by never00miss** [comment]
Is there any info for this? 
we do all automation work in appcenter, but suddently, they upload out universal-<name>.apk, instead of .aab file to playstore

**Comment by adroitandroid** [comment]
hi everyone following this issue. It seems we need to go and upvote https://github.com/microsoft/appcenter/issues/1288 as well for it to be prioritised. Kindly do that

**Comment by piphagor** [comment]
> hi everyone following this issue. It seems we need to go and upvote #1288 as well for it to be prioritised. Kindly do that

How could we do it? Just put 👍 to it?

**Comment by adroitandroid** [comment]
> > hi everyone following this issue. It seems we need to go and upvote #1288 as well for it to be prioritised. Kindly do that
> 
> How could we do it? Just put 👍 to it?

yes

**Comment by Simulacrux** [comment]
So Google also send out this message in the PlayStore:

> Starting August 2021, new apps will be required to target API level 30 (Android 11) and use the Android App Bundle publishing format. Starting November 2021, all app updates will be required to target API level 30 (Android 11).

As it a bit unclear if the .abb files also start in November for all apps, but time will run out for this issue.

**Comment by adroitandroid** [comment]
> So Google also send out this message in the PlayStore:
> 
> > Starting August 2021, new apps will be required to target API level 30 (Android 11) and use the Android App Bundle publishing format. Starting November 2021, all app updates will be required to target API level 30 (Android 11).
> 
> As it a bit unclear if the .abb files also start in November for all apps, but time will run out for this issue.

Their communication confirms that AAB is needed by the deadline for new apps. Existing apps need not move mandatorily to AAB just yet.

**Comment by ostannar** [comment]
Is there any news on this yet?

**Comment by LDan1117** [comment]
any news?

**Comment by skubo** [comment]
I got following answer from Microsoft Appcenter support:

Hi there, Thanks for writing to us! Currently, upload aab to the app center groups is not supported.Do you mind making your feature request on our Github repo:&nbsp;https://github.com/Microsoft/appcenter/issuesYou may also search there to see if it has already been submitted. In that case, please&nbsp;&nbsp;the issue to show your interest.Regards,Anvesh
--

**Comment by jahmai-ca** [comment]
So if I understand this correctly, as of August AppCenter will be unusable for new Android apps and therefore won't be able to grow it's customer base. Isn't that... kind of a major problem for the AppCenter team? That's 2 months away!

**Comment by robinfischerinnogames** [comment]
While I also want this feature I just wanted to say that I don't think AppCenter will be unusable. 

Just because Google Play only accepts the AAB format does not mean you can't still create an .apk and install that on devices via AppCenter.
Similar to this other AppStores like Amazon Kindle Store also only accept .apk files AFAIK.

We are already doing it this way. Building .apk files for AppCenter/Amazon and building .aab files for Google Play. 

I want to simplify things and just create one .aab file that can go to AppCenter and Google Play so this feature request is valid.

**Comment by timvandenhof** [comment]
> While I also want this feature I just wanted to say that I don't think AppCenter will be unusable.
> (...)
> I want to simplify things and just create one .aab file that can go to AppCenter and Google Play so this feature request is valid.

I agree that it is indeed possible to use App Center with APK's. From a testing perspective it is quite strange to test a APK build and then ship a different binary, the AAB. Especially if you only target Google Play as an app store.

**Comment by jahmai-ca** [comment]
> While I also want this feature I just wanted to say that I don't think AppCenter will be unusable.
> 
> Just because Google Play only accepts the AAB format does not mean you can't still create an .apk and install that on devices via AppCenter.
> Similar to this other AppStores like Amazon Kindle Store also only accept .apk files AFAIK.
> 
> We are already doing it this way. Building .apk files for AppCenter/Amazon and building .aab files for Google Play.
> 
> I want to simplify things and just create one .aab file that can go to AppCenter and Google Play so this feature request is valid.

Yes I see, and that's a fair enough workaround. But one of the features of AppCenter is that it deploys to the store on your behalf, which would break right?

**Comment by robinfischerinnogames** [comment]
> > While I also want this feature I just wanted to say that I don't think AppCenter will be unusable.
> > Just because Google Play only accepts the AAB format does not mean you can't still create an .apk and install that on devices via AppCenter.
> > Similar to this other AppStores like Amazon Kindle Store also only accept .apk files AFAIK.
> > We are already doing it this way. Building .apk files for AppCenter/Amazon and building .aab files for Google Play.
> > I want to simplify things and just create one .aab file that can go to AppCenter and Google Play so this feature request is valid.
> 
> Yes I see, and that's a fair enough workaround. But one of the features of AppCenter is that it deploys to the store on your behalf, which would break right?

I think this was handled with this issue: https://github.com/microsoft/appcenter/issues/194
Doc link: https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay#publish-your-aab-to-the-google-play-store

Our team does not use this feature so please re-check this information. But it seems that publishing of AAB files is supported.

**Comment by jahmai-ca** [comment]
It's not stale bot, see? *freshen's up the place*

**Comment by jahmai-ca** [comment]
I am still interested in submitting .aab to AppCenter, cheers msftbot

**Comment by quentinR0bert** [comment]
Any news about this ? Because we have a very strange repro from AppCenter.

For some days we have see that AppCenter allow the upload of AppBundle for the Distribute part, so we were like "yes ! let's go ! Let's try and remove BundleTool from our CI if it's okay".

When we upload manually a AppBundle, it's okay and when we go to the url with a phone when we download we get an apk (an universal we suppose).

And when we upload from appcenter-cli it's okay, but when we go to the url with a phone when we download we only get the AppBundle file ! Why ?

**Comment by icyleaf** [comment]
Hello everyone, I would like to recommend an open source project zealot, the latest release 4.3.0 version already supports .aab file format upload and parsing, the project supports docker self-deployment is very simple, welcome feedback on any suggestions: https://github.com/tryzealot/zealot

**Comment by quentinR0bert** [comment]
Well no, we not forget, like here https://github.com/microsoft/appcenter/issues/1288

**Comment by nihartsx** [comment]
+1

**Comment by RelMAnton** [comment]
Are such reported tickets marked as feature request looked followed up further in general or we need to use the different channels of communication? 3 years and attempts not to keep it stale sound concerning.

**Comment by bboles** [comment]
@botatoes or @dimazaid can we get and update on this issue?

**Comment by RelMAnton** [comment]
to remove stale status and finally get any progress on it

**Comment by FreakyAli** [comment]
Is this every getting fixed?

**Comment by adroitandroid** [comment]
hi y'all, personally I'd recommend moving to play store itself from appcenter, it give everything you need for the testing and easy to integrate in CI/CD, early reviews (from closed track onwards itself) etc. at least at my company we're not missing appcenter since, the move is quick and resolves this annoying issue.

**Comment by FreakyAli** [comment]
This is just sad

**Comment by RelMAnton** [comment]
is there a way to change assignees? we're not progressing with this issue further at all

**Comment by FreakyAli** [comment]
It's sad to see such a great tool die but we'll! No can do i suppose

**Comment by RelMAnton** [comment]
@botatoes @dimazaid do you have any news here?

**Comment by RelMAnton** [comment]
@botatoes @dimazaid  can you please take this up or change assignees?
