### ISSUE TITLE
Icon of android app not showing on App Center

### ISSUE THREAD

**Issue by Ishita-Pandey** [microsoft/appcenter#958]
I have added the app icon as a vector drawable instead of a .png in my android app.
From my earlier discussion with the AppCenter support team, I learnt that vector drawables are not considered while extracting the icon to show on install.appcenter.ms if it's provided via vector drawables.

Vector drawables are the recommended way of developing for several reasons [https://developer.android.com/guide/topics/graphics/vector-drawable-resources]

I strongly encourage AppCenter to take this consideration in to account

**Comment by amchew** [comment]
Thanks @prettypancakes for the feature request! @botatoes would you mind taking a look?

**Comment by botatoes** [comment]
Noted and in the backlog. We will prioritize this accordingly.

**Comment by Ishita-Pandey** [comment]
Closing this issue as the request was catered.
Thanks team for looking into this!

**Comment by ramit-2343113** [comment]
Is see this ticket was closed. Has this been implemented?
