### ISSUE TITLE
Android keystore credentials available as env variables from build config

### ISSUE THREAD

**Issue by antpuleo2586** [microsoft/appcenter#959]
**Describe the solution you'd like**
I'm building and uploading a test app for Detox ui testing via Bitbar in my post-build script.
This involves signing the test app with the keystore. However, even though I've entered the credentials into the build configuration, I don't have access to them during the build.

**Describe alternatives you've considered**
I've had to add all the keystore credentials again as env variables, accessing during the build that way, but this seems like a redundant duplication.

**Comment by amchew** [comment]
Thanks @antpuleo2586 for the request! @nrajpurkar would you mind taking a look?

**Comment by nrajpurkar** [comment]
Thanks for the feature request. The alternative described is the current expected behavior. Understand how exposing signing credentials as variables could make streamline this process. We'll keep the feature request open to track additional interest.
