### ISSUE TITLE
Regression: the button for installation in an e-mail for a release no longer downloads

### ISSUE THREAD

**Issue by ddobrev** [Microsoft/appcenter#96]
**What App Center service does this affect?**
Distribution.

**Describe the bug**
When a release is made, App Center sends an e-mail. This button contains a button called "Install" which used to download the uploaded package (such as .apk for Android) when clicked from a PC. Now it just says "Package incompatible" and has the button for downloading disabled.

**To Reproduce**
1. Publish a release
2. Wait for the e-mail
3. Click the "Install" button in the e-mail

**Expected behavior**
The button takes to a page where the package for the release can be downloaded.

**Screenshots**
<img width="713" alt="screenshot 2019-02-22 at 16 29 13" src="https://user-images.githubusercontent.com/5193072/53248725-0e6a1f00-36bf-11e9-8eeb-b2894c6fe1ba.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser Firefox 65.0.1

**Additional context**
This used to work and broke two months ago. I reported it to your chat at https://intercom.help/appcenter/ and nobody took any action whatsoever.

**Comment by patniko** [comment]
Referencing #82 - will get this addressed in our next iteration.

**Comment by patniko** [comment]
This link should again be active for you to download apk's for sideloading.
