### ISSUE TITLE
react-native-maps failing while build

### ISSUE THREAD

**Issue by amarjeet89** [microsoft/appcenter#960]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Oddj0b** [comment]
App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
