### ISSUE TITLE
In App center events page should we able to see the Device information about particular event ?? 

### ISSUE THREAD

**Issue by galla-devlop** [microsoft/appcenter#961]
Is it possible to see the device information in app center event page ..??

Example :
i have 10 user, they are using my application and i am getting the events from the 10 devices. But i want to know from which device which event has occurred and which version that user is using like this i want information. 

Could please let me as soon as possible ..
Thank you in advance.

**Comment by amchew** [comment]
Thanks @galla-devlop for the question! @hamswan would you be able to take a look please?

**Comment by yoannchaudet** [comment]
Our analytics module counts and aggregates your events but does not keep track of them individually.

You can identify which exact device sent an event by looking at the actual SDK logs using our [Export](https://docs.microsoft.com/en-us/appcenter/analytics/export) feature.
