### ISSUE TITLE
W/System.err( 6127): remove failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/appcenter#964]
During app initialization on android, before I get to the MainPage I get following error: 08-30 13:46:19.081 W/System.err( 6127): remove failed: ENOENT (No such file or directory) : /data/user/0/com.app.myapp/files/appcenter/database_large_payloads/group_analytics/10.json
After this the splashscreen stays on my screen until I kill the app, if I press pause in visual studio, I don't see any c# threads, I only see a worker thread
Not Flagged        6    0    Worker Thread        System.Threading.WaitHandle.Wait_internal()
                              [External Code]

**Comment by hamswan** [comment]
Thanks for reporting , we will take a look at this. Looks like you already created on https://github.com/microsoft/appcenter-sdk-android/issues/1233/

I will close this one as we are following this up in our SDK board.
