### ISSUE TITLE
Xcode 11 Support to distribute .xcarchive.zip file instead of .ipa

### ISSUE THREAD

**Issue by lilyngabichtranADBE** [microsoft/appcenter#965]
+1 **Be able to upload the application.xcarchive.zip file to HockeyApp**
With xcode11, we will now have to deliver to Apple .xcarchive bundle.  We would like to be able to post the same .xcarchive bundle to HockeyApp.  Currently with Xcode 10 and below, we are posting .ipa.

**Comment by amchew** [comment]
Thanks for the feature request @lilyngabichtranADBE! We're currently in the midst of [deprecating HockeyApp by Nov, 2019](https://hockeyapp.net/blog/2018/11/16/thanks-hockeyapp-app-center-will-take-it-from-here.html), so if anything, this feature will be implemented in App Center.

In the meantime, I'll let @derpixeldan and @botatoes share more details.

**Comment by BinkanSalaryman** [comment]
@derpixeldan HockeyApp used to (and still does) accept a .xcarchive.zip file... Would be cool if that were a feature in AppCenter too.

**Comment by derpixeldan** [comment]
@blinkansalaryman I do see that the journey goes towards xcarchive.zip files but it requires us to process the contents of the file to serve the right .ipa to the right device when it comes to downloading/installing. On HockeyApp it's not possible to upload xcarchive.zip for iOS apps.

**Comment by derpixeldan** [comment]
@BinkanSalaryman I do see that the journey goes towards xcarchive.zip files but it requires us to process the contents of the file to serve the right .ipa to the right device when it comes to downloading/installing. On HockeyApp it's not possible to upload xcarchive.zip for iOS apps.

**Comment by BinkanSalaryman** [comment]
@derpixeldan Ok, I'm not 100% sure what the issue is with it. But as a user, I can confirm that HockeyApp does have support for Xcode Archive files. Take a look here: https://hockeyapp.net/releases/mac/

![image](https://user-images.githubusercontent.com/6740731/64416420-6c78b580-d097-11e9-9109-86b763f80be8.png)
![image](https://user-images.githubusercontent.com/6740731/64416431-73072d00-d097-11e9-82b7-40df08b92850.png)

**Comment by derpixeldan** [comment]
@BinkanSalaryman that's the HockeyApp macOS app that handles the archive to extract the ipa and symbols and uploads them, however, HockeyApp itself does not support to upload/distribute .xarchive.zip. The .zip in the second screenshot is referring to macOS apps and is just an example. You cannot upload .zip for iOS apps.
