### ISSUE TITLE
Support for Test Runs with Android App Bundle (.aab)

### ISSUE THREAD

**Issue by Swiftless** [microsoft/appcenter#968]
**Describe the issue experienced**
Attempting to run a UITest via Azure Pipelines on a build that produces a .aab file results in:

> Validating application file... failed.
> Error: The application file must be either Android or iOS application

**Describe the solution you'd like**
For the application file to successfully validate, required apk files to be extracted and tests to be run.

**Describe alternatives you've considered**
Modifying the pipeline to use a different build configuration that produces an .apk file however this doesn't test against the final distributed app bundle.

**Additional context**
It is preferable to run tests against the final distributable and while it may not be an issue in the future, I personally experienced the "Internal Only" issue seen here that was only applicable on the .aab file (my .apk file was fine and tests against the .apk file were fine but Google has suggested no longer using them for distribution):
[https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.4#known-issues-2](https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.4#known-issues-2)

**Comment by blparr** [comment]
Hello @Swiftless , thanks for your request. @Oddj0b can you take a look at this ticket?

Thanks!

**Comment by Oddj0b** [comment]
This is a great feature request, thanks for creating it. It's not on our immediate roadmap, but I'm hoping it will amass enough reaction to be taken into consideration.

**Comment by uwe-neuronation** [comment]
Since Xamarin.Android 10.1 now fully supports the AAB-System, it's the time to also support that on  the tests.

**Comment by sonjz** [comment]
no support yet, possible workaround if you are stuck with upgraded aab for now.
https://github.com/microsoft/appcenter/issues/194#issuecomment-852398672

NOTE: I recall last month when setting SDK 30, there were signing issues though and had to downgrade to API 29 for apks going to appcenter for testing.  this test gave me the same result i was getting from appcenter response.
```
apksigner verify --in gov.troyny.recollect.waste-test.apk --min-sdk-version 16 --max-sdk-version 30
DOES NOT VERIFY
ERROR: JAR signer PLAYSIGN.RSA: JAR signature META-INF/PLAYSIGN.RSA uses digest algorithm SHA-256 and signature algorithm RSA which is not supported on API Level(s) 16-17 for which this APK is being verified
```

**Comment by Swiftless** [comment]
Any updates on whether this will be addressed?

**Comment by Hackmodford** [comment]
Just ran into this issue.
