### ISSUE TITLE
 Regression: the e-mail for a release no longer lists the release notes

### ISSUE THREAD

**Issue by ddobrev** [microsoft/appcenter#97]
**What App Center service does this affect?**
Distribution.

**Describe the bug**
When a release is made, App Center sends an e-mail. This e-mail used to contain the release notes. Now it doesn't.

**To Reproduce**

    1. Publish a release

    2. Wait for the e-mail

**Expected behavior**
The e-mail contains the notes to the release.

**Screenshots**
<img width="385" alt="screenshot 2019-02-22 at 16 35 11" src="https://user-images.githubusercontent.com/5193072/53249073-e16a3c00-36bf-11e9-8e99-1ad76fd2a28e.png">

**Desktop (please complete the following information):**

    * OS: macOS 10.14.3

    * Browser Firefox 65.0.1

**Comment by botatoes** [comment]
Hi @ddobrev 
We couldn't repro the issue. Can you tell me a little more about the app or if you're still experiencing the issue?

**Comment by botatoes** [comment]
Closing this for now. Feel free to create a ticket on intercom on appcenter.ms so we can help you further.
