### ISSUE TITLE
Add React Native support for tvOS apps

### ISSUE THREAD

**Issue by jarnzeninen** [microsoft/appcenter#971]
**Describe the solution you'd like**
We need the ability to create tvOS apps built on React Native. We'd like to have React Native offered as a Platform option when adding tvOS apps in AppCenter. That is currently only available of iOS apps, not tvOS apps.

**Describe alternatives you've considered**
We are currently investigating the use of a post-clone build script to install React Native dependencies.

**Comment by nrajpurkar** [comment]
@jarnzeninen thanks for the feature request! Are you only interested in Build services for tvOS or are you also interested in the other services App Center has to offer for tvOS apps? Additionally, if you do get a build script working, it would be awesome for you to contribute that to the [public community driven build scripts](https://github.com/microsoft/appcenter/tree/master/sample-build-scripts) in this repo!

**Comment by jarnzeninen** [comment]
@nrajpurkar We're interested in Code Push, App Store distribution, and analytics and diagnostics features, in addition to build services.

I didn't realize until after submitting this feature request that AppCenter doesn't currently support even native builds for tvOS, so adding that would be a good first step :-) Without that, we can't try the alternative approach described above. Should I enter another feature request for native tvOS build support?
