### ISSUE TITLE
React Native iOS: follow example for appcenter-post-clone.sh but got "sed: Podfile.lock: No such file or directory"

### ISSUE THREAD

**Issue by tientruongvan1995** [microsoft/appcenter#973]
**Issues**
File: [appcenter-post-clone.sh](https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/ios/match-cocoapods-version-to-lockfile/appcenter-post-clone.sh)
As title, I followed the example and still got 

> sed: Podfile.lock: No such file or directory

**Solution**
I created `appcenter-post-clone.sh` beside my project `package.json`. Make sure that you already have Podfile.lock in your project's `ios` folder. I actually change `Podfile.lock` path then check cocoapod versions for general purpose. Hope to help you guys
```bash
#!/usr/bin/env bash
CUR_COCOAPODS_VER=`sed -n -e 's/^COCOAPODS: \([0-9.]*\)/\1/p' ios/Podfile.lock`
ENV_COCOAPODS_VER=`pod --version`

# check if not the same version, reinstall cocoapods version to current project's
if [ $CUR_COCOAPODS_VER != $ENV_COCOAPODS_VER ];
then
    echo "Uninstalling all CocoaPods versions"
    sudo gem uninstall cocoapods --all --executables
    echo "Installing CocoaPods version $CUR_COCOAPODS_VER"
    sudo gem install cocoapods -v $CUR_COCOAPODS_VER
else 
    echo "CocoaPods version is suitable for the project"
fi;
```

**Environment**
- MacOs version 10.14.6 
- Xcode 10.3
- CocoaPods 1.7.5
- React Native: 0.60.5

**Comment by nrajpurkar** [comment]
Thanks for the suggestion @tientruongvan1995! Do you mind making a [PR](https://github.com/microsoft/appcenter/tree/master/sample-build-scripts/ios/match-cocoapods-version-to-lockfile) with the additional changes you had to make as an example for others who may have the same issue?

**Comment by tientruongvan1995** [comment]
thanks for notice, but this case is for React Native, I wonder if it works with another platform, so I think I cannot make a PR for it

**Comment by tientruongvan1995** [comment]
> Thanks for the suggestion @tientruongvan1995! Do you mind making a [PR](https://github.com/microsoft/appcenter/tree/master/sample-build-scripts/ios/match-cocoapods-version-to-lockfile) with the additional changes you had to make as an example for others who may have the same issue?

thanks for notice, but this case is for React Native, I wonder if it works with another platform, so I think I cannot make a PR for it, I need some like/agreement to do that
