### ISSUE TITLE
Release notes Textile formatting

### ISSUE THREAD

**Issue by RAM237** [microsoft/appcenter#975]
**Describe the solution you'd like**
Each Release has Release notes, the Textile formatting used for them in HockeyApp is completely messed up in AppCenter, this definitely needs to be fixed, so that it looks **exactly the same** as it was in HockeyApp.
It seems Textile formatting is not supported in AppCenter at the moment (probably only Markdown?), so it is required to implement it and consider the original Release notes formatting when migrating from HockeyApp, otherwise ALL of my migrated Releases look very ugly.

**Describe alternatives you've considered**
Converting the original formatting into the formatting currently supported. I guess, it will be way more error prone than just to add support of formatting that HockeyApp supported.

**Additional context**
This is how nice it looks in the HockeyApp:
![RNFormatiing-HockeyApp-cnsrd](https://user-images.githubusercontent.com/15870100/64261114-ad0bee00-cf34-11e9-8028-9b0a37f93f50.JPG)

And this is how ugly the same is in the AppCenter at the moment:
![RNFormatiing-AppCenter-cnsrd](https://user-images.githubusercontent.com/15870100/64261139-b4cb9280-cf34-11e9-9be7-2e328f07c2fe.JPG)

**Comment by blparr** [comment]
Thanks for sharing that feedback! Our team will be taking a look at your request and act accordingly.

Thanks!

**Comment by RAM237** [comment]
Hi, I would say this is a bug, because it breaks the functionality which was out-of-the-box in HockeyApp, and now in AppCenter the Release notes of migrated stuff are absolutely unreadable.

This is a degradation of provided service and I want to ask - are you sure you are going to retire HockeyApp in 2 weeks? This means you leave your users with a broken experience, haven't even taking care of the reported issue for 2 months now. And there are more things still not working as expected in AppCenter which I got used to in HockeyApp. This is very upsetting.
