### ISSUE TITLE
Be able to revert an Ignore action on unsymbolicated issues

### ISSUE THREAD

**Issue by dominiquelee** [microsoft/appcenter#976]
**Describe the solution you'd like**
In the Issues tab, under Unsymbolicated, once an unsymbolicated version has been ignored, it's impossible to un-ignore it.

**Describe alternatives you've considered**
Swagger only features POST /v0.1/apps/{owner_name}/{app_name}/symbols/{symbol_id}/ignore, not some kind of opposite of it, so there's no alternative in there either.

**Comment by blparr** [comment]
Hello @dominiquelee , thanks for your request. @winnieli1208 will be taking a look at your request and prioritize accordingly.

Thanks!

**Comment by winnieli1208** [comment]
Thanks for the request! We're exploring ways to improve our symbolication experience and this is something we're considering. I don't have an ETA at the moment but will post here with any updates. Thanks!
