### ISSUE TITLE
Connecting to Azure SQL Database

### ISSUE THREAD

**Issue by himanpan** [microsoft/appcenter#980]
I see that currently appcenter allows connecting to Azure Cosmos Database. It would be good if functionality to connect to Azure SQL Database is also added.

I can use Azure Mobile Apps to achieve that, but from November 11th, 2019 Azure Mobile Apps is going to be made obsolete. So, this feature is pretty much needed in appcenter.

**Comment by elamalani** [comment]
@himanpan Thanks for reaching out. We would like to understand your scenarios and use cases for storing application data using Azure SQL Database. Would you be able to hop on a call with us and discuss it in detail? Please let me know if this is something you would be interested in.

Thanks,
Ela

**Comment by himanpan** [comment]
Hello Ela,

Thank you very much for your quick response.
Yes, I would surely like to discuss on a telephone call and explain my
expectations/problem that I am facing.

You can connect with me at +81-80-3176-0755.

Himanshu.

**Comment by elamalani** [comment]
Thanks Himanshu. Can you please reach out to me at emalani@microsoft.com and I’ll set up a Teams meeting invite based on your availability.

Look forward to speaking with you.

**Comment by gerfen** [comment]
I too am interested in being able to connect to Azure SQL databases.

**Comment by elamalani** [comment]
@gerfen Thanks for your interest. Can you please send me a mail at emalani at microsoft dot com and I'll set up some time accordingly?

**Comment by Vroomer** [comment]
Any ETA for this feature? As you abandoned Easy table from Azure, there is currently no easy way to connect app via API to Azure SQL. NoSQL is really not an option.

**Comment by HUBBER12** [comment]
I desperatly need an answer on this.  I too have multiple Enterprise LOB Apps dependent on MobileApps/Azure SQL.   I tried to re-imagine a design with Azrure Cosmos DB(NoSQL), and came away very impressed with what i "could" do with Azure Cosmos DB.  However, I have concluded..  while NoSQL is drop dead perfect for many Apps and excels in the scalabilty of those apps, it is the wrong choice for my LOB Enterprise Apps.   

I have seen that when as the complexity of the Data to be managed becomes more complex maintaining it correclty becomaes increasingly difficult.  A case can always be made that any type of problem **_can_** be solved in NoSQL.. but what i'm talking about is the complexity, and maintainability.  As the data types get very complex, so does the capability of maintaing it correclty in NoSQL.  Certian tasks that woudl be lightning quick turn into performance hogs..   there is just a threshold where NoSQL does not make sense.. and the threshold is Data Complexity not Data Scale.  A simple Banking App Like Frost Bank, or Wells Fargo.. would rock on NoSQL.  But my LOB apps if i'm forced to NoSQL, will be a nightmare.

Please hlep update us if Azure SQL will be part of the road map or not, as i need to be making some decisions soon on what to do for new LOB Apps, and what to do with my Legacy LOB Apps.
