### ISSUE TITLE
Add Custom Notes next to Release Notes

### ISSUE THREAD

**Issue by shpakovski** [microsoft/appcenter#983]
**Describe the solution you'd like**

We need a way to store custom (private) notes in addition to standard (public) release notes. Such markdown hidden from beta testers would be extremely useful for own snippets of information, especially in older (disabled) builds.

**Describe alternatives you've considered**

As far as I know, there’s no way to store custom notes with a build.

**Comment by nrajpurkar** [comment]
Thanks for the feature request @shpakovski! Are you interested in these being different sets of release notes that go out to different sets of testers? Or just an additional field that you see within the App Center Releases UI?

**Comment by shpakovski** [comment]
Thanks for getting back to me @nrajpurkar! I mean just an additional field in the Release UI, hidden from beta testers.
