### ISSUE TITLE
Export error and crash data to Application Insights

### ISSUE THREAD

**Issue by ignasbagdonas** [microsoft/appcenter#984]
**Describe the solution you'd like**
Export error and crash data to Application Insights like Analytics data. Now I can't find specific user problems and can't provide solutions for my customers.

**Describe alternatives you've considered**
Now we should use other logging solutions which are not perfect as AppCenter infrastructure.

**Additional context**

**Comment by blparr** [comment]
Hello @ignasbagdonas ! Thanks for your feature request. This feature is under our radar, but we don't have an ETA we can provide yet. In the meantime, note that you can export the Diagnostics data to Blob Storage.

Thanks,
Blanca

**Comment by winnieli1208** [comment]
@ignasbagdonas thanks for the feature request! This is something we'd love to support. Can you give feature #339 +1 so we can close this duplicate one? Thanks!
