### ISSUE TITLE
API activate push notifications payload

### ISSUE THREAD

**Issue by ricavir11** [microsoft/appcenter#985]
Hi,

What is the JSON payload structure needed to activate PUSH notifications over REST API on endpoint : /v0.1/apps/{owner_name}/{app_name}/push/notifications_config.

For iOS, we need to pass : 
- KeyID
- AppID
- attach P8 file
- select production or sandbox

Current swagger doc is not enougth to launch a request :
![image](https://user-images.githubusercontent.com/25507232/64331556-4c7fbe00-cfd3-11e9-9fc6-fc2b57eeb300.png)

**Comment by jwargo** [comment]
@ricavir11 App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

The API you're referring to here is to set a configuration value for the push service, that isn't the API to send a notification. Complete instructions for how to send notifications using the API are available here: https://docs.microsoft.com/en-us/appcenter/push/rest-api.

**Comment by jwargo** [comment]
@ricavir11 I'm sorry, I misunderstood your need here; so you're trying to configure push via the REST API? You're right, the documentation for that is missing from the swagger. It's sometimes challenging to expose all the data we need through the swagger. I'll make a bug to get this updated. In the mean time, support is the fastest way to get an answer on this one; I'll see i fI can pull it, but support can get it faster. 

Do you have some time to chat about how you're using Push?
