### ISSUE TITLE
get a QR (or link) to a specific build/release

### ISSUE THREAD

**Issue by tele-bird** [microsoft/appcenter#986]
**Describe the solution you'd like**
I see there's an easy way to get a QR code to download the latest app release (from the Overview tab). Is there a way to get a QR (or link) to a specific build/release?

**Describe alternatives you've considered**
Writing directions to navigate to a specific release is onerous.

**Additional context**
No, this should be enough.

**Comment by blparr** [comment]
Hi @tele-bird ! My colleague @botatoes will be looking into your feature request soon.

Thanks!
Blanca

**Comment by lumaxis** [comment]
This might be a duplicate of #140
