### ISSUE TITLE
Allow the release for ANY apps format or installer (e.g. QT)

### ISSUE THREAD

**Issue by zhichien** [microsoft/appcenter#987]
Hi,

Many apps were developed and not yet integrate with the diagnostics feature. But it is possible that the management is transferred first to the platform.
Please consider to add,
Under "Add new app", "OS: Windows", "Platform: **Others**".
Under "New release", "Upload a build", "Release: ANY".
By doing so, we can upload only the installer to the platform and start managing it, until we migrate the old codes.

Thank you.

**Comment by winnieli1208** [comment]
Hi @zhichien thanks for submitting an issue. Are you looking for a way to upload a release to App Center? How is your Windows app packaged? 

Thanks!

**Comment by zhichien** [comment]
Hi @winnieli1 yes you right. I have several software teams in the company and they do not want to share their codes outside the team. And they do not want to use App Center (yet). But we need a method to manage the release to end user. They build the installer (.exe) from WinForm/WPF projects and send me. I would like to use App Center to manage all the releases. Will I be able to upload and release through the App Center?

**Comment by marikavertzonis** [comment]
My team uses AppCenter primarily for distribution. We create apps of platform type:
 - Windows Desktop (visual c++ desktop apps)
 - UWP
 - macOS
 - Ubuntu
 - iOS
 - iOS Simulator
 - Android
And we also produce variants of some of these of x86 and x64, resulting in easily 10 'releases' for every app. Currently there is no option for the Windows Desktop app, Ubuntu and iOS Simulator for us.
