### ISSUE TITLE
Enable "Distribute" for Cordova apps

### ISSUE THREAD

**Issue by dun3** [microsoft/appcenter#990]
**Describe the solution you'd like**
Hi all! We are currently transition our Cordova apps from hockeyapp to appcenter - we are a bit worried that "Distribute" doesn't exist for Cordova - https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios - we need it for our apps. Native code changes are to be anticipated, which needs a full Distribute for our Cordova app. Please advise! Thank you very much.

**Describe alternatives you've considered**
It is suggested to use CodePush for Cordova applications for pushing updates. You may refer to: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cordova

But CodePush does not cover changes in plugins. So if we change native code we are out of luck. If there are bugs in plugins or cordova, we need to be able to update native code.

**Additional context**
Please extend the hockeyapp period until this is solved. We must be able to reliably change native code.

Thank you very much, we really like appcenter - but we are very worried about updating native code reliably in our Cordova apps.

**Comment by botatoes** [comment]
Hi there, 
We do support distribution for Cordova apps. You can try it out in appcenter.ms. You do not need the App Center SDK to use distribution. 

You can try it out by creating a new Cordova app in app center and going to the distribute service.

**Comment by dun3** [comment]
thank you for your answer. just to clarify though - your approach does not update the app though, right? so, yes an initial install will work, but no updates will be delivered? this is not good. we need updates delivered to installed instances.

**Comment by dun3** [comment]
Sorry for keeping this alive, but am I seeing in my assessment? Could we please have the full distribute functionality for Cordova? Can we implement that ourselves?
