### ISSUE TITLE
Dark theme breaks build log screen

### ISSUE THREAD

**Issue by jorisw** [microsoft/appcenter#991]
In both Safari and Chrome on Mac, the Build log screen of an app, renders a blank page when using the preview Dark theme in App Center. The browser console then shows 404s for URLs that look like `https://mobilecenter.azureedge.net/generated/5c8a5026f5bb42c6d611.js.map`.

Reproduce:

1 - Go to your Account Settings.
2 - Click the pencil edit icon next to `User Interface`.
3 - Pick the `Dark (Preview)` theme.
4 - Click All Apps in the top left.
5 - Go to one of your Apps
6 - Go to Build
7 - Choose a branch
8 - Click on a past or running build
9 - Find yourself blinded by the blank screen.

Going back to the Light theme fixes the problem.

**Comment by blparr** [comment]
Thanks so much for reporting this issue! We will create an item in our board and get to it as soon as we can!
