### ISSUE TITLE
Win32 (native C++ windows app) diagnostics support 

### ISSUE THREAD

**Issue by parapaul** [microsoft/appcenter#992]
At the moment our game uses hockeyapp for crash reporting. We have UWP and win32 (Steam) versions of the game. Both use hockeyapp REST API method "Post Custom Crashes" (https://support.hockeyapp.net/kb/api/api-crashes#post-custom-crashes) to upload crash info.

Crashes from both versions are not forwarded to appcenter. For UWP app everything is clear - we need to integrate appcenter SDK. What about win32 version of the game? Does appcenter have REST API method similar to hockeyapps "Post Custom Crashes"?

**Comment by winnieli1208** [comment]
@parapaul thanks for the feature request. App Center doesn't support Win32 at the moment but the custom crashes API is on the iteration plan this month. We expect to have this complete in the upcoming weeks. I'll post here with updates!

(For reference: https://github.com/microsoft/appcenter/issues/31)

**Comment by Kinkard** [comment]
I tried to upload win32 crash report as described in https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes#upload-an-attachment adding `"wrapperSdkName": "custom.ndk"` and setting exception type as "minidump" but no report has appeared in AppCenter.

If I remove `wrapperSdkName` and add mock frame in exception (without it crash not appeared in AppCenter) my minidump appears as attachment but no call stack from minidum is shown.

Also, is it possible to attach my custom properties to the crash? I tried to add fields in JSON as described in Swagger, but nothing changed.

Why don't you post any message to the 'diagnostics' section if some internal AppCenter happened during crash report parsing? Without it using API feels like being in a mine field.

**Comment by mayenjoy** [comment]
Is there any progress? Our whole company is waiting for this matter.

**Comment by winnie** [comment]
Hi @mayenjoy we don't have any short term plans to add support for Win32 apps. You can upload your crashes via our API here: https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes 

@Kinkard - apologies for the delay. Please start a support thread (blue chat bubble) and our team can help investigate. Thanks!

**Comment by triplef** [comment]
We would also very much like to see an App Center C++/Win32 SDK for Windows.

**Comment by triplef** [comment]
FYI #374 is basically the same request as far as I can see.

**Comment by sseyod** [comment]
Issue #436 as well! Pete

**Comment by triplef** [comment]
We’ve moved on to use [Sentry](https://sentry.io) for crash reporting on Windows. Highly recommended!

**Comment by sseyod** [comment]
@triplef same here - crazy, isn't it?! ;)
