### ISSUE TITLE
Code Coverage for Espresso tests

### ISSUE THREAD

**Issue by fvillelaa** [microsoft/appcenter#995]
It would be create to get code coverage from Espresso tests running on AppCenter.

This is an important metric to our project, for this reason, we are running the Espresso tests on Android emulator instead of running on AppCenter.

**Comment by blparr** [comment]
Hello @fvillelaa! Thanks for your feature request. We will be taking your request into consideration for future prioritization.

**Comment by Oddj0b** [comment]
hi @fvillelaa, 
Thank you for your request, it's a good idea and I can see it being useful to expose code coverage. I have some questions: 
1. Where do you track the metric?
2. How would you like to access the metric?

**Comment by fvillelaa** [comment]
Hi @Oddj0b , thanks for the answer.
We use SonarCloud to track this metric.
Maybe add this metric to the App Center interface along with the Test Runs... And generate a file that we can use for getting the coverage, for example, Jacoco generates .exec files...

**Comment by Oddj0b** [comment]
Thank you for clarifying the request.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.

**Comment by NilsLattek** [comment]
Please keep it open.
