### ISSUE TITLE
AppStore Connect two factor auth with trusted phone number is not possible

### ISSUE THREAD

**Issue by evorotnikov** [microsoft/appcenter#996]
As part of distribution of iOs build there is a possibility to deploy it directly to AppStore/TestFlight vis store connection.

Currently while creating new connection for AppStore Connect i can't use trusted phone number and i don't have ios device with linked Apple Id, so there are no way to create a store connection.

It will be great to be able use trusted phone number and got two factor auth via sms or phone call.

**Comment by blparr** [comment]
Hi @evorotnikov - thanks for your feedback! We'll take that into consideration for future prioritization.

**Comment by Oddj0b** [comment]
@evorotnikov Are you talking about support for 2-step verification instead of 2-factor authentication?

**Comment by evorotnikov** [comment]
@Oddj0b not really in my understanding, it's still 2-factor, but apple originally provide several options how to get a second factor:
- Default is via Apple codes (okta like) when you have a trusted device
- Alternative is by sending sms or calling trusted phone number (in case you don't have trusted ios device)

So second case is not covered in appcenter in my opinion. 

Attaching what i see while logging in into developer.apple.com:

<img width="673" alt="Screen Shot 2019-09-10 at 10 12 35 AM" src="https://user-images.githubusercontent.com/2075293/64626559-9db4f680-d3b3-11e9-855d-dee5ee9a66a8.png">
<img width="705" alt="Screen Shot 2019-09-10 at 10 12 29 AM" src="https://user-images.githubusercontent.com/2075293/64626560-9db4f680-d3b3-11e9-8217-1d046170569f.png">

**Comment by Oddj0b** [comment]
@evorotnikov thanks for clarifying, I wasn't aware that Apple offered a service like this. I'll talk with our engineers to understand how hard it would be to implement. We normally prioritize Github tickets by reaction and if this receives enough 👍 there's a bigger chance it will be implemented.

**Comment by evorotnikov** [comment]
@Oddj0b sure, thanks for replying to this one. I hope it will eventually be in.

**Comment by Ajaykn21** [comment]
@evorotnikov 
Apple by default sends 2FA codes to your trusted phone number if you have no devices linked.
Please check once https://appleid.apple.com/account/manage

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/40024974/67750806-43f7b100-fa73-11e9-88db-a01eec8845e8.png">

And you should be able to create a store connection in AppCenter with the codes you receive to your phone number as you mentioned that your account has no devices linked. 
We hope you are not blocked currently.

But yeah option where we explicitly wants to receive the code to the phone instead of devices is not available in AppCenter.

**Comment by bramski** [comment]
I can't use my SMS code to connect the apple account. This is very frustrating as my iPhone died. The code won't go to my macbook and I'm stuck unable to build our production branch.

**Comment by ajaykn** [comment]
Hi @bramski 
If I understand correctly, you are not receiving codes to your MacBook.
Can you check if your MacBook is listed under trusted devices [here](https://appleid.apple.com/account/manage)

**Comment by bramski** [comment]
It's tied to a dead iphone and since that's unavailable i'm getting them by SMS. My Macbook is a trusted device.

**Comment by bramski** [comment]
I searched through why my macbook isn't receiving them; apple prefers to send to your mobile device and if that's unavailable it will send to your SMS.  So I'm stuck unable to upload my builds until I can revive the iPhone.

**Comment by ajaykn** [comment]
Oh thats strange why your MacBook is not receiving the 2fa codes.
Not sure if this is related, please check, if you have DnD mode ON
<img width="389" alt="image" src="https://user-images.githubusercontent.com/40024974/79257396-2f836580-7ea7-11ea-9c9d-67f60827c452.png">

**Comment by rzane** [comment]
This is also happening to me.

* My MacBook is listed under "Devices" for my Apple ID.
* I'm receiving a text message, but if I enter the code, I get an error saying "Two-Factor Authentication via SMS is currently not supported".

**Comment by Oddj0b** [comment]
It sounds like you have a trusted phone number and not a trusted device: https://support.apple.com/en-us/HT204915

**Comment by patrickbdev** [comment]
Is there any movement on this? Noticed the error message states that I can't use text messages.
![image](https://user-images.githubusercontent.com/11362913/89137630-1ef11b00-d57c-11ea-8e2f-de61b047c30b.png)

**Comment by maciejtrybilo** [comment]
I'm in a bit of a bind with this one. We use managed Apple IDs in the company and Apple has disabled the "trusted devices" 2FA for managed Apple IDs and I can only receive the code via SMS. But, as the screenshot above shows, App Center doesn't support 2FA via SMS codes. 

I would be very grateful if you guys could add support for SMS codes as I'm unable to set up TestFlight distribution in App Center at all at the moment.

**Comment by astk** [comment]
I'm also stuck at this stage. Right now can't connect App Store because I don't have trusted device and there's no option to request to use trusted phone number added.

**Comment by tiagopiresxpand** [comment]
> I'm in a bit of a bind with this one. We use managed Apple IDs in the company and Apple has disabled the "trusted devices" 2FA for managed Apple IDs and I can only receive the code via SMS. But, as the screenshot above shows, App Center doesn't support 2FA via SMS codes.
> 
> I would be very grateful if you could add support for SMS codes as I'm unable to set up TestFlight distribution in App Center at all at the moment.

@maciejtrybilo Do you have managed Apple IDs with federation enabled?

**Comment by lourencogui** [comment]
I'm facing the same issue

**Comment by KAnderson** [comment]
I have the same issue, it was working and I am unable to reconnect. I have multiple macbook pro's listed as devices but neither receive the code, it only comes via SMS

**Comment by dimayurkovski** [comment]
Same issue. SMS code come to phone but error message is
"The verification code entered is invalid. Make sure your trusted device is logged to iCloud. Two-Factor Authentication via SMS is currently not supported. Enter the valid pop-up two-factor code from your trusted device."

**Comment by erdenemunkh** [comment]
Same issue. I am received SMS code. But verification failed. Stil error message.

**Comment by amie-wilt** [comment]
Same issue. 

I'm using a separate Apple ID for development purposes (dev@...) instead of my personal Apple ID. From what I gather, I'd need to sign out of my iPhone with my personal Apple ID and sign in with the developer Apple ID so that my device could be recognized. However, that's a little cumbersome to have to do. Seems like the SMS code should suffice.

**Comment by amie-wilt** [comment]
I found a workaround for this in case anyone is still stuck. 

Under "Add a device to the list" on this support page (https://support.apple.com/en-us/HT205064), there's a list of places you can sign into for your device to be recognized. One of those places is Game Center. I don't really know what that is but I don't use it so I figured I'd see if I could sign into it. I took the following steps on my iPhone, although I'm sure the same/similar goes for iPad, Mac:

1. Go to Game Center (I just searched it).
2. Sign out if you're already signed in.
3. Toggle Game Center back on, and sign in with the Apple ID you're trying to get passcodes for.
4. At this point you should see your device listed as a trusted device.
5. Then go to Settings and click on your name to view your Apple ID info, then Password & Security, then "Get Verification Code". 
6. I used this verification code for AppCenter and it worked. ¯\_(ツ)_/¯

Hope that helps.

**Comment by tiagopiresxpand** [comment]
> > I'm in a bit of a bind with this one. We use managed Apple IDs in the company and Apple has disabled the "trusted devices" 2FA for managed Apple IDs and I can only receive the code via SMS. But, as the screenshot above shows, App Center doesn't support 2FA via SMS codes.
> > I would be very grateful if you could add support for SMS codes as I'm unable to set up TestFlight distribution in App Center at all at the moment.
> 
> @maciejtrybilo Do you have managed Apple IDs with federation enabled?

@maciejtrybilo yes i do.

**Comment by maciejtrybilo** [comment]
@amie-wilt Thank you for that, but when I go to the Game Center I get a message: "This Apple ID cannot be used with Game Center. Your Managed Apple ID is not eligible to use Game Center."

**Comment by ianthetechie** [comment]
Does anyone at Microsoft actually maintain this product anymore? This is completely absurd. Fix your junk.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/2140440/106565597-6760b400-6572-11eb-9993-b5c1e5414c99.png">

**Comment by tkharuk** [comment]
`Two-Factor Authentication via SMS is currently not supported.`

When the "currently" is going to happen? :)
Are there any plans for this to be supported?

**Comment by j-bbr** [comment]
I want to give this another bump. Signing out and into developer accounts every 30 days is very annoying!

**Comment by ianthetechie** [comment]
Bump. This as BROKEN. We cannot use App Center without this. Your integration is broken. Full stop. Additionally, generating app-specific passwords seems to no longer work?

**Comment by vietstone-ng** [comment]
No one care :v

**Comment by tkharuk** [comment]
@j-bbr it is not only annoying.
But since I don't use my PERSONAL Apple account for development, but rather a CORPORATE issued account.
I'm simply unable to log in at all!

**Comment by AntAttakk** [comment]
Please fix this! I only have one device signed into my job Apple account. It works fine everywhere else using authentication via SMS to my personal phone, but not on AppCenter. This means we can no longer use the integration with AppStore at all.

**Comment by khalilyamoun** [comment]
No one cares :( leaving AppCenter soon.

**Comment by michael-knee** [comment]
I've hit the same issue with both trusted phone SMS codes and trusted device codes. 

<img width="473" alt="image" src="https://user-images.githubusercontent.com/60201297/120435587-3fb71680-c3c1-11eb-8f02-6cd67fbe6ccb.png">

**Comment by nkovacic** [comment]
> No one cares :( leaving AppCenter soon.

Are there any alternatives?

**Comment by patrickbdev** [comment]
> > No one cares :( leaving AppCenter soon.
> 
> 
> 
> Are there any alternatives?

Bitrise with fastlane, until Xcode cloud comes out of beta

**Comment by FranFara** [comment]
Hello everyone, I have the same problem here. Are there any reports of any progress on this issue?

**Comment by boxofnotgoodery** [comment]
Same issue.
Please address.
Please accept the SMS codes

**Comment by phonglee** [comment]
Here my fixed:
- Sign in with the apple account into the phone that registered phone number in the apple account
- In AppCenter, reconnect to the AppStore
- In phone, a message will be displayed to allow/not allow another device login -> Yes -> 6 digit code will be displayed
- Enter 6 digit code for AppCenter

**Comment by boxofnotgoodery** [comment]
> Here my fixed:
> 
>     * Sign in with the apple account into the phone that registered phone number in the apple account
> 
>     * In AppCenter, reconnect to the AppStore
> 
>     * In phone, a message will be displayed to allow/not allow another device login -> Yes -> 6 digit code will be displayed
> 
>     * Enter 6 digit code for AppCenter

The verification code entered is invalid. Make sure your trusted device is logged to iCloud. Two-Factor Authentication via **SMS is currently not supported**. Enter the valid pop-up two-factor code from your trusted device.

**Comment by phonglee** [comment]
> > Here my fixed:
> > ```
> > * Sign in with the apple account into the phone that registered phone number in the apple account
> > 
> > * In AppCenter, reconnect to the AppStore
> > 
> > * In phone, a message will be displayed to allow/not allow another device login -> Yes -> 6 digit code will be displayed
> > 
> > * Enter 6 digit code for AppCenter
> > ```
> 
> The verification code entered is invalid. Make sure your trusted device is logged to iCloud. Two-Factor Authentication via **SMS is currently not supported**. Enter the valid pop-up two-factor code from your trusted device.

You must use 6 digit code from the Verification Code dialog not the code from Messenger App otherwise you will get above error

**Comment by boxofnotgoodery** [comment]
> > > Here my fixed:
> > > ```
> > > * Sign in with the apple account into the phone that registered phone number in the apple account
> > > 
> > > * In AppCenter, reconnect to the AppStore
> > > 
> > > * In phone, a message will be displayed to allow/not allow another device login -> Yes -> 6 digit code will be displayed
> > > 
> > > * Enter 6 digit code for AppCenter
> > > ```
> > 
> > 
> > The verification code entered is invalid. Make sure your trusted device is logged to iCloud. Two-Factor Authentication via **SMS is currently not supported**. Enter the valid pop-up two-factor code from your trusted device.
> 
> You must use 6 digit code from the Verification Code dialog not the code from Messenger App otherwise you will get above error

That's what the issue is. <-----

Some people do not have, or have access to a device that shows the dialog.

**Comment by ptrkstr** [comment]
Bump

**Comment by syntax-e** [comment]
Hi, In my org there are a few engineers who have their phone numbers registered with our single Apple ID's 2FA. There is only one Apple device that is signed in with that Apple ID and not everyone has physical access to that device to receive the 2FA dialog. Those engineers are unable to reestablish AppCenter connections to the Apple App Store when "Your Apple App Store Credentials are no longer valid. Please re-authenticate." occurs. It would be ideal if App Center supported an option allow the 2FA code to still be sent via SMS even if there is an Apple device logged in with that Apple ID somewhere. 

This 2FA setup is quite challenging to manage in a group environment.

**Comment by ptrkstr** [comment]
Bumping. Developers need this.

**Comment by gcaven-nbx** [comment]
This is a show-stopping problem for anybody who deals with multiple Apple IDs for work, how has this been allowed for fester for so long? Has anybody from the Microsoft even acknowledged this issue?

**Comment by amie-wilt** [comment]
Maybe we should open a new issue? Seems like bad practice but maybe it would get someone's attention. At least if someone closed it, we'd know it was seen and blatantly ignored.

**Comment by ptrkstr** [comment]
Looks like it was assigned to @botatoes a while back and checking on their profile it appears they didn't have access to their account until recently.
@botatoes any chance you had any insight on the status of this ticket?

**Comment by dorgonman** [comment]
same issue here

**Comment by nwenner** [comment]
Wanted to add my name to this list as well. I'm still experiencing this issue. The apple developer ID I use is on behalf of a client to build/provision/distribute. I don't have access, nor intend to sign in with this apple ID on a physical device. Not being able to use SMS for 2FA verification is a breaking issue.

Any updates on when this will be fixed? Any updates would be much appreciated!

**Comment by SHEePYTaGGeRNeP** [comment]
same issue too

**Comment by tobiasalthoff** [comment]
I have the same issue.

**Comment by gcaven-nbx** [comment]
Just had to deal with this issue blocking app distribution again. Any updates would be very appreciated!

**Comment by SirCameron** [comment]
Same issue :(

**Comment by amie-wilt** [comment]
I'm starting to feel like we're SOL on this. I've been having some issues with CodePush and came across this https://github.com/microsoft/code-push/issues/751 which led me to this https://github.com/microsoft/appcenter#planning. I realize this is right there in the README but I overlooked it.

**Comment by SirCameron** [comment]
@amie-wilt .... that's sad.. but this is a compatibility issue - if that's what they're focusing on.

**Comment by adammcarth** [comment]
Story suggestion: 

As a normal human being, I don't want to sign out of the personal Apple ID on my iPhone in order to sign in with a company issued Apple ID (thereinafter disabling iMessage and risking my personal photos and messages being uploaded), just to receive one 2FA code to distribute an app update at 5:00pm on a Friday night.

**Comment by amie-wilt** [comment]
@adammcarth not ideal but did you try this? https://github.com/microsoft/appcenter/issues/996#issuecomment-762518164

**Comment by tomassvatek** [comment]
> Story suggestion:
> 
> As a normal human being, I don't want to sign out of the personal Apple ID on my iPhone in order to sign in with a company issued Apple ID (thereinafter disabling iMessage and risking my personal photos and messages being uploaded), just to receive one 2FA code to distribute an app update at 5:00pm on a Friday night.

I agree. This is must-have feature!

**Comment by caphun** [comment]
Come on devs, this issue has been opened for 2+ years! It is clear by now that this is a must have feature, as it's causing the community so much pain. I am close to moving away from App Center due to this issue. The fact that we have to deal with it on an ongoing basis as the App Store connection requires a re-connect every few months just adds insult to injury! I hope you can hear my frustration though text as I nearly missed a deployment deadline today due to this very issue. Please bump this one to the highest priority level. please!

**Comment by rodrigo-at-hypergiant** [comment]
I am also impacted by this must-have feature.  Right now if you don't have an iOS phone linked to the Apple ID you use to manage App Center, you cannot add iOS testers.  There's no justification for this.

**Comment by taylormoyle** [comment]
I am experiencing a blocker here as well. 

When I enter the 6-digit code sent to my iPhone 12 Pro Max listed as a Trusted Phone Number, I get the same error as stated above. I've tried the aforementioned fixes and various other things found on the web, such as going into appleId settings and generating a 2-step verification code and trying to use that for the 6-digit prompt. 

The issue may be with my appleId account not showing any `Trusted Devices`, only `Trusted Phone Numbers`.

Side note: When I try to `Reauthenticate` on certain AppCenter releases/stores tab, I get prompted with an email of the employee who created the account, who is no longer here.

Have been wrestling with this for the better part of a day, any leads would be appreciated.

**Comment by nissaba** [comment]
This is important. people will just drop app center for this with out opening a ticket or supporting this one. 90% of people just will quit without saying a word. You need to se the number of people her multiplied to 100 i not 1000.

**Comment by EenPOOL** [comment]
One of the top 10 commented (open) issues... and there is still no response from devs.
Each time again and again I bump into the same issue... I could create an app-specific password and everything... but it expires each time after a while... 

The most funny thing is that I receive an sms with the verification code.. but I cannot use it... 

Please give us at least some timeline when it will be fixed :)

**Comment by froston** [comment]
Same issue

**Comment by LeoJHarris** [comment]
I was having issues with the SMS as well and the way I resolve this was on my mac going to 

System Preferences => Apple ID

You will see the below screen then click "Get a verification Code" then copy the code into AppCenter to complete the authentication. Not sure if this resolves the original issues here but a method I use to authenticate from a trusted device.

<img width="600" alt="PastedGraphic-1 7753" src="https://user-images.githubusercontent.com/5468757/178162839-20f8258f-7b96-40e0-9a41-8b36c92286a2.png">

**Comment by ohernang** [comment]
Same problem here, nothing new to add. 

![image](https://user-images.githubusercontent.com/89062/187169004-d615c88e-7c06-42db-ad71-584f1347da7a.png)

**Comment by 00elan** [comment]
![image](https://user-images.githubusercontent.com/52146145/188530293-5d2f754a-b0d4-4d75-b13e-b3271f0a991b.png)


Same issue,,,

**Comment by sonhd92** [comment]
bump it up. Still got this issue

**Comment by EmilAlipiev** [comment]
@LeoJHarris   Others having problem here "NOT HAVING ANY DEVICE" associated because AppleId i use and others use is ONLY for Development purpose. We have main apple ID we use for our personal devices and we dont want to add any corporate Apple ID which is only for development. When MS developers sees such "workaround", they don't act. 
Lets understand, THERE IS NO SOLUTION or WORKAROUND for this UNLESS APPCENTER DEVELOPERS ACTS!

IMHO, Microsoft doesn't care with appcenter and they will retire this product soon or later as many others they did. Only solution here is using Azure Devos directly,

**Comment by darpsoft** [comment]
I did the following

1 I created an account exclusively for iOS deploy 
2 I associated a phone number to the account to receive the 2FA code
3 With that account I started on a physical device (In my case) a Macbook
4 The account created was the one I used for AppCenter
5 When I went through the steps again, I got the authorization code to the Macbook

With this, I was able to connect to Appcenter with Apple.

**Comment by afranz33** [comment]
I went through support within the App Center web site and I ended up removing my attached account then they sent me a URL(specific for me) and it took me to add an account from the distribute page not the account settings page. I entered my creds, got the 2FA code, entered and now back in business.

**Comment by ckapatch** [comment]
my issue is similar however I do have a physical device and the code sent to my device doesn't work, it'll give me this error each and every time:

![image](https://user-images.githubusercontent.com/855721/215604263-2ea52f8d-0a7a-4992-bb3f-b036869818d6.png)

**Comment by MalmoIt** [comment]
@amie-wilt solution worked perfectly for me.

**Comment by henninghall** [comment]
Still an issue for us.

**Comment by ComplexVariable** [comment]
Still an issue. Why is this closed ?
