### ISSUE TITLE
Timestamp Timezone changed?

### ISSUE THREAD

**Issue by myokeeh** [microsoft/appcenter#997]
Was there a recent change regarding **Timestamp** and/or **TimeZoneOffset** values logged/exported to **logs.v1.data**?

I've been using PowerBI to analyze the data and just now noticed that the time seems off.

**Comment by blparr** [comment]
Hello @myokeeh, let me check back with the team to see if there was any change that might have caused that.

We'll get back to you as soon as we have updates.

Thank you!

**Comment by YiMysty** [comment]
Hi @myokeeh we do not have changes to our export service recently. When did you notice this change? thanks!

**Comment by myokeeh** [comment]
I'm starting to think it might be a bug in PowerBI Desktop. I'm investigating that now. I'll go ahead and close this out. Thanks!
