### ISSUE TITLE
HockeyApp SDK missing in App Center

### ISSUE THREAD

**Issue by markdiener** [microsoft/appcenter#998]
How to use App Center API to create a new app?

Where is the equivalent API in App Center for the Hockeyapp?

curl \
  -F "status=2" \
  -F "notify=1" \
  -F "notes=Some new features and fixed bugs." \
  -F "notes_type=0" \
  -F "ipa=@hockeyapp.ipa" \
  -F "dsym=@hockeyapp.dSYM.zip" \
  -H "X-HockeyAppToken: 4567abcd8901ef234567abcd8901ef23" \
  https://rink.hockeyapp.net/api/2/apps/upload

The api in App Center allows for upload:

/v0.1/apps/{owner_name}/{app_name}/release_uploads

But it does not allow for creating a new app.

https://openapi.appcenter.ms/#/

Any ideas?

**Comment by derpixeldan** [comment]
@markdiener the title of the ticket doesn't align with the content. For apps that got moved you can still use the [HockeyApp API](https://docs.microsoft.com/en-us/appcenter/transition/api). The App Center API is documented [here](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#uploading-using-the-apis). Let me know if that was what you're looking for.

**Comment by markdiener** [comment]
Can I use the HockeyAPP API with app center?

Where do I get a Hockey APP token?

If not, how do I create a new app with the new App Center Api?
(Send me the URL- We want the Hockeyapp equivalent)

Thanks,

md

**Comment by derpixeldan** [comment]
@markdiener the current App Center upload procedure is what I mentioned [above](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#uploading-using-the-apis). We're investigating to use a similar HockeyApp upload API design on App Center.

**Comment by markdiener** [comment]
That is totally not helpful.

So how do you create a NEW app with the AppCenter Upload.  

Basically, how do you create a new {app_name} ?

Yes, I am trying to use: https://docs.microsoft.com/en-us/appcenter/distribution/uploading#uploading-using-the-apis

Cheers,

Mark

**Comment by derpixeldan** [comment]
@markdiener the whole App Center API is documented [here](https://openapi.appcenter.ms) and you can create an app via [API as well](https://openapi.appcenter.ms/#/account/apps_createForOrg). You cannot use the HockeyApp API with App Center, only what's documented [here](https://docs.microsoft.com/en-us/appcenter/transition/api).

**Comment by markdiener** [comment]
Ok, that is what I was looking for.  Thank you.

https://openapi.appcenter.ms/#/account/apps_createForOrg
