### ISSUE TITLE
Add Unity-Windows to your list of supported platforms

### ISSUE THREAD

**Issue by rgonzalezVW** [microsoft/appcenter#999]
Since you recently added WinForms and WPF, and you already have Unity as platform, it would be great to also have Unity3D available for Windows builds.

**Comment by PavanJakhu** [comment]
Does does mean Win32 builds or UWP builds?

**Comment by elamalani** [comment]
@rgonzalezVW Thanks for adding this feature request. We will review it with the team and consider it for future prioritization.

**Comment by rgonzalezVW** [comment]
I mean Win32 builds (both 32 and 64 bits).

**Comment by ricduong** [comment]
Thanks for the feedback @rgonzalezVW We will be looking into this request.

**Comment by PavanJakhu** [comment]
It looks like this got implemented since you can select Windows as your OS and Unity as your platform when you create a new app but in-app updates, push and analytics (I think) are not supported so nothing in the Unity App Center SDK work.

**Comment by sandersdevelopment** [comment]
We are very interested in Unity3D support aswell! Our Use Case is that we want to use it in an Unity VR Windows-Desktop-App / Oculus-Quest-App to synchronize datasets among devices

**Comment by asandersSAP** [comment]
We are very interested in Unity3D support aswell! Our Use Case is that we want to use it in an Unity VR Windows-Desktop-App / Oculus-Quest-App to synchronize datasets among devices

**Comment by davidezordan** [comment]
I'm also interested in Unity3D support for Windows desktop builds
